### ISSUE TITLE
Deploy and release: Replace Renovate with GitHub Actions

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10011]
Replace Renovate with GitHub Actions for updating deploy-sourcegraph and deploy-sourcegraph-docker, and the dogfooding instances. Benefits:
* Synchronous
* Debuggable / inspectable

**Comment by slimsag** [comment]
I will tackle this in two phases:

- 3.16: Replace Renovate with a script that can be ran to update the images.
- 3.17: Run that script as a GitHub action.

**Comment by bobheadxi** [comment]
could we have GitHub actions fire off Sourcegraph campaigns to do this? 🤯

**Comment by slimsag** [comment]
Complete rationale:

- Renovate is good for handling _dependency updates_.
- Renovate is not good for handling Docker image updates _as part of our release process_.

This is mostly due to (1) its asynchronous nature and (2) the fact that it cannot operate well retroactively on older branch versions (e.g. 'update image tags from 3.15.1 -> 3.15.2, while the latest version is 3.16.2') -- it can be configured to do this, but it's not straightforward to put this into place on each release branch.

There are some additional concerns with using Renovate for Docker image tag updating:

1. (major) Reliability: It has on multiple occasions, for me and others, failed to produce updates for several hours. This has delayed releases 2-3 times in total. In the context of updating dependencies, that's fine - but in the context of our release process that is _not_ okay.
2. (major) Atomicity: Renovate has produced several 'partial updates', where a few images have their versions updated (e.g. 3.15.0 -> 3.16.0) but not others. This has in the past produced [broken Sourcegraph releases](https://github.com/sourcegraph/sourcegraph/issues/9725). We need to guarantee all images in the git repository are updated, without worry that a Renovate job for select images may have not started or completed yet, so that we can appropriately tag the release.
3. (major) Automation: We want our release process to be automated eventually, this is much harder to do while relying on an asynchronous tool like Renovate (vs. being able to simply shell out to a tool that does the same thing).
4. (minor) Security: Dependency updates can (and need to) have someone verify the integrity of their contents from a security POV, to ensure e.g. nobody has introduced malicious code. With Docker images, it is akin to inspecting an arbitrary binary -- not feasible. Trusting Renovate to perform these updates means trusting a third-party service, and all of its dependencies. Reducing the chain of things we must trust to just "a dumb tool we wrote and can verify" is a positive thing in this regard.

Almost none of these concerns apply to dependency updates, because they can be asynchronous, ad-hoc, and non-atomically. But for use in our release process, it makes more sense to use a simple CLI that performs the updates in an atomic and reliable way.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Update: more recently I created https://github.com/slimsag/update-docker-tags outside work which we can use for this.

Dax has been working on integrating this in a GitHub action for https://github.com/sourcegraph/sourcegraph/issues/9983 and we should be able to reuse that work elsewhere.

**Comment by keegancsmith** [comment]
@daxmc99 how is this going? renovate was annoying me today since we haven't had a deployment all day due to it deciding just not to update. I am feeling motivated to make this happen, so just don't want to step on your toes / duplicate effort.

**Comment by slimsag** [comment]
He sent me two PRs I need to review here: https://github.com/slimsag/update-docker-tags/pulls

Then we just need to actually use the GitHub action here and fix any remaining issues it may have

Apologies for the delay in reviewing these, will look ASAP

**Comment by daxmc99** [comment]
Those two PRs should get the `update-docker-tags` into a place where it can update most docker tags. 
The Github action portion still needs quite a bit of work. 
https://github.com/daxmc99/update-docker-tags/blob/github-action/.github/workflows/update-docker-tags.yml 
I think a clear goal is to be able to run it locally for which I tried to use Act https://github.com/nektos/act
I'm not sure if Act is the issue or the action I wrote just needs to be written better

**Comment by pecigonzalo** [comment]
FYI, renovate also has a github action https://github.com/renovatebot/github-action

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
I am going to close this for now, as it seems we are working towards improving this in some other ways.
