### ISSUE TITLE
Slow search queries should prompt user to investigate issue in Jaeger

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10048]
When regular users encounter a slow search, they should be prompted to enable tracing for the request and look up the corresponding trace in Jaeger.

Also, make Jaeger available through the admin proxy (like Grafana is)

**Comment by daxmc99** [comment]
Could be part of https://github.com/sourcegraph/sourcegraph/issues/10491

**Comment by slimsag** [comment]
> When regular users encounter a slow search, they should be prompted to enable tracing for the request and look up the corresponding trace in Jaeger.

@beyang what exactly is your thinking here? Since plain users cannot enable tracing in the site config, I am confused why we would show this to plain users.

Maybe you mean just for admins? Or just if jaeger is enabled on the instance, and then for plain users?

I can imagine this will require some extensive changes in the search frontend/TS code to display this message. It may make sense to punt on doing this until more specifics are figured out. We should loop the search team in, as well.

**Comment by slimsag** [comment]
@rvantonder @sourcegraph/search is there a good way (or way in the future) we could add a note like "we saw your search was slow... try the following steps: ..."?

**Comment by rvantonder** [comment]
Mostly straightforward to surface an alert if ElapsedMilliseconds exceeds some threshold based on the search. The question is what sort of alert/notification you think helps here. The default Info alert with query suggestions is a bit big/"loud" IMO, but I think this a question of revisiting UI design of those alerts. Apart from that, using that alert mechanism today would also be dependent on #9745 first. 

But for example, a better alternative way may be to surface this next to the calculator icon (similar to where I recently added the fork/archive excludes), which is not so big/loud. This implementation would be almost entirely web-app side, and it feels like we could probably add this real soon? @attfarhan

**Comment by stefanhengl** [comment]
Closing this, because we have a button to open the trace of the last search if the user add the query parameter trace=1. We don't expect the average user to investigate traces. Jaeger is exposed through the admin interface, too.
