### ISSUE TITLE
Can't copy text from search results page

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10092]
A user at https://app.hubspot.com/contacts/2762526/company/464956351/ complained that It is impossible to select text in the search results UI so he has to navigate to the file first, he said this is a very common workflow for anyone developing Java code and right now it is very annoying to have to navigate to the file first.

Full context: https://sourcegraph.slack.com/archives/CMB6K7SMN/p1587499846168800

**Comment by rvantonder** [comment]
Just assigning to @lguychard for visibility, feel free to change.

**Comment by lguychard** [comment]
@attfarhan seems low effort / high ROI, do you feel like you could tackle this in 3.16?

**Comment by attfarhan** [comment]
We had this filed before, but we punted on it since there wasn't an agreement on the solution: https://github.com/sourcegraph/sourcegraph/issues/875.

Does anyone have a strong opinion on how this should work now? I may have time to take this on, but I don't think the UX is as obvious as it may seem given our past discussions.

cc @imtommyroberts maybe you have a good idea for this?

**Comment by lguychard** [comment]
We should discuss in the original issue (https://github.com/sourcegraph/sourcegraph/issues/875).
