### ISSUE TITLE
"Go to definition" and "Find references" no longer work for Go source identifiers

### ISSUE THREAD

**Issue by seh** [sourcegraph/sourcegraph#10163]
# Context
- **Sourcegraph version:** _sourcegraph.com_
- **Platform information:**
  - macOS 10.15.4
  - Firefox 75.0

# Steps to reproduce:
1. View a Go language source file on _sourcegraph.com_.
1. Hover the mouse over an identifier until the related panel pops up over the symbol
1. Choose either "Go to definition" or "Find references"
1. Observe resulting browser state

# Expected behavior:
- For "Go to definition," the browser jumps to focus on the symbol's definition.  
  If already at the definition to start with, "Go to definition" should not be an option.
- For "Find references," the panel at the bottom of the page opens with references to the symbol in question sorted by some criteria.

# Actual behavior:
- For "Go to definition," the browser navigates to a new page, still focusing on the target identifier, but now with the panel at the bottom of the page open with lots of string matches for the highlighted identifier, but these are otherwise unrelated to the target identifier.
- For "Find references," similarly, the panel at the bottom of the page opens with lots of string matches, but they are otherwise unrelated to the target identifier.

# Example
1. Start with file _staging/src/k8s.io/client-go/tools/cache/listwatch.go_ in the _kubernetes/kubernetes_ repository, focusing on [the `Lister.List` method](https://sourcegraph.com/github.com/kubernetes/kubernetes@0acf2f0983d1491caf60367f12c1bd76651209cc/-/blob/staging/src/k8s.io/client-go/tools/cache/listwatch.go#L33).
1. Click "Go to definition," and observe a bunch of functions named `List`, but with different parameter types.
2. Click "Find references," and observer lots of lines with the word "List" (including comments) or method calls with different arity, proving that they're not references to _this_ method.

**Comment by unknwon** [comment]
I think this is because we removed LSP and fell back to search-based ctags because no LSIF was uploaded for k8s/k8s repository. cc @sourcegraph/code-intel

**Comment by seh** [comment]
Looking through the repositories I've visited lately, I see the same problem in [the _open-telemetry/opentelemetry-go_ repository](https://sourcegraph.com/github.com/open-telemetry/opentelemetry-go@master).

**Comment by gbrik** [comment]
This is because we removed LSP-based code intelligence. As a short term solution, you can nominate repos for us to index offline here: #9746. Offline indexing will make precise code intelligence more consistent, faster, and more scalable. Disabling the LSPs is letting us get there sooner.

**Comment by seh** [comment]
Is there some indication visible on the Web page that LSP or code intelligence is not in use? The imprecise lookups make Sourcegraph look bad, pushing us back to just browsing on GitHub.

**Comment by efritz** [comment]
Yes, there should be info indicators on the hover tooltips and in the references panel. Are you browsing on DotCom or on a private instance? In the latter circumstance you can try adding this to global or your user settings:

```
"experimentalFeatures": { "showBadgeAttachments": true } }
```

This flag should be on by default, but there was an error in frontend code that was recently fixed (so instances prior to 3.15 will not show these by default).

**Comment by seh** [comment]
I'm looking at _sourcegraph.com_. I now see there's a circled "i" symbol in some of the popup panels that indicate that I'm suffering "search-based results."

I'm partway through reading [RFC 139](https://docs.google.com/document/d/1dl5u03dD63-RZB7S1p2IqFTiVcdx6On0aeIOXgsTehA/), and am disappointed. From the "Not in Scope" section:
> Completing Phase 1 above will have the effect of removing precise code intelligence for Go and TypeScript repositories on sourcegraph.com, that do not have LSIF indexing set up. This is a regression, but the evidence so far suggests this will not affect that many users.

I can't leave a comment there, for lack of permission, but this regression is affecting me, and presumably everyone else looking a Go source code through _sourcegraph.com_. Does it impact paying customers too?

Even with [the adoption documentation for LSIF here](https://docs.sourcegraph.com/user/code_intelligence/adding_lsif_to_workflows#lsif-on-gitgub), I can't see what would motivate repository owners to set this up themselves. If you're the author of the code, you probably interact with it mostly in your own editor with an LSP available locally. It's the people who _don't_ work on the given code base all day who benefit most from _sourcegraph.com_.

**Comment by seh** [comment]
@felixfbecker makes excellent points in the aforementioned RFC here, anticipating my own experience:
>  If LSP truly already is impeding widespread adoption of LSIF, I would immediately agree to execute this proposal immediately (again, I totally want LSIF to become wide-spread). But I’m not convinced by the data presented in this RFC that that is the case. I don’t expect LSIF usage to suddenly increase at all just because we removed language servers. The evidence presented above is that it is confusing to distinguish LSIF and LSP. I agree with this, but it is not surprising given there are zero UI indicators (unlike for basic code intel). If we actually did make the indicators also work for LSP vs LSIF, and e.g. add the UI nudges mentioned above (which you seem to support), and LSIF spread then increases, then I think that will have been because of that UI, whether language servers are still there as a fallback or not. If anything I think it could hurt adoption because users may stop using sourcegraph.com in general because it doesn’t have value for them anymore on non-LSIF-enabled repos, and then they don’t feel like gambling every time whether a repo will have LSIF or not when they want to go to Sourcegraph, and will just stop using Sourcegraph in general.

The last sentence starting with "If anything" captures my current degraded sentiment toward using _sourcegraph.com_. @creachadair, as you're the RFC editor, I figured you might be interested in this discussion.

**Comment by gbrik** [comment]
We fully agree with everything you've said, and we're actively working on addressing your concerns. I just merged changes that make LSIF setup trivial for the majority of Go projects, and we're planning multiple different features to make code intelligence via LSIF as easy as is technically possible. We want precise code intelligence back just as badly as you do, and any changes we make are to serve the goal of providing the feature to as many people as possible.

Language servers were not designed to be used the way we were using them, and it would have been technically impossible to continue using them as usage on Sourcegraph.com continues to grow. This is due to starting a process that used several GB of RAM each time a Go repository was visited. Additionally, language servers did not work for languages with more complex build environments, so to scale support beyond Go and TypeScript with language servers was not feasible.

I appreciate you taking the time to open this issue, and I hope this provides a bit more context about why we made this decision. We're monitoring how this affects users, and this is the first report we've had since disabling the language servers last week. We'll definitely revisit this issue if necessary!

**Comment by seh** [comment]
Thank you, @gbrik. I appreciate the difficult bind you find yourselves in, especially after reading that RFC.

I would have posted this report sooner, but for several days I kept thinking that this was a temporary glitch that I'd find resolved soon enough. From my experience with Sourcegraph, this code intelligence is its _raison d'être_. Had I found _sourcegraph.com_ just serving an advisory page that said, "Code intelligence is disabled for now. Please try browsing GitHub instead," I would have gone away neither miffed nor confused. I'd just check back periodically.

I think it would help both Sourcegraph and your users if you told people more prominently that you're in a transition period, that things are going to get way better as a result, and that there are steps users can take to speed along the transition. Showing you're proud of the changes but aware of the temporary inconvenience will earn more goodwill from your eager users.

I look forward to seeing LSIF deployed more broadly.

**Comment by gbrik** [comment]
We considered writing a blog post about this but after validating that it affected an extremely small number of private instances (only one customer was using them due to the issues mentioned above), we decided it might cause more confusion than it resolved. We'll definitely take that feedback into account in our future communication because I agree that we may have been able to find a happier compromise.

Side note, I just noticed you mentioned that you were going back to browsing on GitHub because of this issue, and I wanted to make sure you're aware of our [browser extension](https://docs.sourcegraph.com/integration/browser_extension). You don't have to choose! We want to make these features available everywhere you browse code (my absolute favourite thing about the entire product is hovers in PRs).

**Comment by seh** [comment]
Yes, I do use that extension with GitHub—modulo some recent trouble per #7689—but it's the "Find references" side of the popups that lead back to the real action on _sourcegraph.com_. I mostly meant that I'd take a break from using that reference chasing half of the popups.
