### ISSUE TITLE
Creation of the first user through the API ?

### ISSUE THREAD

**Issue by IizunaK** [sourcegraph/sourcegraph#1036]
* Sourcegraph version: 2.13.3
* Platform information: Ubuntu 18.10

My ultimate goal is to be able to automate completely the install and update of Sourcegraph without having to go to the UI to configure, so through the API.

But I realized that I stiil need to create the 1st admin user and create its token through the UI, for now

Something like :+1: 
- Create the 1st admin user through API
- Create its admin token through API
- Send the `updateSiteConfiguration` site full json though API
- Enable all the found git repositories through API
- Continuously enable new git repos every time a new bare repo is added to the host server through API

Is that possible ? Is that wanted ?
Or are you afraid of it for security reasons ?

**Comment by sqs** [comment]
Creating the 1st user (and initializing the site) through the API is not currently supported because the entire GraphQL API is subject to user authentication. Prior to the site being initialized, there is no meaningful way to authenticate users, so this means the whole GraphQL API is inaccessible.

This is just a technical limitation based on the most common user flow, though. There's no fundamental or product reason that makes it impossible to support what you want. (You would need to ensure that in making the GraphQL API accessible prior to site initialization, you don't introduce other security holes, of course.)

My recommendation: look at the HTTP POST requests that the site initialization screen makes, and just make those HTTP requests directly. That is also an API (it is undocumented/internal and is not GraphQL, but it's still usable as an API). You may need to include an `X-Requested-With` HTTP header to bypass the CSRF token check.
