### ISSUE TITLE
Make conf.DeployType() differentiate between k8s and docker compose

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10399]
This is critical for a lot of reasons — including the top two on my mind right now:

1) docker compose admins won't see the appropriate upgrade warnings, as their instances are still reporting "kubernetes"
2) we don't know who to notify when deployment changes/migrations are required

**Comment by slimsag** [comment]
> won't see the appropriate upgrade warnings

What does this mean?

Agreed otherwise, thank you for filing

**Comment by dadlerj** [comment]
We report the version to upgrade to based on the deploy type: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5204b66f7505d7d40fa2d1df125fdb712f060d9b/-/blob/cmd/frontend/internal/app/pkg/updatecheck/handler.go#L48:6

It's rare for there to be a long gap between Kubernetes and Docker Compose, but it could confuse users if they click the link and land on a page that still references their old version.

**Comment by slimsag** [comment]
I believe this should involve just the following:

- Set `DEPLOY_TYPE=docker-compose` in both `frontend` deployments in https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml
- Set `DEPLOY_TYPE=pure-docker` in both https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/deploy-frontend.sh and https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/deploy-frontend-internal.sh
- Confirm in the main sourcegraph codebase that those two values are accepted and don't have some weird side effect (I think this should already be the case due to https://github.com/sourcegraph/sourcegraph/pull/8658 but am not 100% positive)
- Run both the pure-docker (`deploy.sh`) and docker-compose (`docker-compose up -d`) deployments and briefly check they work OK.
- Send PRs.
