### ISSUE TITLE
Surface availability of the browser extension in a more persistent way

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#10409]
For instances using GitHub, native integrations are not available so the in-app hints will not be useful (https://github.com/sourcegraph/sourcegraph/issues/10225). 

For organizations using GitHub Enterprise or GitHub.com, we should surface to users that there is a browser extension available. The initial pop up is shown when first visiting the site, and many users dismiss it before they understand the power of Sourcegraph and the value the browser extension provides.

Idea for a quick improvement: make the notification come back every X days/weeks for users that do not have the browser extension installed. Provide a "dismiss forever" option.

I think there is opportunity to do this really nicely, while educating the user about the different features of Sourcegraph.

Requested by a user at https://app.hubspot.com/contacts/2762526/company/557691596

**Comment by lguychard** [comment]
@marekweb tentatively assigning this to you for 3.17

**Comment by lguychard** [comment]
@rrhyne @christinaforney this is something we'd like to get done in 3.17. I suggest the following:
- Restrict these improvements to Sourcegraph.com: before surfacing the browser extension more aggressively on private instances, #10819 and #10814 would be needed. No special action is needed here: the current browser extension popup is [only shown on sourcegraph.com](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e5bd075bfbca90eab2c7f8da81e1b995f00cb2b7/-/blob/web/src/marketing/BrowserExtensionToast.tsx#L40).
- Show notification every 7 (?) days until the user installs the browser extension, unless they "dismiss forever".
- Ideally package this with #10589 so that the browser extension install experience is one-click (instead of linking to our docs, and having to figure out how to install from the docs). My instinct is that our current flow causes a lot of churn.
- Make sure our current popup is only shown on github.com repositories (currently it shows on all sourcegraph.com repositories, but the wording explicitly mentions GitHub). Should we show a different popup for gitlab.com repositories, linking to https://docs.gitlab.com/ee/integration/sourcegraph.html#sourcegraph-for-gitlabcom?

![image](https://user-images.githubusercontent.com/1741180/83000439-a7968c80-a00a-11ea-82fc-2946f18bb9bb.png)

@rrhyne would you want to make other UX/design changes here?

**Comment by rrhyne** [comment]
1. The browser installation link should also be placed in the getting started workflow for each user affected. I'm not sure how you can determine that, so I'd default to adding it there for everyone.

![getting-started-png](https://user-images.githubusercontent.com/539268/83291824-d8f39180-a19d-11ea-9856-7147053bda3c.png)

2. I agree, [#10589](https://github.com/sourcegraph/sourcegraph/issues/10589), inline installation is likely to improve conversion ratios greatly
3. I think we can improve on the popup. I've watched user testing videos of people simply dismissing it reflexively without ever reading the contents.  My hunch is that a banner above the search results would convert better. I've attached a few options. The first is fairly aggressive, the second is less so.

#### tall banner
![tall-browser-exten-install-dialog](https://user-images.githubusercontent.com/539268/83293868-376e3f00-a1a1-11ea-9ec4-86747f2c50fb.png)

#### wide banner
![tall-browser-exten-install-dialog-1](https://user-images.githubusercontent.com/539268/83293871-389f6c00-a1a1-11ea-84d6-bb924c3b37f5.png)


Figma file:
https://www.figma.com/file/dThfwgbr0VVxOFRVukMgTU/Browser-Extension-Installation?node-id=0%3A1&viewport=54%2C780%2C0.5925044417381287

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Closing this as fixed with RFC 221 (if there were any nuances here that did not get designed/implemented please file as separate issues)
