### ISSUE TITLE
RFC 145: Event-level data from customers export button

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#10434]
Details in [RFC 145](https://docs.google.com/document/d/1-FzChixjEIA2HAeNZTRxiFYTLlRl2U0_2HKNmUydskk/edit#heading=h.nbo8mnby2v5k
)

Add button to export data to CSV

cc @christinaforney

**Comment by tsenart** [comment]
I'm making this issue only about adding the button. Please create a separate issue for the usage chart in the admin area and label it with RFC-145.

**Comment by tsenart** [comment]
I started working on this today. Writing up questions as I go along that I need clarification on (cc @dadlerj since you worked on a lot of this code).

1. Can safely target only deployments that use the new usage stats infrastructure backed by Postgres or do we also need to support the older Redis based deployments?
1. Are the SQL queries in the RFC exactly what is needed or could we reuse some of the already existing code in the `usagestats` and `usagestatsdeprecated` packages? (e.g. https://github.com/sourcegraph/sourcegraph/blob/4d5197600899b6a543ebaa92e4411c01f094f46c/cmd/frontend/db/event_logs.go#L257).
1. Regarding **Query 1** in the RFC: Is the only difference between that query's output and the already existing [`GetSearchUsageStatistics`](https://github.com/sourcegraph/sourcegraph/blob/abbc35ba2521775b8eeb1782ccd614adc2b58f79/cmd/frontend/internal/usagestats/search.go#L27) and [`GetCodeIntelUsageStatistics`](https://github.com/sourcegraph/sourcegraph/blob/f1b1867700476dc2a51b6f21fcef869348f19140/cmd/frontend/internal/usagestats/codeintel.go#L33) that it aggregates usage per user ID, rather than globally across all users? If so, can you explain why that is needed? I couldn't find the rationale in the RFC.

**Comment by tsenart** [comment]
Adjusted estimate based on the amount of feedback I need — I suspect we'll need a few timezone communication rounds before this gets done.

**Comment by dadlerj** [comment]
>Can we safely target only deployments that use the new usage stats infrastructure backed by Postgres or do we also need to support the older Redis based deployments?

Yep, this is actually impossible using the Redis data — we only have the date of the "latest" search/codeintel event there.

>Are the SQL queries in the RFC exactly what is needed or could we reuse some of the already existing code in the usagestats and usagestatsdeprecated packages? (e.g.

@ebrodymoore can confirm, but my hunch is that reusing existing code would be perfectly fine. The example SQL code was to clarify the output needed (and to simplify implementation on your side), but as long as the same results are provided, it's fine.

(The function you linked to only provides the aggregate count of unique users, though, not a list of users along with their daily activity... I'm not sure if there is any existing code that will actually be helpful here)

>Regarding Query 1 in the RFC: Is the only difference between that query's output and the already existing GetSearchUsageStatistics and GetCodeIntelUsageStatistics that it aggregates usage per user ID, rather than globally across all users? If so, can you explain why that is needed? I couldn't find the rationale in the RFC.

Yes, that is correct. The goal of this RFC is specifically to measure user-level engagement rather than aggregated engagement. The four bullets under the "Problem" section describe the specific analyses that are currently impossible.

Because this data would include user-level details, it is "opt-in", in that they'd have to click a button to download it and manually send to us.

@ebrodymoore might have more to say here about why this is useful/needed for the growth and product teams.

**Comment by ebrodymoore** [comment]
That's all correct, thanks @dadlerj . As long as the output is usage stats aggregated by individual user, I'm fine with any implementation - you know better than I do about the best way to get there.

It's important to note that GetSearchUsageStatistics and GetCodeIntelUsageStatistics are important, but a user does not necessarily have to take one of these actions to be an 'active user'. In the sample output in the RFC there are circumstances where the user was active but search and codeintel actions were null/zero, and these users still need to show up in this output.

**Comment by tsenart** [comment]
Thanks! This is helpful and I think I have enough to make progress on this on Monday. Today didn't have the chance for any coding time.
