### ISSUE TITLE
update docs to reflect creating clusters outside the sourcegraph-dev GKE project

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10453]
The sourcegraph-dev GCP project contains the k8s clusters for sourcegraph.com, k8s.sgdev.org, buildkite, etc.

When we create and delete new clusters in the same GCP project, it is easy to mistake one for the other and end up deleting or altering an important cluster instead of your dev/test cluster.

This issue reflects that we should update all our docs to indicate creating dev/test clusters outside the sourcegraph-dev project, to reduce chances of that happening.

**Comment by bobheadxi** [comment]
Is there instances of docs recommending using sourcegraph-dev? when I was testing out https://github.com/sourcegraph/deploy-sourcegraph/pull/707 I did a quick search and immediately landed on https://about.sourcegraph.com/handbook/engineering/deployments#how-to-start-a-test-cluster-in-our-sourcegraph-auxiliary-project-on-gcp, which recommends using sourcegraph-server

aside: it's rather confusing because in my mind I thought our deployments/buildkite/etc would be on something named sourcegraph-server, and playgrounds would be on sourcegraph-dev 😅

**Comment by slimsag** [comment]
I think @pecigonzalo has cleaned this up in a PR somewhere, but I don't have a link handy. Closing.
