### ISSUE TITLE
search sometimes returns "No results" with no indication that timeout was hit

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10469]
This gives two results:

https://k8s.sgdev.org/search?q=123451231+timeout:2m&patternType=literal

![image](https://user-images.githubusercontent.com/3173176/81266943-87bb0c80-8ffa-11ea-93d4-3065a9821c62.png)

But, if that query hasn't been ran for some time, [`123451231`](https://k8s.sgdev.org/search?q=123451231&patternType=literal) alone (without a large timeout) just shows `No results` (no indication that any repos timed out, or that a larger `timeout` could help).

**Comment by rvantonder** [comment]
I think this behavior originates from searcher (unindexed search) and repo zip archive copying. At least I get the same thing when I try search a large repo like linux for the first time on local machines. It may also be that this doesn't exist because I recall we don't have a good way of communicating from searcher that various errors occurred, we only rely on HTTP status codes. Can't recall exactly how we handle searcher responses but I think something like https://github.com/sourcegraph/sourcegraph/pull/8554 would be needed to communicate this.

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.
