### ISSUE TITLE
search: revert decision to exclude forks (and archives) by default 

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10482]
The proposal is to go back to including forks and archives by default. The change to exclude these was well-intentioned, but the fallout is causing significant user frustration and additional (and urgent) work. I'd like to reduce the risks associated with the change.

**Recap: Why did we make the decision to exclude forks?** Most significantly (but only partly) prompted by customers requested to exclude forks, as well as users over the course of time. All participants in the discussion basically agreed that "this was the right decision" (paraphrasing) https://github.com/sourcegraph/sourcegraph/issues/7004.

**Why revert now?** See #feedback, there have been a lot of unintended consequences and it's not clear that there's been a payoff. We spent significant effort trying to mitigate the fallout of this decision with (1) alerts (though insufficient for some use cases), (2) site setting options, and (3) “magic” treatment for repo matches, and now we need more explicit notifications and perhaps there are further unknowns. It’s wearying that we’re still trying to converge on a solution that was supposed to be a straightforward change, and it’s not clear that there’s a light at the end of the tunnel. While we're in this position, we risk more P1 issues, which leads to unplanned or hasty damage control.

**What next?** I propose we revert the decision so that forks (and archives) are included by default. User and global settings can opt-in to exclude forks for repos. We can then work towards converging on a suitable solution (additional notifications, etc.) for users or customers that choose to opt-in for excluding forks in a way that doesn't expose customers to this behavior by default, and so avoiding the urgency and P1 issues cropping up. I.e., https://github.com/sourcegraph/sourcegraph/issues/9928 will still be addressed (and I'll prioritize it), but the idea behind reverting here is to avoid the urgency for addressing the fallouts like these. Based on recurrent issues, I'm not convinced that addressing #9928 crosses the finish line for resolving the transition to exclude forks by default.

**Comment by rvantonder** [comment]
From https://github.com/sourcegraph/sourcegraph/issues/10313#issuecomment-625451535 @slimsag 

> I suspect this would not be a good choice and would introduce more confusion for users ("Now forks ARE included by default?!")

I agree churn is bad. But the converse here is the risk of more facepalming like https://github.com/sourcegraph/sourcegraph/issues/10313#issuecomment-624994250 and more "fix this quickly" as in #9928.

**Comment by slimsag** [comment]
First, I want to say _I still think excluding forks and archives by default is the right thing to do_. From every user I have seen interact with this, it did make sense to every one of them and site-admins alike. So, I do believe that even if we undo this change we are likely to have to make it in the future again. Now, on to the meatier topic here.

I can see why, in light of all this, it may be tempting to think we can simply revert the change -- but it's (unfortunately) not that simple. Forethought here about the overall situation is important:

Many of our users have already been trained (painfully, yes) that forks and archives are no longer included by default. There are going to be users in many different buckets here:

- Users that were used to the old behavior, painfully learned (or have not yet learned) the new behavior but have had it for 1-2 months.
- Users that have *only* had the new behavior (new customers).
- Users that are in both of the above buckets, and because their admins will not upgrade frequently will continue to have the same behavior for the next 1-8 months.

We could've done better educating users in many aspects about this change, for sure, but if we attempt to undo the change we're going to have to do the same and communicate that we've undone the change or we'll see a more drawn-out series of the same types of issues and confusions. I imagine:

- Six months from now someone upgrading and saying "Well, that's surprising, now forks and archived repos are included by default? My searches include a ton of junk! We need a way to undo this ASAP"
- A month from now someone upgrading and saying "Whoa, I am confused, my saved search query is now sending me notifications about forked repos and that is NOT ok"
- Three months from now someone upgrading and saying "Find references appears to be returning results in forks/archived repos now, what is going on??"

It's not just that churn is bad here -- but the fact that we're going to have this churn in large part for the next 1-9 months because people kinda don't upgrade frequently.

Given this I really see only two options to get us out of this shallow hole we dug by accident:

1. Revert the change, but:
  a. Migrate saved searches or otherwise ensure they do not change
  b. Add super clear disclaimers in our blog post and CHANGELOG to any API consumers that we undid the change
  c. Add a dismissible alert after upgrade that tells users forks and archived repos are now included by default again, including in code intel results (but how do we inform users of e.g. the bitbucket native integration which would also be affected?)
  d. ...Revisit doing all of this again in the not too distant future...
2. OR, move forward on this and just reprioritize work to make this one of our highest priorities
  a. Fixing https://github.com/sourcegraph/sourcegraph/issues/9928 in 3.16 or a 3.16 patch release
  b. Acknowledging there may be other unknowns here, and depending on their severity we may have to reprioritize again to adjust for it

My estimate would be that we are near to the end of the tunnel, and are better off going with option 2 above, but I agree there are of course risks there. My point with this message is option 1 is also not cheap, free, or easy, in any form :)

**Comment by rvantonder** [comment]
Understood. With the abundance of predominantly negative feedback and no real positive feedback(i.e., I believe there are positive sides to the change, but it is entirely tacit) reverting seemed like something in our interests. I accept that reverting is overshooting based on what you've said and option 2 is better overall. 

The position we're in is not great though, and hopefully there are a few takeaways to be more mindful of with search work going forward. I'm going to close this, but whoever can feel free to comment on the discussion.

**Comment by keegancsmith** [comment]
I missed this. In future could you cc the searchers team for issues you would like others to see?

**Comment by rvantonder** [comment]
Yes
