### ISSUE TITLE
`src actions exec` can cause frontend to be OOMKilled

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10540]
Repro:
* Configure `src` to hit `k8s.sgdev.org`
* Create a file `test.action.json` with contents: `{ "scopeQuery": "lang:go repo:sourcegraph" }`
* Run `src actions scope-query -f test.action.json`
* Observe the frontend OOM, which will result in a 503 error until the frontend restarts. You can observe also using `kubectl get pods` and `kubectl describe` against k8s.sgdev.org. (To configure `kubectl` to hit `k8s.sgdev.org`, run `gcloud container clusters get-credentials dogfood-full-k8s --zone us-central1-a --project sourcegraph-dev`.)

Note that the OOM isn't triggered when searching `lang:go repo:sourcegraph` in the GUI. I suspect this is because the results are limited.

I don't think the repository set being selected here is ridiculously huge, and my suspicion is the OOM is triggered by forwarding all file content matches to the frontend, whereas in theory we just need to forward the repo names for scope queries.

**Comment by mrnugget** [comment]
This is most likely due to us fetching `defaultBranch` for every search result: https://k8s.sgdev.org/github.com/sourcegraph/src-cli@d8eb823b74ccd3775d9b56420d26ed1f1fb770a9/-/blob/cmd/src/actions_exec.go#L410-440

@eseliger had an idea on how to improve it.

First milestone: in src-cli:

1. First fetch all the results, _without_ the default branch
2. Get the repositories of the results, de-duplicate list
3. Batch-query the default branch for the repositories

The next milestone would be to do this in the graphqlbackend and detect when multiple file matches have the same repository and memoize the default branch of that. End result would be that if we have X file matches in Y repositories, where X > Y, we only make Y requests to gitserver.

**Comment by eseliger** [comment]
One big problem is that `defaultBranch` is potentially fetched way more often than required. This comparison: https://github.com/sourcegraph/sourcegraph/compare/master...a3c2aef8737e03b4f5de120dd671e1156ce763da added caching on the repo level and reduced a query I ran locally from 1.05m to ~900ms.
This is not the only cause for the described issue, though. I found 2 more culprits:
- The response from Zoekt is just huge, much of the memory consumtion comes from the parsed zoekt result (Some GB).
- The response time is also bad because of these 2 lines: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b284ab9c8197a23bad0d1a77f0c98048fe968016/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L214-215. If we _could_ (idk if we can) make the assumption that the fragments are _ordered_ and never overlap, it would be much faster, as we can start parsing the runes from the last highlighted section on, effectively only parsing the line once, instead of several times (when there are multiple matches in a row)

**Comment by ryanslade** [comment]
@eseliger Is there a reason your change above wasn't merged? https://github.com/sourcegraph/sourcegraph/compare/master...a3c2aef8737e03b4f5de120dd671e1156ce763da

**Comment by eseliger** [comment]
Oh, I wanted to investigate some further if I can get even better results but didn't get around it yet. I'll just open that one as a pr now

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
I tagged this as cloud so that it shows up in that tracking issue too

**Comment by ryanslade** [comment]
This has been fixed in the backend via https://github.com/sourcegraph/sourcegraph/pull/11736
