### ISSUE TITLE
Investigate and fix syntax for searching all branches/commits

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10571]
`repo:foo@*` doesn't search all revisions, but a subset like `repo:foo@*bar` does. Likely we need to enable this in the implementation.

**Comment by rvantonder** [comment]
Inconsistent behavior:

`repo:^github\.com/sourcegraph/sourcegraph$@3.18:3.17` will list the matching repo revisions. But using `repo:^github\.com/sourcegraph/zoekt$@*refs/heads/` does nothing, when I would expect it to list the repo revisions. The `refs/heads` variety needs `type:commit` or such.

**Comment by rvantonder** [comment]
via @poojaj-tech , this is a good example of a rev pattern that just doesn't work, but feels like it should (or should raise an alert)

[`repo:github.com/sourcegraph/sourcegraph@3.1*`](https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph%403.1*&patternType=literal)

<img width="1108" alt="Screen Shot 2020-07-30 at 11 30 55 PM" src="https://user-images.githubusercontent.com/888624/89006992-bd4f5900-d2bc-11ea-8fea-8994c73e32ee.png">

**Comment by stefanhengl** [comment]
> Inconsistent behavior:
> repo:^github\.com/sourcegraph/sourcegraph$@3.18:3.17 will list the matching repo revisions. But using repo:^github\.com/sourcegraph/zoekt$@*refs/heads/ does nothing, when I would expect it to list the repo revisions. The refs/heads variety needs type:commit or such.

Currently, [glob patterns in revisions are only resolved for unindexed searches](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3473124/-/blob/cmd/frontend/graphqlbackend/textsearch.go?subtree=true#L441:33). [If a reporef contains a glob pattern it is automatically categorized as unindexed](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3473124/-/blob/cmd/frontend/graphqlbackend/zoekt.go?subtree=true#L647:1)  even if the repo and the (resolved) revision(s) may be indexed. The code path for repo results does currently not resolve ref-globs. [For repo results, revisions with glob patterns are simply discarded](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3473124/-/blob/internal/search/repo_revs.go?subtree=true#L156). 

Since both unindexed search and repo search need to resolve revisions, we could move the resolution of ref-globs up just below determineRepos.
