### ISSUE TITLE
Ping investigation: Instances are offline

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#10598]
## Context

- **Observation:** We started seeing more (large) instances became offline.
- **Affected versions:** Since 3.14.
- **Result:** We can't receive pings and customer instances won't be able to receive update notifications.

## Conclusions

1. Our queries are really slow. Based on pghero, it take 44s on average on dot-com:

![image](https://user-images.githubusercontent.com/2946214/81689409-d5b59180-948c-11ea-9dca-0eb90174a5aa.png)

2. We run too many queries for each ping. With a naive instrumentation, the method [`eventLogs.countPerPeriodBySQL`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/db/event_logs.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.1.2#L402:30) being call **222** times!

```diff
+var count = 0

func (l *eventLogs) countPerPeriodBySQL(ctx context.Context, countExpr, interval, period *sqlf.Query, startDate, endDate time.Time, conds []*sqlf.Query) ([]UsageValue, error) {
+	count++
+	fmt.Println("count:", count)
```

It is not a problem we would be able to notice immediately as it takes time for an instance's `event_logs` to grow until queries become too slow to finish before timeout. As of now, dot-com has 13M rows in `events_log`.

The major offender is we do _daily_, _weekly_ and _monthly_ for each type of events we care, e.g. code intel would at least call `eventLogs.countPerPeriodBySQL` 27 times:

https://github.com/sourcegraph/sourcegraph/blob/c3f41185f29f4f2d48007acce73d5795dfd52a5f/cmd/frontend/internal/usagestats/codeintel.go#L85-L95

[Same phenomena for search stats](https://github.com/sourcegraph/sourcegraph/blob/c3f41185f29f4f2d48007acce73d5795dfd52a5f/cmd/frontend/internal/usagestats/search.go#L75-L83).

## Suggestions

There are three things we could probably do to tackle the problem:
1. Make as many queries concurrent as possible.
2. Reduce the number of queries by doing some of the calculations without SQL.
3. Optimize the query itself (note: almost every column used in `event_logs` table has an index).

<details>
<summary>Example EXPLAIN ANALYZE</summary>

```
sg=# EXPLAIN ANALYZE WITH all_periods AS
  (SELECT generate_series(
     ('2020-04-01')::timestamp,
     ('2020-05-01')::timestamp,
     ('1 month')::interval) AS period),
 count_by_period AS
  (SELECT DATE_TRUNC('month', timestamp) AS period,
   COUNT(DISTINCT CASE WHEN user_id = 0 THEN anonymous_user_id ELSE CAST(user_id AS TEXT) END) AS count
   FROM event_logs
   WHERE (name='SearchResultsQueried')
   GROUP BY period)
SELECT all_periods.period, COALESCE(count, 0)
FROM all_periods
LEFT OUTER JOIN count_by_period ON all_periods.period = (count_by_period.period)::timestamp
ORDER BY period DESC;
                                                                             QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Merge Left Join  (cost=575347.41..594213.33 rows=1047690 width=16) (actual time=9035.404..9035.408 rows=2 loops=1)
   Merge Cond: (all_periods.period = ((count_by_period.period)::timestamp without time zone))
   CTE all_periods
     ->  ProjectSet  (cost=0.00..5.02 rows=1000 width=8) (actual time=0.003..0.004 rows=2 loops=1)
           ->  Result  (cost=0.00..0.01 rows=1 width=0) (actual time=0.000..0.001 rows=1 loops=1)
   CTE count_by_period
     ->  GroupAggregate  (cost=543215.64..548977.94 rows=209538 width=16) (actual time=8633.789..9035.335 rows=4 loops=1)
           Group Key: (date_trunc('month'::text, event_logs."timestamp"))
           ->  Sort  (cost=543215.64..543739.49 rows=209538 width=45) (actual time=8558.695..8610.906 rows=205325 loops=1)
                 Sort Key: (date_trunc('month'::text, event_logs."timestamp"))
                 Sort Method: external merge  Disk: 11888kB
                 ->  Gather  (cost=7744.48..518248.78 rows=209538 width=45) (actual time=122.223..8418.548 rows=205325 loops=1)
                       Workers Planned: 2
                       Workers Launched: 2
                       ->  Parallel Bitmap Heap Scan on event_logs  (cost=6744.48..496294.98 rows=87308 width=45) (actual time=115.814..8424.974 rows=68442 loops=3)
                             Recheck Cond: (name = 'SearchResultsQueried'::text)
                             Rows Removed by Index Recheck: 766317
                             Heap Blocks: exact=19162 lossy=32478
                             ->  Bitmap Index Scan on event_logs_name  (cost=0.00..6692.10 rows=209538 width=0) (actual time=103.060..103.060 rows=206060 loops=1)
                                   Index Cond: (name = 'SearchResultsQueried'::text)
   ->  Sort  (cost=69.83..72.33 rows=1000 width=8) (actual time=0.009..0.009 rows=2 loops=1)
         Sort Key: all_periods.period DESC
         Sort Method: quicksort  Memory: 25kB
         ->  CTE Scan on all_periods  (cost=0.00..20.00 rows=1000 width=8) (actual time=0.004..0.006 rows=2 loops=1)
   ->  Materialize  (cost=26294.62..27342.31 rows=209538 width=16) (actual time=9035.390..9035.391 rows=3 loops=1)
         ->  Sort  (cost=26294.62..26818.47 rows=209538 width=16) (actual time=9035.387..9035.387 rows=3 loops=1)
               Sort Key: ((count_by_period.period)::timestamp without time zone) DESC
               Sort Method: quicksort  Memory: 25kB
               ->  CTE Scan on count_by_period  (cost=0.00..4190.76 rows=209538 width=16) (actual time=8633.794..9035.357 rows=4 loops=1)
 Planning Time: 0.193 ms
 Execution Time: 9043.278 ms
```

</details>

**Comment by unknwon** [comment]
Further experiment with @eseliger make us think the following part is the most expansive:

```
COUNT(DISTINCT CASE WHEN user_id = 0 THEN anonymous_user_id ELSE CAST(user_id AS TEXT) END) AS count
```

Notable: `anonymous_user_id` does not have index on it.

**Comment by tsenart** [comment]
> We run too many queries for each ping. With a naive instrumentation, the method eventLogs.countPerPeriodBySQL being call 222 times!

Addressing this would mean converting all of these 222 SQL queries into one that scans over the event_logs table a single time and aggregates everything in one pass.

In the mean time, it's possible that we can get some good mileage from increasing the memory available to Postgres to hold all the database in memory. Given it's 20.5GB, it's doable. We also need to tune the settings with https://pgtune.leopard.in.ua/

@slimsag: What amount of memory and CPUs are we giving Postgres at the affected customers and how are we tuning Postgres (e.g. `shared_buffers`)?

**Comment by tsenart** [comment]
CC @sourcegraph/code-intel

**Comment by unknwon** [comment]
Update: @eseliger and I added a btree index for `anonymous_user_id` column on dot-dom PG pod, the index consumes about 718MB.

Now the same query (posted in the original content) is much faster now ~1s (vs 9s-30s). So this is something we need to persistent. But it still read from disk on merging results, increase the RAM would definitely help here.

**Comment by tsenart** [comment]
@unknwon: Can you open a PR with that migration and cross reference with this issue?

**Comment by unknwon** [comment]
> @unknwon: Can you open a PR with that migration and cross reference with this issue?

Yep will do.

**Comment by tsenart** [comment]
After increasing RAM on the dotcom pgsql deployment, the same query now takes roughly 740ms. This mainly due to not having to read from disk after all the rows are already in the buffer cache.

**Comment by eseliger** [comment]
@unknwon and I also added the index, this might also influence the results

**Comment by slimsag** [comment]
> @slimsag: What amount of memory and CPUs are we giving Postgres at the affected customers

From what I understand, this issue affects all customers with high usage but we d not have an exact list of affected customers.

Moreover, we do not have any Postgres resource requirements / guidelines in place aside from our base deployment which requires 4CPU 2G memory:

https://github.com/sourcegraph/deploy-sourcegraph/blob/93f3e3b1ee561d882b88608ad3eccd48f799f66a/base/pgsql/pgsql.Deployment.yaml#L50-L56

Many of these customers opt to use a managed Postgres instance such as RDS, based on the same resource constraints. And this has worked well up until now, so I would expect us to optimize, reduce the dataset size, or manage the data more slowly in the background so that is no longer a problem.

We can ask customers to increase resources to postgres and configure things, but:

1. We will have to document how to migrate the data over
2. We will have to document how someone on RDS would do it
3. It is likely some/many customers will just miss the instructions and we will need to surface the issue directly in our app.

> and how are we tuning Postgres (e.g. shared_buffers)?

- For Kubernetes: https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/pgsql/pgsql.ConfigMap.yaml#L127 (safe to assume unmodified in all customer deployments).
- For other deployment types: unmodified / default.

**Comment by dadlerj** [comment]
Wow! Thank you all — this is fascinating.

I don't think that requesting more resources should be necessary. If simply adding an index drops queries from 9-30s to 1s, then that's 99% of the solution. 

We absolutely should cut down the volume of queries, and the volume of data returned (e.g. getting at the daily/week/monthly issue). I'll file a separate issue for that.

My preference is to reduce the number of migrations. If we can make this work on Dotcom without that, then it should be fine at customer sites for now.

**Comment by tsenart** [comment]
> Many of these customers opt to use a managed Postgres instance such as RDS, based on the same resource constraints. And this has worked well up until now,

The introduction of analytics workloads and data volume makes this much more important. Since we now have this by default, I think we need to adjust how resourcing equations and recommendations, as well as migrate existing customers that could be affected (larger ones).
 
> Moreover, we do not have any Postgres resource requirements / guidelines in place aside from our base deployment which requires 4CPU 2G memory

@slimsag: I believe we should incorporate Postgres resourcing (and tuning) into your resource estimator work. Ideally, the Postgres instance has enough memory to hold most of its dataset in memory, and be tuned with according recommendations from pgtune. How could we best accomplish this?

> I don't think that requesting more resources should be necessary. If simply adding an index drops queries from 9-30s to 1s, then that's 99% of the solution.

I am not confident that we can interpret this at face value. That reduction could have been from the second run of the query benefiting from caching that the first one didn't (even if the available in memory cache size was still small).

Overall, with analytics workloads and data volumes, large customers need more resources.

> We absolutely should cut down the volume of queries, and the volume of data returned (e.g. getting at the daily/week/monthly issue). I'll file a separate issue for that (#10612)

I will take a look at this tomorrow, see if I can muster some nice optimizations :)

> My preference is to reduce the number of migrations. If we can make this work on Dotcom without that, then it should be fine at customer sites for now.

The migration on dotcom was smooth, so if other customers have enough resources in their K8s node pools, then it should be relatively painless as well. Of course, it is going to be some work to document and guide these customers through that, but it's important.

**Comment by slimsag** [comment]
> I believe we should incorporate Postgres resourcing (and tuning) into your resource estimator work.

That would be great, but almost all customers today are running the base resources I mentioned, so what are the reference scaling factors here? we don't have any data points for this. We would need an appropriate entry here: https://github.com/sourcegraph/resource-estimator/blob/master/internal/scaling/references.go

> Ideally, the Postgres instance has enough memory to hold most of its dataset in memory, and be tuned with according recommendations from pgtune. How could we best accomplish this?
>
> Overall, with analytics workloads and data volumes, large customers need more resources.
>
> The migration on dotcom was smooth, so if other customers have enough resources in their K8s node pools, then it should be relatively painless as well. Of course, it is going to be some work to document and guide these customers through that, but it's important.

I totally understand the motivation and desire here. But, this is going to be time consuming to do. Here's what we'll need done:

1. Documentation for when a site admin SHOULD do this (how do they know when postgres isn't tuned properly?).
2. Documentation for how to do this in Kubernetes + our pgsql deployment.
3. Documentation for how to do this in Kubernetes + RDS (I am not sure you even can run pgtune there, will need investigation).
4. A callout in our blog post and changelog that Sourcegraph now needs this.

Even with the above, I suspect <50% of site admins will follow through on this because "sourcegraph is running fine for us". We could email them aggressively about it, too, but I also doubt that will do much. Probably the only thing that will help is some aggressive in-app warnings about postgres having insufficient resources; so we'll need to add that to the app somehow as well (and figure out how to detect that case).

I'm not saying we shouldn't do this, I'm just saying it's going to be difficult and time consuming - and we're going to have to find a time when there are not more important matters at hand.

In the meantime, are we sure reducing the dataset size or performing these queries more incrementally / slowly is not a good idea?

**Comment by tsenart** [comment]
> That would be great, but almost all customers today are running the base resources I mentioned, so what are the reference scaling factors here

The scaling factors are 1) number of daily active users and how active they are (i.e. how many event_logs rows are added every day) and to lesser degree 2) number of repos.

> I totally understand the motivation and desire here. But, this is going to be time consuming to do. Here's what we'll need done:

I understand, I defer to you and the distribution team to prioritize this accordingly.

> Documentation for when a site admin SHOULD do this (how do they know when postgres isn't tuned properly?).

By default, we should always be configuring the Postgres deployment accordingly to the scale of the customer (resources + tuned config). Scaling resources for our services, but not our databases, is a problem.

> Documentation for how to do this in Kubernetes + our pgsql deployment.

Yeah, this should be straightforward, see https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2502.

> Documentation for how to do this in Kubernetes + RDS (I am not sure you even can run pgtune there, will need investigation).

Pgtune only produces configuration that we need to apply to an instance. I suspect that managed services like RDS are already tuned appropriately for the service tier the customer chooses, so we should just recommend a certain service tier (i.e. amount of resources).

> A callout in our blog post and changelog that Sourcegraph now needs this.

Yeah, makes sense, although I wouldn't expect admins to be surprised with the fact that there's a need to scale the database along with the rest of the infrastructure.

> Even with the above, I suspect <50% of site admins will follow through on this because "sourcegraph is running fine for us". 

How much of it could we (semi?) automate during an upgrade?

> Probably the only thing that will help is some aggressive in-app warnings about postgres having insufficient resources; so we'll need to add that to the app somehow as well (and figure out how to detect that case).

Bitbucket Server does this well so I think that could be a good approach.

> In the meantime, are we sure reducing the dataset size or performing these queries more incrementally / slowly is not a good idea?

Yes, I'll be looking into optimizing queries nonetheless, but that won't address the fact that many of our Postgres instances at customer's are misconfigured and potentially under-provisioned.

**Comment by slimsag** [comment]
> Scaling resources for our services, but not our databases, is a problem. [...] that won't address the fact that many of our Postgres instances at customer's are misconfigured and potentially under-provisioned.

This hasn’t been a problem for any Sourcegraph instance for as far back as at least the earliest 3.0 release. This is a recent problem, and as I understand it primarily a problem with the introduction of a large amount of data and heavy queries for user event logging.

My point here is (1) yes this is a problem and we should address it ASAP but (2) I believe this to be primarily a _regression_ because we introduced new features here without proper forethought/planning about how it was going to scale and how we would communicate the change to admins. We made an assumption here that Postgres scaling was something we already do well and that admins would know how to do it — but that is not true today and as such it has come back to bite us and we’re having to play catch up here to fix this regression.

Will follow up on your other points later, just wanted to give some clearer insight into how I view this largely as a regression / lack of forethought so we can learn from this type of issue in the future

**Comment by slimsag** [comment]
A different way of phrasing what I am trying to say above:

From the perspective of a site admin, Sourcegraph requires lightweight / minimal and static postgres resources. This has been true of all Sourcegraph versions they have ever used. Then, just recently, we introduced a number of changes which put significantly more pressure on their Postgres instance and do not tell them nor communicate what they should expect it to increase, how they should deal with it, etc. AND harming the performance of their Sourcegraph instance by effectively making it now incorrectly provisioned.

That is a _bad_ regression from my viewpoint as a site admin.

**Comment by tsenart** [comment]
> That is a bad regression from my viewpoint as a site admin.

Agreed. We're playing catch up on this issue.

**Comment by dadlerj** [comment]
>In the meantime, are we sure reducing the dataset size or performing these queries more incrementally / slowly is not a good idea?

I don't know if this will solve the problem, but I strongly support this. And I do agree with @slimsag about how painful it will be to have to go back and ask former admins to change things. @efritz I know you're working overtime with the LSIF backend migration work, but once 3.16 is shipped, could you prioritize investigating if we're over-logging codeintel events? As of right now codeintel.searchdefinitions and codeintel.searchhover alone represent >half of all events fired on dotcom (in the last $REDACTED days). This is likely due to the huge volume of browser extension users, so it may be totally valid, but it's worth looking in to).
![image](https://user-images.githubusercontent.com/5589410/81954877-401a1f00-95be-11ea-8ae9-330525376c60.png)

Another optimization — getting rid of now-duplicated events. E.g., "hover" fires on hovers on dotcom, while "codeintel.searchhover" or "codeintel.lsifhover" or "codeintel.lsphover" also does.

This sort of event audit/cleanup just has to be prioritized — perhaps @ebrodymoore can help with identification of unneeded events.

**Comment by tsenart** [comment]
@dadlerj: I've some work today on optimizing these queries, please take a look: https://github.com/sourcegraph/sourcegraph/issues/10612#issuecomment-628694158

**Comment by dadlerj** [comment]
Thanks @tsenart ! That's huge, and there's no way this could work without that... That said, reducing the total # of events to those we actually need is still valuable. Perhaps not top priority any more though.

**Comment by unknwon** [comment]
@dadlerj Just checking, has everything back to good state? If so, I'll close this issue.

**Comment by tsenart** [comment]
And if so, we can also remove some dead code in the usage stats and db package.

**Comment by unknwon** [comment]
I'll own removing related dead code in 3.17.
