### ISSUE TITLE
Indentation changes on hover

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#107]
- **Sourcegraph version:** Sourcegraph.com
- **Platform:** All

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/golang/go@go1.10.3/-/blob/src/path/filepath/path.go#L25
2. Hover over lines 69-74 and observe the indentation jumps

HT @AstromechZA

**Comment by sqs** [comment]
More info from a private issue https://github.com/sourcegraph/enterprise/issues/12218  (since closed and redirected here):

---

from @sqs 

https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/ThirdPartyNotices.txt also repros it

---

from @slimsag 

This is definitely a regression. The issue appears to be in how tabs are rendered in spans.

Before the line is hovered over, it is a single span element and it renders properly:

![image](https://user-images.githubusercontent.com/3173176/42599321-b74d8a8e-8513-11e8-9f8c-d175337b8303.png)

However, afterwards it gets split / broken into a bunch of smaller spans:

![image](https://user-images.githubusercontent.com/3173176/42599345-cad441ce-8513-11e8-87da-d9c47d59aacb.png)

When this occurs, the tab in the line gets put into its own span which for some reason affects how wide it renders as.

---

**Comment by dadlerj** [comment]
This was also reported by a user on Twitter: https://twitter.com/liamzebedee/status/1069938760706609153 

In https://sourcegraph.com/github.com/ethereum/solidity/-/blob/libevmasm/Instruction.h#L121:2

**Comment by Joelkw** [comment]
This doesn't seem to still be an issue; tested the flow described in sourcegraph/enterprise#12218
