### ISSUE TITLE
Large value of ElapsedMilliseconds when empty search returns instantly

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10701]
Some searches (ones that typically have no results and return instsantly) have a very large `ElapsedMilliseconds` value. This can be reproduced against the sourcegraph.com or local endpoint with a [`src`](https://github.com/sourcegraph/src-cli) query like:

```
SRC_ENDPOINT=https://sourcegraph.com  SRC_ACCESS_TOKEN="<your-token>" src search -json 'repo:*'
```

And you'll see:

```
{
  "SourcegraphEndpoint": "https://sourcegraph.com",
  "Query": "repo:*",
  "Site": {
    "BuildVersion": "63706_2020-05-14_48cb2bc"
  },
  "Results": [],
  "LimitHit": false,
  "Cloning": [],
  "Missing": [],
  "Timedout": [],
  "ResultCount": 0,
  "ElapsedMilliseconds": 2077252342
}
```

This is not an issue in `src`, it is reproducible in the api console, so the problem lies in the backend code:

<img width="1039" alt="Screen Shot 2020-05-14 at 5 20 37 PM" src="https://user-images.githubusercontent.com/888624/81998426-4d0f3080-9607-11ea-9e15-c5bebdac8e24.png">

I think I've seen this recurrently in the last couple of months, so I don't think it's a new issue. This is likely what affects some metric logging #10058. Something is going awry, and it is likely an integer conversion problem, so the code and values that contribute to [calculating ElapsedMilliseconds](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@48cb2bc0136f768ff18577ab4c6a6e11b431cdb8/-/blob/cmd/frontend/graphqlbackend/search_results.go#L195) needs investigating.

**Comment by rvantonder** [comment]
@fedealconada this is another issue that you could pick up, if you like. As per description, it's probably something silly and not too difficult to fix, just needs time to trace the source of imprecision.

**Comment by rvantonder** [comment]
Pointer: I would recommend debugging by running the query with [`src`]https://github.com/sourcegraph/src-cli) against a local sourcegraph instance. You generate the `<access token>` in user settings.

**Comment by fedealconada** [comment]
Great, I'll take a look at it :) Btw, I can't access the link on [#10058](https://github.com/sourcegraph/sourcegraph/issues/10058). Not sure if its relevant though.

**Comment by rvantonder** [comment]
Ah, yeah. Nah, there's nothing in the link that's helpful.

**Comment by fedealconada** [comment]
I'm running Sourcegraph locally and when trying to generate an access token I get this...
![image](https://user-images.githubusercontent.com/4473536/81999571-da647c00-962b-11ea-8416-8b4aa001b068.png)

**Comment by rvantonder** [comment]
Ah, shoot. I guess that won't work, I'll try find out if we have a work around, but what you could do instead is just issue requests through the web UI (`repo:*` in the search bar) and add a log statement in `EllapsedMillisecond` function I linked and go from there.

**Comment by fedealconada** [comment]
Yeah, using the GraphQL API console works fine

**Comment by fedealconada** [comment]
So, I've checked a bit the code and found out that, basically, the problem is just that [`sr.start`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@48cb2bc/-/blob/cmd/frontend/graphqlbackend/search_results.go#L195) is not defined, so it takes its default value `0001-01-01 00:00:00 +0000 UTC` and that's why the calculation throws a large number. This happens when handling the errors from the queries that end up on a [`return alertForQuery()`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%4048cb2bc+return+alertForQuery&patternType=literal) so then the `Results` method instantiates a [`SearchResultResoler`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@48cb2bc/-/blob/cmd/frontend/graphqlbackend/search_alert.go#L601:2) without a `start` time, which causes the bug.

There are multiple ways in which we can solve this:
**1).** One workaround could be just to pass `return &SearchResultsResolver{alert: alert, start: time.Now()}, nil` but that time, theoretically, will not really reflect a real time. But, as we know this problem happens when there's like an error and the queries return instantly I guess that in practical terms the elapsedTime is 0 milliseconds... So, IDK, up to you... 
**2).** Add a `start :=  time.Now()` line inside [`NewSearchImplementer`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@48cb2bc/-/blob/cmd/frontend/graphqlbackend/search.go#L71), modify `alertSearchQuery` signature to also receive the time and also modify the [`searchAlert` ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@48cb2bc/-/blob/cmd/frontend/graphqlbackend/search_alert.go#L22) struct so it has a `start` member and, finally, modify the `Results` method so it instantiates the resolver with the time.
3). I have not given it a thought but, maybe I there could be some other way that does not need to change the signature of `alertForQuery` method...

Thoughts on this @rvantonder ?

**Comment by rvantonder** [comment]
That makes so much sense now! 🤦 See PR comments.
