### ISSUE TITLE
When changeset creation fails spinner does not disappear

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10717]
When creation of changeset fails, the errors show up at the top, but the "Publishing" next to a patch set is still a spinner and "Publishing...". It should show that there's an error. Otherwise, if it's a long list of patches, the user misses the errors at the top.

**Comment by ryanslade** [comment]
Is this the issue? Or should it display the red error message?

<img width="1140" alt="Screenshot 2020-05-19 at 16 40 05" src="https://user-images.githubusercontent.com/25610/82340601-b4562780-99ef-11ea-8840-2733d09d3c5b.png">

I can reproduce the "blue banner" error above if we have a changeset job with an error but a null  `finished_at`. At the moment I'm doing this manually in the DB in order to reproduce the error state.

I can't reproduce the red error banner and a spinner though.

@mrnugget

**Comment by ryanslade** [comment]
I just spoke to @eseliger and he said that he's seen this again recently but with the red banner. This indicates that background processing state is `ERRORED`

However, he said that once he refreshed the page the spinner was gone and the red error banner was still there. 

The fact that refreshing the page fixed the state makes me think it's a frontend issue, so passing over to @eseliger. He'll pass it back if it looks like a backend issue.
