### ISSUE TITLE
Code discussions links are not real links

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1072]
Repro:

1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph
2. Under **Discussions** on one of the threads, try:
  - middle-clicking to open in new tab (DOES NOT WORK, opens https://sourcegraph.com/github.com/sourcegraph/sourcegraph# not the thread)
  - ctrl-clicking to open in new tab (WORKS AS EXPECTED)
  - right-clicking on the link and copying the link URL (DOES NOT WORK, copies https://sourcegraph.com/github.com/sourcegraph/sourcegraph#)

@slimsag 	I noticed that a lot of code discussions links are like this. Is there a reason why (or just a bug you haven't fixed yet)?

**Comment by slimsag** [comment]
Yeah this is a bug, it comes from our usage of `openFromJS`: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+openFromJS It should be possible to fix that func to replicate this behavior I think.

The reason this is needed (i.e. the reason we don't use real links) is because it is desirable to have 'clicking anywhere in the entire row' open the discussion, i.e. clicking anywhere in here:

![image](https://user-images.githubusercontent.com/3173176/48753679-20fe3380-ec4c-11e8-99e3-093b9e2fd2ce.png)

But we still need links below that element, like clicking on `chris` to work. And browsers do not allow links-inside-links, so we kind of emulate it a bit.
