### ISSUE TITLE
Sourcegraph.com behaves like customer instances for a subset of repositories

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#10821]
I shared this idea with @tsenart and @slimsag in person, but wanted to write it down for the team's consideration.

Any time we get "the largest customer ever" in our sales pipeline, we face unknown unknowns (e.g., [current example](https://app.hubspot.com/contacts/2762526/company/557692805/)).

One thing we do to be proactive is to spin up a private instance to replicate the customers environment as closely as possible so we can find issues before the customer finds them. This is still a 1-off process per customer. It would be nice if we could be even more proactive at scaling Sourcegraph even before customers enter our sales pipeline.
 
Given that we are prioritizing work on Sourcegraph.com this year (see [RFC 151](https://docs.google.com/document/d/1qSSo83MJNcNbJhQOhDyHsGBCYPjyr7uhVQKGfZ8Vxfg/edit)), it would be nice to be able to use Sourcegraph.com as a test of the scale that our product can support. This is not true today because Sourcegraph.com takes shortcuts that would not be acceptable on customer instances (e.g., we only index top 10k repos, we lazily sync repositories).

The ultimate goal would be "Sourcegraph.com has no special logic to handle scaling and behaves exactly like customer instances".

To get there, I propose an intermediate milestone: "Sourcegraph.com has no special logic to handle scaling and behaves exactly like customer instances for N repositories".
- N can start at 10k.
- The difference from where we are today, is that we would want to start proactively syncing these 10k repos on Sourcegraph.com.
- The lazy logic still works for all other repositories not included in the set of N.
- Over time we can increase N until we find a new set of issues. We fix those issues and then continue increasing N until we find another new set of issues.

If we had this capability, it might actually be useful for us to use with customers too (I am less sure about this part, but wanted to share anyway). Currently if we have a customer who has more repositories than we think we can support, we ask them to try connecting a subset to Sourcegraph first (call this subset `R`). This is less than ideal because then we have to figure out which repositories to connect. If we had this capability, we could tell them to connect all their repositories, but we would only proactively index/update repositories in the subset `R`. All of the other repositories would still be accessible on the instance, just like Sourcegraph.com today. This would be a better customer experience and the customer could dynamically increase `R` over time as we find and resolve issues.

To be clear, this proposal probably would not eliminate the need for us to spin up test instances per customer, but I think it would eliminate a class of issues that we would find during that kind of testing.

**Comment by nicksnyder** [comment]
@keegancsmith @tsenart This issue is merely a proposal and for your consideration. You are free to close this issue or act on it in any way you wish.

**Comment by keegancsmith** [comment]
When I saw it mentioned on slack we should make sourcegraph.com have less special cases I had the same idea as a proposal. So this sounds good to me.

**Comment by keegancsmith** [comment]
General thought on large customers and RFC 151 from a backend perspective. These thoughts occurred to me while chatting to @tsenart now. They are not fully baked :) Posting them here since it seems like a useful discussion area for this. Also will help me converge on how to think about these things.

Sourcegraph.com RFC 151's work will be quite different to a large customer. RFC 151 is mostly about targeting smaller customers. If you are a small customer then your global searches won't be over that much code. This implies that the workload for a user request won't really change much from what we support today. Contrasting to large customers were just the list of repositories alone is huge, this affects every "global" user request.

There is overlap in our batch systems (repo syncing/indexing/etc), and there are parts of RFC 151 which require us to provide fast search over a higher scale of repositories (providing OSS value). However, for sourcegraph.com there are simplifications we can take to this, since the target is much clearer (eg rely on github teams/orgs to help scope things/etc).

Given those thoughts I think we should create a plan for RFC 151 independent of our large customers. Then once that plan is sketched out, we can see how we fit in wins for large customers. My concern is we end up creating much more complicated solutions / incorrect prioritization when we have in mind large customers while planning RFC 151.

Does that make sense @nicksnyder? Or am I off base a bit here?

@christinaforney how are you thinking of RFC 151 in relation to large customers? Does what I say above resonate with the product planning you are doing?

cc @sourcegraph/core-services

**Comment by nicksnyder** [comment]
@beyang is working on this: https://sourcegraph.slack.com/archives/CHPC7UX16/p1593446317093200

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
I am going to close this since it was more of a longer term discussion than a concrete proposal for next steps. Feel free to reopen and/or resassign if you wish.
