### ISSUE TITLE
sourcegraph/server:insiders DB not available: dial tcp: lookup pgsql on 192.168.65.1:53: no such host

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1082]
Commands:

```
docker pull sourcegraph/server:insiders
rm -rf /tmp/sourcegraph
docker run --publish 7080:7080 --rm --volume /tmp/sourcegraph/config:/etc/sourcegraph --volume /tmp/sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock sourcegraph/server:insiders
```

Output
```
00:49:03 zoekt-indexserver | 2018/11/21 00:49:03 Post http://127.0.0.1:3090/.internal/repos/list: dial tcp 127.0.0.1:3090: connect: connection refused
00:49:05          frontend | DB not available: dial tcp: lookup pgsql on 192.168.65.1:53: no such host
00:49:05          frontend | Terminating frontend
frontend died. Shutting down...
```

This is not broken on 2.13.5, so something since then broke this.

**Comment by slimsag** [comment]
When I added these `docker:env` directives in https://github.com/sourcegraph/sourcegraph/commit/848a8cf23221f71b9b36b4683979d853d5991747 I assumed that like `docker:cmd` directives, they would be ignored if they were not in the main package being dockerized.

However, it turns out I was wrong. Comparing:

- https://github.com/sourcegraph/godockerize/blob/master/godockerize.go#L129-L137
- https://github.com/sourcegraph/godockerize/blob/master/godockerize.go#L119-L120

We do only use `docker:env` in this fashion, however: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22docker:env%22#1

The fix here is as simple as copying that godockerize logic for `cmd` case above into the `env` case above and updating godockerize in the repo.
