### ISSUE TITLE
Frontend: Repository permissions for campaigns

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10982]
Related backend work: #10809

- [x] Implement UI component for `HiddenPatch`
- [x] Implement UI component for `HiddenExternalChangeset`
- [x] Make sure campaign status also shows errored for errors.length === 0 but status === ERRORED
- [x] In campaign update diff generator put all hidden{Changesets|Patches} into unmodified tab
- [x] CampaignUpdateDiff: Show info box when some changesets won't be updated

Related backend PR: https://github.com/sourcegraph/sourcegraph/pull/10856

**Comment by mrnugget** [comment]
@eseliger I updated this ticket and https://github.com/sourcegraph/sourcegraph/issues/10809 to remove the task about the `visibility` filter in the `changesets` query, since @sqs confirmed in [this Slack thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1591280008031100) that we can delay the implementation of that until we have the new flow ready. That means, for now, you can take the number of open changesets out of the modal.
