### ISSUE TITLE
Remove hard distinction between manual and patchset campaigns

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10984]
RFC: [RFC 157 - Campaigns authorization model](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit#heading=h.m2a6qvh96dy8)

- Remove campaign.patchSet query
- Test all workflows

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
Backend part done in https://github.com/sourcegraph/sourcegraph/pull/11495.

Since changing the frontend would mean making the "Add changeset" form available even if the campaign has a patchset I think we should wait with the frontend work until we have the new campaigns flow settled. What do you think @eseliger?
