### ISSUE TITLE
repository status page with "cloning" filter is extremely slow

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#11029]
- **3.16** 
- **k8s on GKE** 

#### Steps to reproduce:

1. Spin up a Sourcegraph instance and feed it 50k repos
2. Go to Admin -> Repository status -> "Cloning" 

#### Expected behavior:

Repo list of currently cloning repos shows up.

#### Actual behavior:

That page takes a long time to construct and more often than not times out.

**Comment by eseliger** [comment]
This was supposed to be fixed here https://github.com/sourcegraph/sourcegraph/issues/8725 but apparently there's more

**Comment by tsenart** [comment]
@ryanslade: Was the work you did in https://github.com/sourcegraph/sourcegraph/pull/10041 supposed to help with this?

@keegancsmith: I'm adding the git metadata indexing service idea that would solve this by having this information in Postgres to the work to be done in RFC 151. Seems like a good one to prioritise sooner rather than later, but we can discuss in our meeting on Wednesday.

**Comment by keegancsmith** [comment]
> @keegancsmith: I'm adding the git metadata indexing service idea that would solve this by having this information in Postgres to the work to be done in RFC 151. Seems like a good one to prioritise sooner rather than later, but we can discuss in our meeting on Wednesday.

That won't necessarily help in this case, that is about the list of repositories that are cloning. Metadata is more likely relevant for cloned repos.

The fix for this issue is likely more straight forward. On each gitserver we maintain a list of all clones. We need to query it directly. We likely are doing something indirect.

**Comment by ryanslade** [comment]
> @ryanslade: Was the work you did in #10041 supposed to help with this?

It helped in the previous instance but we must be hitting a different bottleneck here, probably because a lot of repos are currently cloning. The previous slowdown was happening after we already had all repos cloned.

**Comment by uwedeportivo** [comment]
similar behavior with "cloned" and "indexed"

**Comment by keegancsmith** [comment]
I assume this is relatively high priority for the scale you are testing? High priority since you rely on these pages for insights into instance health / progress? Or can be fixed later?

**Comment by tsenart** [comment]
@keegancsmith: Makes me wonder if #11169 should happen sooner rather than later.

**Comment by felixfbecker** [comment]
Unassigning `team/web` since this appears to be handled by the cloud team, lmk if that's not correct

**Comment by asdine** [comment]
After discussion with @keegancsmith, the solution would be to add an endpoint to Gitserver that would determine the list of cloned/cloning repositories from the [`RepositoryLocker`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@61ab19c9019c853759156c0b1957bffa0e6e166f/-/blob/cmd/gitserver/server/lock.go#L23) map and return it.

For example, the list of cloning repositories can be determined by checking all repositories whose `GitDir` doesn't exists.

**Comment by tsenart** [comment]
@asdine: So what do we do with that data that gitserver returns, who consumes it? Are we putting in the repo table for each  repo via repo-updater?

**Comment by keegancsmith** [comment]
> @asdine: So what do we do with that data that gitserver returns, who
> consumes it? Are we putting in the repo table for each  repo via
> repo-updater?

The cloning status page graphql resolver does a few things, but
essentially it looks like this:

  repos := db.ListAllRepos()
  info := gitserver.GiveCloningInfo(repos...)
  return filter(info.Repo if info.Cloning)

To make it efficient we can instead do

  cloning := gitserver.ListCloningRepos()
  repos := db.ListRepos(cloning)
  return repos

**Comment by asdine** [comment]
@tsenart No writes will be done on the database, basically on postgres side we'll just change how the query that lists the repository is made

**Comment by tsenart** [comment]
How is this approach going to help with this? Additionally, what are the pros / cons of storing this information in Postgres vs having to RPC out to git-server (i.e. application level joins)?

> similar behavior with "cloned" and "indexed"

**Comment by tsenart** [comment]
I scheduled a 30 minute chat for us to discuss this live.

**Comment by keegancsmith** [comment]
To pre-empt the live discussion:

- Each gitserver maintains a list of currently cloning repos as part of its operations.
- Zoekt maintains a list of indexed repo/revisions as part of its operations.

Storing this state in the DB pros:
- You can use it in a where query
- Less complexity for clients of this info.

Storing the state in the DB cons:
- Cached data, source of truth is still what is on disk.
- Requires a process to clean up table in case of a process crashing mid clone/etc.
- Requires introducing a write path to DB for services which are independent of the DB.
- More complexity for server.

**Comment by tsenart** [comment]
Outcome of the discussion.

- PR 1: Add migration to add `cloned` column, add index, and implement store.SetClonedRepos and use it in the syncCloned loop. The query to back that is like `UPDATE repo SET cloned = false WHERE cloned AND id NOT IN (UPDATE repo SET cloned = true WHERE NOT cloned AND name IN (...) RETURNING id);` . We can easily extend that to normalise the casing which is something I hadn't thought about.
- PR 2: Implement store.CountClonedRepos in repo-updater to replace the current implementation in computeNotCloned method: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repoupdater/server.go#L603
- PR 3: Update the frontend db.Repos.ListRepos and repo-updater store.ListRepos to be able read cloned column and filter by it. Use that capability in the repositoryConnectionResolver  instead of doing application level filtering.
- PR 4: Delete clone in progress list page and all code related to it. The cloning status indicator already serves this purpose of informing the admins of cloning progress.

**Comment by asdine** [comment]
> We can easily extend that to normalise the casing which is something I hadn't thought about.

@tsenart Could you tell me more about this?

**Comment by tsenart** [comment]
@asdine: This something that @keegancsmith mentioned regarding the casing of the names that gitserver returns. @keegancsmith: What needs to be normalized exactly? All else considered, it'd be important for us to be able to use the name index, `LOWER(name)` wouldn't be good, but lowercasing every name returned by gitserver in the application side would be fine. Is this what you meant?

**Comment by keegancsmith** [comment]
> What needs to be normalized exactly?

See the function `NormalizeRepo`. All repo names on gitserver go through this function. The list of cloned repositories from gitserver would have gone through this.

In the repo table the name column is case insensitive, so this might not be an issue to worry about since you will be upserting based on that column.

A side note: `NormalizeRepo` is a historical artifact. In theory we could remove it and just use the casing from the repo table. Alternatively we could make it just `strings.ToLower` (after the pathname cleanup) since its case insensitive in our DB. Ideally we would switch to always using the repo ID.

**Comment by asdine** [comment]
Fixed by #11903 #11932 #12043
