### ISSUE TITLE
Failing index continues to retry without indication of problems on UI

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#11045]
- **3.16**

- **K8S 1.14 on GKE**

**Steps to reproduce**

- add repo https://ghe.sgdev.org/fervent-tu-233/inhabitedtype-ocaml-aws

- review indexing status on the repo and in the inde xserver logs

- look for the following errors:
```
error indexing ghe.sgdev.org/fervent-tu-233/inhabitedtype-ocaml-aws@HEAD=4d76d0d ││ 760b0e94f496ee49bd3f68fcb671308b8: command [zoekt-archive-index -name ghe.sgdev.org/fervent-tu-233/inhabitedtype-ocaml ││ -aws -commit 4d76d0d760b0e94f496ee49bd3f68fcb671308b8 -incremental -branch HEAD -download-limit-mbps 1000 -file_limit  ││ 1048576 -parallelism 8 -index /data/index -require_ctags http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev. ││ org/fervent-tu-233/inhabitedtype-ocaml-aws/tar/4d76d0d760b0e94f496ee49bd3f68fcb671308b8] failed: signal: killed 
```

Currently visisble on http://34.72.32.117/ 

**Expected behaviour**

There is some indication of a problem indexing the repo via the UI

**Actual Behaviour**

The UI reports the repo is still indexing with no messaging to indicate there's a problem. Additionally an alert or notification could be sent.

**Comment by tsenart** [comment]
Please triage @keegancsmith.

**Comment by keegancsmith** [comment]
We need to add some bookkeeping to sourcegraph-zoekt-indexserver which maintains some info on the last index job for a repo. Then expose that on the admin index info page. This is relatively straight forward to implement. However, we currently don't have anything which queries zoekt-indexserver in Sourcegraph, so that will be the most time consuming part. Additionally there are some complications around which replica is responsible for a shard (due to rebalancing/etc). Easiest solution is likely broadcasting to all indexservers to query this information. This would likely be useful to start exposing other functionality. I estimate a days work for someone familiar with this.

I would regard this as important polish work for a large installation. A related and important issue would be an aggregate dashboard exposing which repos are having trouble.

I think this is likely less important to get done now than other RFC-151 work.
