### ISSUE TITLE
Go: Hovercard references wrong method

### ISSUE THREAD

**Issue by mholt** [sourcegraph/sourcegraph#11089]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Firefox/macOS

#### Steps to reproduce:

I just happened upon this today, and I might be reading it wrong, so forgive me if I've overlooked something.

On this line of code: https://sourcegraph.com/github.com/caddyserver/caddy@9415feca7cf0fe14b9d881c7318be2da20b2985f/-/blob/modules/caddyhttp/reverseproxy/httptransport.go#L218:21

Hover over `RoundTrip`.

#### Expected behavior:

I should see the definition of `http.Transport.RoundTrip` in the `net/http` package.

#### Actual behavior:

It shows this in the card:

```
func (h *HTTPTransport) RoundTrip(req *http.Request) (*http.Response, error) 
```

but that is not the right RoundTrip. That is the RoundTrip that the line of code appears in; `h.Transport` is actually a `*http.Transport` type, so this RoundTrip should be referencing a function in the Go standard library.

Incidentally, the [definition link](https://sourcegraph.com/github.com/caddyserver/caddy@9415feca7cf0fe14b9d881c7318be2da20b2985f/-/blob/modules/caddyhttp/reverseproxy/httptransport.go#L93:18&tab=def) seems off, too.

**Comment by efritz** [comment]
If caddyserver does not have a valid LSIF index then it will use search to find all definitions with the same name. This is expected behavior.

One solution is to [generate and upload an LSIF index](https://docs.sourcegraph.com/user/code_intelligence/lsif) for caddyserver. Another solution is to wait until we improve our auto-indexing solution to catch it.

Keep an eye out and see if it gets better in the next milestone!

**Comment by mholt** [comment]
Okay, thanks. I was under the impression that Sourcegraph was automatically doing the indexing.
