### ISSUE TITLE
"Expand/Collapse all" button does nothing

### ISSUE THREAD

**Issue by djuarezg** [sourcegraph/sourcegraph#1111]
- **Sourcegraph version:** 2.13.3
- **Platform information:** Running on CentOS7, using Chrome extension, on Docker 1.13.1

#### Steps to reproduce:

1. Search anything on the Sourcegraph instance
2. Click on "Collapse/Expand all" button.

#### Expected behavior:

Result boxes should collapse or expand.

#### Actual behavior:

Action is ignored, nothing is reported on the console.

**Comment by sqs** [comment]
It seems to be working, but not as you expect. And it is quite reasonable to be confused. Assigned to @francisschmaltz 	to improve this UX.

Take a query like https://sourcegraph.com/search?q=repo:gorilla/mux+route. The 1st file match has a **Show 63 more matches** in the top right. You can click that to expand and see a lot more matches in the file. The **Expand all** button is like clicking the **Show N more matches** for all files.

This is how it's expected to work. Let me know if it's NOT working that way for you.

The confusion occurs, I think, because the button is always shown, even if it wouldn't do anything. And it is reasonable to assume it does something like show more of the file, not just +/- 3 lines around matches.

**Comment by djuarezg** [comment]
Indeed, it works as expected, sorry for the noise.

**Comment by sqs** [comment]
@francisschmaltz you should consider the UX here and see what we can improve

**Comment by francisschmaltz** [comment]
We could show a number of results for every file. Either display “3 matches found” or “33 matches found - show 23 more” but I fear that this would clutter the results and you wouldn’t know instantly if that was all the matches. I’ll play around with this idea before 3.0 release.
