### ISSUE TITLE
Incorrect `preview` returned in search API when using patternType: structural

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11134]
Check out this search query: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+prometheus.MustRegister%28:%5Bcollector%5D%29&patternType=structural

It includes for example this result:

![image](https://user-images.githubusercontent.com/10532611/83361629-bb374f80-a38a-11ea-94eb-cdf4fff15125.png)

If we do the same search in the [API Console](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20Search(%24query%3AString!)%20%7B%5Cn%20%20search(version%3AV2%2C%20patternType%3A%20structural%2C%20query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20lineMatches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20preview%5Cn%20%20%20%20%20%20%20%20%20%20%20%20offsetAndLengths%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22operationName%22%3A%22Search%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3A%5Egithub%5C%5C%5C%5C.com%2Fsourcegraph%2Fsourcegraph%24%20prometheus.MustRegister(%3A%5Bcollector%5D)%5C%22%5Cn%7D%22%7D), we get this result:

```json
"lineMatches": [
  {
    "preview": "prometheus.MustRegister(requestDuration)",
    "offsetAndLengths": [[1, 40]]
  }
]
```

My understanding ([the docs](https://github.com/sourcegraph/sourcegraph/blob/2a1cd8a30c72780ad884159161d0ec828cfe69a3/cmd/frontend/graphqlbackend/schema.graphql#L2819-L2825) are very fuzzy on this) is that `preview` is supposed to be the whole line of the match, while `offsetAndLengths` is 0-based  offsets from the beginning of the line with the ranges to be highlighted. This is supported by this line of code:

https://github.com/sourcegraph/sourcegraph/blob/2a1cd8a30c72780ad884159161d0ec828cfe69a3/cmd/frontend/graphqlbackend/zoekt.go#L241

It is also how it works when using `patternType: literal` ([API Console](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20Search(%24query%3AString!)%20%7B%5Cn%20%20search(version%3AV2%2C%20patternType%3A%20structural%2C%20query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20lineMatches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20preview%5Cn%20%20%20%20%20%20%20%20%20%20%20%20offsetAndLengths%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22operationName%22%3A%22Search%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3A%5Egithub%5C%5C%5C%5C.com%2Fsourcegraph%2Fsourcegraph%24%20prometheus.MustRegister(%3A%5Bcollector%5D)%5C%22%5Cn%7D%22%7D)):
```json
"lineMatches": [
   {
     "preview": "\tprometheus.MustRegister(requestDuration)",
     "offsetAndLengths": [[1, 24]]
   }
]
```

Notice how in both cases the `offsetAndLengths` starts at character 1 (i.e. the 2nd character, or the first character after the tab), but with `patternType: structural`, the preview does not contain the leading tab character (i.e. not the whole line), meaning that if the CLI wants to display `preview` and highlight the matching ranges it will fail with index out of bounds errors.

**Comment by rvantonder** [comment]
Yeah honestly `preview` is a very fuzzy spec to me. I think what I do here is just substitute the matched fragment that comby returns instead of the line, because this works out fine in the web ui, but not as an API, if the "whole line" assumption is made on the fuzzy spec that is `preview`. So this may be as simple as just including the whole first line of a match instead of the range/content of the matched fragment (and possible last line too, I suppose). I'll look into it.

Aside, but related: I'm frustrated that we have both lineMatches and the alternative highlight ranges in our API, and no true `range` support. I ran into issues supporting highlighting in src-cli, which doesn't use preview, and this whole interface seems fragmented and troublesome for first class support of multi-line matches. The idea behind 'preview' would be better supported by "context lines" around a match (so it is clear to what extent respecting line boundaries are important, which `preview` doesn't communicate), but also to make `preview` optional (i.e., the client requests how many line of context/how much preview it wants, or if it doesn't want/need one at all).

**Comment by felixfbecker** [comment]
I think it works in the web UI because the web UI doesn't use `preview` at all. It fetches the entire file content and slices the range out because it wants syntax highlighting (see #6992).

> Aside, but related: I'm frustrated that we have both lineMatches and the alternative highlight ranges in our API, and no true range support. I ran into issues supporting highlighting in src-cli, which doesn't use preview, and this whole interface seems fragmented and troublesome for first class support of multi-line matches. The idea behind 'preview' would be better supported by "context lines" around a match (so it is clear to what extent respecting line boundaries are important, which preview doesn't communicate), but also to make preview optional (i.e., the client requests how many line of context/how much preview it wants, or if it doesn't want/need one at all).

100% Agree.

A good first step would be though to make `preview` behave the same for structural search as it does for regex and literal search, to remove the inconsistency and to make our CLIs not choke on highlighting structural search matches.

> I ran into issues supporting highlighting in src-cli, which doesn't use preview

It seems to query it though:

https://github.com/sourcegraph/src-cli/blob/0cecdc89607f99a6ee000f1f9273e66603808565/cmd/src/search.go#L116

I was trying to find how it is used but it seems I can't do find-references on  anything since it's all `interface{}`:

https://github.com/sourcegraph/src-cli/blob/0cecdc89607f99a6ee000f1f9273e66603808565/cmd/src/search.go#L279

I'm curious how you do it

**Comment by rvantonder** [comment]
> A good first step would be though to make preview behave the same for structural search as it does for regex and literal search

Yep, that's why I'm fine with this being labeled as bug and will fix it.

> I'm curious how you do it

See the first code comment in https://github.com/sourcegraph/src-cli/pull/72 and others, and PR description. I basically didn't use preview because the spec is too loose (it is not a real source of truth, the description/spec doesn't say what this is) and makes it awkward to implement range. So I basically implement `range` in `src-cli` using highlight info for structural search, but expensively end up needing to fetch all the file contents to do that. Not satisfying doing it that way but I wanted it to work. I think in your case you could have done something similar, if you didn't rely on `preview` (that said I agree that it makes sense to mimic the expectation here of other search types).

**Comment by rvantonder** [comment]
@felixfbecker thinking more about it, if the only problem here is rendering, perhaps you might consider using the ranges (i.e., `offsetAndLengths` values on the file contents (I.e., you'd have to fetch those file contents, in your GQL request) to extract the context you are interested in instead, similar to what I settled on doing in `src-cli`. This is extra work for your app, but (a) abiding by this loose `preview` convention using structural search _will_ currently induce a perf hit (I will have to benchmark how bad it is, and if it is very bad, I may be reluctant to turn this "always on", and we really should make `preview` an optional parameter in the interface) and (b) you can go that direction to get accurate rendering right now without waiting for a fix.

**Comment by rvantonder** [comment]
Depends on https://github.com/sourcegraph/sourcegraph/issues/31028

**Comment by camdencheek** [comment]
Closing as done, since we now use chunk matches that have a more well-defined spec
