### ISSUE TITLE
Allow previewing of changesets for unsupported code hosts

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#11193]
Right now, if you try to create a patch on a repo that is not supported (eg because it's on GitLab or another non-supported code host), it is silently discarded:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@615077bc91a6208bb60288fedba19a0adc5d6d1d/-/blob/enterprise/internal/campaigns/service.go#L82:17

This is surprising *and* prevents someone from trying out campaigns if their code host is not yet supported.

Proposed behavior: You can create patches on any repository (that you can view). In the list of patches, a patch that is against an unsupported repository will not have a publish button and instead will have an indication that it can't be published because the code host is not yet supported. If you try to publish them via the GraphQL API, the publish operation will fail with an error (as [it does currently](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@615077bc91a6208bb60288fedba19a0adc5d6d1d/-/blob/enterprise/internal/campaigns/resolvers/resolver.go#L417)).

TODO(sqs): make a mock for this

**Comment by mrnugget** [comment]
We just discussed this in planning meeting and @eseliger is going to work on this as preparation for the new campaigns flow.

What we're going to do is to accept patches for unsupported code hosts but not allow their publication. That'll still be necessary once we have the flow in place.

Tasks:

- [ ] Move the [`IsRepoSupported`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%402ef06a3+IsRepoSupported&patternType=regexp) checks so that patches from unsupported repositories are accepted, but not _published_ (checks need to be moved to the `Service` and possibly the `ExecChangesetJobs` function)
- [ ] In `publishChangeset` mutation we should return an error
- [ ] In `publishCampaignChangesets` mutation we should skip them
- [ ] We should add a `Publishable: boolean` property to `Patch` in the GraphQL API
- [ ] We need to remove the "is supported" check in `src-cli`
