### ISSUE TITLE
progress indicator of state of indexing

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#11202]
#### Feature request description

the repositories status page is useful but when you have many repos (250k) it is impossible to tell, how far along the indexing is. (cloning for that matter too).

having some form of progress indicator would help immensely

something like:

(still to be indexed: 34,498 repos)

#### Is your feature request related to a problem? If so, please describe.

the problem is establishing when a big instance is ready to "go" and a search will span over all repos in the instance

**Comment by rvantonder** [comment]
Possibly related to https://github.com/sourcegraph/sourcegraph/issues/10899

**Comment by pecigonzalo** [comment]
I believe this is related to https://github.com/sourcegraph/sourcegraph/pull/12322

**Comment by keegancsmith** [comment]
> I believe this is related to #12322

Similiar. This issue is about creating the indexes. The linked is trying to address the webserver being slow to read in the indexes.

For the person that tackles this, this is the interface between zoekt and sourcegraph telling it what to index. It knows what a replica has indexed, cached information of what other replicas have indexed and decides what it should index. https://github.com/sourcegraph/sourcegraph/blob/c6de674fa8b71600d28f4ab0028ccad8d97795b0/cmd/frontend/internal/httpapi/internal.go#L233

**Comment by stefanhengl** [comment]
This has been implemented
