### ISSUE TITLE
Scroll within GithHub [Find reference]

### ISSUE THREAD

**Issue by anishhegde** [sourcegraph/sourcegraph#1132]
#### Feature request description

Clicking on find references should scroll to the reference in the file within GitHub.

**Comment by sqs** [comment]
We plan to support showing the references panel (at the bottom) on GitHub instead of having it navigate to Sourcegraph to show you the references. Would this satisfy you?

![screenshot from 2018-11-26 18-58-42](https://user-images.githubusercontent.com/1976/49055683-53a8ae80-f1ad-11e8-980e-c290d53d3eb5.png)
