### ISSUE TITLE
`archived` filter showing up in "repositories" row on search results page

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11355]
I've been seeing this for a few days, just getting around to filing.

![image](https://user-images.githubusercontent.com/5589410/84066960-8b380f80-a97b-11ea-9bf4-03596dd6eef8.png)

Reproducible at https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph+auth&patternType=literal

**Comment by rvantonder** [comment]
@dan I introduced this filter to repositories because it calculates and shows the number of repositories excluded (we can't do that for the Filters above I think, and this extra info is important, see issue https://github.com/sourcegraph/sourcegraph/issues/9928). The PR that introduced this was https://github.com/sourcegraph/sourcegraph/pull/10624.

It's possible we can group this chip with the Filters row, but it needs to be prioritized before others in that case (there has been continual friction about surfacing missed forks and archived repos). I'm hesitant because moving it to Filters can be more easily missed. 

CC @christinaforney @rrhyne @slimsag 

Also, sorry it took long to see this, please just assign these issues to me or someone on search as a best guess.
