### ISSUE TITLE
LSIF tree data query for repository root returns null

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11490]
[API Console](https://sourcegraph.com/api/console#%7B%22query%22%3A%22%23%20Type%20queries%20here%2C%20with%20completion%2C%20validation%2C%20and%20hovers.%5Cn%23%5Cn%23%20Here's%20an%20example%20query%20to%20get%20you%20started%3A%5Cn%5Cnquery%20%7B%5Cn%20%20repository(name%3A%20%5C%22github.com%2Fsourcegraph%2Fsourcegraph%5C%22)%20%7B%5Cn%20%20%20%20commit(rev%3A%20%5C%227442c3a0dd71fad0c9c0b493192e533027e154fa%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%5C%22%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22lsif-eslint%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D)

```graphql
query {
  repository(name: "github.com/sourcegraph/sourcegraph") {
    commit(rev: "7442c3a0dd71fad0c9c0b493192e533027e154fa") {
      tree(path: "") {
        lsif(toolName: "lsif-eslint") {
          diagnostics {
            totalCount
          }
        }
      }
    }
  }
}
```

The GitHub action ran for that commit, but the result is always:

```json
{
  "data": {
    "repository": {
      "commit": {
        "tree": {
          "lsif": null
        }
      }
    }
  }
}
```

If I remove the `toolName` filter, it still shows 0 diagnostics:

```json
{
  "data": {
    "repository": {
      "commit": {
        "tree": {
          "lsif": {
            "diagnostics": {
              "totalCount": 0
            }
          }
        }
      }
    }
  }
}
```

**Comment by efritz** [comment]
Ok, good catch! This isn't related to toolName, though, but the roots.

If you have a path like `tree(path: "web/src") {` then it will show the correct results. The issue is that we currently always look for the bundle that _contains_ the given path (which always worked because we only queried exact files before). Now we need all bundles that _intersect_ the given path, so we have to query multiple bundles.

This shouldn't be a huge issue to fix.
