### ISSUE TITLE
monitoring: provisioning alerts not consistently applied

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#11571]
- **Sourcegraph version:**  dot-com, k8s
- **Platform information:** 

#### Steps to reproduce:

1. go to https://sourcegraph.com/-/debug/grafana/d/syntect-server/syntect-server?panelId=2&fullscreen&orgId=1 , see provisioning alert there (currently named `80%+ or less than 30% container cpu usage total (1d average) across all cores by instance`)
2. go to https://sourcegraph.com/-/debug/grafana/d/frontend/frontend?panelId=2&fullscreen&orgId=1 , no such alert is defined for `frontend`

#### Expected behavior:

https://github.com/sourcegraph/sourcegraph/pull/11082 adds provisioning warnings like the one described in step 1 above, that every service with the provisioning dashboard should have. each service should get 6 alerts (1x 5m alert, 2x 1d alert, for each of memory, cpu)

#### Actual behavior:

* in dot-com, it seems quite a few containers don't have this alert
   * ~20 `provisioning.*` alerts defined: https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22count(alert_count%7Bname%3D~%5C%22provisioning.*%5C%22%7D)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D (this seems to fluctuate)
* in k8s, it seems more do, but a few still don't
   * 56 `provisioning.*` alerts defined: https://k8s.sgdev.org/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22count(alert_count%7Bname%3D~%5C%22provisioning.*%5C%22%7D)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D
* sourcegraph.sgdev.org (a `sourcegraph/server` deployment from what I understand) has more provisioning alerts defined than both dot-com and k8s
   * 84 `provisioning.*` alerts defined: https://sourcegraph.sgdev.org/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22count(alert_count%7Bname%3D~%5C%22provisioning.*%5C%22%7D)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D (this seems like it should be the right number, at 6 alerts per service)

cc @slimsag

**Comment by slimsag** [comment]
From a quick glance everything looks like it should be working, that's odd

If you port-forward prometheus, you can access its web UI and see if any of these rules are failing from there IIRC

I'll take a closer look tomorrow

**Comment by bobheadxi** [comment]
I'm seeing a lot of:

```
vector contains metrics with the same labelset after applying rule labels
```

each rule has at least a unique `name` and `service` label combination however 🤔 don't see a clear pattern here either (some services have all 8 of the provisioning rules fail, in some services a few succeed and the rest fail)

**Comment by bobheadxi** [comment]
Some comments in [this stackoverflow post](https://stackoverflow.com/questions/57788605/prometheus-rate-on-series-by-regex) suggest that this might be because multiple series have their non-`__name__` labels be identical. This would explain why the `sourcegraph/server` deployment has the full 84 alerts - no cAdvisor metrics are collected in the single-server deployment.

However, it appears we don't do set the `__name__` and we always do set a `name` label, which is always unique (in the case of the new alerts with two bounds, each is suffixed with either `_low` or `_high`). Also if this were the case, *all* the alerts should fail to be applied, which doesn't seem to be what is happening

Also, I checked the dot-com query this morning and it seems a number of the provisioning alerts have just resolved themselves (though it's still not the full 84):

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/23356519/85237815-2214c980-b45c-11ea-97e4-14c78e49207b.png">

I wondered if it might be that the change in how [we aggregate the cAdvisor metrics](https://github.com/sourcegraph/sourcegraph/pull/11082/files#diff-eda4b3c8dbf5224cd0c08aff6fc7fba5) caused duplicate series to appear, but it's not just the `cpu` alert that is failing, so I'm don't think that's it

**Comment by bobheadxi** [comment]
Running one of the failing alert rules seems to return the results I expect:
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/23356519/85238042-cb0ff400-b45d-11ea-8518-35da6f93f15b.png">

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/23356519/85238015-9dc34600-b45d-11ea-972c-f760c009e0b0.png">
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/23356519/85238021-a7e54480-b45d-11ea-8a20-c154b88ef512.png">

**Comment by bobheadxi** [comment]
## Attempted fixes

will update this comment

* `sum by (name)` - `name` is the only label on these cadvisor metrics, and they look unique, but I figured this might help. manually edited + reloaded config on k8s-dogfood and it doesn't do the trick 
<img width="1774" alt="image" src="https://user-images.githubusercontent.com/23356519/86336300-46557f00-bc82-11ea-85c5-caaefe407a95.png">

**Comment by slimsag** [comment]
@bobheadxi Sorry it took me so long to look at this, I see what the problem is.

Take this query as an example:

```
clamp_max(clamp_min(floor(((((cadvisor_container_memory_usage_percentage_total{name!~".*(_POD_|_jaeger-agent_).*",name=~".*frontend.*"}) / 99) or on() vector(0)) >= 0) or on() vector(1)), 0), 1) or on() vector(1)
```

When ran in the Prometheus UI, it returns the following (all of which have unique names):

![image](https://user-images.githubusercontent.com/3173176/86696775-9f931a80-bfc2-11ea-8835-4f4c66f1de90.png)

But in the web UI the rule for it is failing:

![image](https://user-images.githubusercontent.com/3173176/86696836-af126380-bfc2-11ea-8ceb-671c642ca1b3.png)

The reason for this is because Prometheus _rules_ (which is what this is) add the specified `labels` to the queried vector, defining a new metric entirely.

Our original query returned 6 unique series, but only because `name` is unique. Once it gets replaced with the new value `container_memory_usage` they are no longer unique and hence the error. The reason your fix works is because it introduces _another_ label `container` which is unique and not overridden by the Prometheus rules' `labels`.

Now on to why this really happens:

I previously thought `name` (which is what all of these metrics are supposed to aggregate on) used to be _per-service_ when meant no queries we had ever returned more than one series so we didn't hit this - or so I thought. It turns out I was wrong and `name` wasn't per-service, but rather per-container; hence we hit into this. This was a really ill-thought-out implication of allowing alerts to be per-container in some instances but not others.

I would propose the following:

1. Remove `instance` from this docs page: https://docs.sourcegraph.com/admin/observability/metrics_guide - nobody uses it today and interacting with it is frankly _very weird_ (some metrics are per-service despite having an `instance` label, others are not, etc.)
2. Eliminate per-container / per-replica / per-pod labels from the final alert_count rule calculation, e.g. instead of the innermost division reading:

```
cadvisor_container_memory_usage_percentage_total{name!~".*(_POD_|_jaeger-agent_).*",name=~".*gitserver.*"}) / 99
```

Which produces:

![image](https://user-images.githubusercontent.com/3173176/86698577-47f5ae80-bfc4-11ea-8548-c584dee79fd3.png)

Just take the max (so if any one is firing, we signal that):

```diff
-cadvisor_container_memory_usage_percentage_total{name!~".*(_POD_|_jaeger-agent_).*",name=~".*gitserver.*"}) / 99
+max(cadvisor_container_memory_usage_percentage_total{name!~".*(_POD_|_jaeger-agent_).*",name=~".*gitserver.*"}) / 99)
```

![image](https://user-images.githubusercontent.com/3173176/86698690-60fe5f80-bfc4-11ea-8454-af541ca7c443.png)

Let me know if this makes sense or not!

**Comment by bobheadxi** [comment]
@slimsag does this involve changing how each of our alerts are generated? From what I understand, this `max` will have to be added here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@distribution/provisioning-alerts-fix/-/blob/monitoring/generator.go?utm_source=VSCode-1.1.0#L661:25

**Comment by slimsag** [comment]
I am pretty sure (but didn't explicitly test) that we can declare it here by wrapping `alertQuery` in `max(...)`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@distribution/provisioning-alerts-fix/-/blob/monitoring/generator.go?utm_source=VSCode-1.1.0#L940

**Comment by bobheadxi** [comment]
Yeah that would be cleaner - just wanted to make sure we wanted to apply this change to _all_ of our alerts :)

**Comment by slimsag** [comment]
Yes, correct - it should be applied to all alerts in order to remove this issue + the ambiguity I noted earlier about alerts sometimes being per-container/per-replica and sometimes not
