### ISSUE TITLE
Use paginated search in src-cli to fetch repositories for campaigns

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#11587]
After running into https://github.com/sourcegraph/sourcegraph/issues/10540 and experimenting with alternate forms of querying in https://github.com/sourcegraph/src-cli/pull/226 I think we should investigate whether paginated search can solve our problems.

I want to do a spike to see whether it solves our problem and could work for us in campaigns, because the known limitations of the current paginated search implementation don't seem relevant to campaigns (since we're not (yet) interested in file matches, but only want repositories).

Docs:
- https://docs.sourcegraph.com/api/graphql/search#sourcegraph-3-9-experimental-paginated-search
- https://docs.sourcegraph.com/dev/architecture/search-pagination

**Comment by eseliger** [comment]
Report: 

I don't think this is a viable/useful solution, unless we have big trouble with the size of the response bodies. It is only possible to use queries with `type:file` (which might be okay for the beginning, I started by adding a detection for that sequence in the query and only use pagination in that case, and wanted to encourage users to add that type where possible to decrease search result times). But as measurements with `htop` and the documentation of the pagination implementation reveal, the memory consumption on the server-side is not reduced in most cases. Given that this is the main driver here, I think we should abandon that approach for now, as it's kinda brittle with only one explicit type working, it doesn't reduce load in many cases, but even have the load prevail for a much longer period `(N - m) * P` where `P` is page count, `N` is total query time without pagination and `m` is the small performance gain you get when the results of the page aren't scattered until the end.

**Comment by mrnugget** [comment]
> I don't think this is a viable/useful solution, unless we have big trouble with the size of the response bodies.

The response body size and/or memory consumption on the sever aren't our only concern. We also want to _not miss results_ and since the default search can time out and doesn't guarantee a complete list of results, pagination might be an option.

Does your verdict change when taking these two constraints into account?

> It is only possible to use queries with `type:file`

Right now, or in general?

> as it's kinda brittle

Why is it brittle?

**Comment by eseliger** [comment]
> Does your verdict change when taking these two constraints into account?

The complete list constraint is only not ensured right now when there are more than the hard-coded `999999` results. In that case, it would work, but would basically take forever to paginate to that result (unless we set the `first` value to something _really_ high). And the problem with the search timing out is still not ensured to not happen, because it still needs to compute much more than just a `100` results.

> Right now, or in general?

Right now, not sure if it would be impossible, but it isn't implemented at this time.

> Why is it brittle?

First, we don't encourage customers to not use it for production, but more importantly it is hard to choose the right value for `first`, and might cause a lot of duplicated computations over the page requests, which actually puts the pressure on the backend for longer. https://docs.sourcegraph.com/api/graphql/search#choosing-the-right-per-page-value. So even if we find a good value for testing, it might be a very bad value for some other queries.

**Comment by mrnugget** [comment]
Thanks!

> The complete list constraint is only not ensured right now when there are more than the hard-coded `999999` results.

Is it? I assumed that even with `count:999999` we have unstable result sets that change from search to search.

If we, say, use `count:999999` and `timeout:10m` — do we get all results? If the answer to that is "yes", then I agree that we can defer looking deeper into paginated search.

**Comment by eseliger** [comment]
When there are more than that amount of matches, it can become a problem. But it pretty much already is a problem at that point because that search query will take a super long time and need lots of memory 🤔 I tried some big queries locally and wanted to grab 1000 results at once, and it pretty much takes the same time per page as the whole query does and still consumed around 11GB of memory. So as far as I understand that API, it can take up to 10,000,000/1,000 = 10,000 times as long while still consuming that memory, so not sure we do get any quick wins here which apply to _all_ queries. I think as soon as queries get that difficult, we should rather encourage users to simplify their queries for now, until we can find a way where we maybe don't even need to query the matches but can only query the repos with matches(?)
It's fairly easy to implement pagination, but I didn't get any promising results out of it yet. We could try to dig deeper here, but I'm not sure what wonders to expect, especially given that customers would need to learn to use the `type:file` filter where possible (but not when impossible) 🤔

**Comment by mrnugget** [comment]
> until we can find a way where we maybe don't even need to query the matches but can only query the repos with matches(?)

That's the _other_ idea we had, right? That we do a search but have something like a "onlyReturnUniqueRepos: true" parameter, right?

> We could try to dig deeper here, but I'm not sure what wonders to expect, especially given that customers would need to learn to use the `type:file` filter where possible (but not when impossible) 🤔

I think it's fine. But it would be great if you could try to summarise your findings in this ticket here in a condensed form that answers the following questions:

1. Why are we in campaigns interested in paginated search?
2. What did we do to evaluate it?
3. What was the outcome?
4. Based on the outcome, does it make sense for campaigns to switch to paginated search?
5. If not, what would it take for paginated search to be a viable option?

That would give us something we can link and refer to and possibly hand to the search team as a bit of feedback and inspiration for future improvements. After that, we can close the ticket.

**Comment by eseliger** [comment]
> That's the other idea we had, right? That we do a search but have something like a "onlyReturnUniqueRepos: true" parameter, right?

Yes, exactly.

## Report

### Why are we in campaigns interested in paginated search?
In order to determine the matching repositories for a scopeQuery, we have to iterate over all search results and get the repository of that match. That can potentially yield hundreds of thousands and even more results, that we all need to parse and query from the search api, which often results in memory problems or timeouts. To reduce pressure, we wanted to investigate if the paginated search can help us here, by, say, only querying a 1000 results at a time.

### What did we do to evaluate it?
Implemented a prototype in src-cli, evaluated the following documentation:
- https://docs.sourcegraph.com/api/graphql/search#sourcegraph-3-9-experimental-paginated-search
- https://docs.sourcegraph.com/dev/architecture/search-pagination

and took performance/memory measurements on the search, to see whether it has a positive impact.

### What was the outcome?
Turns out paginated search doesn't work for all kinds of search queries. Hence, we need to educate people to use `type:file` as much as possible, and need to fall-back to non-paginated search for all other queries.
In addition, the compute overhead for pagination can be quite high apparently, causing the same memory consumption and much higher overall compute time, given we need to fetch many pages.

### Based on the outcome, does it make sense for campaigns to switch to paginated search?
Not at this point in time. It would only work when a user searches using `type:file` and then it would still require lot's of resources still, making it not an easy win in my opinion. Tweaking the per page parameter to a performant value can also depend on the search query, which makes it hard to come up with a generalized solution. If the search API were to return the repos that matched, we would likely not need that approach anyways.

### If not, what would it take for paginated search to be a viable option?
(This is from the perspective of someone who only read the above mentioned documentation, but didn't dive into the code)
- Support for all search query types would be helpful.
- Less pressure on the search backend, that ideally only has to compute the amount of results that we actually ask for.

--- 

Given this was a spike, I am going to close this, as the spike work has been done.
