### ISSUE TITLE
Broken godoc symbols links

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1162]
#### Steps to reproduce:

1. Visit a Go package on godoc.org, try to click the "Uses" buttons (e.g. any links in https://godoc.org/github.com/gorilla/websocket)
2. Hit a 404 (e.g. https://sourcegraph.com/go/github.com/gorilla/websocket/-/Conn/Subprotocol)

This doesn't affect all Go libraries. I'm not sure what the difference is between gorilla/websocket and other ones that work (e.g. https://godoc.org/github.com/aws/aws-sdk-go/aws)

**Comment by slimsag** [comment]
Probably the code path at fault is that workspace/symbols does not match up with something we expect for some reason: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/go_symbol_url.go#L65-70

**Comment by sqs** [comment]
@chrismwendt 	or I are committed to changing this code path for 3.0-preview anyway, so we will fix this issue.

**Comment by slimsag** [comment]
@chrismwendt @sqs It looks like this is now happening for _all_ godoc.org Uses links. I am guessing that some were cached, and any hitting the new lang-go service are failing. Once that service was redeployed, all are now failing (the logs look fine though).

**Comment by sqs** [comment]
OK, I will try to come up with this fix ASAP then.

**Comment by sqs** [comment]
Actually, the problem was that lsp-proxy was down (see https://sourcegraph.slack.com/archives/C08JA8Q1H/p1543485706242800?thread_ts=1543484155.240700&cid=C08JA8Q1H). Now that it is back up, all of the godoc.org links I've tried are succeeding and I don't see any errors (except for the one linked above, https://sourcegraph.com/go/github.com/gorilla/websocket/-/Conn/Subprotocol, which is still a valid problem--but thankfully less widespread).

**Comment by slimsag** [comment]
Gah, sorry I didn't catch this :/

**Comment by sqs** [comment]
Reassigning back to @chrismwendt 	too given that this is not as urgent

**Comment by sqs** [comment]
This was fixed
