### ISSUE TITLE
Diff query for unknown revision is slow

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#11654]
This is a follow up to https://github.com/sourcegraph/sourcegraph/issues/11466.

A team inside the customer relies on the GraphQL endpoint for languages in a repo to keep track of this information. They would like to ensure the results are no more than an hour stale. One possible way (not necessarily the best) of accomplishing this is to make the cache TTL configurable.

@aisbaa can you let us know the urgency level so we can prioritize accordingly?

**Comment by aisbaa** [comment]
It is quite urgent. It impedes security team work quite a bit.

**Comment by slimsag** [comment]
Just to make sure I understand the issue here: the problem is that the repository inventory results are _too stale_ - not that their computation is exepensive/problematic and we're trying to cache them due to that, right?

I am asking because I see we do have an unbounded Redis cache in place for these results (i.e. once they are computed, they never expire).

**Comment by aisbaa** [comment]
>  the problem is that the repository inventory results are too stale - not that their computation is exepensive/problematic

Staleness is not an issue at the moment.

The issue is that sourcegraph-frontend crashes with OOM or exit 137. To resolve OOM I will allocate more memory (increase limit value from 24G to 32G and increase frontend count from 3 to 6).

I am suspecting language query to be the culprit, because this started after upgrading to 3.16.2 (ref: #11466). But I'm not 100% sure, because none of long requests are logged to jaeger. In last 24hours there is no request in jaeger that takes more than 1s. Which is bizarre because in ELK I see this:

<img width="833" alt="Screenshot 2020-06-24 at 11 05 22" src="https://user-images.githubusercontent.com/82692/85519828-c50b4600-b60a-11ea-954a-824ad0795679.png">

Slow query is request that takes 10s and more. Each bar is slow query count over 30min.

I'm asking to cache language query results for an hour or more, because:
1. the issue started after upgrade to 3.16.2
2. language query is computationally expensive, especially for large repos
3. appsec team hits this query every time it there is a push to master
4. I have no other options atm

**Comment by ryanslade** [comment]
Which version did you upgrade from? It'll help to narrow down the changes

**Comment by aisbaa** [comment]
Last time it was from 3.16.1 to 3.16.2. Though now I see the same crash pattern on 3.16.1.

**Comment by ryanslade** [comment]
The language statistics are cached per git tree which means that after a commit we'll only need to recompute statistics for changes since the last commit.

Can you confirm whether the query returns at all?

**Comment by aisbaa** [comment]
I found a new clue

Error: `"graphql: revision not found: REPO_NAME_REDACTED@COMMIT_HASH_REDACTED~^0"`

Query from trace:
```
query GetDiffBasedOnCommitHash($repoName: String!, $commitHashPrev: String!, $commitHash: String!){
	  	repository(name: $repoName) {
			comparison(base: $commitHashPrev, head: $commitHash) {
				fileDiffs {
					rawDiff
					nodes {
						oldPath
...
```

I think this is the full query (form code)
```
	query GetDiffBasedOnCommitHash($repoName: String!, $commitHashPrev: String!, $commitHash: String!){
	  	repository(name: $repoName) {
			comparison(base: $commitHashPrev, head: $commitHash) {
				fileDiffs {
					rawDiff
					nodes {
						oldPath
						newPath
						hunks {
							body
						}
					}
				}
			}
	  	}
	}
```

Jaeger traces disappear before I can export it.

**Comment by ryanslade** [comment]
I'm going to look into the performance implications of doing a `GetDiffBasedOnCommitHash` query when the revision doesn't exist.

**Comment by ryanslade** [comment]
I can confirm that this is a lot slower than expected and will continue to look into the root cause.

**Comment by ryanslade** [comment]
The slowdown is caused by needing to fetch from the remote when the revision is missing. 

I'm checking internally as to whether it is safe to change this default behaviour. If not, we may be able to add an option to override it.

**Comment by ryanslade** [comment]
@aisbaa I'm going to update the issue name as the root cause doesn't appear to be related to the language query

**Comment by ryanslade** [comment]
I don't think we're going to be able to change the default behaviour of our `comparison` endpoint to NOT attempt to fetch missing revisions as this change in behaviour may cause problems for other users of the API.

We have a few options:

1. Add a parameter to the API to opt out. This is the most direct route but would require the bad queries to be altered.
2. Add a config option to specifically change the behaviour of the `comparison` endpoint. My concern here is that it adds another variable that will make debugging issues in future more difficult. It could also cause unforeseen issues for other users of the API at the customer.
3. Stop the bad queries at the source

3 would be preferable, @aisbaa did you have any luck tracking it down?

**Comment by aisbaa** [comment]
I really like second option. To be honest I like any option that removes git fetch when sha is not found. But let me check with affected team.

**Comment by aisbaa** [comment]
@ryanslade we will look into **option 3** for this case. Despite that we really want **option 2** implemented, because it just matter of time when the next bot will start misusing API.

In this case sourcegraph went down multiple times over 2 days. So in general case I would like that sourcegraph would do as little as possible to return API call.

**Comment by beyang** [comment]
My 2c on this:

1. In general, I think it is better to have an explicit parameter to change the behavior of a request being made, rather than a "global" config parameter that affects behavior implicitly. As @ryanslade mentioned, this makes issues harder to diagnose and debug.
2. No request to Sourcegraph should take down the entire site. There will always be users trying to do new things with our API and they and @aisbaa shouldn't have to worry about which requests might take down the site.

Could the fix for this address both? E.g.,
* Add a parameter to the GraphQL endpoint to opt-in or out of blocking on fetching the revision.
* Regardless of what the parameter value is, the request shouldn't bring down the entire site. It is better to return an error as a response than to compromise the entire site, no matter what the request is.

**Comment by keegancsmith** [comment]
Some more 2c: Our APIs make the general assumption that if you are asking for a full SHA for a repo, that full SHA exists. eg its hard for a correct client to make up a SHA. So we attempt to fetch it if missing so everything works. The most visible example of this is when viewing a PR with our browser extension, if we don't have the commit then fetch. This is fairly common, since people generally browse a PR soon after the code is pushed. We do this transparently to the client (except for the fact the request is slower).

I agree this leads to these sorts of cases (which has bitten us internally before). It would be great if we could make all clients handle retries with an explicit endpoint for saying I really do think this commit exists pls fetch. But that is a long term ask.

As for disabling our fetch on missing behaviour, that would likely break browser extension / etc. Additionally if you have configured `disableAutoGitUpdates: true` we rely on this behaviour to update repos.

**Comment by ryanslade** [comment]
Our plan to resolve these kinds of issues in future is to enable client rate limiting on our side. It's on our roadmap but we don't have a concrete time frame for it yet.

@aisbaa Are you happy if we close out this specific issue with the plan to add rate limiting in future?

**Comment by aisbaa** [comment]
In general I agree with what was set above. Rate limiting sounds like a great idea.

> As for disabling our fetch on missing behaviour, that would likely break browser extension / etc. Additionally if you have configured disableAutoGitUpdates: true we rely on this behaviour to update repos.

We kept git auto updates`disableAutoGitUpdates: false`. In addition to that we also use repo refresh HTTP endpoint, in last 24h there was 132k calls to this endpoint.
 
- I would be willing to get fast 404 in case sha is not on sourcegraph and wait for sourcegraph to catch up.
  - In case 404 was received by UI - then UI can issue request to fetch for the repo.
  - In case 404 was received by service that consumes API - then it is upto service to decide what to do.
- In addition, if we want to keep current behaviour for human API users, it is possible to recognise if API caller is a human or bot. Simplest way is just to use user agent header

<img width="1370" alt="Screenshot 2020-06-26 at 12 09 44" src="https://user-images.githubusercontent.com/82692/85840961-126fea80-b7a6-11ea-984e-261492f6efe6.png">

**Comment by aisbaa** [comment]
> @aisbaa Are you happy if we close out this specific issue with the plan to add rate limiting in future?

Rate limiting is great idea and I would love to see it in sourcegraph.

Despite that I would really like sourcegraph to respond fast for this request. `git show` is consistently less than 15ms and `git diff` is consistently less than 25ms for non existing shas. Waiting to fetch non existing shas only increases load on all 3 parties: client, gitolite and sourcegraph servers without good reason.

I agree with @keegancsmith that non existing sha usually means that PR that sourcegraph did not have a changes to fetch it.

Would it be possible to get a quick fix for now so that we would not need to waste resources on sourcegraph, gitolite and appsec services?

I'm fine with option to disable fetch when SHA is not found. Or better solution would be not to fetch repo if user agent is curl or go-http-client.

**Comment by ryanslade** [comment]
Unfortunately I don't think we'll be able to do it via user agent without potentially breaking other users of the API.

Would option 1 from my previous comment be a suitable compromise? That's something we could safely ship without the risk of breaking any other consumer.

> Add a parameter to the API to opt out. This is the most direct route but would require the bad queries to be altered.

**Comment by aisbaa** [comment]
Adding parameter to the query to opt out of git fetch would be good, it would allow to my to create PR for service owner. I'll take a look at nginx [rate limiting](https://www.nginx.com/blog/rate-limiting-nginx/)

**Comment by ryanslade** [comment]
Great, I'm looking into this today

**Comment by ryanslade** [comment]
@aisbaa The two issues above should help with your issue.

If we are able to get a patch release ready for the middle of next week would that be acceptable?

**Comment by slimsag** [comment]
Update: just saw the earlier comments about how high-priority / urgent this is, we will ship this in a patch ASAP (like tonight or tomorrow)

**Comment by aisbaa** [comment]
This is great, thank you. I'll push the team to update their query right after this fix is released.

**Comment by uwedeportivo** [comment]
this is going out with 3.17.3 today

**Comment by uwedeportivo** [comment]
3.17.3 is released

**Comment by beyang** [comment]
@aisbaa has this issue been resolved for you?

**Comment by aisbaa** [comment]
@beyang I've upgraded and tested 3.17.3-1, it works as expected. Thank you team!

**Comment by ryanslade** [comment]
Great, glad to hear it 😄
