### ISSUE TITLE
Version contexts don't accept multiple revisions for the same repository

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#11668]
- **Sourcegraph version:** 3.16.2, k8s.sgdev.org
Context: https://sourcegraph.slack.com/archives/CHEKCRWKV/p1592867180281100?thread_ts=1591816872.229400&cid=CHEKCRWKV

#### Steps to reproduce:
K8s repro:
1. Go to https://k8s.sgdev.org/search?q=3.16&patternType=literal&c=3.16+and+17
2. See error `text search failed: not yet supported: searching multiple revs in the same repo`

#### Expected behavior:

The search should work. For example, on Sourcegraph.com we can search over the [3.16 and 3.17 branches of our repo](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%403.17:3.16+test&patternType=literal) using this query: `repo:^github.com/sourcegraph/sourcegraph$@3.16:3.17 3.16`

#### Actual behavior:

We get an error saying we can't search the same repo at multiple revs

**Comment by keegancsmith** [comment]
@dadlerj I'm not sure why this worked when I tested before, but I can't work out what changed in the code to break it. The fix was always enabling the experimental feature `{ "experimentalFeatures": { "searchMultipleRevisionsPerRepository": true } }`. The workaround for the customer is to enable that feature.
