### ISSUE TITLE
Resolving repo by clone URL fails in production with RepoLookup: {Repo: ExternalRepo:<nil>}: http status 500

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1166]
https://sourcegraph.com/api/console#%7B%22query%22%3A%22query(%24cloneUrl%3A%20String!)%20%7B%5Cn%20%20%20%20repository(cloneURL%3A%20%24cloneUrl)%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22cloneUrl%5C%22%3A%20%5C%22https%3A%2F%2Fgithub.com%2Fgorilla%2Fmux%5C%22%5Cn%7D%22%7D

Error:
```
RepoLookup: {Repo: ExternalRepo:<nil>}: http status 500
```

**Comment by felixfbecker** [comment]
This is blocking https://github.com/sourcegraph/lang-typescript/issues/8

**Comment by nicksnyder** [comment]
I don't anticipate having time to investigate this in the next 24 hours.

**Comment by slimsag** [comment]
The trace indicates that `reposource.CloneURLToRepoName(*args.CloneURL)` is returning an empty string and no error.

The function does that when there are no registered repo sources in the configuration which can interpret the URL: https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/pkg/conf/reposource/common.go#L71

@beyang thoughts on the above since you wrote the package? what is a good solution here?

@felixfbecker warning: I will not have time to look into this further until at least Mon.

**Comment by felixfbecker** [comment]
Thanks, I added a check for the empty string in https://github.com/sourcegraph/sourcegraph/commit/8821f9653a7c4959a3a93dff59853caa0b62ddaa, but it will not fix the issue of course.

So does prod not have configured "repo sources" for GitHub and Gitlab? @beyang

**Comment by beyang** [comment]
PTAL: https://github.com/sourcegraph/sourcegraph/pull/1180
