### ISSUE TITLE
license check failing in CI: mdi-react

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#11866]
Dependencies that need approval:
Yarn, mdi-react, 7.3.0, "(MIT AND OFL-1.1)", https://github.com/levrik/mdi-react, "Not approved"

Getting red on all PRs. Not sure when this changed. cc @sourcegraph/web

**Comment by bobheadxi** [comment]
Yeah this is strange, that dependency hasn't changed since #11321 - will dig into it tomorrow

https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+type:diff+mdi-react&patternType=literal

<img width="907" alt="image" src="https://user-images.githubusercontent.com/23356519/86250230-e78cf880-bbe2-11ea-9f58-f4cfe9d31fae.png">

**Comment by bobheadxi** [comment]
For the time being I don't think it's a required check, hopefully wont block anyone

**Comment by keegancsmith** [comment]
can you just remove the check until you look into it?
