### ISSUE TITLE
search: structural search disentangling from zoekt

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#11902]
@rvantonder 

Context: I've been adding support for branches in indexed search. It's the first time I've properly had to page into my head the zoekt related code in graphqlbackend for a while. I've noticed ways to reduce code, and this issue is about a potential restructuring of structural search's integration with Zoekt.

I really want to remove `zoektSearchHEADOnlyFiles` and instead just rely on `zoektSearchHEAD`. The motivation is:

1. The logic to associate branches to results is slightly tricky and I don't want to duplicate it.
2. You only need to specify `type:file` to zoekt and it will search just files. You don't need to adjust anything else.

Please correct me if I am wrong, but the main complication from what I can tell is:

1. We do a zoekt query followed by searcher with structural search query and modified list of file patterns.
2. The zoekt query can be run twice, the second time with a more permissive regex.

Proposal:

Do the two queries in `searchFilesInRepos`. You create a copy of `search.TextParameters` for zoekt and update `Pattern` to be the structural search regex. You can then do a second search if there are not enough results. To only get file matches back we will get zoekt to have `type:file` in the query it builds. This will be more efficient than what is done today.

Does this sound reasonable? I'm happy to implement this. Just want to check if there is some other trickery I am not aware of.

**Comment by keegancsmith** [comment]
Realised there are a few changes needed to support branches in structural search. Has baked in "HEAD" in quite a few places. So punting on structural search + multi for now: https://github.com/sourcegraph/sourcegraph/issues/11906

However, solving this helps us get closer to supporting it :)

**Comment by rvantonder** [comment]
> I really want to remove zoektSearchHEADOnlyFiles and instead just rely on zoektSearchHEAD.

Agree. It'd be nice if the zoektSearchHEAD logic could work as a kind of API call. On point (2) of motivation:

> You only need to specify type:file to zoekt and it will search just files. You don't need to adjust anything else.

This is strictly a "nice to have" (and we should use it), but it is not the reason or constraint on how things evolved to the current state.

> Please correct me if I am wrong, but the main complication from what I can tell is...

The main reason is (2): there was no elegant way to rerun a modified Zoekt query a second time, where you would only rerun the query depending on the results of the first query. The thinking went like this:

> 1. I need to rerun a second Zoekt query depending on the results (I reference the change below, keep reading :-))

> 2. ZoektSearchHEAD doesn't return the values I'm interested in to rerun the query (I can't easily lift the logic into `searchFilesRepos` without changing ZoektSearchHEAD's return types. If those return types change, I have to refactor all the other code that relies on ZoektSearchHEAD results.)

> 3. Well, then I shall add the logic inside ZoektSearchHEAD itself. I try and this is getting super icky, I can't tell what I'm doing anymore. See the comment: https://github.com/sourcegraph/sourcegraph/pull/8372/files#r449292930

> 4. Pull out that logic to attempt a self-contained use of Zoekt where I can run subsequent calls depending on the result. This is the current state.

You say: `Do the two queries in searchFilesInRepos.` I support the proposal. I couldn't manage to do this straightforwardly back then :'( I'm not sure how you would tackle it, but my take would be to split `ZoektSearchHEAD` into a pipeline of individual functions. The individual functions could simply be called in sequence for existing textsearch/symbol search, but for structural search, it would serve as a set of functions that expose the raw values/responses (and inputs) that I need to drive the logic implemented in https://github.com/sourcegraph/sourcegraph/pull/8372/files#r449292930. 

So yeah, the part about `type:file` is a nice optimization that I didn't act on, but not the fundamental issue. I just named the modified function `ZoektSearchHEADOnlyFiles` because I needed to distinguish it. It may as well have been `ZoektSearchHEADForStructuralSearch`.

> Does this sound reasonable? I'm happy to implement this.

Sounds totally reasonable, just likely difficult or time consuming. Happy to help or I can block out time to attempt what I mentioned above.

---

These changes might be informative:

- [Step-by-step commits](https://github.com/sourcegraph/sourcegraph/commits/71fbfd2b91a34a29465a70148760fbc3ca8a11c9/cmd/frontend/graphqlbackend/search_structural.go) that show where `ZoektSearchHEADOnlyFiles` starts off being duplicated and then diverges from `ZoektSearchHEAD`

- The PR that motivated the above changes (this is the one I reference in the comments): #8372

**Comment by keegancsmith** [comment]
I just realised that in a multi branch world we don't tell Structural search to just search HEAD since we use RepoSet just for it. This is a bug that I'll fix today.

**Comment by rvantonder** [comment]
I've been doing some experimenting off the side and I think I might just pull out the dependency to use Zoekt for filtering files altogether. Basically, I find that:

- I need to run a regex to filter candidate files. Using just the constant search terms, without ordering (i.e., as a trigram look up to Zoekt using `and` queries) results in too many hits. I know this from trying things prior. The ordering on terms in a regex significantly reduces the set of candidate files significantly.

- New information I experimented with locally: ripgrep is faster at running the regexes that I currently send off to Zoekt. Implication: maybe I should use ripgrep to do the pre-processing

So the proposal is to investigate the following flow:

Filter repos using the `List` command. => Pass off repos to searcher (like we do for unindexed search) => generate the regexes and run ripgrep in searcher to filter files (this replaces the code that touches Zoekt) => run comby on the filterered files. 

This would be much cleaner since I wouldn't have to touch Zoekt things, and wouldn't have to create these file paths and pass them along. I will need to experiment to see if what I tried locally fits into the Sourcegraph flow. One thing that's still up in the air is whether using ripgrep with the zip archives on searcher pans out--the local stuff I did was on the fs.

**Comment by keegancsmith** [comment]
> * I need to run a regex to filter candidate files. Using just the constant search terms, without ordering (i.e., as a trigram look up to Zoekt using `and` queries) results in too many hits. I know this from trying things prior. The ordering on terms in a regex significantly reduces the set of candidate files compared to unordered terms.

Is the issue that the terms are quite small when doing a structural search?

> * New information I experimented with locally: ripgrep is faster at running the regexes that I currently send off to Zoekt. For small regexes this difference is negligble, but for large ones, for some reason Zoekt takes like 1 second where ripgrep takes 100ms. Implication: maybe I should use ripgrep to do the file filter pre-processing.

The disparity is surprising here. I wonder if there is something else going on? But I do know the ripgrep regex engine is a lot better.

Maybe the issue here is more complicated regexes just result in very poor performance in zoekt due to the large number of AND sub queries. I can imagine that dominating search time.

> Filter repos using the `List` command. => Pass off repos to searcher (like we do for unindexed search) => generate the regexes and run ripgrep in searcher to filter files (this replaces the code that touches Zoekt) => run comby on the filterered files.

I've been wanting to move searcher to ripgrep anyways. This sound very good. Your issue will be that this just won't work at scale without a small enough repo set. IE asking searcher to search 10k repos just won't work as things stand.

You can still use zoekt to filter down the set of repos (not files)? ie a `type:repo` query should be relatively fast and avoid the pathologies around large number of candidate files.

> The other thing that's still up in the air is whether using ripgrep with the zip archives on searcher pans out--the local stuff I did was on the fs.

You will likely need to write some rust here. But the idea of any binary generating results over stdout given a query + zip file sounds like a good abstraction for searcher to move towards.

**Comment by rvantonder** [comment]
> The disparity is surprising here. I wonder if there is something else going on? But I do know the ripgrep regex engine is a lot better. Maybe the issue here is more complicated regexes just result in very poor performance in zoekt due to the large number of AND sub queries. 

Yeah the disparity only comes up with long regex queries :-) I can share more comprehensive findings at a later point.

>  Your issue will be that this just won't work at scale without a small enough repo set. 

Yeah, I suspect the same. 

> You can still use zoekt to filter down the set of repos (not files)? ie a type:repo query 

Now that we're talking about it, I don't actually know how Zoekt manages extracts a candidate repo set from a given a query and why that works out fast. I _really_ want to know how this part works--what index does it check or how does it iterate the shards? It strikes me now that this is potentially the only part that I would really need to depend on, and could still greatly simplify things.

> You will likely need to write some rust here.

Don't tease me like that. I'd happily get distracted into writing some rust.

> but the idea of any binary generating results over stdout given a query + zip file sounds like a good abstraction for searcher to move towards.

So ripgrep already supports processing from zip, but I don't know what the internals are, so would look into it or ask maintainer once I know the questions that I want answered :-)

**Comment by keegancsmith** [comment]
> > You can still use zoekt to filter down the set of repos (not files)? ie a type:repo query
> 
> Now that we're talking about it, I don't actually know how Zoekt extracts a candidate repo set from a given a query and why that works out fast. I _really_ want to know how this part works now--what index does it check or how does it iterate the shards? It strikes me now that this is potentially the only part that I would really need to depend on, and could still greatly simplify things.

`type:repo` was added in essentially two commits:
- https://github.com/sourcegraph/zoekt/commit/f3a07d82 all: Support type:repo queries
- https://github.com/sourcegraph/zoekt/commit/45b7f7d6 Support search queries for List

Essentially `List(q)` does `Search(q, {ShardMaxMatchCount: 1,
TotalMaxMatchCount: 1})`. IE stop searching once you have found one result. If we find a result that repo is included in the list.

`A (type:repo B)` gets translated into doing:
1. `List(B)` gets you a `RepoSet` called `R`.
2. Do search `A R`.

On further thought you could actually directly use `Searcher.List` in Sourcegraph rather than needing to wrap it in a `type:repo`.

> > but the idea of any binary generating results over stdout given a query + zip file sounds like a good abstraction for searcher to move towards.
> 
> So ripgrep already supports processing from zip, but I don't know what the internals are, so would look into it or ask maintainer once I know the questions that I want answered :-)

Yeah, it was a feature request at the time searcher was written. If it existed we probably would of used that approach :)

**Comment by rvantonder** [comment]
Update on the discussion around zips: `ripgrep` doesn't support random-access zip like PKZIP, only streaming formats, like _g_zip. The flag `--search-zip` shouldn't be confused with with random-access zip.
