### ISSUE TITLE
Update Slack bot webhook code to not override user-configured name and icon

### ISSUE THREAD

**Issue by adam-moss** [sourcegraph/sourcegraph#1224]
#### Question description

Slack notification does not appear to respect settings configured within the Slack webhook configuration, e.g. name of bot and icon, instead posting as "saved-search-bot".  How can this be configured?

**Comment by dadlerj** [comment]
Thanks for posting @adam-moss! Looks like our code uses Slack's recently-made-legacy webhooks (see https://api.slack.com/custom-integrations/incoming-webhooks), rather than Slack App webhooks (since we override the default username and icon in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/query-runner/slack.go#L71:17).

We can probably make a quick fix for this by simply deleting the `Username` and `IconEmoji` fields in that payload, but we should really update to use the new Slack App incoming webhooks instead (https://api.slack.com/incoming-webhooks).

**Comment by lguychard** [comment]
Saved searches no longer support notifications, and we are building new slack notifications support for code monitoring.
