### ISSUE TITLE
ci-db-backcomp.sh is not branch-aware

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#12302]
see for example https://buildkite.com/sourcegraph/sourcegraph/builds/68763#f4388355-891f-4ace-be26-4b4401a103b3

if a DB schema change lands in master after a release branch was cut, then this check fails in the branch, because it compares HEAD of branch with latest in master.

make this check branch-aware

**Comment by efritz** [comment]
See https://docs.google.com/document/d/1pReWeznvPWQQknXdsK4z7zyhaVzdAcB1FhdDA_b1b24/edit# for context.

We can't make this check branch aware because that misses the point of the check: it needs to determine if this code landing in master will allow the _current_ frontends deployed in sourcegraph.com to successfully write to the new schema.

cc @tsenart and @pecigonzalo who were there for the discussion on the linked RFC. My original proposal was to delete this check, not modify it.

**Comment by efritz** [comment]
Oh I see this is an issue for tagged versions. This could definitely be updated to support older versions - could we simply disable the check for verion-tagged branches?

**Comment by uwedeportivo** [comment]
yeah, either way we need to find something for releases (version tagged branches), but what you say makes sense

**Comment by felixfbecker** [comment]
> We can't make this check branch aware because that misses the point of the check: it needs to determine if this code landing in master will allow the current frontends deployed in sourcegraph.com to successfully write to the new schema.

I understand this argument, but why does my branch need to fail that only touched CSS?

Maybe instead of testing the tip of the branch, the check should be testing the to-be merge commit the way that e.g. Travis runs builds on pull requests?

**Comment by efritz** [comment]
So do a rebase to the target branch before doing the check? Are you ok with CI failing here because there's merge conflict instead?

**Comment by efritz** [comment]
I would like @sourcegraph/distribution to own this problem going forward if possible. I'm in a bit too deep here and have already voiced my dislike for this check.

**Comment by efritz** [comment]
Additional doc changes related to this are here: https://github.com/sourcegraph/sourcegraph/pull/12298

**Comment by felixfbecker** [comment]
Not a rebase, a merge. GitHub transparently creates a merge commit that can be fetched under `refs/pull/123/merge`. Failing CI only when a branch is outdated AND has merge conflicts seems strictly better than always failing CI whenever a branch is outdated at all.
Here's the docs of how Travis does this and how it handles merge conflicts: https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built
There's also a feature request for Buildkite to support this natively: https://github.com/buildkite/feedback/issues/366
and someone who built a plugin that does it, with some nice example why this is useful: https://github.com/seek-oss/github-merged-pr-buildkite-plugin

Who owns this of course I don't care, not trying to put this on you @efritz. I personally get zero value out of this check since I don't write DB migrations, so currently it's helpfulness for me is negative because it's constantly failing. But I assume others do get value out of it, so I just need the flakiness to be solved.

**Comment by uwedeportivo** [comment]
we (distribution) will own this. one solution would be to somehow detect when DB migrations are added (or this is manually declared) and the check kicks in only then. i'm sure we'll find something

**Comment by keegancsmith** [comment]
I see this check is now sourcegraph.com specific, rather than being about the versions we release to customers. Simple fix for sourcegraph.com is to not run if sourcegraph.com is ahead. I'll send a PR since its quick to do and this annoyed me today :)

I would suspect we care about this more for customers rolling out sourcegraph? If that's so we can derive this state via parsing git history in relation to tags. Then we can pick the appropriate tag to check backcompat with. This is a little more work, but not much.
