### ISSUE TITLE
Sourcegraph LaunchDarkly extension design

### ISSUE THREAD

**Issue by yevbar** [sourcegraph/sourcegraph#1249]
#### Feature request description

Sourcegraph LaunchDarkly extension

#### Is your feature request related to a problem? If so, please describe.

The Sourcegraph browser extension allows for individuals to create their own extensions - see [Authoring docs](https://docs.sourcegraph.com/extensions/authoring). There is currently one for [Codecov](https://github.com/codecov/sourcegraph-codecov) and there isn't one for [LaunchDarkly](https://launchdarkly.com/) (yet!)

#### Describe alternatives you've considered.

1) First feature: Get information on feature flag on hover (visibility check requires client id)

![image](https://user-images.githubusercontent.com/10301415/49556019-e71d6600-f8b6-11e8-956e-92f637f48015.png)

Every flag has its own page that looks like `https://app.launchdarkly.com/default/LOCATION/features/FLAGNAME/targeting` so a link to this page could be included in the hover box.

Visibility of an LD feature requires a client id which can be obtained similarly to the Codecov extension

![image](https://user-images.githubusercontent.com/10301415/49556626-922f1f00-f8b9-11e8-9667-f8bbfb8e5915.png)

2) Second feature: Listen for changes in feature flags (client id required)

![image](https://user-images.githubusercontent.com/10301415/49556851-6e200d80-f8ba-11e8-9687-76bb5b00cb43.png)

#### Additional context

This is posted to gather feedback on what should/shouldn't be implemented. The above features are what are provided in the [JavaScript SDK](https://docs.launchdarkly.com/docs/js-sdk-reference). There's one more functionality provided which is the manipulation of the `user` object used to connect to LD however it makes no sense to store Github viewing session in the sessions database.

**Comment by yevbar** [comment]
As clarification: I plan on developing this extension, I'm putting this issue here so I could show what features are currently planned and see what else needs to be added

**Comment by sqs** [comment]
Awesome!

For the first feature (seeing whether a feature flag is visible), here are a few related improvements that I think are more valuable than listening for changes in feature flags:

1. Showing the visibility info in an after-line decoration like the blame text (`Ying Li, 2 years ago: ...` in https://sourcegraph.com/extensions/sourcegraph/git-extras), using `setDecorations` in the Sourcegraph extension API
1. Showing other stats beyond just visible yes/no: # of users for whom this is visible, when the targeting of this feature flag was last changed and by whom, and any SVG charts or other visualizations that might be available
1. A panel (using `createPanelView` in the extension API) that shows all of the feature flag keys that are used in the repository and links to a search query for each one that shows all of the places where that feature flag key is used. Bonus for including those same stats as in (2) here, too!

**Comment by atrakh** [comment]
Hi @yevbar,

I'm Arnold, I work at LaunchDarkly, and I built our [Visual Studio Code extension](https://github.com/launchdarkly/ld-vscode), which has similar functionality to your extension proposal. We think this is a great idea!

I'm not too familiar with creating extensions for Sourcegraph, but I have some ideas for how we could make the @sqs's suggestion of displaying flag stats in sourcegraph possible. This functionality wouldn't work too well with the JavaScript SDK,  because the JS SDK doesn't store any feature flag configuration data internally, but instead delegates to the LaunchDarkly API to handle flag evaluations. This is done to avoid exposing feature flag configurations in client-side contexts.

On the other hand, our [node sdk](https://docs.launchdarkly.com/docs/node-sdk-reference) doe store flag configs in-memory, which will make it much easier to access flag settings (number of user targets, rules, etc). For our VSCode extension, we were able to retrieve and interact with flag configs using the node SDK's internals (see https://github.com/launchdarkly/ld-vscode/blob/master/src/flags.ts#L100).

Also had a question about your planned implementation- will the extension resolve all string literals containing flag keys, or only when they're inside of `variation` calls?

Hope the above is helpful! Feel free to @ me with any questions

**Comment by chrismwendt** [comment]
Here's the API for fetching feature flag info: https://apidocs.launchdarkly.com/docs/get-feature-flag

**Comment by atrakh** [comment]
> Hey again, we were wondering if we could use the V1.0 API since the request is much simpler (just `/features/:key`)?

The v1 REST API has been deprecated, and is not compatible with most LaunchDarkly accounts.

If you're planning on using our API over an SDK to retrieve flag data, I'd recommend using the v2 API's [flags endpoint](https://apidocs.launchdarkly.com/docs/list-feature-flags). The main difference between the v1 and v2 APIs is that in v2, flags are scoped to [projects](https://docs.launchdarkly.com/docs/projects), and results can be filtered by environments (since your environments, like `production` and `staging`,  can have different flag rules). So, it's likely that the extension would need to either iterate over all projects, using the [projects endpoint](https://apidocs.launchdarkly.com/docs/list-projects), or have the user configure which project they'd like to use at extension installation/configuration time.

**Comment by yevbar** [comment]
@atrakh Ok, I'll be iterating over all the user's projects and features then :slightly_smiling_face:
