### ISSUE TITLE
Remove or resolve Codemod types in extensions

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#12544]
We have a number of extensions that are live on sourcegraph.com that use the Codemod GQL result type, which I tried to remove in #12480. Despite testing all changes and green CI, this ended up breaking prod

![image](https://user-images.githubusercontent.com/888624/88846497-8da83000-d19a-11ea-8dbb-a838576daba9.png)

The following worry me:

- Error isn't clear where the source of the problem is (likely some extension). I haven't confirmed yet, but based on the default enabled extensions and [this search](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/.*+codemodresult+-repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24&patternType=literal#3) it could be either `sourcegraph/code-stats-insights` and/or `sourcegraph/code-intel-extensions`. 

- The PR above passed CI and I did a bunch of checks to make sure I don't break anyone's dev environment. Despite my best effort, the breakage didn't get caught. I don't know what the state of e2e tests are. If they aren't running per PR, that's unfortunate. If they are, but missing an e2e test that includes the default extensions we author and activate for sourcegraph.com, shouldn't we add tests to cover that?

---

Deprecate versus removing codemod result type: I feel we should remove it, it was never documented or released in a changelog, so there shouldn't be any client/extension that makes use of this except ourselves. But, I don't know if we package the GQL types for extension authors and whether this would break any previous clients. @felixfbecker can you comment on these issues, and can I ask for your help in pinpointing where these references to `CodemodResult` should be removed? I'm happy to go and make PRs based on the search above, but I still won't have confidence that I've covered everything unless I know someone who's worked with the extension code can vet those changes.

**Comment by felixfbecker** [comment]
Weird. The error definitely looks like a backend error that would come from a client making a query for `CodemodResults`. The only "strong" reference to `CodemodResult` in your linked code search, excluding the web app code that was removed, comes from the [pull request extension](https://sourcegraph.com/github.com/sourcegraph/pull-request-extension-exp/-/blob/src/codemod.ts#L81) you wrote a while ago, all the other references are just (slightly outdated) schemas/interfaces, not actual queries. It's also the only extension that would be in the search code path because it registers a query transformer - code intel extensions and code insights extensions are not in the code path of running a search, so I don't see how they could cause this error. They definitely don't query `CodemodResult`s though. Even the query transformer of the pull requests extension looks completely harmless.

I don't see the pull request extension enbabled in org or global settings though, and enabling it locally before the revert, I cannot reproduce the error. It may have been likely you had it in your user settings, but I don't know how @rrhyne would have that extension enabled (unless he enabled a bunch of random extensions for design testing?).

Since I cannot repro locally, I don't know how to further debug... What I would need is seeing the console and network tab when this error happens, did you screengrab or save a HAR by any chance? Does it maybe not come from extensions, but from the backend? What lead you to believe it likely came from an extension? Could it maybe be that some service deployment was out of sync? Or maybe your client bundle was cached and needed a hard reload?

**Comment by rvantonder** [comment]
OK, thanks for the context, this is really useful.

> but I don't know how @rrhyne would have that extension enabled (unless he enabled a bunch of random extensions for design testing?).

> Could it maybe be that some service deployment was out of sync? Or maybe your client bundle was cached and needed a hard reload?

This is the key thing--@rrhyne reported this issue, and said that he only has the default extensions enabled (no pull request extension, probably no local dev for extensions or any sort of caching).  So I'm ruling out local caching or dev environments. The deleted replacer change was live for probably > 12 hours, so I am surprised that no one else reported this issue. I'm going to do some more digging, I'll try a couple of things to reproduce locally. Maybe @rrhyne and I can jump on a call to try get a screen grab or the like by reproducing from a branch with the service removed. I'll take it from here and  report back.

**Comment by felixfbecker** [comment]
I find the cached client bundle the most likely theory (i.e. browser still had an outdated JS bundle cached/in memory while the backend was already updated, especially likely if it was a tab that was still open from before the deploy). A hard reload should fix it in that case.

**Comment by rvantonder** [comment]
I was able to reproduce this locally when switching branches during local dev, on one branch where replacer was removed, and then to a branch where it exists (and local dev rebuilds the things it think it should at runtime). After switching to the one where it supposedly exists, the frontend shows the `Unknown type` issue (even with caching disabled):

<img width="1434" alt="Screen Shot 2020-08-06 at 5 38 09 PM" src="https://user-images.githubusercontent.com/888624/89597779-eec1aa80-d80f-11ea-8d46-36c7cb069981.png">

But when I do a hard refresh, or paste the URL into a different tab, it goes away, so I'm chalking it up to Felix's explanation.
