### ISSUE TITLE
Sign in page has ugly navbar

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12547]
The sign in page has an ugly navbar at the top. I don't know how long it's been like this, but I feel like we can do something nicer to incorporate the logo / Sourcegraph icon into the page than having an empty navbar. Thoughts?

![image](https://user-images.githubusercontent.com/3173176/88863024-9870be00-d1b6-11ea-9617-768d0c95a0d6.png)

cc @sourcegraph/design @sourcegraph/web

**Comment by felixfbecker** [comment]
@AlicjaSuska this would be good to include in the information architecture project - which pages should have a navbar (and which should have the search navbar)

**Comment by rrhyne** [comment]
Agree the navbar could go, but the overall design here should be a project as well.

**Comment by AlicjaSuska** [comment]
I think it would make sense to incorporate in it the Information Architecture project. I think I can take some time next week to prepare the designs. @rrhyne why do you think it should be a separate project? Are there any other UX changes that need to happen outside of the visual adjustments?

**Comment by rrhyne** [comment]
I mean that "the overall design" should be a separate project, the navbar can certainly be fixed in the IA project. 

My issue with the design is that it is uninspiring. Here's a sketch of the opposite of that page. It goes a bit too far and is now off-brand, but illustrates the spectrum of possibilities:

https://www.figma.com/file/BsMRCHLqk8okCkDICYmtWE/Login-page-exploration?node-id=3%3A191

**Comment by rrhyne** [comment]
@quinnkeast https://github.com/sourcegraph/sourcegraph/issues/12695 addresses this, can you close and reference if that is correct?

**Comment by quinnkeast** [comment]
Addressed in #12695.
