### ISSUE TITLE
Question about site-usage

### ISSUE THREAD

**Issue by bencripps** [sourcegraph/sourcegraph#1257]
#### Question description

`/site-admin/usage-statistics` seems to `404` -- are these [docs](https://docs.sourcegraph.com/user/usage_statistics#usage-statistics) out of date, or is there an issue with my local instance?

#### Additional context

Current product version: 2.13.5 (2.13.5)

**Comment by sqs** [comment]
Yes, please see https://docs.sourcegraph.com/@v2.13.5/user/usage_statistics or the /help pages on your own instance for the right version. 

We have a TODO to make this clear in the docs site. In the meantime I will add a note to that page mentioning the change to avoid future confusion. Will close this issue when done.

**Comment by bencripps** [comment]
Thank you! Is there a setting I need to set to track actions from unlogged in users? It seems like those actions aren't being logged.

**Comment by dadlerj** [comment]
Thanks for reporting @bencripps, the bug undercounting anonymous users will be fixed in our next release. 

If you don't mind my curiosity, what made you choose, I presume, a setup that allowed unauthed usage, as opposed to using Sourcegraph's built-in auth (which is free)? 

(And if you want a license key for a trial of SSO, happy to give you one as well! 😄)
