### ISSUE TITLE
Can't find cross-repo refs for definition in vscode package

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1258]
At https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/src/vs/vscode.d.ts#L1074:19&tab=references I want to find cross-repo references to the `vscode.d.ts` type `TextEditor`. 

I see it says `Searching for dependents of code-oss-dev through npm`, but it should be looking for dependents of `vscode`.

It is 100% fine to special-case this specific file in this repo (or all files named `vscode.d.ts`).

You should do the same for `sourcegraph.d.ts`, too, if needed.

**Comment by felixfbecker** [comment]
Even with a special case this is unlikely to return good results, because extensions are not published to npm, but to the vscode marketplace. I could implement a dependentsprovider for the marketplace, but I know that the API is undocumented. In addition, there would need to be a special case on the server too, because the vscode.d.ts is actually fetched in a postinstall script, which we don't run. This is probably all not worth the effort, so closing for now.
