### ISSUE TITLE
What is the actual API rate limit required for repository permissions?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12682]
A customer https://app.hubspot.com/contacts/2762526/company/407948923/ uses a newer version of Bitbucket Server which has [built-in rate limiting](https://confluence.atlassian.com/bitbucketserver/improving-instance-stability-with-rate-limiting-976171954.html) which I believe affects Sourcegraph even in the case of it running as a Bitbucket plugin as they have set up today.

We need to know: What is the rate limit requirement of repository synching + repository permissions for a given number of repos/users in general? - without this it seems risky to just enable repository permissions as it may lead to both repositories and permissions not synching at all or very fast.

---

I believe that this would also apply to anyone using our [internal rate limiting](https://docs.sourcegraph.com/admin/external_service/bitbucket_server#internal-rate-limits) option, as despite the fact that it says in the docs that it only applies to changeset synching, the code itself seems to indicate [it does apply to repository synching too](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/extsvc/bitbucketserver/client.go#L98-102)

**Comment by unknwon** [comment]
I can only speak about repository permissions with Bitbucket Server regarding rate limiting (and I believe rate limiting topic for each code host should be discussed and dealt with separately as they often have different mechanisms). I think @ryanslade knows more about repository syncing with rate limiting as he had done the work of internal rate limiting.

---

Based on the new [Bitbucket Server built-in rate limiting](https://confluence.atlassian.com/bitbucketserver/improving-instance-stability-with-rate-limiting-976171954.html) (the link you posted), it works in a very similar way to our current self-imposed Bitbucket Server rate limiting (that controls burst and rate per second):

https://github.com/sourcegraph/sourcegraph/blob/3cce5e9d8c96d5236c247748c01d7bb0d017f8ab/internal/extsvc/bitbucketserver/client.go#L54-L55

Therefore, shouldn't be hard to support it, including updating corresponding site configs around rate limiting.

As for the repository permissions rate limiting requirement, there is no real requirement in the current implementation because there is no sense of TTL, just doing as fast as it could (because there is no "complete" state in terms of mirroring permissions). The syncing process is currently sending sequential requests (only send another one until the previous one is finished), this should be fine according to the section **How to help users avoid being rate limited** in the link (although this totally depends on customer's settings regarding "refill per second"):
>[...], they can consider sending them one at a time, and only sending a new request after the previous one has finished.

If Sourcegraph can reach their Bitbucket Server and get response around 100ms in average, then ideally we need 10 refill per second (1000ms / 100ms = 10) just for repository permissions.

What we can calculate is the number of API requests we need for repository permissions (e.g. for the initial round). If a customer has 500 users and 10k repositories and is using Bitbucket Server (which has page size 1000), then in the worst case scenario (all repositories are private, every user has access to every repository), we need 500 * 10000 / 1000 = 5000 requests.

**Comment by ryanslade** [comment]
Currently repo syncing performs a sync every minute by default but can be changed by setting `repoListUpdateInterval` in config.  For each BitBucket external service we make two queries:

* Fetch all archived repos (at 1000 per page)
* Fetch all repos (at 1000 per page)

Each page query would be considered a request AFAICT. So, it depends on the total number of repos and how frequently we check.

FYI, we're planning to change this as part of RFC 211 so that we'll back off and sync less frequently when a sync determines that we were up to date already.

**Comment by unknwon** [comment]
Thanks @ryanslade! 

To summarize with a simple calculation: with default a sync per minute, and 10k repositories, every minute we make 10000 / 1000 = 10 requests, which seems pretty low usage to me (for Bitbucket Server).

@slimsag: Do you think you've got enough information, and/or is there anything specific you're still unclear about?
