### ISSUE TITLE
Assess consequences of removing noGoGetDomains and the go get domains blacklist - add back to Go extension

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1276]
These settings used to be in site config but were removed when Go support moved to an extension.

See if they are still needed and add them back if so.

(From https://github.com/sourcegraph/sourcegraph/pull/584)

**Comment by chrismwendt** [comment]
I believe @slimsag mentioned to me that these are still necessary.

I'm retaining this functionality in go-langserver https://github.com/sourcegraph/go-langserver/pull/345 (specifically on line https://github.com/sourcegraph/go-langserver/pull/345/commits/6cdc21f898bf72efe660ea1798735f7c03f125a2#diff-893794fd1c4c9c7b18d54d632bedd5b7R22, hard to see since the diff is so big).
