### ISSUE TITLE
External references are not shown when revision is not "master" or is "HEAD"

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1282]
I am returning an Observable from my (single) references provider. It is first emitting local references, then as external references are found, adds chunks of them and emits a new array (concatenated with the new references).

The local references are shown, but the external references are not.

![image](https://user-images.githubusercontent.com/10532611/49654685-d1d04500-fa38-11e8-863a-093708cf6bf9.png)

Here's the log file from the console:

[localhost-1544194162393.log](https://github.com/sourcegraph/sourcegraph/files/2657659/localhost-1544194162393.log)

Search for `EMITTING VALUE` and note `COMPLETE` only appears at the very end.
These logs were done at the direct calls to `observer.next()` and `observer.complete()`.

The Observable is not unsubscribed from, that would cause another log `UNSUBSCRIBED`. Also the loading spinner is there until `COMPLETE` is logged.

This worked yesterday when I posted the demo gif in Slack.

(All access tokens in the logs are only to my localhost instance).

**Comment by felixfbecker** [comment]
It is still working for me on http://localhost:3080/github.com/sourcegraph/javascript-typescript-langserver@6a7ad453eef4491ab1a551195fe271334a6c9ca9/-/blob/src/project-manager.ts#L699:16, but not on http://localhost:3080/github.com/DefinitelyTyped/DefinitelyTyped@HEAD/-/blob/types/react/index.d.ts#L355:11&tab=references

**Comment by felixfbecker** [comment]
Ha, it doesn't work when the revision in the URL is `HEAD`: http://localhost:3080/github.com/sourcegraph/javascript-typescript-langserver@HEAD/-/blob/src/project-manager.ts#L699:16&tab=references

**Comment by felixfbecker** [comment]
So external references are shown if the revision is `master` or a commit SHA pointing to `master`. They are _not_ shown if the revision is any other branch, tag or `HEAD` (even though `HEAD` is the same as `master`).

**Comment by felixfbecker** [comment]
I am not sure if this is caused by the rev returned by the extension or by the rev present in the browser URL

**Comment by lguychard** [comment]
I believe we may actually have two bugs here.

Bug 1:
- On http://localhost:3080/github.com/sourcegraph/javascript-typescript-langserver@HEAD/-/blob/src/project-manager.ts#L699:16=&tab=references
- No cross-repo references are shown initially
- once the external definition has loaded in the tooltip, navigate to the definition panel, see the cross-repo definition from felixfbecker/iterare
- navigate back to the references panel, see cross-repo references from felixfbecker/iterare
- this behaviour is the same on master, HEAD, or any other branch or tag

![refrences1](https://user-images.githubusercontent.com/1741180/49677113-c75e7d00-fa31-11e8-9686-75476127e3e0.gif)

Bug 2:
- On http://localhost:3080/github.com/DefinitelyTyped/DefinitelyTyped@HEAD/-/blob/types/react/index.d.ts#L355:11&tab=references some cross-repo references might be shown, but they disappear after a while
- this is due to an error being thrown by the lang-typescript extension `Error: Not a Sourcegraph raw API URL: file:///private/var/folders/gv/hdx6nz_j6d9_3y3_qrqk5cxr0000gn/T/f79fc630-fa6e-11e8-99f5-211fad1c00bd/repo/packages/adaptableblotter/node_modules/%40types/react-redux/index.d.ts`
- This error is somehow caused by finding cross-repo references in, I assume, the dependencies of https://github.com/JonnyAdaptableTools/adaptableblotter
- this behaviour is the same on master, HEAD or any other branch or tag

I feel like this second one is a lang-typescript bug rather than a Sourcegraph bug.

@felixfbecker can you confirm these behaviours?

**Comment by sqs** [comment]
@lguychard So for bug 1, is that related to the bug where we were seeing a long list of references results all from the same repo and in the file types/react/index.d.ts? Does switching back and forth between panels somehow fix that issue? Or is that bug yet another bug?

**Comment by lguychard** [comment]
@sqs those were legitimate - there were 273 references in the repo DefinitelyTyped, and 45 of those in types/react/index.d.ts

**Comment by felixfbecker** [comment]
@lguychard are you sure the bug is caused by the error? There are a lot of places where an error can occur, but when looping (e.g. over dependents) lang-typescript/the TypeScript backend usually just logs these, then continues with the next one. How did you verify that that error causes the bug?

**Comment by felixfbecker** [comment]
Note that in the logfile I uploaded in the issue there is not a single error log.

**Comment by lguychard** [comment]
@felixfbecker this is the error I've been seeing (and just reproduced on https://sourcegraph.com/github.com/DefinitelyTyped/DefinitelyTyped@master/-/blob/types/react/index.d.ts#L355:11&tab=references):

![image](https://user-images.githubusercontent.com/1741180/49837493-d2553c80-fda6-11e8-8f47-3db95245ac51.png)

This is [thrown in lang-typescript](https://sourcegraph.com/github.com/sourcegraph/lang-typescript/-/blob/extension/src/uris.ts#L36), and the [callsite that throws it](https://sourcegraph.com/github.com/sourcegraph/lang-typescript/-/blob/extension/src/extension.ts#L384) is not wrapped in a try/catch block.

Before seeing this error, external references are shown. After seeing this error, only local references are shown.

**Comment by felixfbecker** [comment]
Ah, I see. I'll get that fixed. However, I think this is a different issue - the behaviour I observed in the issue description was not references _disappearing_, but references _not showing up_ in the first place.

Besides that, if a hover provider throws, the panel should not display "no references found", it should display the error.

**Comment by lguychard** [comment]
@felixfbecker as mentioned the closest I could get to reproducing your original scenario was bug 1 described above.

I never found a correlation between the revision being master/head and references being shown or not.

**Comment by felixfbecker** [comment]
I see external references now even when the rev is HEAD so I assume this is fixed.

![image](https://user-images.githubusercontent.com/10532611/50250940-8f1c4e80-03e2-11e9-8d5b-6a002747ec82.png)
