### ISSUE TITLE
Discussion: Reduce Renovate PR spam

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1290]
At this moment we have 40 open PRs and [20 of them are from Renovate](https://github.com/sourcegraph/sourcegraph/pulls?q=is%3Apr+is%3Aopen+author%3Aapp%2Frenovate+sort%3Aupdated-desc), mostly Go dependencies. This seems exacerbated by the fact that we have dependencies on pinned on commit hashes instead of semantic versions with release notes (I am not sure if semver tags are available for various dependencies). These PRs have been open for a month, which indicates to me that the value of these PRs is very low (otherwise we would have merged them). I view these PRs as noise in our open PR list that should be eliminated.

I would be in favor of completely removing the dependency updating for Go. Generally, I don't see a reason to recreationally update dependencies unless the updates contain features or bug fixes that we explicitly need.

Combining all Go dependencies into a single PR would also solve the PR spam problem while still giving us information about what dependencies are out of date. I would still have the same reservations about regularly merging said PR as expressed above.

I would be interested to hear everyone's opinion.
cc @slimsag @beyang @tsenart @keegancsmith

**Comment by tsenart** [comment]
How much additional confidence do we need in our test suite that merging these PRs when CI passes could be automated?

**Comment by beyang** [comment]
Agree with removing Renovate for Go. I think the main value of such systems is to eliminate old security vulnerabilities, but I'd rather get notified about those and focus on those. Updating this frequently just means we are merging a lot of code that we're not really reviewing (thereby introducing the risk of merging the latest and greatest security vulnerabilities).

**Comment by felixfbecker** [comment]
The only thing this tells me right now is that we don't care about keeping our Go dependencies up to date, which I find concerning.

It seems like all of these PRs have been open from the first time that Renovate was enabled for Go. Since dependencies were already outdated at this point, we started with a backlog, that apparently was never cleared. Note that Renovate is configured to only run once per month so I wouldn't necessarily call that "spam". Surely it is worth to take one hour every month to review and merge these?

It's not like only security updates are worth to update, like if Zoekt just improved performance by 5%, and we can get automated PRs to update that, we should merge that. Or just some new API that someone next week might need and can directly discover and use through autocompletion. Or this one bug that maybe noone discovered in our product or is a code path that wasn't even hit right now but it is next week or only by a customer and we saved someone a day of debugging by updating before that happens without even knowing.

@slimsag I didn't notice that Go PRs don't have them - would what the npm update PRs have suffice you? I would recommend you to open an issue at https://github.com/renovatebot/renovate, past requests were implemented in less than a week.

**Comment by tsenart** [comment]
> Surely it is worth to take one hour every month to review and merge these?

+1

We can surely rotate who takes care of this but I agree 100% that we should not let our dependencies rot.

**Comment by tsenart** [comment]
I actually volunteer to start reviewing and processing these PRs tomorrow.

**Comment by nicksnyder** [comment]
> The only thing this tells me right now is that we don't care about keeping our Go dependencies up to date, which I find concerning.

I don't find it concerning that teammates have not prioritized updating dependencies that appear to be working just fine for us. Unless there are concrete reasons to update (i.e. bug fixes, security fixes, or features that impact us), then leaving them in a known working state is perfectly fine.

> Note that Renovate is configured to only run once per month so I wouldn't necessarily call that "spam"

The problem is not the frequency, it is the number of open PRs that is the spam.

> It's not like only security updates are worth to update, like if Zoekt just improved performance by 5%, and we can get automated PRs to update that, we should merge that.

Updating a dependency is a cost/benefit analysis. You mention all the benefits in the best case scenario but none of the costs in a not-best-case-secenario. One cost is that there is always a risk that any update introduces a regression in behavior which might not get discovered until later.

> we should not let our dependencies rot.

We definitely should let them rot if there are more valuable uses of our time. Different people can have different assessments of what is valuable though.

> I actually volunteer to start reviewing and processing these PRs tomorrow.

Do you think that updating a lot of dependencies right before we cut 3.0-preview is wise? Personally, I would wait.

**Comment by tsenart** [comment]
> Unless there are concrete reasons to update (i.e. bug fixes, security fixes, or features that impact us), then leaving them in a known working state is perfectly fine.

Totally agree @nicksnyder, but how can we know if there are bug fixes, security fixes or features that impact us if we don't review our dependencies regularly?

> The problem is not the frequency, it is the number of open PRs that is the spam.

We could verify if this continues to be the case after doing an initial review of open PRs and processing them, thus attaining a clean slate. If it turns out that our dependencies continue to have a lot of on-going development, we should reconvene. But typically, reviewing one small dependency at a time is going to be easier and more thorough than reviewing a whole batch of them; it's the same dynamic as with small PRs vs large PRs.

> Updating a dependency is a cost/benefit analysis.
> We definitely should let them rot if there are more valuable uses of our time. Different people can have different assessments of what is valuable though.

Indeed, updating a dependency, like most other things, should be preceded by a cost / benefit analysis. But I'm not sure how we can do that analysis without first reviewing what we'd be bringing in to the codebase, either via CHANGELOGS, release notes or straight up code review.

Perhaps I'm under-estimating the time required to do these reviews and assessment before changing any code and subsequently testing it, but out experience, if we do these regularly, it's very manageable.

> Do you think that updating a lot of dependencies right before we cut 3.0-preview is wise? Personally, I would wait.

I don't believe that updating a lot of dependencies before a big release is wise. 😅 

I think it's wise to review and triage these PRs for us to know what they include, before bringing in any changes to master. We can do so in an incremental manner, not necessarily all at once, and we can begin by looking into those that we think would yield the biggest benefit or attenuate the biggest risk, like the `golang.org/x/` repos that @slimsag mentioned.

**Comment by felixfbecker** [comment]
I agree with how @tsenart put it. It is fine if someone inspects a PR, sees the changes made don't provide us a benefit (and therefor only a risk) and closes the PR. Renovate will not recreate closed PRs. But the PRs are a method for us to get notified of a new release, an interface for us to review them and to make a decision whether to merge or skip the update. They should just not be left pending.

@tsenart you could review the PRs now and use GitHub's approve feature to mark the ones we want to merge after the release and close the ones that are not of use to us.

**Comment by tsenart** [comment]
> @tsenart you could review the PRs now and use GitHub's approve feature to mark the ones we want to merge after the release and close the ones that are not of use to us.

That sounds good to me. I'll begin with the `golang.org/x/` ones.

**Comment by tsenart** [comment]
Question: What reasons do we have for pinning `golang.org/x/` repos to commit hashes instead of semantic versions?

**Comment by tsenart** [comment]
It seems there are not tags in `golang.org/x/` repos, but there are release branches. We could use those instead.

**Comment by nicksnyder** [comment]
> Can @renovate-bot always paste a comparison link, even when a dependency is pinned to a commit? Doing this manually is a waste of time :-)

> On another note, a local go get -u updates only minor and patch versions automatically. It seems like Renovate is doing more than that, as the diff of the result local go.mod shows:

You can file an issue for both of these to discuss; they have been responsive to me in the past.
https://github.com/renovatebot/renovate/issues

> It seems there are not tags in golang.org/x/tools repo, but there are release branches. We could use those instead for that particular dependency.

I would definitely prefer to use semver or release branches if they are available.

**Comment by felixfbecker** [comment]
Just wanted to mention again that JS update PRs already have comparison links so I expect a request to add them to Go PRs too to be implemented quickly

![image](https://user-images.githubusercontent.com/10532611/49825182-1daa2380-fd84-11e8-9e70-47fdcc743ad4.png)

**Comment by tsenart** [comment]
I created two issues on their repo:

1. Renovate doesn't match `go.mod` based `go get -u` semantics (https://github.com/renovatebot/renovate/issues/2942)
1. Add support for "Compare Source" + change summary to `go.mod` based repos (https://github.com/renovatebot/renovate/issues/2939)

We got a reply already: https://github.com/renovatebot/renovate/issues/2939#issuecomment-446354515

**Comment by rarkins** [comment]
Hi, Renovate author here. FYI I think point 1 above is just because your settings in this repo impose a concurrent limit of maximum 20 PRs open at one time. You can raise or lower that of course, but that doesn't really fix the core challenge of what to do when your modules have updates available but aren't being merged.

As a general point, I'm surprised to see so many Go dependencies without without support for semver. Once we detect a Go module dependency has adopted semver versioning, you'll no longer see the PRs that just bump the hash and instead they convert from hash to a version.

Something else you might want to consider is adding the Renovate feature "masterIssueApproval" to your config. It creates a single long-lived Issue in each repo and lets you gate/approve PRs before they're opened. Like any other Renovate config, you can enable/disable it selectively per-package, per-type, etc.

The downside though is that this can shift the problem from being "all these PRs we are ignoring start to feel like spam" to "out of sight, out of mind". But for example if you find the hash-based updates to be harder to review than semver-based ones, then you could set a policy that says require approval only for hash-based ones and semver updates are raised automatically like before.

You can see an example of this master issue in the Renovate repo that I'm dogfooding: https://renovatebot.com/gh/renovate/issues/2743

**Comment by rarkins** [comment]
FYI, I think this backlog of Go PRs has also resulted in your Kubernetes manifests getting rate limited and hence "blocked" because the 20 open PRs limit is already exhausted.

Quickest thing you can do right now is add `"masterIssue": true` to your config, which means all team members can get visibility of which PRs are open and which are pending. It doesn't mean that any *require* approval though, so does not change the current policies. It also allows anyone with write access to the repo to trigger a rate-limited PR to be force opened.

However I'm sure your Kubernetes people would prefer their updates didn't get held up if they are in the business of merging them, so you probably need a better long term solution.

**Comment by felixfbecker** [comment]
@rarkins shouldn't the PR limit be per-repo? The Kubernetes files are in a different repo

**Comment by rarkins** [comment]
@felixfbecker sorry, you are right about that, I got the repos mixed up. Will edit above

**Comment by tsenart** [comment]
I think using `"masterIssue": true` like https://github.com/renovatebot/renovate/issues/2743 could be helpful. Shall we enable it?

**Comment by felixfbecker** [comment]
I'm not sure. I definitely would not want it for JS. To determine whether we want to update a dep or not, we need to review the change/commit log. But that master issue does not include this context. So I feel like we would just never check the boxes, or check them all to then inspect the PRs. At which point we could have just reviewed the PRs as they were created and closed/approved/merged them directly.

**Comment by tsenart** [comment]
@felixfbecker: Yeah, you're right. What we're missing really is the change-set links and more dependencies of our Go dependencies to adopt semantic versioning.

**Comment by rarkins** [comment]
I probably didn't explain the two options clearly enough yesterday.

`"masterIssue": true` is configured globally and simply adds an issue to the repo that gives a view of all PRs open and pending. So in cases like this, you can see the blocked PRs and choose to force override them to be created. You could think of it as like a dashboard within the repo.

`"masterIssueApproval": true` can be configured globally or per-package and does change the workflow. It means that PRs matching this will not be created automatically, and instead will show up as "Pending Approval".

I think @felixfbecker you maybe don't like the approval approach because you can't see until the PR is created either (a) if it passes tests, or (b) what the changelogs are.

FYI I have improvements planned to address both of those:

(a) Add an option that will create *branches* always, but not PRs until they are approved. That way the build status will be able to be seen in the master issue (green/yellow/red).
(b) renovatebot.com will soon host copies of changelogs meaning that the master issue can link you to a page containing the same contents as you would see in the PR body if the PR is created.

**Comment by felixfbecker** [comment]
Thanks for the explanation. I think I personally would still prefer to just interact with PRs directly.

**Comment by slimsag** [comment]
To be honest, using Renovate for Go dependencies right now sucks:

1. According to @felixfbecker the large number of Go PRs is blocking our TypeScript PRs from being created.
1. Despite Renovate PRs trying to be scoped to a single dependency, Go dependencies are intermingled  so when Renovate updates "1 dependency" it is actually updating multiple in the go.sum file. So you aren't just reviewing the update of a single dep.. you're reviewing the update of multiple.
1. Because go.sum contains multiple dep updates per PR, as soon as we merge a Renovate Go PR every single other one now has a merge conflict and you have to wait ~20 minutes for Renovate to rebase it.
1. All of our Go PRs still don't have comparison links, I assume this is because they were created before those were added? I'm not sure but it makes reviewing these a PITA. I also assume the comparison links won't include changes to downstream deps in go.sum.

Basically, having Renovate notify us about the fact that there are updates to Go dependencies is nice, but the actual medium for consuming that information (PRs) is absolutely awful.

Currently the best approach I have is using the Renovate PRs as a notification system, then using the `go` tool directly to produce a branch that updates the deps (to avoid waiting hours of time for Renovate to resolve merge conflicts), then manually inspecting the changes listing in go.sum because the Renovate comparison links either don't exist or are an incomplete picture (which is dangerous).

**Comment by nicksnyder** [comment]
My vote would be to enable be master issue workflow (for at least Go) so PRs don’t get created until someone is actually ready to take a look. I don’t think “get notified that a dependency has an update” is that relevant because (1) it seems safe to assume that all deps always have an update and (2) the notification doesn’t actually help because it is rarely the case that we have the bandwidth to deal with it at that time anyway.

**Comment by slimsag** [comment]
To be clear, by notification I actually meant "having a list of dependencies that need updating"

**Comment by rarkins** [comment]
I’d also recommend Master Issue Approval enables for Go specifically: https://renovatebot.com/blog/master-issue

Re: go.sum, It’s unavoidable that a “single” update may trigger many updates to go.sum, just like with yarn.lock. But further, it can even trigger multiple updates to go.mod too, if there are shared dependencies. This is a particular characteristic of Go’s minimum version approach.

**Comment by felixfbecker** [comment]
@nicksnyder SGTM.

@slimsag I don't think they should update more than one dependency. Sounds like a bug @rarkins?

**Comment by slimsag** [comment]
@rarkins Definitely, no argument there, it is an intrinsic property of Go's versioning system. But this property makes Renovate's PR interface quite nasty to use in combination with Go.

**Comment by rarkins** [comment]
@felixfbecker not a bug, it’s a feature of Go’s minimum version selection. If the dependency you’re updating itself requires a newer version of something in your go.mod then you get more than one line updated. 

I can assure you that doing it all by hand sucks pretty hard too.

**Comment by felixfbecker** [comment]
But I don't see how that is any different for other langs - if an npm dependency requires a newer transitive dep, it would update that too?

**Comment by slimsag** [comment]
What does your review flow for renovate PRs with transitive deps @felixfbecker ?

In my case with Go, it looks like:

- View renovate PR
- Look at diff to figure out what the commits were to find difference in each dependency (transitive or not).
- Review those diffs.
- If they look good / came from trusted authors, approve and merge renovate PR.
- All other renovate PRs now have merge conflicts, need to click rebase checkbox and wait ~30m.
- Repeat (or, more likely, forget).

**Comment by felixfbecker** [comment]
I think npm deps rarely update transitive deps, and if they do, they are usually not important to review because only updates to the first-order dependency can affect the API and be breaking (transitive deps are an implementation detail, and if they are breaking, the first-order dependency would bump the major version too)

**Comment by rarkins** [comment]
When you merge a Renovate PR, it triggers a webhook that causes Renovate to run within seconds. How long it takes to complete depends on how much work it needs to do, and this repo has over 100 branches of outdated dependencies so that's a lot of work. 

Looking at the last 2 merges of Go dependencies in this repo:

Last:
- 2019-04-29T19:39Z        @slimsag merged #2507 (approximate time according to GitHub UI)
- 2019-04-29T19:42:37.969Z Renovate finished its subsequent update

Second last:
- 2019-04-25T21:15Z        @nicksnyder merged #3151
- 2019-04-25T21:19:12.382Z Renovate finished its subsequent update

**Comment by rarkins** [comment]
@felixfbecker you can of course liken `go.mod`/`go.sum` to `package.json`/`yarn.lock` although the comparison only stretches too far. In my opinion, the updates you get to `go.sum` *can* be compared to the updates you get to `yarn.lock`. However the cascading impact in Go can be very different between `go.mod` and `package.json`. An update to a version in `package.json` can never "force" other dependencies in the `package.json` to be updated, however an update to a single dependency in `go.mod` can have cascading effects including to `go.mod`.

Generally in JS, most people ignore the transitive dependencies and their updates, reasoning that their *direct* dependencies should be looking at those. But in Go, when you see the `go.mod` get updates then it's natural to want to look at every line/dependency, even if in theory the package you're updating is the single trigger for those other changes and in theory the changes you see are "transitive" too.

**Comment by rarkins** [comment]
Predictably I'm a firm believer in "if you update dependencies by hand, you're going to have a bad time". I welcome any ideas for bettering the way we *automate*, but have to remind first that:
1. If a "single" dependency update appears to impact `go.mod` and `go.sum` more than you like, there's nothing you can do because that's how Go Modules work
2. If you have lots of PRs open, you have a good chance that merging one will cause conflicts in the others. This is git and the only solution is "have less open at a time".

One area that *can* be improved is in the area of release notes. I am currently working on a dashboard system for reviewing updates that I think may suit some teams far better than PRs, and give a lot more flexibility in terms of UX than static Pull Request markdown does.

In the meantime, the `masterIssueApproval` config option for Go updates still seems like the best fit here. It's guaranteed that the project will remain as behind or more behind in terms of Go updates, but it may make the experience better for both Go and non-Go development team members. i.e. Go team members can selectively create PRs one at a time when they have time available for review, and non-Go members won't see so many Go PRs piling up.
