### ISSUE TITLE
Prometheus crashing; 503 error when trying to access a metrics dump; WAL file errors

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12950]
- **Sourcegraph version:** 3.18.0
- **Platform information:** Kubernetes deployment

Reported by https://app.hubspot.com/contacts/2762526/company/768958891

After reporting that Prometheus was crashing after an upgrade, I asked the customer to provide a metrics dump using the instructions at https://docs.sourcegraph.com/admin/troubleshooting#kubernetes-deployments

He responded:

```
$ kubectl -n sourcegraph exec -it prometheus-6df578bd8f-99wtf -- sh                [10:49:11]
/prometheus # wget --post-data "" http://localhost:9090/api/v1/admin/tsdb/snapshot
Connecting to localhost:9090 (127.0.0.1:9090)
wget: server returned error: HTTP/1.1 503 Service Unavailable
```

>does not pass health checks so pod was restarted here are logs

Logs have been provided in a linked private issue

**Comment by pecigonzalo** [comment]
The source of this problem was the integrated Prometheus scraping metrics from all pods in the cluster, which in some big deployments causes the memory consumption to skyrocket and trigger OOM. For more information check the comments after https://github.com/sourcegraph/customer/issues/75#issuecomment-678146313

To fix this, we updated Prometheus to drop all metrics from resource not in the Sourcegraph metric.
```
- source_labels: [container_label_io_kubernetes_pod_namespace]
        action: keep
        regex: ^$|sourcegraph
```

Unfortunately, not all deployments use the same namespace which requires a more complex fix.
