### ISSUE TITLE
Hover shows precise result, but go-to-def jumps me to fuzzy result

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#13149]
Repro:

1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/session/session.go?subtree=true#L82
1. Hover over `sessions.Session`. Observe it displays the correct documentation for the struct.
1. Click go-to-def.
1. Arrive at https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/user_session.go?subtree=true#L11:1, which is the wrong definition (the `UserResolver.Session` method instead of the `session.Session` struct).

**Comment by efritz** [comment]
github.com/gorilla/sessions is not indexed so definitions fall back to search-based code intelligence. For cross-repo to work with LSIF (currently) both source and target need to be indexed.

https://github.com/sourcegraph/sourcegraph/issues/12706 surfaces this issue so that it doesn't appear broken. There are some other heuristic we can add here to at least hint to the search-based providers that a particular moniker/package is involved, but we don't expose this data from the API today.

**Comment by efritz** [comment]
This should also be solved with whatever solves https://github.com/sourcegraph/sourcegraph/issues/13137.
