### ISSUE TITLE
Insights page fails when globbing is enabled

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#13370]
This is coming from the insights page on dotcom.

The query that ran:

```json
{"query":"
                            query SearchResultsStats($query: String!) {
                                    search(query: $query) {
                                        results {
                                            limitHit
                                    }
                                    stats {
                                            languages {
                                                name
                                            totalLines
                                        }
                                    }
                                }
                            }
                        ","variables":{"query":"repo:^github\\.com/sourcegraph/sourcegraph$"}}
```

The error: 

```
graphql: got nil for non-null "SearchResultsStats"
```

When removing the stats field and querying the alerts, it reveals that the insights page doesn't work with globbing.

```json
{
  "data": {
    "search": {
      "results": {
        "limitHit": false,
        "alert": {
          "title": "Unable To Process Query",
          "description": "Invalid glob syntax in field repo: ",
          "proposedQueries": null
        }
      }
    }
  }
}
```

Not sure who can fix this, so I tagged both web and search.

**Comment by felixfbecker** [comment]
Hmm, the query in the API console works for me: [API Console](https://sourcegraph.com/api/console#%7B%22operationName%22%3A%22SearchResultsStats%22%2C%22query%22%3A%22query%20SearchResultsStats(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20limitHit%5Cn%20%20%20%20%7D%5Cn%20%20%20%20stats%20%7B%5Cn%20%20%20%20%20%20languages%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20totalLines%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5C%22query%5C%22%3A%5C%22repo%3A%5Egithub%5C%5C%5C%5C.com%2Fsourcegraph%2Fsourcegraph%24%5C%22%7D%22%7D)

Do you maybe have a feature flag enabled for making `repo:` glob-based that is backwards-incompatible?

**Comment by felixfbecker** [comment]
The query looks correct to me so unassigning the web team

**Comment by eseliger** [comment]
Yes, I have globbing enabled, sorry forgot to mention that directly.

**Comment by felixfbecker** [comment]
@sourcegraph/search is the globbing feature supposed to be backwards-incompatible?

**Comment by keegancsmith** [comment]
This is a good point, any client which constructs a query now needs to be aware of this user setting. We likely need a new version of search to toggle on globbing. And then it shouldn't be optional since that makes it impossible for clients to generate queries (eg code-intel).

**Comment by rvantonder** [comment]
We're very much aware that the wildcard syntax is not backwards-incompatible, and if you signed up for user testing you should be aware that we outline these limitations in [the linked document](https://docs.google.com/document/d/1-6WGaYbk-AlNqjeEtvipGO4CNsojg0iLlLx98I20D5g/edit#heading=h.n0qpwg1gy359). I've updated the section to be more explicit, and added that this limits doesn't work with code insights. 

> And then it shouldn't be optional since that makes it impossible for clients to generate queries (eg code-intel).

We did not intend to make it optional for users, which is why we controlled visibility of this flag through a user testing process and point this out explicitly. We should be emphasizing in that process that you should turn the flag _off_ after your testing if you can't work with those limitations, but if you want to keep it on, more power to you--just keep in mind the limitations in the doc and that this is WONTFIX.

In any actual solution, it will have to be enabled org wide, and/or we will explore alternative (unified) syntax to address concerns. There are currently no plans to make wildcard syntax available broadly until we've consider feedback we are currently collecting. We will again invite feedback if/when we get to that stage.
