### ISSUE TITLE
Zoekt reports err invalid argument when reloading

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#13451]
Many instances of `err invalid argument` are reported by `indexed-search-0` when restarting.

```
Aug 28 12:43:15 indexed-search-0 zoekt-webserver 2020/08/28 10:43:15 reloading: /data/index/FOOBAR, err invalid argument
```

Inspecting the filesystem, there are many empty files which are not present in the other instances and I believe this is causing the error.
```
/home/sourcegraph # ls -lah /data/index/github.com%2Fawslabs%2Freal-time-analytics-spark-streaming_v16.00000.zoekt
-rw-r--r--    1 root     root           0 Jul 11 12:30 /data/index/github.com%2Fawslabs%2Freal-time-analytics-spark-streaming_v16.00000.zoekt
/home/sourcegraph # cat /data/index/github.com%2Fawslabs%2Freal-time-analytics-spark-streaming_v16.00000.zoekt
```

**Comment by keegancsmith** [comment]
Context: original slack thread https://sourcegraph.slack.com/archives/C07KZF47K/p1598468207104000

My message in that thread

> very weird. It seems "invalid argument" means error number 22 EINVAL on linux.
Note we do os.Open and we do mmap. So either of those could return EINVAL. I have no idea why this would happen, but it does seem to happen often. Does every webserver replica exhibit this behaviour?

Good find on the empty files. I don't know why these would exist to be honest. They may be very old remnants of the past. since this is our original indexed search pod (before horizontal scaling). We shouldn't be creating empty files ever in zoekt, but it is the possibility when crashing that ext4 syncs the filenames but not the data.

However, I am gonna assume this is an old issue. I have gone and deleted all empty files. We should re-open if this pops up again.

```
kubectl exec indexed-search-0 -c zoekt-indexserver -- find /data/index -type f -empty > 2020-08-28-indexed-search-0-empty-shards.txt
kubectl exec indexed-search-0 -c zoekt-indexserver -- find /data/index -type f -empty -delete
```

[2020-08-28-indexed-search-0-empty-shards.txt](https://github.com/sourcegraph/sourcegraph/files/5142444/2020-08-28-indexed-search-0-empty-shards.txt)
