### ISSUE TITLE
Make links into sourcegraph.com product more explicit

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#135]
Feedback from @goinggo:

It's much harder to get into the sourcegraph.com product now than before, because the homepage features the Chrome extension and Sourcegraph Server container more prominently. There are links into the sourcegraph.com product, but it's not clear that they lead to a usable product rather than toy examples for demo purposes.

Before, the unauthenticated homepage of Sourcegraph.com was the product itself:

![image](https://user-images.githubusercontent.com/1646931/44883152-0b8bf580-ac6b-11e8-843f-3c1dce4700d2.png)

Now it looks like this. Links into the product are visible at the top, but it's not obvious they link into a real product rather than demo examples:

![image](https://user-images.githubusercontent.com/1646931/44883200-2f4f3b80-ac6b-11e8-9261-c328d917858a.png)

The added friction makes it harder to demo Sourcegraph to new Go users. We obviously have to balance the tension between sourcegraph.com, the Chrome extension, and Sourcegraph Server, but it would be nice if it were more obvious to new users how to use the product to explore Go open source.

Goal: make it easier for new users to discover and onboard to sourcegraph.com on open source repositories without sacrificing conversion of users who are interested in the Chrome extension and/or Sourcegraph Server on private code.

Note: simply linking to the main search page is probably not a great experience for most new sourcegraph.com users, because (1) we don't have global search support yet and (2) many users might not know what to search for. Maybe we should feature "popular repositories" on this page.

**Comment by beyang** [comment]
cc @francisschmaltz

**Comment by felixfbecker** [comment]
Can we render a real HoverOverlay on the webpage and make Go-to-definition actually jump to sourcegraph.com?

**Comment by francisschmaltz** [comment]
Working on this for this iteration. Looking into making the flow match for both sites and equally easy to get between both

**Comment by ardan-bkennedy** [comment]
This describes the problem well. I was in a class and wanted to show off sourcegraph compared to golang.org. I couldn't figure out how to do a basic search for a Go package like I could do in the past. Then I installed the Chrome extension thinking I would have the ability to do it. Nothing changed. Not even sure what the extension does or how it allows me to start searching content.

**Comment by ardan-bkennedy** [comment]
I am trying to use the search site: "https://sourcegraph.com/search"

I am having difficulty bringing up the Go packages. It used to be very simple to do this.

None of this works

"golang io"
"golang.org/io"
"github.com/golang/io"

I am confused how to find this package.

This works

"repo:^github\.com/golang/crypto" for the crypto package.
"repo:^github\.com/golang/net" for the net package.

"repo:^github\.com/golang/io" DOESN'T find the io package?

I can go into Google, type "golang io" and find what I need. :(


I feel like in the past this search worked incredibly well. For me, this is the starting point to see the value in the product. "Forget about looking at documentation on golang.org, sourcegraph does it better". Because it does it better for the open source projects, think what it can do for you internally.

**Comment by dadlerj** [comment]
Hey @ardan-bkennedy, thanks for sharing this. Our search uses repository URLs, not Go package names (though that would be a great addition for Go users!). Since golang/io is a subpackage in the github.com/golang/go repo, you have to do a search that also filters on file path:

`repo:github.com/golang/go file:src/io`

The other two searches work because those packages are stored in their own repositories (at github.com/golang/crypto and github.com/golang/net)

And Sourcegraph for Chrome (the browser extension) actually provides code intelligence right inside of GitHub, so you can get hover tooltips, go to definition, etc. (see the screenshot below). It also provides the ability to do a search from the URL bar (type `src` and hit Tab). But it doesn't provide any special support for Go packages.

![image](https://user-images.githubusercontent.com/5589410/45116807-c2272480-b108-11e8-9ace-e6f048691c93.png)

The high level problem you're pointing out here (that it's hard to use Sourcegraph.com for a simple search) does fit in this issue though... We will be working on updates here soon — would you mind if we send you ideas for updates to get your thoughts in the future?

**Comment by ardan-bkennedy** [comment]
I'm always available. 

it wasn't clear to me initially that if I installed the chrome extension, I could go to github and start navigating. If in that header on the home page to mentioned this specifically, it would help.

**Comment by ardan-bkennedy** [comment]
But a simple search feature on the home page, which was there in the beginning, would be great.

**Comment by francisschmaltz** [comment]
This is resolved with our new home page design living on Sourcegraph.com/welcome
