### ISSUE TITLE
Browser extension not showing hovers on GitLab

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1353]
Repro:

1. Go to https://gitlab.com/gitlab-org/gitlab-runner/blob/master/helpers/service/simple.go
2. See no hovers, no "View File" button

Note that the repo and file is properly mirrored to Sourcegraph: https://sourcegraph.com/gitlab.com/gitlab-org/gitlab-runner@master/-/blob/helpers/service/simple.go?diff=e77e13d679a9bd87c2357e60793a18792ebb968d.

**Comment by ijsnow** [comment]
![screenshot 2018-12-14 10 59 34](https://user-images.githubusercontent.com/11557758/50021932-70a3f680-ff8f-11e8-8237-1e4971040ed4.png)

Could you provide more information or try again? Seem to be working just fine for me.

**Comment by ijsnow** [comment]
The problem was that you weren't logged in and I needed to use the GitLab API for code intelligence which needs authentication. However, [single file code views don't need the API](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/client/browser/src/libs/bitbucket/file_info.ts#L14-19) so it should still work for the link in the repro steps above.
