### ISSUE TITLE
dbworker: Cleanup stalled processing jobs

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#13602]
When a worker is processing a job and gets killed for any reason (service restart, panic), I believe the job row is marked as `processing`  forever in the job sync table and never gets put back as `queued` when the service is restarted.
It would be great if we had a way to ensure these rows are cleaned up if they are in a `processing` state for too long and/or if they are not locked.

**Comment by efritz** [comment]
🎉 

https://github.com/sourcegraph/sourcegraph/blob/main/internal/workerutil/dbworker/resetter.go

**Comment by efritz** [comment]
Wherever a dbworker is used you should also have _some_ process running the resetter process. This will do exactly what's described here: find all processing-but-not-locked records older than N seconds and put them back to queued.

In the case that it's a super large input that will continually cause the processor to OOM, there's a limit to how many times it can be reset to stop from an infinite crash loop due to bad/malformed/large input.

**Comment by asdine** [comment]
Awesome, thank you!
