### ISSUE TITLE
Last breadcrumb should not be a link on non-repo pages

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#13651]
#### Current Behavior

When the breadcrumb element is a link, it renders as a link regardless of its depth.

#### Desired Behavior

The deepest breadcrumb should be rendered as plain text even when it is a link.

The current behavior should be maintained for repo pages.

**Note**: Make sure that consumers of the Breadcrumbs API do not need to be aware of this logic as a result of the solution.

**Comment by felixfbecker** [comment]
Should it be? A link allows the last element to be right clicked for "Copy link address" and allows clicking it to reset any `#` hash fragment (e.g. line in the file view, but could also be e.g. a certain comment in a campaigns timeline view).
What speaks for making it plain text?

**Comment by AlicjaSuska** [comment]
Breadcrumbs should look like this:
<img width="1286" alt="Screenshot 2020-09-08 at 15 30 32" src="https://user-images.githubusercontent.com/20326070/92482764-45901a80-f1e8-11ea-872f-61cac12c9e83.png">

@tjkandala in the example that we were discussing during our last call, the last breadcrumb in the web view (marked as 'Page name' in the example above), was blue instead of grey. It was correct on the extension details page (extension name was grey) but on the extensions registry 'Extensions' breadcrumb was blue, should be grey. That was the only correction :)

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
