### ISSUE TITLE
Record and expose LOC metric in Zoekt

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#13713]
Context in [RFC 234](https://docs.google.com/document/d/1a1CMFfTMEdnYXqa36ud64c_CHXWNXlmezVB8Wvku00E/edit?disco=AAAAG6c9nLs) 

@keegancsmith: Please provide guidance on your architectural / design thoughts on this approach!

**Comment by keegancsmith** [comment]
Every zoekt shard computes ([newLinesIndices](https://github.com/sourcegraph/zoekt/blob/master/write.go#L183)) an index ([newlinesIndex](https://github.com/sourcegraph/zoekt/blob/master/indexdata.go#L37)) of all the newlines per document. This index is a `[]uint32` slice of offsets in the file. The way the index is encoded is sized deltas. This means the first value is the length, ie the number of "\n" that appear in the file. Follow the trail from `readNewlines` to understand how to just read the size of each list efficiently. This will require writing code to do that, but is pretty straight-forward.

The bigger concern is how do we expose this information via RPC. There are two possible approaches:

-   A new endpoint which just returns this number over all shards
-   Optionally populating a new field on [zoekt.RepoStats](https://github.com/sourcegraph/zoekt/blob/master/api.go#L240).

It is probably easiest to the first one. I would recommend exporting [rpc.client](https://github.com/sourcegraph/zoekt/blob/master/rpc/rpc.go#L43), returning it (instead of zoekt.Searcher) and adding a new method to it which does what we want.

The second option is interesting because it would allow you to do queries like `repo:foo stat:linecount` and get back line counts for all repos matching foo :) but that is def overkill and it requires touching a lot more parts of the codebase. We wouldn't want to just extend zoekt.RepoStats to always populate the value since it isn't free to compute (all the other values are already computed). Storing the computed number of newlines in the index is an option, but that would trigger a reindex of all repos which seems like overkill for the value we want to provide.

**Comment by keegancsmith** [comment]
@unknwon and I will pair on this tomorrow morning. I will try and ensure this is complete by EOD tomorrow, so we can comfortably get the feature in by branch cut. Reason I am context switching away from streaming search is this is an important to get in soon, and I have a lot of experience in zoekt and gitserver.

@christinaforney @juliasourceress @dadlerj Outlining what will be computed and sent in pings. Just want to confirm before working on this that its good to send in pings, and captures everything you want.

First from indexed search:

```go
// ExtendedRepoStats captures repository statistics computed from zoekt
// indexes.
type ExtendedRepoStats struct {
  // RepoStats is the existing statistics we capture in Zoekt. In particular
  // this records the total number of bytes we have indexed (ContentBytes).
  RepoStats

  // NewLinesCount is the number of newlines "\n" that appear in the
  // repository. This is not exactly the same as line count, since it will not
  // include lines not terminated by "\n" (eg a file with no "\n", or a final
  // line without "\n").
  NewLinesCount int64
}
```

From gitserver

```go
// RepoStats is an aggregation of statistics from a gitserver.
type RepoStats struct {
  // Repos is the number of cloned repositories.
  Repos int

  // GitDirBytes is the amount of bytes stored in .git directories.
  GitDirBytes int64
}
```

Open questions:

-   Do we want to report separately the counts of the default branch and other indexed branches? Zoekt does deduplication across branches, so we just report the sum (with only counting dedupped files once).
-   Is it alright to just count "\n"? IE we won't count a line if it is at the end of the file and its missing the trailing "\n". Checking that extra condition makes computing this orders of magnitude slower.
-   Do we also want to report anything else from [zoekt.RepoStats](https://github.com/sourcegraph/zoekt/blob/master/api.go#L240)?
-   Is there anything else we want to compute on gitserver?

**Comment by dadlerj** [comment]
Awesome, thanks!

>Do we want to report separately the counts of the default branch and other indexed branches? Zoekt does deduplication across branches, so we just report the sum (with only counting dedupped files once).

Yeah, ideally we'd re-dup the counts... We'd want to report: 

* total count for all default branches
* total count for all other indexed branches (without the de-duping effects if lines are shared between these and the default branches, or even if they're shared across these other non-default branches)

>Is it alright to just count "\n"? IE we won't count a line if it is at the end of the file and its missing the trailing "\n". Checking that extra condition makes computing this orders of magnitude slower.

This seems fine to me... I have trouble imagining that this would bump a customer from one pricing tier to another, even with a gigantic number of files (100k+?).

>Do we also want to report anything else from zoekt.RepoStats?

I don't think so. I'm not even sure if we intend to capture repo count like you have above in `RepoStats`. I defer to Julia and Christina on this.

>Is there anything else we want to compute on gitserver?

Not sure. The RFC only specified three things I believe, so I think we're good with those three!

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
