### ISSUE TITLE
Enable new ref panel by default

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#13722]
**Currently**, the 'References' panel closes after clicking on one of the references. It takes the user completely out of the context. To come back to the references list, the user needs to click on 'Find references' every single time.

Please, see the [recording 1](https://drive.google.com/file/d/12h3eLWzsCWYJkmw3-j20Q6vA4EJHo_Ic/view?usp=sharing) and [recording 2](https://drive.google.com/file/d/12h3eLWzsCWYJkmw3-j20Q6vA4EJHo_Ic/view?usp=sharing) from the recent usability testing. The tester explains the flow and reasoning.

**Proposition:**
Keep the 'References' panel open after clicking on one of the references to provide a better experience for users who want to explore more items from the list.

To improve the experience, we can highlight the currently viewed reference and display the number (ex. 'Currently viewing: reference 1 of 100').

![Reference-highlight-count](https://user-images.githubusercontent.com/20326070/92615283-3c24b200-f2bd-11ea-8c87-ddb9582ad403.png)

@sourcegraph/code-intel @quinnkeast @rrhyne @christinaforney @poojaj-tech - looking forward to your feedback on this idea :)

**Comment by gbrik** [comment]
Thanks for filing, IMO we definitely want to do this! I added it to the tracking issue for UI improvements.

**Comment by AlicjaSuska** [comment]
Great, I've created the screens in [Figma](https://www.figma.com/file/1OJmsXQtb9mnYBdlyRXtgx/13722-Keep-References-panel-open-after-clicking-on-one-reference-Review?node-id=0%3A1)

Changes:
- background-color of the currently viewed Reference: body-bg-1 in dark theme, body-bd-4 in light theme
- small-text: 'Currently viewing: reference <strong> 1 of 100 </strong>' (strong text should be semi-bold)

**Comment by AlicjaSuska** [comment]
@macraig do you think it can be done any time soon?

**Comment by efritz** [comment]
(I think) I am capable of doing these changes, but would like to tag someone on the @sourcegraph/web team to estimate how much of an effort the change in behavior would be here (since I'm not super familiar with the code here; seems trivial but might be surprising).

**Comment by macraig** [comment]
@AlicjaSuska I agree with Eric, we should estimate the effort first, but provided it's something trivial I think we can add it to one of our next plannings. Thanks for filing this and helping us improve our UI!

**Comment by felixfbecker** [comment]
I'm actually surprised it doesn't, that's unexpected to me. When clicking references, they are links that need to update the URL. The references panel is open whenever there is a URL param in the URL. What could be happening here is that the references links do not include that URL param anymore so it gets removed, which closes the panel. So I would check where those links are rendered.

**Comment by olafurpg** [comment]
For what it's worth, I like how the Chromium code search displays "find references". Example https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ui/webui/webui_util.cc;l=42;drc=24842514ee052f9b2e785bf1a06f33ac90a710a4;bpv=1;bpt=1

The references stay in the bottom panel until you explicitly press a link to open a specific reference in the main window.


https://user-images.githubusercontent.com/1408093/105820841-5fc16e00-5fba-11eb-997c-8eadef141f79.mp4

**Comment by jjinnii** [comment]
Updated Alicja's original designs to reflect current UI. [Upon selection in dark mode](https://www.figma.com/file/1OJmsXQtb9mnYBdlyRXtgx/%2313722-Keep-'References'-panel-open-after-clicking-on-one-reference-%5BReview%5D?node-id=209%3A6788), bg color for selected reference is color-bg-3/dark. [For light mode](https://www.figma.com/file/1OJmsXQtb9mnYBdlyRXtgx/%2313722-Keep-'References'-panel-open-after-clicking-on-one-reference-%5BReview%5D?node-id=209%3A5559), bg color for selected reference is body-bg/Light. 

I've excluded the "Showing 1 of x results" for now, as the root of the problem here is:
* Ensuring that the reference panel stays open after user navigates to reference
* Communicating to user what reference they're at

I will think about where we can communicate the number of results when tackling [issue 28480](https://github.com/sourcegraph/sourcegraph/issues/28480) for adding reference panel filters.

**Comment by mrnugget** [comment]
> What could be happening here is that the references links do not include that URL param anymore so it gets removed, which closes the panel. So I would check where those links are rendered.

I stumbled upon the same thing yesterday and reading your comment today made me dig in: https://github.com/sourcegraph/sourcegraph/pull/30021

Keeping it open works now, but the problem is that the whole app reloads, including the references, which makes this feel not that great.

That's also the problem with implementing "Communicating to user what reference they're at". If the references are reloaded we might not have the same reference available when navigating to a new file. Example: user clicked on reference 36/500 and when landing on a new page only the first 10 references are loaded.

**Comment by jjinnii** [comment]
> Keeping it open works now, but the problem is that the whole app reloads, including the references, which makes this feel not that great.

@mrnugget  Could you clarify this point for me? Sorry not fully understanding what's happening and what you mean by "not great" here. I'm assuming the whole app reloading refers to the entire page reloading when a user clicks into a reference -- is not great the performance/buffering time it takes for the app to reload and then re-expose the reference panel? 

> That's also the problem with implementing "Communicating to user what reference they're at". If the references are reloaded we might not have the same reference available when navigating to a new file. 

If a user clicks into a reference at Point A  to get to Point B -> does the user want to see the references that were available to them at Point A, as opposed to the new list at Point B? Is what references are available at Point B not necessary for a user at all? 

Thanks for looking into this!

**Comment by mrnugget** [comment]
> @mrnugget Could you clarify this point for me? Sorry not fully understanding what's happening and what you mean by "not great" here

Take a look at the second video I put in the PR description of https://github.com/sourcegraph/sourcegraph/pull/30021. 

> I'm assuming the whole app reloading refers to the entire page reloading when a user clicks into a reference -- is not great the performance/buffering time it takes for the app to reload and then re-expose the reference panel?

Correct. In the second video you can see how everything reloads - including the list of references. The reloading also amplifies all the pain points described in https://github.com/sourcegraph/sourcegraph/issues/30022.

> If a user clicks into a reference at Point A to get to Point B -> does the user want to see the references that were available to them at Point A, as opposed to the new list at Point B? Is what references are available at Point B not necessary for a user at all?

I think _ideally_ the list wouldn't change and the user can click through the references until they find the one they need. (Adding filtering and ability to delete entries from that list would then turn it into a proper tool)

The problem is that the list of references is paginated: the user clicks "Find references", a few get loaded, user scrolls down, a few more get loaded, user scrolls down, a few more get loaded. They never know how many references there are and how many of them they have loaded. When they then click on a reference and it results in a navigation to a different file then this whole list is reloaded and the user starts from scratch and has to scroll, load, scroll, load, scroll, load to get to the point where they left of.

That's the current state at least and my PR doesn't fix any of that, it only makes sure that the references panel stays.

**Comment by jjinnii** [comment]
@mrnugget I was reviewing your [comments in the plan document](https://docs.google.com/document/d/1E_6hgnFlRutelU4QI8PtFfOrxrq_wjw0UMbMMtAuQ4g/edit#heading=h.rym8fboiygpn) and I just wanted to clarify to make sure I understand your point. The "keep ref panel open" and "support preview for refs" are not technically contingent on each other (i.e. from an implementations perspective, it's not that one can't be done without the other), right? 

When you say "the "preview references/implementations in a side panel" is actually a solution to "Stay open when navigating"" - you just meant that if a user scrolls through a large list of references and decides to navigate to a file, it'd be painful UX to lose their place in the ref panel, especially since we'd re-load the panel to update the new token location right?

**Comment by mrnugget** [comment]
> When you say "the "preview references/implementations in a side panel" is actually a solution to "Stay open when navigating"" - you just meant that if a user scrolls through a large list of references and decides to navigate to a file, it'd be painful UX to lose their place in the ref panel, especially since we'd re-load the panel to update the new token location right?

No. I meant exactly that: in order for the reference panel to "Stay open when navigating" I implemented the "preview references/implementations in a side panel". See my comment here https://github.com/sourcegraph/sourcegraph/issues/13722#issuecomment-1019872005 and the videos it links to here https://github.com/sourcegraph/sourcegraph/pull/30021. The latter is a PR that implements "stay open when navigating" as good as it gets _with our current implementation of the reference panel that relies on the URL to keep track of which token to show the references for_. 

In the plan document you linked to I described the problem like this:

> There's 3 things involved here:
> 1. Panel opens showing references for the token given in the URL
> 2. When clicking on an item in the list of references and navigating to it, we need to update the URL to reflect the new location, updating the token in the URL
> 3. The panel (if it stayed open) would now reload the list of references, because the token in the URL changed. It's still the same token, but at a different location, so the order might be different (and if we're using search-based code intel, then it might be completely different).

But let me try to put it in different words. This describes the current state of the non-experimental reference panel on Sourcegraph.com:

1. User clicks on the definition of a token
2. The URL will get an `#tab=references` appended to it, along with the line and character. Example: [.../-/blob/internal/batches/executor/coordinator.go?L63:6#tab=references](https://sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/internal/batches/executor/coordinator.go?L63:6#tab=references)
3. The reference panel shows up **because** the URL now contains `#tab=references`
4. The list of references is just a list of links. Example link: [...src-cli@da111edf06332698519160c4d93be3a506408111/-/blob/internal/batches/service/service.go?L289:18](https://sourcegraph.com/github.com/sourcegraph/src-cli@da111edf06332698519160c4d93be3a506408111/-/blob/internal/batches/service/service.go?L289:18) **NOTE:** the link does _not_ contain the `#tab=references` addition
5. User clicks on the link
6. Browser/our webapp navigates to URL
7. Since the URL doesn't contain `#tab=references`, the reference panel disappears

What I tried in #30021 was to change point 4 here: I added `#tab=references` to each link in the list of references. But that has problems, as described above, but now we can see why:

- Original URL: `... coordinator.go?L63:6#tab=references`
- URL after navigating to reference: `... service.go?L289:18#tab=references`

The reference panel would stay open but it would load the **references of a different token**. _We_ know that it's the same token, because it's just a reference of the one we came from, _but the reference panel doesn't_. And once it sees `... service.go?L289:18#tab=references` it will load the references for that token.

Which means we load the list again, which means we lose our position in the list of references (because it's a different list).

So the question is: how do we allow the user to navigate through references while keeping the panel open and not losing position in the list?

And my answer was: I can't find a way to do that when navigating to the references via URL. We would either need to keep _more_ state in the URL (i.e. not only "show references for this token" but also "show references for this token, but show this token") or (and that's what I did) we don't navigate to the references on click, but open their definition in a little code blob to the side and let the user decide when to navigate to that definition in the "big view".

And there are even more solutions to this. For example: we could try to navigate the user to the reference but **not** update the URL. The problem with that is that it breaks one of the conventions in our app: the URL now doesn't point to the view/location the user is looking at.

It's all intertwined: how we navigate from references to reference, how we point (via URL) to a specific location, when we open the reference panel (in the current version of the new experimental ref panel I open the panel on click, without updating the URL and navigating away, for example), when we hide it, how you can link to a location etc.

I hope that makes sense. I highly recommend that you try this out yourself on Sourcegraph.com with the old panel and with the new panel and see how they differ and consider why.

**Comment by Numbers88s** [comment]
@mrnugget Is this still unresolved?

**Comment by mrnugget** [comment]
The new reference panel fixes this with the preview window. But since it's not the default and still behind a feature flag, I'd say it's still unresolved, yes.
