### ISSUE TITLE
SourceGraph fails to find results in repos unless "repo:<prefix>" is specified. Reports "nnn Repositories Not Found"

### ISSUE THREAD

**Issue by rthille** [sourcegraph/sourcegraph#13840]
- **Sourcegraph version:** 3.19.2
- **Platform information:** `uname -a` output: "Linux IP-REDACTED 4.X.Y-REDACTED #1 SMP Wed May 13 01:31:52 UTC 2020 x86_64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz GenuineIntel GNU/Linux", AWS, Chrome Version 85.0.4183.102, "Docker version 19.03.8, build afacb8b7f0" 

#### Steps to reproduce:

1. Perform search for term you know is present in a repo. In my case, searching for 'download-tags' (without quotes) fails and the result line says: "0 results in 0.05 seconds     825 repositories not found" (there are 1025 repos configured)
2. Perform same search with addition of "repo:in", where "in" is a prefix of the repo(s) where you know the string is present. In this case, the result line says: "7 results in 0.04 seconds  359 repositories not found"

#### Expected behavior:
Sourcegraph finds the string in the repo (infra/[redacted]) without having to specify the prefix of the repo.

#### Actual behavior:
Sourcegraph does not find many results unless a "repo:<prefix>" term is added to the search specification.

This behavior started recently, after we upgraded from 3.16.1 to 3.19.2 (via a 3-stage upgrade, deploying 3.17.3, then 3.18.0, and finally 3.19.2).
The admin interface shows all 1025 repositories cloned and none in the "Not cloned" or "Needs index" state.

Site info:
{
  "site": {
    "disablePublicRepoRedirects": false,
    "search.index.enabled": false,
    "extensions": {
      "allowRemoteExtensions": [
        "sourcegraph/python",
        "sourcegraph/typescript",
        "sourcegraph/go",
        "sourcegraph/cpp",
        "sourcegraph/r",
        "sourcegraph/ruby",
        "sourcegraph/scala",
        "sourcegraph/swift",
        "sourcegraph/kotlin",
        "sourcegraph/powershell",
        "sourcegraph/rust",
        "sourcegraph/shell",
        "sourcegraph/git-extras",
        "REDACTED/scrolls-sourcegraph"
      ]
    },
    "experimentalFeatures": {
      "andOrQuery": "enabled"
    },
    "auth.providers": [
      {
        "type": "builtin"
      },
      {
        "allowSignup": true,
        "clientID": "REDACTED",
        "clientSecret": "REDACTED",
        "displayName": "HOSTNAME",
        "type": "HOSTNAME",
        "url": "https://HOSTNAME.REDACTED.TLD"
      }
    ],
    "externalURL": "https://SGHOSTNAME.REDACTED.TLD",
    "htmlBodyBottom": "<script>localStorage.setItem('DismissibleAlert/performanceWarningAlert/dismissed', 'true')</script>",
    "licenseKey": "REDACTED"
  },
  "externalServices": {
    "GITHUB": [
      {
        "url": "https://HOSTNAME.REDACTED.TLD",
        "token": "REDACTED",
        "repositoryQuery": [
          "org:REDACTED archived:false fork:no",
          "org:REDACTED archived:false fork:no",
          [28 more org:<org-name> queries redacted]
        ]
      }
    ]
  },
  "settings": {
    "subjects": [
      {
        "__typename": "DefaultSettings",
        "settingsURL": null,
        "contents": {
          "extensions": {
            "sourcegraph/cpp": true,
            "sourcegraph/git-extras": true,
            "sourcegraph/go": true,
            "sourcegraph/kotlin": true,
            "sourcegraph/powershell": true,
            "sourcegraph/python": true,
            "sourcegraph/r": true,
            "sourcegraph/ruby": true,
            "sourcegraph/rust": true,
            "sourcegraph/scala": true,
            "sourcegraph/shell": true,
            "sourcegraph/swift": true,
            "sourcegraph/typescript": true
          }
        }
      },
      {
        "__typename": "Site",
        "settingsURL": "/site-admin/global-settings",
        "contents": {}
      },
      {
        "__typename": "User",
        "settingsURL": "/users/REDACTED/settings",
        "contents": {
          "git.blame.lineDecorations": true
        }
      }
    ],
    "final": {
      "extensions": {
        "sourcegraph/cpp": true,
        "sourcegraph/git-extras": true,
        "sourcegraph/go": true,
        "sourcegraph/kotlin": true,
        "sourcegraph/powershell": true,
        "sourcegraph/python": true,
        "sourcegraph/r": true,
        "sourcegraph/ruby": true,
        "sourcegraph/rust": true,
        "sourcegraph/scala": true,
        "sourcegraph/shell": true,
        "sourcegraph/swift": true,
        "sourcegraph/typescript": true
      },
      "git.blame.lineDecorations": true
    }
  },
  "alerts": null
}

**Comment by slimsag** [comment]
The problem and repositories reported missing indicates that the search indexer is in accessible over the network or it is failing to index your repositories.

This is a single-docker container deployment, I presume? How many repositories do you have on it? What do the logs look like? (You can send them to stephen@sourcegraph.com)

**Comment by rthille** [comment]
Yep, single-docker container deployment, 1025 repos.  When I upgraded our test system I saw the same issue but it complained about being unable to find only ~430 repos (don't remember the exact number), but editing the repo search spec seemed to clear that up.  Now both the test and prod SourceGraph systems are reporting the same number of repos not found (which initially made me think it was the github server, though the fact that including the `repo:<prefix>`) in the search finds them makes me skeptical of that.

**Comment by kentwberry** [comment]
Has this been resolved?

We are experiencing the same issue after upgrading to 3.19.1.  Un-scoped searches are not finding all instances of a string, but when we add "repo:<gitlab-group1>/<gitlab-group2>" it finds the expected instances of the string.  Additionally, the repo path must include the immediate parent group of the project in order to find all the instances.  In other words "repo:<gitlab-group1>" won't work if the instances are in a project under gitlab-group2.

**Comment by dadlerj** [comment]
Hey @rthille it looks like you have `"search.index.enabled": false,` set in your configuration. With that value set, Sourcegraph will not index any code—all searches will be done in real-time. If you delete that line, this problem should go away. 

Note that Sourcegraph's indexer will add some larger memory requirements, so that's something to keep track of.

**Comment by juliasourceress** [comment]
Hi @rthille checking in to confirm whether that resolved your issue?

**Comment by kentwberry** [comment]
We don't have search.index.enabled set to false and we are experiencing this.  It's becoming increasingly frustrating.  We are using version 3.19.1.

**Comment by christinelovett** [comment]
Hi @kentwberry thanks for your note - we have an open support ticket right now to address this with your colleague. If you'd like to open a separate ticket where we can work through troubleshooting please submit to support@sourcegraph.com! Thank you :-)

**Comment by slimsag** [comment]
FYI for anyone coming here this can be caused by a number of different things, it is best to contact us via support@sourcegraph.com with all your details so we can help you with your specific situation.

A few of the things that could cause this:

- The repository is a fork repository (excluded from search results by default) and `fork:yes` is not specified in the search query.
- The repository is an archived repository (excluded from search results by default) and `archived:yes` is not specified in the search query.
- `"search.index.enabled": true,` is NOT in your site config (it should be and should be `true`).
- There is an issue indexing the repository, check the logs of `repo-updater` and/or `search-indexer`
- The search index is unavailable for some reason (try the search query `repo:<the_repository> index:only` If it returns no results, the repository has not been indexed.)

**Comment by kentwberry** [comment]
Hi Stephen,

Thank you for the troubleshooting tips.  It is the search.index.enabled setting.  I assumed if it wasn't present indexes would be created.  I updated the site config and that seems to have resolved the issue.

Thanks again,

Kent

**Comment by rthille** [comment]
@juliasourceress Hi, sorry I didn't get back to you sooner (I think I did via email to support), I don't check github notifications often :-)
Yes, switching the "search.index.enabled" setting to true solved the issue.  Thanks!
