### ISSUE TITLE
"No definition found" shown when definition is still loading

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1387]
It used to be that while the definition was still loading, a loader would be shown on the button.
Now, "No definition found" is shown. The user has to repeat the action at arbitrary intervals to find the definition once loaded.

![2018-12-13 02 23 11](https://user-images.githubusercontent.com/10532611/49937518-37a84b00-fed7-11e8-98c1-2d6f78e0aa83.gif)

This may be caused by basic code intel but not sure.

**Comment by lguychard** [comment]
This was due to having both basic-code-intel and lang-typescript enabled.

This is fixed now, with the following behaviour: no Go to definition button is shown if no definition is found or definition is still loading.

![image](https://user-images.githubusercontent.com/1741180/51189700-dbbf5080-18e0-11e9-8275-207b2903bc54.png)
