### ISSUE TITLE
Inconsistent repo and repogroup query semantics

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#14004]
Current behavior for `repogroup:x repo:y` implies any repos in `x` OR repo `y` (union). Our comments say ['intersection'](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dd88e72f609123b3d5cfd3d654af6249916ed6ca/-/blob/cmd/frontend/graphqlbackend/search.go#L768) but mean 'union'. We have chosen space to mean intersection (`and` not `or`), so the behavior is inconsistent with the convention, even though it might seem more intuitive. We really do need to care about being consistent in our query language (i.e., when we say space means `and`, it means `and`). If the more intuitive behavior here is `or` and not `and`, we should nudge the user to modify the query as needed. If we don't do this, the alternative is that we have to somehow heuristically contextually pick whether a space implies `and` or `or` depending on the filters, queries may not behave predictably, and this is just not an acceptable way to maintain or grow the language.

**Comment by novoselrok** [comment]
I don't think so. For example:

Query `context:@sourcegraph/all repo:^github\.com/sourcegraph/sourcegraph$` returns the specified repo (sourcegraph/sourcegraph is in the context). Meanwhile query `context:@sourcegraph/all repo:^github\.com/novoselrok/codesnippetsearch$` returns no results because `novoselrok/codesnippetsearch` is not in the context. If I got my thinking right, this can be closed with the repogroup removal.
