### ISSUE TITLE
dbworker: Pass sql options to TransactableHandle

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#14044]
It would be nice if there was a way to customize how the transaction is created by the worker.
We have a case where we need to change the serialization level of that transaction to `Read Committed` instead of `Serializable`.
Unless perhaps the dbworker package is sensitive to transaction isolation levels?

**Comment by efritz** [comment]
No, this should be easy to do.

**Comment by efritz** [comment]
This _should_ be covered in https://github.com/sourcegraph/sourcegraph/pull/14063. Does this give you enough freedom here? I left out being able to set ReadOnly since I think that's counter to how this workflow works, but I don't think that any of the isolation levels should be in direct conflict, although I could be wrong here.

Could you help me with a bit of due diligence here? The previous assumption was that SKIP LOCKED would skip any records that are selected FOR UPDATE within a transaction, but I'm not sure if that holds for all isolation levels. Can you comment on this at all?

**Comment by asdine** [comment]
To my understanding, `SELECT ... FOR UPDATE [SKIP LOCKED]` and isolation levels are orthogonal. FOR UPDATE will lock the row for the current transaction, regardless of its isolation level, until that transaction is either committed or aborted, and SKIP LOCKED will skip that row.
I tested manually using 2 psql instances and it works as described above.
We still need to do some QA on PR #13483 to validate that setup once and for all but I think we can safely merge #14063.
