### ISSUE TITLE
focus-visible polyfill styles don't work on sourcegraph.com

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#14085]
<img width="395" alt="Screen Shot 2020-09-23 at 1 25 47 AM" src="https://user-images.githubusercontent.com/37420160/93970828-dadcf400-fd3c-11ea-8ff9-c3a4ea0eedcc.png">

The `focus-visible` class is still applied, but without the proper focus styles. The new toggles have no focus ring. This only happens on sourcegraph.com, not locally. Could changes to the postcss config have caused this regression? Autoprefixer seems to work, though. cc @felixfbecker

**Comment by felixfbecker** [comment]
Tracked the problem down to the CSS minifier (CSSNano) merging rules with the same selector in production builds. The `:focus-visible` PostCSS transform creates duplicate rules, but CSSNano combines them, which causes browsers that don't yet recognize `:focus-visible` to discard the entire rule. This was fixed in https://github.com/cssnano/cssnano/issues/642 but is not yet released.
