### ISSUE TITLE
Simplify repo.Store interface

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#14092]
The repos.Store interface is very large. Can we reduce it by using the DBStore directly in the Syncer 
and only exposing methods on the store interface that are required outside of the package?

**Comment by ryanslade** [comment]
I'm think we can pair on the initial design and then one of us can implement it

**Comment by asdine** [comment]
### Proposal

Remove the repo-updater store and its different implementations, move the generic methods to internal/db, and create a repo-updater/internal/dbStore with methods specific to repo-updater logic.

#### Motivation

Because we have a shared database setup, any service should be able to access data from anywhere. There is already an ongoing work to provide stores for our different domains, we should go in that direction.
Currently, repo-updater and the campaigns code both access the same tables, and the campaigns code needs to import that store into their code. This gives the false impression that repo-updater owns the `repo`, `external_services` and `èxternal_service_repos` tables while there is currently no strong reason why it would be the case. It also creates some weird coupling between both these services.
However, that doesn't mean that table ownership is not a thing, the `external_service_sync_jobs` table is a good example of tables that shouldn't be updated by anything other than a single service.

#### Proposed changes

**internal/db/repos.go**

- [ ] Modify `Get`, `GetByName`, `GetByIDs`, `GetReposSetByIDs` and `List` to return repos with their associated sources
- [ ] Add a `Create` method:

```go
func (s *repos) Create(ctx context.Context, repos ...*types.Repo) error
```

- [ ] Add a `Delete` method:

```go
func (s *repos) Delete(ctx context.Context, ids ...int64) error
```

- [ ] Replace all calls to repo-updater's `ListRepos` with `internal/db/repos#List`
- [ ] Replace all calls to repo-updater's `Insert` with `internal/db/repos#Create`
- [ ] Replace all calls to repo-updater's `Delete` with `internal/db/repos#Delete`

**internal/db/external_services.go**

- [ ] Add an `Upsert` method:

```go
func (*ExternalServicesStore) Upsert(ctx context.Context, svcs ...*types.ExternalService) error
```

- Replace all calls to repo-updater's `UpsertExternalServices` with `internal/db/ExternalServicesStore#Upsert`
cmd/repo-updater/internal/store.go
- Replace all calls to repo-updater's `ListExternalServices` with `internal/db/ExternalServicesStore#List`

**cmd/repo-updater/internal/store.go**

- [ ] Create a Store with the following methods

```go
// Concrete type with baked-in observability
type Store struct{}

ListExternalRepoSpecs(context.Context) (map[api.ExternalRepoSpec]struct{}, error)
UpsertRepos(ctx context.Context, repos ...*Repo) error
UpsertSources(ctx context.Context, inserts, updates, deletes map[api.RepoID][]SourceInfo) error
SetClonedRepos(ctx context.Context, repoNames ...string) error
CountNotClonedRepos(ctx context.Context) (uint64, error)
CountUserAddedRepos(ctx context.Context) (uint64, error)
EnqueueSyncJobs(ctx context.Context, ignoreSiteAdmin bool) error
```

**Comment by tsenart** [comment]
What's the rationale for having a separate repo updater store still? Would it make sense to go all the way and have a single one, as well as having only `types.Repo` and `types.ExternalService` rather than having also `repos.Repo` and `repos.ExternalService`?

**Comment by asdine** [comment]
Some queries only make sense in the context of repo-updater, like `UpsertRepos`, `EnqueueSyncJobs`, `CountNotCloned`. The methods of the other stores in `internal/db` seem very generic (Create, List, GetByFoo, Delete, etc.), it felt wrong to just move everything to it.

**Comment by tsenart** [comment]
> The methods of the other stores in internal/db seem very generic

If that's the case, and I don't think it is universally, that'd not be by design. I'm not yet convinced of the value of maintaining two stores and two sets of types.

**Comment by mrnugget** [comment]
I get the argument that it's confusing to have many stores, especially when they touch not only the same database but also the same tables. That being said: in campaigns I think we profited greatly by having our own `campaigns.Store` in which we could do what we want, encapsulating our logic in a single place. The story for `repos.Store` might be different, since it allows accessing two tables that are used everywhere: `repos` and `external_services`, which is also why we used it in campaigns.

But there's a second argument for having separate stores: the `internal/db` store uses a global database connection that makes it harder to test the code and, *most importantly*, makes it harder or near impossible to share transactions.

Right now we can share transactions between `campaigns.Store` and `repos.Store` (and the code intel stores), but whenever we need to use something in `internal/db` we lose our transactions.

Wouldn't a better approach be to convert `repos.Store` to use `*basestore.Store` and use its utility functions to get rid of a lot of duplicated code and then, slowly, migrate `internal/db` to also use `*basestore.Store`, so that we could have different domain-specific stores but use the `basestore.Store` interface to share transactions between them?

That was also the idea in https://github.com/sourcegraph/sourcegraph/issues/11678 and https://github.com/sourcegraph/sourcegraph/issues/11676.

**Comment by asdine** [comment]
> If that's the case, and I don't think it is universally, that'd not be by design. I'm not yet convinced of the value of maintaining two stores and two sets of types.

Regarding maintaining two sets of types, I totally agree we should not do that regardless of the solution.
Regarding maintaining one generic store + custom stores specific to a particular service, there are some cases where we believe it's dangerous to use certain existing methods. For example, `UpsertRepos` doesn't write the sources to the `external_service_repos` table because doing that requires some logic that is specific to repo-updater (computing a diff between repos, making sure there are no duplicate, ... basically the content of the `SyncExternalService` function). If this function is exposed in the shared store, it can be very misleading.
The same thing goes for `EnqueueSyncJobs`, which is very specific to repo-updater.

I'm just afraid that we would end up with shared stores that contain lots of methods that are unusable outside of the service that added them.

What we were picturing is the following, though this is not part of the proposal above, this is the end goal:

- A powerful `*basestore.Store` with baked-in observability, nested transaction support etc.
- Shared generic stores in `internal/db` based on  *basestore.Store`. They would provide basic CRUD queries plus any useful query non specific to a particular service logic.
- If services have some queries that don't belong in these shared stores, they can create their own store by extending the `*basestore.Store` and reusing the shared types as well.

> Wouldn't a better approach be to convert repos.Store to use *basestore.Store and use its utility functions to get rid of a lot of duplicated code and then, slowly, migrate internal/db to also use *basestore.Store, so that we could have different domain-specific stores but use the basestore.Store interface to share transactions between them?

I totally agree with that and I think this is the end goal that's proposed by #11676, but it depends on how far we want to go with the issue at hand. My initial thought was to only focus on the cheapest first step towards that direction, but I'm open to suggestions.

**Comment by tsenart** [comment]
Makes sense, but I think moving towards `*basestore.Store` integration makes sense to do already, no?

**Comment by mrnugget** [comment]
If you do it in two steps

1. use `*basestore.Store` in `repos.Store`
2. move `repos.Store` methods to `db`

it should be easier to manage, I think.

**Comment by asdine** [comment]
Since the focus of our team is currently on repo-updater, we'd like to quickly eliminate some debt on that service to relieve our team, then progressively move towards using basestore. This might not be the fastest path but I believe we might see the benefits faster on any other repo-updater task.
I have created two other issues to deal with that once the repo-updater store has been cleaned up: https://github.com/sourcegraph/sourcegraph/issues/14755 https://github.com/sourcegraph/sourcegraph/issues/14755

**Comment by ryanslade** [comment]
Closing and removing this from our milestone as we've pulled everything out into individual tasks now and don't want this showing up as a duplicate in the tracking issue.

**Comment by tsenart** [comment]
> Closing and removing this from our milestone as we've pulled everything out into individual tasks now and don't want this showing up as a duplicate in the tracking issue.

Can you describe what the high level plan is on this for the remainder of this cycle and what's gonna be left to do then?

**Comment by ryanslade** [comment]
We're going to continue with the plan @asdine described above. Since the original task had a 2 day estimate and was assigned to both of us, we'll assign 2 days worth to each of us for this cycle and the remaining tasks will need to be picked up in the next cycle.

**Comment by asdine** [comment]
Here is the updated plan:

### This cycle

@asdine:

- repo store: Return sources from existing repo store methods https://github.com/sourcegraph/sourcegraph/issues/14707

@ryanslade:

- repo store: Add Create method https://github.com/sourcegraph/sourcegraph/issues/14708
- repo store: Replace all calls to repo-updater's ListRepos with internal/db/repos#List https://github.com/sourcegraph/sourcegraph/issues/14710
- repo store: Replace all calls to repo-updater's Insert with internal/db/repos#Create https://github.com/sourcegraph/sourcegraph/issues/14711
- repo store: Replace all calls to repo-updater's Delete with internal/db/repos#Delete https://github.com/sourcegraph/sourcegraph/issues/14712

### Remaining tasks

- external service store: Add an Upsert method https://github.com/sourcegraph/sourcegraph/issues/14713
- repo updater store: Simplify interface https://github.com/sourcegraph/sourcegraph/issues/14714
- repo-updater: Convert the Store to use basestore https://github.com/sourcegraph/sourcegraph/issues/14755

**Comment by mrnugget** [comment]
I can't tell from the tickets themselves, but do the `Replace all calls [...] with internal/db/[...]` include adding the ability to use transactions in `db/repos`? Because we do use transactions right now and I don't think it would be great to lose that (out of necessity we sometimes _have_ to use `db/repos#List` inside transactions because only that one supports the `authzFilter`)?

Example of such a call: https://github.com/sourcegraph/sourcegraph/blob/a254f64b149ab56b654764dbac4e9b031d62a5e9/enterprise/internal/campaigns/reconciler.go#L610-L619

**Comment by asdine** [comment]
@mrnugget Good question, as it already happened, we will probably have to change the order or split some of the tasks if we realize something is missing.
In any case, the goal is not to downgrade what we currently have, we will make sure that every existing feature will get moved or have its counterpart in the final solution. 
If we need transactions on some of the calls, then we might have to tackle #14755 before the other tasks (cc @ryanslade)
