### ISSUE TITLE
Active tab no longer underlined

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#14251]
![image](https://user-images.githubusercontent.com/10532611/94469189-f412f400-01c5-11eb-9971-14c30a763932.png)

Reproduces on dotcom: https://sourcegraph.com/github.com/sourcegraph/sourcegraph

**Comment by sqs** [comment]
@felixfbecker #14852 does not fix this. I think this problem is caused by something that's added in our production bundle and is not present in the dev bundle. The button's `border-bottom-width` is 3px in dev and 0px in the prod build.

In the dev build, the CSS for the element is:

![image](https://user-images.githubusercontent.com/1976/96606626-54b8bc80-12ac-11eb-9923-bbaa94f3f2ff.png)

In the prod build, the CSS is:

![image](https://user-images.githubusercontent.com/1976/96606652-5aae9d80-12ac-11eb-8202-5e02c10184b7.png)

So perhaps there is some CSS minifier step that is changing the inheritance here?

**Comment by felixfbecker** [comment]
Ah awesome find! Very much sounds like it. Maybe it's one of the `cssnano` optimizations: https://cssnano.co/docs/optimisations
Next steps would be selectively disabling individual `cssnano` optimizations.

**Comment by AlicjaSuska** [comment]
@felixfbecker the same problem occurs in the definition/references/history tabs:
<img width="473" alt="Screenshot 2020-11-02 at 08 32 35" src="https://user-images.githubusercontent.com/20326070/97841398-09f46700-1ce6-11eb-9bb3-3e0699c0c88c.png">

**Comment by felixfbecker** [comment]
I updated `cssnano` this week (thanks Renovate!) and that fixed it (for some context: we were on a nightly cssnano version to fix another issue, but since then cssnano finally got a new stable release with both bugs fixed, and now we're back on stable).
