### ISSUE TITLE
HTML entities are stripped from comments in hover

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#14314]
- **Sourcegraph version:** dotcom on Sep 30, 2020
- **Platform information:** macOS 10.15.6, Chrome 85

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b2cd5ddf5a013b12df9691c670d8644dcf26a936/-/blob/shared/src/components/LinkOrButton.tsx#L46:14
2. Hover over LinkOrSpan
3. Compare displayed doc block with the real docblock:

```
/**
 * A component that is displayed in the same way, regardless of whether it's a link (with a
 * destination URL) or a button (with a click handler).
 *
 * It is keyboard accessible: unlike <Link> or <a>, pressing the enter key triggers it. Unlike
 * <button>, it shows a focus ring.
 */
```

#### Expected behavior:
The comment is displayed as-is.

#### Actual behavior:
The HTML entities are not shown.

![image](https://user-images.githubusercontent.com/19534377/94684358-410edb80-0328-11eb-88c7-e1d50dc38c36.png)

Not sure if this is web or codeintel, so assigning both.

**Comment by felixfbecker** [comment]
This is expected behavior. Comments are interpreted as markdown and markdown allows inclusion of HTML. The doc block should wrap the `<button>` etc in backticks.

Whether we treat comments as markdown or as plain text, there will always be a set of comments that would have looked better as the other option. I think treating them as markdown is best for the majority of comments, and a small set of comments that don't look good is acceptable.
I think it's also VS Code's behavior.

**Comment by felixfbecker** [comment]
I unassigned `team/codeintelligence` since this rendering is inside the webapp, but @efritz if you disagree with the take above you can also mark the hover content as `PlainText` by modifying the code intel extension, so I guess it's actually your call :)

**Comment by macraig** [comment]
@efritz any follow ups on what Felix described above?

**Comment by efritz** [comment]
No, I think this is reasonable (and something we're not putting any focus on at the moment).

**Comment by ryankscott** [comment]
This should no longer be an issue when we migrate code intelligence away extensions.
