### ISSUE TITLE
Metrics or indicator for search readiness (for massive scale instances)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#14316]
Requested by https://app.hubspot.com/contacts/2762526/company/557692805

Discussion in Slack: https://sourcegraph.slack.com/archives/CJX299FGE/p1601066252032700

## Context/use case

Company's instance has ~400k repositories, and their primary use case is **comprehensive searches** . I.e., searches to get ALL of the results across all of their code, even if it's thousands or tens of thousands of matches. They primarily use the API/CLI for this, but using the UI is important as well...

## Problem

If they run the same search several times in a row, the results can fluctuate (the main culprit of this https://github.com/sourcegraph/customer/issues/82, has been fixed, but this issue still occurs periodically... And outside of the main issue, there are also questions that that fix alone didn't address, such as "can I be confident that all of my code is in Sourcegraph and indexed?"). 

These issues are essential to making our security use case work (as well as campaigns, insights, and more). E.g., if I search for all usages of a vulnerable library, but only later discover that some repos weren't cloned yet, or that the search timed out, I'll trust Sourcegraph less.

## Desired solution

Overall, what they really need/want is an answer to “Is Sourcegraph ready for us to start searching now or not”. This wraps up several things, and it may be hard to come up with a single great metric here (since we are always cycling repos through the indexing queue). Do we have a good way to answer this question? E.g. some combo of metrics like:
- How many repos haven’t been cloned at all yet?
- How many repos don’t have an index at all yet?
- How many repos haven’t been synced in the last [24h]?
- How many repos don’t have an index in the last [24h], that do have an update in that time?
- What is in the queue for indexing right now?
- How many indexes aren’t loaded into memory yet?
- Etc.

Additionally, I think updating the **Site-admin > Repository** status page also needs a bit of work (this falls on Cloud) for instances with huge numbers of repos. Summary metrics for the radio buttons like “Needs index” are probably more important than the full list.

Tagging both Search (for the bulk of this, the actual search stuff) and Distribution (for the metrics/observability aspect).

**Comment by dadlerj** [comment]
From @slimsag :

>I am not sure the actual product request here ("really need a good answer to is Sourcegraph ready for us to start searching now or not") is actually best handled by us on Distribution. More likely it is better handled by Search or Cloud teams, or maybe a mixture of all three - I'm not completely sure.

>There are a lot of aspects at play here, including both what you mentioned (which mostly falls under repo-updater/cloud-team and zoekt/search-team) as well as deeper questions like "How do we ensure search performance is deterministic, or communicate that it is not?" this includes things like

> * Zoekt using mmap and the cache being cold and somewhat arbitrarily managed by the Linux kernel and not us. Indexes can "fall out of memory" without us knowing and search perf will then be quite bad until someone runs a search that requires those indexes again, and then search will be fast again. At large scales this means "I get less results and the UI isn't really clear about why"
> * Falling back to unindexed search for a somewhat non-deterministic set of repositories
> * Repositories being searched in a non-deterministic order, leading to non-deterministic amounts of results for the same query ran multiple times
> * Some queries being exponentially more expensive than others, even if indexed, and how to communicate that to users

**Comment by dadlerj** [comment]
From @rrhyne :

>@keegan, in the streaming search kickoff, we talked about possibly displaying a few of these metrics on a per search basis. Are they all available to display? Would that make sense for each search, or would this kind of content be more appropriate in the search log idea you mentioned?

From @keegancsmith :

>these statistics are available to display as the search progresses :slightly_smiling_face: Right now we don't plumb them all the way to the frontend, but we can if we need to (and its quite pleasing to see for longer searches) (edited) 

>Things like differing result counts hopefully will mostly be solved as streaming gets mature. Root cause is how our file match limits and time limits interact with what is in the cache. Streaming will be able to mostly eliminate time limit part and we can have much higher defaults for file match limits. It won't solve issues around unindexed searches, but maybe our messaging will improve around distinguishing indexed vs non-indexed results.

**Comment by dadlerj** [comment]
Response to @slimsag :

I actually don't think determinism is a critical component of this (in the way we've used that term to talk about search priorities in the past). Because their searches are _comprehensive_, the results set should be deterministic, yes, but that's a side effect of the fact that it's comprehensive (rather than inherent to the search)! E.g., order of results doesn't matter, but knowing that 100% of results will be returned is essential.

Curious to hear from @christinaforney @poojaj-tech and @lguychard on how we can better serve this search use case.

**Comment by slimsag** [comment]
This came up again as an important point for a customer. https://sourcegraph.slack.com/archives/CHEKCRWKV/p1602875508288500?thread_ts=1602875018.288200&cid=CHEKCRWKV

**Comment by slimsag** [comment]
Metrics and indicators are good, but let's not lose sight of the point I was raising about determinism here. I don't mean order of results (though I believe we really should have that..) I mean _"am I actually getting all of the results, and can I actually feel confident that is true?"_ If the system is constantly changing things on me, the answer is no, I can't feel confident in that.

Things that make me feel extremely uneasy about "I got all the results and I believe it" are:

1. Zoekt cold cache returning less results sometimes: https://github.com/sourcegraph/sourcegraph/issues/9001
2. Repositories sometimes not being indexed and hitting a different unindexed search path.
3. Unindexed search and indexed search returning a different amount of results -- even if they complete. For example, an unindexed symbol search returns a different number of results (and different results entirely!) than an indexed symbol search.
4. Repository updates/discovery sometimes not working or running behind.

And, from a user expecting a consistent and exhaustive result set, the only way I can actually be confident in this myself (and the way I have seen customers expect to verify this) is by comparing results across multiple queries. They quickly find our results are not returned in a specific order and "settle" on the result count - which is all over the place even when everything is working properly due to the number of changes constantly being ingested by Sourcegraph.

My point: This is not just about "can I check if everything is working as intended" today, it's also about having our systems work in such a way that they establish some level of confidence that they are doing the right thing. An example of how adding extensive metrics here could NOT solve this problem is "the metrics say everything is fine but I get a different number of results when running the search at different times of the day - why?" and this stems from a number of systemic issues from underlying design decisions. If we don't correct that, we don't fully solve this problem IMO.

**Comment by slimsag** [comment]
https://app.hubspot.com/contacts/2762526/company/407948923/ has also complained about this in the past on multiple occasions and someone over there just ran into this, details:  https://sourcegraph.slack.com/archives/C0W2E592M/p1602882114120000

Another instance of non-determinism I forgot about in the above: even if you have `count:9999999 timeout:2m` in your query, we will sometimes and sometimes not include other mixin result types like symbol search results depending on how fast they return. So the same query `foobar count:9999999 timeout:2m` ran multiple times may not timeout but will return different results (sometimes including some, none, more or less symbol search results as an example).

**Comment by keegancsmith** [comment]
Thanks for raising these points. They are indeed top of mind and we are tackling them. I've spent some time reading (and re-reading) this thread to ensure I have absorbed it :)

To quote what Rob said:

> Much of my work on streaming search has been to help the UI be more transparent about what was searched and what wasn't.
> 
> &#x2026;snip
> 
> The UI and the API should consistently return the same stats for any given query or at the very least, we message to offloading longer queries to the API well.

I hope this goal helps illustrate that we want to make users much more confident in the exhaustive usecase. A browser can't display exhaustive results, but our statistics should be stable.


<a id="org1e8cb4f"></a>

#### Specific concerns

> Zoekt cold cache returning less results sometimes

The root cause here is poorly communicating back what zoekt did, and what it skipped. Zoekt explicitly tells us when it times out or didn't search everything. We currently ignore that, since until our very large customers and cloud scale we never ran into Zoekt being slow!

We specifically chatted about this in our work on designing streaming search UI. Once communication is fixed, there is still poor behaviour here by default. This is due to how our relatively low limits for our batch API interact with the user experience. This is also being addressed in streaming search.

> Repositories sometimes not being indexed and hitting a different unindexed search path.

This should be resolved with better communication + streaming. The paradigm of how we communicate these sort of things change when we don't have strict time budgets of our batch API.

> Unindexed search and indexed search returning a different amount of results &#x2013; even if they complete. For example, an unindexed symbol search returns a different number of results (and different results entirely!) than an indexed symbol search.

This sounds like a bad issue. I did some work recently to try and align ctags in zoekt and symbols service. (Follow the trail from symbols: use shared go-ctags library [#14073](https://github.com/sourcegraph/sourcegraph/pull/14073)). Is there an issue about this with some details?

> Repository updates/discovery sometimes not working or running behind.
> 
> &#x2026;snip
> 
> Specifically he wanted a lot more insight into how to tell when Sourcegraph is actually fully indexed or not. I gave him raw Prometheus metrics like indexer queue length, index\_num\_assigned and index\_num\_indexed - but he is really going after "how do I check if Sourcegraph has actually cloned and indexed all my repos? and how far behind it is?" and we don't have a good answer to this today. For example, if repo-updater is behind then the metrics I gave them will report "all good" when in fact it is not.

When things go wrong here, do you think we should communicate this to admins (or users?) more loudly? cc @asdine @ryanslade

Given we poll both from zoekt -> gitserver and gitserver/repo-updater -> codehost there is some inherent lag here. However, I think zoekt reporting on the queue length of what it knows needs updating may help? eg even if there is 5min lag, a small queue size indicates we are not backed up. Still doesn't solve lag in gitserver/repo-updater -> codehost.

> And, from a user expecting a consistent and exhaustive result set, the only way I can actually be confident in this myself (and the way I have seen customers expect to verify this) is by comparing results across multiple queries.

This feels like a good goal to strive for in our default user experience, as well as when opting into exhaustive search. This sort of goal makes me consider removing our slower searches from the default path (eg symbol), so our results are more consistent. Or atleast may influence our design so we report different type results differently.

**Comment by tsenart** [comment]
This still seems to be a problem. Not sure if it falls neatly into search core's domain though. Overall "search readiness" crosses into repo-management too, but that's not an issue.

**Comment by jjeffwarner** [comment]
@keegancsmith @stefanhengl Which of these items are still an issue beyond?

> And, from a user expecting a consistent and exhaustive result set, the only way I can actually be confident in this myself (and the way I have seen customers expect to verify this) is by comparing results across multiple queries.

This feels like a good goal to strive for in our default user experience, as well as when opting into exhaustive search. This sort of goal makes me consider removing our slower searches from the default path (eg symbol), so our results are more consistent. Or atleast may influence our design so we report different type results differently.

**Comment by keegancsmith** [comment]
Users should be confident now in our result sets, that comment was from 2020 :) If we have examples of indexed search misbehaving here, I'd love to have examples to dive into and fix.

I think the issue title is valid still and ties into admin work. We should have some high level indicator for zoekt having indexed everything.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. Parts of this ticket have been implemented in the meantime.
