### ISSUE TITLE
window.gtag isn't set on docs.sourcegraph.com

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14323]
I was changing the docs.sourcegraph.com sidebar and saw that there is some code (for tracking clicks on the quickstart command) in the docs JS file that checks for `window.gtag`. This never seems to be defined, even on the currently live docs.sourcegraph.com, so the tracking might not be firing. I'm going to leave this part of the code untouched, and when you are back, @aileenrose, we can troubleshoot it together.

**Comment by aileenrose** [comment]
Luckily we can still see the click activity via Google tag manager.
![Screen Shot 2020-10-15 at 11 42 48 AM](https://user-images.githubusercontent.com/2164916/96173971-7e08cf80-0edd-11eb-8e19-72fb21801d7d.png)

The only thing is missing is the click to copy-to-clipboard as noted in https://github.com/sourcegraph/sourcegraph/issues/14645

Closing this issue since tracking is firing.
