### ISSUE TITLE
Searches panel search text is not highlighted

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#14383]
The repository panel on the left contains a filter and value that are highlighted as per the search language. The searches panel is not. 

![image](https://user-images.githubusercontent.com/539268/94954807-7a695780-049e-11eb-8e0b-3f510a21baab.png)

**Comment by limitedmage** [comment]
Right now we don't have a way to do this easily. All example searches (eg in reprogroups) have hardcoded "syntax highlighting".  We can do it in the Repositories panel because we are parsing the query to just extract the repo, and manually inserting the `repo:` string with syntax highlighting also hardcoded.

To make this work on the recent searches panel, we would need to build a way to generate HTML from an arbitrary query. We can do this, but it's not small.
