### ISSUE TITLE
Create demo video for user added public repos in sourcegraph.com

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#14438]
Let's take inspiration from @mrnugget and the @LawnGnome and demo our first milestone to the rest of the company!

Reference:

- https://twitter.com/thorstenball/status/1306601556238884864
- https://sourcegraph.slack.com/archives/CMMTWQQ49/p1601596556103600

**Comment by ryanslade** [comment]
@mrnugget @LawnGnome What is the software you use to do the "picture in picture" effect?

**Comment by mrnugget** [comment]
I use Screenflow on macOS (not free). OBS Studio can also do this, I think.

**Comment by LawnGnome** [comment]
Sorry, I was behind on my GitHub notifications (and yesterday was a holiday here).

For future reference, I didn't try to do the compositing live: I recorded the video, screen, and audio as separate streams (on different devices), and then used a video editor to sync the streams and layer them after the fact. Since that's probably overkill in practice, I would recommend OBS or Screenflow (if you're on macOS). :smiley:
