### ISSUE TITLE
Opening extension from debug menu is broken

### ISSUE THREAD

**Issue by yevbar** [sourcegraph/sourcegraph#1444]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Sourcegraph Chrome extension

#### Steps to reproduce:

1. Enable the Ext debug menu ([here](https://docs.sourcegraph.com/extensions/authoring/debugging#enable-trace-logging) are the steps to do so if you haven't already)
2. Go to a file on [sourcegraph.com](https://sourcegraph.com)
3. Open the debug menu and select an extension
![ext-debug-menu](https://user-images.githubusercontent.com/10301415/50036024-7400a780-ffba-11e8-9b12-6fd0b51a60e8.png)
4. The link starts with `sourcegraph.com` so it appends the URL and gives you something along the lines of `https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/extensions/sourcegraph/lang-go`

#### Expected behavior:

I should go to the extension page

#### Actual behavior:

I get the following error

```
Git ls-tree extensions/sourcegraph/lang-go: file does not exist
```
![git-ls-tree-error](https://user-images.githubusercontent.com/10301415/50036070-c5a93200-ffba-11e8-9f53-529ee1c46366.png)

**Comment by vanesa** [comment]
I'm not able to reproduce this. All the extensions listed under `Active extensions` link correctly. However, I notice that not all of my active extensions are listed, specifically all of the language ones are missing in the menu. Is this intended? I filed that issue here in case it's a bug: https://github.com/sourcegraph/sourcegraph/issues/2235
