### ISSUE TITLE
https:// should not be possible to delete in the browser extension URL input

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#14723]
1. User shouldn't be able to delete the 'https://' part from the 'Sourcegraph URL box

<img width="443" alt="Screenshot 2020-10-14 at 17 13 55" src="https://user-images.githubusercontent.com/20326070/96009195-a989ac80-0e40-11eb-9ec3-4ad77a190cdd.png">

[Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=556%3A227) @felixfbecker we had a discussion about the copy in [this comment](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc?node-id=556:284#43027401), can we come back to it?

**Comment by felixfbecker** [comment]
Moved the second issue to https://github.com/sourcegraph/sourcegraph/issues/14729 since these are two issues

**Comment by taras-yemets** [comment]
Sourcegraph browser extension changed a lot since this issue had been created.
Below are a few examples of how different URL input validation errors are handled:
| Error | Example |
| ------- | ----------- |
| empty field | ![image](https://user-images.githubusercontent.com/25318659/151579067-d7d13066-5fd2-4628-a942-b0870d380df4.png) |
| invalid protocol | ![image](https://user-images.githubusercontent.com/25318659/151578504-0cab9f84-39bc-48c3-af95-06f0c08672ff.png) |
| invalid URL | ![image](https://user-images.githubusercontent.com/25318659/151578623-98d63195-e070-4d47-b616-b8a2e67bcede.png) ![image](https://user-images.githubusercontent.com/25318659/151578950-e83c526f-5982-4288-9f70-09d737392b0f.png) |
| invalid instance address | ![Screenshot from 2022-01-28 17-46-26](https://user-images.githubusercontent.com/25318659/151579409-462e1c54-afc3-49d3-8853-0e44df168e07.png) |

I started to work (PR [#30282](https://github.com/sourcegraph/sourcegraph/pull/30282)) on disabling user to delete _https://_ part of URL field value, and faced a bunch of edge cases when handling user copy pasting different kinds of partially correct URLs. These edge cases can be handled but require additional effort.

Given that current state off URL input validation errors handling provides user with descriptive texts of what exactly went wrong, I wonder if the requirement to disable user to delete _https://_ part of URL field value is still relevant.

What do you think @AlicjaSuska?

cc: @erzhtor

**Comment by erzhtor** [comment]
Hey, @AlicjaSuska! WDYT if we close this issue as irrelevant (not needed) anymore?

**Comment by AlicjaSuska** [comment]
Hi @erzhtor Thank you for explaining the context. If it causes issues with pasting URLs and we have good error messages, I think it's fine to close the issue. What could be potentially done to improve the experience is to have a placeholder text 'https://' for the empty field to emphasize that it's necessary to add it. wdyt @erzhtor ?

**Comment by erzhtor** [comment]
Thanks, @AlicjaSuska. Yeah, adding a placeholder sounds good! 👍  cc @taras-yemets
