### ISSUE TITLE
Use official amd loader for Monaco-editor

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1488]
Jest fails because it cannot find the `monaco-editor` module. [See this PR for more info.](https://github.com/sourcegraph/sourcegraph/pull/1484)

Assigning a few people for whoever gets to it first. I can do this tomorrow if no one else beats me to it.

**Comment by felixfbecker** [comment]
What do you mean with “official AMD loader”?
AMD is a rather outdated technology, and I would rather stay away from the homrbaked loader stuff of vscode.
All that monaco does and webpack tranpiles for us is dynamic ESM import(), which is something our test env should support because we may want to use it in more places than just for monaco.

**Comment by sqs** [comment]
I mean the vs/loader.js AMD-style loader that they have. I remember it being a lot faster. I regret making it use Webpack for bundling. If I am wrong, then great. :smile:

**Comment by ijsnow** [comment]
Perhaps one of you two should take a look at this then. I'm having trouble finding exactly what we're doing with monaco editor that is weird. It looks like our setup should already support dynamic imports so I'm not sure why it wouldn't work. Could you point me to where I should be looking?

**Comment by felixfbecker** [comment]
@ijsnow do you have an error message or something to share?

**Comment by sqs** [comment]
Please reopen if this is still important and cite why. Overall, what we have now works and is the recommended way to do it (although it might be a bit slower in webpack initialization).
