### ISSUE TITLE
Fix integration test alert localStorage flakiness

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#15126]
Theory: Different Puppeteer instances share the same localStorage and parallel running tests conflict with setting/clearing localStorage.

Using independent `--user-data-dir`s per Puppeteer launch (folder with UUID) should fix this.

**Comment by tjkandala** [comment]
Update:

Different Puppeteer instances appear to have unique temporary user data directories. I created a temp dir in the repository root with `mkdtemp`, but I believe this doesn't add value over Puppeteer's default behavior.

**Custom temp dir**

![Screenshot from 2020-10-29 09-19-49](https://user-images.githubusercontent.com/37420160/97582246-e66eab00-19cb-11eb-894f-fd1c26aaeb47.png)


**Puppeteer data dir paths (parent of profile path)**

![Screenshot from 2020-10-29 09-24-37](https://user-images.githubusercontent.com/37420160/97582264-ebcbf580-19cb-11eb-8fbd-e87851356076.png)

![Screenshot from 2020-10-29 09-21-57](https://user-images.githubusercontent.com/37420160/97582316-f71f2100-19cb-11eb-8d2e-4aa8913b713e.png)

**Comment by felixfbecker** [comment]
I found out that `onHoverShown` is called many times during the course of one test that hovers a token.

![image](https://user-images.githubusercontent.com/10532611/97901845-03450e80-1d3d-11eb-8cdb-7d2685305264.png)

**Comment by tjkandala** [comment]
Will likely be fixed in `Blob` refactor. 

I ran `'shows a hover overlay from a hover provider and updates the URL when a token is clicked'` 60 times on `main` and 60 times on the blob refactor branch.

|  | Alert shown | Alert not shown |
| --- | --- | --- |
| `main` | 7 | 53 |
| `Blob` refactor | 0 | 60 |

Script in [this gist](https://gist.github.com/tjkandala/94eea45d2138a6fa8e298bdfbc6d77de).
