### ISSUE TITLE
Repo search tab missing results

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#15182]
searching for `repo:X` returns many more results than searching for `X type:repo`. Seems like these should be the same?

Repro:

* Look at https://sourcegraph.com/search?q=sourcegraph+type:repo&patternType=literal
* Look at https://sourcegraph.com/search?q=repo:sourcegraph&patternType=literal

**Comment by rvantonder** [comment]
I think what's happening underneath the hood here is different (I agree these two should be the same). Here's what I _think_ is happening:

`type:repo ...` -> gets forwarded to Zoekt's `type:repo` (which has a different semantics, it makes sure to return only result types of indexed repos), and then we process the results to return the repo results. The nature of `type:repo` in Zoekt, IIRC, is that it limits shards to 1, which has the effect here of returning fewer repos than `repo:`... But I'm not totally sure.

- `repo:...` on the other hands goes to the DB to fetch matching repos.

The part I'm fuzzy on is what exactly `type:repo pattern` does in our code. I need to go search down that code to figure out what we do. I can create a temporary fix pretty easily by transforming `type:repo <pattern>` to `repo:pattern`.

CC @keegancsmith

**Comment by keegancsmith** [comment]
cc @stefanhengl who is now an expert out type:repo :)

**Comment by stefanhengl** [comment]
I did a bit of digging and I think I found the root cause.

Root Cause:

`repoSearch` returns different results.

**Why does `repoSearch` return a different result?**
`repoSearch` matches the pattern against the resolved repositories coming from `determineRepos`, which returns a different list of repos for the two queries.

**Why does `determineRepos` return a different list?**
Because of the missing repo filter in `sourcegraph type:repo` we match the pattern `sourcegraph` against the list of default (indexed) Repos (200k). In the case of `repo:sourcegraph`, we match the pattern `sourcegraph` against the list of all repos (with a configured limit of 500k) in the db.
