### ISSUE TITLE
EITHER we require codehost authentication (no built-in auth) OR we need to improve our built-in auth security

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#15275]
2FA

Lockout after X incorrect login attempts

Add IP address to event logs

**Comment by christinaforney** [comment]
Link to subfeature: https://sourcegraph.productboard.com/feature-board/planning/features/5982442

**Comment by ryanslade** [comment]
I think we should break this into three issues. Do we need to do that on product board?

**Comment by chayim** [comment]
If we cannot improve our codehost authentication, then we should to require two-factor authorization (Google authenticator style is preferred). Users should be locked out of their accounts after 3 incorrect logins.

**Comment by ryanslade** [comment]
Something to consider from a product side, how do we handle existing accounts that haven't added 2FA yet?

**Comment by ryanslade** [comment]
2FA work is being tracked here: https://github.com/sourcegraph/sourcegraph/issues/436

**Comment by ryanslade** [comment]
We decided that users cannot add their own code without connecting via a code host using OAuth:
https://docs.google.com/document/d/1pB2uF3SVNVqWf97jtJCR_bMz4qHguxJgRAS8UjEZPNE/edit?disco=AAAAKpT-Ql0

However, I don't think this really closes the loop on this issue. There's currently nothing stopping a user from having signed in via a code host and also with email auth at some point which means we're back to square one regarding security.

I think we only really have two options:

1. Enable 2FA for our email based auth and only allow users to add their own code if they have 2FA enabled or they use code host auth.
2. We disable email based auth completely.

Option 1 is something that we can move forwards with as we're only adding features rather than taking something away. It was specced out in RFC 262.

I don't see a way to go with Option 2 that would be acceptable to existing users unfortunately.

**Comment by tsenart** [comment]
@quinnkeast: Please advise :)

**Comment by ryanslade** [comment]
If we decide we are going to keep our email auth I'll close this issue and break the 3 subtasks above into separate issues.

**Comment by ryanslade** [comment]
I've broken this out into separate issues which we'll tackle in our next cycle so I'm closing this
