### ISSUE TITLE
Dropdown button background colour issue

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#15626]
- **Sourcegraph version:** Cloud
- **Platform information:** Firefox 82.0.2

#### Steps to reproduce:

1. Interact with dropdown button on extensions page

#### Actual behavior:

![colour-bug](https://user-images.githubusercontent.com/6304497/98717342-37e44600-238d-11eb-9a31-67b20526e7b5.gif)

I'm guessing the dark theme is being triggered somehow.

**Comment by Joelkw** [comment]
Thanks for filing!

**Comment by Joelkw** [comment]
We've since changed designs but this is broken on the dark theme now: 
![image](https://user-images.githubusercontent.com/11967660/126205704-6b2ed2af-38f9-47e1-b075-143f128894ec.png)
![image](https://user-images.githubusercontent.com/11967660/126205743-c41e82a9-75e1-4bbe-baca-4da373f815fd.png)

@muratsu noted this might be owned by frontend platform now cc @AlicjaSuska. Not urgent but retagging appropriately.

**Comment by Joelkw** [comment]
(Closing in favor of #23248 )
