### ISSUE TITLE
Allow named repo/rev pairs in version contexts

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#15662]
Requested by https://app.hubspot.com/contacts/2762526/company/768958891

This customer is using src-expose/src serve-git and version contexts.

They only use src-expose because version contexts don't allow them to _name_ {repo, rev} pairs. To describe what I mean:

Suppose company had a v3.20 release in 2019. They have multiple feature branches in their main repository that should be included in the corresponding version context. So, for example, imagine their context included:

- `{ repo: github.com/sourcegraph/sourcegraph, rev: abc123 }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: feature-branch-1 }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: xyz345 }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: feature-branch-2 }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: def678 }`
- `{ repo: github.com/sourcegraph/about, rev: ghi901 }`
- `{ repo: github.com/sourcegraph/infrastructure, rev: jkl234 }`
...
(and a few dozen more)

When a user goes to search on Sourcegraph in that version context, they are likely to see results from _multiple_ versions of the main sourcegraph/sourcegraph repo. So, for example, if I search for `test`, I might see results from `sourcegraph/sourcegraph@abc123`, `sourcegraph/sourcegraph@feature-branch-2`, `sourcegraph/sourcegraph@def678`, etc.

This customer finds this impossible to manage—there could be dozens of different versions of the same repo at different commits in a single version context due to how they organize their code. Search results that come from the same repo at a bunch of random/meaningless commit hashes are impossible to use.

They would like the ability to specify version contexts with an optional `name` field that would be displayed on the search results page instead. As an example:

- `{ repo: github.com/sourcegraph/sourcegraph, rev: abc123, name: "repo-updater-component" }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: feature-branch-1 }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: xyz345, name: "frontend-component" }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: feature-branch-2 }`
- `{ repo: github.com/sourcegraph/sourcegraph, rev: def678, name: "code-intel-component" }`
- `{ repo: github.com/sourcegraph/about, rev: ghi901 }`
- `{ repo: github.com/sourcegraph/infrastructure, rev: jkl234 }`
...

So that search results would come back showing: `repo-updater-component (sourcegraph/sourcegraph@abc123)`, `sourcegraph/sourcegraph@feature-branch-2`, `code-intel-component (sourcegraph/sourcegraph@def678)`

**Comment by keegancsmith** [comment]
Another perspective on the customer using src-expose: It sounds like they could get rid of src-expose if they had a way to expressively map `(repo, rev) -> (repo_renamed, rev_renamed)`? This is hard on our side to accomplish, because "git" is our data store. But git supports this idea! If our "other" external service allowed users to set refspecs we used to clone/fetch, they could manage this mapping easily without src-expose. https://git-scm.com/book/en/v2/Git-Internals-The-Refspec

Presenting a different name at the presentation layer / version contexts sounds like we would end up in lots of strange inconsistencies all over the place since there would be more and more corner cases to follow up. Most of which tie to the fact that only search requests have a version request, while everything else doesnt:
1. When clicking through on search results, the name used for the rev would be lost. This is because everything else would require the `rev` to work.
2. Does `repo:` support the name shown?
3. Pretty much anything involving reponame/rev would be weird.

This is why I think somehow making this happen such that the store (git) represents this correctly. eg a tag for revs/etc. The customer should maybe consider tagging the special revs in src-expose?

**Comment by lguychard** [comment]
Version contexts are deprecated.
