### ISSUE TITLE
Cannot add repositories from GitHub to local instance since external services

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1570]
When going to http://localhost:3080/github.com/codecov/sourcegraph-codecov I get this screen:

![image](https://user-images.githubusercontent.com/10532611/50388610-2273bd80-071c-11e9-80a5-e805b8b0374a.png)

This is a public GitHub repo, so I would expect it to "just work", at least for our dev instances (which used to be the case).

When clicking on "adding an external service" (which is almost impossible to notice as a link), I tried adding an external service for GitHub:

![image](https://user-images.githubusercontent.com/10532611/50388615-564ee300-071c-11e9-97fd-3a4a81ad0700.png)

At first I hit the back button because I didn't realise the "Add external service" button was like a "Save" button.

After saving, I still saw the same error.
I then noticed the little hint that a `token` was missing. Why do I need a token for public GitHub repos?

So I added a token, and now I am getting this error:

![image](https://user-images.githubusercontent.com/10532611/50388629-ad54b800-071c-11e9-9c36-ffc46429ab3a.png)

At this point I don't know what to do anymore, because being a public repository, this repo is obviously accessible with any token.

**Comment by felixfbecker** [comment]
Marking as release blocking.

**Comment by nicksnyder** [comment]
There are a few things here:

> When clicking on "adding an external service" (which is almost impossible to notice as a link)

I tested on light theme, which is better but not great. This is indeed a problem for dark theme.

> At first I hit the back button because I didn't realise the "Add external service" button was like a "Save" button.

Would your confusion have been resolved if we used a different verb, like "Connect an external service", or "Create and external service connection"? Do you have any other suggestions that would have resolved this confusion for you?

As a point of reference, orgs and users are "Created" and access tokens are "Generated" (the former being a blue button and the latter being a green button. There is also some inconsistency with using a leading "+" icon or not. cc @francisschmaltz to chime in.

> I then noticed the little hint that a token was missing. Why do I need a token for public GitHub repos?

The schema doesn't differentiate between GitHub.com and GitHub Enterprise. For the latter you almost certainly need a token. For the former, you don't _need_ a token for public repos, but it helps, because the rate limit increases from 60/hour to 5000/hour.

> So I added a token, and now I am getting this error. At this point I don't know what to do anymore, because being a public repository, this repo is obviously accessible with any token.

The missing step here is you need to explicit add the repo you want to "repos" list. While we can and do sync all repositories for private instances (e.g. GitHub enterprise), we obviously can't do this for GitHub.com so you need to be explicit.

Action items (I don't think all of these are release blocking):

- [ ] In dark theme, the link for the "connecting an external service" text is not obvious. White theme is a little better but could also probably be improved. [Here is the link that needs to be styled](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/repo/RepositoryErrorPage.tsx#L202:45-208:48).
    ![image](https://user-images.githubusercontent.com/754768/50808987-093f4500-12b6-11e9-9ec4-d52b29147cb2.png)
- [ ] Improve the wording of "add external service" action.
- [ ] Customize the default config for each code host type with helpful comments.
- [ ] Improve the "Check that this site has been configured" message.
- [ ] Add docs about external services to docs.sourcegraph.com

**Comment by felixfbecker** [comment]
> I tested on light theme, which is better but not great. This is indeed a problem for dark theme.

@francisschmaltz what color should links have in dark theme, and where can I look this up / is the single source of truth? I couldn't find a style guide in Zeplin

This should be solved for all links in dark theme globally.

> Would your confusion have been resolved if we used a different verb, like "Connect an external service", or "Create and external service connection"? Do you have any other suggestions that would have resolved this confusion for you?

The biggest problem is the icon, ➕ usually adds an (unsaved) item to a list, I wouldn't expect it to be a required action to _persist_ an unsaved item. "Create" or "save" would be better, or a ✔️ as an icon. It would also help to have a navigation listener that prompts to ask if you want to save unsaved changes before leaving the page, which should be possible with react-router.

>  Customize the default config for each code host type with helpful comments.

This would help tremendously.

> The missing step here is you need to explicit add the repo you want to "repos" list. While we can and do sync all repositories for private instances (e.g. GitHub enterprise), we obviously can't do this for GitHub.com so you need to be explicit.

So it seems like `repos` property is required, but it doesn't tell you in the hints:

![image](https://user-images.githubusercontent.com/10532611/50841580-529a9d80-1365-11e9-857f-cabfc88a781b.png)

The editor should show errors if not all properties are configured that need to be configured to make the external service work.
If one of `repos` /`repositoryQuery` is required, that can be expressed in JSON schema too.

**Comment by nicksnyder** [comment]
> So it seems like repos property is required, but it doesn't tell you in the hints:

No, it is not required in general. It is only required to sync public repos on public code hosts (e.g. github.com). For example, it isn't required on a private GitHub Enterprise instance, or if you are only trying to sync private repos from GitHub.com.

I do believe this pain is mostly a dev pain and not a customer pain, because real site admins are not going to configure repos one by one (I am not saying that this can't/shouldn't be improved though).

> If one of repos /repositoryQuery is required, that can be expressed in JSON schema too.

This isn't true in the general case (e.g. private github enterprise instance with access token).

**Comment by nicksnyder** [comment]
> The biggest problem is the icon, ➕ usually adds an (unsaved) item to a list, I wouldn't expect it to be a required action to persist an unsaved item. "Create" or "save" would be better, or a ✔️ as an icon.

Yeah, there should not be a ➕icon on the save button (to be consistent with other forms in the app) so I will fix that. Linguistically I think it needs to be "Add external service" or "Create external service connection". "Create external service" sounds wrong to me because you aren't creating an external service. "Add external service" is briefer so I am going to stick with that. As a point of reference, GitHub uses the "Add" terminology for [webhooks](https://github.com/organizations/sourcegraph/settings/hooks/new) which I think is a similar situation.

> @francisschmaltz what color should links have in dark theme, and where can I look this up / is the single source of truth? I couldn't find a style guide in Zeplin
> This should be solved for all links in dark theme globally.

I agree and filed a separate issue https://github.com/sourcegraph/sourcegraph/issues/1724

> It would also help to have a navigation listener that prompts to ask if you want to save unsaved changes before leaving the page, which should be possible with react-router.

We don't appear to do this for other forms on the site (I checked orgs, users, so I am going to defer this).

**Comment by nicksnyder** [comment]
I have improved the documentation and made some of the minor fixes discussed. The biggest improvement is having a default config per code host. The link styling is a separate issue now.

I am going to close this and we can see how smoothly the test plan goes.

**Comment by francisschmaltz** [comment]
@felixfbecker colors for text (dark theme) is here: https://zpl.io/2jv9lx6

**Comment by felixfbecker** [comment]
I updated the dark theme text color (not links yet though)

**Comment by nicksnyder** [comment]
Please continue the styling discussion in this separate open issue:

https://github.com/sourcegraph/sourcegraph/issues/1724
