### ISSUE TITLE
Implement a URL unfurl endpoint to the Sourcegraph API

### ISSUE THREAD

**Issue by jeanduplessis** [sourcegraph/sourcegraph#15735]
## Requirements

Add an endpoint to the Sourcegraph API that takes a URL as an input and returns meta-information regarding the URL.

## Implementation details

When the endpoint received the request it will:
1. Validate the input as a valid URL
1. Check if a result exists in the cache for the URL
	1. If one exists and it is not stale (older than X hrs [TBD]) then return the result from the cache
    1. If no result exists or it is stale make a new request to the URL
1. Make a request to the URL and parse the HTML for relevant meta tags
1. Store the result in the cache
1. Return the result 

The following additional requirements should be considered:
- Follow redirects when making a request to the URL

## Additional resources

Examples of URL unfurling services written in Go:
- https://github.com/heyvito/go-unfurl
- https://github.com/Doist/unfurlist

https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

Relates to https://github.com/sourcegraph/sourcegraph/issues/15584

**Comment by jeanduplessis** [comment]
@Joelkw would love to get a read from you on the priority of this work considering the potential large time commitment needed to implement this. The trade-off is between doing this work to enable link previews vs deprioritizing whatever else is waiting for us in the next iteration.

**Comment by Joelkw** [comment]
@jeanduplessis my read is that we should deprioritize this until we either: 

- hear from a big customer that they're hitting the block and it's frustrating them, or see a whole lot of usage on this extension when we get data on that back
[and/or]
- we have more people on the web team so this doesn't take 33% of our capacity for a week. 

Given that we can update the more popularly-requested extensions (Sonarqube, synk) directly, and that we fail on link-preview-expander by still showing a clickable link, just not with the preview info, I'm okay otherwise leaving this pointed to the default proxy for a good while. 

Moving this to our backlog for now.

**Comment by Joelkw** [comment]
@felixfbecker did you mean to make this a frontend platform issue? (Would that be the team that implemented this? Could see it being either team since it's a platform feature but only used by one team / would other teams need this?)

**Comment by felixfbecker** [comment]
No, probably fits best under extensibility.

**Comment by vdavid** [comment]
I'm done with all features except:
 - **Validation:** I've noticed this among the requirements: "Validate the input as a valid URL". Not sure if this needs to be explicit or if it's OK if the endpoint accepts random garbage (as it does) without throwing an error.
 - **Some tests:** The HTTP fetching and Redis caching parts are not covered with tests yet. With my current skills, it'd take me an amount of time that I'd find hard to justify, plus I'd probably not do it the right way on my own.
 - **Standardization:** I'll need an in-depth review because I assume that I did a few things in an odd/non-standard way. This is my first bunch of commits at Sourcegraph and my first time coding Go independently. I'm pretty sure that I failed to follow some best practices. I'd be happy to get feedback and learn.
 - **References vs. values**: I'll especially need advice on this topic: the `LinkMetadata` struct having pointer fields allowed me to return `nil` instead of empty strings (a practice that the Go website encourages), but it caused me to use two dozen lines of boilerplate code which I don't like. Not sure about the best choice here.

@tjkandala, please advise who would be the best person to do this code review with. Also, I'm grateful to you for looking up this task for me and for the advice you gave me with it. It is a rewarding experience as a first project.

**Comment by ryankscott** [comment]
No longer relevant as we do not intend to support the link-expansion extension
