### ISSUE TITLE
Sidebar explorer doesn't scroll vertically from scrolling after scrolling horizontally

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#1574]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Surface Laptop running Chrome 71 on Windows 10

#### Steps to reproduce:

1. Visit a repo file with enough files in the repo tree to cause both horizontally and vertical scrollbars. Example: https://sourcegraph.com/github.com/Microsoft/tslint-microsoft-contrib@9084d549f575db25c5818d6196ab8d381f9253fd/-/blob/src/tests/MissingOptionalAnnotationTests.ts
2. Use two-finger trackpad scroll _horizontally_ on your Surface Laptop _(presumably other forms work 😊)_ 
3. Try scrolling vertically in the same way

I tried this out with some other divs on webpages without JavaScript and it didn't repro. Still feels like a browser bug but who knows...

To be clear, it's this `#sidebar`:

![image](https://user-images.githubusercontent.com/3335181/50427143-f405f780-086d-11e9-8452-0459050a0f0e.png)

#### Expected behavior:

Scrolling vertically should be possible after horizontal scroll

#### Actual behavior:

At step 3, it'll slightly scroll horizontally instead of vertically. The problem goes away if you skip step 2 or resize the screen.

**Comment by JoshuaKGoldberg** [comment]
😕 I was able to repro this on multiple pages but am no longer able to... spooky. Never mind!

**Comment by sqs** [comment]
Hmm, this is very strange. I am not able to repro on Chrome 71 on 2 different Linux machines, 1 with a mouse and 1 with a trackpad.

- Can you repro if you use a different pointing device (such as a mouse instead of a touchpad) or scrolling method (such as using arrow keys)?
- When it is preventing you from scrolling vertically, is it still showing vertical scrollbars? Can you scroll vertically with the arrow keys and/or by clicking on the scrollbar up/down buttons?

**Comment by JoshuaKGoldberg** [comment]
It's not coming back. Sorry for the noise haha

**Comment by sqs** [comment]
All good, thanks!
