### ISSUE TITLE
var automatically replaced by const in definition of variable on hover, which is not correct as var is there in original source code

### ISSUE THREAD

**Issue by sktguha** [sourcegraph/sourcegraph#15791]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Chrome on Macos catalina

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/facebook/react@765e89b908206fe62feb10240604db224f38de7d/-/blob/fixtures/legacy-jsx-runtimes/react-14/cjs/react-jsx-dev-runtime.development.js#L180:36
2. It should automatically show definition of `functionName` , if not hover above `functionName`
#### Expected behavior:

It should show `var functionName = innerType.displayName || innerType.name || '';` on hovering above `functionName`

#### Actual behavior:
It shows as const , refer image below
![image](https://user-images.githubusercontent.com/8387608/99227144-dac71500-2810-11eb-99ce-01bf2cf693b7.png)

Which is definitely not correct, as in original source code it is `var functionName = innerType.displayName || innerType.name || '';`

Thanks
Saikat Guha
sktguha@gmail.com

**Comment by efritz** [comment]
Unfortunately this is an example of where our [basic search-based code intelligence](https://docs.sourcegraph.com/code_intelligence/explanations/basic_code_intelligence) falls short. If you [search for the `functionName` symbol in this repository](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/facebook/react%24%40765e89b+type:symbol+functionName&patternType=literal), you'll see the definition it _thinks_ that the symbol you're hovering refers to. You'll jump to the same symbol if you press the "Go to definition" button on that tooltip.

Search-based code intelligence (that you're seeing here) doesn't have contextual or semantic information. In order to get more precise definitions and references for this repo, we'll need to [ensure that an LSIF index exists for facebook/react](https://docs.sourcegraph.com/code_intelligence/explanations/precise_code_intelligence) on the Sourcegraph.com instance.

We're currently putting engineering effort into indexing popular repositories such as this, so you will likely see improved results in the upcoming weeks.
