### ISSUE TITLE
Allow users to mount local files into containers

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#15821]
Run steps can quickly become complex. Allow users to extract those steps to an external file, include the file in their Docker container, and successfully execute the result.

**Comment by mrnugget** [comment]
Is this about documentation or the feature? Because the feature doesn't exist. We currently don't allow users to mount local files into the containers. You _can_ [create files inside the container by specifying their contents](https://docs.sourcegraph.com/campaigns/references/campaign_spec_yaml_reference#examples-6), but you can't mount local files into it.

@eseliger and I had a prototype for this, but we ended up wondering how it should work:

- do you specify the path of the local file relative to the location of the campaign spec? or is it relative to where you run `src campaign apply|preview`? or is it absolute?
- do we add a separate `mount` property instead of reusing `files`?

**Comment by sdann** [comment]
In our case, using `files` is what became complex, trying to write a shell script indented within a YAML file. So we used COPY within our custom Dockerfile to include scripts at image build time, instead of at `src` runtime.

A `mount` section in the Campaign YAML would save us that step and allow us to skip a custom Docker container for this use case.

**Comment by mrnugget** [comment]
Thanks @sdann! Let's use #14851 as the ticket for this then, since this seems to now be a duplicate.
