### ISSUE TITLE
Keep merged and closed changesets in campaign to retain change log

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#16031]
We currently drop all changesets from a campaign where we don't have a new changeset spec. That means when something got fixed upstream by merging one of the changesets, when I reapply that merged changeset will disappear from the campaign (because my search didn't return this repo anymore).

I think we should investigate if we can keep merged/closed changesets (and potentially also the ones we close).

**Comment by malomarrec** [comment]
When I measure the result of a campaign, 
I want to know the total effort I put into the campaign, so I need it to show show all the changesets, including closed ones.

This is important for enforcing code invariants.

**Comment by malomarrec** [comment]
Why don't we keep all changesets (regardless of status) in the campaigns?

**Comment by malomarrec** [comment]
Version 1:
(v1) When I apply, "detached" changesets go to the "Archived tabs.
(v1) Archived changesets count towards the total. I can filter in / out "Archived" changesets in the burdown view. 
(v2) I can then go to the Archived tabs, and detahc them


Needs investigation on customer dependencies. Is this gonna break customer workflows?

**Comment by mrnugget** [comment]
We just agreed on the scope of this in the sprint planning:

- Feature flagged
- The `changeset.campaign_ids` association will have additional "archived by application of spec" (or something)
- If feature flag is on, changesets are not detached by default, but archived
- If feature flag is on, archived changesets show up in a separate tab
- If feature flag is on, archived changesets count towards progress
- If feature flag is on, the "preview" screen will show "archive" instead of "detach" operation

**Comment by mrnugget** [comment]
Oh, and that @eseliger will help me with the frontend work on this.

**Comment by mrnugget** [comment]
Follow-up TODOs to https://github.com/sourcegraph/sourcegraph/pull/18559:

- [ ] Add button to burndown chart that toggles archived changesets on/off
- [ ] Add number of archived changesets next to "archived" tab
- [ ] After applying a spec and that archived changesets, show a dismissable note "14 changesets have been archived"
- [ ] Backend: change the default scope to also exclude changesets where "Archive: true" so that they don't show up in the "changesets" tab when they're being reconciled to be archived, but instead show up in the "archived" tab
- [ ] Add tooltips to operations, see https://github.com/sourcegraph/sourcegraph/pull/18559#issuecomment-802861387

**Comment by mrnugget** [comment]
FYI @malomarrec the tooltips are already there (you proposed adding them in https://github.com/sourcegraph/sourcegraph/pull/18559#issuecomment-802861387), as I just found out:


https://user-images.githubusercontent.com/1185253/112128081-5c1b2380-8bc6-11eb-88cf-873a734be0aa.mp4

**Comment by malomarrec** [comment]
Follow up work in comments above, as well as:
- add detach functionality from CLI

**Comment by mrnugget** [comment]
Closing this after getting #19353 over the finish line and creating https://github.com/sourcegraph/sourcegraph/issues/19702 for the follow-up on design feedback.
