### ISSUE TITLE
Add support for Gerrit

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#16079]
We want to add support for Gerrit so our customers who use Gerrit can enjoy Sourcegraph in code reviews.

Some details: 
- Gerrit is both code host and frontend
- We do not need a Gerrit Plugin (we can use the browser extensions)
- Instance version TBD

**Comment by Joelkw** [comment]
@marekweb confirmed clarity [here](https://sourcegraph.slack.com/archives/CMT39K56Z/p1606178075486600?thread_ts=1605739464.384500&cid=CMT39K56Z): "expectations will be met when Gerrit support provides code intelligence (and other extensions) on Gerrit code view pages (like diff or blob pages) to the same degree the browser extension does on github.com."

**Comment by marekweb** [comment]
Gerrit support update:

- On the back-end, we have Sourcegraph syncing with Gerrit git repositories mostly successfully. There have been some glitches which are being investigated in a [separate issue.](https://github.com/sourcegraph/sourcegraph/issues/16387)
- On the front-end side of the integration, an added challenge has been to interact with the DOM containing shadow roots, because the interface is built with [web components using Polymer](https://github.com/gerrit-review/gerrit/tree/master/polygerrit-ui). I'm implementing workarounds for this.

**Comment by felixfbecker** [comment]
@marekweb can this be closed?
