### ISSUE TITLE
Remove configmap/config-file resource from Sourcegraph.com k8s

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1610]
Sourcegraph.com's k8s deployment and dogfood's k8s deployment both still have a `configmap/config-file` resource that has settings set in it. We've seen that it makes it harder for other teammates to make changes if they are unsure of whether our own deployment is using legacy/deprecated functionality, so this resource should be removed or made 100% empty (so that anyone viewing it knows it is not relied upon, and all config is stored in the DB).

This blocked me when I was working on #929. I want to remove `httpStrictTransportSecurity` from it, but I don't know whether it is still in use. I could spend the time to confirm yes or no, but as long as it remains, anyone else in a similar situation would need to spend that same time, so it is better to just remove or empty it.

Related to #1538 but not the same (that issue is about removing it from deploy-sourcegraph, this one is about removing or emptying it in prod)

**Comment by slimsag** [comment]
This can be removed at the same time and as part of #1538, so I am closing this.

It is not in use anymore, you just need to use the management console to make config changes.

I understand the desire to remove it ASAP, but it is counter-productive to do so ahead of #1538 because (1) it removes the ability for us to cleanly test removal as part of #1538 in the future and (2) it requires a context shift from other work. Instead, we can just address this by sharing some simple knowledge: you only need to use the management console / site admin area for updating config. Nothing else.
