### ISSUE TITLE
Cleanup changesets that have been detached for a while

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#16122]
I think those would currently remain in the DB forever. We might be able to clean them up after some time to get back some performance on those tables for long-living instances.

**Comment by mrnugget** [comment]
Just a note: we currently don't have a way to find out _how long_ a changeset has been detached (which is the "for a while" in the title of this ticket).

**Comment by eseliger** [comment]
Hmm, right. Since we do have updated_at and those aren't synced, that might help. But we could also introduce a separate state

**Comment by mrnugget** [comment]
> Hmm, right. Since we do have updated_at and those aren't synced, that might help.

I wouldn't rely on that though, since that's just an implementation detail that might change.

One "proper" way would be an additional timestamp field that's set when the changeset is not attached anymore. Another way would be join table that records relations to campaigns and whether they're active or not.

**Comment by Piszmog** [comment]
Dependent on #36359
