### ISSUE TITLE
campaigns: don't update diff stat until after changeset reconciliation is complete

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#16196]
This only applies to updated changesets, rather than new ones: we currently update the cached diffstat on the changeset before even enqueuing the operation to push the updated branch to the code host. We should defer that until after the push has actually succeeded.

**Comment by eseliger** [comment]
I wonder why this is a problem. Maybe we just need to return the changeset_spec.diff while a changeset is processing, rather than doing the slightly trickier "deferred state update"?

**Comment by mrnugget** [comment]
> I wonder why this is a problem. Maybe we just need to return the changeset_spec.diff while a changeset is processing, rather than doing the slightly trickier "deferred state update"?

But that would be the same thing: we _do_ update the `changeset.diffStat` to `changesetSpec.diffStat` when applying a new spec. The problem is that updating the changeset on the code host might fail and then the `diffStat` shows the _new_ diff stat but the diff view shows the current state on the code host, which doesn't match the `diffStat`

**Comment by eseliger** [comment]
yeah but that would be fixed if in non-published-completed states the `changeset_spec.diff` is returned, no? that would also fix us not rendering the diff for processing changesets, I guess.

**Comment by mrnugget** [comment]
Not sure I understand correctly: are you saying that we display the `changeset_spec.diff` when the `changeset.ReconcilerState != ReconcilerStateCompleted`?

That _could_ be weird, I think, because if we previously pushed diff A to the code host, and then the user tries to update to diff B and it errors, we'll show diff B even though diff A is on the code host (and is the diff on which the CI status, the view status, etc. are based)
