### ISSUE TITLE
Site admin, admin user campaigns tokens, remove user token actually removed own token

### ISSUE THREAD

**Issue by jensim** [sourcegraph/sourcegraph#16217]
- **Sourcegraph version:** 3.22.0
- **Platform information:** 

#### Steps to reproduce:

<img width="1055" alt="Screen Shot 2020-11-27 at 12 30 00" src="https://user-images.githubusercontent.com/3663856/100445321-31eca580-30ad-11eb-8ff3-62c94543ae83.png">

<img width="468" alt="Screen Shot 2020-11-27 at 12 34 36" src="https://user-images.githubusercontent.com/3663856/100445318-30bb7880-30ad-11eb-8ee1-e229971db9a1.png">

#### Expected behavior:
The users access token to be removed

#### Actual behavior:
Your own access token is removed.

**Comment by eseliger** [comment]
Thanks for reporting! You're totally right... We'll fix that!

**Comment by eseliger** [comment]
Two things need to be done here:

- Fetch the credential list for the _viewed_ user, not the authenticated user. That will fix the wrong tokens being displayed and will fix deleting the wrong tokens as well. (I think)
- Add a `user: ID` property to the `createCampaignUserCredential` mutation to select the user. We decided against having that because we can infer the user from the `ctx`, but that's not the correct user for site-admins that edit tokens for _other_ users.
