### ISSUE TITLE
Add configuration option to set a list of files that should be searchable regardless of their size

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1624]
We currently exclude large files (> 1MB) from searches (https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dd08f0db515f5c89e818afadd5e8af6d9250ca5b/-/blob/cmd/searcher/search/store.go#L280). In most cases, this is preferred, as large files are often generated and users do not want to view them in search results.

In some cases, however, a user would like to increase the max file size limit.

Proposal: add a `maxFileSize` search query keyword that overrides the default max of 1MB.

Other customer context: https://sourcegraph.slack.com/archives/G9EN3TJDD/p1550603834001000

**Comment by beyang** [comment]
cc @sqs

**Comment by gergelyke** [comment]
Thanks for taking this on @beyang ! Any chance you have a timeline for 3.1?

**Comment by sqs** [comment]
@gergelyke We plan to ship Sourcegraph 3.1 on 2019-02-20.

**Comment by nicksnyder** [comment]
Is the file size limit applied at index time or search time? If it is the former then it will be harder to override on a per-search basis and we might have to consider other solutions:
- Have a message that says files were skipped due to size
- Always index certain files that are large (e.g. yarn.lock, package.lock)
- Fallback to non-indexed search only for files that are too big and only if we haven't saturated max count
- etc.

**Comment by keegancsmith** [comment]
For indexed search it is at index time. For JIT search, we exclude large files as we stream in the `git archive`.

**Comment by sqs** [comment]
This will not ship in 3.1, unfortunately. We plan to prioritize it for 3.2 (shipping on March 20).

**Comment by sqs** [comment]
Alternate proposal (instead of adding a `maxFileSize` query or site config option):

- Index the following files even if they are very large (<= 20 MB): `["package.json", "yarn.lock", "package-lock.json", "go.mod", "go.sum", "*.idl", "*.proto", "*.thrift", "*.graphql"]` **PLUS** any filenames or `*.fileextension` strings mentioned in a *new* site config option `search.index.largeFiles`
  - We can add entries to this default list at will, e.g., for other programming languages' dep manager lock files. There is very little downside to adding new patterns to it (as long as they don't match a TON of large files). 
- "Very large" is hardcoded as 20 MB. (I.e., a 19 MB yarn.lock file will be indexed. A 21 MB yarn.lock file will not be indexed.) This should be large enough to cover the vast majority of such files, and any larger than 20 MB is (arbitrarily deemed) very rare. For comparison, the default max file size for the indexer is 1 MB.

Most customer problems we've heard related to this issue would be solved by the default list above. In case we missed any files/extensions, site admins could add additional patterns.

Other notes:

- We need to add a way to trigger a reindex, and possibly automatically trigger reindexes on all (affected?) repositories when this value changes.
- We need to make sure this applies to searcher as well (causing it to not skip the specified large files).
- I think this is better than specifying a `maxFileSize` because that will likely result in the inclusion of many more unwanted files in the index.

**Comment by aisbaa** [comment]
I like this approach more than `maxFileSize`!

**Comment by ijsnow** [comment]
@sqs the proposed configuration option being named `search.index.largeFiles` suggests that this change only affects indexed search. However, you mentioned that we need to make sure this applies to searcher as well. Should the configuration option just be named `search.largeFiles`?

**Comment by sqs** [comment]
@ijsnow Yes, good point.

**Comment by keegancsmith** [comment]
Replying inline to some questions you asked on slack. As a more general point the sort of changes you are making here can be upstreamed to zoekt. I'd highly recommend doing that. The maintainer of zoekt is usually very responsive to CRs and gives good quality feedback.

> 2. My plan is to use `conf.Watch` to trigger code to hit the proposed update endpoint on the index server. Where should we add the `conf.Watch` logic to trigger updates? Would frontend’s main func be the proper location? Or repo-updater’s?

indexserver does polling. Part of that polling can be fetching the options to use. I would do that rather than introducing `conf.Watch` since it is simpler and would fit nicely into the current index server.

> 3. Should this logic go through the zoekt webserver or is it ok to communicate directly with the index server?

As I mentioned above, I think part of indexserver's polling. To make it more explicit, part of doing `resolve-rev` you also do a `getOptions` or something.

> 4. What needs to be done to trigger updates? It currently looks like I just need to update the setting on `Server` and the indexer will index it automatically because it’s indexing everything always (https://github.com/sourcegraph/sourcegraph/issues/3235)

The indexer will skip indexing if it the rev hasn't changed. I'm unsure if it detects if the options used to index have changed. You would need to update it to do that.

**Comment by slimsag** [comment]
> The indexer will skip indexing if it the rev hasn't changed. I'm unsure if it detects if the options used to index have changed. You would need to update it to do that.

@keegancsmith where is the code that actually does this? see #3235 because I couldn't find any that does it, all evidence seems to suggest it does not

**Comment by keegancsmith** [comment]
> > The indexer will skip indexing if it the rev hasn't changed. I'm unsure if it detects if the options used to index have changed. You would need to update it to do that.
> 
> @keegancsmith where is the code that actually does this? see #3235 because I couldn't find any that does it, all evidence seems to suggest it does not

Answered in that issue.

**Comment by keegancsmith** [comment]
FYI the code which decides whether to reindex or not is here: https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-archive-index/main.go#L144-149

**Comment by ijsnow** [comment]
This will not make it into 3.3. This is currently blocked by https://github.com/sourcegraph/sourcegraph/issues/3421.

**Comment by ijsnow** [comment]
The work for this feature is almost done:

- [x] `search.largeFiles` site setting added
- [x] Searcher support
- [ ] Indexed search support
  - [ ] google/zoekt supports the large files option. [In review.](https://gerrit-review.googlesource.com/c/zoekt/+/220077)
  - [ ] google/zoekt updates the index when options that affect the created index are changed. [In review.](https://gerrit-review.googlesource.com/c/zoekt/+/221562)

**Comment by beyond2002** [comment]
search.largeFiles site setting doesn't work for Github repo. file size larger than 1MB still not appear in the search results.
