### ISSUE TITLE
CNCF repogroup homepage improvements

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#16256]
As we talked about in the search data working session, the CNCF homepage requires two updates that is expected to address gaps that led to low retention. The priority of this work is TBD and will likely come in collaboration between the product and marketing teams when we engage the user base for a second time
1. Add search syntax references so new users have something to help them get started (as these can be landing pages)
<img width="234" alt="Screen Shot 2020-11-30 at 2 36 27 PM" src="https://user-images.githubusercontent.com/25422491/100655596-8300d180-3319-11eb-93f0-234c17d34cea.png">
2. Add a list of repos the repogroup contains so users know what they can search over
<img width="544" alt="Screen Shot 2020-11-30 at 2 37 31 PM" src="https://user-images.githubusercontent.com/25422491/100655653-96ac3800-3319-11eb-8615-c2b462b938da.png">

cc @christinaforney @kaciewj

**Comment by lguychard** [comment]
@limitedmage how would you estimate the complexity of using `<HomePanels>` on `<RepogroupPage>`, so that we can start showing the search syntax reference / other useful panels on these pages?

**Comment by limitedmage** [comment]
@lguychard  Instead of using the panels, we should make the CNCF homepage similar to other repogroup pages. Right now we are special-casing it to be an empty search page, as that was the original idea. We can start by removing that special casing to make it show example searches and repos available in other repogroup pages.

If we want to use the homepage panels instead, I would need a more detailed design to see how the whole page would be laid out before being able to give a good estimate.

**Comment by lguychard** [comment]
We do not expect to make changes to the CNCF homepage specifically until we tackle community pages more broadly.
