### ISSUE TITLE
Make sure that existing repos are searchable and accessible when rate limit is exhausted (graceful degradation)

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16392]
Follow up from https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#heading=h.r7tahw4ry14v

**Comment by ryanslade** [comment]
I'm unable to reproduce this locally.

I've manually updated `github-proxy` to: 

1. Always return an error OR
2. Always return 0 tokens remaining

In both cases I was able to browse and search as usual. The only error I've seen was that saving an external service fails since it can't check the token is valid which I think is fair enough.
