### ISSUE TITLE
Error fetching SAML auth provider... certificate signed by unknown authority

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1655]
- **Sourcegraph version:** 
- **Platform information:** 

#### Actual behavior:

From a customer:

>I am attempting to setup my own Sourcegraph instance to work via SAML. In the logs I keep seeing the following message

`
15:56:55 frontend | t=2018-12-31T15:56:55+0000 lvl=eror msg="Error refreshing SAML auth provider." id="{Type:saml ID:}" error="fetching SAML Identity Provider metadata: Get <REDACTED>/saml2/idp/metadata.php: x509: certificate signed by unknown authority"
`

>You can check the link, the certificate is valid.

**Comment by beyang** [comment]
This error occurs when the SSL certificate presented by the SAML authentication provider is not trusted in the Docker container running Sourcegraph. This is likely due to the certificate being issued by your internal security team, so it is not signed by one of the standard public CAs.

To fix this, we'll need to add your certificate to the list of trusted certs. This should be straightforward to do:

1. First, ensure your Sourcegraph Server instance is running via the `docker run ...` command.
1. First, obtain your cert by navigating to your SAML login URL in Chrome, open dev tools (cmd-shift-i), click the `Security` tab, click "View certificate", click "Details", click "Export", save the cert as a single base64-encoded text file called "saml.crt".
1. Copy the cert into the Docker container
    ```
    docker cp saml.crt $(docker ps --filter 'ancestor=sourcegraph/server:insiders' --format '{{.ID}}'):/usr/local/share/ca-certificates/saml.crt
    ```
1. SSH into the Docker container
    ```
    docker exec -it $(docker ps --filter 'ancestor=sourcegraph/server:insiders' --format '{{.ID}}') sh
    ```
1. Inside the Docker container SSH shell, verify the cert exists:
    ```
    ls /usr/local/share/ca-certificates/saml.crt
    update-ca-certificates  # (ignore the warning)
    ```
1. Go back to the Sourcegraph UI (do NOT restart the Docker container) and try to log in again.

**Comment by GL-KenDLG** [comment]
Hey @beyang,

The steps I took are the following:

1) Removed the default auth authentication config.

2)Added the saml config
`    {
      "type": "saml",
      "identityProviderMetadataURL": "https://domain.com/dag/saml2/idp/metadata.php"
    }`

3) That prompted for a server restart.
4) Navigating to the login page I now see: 
`Unexpected error refreshing SAML authentication provider.`

5) From there, I ran the docker cp command and got the following
`# docker cp saml.crt $(docker ps --filter 'ancestor=sourcegraph/server:insiders' --format '{{.ID}}'):/usr/local/share/ca-certificates/saml.crt
must specify at least one container source`

6) Modified the command and ran it again without issue:
`# docker cp saml.crt $(docker ps --filter 'ancestor=sourcegraph/server:2.13.5' --format '{{.ID}}'):/usr/local/share/ca-certificates/saml.crt`

7) After I finished running your commands, I am still seeing:
`Unexpected error refreshing SAML authentication provider.`

Note: It is entirely possible that I am just not configuring it correctly. I tried going off the docs but obviously I do not have it working. It might be helpful if we can jump on a call real quick.

Also, running a docker log on the container I still see:
`x509: certificate signed by unknown authority"`

I reverted back to the built in auth. If we can put some priority on this would appreciate it. Right now our engineering team is not using it since we have to have it working with SAML first.

**Comment by beyang** [comment]
@GL-KenDLG Thanks for walking through the steps above. I was able to reproduce this on our end, so I've escalated this to the development team. Let me follow up with them once a patch is available and then I'll shoot you an email to schedule a call to help you get this all set up.

**Comment by beyang** [comment]
I believe this was fixed awhile back. Please re-open if it is still an issue.
