### ISSUE TITLE
Collapse navbar items to hamburger menu on small screen sizes

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#16567]
#### Details

Navigation will grow by an element with the addition of code monitoring. That addition alone shortens the search box by 86 pixels  or around 10 to 11 characters.    With the display of ‘Get started’ for new users and code insights (which is feature flagged), the navigation is much too large to support the search bar. 

This Figma file explains the problem visually and presents a solution:

https://www.figma.com/file/QSEhj2Nt4MSYLTjqVa2mOO/Navigation-short-term-updates?node-id=2%3A6846&viewport=480%2C487%2C0.25

#### Impact 

High, the usability of the search bar will be significantly impaired. 

#### Urgency 

3.23

**Comment by Joelkw** [comment]
Yep, @rrhyne and I chatted about this. We'll move the extensions discoverability path to the action bar. This won't be a long-term solution, but it will serve our purpose until the design team has redesigned the nav bar (hopefully sometime by when code insights reaches GA, April-May-ish). I'll make sure this goes into an iteration before 3.23 ships (basically, not the current one but either of the next two).

**Comment by Joelkw** [comment]
@felixfbecker what do you mean "that" in "that is only displayed if you don't have any extensions"? I think the "Add extensions" '+' button is present even if you have extensions ([Figma link](https://www.figma.com/file/p7g56TD2qFbqxRJ4ODrbo7/RFC-250-Action-items-bar-Final-review?node-id=1161%3A0)).

**Comment by felixfbecker** [comment]
That's not how it's currently implemented. I'm talking about this button:

![image](https://user-images.githubusercontent.com/10532611/104756560-40c21100-575c-11eb-9216-627ec459adb2.png)

What you linked hasn't been implemented yet (that is a larger project)

**Comment by 5h1rU** [comment]
> So the task here is to just remove the "Extensions" item? Since we already have "Add extensions" in the actions bar. That is only displayed if you don't have any extensions though, so I think we should at least add it back to the user menu.

Extensions link is already on the user menu. Saying that I think removing the extensions button from the navbar is safe.

**Comment by AlicjaSuska** [comment]
@5h1rU please, take a look at the designs in [Figma](https://www.figma.com/file/QSEhj2Nt4MSYLTjqVa2mOO/16567-Navigation-short-term-updates?node-id=12%3A299). The scope of this issue is:

- remove the 'Extensions' tab from the nav bar (it remains only in the user menu)
- items that should be displayed in the nav bar:
-> avatar
-> command palette
-> tabs: campaigns and code monitoring (for all users), insights (if enabled in settings), getting started (for new users)
-> search bar and logo
- collapse tabs to the hamburger menu for width <=1025px
- create a [menu](https://www.figma.com/file/QSEhj2Nt4MSYLTjqVa2mOO/16567-Navigation-short-term-updates?node-id=11%3A245) that opens from the hamburger icon that contains the tabs

The 'add extensions' button that @felixfbecker mentioned above is present only on code-oriented pages for the users who have only default extensions enabled. That doesn't change :)

**Comment by AlicjaSuska** [comment]
@felixfbecker @5h1rU this issue should be still open - #17389 only closes the first part (remove extensions) but doesn't address the hamburger menu
