### ISSUE TITLE
Search alerts should be rendered as markdown so links are clickable

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#16576]
![image](https://user-images.githubusercontent.com/10532611/101627393-977e5180-3a1e-11eb-8ca3-25cff737b431.png)

Note that the link is not clickable

**Comment by rvantonder** [comment]
I've tried putting markdown in search alert messages coming from the backend in the past, and they don't render as markdown int he frontend. I don't know if it's intentional. Either way this is a web-rendering issue IMO.

<img width="378" alt="Screen Shot 2020-12-17 at 11 46 47 PM" src="https://user-images.githubusercontent.com/888624/102583588-36abe480-40c2-11eb-9180-8154be15c753.png">

**Comment by rvantonder** [comment]
(added back search label so we can enable this for backend alerts if markdown does get rendered in front end)

**Comment by felixfbecker** [comment]
This is a frontend issue, but not one that should be owned by the web team. The search alerts are rendered in search (client) code and we have simple utility functions available to render markdown so I don't see a web platform issue. If there is, please let us know.

**Comment by lguychard** [comment]
@limitedmage is this handled by the search results redesign, or will it still be an issue?

**Comment by limitedmage** [comment]
> @limitedmage is this handled by the search results redesign, or will it still be an issue?

We addressed this for streaming search "skipped items" alerts but I don't think we did for the rest of alerts.

**Comment by lguychard** [comment]
Should be handled as part of search alerts redesign: https://github.com/sourcegraph/sourcegraph/issues/21036
