### ISSUE TITLE
src-cli progress reporter can print negative times

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#16740]
And they seem to be stuck, too.

![image](https://user-images.githubusercontent.com/19534377/102162890-55c03180-3e8a-11eb-84b4-34bf1ca32606.png)

**Comment by mrnugget** [comment]
Closing this because I just came across it and don't think it's a problem anymore with the revised UI system we now have in src-cli.

See these two commits for an entrypoint into the new system: https://github.com/sourcegraph/src-cli/commit/26a97591d39f1698976817830251107fac9de6ad and https://github.com/sourcegraph/src-cli/commit/e486e84e8e79fa1443e162749336ec3bc22fdf9c
