### ISSUE TITLE
Deprecate external service tokens in batch changes in 3.29

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#16814]
To fully make campaigns separate from the external service configs, I think we should want to migrate the syncer away from using their tokens. Instead, we should want to import and sync using the users token. 

The problem: What user are we getting the token from? 
For changesets published by campaigns, this is currently pretty simple: The last applier of the owning campaign is the token donor. That connection is: changeset->owning_campaign->last_applier

For imported changesets, however, we don't have this kind of connection. What we _could_ do:

We use changeset->campaigns->last_appliers, which would be all last appliers for all the campaigns the changeset is tracked in. 
That, however, would be hard to fix for users when one of the last_appliers has a bad credential stored, for example. Currently, we don't even expose syncer errors so it would be hard to debug for users. 
It certainly isn't any worse than the current state, so I think we might still want to do that as a short-term fix, but we should ultimately try to find a better solution - as a follow-up item.

**Comment by chrispine** [comment]
Is this coming from a user issue, or an anticipated issue, or paying down tech debt?

**Comment by mrnugget** [comment]
> Is this coming from a user issue, or an anticipated issue, or paying down tech debt?

I think it's "anticipated issue" and "possible improvement with regards to the rate limits".

---

I removed the estimation label, because I think there are still a few details missing in the proposal that would influence an estimate.

I also want to say that I don't think the current state is necessarily a problem: changesets are, as soon as they're created or imported, global entities in Sourcegraph and can belong to more than one campaign and can be viewed by more than one user. In that they mirror repositories in Sourcegraph. And those are also synced by the tokens set in the code host (external service) configuration.

With regards to code host rate limits it would be nice if we could use more than one token to sync changesets, but just as mentioned in the orignal issue here, it's not _that easy_: which token should we use if a changeset has been imported by multiple campaigns? what if one campaign created it and others import it? what if the user was deleted, which token do we then use? do we fall back to the global one? what if the token's rate limit is exhausted, do we then fall back to the global one?

I don't think we can get away without a fallback to the global one, so before we tackle (and estimate) this, we should be clearer about what this even and whether we want to do it.

**Comment by chrispine** [comment]
Needs an RFC

**Comment by chrispine** [comment]
This also needs an estimate (after the RFC)

**Comment by malomarrec** [comment]
I think this issue is aggravated by RFC 312 :slightly_smiling_face:
Now there are 2 (+1) ways to set things up 
* Service account
* My PAT
* (and be careful, because the site admin PAT is used for tracking)

When a user sees permissions issues, drilling down to the cause is becoming complex, because there are 3 places to look at.
