### ISSUE TITLE
Monitor disk allocation for elastic cloud, define retention policy

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#16962]
Our current logging burns through a significant chunk of disk. We may need to scale our elastic deployment to ensure it doesn't run out of space.

Relevant [slack thread](https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1608667498407900)

This work should also encompass defining our retention policy for logs

**Comment by chayim** [comment]
I changed the indices for pubsubbeats to have a lower retention. Retentions are set to 15d prior to swapping to cold storage, 30d retention by default. Disk allocations are solved by the other PR. For now, this is set using the ILM UI - since it's fast.

https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html
