### ISSUE TITLE
Commit search fails to find commit by message

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#16969]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Go to https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+14588&patternType=literal
2. Note that there are no results
3. Go to https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+docsite+&patternType=literal
4. Note that there are results, including a commit 428cbbf4d7913dcae860c230ff87e80cae027b12 whose message contains the query from step 1 (`14588`)

The same problem occurs with other queries that should work (such as `docsite fails` not just `docsite`).

#### Actual behavior:

Because `14588` is in the commit message, 428cbbf4d7913dcae860c230ff87e80cae027b12 should show up in the results in step 1.

**Comment by rvantonder** [comment]
This almost certainly due to/duplicate of https://github.com/sourcegraph/sourcegraph/issues/13313, and I proposed solutions there. The easy way to see the first query fails is by simply doing `type:commit message:14588` instead of omitting `message`. Agree on the expected behavior--the existing behavior has been this way for ~2 years I think.

**Comment by rvantonder** [comment]
Confirmed change is live and working on Sourcegraph.com for that first query https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+14588&patternType=literal

**Comment by sqs** [comment]
@rvantonder Thank you!

**Comment by rvantonder** [comment]
Credit to @camdencheek for pushing the fix :-)

**Comment by sqs** [comment]
Thank you, @camdencheek!
