### ISSUE TITLE
Code intel popover/hover closes unless mouse movements respect rollover areas

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#17065]
When the user moves their mouse from a highlighted keyword to the code intel hover popover, it is easy to inadvertently move outside of both the highlighted keyword and the hover popover which causes it to close. 

See illustrations of the problem and a potential solution:

![image](https://user-images.githubusercontent.com/539268/103710766-b6fb9200-4f6a-11eb-936d-cca338ecbf77.png)

**Comment by Joelkw** [comment]
@rrhyne quick question – I definitely see the advantage of expanding the hover area to prevent unintentional closures (and your illustration is a great way of describing this!), but I am concerned that expanding the hover area might actually prevent you from hovering another symbol hidden in this area without having to move your mouse away and then back, which is also a frustrating interaction. I can think of/find many cases in the code where symbols would be close enough together to be "under" either of these yellow boxes. 

I know that a deactivation delay might come with its own problems – it might leave ghost hovers onscreen too long – but do you think if we got the timing right then it could solve the same problems, and now you only have to wait ~.1 second if you need to hover a symbol that is otherwise hidden in this yellow area?

**Comment by rrhyne** [comment]
@joel multiple rollovers in a single area is an edge case we have no data on. The primary issue being reported happens often and restricts the primary action a user needs to take. 

The proper deactivation delay would vary for each user (their mouse speed settings and speed of motion are different), so you end up setting the delay higher to accommodate. This makes the UI seem slow. We don't want that.

**Comment by Joelkw** [comment]
(@felixfbecker I think this should be extensibility? Updated.)

**Comment by felixfbecker** [comment]
On the proposed solution, a hover area extended to the right (not a timed delay) seems like a non-starter because it would prevent you from hovering adjacent tokens. It would make the feature feel broken. The example screenshot doesn't show this because it shows a JSON file (just one key per line). That's not the common case for code. I think time-based is the only option. Maybe you could calculate the user's mouse trajectory but that's way too complex.

**Comment by olafurpg** [comment]
An alternative proposal would be to replace the "Go to definition" and "Find references" buttons with cmd+click, right-click menubar and keyboard shortcuts similar to how it works in VS Code and IntelliJ.

### VS Code
![CleanShot 2021-04-15 at 11 29 17](https://user-images.githubusercontent.com/1408093/114847369-ed547300-9ddd-11eb-8cef-30bdcdbf3215.gif)

### IntellliJ
![CleanShot 2021-04-15 at 11 27 37](https://user-images.githubusercontent.com/1408093/114847377-f0e7fa00-9ddd-11eb-9d36-8a885a535343.gif)

Most people are using Sourcegraph alongside their editor so I think it would be nice to offer the same UX.

I agree with @felixfbecker that's it's problematic to increase the size of the hover area because it's common to have multiple tokens on the same line.

**Comment by felixfbecker** [comment]
@olafurpg I think that's an orthogonal issue. We're a read-only/read-optimized UI the web, not a native application/IDE, so we have a bit different constraints and patterns. I don't think adding single-click functionality is a bad idea, but we'll likely still want to keep the buttons _in addition_ to that because a cmd+click shortcut or right click menu is not discoverable, at least not on the web where the right click menu is usually the browser native menu for things like "Open in new tab" and users won't naturally go to look there (and overriding it is a bit problematic for accessibility reasons). Making tokens proper links is something we may want to investigate anyway though for accessibility.

We have some experiments BTW around this you can enable in settings: https://github.com/sourcegraph/sourcegraph/pull/3444
I can't find an issue tracking it, might be worth filing.

Also referencing the original issue for the OP: https://github.com/sourcegraph/codeintellify/issues/48

**Comment by olafurpg** [comment]
@felixfbecker #3444 was an interesting link, thank you for sharing that!

It's a good point that the buttons are important for discoverability. I don't agree this is an orthogonal issue, the current behavior of the hover area can remain unchanged if we introduce alternative ways to navigate to definition/references.

Google Codesearch uses proper links for tokens, example https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/util/SimpleLogHandler.java;l=870;drc=cb37ecb70ac08b15e0371421f498a6e551ab875a;bpv=1;bpt=1 

![CleanShot 2021-04-15 at 12 47 41@2x](https://user-images.githubusercontent.com/1408093/114857793-f991fd80-9de8-11eb-84fc-69b5580dddbd.png)

At reference-site, the link points to the definition and at definition-site the link points to references. This seems like a good solution that is also consistent with Cmd+click in VS Code and IntelliJ (clicking on the definition shows references).

Google Codsearch also has a custom right-click menu, which I personally think is nice and intuitive. I can imagine this is a more controversial UX decision due to accessibility issues among other things. However, I suspect a large majority of users expect webapps like Sourcegraph to have a custom right-click menu because it's so widely available in alternative tools. Including webbased apps like Google Codesearch and [github1s](https://github1s.com/AgoraIO/Basic-Video-Call/blob/HEAD/Group-Video/OpenVideoCall-Web/src/pages/meeting/meeting.js).

<img width="1128" alt="CleanShot 2021-04-15 at 12 51 20@2x" src="https://user-images.githubusercontent.com/1408093/114858263-86d55200-9de9-11eb-9ee0-b00d7f7ba357.png">

It's worth keeping in mind that Sourcegraph may support more LSP features in the future

- go to type definition
- go to implementation
- go to declaration

All of those features are available via shortcuts and right-click menus in IDEs and that's how most users will expect to find those actions on Sourcegraph.

**Comment by rrhyne** [comment]
I'm ok with the time-based approach Joel and Felix proposed. 

I agree the right click to open causes discoverability issues and would not want to go down that path without the user explicitly setting this as an option. A setting would allow users to discover the behavior initially, then map their experience to their IDEs.

**Comment by Joelkw** [comment]
Thanks @rrhyne ! I'll add this to our queue and we'll experiment live (and include you in that) with what time delay "feels" right.

**Comment by Numbers88s** [comment]
Fixed.
