### ISSUE TITLE
monitoring: Demo new api features

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#17062]
Create a demo dashboard for an existing service with more functionality as a means of showcasing the new API

**Comment by bobheadxi** [comment]
Instead of a dashboard, I think we should instead implement new configuration presets of some sort, since the main thing we'll want to showcase is the capability to both make extensive customizations and have them be shared. That said, some updated panels would be a good showcase (instead of a full-blown dashboard)

I think a good candidate to try and "rework" would be the resources dashboards in `monitoring/definitions/shared`, which currently look less than ideal for services with large numbers of replicas

**Comment by pecigonzalo** [comment]
@davejrt @bobheadxi something that was suggested by @tsenart was that we should model the dashboard in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/dashboards/files/gitserver-cloud.json with the new API. This will work as a good test of our ability to model some of the required panels.

**Comment by bobheadxi** [comment]
> we should model the dashboard in sourcegraph/deploy-sourcegraph-dot-com@release/dashboards/files/gitserver-cloud.json with the new API.

I would aim for a slight adjustment to this, instead of modelling the entire dashboard incorporate it as much as possible into the existing git server dashboard

**Comment by davejrt** [comment]
Closed via https://github.com/sourcegraph/sourcegraph/pull/17845

**Comment by pecigonzalo** [comment]
@davejrt I checked https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server while closing this project and there seems to be a bunch "No data" panels. I believe some query might be missing, I suspect its the Shard selector which is present in the manual panel.

**Comment by davejrt** [comment]
Yeah i noticed this as well after deploying on Friday, will circle back here today and make any adjustments as needed before closing.

**Comment by davejrt** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/17926
