### ISSUE TITLE
Show both "current monthly users" and "total users" in the admin UI

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#17098]
Based on customer feedback from multiple customers and logged by @justdueck – 

In our admin dashboard at /site-admin we have this displayed: 

![image](https://user-images.githubusercontent.com/11967660/103806182-8159b600-5009-11eb-8ede-0cc7ed17ac6c.png)

We want that to show both highest-ever count but also still available if that number has since decreased via user deletion or folks no longer active, via showing a separate count next to this that accurately reflects the next MAU billing number of users.

**Comment by dadlerj** [comment]
I posted https://github.com/sourcegraph/sourcegraph/issues/17282 without realizing this existed!

My message from there (reposting for additional details):

=====

The question of how the number of licenses used on the Site-admin > Overview page is counted has come up several times recently. Customers will delete a group of users, but the X in the "X used / Y remaining" count doesn't change.

Recently:
- https://app.hubspot.com/contacts/2762526/company/554275594
- https://app.hubspot.com/contacts/2762526/company/690744415
- https://app.hubspot.com/contacts/2762526/company/557475882
- https://app.hubspot.com/contacts/2762526/company/5184085451

Problem:

The licenses used count at Site-admin > Overview page reflects the **max** count of user licenses, not current.
![image](https://user-images.githubusercontent.com/5589410/104620728-2a289680-5644-11eb-967c-740964c5e42a.png)

If they subsequently delete users, this number doesn't go down, even though those seats/licenses are re-assignable.

Showing this was once intentional, because we bill based on the max. E.g., if a company has a license for 100 users, but they hit 101, then we will bill them for that next tier of users, even if they subsequently delete them to get below 100.

That said, it's very confusing, and customers don't realize that they are reassignable.

I think a VERY simple solution to this is go from:

`X used / Y remaining` 

to:

`Z currently used / Y remaining (X maximum ever used)`

Where:
- X and Y stay the same as they are today
- Z === current user count (same as what is displayed lower down on the Site-admin > Overview page, and what is displayed on the Site-admin > Users page

Follow-ups to this issue include:
1. A refactoring of the Site-admin > License page, which desperately needs some refreshing
2. Changes to all of these numbers/pages to account for non-standard licenses (e.g. MAU billing)

**Comment by Joelkw** [comment]
@AlicjaSuska I'm fine with implementing a quick text change (I think this is be a small change overall) but just wanted to make sure you saw this in case there are other patterns you want us to consider or used elsewhere that I'm not aware of!

**Comment by felixfbecker** [comment]
@AlicjaSuska anything you want to add here, or can I remove `needs-design`?

**Comment by AlicjaSuska** [comment]
@umpox to unblock you on this one:

I think it's a good change to show current monthly users. Anyways, I'm not sure if `Z currently used / Y remaining (X maximum ever used)` explains the 'monthly' aspect correctly. How about

`Z current monthly users / Y remaining (X licenses ever used)`? @dadlerj @Joelkw 

In addition, I would consider adding an info icon with the tooltip that explains what 'ever used' includes and that it's possible to reassign licenses. Alternatively, we could add a link to docs (if we have it explained somewhere, I couldn't find relevant info. @dadlerj ?)

**Comment by dadlerj** [comment]
I suppose this issue does have a key difference from my other issue. Mine didn't contemplate showing MAUs at all, it only focused on the definition of seats/licenses used. My proposed solution of `Z currently used / Y remaining (X maximum ever used)` would use:

* Z == current licenses used
* Y == difference between licensed total and current
* X == max licenses ever used

Since this is how we bill (most of) our customers.

Adding MAUs onto this "license" panel would only add confusion actually, since the vast majority of customers don't use MAUs in billing. The exception of course is that some customers DO use MAU-based billing, which is an additional wrinkle.

Note that we do already show WAU count on the site-admin overview page, just a bit lower. We could update this to show MAU by default if the desire is to show that to everyone.

![image](https://user-images.githubusercontent.com/5589410/105757524-e9156980-5f02-11eb-8b54-145f10b4cbfe.png)

**Comment by Joelkw** [comment]
@AlicjaSuska I echo what Dan said – I think the word "monthly" might otherwise confuse more than clarify given that we bill based on max. (Also, if it's "monthly" then this have to reset every single month and start counting up to be truthful? The customer doesn't need that.) I didn't expect there to be too much and just wanted to get your confirmation on these changes –  my apologies if the word "monthly" in my issue title added more confusion (I am also learning a bit about how we bill from what Dan posted). 

So I think `Z currently used / Y remaining (X maximum ever used)` works fine given this, unless there's another reason @AlicjaSuska that isn't clear?

**Comment by AlicjaSuska** [comment]
Yes, let's move forward with this one @Joelkw Thank you! I took this issue as more complex than it actually is 🙈 @umpox FYI

**Comment by umpox** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/commit/03f25bff297d15d4d83da9de982928bf5c7a4f90
