### ISSUE TITLE
Show additional (higher) levels in the file tree view on file pages

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#17122]
[This customer](https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001dCDxNAAW/view) initiated this request. 

On the file tree view (panel to the left when viewing a file), we currently show you the directory your file is in and let you expand all sub-directories, but you can't navigate higher in the tree. There are times when users want to look at the directory structure of the entire repo and browse other files. 

One note – we don't re-load the file view right now, so if you start at a higher-directory file and navigate to a lower-directory file in this view, it still shows higher-level directories. 

The view in question: 
![image](https://user-images.githubusercontent.com/11967660/103945733-79be0e00-50ea-11eb-9db6-37958a747aa1.png)

Direct feedback: "Basically getting to the top level of the repo will be sufficient. Currently when jumping to files with go to definition the default is to show only the most inner directory of the file that I jumped to which makes it hard to understand its context or navigate to nearby other files."

**Comment by felixfbecker** [comment]
> Basically getting to the top level of the repo will be sufficient.

You can jump to the top level by clicking the repo name right above the file tree.

But I think an "upwards" button like in Windows explorer would make a lot of sense:

![Uploading image.png…]()

**Comment by jjinnii** [comment]
@macraig  [Slack thread discussion ](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1632748309104000)for reference. 

Here is a video of the [prototype](https://www.loom.com/share/98bdea4795164820ade6843db843df08)with a first pass solution, and here is the [link to the Figma design](https://www.figma.com/file/F0lMTJwgcpUAsnhaXUDxwc/Higher-level-in-file-tree-view?node-id=1114%3A5678), which shows an option with left-aligned button. 

Due to the technical constraints discussed in the above Slack thread, the proposed solution adds a "return to parent" button that takes the user to a separate parent repo-level view. Because we are not adding another layer to the file tree itself, once on this higher level parent view, the user has to click into a lower directory to then see the file tree view again.

**Comment by oleggromov** [comment]
This must be solved, at least in part, by this PR: https://github.com/sourcegraph/sourcegraph/pull/39138
To subscribe to other improvements of the tree view, please look at https://github.com/sourcegraph/sourcegraph/issues/38667
