### ISSUE TITLE
Test plan for TypeScript code intelligence

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1718]
While testing code intelligence, imagine you’re a site admin setting up language support for the first time because they are the people who will get their company from 1 to 20 users.

* Spin up a fresh Sourcegraph instance
* Deploy the language server in a Docker container by following: https://docs.sourcegraph.com
* Find a random TypeScript repository (e.g. from https://github.com/search?o=desc&q=language%3Atypescript&s=stars&type=Repositories) and make sure hovers/defs/refs work
* Basic functionality should also work in JavaScript repos, but note that j2d might not always be found, hovers may be `any` a lot, references may not all show up etc because it's not typed.
* Special features
   * Cross-repo defs/refs
      * The package tsconfig.json needs to use `declarationMaps: true`
      * If the package is in a subfolder of the repo, package.json needs to contain `repository.directory` field
      * Examples: https://github.com/Microsoft/vscode-languageserver-node, https://github.com/sourcegraph/codeintellify, https://github.com/felixfbecker/iterare
   * Private repositories & private dependencies
     * You need to configure an npm token for this (follow the docs)
     * Examples: https://github.com/sourcegraph/test-private-package, https://github.com/sourcegraph/test-private-dependency
* Test the same steps in the browser extension as well

Comment on this issue when you're done.

This issue should be closed after a sufficient number of people have tested.

**Comment by chrismwendt** [comment]
I'm beginning to test TypeScript code intelligence. Here's my status:

- [ ] Run a fresh 3.0 alpha9 instance
- [ ] Deploy the TypeScript language server in Docker locally
- [ ] Try some hovers/defs/refs
- [ ] Try cross-repo code intel
- [ ] Try private repositories/dependencies
- [ ] Test in the browser extension

**Comment by ryan-blunden** [comment]
For http://localhost:7080/github.com/sourcegraph/sourcegraph/-/blob/shared/src/commandPalette/CommandList.test.ts#L2:10, two errors were returned.

![screen shot 2019-01-10 at 5 21 11 pm](https://user-images.githubusercontent.com/133014/51007400-29f8dc00-14fc-11e9-90b5-c0c16a4ab89e.png)

**Comment by beyang** [comment]
### My testing progress
* [ ] Spin up a fresh Sourcegraph instance
* [ ] Deploy the language server in a Docker container by following: https://docs.sourcegraph.com
* [ ] Find a random TypeScript repository (e.g. from https://github.com/search?o=desc&q=language%3Atypescript&s=stars&type=Repositories) and make sure hovers/defs/refs work
* [ ] Basic functionality should also work in JavaScript repos, but note that j2d might not always be found, hovers may be `any` a lot, references may not all show up etc because it's not typed.
* [ ] Special features
   * [ ] Cross-repo defs/refs
      * [ ] The package tsconfig.json needs to use `declarationMaps: true`
      * [ ] If the package is in a subfolder of the repo, package.json needs to contain `repository.directory` field
      * [ ] Examples: https://github.com/Microsoft/vscode-languageserver-node, https://github.com/sourcegraph/codeintellify, https://github.com/felixfbecker/iterare
   * [ ] Private repositories & private dependencies
     * [ ] You need to configure an npm token for this (follow the docs)
     * [ ] Examples: https://github.com/sourcegraph/test-private-package, https://github.com/sourcegraph/test-private-dependency
* [ ] Test the same steps in the browser extension as well

### Issues found

**Comment by felixfbecker** [comment]
@chrismwendt 

> While navigating around http://localhost:7080/github.com/sourcegraph/codeintellify/-/blob/src/hoverifier.ts, I got a few errors:

Unless any of these errors resulted in unexpected behaviour they are all normal.

> Cross-repository references do not work at http://localhost:7080/github.com/sourcegraph/test-private-package@0cc4c3f2ba862a0af5a4d774dae32fc860ce93a4/-/blob/src/index.ts#L2:17&tab=references (I first did a cross-repository definition to get to that line)

Fixed this, please retest. The extension was using the server Sourcegraph endpoint.

@ryan-blunden 	

> For http://localhost:7080/github.com/sourcegraph/sourcegraph/-/blob/shared/src/commandPalette/CommandList.test.ts#L2:10, two errors were returned.

Same as above, unless any of these errors resulted in unexpected behaviour they are all normal.

> Code intelligence doesn't seem to work on GitHub.

It works for me (connected to my Docker instance):

![image](https://user-images.githubusercontent.com/10532611/51049764-23876480-15cf-11e9-8b90-6867092703d7.png)

What instance are you connected to? What do the background page logs say?

> Simplify for the 3.0 release

What would you suggest removing and why?

> Docker run command

All these suggestions make the command more complicated, which seems to contradict your suggestion before to simply to the bare minimum?

> Improving performance with an SSD
> This seems like an optimization that would apply to all language servers so perhaps it could be placed in the docs and linked to from the README.md.

It's rather TS-specific because TS is configured with a special env var to put special folders onto the mounted SSD

> Is there a reason why the lang server has a Docker and k8s example but the NPM proxy only has a k8s example?

No reason other than the Docker instructions were meant for quick local try-it-out while the Kubernetes instructions were the full-blown how-to-deploy-and-make-it-scale instructions. Before you deploy an npm proxy with Docker you probably want to upgrade to Kubernetes.

**Comment by chrismwendt** [comment]
> > Cross-repository references do not work at http://localhost:7080/github.com/sourcegraph/test-private-package@0cc4c3f2ba862a0af5a4d774dae32fc860ce93a4/-/blob/src/index.ts#L2:17&tab=references (I first did a cross-repository definition to get to that line)
> 
> Fixed this, please retest. The extension was using the server Sourcegraph endpoint.

@felixfbecker I verified this is fixed ✅

**Comment by ryan-blunden** [comment]
My explanations are below. I just want an admin/developer wanting to get the TypeScript lang server up and running as fast as possible without having to do much thinking and mainly copying and pasting.

My perspective is:

 - Works great for 1-20 users.
 - Presumes production quality code samples. 
 - Can be mindlessly copy and pasted.

My view is that because 3.0 is the vehicle that will take us from 1-20 users, it's vital that we optimize for that at this point in time.

My responses to your questions are below.

> What would you suggest removing and why?

I suggest removing:

 - Kubernetes manifests
 - Improving performance with an SSD
 - Improving performance with an npm registry proxy

The reason why is how does an admin/dev know which steps are on the critical path and which are not? Are we expecting them to read the entire page, then figure it out? It's great quality documentation and code for sure, but it's a lot to digest when all you want to do is get TypeScript code intelligence working for a brand new instance.

Could you strike a balance by linking to pages on the above list in a docs directory in the `lang-typescript` repo? It doesn't seem like these would need to be changed between new lang-server releases.

I'd also add some troubleshooting, logging and debugging tips for when customers report issues.

> All these suggestions (to the docker run command) make the command more complicated, which seems to contradict your suggestion before to simply to the bare minimum?

I would say exposing all production ports, explicitly defining the image tag, running the container in detached mode and adding a restart policy are the simplest instructions if the command is run in a production environment (meaning available not just to one person on their local machine). 

> No reason other than the Docker instructions were meant for quick local try-it-out while the Kubernetes instructions were the full-blown how-to-deploy-and-make-it-scale instructions

This perhaps explains to me your reasoning for why to keep the `docker run` command the way it is. 

I would like to challenge the assumption that the docker version is only for local try-it-out scenarios. Enabling an instance to get from 1-20 users I believe largely depends on the administrators ability to get Sourcegraph working quickly and easily and although I may be wrong, I see using docker only as the simplest, fastest and therefore, best way to do that. Kubernetes deployments can come later when scaling becomes an issue.

I'll put together a README.md that incorporates my suggestions to make this more concrete.

**Comment by ryan-blunden** [comment]
I was able to get cross repo jump to definitions to work ([sourcegraph => codeintellify](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/libs/code_intelligence/code_intelligence.tsx#L556:36)) but it took over a minute and the experience wasn't great because it seemed like it was broken every time I tried until it worked.

Even if it's not possible to speed up the time taken to be able to jump-to-def, the waiting experience needs to be improved.

Video is at https://www.dropbox.com/s/w92hx1hg89hdzmu/cross-repo-j2def-ts.gif?dl=0

**Comment by felixfbecker** [comment]
@sqs both @beyang and @ryan-blunden complained about no feedback during initialization time, and #1572 suggests that notifications are only unwanted when on GitHub && not actively using codeintel features. I propose to reenable progress notifications again by default.

**Comment by sqs** [comment]
Yes, that sounds great.

1. Make sure they don’t show up on GitHub until the user performs a hover (it is ok but not required if they show up on Sourcegraph before the user performs a hover)
1. Add a command palette action to toggle showing the progress notification and document it

The intent is that most users won’t see this progress notification unless it is useful to them. To satisfy this invariant better over time, monitor and solicit user feedback just as you did in #1572 (and I will do the same).

**Comment by felixfbecker** [comment]
Sufficiently tested.
