### ISSUE TITLE
Test plan for auth

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1723]
# 3.0 Auth test plan

## GitHub authentication

1. Run a new Sourcegraph Server instance
1. After initializing the Sourcegraph Server instance using built-in authentication, use the management console to configure the server to authenticate via GitHub.com by navigating to docs.sourcegraph.com and finding the documentation to do so. (If you can't find it, go [here](https://docs.sourcegraph.com/admin/auth/#github), but try first to find it yourself.)
   1. Keep the built-in auth provider enabled. Disable sign-up via GitHub (this is the default).
   1. Verify you can sign in using a GitHub account with the same email (must be verified on both Sourcegraph and GitHub) as an existing built-in account. Go to 
   1. Verify you cannot sign up using a GitHub account that doesn't have a verified email that matches an existing Sourcegraph account.
1. Enable sign-up via GitHub
   1. Verify that you can now sign in using a GitHub account that doesn't have an email that matches an existing Sourcegraph account.
1. Disable built-in authentication
   1. Verify that GitHub authentication still works.
1. Do the above steps for http://ghe.sgdev.org, instead of github.com.

## GitHub authorization

1. Add a GitHub external service to your Sourcegraph instance.
1. To the GitHub config, add the `authorization` field:

```
{
  "authorization": {},
  ...
}
```

1. Verify that a user does not have access to private repositories that it doesn't have access to on GitHub in the following cases:
   1. A private repository belonging to another user.
   1. A private repository in an organization.
1. Verify that a user *does* have access to a private repository that it can access on GitHub.
   1. The user's own private repository.
   1. A private repository in an organization.
   1. A private repository belonging to another user, but with collaborator access.
1. Verify that a user has access to a public repository from GitHub.
1. Add the `ttl` field to the GitHub connection `authorization` object. Set it to "1s".
   1. Revoke access to a repository from your user on GitHub and verify that the new permission is enforced on Sourcegraph within 1s.
   1. Grant access to the repository again and verify your user can access it after 1s.

## GitLab authentication

1. Use the management console to configure the server to authenticate via GitLab.com by navigation to docs.sourcegraph.com and finding the docs to do so. (If you can't find it, go here, but try first to find it yourself.)
   1. Verify you can sign in using a GitLab account with the same email as an existing account.
   1. Verify you can sign up for a new Sourcegraph account by logging with a GitLab account whose email isn't yet associated with an existing Sourcegraph account.

## GitLab authorization

1. Add a GitLab external service to your Sourcegraph instance, pointing to https://gitlab.sgdev.org.
1. To the GitLab config, add the `authorization` field as described in the docs. Try to find the doc
   page yourself first (if you can't, file an issue and go
   [here](https://docs.sourcegraph.com/admin/repo/permissions#gitlab)).
1. Verify that a user does not have access to private repositories that it doesn't have access to on GitLab in the following cases:
   1. A private repository belonging to another user.
   1. A private repository in an organization.
1. Verify that a user *does* have access to a private repository that it can access on GitLab.
   1. The user's own private repository.
   1. A private repository in an organization.
   1. A private repository belonging to another user, but with collaborator access.
1. Verify that a user has access to both public and
   [internal](https://docs.gitlab.com/ee/public_access/public_access.html#internal-projects)
   repositories from GitLab.
1. Add the `ttl` field to the GitLab connection `authorization` object. Set it to "1s".
   1. Revoke access to a repository from your user on GitLab and verify that the new permission is enforced on Sourcegraph within 1s.
   1. Grant access to the repository again and verify your user can access it after 1s.

**Comment by KattMingMing** [comment]
I'm seeing the following after creating a new GitHub OAuth and updating `auth.providers` to GitHub:

![screenshot 2019-01-10 13 47 42](https://user-images.githubusercontent.com/4897310/50999195-7af9d780-14de-11e9-8358-1358f8067abc.png)

I'm not seeing any errors indicating why it's not working. I tried making an application pointing to localhost and my own domain.

**Comment by felixfbecker** [comment]
I only got through the first item and only for github.com. Just FYI this test plan looks **very** time-intensive. https://github.com/sourcegraph/sourcegraph/issues/1785

**Comment by beyang** [comment]
Fix for #1785 is in master.

@felixfbecker If the test plan takes too long and there's other stuff you need to get to, could you tackle just Git**Hub** first? @KattMingMing could you tackle Git**Lab** first?

**Comment by KattMingMing** [comment]
**GitLab Testing checklist:**

**GitLab authentication**
- [ ] Use the management console to configure the server to authenticate via GitLab.com by navigation to docs.sourcegraph.com and finding the docs to do so. (If you can't find it, go here, but try first to find it yourself.)
    - [ ] Verify you can sign in using a GitLab account with the same email as an existing account.
    - [ ] Verify you can sign up for a new Sourcegraph account by logging with a GitLab account whose email isn't yet associated with an existing Sourcegraph account.

**GitLab authorization**
- [ ] Add a GitLab external service to your Sourcegraph instance, pointing to https://gitlab.sgdev.org.
- [ ] To the GitLab config, add the authorization field as described in the docs. Try to find the doc
page yourself first (if you can't, file an issue and go
here).
- [ ] Verify that a user does not have access to private repositories that it doesn't have access to on GitLab in the following cases:
    - [ ] A private repository belonging to another user.
    - [ ] A private repository in an organization.
- [ ] Verify that a user does have access to a private repository that it can access on GitLab.
    - [ ] The user's own private repository.
    - [ ] A private repository in an organization.
    - [ ] A private repository belonging to another user.
- [ ] Verify that a user has access to both public and internal repositories from GitLab.
- [ ] Add the ttl field to the GitLab connection authorization object. Set it to "1s".
    - [ ] Revoke access to a repository from your user on GitLab and verify that the new permission is enforced on Sourcegraph within 1s.
    - [ ] Grant access to the repository again and verify your user can access it after 1s.

**Comment by felixfbecker** [comment]
@beyang do you have an example of a private repo that I/we don't have access to?

**Comment by KattMingMing** [comment]
@felixfbecker you can test against one of my repos - https://gitlab.sgdev.org/kingy/mux

**Comment by felixfbecker** [comment]
I'm testing GitHub, do you have one for GitHub?

**Comment by KattMingMing** [comment]
**GitHub Testing Checklist**:

GitHub authentication

- [x] Run a new Sourcegraph Server instance
- [x]  After initializing the Sourcegraph Server instance using built-in authentication, use the management console to configure the server to authenticate via GitHub.com by navigating to docs.sourcegraph.com and finding the documentation to do so. (If you can't find it, go [here](https://docs.sourcegraph.com/admin/auth/#github), but try first to find it yourself.)
   - [x]  Keep the built-in auth provider enabled. Disable sign-up via GitHub (this is the default).
   - [x] Verify you can sign in using a GitHub account with the same email (must be verified on both Sourcegraph and GitHub) as an existing built-in account. Go to 
   - [x] Verify you cannot sign up using a GitHub account that doesn't have a verified email that matches an existing Sourcegraph account.
- [x] Enable sign-up via GitHub
   - [x] Verify that you can now sign in using a GitHub account that doesn't have an email that matches an existing Sourcegraph account.
- [x] Disable built-in authentication
   - [x] Verify that GitHub authentication still works.
- [ ]  Do the above steps for github.sgdev.org, instead of github.com.

## GitHub authorization

- [x]  Add a GitHub external service to your Sourcegraph instance.
- [x]  To the GitHub config, add the `authorization` field:


```
{
  "authorization": {},
  ...
}
```

- [x]  Verify that a user does not have access to private repositories that it doesn't have access to on GitHub in the following cases:
   - [x]  A private repository belonging to another user.
   - [x]  A private repository in an organization.
- [x]  Verify that a user *does* have access to a private repository that it can access on GitHub.
   - [x]  The user's own private repository.
   - [x]  A private repository in an organization.
   - [x]  A private repository belonging to another user.
- [x]  Verify that a user has access to a public repository from GitHub.
- [x]  Add the `ttl` field to the GitHub connection `authorization` object. Set it to "1s".
   - [x]  Revoke access to a repository from your user on GitHub and verify that the new permission is enforced on Sourcegraph within 1s.
   - [x]  Grant access to the repository again and verify your user can access it after 1s.

**Comment by felixfbecker** [comment]
Tested GitHub authentication and authorization together with @KattMingMing for github.com (not GitHub Enterprise).

Only feedback I have is that the empty object `authorization: {}` to enable permission checks and checks being off by default is confusing. I wouldn't expect an empty object in settings to enable anything and forgot to add it initially. Therefor, since I configured the site with my GitHub token, Kingy (and everyone else) had access to all my and my org's private repos. I would prefer it to default to on and be possible to disable with
```json
"authorization": false
```

**Comment by chrismwendt** [comment]
I'm running through the auth test plan. Issues found so far:

- https://github.com/sourcegraph/sourcegraph/issues/1860
- https://github.com/sourcegraph/sourcegraph/issues/1859

**Comment by nicksnyder** [comment]
Moved to 3.0 milestone. This feature will be explicitly marked as beta in 3.0-beta and we will continue testing it as part of 3.0 release.

**Comment by nicksnyder** [comment]
@beyang Is any more testing needed here for 3.0?

**Comment by beyang** [comment]
Nope
