### ISSUE TITLE
Add "create code monitor" button to search results

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17267]
[Figma design](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3700%3A0)

- Add a "create code monitor" button to search results
- The button should only be shown when the context allows for the creation of  a code monitor (query is `type:diff` or `type:commit`, no search expressions usage)
- Button links to the code monitoring creation page, with the query field pre-filled

**Comment by quinnkeast** [comment]
Design proposal, based on @rrhyne's previous work on this area during his work on streaming searches:

[View on Figma](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3700%3A0)

Remarks:

- Also updates the labels for "Save this search query" to "Save search," removes the text label from "Expand all," and re-orders items slightly as per Rob's design.
- When code monitor can't be created from results, button remains but is disabled. Hovering over button shows tooltip with information. (Counter to @lguychard's initial thought—happy to discuss!)

**Comment by lguychard** [comment]
> When code monitor can't be created from results, button remains but is disabled

I'm concerned with taking up real estate in search results with something that will not be actionable most of the time, especially since when this is disabled, we show no direct hint to the user as to why that button is here / what it does. Since this is feature-flagged for now, we can still iterate on it though (eg. make it more educational, link to appropriate code monitoring docs, explain/link to docs explaining why it only works with diff/commit search).

Even when the button is clickable, making sure it doesn't take you fully out of context in just one click would be valuable.

**Comment by lguychard** [comment]
Designs LGTM otherwise!

**Comment by quinnkeast** [comment]
>     

I'm concerned with taking up real estate in search results with something that will not be actionable most of the time, especially since when this is disabled, we show no direct hint to the user as to why that button is here / what it does. Since this is feature-flagged for now, we can still iterate on it though (eg. make it more educational, link to appropriate code monitoring docs, explain/link to docs explaining why it only works with diff/commit search).

Your concerns make sense to me! Why don't we go ahead with your direction—only show it when it's available—for now, and go from there?
