### ISSUE TITLE
Reuse sign-in OAuth workflow for code host connections

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#17356]
### Description

To reuse existing "sign-in with" OAuth workflow for code host connections, we need to have a secure way to tell the sign-in-workflow to bind given code host (user external account) to user and not with an email but with a special ID X, where X could be an opaque user ID. 

Otherwise we need to require users to add their email address (of what they have in the code host) before creating code host OAuth connection. If user won't have an email address, we may end up creating a new Sourcegraph account. 🙅 

### Links
* [Slack convo in #cloud](https://sourcegraph.slack.com/archives/CHPC7UX16/p1610934342030900)
* [Project board](https://github.com/orgs/sourcegraph/projects/126)
* [Figma designs for UI](https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-%26-Private-Repos-for-Users-on-Cloud?node-id=656%3A24221)

**Comment by ryanslade** [comment]
It appears that we already support this workflow. If we attempt to "sign in with codehost" after a user is already authenticated then we'll link the external account with the currently logged in user.

I've tested this locally in the following way:

1. Sign in to Sourcegraph with a new user with an email that doesn’t match any in GitHub (using the `+` trick for gmail)
2. Temporarily disable the redirect [here](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/auth/SignInPage.tsx#L33-L36) so that can “continue with GitHub”. 
3. Navigate to `/sign-in`and click on `continue with GitHub`
3. It successfully links the GitHub account with the existing logged in user and creats a new entry in the `user_external_accounts` table.

**Comment by ryanslade** [comment]
@artemruts Did you confirm that the above works, can we close this?

**Comment by artemruts** [comment]
@ryanslade I'll close this after code goes through QA, I believe it works :)
Will re-assign to myself.

**Comment by tsenart** [comment]
@artemruts: Can we get a demo video to share in #progress?
