### ISSUE TITLE
codeintel: Write RFC 294: Replacing ctags for symbol search

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#17378]
Fill out [RFC 293](https://docs.google.com/document/d/17hhirhcuQYCxT_1-0A-eWUPyqX9VoXOVkcdi9VBGZjA/edit#heading=h.trqab8y0kufp) with the current state of symbols search and its problems. Write a short draft of a strategy vision and open it up to code-intel team internal discussion before the next round of revisions.

**Comment by alidn** [comment]
This RFC is very interesting, and I have worked on something similar, so I might have some useful insights.

I have used 2 different approaches to address the problem in the RFC:
	1. Using tree-sitter, like mentioned in the RFC (https://github.com/alidn/lsif-os)
	2. Using a language server (https://github.com/alidn/universal-lsif)

The first solution is very fast, but will never be 100% precise, while the second one is precise but slow.

IMO, the best approach is to speed-up the second solution by reducing the number of requests sent to the language server:

For a lot of symbols, a tree-sitter indexer can’t find the definition, but if it magically does find the definition (like by asking the language server), it can use that information for every other reference of that symbol (partly because it knows the scoping rules). So, very few requests need be sent to the language server.

It might even be possible to give the option to choose between performance and precision. The only drawback I can think of is that it needs to gather dependencies and share steps with the build process (which was mentioned in the RFC).

What do you think about this approach as opposed to just using tree-sitter?

BTW, even though I won’t be able to spend too much time on this, I would be very interested in contributing to this, especially to a my implementations or their forks.

**Comment by efritz** [comment]
@alidn Thanks for the feedback! Your lsif-os project is what actually kicked off me thinking about this, so thanks for the inspiration! 👏 

At least for Sourcegraph's needs, we are specifically targeting a way to get information that's strictly better than the output of universal-ctags (the current floor we need to compare to) without adding any additional steps that need to be fulfilled by a human.

We are exploring ways to auto-infer the proper way to invoke an LSIF indexer given only the source code in parallel. However, this is a much heavier task: wee need to be able to install dependencies, os packages, etc, in order for the indexer to have the data it needs to precisely index the code (the source text is rarely enough).

Tree-sitter only requires the source text, like ctags, but gives us much better output. The problem with the second approach you suggested is that language servers will have the same requirement as the LSIF indexers do.

I do like the idea of bootstrapping an LSIF indexer with an existing langauge server, though. We've tried it a few times and it was super super slow (but didn't optimize too far) and decided to abandon the approach for a few more fruitful options. Not to say we can't revisit that approach though now that we have some more engineering capacity :shrug:.

And community support is _always welcomed_. I'll be sure to make sure we keep as much as the conversation in easily accessible public spaces as possible.

**Comment by alidn** [comment]
> I do like the idea of bootstrapping an LSIF indexer with an existing language server, though. We've tried it a few times and it was super super slow ...

That's right, this approach _is_ extremely slow, but in combination with tree-sitter, it won't be (I haven't implemented this, just predicting).

>  ... now that we have some more engineering capacity

Are you still looking to expand the code-intel team? Because I would love to give it a try :)

> ... we need to be able to install dependencies, os packages, etc, in order for the indexer to have the data it needs to precisely index the code ... the problem with the second approach you suggested is that language servers will have the same requirement as the LSIF indexers do.

Sorry for my naive question: If in theory, we have a fast indexer that uses an existing language server, why can't sourcegraph use it? Do language servers need to have the dependancies installed to give precise information?

**Comment by efritz** [comment]
> I haven't implemented this, just predicting

I'd be interested to see how you could combine these results. Please keep us posted if you end up playing around with this!

> Do language servers need to have the dependancies installed to give precise information?

Generally, yes. We used to have a Go and a TypeScript language server deployed on our Sourcegraph.com deployment. These were deprecated in favor of pre-indexing via LSIF, since the language servers would have a very slow cold start time due to running things like `go get`, `npm i`, or `yarn`.

**Comment by efritz** [comment]
Now in review status.

**Comment by alidn** [comment]
> I'd be interested to see how you could combine these results. Please keep us posted if you end up playing around with this!

@efritz I tried this, it's not exactly what I was talking about, but that would take time to implement: 
It got a big performance improvement as expected, despite being single-threaded and not as efficient as it can be. It indexes a Rust repo with 75,000 loc in ~74 seconds, which is not too bad.

Anyways, I'm out of ideas now, but I think you _can_ have a fast indexer if you optimize this 🤷
