### ISSUE TITLE
Git blame should be toggle-able in the UI when on a code host

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#17430]
We have [repeated internal feedback](https://sourcegraph.slack.com/archives/CMT39K56Z/p1610982123030900?thread_ts=1608025360.210300&cid=CMT39K56Z) that it's frustrating to have git blame settings "persist" into the code host (if you have it on in your sourcegraph, it's on in github) with no way to modify them. 

We don't think there is a major historical reason why this doesn't exist already. Our best guesses from older team members are that it might be confusing with the native blame button on the code host, or it might have been in an effort to keep the extensions area cleaner since git blame is an extension that's on by default. Our solution should take both these points (make it clean and make sure it's not confusing with any native blame buttons) into consideration. ([Slack thread](https://sourcegraph.slack.com/archives/CMT39K56Z/p1608025360210300).)

**Comment by AlicjaSuska** [comment]
**Before solving #17429**
I think it makes sense to add a Git Blame icon-only button to code hosts since we're planning to implement the icon-only approach in the action items bar issue anyway. Also, without the 'Blame' label, this button will not be confused with GitHub's 'Blame' button.

This button would work the same as the Blame button on Sourcegraph:
- off - no inline annotations
- on, first click - annotations per line
- on, second click - annotations for all the lines
Is it possible to implement it this way of GitHub or it can support only 2 states - on and off? @tjkandala 

[Please, see the Figma file for details](https://www.figma.com/file/G5QfvveEAEcnubx2lGgGel/Git-Blame-improvements-17429-17430-17434-16409-WIP?node-id=275%3A1628)

**After solving #17429** 

We can come back to this issue if there is a new solution for 3 states of the toggle button. It may take us some time to figure out the solution for #17429 so I suggest implementing the current approach on the code host first to address the urgent need.

@Joelkw @tjkandala @felixfbecker

**Comment by Joelkw** [comment]
@AlicjaSuska that sounds good to me, thanks!

**Comment by ryankscott** [comment]
This is no longer required after sunsetting extensions.
