### ISSUE TITLE
Revamp Git Blame display so it leaves the code cleaner

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#17434]
We have both internal (see attached concept from @rrhyne) and [external feedback](https://sourcegraph.productboard.com/feature-board/2330167-web-extensibility/features/6723352/insights) that our git blame display makes reading the code more difficult. We should consider changing how we display it. 

Considerations: 

- This might involve creating another contribution point(s) to the extensions API, which is not a minor lift. 

![image (5)](https://user-images.githubusercontent.com/11967660/105087485-6480a200-5a4f-11eb-8fc6-cba3873e8a86.png)

**Comment by AlicjaSuska** [comment]
This also aligns with the [feedback](https://docs.google.com/document/d/1a1ZBKwUBilidXbm3r_ee6jOjnol3q6XyL9P3LvIM0rg/edit#bookmark=id.dl2qwft1qwqg) I've gathered from uses when testing the action items bar.

**Comment by Joelkw** [comment]
Additional concept/feedback:

> A prospect on a demo today asked if we had anything similar to this particular blame history view in GH: https://github.blog/2017-01-18-navigate-file-history-faster-with-improved-blame-view/. He liked the inline blame, he liked the file history, but he wanted the history for the line, essentially. (At least that was my understanding of the thing he sent and the way he described it.) Am I missing a way to nab that, or is that specific sort of view just not an option?

**Comment by jjinnii** [comment]
[Additional internal feedback in Slack](https://sourcegraph.slack.com/archives/C07KZF47K/p1641504092019900) 

Feedback is specific to code legibility - the padding and placement of git blame is very close to the code, making it hard to differentiate and detracting from code legibility (and velocity).

**Comment by jjinnii** [comment]
@ryankscott @taras-yemets [Quick concepts](https://www.figma.com/file/MzN5BUNI0OJ4gQyrKqT7Nw/Improve-git-blame-readability?node-id=275%3A1628) for git blame scannability improvements. They're very similar to Rob's proposal, but I pulled from more industry standards to include what the change was and how the date was formatted.

**Comment by taras-yemets** [comment]
Removing the blame decoration background, increasing the text color opacity, and increasing the left margin could improve the code readability too.

|     | Light | Dark |
| -- | -- | -- |
| GitHub | ![image](https://user-images.githubusercontent.com/25318659/166487275-a41f969a-4e0a-4415-94a1-8cbd812da2df.png) |![image](https://user-images.githubusercontent.com/25318659/166488174-041e544e-eff6-48c7-967d-44c209b494e5.png)|
| Sourcegraph |![image](https://user-images.githubusercontent.com/25318659/166487714-ca2971d4-1ff8-4942-a4e6-403f0481a6f3.png) |![image](https://user-images.githubusercontent.com/25318659/166487466-72831e49-64c8-4444-8686-df356dc71fdc.png) |

cc: @ryankscott @jjinnii

**Comment by ryankscott** [comment]
@taras-yemets that looks fantastic! So much better 🎉

**Comment by rrhyne** [comment]
Sorry @ryankscott @taras-yemets, this will not meet accessibility guidelines:

![image](https://user-images.githubusercontent.com/539268/166525847-d0395efa-3ecf-4403-b272-d0ecd245b215.png)

and it doesn't address that we are combining the code with history, which undermines the readability of the code. 

Have you determined an investment into correcting this with a new column is not feasible?

**Comment by taras-yemets** [comment]
Thank you for your feedback, @rrhyne!

> it doesn't address that we are combining the code with history, which undermines the readability of the code

Agree. Having a separate column for git blame helps with the file-level blame. How do we approach showing blame for selected lines in this case? Do we inline blame decorations as we do now? If so, we can enhance code and blame decorations readability by modifying the colors and margins of the latter. 

> this will not meet accessibility guidelines

It is not actual implementation. It is a draft created by manually adjusting colors in the browser's console. If we decide to proceed with color changes, we'll ensure they meet the accessibility guidelines.

> Have you determined an investment into correcting this with a new column is not feasible?

No, we haven't. We're evaluating the possible options now.

cc: @ryankscott

**Comment by ryankscott** [comment]
Sounds like we'll have to bump up the contrast before building anything, but the padding definitely helps. 

> Additionally, it doesn't address that we are combining the code with history, which undermines the readability of the code. 

For a single-line blame this seems like a reasonable approach and a great improvement. For full file-level blame, I agree we need to look into a better approach. 

> Have you determined an investment into correcting this with a new column is not feasible?

Not yet, it is something we're investigating. There's also the discoverability problem that we also want to tackle. as any improvements in a column view is pointless if users can't find it. This obviously requires more design thought so we're doing a minor improvement to begin with.

**Comment by taras-yemets** [comment]
Color contrast concern is confirmed.
I updated the colors to meet [our color contrast rules](https://docs.sourcegraph.com/dev/background-information/web/accessibility/detailed-checklist#color-contrast), and it made code and blame hard to read again (even in selected lines blame mode). Now it's hard to distinguish code comments from blame decorations. 

|   |  |  
| - | - | 
| GitHub | ![image](https://user-images.githubusercontent.com/25318659/166650885-6290adad-b914-429e-8464-916a648cbde6.png) |
| Sourcegraph |![image](https://user-images.githubusercontent.com/25318659/166651107-f7c28ddf-8eaf-4c39-87f0-2fa8f1e892be.png) ![image](https://user-images.githubusercontent.com/25318659/166651308-bc43b16b-f288-4990-ba6b-49630dab9887.png) |

Another possible issue with inline decorations is that git-extras could not be the only active extension adding inline decorations, so we may have even more text there.

The possible solution could be removing _'show git blame for selected lines'_ mode and adding a git-extras icon to the hovered line. Hovering that icon will show git-extras popup (similar to the existing code intel popup).

**Icon placement:** ![image](https://user-images.githubusercontent.com/25318659/166659751-1c1a1d21-7b78-43be-acd4-a2ad545d0468.png)

**Popup example:** ![image](https://user-images.githubusercontent.com/25318659/166660219-16f957fa-a2bd-4b81-a5c9-ea13891d2613.png)

@ryankscott, @jjinnii, @rrhyne, what do you think?

**Comment by ryankscott** [comment]
I'd worry about the popup hurting discoverability. Perhaps we have two options that we can weigh up:
1. Adding just padding and keeping the same colours in the original git blame
2. Adding a new column, based on @jjinnii's designs

If we can get a ballpark estimate (e.g. days / weeks / months) then we can decide which way we want to go.

**Comment by jjinnii** [comment]
Catching up on the git blame work now that I'm back! It seems we all agree a new column is the best solultion, but the question is whether it's worth the significant effort. Given that: 

- We have documented customer and internal feedback going back 1+ years
- The new designs get us closer to industry standards

I feel like it's a high effort but low risk investment. Maybe this last question could be the deciding factor:

@taras-yemets if we implement a new git blame column, does it reduce effort for future work to improve/add new columns for other extensions such as Datadog/Codecov like in @rrhyne's [design concepts](https://www.figma.com/file/MzN5BUNI0OJ4gQyrKqT7Nw/Improve-git-blame-readability?node-id=1716%3A6262)?

If the answer is yes, I feel this further lowers risk for spending time on this feature as it will be an investment for us to potentially improve other extensions.

**Comment by taras-yemets** [comment]
@jjinnii, what do you think about the diff view? Are we going to display the blame in separate columns too?

**Comment by jjinnii** [comment]
@taras-yemets Would it expand the scope (and engineering time) if we did? 

More on the question of whether we _should_, correct me if I'm wrong but GitHub doesn't show their blame column for their diff view right? Do you (as a user) find blame valuable when looking at a diff view? (we can also do an internal poll on this too)

**Comment by taras-yemets** [comment]
@jjinnii, 

> Would it expand the scope (and engineering time) if we did?

Yes, it expands, but not significantly. We can leave the blame display inline as it is now, and change/remove it later if we want to. 

> GitHub doesn't show their blame column for their diff view right?

As far as I know it doesn't.

> Do you (as a user) find blame valuable when looking at a diff view?

I don't use it often, but I assume someone might find it useful. For example, when comparing diffs user might want to be able to see the blame on the base branch to understand when it was touched previously without navigating to the file view. Right now I don't have a real-world use case for blame on the head branch when in diff view.

> we can also do an internal poll on this too

It could be very helpful 👍🏻

**Comment by jjinnii** [comment]
@taras-yemets 

I've cleaned up the[ designs ](https://www.figma.com/file/MzN5BUNI0OJ4gQyrKqT7Nw/Improve-git-blame-readability?node-id=1745%3A7108)to reflect our lowest-effort improvement to git blame. Here's a[ Loom](https://www.loom.com/share/03151e2585c3461ab9b42aa07261935b) walking through some prototypes that better describes the behavior! 

To answer some of your questions:

- I've updated the timestamp to be relative. Having given it a second thought, there's no reason to change to an absolute format atm (I changed it initially to better match industry standards). Please ignore that it's not updated in the prototype! 
- I do think single line blame is important as I mention in the Loom. If we think of a user flow, if a user intentionally turned on blame while looking at a line of code, it's important that we maintain that position when they user our extension. Take a look at the Loom for the single blame flow, particularly the tooltip location, and lmk if that still requires us to tweak the Wildcard tooltip as you mentioned in Slack. 

One final note on design - In Figma, I have the container for git blame and container for code blob separately highlighted. 

<img width="514" alt="Screen Shot 2022-05-26 at 7 33 01 PM" src="https://user-images.githubusercontent.com/87138876/170471319-07f7abad-a559-4ebc-9e76-1376408a3215.png">


I think it looks neat this way, but also it's really difficult to have the whole line highlighted the way that component is built in Figma 😅 . You can first build it with the whole line highlighted (since I think that's easier), and I can review to see if we need to put in the extra effort to separate the containers.

**Comment by taras-yemets** [comment]
@jjinnii 

Here's a [Loom](https://www.loom.com/share/1542162bff3a4da9b637162919575896) walking through the current state of the git blame redesign.

The current implementation doesn't have the spacing between columns when we hover over or focus the blame decoration, so the whole line is highlighted. How do you like it? 

Another difference from the design is decoration text alignment. 
![image](https://user-images.githubusercontent.com/25318659/170677051-64012024-1c3d-49f0-8572-03818d48f5db.png)
The current extension API implementation allows extensions to pass only text content as decorations. To achieve the layout on the screenshot we need to somehow create 2 HTML elements with different alignments. At first glance, it could be solved by changing the extensions API allowing extensions to pass _either_ HTML instead of text (but I have strong doubts about the security of this approach) _or_ configs on how the text should be divided and rendered. Both options require decent implementation effort.   
Given that, I wonder how critical is to have 2 types of alignment?

**Comment by taras-yemets** [comment]
@jjinnii, what do you think about the line highlight on blame decoration hover/focus when the line is already decorated by another extension. Whose background should take precedence in this case?
![image](https://user-images.githubusercontent.com/25318659/170682157-d0a5e471-8da9-4789-bcbf-1f8f57297697.png)

**Comment by jjinnii** [comment]
> Given that, I wonder how critical is to have 2 types of alignment?

Thanks, @taras-yemets ! I wouldn't say it's critical, especially if it poses security/implementation concerns, not just added effort. Would you be able to send a screenshot of the approach you've taken in the most recent screenshot, but just shorten the datestamp to "1d ago Sara Lee [blah...]" -- e.g. all left-aligned instead of having two columns. 

>  what do you think about the line highlight on blame decoration hover/focus when the line is already decorated by another extension. 

Re: Codecov extension. Can we implement exactly what you have in that screenshot? On For rows that don't have code coverage bg color, the whole row would be grey. For rows that do have a code coverage bg color, we'd maintain code coverage color for code blob, but show grey bg for the git blame. If possible, could you capture a video of this behavior? It's not ideal, but we will be working on code coverage after git blame improvements. Not to mention, even currently, we don't change the code row highlighting to be grey if the code cov extension is turned on.

**Comment by taras-yemets** [comment]
@jjinnii 

> Can we implement exactly what you have in that screenshot?

I made a screenshot from my local branch, so it's already implemented ([Loom](https://www.loom.com/share/d9d99d74775d4e359e3a54890eea1f03)).

**Comment by jjinnii** [comment]
Thanks @taras-yemets . Would you be able to update the datestamp to reflect the shorted "2d ago, 1y ago, 3 m ago" etc.? We may have to introduce back the "•" in between the datestamp and blame to improve readability.

**Comment by taras-yemets** [comment]
@jjinnii 

> Would you be able to update the datestamp to reflect the shorted "2d ago, 1y ago, 3 m ago" etc.?

Right now I'm looking for a way to customize the time unit labels in the library we use for date formatting. Will share a screenshot once it's ready.

**Comment by jjinnii** [comment]
Okay thanks @taras-yemets! I didn't realize changing the date formatting required us to customize the time units. Please do let me know if this ends up being significant effort..

**Comment by jjinnii** [comment]
Thanks @taras-yemets! Re-looking through our[ copy guidelines](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/#time), I think we should actually go back to spelling out the full date, sorry about that! I wanted to shorten it to show as much of the blame as possible, but I should have double checked with our guidelines. I also think the differing month/minute lacks in consistency too. Could you also ensure there's a space after the numerical value and the "year,day, month, etc."? 

Just a question, in this Loom at [0:22-25](https://www.loom.com/share/25a83d9819cc441788c39a68bb4e7c2c), are you using cntrl + arrow keys to navigate up and down the blame?

**Comment by taras-yemets** [comment]
Thanks for your feedback, @jjinnii!

I'll revert the date formatting changes to the state on the screenshot in https://github.com/sourcegraph/sourcegraph/issues/17434#issuecomment-1139488559.

> in this Loom at [0:22-25](https://www.loom.com/share/25a83d9819cc441788c39a68bb4e7c2c), are you using cntrl + arrow keys to navigate up and down the blame?

I use Tab to move focus forward and Shift+Tab to move it back. Do we need support for CTRL + arrow keys too? If yes, how should they be different from Tab / Shift+Tab (should they move focus only on the blame decorations)?

**Comment by jjinnii** [comment]
@taras-yemets No, that's great! I wasn't sure from the Loom what keyboard nav we had enabled. Thanks.

**Comment by taras-yemets** [comment]
Feedback from @Joelkw on the first iteration of the git-blame redesign (PR https://github.com/sourcegraph/sourcegraph/pull/36007, [Slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1655113956717159)).

>My quick feedback as a hobbyist dev / full time PM, ordered by strength (strongest feedback item first):
> 1. **It would be really nice if instead of truncating the blame message, for cases when it’s the same blame for multiple lines anyway, we just show the full message wrapped** (this might get complicated with other possible line-decorating extensions that could interact, but the condition is just “is next line in use? If not, wrap message 1 more line”). We could then truncate the blame message only if the next line had a new column decoration. Would make it much more readable, given how much space there is and vs the old version (which showed more of the message).
a. Screenshots to compare how much of the message I can read now vs before. The before this change state is much more useful to actually know the blame message without needing to hover.
![image](https://user-images.githubusercontent.com/25318659/174791190-f0cb44f2-563c-499f-9eb7-59f31a2be929.png)
![image](https://user-images.githubusercontent.com/25318659/174791205-1a1042e3-e5d7-4a60-a2b7-9ea3bf4ac661.png)
> 2. **Would be curious to know why we decided to nest this on the left rather than the right, since it moves the whole code pane over** – it’s slightly jarring that the thought of “I just want to see who wrote this one line” involves shifting the entire code pane to the left (vs nothing would need to move if it came over from the right). My guess is so line numbers were close to the blame and easy to follow, but just my first take.

**Comment by fkling** [comment]
We have a much different blame view now. I think this can be closed.
