### ISSUE TITLE
UX for adding public repositories needs optimizing

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#1748]
In the past, whenever I opened a public repo with Sourcegraph that wasn't yet in my list of repositories, I would get a message giving the chance to add it by clicking an "Add Repo" button.

Now, when I try to open a repo that isn't on my list, I'm asked to add the repo to my list in my external services.

I find this cumbersome and not a great user experience when adding public repos.

![image](https://user-images.githubusercontent.com/9110008/50914814-02593380-146a-11e9-99a2-f1ef9916c05e.png)

I would prefer to click on a button that would then add and enable that repo.

**Comment by nicksnyder** [comment]
> In the past, whenever I opened a public repo with Sourcegraph that wasn't yet in my list of repositories, I would get a message giving the chance to add it by clicking an "Add Repo" button.

That is only because you were a site admin. Most users are not admins of their own instance and can not go through that workflow. Instead they would have seen this in 2.x:
![image](https://user-images.githubusercontent.com/754768/50917630-dc447c80-13f2-11e9-9a39-20705a96a1bb.png)

> I find this cumbersome and not a great user experience when adding public repos.

You are correct that this particular workflow is more cumbersome, but overall external services give us a better data model to provide support for things like renames to I think it is a good tradeoff.

I filed a new issue which discusses the rational and potential future improvements:
https://github.com/sourcegraph/sourcegraph/issues/1749

Thanks for the feedback!
