### ISSUE TITLE
Can't xrepo j2d on sourcegraph.com

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1753]
https://sourcegraph.com/github.com/sourcegraph/docsite@11f5f871132b04b82ab0558d104cb6466e966eab/-/blob/markdown/markdown.go#L42:21

**Comment by felixfbecker** [comment]
I get this:

![image](https://user-images.githubusercontent.com/10532611/51064712-5cd8c800-1601-11e9-999f-e30cd7f98508.png)

**Comment by felixfbecker** [comment]
@nicksnyder Yeah I corrected the link to point to the commit when the issue was filed instead of master

**Comment by chrismwendt** [comment]
I think this is failing because go-langserver doesn't support Go modules. Closing since we don't have plans to add Go modules support to go-langserver right now.

Specifics: the docsite repository (the running example in this issue) uses Go modules and specifies blackfriday v2, but go-langserver is downloading HEAD, which is missing some functions that exist in v2.
