### ISSUE TITLE
Streaming search: "0 results in 0 seconds" is odd

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17558]
This loading state can be displayed for several seconds:

![image](https://user-images.githubusercontent.com/1741180/105497490-30abb380-5cbf-11eb-881a-7e82a2442425.png)

I personally find it odd. Until we get some results or the search completes without results, should we instead display something like "searching for results" (no result count or duration)?

cc @limitedmage @rrhyne

**Comment by lguychard** [comment]
@rrhyne to play with some loading copy

**Comment by rrhyne** [comment]
A few options:

How I originally intended this, is that time passed (in 0.00s) incremented until a result comes back is, even while there are 0 results. Interval would be similar to how the time since search works on the search history links.  

It's hard to see without prototyping but registering the first second, then each additional 3 or 5 seconds would seem like an appropriate interval time. 

A second approach we can take here is to change the text to 'retrieving results' and not display the time elapsed. I don't think that's a good option at all, as direct feedback is open and honest and would result in a greater 'trust' factor.

**Comment by limitedmage** [comment]
I know @keegancsmith  and @stefanhengl  are working on improving progress reporting to make it faster and more accurate. I addition to this, I think changing the button to say something like "retrieving results" before anything is loaded yet is a good idea. @rrhyne  If you agree, let me know what the final content string should be and I can make this change.

**Comment by lguychard** [comment]
I think this is de facto solved by https://github.com/sourcegraph/sourcegraph/pull/17766

**Comment by keegancsmith** [comment]
> I think this is de facto solved by #17766

Should we up the frequency to every 1s?

**Comment by rrhyne** [comment]
From reading the code, it looks like it's 5 times a second and I think that could be annoying. I don't think we would need to update more than 1 time a second, but I'd need to see it in action to know how disturbing it could be.

**Comment by keegancsmith** [comment]
@rrhyne it is currently once every 5s. It is deployed to sourcegraph.com, so you can try it out to see how it feels.

**Comment by rrhyne** [comment]
I'm happy with 5 seconds, thanks! Seems to be an extra 0 at the end though?

![image](https://user-images.githubusercontent.com/539268/106237115-f48ebc00-61b2-11eb-8e39-4d8cbccf626a.png)

**Comment by keegancsmith** [comment]
@rrhyne good catch. Fixed the extra 0 here https://github.com/sourcegraph/sourcegraph/pull/17830
