### ISSUE TITLE
site-admin: External services creation or update shows no confirmation

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#1756]
#### Steps to reproduce:

1. Go to http://localhost:3080/site-admin/external-services/add
2. Create or update a valid external service.
3. Submit.

#### Expected behavior:

Some confirmation notification is shown.

#### Actual behavior:

No confirmation notification is shown.

**Comment by nicksnyder** [comment]
We don't have a standard way to do this.

Organizations show "updated!" text
![screen recording 2019-01-09 at 02 08 pm](https://user-images.githubusercontent.com/754768/50931676-2db33280-1418-11e9-96f6-d956513f3f60.gif)

Extensions do nothing:
![screen recording 2019-01-09 at 02 07 pm](https://user-images.githubusercontent.com/754768/50931678-2f7cf600-1418-11e9-8aa8-3d2033e00165.gif)

User profiles flash a green bar:
![screen recording 2019-01-09 at 02 02 pm](https://user-images.githubusercontent.com/754768/50931681-30ae2300-1418-11e9-805b-96f19b61ffc2.gif)

@francisschmaltz how should we present confirmation messages?

This issue is not urgent.

**Comment by nicksnyder** [comment]
@francisschmaltz this is already fixed https://github.com/sourcegraph/sourcegraph/commit/d72363a1b1f1bb4df73ca2b83b8204309b259a8a

**Comment by nicksnyder** [comment]
(All the examples here are about updating not creating)

**Comment by nicksnyder** [comment]
@attfarhan can you work with Francis to come up with a solution to this problem and implement it consistently across our forms (if possible, make it easy to do the right thing for future forms)

**Comment by francisschmaltz** [comment]
@attfarhan we should flash the green bar.
