### ISSUE TITLE
Streaming: send empty events to keep the stream alive

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17571]
Rel: #17561

**Comment by limitedmage** [comment]
@keegancsmith / @stefanhengl  do you have bandwidth to look into this? The server should periodically send empty (comment, `:\n\n`) events to the client to keep the connection alive, every 15 seconds or so.

**Comment by keegancsmith** [comment]
This is doable, rather than an empty event we will send the current state of progress (even if it hasn't changed).

The root cause of this is more than likely frontend OOMing rather than the network timing out. We are actively working on removing any need to do aggregation in the backend while streaming. Once we remove aggregation, then memory use of a streaming search should avoid OOMing.

We are backed by cloudflare, which does impose a 60s network timeout. When I last researched this it treated SSE streams as special, but should confirm that. Either way this is unlikely to affect customer deployments. If it does, we likely need a more general solution. For example we can't just rely on websockets, because those often also are unreliable at customers (from previous experience when we used websockets).

**Comment by limitedmage** [comment]
Thanks @keegancsmith , do you think you could tackle this issue as part of the progress/OOM work for streaming search?

**Comment by keegancsmith** [comment]
> do you think you could tackle this issue as part of the 
> progress/OOM work for streaming search?

Yup
