### ISSUE TITLE
Flesh out developer docs to improve onboarding

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#17580]
from [Stephen's list](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1611349773084200):

- The difference between internal/campaigns and enterprise/internal/campaigns packages
- Coming across the graphqlbackend which is all stubs with no explanation of where they are implemented: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/campaigns.go
- Trying to understand ultimately which Sourcegraph services bundle up campaigns code
- Why we chose to use inheritance for a internal/db/basestore type
- The relationship between a store, basestore, and sharable store
- Why non-store code occasionally reaches into the DB layer directly (intentional? tech debt? etc)
- High-level explanations of code breakdown, e.g. `store.Store` isn't idiomatic Go and the level of testing utility packages we have seems strange at first glance

**Comment by eseliger** [comment]
@slimsag To give you some quick feedback on the items and unblock you, I'll do a short write-up here, until we get to writing docs.

> - The difference between internal/campaigns and enterprise/internal/campaigns packages

The difference is as follows: We don't want enterprise-only code to live in non-enterprise packages, because it would not be covered by our enterprise license. In an ideal world, that means that `internal/campaigns` doesn't exist. However, GraphQL-go relies on reflection and validates the root resolver against the schema on startup, so it expects all queries, mutations and fields on types to be reachable using reflection. For that, there needs to be an interface, and some stub resolvers for the mutations, that we can feed in when running Sourcegraph OSS. The actual resolver logic, which implements these interfaces then, lives in `enterprise/internal/campaigns`. What I would ideally want to have in the future:
- Split up `schema.graphql` into feature areas, so there would be a `enterprise/internal/campaigns/resolvers/schema.graphql`, that contains all campaigns resolvers. That would mean that OSS can start up just fine without finding valid resolvers for all these additional graphql types. For that the `extend` keyword in graphql will be useful:
    ```graphql
    extend type User {
        campaigns: CampaignsConnection!
    }
    ````
- Register node resolvers using some `map[string]ResolverFunc`, so there also is no need to return a `CampaignResolver` in the global `nodeByID` resolver
- have a way to augment existing resolvers, like the user resolver for example. (I believe this requires a library change.. and this is where I got stuck at trying this for like 30 minutes in the past)

Once that is done, I don't think there should be any other reason to maintain the non-enterprise package.

> - Coming across the graphqlbackend which is all stubs with no explanation of where they are implemented: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/campaigns.go

This is part of the problem above.

> - Trying to understand ultimately which Sourcegraph services bundle up campaigns code

There are two entry points into the campaigns code: 
- [The resolvers to be used by the frontend service](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/frontend.go)
- [The setup for the background jobs like syncer, cleanup jobs and the reconciler, which currently run in repo-updater (until it sunsets)](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/background.go)

These files are also the only enterprise pkg root-level files currently. This package should be the [only one used outside of `enterprise/internal/campaigns/.*`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+enterprise/internal/campaigns/.*%22+count:1000+-f:enterprise/internal/campaigns/.*&patternType=regexp)

> - Why we chose to use inheritance for a internal/db/basestore type

@efritz can probably help fill this section here

> - The relationship between a store, basestore, and sharable store

.. and this

> - Why non-store code occasionally reaches into the DB layer directly (intentional? tech debt? etc)

I think you're talking about the non-campaigns tables, right? Like `db.GlobalUsers.GetByID(ctx, id)`. I think this is actually tech debt, and should use the same db handle as the campaigns store in scope, once they all allow injecting a db handle other than `dbconn.Global` (I _think_ this migration is still ongoing?).

> - High-level explanations of code breakdown, e.g. `store.Store` isn't idiomatic Go and the level of testing utility packages we have seems strange at first glance

`store.Store` - hm yeah not super pretty. Suggestions always welcome 😬 
We just recently started tinkering around with package names and introducing more packages, since we in the first place just had a giant package. That helped us have more cache hits running `go test` and forced us to write more self-contained tests, because coverage for implicitly tested paths would not be documented. This is still an ongoing process and once this is done, more tests should require no db at all and we can probably have fewer global test helpers. In the beginning things were just faster to test using integration tests, but now as things become more sophisticated and the product structure settled more, we have seen potential in having better and easier to write tests when we switch to having unit tests. And as in the nature of integration tests lies a big overhead for setup, we introduced a campaigns/testing package to help us reduce the amount of copy-pasted test setup code.

---

@LawnGnome @mrnugget feel free to correct me where I'm wrong :)

**Comment by slimsag** [comment]
Thanks for the write-up, I’m sure this will be super useful in compiling docs and was useful in confirming what I thought - just to be clear I’m not blocked on anything here but do think having this in place will be super important as we onboard more folks (and our first backend engineer for code insights, so let me know if I can help formulate this or review somehow)

**Comment by mrnugget** [comment]
After talking to @tsenart this week I was also planning to describe our directory structure and why certain things live in certain folders and how they relate to each other. I'll post this in this issue here too!

**Comment by mrnugget** [comment]
Everything in @eseliger's response is correct, but I think I can provide some additional information around _why_ things are the way they are.

The biggest influence on how the campaigns code is laid out on disk and in Go packages is the following chain of considerations and trade-offs:

1. Campaigns code should be in `enterprise` as much as possible.
2. `enterprise` code can import non-enterprise code but not the other way around.
3. We needed some way to run campaigns-specific background processes (syncing data from code hosts periodically) and async operations (pushing commits to code hosts).
4. We didn't want to introduce a new campaigns-only background service, because as @slimsag pointed out [in this document about "Introducing a new service"](https://about.sourcegraph.com/handbook/engineering/introducing_a_new_service), it requires quite a bit of auxilliary work (monitoring, deployment, ...) that we couldn't afford to do in the time we had back then (September/October 2019).
5. That lead to the decision of using the singleton service that talks to code hosts that already exists: `repo-updater`.
6. `repo-updater` already used this "`enterprise` kinda inherits from the non-`enterprise` version"-scheme (which I, for one, find highly confusing)
7. We tried to get our background processes in there, but we couldn't find a way around having _some_ references to `campaigns` types, because we wanted to use the `repos.Source` interface (which is an abstraction over "code host client" that works well with our repository/external-service types) to talk to the code hosts on behalf of campaigns. That required us to move type definitions from `enterprise/internal/campaigns` to `internal/campaigns` so that we can add, for example, `CreateChangeset` methods to the `repos.Source`s. But still: we kept the complete campaigns business logic mostly in `enterprise` and only types/interfaces in the open code.
8. Then there was also "we need GraphQL resolvers in the `frontend` that have campaigns functionality, without referencing actual campaigns code"-problem that @eseliger mentioned.

None of these are set in stone, all are malleable — _with enough time_, which we didn't necessarily have and, frankly, I also think "re-architect how our codebase is split into `enterprise` and non-`enterprise` code" would've been wasted time/effort back then.

**Short version**:
1. The `enterprise`/non-`enterprise` split of our codebase makes it hard to reuse code across this boundary without either (1) introducing super abstract code (which is what you see in the stubbed-out `frontend` resolvers) or (2) exposing one to the other, in some way (which is what we did by moving type definitions from `enterprise` to open).
2. We needed a singleton-service to access the database and run background jobs/asynchronous operations that are either (1) enqueued by the `frontend` or (2) run periodically. `repo-updater` was already a place where that was done, _plus_ the whole "talking to code host" thing, so we added our code there.


---

(The following makes more sense after reading through the [Campaigns architecture overview](https://docs.sourcegraph.com/dev/background-information/architecture#campaigns)).

Let's look at what's in each directory, starting with this list:

```
$ find internal/campaigns enterprise/internal/campaigns -type d -not -path '*testdata*' -not -name '.*'
internal/campaigns
enterprise/internal/campaigns
enterprise/internal/campaigns/background
enterprise/internal/campaigns/rewirer
enterprise/internal/campaigns/state
enterprise/internal/campaigns/search
enterprise/internal/campaigns/search/syntax
enterprise/internal/campaigns/resolvers
enterprise/internal/campaigns/resolvers/apitest
enterprise/internal/campaigns/testing
enterprise/internal/campaigns/reconciler
enterprise/internal/campaigns/syncer
enterprise/internal/campaigns/service
enterprise/internal/campaigns/webhooks
enterprise/internal/campaigns/store
```

`internal/campaigns`: type definitions of common `campaigns` types, such as `Campaign`, `Changeset`, etc. A few helper functions and methods, but no real business logic.

`enterprise/internal/campaigns`: the two hooks, `InitBackgroundJobs` and `InitFrontend`, to inject campaigns code into `enterprise/{repo-updater,frontend}`. This is the "glue" in "glue code".

`enterprise/internal/campaigns/background`: another bit of glue code that starts background goroutines: the changeset reconciler, the stuck-reconciler resetter, the old-changeset-spec expirer.

`enterprise/internal/campaigns/rewirer`: the `ChangesetRewirer` maps existing/new changesets to the matching `ChangesetSpecs` when a user applies a campaign spec.

`enterprise/internal/campaigns/state`: all the logic concerned with calculating a changesets state at a given point in time, taking into account its current state, past events synced from regular code host APIs, and events received via webhooks.

`enterprise/internal/campaigns/search`: parsing text-field input for changeset searches and turning them into database-queryable structures.

`enterprise/internal/campaigns/search/syntax`: the old Sourcegraph-search-query parser we inherited from the search team a week or two back (the plan is _not_ to keep it, but switch to the new one when we have time)

`enterprise/internal/campaigns/resolvers`: the GraphQL resolvers that are injected into the `enterprise/frontend` by the aforementioned `InitFrontend`. They mostly concern themselves with input/argument parsing/validation, (bulk-)reading (and paginating) from the database via the `campaigns/store`, but delegate most
business logic to `campaigns/service`.

`enterprise/internal/campaigns/resolvers/apitest`: a package that helps with testing the resolvers by defining types that match the GraphQL schema.

`enterprise/internal/campaigns/testing`: common testing helpers we use across `enterprise/internal/campaigns/*` to create test data in the database, verify test output, etc.

`enterprise/internal/campaigns/reconciler`: the `reconciler` is what gets kicked off by the `workerutil.Worker` initialised in `campaigns/background` when a `changeset` is enqueued. It's the heart of the declarative model of campaigns: compares changeset specs, creates execution plans, executes those.

`enterprise/internal/campaigns/syncer`: this contains everything related to "sync changeset data from the code host to sourcegraph". The `Syncer` is started in the background, keeps state in memory (rate limit per external service), and syncs changesets either periodically (according to heuristics) or when directly enqueued from the `resolvers`.

`enterprise/internal/campaigns/service`: this is what's often called the "service layer" in web architectures and contains a lot of the business logic: creating a campaign and validating whether the user can create one, applying new campaign specs, calling the `rewirer`, deleting campaigns, closing campaigns, etc.

`enterprise/internal/campaigns/webhooks`: these `webhooks` endpoints are injected by `InitFrontend` into the `frontend` and implement the `cmd/frontend/webhooks` interfaces.

`enterprise/internal/campaigns/store`: this is the campaigns `Store` that takes `internal/campaigns` types and writes/reads them to/from the database. This contains everything related to SQL and database persistence, even some complex business logic queries.

**Comment by efritz** [comment]
FYI code intel has Postgres advisory locked critical sections in the frontend to emulate a singleton service.

**Comment by mrnugget** [comment]
Created a diagram to provide a rough overview of how control flows:

![batches-package](https://user-images.githubusercontent.com/1185253/110353133-00359400-8037-11eb-9eb6-d442e3523249.png)
