### ISSUE TITLE
Safari 13 is not supported (latest is 14)

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#17606]
- **Sourcegraph version:** 
Sourcegraph.com
- **Platform information:** 
MacOS Catalina 10.15.6, Safari 13.1.2

#### Steps to reproduce:

1. Got to about.sourcegraph.com on Safari
2. Click the 'Sign in' button in the top right corner

#### Expected behavior:
Showes the sign-in form

#### Actual behavior:
Loads empty page

Please, [see the video](https://www.loom.com/share/8620a9a3a4d34712a536e315f344b677).

This problem only occurs on Safari. On Chrome and Firefox, the sign-in button works as expected.

**Comment by felixfbecker** [comment]
I cannot reproduce this. What version of Safari are you running?

![image](https://user-images.githubusercontent.com/10532611/105697764-45798880-5f05-11eb-88e4-0050bf290ef7.png)

The Sign in link is just a very simple link to the sign in page on sourcegraph.com (with a `ga` param).
- Does navigating there directly work?
- Are you signed in?
- What is the full URL where you arrive?

**Comment by AlicjaSuska** [comment]
- I'm on Safari Safari 13.1.2
- I'm not signed in
- The url: https://sourcegraph.com/sign-in?_ga=2.141968242.1944897601.1611570220-390282089.1611570220
- Going directly to https://sourcegraph.com/sign-in doesn't work either

**Comment by jeanduplessis** [comment]
Not supporting Safari -1 version seems quite aggressive considering not everyone upgrades to the latest macOS version immediately.

**Comment by felixfbecker** [comment]
If I'm reading the query directly, I think it would still be included if it was used still by more than 1% of users. I agree with what you said though. But the problem is that Safari is usually the last (slowest) browser to adopt new features, and they only release yearly, so it will hold back shipping smaller bundles to all other browsers (the bundles are only as modern as the worst browser). Maybe we could add some query there that gives users X months grace period to upgrade. That however would make builds irreproducable as the output would depend on the current date. So not sure about the best solution. Probably we should relax the user % minimum to just include Safari 13 right now.

@Joelkw @ebrodymoore curious how much % of _our_ users are on Safari 13? I couldn't find any working look in Looker 🙇🏻

**Comment by ebrodymoore** [comment]
[This is what we currently have related to browsers](https://sourcegraph.looker.com/looks/659), but it's for Cloud only browser extensions. not the web app so won't be useful.

Did some searching on Google Analytics. ~10% of users are on Safari, and of those on Safari, over 80% are on some version of Safari 14.

**Comment by felixfbecker** [comment]
Concrete task here would be to toy around with the `browserslist` config according to their docs (e.g. changing the percentage?) and using `yarn browserslist` to check which get included. Modify until a config includes Safari 13.

**Comment by umpox** [comment]
PR attached: https://github.com/sourcegraph/sourcegraph/pull/17873

We can support the *last 2 major versions* of Safari explicitly here, so we don't have to rely on a specific percentage aligning for this case
