### ISSUE TITLE
sourcegraph.com experiencing unexpected error every now and then

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#1760]
I've been seeing this error every now and then when using Sourcegraph.com . It will randomly appear when I'm switching from one page to another. It resolves by reloading the page.

![image](https://user-images.githubusercontent.com/9110008/50939204-74ec0280-14ae-11e9-8efb-eeda3862a4eb.png)

The console shows this error:
```Failed to load resource: the server responded with a status of 404 ()``` originating from a `https://sourcegraph.com/.assets/scripts/27-43007cc1aa014fb8b79e.chunk.js`

I'll keep the network tab open from now on so I can get that error too, next time this happens.

**Comment by nicksnyder** [comment]
Can you look into this Felix?

**Comment by felixfbecker** [comment]
I changed the error boundary to show error messages. I don't know exactly how to repro though so can't do anything else rn. Sentry would help here.

**Comment by sqs** [comment]
If the site was redeployed and you were browsing around.

**Comment by nicksnyder** [comment]
Ok, I could imagine how this could happen if we are lazily loading JS chunks (is that the case?).

If so a reproduction might look like:
1. Open sourcegraph in a browser tab
2. Deploy a new version of javascript
3. Navigate around the app to force it to try to load a new chunk -> this could 404

Is there a way to catch these 404s and handle them by doing a hard page refresh automatically?

**Comment by sqs** [comment]
Yeah we are now, I introduced that recently. This is definitely a problem. We could go back to using a single chunk for now in webpack config (ideally keep the work that refactored the UI to use multiple chunks, but just override webpack in 1 place to tell it to emit a single chunk).

Doing a hard page refresh seems like the best simple option, but it MIGHT be problematic:

1. if you had state like an unsaved settings editor (then a hard page refresh would lose it) -- although you're unlikely (impossible?) to encounter these 404s when you are in that state
1. identifying which 404s would be fixed by this reload and which wouldn't may be complicated, and we don't want a reload loop

If someone has a good idea on how to address those 2 things, then :+1: let's do it

**Comment by nicksnyder** [comment]
For 3.0 release I think we should just go back to 1 chunk. I neither saw any recent commits in [webpack.config.ts](https://github.com/sourcegraph/sourcegraph/commits/tsenart/repos-list-replacement/web/webpack.config.ts), nor on obvious config to set. @felixfbecker can you do this?

**Comment by sqs** [comment]
There were no changes to webpack config, it was changes in how we import code. I'll do it (quick change, I have context)
