### ISSUE TITLE
Frontend: Add "Product research and feedback" page to user settings

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17646]
Part of implementing [RFC 215: Improving User Feedback](https://docs.google.com/document/d/1mn3AxOMLM_ivu-mfWa3VAXyJnmX4WFInREdB2kI_g6o/edit#).

**Description**

Add "Product research and feedback" page to user settings.

<a href="https://www.figma.com/file/9FprSCL6roIZotcWMvJZuE/Improving-user-feedback-channels?node-id=386%3A310"><img width="1338" alt="CleanShot 2021-01-26 at 11 11 14@2x" src="https://user-images.githubusercontent.com/6304497/105831611-39ee9600-5fc7-11eb-817b-8be9e88db77f.png"></a>

Button link will likely need to support dynamic URL parameters so we can pre-populate a signup form on an external source (e.g. Airtable, HubSpot – yet to be finalized).

Note that based on @dadlerj's feedback, site admins will need to be able to disable this page for all users on their instance (#17647).

**Design documentation:**

- [View in Figma](https://www.figma.com/file/9FprSCL6roIZotcWMvJZuE/Improving-user-feedback-channels?node-id=386%3A310)

**Comment by umpox** [comment]
@quinnkeast @attfarhan @ebrodymoore 

> (e.g. Airtable, HubSpot – yet to be finalized).

Do we have an idea of where this 'Sign up now' link will go yet?

**Comment by ebrodymoore** [comment]
@umpox I think it's likely going to be HubSpot. I have an [RFC](https://docs.google.com/document/d/1eUb3ws7Lhp5WDOs3ePw5o2ctfuBDnh_XXE1HYXoty78/edit?ts=60190c4a#heading=h.g0gjwch98szj) out that I threw my thoughts into and am advocating for HubSpot (and as long as @quinnkeast is cool with HubSpot we'll go with it 😄). Hopefully we'll nail this decision down in the next 24 hours.

In part because the implementation should be easier since [we already use it](https://docs.google.com/document/d/1eUb3ws7Lhp5WDOs3ePw5o2ctfuBDnh_XXE1HYXoty78/edit?ts=60190c4a#heading=h.g0gjwch98szj).

**Comment by ebrodymoore** [comment]
@quinnkeast let me know what the form fields should be so I can create them in HubSpot!

**Comment by quinnkeast** [comment]
[Here's our previous research signup form](https://airtable.com/shr2JxrSfqFcySukF). I think we can use the same fields and language.

**Comment by umpox** [comment]
Are we able to create a similar form in HubSpot? The page structure and admin toggle work for this is done. Just need to form the URL to point the 'Sign up now' button at

**Comment by ebrodymoore** [comment]
[Here's the form](https://share.hsforms.com/1tkScUc65Tm-Yu98zUZcLGw1n7ku). @quinnkeast let me know what you want in terms of a follow-up email, any different styling on the form, etc. I'm trying to figure out how to add a title to the form but it's not as easy as it should be 😆
