### ISSUE TITLE
search: Error not exposed to user

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#17725]
I've noticed during my work on structural search that, in some cases, the error message is not exposed to users, and instead "No results" is displayed. 

For example, the query `repo:sourcegraph/sourcegraph-typescript@master const :[1]: patternType:structural` causes a backend error because doing structural search on a specific branch isn't yet supported. See [here](https://github.com/sourcegraph/sourcegraph/blob/bd8e595e3a47b157fa3c907dc301d302fa3e0824/cmd/frontend/graphqlbackend/zoekt.go#L179).

This error message should be exposed to users.

**Comment by rvantonder** [comment]
Looks like this was a bug introduced by streaming search (or old code path was buggy?). Now, you'll see "unindexed branches not supported". This is still false, since `master` will often resolve to `HEAD`. We should fix this one. Link to query above:

[`repo:sourcegraph/sourcegraph-typescript@master const :[1]: patternType:structural`](https://sourcegraph.com/search?q=repo:sourcegraph/sourcegraph-typescript%40master+const+:%5B1%5D:&patternType=structural)

**Comment by rvantonder** [comment]
Seems related to our [comment](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/searcher/search/zoekt_search.go#L155-157) too:

>  // TODO(@camdencheek) TODO(@rvantonder). repoBranches is currently
// hardcoded to HEAD. Choose sensible values for k when we generalize
// this.


I think we can delete ^ now since we resolve more than `HEAD` right? There's just the question of resolving `master`.

**Comment by camdencheek** [comment]
I can't reproduce this anymore with either of those queries, so I think we should close this unless we can come up with another error that isn't propagated up to users. I'll make a PR that removes that comment
