### ISSUE TITLE
Report errors to Sentry whenever we call `log15.Error` or `log15.Fatal`

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#17746]
This may include a spike on writing a hook for log15.

**Comment by arussellsaw** [comment]
i remember giving this feedback when we chatted but after our discussion the other day maybe this isn't the approach we want to take for now?

i think this only works in a world where our error handling is super clean, eg errors are handled & swallowed, otherwise they're serious.

perhaps this is worth putting on the backburner until our error handling is a bit more mature.

**Comment by unknwon** [comment]
@arussellsaw Yes, 100% agree we need to fix loggings first, would do this one after https://github.com/sourcegraph/sourcegraph/issues/17743 solve your concern?

**Comment by unknwon** [comment]
Close as implemented, docs https://docs.sourcegraph.com/dev/how-to/add_logging.
