### ISSUE TITLE
Kubernetes database restoration docs missing?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#17857]
https://sourcegraph.slack.com/archives/C07KZF47K/p1611958288163200

I couldn't find Kubernetes postgres snapshot restoration docs, they appear to be missing or not discoverable.

I expected to find something like:

> Key thing here is just to make sure Sourcegraph services (pods) aren't running while the restoration is taking place. so:
> 1. Take down all existing deployments (e.g. kubectl scale deploy $DEPLOYMENT --replicas=0 )
> 2. Restore the Postgres DB from one of your snapshots
> 3. Start back up all deployments (scale replica count back up to original number)
> If you do that, everything should be totally smooth sailing

Otherwise AFAIK there are a number of bad issues that arise during a snapshot restoration

**Comment by pecigonzalo** [comment]
@slimsag We don't provide backup or restore docs except for some high-level guidance on [which parts of the system can be recreated](https://docs.sourcegraph.com/admin/install/migrate-backup). 

If I understand this correctly, we are not looking to add docs on how to perform the actual backup, but rather on what other steps are necessary when performing a backup or restore. If this is the case, I will add this as `debt` instead of  `bug` and will edit the original issue body to match and describe the desired state.

**Comment by daxmc99** [comment]
I think this might be a good task to tackle this cycle? wdyt @pecigonzalo ?

**Comment by pecigonzalo** [comment]
Sounds good, if we have the bandwidth go for it.

**Comment by daxmc99** [comment]
It also might be worthwhile to add some docs that you can perform a database upgrade by setting the database to read-only and performing the upgrade.
