### ISSUE TITLE
Ability to jump directly from search results page -> viewing the result on code host

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#17963]
A user at https://app.hubspot.com/contacts/2762526/company/407948923/ requests we provide the ability to jump directly from the Sourcegraph search results page to the result (file/line) directly on the code host.

I think this makes a _ton_ of sense, actually, and would make Sourcegraph easier to integrate into devs whose main workflow is using the extension on their code host (or who are just not as comfortable staying in the Sourcegraph interface in general.)

@sourcegraph/product-team can we consider this as we think about search page designs etc.?

https://sourcegraph.slack.com/archives/C0W2E592M/p1612391851045700

**Comment by Joelkw** [comment]
(Just merged the new team/frontend-platform notifier!)

**Comment by felixfbecker** [comment]
@Joelkw I think this is misclassified as a platform issue, features on the search results page should be owned by the search team.

**Comment by Joelkw** [comment]
@felixfbecker oh perfect, fixed! My bad.

**Comment by camdencheek** [comment]
I think this is a "won't fix" because:
1) The search results page is pretty constrained space-wise, and I don't think we really have the design room to add a button to jump to the code host
2) We _do_ support this on the blob pages, so it's only one more click away
3) Our browser extensions have massively underloved, so relying on those for a good experience is not a good bet right now
4) This issue is quite old and I'm trying to clean stuff up 🙂 

cc @taiyab to take into account though. Maybe we could add a code host action in the preview panel?
