### ISSUE TITLE
Go code intelligence extension fetching source code from outdated url

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#180]
- **Sourcegraph version:** 20099_2018-09-07_e93d7c6
- **Platform information:** 
#### Steps to reproduce:

My personal Sourcegraph instance which is running build `20099_2018-09-07_e93d7c6` is unable to use the Go language server extension via the browser extension.

I'm seeing the following errors in the console: 

![screenshot 2018-10-01 14 17 08](https://user-images.githubusercontent.com/4897310/46316894-42b13780-c586-11e8-9523-a0fc680e76b8.png)

I think the issue has to do with the Source code URL being set to https://storage.googleapis.com/sourcegraph-cx-dev/sourcegraph-langserver-http.js instead of https://storage.googleapis.com/sourcegraph-cx-dev/sourcegraph-langserver-http.3.js (which it is on sourcegraph.com)

How does this URL get updated and do we know why my extension would be out of date?

#### Expected behavior:

Go code intelligence would work on my instance and via the browser extension.

#### Actual behavior:

Go code intelligence only works on my instance and does not work via the browser extension.

**Comment by sqs** [comment]
This will occur when you use a new browser extension version with an old server. This occurred because:

1. Your old Sourcegraph server used a hardcoded URL to an old version of the langserver extension (which is used for all languages' code intel)
1. Your browser extension was new and expected an extension that used the new API

The only server versions affected are those that are very old and before Sourcegraph extensions were available to users. Because of that, and because we will be making individual extensions for each language that are not hardcoded in the server, I am going to close this.
