### ISSUE TITLE
Disable context selector if query contains `context:`

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#18086]

**Comment by rvantonder** [comment]
Please implement the check for "does the query contain `context`" in `validate.ts`, similar to this [`findFilter` function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/search/query/validate.ts#L27). Unfortunately `findFilter` won't work out of box, since you probably want to detect _any_ context field. I recommend keep it simple: just add a `contextExists` function here and iterate over the fields similar that existing `findFilter`. It's possible to factor out some things at a later stage, and I will be looking at this code soon, so just go the easy route with `contextExists`.
