### ISSUE TITLE
Reenable the status message navbar item on Cloud for site admins and users who are dogfooding adding their own code.

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#18199]

**Comment by artemruts** [comment]
@ryanslade Right now we can enable status messages for dotcom admins (Sourcegraph team), I don't think we can enable for users before we scope status messages to those users.

Right now we'll get status message for the whole cloud instance:

```js
{
  "data": {
    "statusMessages": [
      {
        "__typename": "CloningProgress",
        "message": "2675282 repositories enqueued for cloning..."
      },
      {
        "__typename": "ExternalServiceSyncError",
        "message": "bad credentials",
        "externalService": {
          "id": "xxx",
          "displayName": "GitHub (Artem) - will delete after test"
        }
      }
    ]
  }
}```

**Comment by ryanslade** [comment]
The query is scoped by the current logged in user so if it's made by a non admin user it'll only return the details of their own repos and external services. 

https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/graphqlbackend/status_messages.go#L14

We should still only enable it for user's opted in though since it doesn't make sense for users who can't add their own code.
