### ISSUE TITLE
Update action buttons in search results

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#18281]
Based on the hallway testing outcomes along with the design team feedback, we have an iteration on the search result actions UI:

<img width="604" alt="CleanShot 2021-02-15 at 14 42 29@2x" src="https://user-images.githubusercontent.com/6304497/107953917-10a8a080-6f9c-11eb-9017-820dbcb26606.png">

[Full design documentation in Figma](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3921%3A37186)

Includes:

- Update button labels and add icons
- Separate search details from buttons with bar; separate buttons from collapse action with bar
- Always show "Monitor" button on all results, but disable if current search query isn't valid for a code monitor
- Show tooltip while "Monitor" button is disabled with message explaining why
- Show "New" tooltip the first time the user runs a search that can be monitored

**Comment by limitedmage** [comment]
@quinnkeast  Regarding this item: 
> Always show "Monitor" button on all results, but disable if current search query isn't valid for a code monitor

I'm hesitant about doing this because the space on the infobar is already so tight. We want the infobar to be on the same line as the tabs, and adding this button may cause the infobar to be too long for that and be pushed to under the tabs.

Example:
![image](https://user-images.githubusercontent.com/206864/111340025-7b013f00-8635-11eb-8200-8ada3b60803a.png)

If you feel it's still worth it to add the disabled button for discoverability, I can go ahead and do it, just wanted to raise this concern.

**Comment by limitedmage** [comment]
@quinnkeast FYI there is still work left on this (the "New" tip on the Monitor button), so please re-open this issue or create a new issue for that if we still want to do that work.

**Comment by lguychard** [comment]
I created a more specific issue for the work that is left to do: https://github.com/sourcegraph/sourcegraph/issues/21049
