### ISSUE TITLE
Impossible to sign out when using GitHub auth

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1834]
When using only GitHub auth, the sign out button is a noop.

![2019-01-12 19 36 03](https://user-images.githubusercontent.com/10532611/51077060-5d28a000-16a1-11e9-9301-2a9f00c4c179.gif)

Config:

```json
{
	"auth.providers": [
    {
      "type": "github",
      "clientID": "...",
      "clientSecret": "..."
    }
	]
}
```

**Comment by KattMingMing** [comment]
Looks like this is caused by the redirect when only 1 auth provider is present.
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/auth/oauth/middleware.go#L34:3-34:101

I noticed another bit of slightly confusing UX with the auto redirect that could impact how we solve the UX related to signing out:

When a new user goes to a Sourcegraph instance for the first time with only 1 auth provider they are automatically redirected to the auth provider website (GitHub, GitLab, etc)  that requests permissions. This is confusing if it's your first time going to Sourcegraph and immediately are shown a prompt to accept permissions.

**Comment by felixfbecker** [comment]
It also looks very weird when you share a URL to your instance because the crawler gets redirected to GitHub too:

![image](https://user-images.githubusercontent.com/10532611/51078183-db8d3e00-16b1-11e9-96f4-a35aa1388f17.png)

**Comment by beyang** [comment]
Proposed changes:
* "Sign out" clicked on Sourcegraph -> Sign out page indicated they signed out with link to https://github.com/logout that gives the user the option to sign out of GitHub, as well.
* Remove automatic redirect when the fetcher is a bot (so that the preview image is still Sourcegraph)
