### ISSUE TITLE
Result type tabs buggy when using type: and select: in conjunction

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#18501]
[`repo:^github.com/microsoft type:commit after:"2 weeks ago" monaco select:repo`](https://sourcegraph.com/search?q=repo:%5Egithub.com/microsoft+type:commit+after:%222+weeks+ago%22+monaco+select:repo&patternType=literal&context=global) (awesome query to write by the way 🙂 )

![image](https://user-images.githubusercontent.com/1741180/108551238-f3533980-72ef-11eb-95d8-d2798ff22ceb.png)

All returned results are repositories (as per the `select:` field), but the "Commits" tab is selected because the heuristic we use on the frontend is too naïve. @rrhyne more signal that we need to get rid of those tabs.

**Comment by rvantonder** [comment]
My take: the underlying issue is that tabs generalize poorly to this use case (UI/UX "bug"). Since you labeled this as bug and assigned Camden and I, the only way I can see us fixing this until we have a consensus on UI/UX is to implement "if commit tab selected => diagnostic that raises that `select` is not valid, or grays out the search bar, or something". Did you have a solution in mind to resolve this around some notion of "correct" behavior?

**Comment by rvantonder** [comment]
Oh, I see it will automatically select the `commit` tab with `type:commit`. Uh, yeah, that's another UI/UX bug. I have to say, I don't have a proposal for fixing this personally, it would need to be replaced with "something" and I haven't thought deeply about the design/UI of that something.

**Comment by lguychard** [comment]
Yeah, I should have added: I don't have a fix in mind either, don't feel like it's high-priority (since we want to bin the tabs), just wanted to file for bookkeeping, and tagged you+Camden as the feature authors 🙂

**Comment by lguychard** [comment]
We no longer have result type tabs 🎉
