### ISSUE TITLE
Chrome Web Store listing issues

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#18545]
1. "Mature content" warning: 
![image](https://user-images.githubusercontent.com/1976/108770158-d5175480-750e-11eb-9bf4-f87221ebd146.png)
1. Broken link to source: <blockquote> Noticed that the browser extension description on Chrome Web Store https://chrome.google.com/webstore/detail/sourcegraph/dgjhfomjieaadpoljlnidmbgkdffpack is outdated. It says that "This extension is open source", but the URL pointing to a GitHub repository is returning error: "404 This is not the page you are looking for".<br/><br/>Might be worth updating the description, as it would help new potential extensions users to verify what the extension does (especially since it is having user activity collection as part of editor functionality).</blockquote>

**Comment by marekweb** [comment]
I fixed the source URL and removed the "Mature content" flag. It's not clear to me why that flag got enabled on our listing.

**Comment by Joelkw** [comment]
(I think this may not have gone into review for whatever reason, so I submitted it for review just now. I did see that your changes @marekweb were saved in the draft resubmission; thanks for fixing those.) 

I'm not sure where the mature content warning came from but will keep a closer eye on this version.

**Comment by Joelkw** [comment]
This is fixed (label gone). 

As for #2, it's "mostly fixed" – it looks like the link goes to `https://github.com/sourcegraph/sourcegraph/tree/master/client/browser` rather than `...main/...` but this still redirects properly to our repo now instead of showing a 404. (My bad – I saw the typo in the url and pattern matched that to "this is what's wrong" without noticing it had "master" rather than "main"). I've updated it to go out in the next release, saved in draft form.  I'm not sending out this update immediately so I don't block our Chrome extension release ([which apparently happens otherwise](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1614052527022900?thread_ts=1614052205.022800&cid=C01LZKLRF0C)).
