### ISSUE TITLE
Repository "Check connection" fails on SSH clones, even though cloning the repo works

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1856]
1. Start Sourcegraph and configure it to clone via SSH by following our docs.
2. Add an External Service connection of type `OTHER`:
```
{
  "url": "ssh://git@github.com",
  "repos": [
    "slimsag/my-private-repo",
  ]
}
```

3. Visit the /site-admin/repositories page. Your repository will appear.
4. Visit the repository. Notice that it cloned fine, you can view code etc.
5. Visit the mirroring page for the repository at e.g. /github.com/slimsag/my-private-repo/-/settings/mirror
6. Notice the `Remote repository URL` correctly indicates `ssh://git@github.com/slimsag/my-private-repo"`
7. Click `Check connection` and see error:

```
The remote repository is unreachable. Logs follow.

repo not found (name=github.com/slimsag/my-private-repo url=https://github.com/slimsag/my-private-repo.git notfound=true) because exit status 128 (output follows)

remote: Repository not found.
fatal: Authentication failed for 'https://github.com/slimsag/my-private-repo.git/'
```

It seems as though `Check connection` button is not using regular gitserver cloning but instead trying to clone via HTTPs or something to check for indication of access. This is obviously wrong.

@nicksnyder who should own this?

**Comment by nicksnyder** [comment]
Need to triage this to see if it is a regression from 2.13.5 or not.

**Comment by tsenart** [comment]
I verified that this is a regression, but I'm not sure why exactly yet. The issue seems to be [here](https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/repos_vcs.go#L87). We're returning the wrong URL based on not having a token configured and finding the `github.com` sub string, even when the whole URL is of the form `ssh://git@github.com`

**Comment by tsenart** [comment]
OK, so this commit introduced the regression: https://github.com/sourcegraph/sourcegraph/commit/fea40186d9306153ccfbf89e1afb13f3e35c336f#diff-38d673c3d1ef2fb59e5788a6a3e30e7b

Before, we were returning `nil` from `quickGitserverRepo` when we didn't have a token for github.com. With this change, we now return false and the repo with the wrongly constructed https URL.

**Comment by tsenart** [comment]
A note for later that may help debugging: This doesn't happen when testing on the local development environment started with `./enterprise/dev/start.sh`, but it happens when working with the server:insiders Docker image (even after `cp -R ~/.ssh/ ~/.sourcegraph/config/ssh/` and restarting the Docker image).

**Comment by chrismwendt** [comment]
I think I found the problem: the frontend neglects to check that the repository is associated with a GitHub external service in addition to checking that the repository hostname is `github.com` before finding for an access token and looking up the repository on GitHub.com via HTTPS.

That means when you have a GitHub external service with an access token and one of your repositories is associated with an Other external service configured with `"url": "ssh://git@github.com"`, the frontend incorrectly thinks it can clone the repository from GitHub.com using the access token.

You can reproduce it in your local development environment by deleting all but the Other external service.

I opened a tentative PR https://github.com/sourcegraph/sourcegraph/pull/2102
