### ISSUE TITLE
No code intelligence for vscode references because of postinstall script

### ISSUE THREAD

**Issue by reflog** [sourcegraph/sourcegraph#1865]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Chrome, Windows

#### Steps to reproduce:

1. Open https://github.com/reflog/vscode-jsonresume/blob/master/src/validate.ts
2. Hover over "diagnosticCollection: vscode.DiagnosticCollection"

#### Expected behavior:
`diagnosticCollection` should have a type of `vscode.DiagnosticCollection`
and `vscode.DiagnosticCollection` should link to the vscode typings.

#### Actual behavior:
![image](https://user-images.githubusercontent.com/109876/51119313-32faed80-181b-11e9-8c1f-e3708b154a01.png)

**Comment by felixfbecker** [comment]
The problem here is that the `vscode` package doesn't actually contain the `vscode.d.ts` file: https://unpkg.com/vscode/
It just contains a script that downloads the file from GitHub, which is called from a `postinstall` script: https://github.com/reflog/vscode-jsonresume/blob/d79faeb0a39fa7ca6a9b3d7f6df8c0aa8816f5a6/package.json#L82

Unfortunately we cannot run `postinstall` scripts because that would allow arbitrary code execution on the server

**Comment by christinaforney** [comment]
Hi @reflog - This has been on our backlog for awhile and we haven't seen much other interest in it yet. I'm going to close this out, but have added a someday/maybe label which we will review periodically to pull in ideas that have interest or become more relevant.

Interested parties, please +1 this issue to help this get attention.
