### ISSUE TITLE
RFC 311: Make a down-migration utility separate from the instance

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#18659]
We have an issue for downgrades:

- We introduce a migration that translates records R from v1 -> v2
- We can read both v1 and v2 records on our current instance version (but the previous one could read only v1)
- We write only v2 records

If the user wants to downgrade, active writes to the table will increase the work on the down migration. In order for the down migration to succeed, we need all records to have v1 before shutting down.

I think we need a last-step prior to downgrades that will basically finish the migrations "offline". This could take the form of either:

- shutting off writes to the table from the outside (could be tricky, instance will be partially functional)
- running the frontends in "migration-only mode" before re-booting the previous version (requires downtime)

**Comment by eseliger** [comment]
Hmm I wonder if it would be fixed by adding two guidelines:
- Always have a migrator around for at least 2 versions, followed by deprecation
- Read the old data format in the first release that includes the migration

Given versions `N, N+1, N+2`,
in `N` a migrator is introduced, but the whole application code still relies on the _old data_, in `N+1` it still exists and reads the _new data_, and in `N+2` it is deprecated, and still reads the _new data_

Then when downgrading from `N+2` to `N+1` should always be safe, since N+1 needs to be supporting both format `A` and `B`, but the remaining instances of `N+2` would fail to read format `A`, so ideally the down migration would only start after all `N+2` instances are gone.
Then, once that migration is "almost"(new records can still come in) done, migrating down to `N` is possible. `N` understands `A` and `B`, too, so there is no failure because a the data schema is not understood. Once all `N+1` instances are terminated, only data in the old schema will be written to the DB and the migration can run to completion. Once that happened, migrating down from `N` to `N-1` should be 100% safe without ever needing to "suspend" any instances.

**Comment by efritz** [comment]
@eseliger I want to respond to this within the year 😝 

This could work but I think might be more error-prone than having a way for the user to run out of band migrations separately. This would basically be a simplified instance of the `worker` process that only registers out of band migration tasks.

This would be useful even if we did the scheme described above, as the admin could run out of band migrations in the presence of other errors that prevent the migrations from running _at all_ (which is also possible).

Having a separately runnable utility that you just point at a database seems like a nice escape hatch to have, even if we don't have a particular use-case driving it.

**Comment by efritz** [comment]
This is already done (but not explicitly documented) by having moved the migrators into the worker instance. Workers can now be started with ONLY that task independently of the other services.
