### ISSUE TITLE
UI rendering bug – if you move your mouse slowly over a graph, the graph re-renders (It shouldn't)

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#18888]
Slowly mousing over the graph causes the UI re-renders. See attached: 

https://user-images.githubusercontent.com/11967660/110048539-e299bf00-7d04-11eb-937f-5406f5f7923a.mp4

**Comment by felixfbecker** [comment]
I think this has to do with the sizing/positioning logic. The tooltip probably makes the graph larger, causing it to recalculate the positions/sizes. Might be related to #18649. Rerendering is not wrong per-se since it needs to render the tooltip, but it shouldn't reposition and retrigger animations.
