### ISSUE TITLE
Typescript: Go To Definition goes to wrong repository

### ISSUE THREAD

**Issue by justinfagnani** [sourcegraph/sourcegraph#189]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Open https://sourcegraph.com/github.com/Polymer/lit-element/-/blob/src/lit-element.ts
2. Hover over `TemplateResult` on the last line of code
3. Click on "Go To Definition" in the popup

#### Expected behavior:

Window navigates to:

https://sourcegraph.com/github.com/Polymer/lit-html/-/blob/src/lib/template-result.ts#L23

which is in the repo of the dependency where `TemplateResult` is defined.

#### Actual behavior:

Window navigates to:

https://sourcegraph.com/github.com/jdubray/sam-samples@5a51711799a3e8797a77a106570852013487509f/-/blob/lit-html/src/lit-html.ts#L65:1

Which is some random repo that copied lit-html into its source at some point.

Shouldn't SouceGraph be trying to locate the actual source used from a dependency? In this case we have a package.json that lists `lit-html` as a dependency. That npm package in turn lists Polymer/lit-html as the repository it's from.

**Comment by felixfbecker** [comment]
Thanks for investigating @keegancsmith. I would expect the TypeScript language server would return the `repoURL` here, not sure why it doesn't.

**Comment by felixfbecker** [comment]
@justinfagnani our new TypeScript support now uses declaration maps to power cross-repo go-to-definition instead of the previous fussy symbol search. Your example now takes you to Polymer/lit-html correctly 🎉 

![2018-12-12 22 51 37](https://user-images.githubusercontent.com/10532611/49901088-92eb2680-fe60-11e8-8395-c5f86028ea7d.gif)
