### ISSUE TITLE
dev/ci/yarn-test.sh shared buildkite step sometimes hangs

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1898]
I saw this hang up to 30 minutes. Retrying seemed to fix it.

Example: https://buildkite.com/sourcegraph/sourcegraph/builds/26706#ed7c49d6-58da-4826-9c5f-1df934a1c16b

**Comment by nicksnyder** [comment]
Looks like the message `Error sideloading extension: baz` always happens and is a red herring. This build step does seem to hang though.

**Comment by nicksnyder** [comment]
I don't know if this is still happening, so I am going to close.

**Comment by nicksnyder** [comment]
This just happened with the 3.0.1 build
https://buildkite.com/sourcegraph/sourcegraph/builds/27575#434ac7bb-33d6-4a1d-b1be-a68900f31a85

**Comment by ggilmore** [comment]
The javascript error is a red-herring. Here are the logs from the buildkite agent that was running [that job](https://buildkite.com/sourcegraph/sourcegraph/builds/27575#434ac7bb-33d6-4a1d-b1be-a68900f31a85):

https://console.cloud.google.com/logs/viewer?interval=P1D&project=sourcegraph-dev&organizationId=1006954638239&minLogLevel=0&expandAll=false&timestamp=2019-02-08T16:46:04.035000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22ci%22%0Aresource.labels.namespace_id%3D%22buildkite%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.zone:%22us-central1-a%22%0Aresource.labels.container_name%3D%22buildkite-agent%22%0Aresource.labels.pod_id:%22buildkite-agent-%22%0A434ac7bb-33d6-4a1d-b1be-a68900f31a85&scrollTimestamp=2019-02-08T02:34:19.597016293Z&dateRangeEnd=2019-02-08T16:48:09.715Z&dateRangeStart=2019-02-07T16:48:09.715Z

You can see that it was eventually canceled: https://console.cloud.google.com/logs/viewer?interval=P1D&project=sourcegraph-dev&organizationId=1006954638239&minLogLevel=0&expandAll=false&timestamp=2019-02-08T16%3A46%3A04.035000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.pod_id%3D%22buildkite-agent-698647648b-b67cc%22%0Aresource.labels.zone%3D%22us-central1-a%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.cluster_name%3D%22ci%22%0Aresource.labels.container_name%3D%22buildkite-agent%22%0Aresource.labels.namespace_id%3D%22buildkite%22%0Aresource.labels.instance_id%3D%224842285353073032386%22%0Atimestamp%3D%222019-02-08T02%3A34%3A19.065571934Z%22%0AinsertId%3D%221awh83ef5dcdal%22&scrollTimestamp=2019-02-08T02%3A34%3A19.597016293Z&dateRangeEnd=2019-02-08T16%3A48%3A09.715Z&dateRangeStart=2019-02-07T16%3A48%3A09.715Z

The pod has since been destroyed and so I can't pull up any metrics on how much memory it was using. I do think that it ran out of RAM and the job stalled. I'll try bumping the amount of memory to 7 gigs and see if that happens again.

**Comment by ggilmore** [comment]
I bumped the Buildkite agent's memory to 7 gigs in https://github.com/sourcegraph/infrastructure/commit/64ba7c03d31b22b9eb4cb38f266d2bae9c1398c0

We can revisit this issue if it happens again.

**Comment by ggilmore** [comment]
@nicksnyder @lguychard I just observed a buildkite agent using ~6 gigs when running that build step: 

![screen shot 2019-02-08 at 9 20 59 am](https://user-images.githubusercontent.com/9022011/52494604-4764a880-2b83-11e9-9830-c01937afc3cf.png)

See https://console.cloud.google.com/kubernetes/pod/us-central1-a/ci/buildkite/buildkite-agent-67c6944878-4mjvl?project=sourcegraph-dev&organizationId=1006954638239&container_summary_list_tablesize=10&tab=details&duration=PT1H (link is not stable)
