### ISSUE TITLE
Extension enable/disable button shows in different places

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#19076]
Depending on the length of the extension sub-header the enable/disable button will show in a different location. This could potentially cause a confusion for the end user.

See the examples:
![image](https://user-images.githubusercontent.com/1308560/110868228-10d74b80-827d-11eb-8d3d-4da728b46518.png)

**Comment by Joelkw** [comment]
@muratsu nice find! @AlicjaSuska what do you think about changing this page so we just show the extension repo title rather than the "author / [title]" format? It's not a super common pattern but I know we've redone/focused a lot on our breaders navigation – does it have to be this way for consistency or is that something we could change when we get to this page?
