### ISSUE TITLE
Clean up gitserver's usage of HOSTNAME

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#19098]
The fix in https://github.com/sourcegraph/sourcegraph/pull/19097 is only meant to be temporary and was caused by a missing `HOSTNAME` env var when starting `gitserver` in the server image.

`HOSTNAME` is a really generic name for an env var (and also set/used by other Unix programs) that's used to give a gitserver shard member a unique identity.

Maybe we can find a better name for this and try to set it automatically or at least next to the other `SRC_GITSERVER` variables and not in the Procfile.

**Comment by ryanslade** [comment]
I'd propose changing it to `SRC_GITSERVER_SHARD`

We can't change what's in `SRC_GIT_SERVERS` since the value in there are actually used by the gitserver client to pick a host depending on which repo we're accessing.

**Comment by mrnugget** [comment]
Then at least let's be consistent and use `SRC_GIT_SERVER_SHARD_ID` or something.

**Comment by ryanslade** [comment]
Here's another idea of how we could solve this:

Frontend instances already communicate with gitserver instances. Why not have frontend instances iterate over the list of gitserver instances they know about and send them their shard id? This would remove any ambiguity since we would be using a single source of truth. We'd have to do this periodically but the amount of data actually being sent is negligible. 

The only negative I see is that it introduces extra communication overhead but considering that gitservers already require frontend to be alive to get config it's not making things any worse. 

@keegancsmith @mrnugget WDYT?

**Comment by mrnugget** [comment]
Interesting! I think the Zoekt sharding mechanism works the other way around, right? Zoekt instances know that they are Shard #1, for example, and then ask frontend which repositories they should have.

> Why not have frontend instances iterate over the list of gitserver instances they know about and send them their shard id? 

How do you ensure that different frontend instances always send the same thing? How do you handle "sticky" shard IDs so if you change the number of gitservers you don't run into the problem of thousands of repositories being deleted and recreated on another shard?

**Comment by ryanslade** [comment]
> How do you ensure that different frontend instances always send the same thing? 

In theory they all have the same value in their `SRC_GIT_SERVERS` var. If that value changes it would be different temporarily as each instance of frontend rolls out but we'd have that same issue today as sharding happens in the `gitserver` client. 

> How do you handle "sticky" shard IDs so if you change the number of gitservers you don't run into the problem of thousands of repositories being deleted and recreated on another shard?

That's a larger problem and one that would bite us today anyway. `gitserver` sharding is very naive at the moment and any change to the number of instances will cause a big reshuffle. This is something we want to look into later this year, probably as part of https://github.com/sourcegraph/sourcegraph/issues/16577

The main aim of this change is to ensure that as much as possible gitserver and frontend have a consistent view of which gitserver instances exist and the id of each instance.

**Comment by mrnugget** [comment]
Okay. And how would gitserver store this information? Or is this being sent along with every request and its stateless?

**Comment by ryanslade** [comment]
We'd probably rename this to 'ShardID` and store it there:
https://github.com/sourcegraph/sourcegraph/blob/39a2b33e2600f6168866ed6c7244535308fb8001/cmd/gitserver/server/server.go#L141

We need to store it since `gitserver.SyncRepoState` needs to know the state when it runs in the background. 

We'd need to wait until the first time it received a valid shard id to kick off:
https://github.com/sourcegraph/sourcegraph/blob/39a2b33e2600f6168866ed6c7244535308fb8001/cmd/gitserver/main.go#L143

I did think about perhaps including the shard id in a header we send on every request which might make this a smaller change but it not the most explicit. 

I just saw that we already have a `/ping` endpoint on `gitserver` and a `pingAll` method on the client so we could reuse that.

**Comment by keegancsmith** [comment]
Sending the name makes sense. In fact you can just check the http host header (I think that includes port?). This would solve the "what name does frontend reach me by" issue. I considered this for Zoekt, but thought the waiting for a frontend request would be weird and introduce a very tight coupling. Zoekt is slightly different though because the frontend doesn't directly communicate with the idnexserver, which was part of the issue.

Zoekt does what you originally did, but trys to use defaults to make configuration clean. So zoekt does default to `HOSTNAME`. The reason is on kubernetes that is what you use for identity in a statefulset. Then we added a `-hostname` flag to zoekt-indexserver so environments other than k8s we could encode the "hostname:port" to identify the server. I *think* we also simplified the common case, which is one zoekt server. If there is only 1 we skip matching and just assume it needs to index everything.

It feels like thinking about a more general bit of infra here may help us long term. We now have this need in two places, and in general we have some pretty "rough" service discovery stuff. It shouldn't block this issue, but I think a simple solution likely exists. For example a consistent envvar we set on all services for what its reachable address is. For k8s we just rely on what k8s provides.
