### ISSUE TITLE
Improve CSS code splitting

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#19135]
#### Description
Currently we `@import` many `scss` files into a single large bundle. We should investigate how we can improve this and ensure that only styles that we actually need are loaded onto the page.

My initial thoughts are that we should have a setup like this:
1. Define and bundle our global styles
2. Import component specific SCSS from the component file, ensure styles are only loaded when component is required

**Comment by felixfbecker** [comment]
This would be great to have.

Here are some complexities that need to be solved by a solution of this:
- Like you mentioned in the issue, there are global styles and component styles, which need to be separated. Global styles could be their own bundle and always be loaded, while the other styles could be lazy-loaded through Webpack code spliting/chunking the similarly to how our TSX uses code splitting.
- There is one more layer here though: There are global CSS declarations, and there are also global Sass variables or mixins which are referenced in component styles. So you may need to split the "global styles" into 2 parts - one part that contains only the Sass variables (which would not increase bundle size, since they're compile-time), and one part that imports the variables and Bootstrap, contains the global styles, etc. That first part can then also be imported by component stylesheets to get access to the variables (without bundle size increase).
  - You may also be able to avoid that import in many components by changing them to use CSS vars instead of Sass vars (but some things can only be done at compile time with Scss, not with CSS).
  - If any component uses `@extend`, that component could not be code split. But we try to avoid using that.

**Comment by umpox** [comment]
Closing, we now have this through CSS modules and lazy loading. We may want to revisit how we handle certain global styles in the future, as we've had certain issues with CSS ordering (e.g. Wildcard styles loaded after something else trying to override it, and then specificity issues)
