### ISSUE TITLE
frontend deployments missing CACHE_DIR

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1913]
The frontend service now writes to `/tmp/vfsutil-archive-cache` as part of the raw file API and Go symbols URL serving: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%408f35577+vfsutil%5C

`/tmp` can fill up causing the host node to die. We need to attach persistent SSD disks to resolve this.

1. Copy this CACHE_DIR code from the old xlang-go to frontend https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%402.13+vfsutil%5C.ArchiveCacheDir
2. Add a cache SSD to the frontend deployment, similar to the old xlang-go: https://github.com/sourcegraph/deploy-sourcegraph/commit/c01dfc624b8e8072c89e6c9ae4c5404d3368eb64#diff-0bf3b338b4830c41d40d583974a525f7L44
    - [ ] Update deploy-sourcegraph
    - [ ] Update deploy-sourcegraph-docker

**Comment by keegancsmith** [comment]
We discussed this more on slack. https://sourcegraph.slack.com/archives/C08JA8Q1H/p1547575543064700

Alternatively:
- A service for archives
- gitserver adds direct support for archives

**Comment by slimsag** [comment]
@keegancsmith want to take over this?

**Comment by keegancsmith** [comment]
I am going to implement the original idea in this issue since it is the most straightforward path forward. However, I do quite like the idea of gitserver having this functionality. It would digress from gitserver only doing git exec for a repo as its API (+ some clone management APIs). However, it would be better than the current code used by frontend, since we load balance across the frontend servers.

What are peoples thoughts on adding "native" archive support to gitserver? We use it all across our services so its likely gonna have a nice payoff. cc @nicksnyder @tsenart

**Comment by ggilmore** [comment]
Will https://github.com/sourcegraph/deploy-sourcegraph/pull/173 need to be reverted if move forward with adding archive support to gitserver?

**Comment by keegancsmith** [comment]
> Will [sourcegraph/deploy-sourcegraph#173](https://github.com/sourcegraph/deploy-sourcegraph/pull/173) need to be reverted if we move forward with adding archive support to gitserver?

Yes.

**Comment by keegancsmith** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/1995 about archives + gitserver. I'll close this issue once we have all attached issues closed and deployed to production.

**Comment by keegancsmith** [comment]
Deployed in production. https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/35ed75257b08aa6515c8bced8b3925d14eff4dc3
