### ISSUE TITLE
insights: historical enqueuer better debugging / observability facilities

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19195]
The historical enqueuer is a fairly complex algorithm to understand (see e.g. [this thread](https://github.com/sourcegraph/sourcegraph/issues/19089) where there is much confusion about "how it works" in general) and when something goes wrong with it (or even when nothing is going wrong with it), it can be hard to get a clear picture of:

* How much progress has it made?
* How much progress remains to be made?
* When might it finish?
* If it is having issues, why?

There exist [some metrics](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8d083e473df66a94283e296a3eab1e8bc4fd9308/-/blob/enterprise/internal/insights/background/historical_enqueuer.go#L60-68) but they are not really useful (just give an indication of "did it actually start running?")

We need to extend those metrics to include more detailed info about where the algorithm is at in its execution.

One challenge here is figuring out how to instrument that, exactly. Since it is effectively a deeply-nested loop:

```
for {
    for {
       for {
          ...
       }
    }
}
```

Which takes days or hours to complete, it's hard to identify a clear explanation for "how much more work remains?" because _we don't know_ (that's what the loop does.) We will need to brainstorm the best way to instrument this.

**Comment by coury-clark** [comment]
Relevant https://github.com/sourcegraph/sourcegraph/issues/23844

Leaving this issue open but with some context:
We have some instrumentation since this issue was opened to track the number of repositories analyzed `insights_historical_repositories_analyzed`. The more general scope of this issue is guaranteeing and tracking at-least once semantics across all repos while iterating over large cardinality over long periods of time.
