### ISSUE TITLE
dot-com and tooling k8s clusters are overprovisioned

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1922]
![image](https://user-images.githubusercontent.com/754768/51226155-fa364380-1902-11e9-973a-456f64f78bca.png)

Up to you if you want to manage this capacity manually or enable autoscaling on these clusters. Should we have autoscaling on all our clusters?If so, how do we decide how big nodes are?  Are there any downsides to autoscaling?

In any case, you should document your decisions somewhere.

**Comment by keegancsmith** [comment]
We should consult our grafana dashboards for resource usages. We could share those for other installations.

**Comment by ggilmore** [comment]
I don't think [GKE's autoscaler](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler) is that useful in this situation. 

- The autoscaler only takes resource _requests_, not limits, into account - so it won't help us with sudden bursts in workloads. 
- sourcegraph.com's deployment configuration isn't dynamic like our "ci" cluster. Our number of replicas for a given deployment, etc. is fixed unless some manually tunes the K8s manifest. 

The autoscaler could help us to avoid needing to manually edit a node pools size / provision a new pool (and cordon / drain the old one), but I feel like we should tune the cluster manually. (We should be aware of the resources that sourcegraph.com needs to run, and _not_ just let the autoscaler allocate new node silently in the background). 

After some finagling with the autoscaler for sourcegraph.com, it worked out that our current workload can run on three nodes: 
![screen shot 2019-01-16 at 12 50 57 pm](https://user-images.githubusercontent.com/9022011/51278632-fac8eb80-198f-11e9-9385-d99a7443a12d.png)

So, sourcegraph.com now runs on 3 nodes instead of 13. We can manually add more nodes in the future if necessary.

**Comment by nicksnyder** [comment]
Great, thanks for cleaning this up!

Before closing this issue it would be nice for you to document the current configuration of our dot-com cluster and the decisions that you made (not here in an issue, but somewhere in a markdown file that a new eng joining our team could discover). For example, documentation should provide answers to questions like:

1. If I am an engineer who wants to deploy a new service to production, what do I need to worry about?  How do I figure out if I need to increase our cluster capacity? How do I actually increase our cluster capacity if I need to do so? Auto-scaling seems like it would remove all these questions a dev might have.
2. How did we decide to have 3 nodes with 16 CPU and 60GB each instead of 6 nodes with 8 CPU and 30 GB each? Do we want to minimize/maximize the number of nodes?

> The amount of resources that sourcegraph.com requests isn't dynamic...Our number of replicas for a given deployment etc. is fixed unless someone manually tunes the deployment manifests.

Sounds like autoscaler can help us if/when we need to tune deployment replicas?

> After some finagling with the autoscaler for sourcegraph.com, it worked out that our current workload can run on three nodes (I disabled it again after it figured this out):

It sounds like the autoscaler helped you determine the right allocation of resources. When new services are added by different teammates, would it help them too? If so, why not leave it on all the time?

> The autoscaler could help us to avoid the manual labor of editing a node pool's size/provision a new pool (and cordon / drain the old one), but I think that we should be conscious of the resources that sourcegraph.com needs to run (don't just let the autoscaler silently allocate new nodes ).

I agree with both points (it can save us time and we should be conscious of resource allocation), but I would like to challenge the assumption that withholding the former is an effective way to encourage the latter. It seems unlikely that a dev would get to the point of deploying a service, realize that they need to manually add a new node to the cluster, and then go back to the drawing board to figure out how to make their service use less resources. The are just going to want to get their service deployed to prod as quickly and easily as possible at this point; which is probably the best outcome anyway if they want to optimize resource usage, because then they can profile the real service in production and optimize it from there.

**Comment by keegancsmith** [comment]
Additionally we need some extra capacity for rollouts. Hopefully we have that head room. My main concern with auto scaler would be scale downs. We have a lot of SPOFs unfortunately

**Comment by keegancsmith** [comment]
I believe @ggilmore fixed this and we have this follow-up issue now https://github.com/sourcegraph/sourcegraph/issues/1933
