### ISSUE TITLE
Enable case sensitivity by default in user settings

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#19232]
#### Feature request description

 Allow users to `Enable case sensitivity` by default in their settings config.

Users are frustrated by constantly clicking a filter option that they regularly use and want on by default. 

#### Describe alternatives you've considered.

N/A; user continues a click-heavy search pattern. 
#### Additional context

customer: https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001XicWuAAJ/view

**Comment by dadlerj** [comment]
Related—this sort of request has been around for a long time, but for different search preferences: https://github.com/sourcegraph/sourcegraph/issues/10621

Solving this via settings is useful, but the more general problem is still out there 

CC @rvantonder because you worked on the PR for this one

**Comment by rvantonder** [comment]
Thanks for linking @dadlerj. The case sensitivity option is an easy one-shot thing to accomplish and is analog to default pattern type. Looking forward search team having time to do this more comprehensively at some point :-)
