### ISSUE TITLE
type:repo behaves unpredictably

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#19239]
> Can someone explain why this search results in "too many results?" instead of starting with x number of repositories and displaying data?   I've seen this in quite a few sessions lately and users are always surprised.

- borked: [`search type:repo`](https://sourcegraph.com/search?q=context:global+search+type:repo&patternType=literal)
- works: [`repo:search`](https://sourcegraph.com/search?q=repo:search&patternType=literal)

Related to https://github.com/sourcegraph/sourcegraph/issues/15182, where issue was:

> Root Cause:
>
> repoSearch returns different results.
>
> Why does repoSearch return a different result?
> repoSearch matches the pattern against the resolved repositories coming from determineRepos, which returns a different list of repos for the two queries.
>
> Why does determineRepos return a different list?
> Because of the missing repo filter in sourcegraph type:repo we match the pattern sourcegraph against the list of default (indexed) Repos (200k). In the case of repo:sourcegraph, we match the pattern sourcegraph against the list of all repos (with a configured limit of 500k) in the db.

 PR https://github.com/sourcegraph/sourcegraph/pull/16904 that was supposed to help with this but it's not working.

@stefanhengl any objection to me rewriting `type:repo foo` queries to `repo:foo`? I'm still not sure _why_ these are different, is it only because one set is indexed, and the other not? By rewriting `type:repo`, we can interpret these two syntactic variants equivalently internally. In time, we'll have a single type for a repository query, there will be no syntactic distinguish between `type:repo foo`, `repo:foo`.

**Comment by stefanhengl** [comment]
We definitely regressed on that :-(. I have no objection rewriting `type:repo foo` to `repo:foo`. Those 2 queries do something slightly different in the backend, but they shouldn't.

**Comment by rvantonder** [comment]
sounds good, thanks!

**Comment by malomarrec** [comment]
Tagging similar issue in #20138 and https://github.com/sourcegraph/sourcegraph/issues/20141 to feed into prioritisation work.

**Comment by tsenart** [comment]
@rvantonder: I tried to use the `MapXXX` stuff to do this rewrite in response to https://sourcegraph.slack.com/archives/CHEKCRWKV/p1623335641272200, but I'm not sure how to do it properly.

How do we handle queries like `(type:repo foo) and (type:repo bar)`? What about `(type:repo foo) or (type:repo bar)`? I guess the latter we'd want to convert into `repo:foo|bar` and the first one into `repo:foo and repo:bar`. Would love to pair with you on it when you're back.

**Comment by camdencheek** [comment]
> I guess the latter we'd want to convert into repo:foo|bar

That's the eventual goal, but right now, we don't do many optimizations like that. Essentailly, for all `and`/`or` queries, we simplify them to the disjunctive normal form, then run each of the "basic queries" (the backend term for a query with no or statements) separately before merging the results. 

So, for `(type:repo foo) or (type:repo bar)`, we run `type:repo foo` and `type:repo bar` separately, then return the union of the results of each.

There is a lot of room for optimizations in the query processing pipeline. @rvantonder has done some great work on simplifying query processing recently (see #11101), but we've still got a lot of debt we need to pay down before some of these optimizations are possible. For example, we currently can't run `type:repo foo` and `type:repo bar` in parallel because running queries mutates shared state in the `searchResolver`.

**Comment by camdencheek** [comment]
Closing since the two repo queries now behave identically as far as I can tell. We've made a lot of changes here since this was opened, so it's likely this was fixed along the way.
