### ISSUE TITLE
SetExternalServiceRepos GraphQL query takes a long time

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#19235]
### Description 

`SetExternalServiceRepos` GraphQL queries take long time (~5s) on `dotcom` 😢 

### Screenshot

![Screen Shot 2021-03-17 at 6 22 51 PM](https://user-images.githubusercontent.com/1319181/111546400-0110a900-874e-11eb-91c9-06b5903a0cb7.png)

### Notes

`SetExternalServiceRepos` call(s) is made when the users select and save affiliated repositories in the `manage repositories` view. If the user has two external services / code hosts (GitHub and GitLab) we'll have to make two (parallelizable) ~5s calls to set repositories for each of the external services.

**Comment by tsenart** [comment]
@arussellsaw, @ryanslade: This one, I believe, takes long because it waits for repo-updater to list all repos in the external service config.

https://github.com/sourcegraph/sourcegraph/blob/7252febdda9cbccf5dd08780a30f0b4dc045b869/cmd/repo-updater/repoupdater/server.go#L346

That handler logic seems totally broken to me — why do we only validate the incoming request, but ignore it completely otherwise? We trigger the sync job, but we don't use the incoming request to enqueue any job in the database, so the caller also needs to do that. Why??

**Comment by arussellsaw** [comment]
hmm i don't have context on why that handler was written that way, but maybe the best option for us would be to remove the sync call altogether? we're already updating the next sync at, and have polling for the async job on the next page, we probably don't need the call at all
