### ISSUE TITLE
Improve button-styled-as-link accessibility in extension areas

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#19273]
## Issue
We render `<a>` tags with an `onClick` and empty `href` in some areas where we want to behaviour of a button but the styles of a link.

We should refactor these to be `<button>` tags that are styled as links.

### Known examples
1. [LinkOrButton.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/fix-a11y-lint-issues/-/blob/client/shared/src/components/LinkOrButton.tsx?utm_source=VSCode-1.2.4#L97)
2. [HoverOverlay.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/fix-a11y-lint-issues/-/blob/client/shared/src/hover/HoverOverlay.tsx?utm_source=VSCode-1.2.4#L262)

**Comment by felixfbecker** [comment]
I'd generally agree, but for HoverOverlay this is a bit tricky because code hosts likely don't have a `btn-link` class, we want to use their style for `<a>`. Could we just add `role="button"` in that case?

**Comment by umpox** [comment]
Yeah I thought we might have some issues with that. I think this is an OK exception to use `role="button"` for both of these examples, will close and `eslint-disable` for the a11y plugin here!

**Comment by felixfbecker** [comment]
SGTM. We can also utilize the independent `eslintrc.json` files in different folders, or its feature to override rules by file pattern, to tailor rules to areas that are shared with the browser extension or only in the webapp, so we train people to use `eslint-disable` everywhere. We are also more lenient in the browser extension in our CSS linting for example, because e.g. we can't enforce BEM for code hosts :)
