### ISSUE TITLE
Codecov Icicle insight causes `Cannot read property 'map' of undefined` page error

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#19280]
When enabling `codecov.insight.icicle` and looking at https://sourcegraph.com/github.com/sourcegraph/sourcegraph, the CodeCov API returns a 500 (not our fault), which results in the `ViewContent` component to fail with `TypeError: Cannot read property 'map' of undefined` (unusual because usually this stuff should be type safe).

Given this seems new and we've just seen a similar error, I'd guess this is another regression from the RFC155 refactor @tjkandala.
Do you know a solution to make this type-safe?

![image](https://user-images.githubusercontent.com/10532611/111676160-31c01380-881e-11eb-85ae-0a1c82e4bf7f.png)

![image](https://user-images.githubusercontent.com/10532611/111676369-5f0cc180-881e-11eb-90b9-b941308faee2.png)

It would also be good if we had an ErrorBoundary around the content side so the file tree still gets rendered.

**Comment by tjkandala** [comment]
I was able to reproduce this with a contrived error in a commit from before the RFC155 refactor, but that's to be expected since we don't validate our view types. Normal errors don't trigger this for me neither before nor after the refactor, but adding better/more error boundaries will help us figure out how make our view provider functions more type-safe.
![Screenshot from 2021-03-18 19-08-47](https://user-images.githubusercontent.com/37420160/111709152-8020e280-881d-11eb-84bf-50143a64b7d1.png)

**Comment by felixfbecker** [comment]
Hmm interesting. What do you mean with "contrived error" and "normal error"? How do they differ?

Could it be related to an error not being properly rehydrated coming from the extension host worker, and hence not passing `isErrorLike()`?
