### ISSUE TITLE
Inactive default action item icons are confusing

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#19338]
When an extension with no icon contributes an action item to `editor/title` in the webapp, we display a square with the first letter of the extension's name. Information about the action item is displayed in a tooltip.

When the action item is inactive, there's no way for a user to know what extension it is from and _why_ it is inactive.

![Screenshot from 2021-03-22 15-06-36](https://user-images.githubusercontent.com/37420160/112045501-4d2e6580-8b21-11eb-97ec-00b7012db63d.png)

**Comment by muratsu** [comment]
@Joelkw, what do you think is a good solution here?

**Comment by Joelkw** [comment]
@muratsu we can't pre-explain all the active/inactive conditions since that's developer defined, but what about still showing the tooltip with the extension name and a "(inactive)"? At least that way the user can go searching for reasons behind active/inactive (and has the name) rather than wonder why the extension looks broken.

**Comment by muratsu** [comment]
Agreed - quick fix with good uex. 👍
