### ISSUE TITLE
Sourcegraph.com should have some overhead / growing space + use more (less beefy) nodes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1933]
1. Maybe we can add some more overhead to our cluster, e.g. by adding 1 extra node in our current setup. This would give us a little extra CPU/RAM to make use of and hopefully Kubernetes would make use of this by spreading out our services a little bit more evenly thus allowing for our services to go above their `requests` a little.

2. We should use more (but less beefy) nodes. i.e., instead of 15 CPU / 60 GB RAM, let's use many more smaller nodes (~10 nodes total would be a good start), so that if a single node goes down it doesn't take down 1/3 of our services but instead takes down a much smaller fraction.

@ggilmore I am assigning you given your recent work in scaling our cluster, but if you want me to take this on instead just lmk. More context here: https://sourcegraph.slack.com/archives/C08JA8Q1H/p1547687343101900

**Comment by ggilmore** [comment]
Update:

The current hypothesis for what happened is that GKE's autoscaler will **not move pods that use local node storage**. Many of our deployments (lang-go, typescript, searcher, gitserver, etc.) use local disks for caching. 

So, the cluster  put a lot of pods on node 1 and it filled up. Then, the autoscaler  added a new node, but then it couldn't move pods off node 1 because of the local storage issue metioned above, then the 2nd node behaved the same until we got to the 3rd node which didn't fill up.

This left the cluster with 2 nodes with very little overhead, and one node with a lot of overhead. When one of the pods on the filled up nodes used a large amount of memory, it caused all of the pods that node to die (> 1/3 of our services), which caused sourcegraph.com to go down. 

Takeaways:

1. This will happen every time that we use GKE's autoscaler because many of our deployments use local caching. We shouldn't use the autoscaler. 
2. We still have a problem with only having 3 nodes, OOM is just one reason the node may go down. Other reasons such as google just having a blip still means 1/3 of our services die which is bad.
3. If we recreate the cluster with extra room for overhead (and start out with e.g. 4-5 of our current-size nodes) it would solve our scheduling issue
4. This issue would have been largely avoided if our deployment's requested resources were more accurate (k8s would have been forced to spread them out more evenly)

I'll create a new node pool with more nodes so that our services are evenly spread out. I also think that we should look into using https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling#getting_resource_recommendations so that K8s can give us recommendations for what our resource requests _should_ be.

**Comment by nicksnyder** [comment]
Great analysis and plan for resolving this issue!

It is ok to overprovision from our current state. I believe our current setup is using roughly 50% of what we were using before, which is a great improvement. We also have a committed use discount until September which was based on our old baseline, so in the short term over provisioning is "free" (aka pre-paid).

**Comment by ggilmore** [comment]
sourcegraph.com currently is running on 6 nodes and is using ~57% memory utilization and 65% CPU utilization. I've adjusted some of the deployments' usage requests in https://github.com/sourcegraph/sourcegraph/issues/1958#issuecomment-456553817 and filed https://github.com/sourcegraph/sourcegraph/issues/1986 to create a metric/dashboard to detect when sourcegraph.com's deployments are starved for resources.
