### ISSUE TITLE
Management console URL should link to the management console not the doc page

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1934]
It's really hard as a first time user to navigate to the management console. The below closely resembles the first time I tried to access it.

![screenflow](https://user-images.githubusercontent.com/133014/51289259-51e0b780-19b4-11e9-81ce-c419d319db49.gif)

I would propose that we link to what the management console URL is likely to be (host:2633) and add a (?) help element, the contents of which could be:
 - Mentions the username can be anything
 - Mentions to copy the management console password 
 - Links to the docs

One of my on-boarding videos will include using the management console to set the external url and it would a lot nicer if I could just click a link to be taken there.

**Comment by slimsag** [comment]
Agreed. We talked about this earlier on a call and I forgot to file this, thanks! Notes about implementation:

- I am not sure if we can detect if the management console exists at `https://same-url:2633` due to the invalid certificate that must be accepted by the user. I need to look into this.
- If we can detect that, we can either link to the docs OR that URL depending on whether or not it is reachable.
- If we cannot detect that, we need to figure out how to communicate that the link may not work (e.g. in Kubernetes and other cluster environments, it will not).

**Comment by ryan-blunden** [comment]
Points one and two I'd say are optimal but not required for 3.0. Always linking to the management console for 3.0 with a help link to the docs would I think, produce a better user experience and would be a quick temporary solution.

**Comment by slimsag** [comment]
@keegancsmith Today you can:

1. Change something in management console
2. Site is broken
3. Undo your change in management console

Versus if we did that:

1. Change something via app
2. Site is broken
3. You don't know how to undo your change (because the thing you set it through is now broken)
4. Hopefully you find docs and realize management console is the escape hatch

**Comment by ryan-blunden** [comment]
Does "Site is broken" refer to just  the Sourcegraph front-end? If so and presuming nginx is acting as a reverse proxy, could we route traffic to the management console that way?

**Comment by keegancsmith** [comment]
nginx would work, just need to check if it can do TCP proxying since management console does its own TLS.

**Comment by slimsag** [comment]
Tagging for 3.1. This would be a major improvement, but not a 3.0 release blocker and I won't have time to complete it for that.

**Comment by slimsag** [comment]
I think the consensus here is to:

1. [ ] Link to `https://same-url:2633` in hopes that it works, but also link to the docs in case it doesn't.
2. [ ] TCP proxy via nginx the management console, so that it is always exposed to the public internet, even in cluster setups.

I will try to tackle #1 above before 3.1 is shipped, and defer #2 above to 3.2.

**Comment by slimsag** [comment]
I didn't get to this in time, but I did determine that #3 is not possible as the browser cannot tell us anything aside from "connection error" basically, which includes when the management console is accessible but is using its self-signed certificate. So in order to do #3 it would be more complex (server-side logic to determine if the public URL is accessible)

**Comment by slimsag** [comment]
I am backlogging to indicate I do not have time for fixing this. If important, we will need to assign someone else.
