### ISSUE TITLE
Let users specify a fallback / default branch in the editor-to-Sourcegraph extensions

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#19400]
When working on a local branch, users may not be able to map 1:1 onto Sourcegraph (which doesn't have their local branch) so we should let them set a default fallback branch so that the editor-to-Sourcegraph connection works smoothly for them. 

Full thread: https://sourcegraph.slack.com/archives/C015JREMBTR/p1615396498016700

**Comment by tjkandala** [comment]
Hey @Joelkw, we've had the ability to set a default branch since sourcegraph/sourcegraph-vscode#164, but not the ability to set a _fallback_ branch. The default branch is always used, even if there is potentially a remote branch.

I think customers are satisfied based on [this comment], so I wanted to know whether we should pursue the full feature or consider this to be done

**Comment by Joelkw** [comment]
@tjkandala yep, I agree. Thanks for checking!
