### ISSUE TITLE
Ability to add annotations to sign in buttons

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1944]
#### Feature request description

It would be nice to add annotations to the sign in buttons. Example: "Sign in with OpenID" -> "Sign in with OpenID (Google Auth)"

#### Is your feature request related to a problem? If so, please describe.

It's easy to imagine a scenario where only the admin of an organization knows that their auth provider is an implementation of a specification (ex: Google is a provider for OpenID connect). It would be nice if the admin could add some info to the buttons so that they know which one to use to log in.

**Comment by sqs** [comment]
This exists. If you set the auth provider's displayName property (https://docs.sourcegraph.com/admin/site_config/all#displayname), it will be shown.

![image](https://user-images.githubusercontent.com/1976/52206708-5e518500-287b-11e9-98b1-aa9e39776ec6.png)

However, it would be nicer to be slightly smarter about auto-generating these names in common cases. Low priority because use of 2+ auth providers is much less common than use of 1 auth provider (in which case you don't even see these choices).

**Comment by keegancsmith** [comment]
Given this exists and having more than 1 auth provider is unlikely, just gonna close this out.
