### ISSUE TITLE
SQL: Listing user repos is slow

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#19561]
We're seeing listing of user repos taking multiple seconds on sourcegraph.com

<img width="999" alt="Screenshot 2021-03-30 at 14 51 29" src="https://user-images.githubusercontent.com/25610/112991502-7aa19180-9167-11eb-855c-4e32ab567bb7.png">

**Comment by ryanslade** [comment]
It looks like trying to find user repos is slow again:

```sql
SELECT repo_id as id
FROM external_service_repos esr
         JOIN external_services es ON esr.external_service_id = es.id
WHERE es.namespace_user_id = 12832 AND es.deleted_at IS NULL


Gather  (cost=1006.56..91576.57 rows=219682 width=4) (actual time=540.131..559.579 rows=1 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Hash Join  (cost=6.56..68608.37 rows=91534 width=4) (actual time=534.850..534.853 rows=0 loops=3)
        Hash Cond: (esr.external_service_id = es.id)
        ->  Parallel Index Only Scan using external_service_repos_idx on external_service_repos esr  (cost=0.43..63181.71 rows=1967981 width=12) (actual time=0.061..358.827 rows=1563854 loops=3)
              Heap Fetches: 155105
        ->  Hash  (cost=6.08..6.08 rows=4 width=8) (actual time=0.107..0.108 rows=1 loops=3)
              Buckets: 1024  Batches: 1  Memory Usage: 9kB
              ->  Seq Scan on external_services es  (cost=0.00..6.08 rows=4 width=8) (actual time=0.066..0.099 rows=1 loops=3)
                    Filter: ((deleted_at IS NULL) AND (namespace_user_id = 12832))
                    Rows Removed by Filter: 88
Planning Time: 0.211 ms
Execution Time: 559.614 ms
```

How can we force Postgres to get the list of service ids first and then simply filter by those? Conceptually, something like this

```sql
with my_services as (
    select id from external_services
    where namespace_user_id = 12832
      and deleted_at is null
)
select repo_id from external_service_repos
where external_service_id in (select id from my_services);

(This is also slow)
```

But, it *can* be fast if it knows the ids up front, for example:

```sql
select repo_id from external_service_repos
where external_service_id in (88);


Index Only Scan using external_service_repos_idx on external_service_repos  (cost=0.43..8.54 rows=275 width=4) (actual time=0.015..0.016 rows=1 loops=1)
  Index Cond: (external_service_id = 88)
  Heap Fetches: 1
Planning Time: 0.060 ms
Execution Time: 0.027 ms
```

How can we close the gap? I've tried to return the service ids as an array but I'm getting a cast error. I'm trying this:

```sql
select repo_id from external_service_repos
where external_service_id = ANY (
    select array_agg(id)
    from external_services
    where namespace_user_id = 12832
    );
```

But I get this error:
```
[42883] ERROR: operator does not exist: bigint = bigint[]
Hint: No operator matches the given name and argument types. You might need to add explicit type 
```

cc @tsenart

**Comment by tsenart** [comment]
Thanks @ryanslade. My observations match yours. The larger problem is the statistics Postgres is keeping for these tables are largely inaccurate, so the query planner often chooses the wrong plan. Today I haven't had time to look at this deeply, but I have 1h scheduled with Felix tomorrow at noon.

**Comment by tsenart** [comment]
###  Update

- We have a pathological schema design.
- Postgres plans a query ahead of time, before execution.
- It keeps statistics about the distribution of data on each column of a table (and indexes) via the background `VACUUM ANALYZE` that autovacuum runs on all tables.
- The distribution of values of `external_service_id` in `external_service_repos` is highly non-uniform because most rows belong to the `cloud_default = TRUE` external services.
- At planning time, Postgres doesn't know which external_service_ids will be selected because we're doing that in query via the namespace_user_id predicate.
- So Postgres often chooses a plan for the most common and likely case (according to its statistics) which is a `cloud_default` external service.

We have a few actions from this understanding:
1. **Quick fix**: Split the query into a stored procedure (or application code) that does this in two steps: first load the external service ids, then load the repos from those. This fixes the immediate problem, but I'm concerned we just leave ourselves open to more slow queries in the future, given this pathological schema design.
2. **Better fix**: Change the schema design to not require joining with external_services to select their ids.
We could denormalize a bit and add namespace_user_id and namespace_org_id columns to external_service_repos.

**Comment by tsenart** [comment]
I went ahead and implemented the Better fix. See #19615.

**Comment by ryanslade** [comment]
Nice!
