### ISSUE TITLE
Read replica of Sourcegraph Cloud Postgres tables in BigQuery 

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#19799]
Right now we can query Postgres tables in BigQuery using EXTERNAL_QUERY but it's hard to create queries. 

I'm interested in a couple use cases for this: the licenses table to include that data in Salesforce for the sales and CE teams, and I'm a lot of private code and public code dashboards could live on top of these tables.

For now, I'm just interested in how difficult this solution is to implement. In terms of urgency, I'll need the tables in BigQuery by the end of April at the latest so I can start building out the dashboards, but depending on the complexity of this potential solution I can find alternatives if needed.

**Comment by daxmc99** [comment]
I think the level of effort for the read replica is low but I'm not sure how to get this data INTO BigQuery.

**Comment by daxmc99** [comment]
@ebrodymoore We can setup the read replica and point BigQuery at it. Could you pull the data from that into a bigquery table?

**Comment by ebrodymoore** [comment]
GDI I don't know why I didn't think of this before but I could actually use EXTERNAL_QUERY and just use that to copy the entire table over to BigQuery. 

Looks like I started getting errors on EXTERNAL_QUERY starting two days ago (@andreeleuterio could be the update you made). Could I (or the gcp_analytics group) get this permission again?

`Access Denied: Connection sourcegraph-dev.us.sg-cloud: User does not have bigquery.connections.use permission for connection sourcegraph-dev.us.sg-cloud`

**Comment by andreeleuterio** [comment]
It likely is on me but I don't have permissions to determine 100%. I just added a `BigQuery Connection User` role to `sourcegraph-dev@appspot.gserviceaccount.com` on the sourcegraph-dev project. @ebrodymoore can you try the query again?

What's weird is that my changes were to the `sg-production-backend-logging@telligentsourcegraph.iam.gserviceaccount.com` service account credentials on the `telligentsourcegraph` project. @daxmc99 do you have permissions on GCP to view IAM policies for `sg-production-backend-logging@telligentsourcegraph.iam.gserviceaccount.com`?

**Comment by davejrt** [comment]
FYI, I have temporarily added the gcp-analytics account to sourcegraph-dev with bigquery admin and connection editor permissions

**Comment by davejrt** [comment]
I've created scheduled queries, that grabs all the data from the following tables once per day. Unfortunately we can't create these with terraform, so they need to be manually managed for the time being. 
```
public.event_logs
public.external_service_repos
public.external_services
public.feature_flags
public.repo
public.user_emails
public.user_external_accounts
public.users
user_public_repos
public.lsif_indexes
public.lsif_uploads
```

**Comment by daxmc99** [comment]
Reopening on revert

**Comment by daxmc99** [comment]
We should document what scheduled queries we created so that the analytics team can ensure those are working correctly. 

Let's wait to close this until the analytics team confirms they have the data they need in those scheduled queries 

cc @attfarhan

**Comment by attfarhan** [comment]
From an analytics perspective, yes, what we have set up currently does work. We are able to run queries and collect the Sourcegraph Cloud data that we need. However, I don't really understand the mechanics and what has changed, since the conversation has jumped around a bit over time, and would like to understand. @davejrt could you help answer the questions below? If there are others I should speak to, let me know, or if it would be easier to jump on a call, happy to do that as well.

My understanding is that Dave is creating read-only replicas of the Sourcegraph Cloud production database. This prevents an additional service account from having unfettered access to our database.  However, Dax told me that the changes to create this read-only replica was not applied. However, I also know that our old scheduled queries stopped working because whatever service account we were using previously no longer has access to the prod database. I also learned that there were new scheduled queries made to replace the old ones, so some permissions were changed.

I would like to understand:
1. What were the changes made to our BigQuery permissions setup, and what did those changes intend to achieve? 
	1. Specifically, which service account previously had access to the Prod DB? Is this account still in use but with different permissions, or is it gone altogether? If you could walk me through how this is set up (if this is private/contains sensitive info, feel free to send me a message on Slack or elsewhere)
	2. Does the change affect whether BigQuery has access to the prod database at all, or does it only affect whether BigQuery can run queries with the  `external_query` function?
2. I understand that we have new scheduled queries to replace the old ones. The queries are copy-pasted, not changing any functionality. What's the difference between the old and new scheduled queries, and how are these new ones running successfully while the old ones? Do they use a different service account, or are they reading from something that is not the production database?
3. Do these changes attempt to prevent us from pulling private Cloud data at all? To my knowledge, this doesn't, since we still have access to all the tables in the prod database, so we would have to ensure in the scheduled queries that we don't pull private information. Would like confirmation on this, though. 

Thanks!
