### ISSUE TITLE
disableAutoGitUpdates disables all updates instead of just scheduled updates

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1982]
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/repo-updater/repo-updater.Deployment.yaml#L38-L39 sets it to `0` but the proper value would be `-1`.

Also we should not be setting it via environment var as that is no longer respected, we need to set in site config. The fix here should be:

1. [ ] Update the site config to ensure repo updater is off
2. [ ] Remove the env var from the deployment, verify it is also not in deploy-sourcegraph. (https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/214)

**Comment by nicksnyder** [comment]
I think the correct fix is `"disableAutoGitUpdates": "true"`

**Comment by nicksnyder** [comment]
I enabled `"disableAutoGitUpdates": "true"` on sourcegraph.com and discovered a few undesirable behaviors:
1. It disables all updates, not just scheduled updates (bug)
2. The schedule metadata doesn't get cleared out, which makes it seem like auto updates are still scheduled when they aren't.
3. If you configure disableAutoGitUpdates back to `false` then the schedule doesn't correctly re-populate because `updateSource` is stateful, that state isn't cleared when updates are disabled.

I reverted sourcegraph.com back to `"disableAutoGitUpdates": "true"` when I found (1).

cc @tsenart This is closely related to the code you will be working on so I would love to hand off this task to you, and I can give you any additional context that you need.

**Comment by slimsag** [comment]
@nicksnyder How do you know setting that prevented all updates? Looking at the code, I don't see how it would be possible for `disableAutoGitUpdates` to prevent all updates, the logic looks pretty sound to me end-to-end.

**Comment by slimsag** [comment]
If `disableAutoGitUpdates` really is broken, I consider this a release-blocker, since we have multiple customers relying on this I think.

**Comment by tsenart** [comment]
OK, I'm prioritising this over https://github.com/sourcegraph/sourcegraph/issues/1856 now since it's release blocker.

**Comment by nicksnyder** [comment]
Tomas and I chatted about this today. The release blocking behavior is exactly this:
> It disables all updates, not just scheduled updates (bug)

Looking at [the code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repos/reposlist.go#L733:29) you can see that the entire context is canceled, which impacts both scheduled updates as well as on demand updates (since they both go through the same queue). Tomas has the relevant context to fix this.
