### ISSUE TITLE
Possible silent failure: code monitors using personal contexts or repos that are removed

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19836]
## Problem

If a user has added their own repositories via a code host connection, then creates a code monitor with a query that targets those repos or their personal context, and then subsequently removes their code host connection (or repos, when private repos are available), the code monitor may not longer work. In the future, we have a plan for making code monitor events observable, but right now, this may be a silent failure mode for code monitors that could damage trust.

## Next steps

First, we should validate whether this can lead to silent failures in code monitors. Then, we can figure out how we can better surface the error before we have "events" for code monitoring.

**Comment by novoselrok** [comment]
I'm not sure this is a problem at this point because we require a `repo:` filter to explicitly state the repositories in a valid code monitor query. Using `context:` filter and `repo:` filter together doesn't make much sense, since you're then targeting the intersection of the repositories returned by both filters (hard to reason about).

**Comment by ryanslade** [comment]
It sounds like this isn't an issue, @novoselrok shall we close this?

**Comment by novoselrok** [comment]
@ryanslade Yep, not an issue right now.
