### ISSUE TITLE
Currently selected context can't be changed when query is empty

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19834]
## Problem

A user was observed being unable to change the currently selected context using the contexts selector.

[Starting at 6:20 in the session recording](https://drive.google.com/file/d/1ttBaGWResdMSJWkX7zIxJyqGqxoOKs-F/view).

## Expected behaviour

User is always able to change the currently selected context in the contexts selector.

**Comment by novoselrok** [comment]
The problem is that we prevent submitting the search when changing the search context if the query is empty. This was done to prevent submitting a search if you were switching search contexts on the search index page.

I'll fix this by not relying on the query, and instead always submit the search when switching the search context in navbar, and never submitting the search when switching on the index page.
