### ISSUE TITLE
code insights: hovering over panels in Firefox causes vertical line & hover tooltip to be displayed in unrelated insights

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#20098]
I noticed that when I hover over insights in Firefox, like `Commits with revert` the vertical line displays in an unrelated insight:

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/3173176/115074461-94084480-9eae-11eb-96fa-0820ff855c4b.png">

Another example where my mouse is hovering over "Team size" and the vertical line is correct, but the hover tooltip is in the chart below it:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/3173176/115074573-bd28d500-9eae-11eb-9246-57575a31b000.png">

**Comment by vovakulikov** [comment]
@felixfbecker It seems like a firefox bug of `svg.getScreenCMT()` 
https://bugzilla.mozilla.org/show_bug.cgi?id=1610093

Since @visx/xychart tooltip uses this svg API to calculate tooltip position we have to repeat this math by ourselves probably.

**Comment by vovakulikov** [comment]
Related to https://github.com/airbnb/visx/issues/1174

**Comment by vovakulikov** [comment]
For now as a workaround we can use `useCSSTransforms={false}` at `react-grid-layout` component just to avoid this Firefox bug with `svg.getScreenCMT()`. But my concern here css transform much faster because we use separate composite layout with css transformation rather then trigger reflow with `position:absolute `and changing `top/left` values on grid element. 

From react-grid-layout codebase 
```tsx
/**
 * Uses CSS3 `translate()` instead of position top/left.
 * This makes about 6x faster paint performance.
 */
useCSSTransforms?: boolean;
```

**Comment by felixfbecker** [comment]
@vovakulikov I think we should add that asap, so that we don't ship broken charts in the release on the 20th. If we run into perf problems, we can look at implementing some kind of polyfill maybe for `getScreenCTM()`, but from my testing perf wasn't noticeably worse and that is probably more involved.
