### ISSUE TITLE
v3.23.0-rc.3: error in syncExternalService for service "GITHUB" with ID 1: request to http://127.0.0.1:3180/user returned status 403: API rate limit exceeded

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#20156]
Part of #19746 

See https://buildkite.com/sourcegraph/code-intel-qa/builds/2040#6d4e05ee-aae5-410a-b166-d4bbe1d90157/55-1151

for commit https://github.com/sourcegraph/sourcegraph/releases/tag/v3.27.0-rc.3

```
sourcegraph-code-intel-test: 2021/04/19 18:53:10 External service created, but we encountered a problem while validating the external service: error in syncExternalService for service "GITHUB" with ID 1: request to http://127.0.0.1:3180/user returned status 403: API rate limit exceeded for user ID ....
```

**Comment by sourcegraph-buildkite** [comment]
This seems to be a legit error, and not related to any tokens.

**Comment by ggilmore** [comment]
resolved in https://sourcegraph.slack.com/archives/CJX299FGE/p1618858872102800

**Comment by codeanit** [comment]
> resolved in https://sourcegraph.slack.com/archives/CJX299FGE/p1618858872102800

@ggilmore  slack link requires login and i believe that is invites only. I was facing the similar issue while trying to sync a local repo and had similar problem. Could past the solution here?

I am running the Sourcegraph in Docker.

I created a git repo from Generic Git Host option.
![image](https://user-images.githubusercontent.com/414141/115688301-c3212900-a37a-11eb-8ac8-0153a409e89e.png)

Added the configuration option as provided by src-expose log. Error message below:
```
Syncing repositories from external service "Git repositories" failed:
fetching from code host Git repositories: 1 error occurred:
	* Get "https://192.168.1.86:3434/v1/list-repos": dial tcp 192.168.1.86:3434: i/o timeout
```

I choose this option because I could not create a repo like "Go to Admin > Manage Repositories > Add repositories > Single Git repositories" mentioned at https://docs.sourcegraph.com/admin/external_service/non-git

Thanks.
