### ISSUE TITLE
Notices need alert-link class to make links clear

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20152]
Alert links do not appear as links in notices:

![image](https://user-images.githubusercontent.com/539268/115280851-3cabe380-a0fd-11eb-8b48-4e8b940d92bc.png)

Adding the alert-link class to the anchor tag seems to fix the issue:

![image](https://user-images.githubusercontent.com/539268/115281021-695ffb00-a0fd-11eb-9a1c-7084adb8a290.png)

This could be completed for all  global-alerts__alert tags at a minimum.

**Comment by rrhyne** [comment]
@felixfbecker has more information!

**Comment by 5h1rU** [comment]
@rrhyne The `alert-link` class is generated by bootstrap. Unfortunately, we can't add classes to those links since an external service generates them. The markup is passing to react as inner HTML.

I can add styles for the `<Markdown/>` component easily. The only problem is the color for `alert-link` is not part of our palette. 
Do you have any color alternatives, or do you prefer to add the color to the palette?

**Comment by rrhyne** [comment]
@5h1rU LMK if Felix's solution doesn't apply the proper colors var(--web-content-link-color) should work well there.
