### ISSUE TITLE
Diff content being modified/stripped in streaming search misses highlighting and causes confusion

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#20285]
I was working on some diff highlighting and results things and came across a nasty regression in diff highlighting/results.

The `.*` substrings in the results below don't highlight when they should. Neither with a regex or literal pattern, so the problem isn't there:

[`repo:^github\.com/sourcegraph/sourcegraph$ type:diff \.\* select:commit message:repo:contains`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:diff+.*+select:commit+message:repo:contains&patternType=literal)

[`repo:^github\.com/sourcegraph/sourcegraph$ type:diff .* select:commit message:repo:contains`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:diff+.*+select:commit+message:repo:contains&patternType=literal)

<img width="928" alt="Screen Shot 2021-04-21 at 6 03 35 PM" src="https://user-images.githubusercontent.com/888624/115640897-d4136100-a2cc-11eb-914b-1bbf5efb99d7.png">

## Turn off streaming, and the highlighting returns `     "searchStreaming": false` and we see this:

<img width="908" alt="Screen Shot 2021-04-21 at 6 10 36 PM" src="https://user-images.githubusercontent.com/888624/115640919-e42b4080-a2cc-11eb-8ff5-577fe6a509cc.png">

Note the difference in the _content_: the `<params>` part of `P<params>` in the diff content is being stripped when streaming search is enabled . This causes the highlighting to not happen. It also caused me to try and search for the pattern `P\.\*` which doesn't have results, but I thought it would since the first case _renders_ a `P\.\*`. So potentially users could search for a string, in this case `<params>`, and we find it in the backend, but do not render it in the view:

[`repo:^github\.com/sourcegraph/sourcegraph$ type:diff <params> select:commit message:repo:contains`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:diff+%3Cparams%3E+select:commit+message:repo:contains&patternType=regexp)

<img width="999" alt="Screen Shot 2021-04-21 at 6 17 58 PM" src="https://user-images.githubusercontent.com/888624/115641435-f35ebe00-a2cd-11eb-9242-9764b26b9381.png">

**Comment by keegancsmith** [comment]
This is weird. If you search without `message:repo:contains` it works. However, the results above also include Camdens commits, and they aren't highlighted. Notice in the screenshot below that `.*` is highlighted in two of the results:

![image](https://user-images.githubusercontent.com/187831/115689373-4e3ef680-a35c-11eb-8abe-e7b2a7ac8892.png)

Looking at the response from the streaming backend, it is including highlight ranges. So I am assuming this is an issue in something the frontend is doing? For brevity I'll include an example response which isn't being highlighted:

```json
[
  {
    "type": "commit",
    "label": "[sourcegraph/sourcegraph](/github.com/sourcegraph/sourcegraph) › [Camden Cheek](/github.com/sourcegraph/sourcegraph/-/commit/52cb24e14ad432cc8756b31b34b2aba31176e3d4): [Add repo:contains.commit.after() predicate (#19663)](/github.com/sourcegraph/sourcegraph/-/commit/52cb24e14ad432cc8756b31b34b2aba31176e3d4)",
    "url": "/github.com/sourcegraph/sourcegraph/-/commit/52cb24e14ad432cc8756b31b34b2aba31176e3d4",
    "detail": "[`52cb24e` 17 days ago](/github.com/sourcegraph/sourcegraph/-/commit/52cb24e14ad432cc8756b31b34b2aba31176e3d4)",
    "content": "```diff\na/internal/search/query/predicate.go b/internal/search/query/predicate.go\n@@ -52,3 +51,3 @@ func (pr predicateRegistry) Get(field, name string) Predicate {\n var (\n-\tpredicateRegexp = regexp.MustCompile(`^(?P<name>[a-z]+)\\((?P<params>.*)\\)$`)\n+\tpredicateRegexp = regexp.MustCompile(`^(?P<name>[a-z\\.]+)\\((?P<params>.*)\\)$`)\n \tnameIndex       = predicateRegexp.SubexpIndex(\"name\")\n```",
    "ranges": [
      [
        4,
        70,
        2
      ],
      [
        5,
        72,
        2
      ]
    ]
  }
]
```

I am gonna unassign myself and stefan since I believe this is a webapp issue. However, happy to pick it up if @limitedmage doesn't have any bandwidth. (I'd appreciate a quick look at it though to see if I am on the right track).

**Comment by rvantonder** [comment]
I think your assessment is accurate @keegancsmith. 

>  Notice in the screenshot below that .* is highlighted in two of the results:

Yes, I believe that because the `<params>` part is deleted from the first result, the highlight ranges returned are correct, but they misalign with the content being rendered (and so, no highlighting appears). 

@limitedmage I had a brief look at https://github.com/sourcegraph/sourcegraph/pull/18707 again and I think the sanitize call is stripping the diff contents too aggressively: https://github.com/sourcegraph/sourcegraph/pull/18707/files#diff-b0339a9e869ad3191470fee495b608d10f9d10810d9aef71025ede378efdfa32R60-R63

**Comment by limitedmage** [comment]
@rvantonder You're right that this is because of the HTML sanitizer stripping out things that look like HTML tags. This is gnarly and it will be hard to fix unless we also deprecate GraphQL search (otherwise we have to do a lot of extra work to make sure GraphQL search still works OK and is secure, since GraphQL search returns diff/commit results as HTML). 

Because of the brittleness of this code, the difficulty in supporting both types of search, and the security implications, I recommend punting this until GraphQL search is deprecated in the webapp. 

@keegancsmith  At that point, we can consider modifying the streaming search API to return body as a plain string instead of a markdown string and return the type (diff or commit) to use of syntax highlighting. This would simplify this flow a lot because right now we depend on markdown \``` diff or ```COMMIT_MSG starting line to know if it's diff or commit.

**Comment by keegancsmith** [comment]
> @keegancsmith At that point, we can consider modifying the streaming search API to return body as a plain string instead of a markdown string and return the type (diff or commit) to use of syntax highlighting. This would simplify this flow a lot because right now we depend on markdown ``` diff or ```COMMIT_MSG starting line to know if it's diff or commit.

Yes will certainly do this. We only had the old format because that is what GraphQL supported => was easier to support in the webapp.

**Comment by limitedmage** [comment]
@camdencheek  @slimsag  Could this be a bug in the syntax highlighting library that could be fixed by the library returning HTML entities like `&lt;` instead of `<` ?

**Comment by camdencheek** [comment]
@limitedmage It definitely seems possible. I haven't taken the time to fully grok where the escaping issue is happening here, but I fixed something similar in https://github.com/sourcegraph/sourcegraph/issues/20537. (not escaping internal HTML special chars in some cases). 

My plate is a bit full right now, but I'd be happy to dig in to this sometime next week

**Comment by felixfbecker** [comment]
On a high level, if the web app expects a string to be _HTML_ (or in a perfectly documented world, the field in the API is documented to be HTML), then the producing code should ensure that whatever code is embedded into that HTML should have any HTML entities escaped like @limitedmage described (`<` -> `&lt;` etc).

If the web app expects a string to be _markdown_, the same thing applies outside of code blocks, as markdown supports embedded HTML.
If however what the backend returns is just a markdown string containing a codeblock like:

    ```diff
    + <foo>
    - <bar>
    ```
It wouldn't need to be escaped afaik because it is inside a code block, and the whole point of a code block in markdown (compared to HTML `<code>`) is that nothing needs to be escaped (so the file remains human-readable). So if the backend is returning a code block, and the frontend interprets the HTML inside the code block as HTML, it would indeed be a bug in the web app and returning escaped entities inside the code block from the backend would actually be wrong (show the entities literally to the user assuming a well-behaving frontend).

**Comment by limitedmage** [comment]
Thanks @felixfbecker, I've removed the escaping as part of #22024. Everything seems to work OK with no need for HTML entities.
![image](https://user-images.githubusercontent.com/206864/121939435-e1affa80-cd01-11eb-879d-487f1c5aee99.png)
