### ISSUE TITLE
Basic code intel shows hover from a different language

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2029]
![image](https://user-images.githubusercontent.com/10532611/51734211-229d0b00-2084-11e9-917f-38ee43708986.png)

The file is a `.graphql` file, but basic-code-intel shows a hover from a definition in a `.go` file. It should only search for definitions in files of the same language.

**Comment by chrismwendt** [comment]
This will be fixed by #2035

**Comment by felixfbecker** [comment]
Are you sure? I think this requires a code change to search the definition in the same language

**Comment by chrismwendt** [comment]
I can clarify a bit if my previous comment was confusing (let me know why).

Currently, when you hover over `Settings`, basic-code-intel runs a Sourcegraph search that looks like `repo:... Settings type:symbol`. For this example, here's how the query needs to change in order to filter the results:

```diff
-repo:... Settings type:symbol
-repo:... Settings type:symbol lang:graphql
```

We'll need a way to determine the language of the current file in general.

**Comment by chrismwendt** [comment]
Fixed by splitting the single `sourcegraph/basic-code-intel` extension into an extension per language.
