### ISSUE TITLE
repo filter with regexp `(...|...)` doesn't works as intended

### ISSUE THREAD

**Issue by apstndb** [sourcegraph/sourcegraph#20389]
`repo:` filter with `(a|abc)$` doesn't matches the repo names with `abc$`.

- **Sourcegraph version:** 

Both of sourcegraph.com and v3.26.0 private instance.

#### Steps to reproduce:

```
$ src search 'repo:github\.com/sourcegraph/(sourcegraph|sourcegraph-sonarqube)$' | cat
✱ 1 results for "repo:github\.com/sourcegraph/(sourcegraph|sourcegraph-sonarqube)$" in 3ms
github.com/sourcegraph/sourcegraph (https://sourcegraph.com/github.com/sourcegraph/sourcegraph)
```

Filter without `(...|...)` works as intended.

```
$ src search 'repo:github\.com/sourcegraph/sourcegraph-sonarqube$ OR repo:github\.com/sourcegraph/sourcegraph$' | cat
✱ 2 results for "repo:github\.com/sourcegraph/sourcegraph-sonarqube$ OR repo:github\.com/sourcegraph/sourcegraph$" in 18ms
github.com/sourcegraph/sourcegraph           (https://sourcegraph.com/github.com/sourcegraph/sourcegraph)
github.com/sourcegraph/sourcegraph-sonarqube (https://sourcegraph.com/github.com/sourcegraph/sourcegraph-sonarqube)
```

#### Expected behavior:

`repo:` filters contains `(a|abc)$` should match repo names end with the either of `a` or `abc`.

For example,
`repo:github\.com/sourcegraph/(sourcegraph|sourcegraph-sonarqube)$` should hit the both of
* `github.com/sourcegraph/sourcegraph`
* `github.com/sourcegraph/sourcegraph-sonarqube`.

#### Actual behavior:

`repo:` filters contains `(a|abc)$` only matches the repo names end with `a`.

For example,
`repo:github\.com/sourcegraph/(sourcegraph|sourcegraph-sonarqube)$`

* matches only `github.com/sourcegraph/sourcegraph`
* not match `github.com/sourcegraph/sourcegraph-sonarqube`

**Comment by rvantonder** [comment]
Assigning myself to investigate. If I learn something new that another team should own I'll update it here.

**Comment by rvantonder** [comment]
I can reproduce. I thought whether this is working as intended, but it is not, because equivalent, longer regular expressions work, while the simple pattern is broken. I'm ruling out any parser/query processing issue. I think our backend logic is making some simplifying assumptions when it shouldn't, or missing something about the pattern when it takes this particular shape.

CC @sourcegraph/search-core for visibility. I will block off ~2 hours to investigate and report back if I don't find a fix in that time.

The queries below should find two repos (tested locally). I have not checked whether this is a regression, likely it will be too time consuming for me to bisect on local instance so will probably just try find the bug directly.

## Broken:

<img width="578" alt="Screen Shot 2021-04-26 at 9 44 25 AM" src="https://user-images.githubusercontent.com/888624/116120098-07ab0e00-a674-11eb-8fcc-f7941985a4bc.png">

## OK (distribute `$`):

<img width="636" alt="Screen Shot 2021-04-26 at 9 47 53 AM" src="https://user-images.githubusercontent.com/888624/116120609-9029ae80-a674-11eb-8f01-f6f75eb4d190.png">


## OK (make optional):

<img width="584" alt="Screen Shot 2021-04-26 at 9 45 16 AM" src="https://user-images.githubusercontent.com/888624/116120198-25787300-a674-11eb-90d6-885a4b0a696e.png">

## OK (split substring pattern):

<img width="603" alt="Screen Shot 2021-04-26 at 9 44 06 AM" src="https://user-images.githubusercontent.com/888624/116120069-01b52d00-a674-11eb-9bfa-696af88382ae.png">

**Comment by keegancsmith** [comment]
@rvantonder I had a hunch where this problem is, but I'm signing off for the day. So I am including a broken test (which isn't correct), but points at what the problem is:

```diff
diff --git a/internal/database/repos_test.go b/internal/database/repos_test.go
index 16581560f3..9647dca292 100644
--- a/internal/database/repos_test.go
+++ b/internal/database/repos_test.go
@@ -68,6 +68,9 @@ func TestParseIncludePattern(t *testing.T) {
 		`^github.com/(golang|go-.*)/oauth$`: {regexp: `^github.com/(golang|go-.*)/oauth$`},
 		`^github.com/(go.*lang|go)/oauth$`:  {regexp: `^github.com/(go.*lang|go)/oauth$`},
 
+		// https://github.com/sourcegraph/sourcegraph/issues/20389
+		`^github\.com/sourcegraph/(sourcegraph-atom|sourcegraph)$`: {},
+
 		`(^github\.com/Microsoft/vscode$)|(^github\.com/sourcegraph/go-langserver$)`: {exact: []string{"github.com/Microsoft/vscode", "github.com/sourcegraph/go-langserver"}},
 
 		// Avoid DoS when there are too many possible matches to enumerate.
```

**Comment by rvantonder** [comment]
OK I dug into this and thought I got close to a fix but then stopped after spending too much time on it.

Problem: the regex reduces to this

```javascript
repo:^github\.com/sourcegraph/(sourcegraph(|-atom))$
```

or this, depending on order

```javascript
repo:^github\.com/sourcegraph/(sourcegraph(-atom|))$
```

The `repos.go` logic isn't dealing correctly with the empty string case for the `|` operator. I read through the logic and narrowed it down to these return values: somewhere here we should be returning `exact` in the second return position (because the `|` operator has a left and right hand side), but instead we return `exact` in the first return position (`begin && end` evaluates true, and this condition is too generous it seems), implying that there is only one pattern.

https://github.com/sourcegraph/sourcegraph/blob/583902c9e2956e1dc7e36190d822b2bd8e7b554f/internal/database/repos.go#L1394-L1401

I tried some other conditions like `if begin && end && len(re.Sub) > 0` and although that fixes this particular case it breaks other tests and it's not correct. Something in the `OpConcat` branch is making assumptions that's missing the corner case where `subcontains` is a string array like `[]string{"", "-atom"}` and returning it as `exact` instead of `contains`, and I think it's because of how `begin`/`end` state is computed.
