### ISSUE TITLE
Link to extension usage documentation from 3.0-quickstart guide.

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2041]
It's unclear which users an extension is enabled for when following the quickstart guide.

Feedback from: https://twitter.com/pjargon/status/1089530124666470400

It's also unclear to a site admin how to configure a Sourcegraph instance with extensions. Site admins may want to only enable an extension for themselves, an organization, or for all users on a Sourcegraph instance. This documentation exists here: https://docs.sourcegraph.com/extensions/#usage, but is difficult to find.

**Possible solutions:**
(One or several of the following may make it more clear to users and site admins)

- [ ] Include a link to https://docs.sourcegraph.com/extensions/#usage from the new 3.0-quickstart guide.
- [x] ~Allow users to specify who to enable an extension for from extension registry~ #1874 
- [x] ~Add Basic code intel to global settings by default. This would reduce the number of steps to get code intelligence working during onboarding.~ #2028 
- [ ] Add link to https://docs.sourcegraph.com/extensions/#usage from https://sourcegraph.example.com/extensions

Thoughts @sqs, @ryan-blunden?

**Comment by sqs** [comment]
#1874 will add a UI for enabling an extension for all users. (Planned for 3.1.)

#2028 will enable basic-code-intel by default. (Planned for 3.0.)

Updated the above comment's checklist to link to those and strikethrough the items.

The first checklist items seems like a good idea. The last one will be mitigated by #2028 and fixed by #1874, so it's not worth doing. (It's unlikely people would see it there, anyway.)

That leaves us with just 1 checklist item outstanding, so I commented about it on the PR at https://github.com/sourcegraph/sourcegraph/pull/2037#issuecomment-457985906 and will close this issue.

Thanks!
