### ISSUE TITLE
search: Ability to filter repositories based on primary language

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#20469]
Requested by https://app.hubspot.com/contacts/2762526/company/407948923/

Today it is possible to do some fairly complex search expressions, but it's not possible to filter results to just those with a primary language of say `javascript`.

Example:

* I want to find all NodeJS repositories we have, so I write a query `file:package.json "node" select:repo count:9999999`.
* But that includes repositories whose repo is not primarily `typescript` or `javascript` - for example it includes a Java repo which has a small nodejs helper script but otherwise doesn't use nodejs at all.

My only recourse here would be to run the search query using our GraphQL API, querying the languages of each and then filtering client-side - which is complex to figure out.

**Comment by camdencheek** [comment]
Closing since I don't think it's likely we'll add a relatively fuzzy feature like this. We can approximate the feature with the `repo:contains*` predicates, which provide a way to do rules-based matching on repos like `repo:contains.file(package.json)` or even more complex things like `repo:contains.file(path:package.json content:node)`. If the user needs something more detailed, the GraphQL API seems like the right tool to reach for.
