### ISSUE TITLE
UserRepositories and AffiliatedRepositories endpoint differences

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#20477]
### Description

When code host have `private code` enabled, user is an Admin and we request to sync all repos with `allRepos: true` option the following happens:

`UserRepositories` GraphQL endpoint returns _100+_ more repos as `cloned` comparing to `AffiliatedRepositories`  endpoint. For the result was 500 vs 386 repos.

It's important for us to get matching results because we use both queries for different repo views and those views need to be consistent.

**Comment by ryanslade** [comment]
WIP

When running the `AffiliatedRepositories` query I can confirm that we run the following graphql query against the GitHub API:

```graphql
query GetAffiliatedRepos($after: String) {
  viewer {
    repositories(first: 100, after: $after, ownerAffiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]) {
      nodes {
        nameWithOwner
        isPrivate
      }
      pageInfo {
        endCursor
      }
    }
  }
}
```

I can also confirm that this does *not* return private repos within the Sourcegraph org even though my user is a member of that org.

**Comment by ryanslade** [comment]
@arussellsaw Why did we choose to query for affiliated repos via the GraphQL API here:
https://github.com/sourcegraph/sourcegraph/blob/87f66afe6460fa1e94941a7db6d1866dfb356413/internal/repos/github.go#L705

Rather than using the existing method we already have here that is used for syncing:
https://github.com/sourcegraph/sourcegraph/blob/ff7e667d7bb4b4aaddd6f1fc05094f219ab818a6/internal/extsvc/github/repos.go#L368

**Comment by arussellsaw** [comment]
i think i just used it because i assumed v4 was the 'new' client and the one we were expected to use, i have no problem with us using the v3 client for this

**Comment by ryanslade** [comment]
Great, then it should be a relatively quick fix.

**Comment by ryanslade** [comment]
@artemruts I think this is a backend only issue so un-assigning you.
