### ISSUE TITLE
Search error messages

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20498]
**Problem statement**
See [one-pager](https://docs.google.com/document/d/1aKTIo4alkjwtlw10QDggbZwtWQvgLl4PRM28DEQvYrU/edit#)
Substantial UX improvement opportunities exist in the error page design and content.
Explore solutions to common errors such as:
* No results
* Too many repositories

**Comment by rvantonder** [comment]
It's worth adding context to this issue that `type:repo` was a problematic query for both the case of no results and too many repos, as it was buggy or poorly interpreted. This should be fixed by https://github.com/sourcegraph/sourcegraph/pull/20539.

The issue around "No results" can still affect `repo:...` queries, but that's a different context.

**Comment by malomarrec** [comment]
We have estimated this to 2 days of design to get to an MVP, 2 days of frontend work + 2 days of backend work

**Comment by malomarrec** [comment]
Closing this, and consolidating under https://github.com/sourcegraph/sourcegraph/issues/20818
