### ISSUE TITLE
"No repositories" message regression

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#20546]
When a user has a code host connection, but no repositories, they see this message on the Repositories view:

<img width="941" alt="CleanShot 2021-04-30 at 10 40 30@2x" src="https://user-images.githubusercontent.com/6304497/116670912-971c2e00-a9a0-11eb-9a40-e803198aa7f6.png">

This seems like a regression, as we previous had an actionable message like:

<img width="531" alt="CleanShot 2021-04-30 at 10 41 31@2x" src="https://user-images.githubusercontent.com/6304497/116670961-a8fdd100-a9a0-11eb-9a64-ddab23bd72d7.png">

**Edit:** Confirmed, the correct state is still exists and is sometimes shown, but I'm not sure why it is or isn't being shown in this case:

<img width="622" alt="CleanShot 2021-04-30 at 10 45 08@2x" src="https://user-images.githubusercontent.com/6304497/116671376-26c1dc80-a9a1-11eb-9bab-f03e5a7d50ad.png">

The incorrect state was shown while I was signed in as a non-admin user, while the correct state was as an admin/Sourcegraph member.

**Comment by artemruts** [comment]
### Why this happens:

This is a direct result of https://github.com/sourcegraph/sourcegraph/issues/20262 issue.

Our endpoints don't the return same results for Admin and non-Admin users. For the internal rollout, private code should be enabled for Admin users only.

### More details

With the non-admin user with Private code enabled:

1. `ExternalSerices` GraphQL enpoint's result:
   - will contain selected repositories (public and private) in JSON `config` object under the `repos` key
   - `repoCount` field will have correct number of repositories (public + private)

2. at the same time `UserRepositories` GraphQL enpoint will ignore all of the private repositories:
  ```js
  {
    "node": {
      "repositories": {
        // nodes will only include public repos
        "nodes": [
          {
             // ...
             name: "github.com/user/public-repo"
             // ...
          }
        ],
        // totalCount will always be null for non-admin users :(
        "totalCount": null,
        "pageInfo": {
          "hasNextPage": false
        }
      }
    }
  }
  ``` 
  
  Those differences in responses create a situation where `ExternalSerices` shows that user has private repositories but the `UserRepositories` won't fetch any. 

In your case:
1. only added private repositories for non-admin user
2. `ExternalSerices` reported as "yep, user has code hosts and repositorsies"
3. Page rendered repositories list component but since there were no repositories to render it fell back to `No repositories matched.`

**Comment by artemruts** [comment]
Will re-test and close once the blocking issue is resolved.
