### ISSUE TITLE
Bug: number of results do not match across search result pages

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#20559]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Sourcegraph.com

#### Steps to reproduce:

1. Go to [this sourcegraph url](https://sourcegraph.com/search?q=context:global+hashCode&patternType=literal)
2. Click on the first choice in repositories: `github.com/0xZhangKe/Glide-note 170` which supposed to have 170 results
3. Website direct us to that repo search result([link](https://sourcegraph.com/search?q=context:global+hashCode+repo:%5Egithub%5C.com/0xZhangKe/Glide-note%24+&patternType=literal)), with 266 results instead of 170 results

#### Expected behavior:
Redirect us to repo search result with 170 results as stated on the first page

#### Actual behavior:
Redirect us to repo search result with 266 results, which is different than the number stated on the initial page
A customer can also reproduce the same issue on their instance.

**Comment by stefanhengl** [comment]
If the user doesn't specify`count:` we default to `count:500`. As soon as we have found more than 500 results, we stop searching. The filter values show the results we have found so far (in this case 170). If you click on a repository filter, the search is now scoped to just 1 repo and we will search until we have found 500 results in just that repo. 

However, I would have expected the 170 to be displayed as `170+` and not just `170`.

**Comment by stefanhengl** [comment]
I had another look at the code to get a clear understanding when we display a `+` next to a filter chip and when not. It turns out that the current behavior can be quite confusing: For **repo filters**, we don't display `+` for indexed searches. **File and language filters** get a `+` whenever we have too many matches per file on at least 1 file we searched.  This behavior is (almost) independent of "result limit hit", which we display in the dropdown on the search page whenever we hit the `count:` limit. 

@rrhyne I am not certain what the desired behavior is for filter chips. IMO the message "result limit hit" is easy to understand and it accurately indiciates that what you see on the result page is only a subset of all results. 

Should we just get rid of the `+` for filter chips? 

Then the message would be that all counts are lower bounds if a result limit was hit. To see accurate counts, users have to run the query with `count:all`.

**Comment by keegancsmith** [comment]
Indeed. Infact we used to always add `+` essentially, and after feedback we removed that. But this state it is also confusing.

Context: here is the PR we removed it https://github.com/sourcegraph/sourcegraph/pull/17984. quoting the PR description:

> The other user visible change is we now no longer compute the partial
sets. If a repo appeared in partial, we would show a "+" next to the
dynamic filter count for that repo. This is the most contentious part of
the change. The previous implementation was pretty hacky and not
necessarily correct. This is something we could maybe add back when we
create a streaming RPC for zoekt. Or we could not do this change now.

**Comment by rrhyne** [comment]
If we add the plus now we confuse the user when the + is present and shouldn't be as per #17984.  If either one of these confusing/incorrect issues occurs infrequently we could choose that option, but I don't think that's the case. 

I think the only correct answer is to not show the plus until we can show it accurately.

The most immediate thing I can think of to help this issue is to include a tooltip when the user mouses over the number to read, "At least 170 results.", for every count. This would also help new users to understand what the number means. I've seen that asked, so I'd be in favor of the change. 

What do you guys think?

**Comment by keegancsmith** [comment]
> "At least 170 results.", for every count. This would also help new users to understand what the number means. I've seen that asked, so I'd be in favor of the change.

Sounds good.

**Comment by rrhyne** [comment]
Should this be a ticket for search product?

**Comment by keegancsmith** [comment]
> Should this be a ticket for search product?

Yes.

**Comment by keegancsmith** [comment]
@abeatrix this issue is being resolved by https://github.com/sourcegraph/sourcegraph/issues/21170

I think it's alright to close this out? Or does it make more sense to update title/description and link to the product issue, then only close once the customer is happy? If the latter, please re-open :)

**Comment by abeatrix** [comment]
@keegancsmith sounds good to me, thanks for looking into this everyone 🙇
