### ISSUE TITLE
Better UX for adding repositories

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2057]
(This is underspecified, will fill in more details in the 3.2 kickoff.) See the new add-repository wireframes in https://docs.google.com/document/d/1P7uMHtOeYK1IwMj-1WtKspo16v8C_Mevj3qe1cX_kGY/edit#heading=h.vh7b6txgdnec.

Site admins adding repositories is too manual, clunky, and undiscoverable in the current UI. #2025 is probably a prerequisite.

**Comment by chrismwendt** [comment]
Drive-by ideas 💡 

- Redirect `/site-admin/external-services` -> `/site-admin/external-services/add` when there are no services yet
- Replace the JSON editor with a form or turn it into a 2-tab view. Each code host's form would be slightly different. GitHub example:
  - Drop-down: type `[GitHub, GitHub Enterprise]`
  - Text box: URL (GitHub Enterprise only)
  - Text box: access token (with link to https://github.com/settings/tokens)
  - Text area: TLS certificate (GitHub Enterprise only)
  - Checkbox: Inherit repository permissions
  - Radio: cloning via SSH vs HTTP(S)
  - Checkbox: automatically clone on visit
  - Text box: repository path pattern
  - Drop-down: repository query `[public, affiliated, none]`
  - Multi text box: list of other repositories to include

**Comment by beyang** [comment]
In my mind, there are three general approaches here:
1. More docs
2. More user-friendly schema
3. More features

### More docs
Make docs and examples more accessible from `/site-admin/external-services/add`
* Link to the appropriate documentation depending on what service type is selected.
* Show examples of common configuration (e.g., "all GitHub.com repos belonging to an organization", "all my repos on a GitLab instance").
* Better "starter" JSON text with commented out fields with docstrings that explain what the fields do (a la `nginx.conf` and `postgresql.conf`)

### Better user-friendly schema
The current schema is fairly low-level and often requires admins to map from higher-level concepts (e.g., "all repos in GitHub org") to low-level params (e.g., `repositoryQuery`). We can make the schema more user-friendly/obvious by doing things like:
* Change the user-facing schema to allow specifying more explicit options like `organizations` instead of the lower-level `repositoryQuery`

### More features
* Replace the JSON editor with more UI widgets (dropdowns, etc.)
* In the most extreme case, we could use something like https://github.com/brutusin/json-forms to generate forms directly from the JSON schema

### Discussion

First, a few observations
* Most of the user issues about external service configuration pertain to unexpected or invisible behavior when translating a high-level description of the repo set into the config options. I.e., either (1) they couldn't figure out how to express what they wanted using the options available or (2) they couldn't verify they had expressed the right thing. Notably, I couldn't find any issues that complain about the actual format (textual JSON):
  * https://github.com/sourcegraph/sourcegraph/issues/218
  * https://github.com/sourcegraph/sourcegraph/issues/123
  * https://github.com/sourcegraph/sourcegraph/issues/2164
  * https://github.com/sourcegraph/sourcegraph/issues/2042
* Machine access to config is important for developers ([1](https://github.com/sourcegraph/sourcegraph/issues/2140)).
* There is inherent complexity in the external services config, because (1) there are a lot of parameters that could define a set of desired repositories (including users, orgs, teams, groups, external collaborators, and regexes) and (2) there may be multiple ways of configuring authz appropriate for different customers depending on internal security constraints.
* VS Code grew to a bjillion users before adding any UI widgets to their config editor
* The config schema will change in the future. The cost of maintaining the external services UI over time should be considered.

As a consequence, my priors here are to favor first more documentation/examples and second, to add additional fields to the schema to make expressing certain common cases easier. I would like to avoid adding UI widgets, because (1) they don't actually seem to solve the user pains here (i.e., the JSON is not the painpoint), (2) UI forms are fugly when the schema gets even a little complex and if we try to keep them simple we will end up just obscuring the inherent complexity, (3) forms would create a greater disconnect between the UI config and the config that shows up via the API, and (4) it will be more expensive to maintain.

I propose we do the following:
1. Update the external services schema to add certain fields that are more user-friendly. E.g., `organizations` for GitHub.
2. Embed better docs in the "add external service" UI:
  * Link to documentation for each service type
  * Have better "starter" JSON where we all fields and comment out the ones that aren't used by default
  * Have a dropdown that allows a user to see examples of common configs. When a user selects a dropdown item, it will populate the JSON text area with a template. E.g., "All repositories in a GitHub.com organization" would set a template that looks like `{ "url": "https://github.com", "token": "$TOKEN", "organizations": ["$ORG"] }`.

@sqs agree/disagree?

**Comment by sqs** [comment]
@beyang I agree it does not make sense to introduce a form-based UI for this. There is additional UI work that we *should* do, though, which is adding simple buttons that perform JSON edits to the config JSON. We use this in site config and settings, and site admins generally find them useful. They are also simple to implement and maintain. For example, the bullet item in https://docs.google.com/document/d/1P7uMHtOeYK1IwMj-1WtKspo16v8C_Mevj3qe1cX_kGY/edit# that says "For GitHub, helper buttons:" would be these buttons that would just apply a JSON edit that adds a new entry to `repositoryQuery` with a placeholder string for the user to finish filling in.

Adding a few buttons for the most common cases seems like it'd be quite easy to implement (we already do it for other config JSON editors), it'd be easier for the user than reading a comprehensive example/commented JSON document, and it is UX-consistent with other config JSON editors.

We definitely should link to the docs page for each external service from the page.

**Comment by beyang** [comment]
Add'l Slack discussion: https://sourcegraph.slack.com/archives/D02FRPWF5/p1550710718002600

**Comment by beyang** [comment]
Addressed in https://github.com/sourcegraph/sourcegraph/pull/2644
