### ISSUE TITLE
Strip private data before pushing to BigQuery

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#20628]
The [LogEvent](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/event_handlers.go#L43) method is used to send events to both BigQuery and to the `events` table.
We need to stop ~storing~ /~ sending the `url` and `arguments` column as they contain private user information and are not used for analytics anymore.
~Ensure no other part of the codebase is using these columns, through the [EventStore](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/event_logs.go#L75:28)) or through reading the table directly.~

Ensure that we do not send these to BigQuery anymore.

Cf: [RFC-358](https://docs.google.com/document/d/1eCZMbA-155WlUI-RQPRhEhOxUqcveYNvIiGE5nuyiBQ/edit#heading=h.7n0dh9v2qz0z)

**Comment by indradhanush** [comment]
A summary of what I've been upto today:

I made a change to stop writing `URL` and `Argument` to the `event_logs` table and naively "fixed" the tests that were still writing to it here: https://github.com/sourcegraph/sourcegraph/compare/ig/private-analytics?expand=1

That's when I realized from my failing builds (should have checked first) that the columns are `not nulllable`. As a result I had to change my approach to writing an empty string instead. Here's what I suggest for a smooth zero-downtime approach:

1. Write empty strings to these two columns and stop reading from the columns
1. In the next release, we write a DB migration to make the fields nullable
1. In the subsequent release, we permanently stop writing to the field
1. Finally we drop the columns from the database

We could maybe merge `1`, `2` and `3` in the same step but I fear this could lead to some write errors when the db migration is in progress while the code has already been updated to stop writing to these columns. I could be wrong about this as I do not have more insight into the deployment order. Also if these potential errors are not a huge concern then we should definitely merge these three steps into one.

Point number `1` above isn't without its pain points however. Here are the following list of touch points (AFAIK) which rely on reading data from the `argument` column and my feeling is that 

1. [GetCodeInsightsUsageStatistics](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/code_insights.go#L37-47) - Possibly owned by @sourcegraph/code-insights.
1. [aggregatedSearchEventsQuery](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/event_logs.go#L884-890) - Not sure who owns this.
1. [GetExtensionsUsageStatistics](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/extensions.go#L16-19) - Not sure who owns this. Maybe @sourcegraph/code-intel ?
1. [eventLogsCountsQuery](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/batches.go#L64-68) - Possibly owned by @sourcegraph/batchers 
1. [aggregatedCodeIntelEventsQuery](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/event_logs.go#L811-814) - Possibly owned by @sourcegraph/code-intel.

Here's what I have so far in this branch (different from the previous link since I had to change my approach): https://github.com/sourcegraph/sourcegraph/compare/ig/private-analytics-url-args?expand=1

Some tests are rightly failing here which I believe is a symptom of the above touch points relying on the `argument` column for their queries while the change now writes an empty `{}` to it.

**Comment by mrnugget** [comment]
> 4\. [eventLogsCountsQuery](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/batches.go#L64-68) - Possibly owned by @sourcegraph/batchers

We don't use the `URL` of `event_logs`, but we do use the `arguments` column to store "metadata" along with the event: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@40c5c3d665983f879465daa32f7d0154db024791/-/blob/enterprise/internal/batches/resolvers/resolver.go#L99-114

But I don't see how that is private data?

**Comment by rvantonder** [comment]
> We need to stop storing / sending the url and arguments column as they contain private user information and are not used for analytics anymore. Ensure no other part of the codebase is using these columns, through the EventStore) or through reading the table directly.

@asdine can you please clarify whether this issue aims to strip/sanitize logged event data only for private code, specifically for the `argument` column? Or entirely? I can't easily tell from RFC 358.

**Comment by rvantonder** [comment]
@Strum355 about (2), because I happened to look at this, yeah, it flows to big query via this schema (`language_id`): https://github.com/sourcegraph/sourcegraph/pull/15635

**Comment by efritz** [comment]
This seems like a huge hammer.

**Comment by ryanslade** [comment]
> This seems like a huge hammer.

Could you clarify what you mean please? Are you referring to the issue as a whole or the PR linked above?

**Comment by efritz** [comment]
Sorry, the conversation about this was split in too many places. I'm still getting context on this.
