### ISSUE TITLE
Add "smartcase" for regexes

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2084]
**Feature request:**

> Would love "smartcase" for regexes, instead of the default of case-insensitive. If you're not familiar with that terminology: smartcase means case-insensitive unless you use uppercase letters in your query. Would love to change the sourcegraph default from case:no to case:smart.

- [ ] Add `smartcase` option to `case` keyword. `case:smartcase`

The full solution would likely need to include solving: 

- [ ] [Override search keyword default values](https://github.com/sourcegraph/sourcegraph/issues/2085)

- [ ] [Site-wide search query defaults](https://github.com/sourcegraph/sourcegraph/issues/1817)

**Comment by slimsag** [comment]
this would be awesome!

**Comment by keegancsmith** [comment]
This isn't really that much work either. I would note that we have a new search syntax behind a feature flag, so when we work on finally shipping that we musn't forget this feature request.

**Comment by ijsnow** [comment]
@KattMingMing I added `case:auto` which is the setting for smart case. It's on by default, per [@sqs's comment in a tagged issue.](https://github.com/sourcegraph/sourcegraph/issues/2085#issuecomment-459868276)

Since this issue is specifically for smart case, not for the settings in the two linked issues, I'll leave this closed. Tag me in those other issues to let me know if there is still demand for those settings and we'll see how we should prioritize them.

**Comment by brandonbloom** [comment]
Awesome. Thank you!
