### ISSUE TITLE
Repo-updater Sync Jobs - Inaccurate Alert - Grafana/Prometheus Metrics Out Of Sync

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#20911]
- **Sourcegraph version:** v3.26.0 
- **Platform information:** This is an issue in standard Kubernetes SG deployments, and possibly other deployments. 

#### Steps to reproduce:

1. Observe the following alerts:
```
repo-updater: less than 0 repositories synced for 9h0m0s
repo-updater: less than 0 sync was started for 9h0m0s
```
2. Run the following query in `pgsql` to verify that sync jobs are being scheduled:
```sql
select
  ej.external_service_id, es.display_name, state, num_failures,
  started_at, finished_at, log_contents, execution_logs
from external_service_sync_jobs ej
join external_services es on es.id = ej.external_service_id
order by finished_at desc
limit 10;
```
#### Expected behavior: 
The following warnings should fire after 9 hours of the `repo-updater` not scheduling new synch jobs for the gitserver:
```
repo-updater: less than 0 repositories synced for 9h0m0s
repo-updater: less than 0 sync was started for 9h0m0s
```

These alerts are associated to the `Sync was started` and `Repositories Synced` charts.

Running the grafana query `sum by (state)(rate(src_repoupdater_syncer_synced_repos_total[1m]))` in Sourcegraph clouds monitoring suite we observe expected behavior:
![Screen Shot 2021-05-12 at 9 41 45 AM](https://user-images.githubusercontent.com/13024338/118012827-501a2b00-b306-11eb-8dd5-3cedc8dba26a.png)

#### Actual behavior:
These warnings are firing despite the `repo-updater` scheduling sync jobs in both dogfood, and user instances.

The same grafana query from above `sum by (state)(rate(src_repoupdater_syncer_synced_repos_total[1m]))` in our internal dogfood Sourcegraph (note the 0 values for all state columns, frequent rollouts prevent alerts from firing in our dogfood instance, which may have allowed this to go undetected):
![Screen Shot 2021-05-12 at 9 47 25 AM](https://user-images.githubusercontent.com/13024338/118013558-172e8600-b307-11eb-8823-49d281848726.png)

Cross-referencing this with our internal metrics reveals that syncs are indeed being scheduled and occuring:
![Screen Shot 2021-05-12 at 9 54 29 AM](https://user-images.githubusercontent.com/13024338/118014512-28c45d80-b308-11eb-8c49-244fe2e05652.png)

The grafana charts appear to be out of sync with the actual behavior of the `repo-updater` hence flagging this as a bug.

Metric [code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1f755b97b5e6fc0b222478b5307270a1f53473f7/-/blob/internal/repos/syncer.go#L835-852) for reference.

**Comment by DaedalusG** [comment]
@dan-mckean just observed this in a call with a customer, can confirm this is still showing up in v3.35.1

**Comment by DaedalusG** [comment]
Just observed these alerts in an instance running in v3.35.1, notably though we're not seeing them in the k8s dogfood environment. Another distinct feature on this instance was that all of the codehost configs were of type `OTHER`

**Comment by indradhanush** [comment]
Is this still an issue? I checked the metrics on both Cloud and Dogfood and here's what I see:

**Cloud**

![image](https://user-images.githubusercontent.com/2682729/156480880-9db839e7-df23-4315-aa7b-81b45e0eac24.png)

**Dogfood**

![image](https://user-images.githubusercontent.com/2682729/156480928-90a3d257-10a6-4576-8889-7522c86efcaa.png)

**Comment by DaedalusG** [comment]
@indradhanush I can confirm this still comes up, I had a report this week from a customer running v3.37.0 with no apparent issues in repo sync. One observation is the alert seems correlated to when one repo is failing to sync for some reason. 

The alert is currently also present of one of our [test instances](https://cse-k8s.sgdev.org/), which I can grant access to
![Screen Shot 2022-03-03 at 9 56 26 AM](https://user-images.githubusercontent.com/13024338/156623700-a0ee0d06-0bff-4d83-8643-6d1e6e643bca.png)

**Comment by DaedalusG** [comment]
This issue seems to be active again -- noting it in both customer deployments and on a test deployment
![Screen Shot 2022-09-08 at 11 09 11 AM](https://user-images.githubusercontent.com/13024338/189195614-a982a2c9-9278-4de5-a05d-68ccc6f17e98.png)
![Screen Shot 2022-09-08 at 11 09 00 AM](https://user-images.githubusercontent.com/13024338/189195625-c80125cd-3450-4f5b-a290-1bd6721a9dd4.png)

**Comment by mike-r-mclaughlin** [comment]
We saw this at https://github.com/sourcegraph/accounts/issues/554.  Here's a [snippet](https://hello.chorus.ai/listen?guid=7f391c64a73f4746a2d8652b9676ce2d) of the discussion.
It's a very confusing message.  What does "synced" mean here?  Is it just "new" or "deleted" repos?  If so, that doesn't seem like a very good warning since most customers won't have new/deleted repos every 9 hours.  If it's just a general "we haven't seen any activity on any repo in 9 hours", then this has to be a bug because we definitely saw updates during this time.

**Comment by ryanslade** [comment]
@DaedalusG Can you point me at the test instance where you're seeing this?

**Comment by ryanslade** [comment]
Looking at the metric on the [test instance](https://cse-k8s.sgdev.org/-/debug/grafana/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22max%20by%20(state)%20(rate(src_repoupdater_syncer_synced_repos_total%5B1m%5D))%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-93714c07-9508-440e-823d-63aa01af26f3-0A%22%7D%5D) it looks like we're using this query for the metric:

```
max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m]))
```

The problem with that is that we are splitting by the different states a sync can be in:

* added
* deleted
* modified
* unmodified

This lead to four distinct metrics and if *any* of them end up being zero over the last 9 hours, the alert fires. 

It can be quite common for all repo metadata to be unmodified for a period of 9 hours for example which would trigger the alert, even though we *are* syncing them.

It looks like this was already fixed in a [another commit](ecd53a1de9098ccbcac112ccfd1ceff9461cdc38) since the current query is actually:

```
max(rate(src_repoupdater_syncer_synced_repos_total[1m]))
```

Note that this no longer splits by state and so *any* sync will now be counted and we shouldn't get the false alarm anymore.

**Comment by ryanslade** [comment]
@DaedalusG Can we close this?

**Comment by DaedalusG** [comment]
Yeah if I encounter this in the wild again I'll reopen 👍
