### ISSUE TITLE
AffiliatedRepositories endpoint doesn't return repos if one of the code host connections as an error

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#20934]
### Description

If the user creates a single invalid code host connection:
*  by using an invalid personal access token
* by invalidating personal access token
* if _we_ somehow request wrong the OAuth scope

 `AffiliatedRepositories` endpoint will always return no repositories for all of the code host connections.
 
### Example 

**Setup:**
 Two code host connections were added:
* GitLab (5 repos) with an _invalid_ personal access token
* GitHub (10 repos) with OAuth

**Expected result:**
`AffiliatedRepositories` endpoint responds with 10 repos from GitHub

**Actual result:**
`AffiliatedRepositories` endpoint responds with no repositories (`[]`)

**Comment by ryanslade** [comment]
The issue here is that we're using an `errgroup`:
https://github.com/sourcegraph/sourcegraph/blob/744ae71d04842b724d70938240ce24dd3e2a9bdf/cmd/frontend/graphqlbackend/codehost_repository_connection.go#L64

If any request in the group fails, all will be cancelled. 

Instead, we should probably just spin up goroutines ourselves. Successful requests will be appended to the collection and failed ones can log an error. We probably still want to return if *none* of the requests succeed.
