### ISSUE TITLE
Feedback widget - button should be disabled for empty input field

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#21071]
##Description

It shouldn't be possible to send feedback without the message. Currently, after selecting the emoji, the button is enabled.

To prevent getting meaningless messages with emoji only, I think we should enable the button when both conditions are met:
- the emoji is selected
- the message (input field) is not empty

Note: the behaviour hasn't changed because of the refresh changes. It is this way in the current implementation.

**Comment by AlicjaSuska** [comment]
@quinnkeast since you've designed the widget, please share what you think about it. Is it a bug or I'm missing sth?

**Comment by quinnkeast** [comment]
> @quinnkeast since you've designed the widget, please share what you think about it. Is it a bug or I'm missing sth?

I believe it was intentional to let people submit without a message so long as the emoji is selected. The reasoning at the time was that the affective feedback is still valuable on its own when paired with the context, and so we'd reduce friction and get the affective feedback without requiring a message every time.

Looking at the actual responses, it looks like we have at least a few that signal someone isn't having a good time, or that it's a good experience, but without messages.

I'm not feeling strongly one way or the other on requiring the message—wdyt?

**Comment by umpox** [comment]
I feel like we might discourage some people from submitting feedback if we require a message to be sent too. We collect the email + site area when the feedback is sent so I still feel that the emoji value is useful to aggregate data
