### ISSUE TITLE
Typing fast on the search box causes web app to stutter

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#21200]
Repro steps:

1. Navigate to a big page, eg. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/HEAD~40...HEAD?visible=90
2. Type fast on the search bar

Expected: typing works fine
Actual: web app stutters, typing lags

Every component in the page seems to be re-rendered on every keystroke due to the `QueryState` changing.

I tried debouncing changes to navbar `QueryState`, which fixed the stuttering but broke the search box autocomplete.

**Comment by slimsag** [comment]
thanks for filing for me!

**Comment by limitedmage** [comment]
@slimsag  I have this draft PR that might fix this issue, but could introduce other issues with searchbox autocomplete. Can you give it a try? https://github.com/sourcegraph/sourcegraph/pull/21478

**Comment by slimsag** [comment]
I have found this: https://stackoverflow.com/a/51082563

It's let me trace back the cause of this to these props changing:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/3173176/128410847-c83cea9b-36b7-401b-b400-c928becaf7e4.png">

I think that these props are not even part of the declared type; they're being shoved in via the JS object in violation of the TS types.

**Comment by slimsag** [comment]
K, I've traced this back to two things:

1. In our routes, we are using expanded `{...context}` which passes in the additional fields above - in complete violation of the component's declared `Props` types - meaning that there are other fields like `navbarSearchQueryState` passed recursively to most pages (through `{...context}` expansion at the router), leading to any keypress in the search bar to rerender all pages. [here's exactly where](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Eclient/web/src/repo/routes%5C.tsx+%7B...context%7D&patternType=literal)
2. `RepositoryCommitPage`, `RepositoryBranchesArea`, `RepositoryReleasesArea`, `RepositoryStatsArea`, `RepoSettingsArea`, `BlobPage`, `RepositoryCommitsPage`, `RepositoryDocumentationPage` and many more are ALL defined as React functional components. Functional components rerender **always, even if the props have not changed**. So when a rerender is triggered due to keypresses in our search input - the entire page rerenders even though no props have changed for most components. We need to be using https://reactjs.org/docs/react-api.html#reactmemo a lot more liberally.

**Comment by limitedmage** [comment]
@benvenker Moving this into "Next" in case we have the bandwidth to look into it in the next iteration.

**Comment by fkling** [comment]
To me it seems like the proper solution would be to ensure that only the requested/expected props are being passed but that might be difficult to achieve with the way compose our components (prop drilling :( ). It seems like that we also perform unnecessary updates for other props, even though they don't have the same perf impact.

If that's not possible though then I guess we can either

1. Use context to make `QueryState` available (don't know if that depends on anything that platform tries to do with context). 
2. Pass down a (memorized) observable that interested components can subscribe to.

**Comment by felixfbecker** [comment]
@fkling afaik, React context actually also causes re-renders of all intermediate components: https://blog.logrocket.com/pitfalls-of-overusing-react-context/
So I think React context should actually only be used for data that changes rarely/ever at all (e.g. an API client, config, or the current theme) and be **avoided** for a case like this where a prop changes on every keystroke (a prop + `React.memo()` would be best for that).

I think the easiest fix here is to
1. pick a few high-up "boundaries" where we currently pass all props through `{...context}`/`{...props}` and descendants _don't_ need the query state and expand that into explicit props being passed. It's a bit more verbose but we have done this in some places already when it made a difference.
2. make sure the rendered child component is wrapped in `React.memo()` (or use `React.PureComponent` for class components) to make sure it won't rerender

React dev tools have tools to flash re-rendering components I think, which could help to catch any components/page areas that shouldn't intuitively have to rerender based on query changes. The good thing is we only need to apply these steps to the highest common ancestors there, not to every component.

A few other notes:

> We need to be using reactjs.org/docs/react-api.html#reactmemo a lot more liberally.

I would disagree with this general advice, because `React.memo()`/`useMemo()`/`React.PureComponent` have a perf overhead themselves of comparing all props at every render. In fact, we actually overuse(d) `React.PureComponent` and `useMemo()` (same thing) and were trying to gradually remove it from more places and only apply it surgically where it actually provides benefits (which is definitely the case here, to be clear!). @valerybugakov can share more info on this 🙂 

> they're being shoved in via the JS object in violation of the TS types.

> which passes in the additional fields above - in complete violation of the component's declared Props types - meaning that there are other fields

Just to pre-empt anyone wondering "Oh no, does that mean I can't trust the type-checker? Is our TS config is broken?": It doesn't violate the type, since an object with additional fields still satisfies the interface with fewer fields (it's a supertype, and TypeScript has structural typing). This is correct from a type perspective 🙂 
It's also important to keep in mind that TypeScript does not affect runtime behavior – types are simply erased from the source code, so properties can't be stripped from the `{...context}` spread at runtime based on type information (the spread is a JS construct and ends up in the output).

**Comment by fkling** [comment]
Here is a POC that uses https://github.com/pmndrs/zustand to "side load" the query state where needed: https://github.com/sourcegraph/sourcegraph/pull/24844
