### ISSUE TITLE
Make the query input in the Code Insight creation UI a real search box, with autocompletion, syntax highlighting and toggles

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21339]
Currently, our search input is just a plain text input, which means users don't get the same kind of assistance they get when using the search box elsewhere in the product. For example, it is not clear how to change regex vs plain matches, case sensitivity, or use structural search. Operators are also not completed and highlighted, and regex patterns are not explained with hovers. Invalid search queries are not highlighted with squiggles.

### Current:

![image](https://user-images.githubusercontent.com/10532611/119495989-4d3a2400-bd63-11eb-8e0a-fe36fa777de7.png)

### Desired:

![regex-highlight](https://user-images.githubusercontent.com/10532611/119495669-ed437d80-bd62-11eb-8e45-8504518f719b.gif)

It would be great if we could use the same search box from the search box in the code insights creation UI page as a reusable component.

cc @sourcegraph/search-product

**Comment by lguychard** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/17320

**Comment by vovakulikov** [comment]
@felixfbecker totally with you about this thing. Probably we should close this issue https://github.com/sourcegraph/sourcegraph/issues/20201 in favor of this. I put this ticket to the 3.29 tracking for now. And let's prioritize that next week. Thank you for starting this ticket.

**Comment by felixfbecker** [comment]
@lguychard great to hear that search itself (code monitoring) would benefit from it too!

@limitedmage do you have some insight into how reusable is the current search box component to support this use case, or how much work it would be to make it reusable?

**Comment by limitedmage** [comment]
> @lguychard great to hear that search itself (code monitoring) would benefit from it too!
> 
> @limitedmage do you have some insight into how reusable is the current search box component to support this use case, or how much work it would be to make it reusable?

In theory it should be reusable given that all the getters/setters for the query and toggles are passed in, but we haven't ever tried it.

**Comment by felixfbecker** [comment]
@unclejustin how many days of work would you say are still left on this ticket? Are next steps clear, or are there blockers?

**Comment by unclejustin** [comment]
> @unclejustin how many days of work would you say are still left on this ticket? Are next steps clear, or are there blockers?

Unclear. I ran into a ton of problems with types trying to pass a large number of required props down to `SearchBox`. I have an experimental PR for Vova and Juliana to pre-review. Depending on the outcome of that review either 2 more days of bug fixing and testing or 5 minutes of updating the issue to say we can't do it until we re-factor `SearchBox` 😬 

There may still be alternatives similar to what Rok did with notebooks. Meaning we pull out a couple of pieces of `SearchBox` specific to our needs and make that work instead. I am hesitant to go down this path though, as this would create quite a bit of duplication, and will definitely be a maintenance problem.

Even Vova and Juliana agree with my usage of `context` I still think we shoulo spend some time refactoring `SearchBox` to be more composable. Time/scope permitting, I would prefer handling that first instead of continuing on this current path.

**Comment by vovakulikov** [comment]
There are no more easy tasks/issues in the code insights codebase. I think this ticket shows that perfectly. My personal opinion is that we should invest more and maybe make some changes in other places to be able to simplify our approaches and solutions in our code-base.  

@unclejustin I saw that you tried an approach with contexts to solve problems with props I think that's cool. I encourage you to keep going with that and maybe change something on a global level and `SearchBox` too since it seems crucial for us to find a simple and useful solution not only for code insights code-base. 

Let me know if you need any tech help with that. @felixfbecker as always you're welcome to join us in the review I believe you might have some thoughts on this as well 👨‍🔬

**Comment by Joelkw** [comment]
From @felixfbecker – can we use this issue to also take care of our "validation" needs (such as not letting you include a `repo:` in the search, with search validation red squiggles?

**Comment by limitedmage** [comment]
@Joelkw You can add validation to the search box using Monaco. I'm not sure how much work it would be to add validation to the search box in code insights that also does not apply to the normal search box. But it's definitely possible.

**Comment by rvantonder** [comment]
@fkling would be great for you to plug your thoughts/framework for validation rather than us minting other ad-hoc validation routines for Code Insights.

**Comment by fkling** [comment]
What @rvantonder is referring to is https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d3f3d5e2a394a933337301fb16eb83e6f59a6b27/-/blob/client/shared/src/search/query/diagnostics.ts?L84-178 . It's a way to define "patterns" to match the query against, and this is how currently use for generating diagnostics for the main search query input.
