### ISSUE TITLE
Basic code intel is showing known-wrong hovers

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2136]
These hovers are clearly incorrect in a way that (I think) basic-code-intel should be able to determine. Did the hover logic recently get less strict?

![image](https://user-images.githubusercontent.com/1976/52176325-76f56880-27b1-11e9-9fbd-53d8ec15e871.png)
![image](https://user-images.githubusercontent.com/1976/52176331-81affd80-27b1-11e9-855e-e3e9056818cd.png)

**Comment by chrismwendt** [comment]
Yes, I [added some definition patterns on Thursday](https://github.com/sourcegraph/sourcegraph-typescript/commit/061810357678844213f865fe1e93d5e54fdf55ff) and forgot to use `\b`. I fixed the tooltip in first screenshot just now in https://github.com/sourcegraph/sourcegraph-typescript/commit/778f11f2194305f1d8ce5cb3c845162ba97347e8

The definition in the second tooltip is actually [coming from ctags](https://sourcegraph.com/search?q=%5CbSubject%5Cb+case:yes+file:.%28ts%7Ctsx%7Cjs%7Cjsx%29%24+type:symbol+repo:%5Egithub.com/sourcegraph/sourcegraph%24%4034a5e6864c4debebe7d4edbae565dbaf58f1b114). I suspect this is an artifact of TypeScript files being parsed as JavaScript because of `--map-JavaScript=+.ts`:

https://github.com/sourcegraph/sourcegraph/blob/9de90d09a9ede29f96f2c52959ee0671a82a3f8e/cmd/symbols/internal/pkg/ctags/parser.go#L46-L50

I'm fixing this in https://github.com/sourcegraph/sourcegraph/pull/2139
