### ISSUE TITLE
Linking to registry with search "category:Insights" broke in registry redesign

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21393]
We link to the unofficial "insights" category from the code insights creation UI to show all extensions that contribute insights.
In the new registry, this no longer shows any extensions:

![image](https://user-images.githubusercontent.com/10532611/119643058-9c439000-be1b-11eb-9b63-06947d8caa46.png)

https://sourcegraph.com/extensions?query=category:Insights

**Comment by tjkandala** [comment]
It's because all insight extensions are considered to be experimental. Whether to display experimental extensions is up to the user (checkbox in the dropdown at the bottom of the sidebar). Should we provide some sort of override as a URL query parameter?

**Comment by felixfbecker** [comment]
Yeah if you can give us a URL parameter we can add it to our link :)

**Comment by muratsu** [comment]
We will target 3.29 for a fix. @felixfbecker quick question to figure out the impact of this issue. Do we end up visiting this page every time we want to create a new code insight?

**Comment by felixfbecker** [comment]
Awesome, thanks!
No, just for the 3rd choice of these three choices the user is presented (in order of importance/popularity):

![image](https://user-images.githubusercontent.com/10532611/120363485-7ed76000-c30c-11eb-9f71-f41a07d9a7b4.png)

**Comment by muratsu** [comment]
Adding status (all, enabled, disabled) & experimental (true, false) as query params make sense to me. We're also looking into graduating some sg extensions from experimental. Please keep that in mind that so that you can remove the experimental query param once all the high-quality extensions are graduated.

Also tagging @Joelkw for visibility. I'm prioritizing this issue on our iteration board
