### ISSUE TITLE
Automation of sourcegraph configuration

### ISSUE THREAD

**Issue by FrankEppinkMsgGillardon** [sourcegraph/sourcegraph#2140]
#### Question description

I am looking for ways on how to automate the configuration of sourcegraph when running as a single Docker Instance. With configuration I mean
- increasing number of repos to search
- adding an external service and enabling all repositories
- adding GitLab as OAuth provider
Of course that's all fine done manually via web ui, i.e. site-configuration or via the management console.

I tried to use GraphQL via curl statements.
I managed to execute a query (i.e. current user) that way, but did not manage to update configuration (which would be done via a "mutation" I guess).

Any help is appreciated
Thanks
Frank

#### Is your question related to a problem? If so, please describe or link to another issue.

So far I found the following two other threads, which mention automation of configuration, but unfortunately do not elaborate:
https://github.com/sourcegraph/sourcegraph/issues/859
https://github.com/sourcegraph/sourcegraph/issues/1036

**Comment by slimsag** [comment]
Understood.

One idea would be to create a Sourcegraph instance on your chosen version (e.g. `3.0.0`) and configure it as you wish, then create a PostgreSQL database backup. Since configuration is stored entirely in the database since version 3.0.0 (including user accounts, etc), you could then just run the relevant psql command to restore the DB and your instance would be configured as you wish.

**Comment by FrankEppinkMsgGillardon** [comment]
Usage of the PostgreSQL database is also an idea.
Following your hint of checking the generated GraphQL mutation queries I however managed to get the configuration scripted, therefore closing this issue.

Thanks for your support
Frank
