### ISSUE TITLE
Feature: Syntax highlight code in markdown files

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2144]
https://sourcegraph.com/github.com/GoogleChromeLabs/comlink/-/blob/README.md

![image](https://user-images.githubusercontent.com/10532611/52232687-6df1bd80-28bd-11e9-9a2a-35d4d626501f.png)

![image](https://user-images.githubusercontent.com/10532611/52232701-75b16200-28bd-11e9-8c02-f623bf98ebb1.png)

    ```js
    // main.js
    const MyClass = Comlink.proxy(new Worker("worker.js"));
    // `instance` is an instance of `MyClass` that lives in the worker!
    const instance = await new MyClass();
    await instance.logSomething(); // logs “myValue = 42”
    ```

    ```js
    // worker.js
    const myValue = 42;
    class MyClass {
    logSomething() {
        console.log(`myValue = ${myValue}`);
    }
    }
    Comlink.expose(MyClass, self);
    ```

/cc @felixfbecker

**Comment by slimsag** [comment]
This isn't actually a bug, this is something we've never supported in rendered markdown. I definitely would like to see this too, though!

**Comment by felixfbecker** [comment]
This looks like it would also avoid the hacky stuff we currently do to render markdown search results (markdown render on the server, parse HTML, highlight code in HTML on the client, reinject it into the HTML).

Funnily we have a markdown renderer on our docs page that syntax highlights code blocks (and it wasn't difficult for me to add that). Kind of weird that our main product still doesn't.

**Comment by slimsag** [comment]
Yes, I agree this would help resolve the debt in markdown search result rendering, which is a good reason to prioritize this work. I actually meant to prioritize this work earlier when @farhan implemented that logic.

We can perform this work _properly_ once https://github.com/sourcegraph/sourcegraph/issues/2369 is resolved.

**Comment by felixfbecker** [comment]
Yet another issue: https://github.com/sourcegraph/sourcegraph/issues/2592

**Comment by slimsag** [comment]
#2369 is resolved, so we can prioritize this work whenever.

The implementation should be adapting your existing work @felixfbecker in the docsite, but using `pkg/highlight.Code` instead of the other syntax highlighter you pulled in. After that, we will have a good/proper implementation of highlighting for markdown snippets. Given you were able to do that, I assume the work will be straightforward -- we just need to do it.

**Comment by ryan-blunden** [comment]
Have we considered using something like [highlight.js](https://highlightjs.org/)?

**Comment by slimsag** [comment]
Back when I investigated syntax highlighting, we found highlight.js to be very slow and since it doesn't use standard syntax highlighting files (most syntax highlighters unfortunately do not), it doesn't support many languages. So we can't use it for highlighting of regular files.

It may be fine for highlighting markdown snippets (we use it for highlighting hover tooltips, too), but we already do markdown rendering on the backend for the rest of the app so it makes sense to do this there as well I think. Then we get consistent language support, the theme is the same, etc.

**Comment by ryan-blunden** [comment]
Gotcha! Thanks.

**Comment by slimsag** [comment]
I did a small writeup of this a few months back, if anyone is interested: https://news.ycombinator.com/item?id=17932872

**Comment by attfarhan** [comment]
Since this would solve a lot of the search bugs that I've been spending time on, and improve users' search experience, I'm going to prioritize this for 3.3.

**Comment by camdencheek** [comment]
Reassigned to code intel since they own highlighting. With treesitter highlighting, does this become easier?

**Comment by macraig** [comment]
@tjdevries tagging you as the tree-sitter guru, but feel free to redirect to other members of the language tools team.

**Comment by fkling** [comment]
Well, we are definitely highlighting code somehow these days. I'll close this for now.
![2024-02-06_11-52](https://github.com/sourcegraph/sourcegraph/assets/179026/9a98400e-692c-49d9-993b-47a2ee836521)
