### ISSUE TITLE
insights: Isolate the code insights background jobs from repo-updater

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#21531]
Currently a number of background [jobs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/background.go#L28) are started for the code insights backend that currently live within the scope of the repo-updater service.

Code insights should migrate to a worker model ( #16197) to reduce the operational impact on other services. This is also necessary to facilitate future horizontal scaling needs for the code insights backend.

**Comment by coury-clark** [comment]
I had a brief conversation with @slimsag about this. It seems we have the possibility of doing a quick and dirty version of this split by copying the repo-updater deployment configs and renaming to a new service, alias the docker image in CI, and add an argument to repo-updater that would key to different "[runtimes](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@insights/rate-limiters/-/blob/enterprise/cmd/repo-updater/main.go?utm_product_name=GoLand&utm_product_version=GoLand#L55:1)" - ie repo-updater, insights, monitor, etc.

What are the thoughts around something like this? Is it worth doing even if it's not the ideal state?

**Comment by coury-clark** [comment]
Pinging some of the people from #16197
@tsenart  
@efritz

**Comment by efritz** [comment]
There are other things that should go in such a service that are in the frontend because it's ... easy to add to the monolith.

- A lot of the code intel background jobs (commit graph updating, auto-index scheduling, dependency indexing)
- Out of band migrations that run in the frontend
- Telemetry pings

The precise-code-intel-worker could actually be task within this new "worker" service as well.

It would be nice for these "runtimes" to be pretty sliceable, so that if one background service is causing trouble it can be resource isolate by a site admin. The commit graph updater had a regression that kept crashing frontends - would be nice to be able to disable/move these types of background task groups individually. For example, code intel would have the following runtimes:

- commit graph updater (frontend)
- indexability updater (frontend)
- index scheduler (frontend)
- dependency index scheduler (frontend)
- dependency index worker (frontend)
- precise code intel worker (already split)

This does leave some design work around how to make sure that adding new services make it all the way to a customer deployment (if they have to enable it with an envvar or add it to a deployment list, many will forget).

I was actually going to propose this as my dev-exp project, but I'm willing to share/take up whatever work moves us towards this goal. I'm willing to go deep or hands-off/advisory on this, depending on urgency and how excited other people are to work on this type of project.

**Comment by coury-clark** [comment]
I think that makes a lot of sense. Just FYI I opened this ticket just for the insights team to be able to track some work we might need to do before the end of the year. That isn't to say other services don't have this same problem.

My question right now is do you think there is any value in accomplishing some small part of this (just isolating the container) and working towards these other goals incrementally? Or would we be creating more of a debt by doing this the wrong way than we currently have (something relatively stable)?

**Comment by efritz** [comment]
I think I could sketch a prototype of what this service _could_ look like by mid-next week (containing all the code intel stuff that is easy to move around). Adding a service is a _bit_ non-trivial because we have a number of deployment environments and docs to consider (but it's not all that difficult either).

Is this an issue you'd like to plan with more urgency than that?

**Comment by coury-clark** [comment]
That sounds great, and there isn't really a rush. This is something that has been brought up to me multiple times, and I think that given our goals of beta in end of year this is probably something we want to have addressed by then before we roll out to customers.

**Comment by tsenart** [comment]
> I was actually going to propose this as my dev-exp project

Given this isn't urgent for code insights, I'm *very* excited about you picking this up @efritz. I don't think we should go for a quick win that adds more debt unless absolutely necessary — we should strive for some consensus here and I think @efritz has all the context in mind already :)

**Comment by efritz** [comment]
Cool. For reference I've started a work-in-progress branch/[draft PR for visibility](https://github.com/sourcegraph/sourcegraph/pull/21537) on Friday. Will end up doing some exploration here before force pushing an actual solution for review.

**Comment by felixfbecker** [comment]
@coury-clark can you put a quick estimate on this issue?

**Comment by efritz** [comment]
The worker is ready for other things to be registered into it. I can help @coury-clark with migrating code. I'd estimate moving a few background routines to another service should be as easy as:

1. Move the code for the job into enterprise/cmd/worker/internal/codeinsights
2. Register it in the worker main function
3. Adding the job type to https://docs.sourcegraph.com/admin/workers
4. Move any existing metric dashboards over to the new service

**Comment by coury-clark** [comment]
Thanks @efritz. I poked around the code today and I have some questions, but overall it seems pretty straight forward. I'll reach out when we get to this work.

**Comment by coury-clark** [comment]
Some notes on implementation for code insights:

Right now we have little need for splitting our individual jobs out, so I'm going to limit the scope of this change to migrating code insights from `repo-updater` to `worker`. Then I will open a ticket and scope out the work to migrate our horizontally scalable jobs to individual `worker` jobs.

Another thing to note is that we have some customers that have set the environment variable `DISABLE_CODE_INSIGHTS=false` for various reasons on the repo-updater service. This will need to be set on the `worker` service for those customers after this change. I'll also be updating the [documentation](https://docs.sourcegraph.com/dev/background-information/insights/backend) to reflect the same.
