### ISSUE TITLE
Border/shadow around search quick help button

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#21554]
The quick help button that appears beside the search bar in the top right corner has a very light grey border/shadow around it:
<img width="107" alt="CleanShot 2021-05-31 at 16 22 16@2x" src="https://user-images.githubusercontent.com/17293/120207288-89222d00-c22c-11eb-8522-550c8c685c3f.png">

**Comment by pdubroy** [comment]
The problem seems to be the `box-shadow` on `.SearchBox-module__search-box`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@53935d64db74f2bebffb5c6c662e3d58cdb762c4/-/blob/client/web/src/search/input/SearchBox.module.scss#L11

**Comment by limitedmage** [comment]
There’s 3 ways to fix this:

a) remove shadow altogether (honestly to me the shadow is so subtle I can’t even notice it’s there)
b) remove shadow for all sizes except XS
c) do some refactoring/potential code duplication with conditional hiding so the shadow works in all sizes (might be expensive and also throwaway because we’re eventually removing that help button)

I personally vote a).

**Comment by limitedmage** [comment]
We'll go with a) and then re-add the shadow onces the Search Reference work is complete (see https://github.com/sourcegraph/sourcegraph/issues/21592)
