### ISSUE TITLE
Regex Search Capture Groups

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21579]
_Moving this to a more formal and concrete GitHub issue since we've gotten [more feedback](https://sourcegraph.productboard.com/insights/my-inbox/features/8057379/insights) that this is important, previous context in [this Slack thread](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1615571214206100) started on March 12th._

## Use case

For code insights, we're getting a [strong stream of feedback](https://sourcegraph.productboard.com/insights/my-inbox/features/8057379/insights) asking for the use case of tracking not a specific constant search query as a series, but tracking a dynamic _part_ of a search query.

An example of this is this code insight tracking Java versions:

<img src="https://user-images.githubusercontent.com/10532611/120240710-84c43700-c261-11eb-893f-71b5eca193f7.png" width="350"/>

This is currently only possible by running predefined search queries for each predefined version, which means it can never actually cover the full version spectrum and doesn't solve the user need especially when the software in question has _many_ releases.

## Feature request

What we'd like to do, is let the user define the search query with a **dynamic capture group**, like `java_version=(\d+\.\d+)`, and then be able to get back from the search GraphQL API the value of the capture group for each result, e.g. `1.6`, `1.7`, `1.7`, ... so we can group and count them (and we can take care of the grouping and counting).

In the simplified example above, we could of course easily group on the whole `java_version=1.7` string, but this is not possible if there is any other dynamic part of the query that should _not_ be grouped on, e.g. `(?:apk add|apt-get install) java-(\d\.\d)`.

### API

In concrete API interface terms, this is what I'd imagine:

```graphql
type LineMatch {
    # ...
	
	"""
	The values of any capture groups in the query for this line match, similar to regex APIs in many languages.
    Index 0 is the whole match, 1 the first capture group (if exists), 2 the second (if exists), etc.
    `null` if the query is not a regex pattern type.
	"""
    captureGroups: [String!]
}
```

## Alternatives

@keegancsmith [indicated on Slack](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1615571614206400?thread_ts=1615571214.206100&cid=CHEKCRWKV) that this would be a post-processing step in the backend anyway (which is fine with us).

This brings up the idea that we can try to do this "post-processing" ourselves in the client, but that would mean:

- We would use a regex flavor (JS) that might be subtly different from what is used in search, potentially resulting in mismatches and subtle edge cases.
- We would need to extract the regex out of the search query entered by the user. With the complexity of our search query syntax today with parenthesized expressions, AND/OR, predicates, etc this is non-trivial and we would probably need to reuse the TS search query parser.
  - The search query parser is currently not reusable in different repos as an NPM package.
    - Even if it was, we would become a downstream dependent on the parser and the search syntax, and any update in the future to the search query syntax would probably break us and needs a synchronized update & change on our end.
  - The parser is not enough to know which AND/OR branch was taken, which needs the search evaluation logic.
- We have to fetch all results through GraphQL and post-match the regex on the matching line, presumably on the [`preview` field](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b37b84400abcbb2f6754b08b2c7c6e8b0d3f9d47/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L4151:5) as the only option. The GraphQL API lacks documentation for this and [returns different things depending on the pattern type](https://github.com/sourcegraph/sourcegraph/issues/11134), making this approach not work for structural search and generally was indicated as a fuzzily spec'd field that shouldn't be used. Fetching file content one by one is a non-starter for code insights, as having to fetch all previews as opposed to only the match count is already pretty bad, making one extra request per result would be way to slow.
- General search users will not get to enjoy this feature for their use cases (neither through the search UI nor through the CLI or API).
- We're introducing a search feature just for code insights and need to educate users that this is a special feature that only exists for search queries in the context of code insights.

**Comment by rvantonder** [comment]
@felixfbecker just want to say I read through this, thanks for the write up. Before reading I also thought doing this client side is a reasonable first pass, but I think the nice way you laid out the issues makes me think otherwise. 

For regex dialects and expressions (and/or) I was thinking you could just punt on these initially since although it's prone to failing on edge cases / advanced usage, the simple cases will probably work with shared (simple) regex dialect and without support for expressions. But that combined with the idea of using preview (shudder) and  that it is a good idea anyway, makes me think it may be better (not easier nor faster) to do this in backend.

Our `results` code is more up to the task now with @camdencheek's changes, but there are still things that worry me about how and when we postprocess results, in a way that I can't give a clear "this is how / where I think we should implement this". It will need time to look into. I'm personally tied up the next 4 weeks improving the search inputs code / faster queries, so probably will not have time to investigate this sooner than that, though I think we can provide guidance sooner than that.

Re: the specific details interface, I would say make this an environment result type. I.e., named variables and values. The anonymous capture groups and convention to use ordering in a data structure to infer them is awkward, and then there's also the possibility of named regex groups (it would be a plus to give this to our users), and this environment result type can better share regex and structural search results. E.g.,

```json
   "environment":[
      {
         "variable":"$1",
         "value":"\"hello!\"",
         "range":{
            "start":{
               "offset":7,
               "line":1,
               "column":8
            },
            "end":{
               "offset":15,
               "line":1,
               "column":16
            }
         }
      },
      {
         "variable":"named_arg_or_whatever",
         "value":"\"world!\"",
         "range":{
            "..."
         }
      }
   ]
```

Also let's not import the trap of restricting ourselves to `lines` again. Even if we do not yet internally process multiline results, we could totally postprocess single lines and turn them into logical multiline results in this environment type. Big plus potentially. If we're agreed on that, then the thing to keep in mind here is (a) we will need to mint a new environment type, which we can target as a post processing step of our existing result types and (b) to support expressions we will need to either implement or extend evaluation the evaluation function over this new minted type for merge operations set union, intersection, and subtraction, corresponding to `and`, `or`, and `not`. Tying that evaluation into our current result processing code will probably be the most time consuming part.

**Comment by rvantonder** [comment]
OK it's implemented for file matches. 

[Example](https://sourcegraph.com/api/console#%7B%22operationName%22%3A%22Run%22%2C%22query%22%3A%22query%20Run(%24query%3A%20String!)%20%7B%5Cn%20%20compute(query%3A%20%24query)%20%7B%5Cn%20%20%20%20...%20on%20ComputeMatchContext%20%7B%5Cn%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20commit%5Cn%20%20%20%20%20%20path%5Cn%20%20%20%20%20%20matches%20%7B%5Cn%20%20%20%20%20%20%20%20value%5Cn%20%20%20%20%20%20%20%20range%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20start%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20end%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20environment%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20variable%5Cn%20%20%20%20%20%20%20%20%20%20value%5Cn%20%20%20%20%20%20%20%20%20%20range%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20start%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20end%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22%2Ffunc%20(%5C%5C%5C%5Cw%2B)%5C%5C%5C%5C((%3FP%3Cargs%3E%5C%5C%5C%5Cw%2B)%5C%5C%5C%5C)%2F%5C%22%5Cn%7D%22%7D).

Let's follow up in separate issues for supporting commit search results and structural search, if needed.
