### ISSUE TITLE
e2e tests: The ssh command responded with a non-zero exit status

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#21594]
From https://github.com/sourcegraph/sourcegraph/issues/21249 

We should work to root cause the ssh issues with Vagrant

> (18) The SSH command responded with a non-zero exit status.
(17) An error occurred in the underlying SSH library that Vagrant uses
(6) SSH connection was refused!

**Comment by davejrt** [comment]
My understanding is that in some way shape or form...vagrant cannot connect to the machine it creates, whether that be due to a timeout or an error on the machine itself. In my experience I have never manually created a machine that I cannot ssh into. 

I would insert some logic that at least attempts to retry in bringing the machine up before the text exits completely and causes a failure.

**Comment by pdubroy** [comment]
Awesome! 🎉
