### ISSUE TITLE
Clarity on how to configure SRC_GIT_SERVERS in Kubernetes

### ISSUE THREAD

**Issue by northyg** [sourcegraph/sourcegraph#21657]
#### Describe the issue

There is some confusion on how / where to update `SRC_GIT_SERVERS` and the docs aren't quite clear. 

This line is the line from the docs:

> Update the SRC_GIT_SERVERS environment variable in the frontend service to reflect the number of replicas.

* Which file is SRC_GIT_SERVERS located in? Is it supposed to go in frontend.service.yaml ?
* Is it there by default or does it need to be added? 

#### Where is the issue located?

* https://docs.sourcegraph.com/admin/install/kubernetes/configure#configure-gitserver-replica-count

#### Suggested resolution

* Goal is to provide clarity on how to use this config and provide better examples.

**Comment by ggilmore** [comment]
@northyg `sourcegraph-frontend.Deployment.yaml` is the file that needs to be updated. "The frontend service" is a colloquial statement for Deployments and StatefulSets because those are the only types that deal with the actual configuration (including environment variables ) of the containers themselves. The value is already there by default, but it needs to be updated when the replicas change.
