### ISSUE TITLE
Diff view scrolling

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21662]
Two oddities about how the diff view scrolls are inconsistent with the other areas of the site.

# Vertical scroll location
The page scroll bar currently appears between the actions panel and the diff view:

![image](https://user-images.githubusercontent.com/539268/120528324-2b0e5a80-c390-11eb-9884-e578a7e50d95.png)

Move it to the sidebar to align it with how the rest of the site scrolls content.

# Fixed area
Additionally, the diff view fixes elements of the screen differently than the search results:

![image](https://user-images.githubusercontent.com/539268/120564111-0a112e00-c3bf-11eb-943f-c7528ab604d0.png)

Unify how this scrolling occurs.

**Comment by umpox** [comment]
@rrhyne Please could you clarify the changes required here?

The positioning of the scrollbar and other elements is consistent with the typical code view (e.g. [this file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_query.go?subtree=true)). I think it's more important to be consistent with this view instead of the search results.

What do you think?

**Comment by rrhyne** [comment]
It makes sense to be consistent with the size of the fixed area across search, diff, and code view pages. There is no visual indicator on diff and code views to partition the elements, so the scroll disappears into the background. It should follow the search results example where the top is fixed at the divider line between the search bar and content.

I'm less convinced at the width of the scroll extending to the browser and having the scroll bar appear to the right of the extensions. I believe I filed that part of the issue for @5h1rU who felt this was in error. 

@5h1rU you should weigh in here.

**Comment by pdubroy** [comment]
I also feel that the scroll bar position isn't quite right. Compare where it appears on the search results:

![CleanShot 2021-07-08 at 12 13 05](https://user-images.githubusercontent.com/17293/124905912-d2615b80-dfe6-11eb-8e66-504cb3b27b9e.png)

...to where it appears on the diff view:

![CleanShot 2021-07-08 at 12 12 04](https://user-images.githubusercontent.com/17293/124905955-dc835a00-dfe6-11eb-9bf3-e752399d4ee2.png)

A simple change (which looks more consistent to me, anyways) would be to use _padding_ rather than _margin_ on the RepositoryCommitPage, which means the scrollbar appears further to the right and no longer overlaps with any of the content on the diff page.

![CleanShot 2021-07-08 at 12 14 54](https://user-images.githubusercontent.com/17293/124906278-2ff5a800-dfe7-11eb-8bdb-053c438178f7.png)

**Comment by pdubroy** [comment]
After taking a look at some of the other repository subpages (API Docs / Commits / Branches / Tags / Compare / Contributors), I think I understand the point about the scroll bar better. Those pages are scroll like this:


https://user-images.githubusercontent.com/17293/124910201-a09ec380-dfeb-11eb-9604-43bb89e739cc.mp4

And here is what the scroll bar looks like:

https://user-images.githubusercontent.com/17293/124910254-b14f3980-dfeb-11eb-8a07-0bbc3ac2a86d.mp4

**Comment by pdubroy** [comment]
@rrhyne The above PR would make the diff view page scroll in the same way as the other pages. Let me know what you think.

**Comment by 5h1rU** [comment]
It solves the problem for this section. I swear I tried the same change 🤣, but probably the design refresh changed something in the layout.

Thanks @pdubroy

**Comment by rrhyne** [comment]
Love it. I'm ok with closing this ticket based on those changes if @5h1rU is happy!
