### ISSUE TITLE
Is `// 🚨 SECURITY:` a good way of making the app secure?

### ISSUE THREAD

**Issue by jimbojetlag** [sourcegraph/sourcegraph#217]
I noticed that there is no central permission system, and the permission checking is scattered all over the frontend packages, with the comment prefix of `// 🚨 SECURITY:`. The fact that you need to make a security warning in the comment accented with an emoji implies that the developers do not have confidence in the permission system.

I see 2 problems here:

1. If I am correct, by default the frontend can allow requests, unless otherwise rejected. This is not secure. By default the requests must be denied unless otherwise allowed by the permission system.
2. The lack of a central system for the permission system, preferably a single file, makes it difficult, specially for a new developer, to have a mental map of who can access what under which condition.

Having said these, I am open to know the upsides of the current system.

**Comment by nicksnyder** [comment]
> I noticed that there is no central permission system

We do have centralized authentication handling, but not authorization handling. Authorization is currently handled on a per-endpoint basis. This is mostly an artifact of the fact that we haven't needed to add a lot of authorization code to the app until recently. When we started building Sourcegraph we made two simplifying assumptions (1) there aren't many reasons for individual users to sign in to a Sourcegraph instance, and (2) many companies allow all engineers to see all source code.

We have recently introduced more features that make (1) not true (e.g. code discussions), and we have current and future customers where (2) is not true (which implicitly makes 1 not true also).

We are still gathering requirements here which is why you don't see a generic solution in the codebase. You can view, and comment, on our plans to add ACLs here:
https://sourcegraph.com/github.com/sourcegraph/about/-/blob/projects/acls.md?view=code

The `// 🚨 SECURITY:` comment makes it obvious when devs are using/editing/reviewing code that is security sensitive (both authentication and authorization).

**Comment by nicksnyder** [comment]
I am going to close this as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/134 and in favor of discussing ACLs on the linked document.
