### ISSUE TITLE
Redesigned repo type search results look meh

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#21732]
<img width="1277" alt="Screen Shot 2021-06-04 at 12 31 25" src="https://user-images.githubusercontent.com/67471/120795171-0c939500-c531-11eb-9a33-b64696dc4e07.png">

**Comment by valerybugakov** [comment]
@sourcegraph/design any thoughts on how we can improve it?

**Comment by eseliger** [comment]
The design mockups show quite some more information. We'd need to expose it and can then show it here. Not sure who owns that and what the timeline for it is, though.

**Comment by rrhyne** [comment]
In the end, file and repo matches will look more like this:

![image](https://user-images.githubusercontent.com/539268/120812714-16ea6a80-c502-11eb-9b2f-c3eb03f58b9f.png)

We do not currently collect that data in a manner that is performant for streaming search. Search product has a spike to determine effort here. I hope that would be complete by the next enterprise release. If it is not, we may alter the design. 

@lguychard

**Comment by quinnkeast** [comment]
@rrhyne one concern I have about this approach is that it presents the metadata as the "content," rather than the repository itself. The repository is the result item here, but the metadata in the white container is the first focal point for each result. It'd be interesting to explore if there's a way to elevate the repository itself as the content in these cases rather than the metadata.

While it doesn't contain metadata, an earlier design exploration listed each repository as an item, which captures the content-focus difference:

<img width="1284" alt="CleanShot 2021-06-04 at 16 00 37@2x" src="https://user-images.githubusercontent.com/6304497/120813293-0b249580-c54e-11eb-85aa-d57450b35f79.png">

@AlicjaSuska for visibility.

**Comment by rrhyne** [comment]
Metadata is content material to the selection of a repository.

User testing revealed that users need to make decisions about which result is the most relevant based on that metadata.  Additionally, customers want to be able to search repository metadata. While that isn't possible now, this change sets the stage for being able to query that data. 

Outside of the content issues, a grouping of matches in that manner isn't possible due to the variety of ways users may search or select content from searches.

**Comment by camdencheek** [comment]
Closing since results have since been redesigned
