### ISSUE TITLE
Sourcegraph behind nginx as reverse proxy - redirect problem

### ISSUE THREAD

**Issue by FrankEppinkMsgGillardon** [sourcegraph/sourcegraph#2180]
#### Question description
I am struggling to get Sourcegraph work behind an nginx-reverse-proxy.
I setup nginx to proxy-pass to Sourcegraph which seems to work fine at first, i.e. the request is forwarded correctly to Sourcegraph running on http://<ip-address>:<port>/:      
```
  location /sourcegraph/
        {
                proxy_set_header    Host $http_host;
                proxy_pass          http://<ip-address>:<port>/;              
        }
```
The problem is the redirect location returned by Sourcegraph:
```        
Location: /sign-in?returnTo=%2F
```
which of course is wrong and leads to a 404.
In my opinion the following redirect location would work fine:
```        
Location: /sourcegraph/sign-in?returnTo=%2F
```

#### Is your question related to a problem? If so, please describe or link to another issue.

I experimented with different nginx settings (e.g. proxy_redirect) and setting the external_app in Sourcegraph, but I did not manage to change the location

https://github.com/sourcegraph/sourcegraph/issues/73
https://github.com/sourcegraph/sourcegraph/issues/119
and
https://stackoverflow.com/questions/51223293/nginx-reverse-proxy-subdirectory-rewrites-for-sourcegraph
sound interesting, but did not really help me.

Thanks for your support
Frank

**Comment by sqs** [comment]
In general, Sourcegraph is not (yet) intended to run at a subdirectory. It expects to run at the root path of a host. Can you set it up to run at the root path?

If not, can you help us understand why you want to run it under a subdirectory?

It's theoretically possible for Sourcegraph to support this, but we are reluctant because it is a rare use case and also involves security issues with cookies, same-origin policy, etc.

**Comment by FrankEppinkMsgGillardon** [comment]
We are now running sourcegraph without a subdirectory in the "location" statement", so we no longer have the redirect problem. I do however think it would be helpful if sourcegraph supports subdirectories.

But as we have a working version, closing this issue.

Thanks
Frank

**Comment by alexandnpu** [comment]
@sqs , I have the same problem as the issue stated. Luckily for me, i found the reason that sourcegraph does not support subdirectories right now, so it saves my day.

I can say why I need to run it under a subdirectory. Because it is not easy for me to apply internal domain name in my company. So we use subdirectories to separate our businesses

team1.example.com/business1
team1.example.com/business2

one team has only one domain name.

**Comment by KashingLiu** [comment]
> @sqs , I have the same problem as the issue stated. Luckily for me, i found the reason that sourcegraph does not support subdirectories right now, so it saves my day.
> 
> I can say why I need to run it under a subdirectory. Because it is not easy for me to apply internal domain names in my company. So we use subdirectories to separate our businesses
> 
> team1.example.com/business1
> team1.example.com/business2
> 
> one team has only one domain name.

@alexandnpu Hello, I have the same problem too. I want to use the Sourcegraph under a subdirectories, but I don't know how to set it. I tried to use NGINX like this:
`location /source {
proxy_pass http://sourcegraph.example.com:7080;
}`
But it redirect to http://sourcegraph.example.com/sign-in?returnTo=%2Fsource, but there is not a route `sign-in`.
How can we solve this problem? Thanks a lot

**Comment by alexandnpu** [comment]
@KashingLiu , Right now, I have no solution either. I am also waiting for the official support.
