### ISSUE TITLE
Feature request: hover results on clang `#includes` paths

### ISSUE THREAD

**Issue by northyg** [sourcegraph/sourcegraph#21838]
#### Feature request description

Filing this feature request on behalf of a customer. Essentially in this case C/C++ files are not showing their corresponding files because customer is using relative paths.
 
Example that doesn't work because of the path:
`#include <../dir1/file.cc>`

Because of this, the def/finds refs popup does not work.

It's my understanding that this functionality works in similar products to Sourcegraph, such as OpenGrok. Having this functionality would be incredibly useful!

**Comment by leahnp** [comment]
This is something that gets requested a lot at our firm, it would be great to get it in a future release

**Comment by lguychard** [comment]
@northyg this [came up in triage](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1638955886273500), and I'm trying to understand what the original issue is.

I'm a bit confused, because the issue title mentions supporting relative paths in [`.gitmodule`](https://docs.sourcegraph.com/admin/how-to/submodule-configuration), but the issue description mentions a relative path that would live in a source file (c/cpp `#include` directive). In neither case is the connection to the code intelligence popup super clear.

Is this about:
1. Not being able to click through to submodules from the repository view / file tree when they are specified as relative paths in `.gitmodule`? (eg. the documented limitation from our docs that we currently do not support relative path setups for submodules, which is orthogonal from code intel).
2. Not being able to see hovers / defs / refs for symbols that are defined in files imported with relative paths (_and_ whose relative paths are in submodules?). If so, would that be with precise code intelligence (through `lsif-clang`?), or search-based intelligence?

Thanks!

**Comment by macraig** [comment]
@northyg @alexfogg resurfacing this thread as per @lguychard 's comment above it's a bit unclear where this should fall in terms of ownership. Thanks!

**Comment by DaedalusG** [comment]
Giving this a quick refresher -- 

To re-summarize in languages like Java we can resolve hovers for imports, for example:
`repo:^github\.com/elastic/elasticsearch$@985a2fb file:^server/src/main/java/org/elasticsearch/index/codec/CodecService\.java`
([link](https://sourcegraph.com/github.com/elastic/elasticsearch@985a2fb9b74e72b9c91517f34d8712018ab0fb61/-/blob/server/src/main/java/org/elasticsearch/index/codec/CodecService.java?L13:26-13:32#tab=def))
![Screenshot 2023-03-06 at 11 34 22 AM](https://user-images.githubusercontent.com/13024338/223212456-595fb6b7-4665-45d0-89a8-677c4815a45b.png)

What is desired here is the same behavior for C `includes` for example:
`repo:^github\.com/tensorflow/tensorflow$ file:^tensorflow/core/graph/validate\.h`
([link](https://sourcegraph.com/github.com/tensorflow/tensorflow/-/blob/tensorflow/core/graph/validate.h?subtree=true))

Here a hover on `tensorflow/lite/core/c/common.h` would ideally allow a user to jump to `https://sourcegraph.com/github.com/tensorflow/tensorflow/-/blob/tensorflow/lite/core/c/common.h`

Include
![Screenshot 2023-03-06 at 11 41 27 AM](https://user-images.githubusercontent.com/13024338/223213831-d7b48889-255a-4280-b2df-1ea8d0cdab93.png)

File to jump to
![Screenshot 2023-03-06 at 11 42 13 AM](https://user-images.githubusercontent.com/13024338/223213895-a36f6ba3-93f3-47a0-833d-479e9598aeef.png)

@varungandhi-src any chance you can provide insights about the feasibility of implementing this request?

**Comment by DaedalusG** [comment]
Had a quick chat with Varun -- this feature is on the roadmap for planned work on scip-clang
https://github.com/sourcegraph/scip-clang/issues/2

**Comment by varungandhi-src** [comment]
Fixed in https://github.com/sourcegraph/scip-clang/pull/166. I will be publishing a scip-clang release next week, which includes this.
