### ISSUE TITLE
Improve Performance For Monorepos (Unindexed Search)

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#21855]
#### Feature request description

Improved performance for unindexed monorepo search.

#### Is your feature request related to a problem? If so, please describe.

Many company's codebases contain monorepos. When users attempt to make searches over commits in monorepos, or attempt to open the commit history of a file using the show history button, results are often returned in tens of seconds. 

A sufficiently large repo (say 70g) may result in slow searches for any repos associated with the gitserver responsible for the monorepo. Horizontal scaling of gitservers proves ineffective for alleviating this concern. Intrinsically companies using monorepos will make the majority of their searches over the monorepo. The following grafana chart illustrates memory usage in an instance where horizontal scaling was attempted to resolve performance issues:
![image (3)](https://user-images.githubusercontent.com/13024338/119054684-eb517700-b97c-11eb-9055-c862312bdc85.png)

From another issue related to monorepo performance we can see an illustration of the problem:

> Unindexed commits need to be fetched by symbols. To show you how bad the delay is we can luckily grep the logs for the "Long exec request" logs from the symbols service:
```
$ grep client=symbols sourcegraph_0.log \
  | grep -o 'cmd_duration_ms=[0-9]*' \
  | cut -d '=' -f 2 \
  | python2 ~/src/github.com/bitly/data_hacks/data_hacks/histogram.py
# NumSamples = 130; Min = 60241.00; Max = 509165.00
# Mean = 245271.853846; Variance = 10510181196.570948; SD = 102519.174775; Median 203419.000000
# each ∎ represents a count of 1
60241.0000 - 105133.4000 [     2]: ∎∎
105133.4000 - 150025.8000 [     3]: ∎∎∎
150025.8000 - 194918.2000 [    51]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
194918.2000 - 239810.6000 [    28]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
239810.6000 - 284703.0000 [    11]: ∎∎∎∎∎∎∎∎∎∎∎
284703.0000 - 329595.4000 [     7]: ∎∎∎∎∎∎∎
329595.4000 - 374487.8000 [     9]: ∎∎∎∎∎∎∎∎∎
374487.8000 - 419380.2000 [     5]: ∎∎∎∎∎
419380.2000 - 464272.6000 [     6]: ∎∎∎∎∎∎
464272.6000 - 509165.0000 [     8]: ∎∎∎∎∎∎∎∎
```
> A mean of 245 seconds sucks! I'm not sure we have anything actionable here other than unindexed commits are slow in monorepos and always have been.

Issues with gitserver and symbols may also trigger alarming code-intel warnings:
![image (5)](https://user-images.githubusercontent.com/13024338/119055533-1092b500-b97e-11eb-865b-79e4a3e75987.png)

In general, the issues with unindexed monorepo searches seem to stem primarily from the gitserver. With gitserver sends symbols a working copy of a repo at a commit, and then symbols parses that working copy. In instances where poor monorepo performance has been observed, CPU usage by symbols has been low, while CPU usage for the gitserver associated with the monorepo has been very high. 

#### Describe alternatives you've considered.
I have heard two viable suggestions relating to how to improve performance.

1. From a Sourcegraph customer:

> 95% of queries will happen for our monorepo, but it [picks](https://github.com/sourcegraph/sourcegraph/blob/fabb7dba2c3d5537346ab878c98f5667a456ac22/internal/gitserver/client.go#L114) the server based on a hash of the repo, sooo….. it’s always gonna hit one server. Presumably this is so one gitserver can be warm for a particular repo but in our case….our one repo is a little too hot :sweat_smile:, if we could just round robin or even just totally randomize i think it would instantly fix a lot of problems we have.

2. It may be outlandish but if the major issue here is gitserver fetching info about monorepos to pass to symbols is the hanging problem here, would it be reasonable to implement some sort of [virtualized git](https://devblogs.microsoft.com/bharry/the-largest-git-repo-on-the-planet/) in the way that Microsoft has? 

#### Additional context

I've opened this issue to start a brainstorming area to explore problems that Sourcegraph has when dealing with monorepos. Any other further thoughts about performance with monorepos are welcome here, this issue is specific to unindexed search only because this is the area of performance that I have info on.

**Comment by slimsag** [comment]
Great write-up!

One thing I wanted to call out here is that one way to help mitigate this (but definitely won't solve it in all cases) is to scale gitserver vertically more than horizontally: 2-3 really beefy gitservers with a ton of CPU/memory will _definitely_ behave better than the same amount of resources divided up across many smaller gitservers (due to the fact that a single repo gets put on a single gitserver.)

This issue also affects the `symbols` service (which powers the "symbols" sidebar) I believe in the same way.

**Comment by slimsag** [comment]
cc @sourcegraph/core-application to consider this issue since it is a quite core infrastructure problem

**Comment by keegancsmith** [comment]
Great write-up! Thanks for creating this issue.

> Presumably this is so one gitserver can be warm for a particular repo but in our case….our one repo is a little too hot 😅, if we could just round robin or even just totally randomize i think it would instantly fix a lot of problems we have.

This is correct, and some replicas would help a lot here. It isn't the most straight-forward since we need to solve cross replica writes (eg you fetch a new version of main. make sure we have the same main on all replicas). But there is likely something simple one can do here targetting the problematic queries.

> It may be outlandish but if the major issue here is gitserver fetching info about monorepos to pass to symbols is the hanging problem here, would it be reasonable to implement some sort of [virtualized git](https://devblogs.microsoft.com/bharry/the-largest-git-repo-on-the-planet/) in the way that Microsoft has?

If I am not mistaken a lot of the virtualized git stuff (and in general the techniques used by Google and Facebook) are around the working copy. By making gitserver speak the virtual protocol, maybe there would be benefits in our internal clients to avoid extra work. However, I think we would still run into a lot of the same issues.

> I've opened this issue to start a brainstorming area to explore problems that Sourcegraph has when dealing with monorepos. Any other further thoughts about performance with monorepos are welcome here, this issue is specific to unindexed search only because this is the area of performance that I have info on.

Great! I'll write down some random idea seeds:

- shallow clones + reuse :: symbols currently does a `git archive` per commit it wants to search. Instead it could do shallow clones/fetches. IE keep the git repo around and only fetch what it is missing. This may also cause lots of issues, since I believe shallow fetching is computationally expensive for the serverside.
- git perf :: enable all the git performance features. microsoft has been doing a bunch of perf work on git, a lot of it requires optional opt-in. We should make sure we have all of it turned on.
- archive service :: an intermediate archive service which tries to intelligently reduce load on our internal gitserver. This service could cache archives (which other services may ask for), or try do incremental archive fetching (implement minimal parts of git's object model).
- repo sharding :: have a standard way to divide up a repository. Then any operation on the repository requires aggregating across the shards of it. This is a pretty standard technique for breaking up large things in distributed systems. The hard part is deciding where to draw the lines. Maybe can do user configurable "shard directories". eg imagine splitting sourcegraph up by all its top-level dirs. This would somewhat evenly split the repo up into more manageable chunks.

**Comment by DaedalusG** [comment]
Wanting to flag graphQL query timeout for large repos here as well (experiencing some timeouts in dogfood on initial searches of our large perforce repo): https://github.com/sourcegraph/sourcegraph/issues/6878

**Comment by tsenart** [comment]
What specific kinds of queries or use cases are some of our customers doing that can't be indexed by Zoekt?

Is monorepo support about (in order of priority):
1. Fast commit and diff search
1. Fast commit history view
1. Anything else?

**Comment by DaedalusG** [comment]
Adding a few thing to bullet 3.:

GraphQL API language query support: https://github.com/sourcegraph/customer/issues/415 (we have plans to work on improving this in the immediate future 🔥 ) 

Not as much about zoekt but...

I'd also like to note the existence of the [`gitCustomFetch` site config](https://docs.sourcegraph.com/admin/monorepo#custom-git-binaries) option. Some of our users currently employ this option to run a custom git binary, to do this they also use a custom image for the gitserver. Ideally, this option would be better documented so users wouldn't need to maintain their own image, or, we offered our own built-in custom git binary.

**Comment by DaedalusG** [comment]
Noting here that a number of our customers with monorepo's experience slow loading of the symbols sidebar and frequently receive the error message below (we are investigating the possibility of using LSIF to render symbols):

![image (10)](https://user-images.githubusercontent.com/13024338/134733763-84ff2939-0088-4db8-9210-b38068f9a74c.png)

**Comment by DaedalusG** [comment]
https://github.com/sourcegraph/sourcegraph/issues/13053

**Comment by DaedalusG** [comment]
I've created doc to advise users about Sourcegraph services to tune to help address common performance concerns related to features that default to unindexed symbols service search.
[https://docs.sourcegraph.com/admin/how-to/monorepo-issues](https://docs.sourcegraph.com/admin/how-to/monorepo-issues)

**Comment by DaedalusG** [comment]
This issue is stale, many monorepo improvements have been made since its opening, and are tracked across a variety of independent issues -- closing
