### ISSUE TITLE
Update Codecov logo

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#22205]
Codecov logo we are using currently (in the [Codecov Sourcegraph extension](https://github.com/codecov/sourcegraph-codecov)) is not aligned with their brand [guidelines](https://about.codecov.io/brand/). Please, change it to the following:

![Codecov@3](https://user-images.githubusercontent.com/20326070/122519336-a4ee4700-d012-11eb-86b6-46f769635751.png)

**Comment by anthonygedeon** [comment]
Oh! Im not participating in Hacktoberfest, I just like your software and would like to contribute to any issue you have listed

**Comment by vanesa** [comment]
That's wonderful @anthonygedeon! Yes please, feel free to make this your open source contribution. Also, please join our [Community Space](https://srcgr.ph/join-community-space) to reach support if you need any and to hang out with Sourcegraph mission driven community members 🤗 .

**Comment by muratsu** [comment]
Feel free to create a PR @anthonygedeon! You can find more detailed information on how to contribute [here](https://github.com/sourcegraph/sourcegraph/blob/main/CONTRIBUTING.md) 🚀

**Comment by anthonygedeon** [comment]
Hello!

Pertaining to the logo change for codecov, it seems the logo is getting called from a Graphql query(?) that follows the ExtensionManifest interface. 

My question is that if I wanted to update the image, should I create a codecov image component in the `sourcegraph/client/web/src/extensions/icons` and add some logic in the ExtensionCard component so that once the card is rendered it displays the rounded codecov logo instead of the square via an if-statement. In my head, this approach is pretty bad and unscalable but I have no clue where exactly the data for the images are coming from i.e:  

![extension-images](https://user-images.githubusercontent.com/47023801/140669161-718480d4-1871-4214-aea3-0c36f961617d.png)

So, where should I look in the codebase, and what is another approach that I can use to tackle this problem?

Thanks for the help

**Comment by muratsu** [comment]
Hey @anthonygedeon, the icon actually belongs to the extension itself (located [here](https://github.com/codecov/sourcegraph-codecov/). Feel free to ping me if you have any additional questions

**Comment by anthonygedeon** [comment]
Oh! I really complicated things. @muratsu should I send the pr on the [codecov repo](https://github.com/codecov/sourcegraph-codecov/) with the new image then?

**Comment by muratsu** [comment]
CC: @abeatrix

**Comment by abeatrix** [comment]
The icon has now been updated for the [extension](https://sourcegraph.com/extensions/sourcegraph/codecov), thank you so much for the help @anthonygedeon !
![image](https://user-images.githubusercontent.com/68532117/140981569-beff3cf6-d9a0-404c-8aca-032ad11009dd.png)
