### ISSUE TITLE
saml and externalURL

### ISSUE THREAD

**Issue by huasome** [sourcegraph/sourcegraph#2251]
- **Sourcegraph version:** 3.0.1
- **Platform information:** Ubuntu 18.04, Docker 5:18.09.0~3-0~ubuntu-bionic

#### Steps to reproduce:

1. Configure for saml.
2. Get error "saml auth provider requires externalURL to be set to the external URL of your site (example: https://sourcegraph.example.com)"
3. Try to configure "externalURL"
4. Get error "(root): Additional property externalURL is not allowed"

#### Expected behavior:
Per documentation, https://docs.sourcegraph.com/admin/site_config/all#externalurl-string, this is a configuration setting.

#### Actual behavior:
Error message: "(root): Additional property externalURL is not allowed"

**Comment by huasome** [comment]
![screen shot 2019-02-11 at 4 14 25 pm](https://user-images.githubusercontent.com/2467405/52602590-24065b80-2e18-11e9-8470-5c676e2eeb6b.png)

**Comment by dadlerj** [comment]
Hey @huasome, sorry, I can see why this is a bit confusing — a PR to the docs to make this more clear is coming soon. 

The answer is that the `externalURL` property is a critical configuration value that has been migrated to the [management console](https://docs.sourcegraph.com/admin/management_console), rather than the in-app configuration. You need to enter it in the console that's exposed at `https://sourcegraph.example.com:2633`. 

FYI, the password to the management console should be visible in the site-admin area — see https://docs.sourcegraph.com/admin/management_console#what-is-the-password-to-my-management-console for a screenshot

CC @slimsag in case there's anything I'm missing here

**Comment by huasome** [comment]
Yeah, that fixed it. Thanks for the help.
