### ISSUE TITLE
API docs: using URL fragments seems to prevent Google search results & OpenGraph

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#22575]
Currently each DocumentationNode is just a URL fragment not a separate URL, so how will Google results and OpenGraph previews work? Will Google treat URL fragments as their own page (so that searching for eg `http.Get` will link directly to `#http.Get` not just the `package http` page)? Seems like the answer is no: https://www.seroundtable.com/url-fragment-identifiers-in-google-search-console-30198.html.

**Comment by sqs** [comment]
I see the codeintel.graphql file mentions a `pathID` that seems to imply you considered having non-fragment URLs. Curious if this is still intended for the future.

```
A documentation page under filepath `internal/pkg/mux` with pathID `/Router/ServeHTTP/examples`.
```

**Comment by slimsag** [comment]
👋 (after-hours Stephen here, responding because I think it's interesting)

The comment you found in codeintel.graphql is still correct, but kinda outdated/misleading. All it is saying is that "a path ID is literally not a URL, and might not align with directory structure or anything else in the repo at all. It's an arbitrary string, and just happens to be separated with slashes."

LSIF indexers get to emit whatever documentation they choose, the only requirement is that it be structured: you need to say what is a page and what is a section of a page (and how those sections fit under other sections). It's a graph of documentation nodes, with some of them being marked as beginning a new page with all the nodes below it.

The Go indexer implements this by producing a single page for a Go package, with all the information on it. That matches pkg.go.dev, godoc, godoc.org, etc. and Go developer's expectations of what a good APi docs experience is like.

A Rust indexer for example would choose to do something different: it would emit one page per module in a crate, e.g. mimicking what docs.rs has chosen to do:

* https://docs.rs/rocket/0.4.7/rocket/index.html
* https://docs.rs/rocket/0.4.7/rocket/config/index.html
* etc.

There is no fundamental constraint/requirement that a single symbol be a single page, and one of the things we talked about early on is that we think that would actually be a quite bad user experience. I think it _could_ be good for Google indexing/SEO, to the detriment of user experience (unless we had separate pages for Google specifically.)

This means that, yes, OpenGraph previews and Google indexing would view singular "package" pages and index them as such today. You can get a really clear picture of what that experience looks like today through Google via e.g. `site:pkg.go.dev json.NewEncoder` - it often finds the right page, but the text/preview presented to you is totally useless basically.

To fix that and optimize for that case, we really do need "a separate page for each symbol." The data format is intentionally flexible and allows for that, i.e., nothing prevents us from just taking those logically-structured sections of documentation like all the anchor sections you see on a docs page today and rendering those as distinct pages.

Now that introduces questions like...:

* Do they need to be separate user-visible pages? Is that actually useful compared to e.g. phony pages just for Google, that then redirect to the main page?
* Will Google penalize us for having so many separate pages? (it starts to look an awful lot like spam, so I wouldn't be surprised at all if it did)
* If we did phony pages that redirect, would Google penalize us for that? (I suspect yes, but unclear if there are "other ways" to present more specific information to Google in this case)

And gets us into the clear territory of SEO - and at present it's unclear to me how much we actually want to invest in that aspect of this project vs. the on-Sourcegraph user experience aspects. This tradeoff is still an active/ongoing discussion in my view and something we're trying to get clarity on with this team.

**Comment by slimsag** [comment]
One way to achieve may be through the search integration: maybe a search that yields a single documentation result (symbol) renders that result in a way that looks like a single page dedicated to that symbol, and the current "full API docs page" view becomes more like an "explore documentation" page. ofc. this requires something more like specialized search just for API docs that does not match our current product search result styling, etc. but I think that may be true anyway for API docs.
