### ISSUE TITLE
Support local git repositories

### ISSUE THREAD

**Issue by HeinrichHartmann** [sourcegraph/sourcegraph#226]
#### Feature request description

Support importing of local git repositories, at least for the open-source on-prem version.

#### Is your feature request related to a problem? If so, please describe.

I have a bunch of git repositories on my machine that are not backed by GitHub or other SaaS services for various reasons.
They are usually organized in folders like ~/$proj-workspace or ~/src.
I would love to be able to browse them via sourcegraph.

#### Describe alternatives you've considered.

Quinn pointed me to:
https://about.sourcegraph.com/docs/config/repositories/#add-repositories-already-cloned-to-disk

This is more a workaround than a solution. Shortcomings:
- The repositories are not backed by GitHub, and do not naturally have a GitHub url like assumed there.
- I don't want to create a second copy of the repository (yes, `git clone --reference --mirror`, does copy a lot of data).
- Local changes need to be manually pushed over to sourcegraph
- (minor) Adding multiple repositories is a little tedious. Ideally I'd just be able to import all of them in one go.

**Comment by sqs** [comment]
Thank you for posting this. We would like to support this better! A few notes below.

> The repositories are not backed by GitHub, and do not naturally have a GitHub url like assumed there.

You can ignore the `github.com/my/repo` name. It's just an example. It could also be `my/repo` or just `myrepo`. (I see how it is misleading and will think of a way to improve that.)

> I don't want to create a second copy of the repository (yes, git clone --reference --mirror, does copy a lot of data).

How much of a problem is this? If the other problems were solved, would this problem be a blocker by itself?

> Local changes need to be manually pushed over to sourcegraph

I think we can solve this by inverting the instructions so that your Docker container for Sourcegraph mounts a host volume, and then `docker exec`'ing in the container a `git clone /path/to/host/volume/inside/container` command. If this makes sense to you as-is, then go ahead and try it and let me know. Otherwise you can try it when these docs are updated.

> (minor) Adding multiple repositories is a little tedious. Ideally I'd just be able to import all of them in one go.

Yes, we should make it scan a common parent/ancestor dir that contains possibly many repositories.

**Comment by keegancsmith** [comment]
Our gitserver is built with the assumption it manages the clones (and they are bare). Relaxing that assumption would need a very good reason.

But to work around that assumption you may get away with setting the origin as a filepath to the locally mounted volumes. Alternativelly you could spin something up like gitweb to expose your localy repositories via HTTP. Both of these ideas would rely on setting the `repos.list` setting.

Does that seem alright for now? Alternatively, why can't Sourcegraph just clone the repos from the origin's of the existing repositories? Are you looking to avoid the slow and extra networking to initialize all the clones?

**Comment by sqs** [comment]
@HeinrichHartmann We are planning improvements to our repository syncing now (on our roadmap at https://docs.sourcegraph.com/dev/roadmap). It would be great to hear your answers to @keegancsmith's questions above.

**Comment by sqs** [comment]
Closing in favor of #1527, which is a general tracking issue for this feature
