### ISSUE TITLE
`select:repo` does not work with `and` patterns

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#22651]
The query [`jaeger and prometheus`](http://localhost:3080/search?q=jaeger+and+prometheus&patternType=literal) works fine on Sourcegraph.com, but when you try to do [`jaeger and prometheus select:repo`](http://localhost:3080/search?q=jaeger+and+prometheus+select:repo&patternType=literal), it fails. This seems to be because [intersectMerge](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@793bd5822d7a02ab377e01f6429fa80efe18b222/-/blob/cmd/frontend/graphqlbackend/search_results.go#L507-L534) seems to be written to only merge file matches, skipping any other result types. I haven't spent the time to figure out if this is a regression, or it just never worked

Queries like `repo:sourcegraph and repo:about` work fine, apparently because we don't use intersect for repo queries. I'm not entirely sure why -- maybe we optimize this down to a single regex pattern? I didn't see where that was happening though.

**Comment by rvantonder** [comment]
I tracked this down, it's partly due to this optimization on repos: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/zoekt/indexed_search.go?L401:22&subtree=true. This returns a repo result. The bug is that the merge logic in `intersect` assumes we only ever get file matches, even though this is a repo match: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results.go?L545-571&subtree=true. It needs to handle repo matches.

For this reason, `select:file` works fine with `and`. It is only `select:repo`.

**Comment by rvantonder** [comment]
Which is why I started doing this https://github.com/sourcegraph/sourcegraph/pull/22654. And will make an attempt at fixing after.
