### ISSUE TITLE
Enhance compare and commit view functionality 

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#22677]
#### Feature request description

~~The usability of the compare feature is limited for a couple of reasons. The first is that it is difficult to find, you have to navigate to the repository page to find the compare button- and it is not documented anywhere that this functionality exists. When you do access the compare button, in order to select revisions you have to know the Git revspec.~~

~~**Request**: Add a dropdown for users to select which revisions they want to compare.~~
**Added: https://github.com/sourcegraph/sourcegraph/pull/23977**

~~The other place it would be helpful to have the compare functionality is when viewing a commit. Users would like to select a given revision from a dropdown to compare to while in this view: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/85073d2fa79f0a106948494a0a84ae7c2c859a6a?visible=3~~
Specific ticket: https://github.com/sourcegraph/sourcegraph/issues/24125

~~The third aspect to this is the ability to view a single file in the diff view. Today, when you click on a blame and view the commit- you are also viewing all other files that were committed. It would be helpful to select only that file to view, and the ability to compare to past revisions as well. [Single file diff view is open in a separate FR](https://github.com/sourcegraph/sourcegraph/issues/13411).~~
Specific ticket: https://github.com/sourcegraph/sourcegraph/issues/13411

#### Is your feature request related to a problem? If so, please describe.

This feels like a functionality gap for users who have similar workflows in alternative tooling. 

#### Additional context

Common request and most recently called out by:

- https://app.hubspot.com/contacts/2762526/company/6286373436
- https://app.hubspot.com/contacts/2762526/company/6288462706
- https://app.hubspot.com/contacts/2762526/company/6330348409

**Comment by valerybugakov** [comment]
I see multiple topics here:

1. **Issue**: It is difficult to find diff view functionality. Proposed solution: Add a dropdown for users to select which revisions they want to compare. Needs input from @sourcegraph/design.

2. **New feature**: the ability to select a revision from a dropdown to compare to while in this diff view. Needs input from @sourcegraph/design.

3. **New feature**: the ability to view a single file in the diff view. Since we already have the issue about that, let's continue the discussion about it there.

**Comment by umpox** [comment]
I think we should get thoughts from @sourcegraph/design but one sensible idea here (at least for the first issue) would be to use the RevisionsPopover (pictured below). This currently works by modifying the URL when a revision is selected, we would likely need to refactor this so each revision 'node' acts as a button instead of a link.

![image](https://user-images.githubusercontent.com/9516420/128036589-e3314828-e097-45a2-a1da-4e6419c5434f.png)

**Comment by jeanduplessis** [comment]
@christinelovett we're going to make a best effort to get _"dropdown for users to select which revisions they want to compare"_ into the 3.31 release. The rest of the work is likely going to need much more cross-function and team collaboration to make progress and is not on the roadmap for now.

@umpox is going to take the lead on implementation.

cc @anna-mmikhova

**Comment by christinelovett** [comment]
Awesome!! Thank you @jeanduplessis @umpox 🙌

**Comment by umpox** [comment]
*"Dropdown for users to select which revisions they want to compare"* has been added and will make it into the 3.31 release.

You can see the new functionality at: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/...tr/query-batching

**Comment by umpox** [comment]
Given we already have a specific issue for one of these feature requests, I have created a new issue for the other remaining request and linked everything up. We can now close this issue and track the other work separately
