### ISSUE TITLE
Browser tab completely freezes on ")" (parenthesis)

### ISSUE THREAD

**Issue by oskar** [sourcegraph/sourcegraph#22714]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Windows 10, Google Chrome 91.0.4472.124 (Official Build) (64-bit)

#### Steps to reproduce:

1. Go to https://sourcegraph.com/search
2. Enter `)` in search field
3. Browser hangs and after a while is stopped with an out-of-memory error:

![image](https://user-images.githubusercontent.com/6519/125055771-d903d780-e0a7-11eb-925f-fea821539975.png)

**Comment by camdencheek** [comment]
Woah. Sure enough, just reproduced it in the latest Firefox on MacOS as well. Thanks for the report -- looking into it.

**Comment by 5h1rU** [comment]
Adding @rvantonder here. Looks like a problem with the search logic. I tried to profile the page, but my browser is dying.

**Comment by camdencheek** [comment]
Yep, confirmed that there's a loop in parsing. Here's a profile I caught locally: https://share.firefox.dev/3huynhG

**Comment by rvantonder** [comment]
@oskar This will be fixed upstream soon. In the meantime you can run  the search for `)` by doing `content:")"`.

With the fix, searching for `)` as-is will give an error message suggesting the above, so you'll need to use `content:` either way. We have a general routine that checks some of these properties that now kicks in with the fix, and rather than add a special case that searches for `)` the implementation is cleaner by just having the general routine handle it.

**Comment by oskar** [comment]
@rvantonder Thanks for the quick response and workaround 👍
