### ISSUE TITLE
Bug Report: WSL support for open-in-vscode

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#22776]
- **Sourcegraph version:** 3.29
- **Platform information:** k8s
- **Internal Slack:** [Thread](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1626122651461600)

#### Steps to reproduce:

A user reported not being able to open a file in a WSL via the open-in-vscode extension. In the user settings the user has "vscode.open.basePath": "//wsl$/Ubuntu/user". After clicking the "Open file in VSCode" button, the extension tries to open "vscode://file/wsl$/Ubuntu/user" which is missing a preceding forward slash, leading to a path does not exist error.

#### Expected behavior:
Clicking the Open in VSCode button should attempt to open this path "vscode://file//wsl$/Ubuntu/user"

#### Actual behavior:
The extension tries to open this path "vscode://file/wsl$/Ubuntu/user"

**Comment by caspark** [comment]
This bug report got a bit tangled up with the troubleshooting done in the slack thread.

Here's what happened:

1. I reported that I couldn't use the open in vscode extension because I get an error message like this: 
![image](https://user-images.githubusercontent.com/931544/125403234-e1317f00-e3e7-11eb-91f4-681e31f06392.png)

2. I confirmed I'm using neither the vscode-extras nor openineditor extensions but rather the open-in-vscode extension, and my user settings look like this:
```
{
  "extensions": {
    "sourcegraph/open-in-vscode": true
  },
  "vscode.open.basePath": "\\\\wsl$\\Ubuntu\\home\\ckrieger\\src\\",
  "quicklinks": [
    {
      "name": "Example",
      "url": "http://example.com"
    }
  ]
}
```


3. As one of the troubleshooting steps to make sure that the vscode:// protocol handler was correctly set up in Windows and supported WSL, Gabriel asked me to paste `vscode://file/wsl$/Ubuntu/home/ckrieger/src/sourcegraph-open-in-vscode/src/open-in-vscode.ts` into my browser window
4. I said that URL doesn't work, because it's missing a `/` before WSL, but if I add the missing `/` to turn the path into `vscode://file//wsl$/Ubuntu/home/ckrieger/src/sourcegraph-open-in-vscode/src/open-in-vscode.ts` then it does work (as long as that path exists on disk).
5. Gabriel thought I meant that this is a bug in the open-in-vscode extension (when actually I just meant that his testing instructions had a mistake) and reported it here.

Accordingly, a more accurate bug report would be:

Steps to repro:
1) Enter in a UNC path to WSL (you don't even need to use Windows to trigger this) in your user settings; either `"vscode.open.basePath": "\\wsl$\Ubuntu\home\ckrieger\src\"` or `"vscode.open.basePath": "\\\\wsl$\\Ubuntu\\home\\ckrieger\\src\\"` will do the trick (they both exhibit the same brokenness).
2) Attempt to open a file of your choice in vscode using the extension.

Expected behavior:
* no error message
* if using Windows, the file opens if it exists on disk in `/home/ckrieger/src/<whatever>` in the `ubuntu`

Observed:
* Sourcegraph error message saying the path is invalid because it doesn't start with a leading slash
* The file isn't even attempted to be opened
* Here is a recording of the observed behavior: https://user-images.githubusercontent.com/931544/125404495-40dc5a00-e3e9-11eb-966c-d3ae2f41a26a.mp4

NB: I saw this same behavior with setting up a path of `C:\src\`, so I don't think it's actually WSL specific. I assume the regex being used to validate the path is just not quite right (or further escaping is needed on my part).

**Comment by muratsu** [comment]
Thank you for the incredibly detailed report @caspark! Seems like we have a bug in our path regex.

While looking at your example I've noticed that you're using WSL. I'm working on getting a windows debugging environment ready but can you validate opening the file by following this link `vscode://file//wsl$/Ubuntu/home/ckrieger/src/sourcegraph-open-in-vscode/src/open-in-vscode.ts` opens it remotely? My suspicion is that this path will open the file in vscode locally (windows side) and your vscode extensions won't work as you expect them.

**Comment by caspark** [comment]
@muratsu opening that path works fine, but you are correct that vscode opens the path as a regular UNC path. https://github.com/microsoft/vscode-remote-release/issues/3216 tracks this.

However, that's not a huge deal because I can then do `Ctrl+P` -> `>Remote-WSL: Reopen Folder in WSL` and it'll do the right thing.

![image](https://user-images.githubusercontent.com/931544/125547137-2378bcdc-4c53-40c8-915d-775be6c7bda8.png)

I did some more spelunking and it seems like it is possible to construct paths that open a remote directory (`vscode://vscode-remote/wsl+ubuntu/home/ckrieger/src/sourcegraph-open-in-vscode/src/`), but opening a file (`vscode://vscode-remote/wsl+ubuntu/home/ckrieger/src/sourcegraph-open-in-vscode/src/open-in-vscode.ts`) doesn't work. I've Reported that as https://github.com/microsoft/vscode-remote-release/issues/5331 - but even supporting UNC paths would be fine for this issue.

**Comment by muratsu** [comment]
Hey @caspark, we just added a [feature flag](https://sourcegraph.com/extensions/sourcegraph/open-in-vscode) to unblock you. You just need to make a small change on your config to enable unc paths, see my config for example:

```
  "vscode.open.basePath": "//wsl$/Ubuntu/home/murat/dev",
  "vscode.open.uncPath": true
```

If you're on cloud, refreshing the Sourcegraph tab will automatically load the new extension! Please let us know if you run into any other issues!

**Comment by caspark** [comment]
Awesome, thank you! The workaround you posted works for me :)
