### ISSUE TITLE
Surface to the user if the backend limit(s) get hit and results aren't precise via limitHit

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#22931]
We should always clarify to the user if they've hit a search limit, like the 100,000 match limit that exists at the moment. This helps maintain trust and surface issues a user might think they're hitting.

**Comment by Joelkw** [comment]
(Update: the limit is at 5k in 3.29 and 20k slated for release in 3.30. Perhaps we should read this limit dynamically rather than hardcoded since it seems subject to change.)

**Comment by felixfbecker** [comment]
@coury-clark is this possible? If yes, do you have a sense of what the time effort would be?

**Comment by coury-clark** [comment]
I have a rough sketch of a possible solution to exposing "dirty" insights, where we attach metadata when queries fail. This would be a pretty low-fidelity option that would flag an entire data series. We could possibly get it a little finer by exposing the particular date the query was for, but this gets complicated since we carry values forward on nulls. I haven't really had any time to consider if that is a good idea or not.

 I think we could expose the low-fidelity option in the insights GraphQL query without too much trouble, maybe 1 day.

**Comment by Joelkw** [comment]
cc @AlicjaSuska and @coury-clark – if @coury-clark is able to finish [his proposal here](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1628717137195000) I am fine with pretty much any "quick" design on the frontend that conveys this information – the important thing is just conveying it at all.
