### ISSUE TITLE
The file tree has confusing behavior when selecting a file from a search result

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#23136]
Slack [thread](https://sourcegraph.slack.com/archives/C0W2E592M/p1626968756194900) for context.

Navigating from the repository root provides access to the full file tree. When landing on a file from a search result the file tree is limited in scope to the current directory. Some context from @felixfbecker is that this was a decision to support monorepos and large nested structures; however, it is a confusing experience when compared to normal behavior from an editor.

<img width="282" alt="CleanShot 2021-07-22 at 08 40 45@2x" src="https://user-images.githubusercontent.com/5090588/126699186-e8e70952-42ca-4abc-8974-a3da53e25a3d.png">

In an editor, the default behavior is the file tree would open to the current location. Jetbrains editors deal with a nested hierarchy by having a horizontal scroll component and aligning the current directory to the left side of the panel.

<img width="232" alt="CleanShot 2021-07-22 at 12 33 05@2x" src="https://user-images.githubusercontent.com/5090588/126698850-cafcfde6-1ac9-403f-b29e-05f062607b3c.png">

There is also no way to navigate up the tree from this view without clicking on the breadcrumbs at the top once landing on this view. This doesn't really give the same context as a file tree, and isn't as easy to explore.

Demonstration

![CleanShot 2021-07-22 at 08 43 19](https://user-images.githubusercontent.com/5090588/126698743-0f820011-120f-40d9-8fac-1984b6e71d58.gif)

**Comment by Joelkw** [comment]
related to #17122

**Comment by jjinnii** [comment]
@macraig @olafurpg @efritz   Continuing [Slack thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1632748309104000) about different implementation options here. 

This issue (and related #17122 ) covers a few different navigation problems: 
1. Updating the file tree view as user navigates into lower directories. 
2. Going into file from a search result only displays the lower directory (without the file tree view for context) 
3. No way to navigate to parent directory from panel

1 seems to make a lot of sense to implement, unless we are concerned about performance issues with the file tree reloading each time a user is clicking into directories. On problem 2, opening up the full file tree when clicking into a search result also seems better practice than showing a limited view IMO.

On problem 3, I like Olaf's suggestion, esp given technical restrictions with monorepo support. When clicking the button, I would expect that the file tree updates to a higher level view, like this one. 
<img width="237" alt="Screen Shot 2021-09-27 at 1 43 46 PM" src="https://user-images.githubusercontent.com/87138876/134958825-38a9f053-181c-458d-8b07-715771133fbb.png">
And clicking into a directory, would then resume our current state file tree, so that we're not making the drastic change to add another level to our existing file tree. I would also suggest "Return to parent" maybe because "go to" makes it sound like it will actually load the directory.

**Comment by oleggromov** [comment]
This is partly solved by https://github.com/sourcegraph/sourcegraph/pull/39138, which allows navigating up the tree.
We're considering adding support for rendering the entire tree for deeply nested files but it's coming a bit later.

**Comment by camdencheek** [comment]
Closing as stale
