### ISSUE TITLE
no CORS header for streaming API

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#23140]
No CORS header is set for streaming API, in particular, lack of `Access-Control-Allow-Origin` means browser requests from domains other than sourcegraph.com are blocked. Here's where most of our streaming headers are set:

https://github.com/sourcegraph/sourcegraph/blob/099c4418d881924f912b770004a3b8ca56845cf4/internal/search/streaming/http/writer.go#L32-L40

I think it makes sense to support for other web apps to use (related to https://github.com/sourcegraph/sourcegraph/issues/18847.  I'm not sure whether we confirmed that we allow GQL requests from other origins since that was posted though--I'll see if I can confirm)

**Comment by rvantonder** [comment]
Note that I think this comes into play separately for self-hosted instances where we have `corsOrigin` configs for, e.g., [phabricator extensions/integrations](https://docs.sourcegraph.com/dev/how-to/test_phabricator)

**Comment by keegancsmith** [comment]
I'm not sure what the right thing to do here is. Normally this is handled by a middleware. I remember this sort of thing coming up before, and it had something to do with what the correct thing to do is with api endpoints vs web endpoints. Either way, I imagine someone from @sourcegraph/security could quickly advise us on correct CORS usage.

**Comment by ElizabethStirling** [comment]
This will probably tie into a larger discussion we're going to need to have around CSRF protections (RE: [this](https://github.com/sourcegraph/security-issues/issues/159)). The linked issue has a detailed writeup of how I think we do CSRF protections, and what fixes we're considering. No specific recommendations at present, since we haven't yet decided on a fix here

**Comment by andreeleuterio** [comment]
@rvantonder is the streaming API what powers `/search`? If so what would be a use case for another domain to use it?

**Comment by rvantonder** [comment]
Yes the streaming API now powers `/search`. Previously requests routed via the GQL API.

For similar reasons to https://github.com/sourcegraph/sourcegraph/issues/18847 for the GQL API: It's simply not possible to call our API from another website. There are lots of reasons to allow other domains to use it, if we're interested in opening up our tooling to the public (maybe someone wants to build a page using search results or whatever). Compare to, for example, open uses of the GitHub API. Currently, my understanding is, even if we have auth'ed requests, we'd still cause browsers to block external ones due to no CORS header. It seems limiting to require users to get a middleware to workaround this. My concrete, personal experience is: I tried to run an experiment against Sourcegraph and the CORS policy is limiting, and I'd have to go find my own middleware solution now. I _think_ in general our philosophy and intent around the public part of Sourcegraph tooling is not to block external users (and by extension, domains) from using our API.

Also, since the streaming API now powers `/search`, I believe it is unaffected by the [`corsOrigin`](https://docs.sourcegraph.com/admin/external_service/phabricator#native-extension) setting that we introduce for external services to talk to Sourcegraph for other reasons. I won't be surprised if a customer eventually comes along and says they have a domain that wants to talk to the streaming `/search` endpoint but it's different to the one Sourcegraph is set up on and so gets CORS blocked.

**Comment by andreeleuterio** [comment]
@rvantonder gotcha, thanks. We block those requests because it can be a big security risk. The common attack scenario is through phishing.. send someone a link to a malicious website and then the website takes actions on behalf of the user.

We probably need Product to define what _should_ happen here and then discuss solution and tradeoffs. The goal is definitely to enable any feature. It also helps that `/search` can be handled separately from the rest of the app. The ongoing pentest is also likely to have findings and recommendations related to cross site requests.

**Comment by andreeleuterio** [comment]
cc @dan-mckean something we'll have to follow-up after the pentest

**Comment by keegancsmith** [comment]
For example should we show private repo results for cors requests? That seems like a bad thing? I don't fully understand browser security so will leave it to people who understand it to comment if it is possible for js on a random domain to run a search as a logged in user.

**Comment by andreeleuterio** [comment]
@keegancsmith my instinct definitely agrees 😄  but better understanding the needs from Product may allow us to find good compromises and mitigations

**Comment by rvantonder** [comment]
@andreeleuterio totally understanding of taking a conservative stance to mitigate risk and so that we are deliberate about what we allow/disallow. In general it just seems like there's precedent for allowing external access (what does GH do?) when it comes to this sort of thing.

**Comment by novoselrok** [comment]
Potential use case: https://github.com/sourcegraph/sourcegraph/issues/23666

We are thinking about embedding search notebooks within an iframe on other sites, primarily learn.sourcegraph.com, to create engaging learning content. Notebooks contain search query blocks that allow users to execute arbitrary queries. This is where the CORS issue comes in because it would currently disallow running queries within a notebook. 

We could only allow embedding the main Sourcegraph site on its subdomains (e.g., learn) through X-Frame-Options. Additionally, we shouldn't allow making authenticated requests through an iframe, and we should only keep it limited to unauthenticated requests (which is fine for learning content).

I'm sure there are many more security implications, but I wanted to expose an actual use case to solve the CORS issue.

**Comment by malomarrec** [comment]
@andreeleuterio we just got validation from the Sourcegraph lean team that this 👆  would be a significant win:
- improve the experience on the Learn site
- avoid duplicating contents (Learn tutorial + notebook)

Could we consider @novoselrok's proposal earlier if it's a minimal change, before broadening the conversation to third party domains?
(We also have validation that sharing / embedding search snippets on thrid party sites is a good level for driving virality, but it feels less urgent).

**Comment by dan-mckean** [comment]
I'm not very familiar with CORS beyond its basic concept... But here's what I'm thinking...

1. As long as we have authentication (that we consider sufficiently strong) on the use of the streaming API, then I see no reason to block access to it from another site. If the customer wants to show their Sourcegraph data on that site, then fine. And the use case @novoselrok outlined sounds perfectly acceptable.

2. Is there a way to limit the effect of CORS such that we only block the use of unapproved domain access on pages we own/serve, while allowing use of the API from any site (assuming authentication)?

**Comment by andreeleuterio** [comment]
@novoselrok / @malomarrec that's an awesome use case. I am also onboard with the solution - just please keep us in the loop regarding implementation details. We also might want to do some testing.

@dan-mckean regarding #2, we can be very granular about how we manage CORS. `/search` can be handled differently than `/.api/`, etc. But with great powers comes great vulnerabilities so we should be involved and test it.

**Comment by slimsag** [comment]
I apologize for not chiming into this conversation earlier. There are a few things here that scare me - and probably _not what you think_:

1. Frankly, there is a lot of tech debt here.
2. I understand we're somewhat working around that tech debt - we've added the streaming API under a separate route than the standard `/.api` route, which means it bypasses various handlers and is exceptional in terms of security -- that's very risky in general.
3. I understand we've made exceptions to our CORS policy for websites like github1s.com, this is dangerous because it means we're bypassing our standard CSRF protection model. Obviously, we have a trusting relationship there, but this is dangerous no less.
4. I have long been aware of _customers_ making their instance less secure in order to access the GraphQL API, by setting cors to `*` in their site configuration. This is their right, but we're not doing them any favors by making our `/.api` endpoints harder to access than they need to be.

The irony of this whole situation is that `/.api` was designed from the start to be a set of public API endpoints. The danger in not having CORS for an endpoint is that we could subject ourselves to CSRF attacks, but `/.api` is specifically designed to prevent CSRF attacks by _rejecting cookie-based authentication and any other authentication method that could allow a CSRF attack_. That's the primary defense mechanism.

My memory could be faulty in this paragraph, but I recall just a few years ago this was the case: `/.api` was public. In my view, this is an (old) regression that I just never got around to fixing.

The only reason I hadn't fixed this issue earlier, and made `/.api` public without CORS, is simply because I didn't have ~1d to look into it.

My concern here is that we're lacking understanding across the team about what the `/.api` CSRF protection model actually is, and by lacking that we're introducing other risky behavior (having a separate streaming API endpoint not under `/.api`, adding CORS bypasses for sites we trust like github1s.com, etc.)

This is worrying enough to me that I feel it is warranted in some ways for me spending the time to investigate/fix this, so I'll check this out in code with more depth soon and report back.

**Comment by slimsag** [comment]
Following up on this here: https://github.com/sourcegraph/sourcegraph/pull/23949

**Comment by daxmc99** [comment]
This issue is still impacting other parts of the org. The Learn effort was recently hit by this. https://docs.google.com/document/d/1GXe4Z1IJmErlDq1kWzpn8uGjRLpJbqN1ZlQEIv65bA8/edit#bookmark=id.3ezsczxirl42

**Comment by stefanhengl** [comment]
Another data point: 2 customers I know of want to build on top of the Stream API.

**Comment by slimsag** [comment]
This is now on my TODO list.

**Comment by slimsag** [comment]
Update: I have been doing a LOT of work behind the scenes on our CSRF security model, and the next change that I make (once I am back from Thanksgiving) will be to enable this.

**Comment by slimsag** [comment]
Back from Thanksgiving and being out sick. Just reiterating this is still top of my priority list, the only thing before it is a per-requisite to remove our CSRF tokens. Aiming to complete within 1 week / before I go on holiday.

**Comment by slimsag** [comment]
Also just wanted to say I did in fact confirm where the search streaming API is registered, it is under our general `/.api` handler and so is protected by the same CSRF security model we employ for our GraphQL API and other APIs.

**Comment by slimsag** [comment]
PR to fix this and enable public access of the Sourcegraph.com API is out: #27937

Once merged, you will be able to utilize the streaming search and GraphQL APIs in the following ways from any domain (e.g. jsfiddle.net):

1. As an anonymous user
2. Providing an access token to authenticate

Using session authentication will only be possible if the domain is trusted (e.g. in the `corsOrigin` allow list site config setting.)

**Comment by slimsag** [comment]
I did find one weird thing with the way we're registering search streaming API route: https://github.com/sourcegraph/sourcegraph/issues/29399#issue-1092913125

Not a security issue, and won't prevent this from working - but we should fix.
