### ISSUE TITLE
If I edit an insight from a dashboard saving edits should take me back to the dashboard

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23202]
If I edit an insight from a dashboard, when I save my edits or "cancel" them it should take me back to the dashboard I came from rather than the all insights page.

**Comment by vovakulikov** [comment]
> take me back to the dashboard 

But this is not always true. If you change the visibility setting that means you can change the dashboard visibility as well. Let's say I edit my private dashboard and change visibility to the global level, in this case, we can take you back to the dashboard (private dashboard that you came from) 

But in case if you came from the org level and you're editing the org level dashboard and make the dashboard private in this case I think we should redirect you to the private dashboard 

Same case when you change an org insight or a global insight and put them to a lower visibility level. We should redirect to the destination dashboard. @Joelkw

**Comment by vovakulikov** [comment]
Also since all insights also live in person/org/global settings subject we can redirect to one of these built-in dashboards in case if the visibility of insight has been changed. In case if it wasn't changed we can redirect to the dashboard that the user came from to the creation form.

**Comment by vovakulikov** [comment]
Also, I just checked this behavior from the last message above and it already works in this way.

**Comment by vovakulikov** [comment]
>But in case if you came from the org level and you're editing the org level dashboard and make the dashboard private in this case I think we should redirect you to the private dashboard

@Joelkw Sorry, I made a mistake here, I was talking about insights, If you change the visibility level of insight from org level to private.

**Comment by vovakulikov** [comment]
@Joelkw I see now the problem/ I've been checking editing insight from org level built-in dashboard and current logic brings me back to this dashboard (instead of all insight dashboard) 

But now I see the case, I will take a look at this again, but at the moment it doesn't seem like an expensive thing to fix. Also I think this redirection also related to @tjkandala feedback about 

>Adding insight to dashboards in creation form:
UX: I'm on the "Extensibility team" dashboard -> I click "+ Create new insight" -> Finish creating and click "Create code insight" -> I get sent back to the "Sourcegraph Insights" dashboard. Now I have to go back to the "Extensibility team" dashboard and add the insight from there. It took me a while to realize that I need to add an insight through the breadcrumb menu next to the dashboard selector. Should dashboard actions be hidden behind a menu on large screens?
note: this happens when editing too
apologies if this is already possible, but is there any way to add a new created insight to the desired dashboards at creation-time? or at least get sent back to the dashboard on which I clicked "+ Create new insight" or "Edit"

**Comment by Joelkw** [comment]
Yeah, all good. I agree, I think TJ's feedback is the same, which is basically "if I enter a creation or edit flow from a dashboard, when I exit, take me to that dashboard"
