### ISSUE TITLE
Multiple "Mix precise and search-based results" toggles appearing

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#23393]
At 00:28:42 in https://sourcegraph.zoom.us/rec/play/Myqcmn821ua4oQifFsgtN5l3CTtnD7wrfD_R51vDLzkNkA5bXQfJya9ZyRHxBqG5hj28fAU3ZL1w6Oy6.UYlwH4Ugsst1Tyu4?autoplay=true&startTime=1627621138000 (a Zoom livestream with a user), there are multiple `Mix precise and search-based results` buttons shown:

![image](https://user-images.githubusercontent.com/1976/127614515-9fab0ccb-9183-4e64-8c2e-2bb47c471d96.png)

My guess is that this is caused by multiple language extensions being activated.

**Comment by efritz** [comment]
@sourcegraph/extensibility So we publish a`sourcegraph/lang-{LANG}` extension for each language we support, and they all have the same contributions in the extension manifest.

Is this an incorrect use?

A few paths forward I see here (but don't have good context to list pros/cons):

- The extension host should deduplicate identical contributions from multiple active extensions
- The extension should be able to registered a "shared" extension that will not be active twice as it controls the same underlying user setting (for example; that's what _this_ action does).

**Comment by muratsu** [comment]
@tjkandala would be nice to have your input on this

**Comment by tjkandala** [comment]
@efritz @muratsu After a short investigation, I've concluded that the first path forward would be more viable than the second option (we'd have to look into the parse tree of the template expression for a specific builtin command; it's possible, but a precedent we don't want to set). It also makes more sense to not register actions with duplicate IDs.

Another solution could be to name the reference panel for each language, and to reference that name in the `when` condition for each extension's panel action, fixing this issue "from the other end." This is complicated though, since we currently hard-code creation of the references panel in the webapp. Maintaining backwards compatibility would be tough. 

Because all these actions are essentially the same action, I think we should deduplicate contributions by ID. I don't suspect that this would break any existing extensions, nor would it confuse future extension authors since IDs usually begin with the extension's name.
