### ISSUE TITLE
Add button to get more results when reaching the search result limit

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#23445]
#### Feature request description

Add a button to get more results when reaching the result limit.

<img width="1248" alt="Screenshot 2021-08-02 at 12 04 27" src="https://user-images.githubusercontent.com/1657213/127844245-212e246c-f8ab-488c-8bb5-080f93023856.png">

#### Is your feature request related to a problem? If so, please describe.
Feedback submitted by @slimsag in [Slack](https://sourcegraph.slack.com/archives/C0W2E592M/p1626375997078800)
> I do frequently run into our search limit, and am surprised we don't have any action button I can click to get more results - instead requiring I have to modify my query myself.

#### Additional context

Related to https://github.com/sourcegraph/sourcegraph/issues/20158

**Comment by KashingLiu** [comment]
I have the same problem too. Why don't we use several pages to display all results like OpenGrok? 
Do you know how to config the display limit? It seems that I can only see 500 results, although there are more than 500 results

**Comment by benvenker** [comment]
@camdencheek is this still an issue now that we have streaming search? I seem to just be able to scroll forever.

**Comment by benvenker** [comment]
Please reopen if it can still be reproduced after streaming search implementation.

**Comment by camdencheek** [comment]
So, you can't actually scroll forever. In addition to the limit set by `count:`, we also have a "display limit" (defaults to 1500 results), which limits the number of results sent to the client. The display limit only applies to the web client, not src CLI or the graphql API. Once the backend has sent the 1500 results, it just sends counts for the number of results found without sending the result contents (that's why you can still see "100000+ results"  in the UI). 

I don't expect us to be able to change this anytime soon (maybe ever) because, in order for the web client to request more results, we need to hold the result set in memory in the backend so it can continue sending where it left off. This is not practical because 1) result sets can be huge, and we'd likely OOM `frontend`, and 2) we don't know how long the user will wait to click "more results", and we can't hold the result set in memory indefinitely. 

It's possible that we could implement some sort of cursor-based search in the future, but that would be a pretty massive engineering effort to do correctly given how our backend is currently architected.

**Comment by benvenker** [comment]
That makes sense, thanks for the clarification. @macraig and @slimsag, please see the explanation above. It doesn't sound like there's a clear, low-effort path forward here.
