### ISSUE TITLE
Investigate replacing "all urls" permissions in the FF and Safari browsers with specific scopes (like the Chrome extension)

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23542]
Our chrome extension scopes its permissions asks to only code host urls and Sourcegraph. The Safari and Firefox extensions ask for all urls permissions. 

Historically, we think this may be because when we first built these extensions scoping permissions may not have been available, or it might likely be a difference between Chrome letting users add additional sites to their allowlists using the extension itself while FF and Safari may not allow that (and we didn't want to over-lock-it-down). 

We should see if it's now feasible to bring the FF and Safari permissions in line with the chrome extensions permissons.

**Comment by erzhtor** [comment]
So, based on the latest research, Safari can be fixed to behave like Chrome and ask for permissions during the runtime. ✔️ 

Firefox also supports it now, however, any request not in permissions (not granted or not in the manifest) is blocked due to CORs. In our case, the user will have to first grant permission to their self-hosted instance and then only put it on the options page, which makes UX a bit complicated. 
The ideal solution would be to add `allow-control-allow-origin: moz-extension://*` to the graphqlbackend service, which in turn require all self-hosted instances to be updated as well with a new code.

So, for now, we will fix for Safari in https://github.com/sourcegraph/sourcegraph/pull/26832, and postpone Firefox a bit, until we decide on the best approach.
