### ISSUE TITLE
stack overflow in query parsing

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#23566]
While looking through logs, I came across a stack overflow from a recursive call to `reduce()` that crashed a frontend pod. I've been unable to reproduce it, but the logs can be found [here](https://cloudlogging.app.goo.gl/upvyuVUjdVDX8urs6)

**Comment by rvantonder** [comment]
Does not sound good 😬 . It's probably an interesting one though :-) Thanks for the heads up, I'll take a look--wonder if there's an example query in the logs.

**Comment by rvantonder** [comment]
OK I spent a long time trying to track down the query that caused this, it seems we don't have it in our gcloud logs, nor honeycomb. There are some queries in honeycomb for this pod, but I think we log _after_ parsing so it's possible we didn't catch this value. I stared at the code for a while too and nothing pops out. I will keep this issue open in case we find a reproducible query or I find more time to stare at the code, maybe tomorrow, because this bugs me. But until then I did some pretty good diligence and it's not super obvious what's going on here. It's legit but subtle.

**Comment by camdencheek** [comment]
I took a quick look at it as well, and the recursion looks good to me. There is no path that would recurse through line 1039 without `len(right)` decreasing by 1 every time until `len(right) <= 1` .

Looking at the hex values in the logs, this appears to be an issue with the input to the function, not the function itself. In the top entry of the stack trace, `len(left) == 610078` and `len(right) == 3127649`. That's a lot of nodes (like 200MiB memory just to hold the right slice). 

Also, looking at those honeycomb queries, it's suspicious to me that `context:global repo:contains.content(sbt.version=1.5) AND repo:contains.file(build.sbt)` is in there. That's a query I was playing around with for Olaf, and it's a particularly poorly performing predicate. I wonder if we're somehow expanding to millions of nodes, then running `reduce` on it.

**Comment by camdencheek** [comment]
I can't get as far as a stack overflow locally, but I'm fairly certain that query is the culprit. Running `repo:contains.file(.) and repo:contains.content(.)` locally, I'm getting inputs to `reduce` in the range of ~800 nodes. I imagine with ~1m repos on `sourcegraph.com`, that would get dramatically higher.

**Comment by rvantonder** [comment]
Hmmmm that's starting to make sense. Initially I'm wondering if we really end up calling `reduce` on a subquery. I think it's possible via `newOperator` but I don't see [a call to this coming from our predicate code](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+newoperator&patternType=literal). So maybe a there's another call wrapping it?

To mitigating this, once we're more confident: limit size of nodes in generated subqueries. This is a good idea in general, because the `DNF` expansion code can probably also run into this. I would love if we could do "query cost estimation" using this sort of data in general, in the near-ish term.

Longer term for this predicate, to make the queries more efficient, we should optimize the internal logic. For example, we don't need to build a huge query to answer this for a lot of repos, we can break that up and evaluate (possibly in separate goroutines) after resolving the list of repos, for example, and use our internal representation instead. This is conceptually similar to internal processing we do for `repoHasFile`
