### ISSUE TITLE
Code Insights: Flaky Percy screenshot tests

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#23669]
Currently, we have flaky code insights chart screenshot tests. And because of that, we have a lot of false-positive Percy failed pipelines (see screenshot below)

<img width="420" alt="Screenshot 2021-08-04 at 16 11 21" src="https://user-images.githubusercontent.com/18492575/128186846-3194e15c-dc3a-43a9-833f-34d1ddb7b41f.png">

My guess is that flakiness comes from the mouse position (perhaps the initial position is the viewport center) and then insight grid animation is happening and this may trigger tooltip appearance. A possible fix for it is to set mouse position for the visual screenshot tests of the insight grid explicitly.

**Comment by chrismwendt** [comment]
Percy has flaked on at least 2 more PRs:

- https://github.com/sourcegraph/sourcegraph/pull/25013
- https://github.com/sourcegraph/sourcegraph/pull/25268

The differences appear to be related to antialiasing around the edges of lines in charts:

<img width="661" alt="CleanShot 2021-09-23 at 19 32 19@2x" src="https://user-images.githubusercontent.com/1387653/134604922-601057b1-3931-47d6-9601-10ab0dfaec44.png">

Possible ideas to solve this:

- Adjust Percy sensitivity (if such a setting exists)
- Adjust rendering settings during testing for the charting library we're using
- Automatically approve Percy changes if the differences is below some threshold
- Remove these tests
- Grant more Sourcegraph engineers permission to approve Percy changes

Are any of these actionable? @vovakulikov do you have a path forward?

**Comment by vovakulikov** [comment]
Hey, @chrismwendt thanks for looking into this. I also was thinking about setting up custom sensitivity but unfortunately, I couldn't find anything about this on the Percy doc site. Do you know how to do that? I found that Percy should automatically ignore 1px change but it's seems like hardcoded from their side setting https://docs.percy.io/docs/ignoring-1px-diffs

**Comment by chrismwendt** [comment]
Found this in the project settings https://percy.io/Sourcegraph/Sourcegraph/settings 🎉 

<img width="1265" alt="CleanShot 2021-09-24 at 10 27 46@2x" src="https://user-images.githubusercontent.com/1387653/134709280-54eb5c9e-8c74-4627-828e-fa139c1baea1.png">

I adjusted the slider to "Relaxed":

<img width="1217" alt="CleanShot 2021-09-24 at 10 29 54@2x" src="https://user-images.githubusercontent.com/1387653/134709564-6f432486-46af-4e63-bf3f-0510c2b44fc5.png">

The message

> Highlight only the most prominent color shifts.

makes me think it might still detect changes on the code insights page because the graphs have pretty sharp lines and if they move even a couple pixels then the colors of those pixels can change drastically.

Closing this issue for now, but let's reopen it and try something else if we continue to see flakiness.

**Comment by vovakulikov** [comment]
Awesome. Thanks @chrismwendt!
