### ISSUE TITLE
Code insights backend: default to `archived:no` and `fork:no` filters on backend searches?

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24023]
We have a strong POV (based on customer feedback + behavior so far) that customers expect insights to essentially match Sourcegraph search GUI. 

The Sourcegraph search GUI currently defaults to searching forks and archived repositories, however, because when you search explicitly using a `repo:` tag that's how it works ([see more context from](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629138609041000) @slimsag there). 

Based on @slimsag 's [knowledge of why we default to _excluding_ forks and archive](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629140492056800?thread_ts=1629139713.050900&cid=C02BQB5CCFK)s from sourcegraph GUI searches now, it makes sense to maintain this default in code insights – no reason to give you needless duplicates. 

One positive note/one note to maintain: explicitly passing `fork:` or `archived:` filters in the data series should always be honored (so when we change the default to these both being off, it should still be possible to manually set them on). This is how it works now, which is "positive" because it means even if customers don't want forks in their results, before we change the defaults we just have to advise them to include a `fork:no` and `archived:no` in their data series query. 
![image](https://user-images.githubusercontent.com/11967660/129667024-2175e451-ad1b-4971-ad53-2e508ead0df9.png)

Example: [without archived+forks](https://k8s.sgdev.org/search?q=context:global+count:all+fork:no+archived:false+aardvark+lang:TypeScript+&patternType=literal) 32 results and [with archived+forks](https://k8s.sgdev.org/search?q=context:global+count:all+fork:yes+archived:true+aardvark+lang:TypeScript+&patternType=literal) 33 results

---

Edited by @unclejustin 

## Action Items

As per @felixfbecker's comment here https://github.com/sourcegraph/sourcegraph/issues/24023#issuecomment-900152127

1. Update help text with "This includes archived and forked repositories, add archived:no and forked:no to exclude them."

**Comment by felixfbecker** [comment]
I'd say all we should do here (if you think this is important to solve before Beta) is extending the help text with "This includes archived and forked repositories, add `archived:no` and `forked:no` to exclude them."

We could programmatically add them, but it would be problematic for multiple reasons.
- `AND`/`OR` expressions make it not trivial how to add it.
- If the user tries to override it, it would error due to the duplicate operator.
  - If we do a naive string check for the operator, it could easily overmatch or be wrong with `AND`/`OR` expressions. We can't really do this without proper parsing of the search query, it's complex.

We could add them as a default value, but it  would fill up the query input by default and could be confusing.

**Comment by vovakulikov** [comment]
I agree with Felix. We've been there already with the `:repo` filter for the search page 1-click creation flow. And to support all possible cases is not as trivial as it looks at first glance. So due to the time, we have before our code-freeze and release cut actually (this Thursday) I would avoid any changes on the FE related to this problem. I'm wondering if it's also complicated to turn it off on BE by default with all the sophisticated search syntax we have or it's not. 

cc @coury-clark

**Comment by felixfbecker** [comment]
I would assume it's the same story on the backend.

@unclejustin could you help with the help text addition I mentioned above on the frontend today?
