### ISSUE TITLE
Consider an insight only "loading" if there are pending jobs, not failed jobs. 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24062]
We currently [use both](https://github.com/sourcegraph/sourcegraph/pull/23938/files#r688823010), but at the moment (for about 1 release or so) we either don't re-run failed jobs or we don't clear the counts, so a job failing means an insight gets stuck in "loading" indicator state forever. I think perhaps we should just go off of pending jobs for now.

**Comment by felixfbecker** [comment]
I think this will be very important to fix. I now see the new ⚠️  indicators on basically every insight, and peeking into the Network tab, it seems to be because of `failedJobs`. With the new, prominent progress alerts (https://github.com/sourcegraph/sourcegraph/pull/24055) this will look _very_ alarming and confusing to users.

![image](https://user-images.githubusercontent.com/10532611/129890143-eeb5225a-b37b-49ed-b0d7-244d5308fb7c.png)
