### ISSUE TITLE
stream highlighted results

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#24097]
Proposal: stream configurable, highlighted file content as part of our streaming events.

This issue is created in response to some discussion on https://github.com/sourcegraph/sourcegraph/pull/24038. I had attempted to remove the `Preview` field from our streaming events since it wasn't used by the web app, but it turns out it's still used by `src-cli`.

@rvantonder then suggested that we do all highlighting and content requests server-side to avoid having to re-fetch file content and re-implement highlighting in all the clients. I created this issue to continue that discussion. 

So, I'm going to try to take Rijnard's comments and put together an actual proposal. 

A design should support the following things:
- Streaming full file content
- Streaming only matched lines
- Streaming no content
- HTML highlighted, ANSI highlighted, and plaintext formats
- Configurable lines of context above and below

My attempt at a design:

_Create `Content` struct with optional, disjoint fields_
 ```go 
type Content struct {
	Plaintext       []byte
	HighlightedHTML []byte
	HighlightedANSI []byte
}
```

_Add `Content` to `EventContentMatch` and `EventLineMatch`_
```go
type EventContentMatch struct {
	...
	Content Content
	...
}

type EventLineMatch struct {
	...
	Content Content
	...
}
```

_Add arguments to the `/stream` endpoint that allow configuring what content to return_
```go
type StreamArgs struct {
	FileContent struct {
		Plaintext       bool
		HighlightedHTML bool
		HighlightedANSI bool
	}
	LineContent struct {
		Plaintext       bool
		HighlightedHTML bool
		HighlightedANSI bool
		ContextBefore   int
		ContextAfter    int
	}
}
```

Open questions:
- We currently send 1500 results to the UI client, but often very few of these are actually viewed. Currently, we are only highlighting if that match is scrolled into view, but with this implementation, we would be highlighting all 1500 matches. Given how expensive highlighting is, that might not be ideal. Is there a way around this?
- Is the `StreamArgs` struct just re-inventing GraphQL, but with streaming? The "some fields are expensive, so only send them if they're needed" thing is hitting us in streaming search, but that's exactly the problem GraphQL intends to solve.

**Comment by rvantonder** [comment]
Nice write up, thanks for jumping on this!

> We currently send 1500 results to the UI client, but often very few of these are actually viewed. Currently, we are only highlighting if that match is scrolled into view, but with this implementation, we would be highlighting all 1500 matches.

Really good point, didn't immediately think about this. The "result-in-view -> kick off highlighting" does seem nicer than doing all the work up front. I wonder if we can avoid doing the work up front? From a UX perspective, this isn't a total deal breaker, since time to first (highlighted) result is going to be faster by skipping the roundtrip, and if the user scrolls, the work is already done. But yes we would increase load on the backend I suppose. Which leads to:

> Given how expensive highlighting is, that might not be ideal. 

This adds overhead for sure, but I don't know that it is _that_ expensive. @slimsag says it's "very fast" :P https://github.com/sourcegraph/sourcegraph/issues/6992#issuecomment-611672799. Hopefully I'm not taking that out of context too much... I think intuition is good here but it will probably come down to actually benchmarking.

> Is the StreamArgs struct just re-inventing GraphQL, but with streaming? The "some fields are expensive, so only send them if they're needed" thing is hitting us in streaming search, but that's exactly the problem GraphQL intends to solve.

I think URL params are OK here, and we have a constraint scope for the streaming API--not this overly general model that we want to selectively query on. It's basically search results + some optional decoration and I think we can plausible enforce "_the buck stops there_". I think there are also some who believe that we don't need all of GQL to enable the general solution space of what GQL solves.

**Comment by rvantonder** [comment]
One thing to add about the data structures/API for highlighting. There's:

1. Highlighting syntax for the file, and
2. Highlighting match ranges in the file for search results

I'd have to look into how we achieve (2) while preserving the underlying highlight of (1). Worth thinking about how we can separate those concerns in the API too. Reason I think this could be cool is like @tjdevries once asked me if we can highlight just a subpart of structural search or regex match (or we can highlight submatches in with different colors, for example). If we find a way to give more control to the user to selectively highlight things they want, this would be a world first for a search engine IMO :3

**Comment by slimsag** [comment]
On the syntax highlighting side.. I wouldn’t be _too_ worried. It’s pretty fast.

But you are talking about several orders of magnitude more requests (likely <10 files today highlighted for most searches, to now.. 1500?) it’s the # of files highlighted that matters, not individual results. We highlight the whole file, then pick out the lines we’re interested in. This takes 100ms-2000ms on average IIRC.

“We currently send 1500 results to the UI client, but often very few of these are actually viewed.”

Is it really useful to send 1500 results if users won’t really view that many? How did we choose 1500 and not, say, 50 or 100? Is it because we don’t have any client->server “I want more” event?

**Comment by keegancsmith** [comment]
> Is it really useful to send 1500 results if users won’t really view that many? How did we choose 1500 and not, say, 50 or 100? Is it because we don’t have any client->server “I want more” event?

yup.

If we are worried about highlighting that much content (sounds reasonable), it seems like a highlight limit like the display limit would make sense? Then if the highlighting is missing we fallback to dynamic fetches. This sounds complicated, but I think fits nearly in our architecture. Additionally, this is the core perf/ux in our app so is worth the tradeoff against simplicity I believe.

**Comment by rvantonder** [comment]
> Then if the highlighting is missing we fallback to dynamic fetches. This sounds complicated, but I think fits neatly in our architecture. ...

Interesting tradeoff. This checks out in my mind. Not sure if there's a better proposal. Thoughts on this @slimsag, @camdencheek?

Btw really appreciate the comments here @slimsag and @keegancsmith. I think @camdencheek and I are gravitating towards solving this properly, and tackling this in the next coming weeks. This might be the effort needed to fix things up to make our highlighting interface more maintainable and strengthen code ownership. So any additional thoughts on to help us do this properly is great. I think Stephen laid a lot of the groundwork in https://github.com/sourcegraph/sourcegraph/pull/16570, "just" seems a matter of agreeing on tradeoffs that play well with streaming.

Also want to reference https://github.com/sourcegraph/sourcegraph/issues/17181 -- it looks like sending less data over the wire may not have a huge impact on high-bandwidth connections. Still beneficial though. And with streaming highlighted results, perhaps there's a benefit to reducing the 2x roundtrip to one.

**Comment by stefanhengl** [comment]
What about "dark mode"? Should we add a parameter to the API? Would be a nice touch if a cli user could flip the color scheme based on the terminal background.

**Comment by camdencheek** [comment]
> What about "dark mode"? 

For HTML, we use CSS classes now, so the actual colors are specified client-side. 

For the terminal, I think the same is true if we use standard ANSI color codes. They would just show with whatever color scheme the user has configured. If the user has dark mode enabled, I'd expect their colorscheme to change with that.

**Comment by slimsag** [comment]
> If we are worried about highlighting that much content (sounds reasonable), it seems like a highlight limit like the display limit would make sense? Then if the highlighting is missing we fallback to dynamic fetches. This sounds complicated, but I think fits neatly in our architecture. Additionally, this is the core perf/ux in our app so is worth the tradeoff against simplicity I believe.

This sounds good to me. I would start with highlighting the first 10-15 files that appear in the result set.

I will say, I am not worried about the actual _performance_ of highlighting at all, really. It's ast, and in the worst-case scenario we could just add a simple on-disk cache / effectively perform syntax highlighting offline. The risk with highlighting more files is actually that more files == more potential to run into a bad file that kills 1/8th of all syntax highlighting requests. Since we're not investing in solving that any time soon (#21942) we'll need to stay approximately around the current average of requests: 10-15 highlight requests per search seems reasonable to me.

I don't imagine the fallback logic would be too hard, either.

**Comment by rvantonder** [comment]
> This sounds good to me. I would start with highlighting the first 10-15 files that appear in the result set.

OK! Sounds like we have a plan! I think it would be neat to set `n` here in the stream request, potentially, for benchmarking. @camdencheek and I will figure out a timeline to tackle this :-)

**Comment by rvantonder** [comment]
In addition to streaming server-side rendered highlighting, we're are also leaning towards doing the _highlight overlay_ in the backend (i.e., if a user searches `test` then we overlay-highlight test, but preserve any original file highlighting underneath). 

Currently we do the _highlight overlay_ computation in the frontend in [dom.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/util/dom.tsx). In the past, the shared burden of backend/client needing to do different parts of highlighting (file vs overlay) caused bugs like https://github.com/sourcegraph/sourcegraph/pull/20589 because the backend would diverge in a way that the client computation around DOM nodes messed up. By pushing all highlighting responsibilities to the backend, we could help cut down on issues like these. It does mean that we need to port the [dom.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/util/dom.tsx) to the backend, so that we can compute the overlay highlight there (and directly from our line matches and other result types) and preserve the underlying highlighting. The backend overlay highlighting would take effect both with streaming and if we used the fallback mechanism (fetch file with highlights _with_ overlay highlighting).

Posting this for context and feedback. @camdencheek does that align with your thinking?

**Comment by rvantonder** [comment]
Also, since you touched `dom.tsx` (admittedly a while ago), do you foresee any issues there? I'm having a read through it to see how much effort it would be to port on top of @slimsag's file highlighting in https://github.com/sourcegraph/sourcegraph/pull/16570/

**Comment by rvantonder** [comment]
It appears that if we want to do overlay highlighting in the backend, we will need to support an option to do _only_ overlay highlighting and _not_ file highlighting as well--in the frontend we have such a use case for [`CodeExcerptUnhighlighted`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@38dc36dbbcde96b1bd59f96e528a2501b843c4c0/-/blob/client/shared/src/components/FileMatchChildren.tsx?L109-112&subtree=true).

So _if_ we shift overlay highlighting to the backend, we'll need options to specify:

- Decoration for file highlighting (HTML, ANSI, plaintext)
- Decoration for overlay highlighting (HTML, ANSI)

And the option to turn off decoration for file highlighting but turn on decoration for overlay highlighting.

---

Given scope/design on this point, it might be wiser to tackle streaming file highlighting + match ranges first (and rely on our overlay highlighting in the client) and then tackle backend overlay highlighting at a later stage.

**Comment by camdencheek** [comment]
> in the frontend we have such a use case for CodeExcerptUnhighlighted

[No longer true](https://sourcegraph.com/search?q=context:global+repo:sourcegraph+CodeExcerptUnhighlighted&patternType=literal)! I [got rid of that](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/7c103d3cc607b4333a37febee9701765a86f5c94?visible=2) a while ago as part of some changes when I realized that it was broken and also wasn't used outside of dev debugging.

**Comment by camdencheek** [comment]
> Also, since you touched dom.tsx (admittedly a while ago), do you foresee any issues there?

I don't. It operates pretty generically on the text content of an HTML tree, so as long as we're not changing that, we shouldn't (🤞) hit any issues.

**Comment by camdencheek** [comment]
Closing this since we now stream the unhighlighted content, and I'm now convinced it's optimal to fetch the highlighted content lazily.
