### ISSUE TITLE
Make sure enterprise features are in correct directories or identify what isn't by 2021-09-03

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24200]
We should make sure things for enterprise are in enterprise folders. [More context here](https://docs.google.com/document/d/1qNDIDgF__RmupRDid5YUoMU6Tb01GXExkQbstlGfjo8/edit#)

**Comment by tjkandala** [comment]
Investigation for extensibility ownership areas:

**Extension registry UI**: Mostly not in an enterprise folder, which makes sense since Free instances should be able to connect to the Cloud registry. The components for publishing and managing extensions _are_ in an enterprise folder.

**Extension registry backend**: The [GraphQL API is not in an enterprise folder](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/registry/api/registry_graphql.go#L91:1), but queries and mutations associated with enterprise , such as `PublishExtension` for private extension registries, are under the [top-level enterprise folder](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/registry/api/registry_graphql.go#L91:1).

**Extension host**: Not in an enterprise folder ([`client/shared/src/api`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/client/shared/src/api)), no enterprise folders inside it. This is the core of the Sourcegraph extensions ecosystem, but it can't be in an enterprise folder since Free users can use extensions and it's packaged with the browser extension.

**Browser extension**: Not in an enterprise folder ([`client/browser`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/client/browser)), no enterprise folders inside it.

### Summary

Nothing appeared to be out of place. This code was written with the enterprise/non-enterprise divide in mind.

**Comment by muratsu** [comment]
> Mostly not in an enterprise folder, which makes sense since Free instances should be able to connect to the Cloud registry. 

Free instances use the enterprise license and are not to be confused by OSS. Access to extensions is limited to enterprise only and all pages besides the page where we show the error message.

**Comment by tjkandala** [comment]
@muratsu Thank you, so sounds like we should move the registry UI to `client/web/src/enterprise`?

**Comment by muratsu** [comment]
That's correct - @Joelkw thoughts?
