### ISSUE TITLE
Sometimes we are swapping the values or labels for data series on the same chart

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24296]
Code insights charts seem to mistakenly return the wrong data series values <--> label mappings periodically for multi-series insights. 

Note: the "correct" values are for the TS line to be ~32, the GO line to be ~52, the MD line ~178, and the JS line ~354. We confirmed in the database [that these are also the values stored per-series correctly](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1629844617046600?thread_ts=1629829458.038000&cid=C014ZCKMCAV), which is why we know the problem is somewhere after fetching from the database. 

#### example 1 
This chart can be [viewed here](https://k8s.sgdev.org/insights/dashboards/backendTesting3) and [see the config here](https://k8s.sgdev.org/insights/edit/searchInsights.insight.testV223QueryAardvarkLangGoTsJsMdEVs500?dashboardId=387409ea-e6fb-41dd-88fb-ab843cfeaa17) (please don't edit unless necessary – running tests still). 
![image (46)](https://user-images.githubusercontent.com/11967660/130699833-0727a9a2-51f2-465b-90b1-2f7d43671538.png)

#### example 2
This chart can be [viewed here](https://k8s.sgdev.org/insights/dashboards/backendTesting2) and [see the config here ](https://k8s.sgdev.org/insights/edit/searchInsights.insight.test23QueryAardvarkLangGoTsJsMdExpectedResultsAll500?dashboardId=d46c18c3-d61d-4881-b4e0-e01d3cff595e). 
![image (47)](https://user-images.githubusercontent.com/11967660/130699836-c145fc84-1292-4ade-9b2b-af0ce1f6022e.png)

**Comment by unclejustin** [comment]
The culprit here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/insights/core/backend/utils/create-view-content.ts?L31:13

What's happening is that `createViewContent` is trying to map `series` to `seriesSettings` assuming that both of those arrays are in the same order. But that is not guaranteed. See the screenshot below.

You can see how the series as entered at the top maps to the `seriesSettings` in the first array. But the actual series data comes back in a different order.

If it is possible to order the series data the same as was entered in the settings that would fix this up. cc @coury-clark 

![image](https://user-images.githubusercontent.com/1855233/130707200-e0806b92-ba53-41b7-8700-8a089a531ea6.png)

**Comment by unclejustin** [comment]
Alternatively to sorting if there is some way to add a field to key off of that would work as well. Like a "series id".

**Comment by vovakulikov** [comment]
I think we can close this since both fixes have been merged.
