### ISSUE TITLE
Large-scale GitHub perms sync test environment

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#24470]
https://github.com/sourcegraph/sourcegraph/issues/24470#issuecomment-909434695

**Comment by bobheadxi** [comment]
tl;dr we need a mechasnism for testing and validating https://github.com/sourcegraph/sourcegraph/pull/23978, https://github.com/sourcegraph/sourcegraph/pull/24328, and friends at scale

**Comment by bobheadxi** [comment]
We have a 5-user restriction for ghe.sgdev.org, which means we would need to increase our license to ~100 users for I think ~$2100/month (yikes? 25k a year), a 100 user * 10000 repos might be a sufficiently realistic environment (if pretty heavy on the repo side). 

Most metrics also indicate that Cloud would not be a useful test environment, such as [no waits on github rate limiter](https://sourcegraph.com/-/debug/grafana/d/repo-updater/repo-updater?viewPanel=100231&orgId=1&from=now-7d&to=now). Even if we were to test in Cloud, we would need to find an org that has the prerequisite scale and characteristics (noted above) - generating one is likely not feasible because there is surely a github TOU that forbids spamming it with hundreds of users and repos.

other notes:

- we need to create additional users in sourcegraph and have them log in via the github oauth app, making automation tricky
- code insights requested we not do anything to change the size of k8s.sgdev.org https://sourcegraph.slack.com/archives/C07KZF47K/p1630440523099700 so we might want to spin up a new sourcegraph for this
- I found a few orgs/users that tests are dependent on in ghe.sgdev.org (added as a note to the login page)

I think all the options for building out a realistic environment looks pretty bad. I'm starting to think we should hack in mocking, e.g. by adding database entries and doing things to github-proxy to have it return mock results. However, this will likely prove brittle and might cause all sorts of confusing behaviours.

**Comment by bobheadxi** [comment]
I am leaning towards a large-scale environment for user permissions sync testing being likely more effort and potential cost than it's worth, and as an experimental feature we should just validate this at customers who find the default sync implementation insufficient

**Comment by bobheadxi** [comment]
Closing this for now
