### ISSUE TITLE
Find references broken when clicked on extension or loaded directly (...#tab=references)

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24535]
visit this, references are broken: https://sourcegraph.com/github.com/grafana-tools/sdk@9b7b5661617c60dbf773f49c042e32160328a200/-/blob/panel.go?L538:17#tab=references

visit this, references work: https://sourcegraph.com/github.com/grafana-tools/sdk@9b7b5661617c60dbf773f49c042e32160328a200/-/blob/panel.go?L538:17

from @muratsu 
> This is a frontend state/race issue though. My guess is that it's hard to track but easy to fix. At least nothing is broken on backend

[more context](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1630543274039400?thread_ts=1630541209.024300&cid=C022SPMNR0W) in slack thread with screenshots

**Comment by olafurpg** [comment]
Not sure if it's related but I can reproduce a similar issue by doing "find references" on a clean page and then I can't load new references for other symbols. It gets stuck on the first "find references".

Could this be related to the changes for extension loading? https://github.com/sourcegraph/sourcegraph/issues/23367

**Comment by tjkandala** [comment]
Should be fixed by #24562, related to a weird RxJS import issue uncovered by an experimental esbuild PR (#24487).

For future reference:
The `Find references` button is actually a link to the same location/position but with the hash that indicates that the references panel should be open. When the references panel is open, it requests references for the position from extensions (typically code intel). So it's expected that clicking the `Find references` button when the panel is open doesn't trigger a references request.
