### ISSUE TITLE
Support more kinds of prerendered file decorations for search streaming results

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#24617]
We currently support HTML mark up decoration for streaming results. We should also support:

- plaintext (not HTML plaintext, but actual plaintext)
- ANSI decoration for terminals

Assigning myself as contact/owner for this issue, but may be freely tackled by others in the team.

**Comment by camdencheek** [comment]
We now stream plaintext chunks back to the client for all results in the display limit so results are renderable immediately and fetch highlighted content when the result is scrolled into view. 

We do not plan to expand the streaming endpoint to stream highlighted results because:
1) highlighting can be very slow, and that would delay getting something viewable in the browser
2) we do not know on the backend when the user can actually see the results, so we may be highlighting much more than we need to, and highlighting is not cheap.
