### ISSUE TITLE
Non-site admin user "Account security" page is broken

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#24621]
As a non-site admin user, when I visit my user profile's `Account security` page (eg https://k8s.sgdev.org/users/sqs/settings/security), I get an error `Must be site admin` and the spinner spins indefinitely:

![2021-09-04_00-54](https://user-images.githubusercontent.com/1976/132087387-217fe9f5-ae50-4f17-a7e7-16e7af91ff3b.png)

The error comes from the `MinExternalAccounts` GraphQL API query.

This makes the profile page unusable.

(Similar to https://github.com/sourcegraph/sourcegraph/issues/18269, but that was fixed.)

**Comment by shuyangfang** [comment]
Afaict, this occurs when one of the external accounts is privileged https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.37.0/-/blob/cmd/frontend/graphqlbackend/external_account.go?L61-83, i.e., not gitlab or github

We had this occur as we were trying to add gitlab as an auth provider while still retaining saml, leading to non-admin users being unable to add gitlab to their existing accounts since this page breaks like so

It seems that all allowed external accounts should still be fetched, and the disallowed / insecure ones just shouldn't be available rather than disallowing everything

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
