### ISSUE TITLE
Code Insights: Add `Show more` button for the directory and homepage sections.

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24686]
At the moment we render all insights that we have at directory and search pages. I’ve found a long list with a lot of insight cards as a very distracting and annoying pattern (at the directory and the homepage insights section). We probably want to show only the first N insights (I think 3 is a good number) and hide others by the ‘Show more insights’ button.

cc @AlicjaSuska @Joelkw

**Comment by Joelkw** [comment]
I like this concept, but think it may not be a high priority (or priority at all) – more important than "just show 3" might be actually letting users set what would show here, so if you have 24 insights and only care about the 22nd insight to show on directory pages, instead of showing 1-3, then expanding the remaining 21, you can just show #22 and don't even have to worry about limiting it to 3 otherwise.

**Comment by felixfbecker** [comment]
I think I agree with @Joelkw

**Comment by felixfbecker** [comment]
Moving this out of the iteration given the amount of tasks we already have and no challenge on the above statement.

**Comment by felixfbecker** [comment]
I think we removed these, closing.
