### ISSUE TITLE
dev: poor battery life

### ISSUE THREAD

**Issue by kevinburke** [sourcegraph/sourcegraph#247]
Users report poor battery life when developing sourcegraph/sourcegraph and the enterprise product. The issue may be tied to the use of Node file watchers.

**Comment by kevinburke** [comment]
It's possible that this issue is related to SIGTERM not actually shutting down the server, and multiple instances of `gulp watch` all polling the filesystem. I just merged a change for the later issue.

**Comment by felixfbecker** [comment]
What OS are the users that reported this using?
Our file watchers use chokidar, which uses fsevents on macOS and `fs.watch` on Linux and Windows, which uses the native OS file watch API. None of these cases should use polling.

**Comment by nicksnyder** [comment]
Some action has already been taken and we haven’t heard other complaints.

**Comment by unknwon** [comment]
Since there is [a link](https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/local_development.md#cpurambandwidthbattery-usage) from dev setup docs to this issue, I'm commenting my resolution here (I'm running macOS 10.15.x):

1. Uninstall the Command Lien Tools by `rm -rf /Library/Developer/CommandLineTools`
2. Reinstall it by `xcode-select --install`
3. Go to sourcegraph/sourcegraph’s root directory and `rm -rf node_modules`
3. Re-run launch script

**Comment by nicksnyder** [comment]
@unknwon can you add this to our handbook documentation somewhere?

**Comment by unknwon** [comment]
@nicksnyder Unless we plan to move [this document](https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/local_development.md) into handbook?

**Comment by nicksnyder** [comment]
Updating those existing docs would be fine too. We shouldn't link to issues from the docs, we should inline the information.

**Comment by unknwon** [comment]
PR sent: https://github.com/sourcegraph/sourcegraph/pull/7917
