### ISSUE TITLE
Configure Brotli

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#24873]
We use GZip for static resource compression. [It seems to be possible](https://caddy.community/t/why-caddy-2-is-not-able-to-serve-static-brotli-files/7653/30) to serve pre-compressed Brotli files with Caddy.

We can also enable this through Cloudflare for Cloud. That could be a good test to see how effective this will be.

**Comment by umpox** [comment]
FYI: This is now complete through https://github.com/sourcegraph/sourcegraph/pull/25952 and https://github.com/sourcegraph/httpgzip/pull/1

There is an outstanding issue with our Sourcegraph.com instance due to Cloudflare limitations, tracking here: https://github.com/sourcegraph/sourcegraph/issues/26260

This limitation shouldn't affect many (any?) customer deployments as we do not use Cloudflare for [managed instances](https://github.com/sourcegraph/deploy-sourcegraph-managed) and our [self-hosted docs also do not require this/any other CDN](https://docs.sourcegraph.com/admin/http_https_configuration)
