### ISSUE TITLE
User doesn't know if their browser supports system theme

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2490]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** macOS, Chrome 72.0.3626.109 

![screenflow](https://user-images.githubusercontent.com/133014/53586462-14d41d00-3b3d-11e9-9b66-31987da7032a.gif)

**Comment by felixfbecker** [comment]
This is not supported yet in Chrome. Status "Intend to implement". See the CHANGELOG entry: https://github.com/sourcegraph/sourcegraph/blob/2262bac0ed4d95155db8c12638234aebe5ee8583/CHANGELOG.md#added

**Comment by ryan-blunden** [comment]
If it doesn't work, it's a bug and although I appreciate it's in the CHANGELOG, It's unlikely users will refer to that when something doesn't work in Sourcegraph. I certainly didn't think to look there.

Can't we simply hide the `System` option in browsers (including older versions of Safari) that don't support it yet?

**Comment by ryan-blunden** [comment]
This is an improvement but why would we let the user select something if it's not going to work? If it was something vital to Sourcegraph's functionality and existed because the user was on an unsupported browser version, fair enough, but I'd rather see progressive enhancement used, not graceful degradation.

I appreciate that you're adding support for something new (really new) which brings complexity, but could the conditional logic you have for showing the message just be applied to hide the System option entirely?

An alternative could be settings the System option to `disabled` and adding a `title` attribute (support)? to the option with the disabled message. Even then though, having an option in a disabled state implies that under certain conditions, that option will be enabled. If the option is always going to be disabled (not supported) or always enabled (supported), this will only change between browser versions which is not something the user can change.

**Comment by felixfbecker** [comment]
It's more contrived. There's four stored states to handle: no setting, system, light and dark. In the case of no setting it defaults to system. If system is not supported, it will act as light (but once your browser adds support, it will adapt). The preference is persisted in local storage.
 
So we can either
1. Migrate no setting/system settings to light. This means it won't start adapting once the browser ships support.
1. Lie to the user and tell them their saved preference is light when it is really system.
1. Show to the user that their currently selected option doesn't have an effect (until their browser ships support, or unless they use a supported browser)

I chose 3. because it keeps our default to system, will start to adapt one the browser ships support. It gives the user the ability to still discover this feature and find out what browsers to use to support it and getting excited for when support for their browser is coming.

I would like to not spend more time on this because I don't see it as important and this is issue is going to resolve itself anyway in the coming weeks as more browsers ship support.
