### ISSUE TITLE
Clicking search button doesn't rerun a search if the search hasn't changed

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24909]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:**  All

#### Steps to reproduce:

1. Enter a search in https://sourcegraph.com/search and run it
2. Click the search button
3. See that it doesn't rerun the search

#### Expected behavior:
The search should rerun

#### Actual behavior:
The search doesn't rerun

**Comment by lyqht** [comment]
Hello @limitedmage , yes I am able to run it after @mrnugget has helped to improve the instructions on the Getting Started guide. Thank you both 👍 

I am able to reach the page that this component is shown by @benvenker 

![image](https://user-images.githubusercontent.com/35736525/136577595-936e9afd-d7ea-425d-8870-86fc15233da8.png)

Upon brief inspecting at the search page, I believe that the `useCallback()` on the `onSubmit` method in the `SearchNavBarItem.tsx` is causing the search to be not re-triggered, since the queryState is not changed.

<img width="1201" alt="Screenshot 2021-10-08 at 10 59 19 PM" src="https://user-images.githubusercontent.com/35736525/136580078-a4d137f5-a23a-467a-95fa-fc09850d0d06.png">

However I'm not sure how to add test data to actually check for the search results are refreshed. Could you guide me on that? Thank you!

**Comment by valerybugakov** [comment]
@lyqht, updated it [here](https://github.com/sourcegraph/sourcegraph/pull/26010); thanks for reporting!
