### ISSUE TITLE
Ability to run Sourcegraph Docker Image inside network with proxy

### ISSUE THREAD

**Issue by machbio** [sourcegraph/sourcegraph#250]
#### Feature request description

Ability to run SourceGraph Docker Image inside Corporate Network - that does not allow any traffic without Proxy

#### Is your feature request related to a problem? If so, please describe.

The SourceGraph docker instance does not allow cloning external git repositories in a corporate environment resulting in DNS Error of "Remote Repository not found" or "Hostname not found"

#### Describe alternatives you've considered.

None

#### Additional context

Tried using HTTP_PROXY and HTTPS_PROXY as environment variables when starting the sourcegraph docker instance - the application does not take the PROXY variables and there is no configuration setting to change this behavior in the sourcegraph ui settings page.

**Comment by francisschmaltz** [comment]
@machbio I've taken a look at this and tried to duplicate an environment that might simulate what you have. I setup a server with a public IP as a router. This router drops all traffic from LAN that isn't over the proxy. The proxy is running on port 3128 for http and https. When I setup sourcegraph I am able to launch it and set it up but trying to clone a GitHub.com repo silently fails. 

From my best guess this seems to be due to a certificate mismatch due to using the proxy. I'll continue to investigate on my setup.

CC: @slimsag and @keegancsmith. Can y'all take a look at this and see if I'm missing something or if this is documented anywhere?

Tech notes:

2 VMs set up.
Router VM is on a public IP running Opnsense with 1 WAN and 1 LAN port. Firewall is set to drop all TCP and UDP packets (allows ICMP packets FWIW). 
Client VM was running ubuntu 16.04 Desktop with the network connection proxied.
Docker was proxied using https://docs.docker.com/config/daemon/systemd/ the method in this article.
I also tried passing env flags to the docker image.

**Comment by francisschmaltz** [comment]
Might be related to https://github.com/sourcegraph/sourcegraph/issues/71

**Comment by slimsag** [comment]
- What you are looking at looks right to me, I don't see anything obviously wrong. We don't have documentation for how to do this yet.
- If your proxy is only forwarding HTTP and HTTPS, it is possible that clones are being tried over SSH (port 22) and rather than failing are silently not resolving. It probably waits the kernel default for timeout, which is rather long (something like 5 minutes IIRC?)

**Comment by keegancsmith** [comment]
Hi @machbio. This likely will involve a bit of investigation and work, so is not a straightforward bug fix. We have also planned our work for this month. As such I've added to the backlog and we will likely work on it next month.

In the meantime, do you have any infra for transparent proxying setup? This was something I used to setup on my linux boxes back in the day, so should be relatively straightforward. Some quick googling lend me to these two promising looking guides: https://jpetazzo.github.io/2014/06/17/transparent-squid-proxy-docker/ and https://gist.github.com/int128/aecad331dc66b2272bf0

**Comment by machbio** [comment]
@keegancsmith will try a Transparent Proxy and update here. Thanks

**Comment by sqs** [comment]
@machbio Did the transparent proxying setup work?

**Comment by neculaesei** [comment]
I'm having the same issue using http_proxy. The external service (GitLab) works fine and correctly retrieves the repo list from the API. However cloning any of the repos fails with:

```
repo not found (name=xxx.example.com/team/project url=https://git:xxxapikeyxxx@xxx.example.com/team/project.git notfound=false) because exit status 128 (output follows)

fatal: unable to access 'https://git:xxxapikeyxxx@xxx.example.com/team/project.git/': Could not resolve host: xxx.example.com
```

My setup is a bit weird: [sourcegraph container - docker on linux] -> privoxy (http) -> proxychains-ng (socks5) -> ssh reverse tunnel via VPS -> WSL on Windows under corporate VPN

**Comment by slimsag** [comment]
@neculaesei is `xxx.example.com` your GitLab enterprise instance?

If so, it's quite odd that we'd be able to fetch the repo list BUT not clone at the same time. What does the external service config look like (with any secrets redacted)?

Other things I would try:

- Can you clone the repo using that exact clone URL from your WSL shell?
- Inside the Sourcegraph container, can you clone that repo? (`docker exec <container> sh`)

**Comment by neculaesei** [comment]
@slimsag yes, it's GitLab enterprise

I think what happens is that git/gitserver ignore env.http_proxy.
I'm not able to clone the repository inside the container (over either ssh / https), but works just fine outside of it through the socks5 proxy. Inside the container it failes with `Could not resolve hostname...`.
Also wget has no problem resolving the domain name inside the container.

Here's the config:
```
{
  "url": "https://xxx.example.com/",
  "certificate": "-----BEGIN CERTIFICATE-----REDACTED-----END CERTIFICATE-----\n",
  "token": "mYToKeN",
  "projectQuery": [
    "groups/my-group/projects",
    "?membership=true"
  ]
}
```

Docker logs are filled with this kind of errors:
```
01:16:55          gitserver | t=2019-05-31T01:16:55+0000 lvl=warn msg="error cloning repo" repo=xxx.example.com/a/b err="error cloning repo: repo xxx.example.com/a/b (https://git:tOkeNhErE@xxx.example.com/a/b.git) not cloneable: exit status 128 (output follows)\n\nfatal: unable to access 'https://git:tOkeNhErE@xxx.example.com/a/b.git/': Could not resolve host: xxx.example.com\n"
```

Thanks for replying!

**Comment by slimsag** [comment]
Ah sorry @neculaesei I missed that you were configuring the proxy through the container's env vars. As you noticed that will not work currently, I believe that is because we override the environment when doing `git` operations, but it may also break in other cases I am not aware of. That is what this issue is about (for Sourcegraph to have native support for running behind proxies)

In the meantime we think a transparent proxy should work. If you need HTTPS cloning, I would start here: https://medium.com/datadriveninvestor/how-to-transparently-use-a-proxy-with-any-application-docker-using-iptables-and-redsocks-b8301ddc4e1e Otherwise if just HTTP is okay I'd check out the transparent proxy links @keegancsmith sent above in https://github.com/sourcegraph/sourcegraph/issues/250#issuecomment-427325746

What that would give you is a setup which proxies all traffic from the Sourcegraph Docker container to your proxy regardless of the fact that Sourcegraph isn't aware of how to use HTTP proxies today.

**Comment by neculaesei** [comment]
@slimsag Thank you, I'll try the solution described in the article today! I think Docker should actually do something about this, having an env variable being the official answer to "how do I proxy a container's traffic" is not good enough. Docker should add support for proxies when declaring networks. Many people follow online guides to setup tor + "safe containers" that connect only via tor, when in reality just have env.http_proxy set. Sorry for the rant on Docker and thanks again for your time!

**Comment by keegancsmith** [comment]
If we have a work-around as simple as passing on the proxy env vars to git we should do that. I'll timebox looking into that today.

Another thing you can do is set the system gitconfig inside the container. Have a local file called `gitconfig` with the contents below. Then mount it inside the container at `/etc/gitconfig`.

```
[http]
        proxy = http://<username>:<password>@<proxy-server-url>:<port>
```

**Comment by neculaesei** [comment]
@keegancsmith It works, thank you!

**Comment by keegancsmith** [comment]
> If we have a work-around as simple as passing on the proxy env vars to git we should do that. I'll timebox looking into that today.

Just looked into this, we should be inheriting the parent process env. So not sure why git didn't respect it. However, I am glad the gitconfig trick works for you.

**Comment by neculaesei** [comment]
@keegancsmith at least on my machine, setting http_proxy manually has no effect on  git, so I guess git completely ignores it. curl works correctly.
git version: 2.21.0

**Comment by keegancsmith** [comment]
I've realised we aren't passing on the http_proxy related envvars. Easy to fix luckily.

**Comment by keegancsmith** [comment]
3.15 which will be released later today will respect http and git related environment variables. Quoting the CHANGELOG:

> `git fetch` and `git clone` now inherit the parent process environment variables. This allows site admins to set `HTTPS_PROXY` or [git http configurations](https://git-scm.com/docs/git-config/2.26.0#Documentation/git-config.txt-httpproxy) via environment variables. For cluster environments site admins should set this on the gitserver container.
