### ISSUE TITLE
Handle public repo visibility change when it becomes private

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#25217]
Copied over from [jira](https://sourcegraph.atlassian.net/browse/CLOUD-26)

Public repos synced via our cloud default external services could become private at some point in the future. In this case, we should detect it and remove the associated with the public external service.

We currently check for private repos when adding a repo, but not when syncing an existing repo. The difficulty is that the token associated with a public external service won’t actually see the private repo so we need to handle this case.

More context after some investigation:

* I added a public repo:
[ryanslade/visibility-test](https://github.com/ryanslade/visibility-test)
* Navigated directly to it on SG:
[ryanslade/visibility-test](https://sourcegraph.com/github.com/ryanslade/visibility-test) 
* It was cloned on demand and I could see it.
* Confirmed that it was in our DB and linked with our public github external service (id=4)
* Changed visibility to private in GitHub.
* Browsed to it again on SG, this should kick off another sync.
* Confirmed that it is still accessible and our database still shows it as public

In conclusion:

I was hoping there would be a quick fix, but doesn’t look like it.

The issue is that on .com we only sync a repo on demand once if it doesn’t exist in our database [here](https://github.com/sourcegraph/sourcegraph/blob/47eebbea8011e36c3b902ec66878553569ac1388/cmd/frontend/backend/repos.go#L82)

Note that this code path is never run if we find the repo in the DB. 

Once it exists, we never try and sync it again. We do attempt to update the repo content on every visit [here](https://github.com/sourcegraph/sourcegraph/blob/89490b6bb2b1df61a91e0fa226e077b093852a8f/cmd/frontend/internal/app/ui/handlers.go#L230):

But that code path will kick off a git pull not a code host API call.

We have two options:

1. When we fail to perform a git update on gitserver we requests a sync to check if we still have access to the repo
1. We trigger a sync occasionally when browsing to a repo. 

We would need to be very careful with option 2 since it could cause a big spike in API call. Option 1 is doable but something about having gitserver call back out to repo-updater feels wrong. Need some time to think about this.

**Comment by ryanslade** [comment]
I still think that having gitserver communicate back to repo-updater is a bad idea as it adds more coupling between these services.

As this is a special case for sourcegraph.com, we should handle it as a special case inside of `Syncer.SyncRepo`.

Where we currently check whether the repo is nil, we can add another check whether we failed to pull the repo by looking at the `gitserver_repos` table in the `last_error` column. If there was an error there we should try and sync again. If we are no longer able to find the repo, our repo syncing code will remove it.

**Comment by mollylogue** [comment]
Question. When I navigate to the `Syncer` I see that it has a `Store` for accessing the database, but this db seems to only be for the purposes of reading from the `repo` table and the external service table (I think) via the `RepoStore` and `ExternalServiceStore` fields.  Would we need to add in another "store" for accessing the `gitserver_repos` table? I'm just trying to avoid coupling of gitserver and repo-updater wherever possible so I wasn't sure if that was okay to do. Lmk if this question makes sense or not. I'm still in the mode of trying to understand the problem and the code I'll be changing.

**Comment by ryanslade** [comment]
Our general purpose stores exist in the `database` package and are meant have common methods that may be needed by more than one service. 

We also have the `repos.Store` which has `repo-updater` specific database methods and embeds other stores. Since we need to read `gitserver` specific data you're right, we need to use the `database.GitserverRepoStore`.

*Usually* we would just do something like `database.GitServerRepos(db).SomeMethod()` to create a new instance of the store with given database connection but due to a bit of debt we do things differently in the `repos.Store` and include other stores. 

So the short answer, I think it's fine to  include the `GitserverReposStore` in `repos.Store`. Just remember to initialise it in `NewStore` and include it in the `With` and `Transact` methods too.

This is probably something we can improve on since this pattern isn't really used anywhere else in the codebase AFAIK.

**Comment by mollylogue** [comment]
Okay, so I've reproduced this locally, and I have some follow-up questions. First, it looks like the `repo-updater` currently never touches my public repo that I navigate to via sourcegraph.com (local deployment). It seems that it is _only_ synced on-demand when I navigate to the repo in sourcegraph, and in that case it's just a `gitserver `call (which fails with a `Repository not found` error). But you were saying that we don't want to have `gitserver` then do anything? I'm just unsure if this repo will ever get touched by `repo-updater`, since I was under the impression that repo-updater won't handle on-demand syncs? I was under the impression that `repo-updater` explicitly didn't touch any repos w/ associated external service that is `cloud_default=true`.

**Comment by mollylogue** [comment]
Okay, I have a bit more context now. It looks like there is a single place `Syncer.SyncRepo` is currently called in the code, the `"repo-lookup"` endpoint of the `repo-updater`. I looked at the client to see where the [RepoLookup](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repoupdater/client.go?L69) function (which corresponds to this endpoint) was used, and it appears to be called only via the [Add](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/repos.go?L119) function, which gets called when someone navigates to a new repo on sourcegraph cloud. 

The problem occurs when the repo is then made private and the user navigates back to the repo in Sourcegraph. In this case the [GetByName](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/repos.go?L74) function is called, which just fetches the repo info from the db without checking if we should update. When I added the call to `RepoLookup` in the `GetByName` path (behind the `SourcegraphDotCom` env var), it gracefully handled attempting to fetch the repo and deleting it for me, resulting in a `Repository not Found` page, rather than showing the now private repo.

I personally like this approach, since this call to the `repo-updater` api is already present in this package/file and is super easy to do. But I realize there might be things I haven't thought of or impacts I might not know. Feel free to give feedback! 

Here are the WIP code changes that I validated locally: https://github.com/sourcegraph/sourcegraph/pull/28368

@ryanslade @indradhanush
