### ISSUE TITLE
Batch reports 100% complete when there's still 1 PR left

### ISSUE THREAD

**Issue by robbecker-wf** [sourcegraph/sourcegraph#25235]
- **Sourcegraph version:** 3.26.3
- **Platform information:** Should be independent of browser or client OS

#### Steps to reproduce:

1.  We created a batch with 213 PRs.
2. After merging or closing all but the last 1, the batch reports 100%

#### Expected behavior:

I would expect to still see 99% until the last PR is complete. My guess is the % reported is rounded to the nearest integer which is a fine level of granularity unless you're at the beginning or end of a batch. For instance it shouldn't say 0% done for a  batch if at least 1 PR is complete.

#### Actual behavior:
Showed 100% complete when there was still 1 remaining PR
![image](https://user-images.githubusercontent.com/6053699/134376649-37b89fe9-b59f-496d-9797-1bea460e8564.png)

Once that final PR was completed, it changed the status to a green checkmark
![image](https://user-images.githubusercontent.com/6053699/134377199-6f3bd582-ecbd-49c2-bd19-ad9fc10ce6df.png)

**Comment by mrnugget** [comment]
Hey @robbecker-wf! Thanks for reporting. We'll take a look.

**Comment by chrispine** [comment]
Curious to hear other opinions, but mine is that it should just be rounded down instead of to nearest integer, because that is what is implied by the word "Complete": you don't say it's 100% complete until it really is, you don't say 50% complete until at least 50% is actually completed, and you don't say 1% complete until at least 1% of the work has been completed. (This is not a strong opinion, and I'm open to others. 😄)
