### ISSUE TITLE
Browser extension and its Sourcegraph extensions are limited to a single Sourcegraph instance

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#254]
I don't know which component is at fault here, which is why I am filing on this repo.

1. Configure your Sourcegraph extension to point to dogfood, or some non-public instance, and make sure that `use sourcegraph extensions` is enabled in settings.
2. Go to https://github.com/sourcegraph/sourcegraph-graphql/blob/master/src/extension.ts and toggle inline discussions

**Actual**
The extension will call `https://sourcegraph.sgdev.org/.api/graphql?DiscussionThreads` and receive a response:

> {"data":{"discussionThreads":null},"errors":[{"message":"repo not found at this location, but might exist at https://sourcegraph.com/github.com/sourcegraph/sourcegraph-graphql?utm_source=datacenter","path":["discussionThreads"]}]}

**Expected**

For OSS it should fetch from sourcegraph.com and for private it should fetch from the configured instance?

I could also see an argument for fetching from both.

cc @chrismwendt @ijsnow @slimsag

**Comment by chrismwendt** [comment]
Sourcegraph extensions do not have the ability to choose which Sourcegraph instance they query. That choice is made by the browser extension.

The browser extension [provides](https://github.com/sourcegraph/browser-extensions/blob/ffb64d67db79b099c7879353fdaebfbf2b06194a/src/shared/backend/extensions.ts#L264) e-c-c an implementation of `queryGraphQL` which [falls back to Sourcegraph.com](https://github.com/sourcegraph/browser-extensions/blob/ffb64d67db79b099c7879353fdaebfbf2b06194a/src/shared/backend/graphql.tsx#L78) either when there's an AJAX error or a [set of conditions is met](https://github.com/sourcegraph/browser-extensions/blob/ffb64d67db79b099c7879353fdaebfbf2b06194a/src/shared/backend/graphql.tsx#L89-L92). None of those conditions include GraphQL-level errors, so the request is considered successful and `queryGraphQL` returns the response instead of falling back to Sourcegraph.com.

One problem here is that the browser extension doesn't know if a particular GraphQL query would succeed on Sourcegraph.com when it failed on the private instance.

A deeper problem is that the browser extension doesn't know which instance to query in the first place, and trying the specified URL then falling back to Sourcegraph.com does not work in all cases (e.g. this one). Perhaps the Sourcegraph instance could tell the browser extension whether or not it can service the request, and if not, redirect the browser extension to Sourcegraph.com (much like an HTTP redirect).

**Comment by slimsag** [comment]
I think the expected outcome should be:

1. First try sourcegraph.com
2. If that fails, e.g. due to repo not existing, then try the configured private instance

The question here is: how does a Sourcegraph Extension indicate this?

**Comment by sqs** [comment]
Will discuss mitigating this limitation when we start November 2018 (no promises we can do it, though)

**Comment by lguychard** [comment]
Let's track this in https://github.com/sourcegraph/sourcegraph/issues/643
