### ISSUE TITLE
Markdown Rendering: Empty link in badge renders incorrectly

### ISSUE THREAD

**Issue by khoslaventures** [sourcegraph/sourcegraph#2545]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Web browser version

#### Steps to reproduce:

1. Go to [sourcegraph/javascript-typescript-langserver/-/blob/README.md](https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver/-/blob/README.md).
2. Noticed the Apache License 2.0 badge. It has an empty url around it so it renders the brackets and parenthesis as the symbols themselves and doesn't parse them.

#### Expected behavior:
![image](https://user-images.githubusercontent.com/8366960/53701074-38ea6500-3dae-11e9-9a28-060dc30f3b9e.png)

#### Actual behavior:
![image](https://user-images.githubusercontent.com/8366960/53701081-499adb00-3dae-11e9-990a-f71fb503771c.png)
Seems to be an incorrect rendering of nested URLs around the badge I think.

**Comment by sqs** [comment]
Thanks for reporting. Our Markdown rendering (using Go's blackfriday package) has some other bugs, too, with code blocks and tables.  We need to fix these issues, and it'll likely require upstream patches (or using a different Markdown package).

**Comment by peterguy** [comment]
Checked the steps to reproduce just now, and the behavior is no longer present.
<img width="769" alt="Screenshot 2023-11-16 at 16 43 13" src="https://github.com/sourcegraph/sourcegraph/assets/129280/1ff40b4b-9a50-4016-b3c4-8baa25982208">
The odd-looking `build` render is because of [a newline inside the parentheses of one of the links](https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver@e63108446d2e375fd91a2484466a077f3fc065cc/-/blob/README.md?L25-26&view=code).
