### ISSUE TITLE
Code Folding 

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#25461]
#### Feature request description

Provide options to collapse blocks like if/else/for/while blocks, preprocessor blocks, function blocks, class blocks, etc, similar to what you get in an IDE

#### Is your feature request related to a problem? If so, please describe.

Usability enhancement

#### Additional context

[Customer](https://github.com/sourcegraph/accounts/issues/544)

/cc @felixfbecker

**Comment by macraig** [comment]
Hey @JoshuaKGoldberg! Apologies for the late reply, we were sorting out some team logistics to see how we could collaborate with you in the best way possible 😄 Thanks for volunteering to work on this feature! We've thought about a possible plan to approach this in two phases (that we'd appreciate your help on):

1. The first step would be for you to implement the ability to collapse/un-collapse lines of code. @tjdevries and @chrismwendt from the engineering team can help point you in the right direction where needed. In the meantime, @jjinnii will be exploring designs for how to expose code folding in our UI. 

2. Once we have a few design propositions in the form of an open [RFC](https://handbook.sourcegraph.com/communication/rfcs) (where your input will be more than welcome), we can work on implementing the final design together.

How does that sound to you?

**Comment by JoshuaKGoldberg** [comment]
That sounds fantastic, thanks @macraig!

My initial instinct is that since you're already using highlight.js and they've previously rejected code collapsing (https://github.com/highlightjs/highlight.js/issues/314, https://github.com/highlightjs/highlight.js/issues/797), my go-to preference would be to make some sort of open source extension for them.

An alternative would be to switch to snazzy looking new [CodeMirror 6](https://codemirror.net/6) but that seems like a lot for me to tackle :smile:... and finally getting code folding in hjs would be swell.

Looking forward to hearing back!

**Comment by chrismwendt** [comment]
Hey @JoshuaKGoldberg 👋 VS Code has a [code folding API](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider), and it seems like it would be great to add it to the Sourcegraph extension API. Let me know if you'd like to get started based on that info alone, or if you'd like to chat more about the implementation 😃

**Comment by JoshuaKGoldberg** [comment]
Oh, we might be talking about different things! I was hoping to add code folding to the repository browser on pages in `https://sourcegraph.com/<host>/<org>/<repo>@<commit>/-/blob/<path>/<file>` natively. 

For an example user story:

1. I want to investigate the typescript-eslint no-for-in-array rule works
2. I find [`no-floating-promises.ts` on sourcegraph.com/github.com/...](https://sourcegraph.com/github.com/typescript-eslint/typescript-eslint@81b25c12eceae89e181a7bdb3c8298d820cfe3e3/-/blob/packages/eslint-plugin/src/rules/no-for-in-array.ts)
3. The `meta` section is visual noise to me because I want to be able to quickly scan the important logic from the file
4. I click a ▽  next to line number `6` to collapse lines 6-18 (in VS Code terms, fold them)

I'd definitely be up for chatting more - here, on my [email](mailto:me@joshuakgoldberg.com), or however works for you!

**Comment by chrismwendt** [comment]
I think we're on the same page - I'm imagining 2 main parts:

- The new code folding extension API that allows extensions to tell Sourcegraph when and where to display folding regions in the UI
- The UI: exactly like you're describing it, the UI would ask the extension host for the set of folding regions for the current file (which would in turn ask each extension, and merge the results) and display clickable chevrons in the gutter and handle the hiding of lines

Chatting here works, or we can schedule a Zoom :+1:

**Comment by JoshuaKGoldberg** [comment]
I ended up not having time for this, and probably won't in the near future. If anybody else wants to tackle it, please do!

**Comment by fkling** [comment]
@tjdevries Yep, easy to do with CodeMirror. It has an extension for providing [folding functionality](https://codemirror.net/docs/ref/#h_folding). We only need the data.

**Comment by olafurpg** [comment]
Prototype adding folding ranges https://github.com/sourcegraph/sourcegraph/pull/40453

**Comment by felixfbecker** [comment]
The new GitHub code browsing UI now supports code folding

**Comment by philipp-spiess** [comment]
Hey folks! 

@tjdevries / @olafurpg since you two have worked on a prototype for the backend already: Do you have any idea how long it would take to build something that we can ship? The [prototype](https://github.com/sourcegraph/sourcegraph/pull/40453) looks fairly outdated by now plus I saw some discussion on placing this outside of SCIP.

cc @sourcegraph/code-exploration

**Comment by taras-yemets** [comment]
https://github.com/sourcegraph/sourcegraph/pull/47266
