### ISSUE TITLE
Hover property references another instance's function(?)

### ISSUE THREAD

**Issue by vyzaldysanchez** [sourcegraph/sourcegraph#2549]
#### Question description

Is it OK for the tool to match a property/function that it's not related to the instance it's being access from? For example, I had some Laravel request, and when hovering a property which is suppose to come as part of the HTTP body, it links it to a model relation function:

<img width="587" alt="screen shot 2019-03-03 at 11 21 27 pm" src="https://user-images.githubusercontent.com/8971713/53709621-9531a100-3e0f-11e9-9999-39d4ada0e2dc.png">

If this is not expected, then an issue could be filed.

#### Is your question related to a problem? If so, please describe or link to another issue.

N/A (that I know about)

#### Additional context

N/A

**Comment by sqs** [comment]
This is a known issue and occurs because PHP is using heuristics for code intel, not a (precise) language server that builds and compiles the code. See the "Limitations" section at https://sourcegraph.com/extensions/sourcegraph/php. We have a PHP language server and plan to use it for precise code intelligence in the future.

Assigning to @chrismwendt 	to see if there is any general, heuristic-based way we could avoid showing an incorrect hover here.

**Comment by chrismwendt** [comment]
Here's a relevant idea from https://github.com/sourcegraph/sourcegraph/issues/2298

> Use scope information from ctags and some rudimentary type inference to determine the enclosing class

I think it can actually work, but will take a while to fully research and prototype.

**Comment by aidaeology** [comment]
Closing as we now have better UI to explain basic vs precise code intel behavior.
