### ISSUE TITLE
ESLint passed on PR branch, but failed on main

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#25550]
Context: https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1632985048088500

The ESLint job passed on the PR branch here: https://buildkite.com/sourcegraph/sourcegraph/builds/110098#d1dda4b3-2953-4e47-b2e9-eacf4dc6c1cd

…but failed on main: https://buildkite.com/sourcegraph/sourcegraph/builds/110084#e3c706ee-072c-4f3f-a7b6-09258e4f2d6e

We should investigate to understand why this happened. If it was a true positive on main (e.g., due to a mid-air collision between two PRs that were each green), then there’s no action to take.

**Comment by pdubroy** [comment]
I'm guess it's related to #25087? cc @valerybugakov

**Comment by valerybugakov** [comment]
> I'm guess it's related to #25087?

Correct, [this PR](https://github.com/sourcegraph/sourcegraph/pull/25087) introduced stricter Typescript types for our GraphQL schema. These changes were not pulled into `fa/amplitude-http` that's why ESLint job [passed](https://buildkite.com/sourcegraph/sourcegraph/builds/110098#d1dda4b3-2953-4e47-b2e9-eacf4dc6c1cd) on the PR branch. Pulling changes from main into the branch results into a failure.

> If it was a true positive on main (e.g., due to a mid-air collision between two PRs that were each green), then there’s no action to take

Closing the issue, because that was the reason for the failure on main.
