### ISSUE TITLE
Unclear or missing documentation for adding TLS to Sourcegraph language server extensions

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2559]
After deploying a Sourcegraph instance and following the documentation for the Typescript language server, it was unclear how to add TLS to the language server.

The documentation can be found here: https://sourcegraph.com/extensions/sourcegraph/typescript

There's minimal information TLS in the documentation:

> TLS is optional but recommended for production deployments. It is used if TLS_KEY and TLS_CERT environment variables are set.

A couple questions (cc/ @chrismwendt and @felixfbecker ):
- Is the mention of TLS specific to the Kubernetes deployment?
    - If yes, why is it not necessary when using Docker?
- Do all language server extensions need to have TLS configured?
- Do we have other documentation for using Let's Encrypt on our code intel extensions?

---

### Tasks

- [] Documentation for TypeScript, Go and Python language servers.
- [] Screencast for setting up the Go language server with SSL.

**Comment by chrismwendt** [comment]
Our docs are lacking in this area. I think it's in part because I haven't set up any language server in the same way a customer would (behind an auth proxy), let alone documented it.

If it's ok for the communication between the auth proxy and language server to be unencrypted, then I don't think it's necessary to set up TLS for the language server.

> - Is the mention of TLS specific to the Kubernetes deployment?

No, it applies to Docker, too.

> - Do all language server extensions need to have TLS configured?

I think it will work without TLS, but it's insecure without it, which is why I made the "Secure deployment" section stand out more https://sourcegraph.com/extensions/sourcegraph/go

> - Do we have other documentation for using Let's Encrypt on our code intel extensions?

Not that I know of.

**Comment by ryan-blunden** [comment]
I'll take ownership of this as part of improving the docs for 3.2

**Comment by KattMingMing** [comment]
Open PR for fixing Typescript docs: https://github.com/sourcegraph/sourcegraph-typescript/pull/122

**Comment by ryan-blunden** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph-typescript/pull/122
