### ISSUE TITLE
Incorrect examples on Sourcegraph.com Search

### ISSUE THREAD

**Issue by khoslaventures** [sourcegraph/sourcegraph#2567]
- **Sourcegraph version:**  Sourcegraph.com

#### Steps to reproduce:

1. Go to [sourcegraph.com/search](https://sourcegraph.com/search)
2. Click one of the examples, like "Popular NPM packages". You'll see it has `repogroup` used twice in query. 

#### Expected behavior:
![image](https://user-images.githubusercontent.com/8366960/53772099-0158e700-3e9a-11e9-8ec8-e5594d310d8d.png)

#### Actual behavior:
![image](https://user-images.githubusercontent.com/8366960/53772082-f43bf800-3e99-11e9-8b5f-852c5aca09f1.png)

**Comment by sqs** [comment]
I propose the following limited workaround to make the workflow described above (click a scope on the homepage on Sourcegraph.com) work:

- On Sourcegraph.com, if the query input contains `repogroup:sample` and the user clicks a scope that would result in the addition of any `repogroup:` token, remove   `repogroup:sample` from the query when adding the scope's value to the query.

This is actually a bad bug that I was surprisingly unaware of. @attfarhan I think this is more important than (and in line with the goal of) https://github.com/sourcegraph/sourcegraph/issues/1234. If the workaround above makes sense and you think you can fit it into 3.2 (possibly slipping some of #1234), please move this into 3.2.

---

More background: On the face of it, this is actually a backend issue because all scopes should work the same way (append to query when enabled), and the expected behavior above would mean that `repogroup:` would work differently. The underlying reason why that's expected is that 2 `repogroup:` filters can't be used in the same query. That is a limitation we should remove.

However, that backend work is low priority for 2 reasons:

- We are considering removing/deprecating `repogroup:` because it is not very widely used. We need to survey customers first to better understand how it is actually used before doing so.
- The impl will probably change a lot with subquery search #1005.

Thus the limited workaround I proposed above.
