### ISSUE TITLE
insights: provide organization connection for dashboard visibility

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#25698]
Return a connection to organizations that the current user context has access to from the dashboard node. This will primarily be used to display "ownership" / visibility information about the dashboard.

**Comment by leonore** [comment]
@coury-clark I'm going through old outdated issues. can we close this? it doesn't look relevant anymore (dashboard shows which organisation they're attached to, so this might have been done).

**Comment by coury-clark** [comment]
@leonore sounds good, closing

**Comment by felixfbecker** [comment]
Could one of you check in the schema if the connection was actually added? I want to make sure the reason we're seeing it in the UI is not because the webapp makes an extra API request or some other workaround, in which case this would still be an open debt issue

**Comment by vovakulikov** [comment]
> not because the webapp makes an extra API request or some other workaround

@coury-clark @leonore It does, at the moment, we have some information about users/organisations that the given dashboard is included in, but our API definitely doesn't have a good graph-like API over this information. I have an issue with it here https://github.com/sourcegraph/sourcegraph/issues/32780

I think this issue is either a duplicated of https://github.com/sourcegraph/sourcegraph/issues/32780, or it was about adding grants to the API in this case, let's close it and keep our eye on https://github.com/sourcegraph/sourcegraph/issues/32780
