### ISSUE TITLE
Dry-run external service configuration before saving

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2573]
When saving an external service we call `repoupdater.DefaultClient.SyncExternalService` with the configuration. However, we only do that once we have updated or created the external service in the DB. This is meant to trigger syncs of valid configurations. However, a user may put in incorrect values / unexpected queries resulting in errors or unexpected repos synced.

Adding an endpoint which does dry runs would allow the user to catch errors as well as understand how the configuration affects the set of repositories Sourcegraph syncs.

**Comment by tsenart** [comment]
@beyang: I think #7460 goes along the lines of what we were thinking here. In essence, this issue was proposing an endpoint in the repo-updater API that would simply validate an external service instead of doing a full sync. This would be accomplished by using the `ListRepos` method of the `Source` constructed from the provided external service with a small timeout, within which if no errors would occur, we'd know the external service config would be valid.

Would working on this small endpoint be something that fits in your plans / OKRs?

**Comment by beyang** [comment]
Sure, assign to me.

**Comment by slimsag** [comment]
This seems like some relatively deep repo-updater changes and not in the scope of distribution, please correct me if I am wrong, though. Reassigning to cloud.

**Comment by keegancsmith** [comment]
We mostly do this now, except we do not communicate back to the user which repositories are done. I would also suspect that this feature just won't work for large installations. As such I think we should just close out this feature request now and mark it as out of scope. Taking the liberty to do that, please re-open otherwise.
