### ISSUE TITLE
Browser extension: some event logs make it to the Sourcegraph Cloud database

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#25778]
Some event logs are appearing in the Sourcegraph Cloud BigQuery events database. These events have a source of `CODEHOSTINTEGRATION`. [However, the documentation in the code specifically says that events will only be sent to the local database, and on Cloud, events don't get sent.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/backend/userEvents.tsx?L44-54)

I can't reproduce it reliably, but I can see these events fairly regularly appearing in the BigQuery DB. @erzhtor and I found out that the event URL when these events are sent is actually `null`, so [this check](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/backend/userEvents.tsx?L52) doesn't get triggered. 

![image](https://user-images.githubusercontent.com/16265452/136358468-6d1aa269-5287-4c70-90f3-260072e8a1a2.png)

#### Expected behavior:

No browser extension logs make it into BigQuery.

#### Actual behavior:

Some logs from the browser extension are appearing in BigQuery.

**Comment by erzhtor** [comment]
Based on our [browser extension privacy docs](https://docs.sourcegraph.com/integration/browser_extension#privacy), seems that we need to log cloud events as well.

Regarding the URL being `null`, I think it might be from my local/dev environment when I was working on the fallback URL feature since code-wise it can't be `null` at all (also, dates from the screenshot match the period when I was working). 

P.S: I didn't know that the dev environment still sends user event logs, but it does, not sure why it is enabled 🤷
