### ISSUE TITLE
Add HTTP basic auth to language servers

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2595]
All customers that I know of only deploy language servers inside a VPN, but it would be useful for the language servers to support HTTP basic auth for both the case when they're accessible from the Internet and for additional security.

Tech sketch:

- [x] Add docs for requiring HTTP basic auth to language servers through nginx https://github.com/sourcegraph/sourcegraph-go/pull/37 (TODO move to sourcegraph/sourcegraph)
- [x] Update extension READMEs to mention how to add HTTP auth:
  - Create an `.htpasswd` file with a password
  - Configure nginx to require basic auth before routing traffic to the language server
  - Add the basic auth password to the `{go,typescript,python}.serverUrl` setting

cc @KattMingMing @slimsag

**Comment by slimsag** [comment]
We also will have to advise HTTPS btw, else that password can be stolen easily.

**Comment by beyang** [comment]
Would a user then have to manually navigate to `https://$LANG_SERVER_URL` to enter in the basic auth password? I think a much better solution would be to have Sourcegraph serve as auth proxy (see "Auth proxies" here: https://github.com/sourcegraph/security-issues/issues/11).

**Comment by slimsag** [comment]
I haven't had a chance to read the issue you linked yet, but the answer to your question is:

No, the site admin would set the `go.serverUrl` to contain a shared basic auth password which provides access to the langserver. There are some obvious risks with this approach (that the password is shared) so it is definitely worth considering your suggestion here instead.

**Comment by chrismwendt** [comment]
There are 3 valid approaches:

- HTTP basic auth in each language server (advocated for by @sqs)
- HTTP basic auth in nginx config (advocated for by @keegancsmith)
- Auth proxy via Sourcegraph (advocated for by @beyang)

I don't have much of a preference from the implementation perspective. What are other people's thoughts (pros/cons of each)?

**Comment by sqs** [comment]
I think HTTP Basic auth in nginx config is best for the following customer and product reasons:

- Using HTTP Basic auth in nginx config would be great because it could reuse Sourcegraph's own TLS config. (Setting TLS up for lang servers is a pain; we've heard this from customers.) Would we recommend customers configure subpaths (or other ports) on their Sourcegraph external URL to point to their language servers? (I (and @KattMingMing) believe customers would find it onerous to manage a separate nginx process/instance/container, so I'm assuming this entails using the [existing nginx](https://docs.sourcegraph.com/admin/nginx) in `sourcegraph/server`.)
- Doing it via `sourcegraph/server`'s nginx config is kind of a v0 of the "auth proxy via Sourcegraph". Eventually, Sourcegraph (the mgmt console, perhaps) will manage the nginx.conf file itself and can have an "Install language server" button that does it all. That is clearly out of scope here, but it is nice to know that doing it in nginx config would evolve in a (probably) good direction.

**Comment by beyang** [comment]
Would the HTTP basic auth in nginx config option mean that language servers are served from the same hostname or different hostnames? If different hostnames, then there is still the issue with external auth proxies mentioned in https://github.com/sourcegraph/security-issues/issues/11

**Comment by felixfbecker** [comment]
I am a bit confused here, which party is authenticating to which other party through basic auth?

**Comment by chrismwendt** [comment]
@beyang Same hostname, most likely. It's pretty easy to add another route in the nginx config such as `/go`.

@felixfbecker Browsers are authenticating with nginx, which acts as a proxy to language servers.

Here's a PR to add docs to sourcegraph-go for nginx config https://github.com/sourcegraph/sourcegraph-go/pull/37 Since this will be the same for every language server, I'll move it to sourcegraph/sourcegraph and link to those docs from each language server.

**Comment by felixfbecker** [comment]
In that scenario, is the whole Sourcegraph instance protected by basic auth user+password? Because I don’t think you can pass basic auth programmatically when opening a WebSocket

**Comment by chrismwendt** [comment]
@felixfbecker No, only the `/go` route would be protected. `wss://foo:bar@localhost:7080/go` worked on  my machine.

**Comment by felixfbecker** [comment]
Interesting. I'm surprised because `fetch()` will throw if the URL contains auth info, so I expected `WebSocket` to behave the same.

**Comment by felixfbecker** [comment]
Only thing I could find is this SO answer that says WebSocket Basic auth is deprecated: https://stackoverflow.com/a/4361358/4208018
