### ISSUE TITLE
Add auto-inference for Rust

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#26086]
The rust-analyzer project recently added support to emit LSIF, see

- https://github.com/rust-analyzer/rust-analyzer/pull/10181
- https://github.com/rust-analyzer/rust-analyzer/issues/8696

To run the LSIF indexer, install `rust-analyzer` and run `rust-analyser lsif . > dump.lsif` in a Rust project. Some Sourcegraph repos that have manually uploaded precise code intel for Rust

- https://sourcegraph.com/github.com/BurntSushi/ripgrep/-/blob/crates/regex/src/ast.rs?L23:43#tab=references
- https://sourcegraph.com/github.com/tjdevries/vim9jit/-/blob/src/parser/mod.rs?L22:5#tab=references

It would be nice if Sourcegraph could auto-index Rust repos that have a Cargo.toml file. Here are the steps that would need to happen

- publish a sourcegraph/lsif-rust docker container that includes an installation of `rust-analyzer`
- add `rust.go` and `rust_test.go` files, similar to `java.go` here https://github.com/sourcegraph/sourcegraph/blob/13917e9304cc326b42273bfb91e81cb0d2bc6c58/lib/codeintel/autoindex/inference/java.go

**Comment by sandhose** [comment]
I recently added automatic code intelligence on a Rust project based on the new LSIF indexer in rust-analyzer with GitHub Actions.

The interesting part of the workflow is here: https://github.com/matrix-org/matrix-authentication-service/blob/cf8793da2775b0f1a8e0413a590d73cbb1f01ef4/.github/workflows/check.yaml#L92-L105

Rather than publishing a Docker image with both tools (Sourcegraph CLI & rust-analyzer) I'd suggest checking with the team from the [actions-rs](https://github.com/actions-rs) org to publish either a "setup rust-analyzer" action that installs rust-analyzer in the PATH, or an "index Rust project" that downloads and runs `rust-analyzer lsif`.
On that note, for some reason the existing [`lsif-upload-action`](https://github.com/sourcegraph/lsif-upload-action) did not work for me so I had to manually download and execute the Sourcegraph CLI binary.

The other point is that rust-analyzer LSIF dumps lack monikers, which s there is no cross-repository indexing support yet. I'd be happy to help implementing that in rust-analyzer, but I think I would need some guidance to understand how Sourcegraph handles monikers, especially with multiple versions, and how to deal with indexing/referecing `std`

**Comment by varungandhi-src** [comment]
> Rather than publishing a Docker image with both tools (Sourcegraph CLI & rust-analyzer) I'd suggest checking with the team from the actions-rs org to publish either a "setup rust-analyzer" action that installs rust-analyzer in the PATH, or an "index Rust project" that downloads and runs rust-analyzer lsif.

I don't think the Docker image is intended as an alternative to a GitHub action. Rather, we can do both. The Docker image would be used by Sourcegraph (similar to the Docker image for say [lsif-java](https://github.com/sourcegraph/lsif-java/blob/main/auto-indexing/Dockerfile) or [lsif-go](https://github.com/sourcegraph/lsif-go/blob/master/Dockerfile)), and the GitHub action would be used by folks who want to upload LSIF indexes in CI.

**Comment by varungandhi-src** [comment]
Following up on this:

> > On that note, for some reason the existing lsif-upload-action did not work for me so I had to manually download and execute the Sourcegraph CLI binary.
>
> Is this still an issue?

I just [fixed a typo in the shell script](https://github.com/sourcegraph/lsif-upload-action/commit/a3b808c679b0b33fda9158eb5cc997d8605a29b5) being used; you may have run into an issue with that if you tested with master.
