### ISSUE TITLE
repo-updater: Use ID in scheduler instead of name

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2609]
Right now the scheduler is keyed by name, leading to it not detecting renames from the syncer. We should use an ID (internal or external) instead.

**Comment by tsenart** [comment]
So, this change turns out to be larger that expected because the enqueue-repo-updater endpoint takes in a name and URL. This endpoint is called from [many places](https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+EnqueueRepoUpdate) and is always preceded by a call to [backend.GitRepo](https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+backend.GitRepo) which in turn may call out to repo-updater with lookup.

There's a lot to unroll here. Once all repo kinds are managed by the new syncer, there's a big clean-up to do here. Callers should just pass a repo ID, nothing else. Repo-updater takes care of the rest, and, since now we store the clone URLs in the database, we won't need all those hacky quickGitServerRepo functions and similar.

Additionally, we should consider if it's best to use the external ID. Are there cases where we'd want to enqueue an update for a repo that doesn't yet exist in the database?

**Comment by keegancsmith** [comment]
> Are there cases where we'd want to enqueue an update for a repo that doesn't yet exist in the database?

No.

Could we update your implementation to handle ID being zero but the name being set? If name is set we look up the ID in the DB.

**Comment by tsenart** [comment]
> Could we update your implementation to handle ID being zero but the name being set? If name is set we look up the ID in the DB.

We could do that, but I feel that the systematic untangling work described above still needs to happen. The call graph is getting really hairy and scary.

**Comment by keegancsmith** [comment]
After chatting about this we need to solve this so that the scheduler can support renames. The larger issue of even working out what needs to be done about name being passed around will be done in 3.4. Filed https://github.com/sourcegraph/sourcegraph/issues/3345

**Comment by keegancsmith** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/3369
