### ISSUE TITLE
Deploy executors for demo.sourcegraph.com

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#26143]
We want to dogfood using server-side batch changes, and we also want to start demo-ing it to customers. We cannot use sgdev for demos, because it contains private code (and CEs don't use it).

#### Proposal

Deploy executors for demo.sourcegraph.com, that we can use in demos, with autoscaling.

This will be a good dry run for executors, and the setup docs!

#### Success criteria

- Malo (and others!) are able to run a few batch changes server-side every day on demo.sourcegraph.com.
- We reach a point where customer engineers are comfortable demo-ing server-side instead of locally

**Comment by malomarrec** [comment]
Result of sprint planning:
- As an _exception_, in order to showcase the bleeding edge UI, it's fine demoing on k8sgdev with cherry picked examles.
- Better: deploy GCP executors, connect locally with ngrok, and do a local demo.

**Comment by mrnugget** [comment]
PR here: https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/145

Current status: executors are running on demo.sourcegraph.com, auto-scaling is enabled (1<->5 instances), observability is **not** on yet, because we don't know how to change the Prometheus config on that instance.

Also: executors only work for batch changes right now.

**Comment by eseliger** [comment]
All done, what's left is merging the PR which involves running the upgrade procedure for managed instances. I think this ticket is done now though, so I'll close it.
