### ISSUE TITLE
Enable new searcher by default 

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#2625]
As we continue work on existing issues and changes to the search code base, we're creating more technical debt because the work is being done on code that is already deprecated. In addition to this, the code removal will help others ramp up on the code faster.

[As stated in the planning document](https://github.com/sourcegraph/docs-private/blob/master/201809/hierarchical-search-2.md#implementation) (and confirmed with some smoke tests), we decided to map our existing query syntax to the new parser. If I'm understanding correctly, this means that the new query syntax will the the same as it is now with added support for sub queries. Is it possible to use the new searcher with the old query syntax (i.e. users notice no difference) so that we can enable the new searcher code path sooner rather than waiting for hierarchical search? This will enable us to begin working on and gaining an understanding of the new code path without duplicating any work. 

I've played around with the new searcher path with the `!hier!` query flag and noticed that the same search takes much longer with the flag enabled.

- **~5.4s** - [!hier! repo:github\.com\/sourcegraph\/ test](https://sourcegraph.com/search?q=%21hier%21+repo:github%5C.com%5C/sourcegraph%5C/+test) 
- **~1.7s** - [repo:github\.com\/sourcegraph\/ test](https://sourcegraph.com/search?q=%21hier%21+repo:github%5C.com%5C/sourcegraph%5C/+test)

@keegancsmith what needs to be done before we enable the new searcher? Below is a list of tasks (including stretch) taken from the [second hierarchical search planning document](https://github.com/sourcegraph/docs-private/blob/master/201809/hierarchical-search-2.md#rough-roadmap-including-stretch-tasks):

- Upstream the type: operator into zoekt.
- Switch to a hierarchical query parser (implement or borrow from zoekt) and implement a way to convert the queries into our current pattern structure.
- Evaluator which evaluates type:repo subqueries.

**Comment by keegancsmith** [comment]
I like this idea. :+1:

- Upstream the type: operator into zoekt is not done, but exists in our fork. I don't think this is a blocker.
- Hierarchical search is slower for searcher. I have done no perf work on it yet.
- diff search has not been ported and is quite a lot of work. I think my original plan was to not support hierarchical searches so only support queries which can be translated into the old format.

So I think a decent plan is:
- Address performance issues in searcher. We have benchmarks you can use so this task is good because you will understand how to implement a hierarchical search before you work out how to make it faster. I would budget 2 weeks for this and we would need to pair a bit as well to help familiarize yourself.
- Write a converter from hierarchical queries into old style (or is it something else?). It is only allowed to support non hierarchical queries.
- Write a converter from old style into hierarchical queries. Most of this code exists for zoekt already.
- Delete a lot of code in graphqlbackend.

**Comment by ijt** [comment]
I don't understand the bit about converting hierarchical queries into old style. Don't you want to convert old style into hierarchical?

**Comment by ijt** [comment]
Closing this as obsolete.

**Comment by ijt** [comment]
I'm reopening this issue to explore the possibility of building on Keegan's work.

**Comment by ijt** [comment]
Closing this again because it's not really focused enough.
