### ISSUE TITLE
VSCE: Implement automated releases

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#26437]
We can reference both the existing VS Code extension (which uses [semantic-release](https://github.com/semantic-release/semantic-release)) and our browser extension (releases on commits to the `bext/release` branch).

**Comment by jjinnii** [comment]
@tjkandala  Does this encompass automatic testing?

**Comment by abeatrix** [comment]
A [personal access token](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) from the marketplace might be required for the [publishing step](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions)

Note: the vsce cli tool provides the [auto-incrementing the extension version](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#autoincrementing-the-extension-version) that we can use.

**Comment by abeatrix** [comment]
@tjkandala Can you clarify the end goal of this issue, please? Just want to make sure we are on the same page 😄 

By Implementing automated releases for the VS Code extension, are you referring to the ability to publish the extension directly to the Marketplace in one step/command? Or is there more than that? 

The VSCE CLI tool provided us with the ability to determine the next version number and publishing the package directly to marketplace using the `vsce publish patch` command, so I don't think implementing [semantic-release](https://github.com/semantic-release/semantic-release) is necessary in this case. 

If I understand the task correctly, using the browser extension example provided, do you agree with the following appraoch: 
to implement the automated release so that when we make a commit to a specific branch, say `vsce/release` for example, it should trigger the `vsce publish patch` command to publish the extension directly to the marketplace automatically? 

Thanks!

**Comment by tjkandala** [comment]
@abeatrix I believe the use of semantic release is to automatically determine what version to publish at through commit messages. However, since we won't have a clean "semantic commit" history like we had enforced for the old repo, it wouldn't make sense now. A release process like you've described would be sufficient

**Comment by abeatrix** [comment]
PR for review: https://github.com/sourcegraph/sourcegraph/pull/34537

After the PR has been merged to main, we will need to add the newly added operation and the access token for the VS Code marketplace to buildkite for the automated process to be completed
