### ISSUE TITLE
Feedback and command line button in nav flash on page load

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#26435]
## Problem statement

Command buttons are flashing. Seems like it's a `transition` problem.

https://user-images.githubusercontent.com/19534377/138307798-c247073e-670c-42c1-be5c-9cf73239c2cb.mov

## Success criteria

Command buttons are not flashing on page load.

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov After investigated, I found a reason for this issue, it's the `theme` hook adds `theme-light` class into html after those components are rendered, I tried to use `var(--gray-03)` directly (instead of `var(--border-color)`) in `client/web/src/nav/Feedback/FeedbackPrompt.module.scss > .toggle` and  the flashing effect is gone.

What do you think about this case?

https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/client/web/src/theme.ts?L72

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, thanks for looking into it! I started digging into the reason for the delayed theme class insertion and eventually fixed this issue [here](https://github.com/sourcegraph/sourcegraph/pull/27385).
