### ISSUE TITLE
insights: one time migration for all insights

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#26533]
Currently, insights migrate on a schedule every 10 minutes from settings to the DB. In order to deprecate this process we need to disable these migrations and perform a one time out of band migration. In this OOB migration we should do the following:

1. In global settings
    1. Determine if global has any insights (any kind) defined in the settings
    2. If so, migrate each insight to the database
    3. If so, create a private dashboard with global grant named `Global insights` and attach all insights found in the global settings.
    4. Create any custom dashboards that do not exist, and attach any insights that are associated. These dashboards should have `global` grant
2. For each org
    1. Determine if they have any insights (any kind) defined in their settings
    2. If so, migrate each insight to the database
    3. If so, create a private dashboard with the org grant named `${org name}'s insights` and attach all insights found in the org settings 
    4. Create any custom dashboards that do not exist, and attach any insights that are associated. These dashboards should have the `org` grant
3. For each user
    1. Determine if they have any insights (any kind) defined in their settings
    2. If so, migrate each insight to the database
    3. If so, create a private dashboard with the user grant named `${username}'s insights` and attach all insights found in their settings 
    4. Create any custom dashboards that do not exist, and attach any insights that are associated. These dashboards should have the `user` grant

As long as we go from global -> org -> user we should never find a situation where an insight on a dashboard cannot be referenced.

**Comment by felixfbecker** [comment]
Moving this from Proposed to Todo, this is really important to get into the release 🙂

**Comment by coury-clark** [comment]
> Moving this from Proposed to Todo, this is really important to get into the release 🙂

I don't think there is any need to get it in this release - unless I am misremembering we plan to release this with a disabled feature flag. We can't do a final migration until we intend to have it enabled.

**Comment by felixfbecker** [comment]
Likely that I misremembered it, mea culpa. We don't currently seem to have a source-of-truth place where we have documented how we plan to release the settings migration (at least I can't find on) which I think would be good to have. Would you mind adding a short section to the tracking issue https://github.com/sourcegraph/sourcegraph/issues/22524 under "Plan" named "Release plan" that describes in which release we intend to ship the migration with the feature flag, when it'll be on by default if not immediately, when we would plan the final migration, and when we would remove the feature flag?

**Comment by felixfbecker** [comment]
I think at least at _some_ point we discussed in the sync that we would flip the switch [on by default] after this iteration, because I remember filing this issue during our sync based on @unclejustin's suggestion  https://github.com/sourcegraph/sourcegraph/issues/26593, which is assigned to this iteration. So that's probably where my memory came from, and there are at least some contradictory things here we need to reconcile (e.g. moving that issue to a different iteration).

**Comment by Joelkw** [comment]
We can adjust this plan if need be, but I thought we'd aligned on letting the flag "exist" (so you can turn this off if something goes wrong) but having it on by default for the release, as noted in the team sync meeting notes [here](https://docs.google.com/document/d/1cftSl8GMuw4uUv91wpgpMCPB8BFJ28dd3FojBYDB4rI/edit#bookmark=id.to7r6i7cc6j7).

**Comment by coury-clark** [comment]
I see - so I was misremembering, got it.

So the thing about this ticket is this really is the *last step*. If one were to re-enable settings after they perform this one-time migration, it would break the migration and it would have to be reset and run again (which wouldn't be obvious or probably controllable from the same feature flag). I think we still should be okay to enable on by default, but this ticket we should pair with the same release that removes the feature flag and retires settings permanently.

**Comment by Joelkw** [comment]
Got it, thanks @coury-clark . Without this, if we release with the flag on, what will happen to existing insights? (Will they still show up, but just be pulled from settings still?)

**Comment by coury-clark** [comment]
@Joelkw Everything should work as is today with the syncing jobs. Having said that, definitely something we will want to try.

**Comment by felixfbecker** [comment]
Okay, so based on https://github.com/sourcegraph/sourcegraph/issues/26533#issuecomment-961318901 I'm removing this ticket from this iteration then, and we'll do it in a later release (added a note in the "Release" column).

Thank you btw to @CristinaBirkel for assigning it to this iteration milestone, which triggered this discussion and uncovered the misalignment. I think this shows how important it is to assign issues to milestones so that we're all aligned on what we plan to do when 🙂 

I also added a brief release plan section to the tracking issue.

What I'd still like to get added there is how the feature flag will behave. E.g.
- With the feature flag on, will insights get returned from both settings and the DB?
- With the feature flag on, will edits and creations through the API only be stored in the DB, or in both settings and the DB?
  - And when turning the feature flag off after creating or editing insights with the flag on, will those insights/changes be lost?
- With the feature flag off, only settings insights are returned?

These are things we need to have clarity on cause we may have to communicate them to customers (and of course on the engineering front we need to be aligned on the behavior). @CristinaBirkel @coury-clark could one of you add that information to the release plan in the tracking issue?

**Comment by coury-clark** [comment]
@felixfbecker I added some notes to the tracking issue for the release plan. If everyone could please take a look 🙇

**Comment by coury-clark** [comment]
Modification to the algorithm based on [slack context](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1637008350353500?thread_ts=1637003653.346900&cid=C014ZCKMCAV) and sync with @CristinaBirkel 

1. For each insight tier (global, org, user) we will modify the insight IDs in the following way:
    1. Leave insight ID as is if in global settings
    2. Append `-org-${orgId}` where `${orgId}` is replaced by the org ID containing the insight
    3. Append `-user-${userId}` where ${userId}` is replaced by the user ID containing the insight

For each user retrieve all orgs the user is a member of.

When resolving *any* dashboard references, we will perform a lookup to get the correct insight ID by constructing a query similar to this (for user `1` who is a member of org `5, 6` with a dashboard reference `insights.searchInsight.myFavoriteInsight`:
``` SQL
select unique_id from insight_view
where unique_id
          similar to 'insights.searchInsight.myFavoriteInsight-%(org-5|org-6|user-1)%'
or unique_id = 'insights.searchInsight.myFavoriteInsight'
limit 1;
```

In the `similar to` clause, we will construct a condition for each org and for the user ID currently being migrated.

**Comment by Joelkw** [comment]
Thank you for writing this up @coury-clark @CristinaBirkel ! Couple of quick questions to just confirm – 

1. Does this return us to the "originally proposed state" where effectively we "guess" at the collision / non-unique case, but now because we appended things to the IDs we at least guarantee that we won't accidentally add an insight (say, from user 2 or org 7 here) that this user shouldn't see? Or is this "one step better" and this will perfectly reconstruct all dashboards? 

2. Separately, stupid question probably / I'm likely misinterpreting how this works, but let's say that we are reconstructing a dashboard that was originally in "Org 5". (If nothing else, this will help my understanding of the solution.) 
    1.  Let's say both Org 5 and Org 6 have insights of `myFavoriteInsight` in the ID. 
    2. Let's say that this particular user-1 has access to _both_ Org 5 and Org 6.
    3. Some other _user-2_ only has access to Org 5's dashboards. 
    4. Both org 5 and org 6 have their own distinct "myFavoriteInsight" insights on a dashboard within them. 
    4. Now, when we reconstruct this "org 5 dashboard reference that user-1 has", suppose that we first match the `myFavoriteInsight` that's a part of org 6. (Which I think we can do because we check for all orgs the user has?) 
    5. When user-2 checks this reconstructed org 5 dashboard, it shows the (secret, potentially) insight from Org 6? 
    6. _I assume one of these steps has an incorrect assumption, I'm probably misunderstanding how step (v.) works_

**Comment by CristinaBirkel** [comment]
1. Yes, it doesn't guarantee that we will always get it right with the dashboard references, but does guarantee that if it's wrong it won't be a permissions leak.
2. The only place this issue occurs is on private dashboards with references to org insights. So I think where your example veers off is:
v. I don't think that an "org 5 dashboard reference that user-1 has" is a thing. Org 5 can have dashboards, but they will never accidentally reference insights from another org. Additionally, user-1 might have a private dashboard with references to an insight that gets matched from either org-5 or org-6, but that dashboard won't be visible to uesr-2. Does that make sense / am I understanding your example correctly?

**Comment by Joelkw** [comment]
@CristinaBirkel thank you! I appreciate the answers. 1. makes sense. 

As for 2., I think that makes sense. I misread: 
> In the similar to clause, we will construct a condition for each org and for the user ID currently being migrated.

So I understand that this migration runs "per org dashboard" and "per user dashboard"? I misunderstood the "and for the  user ID" part, I though that meant it was running "per org dashboard-user ID pair" which is how you might end up with insights the user can see that the org can't when you're migrating an org dashboard. (Maybe that's still not correct, but I trust that the concern has been communicated and understood by y'all so I'm not worried about this / this isn't an urgent question, just was curious.)
