### ISSUE TITLE
Support Apple M1 machines with`sg setup`

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#26613]
As mentioned in [this slack thread](https://sourcegraph.slack.com/archives/C07KZF47K/p1631567978338700?thread_ts=1631567135.332600&cid=C07KZF47K), it would be nice if `sg setup` worked on M1 machines so devs don't have to manually follow [these steps](https://github.com/sourcegraph/sourcegraph/blob/main/doc/dev/how-to/m1_mac_local_dev.md).

**Comment by jhchabran** [comment]
- [ ] Puppeteer case: will be fixed by https://github.com/sourcegraph/sourcegraph/pull/28783 
  - [ ] Add a dependency on Rosetta (downloaded binary is still a x86_64
- [ ] Jaeger: PR that builds arm64 has been merged (https://github.com/jaegertracing/jaeger/pull/3431), waiting for the next release. 
  - [ ] Update the version so we get the one that has arm64 binaries available.

**Comment by jhchabran** [comment]
Update: A new release of Jaeger is out that includes the PR, so we can fix this. https://github.com/jaegertracing/jaeger/releases/tag/v1.30.0

**Comment by jhchabran** [comment]
Closing this as https://github.com/sourcegraph/sourcegraph/pull/29815 shipped all the changes.
