### ISSUE TITLE
TypeScript language server is disabled on Sourcegraph.com

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2683]
In the process of resolving an ops incident https://sourcegraph.slack.com/archives/C08JA8Q1H/p1552338934058300, I set the lang-typescript replica count to 0 and disabled the language server by commenting out `typescript.serverUrl`, which means that currently, all TypeScript code intel is from basic-code-intel.

In order to reenable the TypeScript language server, a root cause analysis needs to be done to figure out why the TypeScript language server was using up so much CPU that it apparently starved the frontend. After RCA, that behavior must be prevented before reenabling.

**Comment by keegancsmith** [comment]
We should investigate what cpu limits vs requests in k8s we are giving typescript if it is CPU heavy. Additionally if they are reasonable, we should investigate which pods were starved, and adjust there requests so they have more guaranteed CPU.

**Comment by felixfbecker** [comment]
I was just browsing some JS code and codeintel was terrible, then I noticed that the TypeScript language server on sourcegraph.com is not enabled anymore. I see this doesn't have an assignee and was backlogged. Imo this is a P1 - code intel for one of our core languages doesn't work properly. If we disable it to resolve an ops incident it needs to be properly fixed as soon as possible. I understand that we want to focus on basic codeintel but our core languages are important. My experience as a user was very bad because of this, and we set expectations for these languages.

With a proper Kubernetes deployment we should really never be in the situation where one service's CPU usage can critically affect another service (especially frontend).

Are there any records what the TypeScript server was doing when this happened? How many connections were open (maybe they leaked)? Unfortunately it looks like [Prometheus metrics for TypeScript](https://grafana.sgdev.org/d/8e6slOBik/typescript?refresh=10s&orgId=1) are still not recorded - @ggilmore should they?

@keegancsmith are these reasonable?

https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/b313be899900fa58aa54d11f921d7a3400edee44/configure/lang/typescript/lang-typescript.Deployment.yaml#L72-L78

https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/b313be899900fa58aa54d11f921d7a3400edee44/base/frontend/sourcegraph-frontend.Deployment.yaml#L223-L229

**Comment by ggilmore** [comment]
@felixfbecker 

There are metrics: https://grafana.sgdev.org/d/8e6slOBik/typescript?refresh=10s&orgId=1&from=now-30d&to=now

You just have to pick a timeframe when the Typescript language server was still enabled.

**Comment by chrismwendt** [comment]
> Are there any records what the TypeScript server was doing when this happened?

[Stackdriver metrics](https://console.cloud.google.com/kubernetes/deployment/us-central1-f/dot-com/prod/lang-typescript?project=sourcegraph-dev&tab=overview&deployment_overview_active_revisions_tablesize=50&duration=P7D&pod_summary_list_tablesize=20&service_list_datatablesize=20)

![image](https://user-images.githubusercontent.com/1387653/54303914-4b6c5780-4581-11e9-99fd-c0b764b3a2ef.png)

[LightStep streams](https://app.lightstep.com/sourcegraph-prod/service-directory/ext-lang-typescript/streams)

![image](https://user-images.githubusercontent.com/1387653/54304005-79ea3280-4581-11e9-9b2c-05a570fb49f3.png)

I recall that there were a lot of long-running raw API spans in the Go frontend that were children of ext-lang-typescript spans. I'm not sure if k8s resource limits would be able to prevent this kind of situation where, I suspect, one service (lang-typescript) was making a lot of raw requests to another (Go frontend) which created high CPU load on the receiver.

@felixfbecker Would you be willing to look into this further and take assignment?

**Comment by chrismwendt** [comment]
I set the replica count back to 16 and enabled the language server with the [resource requests set to limits](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/3c7df6f576d675c74727c13fb2bd482f19d8141f). If that doesn't fix it, the next time it starts causing problems we'll be able to see more logs.

**Comment by chrismwendt** [comment]
The high latency alert fired again https://app.opsgenie.com/alert/detail/f34df453-246e-4076-b196-4a1a0eb63d35-1552552643931/details

![image](https://user-images.githubusercontent.com/1387653/54395917-7385b480-466e-11e9-9544-0501108dd51c.png)

Here are the logs during the hour of 1-2 AM Pacific https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=sourcegraph-dev&minLogLevel=0&expandAll=false&timestamp=2019-03-14T22:38:23.255000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22dot-com%22%0Aresource.labels.namespace_id%3D%22prod%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.zone:%22us-central1-f%22%0Aresource.labels.container_name%3D%22lang-typescript%22&scrollTimestamp=2019-03-14T09:00:00.554447133Z&dateRangeStart=2019-03-14T08:00:00.594Z&dateRangeEnd=2019-03-14T09:00:00.623Z

**Comment by chrismwendt** [comment]
I think I figured it out: 1 raw API request is made per package.json, and [some repositories have the `node_modules/` directory checked-in](https://github.com/adam-strain-dev-repos/IDScanner), triggering hundreds of raw API requests in a few seconds.

Here are [the sourcegraph-frontend logs](https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=sourcegraph-dev&minLogLevel=0&expandAll=false&timestamp=2019-03-14T22:39:52.859000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-03-14T08:44:56.158117856Z&dateRangeStart=2019-03-14T08:35:00.594Z&dateRangeEnd=2019-03-14T08:47:00.623Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22dot-com%22%0Aresource.labels.namespace_id%3D%22prod%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.zone:%22us-central1-f%22%0Aresource.labels.container_name%3D%22frontend%22%0Araw%0A%22method%3DGET%22):

![image](https://user-images.githubusercontent.com/1387653/54581472-25541680-49ca-11e9-8027-29281d1667fe.png)

Here's how the raw API responds to single file requests:

https://github.com/sourcegraph/sourcegraph/blob/4064c3e87f35fce9d9f03aebdfd4bada54cf0566/cmd/frontend/internal/app/ui/raw.go#L204-L206

@slimsag What do you reckon the relative performance of this vs, say, `git show` is? I wonder if it would be worth benchmarking and attempting to optimize this if possible.

Another mitigation could be per-access-token rate limits.

**Comment by chrismwendt** [comment]
I started a potential fix in https://github.com/sourcegraph/sourcegraph-typescript/pull/138

**Comment by chrismwendt** [comment]
Fix merged 2 hours ago https://github.com/sourcegraph/sourcegraph-typescript/pull/138 :sparkles:

**Comment by slimsag** [comment]
> @slimsag What do you reckon the relative performance of this vs, say, git show is? I wonder if it would be worth benchmarking and attempting to optimize this if possible.

No clue, but the only substantial work it does aside from `git show` I think is just transferring the zip archive of the repo to the frontend. There is a separate tracking issue somewhere for moving that caching layer into gitserver, which may help, but otherwise I would very roughly guess the same as 'git show'
