### ISSUE TITLE
Should sideloading an extension disable all others?

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2684]
Often times I'll have to disable sourcegraph/go when I sideload my dev version, and that takes a few clicks. Would anyone else prefer sideloading to disable other extensions? Or anyone who prefers the current behavior?

**Comment by lguychard** [comment]
I've given it some thought as well - especially since when you sideload an extension, you're trying to debug it and usually don't want the noise created by other extensions.

Alternatively, we could also reconstruct the public id (`publisher/name`) from the manifest, and disable the extension matching this public ID.
