### ISSUE TITLE
SSBC-EM3.1: EM3 Designs are implemented for all current features

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#26918]
**Outcome**: We implemented/aligned the frontend UI with what we have in the designs for EM3. We exclude features that have not been implemented yet, this will be part of the second cut.

- [x] add [experimental features](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=1569%3A49578)
- [x] Do we need to handle the "private" batch spec permission model yet? @mrnugget **`0.5d`**
  - [x] Q: Who's allowed to see shallow batch changes?
    - A: Creator of shallow batch change or site-admin
  - [x] Q: Who can see the list of executions on a Batch Change?
    - A: Creator of batch spec or site-admin
- [x] #27543 @mrnugget **`2d`**
- [x] #28409 @mrnugget **`1d`**
- [x] https://github.com/sourcegraph/sourcegraph/issues/28080 @eseliger **`2d`**
- [x] List of executions on a Batch Change (pending permissions) **`3d`**
  - [x] Backend @mrnugget **`2d`**
  - [x] Frontend @eseliger **`1d`**
- [x] Implement the layout from the [design](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=526%3A9554) for the executions view. @eseliger **`5d`**
   - [x] the apply/preview button on top, so that users discover the preview button
   - [x] left-side pannel with workspace list, that makes it easy to scroll a large number of changesets
   - [x] Hover tooltips on workspaces status, that let the user know what each icon means.
- [x] Implement RetryBatchSpecExecution resolver @mrnugget **`2d`**
  - [x] Add retry batch spec to UI
  - [x] Maybe: Add flag to retry all, even completed

**Comment by malomarrec** [comment]
UX chokepoints I noticed that are good candidates for this next milestone:

**On the https://k8s.sgdev.org/users/malo/batch-changes/executions/<id> view** 
- Scrolling the workspaces execution list is very hard for reasonably-changed batch changes. The specific task that is hard is: 
   - find all workspaces that have failed in order to view the logs and fix them.
   - navigate to a specific repo or workspace execution (this comes up when I re-run a batch change after fixing the spec to account for a specific repo, and want to understand what's happening to that repo).
 Potential solutions: filter, search or as a quick fix a default but meaningful ordering
- The Preview banner is not on the screen if I don't scroll. If someone launches an execution and comes back, they might miss it and wonder what happens next.
- Does it really make sense that the input spec is at the top of the screen all the time? Maybe it should be collapsible, collapsed by default.
- The floppy disk or disconnected repository icons are not self-exploratory, users will get confused. Suggestion: add hover tooltips on statuses.

**Comment by rrhyne** [comment]
Some items I'm finding. 


* Editor
	* Preview workspace loader isn’t correct for some reason. JS in SVG is broke down
	* Can we make the errors appear below the editor? It’s super distracting when editing the spec and the workspaces jump up and down
	* Love that we are starting with Hello world, but I think we need the basic examples list
* In execution
	* Add the wizard so we’re not still looking at the spec after we run it
	* I feel like there isn’t a great indication of ‘working’, ‘progress’ and ‘done’
		* Says Queued, but everything was cached and I couldn’t move forward
		* KPIs could help here… can we at least get the number of workspaces in progress up near the cancel button?
	* *Step has been skipped.* should this be ‘Step was cached’?
	* Filtering is key
* Canceling should go back to spec… I can’t run this thing again


Wishlist
* The current workspaces are hard to read and review
	* Would love to incorporate icons for the code hosts as we do in search
	* Fix branch text to be closer to design
* Fix loader to center on transition between run and spec being rendered

**Comment by rrhyne** [comment]
Additionally:

* Erik took all the executors, I couldn't evaluate. This will likely happen at our customers
* If I could see other batch changes that other people ran, like Malo's then I wouldn't have to do work to check it out I think. this could be as good or better than fixing the above

**Comment by mrnugget** [comment]
My two biggest problems:

* I want to edit and re-execute a batch spec when I noticed it failed
* I want to see a list of all executions that doesn't require me to click "show more" 4 times

**Comment by malomarrec** [comment]
@mrnugget I'm not sure I get your last point
>I want to see a list of all executions that doesn't require me to click "show more" 4 times

You need to scroll a lot, but there's a list of all workspaces. Then you click on the one you want and see the logs. Can you clarify?

**Comment by malomarrec** [comment]
| Problem                                                                                                                                                       | Fix                                                                                                                                                   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| I want to edit and re-execute a batch spec when I noticed it failed                                                                                           | Fixed by milestone 2.4                                                                                                                                |
| I want to see a list of all executions that doesn't require several clicks                                                                                    | Clarifying                                                                                                                                            |
| See all the batch changes that others ran                                                                                                                     | Fixed by milestone 2.4                                                                                                                                |
| I want to see all workspaces that completed, or errored, or have a certain status.                                                                            | Add basic filtering by status to the workspace execution list.                                                                                        |
| The Preview banner is not on the screen if I don't scroll.  If someone launches an execution and comes back, they might miss it and wonder what happens next. | Implement the layout from the [design](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=526%3A9554) with the Preview button at the top. |
| I want to know the position of my job in the queue, so I can act on it (ask for more executors for example).                                                  | Fixed in [3.2](https://github.com/sourcegraph/sourcegraph/issues/26919) but needs design @rrhyne                                                      |

**Comment by mrnugget** [comment]
> @mrnugget I'm not sure I get your last point

Sorry, what I meant was this page: https://k8s.sgdev.org/site-admin/batch-changes/specs

I originally wanted to say "I need a page that shows all batch spec executions" but then realized we already have that. That one's not the nicest to use though, which is why I added the last part
