### ISSUE TITLE
Dogfood deploying Sourcegraph + executors on GCP and improve the docs

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#26931]
- [ ] Deploy a Sourcegraph instance in a new GCP project
- [ ] Deploy an executor
- [ ] Add the feature flag
- [ ] Hook up the executor to the Sourcegraph instance
- [ ] Cleanup
- [ ] Write a summary and improve docs

**Comment by malomarrec** [comment]
Autoscaling is not documented, but I can go ahead and do the all the rest.

**Comment by mrnugget** [comment]
So! I did this today!

![screenshot_2021-11-23_16 14 37@2x](https://user-images.githubusercontent.com/1185253/143052551-17a76a6a-3887-4868-987b-2a3d198fa724.png)

## Biggest takeaway

The most important bit of the documentation _for me_ (who knows how executors work, etc.) was this: https://github.com/sourcegraph/sourcegraph/pull/27887 

I want a single page where I can see everything I need to look at, download install, configure, etc. to get executors up and running.

That's the goal of https://github.com/sourcegraph/sourcegraph/issues/27864 and as I wrote here https://github.com/sourcegraph/sourcegraph/pull/27887#issuecomment-976334492 I'd put that tutorial or a link to it under the "deploying executors" page.

## Notes of my walkthrough

### Start Sourcegraph with `ngrok`

1. `ngrok http 3080` (make sure to create a ngrok account and login before, otherwise you will run into rate limit issues!)
1. Edit `site-config.json` of Sourcegraph instance (locally that's in `dev-private`):
  - `"externalURL": "<ngrok-url>"`
  - `"executors.accessToken": "my-cool-secret-horse"`
  - `"codeIntelAutoIndexing.enabled": true`
2. Edit user settings:
  ```json
  {
    "experimentalFeatures": {
      "batchChangesExecution": true
    }
  }
  ```
1. Edit `client/web/gulpfile.js` (this wasn't necessary a few weeks ago?): 
      ```diff
      diff --git a/client/web/gulpfile.js b/client/web/gulpfile.js
      index 292e1ab82e..339a4a5474 100644
      --- a/client/web/gulpfile.js
      +++ b/client/web/gulpfile.js
      @@ -108,6 +108,7 @@ async function webpackDevelopmentServer() {
          hot: !process.env.NO_HOT,
          host: DEV_SERVER_LISTEN_ADDR.host,
          port: DEV_SERVER_LISTEN_ADDR.port,
      +    allowedHosts: 'all',
          // Disable default DevServer compression. We need more fine grained compression to support streaming search.
          compress: false,
          onBeforeSetupMiddleware: developmentServer => {
      ```
1. `sg start`
1. Visit: http://4874-87-156-118-82.ngrok.io

### Create a Google project

1. Go to https://console.cloud.google.com/projectcreate
1. Create project with "Location: Engineering Projects"
1. Visit: https://console.cloud.google.com/home/dashboard?project=thorsten-executors&authuser=1
1. Enable "Compute Engine API" for project: https://console.cloud.google.com/apis/library/compute.googleapis.com?authuser=1&project=thorsten-executors
1. `gcloud auth application-default login`

### Create terraform project

1. Create `.tool-versions`:
    ```
    terraform 0.13.7
    ```
1. Run `asdf install`
1. Create `providers.tf`:
    ```terraform
    locals {
      project = "thorsten-executors"
      region  = "us-central1"
      zone    = "us-central1-c"
    }

    provider "google" {
      project = local.project
      region  = local.region
      zone    = local.zone
    }

    provider "google-beta" {
      project = local.project
      region  = local.region
      zone    = local.zone
    }
    ```
1. Create `main.tf` (based on https://github.com/sourcegraph/terraform-google-executors/blob/master/examples/single-executor/main.tf):
    ```
    module "executors" {
      source  = "sourcegraph/executors/google"
      version = "0.0.18" # LATEST

      region                                       = local.region
      zone                                         = local.zone
      executor_instance_tag                        = "thorsten-executors-testing"
      executor_sourcegraph_external_url            = "http://a90d-87-156-118-82.ngrok.io"
      executor_sourcegraph_executor_proxy_password = "my-cool-secret-horse"
      executor_queue_name                          = "batches"
      executor_metrics_environment_label           = "dev"
    }
    ```
1. Run `terraform init`
1. Run `terraform apply`, enter "yes"

### Check executors are connecting

1. Go to http://4874-87-156-118-82.ngrok.io/site-admin/executors?visible=4
1. Check that executors are showing up there
1. Check that executor requests are showing up in ngrok logs
1. Create a batch spec and execute it

**Comment by mrnugget** [comment]
@malomarrec if you don't want to do this too, I think we can close it?

**Comment by malomarrec** [comment]
Let's close it, I might do it independently but this is done.
