### ISSUE TITLE
Insights creation UI: show user error / filter out `count:`, `repo:`, and `-repo:` filters if input in query

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#26977]
While the UI shows you a sentence below the input warning you not to do this, we should better filter it out / show you an error if the query contains a `repo:` or `-repo:` filter. (Or, if we fix this entirely, we should handle it without failing). 

![image](https://user-images.githubusercontent.com/11967660/140014178-33e93f01-1658-4ff8-8ece-d49f84090a14.png)

**Comment by coury-clark** [comment]
> Or, if we fix this entirely, we should handle it without failing

I think we need to make a decision here - do we want to use Sourcegraph search query filters such as repo as an additional mechanism to control which repos get selected, or do we want to keep just the single external mechanism (a list of repos, or list of groups)?

If we allow users to specify things like `repo` or `-repo`, we are sidestepping any application control we have over the repository scope. That is to say, if we wanted to make decisions based on that information, we would have to extract these from the query and populate a repository scope. However, since a `repo` field can be an arbitrary regexp, it is not possible to naively extract the text and assume it is a repository. We would have to make some assumptions about the timeframe for which that repo filter is relevant (current point, across all points [expensive]), and perform a search to extract those matches. This also has implications for how this repository scope can change, where a manual repository scope does not change based on new repos in Sourcegraph, a `repo` filter in the search query might depending on the implementation here.

I suggest we do not allow queries with `repo` or `-repo` or `context`, etc.
