### ISSUE TITLE
Investigate ways to embrace the culture of creating good-first issues

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#27002]
## Context

During the Hacktoberfest 2021, one of the most time-consuming tasks was creating a good-first issues list for external contributors to pick up because we didn't have anything in the pipeline before the preparation.

What can we do to drive this as a culture in engineering to consider defining and tagging good first issues constantly?

## Succes criteria 

The steps that can help to address the question above are documented and the process (if applicable) automated.

## Notes

Two components might help here: champions and communication.

1. Champions are engineers or engineering managers that would create/encourage to create good first issues.
2. The communication that emphasizes that investing time into good first issues is not only about the core product contributions but also about a smooth onboarding experience for new Sourcegraph employees: a pull of issues to pick up during a couple of first weeks, better documentation, friendly local development environment.

Another important aspect is ensuring that good-first-issues are actually picked up and worked on. If devs know there's a possibility that their issue might be completed, they'll be a lot more inclined to add the label.

**Comment by varungandhi-src** [comment]
I have a little bit of experience with this from my experience working on the Swift compiler; here are some of the key pieces IMO for creating good first issues.

### Identifying subsystems/components which are a good source

One recurring source of good first issues in the Swift compiler was diagnostic messages. The hard part of the issue would be largely around getting a build working properly. Another, less common source would be some no-op refactoring (such as a rename). In both cases, I would usually get some +1s from the team first, before marking it as a good first issue, to avoid the person being challenged in terms of direction in the PR.

### Writing clear instructions for newcomers

Sometimes people don't recognize all the implicit knowledge they have when they write an issue description, since it is usually meant for themselves or team members.

I think having a template or two could be valuable to make sure someone didn't forget a piece of context that is usually needed. For example, which files will likely need changes? Are there similar examples in the codebase already? Are certain functions and types key to understanding the issue and fixing it? If a contributor has questions should they @ the person filing the issue or someone else?

### Breaking down larger issues into pieces

Smaller issues are more likely to be good first issues. Often, larger issues can be split up into some heavy-lifting parts, some necessary parts, and some smaller nice-to-have parts. The nice-to-have bits would often make for a good first issue.

### Being proactive about unlabeling bad first issues

In some cases, I've seen people (and I've been guilty of this myself) heavily underestimate the complexity of an issue. It would be good to proactively consider removing the "good first issue" label when an external contributor is not able to fix the issue within reasonable time.

---

I'm not sure about how to go about encouraging people about these (perhaps a short document with guidance might help?) but I hope these points are kept in mind during the process.

**Comment by valerybugakov** [comment]
Hey @varungandhi-src, thanks for sharing your experience! 

> I'm not sure about how to go about encouraging people about these

It would be awesome to capture your thoughts in our developer documentation. We have a young "Contributing" section [here](https://docs.sourcegraph.com/dev/contributing). Maybe it makes sense to create a separate document — "Creating good first issues" and link it there.
