### ISSUE TITLE
insights: feasibility of migrating user / org dashboards from settings

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27146]
In the frontend version of code insights there is a default dashboard for each user, org, and global. This ticket is to determine the feasibility / approach of migrating those dashboards (which do not exist as a custom dashboard) to the database to be retrieved by the API.

Some notes:
1. We can consider the migration a conversion event, at which point these special case dashboards will obey all of the normal rules of custom dashboards

**Comment by CristinaBirkel** [comment]
EOD progress update for transparency and in case you have any feedback @coury-clark. Maybe I'm thinking in the entirely wrong direction.

My current thinking is that for the out-of-band migration we need to do a couple out-of-the-ordinary things:
1. Keep a `settings_migration_metadata` table that will at the very least have a `completed_at` field. This is because even after a migration is finished, its `Progress` method will keep being polled for completion, and then run the `Up` method if it's found incomplete. However we decide to calculate progress, it will inevitably seem to be incomplete again once users start updating their insights, or maybe their settings files. So we need a way to mark it as complete so that `Progress` always returns that it's done even when things get inevitably out of sync. This could also act as an easy mechanism for restarting. (Maybe; have to think that through more.)
2. The `Up` function (which performs work on the migration) can be run concurrently. I went with this assumption for a while and I think it makes things much more complex, and for no real reason. This isn't a huge job. So I would propose we do some kind of locking to make it single-threaded. Not sure how to do that, but I am pretty sure it's possible.

I'm thinking about this in kind of a multi-step process, similar to what we have now except with a new table, `settings_migration_jobs` to keep track of everything.

1. I think we can call `GetSettings` with the `All` filter an `insight` prefix to get every settings row that has insights we need to migrate.
2. For each of those, we add a row to `settings_migration_jobs`. I'm thinking this table will have the following fields:
  - `id  |  user_id  |  org_id  |  global (redundant)  |  completed_at  |  errored_at  |  error_msg  |  retries`
  - Something like this anyway, to keep track of the work in some persistent way.
 3. These jobs can then be executed one at a time, global -> org -> user. Errors can be logged to the table. We can retry a certain number of times before surfacing the errors to the admin via the migrations UI. (Not sure what we ultimately want to do with errors that are not transient. Admin fixes/removes certain insights directly in settings?) And we can do these in batches if we want to. (We can set the interval at which the job runs. In the example it's every 3 seconds.)
  - I think the steps outlined here sound solid to me! https://github.com/sourcegraph/sourcegraph/issues/26533
 4. One we're done with that, we can query for settings again and check the setting's `created_at` field against the job's `completed_at` field, and if the setting has been updated since we've completed the job we can add a new job for that setting. Then I would say rinse and repeat until we can run this and there are 0 updates.
 5. Then we update `settings_migration_metadata.completed_at` and call it done.

That's my general thinking so far. Any initial thoughts? It definitely doesn't feel like a solid plan yet and am still looking into things. This also seems a little tangential to this issue actually, but I'm pretty sure this is what I was meant to investigate today 😆

**Comment by coury-clark** [comment]
> Keep a settings_migration_metadata table that will at the very least have a completed_at field. This is because even after a migration is finished, its Progress method will keep being polled for completion, and then run the Up method if it's found incomplete. However we decide to calculate progress, it will inevitably seem to be incomplete again once users start updating their insights, or maybe their settings files. So we need a way to mark it as complete so that Progress always returns that it's done even when things get inevitably out of sync. This could also act as an easy mechanism for restarting. (Maybe; have to think that through more.)

I don't think this is a problem for two reasons:
1. This migration will be running with insights GraphQL enabled
2. If this migration were to iterate over users / orgs, it would only find new work when a new user or org is added, it would never revisit previously visited ones unless explicitly reset.

> The Up function (which performs work on the migration) can be run concurrently. I went with this assumption for a while and I think it makes things much more complex, and for no real reason. This isn't a huge job. So I would propose we do some kind of locking to make it single-threaded. Not sure how to do that, but I am pretty sure it's possible.

As long as we select records in the proper order (global > org > user) I think this should be fine. Even if there is a small race condition when switching from global -> org or org -> user it should be resolved on the next retry. I think it might be more complicated that we would like to synchronize this, since they are distributed across `frontend` nodes and we don't have a good mechanism of a distributed lock here.

> I think we can call GetSettings with the All filter an insight prefix to get every settings row that has insights we need to migrate.

Somehow we will have to either keep this up to date for new users / orgs, or discover those as part of the query.

> Not sure what we ultimately want to do with errors that are not transient. Admin fixes/removes certain insights directly in settings?

It will probably depend on the problem. In many cases it will likely be easiest to log the insight and just recreate it from scratch, I suspect.

> One we're done with that, we can query for settings again and check the setting's created_at field against the job's completed_at field, and if the setting has been updated since we've completed the job we can add a new job for that setting. Then I would say rinse and repeat until we can run this and there are 0 updates.

I'm still not convinced this is necessary. If this migration is meant to run after the API flag is enabled, we shouldn't expect to support any updates.

Sounds pretty good to me so far!

**Comment by CristinaBirkel** [comment]
Okay maybe this is simpler than I was thinking. Based on our discussion it sounded like we needed to be sure to include any updates made from the start of migration to when it completes, but if the GraphQL API feature flag is enabled from the get-go, it sounds like we don't actually need to care about that. Does it matter if new users/orgs are created while the migration runs? They won't have any insights, and we only care about insights, so I don't actually think those `settings` rows will even get picked up by `GetSettings`.

So maybe this is all we need:

**`Progress()`**
1. If there are no rows in `settings_migration_jobs`, return 0 (no progress)
2. If there are rows in `settings_migration_jobs`, return % of those that are completed.

An easy way to reset the migration would be to delete all rows from `settings_migration_jobs`. And once they are all complete, nothing will re-trigger any updates.

I think the `Up` function will sort of have two parts. And we may need to save a bit of metadata for that. So one issue that seemed to make concurrency difficult was that we can't use `FOR UPDATE SKIP LOCKED` like in the example, because the rows in `settings` need to first be grouped by distinct (due to there being historical settings.) A major benefit we get from creating this separate jobs table is that we can then use that locking to support concurrently working on different settings objects.

**`Up()`**
1. Ensure all rows in `settings_migration_jobs` have been created. This could maybe be done with a SQL query that counts the number of settings objects we want to migrate and compares it with the count of jobs. If these are equal, we consider all jobs to be queued. Incidentally I think this would pick up any new users/orgs if they had `insight` in their settings, (which they shouldn't.)
- If they haven't all been queued, we read from `GetSettings()` and try to add those rows one by one. If there is an error we skip that row and continue. Another process will come back and try again until all of the rows have been queued. We should probably include some state for this in case there's some unrecoverable error and we cannot continue, so that can be surfaced to an admin.
2. At this point it's a matter of picking up those queued jobs. So we start with: "If the global job is not complete, try to pick that up and do it."
3. Then "If any org jobs are not complete, pick those up and do them."
4. And finally "If there are user jobs, pick those up and do them."
- If a thread finds nothing it's allowed to pick up yet that isn't locked, it can just exit.

I actually think this sounds fairly straightforward, unless I'm missing something we need to worry about. What do you think @coury-clark ?

**Comment by CristinaBirkel** [comment]
@coury-clark follow up with a WIP draft PR in case that's easier to make comments on. It's just pseudocode outlines and comments for now but it is probably a little easier to illustrate than paragraphs. https://github.com/sourcegraph/sourcegraph/pull/27473

If you think this looks fairly sound I can probably get a bunch done tomorrow and maybe to a state where it runs and does _something_, to help flush out any more potential issues and see if it sounds like a good plan to finish next week.

**Comment by CristinaBirkel** [comment]
Closing this spike. Outcome: 
- We've decided we need to go ahead with the OOB migration, (including creating these formerly-virtualized dashboards,) and work will continue under this issue: https://github.com/sourcegraph/sourcegraph/issues/26533
