### ISSUE TITLE
Add database schema for webhook actions

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#27157]
Should primarily contain the webhook URL, whether the action is enabled or not, and the type of webhook (generic or Slack). It's possible we need two types of schema instead, one for generic webhooks and another for Slack notifications.

Make sure schema doesn’t assume that search results are the only possible trigger: we currently only have "new search results" trigger, but more may be added in the future.

**Comment by camdencheek** [comment]
Writing down some thoughts:

I think each of our actions types should live in a different table. That is, we have a table for email actions (already exists), a table for generic webhooks, and a table for slack webhooks. I think this will provide us the most flexibility moving forward if we want to change how slack notifications work. 

Some notes on the current state of things:
- Code monitors are defined in the `cm_monitors` table. This basically just contains id`, `description`, and `enabled`.
- Code monitor queries are defined in the `cm_queries` table, along with the last time they ran. This has a 1:1 relationship with `cm_monitors`. 
    - Side note: it's a bit unclear to me why these live in separate tables, but my guess is so it's possible to have multiple queries per monitor in the future?
- When a code monitor is due to run, it is added to `cm_trigger_jobs`, which contains information like whether the job has been run yet, the query to be run, and any failure message for errors during the run.
- After a trigger job has been run and there are results, an "action" is stored in `cm_action_jobs`. This table contains the `id` of the triggering event, the id of the email action in `cm_emails`, and any failure message if the action failed to run.

I expect the db changes to look something like this:
- create new tables `cm_webhooks` and `cm_slack_notifications` with the information needed to run each respective action
- update `cm_action_jobs` to add the columns `webhook` and `slack_notification` in addition to the current `email` column. These three columns (and any additional actions we add in the future) will be mutually exclusive.

This means that `cm_trigger_jobs` and `cm_action_jobs` is no longer 1:1, and we can have multiple actions created from a single trigger. So, when we run a trigger job, we will add an action to `cm_action_jobs` for each action defined on the code monitor. Then, in our history page, for each triggered job, we'll look up the actions associated with it and report their status.

@limitedmage does this sound about right to you? It should be a fairly straightforward set of changes. I'll likely start working on it tomorrow assuming the plan sounds good.

**Comment by limitedmage** [comment]
Thanks for looking into all of this! It all sounds very reasonable to me, aside from two comments:

> * Code monitor queries are defined in the `cm_queries` table, along with the last time they ran. This has a 1:1 relationship with `cm_monitors`.
>   
>   * Side note: it's a bit unclear to me why these live in separate tables, but my guess is so it's possible to have multiple queries per monitor in the future?

I'm thinking it's because in the future, the trigger may not be a search query; we may have different types of triggers (e.g. action required on batch change, code insights chart reached threshold, etc).

> * update `cm_action_jobs` to add the columns `webhook` and `slack_notification` in addition to the current `email` column. These three columns (and any additional actions we add in the future) will be mutually exclusive.

I think making them mutually exclusive will result in a simpler design and I think this is good for the initial implementation. However, I would assume that in the future, we may have multiple actions per monitor, even of the same type.

**Comment by benvenker** [comment]
Thanks @camdencheek and @limitedmage. I would agree with @limitedmage’s comment that we could have both alternative triggers and multiple actions per trigger. I’m not qualified to comment on the rest but really appreciate the effort and thought put into it!

**Comment by camdencheek** [comment]
> I'm thinking it's because in the future, the trigger may not be a search query; we may have different types of triggers (e.g. action required on batch change, code insights chart reached threshold, etc).

Ah! Good call. I forgot that was something we were designing for 😅 

> I think making them mutually exclusive will result in a simpler design and I think this is good for the initial implementation. However, I would assume that in the future, we may have multiple actions per monitor, even of the same type.

Poor explanation on my part. I think these three columns should _always_ be mutually exclusive within a `cm_action_jobs` row, meaning that each row represents a single action with a single type. In order to support multiple actions from a single trigger, we just add multiple rows to this table, all with the same trigger id. So, if we wanted to send two emails and a webhook action, we could add three rows, two with a non-nil `email` column, and one with a non-nil `webhook` column.

**Comment by limitedmage** [comment]
> Poor explanation on my part. I think these three columns should _always_ be mutually exclusive within a `cm_action_jobs` row, meaning that each row represents a single action with a single type. In order to support multiple actions from a single trigger, we just add multiple rows to this table, all with the same trigger id. So, if we wanted to send two emails and a webhook action, we could add three rows, two with a non-nil `email` column, and one with a non-nil `webhook` column. 

@camdencheek  That makes total sense, thanks for explaining!
