### ISSUE TITLE
Extensions are not working for firefox

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#27238]
BExt: v21.10.21.1959
Firefox: 94.0.1 (64-bit) - MacOS

#### Steps to reproduce:

1. Have extensions enabled
2. Navigate to a github repo

#### Expected behavior:
Extensions to be activated

#### Actual behavior:
Errors in the logs
![image](https://user-images.githubusercontent.com/1308560/140780744-e8ad7967-52bc-44ef-b1ed-3c24741d9144.png)

Related issue: https://github.com/codecov/sourcegraph-codecov/issues/77

**Comment by erzhtor** [comment]
1. Error logs are not related to the issue of not working Sourcegraph extension in Firefox. Created a separate bug/issue https://github.com/sourcegraph/sourcegraph/issues/27414.

2. Regarding the actual issue, it turned out that we intentionally DO NOT support Sourcegraph extensions (Except code-intel) in Firefox due to its policy in the addons hub. They don't approve extensions that run remote/dynamic code.

From @muratsu:
> The limitation is unfortunate but makes sense :thinking_face:. Chrome is moving in this direction with the Manifest V3 as well and it's more of a when issue rather than if ([#1](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/EzpG87sNCQQ/m/gmL78qGTDAAJ), [#2](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/uIJqhOWKNWE/m/2vNcwYrVCgAJ), [#3](https://github.com/Tampermonkey/tampermonkey/issues/644)).
I don't think there's anything actionable here. We have to wait for the [new standard](https://github.com/w3c/webextensions/issues/103) work to be finalized before taking any action.
