### ISSUE TITLE
3 customers with >1 Search Notebook

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27353]
This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

Major areas of work:
- [ ]  https://github.com/sourcegraph/sourcegraph/issues/27384

**Comment by yinquanteo** [comment]
@lguychard I lifted https://github.com/sourcegraph/sourcegraph/issues/27384 from the Code Graph board over here. Feel free to reorganize or close things out since it looks like it's a placeholder issue

**Comment by jyavorska** [comment]
Asked about possibility of metric at https://sourcegraph.slack.com/archives/CN4FC7XT4/p1637057998095600.

**Comment by jyavorska** [comment]
@benvenker this is marked as at risk due to design constraints. What are we doing to mitigate those?

**Comment by benvenker** [comment]
We are currently taking a strategy of unblocking development in the short term with sketches and functional descriptions, letting engineers use their judgment where needed. We're still constrained on design research output to inform that development, and on final designs in some cases, but we're not stalling dev work because of that. The plan is to push ahead on known needed functionality and augment/update later based on research findings and high-fidelity designs.

**Comment by jyavorska** [comment]
@benvenker @lguychard what ended up being the final status of this OKR for Q4?

**Comment by jyavorska** [comment]
Closing since the quarter is over, but please be sure to add the final update.
