### ISSUE TITLE
Our services can create an unbounded number of processes

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#2743]
Docker's cpu quota functionality (e.g. [`--cpu-shares`](https://docs.docker.com/engine/reference/run/#/cpu-share-constraint)) doesn't change the number of cores advertised to the underlying container. For example, GOMAXPROCS defaults to the number of physical cores available on the machine. Creating a large number of processes can cause a container's memory usage to explode and can lead to unpredictable behavior (some ops incidents this week were caused by this: https://sourcegraph.slack.com/archives/C08JA8Q1H/p1552586636100100 , https://sourcegraph.slack.com/archives/C08JA8Q1H/p1552515783096700). 

For our Go services, https://godoc.org/go.uber.org/automaxprocs is a package that automatically sets GOMAXPROCS if a CPU quota is used. Other solutions will need to be investigated for services written in other languages.

**Comment by slimsag** [comment]
How does https://godoc.org/go.uber.org/automaxprocs handle the case of no explicit CPU limits being set? e.g. in the case of a regular user of `docker run [...] sourcegraph/server`

We should probably have sane defaults in that case as well

**Comment by ggilmore** [comment]
> Package automaxprocs automatically sets GOMAXPROCS to match the Linux container CPU quota, if any.

**Comment by slimsag** [comment]
Cool, so we should restrict it in that case to something reasonable like 16 (Otherwise someone running sourcegraph/server on a beefy machine would run into this)

**Comment by ggilmore** [comment]
To clarify:

```typescript
GOMAXPROCS = min(CPU_QUOTA || 16, NUM_CORES)
```

Is that what you're saying @slimsag ?

**Comment by slimsag** [comment]
Yes

**Comment by ggilmore** [comment]
Hmm, I don't know how customizable https://github.com/uber-go/automaxprocs is. I'll need to dig into how it's implemented.

**Comment by beyang** [comment]
@ggilmore I'm removing this from the Distribution project, because I'd like for that to include only "active" issues in a given milestone. Otherwise, the To do column would include the entire Backlog. I'd like like to use that project as a way to measure work planned vs work completed for each iteration. In other words, the process would look something like this:
1. Start of the iteration, determine what should be in the "To do" column.
2. Over the course of the iteration, move stuff from To do into the rightward column.
3. At end of iteration, review what remains in "To do", which by definition is work planned but not completed, and dig into the reasons why we didn't get done what we thought we would, determine whether this was the right tradeoff (it very well might be), and roll the learnings into the next iteration.

@slimsag @ggilmore Thoughts on that?

**Comment by slimsag** [comment]
Sounds good, but we need "To do" this in this milestone :)

**Comment by slimsag** [comment]
@ggilmore Any chance you would have time to land this in 3.3? I won't so I am removing for now, but it is kind of important I think

**Comment by slimsag** [comment]
Deferring.

**Comment by slimsag** [comment]
At https://app.hubspot.com/contacts/2762526/company/407948923 this was fixed by adding GOMAXPROCS specifiers equal to the # of CPUs. We should still do the more generic (and automatic) fix here, but it is low priority now I believe. Backlogging.

**Comment by keegancsmith** [comment]
I implemented this at https://github.com/sourcegraph/sourcegraph/pull/4868 (and created a specific issue at https://github.com/sourcegraph/sourcegraph/issues/4867)

I'm unsure why the title of this issue is "unbounded". What is an example? If we do have unbounded usage somewhere, it is unlikely related to GOMAXPROCS.

So go sets GOMAXPROCS to the number of CPUs. However, in container environments this is often limited (eg k8s CPU limits) so the number of CPUs is a bad value. Instead it should be the limited amount. This is all automaxprocs does, set it to a better value by default. If a user sets GOMAXPROCS, automaxprocs does nothing.

I'm unsure about the proposal of limiting GOMAXPROCS by default. I think admins should tune that if its an issue. Can you give more specific information about how setting GOMAXPROCS helped a customer?

In my PRs I have used automaxprocs all over our codebase (including zoekt). Additionally I changed any usage of runtime.NumCPU to rather use GOMAXPROCS.

See this twitter thread about why setting an appropriate GOMAXPROCS is important for the go runtime: https://twitter.com/embano1/status/1149654812595646471

**Comment by slimsag** [comment]
> I'm unsure about the proposal of limiting GOMAXPROCS by default. I think admins should tune that if its an issue.

Yeah, to be honest reading over what I previously wrote here does not make sense to me anymore. Just using automaxprocs SGTM now.

> I'm unsure why the title of this issue is "unbounded". What is an example? If we do have unbounded usage somewhere, it is unlikely related to GOMAXPROCS.

The "unbounded" case I believe only occurred on our CI, not in customer environments. I think "unbounded" was just a poor wording choice. See the linked Slack thread in the issue description for an idea of what that looked like.

> Can you give more specific information about how setting GOMAXPROCS helped a customer?

For https://app.hubspot.com/contacts/2762526/company/407948923 I essentially just manually configured GOMAXPROCS to match the CPU constraints we're applying. This was needed because over there a single machine is in use with e.g. 128 CPUs. automaxprocs is perfect and would have the same behavior here.

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/4867
