### ISSUE TITLE
Create synthetic monorepo that keeps up-to-date with its constituent parts (busy repos)

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#27492]
Create service / script that fetches latest changes from N busy repositories and commits them to a single mega mono-repo. This will be our golden testing mono-repo that we use for baseline performance monitoring.

After this is in production, we should explore the whole product manually in this repo, document what we see is really slow, and compare that with what our customers report.

**Comment by keegancsmith** [comment]
Status update. This was running last week and the code is here https://github.com/sourcegraph/sourcegraph/pull/28228 and the monorepos is here https://github.com/sgtest/megarepo

On Friday I was trying to grow the corpus and started running into issues where GitHub was failing when I tried to push. I don't know if this was due to the size of the repository, or it was instability GitHub was facing at the time. If I still run into issues today I'll shrink the corpus such that it works on GitHub. If we find we still want a larger repo, we likely need to look into exposing the repository from the service or using another host for the repository.

Meta: I started on a more complicated approach Monday day and Tuesday morning (git-fast-export/import based). I then changed direction and hacked up the service on Tuesday afternoon. Wednesday was minor code changes, getting the code packaged and deployed into our cluster and successfully pushing to GitHub. Then Thursday and Friday was all making it more production ready and tweaking the corpus size/etc. Surprising I spent as much time making it "good" from a production point of view. There is def scope in our devexps for making it easier to deploy services which just live in our internal clusters and don't get deployed to customers.

**Comment by keegancsmith** [comment]
Status update: I fixed the github push issue by removing azure-docs from the synthetic repo. I just finished up addressing review feedback so I would regard this issue as done (will let the PR getting merged close this issue).

Try it out in sourcegraph at https://sourcegraph.com/github.com/sgtest/megarepo

**Comment by keegancsmith** [comment]
Stats of the repo currently:
- 6GB working copy
- 731k files in working copy
- 141k commits

```shellsession
# git ls-tree -r --long HEAD | awk '$4 != "-" { total += $4; count++ } END { print total / 1024 / 1024 / 1024.0; print count }'
6.00352
731847
# git log --format='%H' | wc -l
141182
```
