### ISSUE TITLE
codeintel: incremental indexing in the symbols service

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#27611]
@olafurpg and I brainstormed an idea to make the symbols service faster: run ctags on the fly on files that changed since the revision that last SQLite DB was generated for and merge the results.

Operationally, when the symbols service receives a search request for a revision that we don't already have a SQLite DB for:

- Kick off an indexing job (to generate a full SQLite DB for the currentRevision) in the background (could simply be a goroutine)
- Find the last SQLite DB and `oldRevision` that was generated for this repo (latest by timestamp should suffice)
- Run `git diff --name-only oldRevision currentRevision` and run ctags on the new and changed files and save it as a temp DB
- Query the old SQLite DB and new temp DB and merge the results
- Eventually clean up temp DBs, maybe keep them around until the full SQLite DB for currentRevision is ready (will think more about this part as I get to the implementation of it)

**Comment by olafurpg** [comment]
> Run git diff --name-only oldRevision currentRevision and run ctags on the new and changed files and save it as a temp DB
> Query the old SQLite DB and new temp DB and merge the results

What do you think about doing this instead?

1. Query the old database directly
1. Run ctags in-memory on the files from the results of the old db
1. Return those in-memory results

If step 2 turns out to be a bottleneck we could speed it up by using edit-distance to align the positions of the old file with the positions of the new file.

This approach does not index the files that have changed since the last diff but that's maybe an acceptable tradeoff. We could address that limitation in the future by adding support to streaming symbol results. My intuition is that we should optimize for low-latency results even if they're incomplete.

**Comment by chrismwendt** [comment]
That would be even easier to implement, which is nice. If we decided to start returning stale/incomplete results then we should also indicate that in the UI, which has its own costs and could tip the scales against simply returning results from the old DB.

I'm guessing that computing a diff and running ctags on changed files will be fast enough to be worth it, and during implementation I'll collect stats so we can get more information to put into the balance.

**Comment by keegancsmith** [comment]
@sourcegraph/search-core has been chatting about introducing more incrementality in our services, in particular for monorepo cases. It sounds like you are working on this soon? If so I'm sure there is some cool stuff we could learn from it / we should have a chat some time.

I'd point out another DB you can "diff against" is indexed search. It's not exactly the same data (which is a bit of a pain point), but it has much more chance of existing since it is persistent.

Also a snag you will run into is we shard across the symbol service replicas on `repo@sha`, so your replica might not have a symbol db for a repo, but another will. However, it is safe to adjust the sharding algorithm to just use `repo`.

**Comment by chrismwendt** [comment]
Yep, I plan to dive into this in the next few days. Happy to chat anytime!

:+1: to sharding by `repo` instead of by `repo@sha`

**Comment by chrismwendt** [comment]
PR for incremental indexing of symbols https://github.com/sourcegraph/sourcegraph/pull/27932
