### ISSUE TITLE
docs: Add concise docs on how to use terraform/modules

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#27867]
How to:

- tfenv
- set versions
- log into google or aws
- how to tf init, setup provdiers, etc

Seems like there's 2 ways to auth, need to pick one:

- Either via `GOOGLE_APPLICATION_CREDENTIALS`
- Or using "application default credentials" https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#credentials

**Comment by efritz** [comment]
@mrnugget I believe you were the one that mentioned this (could be wrong)?

**Comment by daxmc99** [comment]
cc @sourcegraph/cloud-devops 
@filiphaftek (who has written some incredible modules for us but is currently on parental leave) would be a great resource here

**Comment by mrnugget** [comment]
I'm pretty sure this is fixed by now with the example guides we have on how to deploy executors using terraform: https://docs.sourcegraph.com/admin/deploy_executors#examples

Closing this because the [example installation here](https://docs.sourcegraph.com/admin/deploy_executors#example-installation) contains everything I wanted from this ticket.
