### ISSUE TITLE
Code Insights: [BE] update mutations over insights don't work if insight isn't included in a dashboard

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#27906]
Steps to reproduce
1. Create Insight without that won't be included in any dashboards (omit dashboard field in create insight mutation)
2. Try to run update line chart mutation for newly created insight
3. See error about no insight found

This should work since we can modify insight in "All insights" dashboard. In this "All insights" dashboard we fetch all available insights. Some of them can be insights without that are not connected to any dashboard. Mutations for those insights don't work but it should since users can modify insights in all insights dashboards. For example, update filters or create other insights as a copy

**Comment by coury-clark** [comment]
Confirmed can reproduce on k8s after creating an insight and editing title. Triaging as must-have

**Comment by coury-clark** [comment]
Actually maybe not? I went back after a bit and noticed the insight was there but now in a new order in the results. I'll need to dig in more. If it is returning an error, maybe the issue is just that the apollo cache is invalidated but the insight is updated correctly under the hood? So this may be just an issue with the response not returning the updated insight.

<img width="433" alt="CleanShot 2021-11-18 at 08 22 14@2x" src="https://user-images.githubusercontent.com/5090588/142453900-93e606f2-07e3-4485-b38d-dc34db8fab3e.png">
<img width="384" alt="CleanShot 2021-11-18 at 09 16 18@2x" src="https://user-images.githubusercontent.com/5090588/142453896-e58d5002-5ddf-44b3-a64b-07caafed9c67.png">

**Comment by Joelkw** [comment]
@coury-clark If the question is "interacting with an insight that is not on a dashboard (presumably via the "all insights dashboard") is a weird way of interacting, right?" I wouldn't agree. But if this is "you have to do this through the API" I would think it's a less common interaction at this point. 

Regardless, since we'll ship with the flag off, if it's the former we should be able to fix (assuming it's still an issue – re: your latest comment)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
