### ISSUE TITLE
Sourcegraph.com hasn't refreshed in several days

### ISSUE THREAD

**Issue by tonybruguier** [sourcegraph/sourcegraph#27935]
Hi,

Today's 2021-11-18 and it seems the code from [github.com](https://github.com/tensorflow/quantum) hasn't refreshed in about two weeks. Is this expected? I wouldn't expect a minute latency, but this seems somewhat slow.

![Screenshot 2021-11-18 1 44 21 PM](https://user-images.githubusercontent.com/14946972/142502093-e5e41c7f-82ea-4c37-80b7-59c2df2f0b6b.png)

![Screenshot 2021-11-18 1 44 48 PM](https://user-images.githubusercontent.com/14946972/142502138-12ec3e01-204c-4005-aac1-8cf2454f4ba7.png)

**Comment by unknwon** [comment]
Is this @sourcegraph/repo-management?

**Comment by indradhanush** [comment]
@tonybruguier Thank you for reporting this. I wasn't able to reproduce this and noticed that the repo is up to date with GitHub as of the time of this comment. Since the time of the issue being opened, the repo would have been synced at least once and would have updated to the latest commit as a result. 

![image](https://user-images.githubusercontent.com/2682729/143834109-b4d59677-0857-4d88-b0da-0ac0a086ffe9.png)

Feel free to reopen this if you see this happening again. :slightly_smiling_face:
