### ISSUE TITLE
Performance of alternating queries

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#27984]
Searches of the form `[ab]foo` are slow but searches of the form `(afoo)|(bfoo)` are fast. Users are more likely to write the former, so it seems like we should be able to do some query optimization to make it fast.

# Examples

This search seems to be slow:
https://sourcegraph.com/search?q=context:global+%5B%5C%22%5C%27%5Dgh%5Bpousr%5D_%5BA-Za-z0-9_%5D%7B16%2C%7D&patternType=regexp&case=yes

This search seems to be fast:
https://sourcegraph.com/search?q=context:global+%28%5C%22gh%5Bpousr%5D_%5BA-Za-z0-9_%5D%7B16%2C%7D%29%7C%28%5C%27gh%5Bpousr%5D_%5BA-Za-z0-9_%5D%7B16%2C%7D%29&patternType=regexp&case=yes

**Comment by camdencheek** [comment]
My guess is this is because there are no full trigrams in that first search, so we can't easily use the zoekt trigram index. I believe we've hit this issue before with security token searches. They tend to be very expensive in zoekt because they are often very generic and don't contain any literal strings within the regex patterns to get a list of candidates from the index, so all files effectively need to be scanned.

Comparing `[\"\']gh[pousr]_[A-Za-z0-9_]{16,}` to `(\'gh|\"gh)[pousr]_[A-Za-z0-9_]{16,}` , the latter is _much_ faster, on par with your second link.

**Comment by nicksnyder** [comment]
> Comparing `[\"\']gh[pousr]_[A-Za-z0-9_]{16,}` to `(\'gh|\"gh)[pousr]_[A-Za-z0-9_]{16,}` , the latter is much faster, on par with your second link.

Right, I guess I am wondering if there is a simple optimization we could do for these simple cases (character class followed by a literal string, but could also apply to a literal string followed by a character class) that would effectively rewrite the former to the latter so it is fast (and we can use our trigram index).

There can be a cap on the size of the character class that we would apply this optimization to (e.g. 100? so common character classes like [a-zA-Z0-9] would be included). There would be no complexity explosion because the optimization would only apply up to the first character class.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
