### ISSUE TITLE
Add shortcuts for Go to Definition and Find References

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#28036]
**Problem:** Users must trigger the popover to take actions on a symbol, such as going to def/ref. This is a problem because users must perform an extra click to access the actions they intend to take. It disrupts their workflow, as this is contrary to expected editor behavior. 

**Solution:** Introduce discoverable shortcuts for users to perform key actions without having to trigger the popover. 

#### Describe alternatives you've considered.

**Alternative 1 (chosen ✅):**
Go to definition: Click on symbol 
Find references: Click on symbol at its definition

**Alternative 2 (rejected ❌):**
Go to definition: Cmd + Click on symbol
Find references: Cmd + alt + click on symbol

#### Additional context

Final decision between the alternatives above is currently being polled.

#### Telemetry

- [ ] Record telemetry to track token-clicks for defs/refs vs hover popover

**Comment by jjinnii** [comment]
@chrismwendt For the reasons outlined in the [outcomes section of RFC 534](https://docs.google.com/document/d/1ge8pPI5Xk2vuxbgfeh8L5PMEpwmjhs1ayOAijMy0fjE/edit#heading=h.3ps469qorpbk), we'll be moving forward with the click shortcut behavior! 

To measure the success and usage of this new functionality, are we able to add telemetry so that we can track the volume of users navigating to ref/def, specific to this shortcut? (ie not from the popover or reference panel) 

cc: @macraig

**Comment by chrismwendt** [comment]
Updated the issue description for (non-cmd) click and telemetry.
