### ISSUE TITLE
Improve "create an access token" flow for the VS Code extension

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#28311]
Users need to create an access token on Sourcegraph web, which they then add to their VS Code settings, in order to either view private Cloud repositories or search over private instances. We should try to streamline this process in the VS Code extension.

**Comment by abeatrix** [comment]
Progress Update:

I'm able to set up a local server and redirect the oauth flow to browser, but getting an error saying `could not decode OAuth state from URL parameter.`.  
![Screen Shot 2022-05-10 at 1 33 36 PM](https://user-images.githubusercontent.com/68532117/167717737-c0ce4999-6617-47d8-b81d-d9835ca50d3e.png)

![Screen Shot 2022-05-10 at 1 33 44 PM](https://user-images.githubusercontent.com/68532117/167717747-d66677aa-9e7e-403c-a466-e67815056adb.png)

The state is the same in both login and call back URLs:
https://github.com/login/oauth/authorize?client_id=6c8a4d3cf7096c4b4972&redirect_uri=https%3A%2F%2Fk8s.sgdev.org%2F.auth%2Fgithub%2Fcallback&scope=user%3Aemail%2Bread%3Aorg%2Brepo%2C&state=http%3A%2F%2F127.0.0.1%3A49319%2Fcallback%3Fnonce%3Dvsce

https://k8s.sgdev.org/.auth/github/callback?code=6bdd0d6453c577996780&state=http%3A%2F%2F127.0.0.1%3A49319%2Fcallback%3Fnonce%3Dvsce

**Comment by abeatrix** [comment]
##.Propose tasks for this issue

In the meantime before we can come up with a better alternative, we can try to:

- [ ] Add redirect params to current sign up / sign in links so that users will be taken to the token creation page directly after sign up (For example, from [this](https://sourcegraph.com/sign-up) to [this](https://sourcegraph.com/sign-up?returnTo=%2Fuser%2Fsettings%2Ftokens%2Fnew).) Related Feedback: [link](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1651472440374389)
- [ ] Make the token import process from web to IDE as seamless as possible (maybe auto copy and paste etc)
TBC

**Comment by abeatrix** [comment]
### Progress update - Current auth flow: 

1. Click on login button in VSCE
2. A window will be opened for the user to login (the redirect function seems to be broken currently on Cloud?)
3. After logging in, the user will be redirect to the token creation page where a token will be sent back to our VS Code extension automatically if a specific search query is included in the URI.  (TODO: hash token before it's sent)
4. A windows will pop up and ask if the user wants to open the VS Code extension
5. Once the user has confirmed, the user will be redirected back to VS Code
6. They will be logged into the extension automatically, and the token will be stored in their setting (TODO: store token in secret storage instead of user config)

Demo Video: https://www.loom.com/share/09fc13c51184493796ac326918358e1c

@tjkandala Do you think this would be a good approach / any security concerns?
