### ISSUE TITLE
ci: investigate why the code-insights db is failing often 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28385]
The code-insights database is often a source of failure on the CI, because a test fails to connect to the database. 

Context: https://sourcegraph.slack.com/archives/C01N83PS4TU/p1638306863339000

**Comment by bobheadxi** [comment]
Is this a DevX issue or something for the insights team?

**Comment by bobheadxi** [comment]
re-assigning to insights team, who can close this out if this is determined to be not important due to upcoming migration away from timescaledb

**Comment by bobheadxi** [comment]
Circling back to this, because during grooming I had a suspicion this issue doesn't happen anymore - a query indicates this hasn't happened int he last ~30 days (or whatever our window for build logs is): https://sourcegraph.grafana.net/goto/jAhfvJxnz?orgId=1

Here's the issue tracking the retirement of code-insights db: https://github.com/sourcegraph/sourcegraph/issues/29531

In light of this, @jhchabran do you want to consider unassigning/un-plan-ing/simply closing out this issue? I don't think there's much of a need to investigate this further, especially with everything else on your plate :)
