### ISSUE TITLE
Add a GraphQL API to give repository permissions to a set of users

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#28593]
This endpoint must add permissions to both the `user_permissions` and the `repo_permissions` table.
If permissions for a couple repository/user already exist, they must be ignored.
⚠️ This endpoint must only work if the [explicit repository permissions](https://docs.sourcegraph.com/admin/repo/permissions#explicit-permissions-api) feature is enabled

Endpoint:

```graphql
AddRepositoryPermissionsForUsers(
    repository: "<repo ID>", 
    userPermissions: [
      { bindID: "charlie@example.com" },
      { bindID: "alice@example.com" },
    ])
)
```

**Comment by mollylogue** [comment]
Okay, so my understanding is that this differs from `setRepositoryPermissionsForUsers` because it is additive, i.e. if I call this new function `AddRepositoryPermissionsForUsers` with a single user, it will just add the perms for this user for this repo (& vice-versa for the repo) while maintaining all existing users that may have permissions to access this repository. @asdine @indradhanush does that sound correct?

**Comment by asdine** [comment]
@mollylogue Yes exactly, `AddRepositoryPermissionsForUsers` is simply a more explicit API that does only one thing and that can be optimized for that task.

**Comment by asdine** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/36355
