### ISSUE TITLE
Gauge interest in API docs 

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#28609]
Gauge interest in API docs by improving the empty page for repos that do not have API docs with a form that allows users to submit interest. 

```
Api docs is not available for this repository. You can view the experimental API docs feature at https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/docs

Use the form below or submit an issue to request support for your code.

Your name
[name]

Your email
[email]

Comments
[textarea]

[Submit]
```

**Comment by vdavid** [comment]
I wondered how the page currently looked like → found [an example](https://sourcegraph.com/github.com/sourcegraph/handbook/-/docs).
<img width="733" alt="repo without API docs" src="https://user-images.githubusercontent.com/2552265/148793777-92aa65a0-e42b-4757-8b6f-6aad09f9d3c0.png">
Also, we seem only to support Go now, so this issue is probably low impact.

**Comment by malomarrec** [comment]
Sounds updated. Closing. Re-open if you disagree.
