### ISSUE TITLE
SPIKE: Why is incremental approach for unindexed symbols failing

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#28680]
The initial solution for improving unindexed symbol lookup does not survive the encounter with the mega repo. Explore option for incremental win against the rock skip approach.
From our Q4 OKR sync up.

**Comment by keegancsmith** [comment]
@sourcegraph/search-core what is the status of symbols with respect to our team? Are we waiting and seeing what becomes of rockskip #28719? I think that was our decision, that way we can focus more on unindexed text search.

**Comment by scalabilitysolved** [comment]
Hey @sourcegraph/search-core :wave: 

@chrismwendt is still focusing on Rockskip, he'll be able to provide more detail on where we are with that.

**Comment by chrismwendt** [comment]
Around Dec 7 when this issue was filed, there was a bug (likely introduced in https://github.com/sourcegraph/sourcegraph/pull/28407) that made all symbols requests stop working. I'm guessing that's you mean by "does not survive". That bug was [fixed](https://github.com/sourcegraph/sourcegraph/pull/28720).

However, the `symbols` service does not work on repos that take 20+ minutes to process symbols (~4+GB `.git`). While running a test instance with the megarepo, I discovered the timeout has been in place for years:

https://github.com/sourcegraph/sourcegraph/blob/dc69606570a15895acacef986be03059d2be9e8c/cmd/symbols/main.go#L100

I just now [bumped the timeout to 2 hours](https://github.com/sourcegraph/sourcegraph/pull/29891), which should be enough time to process repos roughly the size of the megarepo.

With incremental processing, the first symbols request on a new commit takes a few seconds because it has to copy the SQLite DB on disk (3.7GB for the megarepo).

I'm going to gather data on repo and SQLite DB sizes to get a better sense for how much of an improvement Rockskip would be.

**Comment by keegancsmith** [comment]
Nice find @chrismwendt, thank you. FYI we are introducing a repo which is 10x the scale of megarepo soon. However, it will only be on k8s.sgdev.org. This is to simulate the scale we know a prospective customer is at.

**Comment by keegancsmith** [comment]
I don't think this is worth tracking anymore after rockskip work that @chrismwendt has done as well as other symbols improvements. Feel free to re-open if I am missing something.
