### ISSUE TITLE
Code monitor appears to run a different query from what is shown in the UI

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#28731]
Source: @andreeleuterio [on Slack](https://sourcegraph.slack.com/archives/C02E3R101L3/p1638970063065500)

> I am receiving a ton of alerts for a repo that I am not making any changes. After disabling that code monitor I am still receiving the alerts.

> I suspect there's a difference between what I'm seeing in the UI and what's stored in the backend. Through the UI the code monitor is turned off and shows as inactive.

**Comment by andreeleuterio** [comment]
Update: I clicked on the `View code monitor` link through the email, set it as `Inactive` and saved it. I now have two disabled code monitors with the same name and seem to have stopped receiving the notifications.

**Comment by lguychard** [comment]
Still 🤯  but... That's that, at least.

**Comment by camdencheek** [comment]
@andreeleuterio Is it possible you had this monitor active under a different account than the one you were logged in to? In the list view, it will list monitors for your currently logged-in account, but since you are a site admin, clicking the link directly to the notifying monitor will still allow you to view the monitor the email was from. It looks like that specific monitor was created by the `andretestingtest` account, which I don't expect is your primary account 😄

**Comment by andreeleuterio** [comment]
@camdencheek that must be it! Sorry for the silly bug report 🙃

**Comment by camdencheek** [comment]
No problem! This was very confusing and concerning -- thanks for bringing it up! I'm glad it turned out to be NBD. We should probably still fix the "site admins can accidentally steal code monitors" thing though 😄
