### ISSUE TITLE
search: Wrong alert. Regex parsing error instead of "no repositories found"

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#28781]
- **Sourcegraph version:** "Sourcegraph.com" 

#### Steps to reproduce:
compare
https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/handboos+%5Cs%E2%80%94%5Cs&patternType=regexp

with
https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/handbook+%5Cs%E2%80%94%5Cs&patternType=regexp

#### Expected behavior:
We should see a message "no repositories found"

#### Actual behavior:
Repo search failed: error parsing regexp: invalid escape sequence: \s

**Comment by rvantonder** [comment]
I'm pretty sure this was introduced by https://github.com/sourcegraph/sourcegraph/pull/27359

> We optimize run.RepoSearch to leverage the database for regex matching on repo name, rather than brute-forcing it through all paginated repos. This should address the massive extra DB load we saw in production yesterday.

Likely the database regex doesn't recognize character class `\s`

**Comment by rvantonder** [comment]
There are multiple ways to solve this. My hunch is to just skip the repo search if the pattern isn't valid. By "skip" I mean:

- don't create a repo search job if the regex isn't valid according to the database regex engine (whatever the call is that needs to be made to determine that). 

Note it's better to not create the search job at all, rather than inlining this validation check somewhere after we process job inputs. So likely, you want to call "thing that answers whether regex pattern is valid for repo search" in the `toSearchInputs` vicinity (or its dependents `query_converter.go`) to decide whether to skip creating a repo search job.
