### ISSUE TITLE
Feature request: call graph

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2882]
For answering "What components is this function called from?".

This could be a graph UI (i.e., with nodes and edges) optimized for understanding the connectivity of a function instead of seeing call sites (as the above screenshot UI is optimized for).

This is more complicated than a call hierarchy (#2881) because it assumes some intelligent grouping/layout of call sites and a visualization UI.

(Split off from #2278, related to #2881 and #2883)

**Comment by gbrik** [comment]
Some recent research into this:

No work has been done to validate the feasibility of supporting this via basic code intelligence, but it seems possible in some scenarios.

Re precise code intelligence, there is starting to be some momentum around this feature in the LSP world. [Here](https://github.com/theia-ide/typescript-language-server/blob/2f1ef7286404e9c8f5e41480c6996eef6cffde3d/server/src/call-hierarchy.lsp.proposed.ts) is an example implementation using an unofficial interface. When the feature matures a bit more, we could consider adding it as a custom extension to the LSIF spec, as I don't think the official version is going to receive updates any time soon. This will require work in all of our indexers, and again calls out the importance of leveraging community work on language indexing to ease our language support burden.

High level steps to support:
- [ ] UI to expose this feature
- [ ] Basic code intel support for this feature
- [ ] Backend support for processing LSIF indexes containing this feature
- [ ] Add this feature to our indexers

Go support could be a project with ~a quarterly timeline, given we probably wouldn't want to dedicate anyone to it full time.

**Comment by codeanit** [comment]
Thank you for raising the issue @sqs.

I was trying to figure out the same and
reached a dead end.

This feature would be very much useful 
for many generic purpose of code analysis. 
But it is sad to see it's not getting any focus.

**Comment by macraig** [comment]
This feature request is now tracked in [Productboard](https://sourcegraph.productboard.com/feature-board/1825051-code-intel/features/8233708/detail)

**Comment by gianluca-sabena** [comment]
I need this functionality (*) too, and I would like to have some update, but I can't access productboard.

What does it mean when a functionality is tracked in Productboard? Is it possible to have access? Will it be available as commercial functionality only?

(*) My use case is to identify what part of a large codebase is connected (and as a consequence is "safe" to migrate/update). 

Thank you

**Comment by macraig** [comment]
Hi @gianluca-sabena, thanks for taking the time to express your interest in this feature! I'll do my best to answer all your questions below:

> What does it mean when a functionality is tracked in Productboard? Is it possible to have access? 

We like to keep our backlog lean, which means we close any issues that are not actively being worked on. As this feature request hasn't been prioritized yet, we are not currently working on implementing it and therefore we've marked the associated GitHub issue as closed for now. 

To keep track of interest and aggregate user feedback we use Productboard, which is only available accessible to Sourcegraph teammates. However, if we were to gather enough feedback to prioritize the feature and start actively working on it, we'll re-open this issue so that anyone that's interested can follow our progress.

> Will it be available as commercial functionality only?

Making it available for enterprise only isn't part of the current plan, if this changes in the future (which I think is unlikely) we'll make sure to state it in a clear way to prevent potential confusion among users. 

> (*) My use case is to identify what part of a large codebase is connected (and as a consequence is "safe" to migrate/update).

Thanks for sharing this information, it's very helpful! Would you mind expanding on your use case? What does your current workflow to solve this problem look like? What's the pain you'd you're looking to solve by having a call graph? Can you describe what that solution would ideally look like to you? 

We’ll be looking at this in the future, would you mind if we reach out to you at that point?

**Comment by yusiwen** [comment]
Any updates?
