### ISSUE TITLE
Can't use Cmd-Left shortcut to go back in browser history when the search bar is focused

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#28846]
- **Sourcegraph version:** latest Cloud version
- **Platform information:** Firefox

#### Steps to reproduce:

1. Open a file view
2. Use "Go to definition"
3. Pressing Cmd-Left to go back in history has no effect

#### Expected behavior:

I expected the browser to go back in history in step 3. I think the best fix would be if we stop auto-focusing on the search bar when loading a new blob view. I think it's OK for users to manually click on the search bar if they want to type a query, or alternatively use the `/` shortcut to focus on the search bar.

#### Actual behavior:

The search bar is focused and the cursor moves to the start of the query. The only way to go back in history is to use my mouse to click on the left arrow icon.

![CleanShot 2021-12-10 at 12 57 12](https://user-images.githubusercontent.com/1408093/145570741-095b5230-1e62-4d85-b844-c29b53e88bc9.gif)

**Comment by macraig** [comment]
@benvenker what's your take on removing auto-focus on the search bar?

**Comment by benvenker** [comment]
Personally, the auto-focus drives me crazy because I use Cmd+left to go back all the time in my normal browsing habits. I don't think keeping the search bar focused is standard/expected behavior, but I assume at some point we thought this might be preferred.

We do have a keyboard shortcut to focus the search bar, and my personal opinion is that that's sufficient.

**Comment by olafurpg** [comment]
Great! I opened a PR removing the auto-focus https://github.com/sourcegraph/sourcegraph/pull/28943

I'll share a video in Slack to see what other people think

**Comment by benvenker** [comment]
Awesome, thank you!
