### ISSUE TITLE
codeintel: Extra "Find implementations" button

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#28973]
Sometimes multiple "Find implementation" buttons appear in the hover popover. No consistent repro steps have been identified, but we have some evidence that it actually occurs:

Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5fd162fc3939d36853dd58e26c6adee1955bfa46/-/blob/cmd/frontend/internal/auth/userpasswd/config.go?L14:6

![Screenshot 2021-11-17 at 12 59 26](https://user-images.githubusercontent.com/1387653/145980189-fd9871b5-ddaa-4070-b70b-579cb6109502.png)

<img width="1741" alt="screenshot_2021-12-14_10 41 31@2x" src="https://user-images.githubusercontent.com/1387653/145978448-905989f9-2d66-4641-a2e4-56a92e1eedba.png">

Extensions running when it occurred:

![image (2)](https://user-images.githubusercontent.com/1387653/145979317-a4a59d56-ac40-423d-9b4a-172fdd5c8f48.png)

My first guess is that there's a race condition somewhere in the extension host.

**Comment by chrismwendt** [comment]
@sourcegraph/extensibility Does this look like an extension host bug?

**Comment by erzhtor** [comment]
Thanks for reporting! Putting a link to the example, which I also could reproduce (sometimes) https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/auth/userpasswd/config.go?L14:6.

We can put it in our backlog to check if it is a bug on the extension host side or somewhere else.

**Comment by erzhtor** [comment]
@chrismwendt, I spent some time researching the issue (how extensions work + what could cause), but I have only assumptions since I could not reproduce it locally.
1. Extension is loaded twice
2. Extension contributions (basically `manifest.contributes.hover` is added into extensionHostState twice

So, can you, please, next time when you face this issue, check whether the extension is loaded twice or not (see dev tools console messages for `Activating Sourcegraph extension: {extension-name}`). Depending on that, we can continue w/ a proper fix.

cc @jjinnii @abeatrix 

P.S: Through, I do have a hacky fix which is to filter unique contribution actions, but I'm worried that it does not solve the root cause:
https://github.com/sourcegraph/sourcegraph/blob/415fded48b44a90f490e56e1efa1288524403a56/client/shared/src/contributions/contributions.ts#L22 to 
```js
     const menuItems = uniqWith(contributions.menus?.[menu], isEqual)
```
OR specifically hover action item buttons
https://github.com/sourcegraph/sourcegraph/blob/4d4320f168c3779d116390d3fd213c040b45bbd4/client/shared/src/hover/HoverOverlay.tsx#L142 to 
```js
     uniqWith(actionsOrError, isEqual).length > 0 && (
```

**Comment by philipp-spiess** [comment]
Do we know if, when this problem occurs, it is limited to one hover or the whole session? I.e if this issue is observed, will it be fixed when we hover over a different code segment? 

@erzhtor Given that there's not really a way for us to repro this and get more data on what's going on: What do you think about the idea of adding production logging and include as much information as we can think of about how this state came together? We could do something like you described above with the `uniqWith` filter and, in case we do have some duplicated, also log all the context we can find. The only thing I’m not sure yet is how much useful information we can even collect without adding a bunch of debug context across the different layers.

**Comment by erzhtor** [comment]
> @erzhtor Given that there's not really a way for us to repro this and get more data on what's going on: What do you think about the idea of adding production logging and include as much information as we can think of about how this state came together? We could do something like you described above with the `uniqWith` filter and, in case we do have some duplicated, also log all the context we can find. 

Sounds good. I like it. 👍 

> The only thing I’m not sure yet is how much useful information we can even collect without adding a bunch of debug context across the different layers.

Yeah, we also need to be careful not to log/collect user/repo info.

**Comment by mrnugget** [comment]
We managed to reproduce it!

1. Query `repo:^github\.com/mattn/goreman$ file:^main\.go` and hover over `procInfo` and see 1 `"Implementations"` button
2. Inside Sourcegraph, navigate to a repo that doesn't support `"Implementations"` and hover there: `repo:^github\.com/rust-analyzer/rust-analyzer$ file:^crates/hir_ty/src/display\.rs`
3. Go back to (1), hover again and see 2 `"Implementations"` buttons

https://user-images.githubusercontent.com/1185253/149803495-17a86a99-f74b-4536-9332-8e27d1f42327.mp4

**Comment by tjkandala** [comment]
Hello! I left a comment on @philipp-spiess's PR that may be addressable in the code intel extension(s):

> Your investigation made me realize that it's not simply the same action contributed by all the language extensions, unlike the panel actions that simply toggled a user setting. I think in this case it might be a code intel issue? I believe they should hide the find implementation button using the `when` field when the command is a noop. Currently they do that by checking if there are [implementations for the current language](https://sourcegraph.com/github.com/sourcegraph/code-intel-extensions/-/blob/template/package.json?L56), but that means that even extensions generated from this template that _aren't_ for the currently language will show their noop buttons. Could they check that the current language also matches the extension's language? It should be doable during [extension generation](https://sourcegraph.com/github.com/sourcegraph/code-intel-extensions/-/blob/scripts/generate.ts?L46).


I haven't tested this myself but I'm 90% confident that this is the issue.

I also wonder why implementations are handled in the extensions themselves, unlike definitions and references. Read:

>It feels bending-over-backwards-y that defs/refs are built into Sourcegraph, but only their presentation, and the actual locationProvider comes from the extension, which has to match up the IDs of the built-in panels…

I think it makes more sense to have all the types of locations be built into Sourcegraph and to have extensions just provide the appropriate locations by `register{X}Provider`s. Most of the complexity/bending comes from our commitment to supporting [generic location providers](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/extension-api/src/sourcegraph.d.ts?utm_source=VSCode-0.0.2#L1710:25-1710:44). I don't know how likely 3rd party extension authors are to contribute a new type of location , and it would probably be easier for the code intel team to have implementations be built-in like defs/refs

**Comment by mrnugget** [comment]
Thanks for the investigation and thorough replies/comments, @tjkandala and @philipp-spiess! I'm new to code-intel and really new to Sourcegraph extensions (and that part of our frontend codebase), so I can't match the thoroughness here, sorry! 😄 I'll try to investigate though.

> I haven't tested this myself but I'm 90% confident that this is the issue.

Will bring this up in @sourcegraph/code-intel! 

> I also wonder why implementations are handled in the extensions themselves, unlike definitions and references.

I think it's because of [this thread in Slack](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1631656788142300?thread_ts=1631653667.141300&cid=C01LZKLRF0C) in which you said:

> I think it's reasonable to add a first-class implementations API, but I think that would make it awkward to control a built-in action through extension manifests.

But, as I said, I'm not well-versed in Sourcegraph extensions, so might be missing nuances here. 

> I don't know how likely 3rd party extension authors are to contribute a new type of location, and it would probably be easier for the code intel team to have implementations be built-in like defs/refs

Agree

> (side note: do defs/refs require "matching up built in IDs"? I was under the impression that that was the case for implementations, but that hover, definition, and reference providers were just "plug and play")

You're right! They're not matched up by ID. I was confused by how we set things up here on the Sourcegraph side:

https://github.com/sourcegraph/sourcegraph/blob/c43eb41b9973128477def452910a9b9ecdd2b09b/client/web/src/repo/blob/panel/BlobPanel.tsx#L177-L188

**Comment by tjkandala** [comment]
> Thanks for the investigation and thorough replies/comments, @tjkandala and @philipp-spiess! I'm new to code-intel and really new to Sourcegraph extensions (and that part of our frontend codebase), so I can't match the thoroughness here, sorry! 😄 

No problem, I always appreciated your bug reports and attention to detail from the other side, can't wait to see if applied here :)


> > I haven't tested this myself but I'm 90% confident that this is the issue.
> 

> 
> I think it's because of [this thread in Slack](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1631656788142300?thread_ts=1631653667.141300&cid=C01LZKLRF0C) in which you said:
> 
> 
> 
> > I think it's reasonable to add a first-class implementations API, but I think that would make it awkward to control a built-in action through extension manifests.

LOL🤦‍♂️. I was definitely more optimistic about the "generic location provider" concept then. 

> > (side note: do defs/refs require "matching up built in IDs"? I was under the impression that that was the case for implementations, but that hover, definition, and reference providers were just "plug and play")
> 
> 
> 
> You're right! They're not matched up by ID. I was confused by how we set things up here on the Sourcegraph side:
> 
Cool, so I kind of overreacted then to the complexity of location providers. It doesn't seem to affect DX for most extension use cases. I think if the quick fix I suggested works out, we can leave this part of the extension API alone
