### ISSUE TITLE
Test src serve-git support for SVN

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#29014]
This request is fairly nebulous, but we have a potential customer that uses Subversion and requires src serve-git to sync. We have some indication that this works at a basic level, but we're not confident enough to recommend it externally. 

The outcome of this issue is to determine how confident we are that src serve-git can support the customer. If we're not confident, identify potential next steps. 

**Need-by date**: mid-January
**Committed Date**: TBD

References:
1. Doc: https://docs.sourcegraph.com/admin/external_service/non-git
2. Tech-deal thread with more info: https://sourcegraph.slack.com/archives/C02MH5Z8MCP/p1638990995038800
3. Dev-chat thread: https://sourcegraph.slack.com/archives/C07KZF47K/p1639508398200400

**Comment by emchap** [comment]
To provide context: this is being prioritized because it impacts https://github.com/sourcegraph/accounts/issues/3556, who is a key prospect. It also impacts https://github.com/sourcegraph/accounts/issues/3440 (closed lost as a result of this), and https://github.com/sourcegraph/accounts/issues/908 (@mike-r-mclaughlin 's).

When https://github.com/sourcegraph/accounts/issues/3440 tested this, they found that SVN to git conversion on a 30GB repo took multiple days, which was not feasible. We need to establish benchmarks for how quickly a repo can convert, if there are max size limits, and do the converted repos behave as expected in Sourcegraph. Is there a converter that will yield better performance than git svn?

See also https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap__c/a1B5b00000K4szAEAR/view

**Comment by RoudyBob** [comment]
I know we were going to discuss in planning meetings to try to determine priority and timeline for this testing work. Any updates based on those discussions?

**Comment by jplahn** [comment]
@asdine is going to start looking into this issue this week.

**Comment by emchap** [comment]
@jplahn Just wanted to bump here—did this work begin/is there an update?

**Comment by jplahn** [comment]
Yep, @asdine started this last week. Unfortunately, he was pulled into the [Booking.com p1 issue ](https://github.com/sourcegraph/customer/issues/589) which put this work on pause while that finishes. Our plan is to wrap up the booking.com issue in the next day or two and then pivot back to this work.

@asdine - can you provide an update on what we've done and what's next?

**Comment by asdine** [comment]
@emchap @jplahn I have tested `src serve-git` with a few SVN repositories and apparently SVN is not supported at all.
`src serve-git` only serves local git repositories and ignores everything else.

`src-expose` on the other hand seems to be doing the job somewhat correctly:
- it serves the content of the current directory to Sourcegraph as if the directory was a git repo
- it detects changes, which are then made available to the Sourcegraph instance on the next sync

However, some important things are to be noted:

- `src-expose` doesn't read commits, git or SVNs, it only deals with files and directories
- The first time `src-expose` is used against a repository, it creates an internal git repository and creates a commit with the current timestamp as the commit message
- Every time a file changes, `src-expose` creates a new commit with the current timestamp

If the customer only cares about indexing the content and not the SVN history / branches, `src-expose` should be enough

If not, they are gonna have to use `src serve-git` in combination with a script + crontab to convert their SVN repo to Git periodically with the latest SVN commits.

I will double check tomorrow how this can be done and which tools should be used to do that.

TLDL; unless I'm missing something, SVN is not *directly* supported by any of these tools:
- either use `src-expose` to index the current *content* of your repository (SVN or anything else)
- or convert it to git and use `src serve-git`

**Comment by asdine** [comment]
`src serve-git` is the right solution, `src-expose` is deprecated and will probably be removed at some point.

Even though SVN is not *directly* supported, anything that can be translated to a Git repo is, and`src serve-git` is our officially maintained solution for that. It is used by other customers and is supposed to support any Git repository (otherwise this is a bug). I have tested it with a few SVN repos and it works perfectly.

Here's what they should do:

- Use [git svn](https://git-scm.com/docs/git-svn) to clone the SVN repository locally as a Git repo.

```bash
git svn clone https://SVN_REPO_ADDRESS
```

- Follow the [src serve-git](https://docs.sourcegraph.com/admin/external_service/src_serve_git) documentation

**Comment by jplahn** [comment]
Thanks @asdine! 

Do you have any thoughts on scaling these steps or what our limits are? I think that's the primary concern here as mentioned by @emchap in the second message. As you outlined, we have confidence that this process _works_, but I don't think we're clear where it stops working within some reasonable amount of time. 

> We need to establish benchmarks for how quickly a repo can convert, if there are max size limits, and do the converted repos behave as expected in Sourcegraph

As a follow up, we're also very interested if you have thoughts on how we might improve the performance of this on larger repos and rough t-shirt sizing to make that happen.

**Comment by emchap** [comment]
Yes, @jplahn is correct—I need to know at what point I can't reasonably recommend this to the customer because of speed, and we have no guidance there.

**Comment by asdine** [comment]
> When sourcegraph/accounts#3440 tested this, they found that SVN to git conversion on a 30GB repo took multiple days, which was not feasible. We need to establish benchmarks for how quickly a repo can convert, if there are max size limits, and do the converted repos behave as expected in Sourcegraph. Is there a converter that will yield better performance than git svn?

Sorry I completely missed that comment and only focused on if `src serve git` was robust enough to serve a large repository (context-switching is hard sometimes)

Regarding `git svn`, it is indeed incredibly slow, I have been trying to clone a few large OSS SVN packages these past 2 weeks and I just gave up. It is definitely not an option.

I am currently testing [svn2git](https://github.com/svn-all-fast-export/svn2git), which apparently is much faster, against various Apache foundation repositories. I'll keep you posted

**Comment by emchap** [comment]
Glad to know it wasn't just my users. :) Thank you for testing! Crossing my fingers on svn2git.

**Comment by jplahn** [comment]
Providing an update here: @asdine has started testing svn2git, but we're currently prioritizing the Tinder p1 issue https://github.com/sourcegraph/customer/issues/622 for the next couple of days. We'll loop back here Wednesday with a new update on whether the Tinder issue is resolved and the status of our testing for svn2git.

**Comment by asdine** [comment]
Hey @emchap, I'm still working on the Tinder P1 issue and will probably be busy until the end of the week. Do you think the customer can wait until then?

**Comment by emchap** [comment]
@asdine Yes, if we need to tackle the p1 it should take precedence. Would love to have this tested next week if we can, though.

**Comment by asdine** [comment]
@emchap [svn2git](https://github.com/svn-all-fast-export/svn2git) is indeed the right solution. It is extremely fast and is the most solid solution for converting large SVN repos to Git.

⚠️ A ruby command also called svn2git exists. This is very slow, they must not use it.

I have tried it on repos of various sizes and it seems to scale linearly.

Here is the most relevant benchmark:

- Generated a 30 Gb repo
- 42k revisions / commits of 1MB each
- **Total**: **39m51s**

Besides being fast, this tool has several advantages:

- Highly customizable
- Can choose min/max revisions to convert
- Resume conversion / update repo with new revisions
- It can generate one or more git repo out of one SVN repo
- The generate repo is a valid git repo that works perfectly with Sourcegraph

Here's what they need to do:

- Build svn2git from [source](https://github.com/svn-all-fast-export/svn2git)
- Write a [ruleset](https://techbase.kde.org/Projects/MoveToGit/UsingSvn2Git#Running_svn2git). This will allow them to generate one or more Git repos, based on a set of rule they need to define. Here is the one I used for my repo:

```
create repository foo
end repository

match /.*/
  repository foo
  branch master
end match
```

- Run this command on their repository (not the working copy): `svn2git path/to/repo --rules ruleset.txt`

This will generate one or more Git repos that they then need to serve using `src serve-git`.

**Comment by jplahn** [comment]
Moving this to done for now, but feel free to re-open if we have follow up.

**Comment by mike-r-mclaughlin** [comment]
In case this is helpful to anyone else, I used `svn2git` (the c++ one linked above) at Carrier and [documented](https://github.com/sourcegraph/customer-assets/blob/main/accounts/Carrier/HOWTO_ADD_SVN_TO_SG.md) the steps that I followed.  I also created a script to [automate](https://github.com/sourcegraph/customer-assets/blob/main/accounts/Carrier/USE_AUTOMATION_SCRIPT.md) creating and keeping a Git repo in sync as part of this too.

Also, fwiw, I wasn't able to convert their repo on the first pass because we saw this error:
`Failed to write to process: Error writing to process` 
The crash report file in the `.git` folder provided the real cause of the error:
`fatal: Can't create a branch from itself: refs/heads/main`

After some debugging, I found the actual problem was that in a previous revision, it ran [this line](https://sourcegraph.com/github.com/svn-all-fast-export/svn2git@6b987addebe07ccfef2834a0be9db38778938b5b/-/blob/src/svn.cpp?L728) and deleted the branch.  It shouldn't have deleted the branch at all.  
When I looked at `svn log -r {revision triggering delete}`, I saw that one of the changes in this revision was to delete a directory.  
After adding a lot more debug log output to `src/svn.cpp`, I realized that the real problem is with the `match /.*/` line in the ruleset file.  When set to `/.*/`, [this line](https://sourcegraph.com/github.com/svn-all-fast-export/svn2git@6b987addebe07ccfef2834a0be9db38778938b5b/-/blob/src/svn.cpp?L433) will set the `svnprefix` to the full path on any matched file.  For example, if a file named `/SVN/Foo/Bar/Baz/example.txt` is changed in a revision, that line will set the `svnprefix` to `/SVN/Foo/Bar/Baz/`. This is fine for most operations.  But, not for delete directory operations.  If you later delete the folder `/SVN/Foo/Bar/Baz/`, the `svnprefix` will match that folder.
And, then [this if condition](https://sourcegraph.com/github.com/svn-all-fast-export/svn2git@6b987addebe07ccfef2834a0be9db38778938b5b/-/blob/src/svn.cpp?L725) evaluates to TRUE (of particular importance is `current == svnprefix`).  This causes it to think the revision is deleting the entire branch (because the "svn prefix" was deleted) when it reality it is only a directory being deleted under the svn prefix.   In order to fix this, I matched the directory at the top (e.g, `match /TopDir/`)

**Comment by jplahn** [comment]
Thanks for that @mike-r-mclaughlin.

Did `svn2git` work for you after you made those fixes? How many repos did the customer have?

**Comment by mike-r-mclaughlin** [comment]
@jplahn : they have just one repo right now.  it's about 15G in size with about 105k commits.  It's not a huge repo.  It took several hours to build the Git repo but updates after that are quick. We'll have users testing it out in the next week so I'll report back if we hear of any issues.

**Comment by emchap** [comment]
@mike-r-mclaughlin Thanks so much!
