### ISSUE TITLE
Codecov integration roadmap

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2920]
This issue captures the work (which spans multiple releases) to improve Sourcegraph's integration with [Codecov](https://codecov.io) in https://sourcegraph.com/extensions/sourcegraph/codecov.

(WIP)

**Comment by felixfbecker** [comment]
I believe the codecov extension is the most useful extension we have in the marketplace that is not a codeintel extension. Here are my thoughts for improving it:

- Use pressed style for toggle: https://github.com/codecov/sourcegraph-codecov/pull/24
- Support decorations on diffs/PRs #911, https://github.com/codecov/sourcegraph-codecov/issues/23, https://github.com/codecov/sourcegraph-codecov/issues/10
- Support start-of-line decorations for line hit counts (instead of end-of-line)
- Fix errors and improve robustness: https://github.com/codecov/sourcegraph-codecov/issues/22, https://github.com/codecov/sourcegraph-codecov/issues/5, https://github.com/codecov/sourcegraph-codecov/issues/3, https://github.com/codecov/sourcegraph-codecov/issues/6, https://github.com/codecov/sourcegraph-codecov/issues/4

**Comment by felixfbecker** [comment]
@nicksnyder why was this closed?

**Comment by nicksnyder** [comment]
This tracking issue is stale and none of this work is on our actual near term roadmap.

**Comment by felixfbecker** [comment]
I think this issue accurately captures the TODOs on the codecov integration (whether we implement it or have the CodeCov team work on it), which has been an important use case of Sourcegraph extensions. We just did very recent work on the codecov integration: https://github.com/codecov/sourcegraph-codecov/pull/38

I'm afraid that the things covered here will not be visible if the issue is closed, and I see us wanting to keep an eye on this. I don't think it's good to close every issue that is not in the near term roadmap doc.

**Comment by unknwon** [comment]
Probably our new [project roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit) document is a better place to track these TODOs?

**Comment by nicksnyder** [comment]
> I think this issue accurately captures the TODOs on the codecov integration (whether we implement it or have the CodeCov team work on it), which has been an important use case of Sourcegraph extensions. We just did very recent work on the codecov integration: codecov/sourcegraph-codecov#38

It looks like there is no unique information in this tracking issue since all of the listed work items are links to issues on the codecov issue tracker.

If there should be an issue for "Support start-of-line decorations for line hit counts (instead of end-of-line)" then it seems like it would be appropriate to create an issue in sourcegraph-codecov for that.

> I'm afraid that the things covered here will not be visible if the issue is closed

The best way to make something visible is to put it in our [project roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit). We don't have plans to work on codecov anytime soon, but if/when we do, then we can easily go to that issue tracker, or more likely, will have a particular need when we decide to work on it and that will be the source of work.
