### ISSUE TITLE
Reached maximum allowed user repos error on Cloud

### ISSUE THREAD

**Issue by benjaminwgordon** [sourcegraph/sourcegraph#29339]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1.  Attempt to sync additional repositories through the "Your Repositories" menu
2.  Wait for the sync
3. Reload the "Your Repositories" page

#### Expected behavior:
New added repositories should be synced as expected
#### Actual behavior:
![Error](https://user-images.githubusercontent.com/17805669/147502071-8db85ed9-2a6f-402f-aaba-7278b5bb4868.png)

After the sync fails, the GitHub code host is marked as unreachable:

![Screen Shot 2021-12-27 at 1 37 26 PM](https://user-images.githubusercontent.com/17805669/147502150-dbf00352-3274-4252-8c99-fe3ece518f17.png)

**Comment by daxmc99** [comment]
@rafax determined that the root cause was in [repo-updater store code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/store.go?L144-159&utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.2#L170:24)

Namely, the query `SELECT COUNT(DISTINCT(repo_id))
FROM external_service_repos
WHERE user_id IS NOT NULL OR org_id IS NOT NULL` has `AND user_id = %d"` appended to it. 

Essentially, all the switch cases run an equivalent SQL statement. This has the effect of ignoring the number of repos that a specific user has added,  instead, it counts ALL user repos against the single user max.
