### ISSUE TITLE
Grafana log error `open /sg_config_grafana/provisioning/plugins: no such file or directory`

### ISSUE THREAD

**Issue by northyg** [sourcegraph/sourcegraph#29351]
- **Sourcegraph version:** 3.34.2
- **Platform information:** Kubernetes 
- [Internal thread for context](https://sourcegraph.slack.com/archives/C02BQBNJVL0/p1639990306089900)

#### Steps to reproduce:

1. User reported seeing the following error messages in their grafana logs.

**A)**
```
t=2021-12-20T08:50:32+0000 lvl=eror msg="Failed to read content of symlinked path" logger=provisioning.dashboard type=file name=sourcegraph_additional path=/sg_grafana_additional_dashboards error="lstat /sg_grafana_additional_dashboards: no such file or directory"
```
**B)**
```
{"@level":"debug","@message":"datasource: registering query type fallback handler","@timestamp":"2021-12-21T13:58:50.856483Z"}
t=2021-12-21T13:58:50+0000 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/sg_config_grafana/provisioning/plugins error="open /sg_config_grafana/provisioning/plugins: no such file or directory"
```
2. I reasoned that A) `/sg_grafana_additional_dashboards: no such file or directory` was due to it being an optional directory per [the docs here:](https://docs.sourcegraph.com/admin/observability/metrics#grafana-configuration)

The work around to no longer seeing that error was to mount an empty directory.

```
- mountPath: /sg_grafana_additional_dashboards
          name: additional-dashboard
- name: additional-dashboard
        emptyDir: {}
```

3. However, this error B) `/sg_config_grafana/provisioning/plugins: no such file or directory`, I could not find this directory listed in the docs. I reasoned it's optionally for Grafana plugins.

I found this one `sg_config_grafana/provisioning/datasource` mentioned in the [stateful set volume](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph/-/blob/base/grafana/grafana.StatefulSet.yaml)

#### Questions: 

1) What is this directory for? B) `/sg_config_grafana/provisioning/plugins`
Is it necessary or perhaps optional for Grafana plugins like the additional dashboard directory?
Is it something new? I didn't find other reported questions about it or docs.

2) Was I correct about A), it's optional?

3) Is there a better way to handle these errors when _not_ using those directories? This behavior is confusing to users who haven't added the optional directories/volumes.

Anything else that would help me understand is much appreciated!

**Comment by caugustus-sourcegraph** [comment]
@northyg - The `/sg_config_grafana/provisioning/plugins` directory is used when a customer wants to install a custom Grafana plugin - a [feature of Grafana](https://grafana.com/docs/grafana/latest/plugins/installation/#install-plugin-on-local-grafana). Since the Sourcegraph image use a custom provisioning directory, but doesn't install any plugins, it doesn't get auto-created. Customers could theoretically install plugins there but it's 100% optional.

I opened https://github.com/sourcegraph/sourcegraph/pull/29363 to take care of both of these errors for all customers. Your solution about mounting the emptyDir for `sg_grafana_additional_dashboards` is ok as well, especially as a short-term fix until the next release.

**Comment by northyg** [comment]
@caugustus-sourcegraph Awesome, thanks for the confirmation and for working on a solution for a future release 😸
