### ISSUE TITLE
Go extension opens multiple Go lang server WebSockets, all but last return empty

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2962]
I am seeing flakiness on https://sourcegraph.com/github.com/sourcegraph/go-diff/-/blob/diff/print.go#L13:6&tab=references with the fix at https://github.com/sourcegraph/sourcegraph-go/pull/53 applied. It usually falsely states there are no references from github.com/sourcegraph/sourcegraph. In doing so, it opens multiple (~4) WebSockets to the Go lang server. All but the last one return empty. The last one returns results, but they are ignored.

My expectation is that there are at least 2 references from github.com/sourcegraph/sourcegraph to that definition.

**Comment by chrismwendt** [comment]
Using the fix at https://github.com/sourcegraph/sourcegraph-go/pull/53 I'm seeing the 2 references (it took ~30 seconds to show up)

![image](https://user-images.githubusercontent.com/1387653/54887321-e81ad900-4e4e-11e9-9f9f-a1c0ed169b76.png)

I refreshed 4 times and got the same result each time. It doesn't wait for all WebSocket connections to respond to the `workspace/xreferences` call. I'm not sure why the results aren't being displayed.

Tangentially related: opening 3 connections to the same repository is redundant. I'll see if that can be consolidated.

**Comment by sqs** [comment]
@chrismwendt What do you see in the WebSocket frames for the other previous WebSocket connections? I see them as returning with `[]`. 

![image](https://user-images.githubusercontent.com/1976/54887504-2b4b6b00-4e94-11e9-9668-3f8f8958b9c7.png)

**Comment by chrismwendt** [comment]
All 3 return a result.

Did you override `go.sourcegraphUrl` by any chance?

To make sure we're on the same commit: https://sourcegraph.com/github.com/sourcegraph/go-diff@042635e6444e67483d777aaa240274f13691500c/-/blob/diff/print.go#L13:6&tab=references

**Comment by sqs** [comment]
Hmm, weird. I am now seeing sometimes where 2/3 or 3/3 return results. There still seems to be some nondeterminism. I can find a workaround.

If there is any way you can make this operation faster (eg just do it 1x instead of 3x), that would be a big improvement, too.

**Comment by chrismwendt** [comment]
There's a tentative fix for the redundant calls in https://github.com/sourcegraph/sourcegraph/pull/2964

**Comment by chrismwendt** [comment]
Another fix https://github.com/sourcegraph/sourcegraph/pull/2966

**Comment by chrismwendt** [comment]
For some reason, calling `sourcegraph.app.createPanelView(id)` seems to trigger a second redundant references call. After ~5 hours, I haven't figured out exactly why this is happening and how to fix it.

Here are some rough notes I kept along the way:

Extension calls `createPanelView(id)`, which registers a panel view provider:

https://github.com/sourcegraph/sourcegraph/blob/f104f673863e406ec459676b6d99b69c19163095/shared/src/api/extension/api/views.ts#L67-L68

https://github.com/sourcegraph/sourcegraph/blob/f104f673863e406ec459676b6d99b69c19163095/shared/src/api/client/api/views.ts#L34

https://github.com/sourcegraph/sourcegraph/blob/f104f673863e406ec459676b6d99b69c19163095/shared/src/api/client/api/views.ts#L38

> `viewRegistry` is known as `services.views` elsewhere

`PanelView` subscribes to that:

https://github.com/sourcegraph/sourcegraph/blob/f104f673863e406ec459676b6d99b69c19163095/shared/src/panel/Panel.tsx#L64-L71

Then the `HierarchicalLocationsView` subscribes to it:

https://github.com/sourcegraph/sourcegraph/blob/f104f673863e406ec459676b6d99b69c19163095/shared/src/panel/views/HierarchicalLocationsView.tsx#L74

I find it rather difficult to follow the interaction between rxjs subscriptions and React's lifecycle and determine what triggers the extra references call.

**Comment by chrismwendt** [comment]
If I comment out the creation of a panel `const panelView = sourcegraph.app.createPanelView(IMPL_ID)` in the Go extension, `provideReferences` is called once, as I expect. The problem only occurs when the extension creates a panel.

I think the problem is caused by the `Panel` component resubscribing to all location providers from existing panels when a new panel is added:

https://github.com/sourcegraph/sourcegraph/blob/f104f673863e406ec459676b6d99b69c19163095/shared/src/panel/Panel.tsx#L65-L69

- `getViews` basically returns an `Observable<PanelViewWithComponent[]>`
- `PanelViewWithComponent` contains a `locationProvider`, which is an Observable
- When an extension adds a panel, `getViews` emits another `PanelViewWithComponent[]` value
- The consumer of `getViews` doesn't know which panel is new and which panels remain from the previous emission

@lguychard @felixfbecker Do you know of any best-practices related to this (Observables of arrays of Observables) or how to fix it? I'm happy to share my screen and debug this with you if you want.

One way I can imagine fixing this is by emitting the **changes** to the array of panels (i.e. panel add/remove), rather than emitting the whole array each time. If a consumer needs the whole array, they can build it from that, or maybe a new function to get the whole array could be added.

**Comment by felixfbecker** [comment]
@chrismwendt still need help on this?

**Comment by chrismwendt** [comment]
@felixfbecker As long as my idea of "emitting the **changes**" above doesn't sound crazy, I'll attempt to implement it. A sanity check from either of you RxJS wizards would make me feel more comfortable about working on it 😅

**Comment by felixfbecker** [comment]
That sounds like a viable approach to me

**Comment by chrismwendt** [comment]
I attempted implementing the "changes" idea and discovered it's a more involved and fundamental change than I first thought. `FeatureProviderRegistry` and a bunch of subclasses would need to be changed. I'm putting it on the back burner for now.

**Comment by efritz** [comment]
We're no longer putting effort into langserver support.
