### ISSUE TITLE
Fully collapse "Files" and "Sourcegraph extensions" sections by default

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29696]
Currently, the default state in VSCE is having the Files and Sourcegraph extensions sections in the sidebar expanded(images below). These sections are not useful when a user is first starting a search, and it creates confusion as well as blocks the view of the Search section. Can we, by default, have these sections collapsed?

Current:
      
<img width="342" alt="Screen Shot 2022-01-13 at 10 28 09 AM" src="https://user-images.githubusercontent.com/87138876/149359050-5461ea8c-ff61-4c81-82ad-336b3d7dea65.png">
 
Expected
<img width="341" alt="Screen Shot 2022-01-13 at 10 30 00 AM" src="https://user-images.githubusercontent.com/87138876/149359381-25dc7073-3923-4bd3-9587-f19b9427d058.png">

**Comment by jjinnii** [comment]
Caveat to this ask: @abeatrix @tjkandala  is it possible to automatically un-collapse the file view when a user performs a search? I know we had that Files section open by default because we can't just "switch" to a files section sidebar like on sourcegraph.com.

**Comment by abeatrix** [comment]
@jjinnii I've changed it so that the file sidebar would only show up when the user is checking out a file.
Unfortunately, we will need to keep the extension host panel open for code-intel to work. Code intel will not work if the panel is collapsed or hidden, so we are planning to merge it with another sidebar component (tj has created an issue to track [here](https://github.com/sourcegraph/sourcegraph/issues/29642))
My question is, how do we make sure the users know that they will need to keep the extension host panel open to use code-intel before we move the component?
![image](https://user-images.githubusercontent.com/68532117/149370991-0c751fa6-3132-4a96-81ee-83f440541985.png)

**Comment by jjinnii** [comment]
@abeatrix Amazing news on the files section! Could you clarify for me what merging the extension host panel with another sidebar component means? i.e. if we can just merge that section into the Search section, what would need to be present on the UI?

**Comment by jjinnii** [comment]
@abeatrix Okay please do let me know! Having it open titled "Sourcegraph extensions" with nothing in the section is quite confusing for users :) If we decide we need to keep it separate and open, perhaps we can look to add something in there so it's not so confusing.

**Comment by abeatrix** [comment]
@jjinnii What should we put in the Extension Host panel? This is what we have currently as a placeholder 😆 
![image](https://user-images.githubusercontent.com/68532117/151001774-90e16e9a-b380-4cbf-9d86-c985707320d1.png)

**Comment by abeatrix** [comment]
We have migrated the extension host to the search sidebar to avoid confusion for the users in V2.0
