### ISSUE TITLE
Create a synthetic 15GB mono repo

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#29730]
Edit: this was adjusted from 60GB to 15GB after learning we can drastically reduce scale for the target customer.

As part of the Q4 effort on mono repos, create a synthetic 60GB repo so we can test our tools against it and gather metrics.

**Comment by keegancsmith** [comment]
Status update: This has been super slow work, mostly waiting around for git fetches to run to build up enough data. I'm currently only at 20GB working copy...

I also ended up exploring some issues in megarepo and have sent out several fixes/improvements:
- [#30228 git-combine: handle force pushes](https://github.com/sourcegraph/sourcegraph/pull/30228)
- [#30332 git-combine: sanitize usernames and urls out of titles](https://github.com/sourcegraph/sourcegraph/pull/30332)
- [#30333 git-combine: limit flag for a target commit history size](https://github.com/sourcegraph/sourcegraph/pull/30333)
- [#30334 git-combine: skip push if origin is missing](https://github.com/sourcegraph/sourcegraph/pull/30334)

**Comment by keegancsmith** [comment]
FYI I have something like a 36GB working copy. However, we are adjusting the scale down to 15GB after learning our largest target is currently much smaller (about 11GB working). This work was paused to try and learn more since I last commented. I hope to have time this week to finish this up, but support work takes first priority.
