### ISSUE TITLE
Clicking into search result opens file at inaccurate file location 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29772]
#### Expected behavior:
Clicking on the search result will open the file at the location of the searched for token, with exact line highlighted. 

#### Actual behavior:
Clicking into a search result with the expected result on code line x opens the file with line x-1 highlighted. For example, if I click into a search result with a token on line 28, the file opens with line 27 highlighted. This was first uncovered in an internal user test with Kelli Rockwell, and I was able to re-create the issue myself on a few different repository and search results. 
[Loom of bug](https://www.loom.com/share/9d754b19e5e342c89ca32be9b5d967f3)

**Comment by abeatrix** [comment]
I’m able to reproduce and locate the issue. The current behavior is that it doesn’t matter where you click in the file, it will always open the file with the first line number from the result. Using your example, clicking on line 81 or 82 will always open the file with line 80 highlighted.
Will come back with an update

**Comment by abeatrix** [comment]
Currently, on dotcom, a file link is created onSelect in FileMatchChildren for the selected File Match group ([link to code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.35.1/-/blob/client/shared/src/components/FileMatchChildren.tsx?L132)); however, the link does not work in VSCE for opening files since it requires `sourcegraph://` instead of `https://`. To fix this, I created [an alias of FileMatchChildren ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@vsce/vscode-open-in-browser/-/blob/client/vscode/src/webview/search-panel/alias/FileMatchChildren.tsx?L95-101)for VSCE, where it would set the state of positionSuffix for onSelect defined in SearchResult to generate a `sourcegraph://` URI.
