### ISSUE TITLE
INC-62 Followup: Understand why exceeding repository limit breaks an existing service

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#29832]
Follow up on the Action Item from https://app.incident.io/incidents/62

**Comment by sashaostrikov** [comment]
@rafax what does exactly "breaks an existing service" mean?

Exceeding repo limits breaks out of current sync of an external service and returns an error. Original error is generated [here](https://github.com/sourcegraph/sourcegraph/blob/2c11d9c1c4f3b893f012f76eca6dac6868ef7fd9/internal/repos/syncer.go#L693) after the limits are calculated.

Each and every consequent sync will fail if the limits are exceeded. This can be fixed either by deleting repos or by increasing the limits.

Does this answer the question, or did I get it wrong?

**Comment by rafax** [comment]
As far as I remember, even when limits were increased the service still showed an error (not sure if it is possible that it was showing error from last sync, and it would have cleared once the service was resynced).

Regarding the handling of "excess" repositories - should we be refusing to sync additional repos, but keeping the original ones in sync? As an (imperfect) comparison, when I exceed a rate limit of an API I'd expect the excess requests to be denied, but anything under quota should continue to work.

**Comment by sashaostrikov** [comment]
> even when limits were increased the service still showed an error

I think this is expected, because an error is a result of latest sync and will be always shown.

> should we be refusing to sync additional repos, but keeping the original ones in sync?

Well, the logic there is kinda tricky. During every sync requests for repos list are sent to a code host API. This includes `orgs`, `repos`, and `repositoryQuery` config options _and the repos are requested in reverse (bottom-top) order of declaration in site config_ ([it is described here](https://github.com/sourcegraph/sourcegraph/blob/037b501db47c8244619c9dc6fe26c34e647e3962/internal/repos/github.go#L541-L543)). That's why any new repo creation usually comes before any existing repo update, therefore the limits are checked at the first place and sync is "short-circuited" with the error about exceeding the limits.

I agree that new repos which cannot be added should not really affect sync of the repos which are existent, but I guess expanding sync logic to support this feature is neither simple nor quick to implement.

cc @ryanslade about making sync process "smarter" in this sense

**Comment by ryanslade** [comment]
We don't have too much control over the order in which the repos come back from the code host. When there is a manual list of repos defined then it's possible that we could re-order them so that repos that currently exist in our database are synced first though.

Bear in mind that any error during syncing will be bubbled up to the user but the service isn't really "broken". Repos that we know about will still have their code updated as this is taken care of by a different scheduler. The code host syncing is only worried about repo metadata.

**Comment by rafax** [comment]
Shouldn't / couldn't we use the order in which repos were added by the user? I understand we initially store the user intent as a JSON array in external_service config (not sure if the order is defined), but once we add repos to 'repo' table, can't we just take the first XXX repos by created_at?

**Comment by ryanslade** [comment]
A repo could be created by more than one user so the `created_at` date will be the date the first user added it. 

We could potentially add a `created_at` column to `external_service_repos` to track it per user / org. I don't think we can rely on the order of the fields in the external service config.

**Comment by mollylogue** [comment]
Is there more to do/look into here or should this be closed?

**Comment by ryanslade** [comment]
I think we can close this. We understand what was happening and plans to make the syncing order smarter are out of the scope of this incident.
