### ISSUE TITLE
Improve Sourcegraph quickstart guide

### ISSUE THREAD

**Issue by bitwisetech** [sourcegraph/sourcegraph#29857]
Lost ! 
Fedora 35 
sudo dnf install docker

Following quick install instructions: 
   docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 
  --rm --volume ~/.sourcegraph/config:/etc/sourcegraph 
  --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.35.1

Result: 

docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

 docker run --help outputs so, the daemon is running, isn't it ?  

Any hints, Tks

**Comment by varungandhi-src** [comment]
> docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
>
> docker run --help outputs so, the daemon is running, isn't it ?

Hi, the problem seems to be that the Docker daemon isn't running. The way Docker works is that there needs to be a daemon running in a background, and a `docker run` command will try to connect to the daemon when you try to start a container. If the daemon isn't running, then the `docker run` command will fail with the error you're seeing.

It seems like a Docker bug that they're recommending `docker run --help`; they should point to docs on how to start the Docker daemon and how to troubleshoot if the Docker daemon is running or not.

To check if the Docker daemon is running or not, try running `docker ps` (similar to `ps`). It should show an empty list of containers if you haven't started any. `docker run --help` only prints some help text; I don't think it requires the Docker daemon to be running.

If Docker is configured properly, running `sudo service docker restart` should be enough to start the daemon.

If it's not configured, you may want to follow the steps in the Docker documentation on how to configure it. https://docs.docker.com/engine/install/linux-postinstall/

You may also find this discussion on StackOverflow useful (it's about Ubuntu, but I'm guessing much of it probably applies directly to Fedora): https://stackoverflow.com/questions/26137834/starting-docker-as-daemon-on-ubuntu

**Comment by dan-mckean** [comment]
Closing as this isn't something we'd cover in our quickstart guide as this relates to troubleshooting a working Docker install.
