### ISSUE TITLE
search: move search code into a new package: /pkg/search

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3011]
Lots of search-related code is currently tangled up in the graphql layer of the frontend, and also sequestered in cmd/frontend/internal/pkg/search. It seems more logical to have all the search-related code under one directory tree so we can see its code coverage at a glance and more easily navigate it. In addition, we would like to try out the possibility of consolidating all the search-related microservices into a monolith that can easily be tested using `go test`.

**Comment by ijt** [comment]
After spending a day trying to do this, I'm no longer convinced that this is the best way to enable testability and swapping out search backends. I have a different proposal in mind now involving splitting the graphqlbackend into its own process and being able to have more than one version of graphqlbackend possibly running at the same time. I'll follow up with that in a different issue.

**Comment by slimsag** [comment]
Can you link me to that issue once it's created? I do have some concerns about introducing a new process for this. I suspect moving code into a subpackage or moving it into the `searcher` service will make more sense

**Comment by ijt** [comment]
@slimsag, sure.

**Comment by ijsnow** [comment]
Backlogging for now. Will circle back when a more immediate need is felt by the team.

**Comment by ijsnow** [comment]
## Use case: Streaming results

Having the ability to stream results back to the client would be great for our web app's UX. I won't explain why here.

[GraphQL does support streaming via subscriptions,](https://www.howtographql.com/graphql-js/7-subscriptions/) however the go library we use for graphql only [has partial, work in progress support for subscriptions that has seemed to stall.](https://github.com/graph-gophers/graphql-transport-ws)

We have two paths forwards for implementing streaming of search results:

1. Wait on/contribute to graphql-go to add full support and ensure it's production ready

I have not vetted the library's support so I do not know how far away from full support it is. This approach has a lot of unknowns but isn't entirely a bad one.

2. Isolate search logic by removing it from our graphql layer so that we can put it behind an endpoint that supports websockets

I prefer this solution. It will have the side effect of giving us more control and re-usability over our search code. In the end, we'd be able to expose search in any way we'd like. This is also inline with [Graphql's best practices on structuring code/business logic.](https://graphql.github.io/learn/thinking-in-graphs/#business-logic-layer)

**Comment by ijt** [comment]
This looks like too much effort for not enough benefit. Closing it.
