### ISSUE TITLE
Test code host swapping with already on-disk content

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#30144]

**Comment by emchap** [comment]
This is for customer https://github.com/sourcegraph/accounts/issues/4778.

Customer has two GitHub instances: Primary and Secondary. Primary is the production GH; Secondary is a clone of Primary, but running about a month behind. Due to customer's scale, they are worried about the load on Primary if we hit it to clone over all of their repositories at once (more than 100k). 

Customer wants to know if they can connect Sourcegraph to Secondary, clone over the content, and then connect to Primary and have us use the existing on-disk content, and simply fetch updates. Per Slack convo (https://sourcegraph.slack.com/archives/C022SPMNR0W/p1642620725121500) Sourcegraph will not deduplicate between the two instances. However, it was proposed in the conversation that Sourcegraph might be able to use the existing content _if_:

1. Instance is connected to Secondary, clones everything. 
2. The directory structure was altered to point to Primary
3. The connection to Secondary was deleted in the code host management interface
4. Then the instance was connected to Primary. 

Though obviously not supported, would this work?

Is there another way for us to connect to a proxy server but mirror the content as belonging to its URLs at Primary in order to reduce load on Primary? The goal is to reduce load on Primary, so if there's an alternative solution I'm just missing, please let me know.
