### ISSUE TITLE
Required terraform version is inconsistent in the template

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#30221]
Via https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/190, we bump terraform version to 1.1.3, but `infrastructure.tf` is still referencing `0.12.28`

https://github.com/sourcegraph/deploy-sourcegraph-managed/blob/main/template/infrastructure.tf#L83 

## Fix

- Bump the version at https://github.com/sourcegraph/deploy-sourcegraph-managed/blob/main/template/infrastructure.tf#L83 to `1.1.3`

## Notes
There shouldn't be any breaking change. Terraform version keeps on changing every day and I lost track already... 
That said, I should know more later as I am deploying one myself with 1.1.3.

**Comment by kevinwojo** [comment]
Hey @michaellzc, this was an oversight on my part. I was mashing `meld` and somehow forgot to commit that change. Feel free to update and test by creating a new managed instance.

**Comment by michaellzc** [comment]
Hey @kevinwojo , I plan on doing so on my own today.

So I try deploying several managed instances with `1.1.4` without changing anything in the module, so I guess the upgrade should be seamless.

We can do the following

- [ ] Bump the version in the template to `1.1.4` or whichever is the latest
- [ ] Migrate existing managed instances tfsate to use the latest version (I think it's just a matter of rerunning `terraform init` or something? I'll double check their docs)
thoughts?

cc @caugustus-sourcegraph

**Comment by kevinwojo** [comment]
Howdy @michaellzc, 

I think 1.1.4 is fine. Upgrading should be safe as long as `terraform plan|apply` does not make any changes. From what I remember, there were a few fields that change (I believe gcp_buckets now require a location ... small changes like that). Your PR should yield `No changes` I guess is my point.

Make sure to update `.tool-versions` in each project for `asdf`. Otherwise SGTM!
