### ISSUE TITLE
dev/ci: run discovery on ways to improve clone speed

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#30237]
On stateless agents, the git clone step takes over 30 seconds for every build, due to the size of our repository. 

By using https://github.com/buildkite/agent/blob/main/EXPERIMENTS.md#git-mirrors we may be able to get back to the timings we had on the stateful agents.

**Comment by bobheadxi** [comment]
Correction: clone steps take >1m on all jobs

Increasing the scope of this to include _any_ improvement to git cloning. Other approaches:

- https://randyfay.com/content/reference-cache-repositories-speed-clones-git-clone-reference + shared read-only volume

**Comment by bobheadxi** [comment]
Also noted by Keegan:

- we no longer do shallow clones, and instead do a full clone of our repo for every step from github
- submodules also involve full clones

**Comment by keegancsmith** [comment]
Throwing an idea out, no idea if this is easy to do with stateless agents. But in a previous life when I looked after CI in a monorepo one of the major improvements I did was before an agent was marked as ready it would clone into place the repo, then all it had to on the critical path was fetch and checkout. This idea of priming before being marked at ready is quite useful. EG asdf seems to spend more time laying stuff out than fetching when I looked at a few builds.

There was some care taken to remove any state from previous runs, but in practice it worked really well at a much larger scale than our CI.

**Comment by bobheadxi** [comment]
> before an agent was marked as ready it would clone into place the repo

With stateless agents, unfortunately this might just push the setup lag from the "preparing working directory" to "waiting for an agent", since we scale up to roughly meet demand, and agents are discarded once used 😅  Our agents are also shared across multiple repositories, so we can't predict reliably what repo to clone (though the latency is mostly an issue in the main repo anyway so might not be too much of a factor)

Thanks for sharing though!!

@davejrt and I hacked on this a bit today, and we might have an approach with a regularly-updated PV that agents can use, which contains clones for reference: https://github.com/sourcegraph/devx-scratch/blob/main/2022/stateless-agents/log.snb.md#2022-04-06-repository-clone-optimization

**Comment by davejrt** [comment]
@bobheadxi a thought I also had, is could we just do this as part of the image build, and create a new image x time per day and have a PR setup to update [the image](https://k8s.sgdev.org/github.com/sourcegraph/infrastructure/-/blob/buildkite/kubernetes/buildkite-agent-stateless/buildkite-agent.Job.yaml?L25). Then have buildkite apply it as it currently does https://k8s.sgdev.org/github.com/sourcegraph/infrastructure/-/blob/ci/buildkite.sh

**Comment by bobheadxi** [comment]
Oh, in hindsight that does seem easier 😆 But the disk approach is nice in that it separates the concerns a bit better, and I just got it working - initial comparison: down from ~34s to ~5s on a branch that has diverged a bit from main (16 behind, 1 ahead)

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/23356519/162483953-a9e38cd7-826c-4c17-9711-33e5a11c3c13.png">
