### ISSUE TITLE
'Go To Definition' link still remains active when navigated to the definition.

### ISSUE THREAD

**Issue by amarsiingh** [sourcegraph/sourcegraph#3024]
- **Sourcegraph version:** 3.2 or latest
- **Platform information:** macOS Mojave 10.14.3, Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)

#### Steps to reproduce:

1. Go to a source file and tap on a variable/function name.
2. In the exploring popup, tap 'Go To Definition' option.
![Screen Shot 2019-03-28 at 11 05 00 AM](https://user-images.githubusercontent.com/4612840/55170217-8c04cd00-514c-11e9-84bb-7db92c84f0a3.png)

#### Expected behavior:
• When at the root of the of definition, 'Go To Definition' option should be inactive or hidden, to indicate root of the search navigation.

#### Actual behavior:
• 'Go To Definition' option is still active, and tapping on it doesn't have any effect.
![Screen Shot 2019-03-28 at 11 03 49 AM](https://user-images.githubusercontent.com/4612840/55170209-86a78280-514c-11e9-8e72-e4eda89d58a7.png)

**Comment by attfarhan** [comment]
@chrismwendt this is a possible UX improvement to make for code intelligence, assigning you to triage

**Comment by lguychard** [comment]
Retagging as "web" since this is UX/UI related and not so much related to the inner workings of code intel.

**Comment by felixfbecker** [comment]
The hover staying open is actually intentional behavior.
One nuance here though seems to be the use of a touchscreen. 
Because we only show the close button on hover, it's _impossible_ to tap on a touch screen.
Imo we should make the close button always show again. This, and the way it makes hover content badges shift on hover, are worse problems imo than #2053, which we would have to trade.

**Comment by fkling** [comment]
We are not showing the popover anymore when going to the definition so that might not be an issue anymore (if it is we can reopen or file a new one).
