### ISSUE TITLE
TestWorkerHandlerNonRetryableFailure emits >7000 log lines in test runs

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#30297]
This is obfuscating test results by making failures difficult to grok, especially because Buildkite truncates our log lines in the web UI where most folks check the results of CI. In two recent cases I had to use `sg ci logs` to find the correct failure:

- https://github.com/sourcegraph/sourcegraph/issues/30115#issuecomment-1020354456
- https://github.com/sourcegraph/sourcegraph/pull/30296

**Comment by efritz** [comment]
The test package actually correctly turns off logging. We're displaying logs because of [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a8bd06f17a678a0a311aff422026c619530e5ded/-/blob/dev/ci/go-test.sh?L32), which enables verbosity for the tests.

Should we have an extra level for this test, or should we not be running verbose in CI?

**Comment by efritz** [comment]
@bobheadxi Is it possible to make a histogram of output per test?

**Comment by bobheadxi** [comment]
I don't think it would be very ergonomic to do in the Loki logs in Grafana Cloud - you might have to write you own script for this. You can use sg ci logs to get the logs for a particular build/job, and it can give you the JSON-formatted logs that are pushed to Loki as well if that helps

**Comment by efritz** [comment]
Ok. If dev-exp notices another dominating logger just let me know and I can track the next ones down until we're reasonable again 😬
