### ISSUE TITLE
Links to documentation for v3.2 are broken due to incorrect version in URL

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#3030]
Links such as: https://docs.sourcegraph.com/@3.2.0/admin/config/site_config result in a 404 due to the version being incorrect.

The URL should be: https://docs.sourcegraph.com/@3.2/admin/config/site_config

**Comment by sqs** [comment]
My change to https://github.com/sourcegraph/docsite/pull/16 unfortunately broke all doc URLs that have a tag. I fixed this manually for `@v3.2.0` links by making a branch at `refs/heads/v3.2.0`. This is a hack.
 https://docs.sourcegraph.com/@v3.2.0/admin/config/site_config

@KattMingMing  to confirm, https://docs.sourcegraph.com/@3.2.0/admin/config/site_config is not expected to work because there is no tag or branch named `3.2.0` (I mean, it'd be nice for those to work, but afaik there are no existing links to that URL). But https://docs.sourcegraph.com/@v3.2.0/admin/config/site_config and `@vN.N.N` in general need to work.

**Comment by ryan-blunden** [comment]
@KattMingMing What page(s) was this link found on?

[Searching across our repositories](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/+"3.2.0"+lang:markdown) didn't yield any links using `3.2.0`.

**Comment by sqs** [comment]
@ryan-blunden I think he meant `@v3.2.0`. 

I will fix this tonight (but the workaround in place should prevent all user-facing 404s in the meantime). As long as we don't release 3.2.1 before my fix is in, we are all good.

**Comment by sqs** [comment]
This was fixed (worked around) by https://github.com/sourcegraph/docsite/pull/17
