### ISSUE TITLE
Use system python for checkcov

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#30355]
Checkcov is our only current python dependent script and installing with asdf is slow and bulky. We should take advantage of the system python for something this simple

**Comment by jhchabran** [comment]
We should document that somewhere, with some explanations about the consequences of having python (the added packages on the image, its size, etc ...)

**Comment by bobheadxi** [comment]
Maybe we should have each CI step explicitly declare what `asdf` dependencies they require? Then instead of doing a broad `asdf install` we can do `asdf install tool1 tool2 ...` - https://github.com/sourcegraph/infrastructure/pull/3071#issuecomment-1024724751

This would cause less confusion in regards to "do I use asdf this? or system this?"
