### ISSUE TITLE
Bump executor to support terraform 1.x

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#30366]
1.0 upgrade for the `demo` instance or another instances that has `executor` (batch change feature?) enabled are blocked by `executor` module itslef.

it has a strict version constraint ">= 0.13.7, < 0.15.0" https://github.com/sourcegraph/terraform-google-executors/blob/master/modules/executors/providers.tf

I don't think we own this module but I can take a quick look see how much work is required to get the executor module compatible with 1.0, but only after the 1.0upgrade is done on other instances.

Part of https://github.com/sourcegraph/sourcegraph/issues/22905

### TODO

- [ ] Upgrade version constraint and validate https://github.com/sourcegraph/terraform-google-executors
- [ ] Update version constraint and validate https://github.com/sourcegraph/terraform-aws-executors

**Comment by kevinwojo** [comment]
@eseliger Do you mind if we bump the executor to Terraform 1.X+? I scanned the file and didn't see anything that stood out as to stay within those version constraints. Did I miss anything?

**Comment by eseliger** [comment]
I think we would need to bump the modules at https://github.com/sourcegraph/terraform-google-executors and https://github.com/sourcegraph/terraform-aws-executors as well, but maybe that's just about as simple. But not sure, maybe terraform is also more lenient when it comes to transitive terraform dependencies from modules? Otherwise, if there's no diff and it works definitely feel free to bump that :)

**Comment by michaellzc** [comment]
@eseliger thank you:) I'll give it a try
