### ISSUE TITLE
Investigate frontend /exec forwarder

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#30475]
We have a `/exec` handler in *frontend* that forwards all traffic to gitserver:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/internal.go?L319

Since this doesn't use our gitserver client it may allow requests that avoid sub-repo checks. 

Ideally we should remove this endpoint and shift anything that uses it to use our gitserver client instead. 

This was spotted as part of https://github.com/sourcegraph/sourcegraph/issues/28532#issuecomment-1026754944

**Comment by mollylogue** [comment]
So, frontend serves an internal git exec endpoint https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/internal.go?L319  the only place this endpoint is currently being called is in the executor, and is always called by an internal actor: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@07f36e14cfed5728e886dea12f87a38546d1f2d0/-/blob/enterprise/cmd/frontend/internal/executorqueue/queuehandler.go?L36 https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/executor/internal/worker/workspace.go?L48 (Context on executors [here](https://docs.sourcegraph.com/admin/executors) )
This internal endpoint in frontend is being served just for the purposes of being used by the executor, since it is outside the cluster and doesn't have access to call gitserver directly. So, removing this endpoint in the frontend would mean we'd have to find a way to expose gitserver, which I'm not sure we want to do.

We can either a) ensure the actor is passed through for these requests, or b) say this executors feature is disabled for sub-repo permissions and not worry about it for now. I'm open to either.

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/30508

**Comment by mollylogue** [comment]
Add header: https://github.com/sourcegraph/sourcegraph/pull/30520

**Comment by jplahn** [comment]
Do we still need to merge #30508?

**Comment by mollylogue** [comment]
So, the main change to add the actor header was already merged, so that PR is just adding some middleware for metrics. It's not super important (which is probably why I totally forgot about it 😬 ) but I'll follow up.
