### ISSUE TITLE
Breadcrumb links in search results not working

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30515]
#### Expected behavior:

Clicking on breadcrumb links from search results will direct users to the repo/sub-directory/file. 

#### Actual behavior:

Breadcrumb links not functioning in most recent version of VSCE.

**Comment by abeatrix** [comment]
Issue fixed in https://github.com/sourcegraph/sourcegraph/pull/30502/commits/dfabbd47de57ca5a47f67765d5d21f1da66f842f

We only generate links when an index number of the search result has been provided. So the breadcrumb links are not working because there is no matchindex number included. Setting matchIndex to `0` for results that do not include matchIndex number has resolved the issue. Detail in https://github.com/sourcegraph/sourcegraph/pull/30502/commits/dfabbd47de57ca5a47f67765d5d21f1da66f842f

**Comment by abeatrix** [comment]
NOTE: Clicking on the repo and file name would both open the file, but not the repo page. We will try to implement that in V2.
