### ISSUE TITLE
Truncate breadcrumb link when link is too long

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30593]
#### Expected behavior:

When the breadcrumb link in a search result is too long, we should indicate on the UI that part of the link is being cut off. The simplest way to implement this is to add an ellipse to indicate that the link is being truncated, and we can show the entirety of the link in a hover tooltip. 

#### Actual behavior:

Currently, the link just cuts off with no indication that it was too long. This is also how it behaves on sourcegraph.com. 

Could our fix for VSCE be shared with search team?

**Comment by abeatrix** [comment]
I have updated the code so that on both vsce and web:
- hovering on the file name would show tooltip with the entire link.
- filename will now show `...` at the end when it's cut off

![Screen Shot 2022-03-21 at 4 10 45 PM](https://user-images.githubusercontent.com/68532117/159377830-ab627e15-a5e5-4c18-b6ed-716899e7a90a.png)
![Screen Shot 2022-03-21 at 4 10 47 PM](https://user-images.githubusercontent.com/68532117/159377840-dd7328ba-7383-4e24-a649-1a03a7c0d962.png)


![image](https://user-images.githubusercontent.com/68532117/159377217-36325db7-7261-4f85-84d1-f79f3242af1c.png)
![image](https://user-images.githubusercontent.com/68532117/159377232-ffea6244-379e-4eb3-81be-b96b1ae273d6.png)
![image](https://user-images.githubusercontent.com/68532117/159377174-f857c213-6a70-4f71-a226-968b8429ca37.png)

@jjinnii Can you let me know if this is what you have in mind?

**Comment by jjinnii** [comment]
@abeatrix Looks great! And this is a change that'll be applied to dot com as well? If so, it's double amazing that work on VSCE is providing improvements to dot com 🎉 

That was exactly what I had in mind with one small nit - can we have the ellipses (...) in link color? It's technically part of the filename that's likable.

**Comment by abeatrix** [comment]
@jjinnii Yes! The changes will be applied directly to dot come and it'd work the same on VSCE once it's merged 😄 
I've updated it so the  ellipses (...) are now in link color:
![image](https://user-images.githubusercontent.com/68532117/159525779-a629a0e5-9c7b-4102-ae61-66d1927e0fe8.png)


![image](https://user-images.githubusercontent.com/68532117/159525449-b02929d6-705c-4979-8997-8900d02c2261.png)

**Comment by abeatrix** [comment]
@jjinnii I just noticed that the ellipses (...)  color are not in link color currently on cloud for commit-matched and repo-matched results ([example search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub.com/sourcegraph/sourcegraph%24+type:diff+after:%22last+week%22+select:commit.diff.added+TODO&patternType=literal)) because the whole title can be truncated, not only specified to the second part (file path for file match results) of the title. In this case, should we update the color of the ellipse back to the original one? 

Currently on Cloud for commit match search result:
![image](https://user-images.githubusercontent.com/68532117/159782487-9f28a99d-f908-4a92-a4c7-cce584a96db8.png)
![image](https://user-images.githubusercontent.com/68532117/159782745-9e7fc1aa-11dd-4d29-947b-65c0c2c56644.png)

**Comment by jjinnii** [comment]
Thanks, @abeatrix! Yes to be consistent, I think we should go back to ellipses being not link-color blue. Good catch, and sorry for the revert!
