### ISSUE TITLE
Expose line/column ranges for compute regexp capture groups

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#30711]
We postprocess search results by running the input regexp pattern over the entire file. When regexp engines return matches, they don't do bookkeeping over line numbers, and that's the case here. We get absolute offsets in the file, and no line/column ranges. There are two resolutions:

- 1. Actually compute logical matches that may span multiple lines in our regexp search backends (searcher and Zoekt). These need to be exposed through a result type that does not break the result into line matches. This is a difficult task, since many parts of our code has come to rely on assuming strictly-line based matches

- 2. Convert offsets to line/columns. This is extra work and needs to be efficient for large data sets (typically chopping the file into a sorted list of lines corresponding to offsets and then doing a binary search on the offsets to resolve lines/columns).

No functionality currently relies on line/column data, but this is going to be a no-brainer once we want to, e.g., link data points or results from compute to ranges in files.

**Comment by Joelkw** [comment]
@rvantonder This might be something you've already considered, but at least for code insights
> No functionality currently relies on line/column data, but this is going to be a no-brainer once we want to, e.g., link data points or results from compute to ranges in files.

I think we can always get away with just the file and the datapoints themselves, if that helps limit the constraint – because as a workaround if we did need to show the full file, I think we can use the existing search UI itself to jump to the right part in the file (e.g., we could link someone to [a screen like this](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/renovatebot/renovate%24+file:%5Elib/manager/terraform/__fixtures__/modules%5C.tf+k8s-cluster/azurerm&patternType=regexp), if we couldn't link them to the line directly in the file.)

**Comment by lguychard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Search-Product-61302e38f801dc0012e2e050/issues/sourcegraph/sourcegraph/30711?planning-poker) with ZenHub @benvenker @camdencheek @fkling @limitedmage @marisak @novoselrok @rvantonder

**Comment by rvantonder** [comment]
Depends on https://github.com/sourcegraph/sourcegraph/issues/31028

**Comment by camdencheek** [comment]
This was done with the implementation of chunk matches
