### ISSUE TITLE
Search by repository description

### ISSUE THREAD

**Issue by GreenFuze** [sourcegraph/sourcegraph#30733]
Is there a way to search by repository description?

**Comment by benvenker** [comment]
@tsenart do we index repo description? Just trying to figure out where this work would potentially fall.

**Comment by tsenart** [comment]
We don't index description in Zoekt, but we have it in the database. This would most likely be a change to `type:repo` searches that would take the [repository description](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/schema.md?subtree=true#table-public-repo) into the searchable corpus rather than only the name.

Thoughts @rvantonder @camdencheek?

**Comment by camdencheek** [comment]
@benvenker We have repo description [in the database](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6ef17f19ee725995952c3b14dcfa799f40a076f9/-/blob/internal/database/schema.md?L2215-2215), which is how we do repo search. 

I expect implementation here would look like:
1) Add an index to the description column
2) Add description filters to the [`RepoListOptions` struct](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6ef17f19ee725995952c3b14dcfa799f40a076f9/-/blob/internal/database/repos.go?L520-520) and update the generated query
3) Update the [`RepoOptions` struct](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6ef17f19ee725995952c3b14dcfa799f40a076f9/-/blob/internal/search/types.go?L255-255) to include description filters that are used to populated `RepoListOptions`
4) Add a predicate `repo:description()` and populate `RepoOptions` with the values from that

Definitely doable. Probably desirable. Also probably a good task for @tbliu98

**Comment by camdencheek** [comment]
Done in #38337
