### ISSUE TITLE
ERPRIVATEREPOPUBLICSOURCEGRAPHCOM

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3077]
This error is logged to the console when going to a repo on a local Bitbucket server instance that is disabled on the configured Sourcegraph instance, but does exist on sourcegraph.com. It is not shown anywhere in the UI, and code intel only shows "Find references" buttons work without telling the user why.

- Why is this thrown if the repo is only disabled (but does exist)?
- Is there a reason why we can't fallback to sourcegraph.com? Is it a privacy concern? It seems like we already check for the presence on sourcegraph.com, which in itself would already be a request to sourcegraph.com that would have the same privacy concern, so that doesn't make sense.
- Errors need to be shown in the UI or this state needs to be communicated. The "view repository" button correctly leads to the repo page (that shows "disabled")
- This error code is long and unreadable, and doesn't follow the convention of the `E` prefix.

@sqs what do you think should be the desired behaviour?

**Comment by sqs** [comment]
In what case would this actually occur (a repo on a local Bitbucket Server instance that is on Sourcegraph.com)? Sourcegraph.com should not really ever have any repos from local Bitbucket Server instances, because by definition those are never publicly accessible (not like how some repos on github.com, gitlab.com, and bitbucket.org are publicly accessible).

In general, we should avoid leaking private repository (and file, etc.) names to Sourcegraph.com.

Regarding fallback to Sourcegraph.com, this is a great feature to have, but it added a ton of complexity in the past. The priority is to make everything work well without fallback first (which means that users would need to switch the Sourcegraph URL back to sourcegraph.com for it to work on public repos that aren't on their own instance). Then once it's working well, we can add fallback and/or an easier way to switch "profiles" in the browser extension (i.e., switching between sourcegraph.com and your internal Sourcegraph instance).

Does this answer your questions?

**Comment by felixfbecker** [comment]
Tbh I don't know if this only occurs if the repo exists on sourcegraph.com. If it it, then we would leak private repo names to sourcegraph.com here. I just repro'd it on gorilla/mux that I pushed to my local instance and thought it has something to do with sourcegraph.com because of the error, but that may as well be a red herring.

I am confused by your statements though - I don't see a way to have a fallback to sourcegraph.com without leaking (potentially) private repo names to sourcegraph.com, because we need to check for the existance of whatever repo/file was requested on sourcegraph.com, which means we would send it to sourcegraph.com, even if it doesn't exist there.

**Comment by sqs** [comment]
@felixfbecker The way we do a fallback to Sourcegraph.com is by checking in the code host DOM to see if the repo is public or private, and only doing the fallback if it's public. (E.g., on GitHub, you can see which repo icon is used in the DOM to tell whether it's public or private, or there are different HTML class names used too.)

**Comment by lguychard** [comment]
> checking in the code host DOM to see if the repo is public or private, and only doing the fallback if it's public

This is correct. Relevant code:
- checking to see if the repo is public or private: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/util/context.tsx#L59-72
- only doing the fallback if the repo is public: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/backend/graphql.tsx#L86-89

**Comment by felixfbecker** [comment]
Did we solve it already, or will it be solved with the resolveFileInfo error handling overhaul?

**Comment by lguychard** [comment]
This is solved, there is no more fallback to sourcegraph.com (#3233) in the case described above.
