### ISSUE TITLE
Auto-indexing for on prem instances Experimental Phase

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30797]
## Problem to solve

Make precise code intelligence easier to set up and enable cross-dependency navigation. 

## Measure of success

~3 customers adopt auto-indexing~
Get customer feedback and signaling around the improvements needed to move into Beta phase.

## Solution summary

Run executors and configure precise code intelligence auto-indexing via SG UI. Covers Go and JVM code and dependencies.

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/537
- https://github.com/sourcegraph/accounts/issues/565
- https://github.com/sourcegraph/accounts/issues/567
- https://github.com/sourcegraph/accounts/issues/547

## Impact on use cases

Onboarding & velocity, fixing vulnerabilities, incident response, code reuse

## Delivery plan
Executors deployment tracker https://github.com/orgs/sourcegraph/projects/232/views/4

**Comment by macraig** [comment]
Updated definition of success to better reflect our criteria to move into Beta phase.

Recent learnings: 
- Managed instances are the best targets at this point as 1) they are customers operating at a scale that benefits from automating LSIF for their repos and 2) we can manage the deployment for them. Large enterprise customers show interest in the feature but struggle with long upgrading cycles and prioritizing deployment within their distributed in different teams (both of these lead to delays in setting up the feature).
- We’re seeing some site administrators not wanting to adopt auto-indexing because it’s still not zero-configuration. [RFC 624](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0/edit?disco=AAAAXDySXZg) directly addresses this pain point and will be included in our Q2 roadmap.

**Comment by jyavorska** [comment]
@macraig now that the last release of Q1 has shipped we should know if this made it or not. Can you please either close it and mark it as done or move it to Q2 or whatever quarter it is targeting now?

**Comment by macraig** [comment]
@jyavorska marking as done!
