### ISSUE TITLE
Server-side batch changes (SSBC) Experimental Phase

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30816]
## Problem to solve

- Run large or resource-intensive Batch Changes, unlocking large enterprise use cases
- Make Batch Changes easier to use and debug
- Allow for a smooth user flow that starts with a search query and ends with a batch change
- Building block for Batch Changes adoption by every developer

## Measure of success

~3 customers create 200+ changesets with server side Batch Changes~

Receive enough feedback to declare this beta

## Solution summary

Run Batch Changes server-side, using executors.

Artifacts:
- PD: 26

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/565
- https://github.com/sourcegraph/accounts/issues/537
- https://github.com/sourcegraph/accounts/issues/580

## Impact on use cases

- Code reuse
- Code health
- Fix vulnerabilities
- Incident response

## Delivery plan

- [#27841](https://github.com/sourcegraph/sourcegraph/issues/30817)
- Executors deployment progress and initial customers https://github.com/orgs/sourcegraph/projects/232/views/4

**Comment by malomarrec** [comment]
🟡 This is at risk. 
Running batch changes server-side is released as an experimental feature, but traction is slow mostly due to external factors (customers moving to managed instances) and targeting large enterprises with very long cycle times.

**Key take-aways:**
- this feature, is critical for very large scale deployments, not so much for smaller scales, which matches our initial assumption
- very large scale deployments come with the usual sales and deployment cycle, which may be very long
- being `Experimental` is good enough for https://github.com/sourcegraph/accounts/issues/565, which was an early proponent of this feature, but not for others
- releasing on managed instances allows us to just turn it on for customers, but we lack the variable billing infrastructure to bill for compute. This is a bit of a chicken and egg problem where we want to validate usage before investing in that heavy billing infra.


**Details**

This feature tends to be useful for the largest enterprise customers, some of which have 12+ months sales cycle, and then take 4+ months to get their Sourcegraph instance setup (https://github.com/sourcegraph/accounts/issues/4778, https://github.com/sourcegraph/accounts/issues/3), so our rollout cycle time matches that very long sales and rollout timescale.

Among our 3 early adopters:
- https://github.com/sourcegraph/accounts/issues/565 has setup executors and is targeting to GA the future internally by end of quarter
- https://github.com/sourcegraph/accounts/issues/537 decided to move to a managed instance, and is still finalizing setup
- https://github.com/sourcegraph/accounts/issues/580 decided to move to a managed instance, and is still in contract negotiations.

In order to attempt and workaround that long installation cycle, we have pivoted to release this experimentally to a few interested customers on managed instances, because we can easily install executors for them and turn them on without going through setup or negotiations. We transparently communicated that we may have to turn the feature off after a while because we do not have the necessary billing infrastructure in place to support managed instances long-term. We are not waiting to see the result of this at:
- https://github.com/sourcegraph/accounts/issues/547
- https://github.com/sourcegraph/accounts/issues/1004
- https://github.com/sourcegraph/accounts/issues/532
but it seems likely we won't reach the 200 changeset mark.

**Comment by malomarrec** [comment]
Given this context, we are revisiting the success criteria. We had less usage and feedback than expected as explained above, but the success criteria was primarily there as a way to measure we were confident enough to move to Beta.

Conversations with customers, and in particular being adopted by https://github.com/sourcegraph/accounts/issues/565, as well as internal testing leads us to be confident that this can move to beta after we build the scope here: https://github.com/sourcegraph/sourcegraph/issues/31105.

I am updating the success criteria accordingly, this means for practical purposes that this is now 🟢 .

**Comment by malomarrec** [comment]
A user at https://github.com/sourcegraph/accounts/issues/565 created a 500+ batch change

**Comment by LawnGnome** [comment]
:shipit:

**Comment by malomarrec** [comment]
🔥 A user at https://github.com/sourcegraph/accounts/issues/1004 successfully created a 328 changeset batch change successfully.

>yes we ran this last week and it worked really well, thanks.
My biggest issue was what seemed to be rate limiting against the github API but I think that was down to the github API token I had configured. I was seeing some GraphQL errors in the sourcegraph webui with not a whole lot of detail.
I ended up retriggering the creation of some of the PRs in sourcegraph as they seemed to get stuck but they did eventually go through.

**Comment by malomarrec** [comment]
A user at https://github.com/sourcegraph/accounts/issues/547 reported a lot of UX issues with server-side batch changes:
https://sourcegraph.productboard.com/insights/notes/assigned-to-me/notes/22747704

**Comment by jyavorska** [comment]
@malomarrec this is listed as in progress but closed, should it be marked as done?

**Comment by malomarrec** [comment]
My bad, I thought there was automation going on. Fixed!
