### ISSUE TITLE
Do not show Bext CTAs to users who have these products installed

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#30842]
Users who already have one of the Bext extensions installed would rather not see the banners for these products.

**Comment by philipp-spiess** [comment]
Since we don't have a lot of repros here I can only assume what's going on. But there's a few things I noticed:

- For some deployments (e.g the `sourcegraph.test:3443` locally) the browser extension does not have access to the origin. When this happens, any of the installation checks _fail_ because there's no way for the BEXT and the browser client to communicate.
- The BEXT check is lazily initiated which means that in React it does not return `true` in the first render passes. I _think_ this is not a big deal since we use `useObserveable` which will cause a re-render when the value initialized but it's still a bad experience nevertheless (right now it's obscured by the fact that search results also take longer to load so by the time we have some results to show, the BEXT check is already done.
- There are multiple procedures to check if a browser extension is installed and the `fetch` one doesn't seem to work at all (I can try to do a `fetch` in the console and it won't work but it also won't show up in the network tab for a page load?). Additionally, it seems like if any of the observables responds with `false` after the other responds with `true`, we'd overwrite it.

Overall the current setup does seem fragile and I’m sure we can do better. My question is if a potential solution could be in alignment with a solution for https://github.com/sourcegraph/sourcegraph/issues/30843

**Comment by vdavid** [comment]
> The BEXT check is lazily initiated [...]

If by "but it's still a bad experience" you mean that the page may flicker: it shouldn't flicker because we never used `!== true` but always `=== false`, so while waiting for the check and the value is `undefined`, the CTAs won't display. ([example](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@vdavid/improve-acquisition-cta/-/blob/client/web/src/repo/actions/InstallIntegrationsAlert.tsx?L58%3A17-58%3A54=))

It's great that you're tackling this btw! I'm sure it can be a lot less fragile, especially considering the magic three second wait that we do now 😅
