### ISSUE TITLE
Address issue with lang:Apex

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#30868]
There is an issue with Apex support that is preventing us from defaulting the feature flag to on. This is a defect linked to https://github.com/sourcegraph/sourcegraph/issues/25262

**Comment by keegancsmith** [comment]
I don't know the actual scope of the work here due to not remembering / the code has been sitting without being used so likely has already had code rot. This is probably something we should do as part of our planned work rather than being part of support. @ggilmore you are support this week, so this might fit in with something you are interested in doing anyways. More zoekt stuff, but contains a component that is sourcegraph/sourcegraph. If I remember the main issue was we hadn't really resolved what to do with ambiguity in language detection.

**Comment by keegancsmith** [comment]
Closing in favour of https://github.com/sourcegraph/sourcegraph/issues/7841
