### ISSUE TITLE
Manage context link does not work for private Sourcegraph instances

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31022]
#### Expected behavior:

Manage context links should work all Sourcegraph instances. 

#### Actual behavior:

In the current version of VSCE, the manage context link only works when it is directed to Sourcegraph Cloud. When a user is authenticated to a private Sourcegraph instance, they receive an error in the contexts dropdown. 

<img width="566" alt="Screen Shot 2022-02-10 at 7 06 07 PM" src="https://user-images.githubusercontent.com/87138876/153517811-49af867c-79d5-42d4-9b1b-01fdf1b61edc.png">

**Comment by abeatrix** [comment]
Received an error saying `Error: Cannot query field "query" on type "SearchContext".`

Looks like query does not exist in older versions in Search Context type, for example [3.34.2](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.34.2/-/blob/cmd/frontend/graphqlbackend/search_contexts.graphql?L92-140) vs [3.36](SearchContext).

Will investigate further

**Comment by northyg** [comment]
@abeatrix and I did some digging around and found that older versions of Sourcegraph are not compatible with the latest version of VSCE because there is a new field `query` that was not in the older versions. 

In other words, when a user has an older Sourcegraph version and is using the latest VSCE, they see `Error occurred while loading search contexts`

In testing, we tried making the `query: String!` field optional by removing the ! [here:](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_contexts.graphql?L122)
Which makes the extension work in both newer and older versions of Sourcegraph, but looked liked we needed to change [the backend code as well.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/search/src/backend.ts?L51)

Unfortunately that caused this other error when creating a search context:

![image](https://user-images.githubusercontent.com/27694443/154562408-d0127ba2-761a-4ed2-91d8-e11cb1253856.png)

We were trying to determine when this new `query` field was added for the search contexts. Is it related to this pr? https://github.com/sourcegraph/sourcegraph/pull/30888

**Comment by abeatrix** [comment]
Due to what Giselle has mentioned above, we have decided not to make direct changes in the shared code base (to remove `query` from the [search backend file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/search/src/backend.ts?L51)) and created a separate file for the `fetchSearchContexts` function for the search box component to use so that it could support displaying search contexts for instances running from version 3.30 to 3.36:
In Version 3.31.2
![image](https://user-images.githubusercontent.com/68532117/154565473-95370776-2681-4c3b-9187-344315c2d05a.png)
in Version 3.34.2 (even though it says 3.36.3 in the image)
![image](https://user-images.githubusercontent.com/68532117/154566039-e32fd816-2e12-480b-8ec4-46855b499b58.png)

For reference, `query` does not exist in type SearchContext for older instances and hence the `Error: Cannot query field "query" on type "SearchContext".` error
![image](https://user-images.githubusercontent.com/68532117/154570818-7acd90c8-0237-4b59-b261-680878ae9c81.png)

**Comment by jjinnii** [comment]
Thank you both! @abeatrix Could you update your [VSCE version support doc](https://docs.google.com/document/d/1ocy4KcY8_U2S0Jl616g96qYZi1-7CMfJ92p56WY_an8/edit#heading=h.sobp48aawhfd) to reflect this? 😄

**Comment by abeatrix** [comment]
@jjinnii For sure! I will update the docs once the PR has been merged!

**Comment by abeatrix** [comment]
Update: Updated the version support docs to reflect the changes

**Comment by abeatrix** [comment]
Released in v2.0.9: https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph
