### ISSUE TITLE
devx: Adopt streaming compatible RPC framework

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#31179]
Our inter-service communication protocols are not standardized. We mostly use bare JSON over HTTP, but also Gob over HTTP (Zoekt) and SSE for streaming searches in Zoekt and Searcher.

Standardizing on an RPC framework like [GRPC](https://grpc.io/) which supports streaming would have some benefits:
- Requires much less manual work to add / remove / update service endpoints in a backwards compatible manner.
- Protobuf encoding is way more performant than JSON, on-par with Gob.
- Less code duplication of API types across service boundaries.

**Comment by tsenart** [comment]
Anything to add @camdencheek?

**Comment by camdencheek** [comment]
Very nice. Excited that this is being looked into

A couple of small things: 
- It would also ease error handling across API boundaries. The manual process of "convert error to JSON encoding, convert it back into an error type that works well with `errors.Is`" is very tedious, error prone (no pun intended), and often broken because it's not well-exercised. 
- This could also help the `go <-> rust` API boundary for `syntect-server`. Well-typed protobuf-encoded requests/responses could make that a nicer experience, especially if we continue down the treesitter path and things get more complicated.

**Comment by bobheadxi** [comment]
@vrto I heard you're interested in driving the discussion here, assigned you for now!

**Comment by jhchabran** [comment]
Cleaning things, since then we moved to GRPC
