### ISSUE TITLE
compute: panic for some regexp queries

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31195]
It is possible to produce a panic from the `compute` resolver with some regexp strings with double slash (`//`):

``` gql
query Run($query: String!) {
    compute(query: $query) {
        __typename
        ... on ComputeMatchContext {
            repository {
                name
                id
            }
            commit
            path
            matches {
                value
                environment {
                    variable
                    value
                }
            }
        }
    }
```
``` json
{
  "query": "patterntype:regexp // (.*?)\\w$ count:all repo:^github\\.com/hashicorp/go-multierror$@9974e9ec57696378079ecc3accd3d6f29401b3a0"
}
```

Result:
``` json
{
  "errors": [
    {
      "message": "panic occurred: unsupported compute result \u003cnil\u003e",
      "path": [
        "compute"
      ]
    }
  ],
  "data": null
}
```

Example trace: https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%226e3d359a6738ddbb%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

Looking through the stack trace, the `MatchOnly.Run` method is getting called with a nil `computeResult`, and therefore [doesn't match](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/compute/match_only_command.go?L86) the `FileMatch` type. This nil response gets passed into `toComputeResultResolver` and results in a [panic](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/cmd/frontend/internal/compute/resolvers/resolvers.go?L167).

**Comment by coury-clark** [comment]
Just noting, the webapp seems to handle a similar search string without escaping the `//`: https://sourcegraph.com/search?q=context:global+lang:go+//%28.*%29%24&patternType=regexp

**Comment by coury-clark** [comment]
@rvantonder It seems like somehow there is still a difference between `//` in compute. The panic issue is resolved, here is what I found:

``` gql
query Run($query: String!) {
    compute(query: $query) {
        __typename
        ... on ComputeMatchContext {
            repository {
                name
                id
            }
            commit
            path
            matches {
                environment {
                    variable
                    value
                }
            }
        }
    }
}
```
``` json
{
  "query": "lang:go patterntype:regexp type:file // (.*)$ count:all repo:^github\\.com/hashicorp/go-multierror index:no"
}
```

This basically returns the same as `(.*)$`, for example matching the first line `package multierror`. When I did into the [trace](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%2277b55b480d3ae728%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) I find that the query actually sent to Searcher is `"query: (?:).*?(?:(.*)$)"`

I thought maybe the index was the problem, but it seems not. I also tried to reproduce using the `regexp` library, and cannot.

``` go
func main() {
	pattern, err := regexp.Compile("// (.*)")
	if err != nil {
		log.Fatal(err)
	}

	input := "// this is a comment string from a code file\n"

	for _, submatches := range pattern.FindAllStringSubmatchIndex(input, -1) {
		log.Println(submatches)
		for i := 1; i < len(submatches); i += 2 {
			start := submatches[i-1]
			end := submatches[i]
			log.Println(input[start:end])
		}
	}
}
```
```
2022/02/17 12:02:55 // this is a comment string from a code file
2022/02/17 12:02:55 this is a comment string from a code file
```

I also wanted to try and repro in the GQL search path, which does not behave this way, and will match lines that start with `//` appropriately.
``` gql
query search {
  search(query:"lang:go patterntype:regexp type:file // (.*)$ count:all repo:^github\\.com/hashicorp/go-multierror index:no") {
    results {
      results {
        ... on FileMatch {
          file {
            name
          }
          lineMatches {
            lineNumber
            preview
          }
        }
      }
    }
  }
}
```

I also found that using a start of line anchor compute starts to behave:

``` json
{
  "query": "lang:go patterntype:regexp type:file ^// (.*)$ count:all repo:^github\\.com/hashicorp/go-multierror index:no"
}
```

In this case, Searcher is sent this: `"query: (?:^//).*?(?:(.*)$)"`

So it seems for some reason the `//` gets lost without an anchor, but only in the compute path.

**Comment by rvantonder** [comment]
What's going on here is that `//` is actually [recognized syntax in our search language](https://docs.sourcegraph.com/code_search/reference/queries#regular-expression-search) for regexp. For example, you can express a regex as `/<regex-pattern>/`. When we see `//`, we interpret it as delimiters for a regex pattern (even if the pattern is empty).

> I also wanted to try and repro in the GQL search path, which does not behave this way, and will match lines that start with // appropriately.

I think this isn't the case. It might look that way if you only glance at the results. Here's a search query with that syntax, that matches many lines that don't start with `//`:

https://sourcegraph.com/search?q=context:global+lang:go+type:file+//+%28.*%29%24+count:all+repo:%5Egithub%5C.com/hashicorp/go-multierror+index:no&patternType=regexp


So there's no difference here in terms of results, `compute` and `search` are behaving the same. That is, search, with this search pattern, will also generate `"query: (?:).*?(?:(.*)$)"`. And search, just like compute, will also "behave" with the start anchor `^` because now this no longer parses as a `/.../` pattern.

Two ways to go about this:

- recognize `//` literally in regex mode, since there's little utility of prepending an empty string pattern
- just be aware and communicate this, but there's no "fix" here in terms of existing behavior because there isn't a difference

In either case: we should probably highlight `/.../` specially in the search bar, so it's obvious this is special syntax.

**Comment by coury-clark** [comment]
@rvantonder ahh thanks for pointing that out

> recognize // literally in regex mode, since there's little utility of prepending an empty string pattern

If that's possible, it makes a lot of sense to me.
