### ISSUE TITLE
insights: templates don't trigger live preview until you open the series box – can we automatically open the series box? 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#31357]
see this loom for the best explanation of this bug: https://www.loom.com/share/fd62aaf7d6344200a57d06671e9a26ef

We should figure out if there's a way to at least not disable the live preview refresh button so I can manually trigger it, even if we can't automatically trigger? Or can we just open the data series entry box automatically so it validates/checks so the live preview runs?

**Comment by vovakulikov** [comment]
@Joelkw It was fixed in this PR https://github.com/sourcegraph/sourcegraph/pull/31271
It was merged yesterday but probably when you were looking at k8s staging it hadn't been merged yet.

I check this problem once again on the k8s just now and it works fine if you open a template with series and fill out repositories field
