### ISSUE TITLE
spike: How does org hard-deletion affect Batch Changes?

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31426]
We want to allow to delete orgs at some point, so we are asked to provide input what it would take to support that from our end.

**Comment by eseliger** [comment]
cc @miveronese

**Comment by chrispine** [comment]
We need to make sure deleting cascades to all BC things.

**Comment by chrispine** [comment]
After this investigation, if further work is needed, we need to get it scheduled to ship in 3.38. [relevant slack thread](https://sourcegraph.slack.com/archives/C07KZF47K/p1645639250760839?thread_ts=1645637198.174329&cid=C07KZF47K)

**Comment by chrispine** [comment]
First task is just to investigate the current behavior, then create another ticket with that information to actually fix it.

**Comment by LawnGnome** [comment]
The deliverable we need in this sprint is basically the answer to these questions, given this setup.

### Setup

1. Stand up a Sourcegraph instance with one or more batch changes owned by an organisation, not a user.
2. Hard delete the organisation.

### Questions

* If the org is deleted, can the batch change still be seen in the main Batch Changes list, and how does it appear?
* What happens if you go to the batch change directly via its URL? Does it render? What "org" does it belong to?
* What state is the `batch_changes` record in within the database? What is the `namespace_org_id` field set to, and how does that correlate to the `orgs` table?

**Comment by BolajiOlajide** [comment]
Observations from this spike is [documented here](https://docs.google.com/document/d/1xsgCRVIjgWz1vbSmHpv_3O2hvAFoxs_LKOCdGI9E_dg/edit?usp=sharing
).

Feel free to share comments on the doc or in this issue.

cc @eseliger @courier-new @adeola-ak @LawnGnome
