### ISSUE TITLE
release: don't send release captains to `index.docker.io`

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31733]
During a release there is output from the release tool that will direct a captain to log in. It will direct them to `index.docker.io`. This is the DNS for images, but is not viable to log in (users will get an error). Instead, we should direct them to `hub.docker.com`

**Comment by bobheadxi** [comment]
This is a string replace here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/src/github.ts?L457=

**Comment by bobheadxi** [comment]
Actually, index.docker.io redirects to hub.docker.com for me. I think this is not really an issue, because we need index.docker.io for the Docker CLI to interpret the credentials correctly

![Image](https://user-images.githubusercontent.com/23356519/174156556-cf616d98-f061-40bc-9c34-1ded15265362.png)
