### ISSUE TITLE
Flaky test: Blob viewer -> extensibility -> properly displays reference panel for URIs with spaces:

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#31806]
Test has recently been re-enabled in https://github.com/sourcegraph/sourcegraph/pull/31689 and has been flaky since.

Failures:

https://buildkite.com/sourcegraph/sourcegraph/builds/133573#30910e67-7003-4e4c-9ac2-fe325e1ada7f
https://buildkite.com/sourcegraph/sourcegraph/builds/133566#b08022bb-7cb3-455a-b1d2-d4ed7be024b6
https://buildkite.com/sourcegraph/sourcegraph/builds/133615#dfb73f98-0dba-46af-9e7e-57f7bb2e0a48
https://buildkite.com/sourcegraph/sourcegraph/builds/133633#b1e29cb3-33f6-4f9d-b930-23dd1c0473b6

<img width="1015" alt="screenshot_2022-02-24_16 54 09@2x" src="https://user-images.githubusercontent.com/1185253/155559472-b79ba529-b3ec-439b-b991-0154065a6f43.png">

**Comment by mrnugget** [comment]
@muratsu @tjkandala I can't find a growth-and-integrations team here in GitHub assignees so I'm assigning to you, feel free to re-assign if you think someone else owns this.

**Comment by muratsu** [comment]
@mrnugget thanks! I've assigned this to the team

**Comment by tjkandala** [comment]
Note for whoever (could be me) tackles this: it looks like this test broke when clicking on a token no longer pinned it but rather jumped to definition. Removing [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/integration/blob-viewer.test.ts?L1057&utm_source=VSCode-2.0.8) could fix, but if pinning is necessary for the hover tooltip to stay rendered then we need to enable pinning for at least this test. I've lost touch with this part of the codebase as code intel now owns the code intel UI, so I don't know how to do this off the top of my head.

**Comment by bobheadxi** [comment]
@tjkandala @muratsu  in the interim, if the fix is non-trivial can the team just put in a PR to disable it, as per our flakey test policy: https://docs.sourcegraph.com/dev/background-information/testing_principles#flaky-tests

This has caused 8 failures on main in the past 2 days: https://sourcegraph.grafana.net/goto/rJ2UWQf7k?orgId=1

<img width="1734" alt="image" src="https://user-images.githubusercontent.com/23356519/155573393-90f3a356-fe60-4bf1-80de-4ac4adbda307.png">
