### ISSUE TITLE
Improve sign-in process for on prem users

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#31804]
Sourcegraph on-prem users that are not familiar with VS Code extension configuration through user settings are often confused by our current sign-in process. We only show an input for an access token, which would be deemed invalid for these users since the default instance URL is sourcegraph.com.

Tailor the sign-in process to be easy for both Cloud and on-prem users.

**Comment by jjinnii** [comment]
@abeatrix @tjkandala  Can't find the thread that we talked about this in 🤔, but I believe the feature request is to add the step of changing the instance URL in the side panel authentication flow itself, instead of private instance users having to go into VS Code settings to change the URL, is that a correct understanding?

If so, is it possible for us to identify from the authentication code, whether a user is a private instance user? It's easy enough to add a second step/input field for changing the URL, but I'd rather not show this step to everyone, just the relevant private instance users.

**Comment by abeatrix** [comment]
@jjinnii 
> is that a correct understanding?

That's correct!

> If so, is it possible for us to identify from the authentication code, whether a user is a private instance user?

We cannot, we can only know if the authentication code works with the sourcegraph URL or not. 
Maybe we can add a small button where clicking on it would display the input field? For example:
Before click:
![image](https://user-images.githubusercontent.com/68532117/156451463-2bc61ef8-042f-4cf0-9f44-6991fdd87f35.png)
After:
![image](https://user-images.githubusercontent.com/68532117/156451816-f0cea700-2ea3-4784-a02b-0ab241259566.png)

**Comment by jjinnii** [comment]
@abeatrix [Designs ready for review in Figma](https://www.figma.com/file/DmiZkq0n6j7A42uKCjNAs2/VSCE-authentication-%26-feedback-flow-improvements?node-id=275%3A1631) Please let me know if you have any questions or concerns!

**Comment by abeatrix** [comment]
PR: https://github.com/sourcegraph/sourcegraph/commit/aba8c98b84ab0f65b38d64ec9a1e6a61fa36859f
![Screen Shot 2022-03-09 at 4 07 23 PM](https://user-images.githubusercontent.com/68532117/157706685-85e270fc-7dd7-405e-8d01-c7e534c6a824.png)

![Screen Shot 2022-03-09 at 4 07 29 PM](https://user-images.githubusercontent.com/68532117/157706710-27c23e5d-fdf8-491a-8160-e430afc506be.png)

![Screen Shot 2022-03-09 at 4 07 31 PM](https://user-images.githubusercontent.com/68532117/157706751-53132eaf-568e-4eda-b98c-2f722220646a.png)
 
![Screen Shot 2022-03-09 at 4 07 34 PM](https://user-images.githubusercontent.com/68532117/157706808-7154d31b-c64c-42d4-94bd-eaabbbf414b4.png)

![Screen Shot 2022-03-09 at 4 26 37 PM](https://user-images.githubusercontent.com/68532117/157706844-6f90e6f0-3028-4aaf-9834-2dd70e74a7e9.png)

**Comment by jjinnii** [comment]
@abeatrix Don't think this is ready for review just yet but couple quick callouts:
- It's "Authenticate account", not Authenticate access 😄 
- In that last screenshot, just confirming that error messages consistently show up above the input fields? I feel like I vaguely recall a conversation where we said that error messages should go below, but maybe I'm making this up. 
- Would love your thoughts on this[ suggestion](https://www.figma.com/file/DmiZkq0n6j7A42uKCjNAs2?node-id=2222:462#162171785) from TJ!

**Comment by abeatrix** [comment]
@jjinnii added my thought on TJ's suggestion.

I have also updated "Authenticate access" to "Authenticate account" and moved the error message below the input fields. I believe you have mentioned it but the changes were not included after the remake.

Here are the updated looks: 
![Screen Shot 2022-03-10 at 3 19 43 PM](https://user-images.githubusercontent.com/68532117/157772931-c0dc246a-81ea-4875-afe3-88df3660d727.png)
![Screen Shot 2022-03-10 at 3 28 45 PM](https://user-images.githubusercontent.com/68532117/157772946-4b36407e-cd5e-4260-b4de-6c67a71b5288.png)
![Screen Shot 2022-03-10 at 3 29 11 PM](https://user-images.githubusercontent.com/68532117/157772955-5e258b4e-0c55-4ed3-be29-5368ed972708.png)

**Comment by jjinnii** [comment]
Mockups updated to reflect "authenticate account" copy for both Cloud and private instance users. A couple of questions on error states: @abeatrix 

- Are we able to identify cases where the access token is correct but maybe there was a misspelling in the Sourcegraph instance URL?
- Are we able to outline the "access token" input field in warning red to indicate that that's the field with errors? 
- Also really sorry, but with the warning message being contained in a box like that, I think it looks nicer above rather than below 😓 Would you mind moving it back to be above the input fields again? 🙇

**Comment by abeatrix** [comment]
@jjinnii Thanks!
![image](https://user-images.githubusercontent.com/68532117/157977581-b8a2da83-d0bc-431f-b115-55a381443eb0.png)
![image](https://user-images.githubusercontent.com/68532117/157979667-10c99144-f1ac-4022-a704-a6a3d1997a34.png)

1. We can enable spellcheck for the field but not sure if that's helpful for users since most of the customers' names are considered mispelt? 
2. We would show error message if the input is not in the correct format (see picture above), would that work?
3. No problem! I have moved it back to above the input fields (it's a easy change so please feel free to let me know if you want to relocate it again)
![Screen Shot 2022-03-11 at 2 09 58 PM](https://user-images.githubusercontent.com/68532117/157978362-c0845be2-aa32-4eba-89fd-8e9c47e0f3f5.png)

**Comment by jjinnii** [comment]
> We can enable spellcheck for the field but not sure if that's helpful for users since most of the customers' names are considered mispelt?

Yes, agreed. Not sure how beneficial this would be as most URL's would come up as typos. 

> We would show error message if the input is not in the correct format (see picture above), would that work?

Yes, thank you! I'm assuming these are VS Code native error messages?

cc: @abeatrix

**Comment by abeatrix** [comment]
Added to the 2.2.0 release: [changelog](https://marketplace.visualstudio.com/items/sourcegraph.sourcegraph/changelog) / [Commit](https://github.com/sourcegraph/sourcegraph/pull/30084/commits/3066356f4f62e8495e4886d390bcc97c0ec649fc)
