### ISSUE TITLE
Helm: add missing `imagePullPolicy`

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#31887]
Some deployment in helm is missing `imagePullPolicy`, for example https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml

I tried using sourcegraph to identify files that don't contain `imagePullPolicy`, but failed https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph-helm%24+type:file+-file:contains%28imagePullPolicy%29&patternType=literal

I guess we don't support such a use case?

**Comment by mucles** [comment]
@michaellzc so from the docs it looks like we kind of support it ... we could do `(image: not imagePullPolicy:) ` like in this example: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph-helm%24+-file:values.yaml+-file:override.yaml+file:.yaml+%28image:+not+imagePullPolicy%29&patternType=regexp

the issue with that approach is that, the `not` operator excludes files rather than matches, so say for example there are multiple images in that file that have missing `imagePullPolicy` but one of those images in that file does have an` imagePullPolicy` that `not` operator will completely exclude that file from the search results 😅 


I went with this approach for finding all instances there are 11 files that don't have an `imagePullPolicy`
 : https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph-helm%24+-file:values.yaml+-file:override.yaml+file:.yaml+image:+or+imagePullPolicy&patternType=regexp

this highlights all .yaml files that contain the keyword `image:` or `imagePullPolicy`. and I just went through all the matches that had a missing `imagePullPolicy`

- [charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml?subtree=true)
- [charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml?subtree=true)
- [charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/redis/redis-store.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/redis/redis-store.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml?subtree=true)
- [charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm/-/blob/charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml?subtree=true)

**Comment by mucles** [comment]
created a PR for this: https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/49/files
