### ISSUE TITLE
Database URI in Migrator Logs

### ISSUE THREAD

**Issue by benjaminwgordon** [sourcegraph/sourcegraph#31960]
- **Sourcegraph version:** 3.37.0 

#### Steps to reproduce:
1.  Configure codeintel and pgsql to target the same database
![Screen Shot 2022-02-28 at 3 57 31 PM](https://user-images.githubusercontent.com/17805669/156065344-c058788d-62f6-43fb-8514-bfdb63d578e6.png)
3. Start Sourcegraph
4. View the Frontend logs

#### Expected behavior:
- Database URI in error message omits or encrypts password
#### Actual behavior:
- Database URI in error message contains external database connection password

```
migrator | error: frontend and codeintel databases must be distinct: postgres://sg:Fake_Password@Fake_Host:5432/sg?sslmode=disable and postgres://sg:Fake_Password@Fake_Host:5432/sg?sslmode=disable seem to refer to the same database
```

Omitting this password would be beneficial for users who would like to export their logs to an external service, to prevent sending unencrypted passwords.

https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1646082479464059

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by virginiaulrich** [comment]
@dan-mckean can you follow-up with Maria on this one, too, since this is likely something for Code Intel since they did the work to create the migrator.

**Comment by dan-mckean** [comment]
Hi @eseliger - the team suggested you might know where this ought to go/live?

**Comment by eseliger** [comment]
I _think_ wrong Erik, but the message is logged here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/postgresdsn/schema.go?L61:75. 
Gitserver already has a URL redactor, https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go?L1924 maybe that could be refactored to be general-purpose and be reused here. Otherwise, it shouldn't be hard to quickly parse the URL, drop the password section and serialize it again. 
cc @efritz

**Comment by efritz** [comment]
![my ears are burning](https://user-images.githubusercontent.com/103087/160488068-34e38265-7614-4eb4-8f33-497eeed4ccbe.png)
