### ISSUE TITLE
Invalid search filters should warn the user

### ISSUE THREAD

**Issue by mpsenn** [sourcegraph/sourcegraph#31995]
#### Feature request description

As a search user, I'd like to be warned when searching using a filter that doesn't exist. I'd still like Sourcegraph to fallback to searching in literal mode (as it does today), but I'd like to know that my invalid filter won't take effect.

#### Is your feature request related to a problem? If so, please describe.

I commonly know my desired filename when searching. So I include the `file:` filter in my searches. However other tools, such as github.com search, name this filter `filename:`. So when using Sourcegraph, I type `filename:banana`, which is an invalid filter. Sourcegraph shows me "No results matched your query" because there are no files containing the literal "filename:banana"

Screenshot, showing an invalid filter, and no results. I'd like this to warn me "there_is_no_such_filter" does not exist.
<img width="1176" alt="Screenshot showing a filter there_is_no_such_filter:banana and no results" src="https://user-images.githubusercontent.com/2200848/156188354-68d844b7-2adc-4a64-915c-3440f8467eac.png">

#### Describe alternatives you've considered.

Alternatively, `file:` and `filename:` could be aliases.

#### Additional context

Opened from an [internal conversation](https://salesforce-external.slack.com/archives/C01P4R0RZH9/p1644591175875189?thread_ts=1644590945.200529&cid=C01P4R0RZH9) with [redacted customer](https://github.com/sourcegraph/accounts/issues/6716).

/cc @sourcegraph/search-platform

**Comment by benvenker** [comment]
@mike-r-mclaughlin my prediction is that @rvantonder will comment that this is trickier than it sounds because a user may want to search for <some string>:<another string> and we'd potentially be showing an error in cases where there wasn't actually one. I wonder if we could put some design effort into this though and do some kind of warning. Maybe a yellow squiggly underline instead of the red we use for errors currently.

@marisak anything come to mind for you from a design perspective? We could do some kind of warning underline with hover text that says something like "it looks like you're trying to use an unsupported filter" or "<somestring>: is not a supported filter".

**Comment by mike-r-mclaughlin** [comment]
Thanks @benvenker: @mpsenn had another good suggestion that would benefit folks coming from GitHub search: could we add an alias for `filename:` => `file:`?  Maybe that should be its own ticket?

**Comment by benvenker** [comment]
@mike-r-mclaughlin hm, I'm not seeing a `filename` filter. They have `path:` which more or less works like our `file:` filter. We've talked in the past about doing something specific with `path` vs. `file` and making that a little more intuitive, which could possibly help here. Basically make `path` be for the file path only and `file` be only filename. Could that help here?

**Comment by mike-r-mclaughlin** [comment]
@benvenker : The suggestion (noted in the description under "Describe alternatives you've considered") was to add a new filter called `filename:` that is simply an alias to `file:` to help folks coming from Github search.   GitHub search has a qualifier named [`filename:`](https://docs.github.com/en/search-github/searching-on-github/searching-code#search-by-filename) that matches a file with the given name.  

If you are new to Sourcegraph (which uses `file:` to search by filename) but familiar with GitHub search (which uses `filename:` to search by filename) you may inadvertently type `filename:<file>`.  In this case, you are presented with a confusing error message (the primary topic of this ticket).  We should improve the error message or add an indicator as you noted.  But, an additional idea from this ticket is to add an alias filter to cover this specific case.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
Hey @mike-r-mclaughlin, creating a filename: alias for the file: search filter should be an easy kill?
Is there a separate issue for that to reference here?

**Comment by camdencheek** [comment]
Recommend closing as won't fix since we have good highlighting for filters that makes it fairly visually obvious that `filename:` is not a recognized filter. We do not plan to change the highlighting or suggestions on the code search team.

I'm forwarding to @sourcegraph/search-platform in case they have differing opinions about the proposed `filename:` alias.

**Comment by keegancsmith** [comment]
Agreed.
