### ISSUE TITLE
Support strato extension with Scala syntax highlighting

### ISSUE THREAD

**Issue by ayroblu** [sourcegraph/sourcegraph#32043]
#### Feature request description

So we have this strato file, which is really similar to scala, would be great to syntax highlight it as scala at least 

#### Is your feature request related to a problem? If so, please describe.

Strato files are just black and white

#### Describe alternatives you've considered.

Fork SourceGraph? Seems not that easy

#### Additional context

cc @olafurpg 
https://twitter.com/olafurpg/status/1498968696542404610

**Comment by olafurpg** [comment]
Thank you for reporting! The easiest fix would be to add a strato->scala mapping in the codebase here (and maybe a few other places, i'm not 100% sure) https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/languages.ts?L394-398

A more flexible and long-term solution would be to implement this functionality here https://github.com/sourcegraph/sourcegraph/issues/237 so that users can configure this mapping without making a changes in the sourcegraph/sourcegraph codebase.

The best solution would be to have dedicated ctags and syntax highlighting support for strato instead of piggy backing on the scala syntax :) 

I've added this issue for our team's next iteration

**Comment by ayroblu** [comment]
Thanks! We already have an lsif implementation, so we'll be using that, + we already have syntax highlighting for intellij + vscode, so it shouldn't be too difficult to port once needed. Ideally we could do it independently!

**Comment by tjdevries** [comment]
This can now be configured via syntaxHighlighting in the site configuration.

More information can be found here: https://docs.sourcegraph.com/dev/how-to/add_support_for_a_language#customizing-syntax-highlight-language

I'm happy to answer any questions about the feature!
