### ISSUE TITLE
Add a request for feedback in the current IntelliJ extension

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#32064]
This would be a great way to recruit users for feedback for validating the approach of the improved extension. It'd be great if this was semi-automated, as an example a a popup / toast would appear after interacting with the extension for random users etc.

**Comment by vdavid** [comment]
Wow, great idea! Could you sketch up some designs for this @jjinnii? I'm happy to help with it.

**Comment by vdavid** [comment]
I guess it could be aa simple as a link to a 1-2 question long Google Forms survey?

**Comment by jjinnii** [comment]
Yes thanks @vdavid , should have tagged as needing design support. In terms of what we _can_ do in JetBrains, both technically and with low effort. 

Are we able to utilize the JetBrains native notifications (like we discussed [here](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=1461%3A5052)) as a one-time show to users for feedback? 

If the answer is yes, my second question would be- how much control do we have over this component?[ VS Code](https://code.visualstudio.com/api/references/extension-guidelines#notification-examples) has a pretty strict "header", "text" and "buttons" layout for this component.

**Comment by vdavid** [comment]
@jjinnii they'll look like [this](https://jetbrains.design/intellij/controls/notifications/#:~:text=All%20but%20file%20tabs%20or%20tool%20windows). They have these options:
 - title
 - content text
 - link label

I hope this helps. :)

**Comment by jjinnii** [comment]
Thanks @vdavid ! 

The "easiest" route would be if we could somehow embed our existing [NPS survey](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=2405%3A35629) into JetBrains as is. It seems from @ryankscott's [message in Slack](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1647251035243609?thread_ts=1647026947.469529&cid=C01T0BL4EFN), Hubspot will let us extend into JetBrains, but I don't know how much freedom we'll have over UI formatting. 

I guess the question is to what extent we can utilize our Hubspot survey for a JetBrains survey? Is that something you're able to look into, or is that something someone who has more familiarity with Hubspot be better able to handle?

**Comment by ryankscott** [comment]
I took a quick look at HubSpot again, the current NPS form is generic to our product, not specific to the IDE (see screenshot). 

It does look like there's an option to not embed this as an iframe and [instead as raw HTML, where you can style it](https://knowledge.hubspot.com/forms/how-can-i-share-a-hubspot-form-if-im-using-an-external-site). However, we'd have to create a separate form, which I think is OK.

The upside of using HubSpot is not having to deal with collecting results etc. It might make sense to try and spike this up and see what we can achieve.



<img width="839" alt="Screen Shot 2022-03-15 at 09 37 55" src="https://user-images.githubusercontent.com/2660760/158338373-fe427860-e335-4509-b576-4b8b6d6a6bc3.png">

**Comment by jjinnii** [comment]
Thanks for looking into this @ryankscott! Agreed that not having to collect results (with google survey, it'd be tied to an individual's email) is a huge plus. And I believe it'd auto-send over to the #feedback channel which is also beneficial. 

@vdavid is it possible for us to embed this as raw HTML? Based on your last messages, it seems as if that notification area is pretty restricted to header/text/buttons (I don't see any input fields in the example you've sent over).
If it isn't possible, our only option would be to re-direct users outside of Jetbrains to fill out the survey from the notification.

**Comment by vdavid** [comment]
_Finally_, a great source for what can be done in notifications: https://www.plugin-dev.com/intellij-notifications.pdf (page 6) – it seems that the content supports HTML, so I'll try to add the form in there.

**Comment by vdavid** [comment]
Got it working! :) <img width="1512" alt="image" src="https://user-images.githubusercontent.com/2552265/160154762-741d233f-b0d8-4fb9-b984-fbaef4336a45.png">
I've requested access to HubSpot to get the HTML source, then I'll try to set up the form including the submission feature.

**Comment by jjinnii** [comment]
Yay! @vdavid  lmk if you need design guidance on this!

**Comment by vdavid** [comment]
By the way, [our form](https://app.hubspot.com/forms/2762526/a86bbac5-576d-4ca0-86c1-0c60837c3eab/performance) doesn't render the NPS score (1–10) selector (see the [rendered version](https://share.hsforms.com/1qGu6xVdtTKCGwQxgg3w-qw1n7ku)) and nor does [Ryan's copy of it](https://app.hubspot.com/forms/2762526/71272e84-beff-48ab-b420-db35675e2fca/performance). I'm not sure if we're using these somewhere right now, but if we are, I think they are broken.

**Comment by philipp-spiess** [comment]
I have another idea, one that mixes all options a bit: Instead of showing the full NPS form (which contains more than one field and requires text input -- a big commitment!) we only show the 1-10 selector inside the notification. When people select an option, we open a browser window with the NPS form, fill in the rating, and add the option to fill out the email adress + optional additional feedback and send the form. 

This might not be possible directly via a HubSpot link (I don't know if you can set defaults via the URL?) but we could either:

- Have a form on our website where we can prefill form fields (I've added an API for that for the teams signup page)
- Fork the form into 10 different forms for all 10 different options. A bit messy but it would also work.

**Comment by jjinnii** [comment]
Thanks both! @philipp-spiess Is [this](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=1492%3A6285) what you had in mind for your mixed option? I think it's a great alternative because I agree that trying to have a full form in a pop up notification will likely get very poor response rates. However, while people may be inclined to click an easy 1-10 selector, jarringly redirecting them outside of their IDE will probably not encourage any users to fill out a form from there. 😆 I see two potential options here: 

1. Have @vdavid continue exploration for having a full NPS form in JetBrains. 

1.5 Maybe we discard hopes of having users fill out text questions. Only include the 1-10 rating and a "can we contact you" question in JetBrains.

2. Explore @philipp-spiess 's suggestion of redirecting users to a URL after clicking on a 1-10 rating scale

@ryankscott If the goal is to scout users for testing/validation of the new extension (_not_ gathering feedback with the existing extension), then maybe option 1.5 might have the best option/lowest effort/best response rate combo?

To @vdavid 's secondary question about where to collect responses to the survey, I'm passing the baton to @ryankscott for that one 😄

**Comment by ryankscott** [comment]
There are two major goals here:
1. Measure the satisfaction before and after we ship the new JetBrains plugin
2. Get some users for continual feedback as we build

I think 1.5 sounds like a good approach which balances the goals. A 1-10 NPS score and a checkbox "Can we contact you about your feedback?" and an input for an email address.

From what I understand we can't use Hubspot here? How about Google forms?

**Comment by philipp-spiess** [comment]
> Is [this](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=1492%3A6285) what you had in mind for your mixed option?

YES! I love it :D 

> 1.5 Maybe we discard hopes of having users fill out text questions. Only include the 1-10 rating and a "can we contact you" question in JetBrains.

To be fair, most of the NPS messages in the #feedback channel also only consist of the rating + the email address so this sounds good to me! Does anyone know where we store these NPS results? Is this HubSpot?

![image](https://user-images.githubusercontent.com/458591/160795413-d284d500-58e2-441c-80ae-10e52e22b53a.png)

**Comment by philipp-spiess** [comment]
> Does anyone know where we store these NPS results?

If I'm not mistaken it seems that we have a GraphQL API for this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/hooks/useHandleSubmitFeedback.ts?L17:14

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/survey_response.go?L147-149

**Comment by philipp-spiess** [comment]
(I'm spamming now, sorry!)

It seems like we can relay the data from our GraphQL API directly into HubSpot: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/survey_response.go?L173-183

**Comment by vdavid** [comment]
Hmm, that sounds like a great starting point! Thanks, @philipp-spiess!
I can't use the existing endpoint, though. I'll need to create a new one because there are some differences in our needs:
 - The code expects a score between 1–4 ([see the code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/survey_response.go?L152%3A25=)), while we need NPS.
 - It references one specific HubSpot form, and the analytics for that probably are already wired up to deal with the 1–4 score system and the other fields in the form. I'd need to wire up my endpoint with a different form.
 - I don't think I can make graphql calls from a standard HTML form without JS. (I searched for it, found no solutions.) I'll need an endpoint that receives the output of a standard HTML form.

Thanks for clarifying our goals, @ryankscott (satisfaction before vs. after + users to reach out to for feedback)! That was unclear to me, and it helped me see the big picture.

**Comment by philipp-spiess** [comment]
> * I don't think I can make graphql calls from a standard HTML form without JS. (I searched for it, found no solutions.) I'll need an endpoint that receives the output of a standard HTML form.

Ahh, right, I did not think about this. Yeah this will then need a different kind of endpoint. Maybe a page on the dotcom or about site like (about.)sourcegraph.com/jetbrains/feedback. We can at least control some of the UI then and it won't look so generic.

**Comment by vdavid** [comment]
The tasks I'm seeing, for the record:

- [ ] Create front end, see if it can look nice
- [ ] Create Go backend that can receive the form data and handle it
- [ ] Look into where to store the new submission data
- [ ] Create HubSpot form to receive the data
- [ ] Wire up the back end with the HubSpot form

**Comment by vdavid** [comment]
I investigated this yesterday, and unfortunately, our options are very limited for the styling in the notification boxes. This is the best I could achieve with a test form:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/2552265/161238858-62d48381-ce67-457f-b634-f395971d8d38.png">

I see two options:
1. We accept that it's ugly and go with a design like this. We can also list the 0–10 options in separate lines, which might make them look slightly better. I can wire this up with our back end and with HubSpot.
2. We just provide a link to the HubSpot form, and do our best to convince them with a nice copy to click the link.

What do you all think?

**Comment by vdavid** [comment]
I haven't seen any examples where they used images in notifications. Even <style> tags and <script>s are not being parsed.
I suppose they designed this area to be text-only, but people needed some styling, so they went with some minimalistic HTML rendering, maybe with a custom HTML parser. They seem to support only a small subset of HTML. It's difficult to know because the whole thing is undocumented. I've discovered all of this with some helpful third-party articles plus much trial-and-error.

**Comment by ryankscott** [comment]
Ok my last alternative would be to create links behind emoji, something like:
`<a href="https://sourcegraph.com/api/jetbrains/recommend">👍</a>`
That _should_ be supported given it's plain text in an anchor tag. Then we can just look at % of people that recommend.

However, this is quickly moving towards too hard territory if this doesn't work.

**Comment by vdavid** [comment]
Hmm, and what would be at `https://sourcegraph.com/api/jetbrains/recommend`?
If just a "thank you" page, then we won't have the two things we want:
1. The satisfaction level (ratio of people who like the plugin vs who don't) which we'd like to see the trends for as we roll out new features
2. A contact for the people who like our stuff, to ask for deeper feedback.

If a page where they can give more feedback then wit would not be representative because only the people who gave a 👍 would get to the page.

How about we just go with the HubSpot link then?

**Comment by muratsu** [comment]
> Haha, @jjinnii I bet my screenshot scared you 😄 My answer is "it depends".
> 
> Here is my update on my progress with the in-notification NPS survey. In a nutshell, it's complicated.
> 
> * HubSpot’s solution for embedding a form is not an HTML snippet but a <script> tag. This snippet renders the HTML form. I’ve tried to embed this <script> in IntelliJ, but it didn’t work. I suspect that the HTML that is rendered in notifications is not allowed to run scripts.
> * I've reached out to HubSpot to ask if they support if they have an HTML version. They said no.
> * I've tried to get the script to render the HTML locally and "steal" the raw HTML, to see if it works. It didn't work without the scripts, unfortunately.
> * I set up a custom HTML form with a submit button and wired it up with a [test API](https://beeceptor.com/console/david). That worked. So forms _can_ be used, but not with HubSpot. Our options are limited, though. We can run no client-side validation because we can't run scripts, and our styling options are also very limited: only inline styles, with a limited feature set (e.g. I couldn't change the text color inside an  field, but I could change label text colors.)
> 
> So, I'm seeing three options:
> 
> 1. We try to work with HubSpot to somehow resolve this with them. I suggest doing this only if it's very important for us for the results to arrive in HubSpot.
> 2. We set up a custom backend somewhere where a custom form will send NPS data (1–10) and the same three questions that we have in HubSpot. This will be a custom solution, so it'll need a bit of development to send this data to some DB, or, Slack, etc. I suggest doing this if we want to minimize friction.
> 3. We just link the form (https://share.hsforms.com/1cScuhL7_SKu0INs1Z14vyg1n7ku) in the notification. This will cause some friction, but it'll render nicely and it'll work out of the box.

seems like the 3rd option with a styled popover (like the one below) would be the fastest and the most robust solution. I agree that having the full form rendered inside the IDE looks nicer (and potentially has a higher completion rate) but the platform seems to be limited and I would love us to ship this.

![image](https://user-images.githubusercontent.com/1308560/161621398-80c5ed07-6283-4f23-a069-7b4e6c0022ab.png)

**Comment by vdavid** [comment]
I agree. I'll go with that tomorrow.

**Comment by vdavid** [comment]
@jjinnii or @ryankscott do you have a copy in mind for the NPS notification? It'll just contain a link to our [existing NPS survey](https://app.hubspot.com/forms/2762526/a86bbac5-576d-4ca0-86c1-0c60837c3eab/performance), and will pop up a few seconds after someone used a Sourcegraph feature (but not too often, and not after they've clicked on the link). It'll also need a label for a "Don't show this again" button.
I can write the copy myself that follows our [content guidelines](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/), just wanted to ask if any of you'd prefer to write it as I'm not native English.

**Comment by vdavid** [comment]
I did the development today (a tiny part is missing), but then we agreed with @ryankscott that this feature wouldn't give us much value as we have very few users for the plugin.
I'm saving the branch with today's changes. If we need this later, it'll be quick to enable these notifications.
I'm closing this issue for now.
