### ISSUE TITLE
Browser extension: No hover tooltips on GitHub PRs after switching tabs

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#3228]
- Visit https://github.com/gorilla/mux/pull/457
- Then click on "Files" to go to the diff view
- Hover over `Route` on line 289 at the top
- Notice the token becomes highlighted, but the hover tooltip doesn't show up

![2019-04-08 17 58 45](https://user-images.githubusercontent.com/1387653/55766150-26f08780-5a28-11e9-9ce2-b25415538f0e.gif)

**Comment by KattMingMing** [comment]
After refreshing the background page of the browser extension and refreshing the GitHub PR page I was able to get tooltips to show. There was no hover tooltip or any other indications that code intel was working until I did this – I also added and removed the extension.

**Comment by felixfbecker** [comment]
Interesting. Were there any errors in the console or background page console?

**Comment by chrismwendt** [comment]
I'm unable to repro (browser extension v19.4.8.1301) at https://github.com/sourcegraph/sourcegraph/pull/3227/files#diff-a98755ff0b47687b4ea8b2cc6294950eR209

**Comment by chrismwendt** [comment]
I found a repro. I added repro steps to the description + a GIF showing the bug.

**Comment by felixfbecker** [comment]
Thanks for the repro @chrismwendt! This only happens after switching tabs. The hover overlay mount, which is appended to the `#js-repo-pjax-container`, gets removed and not readded. I guess this is because GitHub swaps out the content of `#js-repo-pjax-container`, but will never remove/add `#js-repo-pjax-container` itself, so we don't add the mount again. I don't actually know why we don't just put the mount on  `document.body`, I think this was a hacky attempt to make hover overlays disappear on page navigation, but I have since added proper handling for that. Using `document.body` fixes the issue.
