### ISSUE TITLE
gitserver janitor: get total repo size from the database

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#32482]
Since https://github.com/sourcegraph/sourcegraph/issues/32197, gitserver calculates repo size on every repository clone / update and stores that in the `gitserver_repos` table.

However, the gitserver janitor also calculates the directory size of all repositories periodically. It should instead get that info directly from the database.

⚠️ The site-admin "bytes stored" info will display the wrong number until all repos have been updated at least once, which should take up to 8 hours by default.
<img width="479" alt="Screenshot 2022-03-10 175059" src="https://user-images.githubusercontent.com/2102036/157675690-b4ede9bf-5ee8-4301-8726-6d286bde4a02.png">

@virginiaulrich This means that after the next release, customers will see this number go from 0 to the actual number of bytes for the first 8 hours after deployment. Is this acceptable?

**Comment by virginiaulrich** [comment]
Thanks for letting me know!

It looks like the long term benefits are worth this. And now it's just about how we keep folks informed / what to do next. 

Will an admin even notice this UNLESS they happen to be in there? Or will there be some sort of other indicator that may make them think something is wrong? 

If we think they will notice, then I think I want us to proactively alert our admins. Otherwise, I just want to be sure that our support team is aware so that if customers ask, they are in the know.

Can we mention this in the change log for the relevant release? That will help A LOT, too.

**Comment by asdine** [comment]
@virginiaulrich Thanks for your answer, it gives us more insight in how to deal with this.
FYI we are going to take another route where we will actually make sure the data is migrated properly _before_ switching to the new system, that way there won't be any impact on the UI.
