### ISSUE TITLE
TypeScript code intel: hovers take successively longer to show up

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#3265]
- Visit https://sourcegraph.com/github.com/sourcegraph/codeintellify@02c7f13bdb5981e41ec06266b03cff6ab0b01e47/-/blob/src/index.ts
- Hover over `HoverOverlayProps` repeatedly

Notice that it takes longer and longer for the hover to appear. I would expect it to take the same amount of time. I'm not sure what's going on here.

This GIF ends at 2m15s on the stopwatch

![2019-04-05 17 11 10](https://user-images.githubusercontent.com/1387653/55662253-8fd8c500-57c6-11e9-9e5f-ffd949d0472c.gif)

It appears to take 1s longer on each hover. I wonder if the polling has anything to do with this.

I haven't noticed this on other files or tokens.

**Comment by felixfbecker** [comment]
Interesting find. Assuming this is an issue with the TypeScript langserver, I won't have time to investigate though as I need to focus on the browser extension. I'm happy to help though if you want to investigate it.

**Comment by chrismwendt** [comment]
Ok, I'll assign myself for now. I might investigate this in the next week and I'll reach out if I could use some help, thanks for offering!

**Comment by felixfbecker** [comment]
What I find interesting is that this _only_ happens when rehovering the _same_ token. If do a ping-pong hover with different tokens, they always show up instantly. 

![2019-04-09 14 30 08](https://user-images.githubusercontent.com/10532611/55800545-40e7a400-5ad4-11e9-861d-c02b6d5af8eb.gif)

If you are right and this is because of the polling, this could be a bug in `abortPrevious()`:

https://github.com/sourcegraph/sourcegraph-typescript/blob/e2a2c0fb17d372033bbd6e6dd906ea482deb325f/extension/src/util.ts#L62-L87

**Comment by felixfbecker** [comment]
Another idea: This could be because of `distinctUntilChanged()`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph-typescript@e2a2c0fb17d372033bbd6e6dd906ea482deb325f/-/blob/extension/src/extension.ts#L510-512

When the same token is hovered, the params are equal, so the previous Subscribable is returned and resubscribed to again and the provider run again, but the other Subscribable might not be unsubscribed from.

**Comment by efritz** [comment]
We're no longer putting effort into langserver support.
