### ISSUE TITLE
Search query `timeout` not always honored (just Zoekt?)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#32757]
Some observation about how search behaves around `timeout` and timing out:

- [`repo:^github\.com/sourcegraph/sourcegraph$ a timeout:2s`](https://sourcegraph.com/search?q=context:%40sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+a+timeout:2s&patternType=literal) doesn't time out at 2 seconds, it runs for 8 to 12 seconds. `timeout` seems to have no effect.

- [`repo:^github\.com/sourcegraph/sourcegraph$ a timeout:2s index:no`](https://sourcegraph.com/search?q=context:%40sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+a+timeout:2s+index:no&patternType=literal) with `index:no` does stop sending results before `timeout`, which suggests we are cancelling searcher by respecting timeout. We only know this because @camdencheek looked at traces and noticed that the Zoekt side wasn't getting cancelled

My observations running search via compute is the same: adding `index:no` honors timeout but not otherwise. The compute endpoint would also stream indefinitely without any default cancellation (which suggests that Zoekt is not getting cancelled ever, until the connection is forcibly closed or we hit the max display count). Currently compute does not use the display count to stop anything, so it relies on max timeout logic in our search to stop for long running queries, and basically I haven't ever seen it stop, even for 5min+ running queries :-) 

Related: I've now clamped compute running time by max 1 minute: https://github.com/sourcegraph/sourcegraph/pull/32756

**Comment by keegancsmith** [comment]
Do we have an example query which is more realistic on what a user wants? Asking for all results with a common term is a lot of work. The overhead of ranking/sorting + network is the reason for the delay after the timeout.

TBH we intentionally implemented a non-hard cutoff back in the day, but that was due to us doing normal RPCs. Now that we are streaming, we likely can switch to a hard cutoff. @stefanhengl what do you think?

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.

**Comment by camdencheek** [comment]
FWIW, I think this issue is still relevant. I _think_ it's just that Zoekt does some heavy computation loops that don't check the context. Since we've started relying more on query cancellation for things like hover preloads and limits, I think this is actually more relevant than ever if we can't depend on fast cancellation actually making the query cheap.
