### ISSUE TITLE
Investigate whether Prometheus can default to RoleBinding

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#32777]
In the helm chart Prometheus defaults to creating a [ClusterRole](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/prometheus/prometheus.ClusterRole.yaml) with a hardcoded name. Is there any reason this can't be a RoleBinding instead?

Additionally, we may want to allow disabling role and rolebinding creation entirely. Right now we only have the option to fall back to rolebinding the `view` ClusterRole.

**Comment by caugustus-sourcegraph** [comment]
Related: https://github.com/sourcegraph/customer/issues/773

**Comment by michaellzc** [comment]
Depending on how we define "privileged", I assume the creation of all RBAC-related resources are privileged (CR, CRB, R, and RB). Maybe I am wrong? I was never an extensive RBAC user, admin at the time LOL.

I want to propose a breaking change.

`.<serviceName>.privilged=true` should disable the creation of all RBAC-related resources not just create RB and reuse an existing CR.

Instead, we can create a separate chart, `sourcegraph-rbac` for customers with tighter security requirements where people who run sourcegraph are not the same as people managing roles.

the `sourcegraph-rbac` chart can create necessary RBAC resources with different configuration options where customers can just hand it over to the proper internal team to apply.

Is this a valid use case?

**Comment by caugustus-sourcegraph** [comment]
@michaellzc - I think we can keep the existing `privileged` flag as-is, but add another one that can disable all role creation. Your chart idea sounds ok, not necessarily required for GA but at least one customer does run role creation as a separate step so we know it can be useful.

I'd still like us to investigate whether Prometheus can run without a ClusterRole / ClusterRoleBinding by default. I suspect we copied those permissions over from the official chart, which assumes Prometheus will be monitoring an entire cluster. Since we only run within a namespace it may no longer be required to run with Cluster-level permissions.

**Comment by michaellzc** [comment]
I don't think we can get away with the current `prometheus` ClusterRole.

Our prometheus is configure to discover cluster-scoped resources, e.g. [node](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/prometheus/prometheus.ConfigMap.yaml#L104).

Additionally, when using the `view` CR, `prometheus` is unable to scrape cadvisor metrics, hence all provisioning metrics are broken.

**Comment by michaellzc** [comment]
> but add another one that can disable all role creation

Given the `view` CR is not enough to get our grafana dashboard working properly (lack of permission for prometheus to scrape advisor metrics), is there any good reason to still create the RoleBinding with `view` CR when `prometheus.privileged=false`? Unless we're fine with the grafana dashboard is left at a half-working state where provisioning metrics are missing (maybe there're more metrics that are missing because I didn't do a really throughout check)

## Option 1 - we still create the `view` RB when `prometheus.privileged=false`

In the event users lack cluster-admin role or they have deploy `prometheus` prior installing sourcegraph on the cluster, these users will have a smoother experience, but grafana dashboard is missing provisioning metrics. This may not be a good idea since some of our troubleshooting steps do require users to provide such data. My concern is we don't have a good way to communicate with user that you still need to manually create the proper CRB to make things work.

## Option 2 - we do not create any RBAC resources when `prometheus.privileged=false`

This requires an extra manual step that users have to perform. Same as option 1 - manually create the proper CRB to

**Comment by caugustus-sourcegraph** [comment]
@michaellzc - the current behavior with `privileged` mostly matches our existing [non-privileged kustomize overlay](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/overlays/non-privileged/prometheus/prometheus.ConfigMap.yaml) (although it looks like there are some discrepancies that need to be investigated further). While provisioning metrics aren't available, application-level metrics are, and that's better than not having any data at all.

We could consider outputting a warning in the helm notes when that flag is set, to let users know it will impact monitoring.

**Comment by michaellzc** [comment]
I like the helm notes idea! Let's keep the current behaviour

action items:
- https://github.com/sourcegraph/sourcegraph/issues/32852
- https://github.com/sourcegraph/sourcegraph/issues/32853

**Comment by michaellzc** [comment]
Close in favour of follow-up issues
