### ISSUE TITLE
Setup k8.sgdev with the recommended Batch Changes configuration

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#32897]
k8.sgdev is not configured optimally, which creates issues for Sourcegraph teamates that use it (for example https://github.com/sourcegraph/sourcegraph/issues/21186#issuecomment-1075259645).

Although there are long term improvements we can make to setup and configuration ( #21186, #25394), we can improve this now with minimal efforts by making sure k8 is setup optimally:

- setup a broad permission [global service account token](https://docs.sourcegraph.com/batch_changes/how-tos/configuring_credentials#global-service-account-tokens) for GitHub and GitLab
- setup webhooks

**Comment by BolajiOlajide** [comment]
### Questions / Observations from @adeola-ak & I

- What permissions are required for a `Global Service Account` token?

- All codehosts did not have a global service token configured  - whose account is meant to provide this token (ideally)?
![Screenshot 2022-04-06 at 16 35 32](https://user-images.githubusercontent.com/25608335/162012825-d70049dd-b350-4c4b-9650-b3193430154c.png)

- UX Improvement: We believe the scopes required for the global service account token should be shown either in the docs or in the page that the codehosts status is displayed. Admins will ideally click the `Add credentials` button when they already have a token so it's a bit late to show the scope there. @danielmarquespt what are your thoughts?

![Screenshot 2022-04-06 at 16 41 45](https://user-images.githubusercontent.com/25608335/162014038-f59f9076-2e1c-44f5-b5d3-18ddd1100af0.png)

![Screenshot 2022-04-06 at 16 42 04](https://user-images.githubusercontent.com/25608335/162014098-ee439194-f4c5-4161-ac61-565bd09e84cd.png)

- We were confused about what to do to setup webhooks for codehost repository updates.

- We tried setting up webhooks using [this guide](https://docs.sourcegraph.com/admin/repo/webhooks), we generated a token at `https://k8s.sgdev.org/users/bolaji.olajide/settings/tokens`, however when the token is used we get an error.

<img width="1263" alt="Screenshot 2022-04-06 at 20 14 41" src="https://user-images.githubusercontent.com/25608335/162051376-6d464047-b766-4b94-942d-3fb1e8e73580.png">

The variables used are listed below:

1. `REPO_NAME`: bitbucket.sgdev.org/SOUR/vegeta
2.`SOURCEGRAPH_ORIGIN`: https://k8s.sgdev.org
3. `REPO_NAME`: tbucket.sgdev.org/SOUR/vegeta

cc @courier-new @LawnGnome @eseliger

**Comment by courier-new** [comment]
> What permissions are required for a Global Service Account token?

The same permissions as a normal personal access token. These will vary per code host, but are enumerated in the section that describes [how to create a new token for each code host](https://docs.sourcegraph.com/batch_changes/how-tos/configuring_credentials#creating-a-code-host-token).

> All codehosts did not have a global service token configured - whose account is meant to provide this token (ideally)?

I think that for us it'd probably be an admin account on each of these code hosts, since that would presumably have read/write access to all the repositories there where we might be creating changesets. I think there should be admin credentials for each code host in 1Password.

> UX Improvement: We believe the scopes required for the global service account token should be shown either in the docs or in the page that the codehosts status is displayed. Admins will ideally click the Add credentials button when they already have a token so it's a bit late to show the scope there.

The scopes are shown in the docs if you follow the link from "4. Click Add credentials and follow the steps to [create a new token](https://docs.sourcegraph.com/batch_changes/how-tos/configuring_credentials#creating-a-code-host-token)"! 🙂 However I agree it'd be a super cool enhancement to also show them here.

> We tried setting up webhooks using [this guide](https://docs.sourcegraph.com/admin/repo/webhooks), we generated a token at https://k8s.sgdev.org/users/bolaji.olajide/settings/tokens, however when the token is used we get an error.

Hmm, you know that's a perfectly reasonable place to look for a guide for this, yet that is unfortunately not the right one. 😅 I'm not too concerned about this for a real site admin because I think they'd either come across this doc when they're setting up Batch Changes for the first time or else be directed to it by our [in-app banner](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/batches/detail/WebhookAlert.tsx?L66%3A29-67%3A37=), but the actual guide is Step 4 of [this page](https://docs.sourcegraph.com/batch_changes/how-tos/site_admin_configuration).

**Comment by danielmarquespt** [comment]
> UX Improvement: We believe the scopes required for the global service account token should be shown either in the docs or in the page that the codehosts status is displayed. Admins will ideally click the Add credentials button when they already have a token so it's a bit late to show the scope there. @danielmarquespt what are your thoughts?

Since the scopes are in the documentation I think we can leave this as is for now. I don't think it is a big UX issue to only describe the tokens in the modal. Besides, moving forward as we support more code hosts, there's going to be code-hosts on the list that most of our customers won't ever end up using, so crowding the list with those specific details might not be the best option.

All in all, we can indeed improve this experience but as of now there are more important things and this is not a big UX issue IMO.

**Comment by BolajiOlajide** [comment]
Thanks for the clarification @courier-new @danielmarquespt .

**Comment by BolajiOlajide** [comment]
@adeola-ak & I have completed this.

We've added a global service account token for the following code hosts:

* https://bitbucket.sgdev.org/
* https://ghe.sgdev.org/
* https://github.com/

<img width="1305" alt="Screenshot 2022-04-11 at 18 01 32" src="https://user-images.githubusercontent.com/25608335/162792329-727b6a60-3ffd-4d23-b1a9-21cfae2d0d5d.png">

We've also updated the webhook for the `sourcegraph-testing`
