### ISSUE TITLE
Validate Batch Change name before creation

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#32893]
When a user creates a batch change, we assume whatever the user enters is a valid string, however `yaml` specification requires a string to start with an alphabet.

That means `test-batch-change` is a valid string while `1.2_batch_change` isn't a valid string.
We need to validate that the name of a batch change begins with an alphabet before creating the batch change.

<img width="852" alt="Screenshot 2022-03-22 at 14 40 48" src="https://user-images.githubusercontent.com/25608335/159498019-43229a34-a91b-48c5-be9d-d8a52544eb92.png">

**Comment by BolajiOlajide** [comment]
**Question**: Should this validation be done on both the backend & frontend or ...?

cc @malomarrec @eseliger

**Comment by LawnGnome** [comment]
(Obviously I missed the discussion on this, so apologies if I'm repeating anything.)

> Quoting the `name` in the yaml file is a quick fix for this and we should look into the way we save strings in the `yaml` file.

I think this is the right fix anyway — we could change the pattern in the batch spec schema to be more restrictive on the first character, but since we don't have a technical reason for preventing a digit from being the first character other than YAML's type detection being a bit screwy, I'm inclined to just encourage users to quote their strings in this case.

**Comment by BolajiOlajide** [comment]
> (Obviously I missed the discussion on this, so apologies if I'm repeating anything.)
> 
> > Quoting the `name` in the yaml file is a quick fix for this and we should look into the way we save strings in the `yaml` file.
> 
> I think this is the right fix anyway — we could change the pattern in the batch spec schema to be more restrictive on the first character, but since we don't have a technical reason for preventing a digit from being the first character other than YAML's type detection being a bit screwy, I'm inclined to just encourage users to quote their strings in this case.

Hey Adam, no worries at all.
We agreed the approach of quoting the string in the `yaml` was the best so we're aligned as regards that. :)
