### ISSUE TITLE
No results found when indexing is enabled

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#3294]
After a customer enabled indexing, search results that previously had results are no longer returning results.

For example the following query previously had 1 result without indexing enabled, but now has zero with indexing enabled.

**Query:** `sourcegraph-access`
Returns 0 results fairly quickly.

However if the repository is included in the query the result is found in 0.03 seconds.

**For example:** `sourcegraph-access repo:REPO_RESULT_IS_IN`

There's about 4000 repositories indexed. Users would prefer to search across all repos, and indexed searching is allowing them to do that (in some cases). However, the "No results" is also misleading.

If helpful – since enabling indexing, there was an event of high CPU (expected) while indexing, but now the CPU is consistently higher, even without any activity. Number of processes and kernel context switches is also significantly higher.

What other information would be helpful here @ijt ?

Orgs affected:
* https://app.hubspot.com/contacts/2762526/company/887065580

**Comment by KattMingMing** [comment]
When adding `index:no` to the end of the search query, the following error is returned (previously seen)

**Query:**: `sourcegraph-access index:no`

**Error**: `Unexpected HTTP error: 502 Bad Gateway`

**Comment by sqs** [comment]
This is obviously very high priority. I’m assigning myself. I am adding to 3.3; please remove any features or other less important tech debt work as necessary to get this done.

**Comment by KattMingMing** [comment]
So after narrowing the search to make the results appear, the indexed search later adds those results for an overall search (most likely coming from a cache).

But days later, (like on the `sourcegraph-access` search) The query returns the **No results** response.

**Comment by ijt** [comment]
@sqs, I'm on it.

**Comment by ijt** [comment]
Putting `return nil, false, nil` at the top of `searchFilesInRepos` gives back the "No results" error. Digging some more.

**Comment by slimsag** [comment]
I've just shipped a patch release 3.2.1 which includes #3302 for acquiring more debug info.

**Comment by KattMingMing** [comment]
After upgrading to 3.2.1 the following errors are found when searching:

```
15:51:01           frontend | t=2019-04-09T15:51:00+0000 lvl=warn msg="searchFilesInRepo failed" error="git command [git rev-parse HEAD] failed (stderr: \"\"): context canceled" repo=<redacted>
15:51:01           frontend | t=2019-04-09T15:51:00+0000 lvl=warn msg="searchFilesInRepo failed" error="context canceled" repo=<redacted>
15:52:02           frontend | t=2019-04-09T15:52:02+0000 lvl=warn msg="searchFilesInRepo failed" error="searcher request failed: context deadline exceeded" repo=<redacted>
15:52:02           frontend | t=2019-04-09T15:52:02+0000 lvl=warn msg="searchFilesInRepo failed" error="context deadline exceeded" repo=<redacted>
```

And just one of the following at startup:
```
15:49:59           frontend | t=2019-04-09T15:49:59+0000 lvl=warn msg="zoektIndexedRepos failed" error="context deadline exceeded"```

**Comment by ijt** [comment]
I may have reproduced it.

I made 5000 repos, each containing a single 1MiB file consisting only of rows like 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", and cloned them into my sourcegraph instance. Once they were cloned, I turned on indexing, waited a bit and then ran some queries. For a while, I had to add `index:only` to get "No results", but once over 2k of the repos had indexes it gave "No results" even without `index:only`. 

![Screen Shot 2019-04-10 at 10 09 43 PM](https://user-images.githubusercontent.com/15530/55932298-010ce380-5bde-11e9-8de4-9f39ba910dc3.png)

One way to mitigate it is to run the queries with `timeout:120s` or similar since otherwise the indexed searches get a timeout of [1.5s](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/textsearch.go#L417:15), and apparently they are taking longer than that in many cases.

**Comment by keegancsmith** [comment]
> Do you know why it seems to have no effect to hard code `searchOpts.MaxWallTime = time.Millisecond` in `zoektSearchHEAD`?

@ijt Based on https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/%28google/zoekt%7Csourcegraph/sourcegraph%29%24+MaxWallTime

So in zoekt the setting is respected. We will still spin up a goroutine per shard, but within a shard zoekt checks cancellation [before searching](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/eval.go#L89) and [before looking for the next result](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/eval.go#L144)

So I am guessing the problem is maybe something is overwriting that setting after you hardcode it. If you check the sourcegraph related code we do a bunch of adjustments to MaxWallTime. So just check if you have hardcoded it just before we do the RPC call rather. You can check the net/trace debug page for zoekt-webserver to see the options set for an RPC call. This can confirm you are actually sending 1ms as the timeout. https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/shards/eval.go#L22

**Comment by keegancsmith** [comment]
I realised we don't conveniently expose zoekt's debug/trace pages like we do for our other services. So sent this PR to add them. Hopefully it will help aid your debugging: https://github.com/sourcegraph/sourcegraph/pull/3360

**Comment by ijt** [comment]
Okay, I narrowed it down and got it to reproduce with only a single 1MB repository, with this patch:
```
[ ~/src/github.com/sourcegraph/sourcegraph ] git diff
diff --git a/cmd/frontend/graphqlbackend/textsearch.go b/cmd/frontend/graphqlbackend/textsearch.go
index e8f6ffe321..2306e263e2 100644
--- a/cmd/frontend/graphqlbackend/textsearch.go
+++ b/cmd/frontend/graphqlbackend/textsearch.go
@@ -461,6 +461,9 @@ func zoektSearchHEAD(ctx context.Context, query *search.PatternInfo, repos []*se
 
        tr.LogFields(otlog.String("maxWallTime", searchOpts.MaxWallTime.String()))
 
+       // HACK: reproduce the "No results" bug #3294
+       searchOpts.MaxWallTime = time.Microsecond
+
        resp, err := Search().Index.Client.Search(ctx, finalQuery, &searchOpts)
        if err != nil {
                return nil, false, nil, err

```

I had set it to 1msec, but zoekt was so fast getting back for this small case that it was actually enough.

To get back to the original problem, it appears that we've been setting the deadline too short for indexed queries (about 1.5s). I suggest we increase the timeout to something longer like 10 or 20s in the short term and then 120s or unlimited once we add streaming. We don't want searches to take a long time but we should let our users decide how long they are willing to wait. (Caveat: The possibility of denial of service may force a different answer on sourcegraph.com.)

**Comment by ijt** [comment]
PR #3376 got part of the way, although I'm sometimes seeing erroneous reports of "No results" when I make queries with `timeout:1ms` on a sourcegraph instance with a single repo.

**Comment by ijt** [comment]
@KattMingMing, any update from the customer on this?

**Comment by ijt** [comment]
Discussed offline: the customer is busy with other things. I'm closing this out because it looks like we identified what was going on and fixed the incorrect "No results" messages that were appearing to be timeout error messages instead. In the longer term we would like to eliminate this sort of problem by streaming search results (#3261) but a short term solution is for users to add a `timeout:` directive to queries when searches time out.
