### ISSUE TITLE
Notebooks list doesn't persist ordering selection

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#32973]
Notebooks always sort by stars and doesn't persist the selection order.

Issue: If I change it to `creation date, descending`, and navigate away and come back, it re-sorts by stars. I think we should persist the selection. Working with more than, say, 10 notebooks and wanting to work on recent notebooks, it gets tedious to have to select that menu item every time.

But I won't call this a "bug" until we get acknowledgment on the issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by rvantonder** [comment]
Addendum: yes, the URL persists if I use the browser buttons to go forward/backward, but the issue is I often work in a notebook, then click the notebook link (this thing):

![Screen Shot 2022-03-23 at 12 07 36 PM](https://user-images.githubusercontent.com/888624/159777197-7408b015-f832-4a9a-b916-29cef8601390.png)



 to go back to my notebooks page, and then the URL is empty and doesn't persist that ordering selection

**Comment by benvenker** [comment]
Ah, yeah I've had the same thought but was holding back on raising the issue just because I've seen it done both ways in other products. Your use case makes sense though, and we definitely want to prioritize the needs of creators so persisting last sort order could be the right thing here.

cc @novoselrok
