### ISSUE TITLE
Standardize CI operations

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#33191]
## Measure of success

All CI operations can easily be run locally, so teams can iterate on their testing capabilities faster. 

## Solution summary

Provide standardized tooling that makes it easier to run tests locally. Add documentation that encourages devs to make sure local test pass before pushing to CI. 

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Delivery plan

- [ ] TO DO

**Comment by bobheadxi** [comment]
We are folding this into the more use-case-centric https://github.com/sourcegraph/product-engineering-tracker/issues/117 , which aims to improve developer feedback loops. Standardizing CI operations integrates with that because being able to reproduce CI issues locally is a core part of our overall CI strategy within improving the feedback loop.

cc @quinnhare @jhchabran
