### ISSUE TITLE
JetBrains: How to add virtual files to a project

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#33427]
There are some concerns in the technical document about virtual files always opening in a new editor window. Let's see what we can do about this.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by vdavid** [comment]
I think this is not going to be an issue. According to [this section](https://developerlife.com/2021/03/13/ij-idea-plugin-advanced/#vfs) of an article, the IDE uses VFS (a virtual file system) to access _all_ files. The VFS abstracts away the fact that the file is on the physical disks or an HTTP server, on Sourcegraph, etc.). So I think the problem was something else when Coury tried to open the virtual files in editor tabs.

**Comment by philipp-spiess** [comment]
@vdavid This is awesome! This article does not mention how an extension can _provide_ virtual files and register them with the project. I'll change the topic slightly so that we look into this issue. I assume it's possible but don't know for sure!

**Comment by vdavid** [comment]
It works: https://www.loom.com/share/fa941e1235f346eca58b1596e8314ad1
(at the end of the video, I meant to say "error reports" or something, definitely not syntax highlighting.)
But the errors look weird, so I'll investigate suppressing them.

**Comment by vdavid** [comment]
Solved the syntax highlighting issues, only needed [a little piece of code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-jetbrains@dv/open-virtual-file-in-editor-proof-of-concept/-/blob/src/main/java/com/sourcegraph/SourcegraphSearchView.java?L78%3A1-83%3A1=&utm_product_name=IntelliJ+IDEA&utm_product_version=IntelliJ+IDEA).

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/2552265/162968291-c4287432-b5f7-4ac8-9184-8ea695cb0752.png">

It looks good now, but our friend in the JetBrains team warned us that we might need a bit more than this:
> If it’s too strong, there’s [a more fine-grained approach](https://plugins.jetbrains.com/docs/intellij/controlling-highlighting.html). You might also need [this](https://plugins.jetbrains.com/docs/intellij/syntax-errors.html) if the parser emits strange results due to missing project environment/settings.

But as far far of this issue is concerned, we're done here, so I'll close it.
