### ISSUE TITLE
JetBrains: Styling the web search input

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#33428]
How can we style the web search input component using JetBrains theme variables?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
One thing to be mindful of here is that we do not want the UI to flicker but I think this should be easy to avoid, we just need to make sure we first load the theme detail before we render any UI code. In the mean time, the view could just be empty like the native behavior.

**Comment by philipp-spiess** [comment]
@vdavid Have you also looked into other aspects aside colors? e.g. border behavior, radius, etc? Does it mean that we have to manually migrate every part of the UI that we want to configure to CSS variables first or is this already the case?

**Comment by vdavid** [comment]
> Flickering

I didn't want to tackle this in the scope of this issue because I belive more research is needed there. I'm not sure if the white we're seeing is the page background or the component background. If it's the page background then sure, we can solve it by setting the body background early. If it's the component, then some other trick might be needed, e.g. rendering a different Swing component over the JCEF until the document loads. I've created a new issue about this: https://github.com/sourcegraph/sourcegraph/issues/34694

> Border behavior, radius, etc.

I'm not sure I get your question. Is your question whether these values come from CSS variables?

**Comment by vdavid** [comment]
@philipp-spiess please clarify what you meant by border behavior, radius, etc. (not urgent just I want to make sure this is not forgotten)
Was your question whether these values come from CSS variables in the current version of the Sourcegraph search box (rather than being hardwired in component-level CSS)?

**Comment by philipp-spiess** [comment]
Oh, sorry! Yes, I was thinking if we can also use CSS variables for things like border radius or other themes but TBH I think this should work fine! The only "worry" is that we have to change quite a few properties in our search box styles to use CSS variables that currently use hardcoded values but even if we have to, I don't foresee any issues there (just tedious work). 

Thanks for looking into this 🙂
