### ISSUE TITLE
SSBC: Show download src-cli button when executors are not enabled

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33440]
When executors are not enabled:
- the buttons are swapped.
- users can see a modal landing page explaining what server-side batch changes is

[Figma](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=2003%3A60178)

**Comment by malomarrec** [comment]
@courier-new the second bullet point assumes that we insert a video or a GIF in the modal. Is that feasible, and are there technical limitations on the GIF or video size?

**Comment by courier-new** [comment]
Yeah that's fine, though we may want to wait for a couple enhancements to land on the execution screen (aka complete EM3.5) first, so perhaps recording that should be its own issue that we put in EM3.6.

I'm not sure if there's size limitations but I do know:
- A video is better and can just be made to look like a GIF, like the video at the top of the getting started page that just plays automatically and doesn't have any sound
- Using that video as a reference, the mp4 file is ~5MB, so that seems like a good goal size for this one

If that sounds good, I can draft a separate issue and propose a "script" of what to show off, and we can limit the scope of this issue to detecting the executor setup, flipping the button, and implementing the "modal landing page" for server-side sans video.
