### ISSUE TITLE
[Accessibility Audit] Insights: Delete insight

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33503]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1m8oYTFgim8epA2IfPFCTN2QFSDxODV5WJNe2JhRdMZA/edit?usp=sharing). Use this for further context.

- Find insight through any dashboard on the dashboard page
- Click three dot menu and click delete context item
- Confirm that you really want to delete the insight in the confirmation model UI
- See that the insight has been deleted
- Note: that this insight has been deleted from all dashboards that this insight had been included before. (So it’s deleting by reference)

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
**Audit report**
- **Keyboard navigation** (the general flow of insight deleting is accessibly by keyboard navigation but it turned out that chart - the main insight card content isn't accessible by keyboard, it was filled in this issue https://github.com/sourcegraph/sourcegraph/issues/37885
- **Voice-over announcements.**  One problem that I noticed is there were no announcements when I deleted insight. And the focus wasn't handled properly when I deleted insight and we automatically closes the delete insight modal. It's filled in this issue https://github.com/sourcegraph/sourcegraph/issues/37886
