### ISSUE TITLE
Add performance warning for sourcegraph/server instances that have a lot of repositories

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3370]
We have had a few customers recently experience performance issues when adding thousands of repositories to a single node sourcegraph/server instance. There are separate efforts to improve this performance, but in the meantime we want to inform users that we recommend deploying with Kubernetes at larger scales to avoid these types of problems.

The proposed solution is a dismissable site alert that shows on sourcegraph/server instances when more than 100 repositories are enabled and point the user to our cluster deployment.

Questions for @sqs @dadlerj :
- What copy do you propose for this alert?
- What landing page do you want to direct users to (e.g. https://docs.sourcegraph.com/admin/install/cluster) to learn more about Kubernetes deployments?

**Comment by dadlerj** [comment]
Copy rough draft — just thinking out loud here. What do you think? "Your Sourcegraph instance has a lot of code, and search performance or accuracy may suffer. We recommend instances with 100+ repositories [deploy to a cluster](https://docs.sourcegraph.com/admin/install/cluster) instead of a single-node Docker deployment. [Contact us](https://about.sourcegraph.com/contact) for support or to learn more."

A few questions about behavior:
* Who would see the alert in your mind? All users, or just admins?
* Would it be a one-time alert that can be dismissed, or would it reappear?
* Would it be a "site alert" or a "search alert" — would it show at the top of the screen on every page, or just at the top of search results, similar to the notif here:
![image](https://user-images.githubusercontent.com/5589410/55988284-5685d680-5c58-11e9-8757-add540b4d28d.png)

**Comment by nicksnyder** [comment]
All good questions.

- I think all users should see this alert since it impacts everyone.
- All of our current alerts are dismissible, so I think this one would be too.
- Making it a search alert seems like a good idea, but I would be fine with either. The performance really could impact non-search use cases though too, and I would want to make sure the admin setting up the instance would see it immediately, even if they don't do a search, so perhaps both?

**Comment by nicksnyder** [comment]
I propose a global dismissible alert like this:
![image](https://user-images.githubusercontent.com/754768/55992044-7620fd00-5c60-11e9-91bd-0ea01cb1872e.png)

I am fine making it visible to only admins or to everyone. What do you think?

**Comment by dadlerj** [comment]
Looks good to me (CC @francisschmaltz for styling). It feels a bit more natural to me as a dismissable search alert than a site alert, but I'm okay either way. @sqs should give the final 👍 
from product.,

**Comment by dadlerj** [comment]
See https://github.com/sourcegraph/sourcegraph/pull/3359 for how I'm implementing a new alert as well

**Comment by nicksnyder** [comment]
![image](https://user-images.githubusercontent.com/754768/55997955-3dd5ea80-5c71-11e9-8dbd-b760170a5e24.png)
