### ISSUE TITLE
insights: reset button causes filters to get 'stuck' on currently filtered insight

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33813]
If you have an insight view that is filtered (say with a regexp) and press 'reset' it will become stuck in the last state it was filtered in. New network requests are initiated correctly, but the results don't seem to update.

To reproduce:
1. create an insight that is filterable
2. filter using some string, say `sourcegraph`
3. press `reset`
4. Try to change the filter and observe no changes occur

https://user-images.githubusercontent.com/5090588/163054707-5fd5f684-6a17-46bd-9049-3d9faf83c106.mp4

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
@vovakulikov is correct this is a caching issue (probably). Notably, it's not just the reset button that is broken, but changing the filter back and forth between values also breaks.

It's either Apollo's cache breaking (which they recommend basically not using with `watchQuery` wheeeee) or the observable is not being updated when the value changes. I suspect the former since when I log out what apollo is returning it is incorrect.

I believe we may be better suited switching over to `query` and Promises instead. We already re-call `getBackendInsightData` anyway so I'm not sure what the value is of not just using Promises here and simplifying this code.
