### ISSUE TITLE
Command palette styling is broken on Bitbucket Server pull request list page

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3381]
- Navigate to a repository's pull request list page on Bitbucket Server
- Open the command palette
- Witness command palette styling is broken:

![image](https://user-images.githubusercontent.com/1741180/56041993-54944400-5d3a-11e9-8d15-97326037a316.png)

Customers (not exhaustive): https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by sqs** [comment]
This appears to me to be occurring on all pages (on my local Bitbucket Server v5.15.1 installation), not just the PR list page.

(I encountered this problem while testing https://github.com/sourcegraph/sourcegraph/pull/4545.)

**Comment by sqs** [comment]
@felixfbecker 	@lguychard Any clues why this stopped working? @felixfbecker 	posted a screenshot of it working on Apr 3 at https://sourcegraph.slack.com/archives/C89KCDK5J/p1554336430008100.

(It should work again now that #4547 is merged, but it's still weird that it regressed since I can't see any changes that would have caused that.)
