### ISSUE TITLE
React Router V6 migration

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33834]
## Description

React Router V6 is out, and they have just published a [migration plan](https://github.com/remix-run/react-router/discussions/8753).

We have completed the "Setting up" stage through this PR: https://github.com/sourcegraph/sourcegraph/pull/33835

We should follow the "Migration strategy" stage to complete the migration. 

### Please follow the [migration plan](https://github.com/remix-run/react-router/discussions/8753) guide written by the React Router team themselves. I have avoided duplicating any additional information in this issue as that guide should be used as a source of truth (if it is edited).

**Comment by philipp-spiess** [comment]
The more I try to untangle our routing mess the more confused I am. My latest find is this:

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@ps/rr6-migrate-route-to-compat-route/-/blob/client/web/src/repo/routes.tsx?L122%3A2-133%3A26
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@ps/rr6-migrate-route-to-compat-route/-/blob/client/web/src/repo/RepoContainer.tsx?L435%3A24-446%3A39

For some reason these routes are nested in each 😅 

In #46903, I changed our RR5 `<Routes>` to RR6 `<CompatRoutes>` but this breaks various pages. I think it’s because we use some of the regex features that are not supported (see https://github.com/remix-run/react-router/discussions/8753 in Migration Strategy 1)

> You can’t use regular expressions or optional params in v6 route paths. Instead, repeat the route with the extra params/regex patterns you’re trying to match.

What we do for the repo container: We match for `:revAndRest+` which matches everything (so similar to [RR6 splats](https://reactrouter.com/en/main/route/route#splats) that is supported in V6) but when I change it, the nesting no longer works as we expect it to 😐

**Comment by philipp-spiess** [comment]
It seems like the first level of route matching (in `RepoContainer`) is working and it also seems like it matches the correct path for the second level (in `RepoRevisionContainer`). But for some reason this does not render any child components anymore? 🤔 

<img width="1423" alt="Screenshot 2023-01-25 at 01 20 44" src="https://user-images.githubusercontent.com/458591/214451468-8bec18ea-22ec-4642-bc9d-0bd9cb4cfffd.png">

**Comment by philipp-spiess** [comment]
I think it's clearly me who doesn't understand the nesting rules properly. Take the code monitoring page as an example.

It defines a non-exact `/code-monitor` route in the `Layout` which (based on the components being rendered in the component tree) is always being matched. Cool. 

But for some reason, the second level matching in `GlobalCodeMonitoringArea` is not working 😕 

However, when I try to change it to relative rules https://github.com/sourcegraph/sourcegraph/pull/46903/commits/00713d2eb7d3f28d6bc9e89a323f4d7dbfb1b970 I can get one of the three pages to match. But only one 🤔

**Comment by valerybugakov** [comment]
Hey @philipp-spiess, I shared my notes in the draft PR based on your work. Let's discuss this when you're back online!
- https://github.com/sourcegraph/sourcegraph/pull/46909
