### ISSUE TITLE
when search a short string， get less result

### ISSUE THREAD

**Issue by ac51300696** [sourcegraph/sourcegraph#34032]
![image](https://user-images.githubusercontent.com/11310942/163913481-5f182718-69c3-4e5a-a7c8-4a2de97a56cf.png)
search by /v2/
![image](https://user-images.githubusercontent.com/11310942/163913606-e5dadf15-e95f-437b-9a23-3276bb48fc61.png)
search by /v2/core

search short string， get less respo
Version: 3.38.1

install in local
search loaclGitlab code
need any more information

**Comment by camdencheek** [comment]
Hi @ac51300696!

The repositories listed in the sidebar are only for the results returned. By default, we set a result limit of 500 results, so you will only see which repos the first 500 results belong to. 

In order to see the result count for a larger set of repos, you can add a filter like `count:10000` or `count:all` to your query.

**Comment by ac51300696** [comment]
👌，thx。
l am use it at first，default count is not all is a thing that little difficult to understand
