### ISSUE TITLE
[Accessibility Audit] Batch Changes: View the burndown chart for an open batch change

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34082]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1XgG0udYL37G3RxuT5shizulpHgb6xVtY5L9kBeSkXYk/edit?usp=sharing). Use this for further context.

- Click “Batch Changes” in the top navigation bar
- Scan the list to find the open batch change
- Click the name of the batch change on the list item
- Click the “Burndown chart” tab above the list of changesets
- The burndown chart will be visible

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by courier-new** [comment]
**Note to whoever conducts this audit:** The burndown chart is a feature of our UI that was pretty much implemented as an MVP product and has never been touched since. As such, there are many ways both [known](https://github.com/sourcegraph/sourcegraph/issues/15034) and yet-to-be-explored that the chart could be improved, not even counting a11y. While we should absolutely audit this flow and the usability of the burndown chart itself and log any a11y issues with it, we should limit the time we invest in fixing these issues until we can also invest design resources into this feature and prioritize improvements to it more holistically. Recommendation would be to timebox a11y fixes to this chart to 2 hours.

**Comment by BolajiOlajide** [comment]
Audit complete!
