### ISSUE TITLE
insights: enrich compute MatchContext results with simple repo information

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#34228]
The compute result [MatchContext](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/compute/match_context_result.go?L36:6) does not currently contain any repo information when consumed from a stream:
``` json
data: [{"matches":[{"value":"test","range":{"start":{"offset":-1,"line":4,"column":2},"end":{"offset":-1,"line":4,"column":6}},"environment":{"1":{"value":"test","range":{"start":{"offset":-1,"line":4,"column":2},"end":{"offset":-1,"line":4,"column":6}}}}},{"value":"Test","range":{"start":{"offset":-1,"line":9,"column":5},"end":{"offset":-1,"line":9,"column":9}},"environment":{"1":{"value":"Test","range":{"start":{"offset":-1,"line":9,"column":5},"end":{"offset":-1,"line":9,"column":9}}}}},{"value":"test","range":{"start":{"offset":-1,"line":9,"column":31},"end":{"offset":-1,"line":9,"column":35}},"environment":{"1":{"value":"test","range":{"start":{"offset":-1,"line":9,"column":31},"end":{"offset":-1,"line":9,"column":35}}}}},{"value":"test","range":{"start":{"offset":-1,"line":10,"column":1},"end":{"offset":-1,"line":10,"column":5}},"environment":{"1":{"value":"test","range":{"start":{"offset":-1,"line":10,"column":1},"end":{"offset":-1,"line":10,"column":5}}}}},{"value":"test","range":{"start":{"offset":-1,"line":115,"column":20},"end":{"offset":-1,"line":115,"column":24}},"environment":{"1":{"value":"test","range":{"start":{"offset":-1,"line":115,"column":20},"end":{"offset":-1,"line":115,"column":24}}}}},{"value":"test","range":{"start":{"offset":-1,"line":116,"column":25},"end":{"offset":-1,"line":116,"column":29}},"environment":{"1":{"value":"test","range":{"start":{"offset":-1,"line":116,"column":25},"end":{"offset":-1,"line":116,"column":29}}}}}],"path":"batches/changeset_spec_test.go"}]
```

Code Insights uses `repo_id` and `repo_name` directly from search results to reduce DB transmissions. To avoid a DB trip for this information we should add this to the [MatchContext](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/compute/match_context_result.go?L36:6) type

### Question

I'm not super familiar with the goals of the search API, but if we were to do the work here I'd need a little guidance on how the search team would like it to evolve here.

The standard search [stream API](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/streaming/http/events.go?L18=) returns repo metadata that is flattened with fields such as `repositoryID`.

The GraphQL representation of the compute MatchContext returns a [nested structure](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/compute.graphql?L22-39).

Additionally, the GraphQL returns gql string identifiers and the stream API returns int32 identifiers for the repo id.

If we were to add repo metadata to MatchContext, would we prefer to be consistent with the stream API and flatten them, or consistent with the GraphQL hierarchy for the same compute type?

#### Consistent with stream API
``` go
type MatchContext struct {
	Matches    []Match `json:"matches"`
	Path       string  `json:"path"`
	RepoID     int32   `json:"repositoryID"`
	Repository string  `json:"repository"`
}
```

#### Consistent with GraphQL API
``` go
type MatchContext struct {
	Matches    []Match `json:"matches"`
	Path       string  `json:"path"`
	Repository struct {
		Name string
		Id string
	}
}
```

cc @rvantonder

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by rvantonder** [comment]
> If we were to add repo metadata to MatchContext, would we prefer to be consistent with the stream API and flatten them, or consistent with the GraphQL hierarchy for the same compute type?

I say just flatten it. The nesting with GQL makes sense when you can scope/query/select the values you care about. You get everything with streaming and can't select this way (unless we implement URL params to make it behave otherwise). No clear plans that this will evolve in any substantial way soon.


Nit/aside:

> The GraphQL representation of the compute MatchContext returns a [nested structure](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/compute_graphql_results.go?L97-105&utm_source=raycast-sourcegraph).

That definition looks to be a Go/GQL type with a twist on the actual GQL `MatchContext` type in the [`compute.graphql` definition](
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/compute.graphql?L22-39&subtree=true), but yes, the point stands that the definition/repository values are nested in both cases.

**Comment by coury-clark** [comment]
@rvantonder Sorry, wrong link 😄 - got the tabs crossed. Yes, I meant to point to the original graphql file that you linked!

Got it, sounds good!

**Comment by rvantonder** [comment]
To give a bit of concrete guidance, you should only need to add the fields to this definition: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/compute/match_context_result.go?L36-39&subtree=true

And populate it here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/compute/match_only_command.go?L72-79&subtree=true

In that second link, the function already has the file match `fm`, and the repo name/ID is already available, so this would be a small change that probably takes only 30 or 40 minutes 😆 Didn't realize it'd be that simple, for some reason I had it in my head to change the `Event` type but that's not what should happen. Do you want to dive in or I can do it since it's easy?

**Comment by coury-clark** [comment]
Yeah, it's actually already in a commit on the way 😆 

So I've got it taken care of!

**Comment by rvantonder** [comment]
![](https://media2.giphy.com/media/o0vwzuFwCGAFO/giphy.gif?cid=5a38a5a23p1ythjgpnsuudf6txjlhg3hm87plfkixn67g3r4&rid=giphy.gif&ct=g)
