### ISSUE TITLE
Create consistent query syntax aliases

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#34395]
There are some clean up items around our query syntax. I want to clean up some of these, was prompted by https://sourcegraph.slack.com/archives/C09J2HMAP/p1650748011684269?thread_ts=1650742838.978369&cid=C09J2HMAP. I will propose an RFC but am basically going to go ahead with these. This includes:

- `type:file` to go away (or alias `type:path`), and add `type:content`
- add `symbol:XYZ` to alias `type:symbol XYZ`, same with `regexp:`, `literal:`, and `structural:`
- change "literal" search to "default" search and also support regex with `/.../` syntax
- support `content:/<regexp>/` syntax and such on appropriate fields

This will probably be a 1 to 2 day task.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by vdavid** [comment]
Both the DevInsideYou guy ([here](https://youtu.be/mSaWa9rx-fk?t=3939)) and I had run into the issue when we tried to use double quotes to indicate `exact string` (like in Google and other platforms) rather than literally searching for double quotes.

Idea to solve this:
When typing, whenever I type a double quote in the search box, a warning/info text could come up, teaching me that Sourcegraph will literally search for double quotes (and it would be cool if it also instructed me how to indicate that I want an exact text search). This warning could be dismissible so that I could dismiss it forever once I've learned this.

**Comment by benvenker** [comment]
@rvantonder are you planning on working on this this iteration? Just noticed and automatically got moved over but looks like it's been off your list for a bit. No worries, just wanted to take it out if it's not part of your goals this iteration.

**Comment by rvantonder** [comment]
Mostly addressed by RFC 675 
https://docs.google.com/document/d/1KebTihO_jrPcLblgeT4X428kfgs42NkFz_3kCr8bT0M/edit#heading=h.trqab8y0kufp
