### ISSUE TITLE
error while adding GitHub repositories

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3445]
![image](https://user-images.githubusercontent.com/3173176/56252826-9b51a900-606e-11e9-96b0-a01f3a23e83b.png)

Please make error message clearer

**Comment by sqs** [comment]
I believe that the error string is Markdown-formatted, so you should wrap it in the React `<Markdown>` component. Also, instead of "N errors occurred:", say "Error saving configuration:". This brings it to parity with the same error for site config:

![image](https://user-images.githubusercontent.com/1976/56255385-80386680-6079-11e9-8fe4-68575f38862e.png)

Once you make these changes, I believe that it'd be much clearer. It would look like:

> Invalid configuration:
>
> * token: String length must be greater than or equal to 1

It would be nice if it instead read "token: Must not be empty" or "token: Must set a GitHub access token" or something, but I think 99% of users will understand the above. If you do want to change this sentence (not necessary/worth it IMO), please change it upstream instead of special-casing `github`'s `token` property.

**Comment by sqs** [comment]
I can do this quickly ^

**Comment by keegancsmith** [comment]
I believe @sqs fixed this in #3451

**Comment by keegancsmith** [comment]
Fix cherry-picked onto 3.3 as 92d91ec069a36d42d4d77782453c049ebe05ade1
