### ISSUE TITLE
insights: series data displaying out of order on line chart

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#34485]
- **Sourcegraph version:** 3.39.0

#### Steps to reproduce:
TBD

#### Expected behavior:
The series of data on the chart should move only left to right.

#### Actual behavior:
![OutOfOrder](https://user-images.githubusercontent.com/6098507/165202472-c63bf888-7265-4fb3-bc89-715cedaceca5.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
@vovakulikov assigning to you since it's the end of my day.

@leonore copying you since you are the next BE engineer by timezone in case Vova needs some support.

Notes:

- This only affects 3.39.0
- Seems to happen when the dates are slightly out of order see [this slack thread](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1650911378648839) for more detail.
- Unsure whether this should be a front or backend fix, but @chwarwick experimented locally with just re-sorting the data on the frontend and it seemed to work (mostly).

Could you try out Chris' experiment and see if you find any problems with it? It may be faster to just fix this on the FE this time since it's only a patch for this particular release.

Chris' fix

```typescript
// create-line-chart-content.ts -> getDataPoints

function getDataPoints() {
  // ...
  return [...dataByXValue.values()].sort((a,b)=> new Date(b.dateTime)- new Date(a.dateTime))
}
```

**Comment by chwarwick** [comment]
The issue occurs on search insights that have multiple independent series that have had at least 2 data points added after the insight was created.  This appears to be an issue that has existed for some time but the migration of the charts makes it a little hard to tell if there was an additional sort that used to be present that was fixing it.

### What I observed in v3.39.0:

1. The backfill process [uses the start of the day UTC time](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.39.0/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L395) to create the datapoints in the past.  This ensures that the timestamps for every backfilled data point match.
2. When additional data points are added as time passes, [the current UTC time](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.39.0/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L353) that the search query is run is used.  This causes the new data points to be close but not exactly the same like the backfilled values were.
3. The UI [merges the multiple data series into a single series](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.39.0/-/blob/client/web/src/enterprise/insights/core/backend/utils/create-line-chart-content.ts?L62:17#tab=references) with a value for each query at each unique timestamp. This works for the backfilled data because the timestamps are identical for each of the individual series but causes additional points to be create for the new data points.  This leaves the list of data points out of order. 


This issues does not exist in future version because it appears that the data points are sorted by the LineChart itself. I believe [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/charts/components/line-chart/LineChart.tsx?L171)

### Potential Workarounds:

- Edit the insight changing the time interval

### Fixes
- UI ensures that the series data is sorted by timestamp
- Modifying the background worker to ensure new data points have consistent timestamps.

A thorough fix probably includes parts of both items although I can make case both for and against modifying the background workers timestamp.

**Comment by vovakulikov** [comment]
@unclejustin @chwarwick I tried to run insight locally in a storybook with mock raw data that Justin shared with me and I got this (at the first glance it looks like it should be)

<img width="431" alt="Screenshot 2022-04-26 at 12 30 03" src="https://user-images.githubusercontent.com/18492575/165221530-67ac436b-0304-410c-baf5-02f47a374725.png">

> The UI [merges the multiple data series into a single series](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.39.0/-/blob/client/web/src/enterprise/insights/core/backend/utils/create-line-chart-content.ts?L62:17#tab=references) with a value for each query at each unique timestamp. This works for the backfilled data because the timestamps are identical for each of the individual series but causes additional points to be create for the new data points. This leaves the list of data points out of order.

I think this logic about grouping points by date has been already changed in this PR https://github.com/sourcegraph/sourcegraph/pull/34174 and this is why I could see a proper chart above with raw "bad" data. I think I actually do not understand the problem with data properly. Here is the data that I used for the chart above that Justin shared with me and this looks like a proper data (all dates are sorted properly already there) 

[raw data.txt](https://github.com/sourcegraph/sourcegraph/files/8559861/raw.data.txt) @chwarwick @unclejustin can you expand on this problem a bit more just to be sure I fully understand this. 

>This issues does not exist in future version because it appears that the data points are sorted by the LineChart itself. I believe [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/charts/components/line-chart/LineChart.tsx?L171)

@chwarwick I think you misunderstood this part slightly. This sort works only per series but doesn't change the order of points within the series. It was done for changing the series order rendering in order to recreate the z-index CSS rule for the SVG elements. @unclejustin correct me if I'm wrong. However, somehow I still see a proper chart on the main, maybe refactoring chart API solved this problem with corrupted unordered data from the backend.

**Comment by vovakulikov** [comment]
@unclejustin @chwarwick ok, I think I figured out this for myself, I captured my understanding on this in this document https://docs.google.com/document/d/11WPnLpV6MPcLSgPWTTSP1ThHabp5QXM3spguVokktgQ/edit?usp=sharing

Nothing new actually almost everything like it's described in this issue but with FE context
