### ISSUE TITLE
The "Open file in Sourcegraph Web" option from Windows VSCode fails.

### ISSUE THREAD

**Issue by MattWUnity3d** [sourcegraph/sourcegraph#34630]
- **Sourcegraph version:** Sourcegraph for VSCode v2.2.1
- **Platform information:** Windows 10, VSCode 1.66.2

#### Steps to reproduce:

1. Open a file which is visible in Sourcegraph Web
2. Chose the "Open file in Sourcegraph Web" option on the right click menu

#### Expected behavior:
The file will open in Sourcegraph Web

#### Actual behavior:
Sourcegraph Web gives a Not found error  "<file> does not exist at this revision."
Notice that the URL has %5C where the directory separators are. 
If you replace %5C with / in the URL then the file will be successfully found.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
@MattWUnity3d Just want to let you know that I'm able to reproduce this issue and will work on a fix soon. 

It looks like the link is broken when trying to use the "Open file in Sourcegraph Web" option on a remote (read-only) files. 
Using the same option on local files work as expected --can you confirm if this is the same case for you?

Thanks!

**Comment by abeatrix** [comment]
Update:

After investigate further, I can confirm that this behavior happens to local files and not remote files on windows because the file path is using the \, for example C:\Users\bee\Documents\sourcegraph\schema\aws_codecommit.schema.json

As a result, trying to open the file using the incompetible file path takes me to a 404 page:
![Image](https://user-images.githubusercontent.com/68532117/166073641-6f2bbeaa-3ad7-43bb-9c12-908c763934cd.png)

Changing the double \\ into / would take me to the correct page:
![Image](https://user-images.githubusercontent.com/68532117/166073799-35e74653-ce9c-48ee-b92b-f511b43a6b8d.png)

To confirm, copying the file link in the extension gives me:
https://sourcegraph.com/-/editor?remote_url=https://github.com/abeatrix/sourcegraph.git&branch=main&file=schema\bitbucket_cloud.schema.json&editor=VSCode&version=2.2.1&start_row=28&start_col=30&end_row=28&end_col=30&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands
We can see that the path has a \ in it: schema\bitbucket_cloud.schema.json
