### ISSUE TITLE
Fix CTA banner late rendering and sliding down other content

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#34688]
https://sourcegraph.slack.com/archives/C03B4EMBXL4/p1651153966869059

**Comment by vdavid** [comment]
@erzhtor @thenamankumar Note that Slack history is [deleted](https://handbook.sourcegraph.com/company-info-and-process/communication/team_chat/#slack-retention) after three months.

Here is a quote to retain the source of the issue:

@mrnugget wrote on 2022-04-28: "The way the banner slides in and moves the results seems like a “dark pattern”. Is this intended? Can we change the loading order here? Or add a placeholder-kinda-thing that will be filled out?
Because quickly trying to click on a result and then discovering that a banner slid under the cursor is not… delightful :)"
4-sec video: https://sourcegraph.slack.com/files/UHTSAHETD/F03CW4B7JF9/screenshot_2022-04-28_11.33.02.mp4

**Comment by malomarrec** [comment]
Hey @erzhtor, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
