### ISSUE TITLE
Move Open-in-X extensions to be native parts of the product

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34810]
We believe that the workflow of going from Sourcegraph web to an IDE is a core part of the product and shouldn't have to be added as an extension.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by muratsu** [comment]
This requires merging existing ide extensions (all open-in-x extensions) potentially into a single extension and exposing it at navbar.

**Comment by vdavid** [comment]
Can we perhaps implement the functionality without requiring the user to install _any_ browser extensions? I think that solution causes less friction.

I'm not sure why this functionality is currently in browser extensions. I used to assume that it was because websites can’t have the privilege to open apps. But Zoom, Slack, and other apps regularly open desktop apps without browser extensions, so it seems doable.

**Comment by ryankscott** [comment]
That was what I was considering, at least that would work on our web app. However, if we want to inject this functionality into code hosts we'll need the browser extensions.

**Comment by ryankscott** [comment]
Closing as duplicate of https://github.com/sourcegraph/sourcegraph/issues/38378
