### ISSUE TITLE
JetBrains: Leave popup open when focus leaves the IDE

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34969]
## Context

Currently, when the "Find on Sourcegraph" popup is open and one focuses away from the IDE with Cmd+Tab on a Mac, the popup disappears.
The "Find in Files" native popup remains open on Cmd+Tab.

## Problem

This behavior somehow makes the popup feel awkward and unusual for the IDE.
This is something that I (David) as a long-time JetBrains user notice a lot and has a strong negative impact on my experience.

## Solution

Keep the popup open until the user closes it with Esc, Alt+Enter, or clicking away from it inside the IDE.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
I looked into this issue last week and there doesn't appear to be an easy way to fix this. There's [this option](https://github.com/sourcegraph/sourcegraph/blob/main/client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java#L70) to cancel the view when another window is active but removing this actually causes the popover to not close in various other cases in my limited testing. So this will likely need some manual focus management in the `setCancelCallback`.

I am wondering wether this even is high priority since even when you need it in your workflow, you can instantly re-open it anyway by typing `alt+a`.

**Comment by jjinnii** [comment]
@vdavid Let us know what you find out regarding solutions and associated effort! If low-ish effort, agreed that I think it would be great to get this resolved. If as a JetBrains user, you find it disorienting and confusing, likely other users will too. (I found it confusing too). 

If it's higher effort than expected, I think we can keep it in the backlog until we do some testing pre-release with customers and see if is something important to get addressed before v1.

**Comment by vdavid** [comment]
Update: Created a [Loom](https://www.loom.com/share/dd298e53aaa2409a8270a01b59d57333) and asked Paul and Yann.

**Comment by vdavid** [comment]
[1 minute Loom](https://www.loom.com/share/94e202a620a144b991b034560016ee02) on the number of times `setCancelCallback()` is being called. (tl;dw: many times)
