### ISSUE TITLE
Search tracking issue for 3.4

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3498]
### Planned work:

For this milestone, the most important deliverables are integration testing for search (#3475) and saved search improvements (#3469). The integration testing is meant to support our work on nested search (#1005), which we intend to pick up for our work on 3.5.

[3.4 search issues](https://github.com/sourcegraph/sourcegraph/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Asearch+milestone%3A3.4)

**Comment by ijt** [comment]
@ijsnow, can you take a look and add anything I missed?

**Comment by beyang** [comment]
@ijt @ijsnow Can you update this with the current state of what the priorities are in 3.4 (per the prioritization discussion in https://sourcegraph.slack.com/archives/CHEKCRWKV/p1556561331003000)? My impression from the Slack thread is that the highest priorities are now the [search issues](https://github.com/sourcegraph/sourcegraph/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Asearch+milestone%3A3.4). Do we think these will be fixed in 3.4?

**Comment by ijt** [comment]
This tracking issue is up to date. Yes, the highest priorities are the search issues.

It looks possible to fix them all. We have about 6 business days until the 3.4 release is cut. There are 9 issues left, and 3 of us working on them. If each of us fixes one issue every two days for the remaining time then we'll have it all done.
