### ISSUE TITLE
[Discovery] Unify permissions model across Sourcegraph features

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#35076]
- [x] Explore Ory Keto permission options and propagation

**Comment by pjlast** [comment]
We've explored Ory Keto and while it looks like a really great implementation of Google Zanzibar (so far), we're deciding against it because of
1. Uncertainties around integrating a new service
2. Making a long term bet on something that is not yet considered mature
3. A possible lack of flexibility for edge cases

The current plan is to go with an approach that allows us to make decisions and implementations iteratively, and use tools that empower us to do this (currently Oso looks like a good place to start).

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
