### ISSUE TITLE
Specific Markdown file fails to highlight properly

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3521]
EDIT by @slimsag: This is the file: https://sourcegraph.com/github.com/GoogleChromeLabs/comlink@9517223426999ee68eb540e5059eaef853210c1d/-/blob/README.md

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/GoogleChromeLabs/comlink%24%40v4+endpoint shows:

![image](https://user-images.githubusercontent.com/1976/56454976-b4c45080-630d-11e9-90a6-b8a1457ba32c.png)

The specific GraphQL query that returned the panic error is:

```
{"query":"
                query HighlightedFile(
                    $repoName: String!
                    $commitID: String!
                    $filePath: String!
                    $disableTimeout: Boolean!
                    $isLightTheme: Boolean!
                ) {
                    repository(name: $repoName) {
                        commit(rev: $commitID) {
                            file(path: $filePath) {
                                isDirectory
                                richHTML
                                highlight(disableTimeout: $disableTimeout, isLightTheme: $isLightTheme) {
                                    aborted
                                    html
                                }
                            }
                        }
                    }
                }
            ",
"variables":{"repoName":"github.com/GoogleChromeLabs/comlink","commitID":"5d1932c18c3f0b7dc480b4daf363753733d3730d","filePath":"README.md","isLightTheme":false,"disableTimeout":true}}
```

Assigning to @attfarhan as search frontend owner but @slimsag may be able to give ideas. Adding to 3.4 because this is a bug in a core feature (therefore important). I have never seen this before, so if it is rare or due to temporary deployment/infra problems on Sourcegraph.com, please backlog.

**Comment by slimsag** [comment]
1. This isn't a regression, we just fail to highlight some files. In fact, the behavior here recently improved substantially as we now return an error instead of crashing the entire syntect_server which hurt other requests.
2. This is the first case I've seen of us failing to highlight a markdown file -- quite strange. It is likely this could just be fixed by upgrading syntect, which I plan to do this version but of course that is tricky to do right.
3. I've further improved this behavior by falling back to plaintext rendering when syntect does panic, so we'll always at least get a plaintext form. This is good enough for now, so I am backlogging and assigning to myself.

**Comment by eseliger** [comment]
This file seems to highlight properly now:

![image](https://user-images.githubusercontent.com/19534377/83089298-4c11e080-a096-11ea-9d24-5efec0cb4b5f.png)

I think we can close this?
