### ISSUE TITLE
delta-indexing: faster recovery mechanism 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#35346]
A customer can opt-in to try incremental-indexing on a particular repository by setting the following environment variable:

```
DELTA_BUILD_REPOS_ALLOWLIST: '$REPOSITORY_NAME,...'
```

If something were to go wrong with search results from delta builds, they can go back to the old indexing strategy by removing `$REPOSITORY_NAME` from the environment variable. However, the customer would have to wait for all of the following events to occur before their search results would be restored :

1. `$REPOSITORY_NAME` to be popped from the indexing queue
2. however long it'd take for a full build of `$REPOSITORY_NAME` to complete 

Together, these could take several hours. It would be easier to convince customers to try this if we had a faster way to recover to a known-good state if we need to disable incremental indexing, even if it's an old state. 

Idea:

Right now, incremental-indexing's rudimentary compaction strategy consists of performing a normal build after [150 delta builds](https://github.com/sourcegraph/zoekt/blob/master/gitindex/index.go#L594-L607). Everytime we perform a normal build, we can save the original copies of those shard files in a folder named `/data/index/REPOSITORY_NAME_base_shards/`. We can hardlink those files into to the normal `/data/index` directory. If a user wants to go back to using the normal indexing strategy, they can run a `zoekt-sourcegraph-indexserver debug restore $REPOSITORY_NAME` command that will:

1. `rm` all the shards associated with the repository in the normal `/data/index` folder (e.g. `/data/index/$REPOSITORY_NAME.v16.{00000-N}.zoekt`). 
2. restore the original shard files from the last compaction by re-hardlinking all the files from `/data/index/REPOSITORY_NAME_base_shards/` back into the `/data/index`

After this, all the delta shards should be blown away. Only the shards built via the normal strategy from the last compaction should remain. 

Restoring this should be much faster than waiting for a complete reindex.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
> 1. `$REPOSITORY_NAME` to be popped from the indexing queue

This should be quick since the service will restart and the config on disk will be different to what we want to do (due to UseDelta?). We should ensure UseDelta affects the options hash.

> 2. however long it'd take for a full build of `$REPOSITORY_NAME` to complete

I agree this may take a while since our target customers likely have very large repos for this feature.

Luckily I think we have a very simple strategy to rollback to a known good state: remove all meta files and delta shards for a repository. That will restore you to a good old state. We may want something a bit smarter for the meta files, such that it still includes the usual mutable fields like public/private/stars/etc. But essentially we just want to remove tombstones and use the old repository versions.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
