### ISSUE TITLE
Code Insights: add polling when fetching an InsightView and the insight is backfilling

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#35479]
When attempting to fetch an insightView and that view is currently backfilling data, the web app should start polling until the backfill process has completed so that the user is presented with the complete view as soon as possible.

Future changes in the API will mean that all search insights will get backfilled data points instead of running the queries just in time.  This change is meant to allow those insights that run only over some repos to change from the `This insight is still being processed` state to a full display quickly and without any additional user interact.

Acceptance Criteria:
- When backfilling is complete the `This insight is still being processed` is removed without user intervention and the completed chart is visible
- Webapp polling of backfilling insights can be disabled.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@chwarwick, just out of curiosity, have you thought about GQL subscriptions? This is definitely out of the scope of this issue, but I'm just wondering, is it even possible with our current BE architecture to listen to PostgreSQL tables and push updates from the backend to the frontend through two-way transport? 

Because polling of course will work, but if we compare pooling with BE updates, BE updates would be better in all aspects.

**Comment by chwarwick** [comment]
@vovakulikov subscriptions were my first thought but it didn't appear that we had any currently in place anywhere else to reuse the pattern.  Also when I read the [apollo docs](https://www.apollographql.com/docs/react/data/subscriptions/#when-to-use-subscriptions) I felt like polling was better in this case because the polling should be the exception and not the typical behavior since it will only need to occur while the insight is backfilling.

**Comment by vovakulikov** [comment]
@chwarwick Yeah, I was just wondering because I see profit from subscriptions not only in terms of insight data by in terms of insight and dashboard configuration as well. At the moment, we can't defend ourselves from situations when some user changes the insight's configuration, and then after that, the second user changes the insight's configuration in a different way but with old other values that the first user updated in their way which the second user never got. 

This is definitely a narrow case and we shouldn't spend time on this now but just trying to understand the cost of complexity on the backend about the possibility to have subscriptions at some point in the long horizon future.

**Comment by chwarwick** [comment]
@vovakulikov I agree with you and it's been something I've been thinking about, I'm just not sure when we'll find the right thing that makes it something we need.  

I've also been looking at the `@stream` and `@defer` directives which I think would be great additions.
