### ISSUE TITLE
Detect when zoekt is using the same data dir on multiple replicas

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#35513]
#### Feature request description

The root cause of a recent [customer issue](https://github.com/sourcegraph/customer/issues/924) was determined to be the result of multiple replicas of zoekt writing to the same volume (i.e., each replica saw the same contents of /data/index).  This cost a number of hours to debug.  It would be great if there was a simple warning in the log if this condition was detected.  Or, potentially even better use hostname below /data/index by default.

#### Is your feature request related to a problem? If so, please describe.

See [customer issue](https://github.com/sourcegraph/customer/issues/924).  This problem was caused by the [customer](https://github.com/sourcegraph/accounts/issues/3) using a NFS volume.

#### Describe alternatives you've considered.

N/A

#### Additional context

N/A

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
We rely on a stable network identify for sourcegraph to consistently distribute repos amonst the zoekt replicas. It is refered to as hostname in the `zoekt-sourcegraph-indexserver` pkg. We can use this stable identity to ensure that the current index directory does indeed belong to us. A simple solution would be checking for a file in the index dir, and if the contents of the file are different to our hostname complain loudly and exit.

However, some of our deployment targets don't have a consistent hostname. This isn't a problem since they never have more than one replica. The main target here is docker single server image, but dev environments are also a likely target for changing hostnames.

As such, I think the solution is to monitor the above file and if it is mutated while we are running complain loudly.

Can anyone think of another solution? cc @sourcegraph/search-core @stefanhengl

**Comment by stefanhengl** [comment]
I like this solution. It also behaves nicely in case `hostname` changes intentionally, e.g. if we wanted to mount an index dir to another Zoekt instance or if we renamed the hosts.

**Comment by keegancsmith** [comment]
I think we should probably print a warning out when it changes on startup? This might look a little spammy for docker instances which dont have stable hostnames, but more than likely worth it to catch weird things happening in the future.

**Comment by stefanhengl** [comment]
We could log with level=debug since we don't expect an action from the user. We could then just overwrite the file if it exists and check for changes in our Run() loop.

Since separate index dirs are such a fundamental assumption we should probably just stop indexserver right away once we detect a change.

**Comment by keegancsmith** [comment]
> We could log with level=debug since we don't expect an action from the user. We could then just overwrite the file if it exists and check for changes in our Run() loop.

Agreed, debug log + overwrite on startup.

> Since separate index dirs are such a fundamental assumption we should probably just stop indexserver right away once we detect a change.

Also agreed, after startup detecting change is loud message plus exit code 1.

**Comment by jjeffwarner** [comment]
Nice preventive change. Where will this get documented for CE's reference?
