### ISSUE TITLE
RFC + approval from involved parties on the technical proposal for unified permissions

### ISSUE THREAD

**Issue by RafLeszczynski** [sourcegraph/sourcegraph#35568]

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by pietrorosa77** [comment]
It's important that everyone contributes to this so that we can speed up the process and Identify issues as soon as possible

**Comment by pjlast** [comment]
We got a lot of feedback on the RFC (found [here](https://docs.google.com/document/d/1QfpZx5ytMFeRUr7eAXAsBP91qpjMcuu7sEiEzzFWPhs/edit#heading=h.trqab8y0kufp))

We're revisiting our approach and going to try and focus on something that allows us to make decisions and do implementations iteratively, instead of trying to solve a space with many unknowns upfront.

A new RFC will be drafted at that point.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
