### ISSUE TITLE
Impossible to satisfy "find references" onboarding step

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3563]
CC @beyang 
Not entirely sure what's happening here, digging into this now

## Post-merge TODO
- [ ] Cherry-pick on patch release

**Comment by dadlerj** [comment]
It seems to be that you deleted the line that used to trigger "find refs" logging in your onboarding flow PR. Do you recall why this was deleted? If not, this might have been due to a merge conflict (my code that added refs tracking went in just a few days before this...)

**Comment by dadlerj** [comment]
See: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/1f5cb556724b167c93a6ae1099633791c44bbc9e#diff-c9cc168ddd60dd5bf8a233ce706ccf82L37

**Comment by beyang** [comment]
Hmm, I think that might have been intentional (so the activation event doesn't trigger if the user just opens up the references page). It should be triggered here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/tracking/withActivation.tsx#L166:36. I'll take a closer look at this today.
