### ISSUE TITLE
Review user feedback.

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#35653]

**Comment by marisak** [comment]
@benvenker is this the right view for feedback that's been sorted? ([link](https://sourcegraph.productboard.com/feature-board/3966092-search-product/features/7353190/insights))

**Comment by marisak** [comment]
Today @almeidapaulooliveira and I discussed saving this step for after the research topic has been defined. One of the reasons for this is that Productboard is very broad, and thus may be better suited to adding additional detail to a topic, rather than finding a topic. I'll still leave this issue open and we can move it to another epic later if needed.
