### ISSUE TITLE
3.40 container vulnerabilities

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#35774]
There are [5 CVEs identified](https://buildkite.com/sourcegraph/sourcegraph/builds/148649) for our container images.

**Comment by sourcegraph-bot-2** [comment]
Heads up @dcomas - the "team/security" label was applied to this issue.

**Comment by andreeleuterio** [comment]
@unknwon I have patched some of these vulnerabilities and justified the remaining ones in [this doc](https://docs.google.com/spreadsheets/d/16GU1meb62rfF8t2nuOoEGiSPhqDMwaaZRaVslbM30QE/edit#gid=0). This is definitely a temporary solution - they will be issues in the security-issues repo and tracked per our policies.

CVE patching became a problem again this sprint because we're finishing implementing the RFC. It is also unclear why we had been shipping with so many CVEs.

The release is approved from a security standpoint. Feel free to disable or ignore the trivy CI check (I don't know the best to proceed there).

**Comment by unknwon** [comment]
Thank you @andreeleuterio!
