### ISSUE TITLE
repo-updater 3.3 auto-migration: added lots of deleted repos to "repo" list in external service, causing major rate limit consumption

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3588]
See these comments:
- https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1556144436001800?thread_ts=1556144204.001000&cid=GDS3PJ8GK
- https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1556148331007200?thread_ts=1556144204.001000&cid=GDS3PJ8GK

I was able to reproduce this behavior myself by:
1. Running a 3.2 instance of Sourcegraph
2. Connecting a GHE instance with repositories
3. Deleting one of those repositories on GHE (but not Sourcegraph)
4. Upgrading to 3.3.1

@tsenart can you explain why these deleted repositories are kept on the instance? It caused confusion with the customer.

Customers
- https://app.hubspot.com/contacts/2762526/company/561806411

**Comment by slimsag** [comment]
This also occurred with Bitbucket Server and has more broad negative consequences, please see the section in #3594 about this (ctrl+f on that page for this issue #)

**Comment by tsenart** [comment]
#### Analysis

It's clear to me know what happened here. As they say, this was supposed to be a "feature", not a bug. So perhaps we can determine that it was a specification bug. Here's why:

Before 3.3, deleted repositories upstream didn't get deleted automatically in Sourcegraph. This meant that there could be repositories that Sourcegraph users were relying upon in search results that had been deleted in the code host (or just became invisible to the provided token).

To be on the safe side, the thinking went, we needed to ensure that **enabled** repositories that would be deleted by the syncer were added to the `repos` list, so that admins could review it and handle these cases one by one when upgrading to 3.3.

This migration logic was specified here: https://docs.google.com/document/d/1q3VIsDP5u23luncbm-h7oc9v8mSQCqoiFcpN1tf2oMk/edit?disco=AAAACm2aTkk

In retrospect, there are two things we didn't consider:

1. Admins needed more thorough documentation on this particular bit of migration logic.
2. That code host APIs would consume rate limit quota on non existent repos (404s).

Additionally, with the user feedback we now have, it seems like it was actually overly cautious to keep these repos around. We thought there would be far less of them because admins would have disabled (or deleted) repos in Sourcegraph that had been deleted in the code host.

#### Next steps

The customer feedback we had validated that this behaviour is in fact undesirable. We could add all of these deleted repos to the `repos` list but commented out, but I'm not sure anymore if there's any value in that.

So I suggest we simply eliminate this bit of migration logic. I'll send a PR up for everyone in US timezone to review when you come online. We can then confirm together if that's the right approach.
