### ISSUE TITLE
Crashes caused by ctags not running in sandbox mode.

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#36107]
On large files we can get OOM errors from ctags which cause other processes to fail. We are unable to run ctags in sandbox mode because it is deployed via Docker. The suggested path is to migrate this work to executor which is also used by batch changes and code intel.

_migrated from this for sync notes_

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
There are two issues in this issue. One is ctags OOMing / being unreliable. The other is security since it doesn't run with sandbox mode.

unreliable: I'd consider adding more heuristics around which files are allowed to be passed to ctags. EG a max file size/etc. @chrismwendt work on rockskip with megarepo/gigarepo has likely had him see a few issues with ctags. Did you implement any rules around skipping files / reliability?

For security executors is one way to get this done. However, it is a lot of moving pieces / complicated. Another option is looking into deploying the correct profile just in our clusters so we can use the sandbox. Then provide this as an optional overlay. Customers normally do not index untrusted code, unlike us.

**Comment by chrismwendt** [comment]
- Where are you seeing these errors?
- Is the OOM in the ctags process, or the symbols process?

Considering that we're never sending files over ~500KB to ctags:

![CleanShot 2022-05-27 at 13 49 59](https://user-images.githubusercontent.com/1387653/170780782-2b7360d7-90a1-45ec-a326-da38f2bc68ab.png)

I would guess it's not ctags that's OOMing but rather the symbols process. If we can narrow it down to that, then I bet the root cause is that the symbols process is loading a big file from `git archive` into memory and OOMs. The current file size limit is only enforced after loading the file, but we could move it to before loading the file by checking the tar header.

**Comment by chrismwendt** [comment]
I'm adding a max file size check on the tar headers in https://github.com/sourcegraph/sourcegraph/pull/36199

**Comment by keegancsmith** [comment]
@chrismwendt this is in zoekt. We are not seeing crashes at the moment, except that disabling ctags indexing in the gigarepo lead to zoekt successfully indexing it. This means either ctags or how zoekt handles the output of ctags was chokinjg it.

This issue is about sandboxing ctags since it is written in C and is a security risk. It has crashed in the past due to classic c footguns, like buffer overflow. For example it hardcoded maximum path length (which is a windows thing), which meant long file names would overflow the buffer. We worked around this by limiting filename lengths in go-ctags. But this is likely the tip of the iceberg.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
