### ISSUE TITLE
zoekt: incremental-indexing: properly update LatestCommitDate metadata in older shards 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#36330]
When Zoekt performs an incremental build, it updates the [branch/commit and FileTombstones](https://github.com/sourcegraph/deploy-sourcegraph-cloud/commit/3c749ddf40aec68adeff92f5773fe44dc4df6a85) metadata in all the repositories prior shards. 

However, it doesn't update the[ `LatestCommitDate` field](https://sourcegraph.com/github.com/sourcegraph/zoekt@6c563dc28bcad305aecb33fbada2229773ff38ee/-/blob/api.go?L315:2#tab=references). This metadata is used by other product features, so we should tweak incremental indexing to support updating this field.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
cc @stefanhengl who added this field just to confirm its important to keep the value consistent and up to date across shards for a repo.

**Comment by stefanhengl** [comment]
LatestCommitDate is used by shard merging to decide whether a repo is stale. We also use it decide which tombstoned repo we restore if there is more than one. Since we never merge repos with more than 1 shard, an inconsistent LatestCommitDate shouldn't make a difference.

However IMO it would be desirable to keep it up-to-date anyways. Otherwise this might lead to difficult to track down bugs down the line.

**Comment by keegancsmith** [comment]
Aah ok, I thought we had a search feature that relied on it. But I agree it is good to keep up to date, especially if we start exposing this information to admins.
