### ISSUE TITLE
monitoring: ensure critical alerts are a reliable signal of Sourcegraph instance health

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#36434]
As a follow-up to https://github.com/sourcegraph/sourcegraph/pull/36423 , we should audit existing critical alerts that for their signal-to-noise ratio and the completeness of the `PossibleSolutions` (or next steps docs).

**Comment by bobheadxi** [comment]
cc @michaellzc who mentioned DevOps might have a list of sorts

**Comment by michaellzc** [comment]
A few on top of my head

### [postgres-transaction-durations](https://docs.sourcegraph.com/admin/observability/alert_solutions#postgres-transaction-durations)

- not actionable. it should at least reference our postgres-conf page where operator can tune the configuration
- there's a flaw in the pg-exporter metrics we are utilizing and it doesn't expose sufficient information about the long-running transaction. If requires connecting to the database and run some query to gather additional information. In fact, we found it's just autovacum process doing its work (a long-running transaction). Whether autovacum has any real impact on system performance, that's a different problem https://github.com/sourcegraph/customer/issues/903

### [frontend-page-load-latency](https://docs.sourcegraph.com/admin/observability/alert_solutions#frontend-page-load-latency)

We've seen this happen a few times and we confirmed resource utilization is super low

> Explore the data returned by the query in the dashboard panel and filter by different labels to identify any patterns

The dashboard is not helpful and doesn't reflect what is slow

> Trace a request to see what the slowest part is:

- tracing is not enabled by default, so it's hard to reproduce the issue unless users report the issue to the operator
- it's not feasible to enable jaeger by default because it consumes a lot of memory in a large deployment.

### [repo-updater-github-rest-rate-limit-remaining](https://docs.sourcegraph.com/admin/observability/alert_solutions#repo-updater-github-rest-rate-limit-remaining)

We've seen this error quite frequently on large MI. 

> Try restarting the pod to get a different public IP.

Not really a good solution. Restarting the pod doesn't guarantee a new public IP, and it's possible customers are using a public gateway (e.g. Cloud NAT) with VM without a public IP address. Also, I thought github is rate-limiting by access token, maybe we can ask the operator to rotate the access token or something? 

> Notes: 
> - most alerts from my list that are confusing are actually warning level, but let's focus on the critical level first.
> - some warning alerts feel more important to me, such as permission syncing.

**Comment by bobheadxi** [comment]
> [postgres-transaction-durations](https://docs.sourcegraph.com/admin/observability/alert_solutions#postgres-transaction-durations)

This was removed in https://github.com/sourcegraph/sourcegraph/pull/36423 ✅

**Comment by bobheadxi** [comment]
> [frontend-page-load-latency](https://docs.sourcegraph.com/admin/observability/alert_solutions#frontend-page-load-latency)

Two parts here:

> The dashboard is not helpful and doesn't reflect what is slow

Does [this documentation help](https://docs.sourcegraph.com/admin/observability/dashboards#frontend-page-load-latency)? That said, following it does not give what I might expect (why does gitserver have page load latency?):

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/23356519/172257717-7bce3974-9029-4230-8524-c2f243221c75.png">

cc @sourcegraph/iam-and-admin-experience , since the ownership points to y'all (redirect on https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/saas)

> it's not feasible to enable jaeger by default because it consumes a lot of memory in a large deployment

Isn't Jaeger always enabled by default?

https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/4bcdf13c979f34fb3443dfaed0ce06c257e6d6b4/docker-compose/docker-compose.yaml#L517-L525

Is this the issue volume of tracing? Don't we have [sampling enabled](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/schema.go?L1261-1262) to reduce the volume? IMO if we want to lean on traces (and many teams do, I think at least search does), traces should be enabled by default on managed instances

**Comment by bobheadxi** [comment]
> [repo-updater-github-rest-rate-limit-remaining](https://docs.sourcegraph.com/admin/observability/alert_solutions#repo-updater-github-rest-rate-limit-remaining)

> Also, I thought github is rate-limiting by access token, maybe we can ask the operator to rotate the access token or something?

This seems easy enough to action - preparing a PR with an updated recommendation to create a new machine user.

I'm also wondering if we can add a `.For` on rate-limiting alerts - brief outages are likely not critical, since Sourcegraph should continue working with what it has sync'd already. cc @sourcegraph/repo-management for thoughts - I'm thinking this can maybe be increased to 90 minutes (i.e. if after a 1-hour window, the rate limit rests _and_ we immediately hit a critical threshold again, then it is a serious issue)

**Comment by michaellzc** [comment]
> @michaellzc All the alerts you've raised have been addressed for now - are there any other alerts that we should look at to remove the need for #36321 in the next release?

I think all concern regarding critical alert should be addressed now, thanks so much for making all these PRs!

I think the next step would be reviewing our warning-level alerts

- what warning-level alerts are in fact critical-worthy
- what improvement can be made to "next steps" for warning-level alerts

thoughts?

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@sourcegraph/cloud do we still want to do this and if yes when would be the right to do it and as part of what initiative?

**Comment by bobheadxi** [comment]
Closing as done - initial rounds of alerting cleanup was done, there is no need to keep this open in the long run
