### ISSUE TITLE
insights: sort or limit changes can cause deselected series to disappear and remain deselected

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#36501]
It is currently possible to end up in a dead state chart between the interactions of selecting / deselecting series for view, and sort / limit. This occurs because we do not reset the select / deselect state on sort / limit change, which means its possible for _all_ of the limited series to be removed from the legend. A naive implementation might be to reset the select / deselect state when any sort or limit change occurs, but this will likely run into UX issues where a limited number of series are selected for view intentionally, and sorting may be desirable. An alternative might be to track if any deactivated series is ever removed from the legend, to reactivate it.

As a note, it's also possible this is just another manifestation of https://github.com/sourcegraph/sourcegraph/issues/36461 and will be fixed with the same problem, depending on implementation.

![CleanShot 2022-06-02 at 10 27 56](https://user-images.githubusercontent.com/5090588/171688899-cd3969b2-2d01-4888-b549-501229a5b79f.gif)

**Comment by unclejustin** [comment]
Note to me: the state here is getting out of control. It is worth looking into some combination of zustand and fsm to store and manage this state at this point. This implies more work than it would seem to handle this issue.

I think the extra work is worth it though considering the number of state management-related issues I've just worked on in this area for the last iteration.

Heads up @Joelkw I'm sizing this an 8 because, like L'Oréal, it's worth it.

**Comment by Joelkw** [comment]
Note from sync: we may need to scope this down to get into the release, or re-evaluate how we approach this issue, given it's an 8 and release cut is Friday.

**Comment by unclejustin** [comment]
Spoke with @vovakulikov . We're just going to fix the issue directly and ignore the growing complexity 🎉 💀 . We can come back to this debt later.
