### ISSUE TITLE
Add F# support

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3677]
Some folks have requested F# support. Please follow this issue to get notified about updates.

The full list of currently supported languages is at https://sourcegraph.com/extensions?query=category%3A%22Programming+languages%22.

**Comment by danyx23** [comment]
Thanks for creating this issues so quickly! For F# there is a editor agnostic backend that is used by the popular plugins to parse type information etc: https://github.com/fsharp/FsAutoComplete . I don't follow the developments too closely, but AFAICS the maintainers of the Ionide VS Code plugin (and probably FsAutoComplete as well?) are planning to move to the LSP soon https://github.com/ionide/ionide-vscode-fsharp/issues/1075 which might make this integration easier.

Very much looking forward to having F# support in sourcegraph since that is our primary development language :)

BTW here are a few public F# repositories for testing:
https://github.com/demystifyfp/FsToolkit.ErrorHandling/
https://github.com/fsprojects/Argu/tree/master/src/Argu
https://github.com/fsharp/FSharp.Data

**Comment by scalabilitysolved** [comment]
@macraig do we want to track language requests in github?  Perhaps we can add a specific column/area for it if we feel it gives us meaningful signal.

**Comment by macraig** [comment]
We're currently tracking language requests in Productboard, I'm adding this feedback there and close this.
