### ISSUE TITLE
Add tooltips for state icons in WorkspaceDetails component

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#36799]
![image](https://user-images.githubusercontent.com/19534377/172645737-d595a2bb-3ae5-4906-805b-73d533e1268d.png)

These currently don't have tooltips. Consider adding some to states that aren't 100% clear.

**Comment by courier-new** [comment]
This is actually a bug. They [have tooltip data](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@kr/center-show-more-button/-/blob/client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx?L595%3A17=), it just doesn't seem to trigger on hover.

**Comment by courier-new** [comment]
I took a close look at this and figured out it's because of how `Collapsible` is implemented. The collapsible button adds an `::after` pseudo-element so that the clicking anywhere on the row can trigger it to expand or collapse, but then that `::after` eats the hover event. Demo:

https://user-images.githubusercontent.com/8942601/173502350-feadc5af-4b26-4453-a17f-55fd3dba8c1d.mov

In that case, I'm not sure what the solution should be. 🤔 If we want to keep the existing behavior where the whole row acts like the collapsible toggle button, the `Collapsible` component needs to refactor to not implement that with `::after`, which is probably not something our team should own. We could consider making only the carat button the toggle or something, which would give us back the hover states and only require adding a prop to `Collapsible`, but then we're introducing inconsistent `Collapsible` behavior across the app.

In either case, I think this is probably more like `1-2d` depending on the solution.

**Comment by eseliger** [comment]
I think I saw this problem elsewhere, too actually. I think we should file this and hand it off, given it's a global component. It also happens in our timeline modal for example :) Estimate sgtm
