### ISSUE TITLE
repo-updater duplicate repo issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3680]
In some customer deployments we've observed a problem where duplicate repos somehow end up appearing after `NewDiff` and they prevent repo-updater from doing its job properly. See customer issue for further details.

**Comment by keegancsmith** [comment]
For interest sake the root cause was quite tricky and we came across a few issues while fixing this:

* We would fallback to associating repos by name if external ID lookup fails. This should only be done for repos which don't have external IDs. This is the most likely root cause for the customer.
* Our SQL logic would not allow us to do renames where intermediate updates would have a name conflict. TIL that unique constraints are enforced at row level. We learnt we could enforce it at the statement level and our SQL logic worked again: https://begriffs.com/posts/2017-08-27-deferrable-sql-constraints.html
* A soft deleted repo name could conflict with a visible repo name. We debated a few ways to solve this, but finally settled on just hard deleting repos to avoid the conflict.
* Our SQL upsert logic should of just worked on IDs, instead of doing its own form of rename detection.

We have fixed all of this in https://github.com/sourcegraph/sourcegraph/pull/3745
