### ISSUE TITLE
compute: preserve compute query semantics when regenerating modified query strings

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37173]
Code Insights does some [tree manipulation of Sourcegraph queries](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/querybuilder/builder.go?L17) to ensure that various fields (such as fork and archive) are set appropriately if not defined. This tree is converted back into a human readable query and is queued for processing.

When a compute query is converted the semantics of the `content` field are not preserved and therefore the query parser does not currently preserve identity for compute queries (`Q` -> `Q`). Example:

```
mystring content:output(x -> $lang)
```

After the query parser operations the explicit `content` will get replaced with an implicit `content` and will fail to parse in compute.
```
fork:no archived:no (output(x -> $lang) AND mystring)
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by rvantonder** [comment]
We'll need to get specific about what we're talking about, because it sounds looks like there are some big misunderstandings here.

> Code Insights does some [tree manipulation of Sourcegraph queries](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/querybuilder/builder.go?L17) to ensure that various fields (such as fork and archive) are set appropriately if not defined.

Indeed, I see that. what are these Sourcegraph queries? They look like search queries to me. Remember, search queries and compute queries are not the same. Compute queries build on top of search queries. They are not the same. If you send a compute "string" to this code, which treats it _like_ a search query (i.e., [I see it is parsing it as a search string](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/querybuilder/builder.go?L18)), it is going to be interpreted _as_ a search query. Not a compute query. It's only possible to compute behavior (i.e., input strings to be interpreted as compute queries) when you parse them with the compute query parser. Not the search parser.

> When a compute query is converted the semantics of the content field are not preserved and therefore the query parser does not currently preserve identity for compute queries (Q -> Q)

It sounds like there is an assumption that this code treats an input string as a compute query (maybe by virtue of it having the syntax `content:(x -> y)`). This is absolutely not the case. The code treats your input string based on the parser that parses it. If you parse a string to a search parser, it is going to treat it as a search string. In this case, the syntax of

```
mystring content:output(x -> $lang)
```

and 

```
fork:no archived:no (output(x -> $lang) AND mystring)
```

are indeed perfectly equivalent and correct!

Moreover, this [code returns the string equivalent of the search string, and again correct,](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/querybuilder/builder.go?L36). The type of `Q` is a search query. `Q` cannot be a compute query, that's a different type. There is actually no `StringHuman` implemented for compute queries yet, that I know of (e.g., one that would preserve `content:(...)`). The point is that such a query printer should exist on the compute query type, not `Q`, the search query type.

So I'm questioning where the assumption is that "a compute query is converted". No compute query is converted by this code. It is already treated _as_ a search input string by the time it reaches this function. 

there is no notion of it being a compute query string at all here. That's only possible if it goes via the compute endpoint/parser/logic.



Compute semantics is only valid when you use the compute parser/logic to process the input string. Search logic and parsing will not, and should not, ever make any assumption about whether an input string is a compute query or "pure search query". It is always a pure search query.

**Comment by rvantonder** [comment]
So my feedback on the high level problem is: you can't manipulate the search query string after it's processed by compute, then use the search query printer and expect to get compute query string back. The decision was made in that code to manipulate a search query string (which in this case happens to be the output of a compute query) and then treat the output as something that is not a search query (i.e., map back to a compute query). There's no way or need for a type `Q` to know or persist any of this intent. 

It would be better to manipulate the compute query instead, and then perform whatever search behavior part of it needs running. So this sounds like a "query builder for compute queries" situation, not a "reuse query builder meant for search and have it work seamlessly for compute based on some query syntax". I am not familiar with how the querybuilder stuff works though.

**Comment by coury-clark** [comment]
From slack:

From @coury-clark 

> Thanks for the input -  I think I understand the confusion I had, basically assuming that a compute query is just an extension of the search language and therefore the search parser would work the same.
The problem we face is that we want users to enter valid Sourcegraph queries (or compute queries in some cases) but we want to be able to manipulate them to enforce defaults depending on what the system is doing (fork:yes archive:yes as an example). I wasn’t aware of this separate parser before so I’ll take a look and see if we can accomplish what we need. If not, I’ll be back with more questions

From @rvantonder 

> cool, what will probably work best is:
[Parse the input string as a compute query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/compute/query.go?L283). You get back Parameters []query.Node . You can add additional parameters here (i.e., add field:value nodes, not patterns), and then either rely on the thing running that command to take those additions into account, or you can get a pure search string query back out of it by calling ToSearchPattern() on the command part of the result after parsing and then do whatever with that search input string. If you're just adding archive:... stuff though I would add a helper that takes a compute query as input and spits out a compute query, and all it does is append to the Parameters []query.Node value (avoid inlining direct mutations).
There is another option, to piggyback on the search query visitor/parsing to create a tree, manipulate any which way, but preserve/hold-to-the-side only the content part, then reintroduce the content part to reconstruct compute syntax. Writing a helper that abstracts away those internal details is potentially the cleanest, but not as easy as a quick helper like ^
