### ISSUE TITLE
References panel displays results from old revisions/commits

### ISSUE THREAD

**Issue by plibither8** [sourcegraph/sourcegraph#37311]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS Monterey, Google Chrome v102

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.tsx?L229
2. Hover over `ExecuteWorkspaces` until code intel dialog opens
3. Click on `Find references` to open the references panel

#### Expected behavior:

Search results for the references should be retrieved from the latest commit on the `main` branch of the repo, and no older commits.

#### Actual behavior:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/31861755/174023064-af807397-42b6-4371-a52d-12b55e60b405.png">

* Under the same filename (`client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.tsx`, for example), the multiple results seem to be coming from different revisions of the same file. The file contents of the result on line 229 are different from file contents of the result on line 210.
* As consequence (I’m guessing), the results are not sorted by line-number, and at first glance seems to be pretty arbitrary.

Also:
* [link to the result on L229](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@12fba40034277d11e829c071b4f06995aa0f64ec/-/blob/client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.tsx?L229:30-229:49) has the commit hash 12fba40034277d11e829c071b4f06995aa0f64ec.
  * This commit is the latest right now on the main branch
* [link to the result on L210](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f2b6d58044351d5c6152d6bbf163eb54c215ec8a/-/blob/client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.tsx?L210:34-210:53) has the commit hash f2b6d58044351d5c6152d6bbf163eb54c215ec8a.
  * This is a [14 day old commit](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/f2b6d58044351d5c6152d6bbf163eb54c215ec8a?visible=2).

**Comment by chrismwendt** [comment]
With the old ref panel, the same file shows up multiple times:

![CleanShot 2022-07-19 at 16 49 30](https://user-images.githubusercontent.com/1387653/179861643-911f95ea-4e57-4e22-8e16-40fca4c586c9.png)

This might be caused by having multiple LSIF/SCIP dumps for the same language on the same repo:

![CleanShot 2022-07-19 at 16 57 59](https://user-images.githubusercontent.com/1387653/179862129-425c75cb-a2d4-4938-8c92-f4a12c30fdc2.png)

The backend merges results from all visible dumps, so that part is working as expected.

Potential ways to fix this:

- Delete old dumps manually
- Wait for the retention policy to delete old dumps
- Classify indexers in such a way that the 3 TypeScript indexers are considered to be the same so that the merging logic only includes 1 of them

Thoughts on which one to proceed with, or any other ideas? 💭

**Comment by chrismwendt** [comment]
I deleted the dumps matching `lsif-typescript` from Sourcegraph.com. I'm not seeing the duplicate hits, but I'm also on the new ref panel and can't figure out how to disable it anymore (maybe the old one has been removed by now).
