### ISSUE TITLE
Resource Estimator: Update existing calculator

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#37338]

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.

**Comment by abeatrix** [comment]
# Progress update: 
Rewrite completed. I will work on estimation for disk spaces for external services next. 
![image](https://user-images.githubusercontent.com/68532117/175428417-81529309-5247-4606-a8b2-34ed6054bd91.png)

I've organized the data from the old google sheet and looked through the old slack thread, salesforce, looker and github issues to get some of the missing data in order to get a better picture of how our customers deployed their instance
Data used for the rewrite has been moved from the [my working google sheet](https://docs.google.com/spreadsheets/d/1ftJ-Z88tS-J39xci5SW29povXcsLLlkXMTbo1ccKBcE/edit#gid=1171581380) to the [centralized google sheet](https://docs.google.com/spreadsheets/d/1N7X_OXDwKk0QSR2Ghbj7ZhjVrQXcMNj-yC8mF1amBi4/edit#gid=609023588)

**Comment by abeatrix** [comment]
Work related to the resource estimator that needs to be done: 
- [ ] update go version in the estimator repo ([for more detail](https://sourcegraph.slack.com/archives/C07KZF47K/p1656010650156479))
- [ ] update links in current doc to use new go version
- [ ] docs update
