### ISSUE TITLE
Error on initial start: "Setting up postgres failed"

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#374]
- **Sourcegraph version:** 2.11.2
- **Platform information:** (appears to be Windows)

A user reported a postgres error on Sourcegraph initial startup:

![image](https://user-images.githubusercontent.com/5589410/46846885-8f6eec80-cd96-11e8-9883-fda5c353c1d6.png)

**Comment by dadlerj** [comment]
@felixfbecker have you ever seen anything like this running Sourcegraph on Windows?

**Comment by felixfbecker** [comment]
I tried reproducing but I ran into different errors: #380 #381

**Comment by 40rn05lyv** [comment]
I experience this issue in Windows 8 + Docker Toolbox.

**Comment by 40rn05lyv** [comment]
I tried to perform steps from my comment here: https://github.com/sourcegraph/sourcegraph/issues/381#issuecomment-429577461 , however now I have another exception:
![image](https://user-images.githubusercontent.com/1200215/46910519-a2c4b800-cf4e-11e8-836f-72abf67021ed.png)
I suppose it can be caused by pseudographic symbols that is used to show sourcegraph logo (see https://github.com/docker/toolbox/issues/695#issuecomment-356218801 )
