### ISSUE TITLE
Remove MemoryRouter from ReferencesPanel as it blocks React Router v6 migration

### ISSUE THREAD

**Issue by oleggromov** [sourcegraph/sourcegraph#37489]
## Context
The @sourcegraph/frontend-platform team is now [migrating from Router v5 --> v6](https://github.com/sourcegraph/sourcegraph/issues/33834). This includes staring using `CompatRouter` first to wrap all sub-routes, and later replacing all `Router` and `Route` components with the new versions.

There was also a [crash on dotcom](https://sourcegraph.slack.com/archives/C01LTKUHRL3/p1655395878523209) related to this update.

## ReferencesPanel
However, one of @sourcegraph/code-intel's features, ReferencesPanel, is using MemoryRouter internally (inside the global Router) to support navigation via standard `Link`s without affecting app's global nav state. 

Unfortunately, rendering a MemoryRouter inside a Router in v6 doesn't work anymore, and [the following code](https://gist.github.com/oleggromov/ec7fe2c7ed3f4fb37b33f8a2ec1c25ec) will throw an exception.

### What could we do?
- Reimplement the same functionality without MemoryRouter (tricky and expensive to do)
- Get rid of this implementation of ReferencesPanel and think of something else
- ...

**Comment by oleggromov** [comment]
cc 
@jasongornall 
@scalabilitysolved 
@mrnugget

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by mrnugget** [comment]
Let me add more context on how the `MemoryRouter` is used.

The `MemoryRouter` is used to allow clicking on tokens in the small code preview window without navigating away from the current page. Here's the feature in action:

https://user-images.githubusercontent.com/1185253/174972899-ecd3683f-73ca-4702-956e-84fe849ef212.mp4

The whole reference panel is URL-based, it gets all of its initial state from the URL. That keeps it backwards compatible with the old panel and our hover tooltip buttons.

The `MemoryRouter` was a really neat way to implement the clicking-on-tokens-in-preview-window (as suggested by @umpox), because we could just overwrite the click inside the `Blob` and push the URL of the new token to the `MemoryRouter`. Since the panel is URL-based, it would show the defs/refs of the just-clicked token, without navigating away.

I think it's a _really_ nice feature. I like it. I also think it should be extended to mirror what [cs.opensource.google.com](https://cs.opensource.google/go/go/+/master:src/bytes/buffer.go;drc=master;bpv=1;bpt=1;l=30) does and _keep track of which tokens_ were clicked.

But I also told @oleggromov that maybe nobody uses that feature and we could remove it to help with this migration. Again: I'd hate to see this feature go, but if it's blocking a technical migration and it's only used by myself and 2-3 other users, it might not be worth it.

Or maybe there's an easy way to keep implement the feature without `MemoryRouter`: we'd have to replace the `useHistory()`/`useLocation()` calls to something like `useCurrentURL()` and have a way for the blob preview view to push a new URL to internal state that is then returned by `useCurrentURL` and causes a re-render.

**Comment by macraig** [comment]
@oleggromov would this be a blocker for shipping the ref panel?

**Comment by mrnugget** [comment]
If I understood @oleggromov correctly last time we talked, it wasn't a blocker for shipping the reference panel. But I'll let him decide.

**Comment by oleggromov** [comment]
Hi @macraig and @mrnugget it is not a blocker for us to ship the reference panel.
However, it will block the Router migration that may or may not be under way currently so I'll ask @jasongornall to confirm what the current plan is. If we're not directly interfering with the @sourcegraph/frontend-platform's plans, should be ok.

**Comment by felixfbecker** [comment]
Was this done?

**Comment by olafurpg** [comment]
The ref panel uses `H.createMemoryHistory` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2205a55f060d1e2501bdb5767622962ab58aa36c/-/blob/client/web/src/codeintel/ReferencesPanel.tsx?L695) but it can be replaced with a mutable string variable because we only use `history.replace()`, we don't use it for actual history.

**Comment by felixfbecker** [comment]
What do you mean with "replaced with a mutable string"?

**Comment by olafurpg** [comment]
Badly worded, I meant that we can replace it with `useState("")`. We don't use the history functionality, we only need one string variable to know the URL of the preview pane.
