### ISSUE TITLE
Test (client/jetbrains) CI job failing with `gulp not found` 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#37548]
Investigating this [build](https://buildkite.com/sourcegraph/sourcegraph/builds/155907#01818aa0-316e-47d8-9cfd-8791700641a6/143-145) showed that this particular job doesn't work if the cache isn't available. 

```
[node_modules] - 🚨 Cache restore is skipped because s3://(...)/sourcegraph/sourcegraph/cache-node_modules-3f21cee23df6eba8d19bc1da7c6176d16f8a859e.tar does not exist
```

Looking at the bucket holding the cache, we can see that that specific file was created after this particular job was run. And when @umpox retried the job, it was present, so it worked this time. 

<img width="907" alt="image" src="https://user-images.githubusercontent.com/10151/175029534-3d495134-1ea3-4e27-bb8e-076616e7a99d.png">

The other tests are all using `yarn-run.sh` or `yarn-test.sh` which addresses this particular problem. 

➡️ Solution is probably to use one of these scripts.

**Comment by philipp-spiess** [comment]
I looked into it and posted #37596 as a fix.

Seems like we weren't running `yarn` to install dependencies before we used them 🤦 

I looked into `yarn-run.sh` as well but we need to run a command in a different directory (much like the VSCode scripts) and since `--cwd <dir>` would need a lot of special casing I decided instead to just copy what VSCode is doing.

Thanks for notifying us about this! PR is here: https://github.com/sourcegraph/sourcegraph/pull/37596
