### ISSUE TITLE
JetBrains: Right click on search results should provide a proper context menu

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#37811]
At the moment it just shows "Nothing here", we should provide some useful actions (e.g. open file, share link etc.

<img width="1667" alt="Screen Shot 2022-06-28 at 09 29 41" src="https://user-images.githubusercontent.com/2660760/176120027-9788edc0-59b8-4863-a725-90a38a8d77e9.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
It's strange that this doesn't even get the default "copy" actions etc. Let's see if we can find out where to customize this 😐

**Comment by vdavid** [comment]
Minimum effort: just turn off the context menu altogether.

Nicer solution: add "Open in Editor" / "Open in Browser" menu items to the preview context menu.
Even nicer: also add "Open on Sourcegraph" and "Copy Sourcegraph Link to File" actions

**Comment by jjinnii** [comment]
Sorry I know we closed out this issue, so feel free to create a new one but wanted to ask first. Thoughts on adding a "Go to File" or some equivalent in this menu? 

Part of the feedback from the user test was that since we don't support clicking the Preview to open the file (and I think this could prove annoying within an editor too so I don't think we want to do this), it was unexpected that we don't have a right click go to file/go to line behavior. 

cc: @ryankscott @philipp-spiess @vdavid

**Comment by jjinnii** [comment]
@philipp-spiess Ah yes, that was! Sorry I missed in the PR. 😅 A small suggestion - Could we change the re-ordering so "Open File in Editor" is first? I think it makes sense to put the functionality that's more core to the IDE experience first, versus a re-direct outside to web!
