### ISSUE TITLE
Show scopes below search bar when looking at file/repository

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#3783]
Is there a specific reason for why scopes only show up on `/search`, when constructing a new query and/or looking at search results, but *not* when looking at a file/single search result?

I'm asking because what I find myself doing often:
1. construct search query, using scopes
2. browse through results
3. click on result, think "nope, that's not it"
4. jump to search input in order to refine the query

but now I can't access the filters/scopes anymore.

I think it would be great if a user has access to the scopes/filters whenever they can access the search bar. Especially since the executable (!) scopes/filters are often much better at helping to construct a query than the help tooltip is.

**Comment by sqs** [comment]
Yes, an overall design for search that accommodates this would be very nice. The current design won't accommodate it very well because:

- the search query changes to the `repo:CURRENT_REPO@REV` you're viewing, not your query, when you jump to a file
- they would take up vertical space

There are many outstanding search design issues, and I'll consider this to be one of the goals of the new improved design. (ETA? Not sure.)
