### ISSUE TITLE
insights: support only snapshots for compute type insight

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37868]
Note: this is for a retrofit of our current API

The mechanics of the first version of the compute type insight are such that we want only the current (within a day) values, and only a single value. Since the current API returns timeseries, we will want to purge the old data each day so that the response can be naively inspected to construct categorical charts (bar, pie, etc). For this purpose, we will reuse the snapshot functionality.

When we create a compute type insight we will need to do the following:
1. Prevent any backfilling other than the current time (mark backfilled completed, and possibly queue up a snapshot)
2. Disable interval recording (set the next_interval value to something impossibly far in the future?)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
@coury-clark after working on this a little, there's one thing to raise: there's the issue of the insight card displaying "This insight is still being processed" while the query gets completed, because of the way this is calculated on the frontend (`pending jobs > 0 || backfill_queued_at == nil`)

right now to implement the main logic I've done this:
1. set `backfill_queued_at` to `NOW()` and `next_recording_after` to far off in the future (31/12/9999)
2. stamp the series as snapshot-ready (to `NOW()`)

because of 2), this means that before the series is picked up as ready to be snapshotted and queries are enqueued, there is a lapse of time where the the insight card shows "No data to display" 

so from what I see we have two options:
1. we enqueue the snapshot from the `insight_store` rather than just stamping the series as ready to be snapshotted, which means the frontend will pick up the job as "pending" (this involves probably exporting the [`enqueue` function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/insight_enqueuer.go?L92))
2. we do not set `backfill_queued_at` to `NOW()` but instead make a new [`GetDataSeriesArgs`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/store/insight_store.go?L345:6) argument like `ExcludeGroupBy` so that compute type insights do not get picked up by the historical backfiller [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L369).

I'm laying out my thoughts here as this is the first compute-type issue I'm picking up and I might be missing some of the bigger picture/future changes we're making, so let me know what you think of the options!

**Comment by coury-clark** [comment]
Thanks @leonore - good call out. I think 2. is similar enough to the [approach we use for backfilling scoped insights](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ef8c98dc81120e68c25626171453534ff7480942/-/blob/enterprise/internal/insights/resolvers/insight_view_resolvers.go?L1062:11) that it would make sense to adopt the same pattern. I think some kind of an operator that can manually queue up a snapshot would be useful. I seem to remember having a branch with something like this recently, but I can't find it. At some point I built a tool that could do operations such as:
`QueueSnapshot`
`QueueRecording`

I think something along those lines would be useful in general, and specifically solve the problem listed above. Would you like to add that to the scope of this issue (or open a new one)?

**Comment by leonore** [comment]
I guess my question to you then @coury-clark is how the tool for `QueueSnapshot` and `QueueRecording` would be any different from simply exporting our existing `enqueue` function?

I've opened a PR (#38294) that has a fix for this, and I went around the queuing operation by exporting `InsightEnqueuer` and its `Enqueue` (and derived `EnqueueSingle`) function. we can move discussion there if there's need for any!
