### ISSUE TITLE
Should Sourcegraph do stable search result ordering?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3791]
Today, Sourcegraph's search results are optimized specifically for fastest-time-to-result. The assumption is that most users care about getting results quickly rather than in some defined order. As such, it is often the case that if you search turns up a lot of results (more than can fit on the page) the order of the results will change on page refresh.

While this has been an intentional design decision on our part, I would like to challenge it because I have seen multiple users from our customers, and even us regularly confused by this behavior. We've also seen multiple reports of it not being great for API consumption. So, open questions:

- Does it make sense to do stable search result ordering? Is there a better way to communicate that we don't in our UI?
- How much slower would search actually be if we provided stable search result ordering?
- What amount of additional time would have to be spent on indexing to perform stable search result ordering?
- If we spent the time to invest in stable search result ordering, would it eliminate desire for other things like search result streaming?

Please discuss and help link any relevant past feedback from users.

**Comment by keegancsmith** [comment]
> Does it make sense to do stable search result ordering? Is there a better way to communicate that we don't in our UI?

Stable in the sense of as you incrementally change a search, the first seen results are stable. Or stable across time given the same query and commits search?

> How much slower would search actually be if we provided stable search result ordering?

There are tricks we can do. The simplest implementation of just finding all results and sorting results in a _much_ higher memory usage and is likely a lot slower. I think instead we could deterministically pick the order of repos and files we search to get the same result. However, given searcher's caching nature the results will be unstable until all commit archives are cached. I'm sure there are other tricks we can think up which avoid making search non-interactive.

> What amount of additional time would have to be spent on indexing to perform stable search result ordering?

FYI Zoekt isn't stable either. It's just _more_ stable than the rest of our search stack. It is more stable since it is deterministic (excluding timeouts) once searching in a shard.

> If we spent the time to invest in stable search result ordering, would it eliminate desire for other things like search result streaming?

I believe search result streaming is easier to implement, simpler and will do things like reduce memory usage. So if streaming solves our customer issues I would think it is preferred. However, that is just a gut feeling without thinking through the other problems streaming may bring up.

**Comment by tsenart** [comment]
There has been some recent discussion around this topic here: https://docs.google.com/document/d/1U2IpbO7mlPV8AxLy2LQ0_Tl-bUAy63lBRCUZ0feHL5Y/edit#

cc: @ijt

**Comment by ijsnow** [comment]
I'm not convinced that stable result ordering and streaming are mutually exclusive. I think a good path forwards would be to make changes required to support streaming and then add stable result ordering on top. The changes for stable result ordering would probably involve waiting until all results are found and then caching them somewhere for pagination. 

Based on what I've heard of customer requests for pagination, we would only need to add this by exposing some API rather than adding it to the web app. Am I wrong in assuming that customers are asking for stable result ordering for easier(more sane) programmatic consumption?

**Comment by ijt** [comment]
> * Does it make sense to do stable search result ordering? Is there a better way to communicate that we don't in our UI?

On the UI we could add widgets to allow client-side sorting for users who want it, while not giving up the immediacy of streaming. That would be a way to communicate the default instability of ordering and also mitigate it.

> * How much slower would search actually be if we provided stable search result ordering?

I'd have to check this, but our search may not currently be deterministic even about the set of results returned. So we would have to make search wait for all results to be found in order for this to work. That could be a big slowdown for some queries when there are thousands of repos.

> * If we spent the time to invest in stable search result ordering, would it eliminate desire for other things like search result streaming?

Streaming would allow us to get closer to deterministic search results as a set, without giving up responsiveness.

If we try to get stable search result ordering, it will most likely mean results take much longer and risk more timeouts. That would probably intensify the desire for something like streaming that would show results more quickly.

> 
> Please discuss and help link any relevant past feedback from users.

**Comment by ijt** [comment]
@ijsnow, I'd like us to avoid caching whenever possible since it tends to add complexity and staleness bugs.

**Comment by ijsnow** [comment]
Yea, I said "would probably". But don't you think that if we didn't cache results for specific queries for a bit we would be doing a lot of extra work? Each time the user requested the next page, we'd have to find all the results again.

**Comment by ijt** [comment]
@slimsag, although I think streaming plus frontend sorting is the right way to go for the UI, it should be fine if we add an option to the API to get sorted, exhaustive search results. Then API consumers can opt into it if they don't mind the risk of slowness.

**Comment by ijt** [comment]
@ijsnow, we could have the browser gather the search results as they become available, and dynamically construct DOM elements from them when the user asks for them. There could be some default limit on search result count, say 1k to keep from overwhelming mobile devices.

**Comment by ijsnow** [comment]
So, streaming with a paginated client?

**Comment by ijt** [comment]
@ijsnow, yes. Or we could do something slick like populating the DOM when the scrolling gets beyond what has been rendered.

**Comment by ijsnow** [comment]
👍 we actually already populate more of the dom as we scroll on the search results page

**Comment by slimsag** [comment]
> I'm not convinced that stable result ordering and streaming are mutually exclusive. I think a good path forwards would be to make changes required to support streaming and then add stable result ordering on top. The changes for stable result ordering would probably involve waiting until all results are found and then caching them somewhere for pagination.

@ijsnow I am in full agreement that they are not mutually exclusive and the path forward you described here is effectively what we've already agreed on from earlier discussions. This to me indicates I probably haven't described my theoretical argument very well:

If we came up with a clever way to make search both fast and have deterministic / stable ordering of results, then we could always do pagination (even for regular UI users, not just for API consumers). If we had fast pagination, I believe it would eliminate the desire for streaming because.. fast pagination _is_ effectively streaming.

This is not to say we shouldn't move forward with what you have said above. In fact I think that is the current status quo and it makes sense to go full steam ahead on that.

My goal with this is to challenge the assumption that we aren't able to build search that is both fast and has deterministic / stable ordering. I know that this is definitively an assumption we are making, but I am unsure if it is a valid one or not. I am asking myself questions like "What unique requirements of Sourcegraph search make it such that results in deterministic order is not feasible?" and "If we did search from the ground up, would we come to the same conclusion?"

Definitely think of this as a crazy-wacky-idea "If we threw everything out the window and started from scratch, what would we do?" discussion and not along the lines of "Given what we have today, how do we move forward" (I think we are in full agreement about streaming + optional pagination for API consumers being a decent path forward there)

**Comment by slimsag** [comment]
> Stable in the sense of as you incrementally change a search, the first seen results are stable. Or stable across time given the same query and commits search?

The latter. Stable as in:

- We can support some form of real pagination.
- If me and you independently search for the same thing at the same time, we see the same results in the same order.
- If I reload the page I see the same results in the same order.

**Comment by keegancsmith** [comment]
Without streaming I think removing time budgets is the only way to achieve text book stable results that you desire, but that compromises on performance. Streaming opens up the possibility of streaming results in in a deterministic fashion, without the same amount of compromise in performance. The key is to not sort results (which requires waiting until the end), but rather ensure you deterministically order how you search your repos (or shards). Then if each repo search (or shard search) has deterministic results, you can stream out your results in a deterministic fashion. The algorithm would need to account for parallelism and shards not being ready to be searched. But that seems doable. I haven't fully sketched out my idea here, but I hope the idea comes across enough that it seems reasonable and would work.

**Comment by nicksnyder** [comment]
This was a good discussion. My understanding is that the short answer to the question posed in the title is "yes we need to support stable search results ordering" because
1. Customers need to be able to iterate over all results and
2. We can't return all results in a single request fast enough (without hitting timeouts) at extreme scale.

Streaming could solve both 1 & 2 except that customers have explicitly asked for stable results regardless. If we need to have stable results anyway, then pagination is a very natural solution and API.

Stephen's most up to date proposal is here and he plans to move forward with it:
https://docs.google.com/document/d/1mFOlyYi2D_H_jqqOH44t_d3D2yJF2-E0BqjB5jL2tTQ/edit#heading=h.73qbbhlqhl4

I am closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/2865
