### ISSUE TITLE
zoekt-webserver regularly using 50GB memory, OOMing at 60GB

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3792]
On an xlarge customer deployment (https://app.hubspot.com/contacts/2762526/company/407948923) I am observing zoekt-webserver regularly using ~50GB memory and sometimes OOMing when it goes over 60GB which is the limit we have in place. We've mitigated by bumping up to 80GB but it seems a little crazy to have to do this.

Is there a way we can tell Zoekt "you can use N GB memory, but after that slow down a bit so you don't OOM"? Or is there any low-hanging fruit w.r.t. zoekt-webserver that would reduce memory consumption?

cc @sourcegraph/code-search @sourcegraph/core-services

**Comment by keegancsmith** [comment]
Maybe you can try and increase the shard size flag? For a large repository I believe it may result in overall smaller indexes and lower memory usage in a request. Another possibility is reducing the number of results found per shard.

I don't think there is low hanging fruit other than what I mentioned, but maybe an inspection of some memory traces would reveal some. Otherwise there are some likely higher level changes which can be made:

- Make indexes mmaped as well.
- Horizontally scale zoekt-webserver.
- Smarter decisions in which shards to search and in what order.

**Comment by slimsag** [comment]
@keegancsmith I briefly looked at CLI flags for zoekt-webserver and zoekt-indexserver but didn't find a shard flag size. Can you point me to it? Also, what would you recommend trying to set it to? If we alter it how would it affect the existing indexes produced by Zoekt? (would it need to re-index or something)

**Comment by keegancsmith** [comment]
> @keegancsmith I briefly looked at CLI flags for zoekt-webserver and zoekt-indexserver but didn't find a shard flag size. Can you point me to it? 

`-shard_limit` https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/flags.go#L42:26
It would be for the index server. You would probably have to update our indexserver to set the field, we justrely on the default. @ijsnow recently added functionality allowing us to pass flags from sourcegraph down to the indexserver, so that may be the best place to do it.

> Also, what would you recommend trying to set it to?

Zoekt divides its parallelism up by shards (ie there is one goroutine per shard). So how long it takes to search a shard is the critical path for how quick zoekt is assuming you had infinite cores. 100mb is quite small. As an educated guess I would suspect 1G would still result in fast searches.

> If we alter it how would it affect the existing indexes produced by Zoekt? (would it need to re-index or something)

I believe all indexes will be recomputed (assuming @ijsnow work on reindexing based on command line flags has gone in). If it hasn't, it will only re-index when there is a new commit to index.

**Comment by slimsag** [comment]
Note ongoing work here: https://github.com/google/zoekt/issues/86

**Comment by slimsag** [comment]
@sourcegraph/core-services I am reassigning to you for tracking purposes. I know you're already doing some work on this in google/zoekt#86

It sounds like a good first step here would be what @tsenart suggested in https://github.com/google/zoekt/issues/86#issuecomment-509969657 with just setting GOGC=50 in our zoekt-webserver and zoekt-indexserver containers? Any reason to not do that?

**Comment by slimsag** [comment]
> setting GOGC=50 in our zoekt-webserver and zoekt-indexserver containers

would be good to land this in 3.7 if so

**Comment by tsenart** [comment]
> would be good to land this in 3.7 if so

That sounds like a good idea. Can you land those patches?

**Comment by ijt** [comment]
I'm afk the rest of the day. If someone else wants to land this for 3.7 I'm
fine with that.

**Comment by slimsag** [comment]
(I am doing so)

**Comment by ijt** [comment]
Sounds good. Thanks!

**Comment by slimsag** [comment]
- `GOGC=50` set in Docker containers here: https://github.com/sourcegraph/infrastructure/pull/1601
- deploy-sourcegraph image versions bumped here:
    - https://github.com/sourcegraph/deploy-sourcegraph/commit/55fdba2f7d3a31f42fe55d85ef3170bb2ec68b2f https://github.com/sourcegraph/deploy-sourcegraph/commit/120b17622e93ef12b86b6e8e866d8fb43d04f63d
    - https://github.com/sourcegraph/deploy-sourcegraph-docker/commit/b638e57671d68d316e378bb8d0d6869c95632e27
- Companion server/dev change: https://github.com/sourcegraph/sourcegraph/pull/5199

**Comment by slimsag** [comment]
We'll see how big of an impact this has and, if sufficient, will then close this out.
