### ISSUE TITLE
gitserver: Setting tls.external.certificates clobbers system Certificate Authorities

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#38128]
- **Sourcegraph version:** 3.40.0
- **Platform information:** [sourcegraph/deploy-sourcegraph@v3.40.0](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v3.40.0)

#### Steps to reproduce:

1. Host GitHub Enterprise Server with a TLS certificate that is issued by an internal Certificate Authority.
2. Configure two [GitHub code hosts](https://docs.sourcegraph.com/admin/external_service/github), one for the public GitHub.com and another for your GitHub Enterprise Server:
   ``` js
   "GITHUB": [
     {
       "url": "https://github.com",
       "token": "REDACTED",
       "orgs": ["sourcegraph"]
     },
     {
       "url": "https://github.internal",
       "token": "REDACTED",
       "orgs": ["sourcegraph"]
     }
   ]
   ```
3. Add the internal CA’s certificate to Sourcegraph’s site configuration under [experimentalFeatures](https://docs.sourcegraph.com/admin/config/site_config#experimentalFeatures), so gitserver can connect to github.internal: 
   ``` js
   "experimentalFeatures": {
     "tls.external": {
       "certificates": [
         // Internal CA
         "-----BEGIN CERTIFICATE-----\n…\n-----END CERTIFICATE-----"        
       ]
     }
   }
   ```
4. Wait for gitserver to clone all the repositories.

#### Expected behavior:

1. repo-updater discovers all the repositories in github.com/sourcegraph and github.internal/sourcegraph
2. gitserver clones all the repositories in github.com/sourcegraph and github.internal/sourcegraph

#### Actual behavior:

1. repo-updater discovers all the repositories in github.com/sourcegraph and github.internal/sourcegraph
2. gitserver _only_ clones all the repositories in github.internal/sourcegraph
3. gitserver _fails to clone_ any repository in github.com/sourcegraph with the following warning:
   ```
   t=2022-07-01T20:29:33+0000
   lvl=warn msg="error cloning repo"
   repo=github.com/sourcegraph/sourcegraph
   err="error cloning repo: repo github.com/sourcegraph/sourcegraph not cloneable: exit status 128 (output follows)
   
   fatal: unable to access 'https://github.com/sourcegraph/sourcegraph/': SSL certificate problem: unable to get local issuer certificate"
   ```

#### Analysis

This happens because GitHub.com uses a TLS certificate whose root is _DigiCert Global Root CA_, which is a system certificate that is not mentioned in `experimentalFeatures.tls.enabled.certificates`.

This bug was initially mentioned in #71, but never got fixed because we had a workaround. I’m re-reporting it because I needed to update the workaround again.

@keegancsmith added a debug log in #22285, in case SystemCertPool fails to load, but I found no evidence of this error in our logs. I’d also like to point out that repo-updater was totally fine using system certificates, so my hypothesis is that gitserver isn’t going down this codepath.

Reading the error message, it really looks like it is coming from the actual git binary, which makes me suspect the [GIT_SSL_CAINFO](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpsslCAInfo) environment variable, which is set by #8092:
https://github.com/sourcegraph/sourcegraph/blob/3518a54ce82699d0e1fe3b19b21dd6eb2412ce5e/cmd/gitserver/server/serverutil.go#L115-L129

Note that this only writes the contents of the configuration, but doesn’t prepend /etc/ssl/certs/ca-certificates.crt, which exists in [sourcegraph/gitserver@3.40.0](https://registry.hub.docker.com/layers/gitserver/sourcegraph/gitserver/3.40.0/images/sha256-f6ba7a55b7b9e19b1d8b6de7601f4a54e2e1f866ec7fa97c6b43feace1c59dfc?context=explore). If this were prepended, all the system certificates would be included and I bet this would fix the bug.

#### Workaround

Add the _DigiCert Global Root CA_ certificate alongside your internal CA certificate:
   ``` js
   "experimentalFeatures": {
     "tls.external": {
       "certificates": [
         // DigiCert Global Root CA
         "-----BEGIN CERTIFICATE-----\nMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\nQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\nMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\nb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\nCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\nnh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\nT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\ngdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\nBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\nTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\nDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\nhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\nPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\nYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\nCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n-----END CERTIFICATE-----",
         // Internal CA
         "-----BEGIN CERTIFICATE-----\n…\n-----END CERTIFICATE-----"        
       ]
     }
   }
   ```

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by keegancsmith** [comment]
So this isn't a quick win. Go's system certificate pool code does not expose the actual certificates. This is because depending on the platform go has to use different mechanisms to get hold of the certificates (some of which are costly so are done lazily).

I see two options forward:

-   Copy-paste go's linux code for system certificate discovery. In Linux's case this is straight-forward and will work for our docker images.
-   Document that users should include system certificates in the configuration.
-   More research.

Documenting is easy so will atleast send a PR now for that. Copy-paste of stdlib code doesn't feel that great to be honest, and it isn't full proof in general (eg on my linux distribution (nix) the go runtime is patched to use different code for cert discovery). I've done a fair amount of research, but maybe git has some option to use both system certs and custom ones?

**Comment by sfllaw** [comment]
This is still an experimental feature. Perhaps we could move the certificates soon they are set on a repo, which would match Git's model?

**Comment by keegancsmith** [comment]
I like that suggestion to be honest. Also TIL that you can specify certs per domain. I'm sure we can workaround cli limits via adjusting repo config files. We use this setting also for go communication, so will just need to see if we can do something similar (I am sure we can).

Indeed the feature is still experimental, but fairly certain it is now in use by lots of people :) I'm sure we can do this in a non-breaking way as well.

**Comment by keegancsmith** [comment]
Suggestion to use url matching which is supported by git [`http.<url>.*`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httplturlgt). So investigating if we could reasonably do this for Go:

-   [tls.Config.GetConfigForClient](https://sourcegraph.com/github.com/golang/go@go1.19/-/blob/src/crypto/tls/common.go?L587) isn't on the URL unfortunetly and will only have a ServerName if the server is using SNI.
-   [http.Transport.DialTLSContext](https://sourcegraph.com/github.com/golang/go@go1.19/-/blob/src/net/http/transport.go?L155) isn't on the URL, but does get the address and allows us to establish the TLS connection (ie use a custom TLS config per domain).

I think using `DialTLSContext` would allow us to implement this. It won't be the same as git (URL based), but rather just work on the address (`domain:port`).

My only concern is potential downstream users of `http.Transport` assuming too much and doing things with the `TLSClientConfig`/etc and then that is ignored by our `DialTLSContext`. For example passing in our transport to the AWS client. I think there may even be examples in our own codebase where we manipulate `TLSClientConfig`.

It might make more sense to bake in TLS config into the external service configs instead of a global one. Then these concerns disappear (but requires much more code changes).

Either way this still isn't a quick win, so I'm not sure how we will prioritize this work given there is a workaround.

**Comment by sfllaw** [comment]
@keegancsmith I agree that configuring custom Certificate Authorities probably belongs in the code host’s settings, which can then be associated with its URL when calling out to Git.

On the Go side, you _could_ do something fancy like you proposed above. Or you could just add all the certs to the `x509.SystemCertPool`. This will be a little looser than the actually configuration specifies, but does that really matter? Is there really a world where you trust the CA for one code host but not another?

**Comment by keegancsmith** [comment]
After spending too much time researching other possibilities, I've gone with just including the system certificates for git. This is possible to do on Linux (and only really linux), but that is how we run git so in practice it fixes this bug. https://github.com/sourcegraph/sourcegraph/pull/41253
