### ISSUE TITLE
JetBrains: Doubleclick on a search result should open the file in the editor/browser

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#38477]
When I double-click a search result in “Find in Files”, it opens in the editor.
When I double-click a search result in “Find with Sourcegraph”, nothing happens.
[13-sec demo](https://www.loom.com/share/578cbe6a9feb44c08ad70321773a2e1f)

I think, upon double-click, the result should open in the editor or in the browser.
Can you confirm if this sounds like a good idea, @jjinnii?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by jjinnii** [comment]
@vdavid Sounds good to me! Slightly concerned that people will be annoyed when repo/diff/commits take them to the browser, as in testing users didn't catch the difference in icon. But this is a secondary concern, and I agree that the expected behavior is that double clicking a result will open in editor or browser.
