### ISSUE TITLE
Adding license key to site config prompts for server restart; shouldn't

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#385]
1. Run the latest Docker image.
2. Go to the site config and add a license key.
3. Notice you are prompted for a server restart.

I am guessing this does not actually need a server restart (why would it?) and that an exception should be added to this list: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/conf/conf.go#L257

- [ ] TODO(slimsag): Invert that list by default

**Comment by sqs** [comment]
I fixed the issue. I am closing this issue despite the open TODO to invert the list by default because that's a minor refactor that will be overshadowed by @ggilmore's site config project this month, which will change this a lot (eg https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/conf/conf.go#L247:4-248:4&tab=discussions&threadID=80).
