### ISSUE TITLE
Update docs on how customers can add their own language support

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38529]
Customers can currently [add support for any language](https://docs.sourcegraph.com/dev/how-to/add_support_for_a_language) that we don't support. However, it relies on adding an extension to render the popups. 

We need to find a way of supporting these without requiring an extension

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
I’m moving this task to the next milestone. This is blocked by #38317. I _think_, if we do #38317, this will _just work_, but we should validate for sure (and update the docs).

**Comment by philipp-spiess** [comment]
Here's some additional context: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1659698187195799

The doc is written for Sourcegraph developers and is currently linking to places in the code intel extension to make changes to. With our changes, this doc will need to be updated so that it points to the new code intel extension places in the monorepo instead. Functionality wise this will likely stay as-is but we need to wait for the code intel pull request to confirm.
