### ISSUE TITLE
JetBrains: Onboarding experience: Explaining users how to access the new Sourcegraph window

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#38574]
When a customer upgrades to the new JetBrains extension or installs it for the first time, they getting access to quite a few new features. How can we explaining to them _what changed_ and _how they can access the new Sourcegraph window_?

On VSCode, we apparently show an after install pages that explains the extension (source: @muratsu). Do we want to replicate this for JetBrains?

Additionally there's the new notification that we've added when JetBrains is started and no external URL is configured yet that we can use to highlight new information.

cc @muratsu @jjinnii @ryankscott @vdavid 

## Expected outcome of this issue

- We discuss different options to improve the onboarding experience
- We decide on one option and move this to design/implementation stage

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
## Personal thoughts

I've seen other JetBrains extensions sending notifications when a major version was upgraded, something like this:

![image](https://user-images.githubusercontent.com/458591/178319791-0c8500fc-56cf-442b-af0a-bfdd2454d3a8.png)

We could add one specifically for first time users or those who upgrade from a prior version and:

- Include the biggest highlight inside the notification (e.g explain that we have a new window that you can enable via `alt+s`).
- Include a link to our blog post for more detail.

**Comment by vdavid** [comment]
I agree with the initiative, I think this would help a lot with both old and new users.
I also generally agree with @philipp-spiess's ideas for the solution. In particular, I'd definitely go with notifications.

Random thoughts:
 - One thing to be mindful of will be to handle the clash between the "log in!" and the "update! / try alt+s" notifications, so that we don't show both
 - After 10sec of thinking, I don't know yet how to recognize an update vs a new user
 - For new users, I'd display "hey! thanks for installing! try alt+s!" notification
 - For old users, I'd display a "hey! thanks for upgrading! try alt+s! also, read this blog post!" notification
 - Might make sense to add another on-element notification inside the popup, on the "Settings" button to point out that this is the place where new users can log in right after opening the popup the first time

Any more thoughts?

**Comment by jjinnii** [comment]
@vdavid Would you be able to confirm that we won't have a way to recognize an update versus a new user? I also agree with the notification, but if we are not able to distinguish, I will have to think of copy that will apply to both new and old users.

**Comment by vdavid** [comment]
@jjinnii I'm confident that we could find a way to distinguish between new and old users, but I'm not sure it'll fit in the allocated time frame of the next two days. So for the sake of speed, let's go with **no, we can't distinguish between the two** for now.

**Comment by jjinnii** [comment]
Based on the current restriction that we can't distinguish between a new install versus an upgrade, I've added [a balloon notification](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=1601%3A14159) that will be shown to **all users** upon install or upgrade after our release. Open to feedback on copy! It's a bit difficult to not allude to a successful install or upgrade. 
cc: @philipp-spiess @vdavid

**Comment by vdavid** [comment]
@jjinnii I think it's great! I'll create a PR with this change.

**Comment by vdavid** [comment]
@jjinnii @ryankscott what's the URL the the "Learn More" link should point?
Maybe it's in the [figma](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=1601%3A14159) just I couldn't find it?
If it's to our future blog post then we'll need to figure out something different, or set this last minute.

**Comment by jjinnii** [comment]
It should be to the future blog post! @vdavid
