### ISSUE TITLE
Reference panel: add syntax highlighting to the refs and defs snippets

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38665]
![Image](https://user-images.githubusercontent.com/4605817/177200629-be4001d0-da8e-4881-84d9-368b8bab7dc3.png)

**Comment by olafurpg** [comment]
Comment from @mrnugget 

> it should be relatively easy to use `<CodeExcerpt />`. The biggest challenge is computing the ranges

Thinking out loud, it would be nice if we could use the new infrastructure to apply syntax highlighting lazily 🤔

**Comment by mrnugget** [comment]
Just adding a few things that popped into my head last night.

The current reference panel does the following things that will also need to work with syntax highlighting (or would need to be replaced):

1. Current token is highlighted 
![screenshot_2022-09-09_09 34 30@2x](https://user-images.githubusercontent.com/1185253/189297002-c1e2a52f-6358-4791-b5b7-60760eb0dac5.png)
2. Hovered/active lines are visually marked as such (we don't do that in our search results, because there's no need for an active state, since we change URL on click)
![screenshot_2022-09-09_09 35 05](https://user-images.githubusercontent.com/1185253/189297090-69db390c-a8ef-4c26-8814-d8e44eff3d9f.gif)

**Comment by mrnugget** [comment]
Sharing https://github.com/sourcegraph/sourcegraph/pull/41569 here for context.

Also wondering what the expectation is: does this have to go in 4.0 or not?

**Comment by olafurpg** [comment]
I've opened a new PR based on @mrnugget's work https://github.com/sourcegraph/sourcegraph/pull/42180

Will add more changes later this week and request review once it's cleaned up
