### ISSUE TITLE
Search: use chunk match streaming API

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#38891]
The search backend has recently been migrated to the richer `ChunkMatch` data type, which is a type that makes it possible to represent multiline matches as one logical match. This has been exposed over the streaming API, and is enabled by the [`cm` query param](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@cb906941e8b49806f0be1861fe025b9de863ecdb/-/blob/cmd/frontend/internal/search/search.go?L244-247). When set, the [`ChunkMatches` field](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@cb906941e8b49806f0be1861fe025b9de863ecdb/-/blob/internal/search/streaming/http/events.go?L31-31) will be populated on the `EventContentMatch` instead of the `LineMatches` field.

We should migrate the client to use the new streaming API. This will allow us to display the correct number of results when we have multiline results instead of counting each line of the result as a separate match.

**Comment by novoselrok** [comment]
Side note: I somehow confused `chunkMatches` with [hunks](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/client/search-ui/src/components/FileSearchResult.tsx?L185:38), which are currently causing the duplication in the file search results component.

Nonetheless, to get the full advantage of the new chunk matches, we will need to rewrite the ancient [highlighting function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/common/src/util/highlightNode.ts?L11). Otherwise we will have to convert chunk matches to line matches on the client, and we lose any benefits.
