### ISSUE TITLE
Search: Search result page has flickering home page effect

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38928]
## Problem
You can see the home page for one or two frames when you're going back from blob or repo pages to the search result page. See the video below 

https://user-images.githubusercontent.com/18492575/179476603-8e81103b-d985-4abd-895a-b4502bf36dd8.mov

## Possible root cause of this 
From @vovakulikov 

I think I know what happens here. In this place, we track `location.search` and set the internal state to the Zustand store  `searchQueryFromUR` [https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourceg[…]sion=v1.2.2&start_row=134&start_col=34&end_row=134&end_col=34](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=client%2Fweb%2Fsrc%2FLayout.tsx&editor=JetBrains&version=v1.2.2&start_row=134&start_col=34&end_row=134&end_col=34)

Since `useEffect` (and even `useLayoutEffect`) have async nature, we're starting to have a false value in SearchPageWrapper because on the blob/repo pages, we didn't have a query in URL query params, and therefore, we set "" to the `searchQueryFromURL`. In the next tick/render, we set searchQueryFromURL with parsed query since we have a valid query as URL param on the search result page.

So I'm not sure I have a quick solution here, but it seems that searchQueryFromURL shouldn't exist as a part of the state. This should be a piece of derived information from the URL and its query param.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by fkling** [comment]
We could inspect the URL (parameters) directly in `SearchPageWrapper`, but that alone won't solve the problem that we will still have two renders: One because the URL changes and one after the Zustand store updates. It would be nice to do both at once somehow. Maybe something like a `useImmediateEffect` hook that executes its callback immediately would help?

**Comment by vovakulikov** [comment]
@fkling, I meant that not having `searchQueryFromURL` inside the state would solve the problem with flashing. It could solve problems with double rendering as well because, as I can see, we have only two places where we're reading `searchQueryFromURL` from the state, and in both places, we can easily read from the URL directly. 

I would be cautious with using `useImmediateEffect` since this relies on render calls, and sometimes this may play a weird part.

**Comment by fkling** [comment]
@vovakulikov Yeah, that's what I meant with we can inspect the URL directly. But we would still need to update the internal query state from the URL. We are not just setting `searchQueryFromURL` we are parsing the search query and extract various pieces of information (e.g. `case:yes`). And it would be nice if all this could happen at the same time (and not rendering the search page because of route changes and then update the search page because the query state got updated)

**Comment by fkling** [comment]
With `useImmediateEffect` I basically just mean a helper that would allow to run some code synchronously but only if something has changed. Instead of doing 

```
useEffect(() => setQueryStateFromURL(location.search), [location.search])
```

it would be something like

```
if (location.search !== previousLocation.search) {
  setQueryStateFromURL(location.search)
}
```
