### ISSUE TITLE
Repository Status: Add counts to all filtered views and add "In progress" filters

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#39328]
#### Feedback

* Add counts for all filters (Cloned, Not cloned, Needs index, Failed fetch)
  Currently,  not all of the filtered views show a count.  For example, cloned repos shows no count (`/site-admin/repositories?status=cloned`).
*  Add additional filters for "Clone in progress" and "Index in progress"

#### Customer

https://github.com/sourcegraph/accounts/issues/6716

[Internal Tracking Spreadsheet](https://docs.google.com/spreadsheets/d/1NYwUBDThigD3UfffMjbZqL34gL7MvKq_WBriI57Y1ck/edit#gid=0&range=31:31)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mrnugget** [comment]
@mike-r-mclaughlin FYI I just merged https://github.com/sourcegraph/sourcegraph/pull/39952 which adds counts of repositories to the site-admin page. It doesn't have "Needs index" yet (different subsystem involved there).

**Comment by mrnugget** [comment]
@cbart with your recent PR the counts can be checked off, right?

@mike-r-mclaughlin on the "Index in progress" filter: we can't easily detect that. But we do have "not indexed" and since my changes to persist indexing status, we can show number of indexed repositories too. Do you think that's enough? Or what are you still missing?

**Comment by mike-r-mclaughlin** [comment]
@mrnugget that makes sense.  i think what we were trying to capture with that status was when things were "stuck".  and i think we have other ways of detecting that now.
