### ISSUE TITLE
some cases of slow `repo:contains` searches

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#39392]
Here is a repo `repo:^github\.com/drishal/dotfiles$` that satisfies the query

- `repo:contains.file(flake.nix) pkgs.linuxKernel.manualConfig`

## [query](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/drishal/dotfiles%24+repo:contains.file%28flake.nix%29+pkgs.linuxKernel.manualConfig&patternType=lucky)

When we do a global search for the query on Sourcegraph.com, we eventually find the `drishal/dotfiles` repo, but only after about 53 seconds (and we might actually time out and miss it, based on feedback)

## [query](https://sourcegraph.com/search?q=context:global+repo:contains.file%28flake.nix%29+pkgs.linuxKernel.manualConfig+count:all&patternType=lucky)

<img width="1028" alt="Screen Shot 2022-07-25 at 3 41 34 PM" src="https://user-images.githubusercontent.com/888624/180886278-079b1121-8092-4303-b0d1-c9589e47c5b5.png">

Don't know if this is just inherently an expensive needle-in-haystack query, looks like there are about 2.4K repos that have a `flake.nix` file to potentially search through:

![Screen Shot 2022-07-25 at 3 44 16 PM](https://user-images.githubusercontent.com/888624/180886559-c4ccabfe-2ddc-4703-83e3-fad1581016f4.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by rvantonder** [comment]
CC @camdencheek

**Comment by rvantonder** [comment]
Refreshed my understanding of https://github.com/sourcegraph/sourcegraph/commit/9a0f825568e665f032710741dfce677bafeeed13#diff-625b5188ac3d506dbb4a20b5904654d7a8f6d221bc5ed829270829cdd0887f4bR595 and looks like this is a Zoekt bottleneck? How large is the repo page size, maybe that adds overhead? Just throwing out thoughts here, would probably be better to dig into a trace

**Comment by camdencheek** [comment]
Looking at the traces, it seems the issue is just that we page through that match `repo:contains.file(flake.nix)` 500 at a time and process each page serially, streaming results as we go. On sourcegraph.com, this is millions of repos divided in chunks of 500. `type:repo count:all` also suffers from this on `sourcegraph.com`. In fact, this affects any non-global search, we just usually hit our limit before noticing that the search is really slow. 

I think it may be worthwhile to bump up the number of repos in each page. We can easily hold more than 500 repos in memory at a time. I'm thinking somewhere closer to 4k. A `types.MinimalRepo` struct takes 32 bytes in memory, plus the length of it's name string, which I'll estimate at another 32 bytes. A 4k repo page will take an estimated 256KB memory, which seems like a reasonable tradeoff between cost of processing a page and memory usage.

That said, we process a whole page before starting a search, so increasing the page size will likely also increase latency. In practice, I have no idea how much latency that will be

**Comment by keegancsmith** [comment]
> repo:contains.file(flake.nix) 

Why are we paginating repos here? Can't we rely on zoekt directly here? I know historically we didn't, but I thought you implemented some amazing optimizations here recently? :)

**Comment by camdencheek** [comment]
This PR helped, but these types of searches are still slow. 

> Can't we rely on zoekt directly here? 

Yes, it's possible. And it would likely be much faster for queries that contain no other repo filters. 

_However_, we pay a large amount in complexity by splitting up the repo resolution step. So much, in fact, that we have been producing incorrect results for commit search and repo search because the application of repo filters was not correctly copied to these steps of the search execution. 

My recent PRs consolidated the logic so that either we are running a global search with no repo filters, and we just rely on Zoekt to send us everything, or we are running a `repo:` scoped search and we can rely on the output of `Paginate` to give us the correct set of repos to search.

I _think_ we might be able to make `repo:contains()` not kick us out of global search, which would be a big win for text search. I'm going to try that next.

**Comment by rvantonder** [comment]
concrete numbers: https://github.com/sourcegraph/sourcegraph/pull/39393 helped take 53 seconds -> 15 seconds for original query

<img width="984" alt="Screen Shot 2022-07-27 at 11 18 44 AM" src="https://user-images.githubusercontent.com/888624/181344445-09bde323-d896-4266-bab8-0b4a3f0edd2b.png">
