### ISSUE TITLE
Hover tooltip for C# class name in Bitbucket Server is blank

### ISSUE THREAD

**Issue by doxxx** [sourcegraph/sourcegraph#395]
- **Sourcegraph version:** Docker image using insiders tag (01208_2018-10-15_e694f9e)
- **Platform information:**
  - Ubuntu 16.04
  - Docker 18.06.1-ce
  - Bitbucket Server 5.13.1

#### Steps to reproduce:

1. Configure Sourcegraph to use a Bitbucket Server instance.
2. Browse to a C# file in a monitored repo on the Bitbucket Server.
3. Hover the mouse over a class name.

#### Expected behavior:

Information tooltip is displayed with buttons to find references/definition/implementations.

#### Actual behavior:

- Tooltip is mostly blank with a Sourcegraph icon and a line below that which says "Click for more actions..."
- Bug doesn't occur for all symbols.

![image](https://user-images.githubusercontent.com/677940/46952843-14d5f380-d05a-11e8-9aac-1364de8bd393.png)

Possibly related to this: When I view the same file in the Sourcegraph UI, the hover tooltip for any symbol has the buttons but sometimes has no information about the symbol above the buttons.

I get "not implemented" errors for each of the buttons in the tooltip, so I'm guessing the above behavior is probably due to the experimental nature of the C# language server.

**Comment by felixfbecker** [comment]
Hi @doxxx, the language analysis for C# is provided by the OmniSharp language server: https://github.com/OmniSharp/omnisharp-node-client
The empty hover is a bug in that service. Since that language server is not as solid as other languages (Go, TypeScript, ...) we consider the support for C# experimental until the language server improves.

We are also working on bringing redesigned hovers to Bitbucket Server (you can already see them on GitHub). cc @ijsnow

**Comment by sqs** [comment]
We plan to work on language support for languages other than JS/TS/PHP/Python/Go/Java in December 2018 (see roadmap: https://docs.sourcegraph.com/dev/roadmap#december-2018). That is the earliest we would be able to address this ourselves. But we are releasing big improvements to *how* language support is built in Sourcegraph in early Nov and even more in early Dec, so it's possible someone (you?) could contribute better C# support sooner than that.

Filed the old tooltips issue separately in https://github.com/sourcegraph/sourcegraph/issues/521. I don't believe it is the cause of the empty tooltip.

**Comment by doxxx** [comment]
I can't promise anything since my day job generally keeps me quite busy, but if I have the time I'll have a look.

I agree regarding the empty tooltips. I saw them in the Sourcegraph UI for the same file as well.

**Comment by sqs** [comment]
We have removed the previous experimental C# support for now (see https://about.sourcegraph.com/blog/java-php-experimental-language-servers-temporarily-unavailable) because we are not able to stay on top of these issues. We will be adding much better fuzzy code intelligence for C# in Sourcegraph 3.0 (slated for release in mid-Jan).
