### ISSUE TITLE
Visual regression on the reference panel

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#39517]
### Issue type

Bug fix

### Problem description

![image](https://user-images.githubusercontent.com/43555476/181302812-f6c0a853-65af-41c6-84f9-7b8c440e404b.png)

### Context

https://github.com/sourcegraph/sourcegraph/discussions/35668#discussioncomment-3151913

### Assigning labels

- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by mrnugget** [comment]
Just to be explicit and add more context to the ticket itself: the problem is not with the reference panel, but with the generic "panel action items" that every extension can contribute.

The styling here https://github.com/sourcegraph/sourcegraph/blob/6558f4d7c3caa5893810c3ffda74d23fc54e081b/client/shared/src/actions/ActionsNavItems.module.scss

is supposed to make the overflowing content hidden (with `ellipsis`), but it's missing a `whitespace: no-wrap;` to get it to work.

But even if you add `whitespace: no-wrap;` and it works as seemingly intended, it can hide a lot of text.

So maybe the solution is to increase the width of the items, or overflow them to two lines (if possible?)

**Comment by lrhacker** [comment]
@AlicjaSuska do you have thoughts on how we might prefer to handle long text strings here? See Thorsten's comment above for some initial ideas.

**Comment by mrnugget** [comment]
Maybe the solution can just be to use `overflow: ellipsis;` and put the text in a tooltip? For that to work with the current button, this line here would need to be duplicated to have a `tooltip` with the same value as the `label`:

https://github.com/sourcegraph/code-intel-extensions/blob/dba503cccfbc7e7133663e99b8f07071bfbef057/template/package.json#L74

**Comment by oleggromov** [comment]
@jjinnii what do you think if for that issue I'll apply a temporary fix suggested by @mrnugget, which will just hide the overflowing text with an ellipsis, and then @lrhacker will be able to come up with a proper fix, including a tooltip/popover?

**Comment by mrnugget** [comment]
> a proper fix, including a tooltip/popover?

Just to be clear: that's already supported, as far as I can tell. If I'm reading this code right

https://github.com/sourcegraph/sourcegraph/blob/6558f4d7c3caa5893810c3ffda74d23fc54e081b/client/shared/src/actions/ActionItem.tsx#L212

then we'd have to change this

https://github.com/sourcegraph/code-intel-extensions/blob/dba503cccfbc7e7133663e99b8f07071bfbef057/template/package.json#L74

from 

```json
"actionItem": {
          "label": "${!!config.codeIntel.mixPreciseAndSearchBasedReferences && \"Hide search-based results when precise results are available\" || \"Mix precise and search-based results\"}"
        }
```

to 

```json
"actionItem": {
          "label": "${!!config.codeIntel.mixPreciseAndSearchBasedReferences && \"Hide search-based results when precise results are available\" || \"Mix precise and search-based results\"}",
         "description": "${!!config.codeIntel.mixPreciseAndSearchBasedReferences && \"Hide search-based results when precise results are available\" || \"Mix precise and search-based results\"}"
        }
```

and the tooltip should show up automatically?

**Comment by AlicjaSuska** [comment]
Thank you for brining this up. I think we should fix the labels here - they are too long. My proposition:
1st: '[icon] Send us feedback'
2nd: Hide search-based results [info icon] - with a tooltip 'Hide search-based results when precise results are available'

@jjinnii what do you think about this change?

**Comment by jjinnii** [comment]
Thanks @AlicjaSuska ! I like that suggestion a lot. Instead of continuing with a button that would default to an ellipses, I think it's better to shorten as well. 

Just a question for @macraig , should we be maintaining the "Send us reference panel feedback" after we've enabled the new reference panel as the default experience?

**Comment by macraig** [comment]
@jjinnii I think we should remove it once it's the default panel. I'd try and keep feedback CTAs for other experimental features we decide to roll out in the future. What do you think?

**Comment by jjinnii** [comment]
Agreed! Regardless, I think we should still implement the shorter copy that Alicja suggested: Hide search-based results [info icon] - with a tooltip 'Hide search-based results when precise results are available'. That button is a mouthful, and it won't scale well in the future if we ever have more than two buttons. 

cc: @macraig @oleggromov
