### ISSUE TITLE
Can't verify email on Sourcegraph.com

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#397]
- **Sourcegraph version:** Sourcegraph.com
#### Steps to reproduce:

1. Receive the verify email
2. Open the verify link

#### Expected behavior:

Verifies account

#### Actual behavior:

Requires login and can't log in because the account is unverified

Reported by @aaronperrin

**Comment by slimsag** [comment]
I've just created a new account and confirmed email verification works. However, there are a few oddities:

1. [ ] When you click the email verified link, it just brings you to this page with no indication of what has happened:

![image](https://user-images.githubusercontent.com/3173176/46973980-9ee08500-d077-11e8-93e1-f524b6f554a6.png)

2. [ ] If you open the link in a browser that is already signed into a different Sourcegraph.com account, you will get weird errors like `No email "" found for user 13` with no explanation of what the problem is.

@aaronperrin does the first issue above look like the problem you encountered?

**Comment by slimsag** [comment]
I am tagging P1 until we hear back from the user. If this is just the issues I reported above, then this is lower priority.

**Comment by sqs** [comment]
@aaronperrin Could you please try to reproduce this issue on https://sourcegraph.com now?

**Comment by sqs** [comment]
Unable to repro. Closing after fix https://github.com/sourcegraph/sourcegraph/commit/2d34bc773effb38a43e35aa879e8022dde84d4fc to redirect location and splitting out the bad error message into #1002.
