### ISSUE TITLE
Rename "Code Intel" to "Code navigation"

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#39780]
Rename Code Intel

Code Intel is now Code Graph, and when the team's work is talked about it is often referred to as “code navigation”.

This necessitates the following changes:

[Figma file](https://www.figma.com/file/mmWwgzzqTmpLsxwmiiZwfE/Admin-analytics?node-id=1504%3A10137)

![image](https://user-images.githubusercontent.com/539268/182436692-6b2abc82-c7c5-44d2-80b5-2a14dc2a89b9.png)

**Comment by jjinnii** [comment]
There is a[ similar conversation ](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1659084691187219?thread_ts=1659076332.557719&cid=CHXHX7XAS)that happened for the code intelligence header in the same user settings page. Based on the thoughts in that thread, I feel as if "Code navigation" should be used here? And places where we're talking about auto-indexing set up or config policy pages, we should be using "Code graph (data)".

cc: @macraig @quinnkeast

**Comment by macraig** [comment]
@rrhyne as @jjinnii mentioned above, "code navigation" should be used instead of "code intel" for everything feature related (jumping to def, finding references, etc). Code graph data is used to refer to data that powers precise code navigation (SCIP/LSIF data). I marked the changes in the image below:

<img width="725" alt="adminUI" src="https://user-images.githubusercontent.com/1657213/182329661-25fc8c34-a118-4e6a-81f4-760a808c7524.png">

**Comment by rrhyne** [comment]
Thanks @macraig!
