### ISSUE TITLE
[UI BUG]Extra line under the tabs shouldn't be there

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#39808]
Recommended action: Remove the extra line 😄 

![Image](https://user-images.githubusercontent.com/7814431/182359703-2192c6dd-34d6-42d4-95d4-77aa361556cd.png)

![Image](https://user-images.githubusercontent.com/7814431/182359709-29ebc1ae-2c7a-493d-be2a-dfd400f8c8c1.png)

**Comment by courier-new** [comment]
Hey @danielmarquespt, which environment did you spot this in? I'm wondering if someone already fixed it, which would be cool, because I can't seem to recreate your screenshot. 😅

S2 or K8s, Chromium:

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/8942601/182472403-1847e84d-d7ff-410c-95aa-11a1367207a8.png">

S2 or K8s, Safari:

<img width="945" alt="image" src="https://user-images.githubusercontent.com/8942601/182472643-2f044f2e-3394-476b-9ffa-2b89133b1237.png">

**Comment by danielmarquespt** [comment]
K8s and S2 on Safari:
![Screenshot 2022-08-03 at 10 53 57](https://user-images.githubusercontent.com/7814431/182580179-484eaf92-c56c-4c9a-95fe-6d4b2a477706.png)
![Screenshot 2022-08-03 at 10 53 42](https://user-images.githubusercontent.com/7814431/182580193-b9fd7648-e75f-4597-85fa-9209edc78cef.png)

**Comment by chrispine** [comment]
P0 or P1?

**Comment by courier-new** [comment]
P1, unless someone on the team other than Daniel can reproduce the bug. 🙂 I'll have to get on a call and get Daniel to screenshare when he gets back from PTO otherwise.

**Comment by Piszmog** [comment]
I am able to reproduce the bug. In dark mode, it is a block.

![Screen Shot 2022-08-09 at 08 52 51](https://user-images.githubusercontent.com/38407415/183681921-cf01ab5d-b392-4e76-9ca0-e62ff638fdc7.png)
