### ISSUE TITLE
Jetbrains: can't search on a custom Sourcegraph

### ISSUE THREAD

**Issue by Al3xCalibur** [sourcegraph/sourcegraph#39801]
- **Sourcegraph version:** 3.41.0
- **Platform information:** Windows, Intellij and Rider, plugin 2.0.0

#### Steps to reproduce:

1. Configure an enterprise instance with the right URL and a token
2. Find with Sourcegraph (Alt+S) on any file

#### Expected behavior:

Show a panel with relevant searches in Intellij

#### Actual behavior:

Error message in the panel: Could not connect to Sourcegraph.

/cc @muratsu @jjinnii @ryankscott

**Comment by malomarrec** [comment]
Hey @ryphil, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by jdorfman** [comment]
Hey @Al3xCalibur I would try asking #help in our [Discord](https://srcgr.ph/discord). You can keep this open just in case support can't fix the issue for you.

**Comment by malomarrec** [comment]
Hey @ryphil, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by malomarrec** [comment]
Hey @ryphil, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by malomarrec** [comment]
Hey @ryphil, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by philipp-spiess** [comment]
Hey @Al3xCalibur! Sorry for the troubles in triaging the GitHub issue 😢.

It seems that you did reach out via Disocrd though and that we have created another GitHub issue for this problem from this conversation: https://github.com/sourcegraph/sourcegraph/issues/40601

We'll go ahead and close this ticket so that we only have one in our system (that one already is properly triaged). Please feel free to subscribe to it and comment if there are any other issues.
