### ISSUE TITLE
GitHub external service: repository sync service fails if org name contains _ or -

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#3983]
**Sourcegraph version:** insiders (May 13)

Sync service chokes on `org:my-org` or `org:my_org` `respositoryQuery` strings which are valid GitHub organization names: 

```
Error saving invalid configuration:

warning: external service created, but sync request failed: syncer.sync.sourced: 1 error occurred:
* failed to list GitHub repositories for search: page='\x01', searchString="org:my-org-name",: request to http://127.0.0.1:3180/search/repositories?page=1&per_page=100&q=org%3Amy-org-name returned status 422: Validation Failed
```

![Screen Shot 2019-05-13 at 12 19 25 PM](https://user-images.githubusercontent.com/133014/57648073-60f9ff80-7579-11e9-91b1-05c245eb48cd.png)

## Expected outcome

Syncer can sync repositories belonging to valid GitHub org names

## Feature suggestion

Is it possible for the JSON schema to have regex that validates each `repositoryQuery` string?

**Comment by tsenart** [comment]
```
{
  "message": "Validation Failed",
  "errors": [
    {
      "message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.",
      "resource": "Search",
      "field": "q",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/search/"
}
```

**Comment by tsenart** [comment]
> "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.",

**Comment by keegancsmith** [comment]
In future can you cc @sourcegraph/core-services so it pops up in our notifications :)

**Comment by keegancsmith** [comment]
If I am not mistaken the fix here is to properly surface the error returned from the GitHub API? We should mostly be treating the search queries as opaque, since GitHub is responsible for parsing and running them. If we correctly passed on the error message that github returned do you think that is sufficient @ryan-blunden?

**Comment by tsenart** [comment]
The fix here is to display a better error message to the user to make him aware that the org name he inputed is not correct.

**Comment by ryanslade** [comment]
FYI. this is the error message I get when running our latest code:

![image](https://user-images.githubusercontent.com/25610/71830686-ee153a00-30af-11ea-94ac-06eb3c48d185.png)

**Comment by ryanslade** [comment]
The root cause of the issue is that the org doesn't exist, so during sync GitHub returns a 404.

The request passes through many layers meaning that all we have as a result is the string:
`request to http://127.0.0.1:3180/orgs/my-org-name/repos?sort=created&page=1&per_page=100 returned status 404: Not Found`

The route taken is: Resolver -> repo-updater (via http) -> github (via github source via http)

We could refactor that code to bubble the original http code back up the chain. The question then is what to do with it at the resolver level. We could have a mapping of common status codes to human friendly error messages but I'm not sure whether for example a 404 from github means the same thing as a 404 from bitbucket.

Perhaps I can cover the single case we've seen here and we can add more in the future? What do you thing @tsenart?

**Comment by tsenart** [comment]
> Perhaps I can cover the single case we've seen here and we can add more in the future? What do you thing @tsenart?

Sounds good to me.
