### ISSUE TITLE
Update error message when navigating to old subscription page on dotcom

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#39837]
In 2021, the decision was made to stop allowing self-service sign-ups of the Teams plan on dotcom. At that time, we [removed the 'new subscriptions' button](https://github.com/sourcegraph/sourcegraph/issues/28987) from the subscriptions page on dotcom as a stop-gap to prevent users from signing up on this new plan. 

Recently, a team discovered that if they navigate to the URL (ex: https://sourcegraph.com/users/ryphil/settings/subscriptions/new), the page and functionality still exists. Using this method, they were able to self-service purchase an outdated plan of Sourcegraph. This new subscription page returns 404 on k8s and S2. More details in the [Slack thread](https://sourcegraph.slack.com/archives/C4P2446PN/p1659135668339169).

Definition of success:
- The new subscription page is completely removed from dotcom

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/39837?planning-poker) with ZenHub @kopancek @miveronese @pjlast

**Comment by miveronese** [comment]
It looks like this issue was partially solved. 
When navigating to https://sourcegraph.com/users/<USERNAME>/settings/subscriptions/new, I could confirm that the page still exists. It shows an error message. Will label this as a bug, so we can address it as such.


![Image](https://user-images.githubusercontent.com/1552863/192621304-3d07483f-0504-40d4-a24c-7eadae043fa9.png)
