### ISSUE TITLE
insights: create a list of what aggregations are available based on a possible search query

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#39929]
It will be necessary to know what aggregations should be possible to group on based on the search that is being executed.  Review the potential search keywords and document what aggregations should be possible.

`type:` and `select:` are the two that immediately come to mind that would change what aggregations are possible.

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by CristinaBirkel** [comment]
Most of the query modifiers are filters and won’t affect the type of aggregations we can run. In general we can expect to get Repo, File and Capture Group aggregations. Here is a list of the potentially interesting cases I found around select and type.
 
**`select:repo` (or repo matches)**
- With `type:repo` we could get capture groups
 
**`select:file` (or file matches)**
- Repo
- With `type:path` we could get capture groups
 
**`select:content` (or content matches)**
- Repo
- File
- Capture groups
 
**`type:diff`**
- Repo
- File
- Author
- Capture groups
 
**`type:commit`**
- Repo
- Author
- Capture groups
 
**`type:symbol`**
- Repo
- File
- Capture group
 
**`type:path`, `type:repo`**
- Just want to call out that this will work a little differently for capture groups in that it will match on the path or the repo name instead of matching in the file. May not make a difference in the implementation if we’re getting the right matches back, but just a heads up.

**Comment by CristinaBirkel** [comment]
@chwarwick would you confirm if this is what we're looking for here? Is there a follow up to this issue?

**Comment by chwarwick** [comment]
@CristinaBirkel Thanks yes this is helpful, we can use this as an input into what aggregations are possible.  

It's also interesting I hadn't thought about the capture group output against things like repo matches, but I could see how that might be interesting.

**Comment by felixfbecker** [comment]
Cross-posting from https://github.com/sourcegraph/sourcegraph/issues/39955#issuecomment-1207007461

> I think it's reasonable to always remove `select:` operators for aggregation. If you think about the equivalent SQL, the default in our search is essentially `SELECT *`, and when we run an aggregation, we change that to `SELECT COUNT(*)` (you need to have an aggregation function selected in SQL when using `GROUP BY` or the query will error). Therefor, if the user had specified `SELECT repo` instead of `SELECT *`, it's still reasonable IMO to replace that with `SELECT COUNT(*)` (which basically means just removing any `select:` operator).
