### ISSUE TITLE
Add "View in Perforce" button similar to other code hosts

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#39932]
A customer has built a private extension that emulates our View on GitLab/GitHub button but for Perforce. With the removal of Sourcegraph extensions and the intent of supporting Perforce as a first class code host, we should provide this functionality to our users.

There's also a [Product Gap](https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap__c/a1B5b00000K4U0pEAF/view) for this feature

**Comment by philipp-spiess** [comment]
Is this a potential 4.0 feature? I wonder how we should prfioritize this!

**Comment by ryankscott** [comment]
It's a "nice to have". If we get through all of the others we could add this. It ties in with https://github.com/sourcegraph/sourcegraph/issues/39490 for Gerrit too.

**Comment by philipp-spiess** [comment]
Cool I'll keep it in the backlog then but don't assign a milestone/4.0 tag yet. Same for the Gerrit task.

**Comment by vdavid** [comment]
It may be easy or difficult to create a button for this next to “Open in Editor”. The reason for my uncertainty is that I have no idea how Perforce and Gerrit work.
If these tools are either
a) web-based and there is a standard URL pattern to open (e.g. `https://{gerrit}.{company}.com/{repoName}/{filePath}`) **or**
b.) not web-based but have a standard protocol handler and a standard pattern (e.g. `gerrit://{repoName}/{filePath`)
then it should be easy. In this case, all we'd need to do is:
- Add a button to the same place where I'm adding “Open in Editor”
- Create settings to set up the URL for Gerrit and Perforce, and perhaps an additional one to enable/disable Gerrit.
- For Perforce one, we should implement automatic recognition (_if_ Perforce repo _then_ display button, otherwise not)
That seems like pretty much it.

If they are more complicated / less standard than the above, then it's probably more work.

**Comment by riking** [comment]
Gerrit is a code-review tool only\* and requires an external repository browser to be specified.

Example: On https://cl.tvl.fyi/admin/repos, "Repository Browser" is an external link to cgit at https://code.tvl.fyi/ . The administrative All-Users and All-Projects repositories do not have functional browsers and you need to download the code locally to view it.

**Comment by vdavid** [comment]
Helpful conversation [here](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1661199648671299)

**Comment by vdavid** [comment]
Q&A with the client (answers slightly edited):

1. Do you want an “Open in Perforce Swarm” button to be displayed on the **commit** page ([screenshot](https://share.cleanshot.com/26Ckse)), the **file** page ([screenshot](https://share.cleanshot.com/tRgRFu)), or **both**?

**Both** would be ideal, but there could be a difference in the functionality:
- On the **commit** page, users would usually like to open the CL in Swarm.
- On the **file** page, they'd like to open the file in Swarm. The file version that is opened from Sourcegraph should be the same one that is opened in Swarm. To do this, we could use the GraphQL API in the extension to get the CL number from the commit message of the commit at which the file is being viewed in Sourcegraph, and then open the file version at that CL in Swarm (which I couldn’t figure out how to do so I just opened the CL in Swarm instead)

2. If I understand correctly, you want Swarm URLs to be built like `https://swarm.{company}.com/1234` where `1234` is the CL ID. Is this correct?

Yes. Swarm has an internal redirect from `/1234` to `/changes/1234`. The Swarm URL to open a file/directory looks like `/path/to/the/file/in/perforce`. And how to open a file at a particular CL, is something I haven’t found the answer to yet in the time I had spent on this earlier.

3. How to properly get the CL ID? I could grab it from the end of the commit messages. Is this an elegant solution, or sort of a hack? Like, is this a standard for Perforce in general?

Sourcegraph’s current Perforce integration is based on a tool called `git-p4.py`, which always appends the CL number from which a particular commit has been generated, at the end of the commit message.
However, what we use is an experimental tool called `p4-fusion` that we built that also generates the commit messages of the same format. (This stays true unless there are changes made to the arguments that are sent into `git-p4.py` which can change the commit message format)
Is there a method that is more sure-shot and less error prone? I am not sure if it exists in our current implementation. Since Sourcegraph’s way of generating commit IDs is largely a hash of the state of the Perforce depot, it is impossible to get the CL number from the commit hash alone. If there was a way, it would be the best solution. We have had discussions about making changes to `p4-fusion` so that it generates a mapping of the CL numbers to the commit hashes which could make this simpler but it is just an idea at this stage

4. When I’m on a file page, ideally, which commit do I want?

I think the users would expect to see the CL that last touched that file, or if possible, they could see the file itself in Swarm at the version that user was viewing it in Sourcegraph (e.g. in case of a `repo:org/repo@hash` search)

**Comment by vdavid** [comment]
Rough task list:
- [x] Understand the request: Read the Slack communication.
- [x] Get access to a Perforce server
- [x] Set up a Perforce client to see server contents
- [x] Connect a local instance to the Perforce server
- [x] Use the [code](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1661241681432519?thread_ts=1661199648.671299&cid=C01D50MSA7L) written by our contact as a starting point
- [x] Ask for details from the client, and process this response
- [ ] Figure out how Swarm CL + file URLs look like
- [ ] Figure out how to get the repo URL from the file page in the case of Perforce (I haven’t found it so far 😕 )
- [ ] Figure out whether the action bar could easily be made visible on commit pages. If not, add it, and make sure it's hidden if it's empty
- [ ] Add the button to both the file and commit pages, with a Perforce icon
- [ ] Set up the button on the commit page to link to the related CL
- [ ] Set up the button on the file page of a specific commit to link to the CL&file on Swarm
- [ ] Set up the button on any other file page to link to the closest CL & file on Swarm
- [ ] Do a round of testing
