### ISSUE TITLE
Create a design of the page and get it approved

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#39997]
This is the first step of creating the UI for 1-click export page.

Link to proposed UI blueprint: https://sourcegraph.slack.com/archives/C02DUJRQP70/p1657502264142609?thread_ts=1656506211.384079&cid=C02DUJRQP70

/cc @jplahn @ryphil

**Comment by indradhanush** [comment]
Pasting the contents of the above Slack link in the issue since Slack content is ephemeral.



> @ryphil: I agree that this UI should be something simple and easily configurable for admins. Is there any more advice you're looking for?
It appears our design system is missing a few parts of this but I threw something very basic together if it would be helpful to see. There may be other export options to add/remove.
Does this match what you're planning? I trust you to implement something based on the components and we can iterate from there!
> 
> ![image](https://user-images.githubusercontent.com/2682729/183483728-f1ea9ed8-1b64-4c2d-9095-9ffa19348718.png)
