### ISSUE TITLE
Prometheus: report CPU usage for indexed-search

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4003]
This query `(max by (job)(irate(process_cpu_seconds_total[5m]))) * 100` shows CPU usage over time for different processes, but doesn't include indexed-search. We should include indexed-search.

Customer: https://app.hubspot.com/contacts/2762526/company/464956351

**Comment by slimsag** [comment]
The metric you are talking about, `process_cpu_seconds_total`, comes from Kubernetes/Docker native Prometheus integrations. If it excludes a process, it would be a bug in one of those.

Are you positive you didn't mix up `indexed-search` and `zoekt-webserver` / `zoekt-indexserver`? (the latter is what it would appear as I believe, since `indexed-search` is actually those two separate services in one container)

**Comment by beyang** [comment]
It doesn't show up on prometheus.sgdev.org, either: https://prometheus.sgdev.org/graph?g0.range_input=1h&g0.expr=(max+by+(job)(irate(process_cpu_seconds_total%5B5m%5D)))+*+100&g0.tab=1

**Comment by slimsag** [comment]
Yeah, looks like service discovery isn't working on that deployment: https://prometheus.sgdev.org/targets

Likely because it is one of the only deployments we have with two containers & it is something specific to that.
