### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4005]
Prometheus metrics for:
* lang servers
* code intelligence

Track this specifically for certain repos (e.g., specify list of mono-repos)

Customer: https://app.hubspot.com/contacts/2762526/company/464956351

**Comment by slimsag** [comment]
> Track this specifically for certain repos (e.g., specify list of mono-repos)

@beyang Is there a reason we wouldn't want to track this for all repos?

**Comment by beyang** [comment]
We probably want to track this in aggregate, but I think the cardinality of the set of all repos might be too large to have as a Prometheus label in some cases (see the [warning](https://prometheus.io/docs/practices/naming/#labels) about high-cardinality label sets in the Prometheus docs).

However, the site-admin at https://app.hubspot.com/contacts/2762526/company/464956351 wants to track these metrics for a select set of repos in particular (mainly the big important ones at his company).

**Comment by slimsag** [comment]
Yes, the carnality of all repos is definitely too much I wasn't trying to suggest that. Rephrasing my question:

The initially intuitive thing to me is to track langserver/codeintel metrics across all repositories. After all, even if it is not in a big important repository, if codeintel is throwing errors or slow it affects the site admin's users all the same -- regardless of the repository it occurred in. This makes me wonder _why_ the admin wants to track a specific list of repos instead of all in general?

Possible answers I can think of include:

1. The site admin thinks that would be too high level and thinks perf/error-rates from non-important repos would skew the results?
2. The site admin thinks tracking all repos in aggregate would be too resource intensive, hinting that maybe they want something much more detailed than Prometheus metrics?

**Comment by beyang** [comment]
It is more the first. There's a long tail of smaller repos, many of which are personal forks and are more likely to error. This customer is moving more toward mono-repos, as well, so as more and more of their devs work in one of the monorepos, the less they care about the long tail of smaller repos.
