### ISSUE TITLE
Wildcard: Button group has incorrect visual behaviour 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#40094]
## Background

In code insight compute-powered creation UI we use button group component for rendering different mode for query aggregation. It appereace that if we disable one of the group button all buttons start to have incorrect visual styles (see image above)

![](https://user-images.githubusercontent.com/20326070/179753631-5d2294e6-5df1-42e4-bb57-bdc4762d3afa.png)

I assume this problem comes from the fact that these buttons have tooltip and for disabled button with tooltip we wrap these buttons with additional div in order to solve problem with tooltip for the disabled buttons. 

/cc @taylorsperry @jasongornall

**Comment by taylorsperry** [comment]
@lrhacker Tooltips! Your favorite! Mind taking a peek at this?

**Comment by lrhacker** [comment]
@vovakulikov I did confirm that the issue is from what you assumed (that the disabled buttons must be wrapped in another element to display a tooltip when disabled). [Here's a PR](https://github.com/sourcegraph/sourcegraph/pull/40830) that should help address this issue - though I still need to really test and make sure these changes don't cause regression on button group styles elsewhere.
