### ISSUE TITLE
Error: no such host 

### ISSUE THREAD

**Issue by theoryshaw** [sourcegraph/sourcegraph#40159]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Windows chrome

#### Steps to reproduce:

go here: https://sourcegraph.com/search?q=context:global+open+repo:%5Egithub%5C.com/IfcOpenShell/IfcOpenShell%24+file:src/ifcopenshell-python&patternType=standard

#### Expected behavior:
see appropriate search results

#### Actual behavior:
example of error: `git command [git rev-parse e4016313c49e85389ed6e5f2042fda0e5a72c9c1^0] failed (stderr: ""): Post "http://gitserver-17.gitserver:3178/exec": dial tcp: lookup gitserver-17.gitserver on 10.165.0.10:53: no such host`
![image](https://user-images.githubusercontent.com/507113/183722542-558eaa79-da33-4e32-95f3-0f68cf21e218.png)

/cc @sourcegraph/search-core

**Comment by malomarrec** [comment]
Hey @Joelkw, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by malomarrec** [comment]
Hey @Joelkw, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by Joelkw** [comment]
@eugeniaft is this search-core related?

**Comment by keegancsmith** [comment]
The issue here is actually syntax highlighting failing. In particular, gitserver is down. I am assuming this happened during a deployment. This should happen very rarely, and we explicitly made the tradeoff on simplifying gitserver and accepting a little bit of downtime once or twice a week on sourcegraph.com.

The team that would own this long term would be repo-management.

Either way I am closing this as won't fix, unless the person experienced this a lot. Then they can re-open.
