### ISSUE TITLE
Make filters panel full-height

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#40183]
I think we just didn't specify this explicitly enough in the design, but the filters panel should always be full height.

![CleanShot 2022-08-09 at 21.33.11.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/838175fd-0e69-4fc9-ae8b-60af333e6b27)

**Comment by limitedmage** [comment]
@benvenker Unfortunately, due to CSS limitations, there seems to be no way to do this with this design while still keeping the nice floating sticky scrolling behavior. So either:

A. Keep the current behavior of the floating sticky sidebar that doesn't fill the whole height if the sidebar doesn't exceed the screen size, keeping the padding.
B. Make the whole sidebar one color (remove the top padding) and that color fills the whole height [(screenshot)](https://user-images.githubusercontent.com/206864/186263146-6fc88e79-7e7b-4f12-96eb-b99d9992f8f2.png)
C. Remove the sticky behavior.

I think A (leaving as-is) is the best choice.

**Comment by limitedmage** [comment]
@benvenker Due to technical limitations, there is no way to achieve this via pure CSS, but there is a way to do this via JS/DOM manipulation. This has possible performance implications (we need to recalculate the size of the sidebar on every render and resize). Do we still want to go ahead and do this?

**Comment by benvenker** [comment]
Hm. @almeidapaulooliveira i wonder if there is another solution? What would you think about removing the darker background color so that the filter panel content was more like part of the page?
