### ISSUE TITLE
flake: TestRunCommandGraceful_context cancel

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#40431]
Flake in https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server_test.go?L1541&utm_campaign=search&utm_source=raycast-sourcegraph

https://buildkite.com/sourcegraph/sourcegraph/builds/167350#0182a740-e3ed-4ea2-b981-08a7a76de09d

/cc @jplahn @ryphil

**Comment by ryanslade** [comment]
I'll take this and look into it this week since I added it originally.

**Comment by mrnugget** [comment]
The problem is that this `select` here is not deterministic: https://github.com/sourcegraph/sourcegraph/blob/f2dd23b8287b6db17798f9df4c9246120f8089e3/cmd/gitserver/server/server.go#L135-L136

If a context is cancelled due to a deadline (as in the test), then it's not guaranteed that `<-ctx.Done()` returns something before `<-done`.

**Comment by mrnugget** [comment]
Nevermind. The `runCommandGraceful` function is never used.
