### ISSUE TITLE
CodeMirror Blob: Font difference

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#40484]
**Current file blob**
<img width="1125" alt="Screen Shot 2022-08-17 at 11 30 07 PM" src="https://user-images.githubusercontent.com/87138876/185163227-2b5342ec-a62c-4433-80fc-fe47243facaa.png">

**CodeMirror**
<img width="1119" alt="Screen Shot 2022-08-17 at 11 30 00 PM" src="https://user-images.githubusercontent.com/87138876/185163121-18dbf019-f8ae-4012-9440-d58c21ecb616.png">

I'm having a really hard time identifying the difference in code, as I'm inspecting the same font family and size. But from the side-by-side comparison (take a look at the first line `package auth contains`...), the font looks subtly different...

**Comment by sqs** [comment]
I believe this is a release blocker for 4.0. The font looks significantly different to me than the previous blob view, and it looks a lot more like "Courier New". The characters have less font weight to my eye and look like a fallback font family instead of intentional.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/1976/188297766-379509ab-3a98-48aa-bce9-736977cacde6.png">

**Comment by macraig** [comment]
@sqs completely agree this is a blocker to release the CodeMirror blob. Just to clarify, the blob view release isn't in scope for 4.0. A hard requirement for release is that we have high confidence in UI parity and stability, for which we need to solve all the P1 issues flagged for the CodeMirror blob in the [Code Navigation board](https://github.com/orgs/sourcegraph/projects/211/views/21).
