### ISSUE TITLE
Bitbucket Server / browser extension makes it impossible to copy+paste code

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4051]
A user at https://app.hubspot.com/contacts/2762526/company/407948923 has reported that the Bitbucket Server browser extension integration makes it impossible to copy+paste code.

Keywords: select, selection, selections

**Comment by slimsag** [comment]
Additional details at: https://sourcegraph.slack.com/archives/C0W2E592M/p1557960731006100

cc @sourcegraph/code-nav

**Comment by chrismwendt** [comment]
I was able to repro this yesterday (browser extension v19.4.26.1859)

I'm not able to repro this today (browser extension v19.5.16.1439)

Could we ask the user for the version of their browser extension?

**Comment by slimsag** [comment]
@chrismwendt @felixfbecker @lguychard instead of asking the user for their version (I am hesitant to do that given we should be able to confirm this without interrupting them), can we try reproducing this on the old version (e.g. using the browser extension dev setup) and the new version and confirm it was broken in the old version but not the new one and identify which commit likely fixed it?

**Comment by chrismwendt** [comment]
Shoot, the problem persists on v19.5.16.1439. I'm debugging this now.

**Comment by slimsag** [comment]
Oh strange, thanks for confirming! Feel free to debug on monday instead :)

**Comment by chrismwendt** [comment]
I think this is broken because we mutate the code host's DOM.

CodeMirror (used in Bitbucket) overrides the browser's click-n-drag text selection:

![image](https://user-images.githubusercontent.com/1387653/58052574-109b1880-7b0a-11e9-8d38-3a7ef2f47584.png)

Linking to https://github.com/sourcegraph/sourcegraph/issues/2550 because both of these issues would likely be fixed by a single solution.
