### ISSUE TITLE
patternType:standard mislabels regexp patterns inside parenthesis as literal patterns

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#40511]
Search queries with a pattern field that should be interpreted as regexp (inside `/.../`) will instead parse as literal if the pattern is wrapped in parenthesis. Examples:

[`insight[s]` ](https://sourcegraph.sourcegraph.com/search?q=context:global+insight%5Bs%5D&patternType=standard) is parsed as literal and returns no matches ✅ 
[`/insight[s]/`](https://sourcegraph.sourcegraph.com/search?q=context:global+/insight%5Bs%5D/&patternType=standard) is parsed as regexp and returns matches ✅ 
[`(/insight[s]/)`](https://sourcegraph.sourcegraph.com/search?q=context:global+%28/insight%5Bs%5D/%29&patternType=standard) is parsed as a literal and returns no matches. ❌ 

This can be verified by checking the annotations in the query parser.

`(/asdf/) lang:go` query.SearchTypeStandard
> msg=annotations: labels="[HeuristicParensAsPatterns Literal]"

/cc @benvenker @lguychard

**Comment by lguychard** [comment]
Note [`(foo)`](https://sourcegraph.sourcegraph.com/search?q=context:global+%28foo%29&patternType=standard) also searches for the literal `(foo)` rather than `foo`, so at least we are being consistent and this is not specific to regex patterns (but rather, to an unexpected interpretation of the ambiguous syntax that are parenthesised single patterns).

**Comment by rvantonder** [comment]
> [(/insight[s]/)](https://sourcegraph.sourcegraph.com/search?q=context:global+%28/insight%5Bs%5D/%29&patternType=standard) is parsed as a literal and returns no matches. ❌

This case is currently intended behavior. For example, we don't highlight/indicate this as a potential expression in the query bar either, it is treated and searched as a literal:


<img width="539" alt="Screen Shot 2022-09-07 at 12 43 36 PM" src="https://user-images.githubusercontent.com/888624/188963461-98ed29fe-ea44-468c-89b6-d2d1d190d81a.png">

The convention is in keeping with the literal mode convention that any single pattern inside `(...)` is a literal pattern, not an atomic expression. The reason behind the convention is that an atomic expression is largely not useful: there is be no semantic difference between `(/xyz/)` and `/xyz/`. If there's a case where using `(/insight[s]/)` instead of just /insight[s]/` would provide some benefit it'd be great to know about, but I can't see one immediately. Just to be clear `(/insight[s]/)` would never have the parens refer to a regular expression group, the appropriate syntax for that would be `/(insight[s])/`.

In the converse, it could be useful to interpret `(blah)` and respectively `(/blah/)` literally instead of atomic patterns--this is a reasonable syntax to try and search for literally (e.g., functions, lisp, etc). That is what the `HeuristicParensAsPatterns` label corresponds to.

> Just curious, does this also address https://github.com/sourcegraph/sourcegraph/issues/40511? I suspect it may be the same thing from the description

What's different here is the syntax reveals we have a bonafide n-ary expression (`AND` terms) and parens are meaningful for such expressions.

**Comment by coury-clark** [comment]
@rvantonder I see, thanks for the clarification. I originally stumbled upon this by writing a query similar to this:
```
(test repo:A) or (/insight[s]/ repo:B)
```

It seemed a natural way to express the query to me (grouping the repo filter with the pattern), and it turns out in this case the `/insight[s]/` will be interpreted as regexp. However, when removing the repo scopes
```
(test) or (/insight[s]/)
```

both patterns are then treated literally and ultimately a different set of results will match.

I'm not sure if its a property that removing a repo filter (for example) should always yield the same results (but globally), but it seemed somewhat intuitive at the time.

**Comment by rvantonder** [comment]
Ah OK, yeah so I see how you would get there by editing an existing query with parenthesized expressions :-) And I agree on how, when heuristic behavior then kicks in, would throw you off and not be intuitive ("I just deleted a term from my expression and now the parentheses are meaningful, huh?"). 

Heuristics have tradeoffs and that example runs into the cons. It's really difficult to know when users interact with the queries like your example, versus they get benefit from treating parens literally (e.g., when they're maybe using search for more simple things). We can change the behavior here, but that change should be one directional (i.e., we should be sure it's better). Because, respectively, making the change is high risk, if users are accustomed to the convention. I have low confidence whether it's the right tradeoff and worth the risk.

The best mitigation would be, e.g., enable a "strict" mode (no heuristics) but anytime we run into "custom semantic user preferences" for search it becomes a very complex.

**Comment by coury-clark** [comment]
Yep, understood there are tradeoffs. Most important thing for us at the moment is understanding what it does and whats supposed to happen, so thanks for the clarifying comments! Closing this issue since it seems to be working as intended, and if changes need to be made can revisit.

**Comment by rvantonder** [comment]
@coury-clark np, thanks for making the issue + discussion, useful to have a log of confusion if others run into this
