### ISSUE TITLE
Sourcegraph.com site-admin section gives "Reload required" warnings

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4057]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Be an admin on sourcegraph.com
2. Visit most site-admin pages, e.g. https://sourcegraph.com/site-admin/repositories

**Comment by felixfbecker** [comment]
It's probably a different error that's unintentionally detected as a "reload required" error. This PR I did in January would have prevented the red herring: https://github.com/webpack/webpack/pull/8615

**Comment by attfarhan** [comment]
I am not working today and don’t have special context on this, maybe best to reassign if it’s release blocking @beyang?

**Comment by slimsag** [comment]
Thanks @attfarhan -- unassigned you

**Comment by ggilmore** [comment]
This seems to be breaking all the extension pages: https://sourcegraph.com/extensions/sourcegraph/go:

![Screen Shot 2019-05-16 at 3 08 39 PM](https://user-images.githubusercontent.com/9022011/57890445-8b9fbe80-77ec-11e9-982c-dde6b96c6ed7.png)

Javascript level errors:

```js
The resource from “https://sourcegraph.com/.assets/scripts/16-8ed8be7cd163fc52f6d8.chunk.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
go
Error: "Loading chunk 16 failed.
(error: https://sourcegraph.com/.assets/scripts/16-8ed8be7cd163fc52f6d8.chunk.js)"
    o Webpack
breadcrumbs.ts:112:37
Loading failed for the <script> with source “https://sourcegraph.com/.assets/scripts/16-8ed8be7cd163fc52f6d8.chunk.js”.
```

**Comment by slimsag** [comment]
That URL is a 404 which is why the mimetype appears wrong:

```
$ curl -i https://sourcegraph.com/.assets/scripts/16-8ed8be7cd163fc52f6d8.chunk.js
HTTP/2 404 
date: Thu, 16 May 2019 22:12:36 GMT
content-type: text/plain; charset=utf-8
content-length: 14
set-cookie: __cfduid=d7ebae7a76834b646b4e84c873281b0881558044756; expires=Fri, 15-May-20 22:12:36 GMT; path=/; domain=.sourcegraph.com; HttpOnly
access-control-allow-credentials: true
cache-control: no-cache, max-age=0
x-content-type-options: nosniff
x-frame-options: DENY
x-trace: https://app.lightstep.com/sourcegraph-prod/trace?span_guid=3626915c8eb7ddd3&at_micros=1558044756686585#span-3626915c8eb7ddd3
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15724800; includeSubDomains
cf-cache-status: MISS
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4d80b1b069b39887-LAX

404 Not Found
```

So the question becomes why is the JS chunk URL wrong?

**Comment by slimsag** [comment]
Since this is breaking all extension and site admin pages (but not search, repo, or code view pages as far as we can tell -- and doesn't affect all users yet due to Cloudflare caching), this is a P1 but not P0 I believe.

Someone should look into this soon (next few days) and definitely a release blocker.

**Comment by sqs** [comment]
I just tried purging https://sourcegraph.com/.assets/scripts/app.bundle.js?ce7730d44230bcdf0a75a952238c0124 and https://sourcegraph.com/.assets/scripts/app.bundle.js from our Cloudflare cache. This is to test @slimsag's idea that it is a problem that " doesn't affect all users yet due to Cloudflare caching". After purging the cache, I am still not seeing the problem, so my current hypotheses are:

- something *old* and still cached is causing this problem (not something *new* that is slowly propagating to caches and affecting more users)
- somehow 2 sourcegraph-frontend pods at different versions got deployed

---

Can any 1 person (only 1 needed) who is experiencing this problem on https://sourcegraph.com/extensions/sourcegraph/go please:

1. Load https://sourcegraph.com/extensions/sourcegraph/go with Chrome or Firefox network devtools open
1. Confirm the problem occurs
1. Save a HAR with the entire network fetch (eg **Save all as HAR with content** in the Chrome right-click menu on any network request)
1. Send the HAR to me
1. Try hard-reloading the page (eg check **Disable cache** in network devtools and reload) and tell me if the problem still occurs

If that isn't possible, here is a 2nd best process that will help me find the problem:

1. Load https://sourcegraph.com/extensions/sourcegraph/go with Chrome or Firefox network devtools open
1. Confirm the problem occurs
1. Screenshot their entire browser with the network devtools tab and the `app.bundle.js` request in view
1. Try hard-reloading the page (eg check **Disable cache** in network devtools and reload) and tell me if the problem still occurs

**Comment by dadlerj** [comment]
@sqs I no longer see this. I believe @slimsag rolled back frontend before you posted this (see https://sourcegraph.slack.com/archives/C08JA8Q1H/p1558055858082900)

**Comment by beyang** [comment]
Can anyone repro this on the latest release candidate? If not, I don't think it qualifies as a release blocker.

**Comment by sqs** [comment]
Things ruled out:

- I can't think of anything in https://sourcegraph.com/search?q=repo:^github\.com/sourcegraph/sourcegraph$+type%3Adiff+f%3Awebpack+after%3A%222+weeks+ago%22 that would have caused it.
- We properly set no-cache headers on assets 404s, so a deploy-in-progress with temporarily multiple `sourcegraph-frontend` pods running should not cause this.
- If there were multiple sourcegraph-frontend versions running for a prolonged period, that also should not cause this problem because the assets 200s would be cached forever with `cache-control: immutable, max-age=172800, public`.

I'm down to the following hypothesis:

- We upgraded minor versions of Webpack (4.30.0 -> 4.31.0)  5 days ago in 900abd972fb71d3999646040dfdf07b7277909c8.

which I am testing now

**Comment by sqs** [comment]
I am not able to repro on the RC 3.4.0-rc.5, and I was also not able to repro this problem on any of the sourcegraph/server image tags corresponding to the sourcegraph/frontend images that were deployed during the problem's existence today on Sourcegraph.com.

So my best guess now is that this is a bug involving our deployment, and it wouldn't affect customers.

One fact that supports that is that our site-admin area is actually hit in e2e tests ([proof](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@392986c01d02c790a75713a5157eded48fa6c0de/-/blob/web/src/e2e/index.e2e.test.tsx#L167:37)), and we know those passed in CI and got deployed. So that means that if you remove factors related to our Sourcegraph.com deployment, it worked correctly even on the versions that were deployed to Sourcegraph.com.

Therefore I think this is NOT a release-blocker. And for fixing it, I have NO idea how to do so without being able to repro it...perhaps just to roll forward on Fri night or Sat morning (with lower usage) and monitor for problems?

---

Other notes from my exploration... (none fruitful, except to rule out other obvious things)

<details>
In deploy-sourcegraph-dot-com I looked for the commit BEFORE @slimsag's rollback commit 690ae9fb60cea9469d704974f655ec7dfc63dac7. That previous commit is 690ae9fb60cea9469d704974f655ec7dfc63dac7. This 690ae commit is the commit (or one of many commits) deployed to Sourcegraph.com that exhibited this problem.

The 690ae commit refers to Docker image SHAs from the Buildkite build at https://buildkite.com/sourcegraph/sourcegraph/builds/35269#565efed0-333a-48e0-b1d9-5845716904cf (which I found by looking at the timestamps and ctrl-F'ing in the Buildkite logs).

The 690ae commit also built `sourcegraph/server@sha256:6697b4e16adc8d1c9f7884d2ac4ce08aac96f3e7776c56a195a096f44215bf45`, which I ran locally to repro.

Hmm, the web app doesn't have the `16-8ed8be7cd163fc52f6d8.chunk.js` fragment that was reported as bad in https://github.com/sourcegraph/sourcegraph/issues/4057#issuecomment-493249154. So this must not be the same version that the problem occurred on on Sourcegraph.com.

OK, the previous deploy-sourcegraph-dot-com to 690ae is e26dcb9dafe2e93486a96aad10636fa1e7fe631b. The Docker image it refers to was built in https://buildkite.com/sourcegraph/sourcegraph/builds/35168#98768118-07b1-44ba-aa52-e3bcdc97a800, and that build's server image is `sourcegraph/server@sha256:dbdea824f38258e2d7771b8c1424d658f1aedde50c414a9ac0bc822d2257813c`.

That also doesn't have the `16-8ed8be7...chunk.js` file. So that also appears to not be the same version as the one where the Sourcegraph.com problem occurred.

Anyway, even though I was not able to run the exact version that people reported Sourcegraph.com issues on, on none of these (plus the 3.4.0-rc.5) did the problem occur.
</details>

**Comment by slimsag** [comment]
> perhaps just to roll forward on Fri night or Sat morning (with lower usage) and monitor for problems?

Sounds fine to me. From everyone who saw it occur, it only affected non-critical pages like explore/extensions/site-admin/settings pages anyway. Will give this a go tomorrow night if I have time.

**Comment by ggilmore** [comment]
Note @sqs, you can figure out what commit an image comes from with `docker inspect` now:


```console
> docker pull sourcegraph/frontend:insiders@sha256:35e1c4ad694241793abe309012e03bf02472a3a011bdb450d03e61e1bc442012 
> docker inspect sourcegraph/frontend:insiders@sha256:35e1c4ad694241793abe309012e03bf02472a3a011bdb450d03e61e1bc442012 | jq ' . [] | .Config.Labels'
```

```json
{
  "com.sourcegraph.github.url": "https://github.com/sourcegraph/sourcegraph/commit/5707ece5829adbf9cad912661df0038243bf1ff9",
  "org.opencontainers.image.created": "2019-03-19T15:25:14Z",
  "org.opencontainers.image.documentation": "https://docs.sourcegraph.com/",
  "org.opencontainers.image.revision": "5707ece5829adbf9cad912661df0038243bf1ff9",
  "org.opencontainers.image.source": "https://github.com/sourcegraph/sourcegraph/",
  "org.opencontainers.image.url": "https://sourcegraph.com/",
  "org.opencontainers.image.version": "29690_2019-03-19_5707ece"
}
```

**Comment by keegancsmith** [comment]
Did we attempt to fix this? I don't see any updates on what we did since Thursday.

**Comment by sqs** [comment]
Not that I’m aware of.

**Comment by keegancsmith** [comment]
If I am not mistaken, if we don't roll forward we can't inform instances that the 3.4 update is available.

**Comment by slimsag** [comment]
Yes, I didn't have time on Fri to try rollout again but will in the next few hours.

**Comment by slimsag** [comment]
I've done two things:

1. Redeployed the same version where we saw this originally, all looks good and can't be reproduced by folks who previously could reproduce.
2. Deployed the latest insiders, again all looks good.

I know not knowing what the cause here is sucks, but given we cannot reproduce this at all anymore leads me to believe this may have been a Cloudflare cache serving an old copy somehow. Regardless, there is nothing more we can effectively do here so I am closing this for now.
