### ISSUE TITLE
CodeMirror blob: implement all keyboard shortcuts when focused on the blob view

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#40730]
- [x] Fuzzy finder
- [ ] `/`
- [ ] `?`
- [ ] others?

**Comment by fkling** [comment]
It shouldn't be necessary to replicate the global keybindings because the blob view is not an input.

It actually looks like that this is a bug in the shortcut library (`@slimsag/react-shortcut`) we are using. It seems to ignore key presses when the blob view is focused because the element as the `contenteditable` attribute. However the value of that attribute is set to `false` and should therefore not be treated as an input element. I'll raise that issue on the dependency repo.

Of course the situation changes when we make the view have a text cursor (because then it's an input). But maybe we can extend the other library to accept arbitrary selectors for elements to be ignored.

**Comment by olafurpg** [comment]
@fkling very nice find. That simplifies a lot of things if we can fix the issue in react-shortcut. Ideally, it would be nice to inline that dependency into our main repo.

**Comment by fkling** [comment]
Slack discussion for how to go about fixing this: https://sourcegraph.slack.com/archives/C01C3NCGD40/p1663766838501219
