### ISSUE TITLE
Search sidebar aggregations UI doesn't match latest design

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#40766]
| Actual | [Design](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=246%3A11) |
|--------|---------|
| <img width="250" alt="image" src="https://user-images.githubusercontent.com/10532611/186270211-9ff18e8c-73c7-4f8f-9ece-a07342857560.png">| <img width="250" alt="image" src="https://user-images.githubusercontent.com/10532611/186269291-24701d78-5b0a-418c-b647-210d86e1c280.png"> |

- [x] Buttons should be individual buttons, not button groups
- [x] "Repo" should say "Repository"
- [x] "Grouped by" should say "Group results by"
- [x] <a id="chart-taller"></a>Chart is much taller than in design – this means it takes up much more vertical space in the sidebar compared to other search features.
   - In the design, chart including labels takes up roughly 160px, while in the implementation it is 205px. The largest bar in the design is 95px high, while in the implementation it is 140px high.
- [x] Not-hovered bars turn to gray on hover instead of to a different shade of blue
- [x] Error message has 14px font size instead of 12px (makes it look much bigger than surrounding text)
- [x] Empty and error state for the chart doesn't have "bars" background as it does in designs
- [x] Corners are more rounded than in design
- [x] There are no X axis ticks in design
- [x] Expanded view: Chart and table are not horizontally centered in page as in design

Still missing:
- [ ] Info icon (will be added in https://github.com/sourcegraph/sourcegraph/pull/40997)
- [x] "+N" indicator

Other changes:
- [x] "Save insights" button was cut from scope 

Follow ups:
- [ ] Chart area should take up whole width and not be narrower because the rotated labels take up space – instead according to the design, we should hide labels that don't fit in
  - @vovakulikov: out of scope for the V1, since this change requires much more work on data viz UI than we can afford at the moment
- [ ] Bars should be limited in count and wider, so that no intermediate labels are skipped

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by unclejustin** [comment]
@vovakulikov assigning to you as I think this is covered by https://github.com/sourcegraph/sourcegraph/pull/40803

**Comment by leonore** [comment]
feedback from a first play around with it:

UI nags:
* the general error `We couldn’t provide aggregation for this query. query unable to complete in allocated time. [Learn more](https://sourcegraph.test:3443/)`, could we append the error like `We couldn't provide aggregation for this query: [error]` i.e. add a `.`
* Also the Learn more link leads to nothing, if this is to be added once we write the docs can we add that to todo [in the issue](https://github.com/sourcegraph/sourcegraph/issues/40805)
* `Aggregation is not exhaustive, there are X groups more` -> `there are X more groups`

personal feelings:
* Is there any way we could make the first word of an error Uppercase? i.e. `this specific query does not support aggregation by PATH` -> `This specific query does not support aggregation by PATH`. I don't know if this is just my impression of it but it feels unpolished
* same comment for Uppercasing `PATH` -> `Path` i.e. not having the aggregation modes in all caps. (this seems like just a quick mapping to me- if it's harder to do on the frontend we could do it on the backend)
* it's a shame all the buttons don't fit on one line (but I know we are limited for space, so I don't know whether we can actually do something about that)

**Comment by felixfbecker** [comment]
Re: errors, agree and we have this component/util function for it: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@8b221033b402aed91479f8fea24a84cb473fc955/-/blob/client/branded/src/components/alerts.tsx?L15

**Comment by felixfbecker** [comment]
> would it be very user unfriendly to collapse the group by panel if we can't run a query? it feels like it might get frustrating

The intent is that you can still select attributes explicitly, so I don't think we should hide it

**Comment by vovakulikov** [comment]
Making it transparent I updated point about labels and chart width 
>Chart area should take up whole width and not be narrower because the rotated labels take up space – instead according to the design, we should hide labels that don't fit in (out of scope for the V1, since this change requires much more work on data viz UI that we can afford at the moment)

**Comment by leonore** [comment]
we should probably limit the number of errors displayed on the UI:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/29406849/186875109-e1e4ad9f-5b30-4198-9457-cbcc161d198d.png">

query: `[series\.(\w+) file:insights lang:golang -file:test select:content patterntype:regexp`

**Comment by vovakulikov** [comment]
@AlicjaSuska about this point
>Not-hovered bars turn to grey on hover instead of to a different shade of blue

It converts blue into the dark blue on the dark theme, but it does convert blue to grey colour on the light theme. I couldn't find a generic way to convert colours to darker ones with CSS filters. We need to find a generic algorithm that could handle all possible colours because we're dealing with wildcard shared charts and can't use hardcoded colours there. 

I propose to move this point into a separate issue and solve this problem in general for the bar chart.

**Comment by leonore** [comment]
I'm confused why I can't do anything here? there was a timeout/error and I can't select anything, and rerunning the search doesn't help (I'm assuming there's some caching involved)

https://user-images.githubusercontent.com/29406849/186909075-60c77881-a748-4688-a44d-40733106b571.mov

**Comment by vovakulikov** [comment]
@leonore I think this problem with aggregation mode availability with network error is fixed in this PR https://github.com/sourcegraph/sourcegraph/pull/40905

**Comment by CristinaBirkel** [comment]
Looks like @leonore found this one before I did! But I made an issue for the error overflow bug: https://github.com/sourcegraph/sourcegraph/issues/40940

**Comment by vovakulikov** [comment]
Nice just FYI @CristinaBirkel this PR should close all error UI bugs https://github.com/sourcegraph/sourcegraph/pull/40943

**Comment by felixfbecker** [comment]
Let's keep this issue discussion focused on anything not matching the design, not a general collection of all issues

**Comment by felixfbecker** [comment]
> It converts blue into the dark blue on the dark theme, but it does convert blue to grey colour on the light theme. I couldn't find a generic way to convert colours to darker ones with CSS filters. We need to find a generic algorithm that could handle all possible colours because we're dealing with wildcard shared charts and can't use hardcoded colours there.

Two thoughts:
- If we can convert the color dynamically to a darker blue in dark theme, why can't we do that in light theme? What about the light theme makes it harder?
- I see the point about not hardcoding colors in the chart component, but can't the consumer simply pass in two colors – one for the hover state, one for the default state? Or 4 colors, considering dark/light theme. A generic algorithm to mutate the primary colors dynamically seems overengineered to me

**Comment by vovakulikov** [comment]
My thoughts on chart size (It's my personal opinion) 

- Making it smaller doesn't solve any of the problems that we have on the search result page IMO. We still display the same amount of UI and information (in fact with smaller chart we display even more UI and information on the first screen because we render more filtres at once since there is more space because of smaller chart). 
- Small chart is hard to aim and hard to read and this is why as I think this UI feels squeezed and it looks like control board of space ship (where you have too many controls but non of them is useful because its size) 
- If we want to shrink the height of this panel I don't understand our decisions about aggregation button controls. In the original designs these controls were placed in one line but we make it wider because we care about button text (IIRC). Would it be more sense to make buttons in one line and make chart bigger by height? (this is a compromise because I see points to make buttons with full texts without abbreviations, repo → repository, group → capture group ...)
- This panel is still collapsable, so users if they are distracted by this panel could easily collapse it and we preserve this setting across different browsers and devices. 

cc @AlicjaSuska @felixfbecker

**Comment by AlicjaSuska** [comment]
@vovakulikov just to follow up on your last comment:
- the decision and context for buttons was that: we need to follow the content guidelines (repo vs. repository), there was no shorter label for 'capture group' that would convey the meaning and we couldn't use segmented button because the component didn't have the wrapping logic in it
- height of the chart: we need to take up as little space as possible. Since we're making it smaller vertically, it does not affect the clickable areas. For very small bars we need a minimal height anyways to meet the accessibility requirements.

I hope it clears up the decision.

**Comment by felixfbecker** [comment]
@AlicjaSuska I don't think we need a minimum height to be WCAG compliant. See this exception:

> If the spacing of the targets is essential to the information being conveyed, the "Essential" exception applies. For example, in digital maps, the position of pins is analogous to the position of places shown on the map. If there are many pins close together, the offset between pins and neighboring pins will often be below 24 CSS pixels. It is essential to show the pins at the correct map location, therefore the Essential exception applies.

https://w3c.github.io/wcag/understanding/target-size-minimum.html

In a bar chart, the height of the bar is essential to the information being conveyed, changing the height would falsify the information in the same way that moving pins on a map would. (note that this is not true for the _width_ of the bars, which are not essential to the information being conveyed, hence we have a minimum width there).

The best accommodation I think is that the clickable area could be made larger than the actual bar (without changing the visible bar height) and that users can use the expanded UI and click rows in the table.
