### ISSUE TITLE
Jump to file at line if query like "myfile.go:123" uniquely resolves to a file

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#408]
Reported by a user:

As a user I want to be able to quickly jump to a file at a specific line if I type in a query that uniquely identifies a file and include `:$LINE`. For example, in a repo with only one file named `myfile.go`, typing in a query `myfile.go:123` should show me a search suggestion in the menu whose action is "go to file at line" not just "go to file". If I view the search results page for this query, it should show me a search result indicating that when clicked I will jump to the line (right now it would probably show no results because no files contain the literal string `myfile.go:123`).

**Comment by maxhallinan** [comment]
My [branch](https://github.com/maxhallinan/sourcegraph/tree/issue-408-suggestion-search-line-number) supports this feature only for the list of suggestions that appear as the user is typing.
I haven't supported this feature on the search page yet.
Doing so is a bigger change and I wanted to get some feedback first.
Apologies for the length but I don't want to charge ahead without discussing this a bit:

The QueryInput component fetches suggestions but does not do the search itself.
Search is done in QueryInput's parent contexts: SearchPage, ScopePage, SearchNavbarItem, and TreePage. 
Meanwhile, the Search and Suggestions queries do not support the line number syntax: `filename.ext:123`.
To support the line number on the search page, I either need to update each of QueryInput's parent contexts to add the line number as a second url parameter to the search url, or extend the query syntax.

Here are some considerations:

**A. Extend the query syntax to support a line number**
	
pros:

- all logic for parsing the line number and adding the line number to the suggestion url is located in a single place
- all search fields would just work. no need to modify each context.
- the only modification to the frontend is messaging about "filename at line 123". this is an update to two components: SearchResult and QueryInput

cons:

- it seems odd to extend the query syntax because the line number has no semantic value. semantic value for `<file pattern>:123` would be something like "show me suggestions matching this file pattern and containing at least this many lines".
- `:123` could also be a regex pattern, so the query resolver must positively exclude a regex pattern before treating `:123` as a line number. this is a problem on both the frontend and the backend. 
- still requires updating more than one context: the search _and_ the suggestion query resolvers

**B. Pass the line number to the search results page as a second url parameter** 

pros:

- preserves the integrity of the query language and keeps the services free of logic specific to the user interface

cons:

- does not scale very well. every search context must handle the line number correctly
- more state outside of QueryInput
- forces the search page to duplicate some of the url and display logic used in the suggestions list

What do you think? Does this feature have any value if it is limited to the suggestions list? That might be an odd experience for users who are in the habit of hitting enter on the search field.

**Comment by nicksnyder** [comment]
> My [branch](https://github.com/maxhallinan/sourcegraph/tree/issue-408-suggestion-search-line-number) supports this feature only for the list of suggestions that appear as the user is typing. I haven't supported this feature on the search page yet. Doing so is a bigger change and I wanted to get some feedback first. Apologies for the length but I don't want to charge ahead without discussing this a bit.

Great! I would encourage you to open a PR even if it is only "work in progress" because the diff is relevant context here.

> Here are some considerations:

Neither of these sound appealing to me.

I think this would require changes to both the [indexed search codepath](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/textsearch.go#L832:31) and the [non-indexed search codepath](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/textsearch.go#L797:48).

Here is a rough sketch assuming that the query is `textsearch.go:37`(I am not confident this would be the right solution). 
- Remove `:37` suffix as a pre-processing step so you can get the file matches.
- Remove all results with line matches (e.g. in case a file contains the string literal `textsearch.go`)
- The remaining results are file matches that will look like this:
    ![image](https://user-images.githubusercontent.com/754768/52805461-74a9ce80-303b-11e9-82f3-4b6fdcffd8b1.png) because they don't have line matches.
- Insert a synthetic [lineMatch](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/textsearch.go#L109:9) for line 37. Then EITHER:
    1. (Preferred) Fetch the content of the file at that line to populate the preview correctly. No frontend changes required here. It would look something like this (perhaps no highlighting on the line):
        ![screen shot 2019-02-14 at 9 10 22 am](https://user-images.githubusercontent.com/754768/52804199-77ef8b00-3038-11e9-8b12-37eaf584d911.png)
    2. Leave the preview empty and update the frontend code to render this differently (i.e. as a link to a line in a file).
        ![image](https://user-images.githubusercontent.com/754768/52805928-9061a480-303c-11e9-8c98-81ae14728837.png)

> Does this feature have any value if it is limited to the suggestions list?

I suspect the answer is yes, but this is a product question for @sqs .

Open a PR for adding them just to typeahead, but also see if you can make progress on adding them to search results based on my suggestion above.

> That might be an odd experience for users who are in the habit of hitting enter on the search field.

Anyone in the habit of typing "file.go:123" today will be in the habit of seeing no results, so this change wouldn't make anything worse.

**Comment by maxhallinan** [comment]
@nicksnyder thanks for the feedback! I've opened PR #2306  for what I have now and will start work on the second part. 

> Anyone in the habit of typing "file.go:123" today will be in the habit of seeing no results, so this change wouldn't make anything worse.

I found it a little jarring to see that the suggestions list referenced the line number but when I hit enter on the field, the search results page had changed my query from `filename.ext:123` to just `filename.ext`.

**Comment by maxhallinan** [comment]
@nicksnyder, I've opened WIP PR #2333 that follows your suggested approach. Let me know what you think!

**Comment by keegancsmith** [comment]
>     * Remove `:37` suffix as a pre-processing step so you can get the file matches.
>     * Remove all results with line matches (e.g. in case a file contains the string literal `textsearch.go`)

@nicksnyder What happens when my search query is `mydevcompany.io:8080`? It sounds like your proposal would break those searches. One is almost tempted to run the query twice and merge the results:
- `repo:foo bar.go:123`
- `repo:foo file:bar.go`

This way we don't need to touch each search implementation to handle this feature. Additionally we should be quite strict with which queries we apply this transformation to. It should only happen on very simple queries that don't use extra tokens. Or this is a transformation we do to `file:` tokens only.

**Comment by nicksnyder** [comment]
@keegancsmith Good clarification, my proposed solution needs to be additive.

Assume an input of `repo:foo bar.go:123` .
- Return results for exactly that query as we do today (no change) `repo:foo bar.go:123`.
- **In addition to the above results** for queries that look like a file/line combo (e.g. matches `^[a-zA-Z\.]+:[0-9]+$`) implement special logic to yield a line result in a file (i.e. possibly following the implementation I suggested in the previous comment).

**Comment by maxhallinan** [comment]
I've updated #2333 to support the file number only when one `file:` token is used. I could also have [`searchFilesInRepos`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/textsearch.go?suggestion#L675:6) call itself a second time with a modified `args.Pattern.Pattern` when that string matches the pattern and no file token is used. It's not clear to me: 

- what side effects this function has that shouldn't be repeated 
- how to merge the two [`common`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/textsearch.go?suggestion#L865:20) structs produced by calling searchFilesInRepos twice.

**Comment by camdencheek** [comment]
Closing as won't do. A "line" is not currently a searchable API object, and I don't think we have plans to do so. The proposed syntax is also pretty counter to the direction the language is taking.
