### ISSUE TITLE
Search aggregation insights do not allow to trigger explicit aggregation when timeout was hit

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#40861]
In the case of the short 2s timeout being hit, the RFC states it should still be possible to trigger an explicit aggregation by clicking one of the buttons. This should cause the aggregation to re-run without a timeout.

Currently, an error message is shown, ~~the buttons are disabled,~~ and there is no way to override the timeout.

## Frontend change requirements: see [Design](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=2518%3A31642)
- Replace timeout error message with "Run aggregation" CTA that triggers aggregation with extended timeout (and persists this choice across changes to the grouping attributes)
- Adjust loading state to remove "Loading..." text: only show sceleton graphic.

Details on persistence of the choice:
1. If you hit the timeout, you get the "timeout hit" state on _all grouping attributes (aka tabs)_ even when you switch between them, until..
2. If a user clicks the "run without timeout" action on _any tab_ then all tabs should run without timeout. 

### From meeting sync 

(This only applies to the current query, and does not apply to future search queries.)

The only state when it's preserved is thus: 
1. You have hit this button on the same search and are now switching tabs. If the search box changes input, we reset the state. 

## Pings
We also should tracks # of clicks on “run this anyway with a longer timeout”

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by vovakulikov** [comment]
@felixfbecker I see that you're referring to. In RFC we have the following line about it
> Show proactive aggregations (where the search query allows it) using a small timeout to not set the search backend on fire. Always allow to trigger an explicit aggregation (which doesn’t have a timeout).
>- *We need to display a notification on the frontend side to the user if the search wasn’t exhaustive due to a timeout
>- There should be a feature flag that lets an admin entirely disable all proactive insight aggregations (ship default on, but good as a failsafe)

I'm not sure that we have this part `which doesn't have a timeout` in the recent version of RFC. Our GQL API doesn't expose this setting.

UX concern. cc @AlicjaSuska 
> Essentially, when a timeout is hit, the behavior and UI reacts the same as when proactive insights were disabled through the feature flag.

I disagree that this should work in exactly the same way as when proactive aggregation was disabled. With proactive mode you immediately see loading state if we hide chart (with error message) when BE responded with timeout error we will have a layout shift. 


So I think this issue has two parts 
- Support aggregation retriggering without timeout if we've got a timeout error (I'm not sure that this is something that we could do safely here, as I recall any aggregation without timeout could break our BE entirely cc @sourcegraph/code-insights-backend)
- Adjust layout if we've got a timeout error (I have concerns about layout shift  need to validate with @AlicjaSuska)

**Comment by felixfbecker** [comment]
The RFC said "Show **proactive** aggregations using a small timeout" and "Always allow to trigger an explicit aggregation." I added the "(which doesn’t have a timeout)" part yesterday to clarify since that maybe wasn't clear just from the two sentences before, but that's the desired behavior. This is important as an escape hatch when queries do time out (which may happen in _a lot_ of cases, because we're trying to be conservative).

> Support aggregation retriggering without timeout if we've got a timeout error (I'm not sure that this is something that we could do safely here, as I recall any aggregation without timeout could break our BE entirely cc https://github.com/orgs/sourcegraph/teams/code-insights-backend)

My understanding is that the concern is only about _every_ search triggering `count:all` queries as a side effect. You can always manually run a `count:all` search as a user too without a timeout, and compute notebooks also always run `count:all` queries without timeouts (they can sometimes take over a minute to compute), so the user should always be allowed to trigger an explicit aggregation (without the timeout too). The timeout is only to restrict the proactive insights, when they are explicitly triggered there shouldn't be a timeout. Sounds like the backend resolver needs an additional boolean argument on whether the query should use a timeout or not and then the webapp can pass that.

**Comment by Joelkw** [comment]
+1 here, I came here looking for this same issue after playing with the feature. I agree with everything Felix noted about why we're not concerned (because a user can do this many other ways, we just didn't want to _proactively_ do this all the time) and agree that this was in the scope RFC since August 8th, it appears. 

This is a key part of the feature we need to make sure ships, given how many searches may time out. Is there anything needed from me to ensure we can ship this as planned at this point?

**Comment by AlicjaSuska** [comment]
Thank you for bringing this up. I agree with @vovakulikov that we should have a separate state. @felixfbecker if we show only buttons without explaining why chart is not present, it would be confusing. It would look like the feature is inconsistent as it shows aggregations for some queries and does not show for others.

Here is a proposition of this state ([Figma](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=2518%3A31642))

**Comment by vovakulikov** [comment]
From sync with @chwarwick
- We should extend GQL API in order to understand that we get a timeout error and not other types of error. 
- We should extend GQL input type in order to support aggregation without timeout limitations 

From product point of view @AlicjaSuska do you think it would be better if we would have an explicit UI for retrigerring query without timeout? 

![Untitled-2022-08-29-1824](https://user-images.githubusercontent.com/18492575/187237297-e8a97f22-bbcb-4d3d-b233-0558b8b278ad.png)

QQ: Do we need to store this information about running query without timeout in the URL? In case if I run query, hit timeout, then click run without timeout, get my agggregation, what should happen if I change the query or aggregation type, should we preserve run without limitation setting? Should we preserve it if I share my aggregation by URL with someone else? 
cc @AlicjaSuska @Joelkw

**Comment by chwarwick** [comment]
> compute notebooks also always run `count:all` queries without timeouts (they can sometimes take over a minute to compute)

@felixfbecker  There is a 1 min timeout in compute.  
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/compute/streaming/stream.go?L22-25

I'm not opposed to offering up an increased timeout for the case when a user directly attempts a retry but I do not think we should make it unlimited.

**Comment by Joelkw** [comment]
Proposed UX: 
1. If you hit the timeout, you get this "timeout hit"message gate on _all tabs_ even when you switch between them, until..
2. If a user hits the "run without timeout" on _any tab_ then all tabs should run without timeout. 

From meeting sync

**Comment by unclejustin** [comment]
Do we want to capture pings for these as well?

- proactive limit hit
- explicit limit hit
- explicit limit success
- how long to get successful result

@Joelkw  👀

**Comment by Joelkw** [comment]
@unclejustin good call. I will make a separate stretch pings issue for that.

**Comment by felixfbecker** [comment]
@sourcegraph/code-insights-backend  I extracted backend issue for this: https://github.com/sourcegraph/sourcegraph/issues/41010
We can treat this issue as the frontend issue.

**Comment by vovakulikov** [comment]
@AlicjaSuska curios about your thoughts on this https://github.com/sourcegraph/sourcegraph/issues/40861#issuecomment-1230572209

>(This only applies to the current query, and does not apply to future search queries.)
The only state when it's preserved is thus:
You have hit this button on the same search and are now switching tabs. If the search box changes input, we reset the state.

I kind of against this because in this logic there is a case when we can't say are we in no-timout mode or we still have timeout limitation. As @unclejustin noted this could lead to some problems with understand what happening at the moment. Why does my query run so long? Is it because I turned off timeout limitation and I should wait or something went wrong on the backend or with my network and should just leave the page? 

I think we should make this timeout/no-timeout state explicit somehow. Or we should don't preserve this not timeout at all and any aggregation type change or query change will reset this setting completely.

**Comment by Joelkw** [comment]
@vovakulikov @unclejustin @AlicjaSuska please see my comment and proposal on the figma for this error message (you can decide if you want to create a separate issue or continue to use this one): https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=1908:20472#255201807

**Comment by unclejustin** [comment]
@Joelkw I like this better than what we had proposed.

@AlicjaSuska It's not a big deal to one way or the other, but I'm going to proceed with Joel's idea unless you tell me different.

What I don't have is any design for this "Run aggregation" button. I'm going to assume the same style as the above buttons centered on the skeleton like the old text was until you tell/show me different.

**Comment by AlicjaSuska** [comment]
Thank you for those suggestions. I've replied in this [Figma thread ](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=2653:30074#255201807)and prepared the designs @unclejustin
