### ISSUE TITLE
Unexpected aggregation insights state when there are no search results

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#40871]
<img width="1607" alt="screenshot" src="https://user-images.githubusercontent.com/10532611/186768615-fbb01411-f6e3-4b81-8ac7-50e5a1f9449b.png">

@AlicjaSuska I think the design didn't account for this state. 

I think we should probably be consistent with the repo filter suggestions and hide the entire section, so the user's attention is focused on the educational content and suggestions that actually work in this context (the ones still shown in the sidebar).

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by AlicjaSuska** [comment]
Thank you for bringing this up @felixfbecker. I agree; let's close the section in this case.

**Comment by chwarwick** [comment]
@vovakulikov  Not that it solves all cases but we can make some adjustments to the default selection and availability.  It appears a search pattern is required to be able to aggregate by `File`

**Comment by vovakulikov** [comment]
From sync with Chris
- With selecting repo we at the moment to file aggregation mode. Which doesn't produce any aggregtion and we have empty aggregation datasets. But (we have search matches, one repo on the screenshot above)
- This breaks suggested logic from @felixfbecker where we hide aggregation section in case if we have no data for aggregation. 

## Action items
- We should improve default aggregation mode calculation on the backend (in case if we have repo filter and don't have any search patter in the query we should pick aggregation mode repo not file)
- We still can't disable aggregation mode File for queries what don't have search patters (because we're not sure we will catch everything/all cases with this check and it might be false positive for some queries) 
- This give us 
  - We need to introduce zero state for the chart (@AlicjaSuska) for cases like you can see on the screenshot above
  - It's still make sense to hide this panel completely if we don't have any search (so Felix suggestion is correct but not for all cases, this is why we should have loading state)
  
cc @felixfbecker

**Comment by unclejustin** [comment]
@vovakulikov to clarify: This issue is still valid. We will collapse the panel if the search has no results. It just doesn't solve every case. Is that right?

**Comment by AlicjaSuska** [comment]
[Design](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=2812%3A32866) for zero state for the chart (simple: 'no data to display' message is enough in this case in my opinion) + closing the section as Felix proposed.
