### ISSUE TITLE
insights: Overflow of errors in aggregations UI

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#40940]
Try running the query : `after:"last mont"`

<img width="791" alt="image" src="https://user-images.githubusercontent.com/7999356/186941376-3b01878a-d176-4c00-9204-677ff46ac9a8.png">

It looks like the backend is returning an array of errors. I'm not sure at the moment how to repro that locally, because for me it's just returning one `SearchAggregationNotAvailable`. In any case, do we maybe only want to display the first error to prevent this? 

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by felixfbecker** [comment]
I think there are two issues here:
1. The frontend should have an `overflow` handling in place so that no overly long error message can break the UI like this. Could just be using `text-overflow: ellipsis`.

2. The backend seems to be returning the same error multiple times for each field that was requested, when it seems like the error should be returned just once, one level higher, for the parent field:
```json
{
  "errors": [
    {
      "message": "ParseQuery: query.Pipeline: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 0, "available"]
    },
    {
      "message": "ParseQuery: query.Pipeline: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 1, "available"]
    },
    {
      "message": "ParseQuery: query.Pipeline: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 2, "reasonUnavailable"]
    },
    {
      "message": "pattern parsing: failed to parse search query: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 3, "available"]
    },
    {
      "message": "ParseQuery: query.Pipeline: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 2, "available"]
    },
    {
      "message": "pattern parsing: failed to parse search query: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 3, "reasonUnavailable"]
    },
    {
      "message": "Invalid value .\nExpected type SearchAggregationMode, found .",
      "path": ["searchQueryAggregate", "aggregations", "mode"]
    },
    {
      "message": "ParseQuery: query.Pipeline: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 1, "reasonUnavailable"]
    },
    {
      "message": "ParseQuery: query.Pipeline: invalid date format",
      "path": ["searchQueryAggregate", "modeAvailability", 0, "reasonUnavailable"]
    }
  ],
  "data": { "searchQueryAggregate": null }
}
```

If the query failed to parse, I wouldn't expect each individual "mode availability" and their fields to individually fail, but rather only the `searchQueryAggregate` field.

Is there a reason all those subfields should be nullable?
