### ISSUE TITLE
No searcher endpoints error when using `index:no` on k8s.sgdev

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#4101]
- **Sourcegraph version:** k8s.sgdev.org

#### Steps to reproduce:

1. Search for `(hunk|repository)resolver index:no` on k8s.sgdev.org
2. See that it errors out with `1 error occurred: * text search failed: failed to search gitolite.sgdev.org/13k/mpociot/vat-calculator@: No searcher endpoints` (the repo in the error message changes on retries) 

#### Expected behavior:

Search works. 

#### Actual behavior:
"No searcher endpoints" error with a different repo name each time.

**Comment by slimsag** [comment]
So I observed this on k8s.sgdev.org before a few weeks ago and _for some reason_ restarting pods fixed it. This leads me to believe it is most likely an ephemeral error with detecting searcher endpoints. Nothing around this endpoint code has changed recently so it is very unlikely this is a regression but it is a major issue and makes sense that we require fixing before 3.4-c.

Since we do not override `SEARCHER_URL` on k8s.sgdev.org, we end up using [the default `k8s+http://searcher:3181`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@08e2d340df801edf3b2069477d8e92aa19e3f973/-/blob/cmd/frontend/graphqlbackend/search2.go#L380:1). This is [put into an endpoint map here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@08e2d340df801edf3b2069477d8e92aa19e3f973/-/blob/cmd/frontend/graphqlbackend/search2.go#L405), and the error comes from [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@08e2d34/-/blob/pkg/endpoint/endpoint.go#L176:30).

All of this implies that under certain circumstances our use of the k8s API to resolve searchers fails, i.e. the bug is here somewhere: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@08e2d34/-/blob/pkg/endpoint/endpoint.go#L142-158

My most likely guess is that:

1. Inspecting the logs (of frontend I believe) would tell us the error: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@08e2d34/-/blob/pkg/endpoint/endpoint.go#L82
2. Most likely the error would tell us that this occurs when some pods don't start quick enough, e.g. maybe `searcher` takes a long time to start and thus it errors out.

---

3. A separate but also important issue here is that we don't self-correct this problem for some reason. i.e. the problem is ephemeral but instead of the endpoint logic correctly retrying we appear to become stuck on something where only a pod restart fixes the issue. This implies our watching logic isn't working correctly: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@08e2d34/-/blob/pkg/endpoint/endpoint.go#L150-153

I have some theoretical plans to build out something that monitors inter-service connection statuses and provides prometheus metrics we can alert on to tell us when something like the above happens, but it may be a while before I get around to it and fixing #3 above is valuable anyway.

**Comment by ggilmore** [comment]
In https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/140, I added a `SEARCHER_URL` env var. This bypasses the endpoint watching logic that @slimsag mentioned. After that changes was deployed, I am now consistently seeing the following error:

![Screen Shot 2019-05-17 at 4 37 14 PM](https://user-images.githubusercontent.com/9022011/57961185-156d8b80-78c2-11e9-8d4c-dc5a078f7427.png)

This seems to be the same issue as https://github.com/sourcegraph/sourcegraph/issues/3799. 

I wonder if https://github.com/sourcegraph/sourcegraph/issues/3799 is the underlying cause for this issue, and the "No searcher endpoints" error is just a bad error message?

**Comment by slimsag** [comment]
What you are seeing seems to imply that the frontend can't communicate with searcher over the network. This explains why the Kubernetes service discovery doesn't work.

**Comment by slimsag** [comment]
Stating what I said above but more clearly: This issue and #3799 may have the same underlying cause (network failure in some way, it is unclear how)

**Comment by ijt** [comment]
@ggilmore, I'm still seeing the invalid tar header issue after you reverted that change:

<img width="811" alt="Screen Shot 2019-05-20 at 16 20 24" src="https://user-images.githubusercontent.com/15530/58057973-f5d19f80-7b1b-11e9-8cfe-59ad1aef40bb.png">

**Comment by ijt** [comment]
I'm getting this same error with `index:yes` and without any setting for `index:`.

**Comment by ijt** [comment]
@slimsag, your guess is right: I'm seeing "failed to watch kubernetes endpoint" errors in the logs for k8s.sgdev.org:

![Screen Shot 2019-05-21 at 19 13 36](https://user-images.githubusercontent.com/15530/58142638-cf376580-7bfc-11e9-8de9-1640134f91a0.png)

**Comment by ijt** [comment]
Right after seeing the "No searcher endpoints" error I ran `kubectl get pods` and it showed that there is a searcher running:

![Screen Shot 2019-05-21 at 20 55 36](https://user-images.githubusercontent.com/15530/58146405-cfd6f880-7c0a-11e9-98be-5d54e8a053a7.png)

**Comment by keegancsmith** [comment]
Yeah the error message needs to be better here. Its possible that the service account for frontend doesn't have permission to do a watch or get on endpoints. We do explicitly list it here https://sourcegraph.sgdev.org/sourcegraph/deploy-sourcegraph@e240e032baba4230f7a68fdedaabacdf75317297/-/blob/base/frontend/sourcegraph-frontend.Role.yaml

I double checked that pulumi properly applied this:

<details>

```shellsession
$ kubectl describe deploy/sourcegraph-frontend | grep -i account
  Service Account:  sourcegraph-frontend
$ kubectl describe sa/sourcegraph-frontend
Name:                sourcegraph-frontend
Namespace:           default
Labels:              app.kubernetes.io/managed-by=pulumi
                     category=rbac
                     deploy=sourcegraph
Annotations:         kubectl.kubernetes.io/last-applied-configuration:
                       {"apiVersion":"v1","imagePullSecrets":[{"name":"docker-registry"}],"kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"categor...
Image pull secrets:  docker-registry (not found)
Mountable secrets:   sourcegraph-frontend-token-f5jzl
Tokens:              sourcegraph-frontend-token-f5jzl
Events:              <none>
$ kubectl describe rolebindings/sourcegraph-frontend
Name:         sourcegraph-frontend
Labels:       app.kubernetes.io/managed-by=pulumi
              category=rbac
              deploy=sourcegraph
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"category":"rbac","deploy":"sourc...
Role:
  Kind:  Role
  Name:  sourcegraph-frontend
Subjects:
  Kind            Name                  Namespace
  ----            ----                  ---------
  ServiceAccount  sourcegraph-frontend
$ kubectl describe role/sourcegraph-frontend
Name:         sourcegraph-frontend
Labels:       app.kubernetes.io/managed-by=pulumi
              category=rbac
              deploy=sourcegraph
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"category":"rbac","deploy":"sourcegraph"...
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
  endpoints  []                 []              [get list watch]
```

</details>

So I would suspect one of two things:

1. Kubernetes changed a bit and this is a newer version of k8s than production.
2. It works sometimes, but our endpoints code isn't robust to a new failure case.

**Comment by ggilmore** [comment]
@keegancsmith 

Both dogfood-full-k8s and dot-com are using Kubernetes 1.11.8-gke.6

**Comment by ijt** [comment]
I think this has something to do with the set of repositories currently up on `k8s.sgdev.org`. There are about 18k repos, including 84 copies of `sourcegraph/sourcegraph`: https://k8s.sgdev.org/site-admin/repositories. I believe the sheer number of repos involved is overwhelming the searchers because the backend issues 18k simultaneous requests against them. My guess is that the searchers are becoming unresponsive after a few thousand simultaneous requests and then kubernetes notices they aren't responding, i.e. there are effectively no searcher endpoints, hence the error reported above.

As evidence, if we add a `repo:` filter to the query above then it works consistently: https://k8s.sgdev.org/search?q=repo:%5E35%5C.247%5C.108%5C.89/repos/1/github%5C.com/sourcegraph/sourcegraph/%5C.git%24+%28hunk%7Crepository%29resolver++index:no. 

![Screen Shot 2019-05-22 at 13 40 08](https://user-images.githubusercontent.com/15530/58207242-29850480-7c97-11e9-9ca5-ae952f264ce1.png)

My guess would also explain why we haven't observed any searcher restarts in `kubectl get pods`. They just become temporarily unavailable when under so much load.

Assuming this is true, I propose the following actions:
1. No longer block the release on this issue since it isn't a regression and can probably be mitigated by adding more searchers.
2. Implement (quasi-)streaming #3991. The variant I've been discussing with @slimsag would bring the load on the searchers down to a consistently manageable level regardless of the number of repositories.

**Comment by ijt** [comment]
@ggilmore and I just verified the mitigation describe as action item 1 in my previous comment, by increasing the number of searcher replicas from 1 to 5 on `k8s.sgdev.org`. It works:

![Screen Shot 2019-05-22 at 14 04 22](https://user-images.githubusercontent.com/15530/58208943-c72e0300-7c9a-11e9-8141-6828106e4822.png)

**Comment by slimsag** [comment]
me and @ijt chatted on Slack about this a bit,

it seems one immediate thing we could do to mitigate this issue in 3.4 which goes out to customers is clarify those error messages to indicate that their searcher deployment may be underpowered and suggest the admin may need to scale it out.

**Comment by keegancsmith** [comment]
Could we also limit the number of concurrent searches we issue? That should have lots of positive effects.

**Comment by slimsag** [comment]
Great minds think alike :) I came here to say:

Why do we send so many requests to searcher that we can effectively make it appear down from a network perspective anyway? We should limit our requests before that is ever the case.

This would be important even if searcher load is less (e.g. via @ijt's incremental search proposal above) because searchers can always be underpowered or overloaded with lots of concurrent requests from multiple users, etc.

**Comment by ijt** [comment]
> Why do we send so many requests to searcher that we can effectively make it appear down from a network perspective anyway? We should limit our requests before that is ever the case.

Do you have an idea about how to do that?

**Comment by keegancsmith** [comment]
We actually had a global limit which was hardcoded. However, it clearly wasn't that effective. I just sent https://github.com/sourcegraph/sourcegraph/pull/4198 which is an attempt limiting search requests in a more effective way.

**Comment by slimsag** [comment]
I've cherry-pick'd this onto 3.4 just now.
