### ISSUE TITLE
JetBrains: Plugin crashes on viewing file history for perforce project 

### ISSUE THREAD

**Issue by rakeshjosh2003** [sourcegraph/sourcegraph#41031]
- **Sourcegraph version:** 
- **Platform information:** Ubuntu 20.04.4 LTS and macOS
IntelliJ 2021.3.3
Sourcegraph IntelliJ plugin 2.0.0
Chrome 104.0.5112.101 (64-bit)
Intel CPU

#### Steps to reproduce:

1.Open intellij plugin and try to view file history for a perforce project.
2.Extension crashes on this operation and creates attached logs.

#### Expected behavior:
Extension should not crash and user should be able to view file history.

#### Actual behavior:
IntelliJ plugin crashes on viewing file history for perforce project 

[PerforceHistoryButton.log](https://github.com/sourcegraph/sourcegraph/files/9448470/PerforceHistoryButton.log)
If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @muratsu @jjinnii @ryankscott

**Comment by rakeshjosh2003** [comment]
![image](https://user-images.githubusercontent.com/102702631/187377963-72bc6ae4-ad0b-4aa3-86a8-ae8baae74aef.png)
![image (1)](https://user-images.githubusercontent.com/102702631/187377988-f1566587-9fa4-482e-aeee-bacdd56c2a38.png)

**Comment by vdavid** [comment]
It looks like the problem here is that we're using the “git” CLI command internally, which, of course, doesn't make sense for a Perforce repo.

JetBrains products have built-in VCS functionality, and I've looked into the possibility of tapping into this rather than relying on the git CLI command. It's not very well documented but seems possible.
I think it'd solve this problem, and also this other issue we're having with another customer: https://github.com/sourcegraph/sourcegraph/issues/40452
