### ISSUE TITLE
setRepositoryEnabled codepath still in frontend codebase

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4113]
It is highly unlikely for the code path to be executed (likely a bug if there are no services for a given repository), however the code path is still part of the UI. What was the decision behind keeping this here (if any)? Should it be cleaned up?

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@690c5101d68b26985d95c82d8e51fda09d3cb5c9/-/blob/web/src/repo/settings/RepoSettingsOptionsPage.tsx?utm_source=share#L120

**Comment by slimsag** [comment]
I adjusted the title slightly to clarify we're talking about the frontend codebase here. This is an important distinction because there are two parts here:

1. The frontend support for repository enablement -- this should totally be removed, nobody is using it.
1. The (deprecated) backend / GraphQL API support for `setRepositoryEnablement` -- this should be removed in the next major release but ideally not in this release / before then (https://app.hubspot.com/contacts/2762526/company/407948923 was relying on this and while they are not technically using it anymore, it is nice to have the option of falling back to this if something goes wrong with the new setup I gave them which replaces their use of this for another week or two).

**Comment by keegancsmith** [comment]
This was an oversight when I was cleaning up the frontend. That codepath will never execute since the number of external services is guaranteed to be > 0 now. So this will never show up for users. I will remove it.

And yes, all disable/enable endpoints are now no-ops. We still support the setRepositoryEnablement due to a customer, but indeed we will remove that as well.
