### ISSUE TITLE
explicit permissions API doesn't seem to behave correctly

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#41142]
We encountered an issue when trying to set up the explicit permissions API that we initially thought was leaking search results. After more testing we found that in fact search is behaving correctly (and properly filters permissions), but somehow explicit repo permissions are not behaving right.

Here is what I did:

Start a fresh Sourcegraph instance
Install 2 repos (sourcegraph/sourcegraph and sourcegraph/handbook)
[Enable permissions](https://docs.sourcegraph.com/admin/repo/permissions#explicit-permissions-api)
Use the graphql mutation `setRepositoryPermissionsForUsers` to remove all bindings for `sourcegraph/handbook`
Create a new user without admin and execute searches

What we found was the user could see private repos `sourcegraph/handbook`

We did see a note that maybe these repos were not re-syncing after enabling permissions, so I tried to add a new private repository that was created after the above. This repository _was_ correctly filtered out. Using the GraphQL API to check for permissions yields this:

``` graphql
query {
  authorizedUserRepositories(email: "supersecret@secret.com", first: 100, perm:READ) {
    nodes {
      name
      permissionsInfo {
        permissions
      }
    }
    totalCount
  }
}
```

``` json
{
  "data": {
    "authorizedUserRepositories": {
      "nodes": [
        {
          "name": "github.com/sourcegraph/sourcegraph",
          "permissionsInfo": {
            "permissions": [
              "READ"
            ]
          }
        },
        {
          "name": "github.com/sourcegraph/handbook",
          "permissionsInfo": null
        },
        {
          "name": "github.com/coury-clark/testing-repo-permissions",
          "permissionsInfo": null
        }
      ],
      "totalCount": 0
    }
  }
}
```

The repo that **is correctly filtered** is `github.com/coury-clark/testing-repo-permissions`, but appears to have the same configuration as `github.com/sourcegraph/handbook` which is **not** correctly filtered in search results.

``` graphql
query search {
  search(query:".* patternType:regex count:all select:repo") {
    results {
      ... on SearchResults {
        results {
          ... on Repository {
            name
          }
          ... on FileMatch {
            file {
              path
            }
          }
        }
      }
    }
  }
}
```

``` json
{
  "data": {
    "search": {
      "results": {
        "results": [
          {
            "name": "github.com/sourcegraph/handbook"
          },
          {
            "name": "github.com/sourcegraph/sourcegraph"
          }
        ]
      }
    }
  }
}
```

/cc @sourcegraph/iam

**Comment by unknwon** [comment]
Hey, so far it is unclear whether the instance entirely relies on background permissions syncing or explicit permissions, it is notable that these options are currently mutually exclusive and you [can't enable them both at the same time](https://github.com/sourcegraph/sourcegraph/blob/91e8afb800e58d72fda4e6ac12f471dc57480608/internal/database/repos_perm.go#L24-L25).

If you try, the following error would be showing almost everywhere, and _any_ access to _all_ repositories are blocked for non-site admins.

<img width="1021" alt="CleanShot 2022-09-01 at 11 23 56@2x" src="https://user-images.githubusercontent.com/2946214/187825198-8a26bcaa-c9cd-4bc1-a1b4-9b471be4b6ed.png">
<img width="1194" alt="CleanShot 2022-09-01 at 11 24 03@2x" src="https://user-images.githubusercontent.com/2946214/187825210-20fd2815-d6e8-4e99-ab5d-ccba74f3b57f.png">

When using explicit permissions, every access needs to be explicitly granted (does not care about if the repo is public or private on the code hosts). On the other hand, if you're actually using background permissions syncing, [public repos on the code hosts are always skipped for repo permissions checking](https://github.com/sourcegraph/sourcegraph/blob/91e8afb800e58d72fda4e6ac12f471dc57480608/internal/database/repos_perm.go#L77). In the example repos you give, 
"github.com/coury-clark/testing-repo-permissions" is clearly a private repo, and "github.com/sourcegraph/handbook" is in fact a public repo on GitHub.com.

I did a test on executing the `setRepositoryPermissionsForUsers` mutation, my hypothesis so far is that the confusion might come from this mutation doesn't throw an error when the instance is using the background permissions syncing and does actually clears out permissions bit for the repository at the time of mutation execution, but because background permissions syncing is in use and "github.com/sourcegraph/handbook" is a public repo, the result of this mutation means a noop to our authz mechanism.

Happy to hop on a call to debug your test setup!

**Comment by ryphil** [comment]
@coury-clark - Cleaning up the IAM backlog. Does Joe's response solve your question? We have the work required to introduce permissions systems in parallel tentatively planned for Q4 as part of strategic support.

**Comment by coury-clark** [comment]
@ryphil Thanks for the ping. I haven't had a chance to go back and look at this, and from reading Joe's response I'm fairly sure we just were misunderstanding how permissions work in general. I don't think there is any problem here.
