### ISSUE TITLE
insights: Vertically squished chart for some queries

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#41158]
I'm not sure what it is about [this query](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+query%28.*%29string+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+&patternType=regexp&groupBy=CAPTURE_GROUP) or these results, but I'm seeing a squished chart here:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/7999356/187798586-90a4d97f-da3b-45e8-bad5-b937273c90a2.png">

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by leonore** [comment]
following on from slack, this is caused because of different whitespace results, e.g. ` ` and `\t` and `  `
![image](https://user-images.githubusercontent.com/29406849/187895105-8a56bf4f-e4d3-451b-a2f9-5c8648214425.png)
something in the chart codebase is unhappy with that and causing this squish.

when drilling down into that query we can see the whitespaces are written into the query accurately: e.g. [single space](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%2Fquery%28%3F%3A+%29string%2F&patternType=regexp&groupBy=CAPTURE_GROUP&groupByUI=sidebar), [multiple space](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%2Fquery%28%3F%3A+++++++%29string%2F&patternType=regexp&groupBy=CAPTURE_GROUP&groupByUI=sidebar)

**Comment by leonore** [comment]
I had a search / hack around this for potential workarounds on the backend:

* we can’t wrap whitespace results in ’ ’ or any other character and then strip it when someone clicks into the drilldown because the match could be, actually `’ ’` e.g. https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+-d%28.*%29%2B%5Cs-f2+file%3Acodecov.sh&patternType=regexp&groupBy=CAPTURE_GROUP&groupByUI=sidebar 
* we can't do any other modification (e.g. map `\t` to `\\t`) because of the above
* so unless I’ve thought about this incorrectly our options are:
1. we collect all whitespace only strings together (backend)
2. we figure out why the chart is behaving this way (webapp)

considering time and the load on the frontend team at the moment I’d go for 1) as an acceptable current solution (at least for 4.0) (we would lose differentiated whitespace aggregations but can document it as a limitation) and keep an issue open for 2) to figure out why the chart behaves this way for multiple (different) whitespace 

cc @vovakulikov @CristinaBirkel what do you think?

**Comment by Joelkw** [comment]
sync notes: 
1. Goal state is just "not squish the graph" (ideal long term, frontend shows you \t or \n, but that's out of scope for now. should live on the client) 
2. Filter out whitespace characters from the key? Remove all labels that are whitespace only? Worth a quick check to see if this is that simple. Replace tabs and newline with a space? 

Feels like a frontend problem - @chwarwick  will attempt on the frontend.
