### ISSUE TITLE
insights: Allow for more than 65,000 restricted repositories

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#41157]
If a user does not have permissions to more than 65,000 repositories we cannot currently fetch an all-repos insight for them. At the very least, postgres can only take ~65k parameters. This issue is to make the current permissions work with this scale.

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by felixfbecker** [comment]
Can Postgres take 1 query parameter with an array of over >65k elements? Or does the 65k limit apply to array lengths too?

Basically the difference between querying `WHERE repo NOT IN ($1, $2, $3)` and `WHERE repo != ANY($1)` with `$1` being an array of the repo names the user doesn't have access to.

**Comment by Joelkw** [comment]
sync notes: 
- at the minimum, if we go down the context path, we need to change to not fetch all repos
- options from not complicated to complicated

**Comment by Joelkw** [comment]
notes from sync: 
* can't assume a new branch solves the problem, so solve independently

**Comment by Joelkw** [comment]
notes from sync: 
- we can fix this for just the single-repo / static list case easily
- but we still need to fix it for the larger general case to unblock RFC 741 
- for dynamic lists, we still have to figure out what happens
- if we enable this for just 10-12 repo lists at large customers, that feature may already work with what we have today, doing this is worth it  
- this issue is backend work that just unblocks a part of what we have
