### ISSUE TITLE
IDE Extensions: Support proxies

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#41181]
We have a customer who would like to access Sourcegraph from their IDE extensions via a proxy.
At the moment we have no support for proxies in our VS Code extension and JetBrains plugin.
It’s likely that this will occur more frequently as we talk to other larger organizations that have greater security requirements.

### VS Code extension

from @philipp-spiess

- Implement the proxy support in the process that has access to node APIs (which is outside of the web views IIRC). [This is](https://github.com/microsoft/vscode/tree/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/request/node) how VS Code does it.
- Change our web views so that fetch requests are forwarded to the node thread (if they aren’t already) and use this config.
- Take a look at the streaming APIs. They don’t use fetch at the moment but a different network strategy. It may or may not be possible to hijack packages there and send them to the other thread, but maybe we can rewrite the streaming layer to use fetch instead.

Initial discussion with customer [here](https://sourcegraph.slack.com/archives/C03DTEBNUHF/p1662053628954199)

### JetBrains plugin

by @vdavid 

I guess we could do what VS Code [does](https://github.com/microsoft/vscode/tree/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/request/node), it should work.

**Comment by philipp-spiess** [comment]
I've spent the majority of yesterday looking into this issue for VS Code to understand the current state of things, different proxy settings, and how we could support them. 

## Cross-platform solution?

I want to start by saying that this work is unfortunately not generizeable: The VS Code extension uses electron under the hood. We have different run environments but the one that is allowed to make http request is inside a Node.js runtime. So to make proxies work, we have to work with the fundamentals that the Node.js runtime gives us. Specifically we use `node-fetch` to get a `fetch()` like API available in the Node.js runtime and have compatibility with web-extension bundles which needs to run in a web worker thread. Our JetBrains extensions does not have a Node.js runtime so we need a different approach.

## Types of proxy servers

Generally speaking I found these different options to configure proxies:

- HTTP/HTTPS forward servers 
- SOCKS v4/v5 servers (forward all ports)
- PAC configs - A config syntax to make it easier to configure http/https proxies for specific URLs
- HTTP/HTTPS forward servers exposed via a unix domain socket. _This seems to be a very rare setup that one of our potential customers has chosen_.

## Status quo

This may be unexpected but simple HTTP/HTTPS proxies _already work with extensions_. VS Code patches the runtime of extensions to provide a [custom agent implementation](https://github.com/microsoft/vscode-proxy-agent) which by default, is enabled:

![Screenshot 2022-10-12 at 11 57 39](https://user-images.githubusercontent.com/458591/195312745-91632dfe-185c-43fb-9384-a12121eb85bd.png)

These setting only works with the `http.proxy` config in VS Code which is considered [legacy](https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support) and only supports http/https proxies.

## How to set up a proxy server for testing

I recommend [Proxyman](https://proxyman.io/) as it's a straight forward macOS app. I have changed some settings so that it does not attempt to automatically re-route all requests via proxyman since we want it for the stand-alone http/https proxy feature:

![Screenshot 2022-10-12 at 12 08 41](https://user-images.githubusercontent.com/458591/195315605-de3431f1-4607-4fd3-880c-c3941c35c1ed.png)

For testing an http/https proxy exposed via a unix domain socket, you can check out https://github.com/KnicKnic/domain-socket-proxy (make a custom build via go for mac) and use this to start the domain socket:

```
./domain-socket-proxy.com forward --address 192.168.0.220:9090 --path ./unix.sock
``` 

To test the setup, you can use curl:

```
curl --unix-socket ./unix.sock http://google.com
```

Proxyman should show the connection to Google.com.

## How are proxy servers implemented in VS Code extensions

VS Code extensions have two type of JavaScript runtimes: Web views and background threads. Network requests can only be made from background threads as far as I understand. A background thread has access to the Node.js runtime and as such all http/https network requests go through the `http`/`https` packages.

There exist numerous npm packages that add proxy support (most of them generically for electron) by either monkey-patching these http/https module (VS Code default route) or by providing an _agent_ which is an object that can be passed through Node.js primitives to reroute the network request. 

A very popular library is [`https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent)` which is also used in the bigger bundle of [`node-proxy-agent`](https://github.com/TooTallNate/node-proxy-agent#proxy-agent) which adds support for _most_ proxy setups. 

You can try it out locally very easily via a simple .js file running in Node.js:

```js
const HttpsProxyAgent = require('https-proxy-agent')
const fetch = require('node-fetch')

const agent = new HttpsProxyAgent({
  protocol: 'http',
  host: '192.168.0.220',
  port: '9090',
})

fetch('https://sourcegraph.com', { agent })
  .then(r => r.text())
  .then(console.log)
  .catch(console.error)
``` 

The `node-fetch` library allows the forwarding of an `agent` to the the respective Node.js fundamental APIs

## The Sourcegraph extension

Our VS Code extension makes relevant requests at two points:

- Our GraphQL API is using `fetch` via `node-fetch`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/vscode/src/backend/requestGraphQl.ts?L44-51
- The [`aggregateStreamingSearch` API](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/vscode/src/backend/streamSearch.ts?L67-70) uses the deprecated `EventSource` API which we [have a polyfill for](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/polyfills/vendor/eventSource.js?L174). The polyfill also uses `http` and `https` under the hood so we can theoretically forward an `agent` (or rewrite the streaming API to use the `fetch()` stream capabilities).

## Supporting unix domain http/https sockets

Now, with all that we have learned, I believe it is possible for us to support unix domain sockets. First, here is a PoC that rewrites our two request points (as enumerated above) to use a regular https proxy agent: 

https://github.com/sourcegraph/sourcegraph/pull/42802

![Screenshot 2022-10-12 at 15 55 51](https://user-images.githubusercontent.com/458591/195362286-119e2919-3cd3-4e5c-9a7f-f30f6ec18624.png)

_Note: In order to make this work, make sure to change the extension proxy support to disabled to avoid VS Code monkeypatching the network APIs_

![Screenshot 2022-10-12 at 15 57 29](https://user-images.githubusercontent.com/458591/195362705-c0449823-3ac7-42e9-9cde-9b26cf44d60b.png)

Lucky for us, [`https-proxy-agent`](https://github.com/TooTallNate/node-https-proxy-agent/blob/master/src/agent.ts#L36-L46) simply passes through options to the underlying `net` and `tls` APIs and Node.js [does support connecting to a unix domain socket (see IPC path)](https://nodejs.org/api/net.html#socketconnectoptions-connectlistener).

This means we can configure the proxy to use set the `path` like this:

```js
    const agent = new HttpsProxyAgent({
        protocol: 'http',
        path: '/Users/philipp/dev/domain-socket-proxy/unix.socket',
    })
```

## Further resources

- https://github.com/node-fetch/node-fetch/issues/336
- https://github.com/node-fetch/node-fetch#custom-agent
- https://github.com/TooTallNate/node-https-proxy-agent
- https://github.com/TooTallNate/node-proxy-agent#proxy-agent
- https://www.scrapingbee.com/blog/proxy-node-fetch/
-

**Comment by vdavid** [comment]
Some more docs, and next actions: 

Setting up the environment:

- Download [Proxyman](https://proxyman.io/), install and run it. The optional stuff that needs root permissions is not needed. Also, the free version is fine.
- Clone [domain-socket-proxy](https://github.com/KnicKnic/domain-socket-proxy). Run:
  - `go mod init sourcegraph.com/domain-socket-proxy/v2`
  - `go mod tidy`
  - `go build`
  - `./domain-socket-proxy forward --address {local-ip}:9090 --path ./unix.sock` where `{local-ip}` is your IP on your local network
- Test your setup with `curl --unix-socket ./unix.sock http://google.com`. The request should get a response, and it should show up in Postman.

Next actions:
- [ ] Read settings from config [here](https://github.com/sourcegraph/sourcegraph/pull/42802#discussion_r994361508) – config is [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/vscode/package.json?L106%3A22=)
- [ ] Remove [this](https://github.com/sourcegraph/sourcegraph/pull/42802#discussion_r994361944) once the bug on `main` is fixed
- [ ] Parse the URL, use the http/https version of package dynamically, [here](https://github.com/sourcegraph/sourcegraph/pull/42802#discussion_r994367407)
- [ ] Don't bundle the proxy agent into the browser version—[here](https://github.com/sourcegraph/sourcegraph/pull/42802#discussion_r994371859)
