### ISSUE TITLE
insights: aggregation feature - capture group replacement produces incorrect results with multiple groups in query

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#41274]
Given a query such as `repo:/sourcegraph$ log\.Scoped\((".*"), (".*")\)` produces aggregation results from group number 1 such as `"tracer"`. Clicking on this should replace group number 1 with that literal value, preserving the rest of the regexp. That doesn't seem to be the case, and its seems _all_ groups are being replaced. 

Instead, I get the following:
`repo:/sourcegraph$ /(?:log\.Scoped\((?:"tracer"),).*?(?:(".*")\))/`

In this, it seems a few things are happening:
1. The entire regexp is wrapped in a group (shouldn't happen)
2. The second capture group is converted into a non-capturing group (shouldn't happen)
3. There are unexpected inserts into the regexp (probably because of 1. above)

https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%2Fsourcegraph%24+log%5C.Scoped%5C%28%28%22.*%22%29%2C+%28%22.*%22%29%5C%29&patternType=regexp&groupBy=group&expanded=

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
It seems this is originating from the parser somewhere / for some reason. By the time our replacement code visits the pattern, the pattern has already been manipulated to convert _all_ groups to non-capturing groups (including the overall expression). https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/querybuilder/regexp.go?L167

**Comment by coury-clark** [comment]
Whats strange is we have test cases with the following:
`/b(?:u)(tt)(er)/ patternType:standard` and that works as expected, but for some reason `log\.Scoped\((".*"), (".*")\) patternType:regexp` does this conversion.

**Comment by coury-clark** [comment]
[Here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/query/transformer.go?L564) is where the pattern gets changed. It seems when it enters this function the query parser has interpreted two patterns:
`log\.Scoped\((".*"),` and `(".*")\)

**Comment by coury-clark** [comment]
In summary:

For some reason the query `log\.Scoped\((".*"), (".*")\) patternType:regexp` is getting parsed as two patterns:
1. `log\.Scoped\((".*"),`
2. `(".*")\)`

It isn't clear to me if this is intentional or not, I'll still need to look into this.

The patterns are then fed into [`fuzzyRegexp`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/query/transformer.go?L564) to be concatenated. There is a comment on this `fuzzyRegexp` function that says:
> // fuzzyRegexp interpolates patterns with .*? regular expressions and
// concatenates them. Invariant: len(patterns) > 0.

But this query or pattern doesn't have `.*?`, and I don't see anywhere in this logic that would check for that (but I'm not 100% clear on this).

The result is that we get back a pattern that has been heavily modified and is wrapped in a bunch of non-capturing groups from [this string expansion](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/query/transformer.go?L579). This means when our replacement code tries to replace the first capturing group with the aggregated value, the original pattern no longer matches.

1. Is this behavior correct / desired? From reading the comment it doensn't seem to be behaving as described (this query doesn't have any `.*?`
2. If this **is** desired, what is the recommended workaround? It seems wrapping the query in `content:()` doesn't produce the correct result. I think we could probably hack together a `patternType:standard` query, but I haven't given it a ton of thought.

**Comment by coury-clark** [comment]
Note to @Joelkw and @felixfbecker - the good news is it doesn't actually break the desired _behavior_, we can still drill down into aggregations by clicking on capturing groups. It just makes the resulting query _very_ confusing why it's so different from the original input.

**Comment by rvantonder** [comment]
The short story is: the behavior you see is all intentional, and it exists for either historic or optimization reasons. The state of code search is not built for a predictable, consumer-first API. The decisions it currently encodes are for a fast and "sometimes heuristic-y" behavior of users in the search results page. That's obviously not great if you're a client that wants a predictable, consumer-first API, but it is what it is! We've tried shift that in a lot of ways, but it's not there yet.

> 1. Is this behavior correct / desired? Is there any context to why this .*? concatenation occurs? That isn't clear to me

Yes, from the [search docs](https://docs.sourcegraph.com/code_search/reference/queries#regular-expression-search)

> Search for the regexp foo(.*?)bar. Spaces between non-whitespace strings is converted to .*? to create a fuzzy search. 

This is a historic decision aimed at upping the chances that users get results they might want. The decision precedes my time at Sourcegraph. I've worked _hard_ to try and revese the state of these decisions, which is why `Standard` search exists now, and why I urge the transition to it.

> 2. workaround

Use standard search for this part of the problem. You can stick with `patterntype:regexp` and achieve spaces literally by escaping them in regexp mode: [`log\.Scoped\((".*"),\ (".*")\)`](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+log%5C.Scoped%5C%28%28%22.*%22%29%2C%5C+%28%22.*%22%29%5C%29&patternType=regexp)

The other half of the problem:

> The second capture group is converted into a non-capturing group (shouldn't happen)

For pure search, there is no semantically meaningful difference to the user (they get the same result) whether a regex contains capture or non-capturing groups. Underneath the hood, capturing groups introduce a huge performance hit: https://github.com/sourcegraph/sourcegraph/pull/34683. This is why we convert it to non-capturing groups, and there is no way to toggle this (back to my point about "The state of code search is not built for a predictable, consumer-first API."). Unfortunate, but that's why I embarked on building compute, which allows to recover/adapt the behavior on top of search results. No workaround here unless you use compute or <other new thing> unfortunately.

**Comment by coury-clark** [comment]
@rvantonder thanks for the context! Just for additional color, this is user input so we don't have the ability to control whether or not it's pattern type standard or regexp. That said, that this is the actual search being executed makes me feel a little better about returning these queries in this form.

> This is why we convert it to non-capturing groups

Interestingly, they aren't actually _converted_ as much as wrapped in non-capturing group. The nested capture group is preserved, so I'd suspect we aren't actually realizing any performance gain here in this specific case (barring some Zoekt / search specific behavior I'm not familiar with here).

Example:
`repo:/sourcegraph$ /(?:log\.Scoped\((?:"tracer"),).*?(?:(".*")\))/`

**Comment by rvantonder** [comment]
Yeah, I see, you're right, it's not a full conversion. That may be an oversight or a sufficient approximation--in the PR we are just doing a simple string substitution and not parsing and fully converting nested groups. Passing this off to @camdencheek to follow up whether these regexps are "escaping" the conversion and whether we want to be more principled, or if wrapping the terms avoids a performance hit.

**Comment by camdencheek** [comment]
> This is why we convert it to non-capturing groups

We do not convert user-provided capture groups to non-capturing groups in the regex string (this is intentional). However, recently we made it so when regexes are compiled, [we convert capturing groups to non-capturing](https://github.com/sourcegraph/sourcegraph/pull/40992/files) where appropriate. 

We _do_ try to make sure that whenever we add groups, we make them non-capturing for performance reasons.

---------

It's not clear to me that we _need_ to add the non-capturing groups in `fuzzyRegexp`. I can't think of any reason we couldn't just join the regex patterns with `.*?`. A list of valid regex patterns should always be joinable by `.*?`, right? This isn't like [UnionRegExps](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@66caf792ad51a2a6fe61a1facd2f409ec8b4d480/-/blob/internal/search/query/helpers.go?L14-14) where we need the groups for semantics, at least I don't think

**Comment by coury-clark** [comment]
I want to clarify real quick that this is no longer categorized as a _problem_ for our 4.0 feature given the search matches the resulting drilldown query. Given that, I'm going to close this issue so it's not misleading when we look at the overall status of the project. That said, would be happy to follow up here if the search team decides to take a look at any of this here!
