### ISSUE TITLE
[ReOps] Create Research Ops templates

### ISSUE THREAD

**Issue by meglynst** [sourcegraph/sourcegraph#41271]
Templates will be created in Dovetail

Templates to make in Dovetail:

- [x] Usability test template (UserTesting) [See template here](https://app.usertesting.com/share/f5f2ba6e-6275-4db7-bbfe-5afa21f764fd)
- [x] Usability test template (Dovetail) [See template here](https://sourcegraph.dovetailapp.com/projects/3VnfTGMdL33acqZZ4zLwAM/readme)
- [x] Analysis template (Dovetail) [See template here](https://sourcegraph.dovetailapp.com/data/52K7gQHvkdAbpB1lo2rfjr)

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by malomarrec** [comment]
Hey @meglynst 
Can i ask you to please label your issues with a `team/` label (maybe creating a `team/ux-research` team if needed)?
Every issue needs to have a team label, so that we can clearly see [issues without labels](https://handbook.sourcegraph.com/departments/engineering/product/process/feedback/product_feedback_monitoring/#labelling-github-issues-with-no-team-label) that come from customers or contributors and need to be triaged.
