### ISSUE TITLE
Aggregation drilldown doesn't escape slashes within the pattern

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#41547]
Context: https://sourcegraph.slack.com/archives/CHEKCRWKV/p1662669769229249

Simple example to reproduce:
- [Query for `<title>(.*)</title>`](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%3Ctitle%3E%28.*%29%3C%2Ftitle%3E&patternType=regexp&groupBy=group)
- Click any aggregation bar
- Query becomes [`/<title>(?:Group)</title>/`](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24++%2F%3Ctitle%3E%28%3F%3AGroup%29%3C%2Ftitle%3E%2F&patternType=regexp&case=yes&groupBy=group), which has no results

Expected: [`/<title>(?:Group)<\/title>/`](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24++%2F%3Ctitle%3E%28%3F%3AGroup%29%3C%5C%2Ftitle%3E%2F&patternType=regexp&case=yes&groupBy=group) (slash escaped), which has results

Note: Search has some heuristics to try to allow this in most cases, but I think we should still play it safe and always escape as we cannot predict all possible queries where this might or might not work.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
Some clarifications:

I'm not sure there is actually a bug here, but things just aren't fitting together very well. Regardless, here is the problem:

When searches are issued in `patternType:regex` mode they seem to be _implicitly_ escaped, and the visual display on the search box matches). [Example query](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%3Ctitle%3E%28.*%29%3C%2Ftitle%3E&patternType=regexp&groupBy=group)

In `patternType:standard` it seems queries need to be explicitly escaped. [Example query](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%2F%3Ctitle%3E%28.*%29%3C%5C%2Ftitle%3E%2F&patternType=standard&groupBy=group)

**Comment by coury-clark** [comment]
So we need to fix the scenario where the initial query comes from `patternType:regex`, because any query coming from `patternType:standard` would already have been escaped.

**Comment by coury-clark** [comment]
This ended up being pretty confusing, and I'm truthfully not confident I got all the cases. It turns out we can't just naively assume all slashes can just be escaped, because this breaks queries that were _already_ escaped. For example:
[`\/insi(g)ht[s]\/`](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%5C%2Finsi%28g%29ht%5Bs%5D%5C%2F+count%3Aall&patternType=regexp&groupBy=repo)

So in the end I applied the following rules:
1. If the initial `patternType` was `regex` AND
2. The new pattern doesn't match the following regexp `[^\\]\/` (in other words, if it has any slash `/` that is not escaped we will assume that it all needs to be escaped

**Comment by coury-clark** [comment]
The drilldown query for the original input is now `repo:^github\.com/sourcegraph/sourcegraph$ /<title>(?:Group)<\/title>/`
