### ISSUE TITLE
Sourcegraph.com: can't search for repo:sourcegraph/sourcegraph

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4169]
- **Sourcegraph version:** "Sourcegraph.com"

#### Steps to reproduce:

1. visit https://sourcegraph.com/search?q=repo:sourcegraph/sourcegraph+import.*marked
![image](https://user-images.githubusercontent.com/5589410/58205775-19b7f100-7c94-11e9-9f9e-430f903a4585.png)

@slimsag not sure, but this might be related to the fix you made yesterday with `maxReposToSearch` (or whatever)?

**Comment by dadlerj** [comment]
This doesn't seem to affect other repos for some reason — e.g. https://sourcegraph.com/search?q=repo:kubernetes/kubernetes+todo or https://sourcegraph.com/search?q=repo:gorilla/mux+todo — so I won't mark this as a `p1`

**Comment by slimsag** [comment]
Correct, this occurs because we have more than 50 repositories with the name prefix `sourcegraph`. Adding a $ at the end fixes it:

https://sourcegraph.com/search?q=repo:sourcegraph/sourcegraph%24+import.*marked

This isn't a bug so I will close for now. If we hear this happening often we can bump the `maxReposToSearch` or find a way to enable global search on sourcegraph.com (which may be possible sooner rather than later in some form)

**Comment by dadlerj** [comment]
Got it, that's unfortunate. It'd be nice if we had a way of at least returning exact matches only... Searching for "github.com/sourcegraph/sourcegraph" and seeing that error is pretty irritating.

And did we JUST go over 50 `sourcegraph/sourcegraph*` repos? I've been using sourcegraph.com (versus dogfood) as my default way to search sourcegraph/sourcegraph for months now, and now it's suddenly almost unusable for me.

**Comment by sqs** [comment]
We used to set the maxReposToSearch at 1000 on Sourcegraph.com. This was acceptable for perf for quite a while. Did you set it to 50 because that's the default for sourcegraph/server or because of specific perf problems on Sourcegraph.com? If 1000 was too high, perhaps 500 or 200 would be OK?
