### ISSUE TITLE
Firefox extension needs its own download/install page

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4177]
I want to improve the download/install experience of the browser extension for Firefox users by taking them to a landing page (either on about.sourcegraph.com or the docs site) so the flow feels similar to installing an extension from the add-ons marketplace.

**Comment by aneeshusa** [comment]
+1 on this, for me the https://storage.googleapis.com/sourcegraph-for-firefox/latest.xpi page linked from https://docs.sourcegraph.com/integration/browser_extension doesn't do anything and I have to manually download the xpi file and load it into Firefox.

I imagine that due to https://docs.sourcegraph.com/integration/firefox_security the full extension can't go into AMO, but would it be possible to put a stub extension (without SG extension bits) in AMO that informs the user of how to install the SG-distributed version if they want SG extensions to work? I always forget that the SG isn't in AMO and I think this would make it more discoverable.

**Comment by wldcordeiro** [comment]
> I always forget that the SG isn't in AMO and I think this would make it more discoverable.

Just ran into this brick wall. Why can't it be an AMO extension? That would be ideal as a user as right now I just hit that page I can't do anything with. 🙁

**Comment by muratsu** [comment]
We've shipped an AMO extension for FF, users are encouraged to use the extension from the marketplace.
