### ISSUE TITLE
Compiler error in TreePage's state.treeOrError.directories on IGitTree

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#418]
After setting up a new repository locally following an install and build, `directories` is of type `IGitTree | null[]` in `backend/graphqlschema.ts`.
The `null[]` seems... wrong? 😕

```typescript
export interface IGitTree {
    __typename: 'GitTree'
    path: string
    isRoot: boolean
    name: string
    isDirectory: boolean
    commit: IGitCommit
    repository: IRepository
    url: string
    canonicalURL: string
    externalURLs: IExternalLink[]
    submodule: ISubmodule | null
    directories: IGitTree | null[]
    files: IFile[]
    entries: TreeEntry[]
    symbols: ISymbolConnection
    isSingleChild: boolean
}
```

`TreePage.tsx` is the only place where TypeScript complains:

> ```typescript
> this.state.treeOrError.directories.length
> ...
> this.state.treeOrError.directories.map((e, i) => {
>     ...
>     name={e.name}
> })
> ```

If the type is changed to `IGitTree[]`, no more complaints.

**Comment by keegancsmith** [comment]
cc @attfarhan @felixfbecker

**Comment by felixfbecker** [comment]
Hmm, I am on lastest master (f64048131d7908a8515067cb7c383784031f2c74), did a `git clean -dxff` and ran `./dev/launch.sh`, and do not get any errors.

The mentioned line looks like this in my `graphqlschema.ts`:
```ts
    directories: IGitTree[]
```

which is actually surprising because the GraphQL schema _does_ allow `null` elements:

https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/graphqlbackend/schema.graphql#L1759-L1764

@JoshuaKGoldberg are you running on a clean clone and did you only run `./dev/launch.sh`? What does `npm list @gql2ts/from-schema` print for you?

**Comment by felixfbecker** [comment]
This seems to be a change in `gql2ts` 1.10.0: https://github.com/avantcredit/gql2ts/blob/master/Changelog.md#1100

But we are using 1.9.0: https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph@master/-/blob/yarn.lock?utm_source=VSCode-1.0.13#L829

Could it be that you ran other commands than `./dev/launch.sh`, e.g. `npm install`? That would be an explanation why 1.10.0 got pulled in because we use yarn and npm won't respect the yarn lockfile

**Comment by JoshuaKGoldberg** [comment]
> `npm install`

Oh, yes, that does it. Thanks! Silly mistake on my end. +1 to #431.
