### ISSUE TITLE
batches: Work with docker images with custom UID

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#41836]
When using docker images that use a custom UID, permission issues can occur. I believe this should work in workspace mode, but not in bind mode (warning: Afaik Docker for macOS doesn't honor any permissions from the host in bind mode, but docker on linux does). 

See also https://github.com/sourcegraph/customer/issues/1305

**Comment by LawnGnome** [comment]
Realistically, this is always going to be a problem on Linux, because permissions and ownership semantics are actually going to be enforced properly. (We could potentially do something with user namespaces here, but I think it's always going to be a leaky abstraction.)

We do have a simple heuristic right now to switch back to bind mode by default on macOS if any custom UIDs are in use. Assuming that's still working as expected, I would be inclined towards backlog for this.

**Comment by eseliger** [comment]
Server-side isn't on macOS, so this will be a drawback of server-side over src-cli, but that seems acceptable for now.

**Comment by courier-new** [comment]
Resolution is to update docs for this as a "known issue."

**Comment by LawnGnome** [comment]
After discussing this at the offsite, we're leaning towards not making any significant behaviour changes right now. Options we considered and discarded:

* `chown` before each step to ensure the workspace is owned by the UID of the next container. (Doing this silently is dangerous, but more importantly, large workspaces would be very slow in scenarios where we're already likely IO bound.)
* Running all containers as `root`. (Problematic for containers with specific expectations around ownership and background processes.)
* Shadow the actual workspace volume with `bindfs` to provide the "right" UIDs for the running container. (This requires a privileged container for the FUSE mount, which is likely a non-starter for many users.)
* User namespaces. (The way sub-UIDs are mapped back to the host filesystem doesn't get the actual behaviour we need on the host filesystem, where we want everything to be owned by the same user.)

Instead, what we'd like to do is:

* Detect this situation in src-cli and warn the user.
* Provide new spec fields to override the UID and/or GID a container will run as, both on a per-step and global (per-spec) basis.

As an adjunct to this, we may also add a `src batch doctor` command to pre-flight each step to report the shell and UID/GID that will be used, which will hopefully improve supportability.

**Comment by LawnGnome** [comment]
OK, so this one's actually more insidious than I'd personally realised: SSBC can't run _any_ non-root containers in a useful way, because the workspace is always created as `root` in the first place. That's a bigger problem.

Could we set up the workspace ownership based on the UID of the first container?

**Comment by eseliger** [comment]
That's annoying

Hmm then we need to have the container runnable before the workspace cloning, that doesn't work today as we do the clone before we spawn firecracker, for security reasons we don't clone inside the VM (yet). So I don't think we can do that now, sadly.

**Comment by eseliger** [comment]
We could maybe force every container to run as root, it would certainly not make things _worse_ ™️
