### ISSUE TITLE
Don't allow empty code host config

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#41924]
We've [observed](https://sourcegraph.slack.com/archives/C07KZF47K/p1663663240317159?thread_ts=1662585216.590239&cid=C07KZF47K) a situation where code host config was empty. This causes error when we attempt to unmarshal the config. We should ensure that this is not possible.

/cc @jplahn @ryphil

**Comment by ryanslade** [comment]
Strange, we appear to already have this constraint in our DB:

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@39addfbfe2ef2002cb5ab550e03b5a9810209c19/-/blob/internal/database/schema.md?L1180:6

**Comment by ryanslade** [comment]
I believe this can happen on instances that have encryption enabled since the encrypted value even of an empty string will be non empty.

**Comment by sqs** [comment]
Note that there was a similar error that I fixed in https://github.com/sourcegraph/sourcegraph/pull/42035 that surfaced inconsistent ways that JSON was being validated between settings, site config, and external service config. It was possible to inject an empty JSON document as a user's settings by trying to save something that just had comments. Not sure if this is the case here, just wanted to mention it.
