### ISSUE TITLE
Add org membership restriction option to GitHub auth

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4195]
#### Feature request description

Our [GitHub auth configuration](https://docs.sourcegraph.com/admin/auth#github) would have an option to restrict access to the Sourcegraph instance to only members of a certain organization. 

Perhaps an `allowOrgs: ['org1', 'org2' ....]`?

#### Is your feature request related to a problem? If so, please describe.

Reported by: 
* https://app.hubspot.com/contacts/2762526/company/1712889868
* https://app.hubspot.com/contacts/2762526/company/1749284052

>In particular, we notice that  SourceGraph can provision the account automatically, but seems like if we do that with the github plugin there's no way to restrict access to a user that belong to our organization. 
>Is there a way to only allow a particular github group to login to SG? 

The issue here hits orgs that use GitHub.com, rather than private GitHub Enterprise instances (which themselves already restrict access). In the GitHub.com world, anyone with a public GitHub.com account could access the instance.

#### Describe alternatives you've considered.

Orgs can:
* Use a separate, non-GitHub SSO provider 
* Put their Sourcegraph instance entirely behind some other auth layer
* Use GitHub permissions (though this would still provide public access to the instance itself, even if others couldn't see the repos/code)

**Comment by beyang** [comment]
@ggilmore https://sourcegraph.slack.com/archives/CJX299FGE/p1558694511006100 suggests this is relevant for https://app.hubspot.com/contacts/2762526/company/561806411/.

This seems like a straightforward thing to add; maybe @sourcegraph/core-services can take this on in 3.5? If not, maybe @sourcegraph/distribution should in order to ensure a safe upgrade path for the customer.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
I'm not sure how much work this is, mainly because I am unsure at what point in our code path we would notice a user being removed from a GitHub organisation. @beyang do you have any ideas on how we would implement this, given the above concern? If you do have an idea, how many days work do you think it is?

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
> I'm not sure how much work this is, mainly because I am unsure at what point in our code path we would notice a user being removed from a GitHub organisation. @beyang do you have any ideas on how we would implement this, given the above concern? If you do have an idea, how many days work do you think it is?

For the first implementation of this behavior, it is acceptable to check org membership only on login, via an API request to GitHub.com to verify the just-signed-in user is a member of the specified org(s). We should clearly document the fact that if a user is removed from an organization, they will still be able to access the Sourcegraph instance so long as their Sourcegraph login session has not expired. I believe this is acceptable, because we don't currently invalidate sessions when a user is removed from a code host and that appears to be acceptable.

I believe the function that needs to be modified is [`GetOrCreateUser`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c8390961db597b3e34b752869e2ceca3cb3be04d/-/blob/enterprise/cmd/frontend/auth/githuboauth/session.go#L32) in the GitHub auth provider. It should check that the GitHub user is a member of one of the orgs and return an error if not. I believe this will deny login if the user has already been created but is no longer a member of the org(s).

**Comment by tsenart** [comment]
Thanks for the clear guidelines @beyang. Given your description of what needs to be done, I believe this should take no longer that __1d__. Updating the estimate in our [3.12](https://github.com/sourcegraph/sourcegraph/issues/7190) tracking issue.

**Comment by tsenart** [comment]
I'll do some manual testing of #7331 in our dogfood instance once it's deployed there, but in any case, this should be ready in time for the 3.12 release.

**Comment by tsenart** [comment]
This feature has been tested on sourcegraph.com and it's working as intended.
