### ISSUE TITLE
monitoring for how many repos are indexed/nonindexed missing

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4197]
See https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/search/backend/text.go#L60

**Comment by ijt** [comment]
This is @slimsag's idea: https://github.com/sourcegraph/sourcegraph/pull/4188#discussion_r287160324.

**Comment by slimsag** [comment]
We should still do this, distribution can own.

**Comment by keegancsmith** [comment]
Sorry thought I had already added that. My bad, I see I hadn't.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
I'd like to take a stab at this, but it looks like this has changed since the issue was opened - the linked file no longer exists, and it seems to have been moved [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@257c15c2b02a94a05c0d167c5eedbb3fa0390a9f/-/blob/internal/search/backend/text.go#L36:12), and it seems it no longer deals with indexed/unindexed repos explicitly like it was in https://github.com/sourcegraph/sourcegraph/pull/4188

Trying to find where we might regularly access the number of indexed repos I followed it down to [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/internal.go#L251:19) - it seems you worked on this a while back @keegancsmith , do you mind giving me a bit more context / some pointers on this? Thanks!

**Comment by keegancsmith** [comment]
[`Zoekt.ListAll()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.16.1/-/blob/internal/search/backend/text.go?subtree=true#L45:17) will return a list of all indexed repos. Adding a gauge to that corresponding to the size will answer the indexed part.

For unindexed that is harder to answer, especially taking into account that we do horizontal sharding. Naively it is just the count of repos - indexed. I think a useful gauge would be at your [`reposListServer.serveIndex`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/internal.go#L246) like you linked. That could also then have the indexed count. However, that endpoint deals with a specific zoekt replica, so you would need to make the prometheus gauge have the label hostname so we can see it per zoekt replica.

We could also add in gauges into prometheus. It would go in this file https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-sourcegraph-indexserver/main.go?subtree=true This is the file which communicates with the above mentioned httpapi.

**Comment by slimsag** [comment]
Update: Uwe added some metrics in https://github.com/sourcegraph/zoekt/pull/47 and https://github.com/sourcegraph/zoekt/pull/48 we can use, but we need to add them to the Grafana dashboards / monitoring stack.
