### ISSUE TITLE
backend for timeout surfacing

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#42296]
2d spike:

model storage for surfacing series alerts
API draft
rough sense of how to integrate into queries?

**Comment by coury-clark** [comment]
may need data series and insight level errors (or at least surfacing / aggregation)

**Comment by coury-clark** [comment]
Additional question: can we omit 0 value coalesce if points are timing out for the edge case where multiple series on a chart cause the y axis to break

**Comment by leonore** [comment]
@coury-clark following up on your [loom](https://www.loom.com/share/de27926a203042509ead414dcbdf99f9) (and our retrospective action item of having more eng discussions on github issues.) two questions:

1. why is it quite a bit harder to remove the entire line, rather than return zeros?
1. why would you lose the entire point for forward-facing points (new records, snapshots)? is this because for backfills, we will iterate per-repo, whereas when we do a snapshot, [we just fail the whole point?](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/queryrunner/search.go?L127&subtree=true). this may be beyond the scope of this work but there might be ways of [soft-failing repos in timeout cases](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/streaming/api/types.go?L68&subtree=true). usually when we receive a timeout event it is per-repo, so we might still be able to get matches for other repos. (maybe this adds quite a lot of complexity though)

and to answer your question:
> can we omit 0 value coalesce if points are timing out for the edge case where multiple series on a chart cause the y axis to break

I mean, I'd assume so? it's hard to tell as I'm not sure how we have planned to check for timeouts. but there should be a way of skipping that logic? I think in general my confusion stems from not knowing how we'd plan on handling these timeouts so it's hard to build a mental picture of the edge cases.

**Comment by coury-clark** [comment]
@leonore 
1. Because the design actually calls for this to only happen when it matches one repo. It will interact with our entire fetch / query pattern, and generally adds little value IMO.
2. I agree its possible, but it isn't how it works now. I think if we want to explore this in the future we can, but it does probably come with complexity and more user facing confusions. The API designed for this issue will allow something like this in the future.

From sync discussions closing this issue with sketch of API [here](https://github.com/sourcegraph/sourcegraph/pull/43506/files) and work issues open
