### ISSUE TITLE
CodeMirror: Implement cmd + f search UX 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#42482]
Implementation of issue tracked in #40724. Based on[ Figma designs](https://www.figma.com/file/xZ7os2VODDE3rNe4uFRDFu/CodeMirror-UI-Imrovements?node-id=118%3A13553) and wider design review, the following UX changes need to be made: 

- [x] Upon typing, the search should automatically scroll and select the first match in the blob view. This is consistent with behaviors in the browser and editors. 
 - https://github.com/sourcegraph/sourcegraph/pull/42513
- [x] Implement a button for "Use browser search" that allows users to return to the default browser search
- [ ] #47322
- [ ] #45265

/cc @felixfbecker

**Comment by fkling** [comment]
> Implement a button for "Use browser search" that allows users to return to the default browser search

I've been looking into this but I haven't been able to get it to work. There is a `window.find()` function, but no matter what I tried, I couldn't get the browser's search input to actually appear.
Manually dispatching a key event that "presses" ctrl/cmd+f also didn't seem to work.

Considering this, my suggestion would be to add  prominent toggle with which users can switch between searching the file content and searching the page. This could also make it more obvious to users what happens when they press ctrl/cmd+f

**Comment by fkling** [comment]
> Add a search input field in the file sidebar. Should use the same component as the symbols search input field. (Note: If implementing sub-director search is high effort, please create a follow up issue to track this as a nice to have future feature)

Regarding "Should use the same component as the symbols search input field." I assume that mostly refers to the visual side of things. Because implementation-wise the logic couldn't be more different: We have a separate GraphQL API for searching symbol names, which is what this component uses. It doesn't look like we have the same for the file tree.
We have APIs to fetch the list of entries in a directory, which is what the currently implementation does. There is an option to fetch the directory contents recursively though, so this could be used to get a list of all files and do the filtering on the client side.
With this in mind, maybe we can simple reuse the fuzzy finder logic? (cc @olafurpg)

My biggest concern atm is that adding the ability to render (and browse) and arbitrary list of files will be quite some effort with the current implementation.

And I actually have a question about the expected behavior: If a directory is matching the filter query, should the directory entry in the sidebar be "expandable"? If yes should only children be shown that match the filter or should all children be shown (including sub directories)?

**Comment by fkling** [comment]
There is possibly a relatively simple way to incorporate a simple filter capability (by just passing an additional prop down the tree and have each layer only display the files that match the filter), but even that could possibly lead to surprising scenarios with directories: We basically have to always show directories, regardless of the filter, otherwise it would not be possible to open a subtree and search inside of it. But showing all directories can be unexpected, especially if a subtree doesn't actually contain any file that matches the filter.
So ideally we would only show directories that we know contain a matching file, which brings us back again to the fuzzy finder integration approach...

So IMO building on top of fuzzy finder is the only reasonable approach, but probably also requires the most effort.

**Comment by olafurpg** [comment]
@fkling Have you tried making the `preventDefault()` behavior dependent on a `React.MutableRefObject`? I tried hacking this behavior in the diff but I wasn't able to construct a `KeyboardEvent` that triggers the native find component. You might know better how to get it working 🤔 

 https://gist.github.com/olafurpg/d17eabe3df34964251760057659ab2e8 

This approach doesn't type the search query in the native find component but I think that's a an acceptable compromise.

**Comment by fkling** [comment]
> but I wasn't able to construct a KeyboardEvent that triggers the native find component. 

Yep, I tried a couple of different approaches but I wasn't able to do this either. It's possible that browsers can distinguish between "native" events and manually dispatched events via [`Event.isTrusted`](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) and therefore don't trigger the built-in behavior.

Besides "re-triggering" the event to enable the built-in search, your suggestion is basically the same as mine.

**Comment by jjinnii** [comment]
>Considering this, my suggestion would be to add prominent toggle with which users can switch between searching the file content and searching the page. This could also make it more obvious to users what happens when they press ctrl/cmd+f

@fkling Could you clarify on this point? Do you mean exposing a user setting to have it always default to browser or CM?

**Comment by fkling** [comment]
@jjinnii Basically yes. Instead of having a button that *triggers* the browser's search (which apparently is not possible), have a checkbox that controls which search (file or browser) ctrl+f triggers. That checkbox could be prominently displayed on the file page.

**Comment by fkling** [comment]
@jjinnii , @olafurpg Here is a proof of concept for the toggle, including a video: https://github.com/sourcegraph/sourcegraph/pull/42620

**Comment by felixfbecker** [comment]
The first two items of this issue seem implemented, were the tracking metrics implemented?
The last item sounds like a separate feature unrelated to CodeMirror.

**Comment by felixfbecker** [comment]
Ping @fkling

**Comment by taras-yemets** [comment]
Moved adding a search field to the file tree sidebar to a separate issue:
- https://github.com/sourcegraph/sourcegraph/issues/45265 

cc: @jjinnii

**Comment by taras-yemets** [comment]
Moved tracking to a separate issue:
- https://github.com/sourcegraph/sourcegraph/issues/47322
