### ISSUE TITLE
No "View file in Sourcegraph" button when viewing a file on a non-master branch

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4280]
1. Go to https://github.com/sourcegraph/sourcegraph/blob/01d571ba62853db43d5dd0b73436ec47eca7662b/cmd/frontend/internal/session/session.go#L94:6 (edited)
cmd/frontend/internal/session/session.go
2. Expect to see **View file in Sourcegraph** button in toolbar.

This is also likely the same issue that's causing Codecov deocrations to not appear - https://github.com/codecov/sourcegraph-codecov/issues/29

**Comment by chrismwendt** [comment]
I'm investigating this.

It seems to work on branches and tags, but not on commits

- ✅ https://github.com/sourcegraph/sourcegraph/blob/alert-bg/cmd/frontend/internal/session/session.go
- ❌ https://github.com/sourcegraph/sourcegraph/blob/01d571ba62853db43d5dd0b73436ec47eca7662b/cmd/frontend/internal/session/session.go

Hovers fail with an error that says a file could not be found:

![image](https://user-images.githubusercontent.com/1387653/58733559-b02d9600-83a9-11e9-80c6-1d48e13cdd17.png)

The filename looks weird `/53db43d5dd0b73436ec47eca7662b/cmd/frontend/internal/session/session.go`. The `53db...` part is the original commit with the first 11 characters stripped off. I'm guessing there's some logic in the browser extension that's incorrectly parsing the URL.

Still looking.

**Comment by chrismwendt** [comment]
Ah, the browser extension assumes it'll find a branch name in the selector 

![image](https://user-images.githubusercontent.com/1387653/58735385-15d05100-83af-11e9-9b1e-34afb84e5123.png)

https://github.com/sourcegraph/sourcegraph/blob/6b27dd37fe66ef5907df014ba4e1e92974f1c225/browser/src/libs/github/util.tsx#L199

@lguychard Did you forget about trees? Could we get the branch/tree from the URL instead of the DOM? It's probably easier, and I'm guessing URLs will be more stable, too.

**Comment by chrismwendt** [comment]
The title of the `.select-menu-button` doesn't contain the full name either:

![image](https://user-images.githubusercontent.com/1387653/58735626-cdfdf980-83af-11e9-8a17-af899592e81f.png)
