### ISSUE TITLE
Feedback: Search results should always open in new tab

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4282]
All search result links should open in a new tab.

Multiple users have complained about the fact that search results do not open in a new tab (because going back to the same search results page, you immediately lose the results you were looking at).

I imagine almost *all* Sourcegraph users today cmd+click links out of habit because we have chosen this poor default today. We should change it to open in a new tab always.

407948923

**Comment by donavonelli** [comment]
Just wanted to let the team know that one of our customers is really looking forward to work happening on this. @christyharagan can share more context

**Comment by benvenker** [comment]
@limitedmage or @novoselrok do either of you want to pick this up? Thomas was assigned but seem a little out of his normal scope :D

**Comment by limitedmage** [comment]
I think if we have this, it should be a setting of some kind and disabled by default. After the work we did last year to make navigating back cache the search results, I think this is even less necessary. 

Also, should this only happen when the "simple UI" toggle is on (make it part of the core workflow improvements)?

**Comment by benvenker** [comment]
@limitedmage what if we add an "open in new tab" icon button to the result header and keep the current behavior when you're clicking into a result? If we did that, the one modification I would request is that clicking on the open in new tab button  automatically takes you to the first match in the file.

Today when you click on the file name in the header it just takes you to the top of the file. I'd argue that behavior should be changed either way to take you to the first match in the result.

**Comment by limitedmage** [comment]
> @limitedmage what if we add an "open in new tab" icon button to the result header and keep the current behavior when you're clicking into a result? If we did that, the one modification I would request is that clicking on the open in new tab button automatically takes you to the first match in the file.

I honestly don't see a reason why all this is even necessary. A new tab can always be opened with middle click or Cmd+click. No search engine (Google, GitHub, Amazon, etc) opens results in new tabs by default or provides a button next to results to open in a new tab. This feels like it will clutter the UI and confuse expectations for the majority of users. I'd like to understand more from users who want this feature, especially since the last mention of this was almost a year ago. If this is desired by (a small vocal minority) of users and decide to build it, I think it should be a setting and not the default or an extra button visible to all.

> Today when you click on the file name in the header it just takes you to the top of the file. I'd argue that behavior should be changed either way to take you to the first match in the result.

I think this is a separate issue, if you think we should tackle this, file a work item. FWIW GitHub Code Search doesn't do this.

**Comment by camdencheek** [comment]
Closing as won't do because:
1) The middle click or cmd+click still works
2) The back button now works as expected since we maintain the list of search results and the scroll state in history
3) We now have the file preview panel, so you can look at a file more closely without needing to leave the context of search results
