### ISSUE TITLE
Expose external service sync status

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#42868]
We don't have any visibility into the progress of an external service sync apart from that it has
started.

We should try and expose the following:

* Number of repos synced
* Number of sync failures
* Number of repos added / removed

We should be able to show this on the external service page where we currently show a time
since the sync started counting up.

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
Thought dump since I've poked at this a bit in the past with @eseliger:

* I'd add additional columns to the `external_service_sync_jobs` table to reflect this information. This information is job-specific and it makes sense to save it here.
* (I think @eseliger even has a draft PR somewhere that showcases how to record some data?)
* The return value of this function could be a struct and the handler persists it on the job: https://github.com/sourcegraph/sourcegraph/blob/0d77cc797b2a2435bab17ede9b9f439d202e3a2b/internal/repos/syncer.go#L129
* I think this is the info we want to record: https://github.com/sourcegraph/sourcegraph/blob/0d77cc797b2a2435bab17ede9b9f439d202e3a2b/internal/repos/syncer.go#L665-L669 -- `seen` is the number of all repos we found while querying code host, `added`/`modified`/`deleted` are the numbers we want to display in UI too.

**Comment by ryanslade** [comment]
Cool, all makes sense. 

More brain dumps from me:

Our external service syncer is currently agnostic about how the `SyncExternalService` method is invoked and I'd like to keep it that way. 

If we want to periodically update the counts while the job is running we'll need to provide some at callback function or interface to `SyncExternalService` that will update the row in `external_service_sync_jobs`. I'll need to look into what kind of transactions surround the row from the workerutil package.

**Comment by eseliger** [comment]
Great to see this list! That sounds exactly like what could solve a lot of problems :) 

>  I'll need to look into what kind of transactions surround the row from the workerutil package.

None! While the worker is working on the record. Dequeueing and MarkFinal are two separate transactions, and in between the record is not locked, to support exactly this use-case :) 

In addition to stats, what I could also see as valuable extra information is unstructured information, like are we currently waiting for a rate limit, or which repo exactly was wiped.
I would see the "counting up stats" as the **high-level information that I absolutely must see every time a sync happens**, and when the numbers seem odd, a potential next step could be to investigate additional unstructured logs.

Executors are just a special worker type that also uses the `workerutil.Worker` under the hood. For executors we built a streaming logger before that could be generalized. I did a quick and dirty PoC that shows how we could also add streaming logging to other workers, like the external service sync worker. (includes a screenshot) https://github.com/sourcegraph/sourcegraph/pull/42073

**Comment by ryanslade** [comment]
How do you guys feel about adding a generic `metadata` json column to `external_service_sync_jobs` to store some running stats. I feel like it may be overkill to add a bunch of custom columns where one with some sem-structured data will be enough.

**Comment by eseliger** [comment]
Works for me, migration can sometimes be a bit ugly for JSON but maybe not a problem :)

**Comment by mrnugget** [comment]
Yeah, have to say I like single columns more (and even 10 would not be a lot - this is a database we’re talking about), because JSON is super unwieldy (in Go and in SQL).

But not blocking on this, just personal preference

**Comment by ryanslade** [comment]
> Yeah, have to say I like single columns more (and even 10 would not be a lot - this is a database we’re talking about), because JSON is super unwieldy (in Go and in SQL).
> 
> But not blocking on this, just personal preference

You'll be happy to hear I'm going the multiple column route and it's not TOO bad :)
