### ISSUE TITLE
Support managing non-code host accounts in accounts security page

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#42879]
As a follow up to https://github.com/sourcegraph/sourcegraph/issues/38195 , we should also look into supporting non-code hosts auth providers, like `openidconnect`.

Current behaviour:

When ther is an `auth.providers` entry in the site config that is not GitHub or GitLab, and a user signs in with one of them (such as `openidconnect`, that account connection is not visible in the user's Account Security page

Expected outcome:

When there is an `auth.providers` entry in the site config, that is not GitHub or GitLab, those accounts should also be manageable from the User's "Account Security" page.

**Comment by kopancek** [comment]
Currently the problem is in this line: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx?L57

We should either create a `defaultExternalAccounts` variable with all supported external account types and icons or provide some sane default if there's no match, e.g.:
```
import AccountCircleIcon from 'mdi-react/AccountCircleIcon'
...
...
const { icon, title: name } = defaultExternalServices[kind] ? { icon: AccountCircleIcon, title: kind }
```

**Comment by miveronese** [comment]
Follow-up issue here: https://github.com/sourcegraph/sourcegraph/issues/43256
