### ISSUE TITLE
`.sourcegraphignore`

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#42952]
#### Feature request description

Use a `.sourcegraphignore` file to exclude the content of massive files when cloning/updating repositories. Keep the file name in the tree, but ignore its contents. If the file appears in search results, accompany the search result with a message informing them why they can view the file by name but not the file's contents.

i.e: `this file exists in the repo, but its data has been excluded from recloning by the user. Please remove it from your .sourcegraphignore file if you'd like to search its contents`

#### Is your feature request related to a problem? If so, please describe.

Some of our larger enterprise customers have repos that contain large binary files. The content of these files is irrelevant to any search these users might make. However, significant tech debt is accrued when including those contents in the initial index of such repositories and each subsequent update. In short, we are allocating heavy resources for the task of indexing and updating files whose contents will never be searched.

#### Describe alternatives you've considered.

You can exclude a file from a search every time, but this only optimizes the search, not the indexing/updating process.

/cc @jplahn @ryphil

**Comment by keegancsmith** [comment]
We have `.sourcegraph/ignore` https://docs.sourcegraph.com/code_search/explanations/search_details#exclude-files-and-directories

Excluding files from cloning is a bit more tricky and I'm unsure if it is a useful feature. But our ignore feature will prevent those files from being searched.

**Comment by jasonhawkharris** [comment]
The customer who requested something like this isn't so much interested in whether these files appear in search results, they're more concerned about the effort it takes to clone these large files in the first place.

**Comment by jasonhawkharris** [comment]
@keegancsmith I've summarized the customer's response to the questions you asked. Please let me know if you have any clarifying questions.

As of now, their solution is to simply steer people away from storing large files in Git. If they absolutely need to, they try to direct them to use Git-LFS. But the reality is, they have quite a few repos that aren't following this recommendation, and they don't know for sure how many of those repos with large files are actively used.

The repos in question (those containing large files) tend to cause sync failures, which makes understanding the health of the search data more difficult. Right now, the solution they're employing is to manually exclude the repos in question, which comes with the disadvantage of not being able to search quite a bit of code that they'd like to be able to index.

They also believe that having Sourcegraph be aware of these large files is still valid even if they are not indexable. For example, being able to search the location of the file.

They are increasingly trying to leverage Sourcegraph to support security and platform work, where having a complete picture of their code bases is essential. As this trend continues, they'd like to try and minimize the repo exclusions as much as possible.

**Comment by keegancsmith** [comment]
Right, so as mentioned we can avoid indexing/searching these. Excluding them from cloning is quite a difficult problem. In theory git does support this with protocol v2 as I mentioned. You can omit objects by size and/or a sparse-checkout specification (ie a list of paths to exclude). See [git-rev-list#filter](https://git-scm.com/docs/git-rev-list#Documentation/git-rev-list.txt---filterltfilter-specgt) documentation.

The problem here is two fold:
- More than likely a bunch of our stuff will fail in the cases of having a blob referenced but then it not being in the repo. EG lots of things will think the repo is corrupted. This is quite a deep problem to fix.
- We need to cook up a nice way for users to use this. It will likely always have sharp edges given there is a bit of a chicken and egg problem for knowing which files to exclude without yet having a clone of a repo. IE this leads to some potentially ugly solutions using site config or external service specs.

It's hard for me to think this problem is so big is justifies the above. But just to confirm, in practice they have had problem with _gitserver_ cloning these repos. IE the problems on sourcegraph occurred before zoekt tried to index. If the latter our normal ignore stuff should work great.

Otherwise an alternative solution would be them maintaining some sort of mirrored copy of these repos but without the bad blobs. This wouldn't only be useful for sourcegraph, but sounds like it would be useful for them in general.

**Comment by mrnugget** [comment]
I'm closing this. Let's reopen if it comes up again.
