### ISSUE TITLE
Slow Performance: Code blocks on search results page appear several seconds after the search results appear

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#43021]
- **Sourcegraph version:** 3.43
- **Reported by:** https://github.com/sourcegraph/accounts/issues/6716

#### Details

When the user performs a search, the search results load in a reasonable amount of time.  However, the preview of matching code loads a few seconds later.  An example is captured in [this video](https://drive.google.com/file/d/1gOpFy1UDf-zXQ2dfDx7qKUZhJl78aPlE/view?usp=sharing).

/cc @sourcegraph/search-core

**Comment by jplahn** [comment]
Adding search core

**Comment by keegancsmith** [comment]
> However, the preview of matching code loads a few seconds later.

There are two things done here: fetching the file from gitserver 
followed by highlighting on syntect-server. If the issue was 
gitserver I'd suspect more reports about general performance from 
the customer.

So more than likely syntect-server is the problem. They can try view
charts about its performance or just experiment with giving it more
resources / more replicas to see if it improves the situation.

**Comment by AlicjaSuska** [comment]
cc: @philipp-spiess

**Comment by mrnugget** [comment]
Closing this since it doesn't seem really actionable.
