### ISSUE TITLE
Scaletesting: Explore IDPs and GitHub

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#43044]
It was suggested to us that we could use an IDP to replicate 10k users on a GHE instance by our assigned solution architect.

- we don't know how closely using an IDP with GH matches the use cases of our customers
- we don't know how IDPs and GitHub interacts.

➡️ With that in mind, we believe it's best to run some quick discoveries on IDP and see how big an effort it would be to use one to create 10k users with a bunch of varied permissions.

⚠️ Do not spend more than a day on this exploration.

**Comment by kopancek** [comment]
Here's some official github docs on team synchronization from idp: https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/managing-team-synchronization-for-your-organization

**Comment by sanderginn** [comment]
Findings so far:

### Candidate IdPs (⭐ = officially supported by GH, 🟢  = OS):
- Okta ⭐ 
  - #cloud uses/used a [dev Okta instance](https://dev-97632531.okta.com). Perhaps we can reuse or set up a new one, depending on whether it can support this use case and falls within Okta's policy
- Keycloak 🟢 
- Ory Kratos 🟢
  - [HTTP API](https://www.ory.sh/docs/kratos/reference/api#tag/v0alpha2) seems to be lacking some required features, such as group membership 
- Shibboleth ⭐ 🟢  
  - Non-trivial installation

I would suggest to go with Okta if possible, otherwise Keycloak. Both IdPs have first-class Terraform support, which would allow us to easily seed fixtures while keeping configuration centralised in our scaletesting repo. It would also cut down on implementation time compared to implementing an API-based approach.

### GHE resources:
- [Configuring SAML single sign-on for your enterprise](https://docs.github.com/en/enterprise-server@3.6/admin/identity-and-access-management/using-saml-for-enterprise-iam/configuring-saml-single-sign-on-for-your-enterprise)
- [Managing team synchronization for your organization](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/managing-team-synchronization-for-your-organization)
  - Unfortunately, team synchronisation is only available on GHE Cloud, not on GHE Server. Included the link for visibility.

### Questions:
- Are user objects in GHE created before or after users log in on the instance? If done post login, is there a practical way of automating this behaviour? From the docs:

  > When an unauthenticated user visits your GitHub Enterprise Server instance in a browser, GitHub Enterprise Server will redirect the user to your SAML IdP to authenticate. After the user successfully authenticates with an account on the IdP, the IdP redirects the user back to your GitHub Enterprise Server instance. GitHub Enterprise Server validates the response from your IdP, then grants access to the user.

  If this cannot be automated, I don't really see a path forward supporting tens of thousands of users using an external authentication platform.

**Comment by sanderginn** [comment]
Closing this as integrating an IdP does not offer a realistic path forward at this moment. We will probably revisit at a later stage.
