### ISSUE TITLE
webhooks: Add interfaces to webhook related GraphQL resolvers

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#43078]
[Usually interfaces are used](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+file%3Acmd%2Ffrontend%2Fgraphqlbackend%2F+type+.*Resolver+interface&patternType=regexp&groupBy=path) in GraphQL resolvers, webhook related resolvers should use them too.

/cc @jplahn @ryphil

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/43071/commits/d39446da6f8e9b86593084bda66c4d5e54e839c7

**Comment by mollylogue** [comment]
@sashaostrikov Is there more to do here than what I added in https://github.com/sourcegraph/sourcegraph/pull/43071? The interface isn't used anywhere yet.

**Comment by sashaostrikov** [comment]
@mollylogue sorry, I totally missed my GH notifications...

I thought about something like [Authz resolver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/authz.go?L12&subtree=true), to have a separate `WebhooksResolver` interface and a struct with methods implementing it (instead of having methods of directly `schemaResolver` as it is done now).

This doesn't change anything functionality-wise, just (IMHO) organises code a bit better and makes it more uniform with other interface usages in `graphqlbackend` package.

I guess remaining changes are to create `WebhooksResolver` interface and make `webhookResolver` struct also a struct implementing some `WebhookResolver` interface.

But once again, this can be put aside and implemented a bit later, no hurry at all.

WDYT?

**Comment by mollylogue** [comment]
@sashaostrikov Ahh I see what you're saying. I'll look into it 👍

**Comment by mollylogue** [comment]
@sashaostrikov what kind of functions would we want on this interface, exactly? Just trying to figure out if it's worth it or not to add this extra layer since the functionality we have thus far is relatively simple. I see the benefit in the authz case, but I'm not sure I see it as much in this particular case. Though I'm happy to change my mind :)

**Comment by ryanslade** [comment]
I would say that we should only add the interface when we need it, for example to mock out the resolver. 

I think the reason we have interfaces for some resolvers is so that we can have two implementation, one for enterprise and one for non-enterprise, which I don't think is something we need to worry about yet for the webhook handler.

**Comment by mollylogue** [comment]
> I would say that we should only add the interface when we need it, for example to mock out the resolver.
> 
> I think the reason we have interfaces for some resolvers is so that we can have two implementation, one for enterprise and one for non-enterprise, which I don't think is something we need to worry about yet for the webhook handler.

Sounds good 👍 Let's skip this for now, then.

**Comment by ryanslade** [comment]
I'm going to close this, we can re-open or create a new one when we decide to work on this. I don't want it to appear as an outstanding task in Milestone 1
