### ISSUE TITLE
webhooks: Handle GitHub `push` events

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#43106]
We need to ensure that our GitHub webhook handler can handle `push` events. 

We'll use the information in the [payload](https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#pushevent) to find the appropriate repo. If we don't have the repo in our instance we can ignore the event.

Once we have the repo, we need to ensure that the repo is pushed to the front of the scheduler using our
existing [repo updater client](https://github.com/sourcegraph/sourcegraph/blob/4aa528f8b14172a6a7fd7fd8d508904d729ce272/internal/repoupdater/client.go#L137)

/cc @jplahn @ryphil

**Comment by mollylogue** [comment]
First, I see that we have an existing handler for `push` events as defined in [this pr](https://github.com/sourcegraph/sourcegraph/pull/39941) however, it's not actually registered anywhere except for the tests, and it's in a different location from the other handler functions, which we see are all registered [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/webhookhandlers/handlers.go). I believe the first step is to move that code to be with the rest of the handlers in the `webhookhandlers` package. Then I can test that the push events can be handled successfully or if there are modifications that need to be made to that code.

I'll handle the portion of this task where we ensure the update request goes to the top of the queue in it's own separate PR, likely.

**Comment by mollylogue** [comment]
Just reading through the current code and trying to make sure I understand what currently exists and what we need to do next. We have a handler which handles GitHub push events, which is registered [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/httpapi.go?L97-98). It's a bit unclear to me why we'd have that in a separate package from the other Github webhook handlers, but that's not a big deal. If we trace through the code, we see that [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/httpapi.go?L104) we register the new webhook handler (which contains the uuid in the path) this [handler](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/webhooks.go?L25:6) looks up the webhook in the db based on the uuid in the url path, then does secret validation if necessary. Since the push events will be from GitHub, we follow the path [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/webhooks.go?L60) to handle the GitHub event, which sends us [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/github_webhooks.go?L85:25) where the type of event is determined, and then it's passed to the appropriate handler for that event [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/github_webhooks.go?L114). I'm _assuming_ that since we call `webhooks.GithubWebhook.Register` with `"push"` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/github_webhook_handler.go?L24), that means we should successfully be able to handle the "push" event type already. 

My first step is to actually validate that is the case by creating a webhook via the graphql api, then creating a webhook in Github w/ the webhook url (including the uuid). We'll see if the events are being handled correctly or if there's more we need to do.

I plan to address the portion of this task to move these events to the top of the update queue separately, after I've figured out what the current state of handling push events is.

**Comment by mollylogue** [comment]
I manually set up a webhook for a test repo in our ghe instance and it had a successful test delivery of the payload to the url `https://sourcegraph.sourcegraph.com/.api/webhooks/{webhook uuid}`. I'm going to push code to the repo and see if it successfully enqueues a repo update.

**Comment by mollylogue** [comment]
It works!!!!!!!! Once I added the repo to an external service config, now whenever i commit new code to the repo the code appears almost immediately on S2 🤩  And looking at the traces provided in the webhook response it looks like we're syncing the repo as expected.

**Comment by mollylogue** [comment]
@ryanslade Sounds good 👍 I'll take a look at that PR and think about how to refactor this a bit so that it's a bit more intuitive. I'm also going to look into ensuring that the update requests get pushed to the top of the queue.

**Comment by ryanslade** [comment]
I think it should go to the front of the queue. It ends up [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@9e46677/-/blob/cmd/repo-updater/repoupdater/server.go?L63) which eventually ends up calling `UpdateOnce` on the scheduler which adds it to the queue as high priority [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@9e46677e6d2101a3da78c124bfd60b4c8f7ad806/-/blob/internal/repos/scheduler.go?L394) which will take precedence over any scheduled updates.

**Comment by mollylogue** [comment]
> I think it should go to the front of the queue. It ends up [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@9e46677/-/blob/cmd/repo-updater/repoupdater/server.go?L63) which eventually ends up calling `UpdateOnce` on the scheduler which adds it to the queue as high priority [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@9e46677e6d2101a3da78c124bfd60b4c8f7ad806/-/blob/internal/repos/scheduler.go?L394) which will take precedence over any scheduled updates.

Awesome. I figured, given how quickly the repo was updating whenever I pushed new code, but I hadn't traced down the codepaths to be sure yet.

**Comment by ryanslade** [comment]
I think we can close this now right?

**Comment by mollylogue** [comment]
I think so, unless there's something more you were hoping to get out of this task besides just validating that it works as we expect.

**Comment by ryanslade** [comment]
We're good as long as it works via our new uuid endpoints.

We've got another issue to go back and clean things up a bit code wise.

**Comment by mollylogue** [comment]
Sounds good 👍 I've validated that, so we're probably good to close this out.
