### ISSUE TITLE
Why is repositoryQuery required when orgs is set?

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4322]
![image](https://user-images.githubusercontent.com/10532611/58768192-6e624280-8597-11e9-8345-53e96710c50c.png)

**Comment by mrnugget** [comment]
cc @keegancsmith @tsenart because I think I have as much insight into this as you do :)

My guess would be that it's far better for rate-limits and resources to use `repositoryQuery` instead of fetching the `repos` in sequence and making `repositoryQuery` required helps us nudge users into that direction. Now that we evaluate batch-fetching for GitHub `repos`, maybe that could be changed, but, again, I don't have historical context here.

**Comment by keegancsmith** [comment]
We can make this field non-required. The only thing stopping us is we use it missing as a sign we need to run a migration (we changed the default value of repositoryQuery a few version ago). I think we have had enough minor versions to remove that migration and adjust the requirement. I'll let @tsenart weigh in further.

**Comment by tsenart** [comment]
> I think we have had enough minor versions to remove that migration and adjust the requirement. I'll let @tsenart weigh in further.

We had 3.3 and 3.4, so I think so too that we can remove these migrations in 3.5, and make `repositoryQuery` optional.

**Comment by keegancsmith** [comment]
We can start making changes like this in 3.6. So will add to the milestone since its fun and quick tech debt work.

**Comment by felixfbecker** [comment]
I am still seeing this on k8s.sgdev.org. It still seems to be required.

![image](https://user-images.githubusercontent.com/10532611/62634516-552e9700-b936-11e9-9e8b-4b2ec7965a54.png)

**Comment by mrnugget** [comment]
Yeah, but the original ticket was about repos and repositoryQuery. You‘re
now using orgs, which is a newer addition.

**Comment by felixfbecker** [comment]
I read that the resolution of this issue was to “make repositoryQuery optional”. So adding a new field shouldn’t change that, right?

In general it would worry me that there are implicit dependencies between fields that are not naturally expressed through the JSON schema. E.g. if two fields have an xor relationship, they should be one field with a union type so it is intuitive that it is either one or the other. If two fields are possible to specify in JSON, then one would expect that it is valid to do so too.

I actually didn’t add this. The external service config already had the orgs field, and I added a repositoryQuery field. Then I wanted to remove it again, but couldn’t. So this must either be a regression, or it is possible to get the config into an invalid state, which is also worrying.

**Comment by mrnugget** [comment]
> they should be one field with a union type so it is intuitive that it is either one or the other

You can specify all three, but need at least one of three. You can specify that in the JSON schema, but it leads to a really ugly error message that is far more confusing than the one that originally triggered this issue.

We can just extend the code to take `org` into consideration now.

**Comment by felixfbecker** [comment]
Could a test be added to test specifying only repositoryQuery works and we don’t regress on it the next time we add a field?

**Comment by mrnugget** [comment]
I have added a test that tests that. See the PR/commit that fixed this issue the first time.

This is not a regression, this is a new requirement: you now want the new orgs field to also work without specifying repositoryQuery/repos.

**Comment by felixfbecker** [comment]
Sorry, I meant _not specifying_ `repositoryQuery`. I just want to make sure that if we add another new field in a month, we don't have the same problem again. How can we ensure that?

**Comment by mrnugget** [comment]
Yeah, I got you, I meant the same: _not specifying `repositoryQuery`_.

Currently you need to specify one of the following: `repositoryQuery`, `repos`. One of these two will do.

I'm also working on a commit right now (waiting for yarn) so that you need to specify one of the following: `repositoryQuery`, `repos`, `orgs`.

As I wrote above: one _could_ put that requirement in the JSON schema, but the error message will be confusing if nothing is specified. So instead we validate the requirement in code.

And I don't see a way to way to encode the requirement "specify at least one of _list of fields_" where _list of fields_ is extended automatically by adding a new configuration field.
