### ISSUE TITLE
Perforce configuration expects a P4PASSWD but the example indicates a ticket value

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#43307]
- **Sourcegraph version:** 4.0.0
- **Reported by:** https://github.com/sourcegraph/accounts/issues/583

#### Details

The template in the value field in a new Perforce code host configuration shows:
```
{
  "p4.port": "ssl:111.222.333.444:1666",
  "p4.user": "admin",
  "p4.passwd": "<ticket value>",
  "depots": []
}
```

When Perforce admins see the `<ticket value>` they assume they can just run `p4 login -a -u <user>` and copy the value from `~/.p4tickets`.  The format of that ticket is : `perforce-server:1666=username:hash`.  If you set the configuration value `p4.password` to the full ticket value from `p4 login -a -u <user>`, you will see an error: `Perforce password (P4PASSWD) invalid or unset.`.  If you instead change `p4.password` to the `hash`, it works fine.  

The [docs](https://docs.sourcegraph.com/admin/repo/perforce#depot-syncing) give the correct command `p4 login -a -p` but it's easy to miss that.

#### Suggested Change

Allow `p4.passwd` field to take a ticket value and strip out the hash automatically.  Or, change the template to simply state `<p4passwd value>`.  

See the last paragraph of [this doc](https://www.perforce.com/manuals/cmdref/Content/CmdRef/P4PASSWD.html) for more details.

/cc @jplahn @ryphil

**Comment by vdavid** [comment]
I'm picking this up.

I've discussed the possible solutions with @mrnugget yesterday. The three solution ideas that came up:
1. Strip out the hash automatically when a full ticket is inserted. (As suggested in the issue description.)
2. Change the placeholder to simply state `<p4passwd value>`. (As suggested in the issue description.)
3. Warn the user if they seem to have inserted a full ticket rather than just a hash.

Our suggestion is **no. 2 + no. 3**

**Reasoning:**
 - Solution no. 1 seems very user-friendly, but after discussing it a bit, we came to the opinion that it's probably too much behind-the-scenes magic for this UI. _If it was_ a GUI, we could easily do that magic and delight the user. But this is a JSON. It'd be weird to mess with the plain text data the user enters—even if (or even _more_ because) we don't display that piece of data afterward. (We show `REDACTED` for the password on future page loads.)
 - If we change the placeholder text, that probably resolves most of the issues.
 - We can still detect a string that looks like a full ticket rather than a hash and show a warning. This should solve the rest of the cases while being fully transparent with the user.

@mike-r-mclaughlin please let me know if you disagree; otherwise, I'm going ahead with this solution.

**Comment by vdavid** [comment]
Hey @unknwon!
I’m mentioning you because of this PR:
- https://github.com/sourcegraph/sourcegraph/pull/21189

The client’s request is basically to **either** start accepting Perforce ticket values in the `p4.passwd` config field **or** not call it “ticket value”. My intention is to rename it, plus warn the user if they still paste a ticket value (see my comment above for reasoning and details).
I looked into the code and found your PR that did the exact opposite rename 😄 So I understand that it is deliberate to write “ticket value” but your PR didn’t mention an issue so I have no context on why we did this change.
Could you provide context on this if you remember?

**Comment by unknwon** [comment]
As far as I could remember, the intention was to keep the name of our config option to be aligned with what env vars the p4 CLI takes. Initially, we support handling the interaction of feeding the plain password to the p4 CLI but was dropped due to mainly the sense of insecurity and concerns from Perforce ops admins to give up their super admin account password (not because of technical difficulties).

IIRC, if you give a plain password directly through `P4PASSWD`, it would not work (i.e. has to be fed interactively). So a ticket value is always expected by the p4 CLI if one wants to use the `P4PASSWD`.

The problem here as I read, is that the correct command had been given but was easy to miss, couldn't we just fix that? Although smartly handling full ticket value and only using the part we want also sounds like a reasonable approach.

**Comment by vdavid** [comment]
Wow, thanks for the context, @unknwon! This (and then a bunch of trial and error) were all the missing pieces I needed, and although the way things work is weird, I now have an understanding that seems accurate!

(@unknwon: Only read through this if you're interested; I can complete this on my own. Thanks again!)
(@mrnugget: These notes are mostly for myself; only read through this if you're interested. I'll open a PR once I'm done. Maybe read the "My suggestion is" section at the bottom.)

My findings (mostly for myself):

There are four relevant types of data related to p4passwd and tickets:
   1. The plain-text **`password`**
   2. The **`ticket`** from the `.p4tickets` file one gets after `p4 login` (looks like `perforce-server:1666=username:hash`)
   3. The **`hash`** from the ticket (the last part of the ticket)
   4. And a directly generated hash that looks identical to **`hash`** but confusingly enough, Perfors refers to it as a "ticket" [in their docs](https://www.perforce.com/manuals/cmdref/Content/CmdRef/p4_login.html#:~:text=Display%20the-,ticket,-%2C%20rather%20than%20storing). To give it a unique alias, let's call it a **`short ticket`**.

We [use](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/vcs_syncer_perforce.go?L227) the `p4 ping` command to test the connection in our codebase, so this is what I used, too. I ran this:
`P4PORT={host} && P4USER={admin} P4PASSWD={stuff} && p4 ping -c 1`
and tried all the above options for `{stuff}`. It **only** works with the **`short ticket`**!

So, the proposed solution (that is, recognizing when the user enters a **`ticket`** (reminder: this means the _long_ ticket) and stripping out the clutter) and only using the **`hash`** **won't work** because albeit it _looks_ the same, it behaves differently.

As proof, I could **finally** make my own code host work on a test instance! (My previous project was with Perforce as well, and for weeks I used quirky workarounds because I was also missing this piece of information!)

**My suggestion is:**
- Keep the placeholder (the term "ticket" is accurate based on the [Perforce docs](https://www.perforce.com/manuals/cmdref/Content/CmdRef/p4_login.html#:~:text=Display%20the-,ticket,-%2C%20rather%20than%20storing)), and 
- Make the tooltip text even clearer, by giving an example on how the "ticket" should look and how to get it.
- Add the warning text in case someone pastes stuff that's in the **`ticket`** (long) format.

Phew.

**Comment by unknwon** [comment]
> * Add the warning text in case someone pastes stuff that's in the **`ticket`** (long) format.

I can't recall if it's possible to have `:` in the short ticket, if not, then we could add a JSON schema check aginst this character, as a clear sign someone is pasting in the long ticket.
