### ISSUE TITLE
RFE: Add the number of results next to each item in the user's recent search list

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#43422]
**Reported by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1666693597809989)

#### Feature request description

Add the number of results found next to the search shown in the recent searches list.   This could be the number of results found the last time the search was run rather than a live count.

![image](https://user-images.githubusercontent.com/23640224/197803215-d566f0df-3d59-4dd3-8dec-6c40a44f6af4.png)

#### Is your feature request related to a problem? If so, please describe.

> Having an additional token attached with the search result helps you find the right one to run again because sometimes you would want to iterate on slightly different versions of a search query to get to what you want. If there is a variation of the search query that returned 1000 results and there is a slightly different one that had only 10 results, then I can easily pick from my memory which query is the one I want to iterate even if I don’t remember the exact query

**Comment by vdavid** [comment]
Discoveries after a bit of research:
- To show recent searches on https://sourcegraph.test:3443/search, set `"showEnterpriseHomePanels": true` in global settings
- GraphQL query to get the data is [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/panels/PanelFragments.tsx?L36)
- Data display is [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/panels/RecentSearchesPanel.tsx?L177)
- "SearchResultsQueried" seems to be inserted [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/vscode/src/webview/search-panel/SearchHomeView.tsx?L87) but I'm not sure if the result count is available at this point. If not, we may need to do the "SearchResultsQueried" event logging a bit later.
- I assume our DB schema is not dynamic, so I'll need to insert a field to store the result count for each item. If it's dynamic then it's much simpler.

**Comment by vdavid** [comment]
Hey @limitedmage!
I was discussing this issue with @mrnugget today, and he suggested reaching out to you (or someone from Search) and making sure that working on this wouldn't clash with any of your team's efforts.

So, the goal is to put a new column of data in the "Recent searches" list. The solution I intend to implement is to
 - start logging the search query in the `SearchResultsFetched` telemetry call [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/results/StreamingSearchResults.tsx?L170) and in the other 3–4 similar calls in the code base
 - switch over to querying event log items for `SearchResultsFetched` rather than `SearchResultsQueried` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/panels/PanelFragments.tsx?L38) when we fetch the data for the "Recent searches" list.

Thoughts:
- If this clashes with your efforts or you just don't feel comfortable with someone external to Search contributing here, let me know and I'll drop this, no questions asked. 😃 
- If you're fine with me doing this but you have an alternative suggestion for a solution, let me know; I'm interested! Thorsten and I concluded that the current solution of assembling the recent searches from telemetry data is very ugly as it is, but this time I don't want to fix this just yet; I mean to make this a small change.
- If you're fine with me doing this, and you feel like pairing on it, that's totally cool, too, just let me know!

**Comment by limitedmage** [comment]
Hey @vdavid, we're actually getting rid of the recent searches panel (all panels are now disabled by default). We are adding a new search history feature and we'll ship that before fully removing the panels. So this feature request should be considered in light of this.

The new search history feature is not dependent on telemetry and instead uses temporary settings. We have a lot more flexibility on the data that can be saved here. We can add result count to this, but it might not be as straightforward since we log the recent search right after the search is executed and don't wait for results to load (for example, in case user cancels search because it takes a very long time).

There is more info about the new search history here: https://github.com/sourcegraph/sourcegraph/issues/43230#issue-1416571160

**Comment by vdavid** [comment]
@limitedmage Wow, I'm so glad that I asked! 😅

It's awesome that we're moving away from using telemetry data; it should be a lot cleaner that way!

It'd also be lovely if we could add the result counts. I understand that it needs either:
1. postponing saving the recent searches (and taking the risk that the user may cancel the search)
2. OR updating the saved search with the result count once it's done (and handling the case when the result count is missing)

Do you think this is something that you can fit into your current effort?
I'm happy to contribute with this tiny feature in the way of your preference if this request makes things difficult for your team 🙂

**Comment by limitedmage** [comment]
This requires design input for how it would look in the new search history UI. @quinnkeast can you chime in on this?
And yes, I'm hoping if we implement this, we can go with option 2 (updating the saved search).

**Comment by quinnkeast** [comment]
My impression from reading these comments is that there's two very distinct UI spaces here: 

- _Saved searches_, aka searches saved for the explicit purpose of re-running in the future
- _Recent searches_, aka searches that you recently performed but no further

I think it's important to maintain a conceptual boundary between these two concepts, because there'll be assumptions packed into each one that influence what we can do / expect of them. For example, recent searches are implicitly ephemeral and there should be no user expectation set, either implicitly or explicitly, that their recent searches will always be available to them. Instead, if they want to retain a search for the long term, it should be a saved search.

Based on this, my first reaction right now is it makes more sense to include this result count in saved searches, because not only can we "expect" that the saved search will stick around, but we can tie more explicit metadata to it: at the time this was saved or last run, there were `X` results. In the context of recent searches, that same number might instead suggest that _right now_, there are `X` results.

**Comment by vdavid** [comment]
@quinnkeast thanks for the thoughts! Might it make sense to talk to the customer either directly or through @mike-r-mclaughlin and ask them whether adding the result counts to _saved_ searches rather than _recent_ searches sounds like it'd solve their use case?

**Comment by limitedmage** [comment]
Saved searches are pretty hidden in the product so I don't think this would solve the use case.

IMO, having the result count right next to a date in recent searches implies that this was the number of results *at that time*.

**Comment by vdavid** [comment]
Hey @limitedmage and @quinnkeast! Just a friendly inquiry if you've managed to fit this into your search history work.
**Why I'm asking:** This issue is still on my plate. I'm not personally working on it to avoid interfering with your work, but I want to make sure that it's solved.
If you have a roadmap or tracking issue that I can watch, please share, and I'll track the progress on my own. 🙂 And let me know if I can contribute in any way!

**Comment by limitedmage** [comment]
@quinnkeast Can you help out with a quick design for this?

**Comment by limitedmage** [comment]
@vdavid For now, if you want to work on this, you can experiment with adding an additional column to the existing search history:
![image](https://user-images.githubusercontent.com/206864/204348689-ab621211-d631-493c-bfcc-485df5db6b68.png)
