### ISSUE TITLE
insights: investigate high connection usage

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#43498]
It seems we are using a lot of connections from code insights both in the background processes and in the query path. In dev environment this causing long latencies that we suspect is caused by draining the connection pool.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
p0

**Comment by coury-clark** [comment]
from @Joelkw: this may have been a problem for > 1 year based on customer problems

**Comment by chwarwick** [comment]
Overview:

Latency was observed when polling for an insight to backfill. A consistent pattern was a number of fast requests followed by a slow request which directly proceeded the final request when the insights data was now available.  Traces of the slow request did not point to anything specific to insights, but instead it typically started with a a slow sql request to load the users orgs.  Typically taking 300-400ms.  

This does not appear to be related to code insights and I could not make the issue resolve by modifying the number of postgres connections available as I increased the number of available connections to 1000 and the MaxOpenConnections to 500.  I had expected this to resolve the issue however it had no effect.

Exploration:

Things that didn't effect the latency: 

- From the insights side I removed all db work that is done to save the results, so that the results from the searches were just ignored. This had no effect on the long api call.


Things that did effect the latency seen:

- Running searches that resulted in fewer results being returned.  The longest latency is seen with searches that returned the most results.  The initial search used was for `repo:^github\.com/sourcegraph/sourcegraph$ test` which returns approx 51k results.   Searchs that returned < 100 results did not introduce any latency. I did not continue to increase the result size to find a threshold where it became visible.
- Running fewer concurrent searches.  When I lowered the number of concurrent searches from 12 -> 1 the latency disappeared for the same search `repo:^github\.com/sourcegraph/sourcegraph$ test`.  As I increased the number of concurrent searches the latency grew during the request that occurred while the searches were running.


I could only affect the latency by either changing the number of search results returned or the number of simultaneous searches, this leads me to believe there is something in the search path that is consuming db resources that cause other slow queries.  This may be a factor of local development, we should attempt to duplicate this issue when the backfiller v2 is enabled either another environment.
