### ISSUE TITLE
VS Code: Extension breaks VS Code's Account menu in a few ways

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#43608]
@eseliger's report, slightly edited for easier use:

![image](https://user-images.githubusercontent.com/2552265/198675087-18632e0f-8823-4a92-956e-6a88909a3e8c.png)

The issues:
1. The account menu icon always shows a `(1)` badge. It seems to be from our extension, and it's distracting for the user.
2. The all-caps `SOURCEGRAPH_AUTH` looks out of place.
3. When I click the "Sign in" menu item, nothing visible happens (and the `(1)` bubble stays.

Solution proposed by @vdavid:
- Reproduce the issue
- Figure out why the "Sign in" menu item doesn't do anything
- Replace `SOURCEGRAPH_AUTH` with something better-looking (it might come from an external source, try to work with that source or the way we use it, and change this.)
- Make sure the `(1)` badge disappears once the user is signed in.

/cc @sourcegraph/integrations

**Comment by eseliger** [comment]
Correct, the button just doesn't do anything, and I couldn't find the same thing as a command either

**Comment by abeatrix** [comment]
Oops that's my bad. 

The auth api was introduced last update, I totally missed that if you're not signed in you will be getting that notification badge. I removed the auth command on purpose initially since it is obvious that the users can sign in  through the sidebar if they want to, but wasn't aware that it will be used in the vs code user tab (it wasn't mentioned anywhere in their doc 😥)
This should not show up for logged in users though I think.
