### ISSUE TITLE
Pagination - repo: files and directories - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43657]
### Description
Implement pagination for folder view / file view ([example page](https://scaletesting.sgdev.org/ghe.sgdev.org/sourcegraph/DefinitelyTyped-DefinitelyTyped/-/tree/types))

The currently implemented solution does not scale well with a long list of items.

![image](https://user-images.githubusercontent.com/20326070/198968750-728f4272-176e-493b-ab03-5a0949d4daaa.png)

### Plan

- [ ] Engineering spike to determine the limitations (if any) for implementing the pagination component. Some of the questions to answer: can we show the total number of pages, can the user jump to the first or last page, how many pages user can jump forward and back, etc.
- [ ] Update this issue with a design template
- [ ] Adjust pagination component #43535 (delivery date TBD) if needed
- [ ] Determine the milestone when it is delivered

---
Additional resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

/cc @felixfbecker

**Comment by philipp-spiess** [comment]
Linking some context regarding how to proceed with this issues from Slack: https://sourcegraph.slack.com/archives/C03MW9T8G6A/p1668531004016079

**Comment by felixfbecker** [comment]
Related #44627

**Comment by philipp-spiess** [comment]
So I was looking into this and think that this is not a trivial change to make. Here's what I found:

- The tree endpoint has an option to give you all files for a specific path, all files recursively, and a special option to only add recursive options if the current path exist of only one dir (presumably to expand into the deeply nested packages like Java modules more easily where it's common to have `com/sourcegraph/my/super/fancy/folder` 😅 ).
- However the max item length is only enforced for the first two types of pagination. A tree with over 2500 nested folders (lol) would be unpaginated 🙉 .
- On the backend, this is using directory listing functions (_I think_) and we receive the items in an unpaginated slice. This means we could apply the same trick as in #45811 to get an endpoint that is paginated. This is _good_ but there's some overhead that we have to add to the implementation to not increase memory overhead. Not that much of an issue.
- The real problem comes with how the data is currently loaded though: This is not done as a stand-alone GraphQL query in the component where it is rendered but instead it's added to a shared query for the page. This is actually a good thing as it avoids some data waterfalls but it's not possible to easily re-run the query with updated pagination indexes.
- In addition to that complexity, we also have to take into account that the sidebar is also using the same data. So any change is either going to affect both surfaces _or_ we have separate queries which increases the data transfer need and increases inconsistency. 
- On top of all that, we also have the exiting changes from Beyang that rebuilds this page: https://github.com/sourcegraph/sourcegraph/pull/45390

Because of this increased complexity, I suggest that we incorporate the pagination improvements after we have landed #45390 and following a holistic design review that we want to do as part of the [Precise Everywhere UI](https://docs.google.com/document/d/1qlSoZMnwVnBfo1O7573t7cg2zbAJIPnRRjseI7UgtWs/edit) effort. 

We already have a way to communicate large file lists to the user via https://github.com/sourcegraph/sourcegraph/pull/45846 so I don't think this is a blocker for readiness either.
