### ISSUE TITLE
Blob view: Git blame popover interrupts user's hover as their navigate through annotations

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#43690]
In a nutshell the problem here is in git blame panel, steps to reproduce 
- open the blame panel on any file page 
- hover blame line 
- see blame popover with additional info about commit 
- try to hover the annotation above the current hovered line 
- see that instead of this you hover popover instead and not the line you want to hover (popover interrupts user's hover events)

More details on this problem in [this loom](https://www.loom.com/share/add642f6be95468d92cd6ec796975f05) and in the [original slack thread](https://sourcegraph.slack.com/archives/C0HMGV90V/p1666008002882449)

Sidenote from @vovakulikov:

> Also, it's kind of different problem to this but also about blame tooltip/popover is tooltip content. Now it has link (interactive element).  But spec says that a [tooltip](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role#:~:text=Because%20the%20tooltip%20itself%20never%20receives%20focus%20and%20is%20not%20in%20the%20tabbing%20order%2C%20a%20tooltip%20can%20not%20contain%20interactive%20elements%20like%20links%2C%20inputs%2C%20or%20buttons.) (which is a defined term/pattern/component) cannot contain interactive elements like a link, because it pops up on focus or hover, and therefor cannot receive focus or hovers itself (as opposed to a popover).
So maybe we should use tooltip component here with just plain text (since the blame line is itself a link) and tooltip shouldn't have any links inside (edited)

/cc @sourcegraph/integrations

**Comment by vovakulikov** [comment]
Suggestion from the @philipp-spiess (for this issue history): 

> Thanks so much for the video. I feel really stupid now that we have decided to obstruct the other git blame lines with this view, it doesn’t really make sense and it affacted me before as well (I remember that I had to move the mouse outside of the blame panel to get the tooltip to reset).
Cheap fix idea: What if we move the tooltip more to the right  (and obstruct the code instead). This way, you can still see the git blame information of other rows while you’re investigating a blame related question.
Works for GitHub:

<img width="932" alt="screenshot_2022-10-20_at_11 24 37" src="https://user-images.githubusercontent.com/18492575/199046816-e993b2dc-8b22-41e1-81ea-a3f9b212650f.png">

**Comment by jjinnii** [comment]
We originally positioned the blame popover in its current implementation to be more consistent with how popovers are positioned elsewhere in our product. Because we don't have the arrow to anchor the popover like in the GitHub screenshot, we typically position our popovers directly next to the token being hovered over. See below for examples. 

<img width="650" alt="Screen Shot 2022-11-01 at 8 23 18 PM" src="https://user-images.githubusercontent.com/87138876/199222328-1c01ea35-5591-4d0c-92b9-e66a0be218ec.png">

<img width="659" alt="Screen Shot 2022-11-01 at 8 24 11 PM" src="https://user-images.githubusercontent.com/87138876/199222451-b5ad2d1e-195c-4a20-b0ab-6282cdd86cdd.png">

I think it's fine to move the popover in this case to the right as the code intel popover doesn't block the entire rows around it, like the blame popover is covering all of the lines above it. I would though like to ensure that we're anchoring it directly above the blame line, instead of a few pixels above it in its current implementation. I remember that it was something that I provided in design review, but we ended up not having the time to fix before 4.0. See below screenshot: 

<img width="614" alt="Screen Shot 2022-11-01 at 8 29 51 PM" src="https://user-images.githubusercontent.com/87138876/199223303-3acb0612-edac-46cf-907d-9dfd7a7c1284.png">

cc: @philipp-spiess
