### ISSUE TITLE
Automate machine image release processes

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#43697]
automates the release process for [AWS AMIs](https://docs.sourcegraph.com/admin/deploy/machine-images/aws-ami) through our main CI so that when a new Sourcegraph version is released:
- a new sets of AWS AMI will be generated automatically using our [existing packer AWS packer pipeline](https://github.com/sourcegraph/deploy/tree/main/packer/aws)
- all images should be distributed to all supported AWS regions ([example](https://github.com/sourcegraph/deploy/releases/tag/v4.0.1))
- all images should be marked as public with the [`production` and `version` tag](https://github.com/sourcegraph/deploy/blob/main/packer/aws/aws-builder.pkr.hcl#L339-L342)
- creating tags and branches in the sourcegraph/deploy repo that includes a list of image names for each instance size ([example](https://github.com/sourcegraph/deploy/releases/tag/v4.0.1))

We will only need to automate the process for AWS AMIs only, as the [GCP images ](https://github.com/sourcegraph/deploy/tree/main/packer/gcp)and[ images for AWS one click](https://github.com/sourcegraph/deploy/tree/main/packer/aws-latest) will always start on the latest version.

More info: 
- [Overview of our AMIs](https://docs.sourcegraph.com/admin/deploy/machine-images)
- Docs on our [current image-creation setup](https://github.com/sourcegraph/deploy/blob/main/doc/development.md#development)
- instructions on building and releasing the [AWS AMIs](https://github.com/sourcegraph/deploy/blob/main/doc/development.md#aws-1)
- Our release CLI: https://github.com/sourcegraph/sourcegraph/blob/main/dev/release/src/release.ts#L276
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61114
```

**Comment by DaedalusG** [comment]
There are a few issues with the way we are building AMIs at the moment that need to be addressed in order to properly automate releases:
1. **InsufficientInstanceCapacity** -- currently if a region is in use for testing or has any other EC2 instance running the `packer build` may fail due to insufficient capacity allocated to our account for release
2. **build_in_region** packer variable won't work if the region has no subnet configured.  A good approach to the InsufficientInstanceCapacity issue is to do fail over attempts to build an EC2 machine in other regions. This won't work without more subnet configuration
3. **migrate from sandbox env** -- builds should target our general Sourcegraph aws account rather than our sandbox environment (see [internal comment](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1674339670599089))

**Comment by jdpleiness** [comment]
```[tasklist]
### Tasks
- [ ] Machine images use the new release process [#61114](https://github.com/sourcegraph/sourcegraph/issues/61114)
```

**Comment by Chickensoupwithrice** [comment]
Finally completed this with https://github.com/sourcegraph/deploy/pull/78!! 

Uses bazel to call Packer, on Buildkite, which generates a changelog of the new AMI hashes, and creates a GitHub PR. 
It really should've been like 4 different PRs in hindsight... But hey, it's a complete solution?
