### ISSUE TITLE
dotcom: investigate slow frontend rollout

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#43873]
Frontend has been very slow to roll out for a while ([example](https://buildkite.com/sourcegraph/deploy-sourcegraph-cloud/builds/239936#01843dcf-7047-4912-8665-8bc9b7da2892)). This causes CI to fail but eventually the rollout does reach a completed state.

**Comment by sanderginn** [comment]
Intermittent patch is an increased progress deadline:
- https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17417

**Comment by jhchabran** [comment]
TODO @sanderginn check if that's still the case?

**Comment by sanderginn** [comment]
I spent some time looking for any obvious signs of slow rollout but can't really find any, and the increased timeout has prevented this from being an issue since, so I don't consider it worthwhile spending more time on this.

**Comment by sanderginn** [comment]
Reopening this issue as it is [popping up every day](https://buildkite.com/sourcegraph/deploy-sourcegraph-cloud/builds/265707#01875a57-268d-41dd-8378-8d3cc2e8473b) again.

**Comment by mucles** [comment]
updated: no root cause for slow frontend rollouts but there hasn't been a build reported as failed due to a slow rollout since ([BK Bulid](https://buildkite.com/sourcegraph/deploy-sourcegraph-cloud/builds/275790#0188933b-d95b-42e3-a5dc-fde05ab74dd5)  - June 6th)

one possible bandaid if this fails to start popping up again would be to increase the `progressDeadlineSeconds`
[sg search](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fdeploy-sourcegraph-cloud%24+progressDeadlineSeconds&patternType=standard&sm=1&groupBy=path)
