### ISSUE TITLE
Email users who synced private repos re: Cloud Trial

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43911]
Lots of users synced private repos to .com when we supported it, and they may be interested in signing up for a Cloud trial. (After all, they already understand the value prop of using Sourcegraph on private code). Let's  try it out, and if it's working, we can follow up with emails to frequent users who may not have added private code, but use Sourcegraph a lot. 

WIP [email](https://docs.google.com/document/d/1oumPCoqWI6ki6Gdtf3fxyBP5YiYvlhvFoKFRgc-LMB4/edit) is here and list of recipients in [HubSpot](https://app.hubspot.com/contacts/2762526/lists/2536). 

We'll wait to send this out until the new signup flow from Growth Product is in place on Wednesday, November 16.

The SDR team is [running](https://sourcegraph.slack.com/archives/C03B4EMBXL4/p1666800135113299?thread_ts=1666731392.454919&cid=C03B4EMBXL4) a separate campaign targeting the cloud beta waitlist.

**Comment by taylorsperry** [comment]
@kelsey-brown This only went out to 26 people, so not expecting major traction, but let's see if we get a little bump in activity/signups.

**Comment by kelsey-brown** [comment]
Did some digging trying to see if we saw any signups from your email and couldn’t find any definitively (basically just looked for signups since thursday that were referred by an email application)

I did notice a spike in traffic to the blog post you linked in the email, though. Interestingly it looks like the traffic was referred from hacker news, which is confusing because that blog post wasn’t posted on hacker news as far as I can tell. Maybe the email had something to do with it? 

I'm going to move this out of measuring for now.
