### ISSUE TITLE
3.3.8 regression: corsOrigin * no longer allowed

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4424]
Setting `"corsOrigin": "*"` no longer works in 3.3.8+, Sourcegraph does not respond with the proper `Access-Control-Allow-Origin` header in OPTIONS request responses.

This appears to only affect non-browser extension requests, since those originate from a known origin, which explains why we did not catch this. A customer is relying on the behavior of this outside of a browser extension scope, though, to more generally configure CORS responses from Sourcegraph which seems very reasonable to support in an API context.

This regression appears to have occurred in https://github.com/sourcegraph/sourcegraph/commit/34caedf364b18559ce62f7cba036d6cd890de179#diff-16c810a296953d51a6e43ae5f7d5fd74L138 because `isAllowedOrigin` fails whereas before we set the header regardless:

https://github.com/sourcegraph/sourcegraph/blob/87932e2986a4d758199726acf1b9b6deb1962396/cmd/frontend/internal/cli/http.go#L147

To fix, we should update this function to support `*` properly or revert the relevant part of the bad commit:

https://github.com/sourcegraph/sourcegraph/blob/87932e2986a4d758199726acf1b9b6deb1962396/cmd/frontend/internal/cli/serve_cmd.go#L274-L281

407948923

**Comment by chrismwendt** [comment]
> A customer is relying on the behavior of this outside of a browser extension scope, though, to more generally configure CORS responses from Sourcegraph which seems very reasonable to support in an API context.

Are you referring to some kind of a proxy that the customer has set up in front of Sourcegraph? Can we get more details about their setup? What are their requirements for Sourcegraph's CORS behavior?

The current behavior is:

- Read the `Origin` header value from the request
- Check it against `corsOrigin` from site configuration (space-separated whilelist of origins)
- Write it into the `Access-Control-Allow-Origin` header in the response

Depending on what the customer needs, here's a straightforward addition to our current logic that might work for them: use wildcard matching instead of equality when consulting the whitelist. That's as easy as changing the `==` on line 276 to a glob match.

https://github.com/sourcegraph/sourcegraph/blob/87932e2986a4d758199726acf1b9b6deb1962396/cmd/frontend/internal/cli/serve_cmd.go#L274-L281

With that change, `"corsOrigin": "*"` would whitelist all origins.

However, if the customer needs Sourcegraph to respond with `Access-Control-Allow-Origin: *` (`*` is one of the [valid values](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Directives)), then we'll need to take some other approach.

**Comment by slimsag** [comment]
@chrismwendt I sent #4785 for this just now, please review once you have a chance. I've detailed in that PR what the prior, current, and expected behavior is.

Note that, as far as I can tell, responding with `Access-Control-Allow-Origin: *` when an `Origin: https://www.google.com` request is made would just make any CORS-respecting client reject the request. Regardless, I don't think the behavior there matters as long as we are handling wildcards faithfully (we respond with a header matching the `Origin` header)
