### ISSUE TITLE
CI: investigate why test namespace doesn't get deleted

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#44618]
We have an issue where this [e2e test](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/ci/integration/cluster/test.sh?L12:19) doesn't get deleted properly and holds up nodes. Need to investigate why this fails and see how we can clean it up so that we don't waste resources. 

old namespaces shown in K9s
![Image](https://user-images.githubusercontent.com/51868853/202784515-e49cc0b9-4f1a-4e0c-a942-ec9ea602ba6e.png)

**Comment by davejrt** [comment]
on occasion I've seen this fail due to 
`Terminated with signal SIGKILL (from the agent because the job was canceled). Exit status -1` 

We can't trap on SIGKILL so this is potentially always a risk. 

If we aren't ever seeing the [trap](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/ci/integration/cluster/test.sh?L52:3&subtree=true) get executed then we may need to `set -x` in some other parts of the script to debug this further.
