### ISSUE TITLE
De-jank the hover

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#44623]
There is a lot of accumulated janky behavior everyone has experienced with our hover popup. We need to polish that experience up.

_To be converted into a tracking issue with individual problems_

/cc @felixfbecker

**Comment by philipp-spiess** [comment]
With selection-driven navigation, we also rewrote part of the hover logic including the part that caused for the janky loading screens and re-renders. I recommend that we focus our efforts on bringing this over the finish line by fixing the remaining accessibility issues instead of fixing the older hover logic.

**Comment by fkling** [comment]
If we encounter concrete problems with the popover we should create new issues for them.
