### ISSUE TITLE
FE scale audit: loading big files in search results list bogs down the browser - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#44666]
### Description
According to feedback from one of our [customers](https://github.com/sourcegraph/accounts/issues/6716) ([slack thread](https://sourcegraph.slack.com/archives/C01P4R0RZH9/p1668701456260109) for more context) the large files bog down the browser while doing syntax highlighting and rendering.

### Plan

- [ ] Research the described behavior (so far @philipp-spiess hasn't tested with files that big for the FE scale audit yet)
- [ ] Understand if using codemirror will solve the problem
- [ ] If not, explore potential UI solutions (ex. the download button suggested by the customer) - potential design input needed

**Comment by philipp-spiess** [comment]
The experience for large files is going to be _much much_ improved with the rollout of CodeMirror. I know that the customer in question will be getting CodeMirror soonish, so let's wait to hear the feedback.

There are, of course, additional improvements that we can do. We recently shipped #44199 which allows the streaming of git blame related data. We should do the same with text files! We can stream from the first lines and start rendering as soon as we have enough data to fill the view. This will require additional UI indicators though to convey the state. I do think this is a bit out-of-scope for the scale-readiness data.

What we can (and should) do for now is to improve the loading state for CodeMirror (the other implementation will hopefully not stick around for too long). This is what we currently show:

<img width="854" alt="Screenshot 2022-11-28 at 14 34 23" src="https://user-images.githubusercontent.com/458591/204290934-dda2d1eb-0229-4ffb-90eb-04a2be302eb0.png">

A few ideas:

- Add some text if loading takes over xxx ms or when a large file is shown that explains why it takes so long
- Show a progress indicator (@philipp-spiess to figure out how we could do this technically) including how many kb have been downloaded already?
- Add support for streaming the content

cc @AlicjaSuska

**Comment by philipp-spiess** [comment]
I still think that streaming the blob content would be super helpful here though but the change would require a lot of changes on the backend. We've recently done something similar with git blame (https://github.com/sourcegraph/sourcegraph/pull/44199) and I think we should at least wait and get some feedback on that implementation first before considering this. We'd also need a strong champion for the backend to make this change. I think this change is out of scope for the effort of the front-end scale testing audit.

---

There are still two reasonable next steps, though:

- [ ] Enable CodeMirror for everyone. This is something that the Code Exploration team is actively working on (unrelated to the front-end scale testing efforts). Code Mirror is much faster at rendering the file ones it's downloaded as it doesn't need to render all potential thousand lines of code but instead can render only the visible part. This is being championed by @taras-yemets at the moment.
- [ ] Improving the status quo of loading indicators and maybe set a timeout after a second or so that explains that the viewer is downloading a large file. This would need design work as a next step, cc @AlicjaSuska

**Comment by taras-yemets** [comment]
@philipp-spiess, I like the idea with blob streaming (though I'm not sure about the implementation effort). We can get back to it after we enable the CodeMirror blob view by default and audit the large files performance again.

**Comment by AlicjaSuska** [comment]
@philipp-spiess given the @taras-yemets comment - is this issue on hold now until we have the codemirror implemented or, in the meantime, we still need the design for:

> Improving the status quo of loading indicators and maybe set a timeout after a second or so that explains that the viewer is downloading a large file. This would need design work as a next step

**Comment by philipp-spiess** [comment]
@AlicjaSuska I think it still makes sense to see if there's some quick fix that we can do design wise to make it clearer to the user what's going on. What do you think?

**Comment by AlicjaSuska** [comment]
Sure, I'll get back to you when I have the design ready. Thank you!

*I'm working in this [file](https://www.figma.com/file/5CgqjaXqrRhquTG6GB3YGd/Basic-Project-Template-(Copy)?node-id=275%3A1628&t=TaPSg9bCLwiM1A1N-4)

**Comment by AlicjaSuska** [comment]
Update: @philipp-spiess please see this loading [sequence](https://www.figma.com/file/5CgqjaXqrRhquTG6GB3YGd/FE-scale-audit%3A-loading-big-files-in-search-results-list-bogs-down-the-browser-%2344666-WIP?node-id=275%3A1628&t=TaPSg9bCLwiM1A1N-4) (already reviewed by @quinnkeast)

**Comment by philipp-spiess** [comment]
@AlicjaSuska Nice! Yeah this looks good 🙂
