### ISSUE TITLE
Background of setup instructions should not be animated

### ISSUE THREAD

**Issue by rmccue** [sourcegraph/sourcegraph#448]
- **Sourcegraph version:** 2.12.0
- **Platform information:** Firefox 63b

#### Steps to reproduce:

1. Start new Sourcegraph installation
2. Open in browser
3. Set up initial user and log in

#### Expected behavior:

Setup instructions in banner should not have constant animation.

#### Actual behavior:

Instructions have very distracting background animation which looks like a loader, but isn't.

**Comment by francisschmaltz** [comment]
@rmccue what banner are you referring to?

**Comment by dadlerj** [comment]
@francisschmaltz I assume the green bar: 
![image](https://user-images.githubusercontent.com/5589410/47232368-57fad400-d384-11e8-937f-3f6318dee02a.png)

It was intentional to make this highly visible — otherwise, we find that new users don't know what to do next! Would it be better if it was dismissable, or if it automatically disappeared once the admin clicked on it (even if they chose NOT to add repositories)?

**Comment by francisschmaltz** [comment]
There is a problem with the animation of the bar – but I like that we make it super visible. I think that we should make the bar dismissible too.

Currently, the bar stays until you add a repo source – adding public repos does not dismiss this and I find that a problem.

**Comment by sqs** [comment]
It is dismissible on master now (I changed that a few days ago)

**Comment by rmccue** [comment]
The bar itself is fine (and useful), it's just the constant animation that's an issue. It's very distracting while you're trying to actually do the thing it's telling you, and somewhat headache inducing tbh.

**Comment by sqs** [comment]
@rmccue 	In the next release it will be dismissible. I believe that addresses the distraction and headache issue, because you can now dismiss it. The animation has been helpful in making users NOT miss it (you'd be surprised at what the brain/eye can tune out), so removing it is something we'd want to be a bit more careful about.

Closing this issue as the immediate pain appears to be addressed. @francisschmaltz, you can change this however you want.
