### ISSUE TITLE
Too many Sourcegraph extensions wreck GitHub toolbar UI

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4480]
https://github.com/sourcegraph/sourcegraph/blob/master/browser/src/libs/github/file_info.ts#L22

<img width="1375" alt="Screen Shot 2019-06-12 at 3 28 05 PM" src="https://user-images.githubusercontent.com/133014/59390760-1067f480-8d27-11e9-8913-8a878811932e.png">

I would break this issue into two parts:

1) What can we do to the extensions to make them take up less space?
  - Change the button text of the `code-ownership` extension to be a GitHub icon and the word `Owners` and the owners are displayed on hover in the tooltip.
  - Change the Sentry button to be the logo
  - Change the Codecov button to be the logo

2) Adjust styling to accommodate for button overflow.

**Comment by christinaforney** [comment]
> * Sentry: Do we really need a button for this? Could command palette suffice? If not, lets only make it an icon.

It is now just an icon (see screenshot below). I'd like to have a general command palette discussion in the near future to get me up to speed on intention, vision, limitations, etc.

> * CodeCov: Could we make it only show the percentage, and use the CodeCov logo? ☂️

I like this - let's do it.

> * Code Owners: This one is a big offender. No good ideas here, but also, it is not really a button, just a display. Imo this information should not be contributed through a button in the toolbar but somewhere else.

+1 to this being somewhere else. Strawman: what if instead of being a "button" it is just text right aligned to right edge below the other buttons and makes the header "thicker"?

PR:
![image](https://user-images.githubusercontent.com/1559622/59543602-e64a3a00-8ec0-11e9-92b8-4e9559005c8d.png)

File view:
![image](https://user-images.githubusercontent.com/1559622/59543626-02e67200-8ec1-11e9-99e2-0a46754a9ad3.png)

**Comment by lguychard** [comment]
Tentatively prioritizing for 3.15 cc @christinaforney @imtommyroberts
