### ISSUE TITLE
Letter-based symbol icons

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#45076]
The symbol icons used in the search results are different from the ones used in the symbols sidebar in the blob page. We need to pick one style and apply it everywhere.

Search results users "initial letter" icons:
![image](https://user-images.githubusercontent.com/206864/205357500-5db63033-5fce-47a1-b57f-e244620f1e4c.png)

Symbols sidebar uses "glyph" icons: 
![image](https://user-images.githubusercontent.com/206864/205357565-fa8197bb-2f4d-40e2-acb1-a8ed4b8c2d7d.png)

/cc @felixfbecker

**Comment by felixfbecker** [comment]
I don't know the context of why the new letters were picked for the search redesign, but I personally prefer the icons much more and I've heard the same from others.
The issues I have are:

- There are ambiguous initials, for example "F" can be both "function" and "field", "C" is "constructor" and "constant", "P" can be both "property" and "package" (or maybe even "parameter"). The icons make the distinction pretty clear, with e.g. a function being the mathematical **𝑓** and fields being a box holding a value. With letters I always have to think twice about whether there could be a double meaning.
- While the clarity of some icons can be debated, for some they are definitely clearer. E.g. the 📦 instead of "P". The icons were generally all picked in a way that would match the semantic, e.g. interfaces being a 🔗  link (between components), class showing a hierarchy (inheritance being a defining feature of classes), properties are 🔧 wrenches because they tweak the object, enums being 🔢 numbers, constants are a π in a box because π is a well-known constant,  ...
- The photographic icons were heavily inspired by VS Code both in iconography and color (e.g. methods, fields, properties, variables, classes).
- The colors were intentionally grouped to group similar symbols. A lot of thought had gone into it that we shouldn't just discard and replace with randomness. For example:
  - Functions and methods are both purple as callables.
  - Variables and fields are both blue as they hold a value.
  - Constants are a darker blue because they hold a value but can't be changed.
  - Structs and classes are both orange, as they are similar concepts.
  - Packages are yellow because they are the bundle for classes in many languages and also because yellow is close to cardboard color, which helps make the package icon recognizable.
- In terms of usefulness, I actually think the initials are not really useful in the search results because the declaration is right next to it. I.e. it will say "F" then is directly followed by the highlighted keyword `function`, or "P" is directly followed by `package`. At that point, an icon would be more useful for visual recognition because the letter is just repeating the initial from the word next to it.

**Comment by felixfbecker** [comment]
(renaming this to letter-based symbol icons to distinguish "making it consistent" from "changing to letter-based")

**Comment by limitedmage** [comment]
I personally agree with preferring the glyph icons. @almeidapaulooliveira or @novoselrok , do you have more info about why the letter icons were chosen?

**Comment by fkling** [comment]
Symbol representation seems to be consistent now. Which representation to use is configurable by the user. We'll continue to explore improvements as needed.
