### ISSUE TITLE
Batch Changes stat bar shows incorrect data for organizations

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#45075]
The batch changes stat bar is meant to display batch changes usage applicable to the user or organization. Right now, we display the global list, which is incorrect for non-site administrators since they don't have visibility into all Batch Changes.

This was particularly confusing for me when I creating a new organization and I noticed that the stats bar was showing 8 batch changes instead of zero.

[Context](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1670001603822349)

**Comment by courier-new** [comment]
Does this require backend changes? I don't think the resolver currently supports computing these stats in a specific namespace, so we'll probably need to build that out first. 

Tbh since the bar is mostly about communicating total product value anyway, does it make sense for now to just hide the stats bar on the user/org namespace batch change list pages, so that it's only visible on the global one?

Then later on when we have INSANE MAUs/better traction with orgs and want to show users how much time their individual batch changes have saved, we could prioritize getting these stats on namespace lists, too? 🙂

**Comment by chrispine** [comment]
at the least, let's remove it from this page
