### ISSUE TITLE
Why not use ElasticSearch for a full repo search?

### ISSUE THREAD

**Issue by xingx-xx** [sourcegraph/sourcegraph#4510]
Max repo number is limited for global scale search, why not use search engines such as elasticsearch instead of zoekt for a potential performance improve?

It will be great if there are some comparisons between popular serarch engines and why sourcegraph finally chooses zoekt.

**Comment by slimsag** [comment]
Sourcegraph does support searching over quite a large number of repositories (15-30k depending on various factors including repo size etc) and from what little I know of ES is pretty comparable performance-wise.

Would I be correct in guessing that you tried the Docker container and ran into this message?

> Search performance and accuracy are limited on single-node Docker deployments. We recommend that instances with 100+ repositories deploy to a cluster for optimal performance. Contact us for support or to learn more.

This warning exists primarily because Docker container deployments are rather small usually and once you get past 100 repositories you will want to scale out to more than one machine in general. Note that Sourcegraph isn't just text search, it also has diff and commit message search, symbol search, etc. as well as other things like hovers, jump to definition, etc. that all need to scale out. https://docs.sourcegraph.com/user/search#features

With that being said, we are aware of some single-container Docker deployments going up to around 3k or so repositories with high usage regularly on some beefier server hardware. You could use the workaround here to disable that warning:

https://github.com/sourcegraph/sourcegraph/issues/3538#issuecomment-485894380

> It will be great if there are some comparisons between popular serarch engines and why sourcegraph finally chooses zoekt.

While it doesn't completely match what you want here, the following doc has some information that is somewhat relevant and may interest you: https://docs.sourcegraph.com/adopt/comp

Does this help?
