### ISSUE TITLE
Spike: How do we determine permissions in ADO

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#46269]
Figure out what ADO APIs/steps are required to do:
1) Repository Permissions
2) User Permissions

The result of this spike should a doc that outlines which ADO APIs we will be using (and how) in order to implement permissions syncing.

/cc @ryphil

**Comment by indradhanush** [comment]
# Azure DevOps Permissions Scoping

The APIs to be used and how is documented in a [Postman workspace](https://warped-sunset-576604.postman.co/workspace/New-Team-Workspace~c07d4abf-e2d0-4dcc-afb6-14a8d7d59ffc/request/25434968-1de9d97b-9714-43e9-81cf-7a419aa50a26) to which @varsanojidan and I already have access. The free tier of Postman allows for 3 collaborators at the moment. I found it to be a better solution than listing the API usage in plaintext. Get in touch with me if anyone wants an invite. For now here's a screenshot as a sneak-peek:

<img width="2550" alt="image" src="https://user-images.githubusercontent.com/2682729/214048249-ea024a5b-3591-4652-8649-53ac568fcf3f.png">


The workflow to get permissions is:

1. Specify the resource (project or repo)
2. Make an API request to enqueue a report creation job
3. Query the API for status of enqueued job
4. If job is completed then use the download link (from the response in step 2) to get a JSON file which has everything

## Workflow

1. List all org projects (already implemented)
2. For each org project
	1. Enqueue a permissions report request
	2. List all repositories (already implemented)
3. For each repository
	1. Enqueue a permissions report request

### Permissions report

1. Enqueuing a permissions report returns an API response with the report ID and a download link
2. In the tests the report always generated immediately but I'd imagine for larger instances this might take some time
3. Use the API call to get the status of the permissions report
4. Download the report using the download link if the status is `completedSuccessfully`
5. The report itself is a json file

#### Project permissions report

The JSON structure looks like:
```json
[
  // Includes an entry for every acccount, both user and system.
  // For user accounts, the `AccountName` is the email ID associated on ADO. We can use SG email to correlate with users in the report.
  {
    "Descriptor": "redacted",
    "Id": "redacted",
    "AccountName": "redacted",
    "DisplayName": "Project Collection Build Service (redacted ID)",
    "Resource": {
      "ResourceType": "projectGit",
      "ResourceId": "redacted",
      "ResourceName": null
    },
    "Permissions": [
      {
        "PermissionName": "Bypass policies when completing pull requests",
        "EffectivePermission": "NotSet"
      },
      ... 
      // THIS IS WHAT WE WANT, IGNORE THE REST
      {
        "PermissionName": "Read",
        "EffectivePermission": "AllowedBySystem"
      },
      ...
```


### Repo permissions report

JSON structure is similar to the above, the `Resource.ResourceType`  indicates this is for `repo`.
```json
[
  {
    "Descriptor": "redacted",
    "Id": "redacted",
    "AccountName": "redacted",
    "DisplayName": "Project Collection Build Service (redacted ID)",
    "Resource": {
      "ResourceType": "repo",
      "ResourceId": "repo",
      "ResourceName": null
    },
    "Permissions": [
      {
        "PermissionName": "Bypass policies when completing pull requests",
        "EffectivePermission": "NotSet"
      },
      ...
      // THIS IS WHAT WE REALLY WANT AND IGNORE THE REST
      {
        "PermissionName": "Read",
        "EffectivePermission": "AllowedBySystem"
      },
      ....
  },
  {
    .... and so on for another account
  }
```

### Caveats

1. No way to specify multiple resources in the same request, trying this returns an error: `Permissions report request should contain one Resource of type 'Repo', 'Ref', 'Release', 'Tfvc' or 'ProjectGit'.` even though the documentation suggests [otherwise](https://learn.microsoft.com/en-us/rest/api/azure/devops/permissionsreport/permissions-report/create?view=azure-devops-rest-7.0#permissionsreportrequest).
2. No way to get a permission report of a specific user: It is either a project or a repo only (other resources like `ref`, `release` are supported but it is not relevant for our use case)
3. A permissions report enqueue sends an email to the account holder of the API token used when the report is ready. To prevent spam we must urge site admins to use a different account for the API token.

**Comment by pjlast** [comment]
@varsanojidan yeah I'm available to talk any time, as soon as you want
