### ISSUE TITLE
Avoid duplicate permissions sync jobs to be triggered

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#46321]
Right now, the `schedule` in the prototype branch will enqueue jobs every X seconds, ignoring whether there is already a job enqueued or not.

That needs to be changed to avoid duplicates, where duplicate means: a job with the same `high_priority`, `process_after`, `user_id`/`repo_id` and options fields.

That means we shouldn't allow 2 high-priority jobs, but 1 high-priority and 1 low-priority/process-after job.

**Comment by sashaostrikov** [comment]
After discussion with @thenamankumar and @pjlast it has been decided that:

### Database constraint...

alone is not enough as we want to have a bit more complicated deduplication logic.

However, `permission_sync_jobs` table will have a unique constraint for `high_priority`, `user_id`, `repo_id`, `cancel` and `process_after` (to deduplicate two immediate jobs, i.e. `process_after IS NULL`) columns with a condition of `status == 'QUEUED'` in order to let the table have multiple processing/finished/etc jobs per each user/repo with same priority. 

This index will be used as a last resort if the logic described below will fail to "catch" the duplicate.

### Main deduplication logic...

consists of a check for existing _QUEUED_ job for a given user/repo ID considering that this is an urgent/not postponed sync (`process_after == nil`).

If existing job is high priority -- then new job is just dropped.
If existing job is a low priority -- then in case of adding high priority job, an old one is canceled (`cancel` is set to `true`) and new one is added. In case of adding another low priority job, it is just dropped. 

We shouldn't deduplicate sync jobs with not null `process_after` as we want all of them to be processed in order not to miss any webhook event changes.
