### ISSUE TITLE
High memory usage in 3.3

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4643]
Customer reports high memory usage in 3.3 from the `symbols` service.

Original Slack thread: https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1561139183006900

Customer was running Sourcegraph in single Docker image configuration on an EC2 instance. Alert tripped that showed Sourcegraph was taking 95% of the EC2 instance memory (70 GB total). Investigation via `htop` showed that `symbols` was using up most of the memory. No reported end-user impact (end-user impact was not checked before container was restarted).

This might be benign, but it might also relate to the earlier discussion about imposing stricter resource limits in the single Docker image configuration (either by Docker resource limits https://docs.docker.com/config/containers/resource_constraints/ or `nice`).

Reported by:
* https://app.hubspot.com/contacts/2762526/company/561806411
* Potentially https://app.hubspot.com/contacts/2762526/company/693777177

**Comment by dadlerj** [comment]
Potentially the same issue seen by another customer at https://sourcegraph.slack.com/archives/CFNURMWHE/p1560803915041100?thread_ts=1558638953.005800&cid=CFNURMWHE

**Comment by slimsag** [comment]
The ctags version was changed in 3.3.0: https://github.com/sourcegraph/sourcegraph/commit/313f704f68b6bf77bd417e6f9ce8fa186efb53ca#diff-c70a9dc6c04d3417268ee413da46b0b3

**Comment by slimsag** [comment]
didn't see any other questionable changes

**Comment by slimsag** [comment]
See related issue: https://github.com/sourcegraph/sourcegraph/issues/3534

There are a few possibilities here:

1. Symbols is simply allocating a lot of memory on large repositories and repositories with lots of symbols (particularly I suspect when doing lookups across many repositories -- which is what basic code intel does when performing a jump-to-definition or find-references).
2. There is memory leak in our usage of sqlite (this is unlikely because we would also be observing this in other deployments).

If we assume that it is the first possibility above, which I think is reasonable, then I believe once https://github.com/sourcegraph/sourcegraph/issues/3534 is fixed we would observe:

- More resource usage from Zoekt (but I suspect far less than symbols consumes today, due much less results being loaded in memory).
- Near-zero usage from symbols service (because it'd only be used in non-HEAD branches, effectively).

My suggestion to customers facing this today:

- Increase symbol service (or sourcegraph/server) memory resources until it no longer falls over.
- Wait for us to fix https://github.com/sourcegraph/sourcegraph/issues/3534 which should be a substantial improvement or, at the very least, would give us a more definitive answer on expected resource utilization here.

**Comment by slimsag** [comment]
The change I made in https://github.com/sourcegraph/sourcegraph/issues/3792 just now will help reduce memory consumption of Zoekt in Sourcegraph 3.7.

**Comment by beyang** [comment]
Closing this for now. Can re-open if the issue re-occurs.
