### ISSUE TITLE
batches: decrease retry count and restrict retries by status code

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#46696]
We currently retry one changeset up to 60 times when recreating, with a 5 second break in between the tries. Such a large number is not quite necessary and can be a little distracting. 

We should reduce the retry count and also slightly increase the 5 second retry pause. Additionally, we should restrict reties for certain status codes that we know wont improve with retries, like 403

**Comment by courier-new** [comment]
Updating the max retries and delay sounds trivial, but how much should we slow it by? Maybe just 10 retries, with 10 seconds between each?

In terms of restricting retries on certain status codes, I believe since changeset processing is a dbworker we'd need to somehow mark them as `failed` rather than `errored` in order to stop the automatic requeueing and processing, while still writing the `FailureMessage`. I'm not sure exactly how to do that but I wouldn't put it at more than 1d to figure it out.

**Comment by BolajiOlajide** [comment]
I propose we use exponential backoff here while limiting the retry time. This way we can also avoid quickly reaching rate limits set on the user's token.

Depending on what approach we take I say 1-2d

**Comment by courier-new** [comment]
That's a great idea! However, I don't think dbworker supports a dynamic `RetryAfter` time presently so we'd need to implement something generic for that first.

I haven't touched worker internals before so I'd maybe up my personal estimate to 2-3d due to that unfamiliarity.

**Comment by courier-new** [comment]
For now let's just dial back the retires to 10 with 10 second delays. We can mark the error as non-retryable if the status is one that we know shouldn't be retried. This should likely be anything in the 400 status range but let's think about that a little before committing.
