### ISSUE TITLE
f:has.owner does not correctly respect count:X

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#47280]

**Comment by cbart** [comment]
It looks like `f:has.owner` doesn’t correctly respect `count:X`, when I do a regular search for `f:has.owner` I get 0 results and the warning that a result limit has been hit. Adding `count:all` returns results as expected

-- from slack,

@eseliger could you further comment what's the expected behavior? I have not used count:X before.

**Comment by eseliger** [comment]
`count:X` is supposed to limit the number of returned results (that's my understanding of it at least), so when I say count:50 and there are 500 results total, I expect to get exactly 50 results back. When there's only 49 total, I get 49.
What I've seen with ownership search though is that we have `count:500` and it returns nothing and then `count:10000` returns 100 results, for example. I'm assuming that is because the count is applied before the filter runs, and the filter operates over 500 results then, not until it had seen 500 matches.
