### ISSUE TITLE
Dynamic filter to exclude forks does not exist

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4758]
1. Run a search query that turns up a lot of forks.
2. See the following dynamic search filters:

![image](https://user-images.githubusercontent.com/3173176/60471680-a0100d00-9c1a-11e9-81e9-147a412ec15b.png)

3. Expect that a search filter `fork:no` appears to exclude forks.

Workaround: Add a global search scope `Exclude forks`

Related to and reported by same user as in https://github.com/sourcegraph/sourcegraph/issues/4757

**Comment by keegancsmith** [comment]
@sourcegraph/core-services interestingly adding this feature would imply we would need to load/hydrate the fork column.

**Comment by slimsag** [comment]
@keegancsmith can you clarify? We already have `fork:no` and users regularly make use of it

**Comment by mrnugget** [comment]
> @keegancsmith can you clarify? We already have `fork:no` and users regularly make use of it

IIRC that is directly translated into a `WHERE` clause when loading the repos from the DB. But the `Fork` column is actually never scanned from the loaded rows. And in order to dynamically display the search filter, I guess we would need to determine whether the repos in the results contain forks or not, right?

That would mean we would need to load the `Fork` column. And with #4749 (merged today) we introduced "lazy loading" for non-essential fields on repos, like `Description` and `URI`, to save memory and row-scanning time. If we decide to add `Fork`, we'd need to do the same thing. But then, if we always want to check whether to display the filter or not, it doesn't make sense to lazily load it.

**Comment by rvantonder** [comment]
Closing because forks are excluded by default, we shouldn't be surfacing a dynamic filter to exclude them.
