### ISSUE TITLE
`Find References` on non-code type files results in frontend crashing

### ISSUE THREAD

**Issue by danieldides** [sourcegraph/sourcegraph#47619]
- **Sourcegraph version:** 4.4.1+ (`198623_2023-02-14_3ccc6dd31f83`)

#### Steps to reproduce:

1. Open a text-based file (markdown, .tpl)
2. Hover a word and click "Find references"
    
![Screenshot 2023-02-14 at 11 42 06](https://user-images.githubusercontent.com/8784265/218815764-cd15e847-3e45-43e5-8bb1-46db67fdbdf4.png)

Links that break (reproducible on `sourcegraph.com` and `sourcegraph.sourcegraph.com`:
- https://sourcegraph.sourcegraph.com/github.com/sourcegraph/terraform-google-executors/-/blob/modules/executors/README.md?L8:40-8:46#tab=references
- https://sourcegraph.sourcegraph.com/github.com/sourcegraph/terraform-google-executors/-/blob/modules/executors/startup-script.sh.tpl?L17:10-17:41#tab=references

#### Expected behavior:
Search to find all references of the string or button to be disabled.

#### Actual behavior:
Error page. The site needs to be reloaded.
![Screenshot 2023-02-14 at 11 39 34](https://user-images.githubusercontent.com/8784265/218815148-3d5631b3-ded3-4714-b8f2-2fbf24206d71.png)

/cc @felixfbecker

**Comment by taras-yemets** [comment]
@fkling on [Slack](https://sourcegraph.slack.com/archives/C04931KQVRC/p1676450283416159):
> I think this is a two-part problem:
>- The error should never propagate to the user…
>- Popovers shouldn’t be shown in markdown files (or at least not for every word. I think we had that problem before but I forgot the details about it.

**Comment by taras-yemets** [comment]
Some implementation details:
1. Hover tooltips are managed by [`hoverManager`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ff466c55b67a09c03769a0e56a9677a99943850b/-/blob/client/web/src/repo/blob/codemirror/token-selection/code-intel-tooltips.ts?L213-389&subtree=true): we take [occurrence at position](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ff466c55b67a09c03769a0e56a9677a99943850b/-/blob/client/web/src/repo/blob/codemirror/token-selection/code-intel-tooltips.ts?L327&subtree=true) and provide hover info for it. 
2. If there is no occurrence at the position in syntax highlighting data, we create a new `Occurrence` instance interactive by default (see [`occurrenceAtPosition`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ff466c55b67a09c03769a0e56a9677a99943850b/-/blob/client/web/src/repo/blob/codemirror/occurrence-utils.ts?L61-70)). 
3. We can't focus on created occurrences with the keyboard (keyboard navigation relies on [`closestOccurrenceByCharacter`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ff466c55b67a09c03769a0e56a9677a99943850b/-/blob/client/web/src/repo/blob/codemirror/occurrence-utils.ts?L123:17-123:45#tab=references) method which uses only syntax highlight data). But we can hover over such occurrences (see items 1 and 2).

@olafurpg, can you remember why do we create an empty Occurrence (item 2 above)? 

_Note:_ It seems this issue existed in the initial selection-driven implementation, too (I checked out the commit before https://github.com/sourcegraph/sourcegraph/pull/46765 and could reproduce it).

**Comment by taras-yemets** [comment]
This issue is not reproduced on `yml` files, for example, ([push-schema.yml](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/.github/workflows/push-schema.yml?subtree=true)) where each word appears to be an occurrence (usually non-interactive) not causing code-intel popover to appear.

**Comment by taras-yemets** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/47662

**Comment by taras-yemets** [comment]
@olafurpg, if an occurrence is not in highlight data (e.g., we create it on the client - item 2 [of this comment](https://github.com/sourcegraph/sourcegraph/issues/47619#issuecomment-1431037988)), is it possible that either hover information or references still can be found? In other words, do we need to show code-intel popovers for such occurrences?

**Comment by olafurpg** [comment]
@taras-yemets It's critical that we fallback to `inferOccurrenceAtPosition` because our highlighting data is incomplete for a lot of languages. I'm working on a PR to improve highlight quality for the most common languages (https://github.com/sourcegraph/sourcegraph/pull/47571) but there will still be a long tail of languages where we will continue to syntect for the foreseeable future. 

The fix from @fkling goes a long way to address this issue. A good next step would be to stop displaying popovers in files that have no defined language. You can use `findLanguageMatchingDocument` for this purpose https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ff466c55b67a09c03769a0e56a9677a99943850b/-/blob/client/shared/src/codeintel/api.ts?L155
