### ISSUE TITLE
app: Remove signup/sign in page when a user downloads and opens App

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#47907]
> This probably means creating a "hidden" auto-generated account that can be translated into a "visible" named account with persisted configs once a user signs up

**Comment by keegancsmith** [comment]
There is a proposal from @slimsag here on how to implement this https://github.com/sourcegraph/sourcegraph/issues/47998#issuecomment-1439120533

**Comment by keegancsmith** [comment]
@marekweb is this done? I see some PRs by you related to this.

**Comment by marekweb** [comment]
@keegancsmith No, my PR was a relatively small part (removing just the Sign Out UI) and I'm not currently working on this. I can pick up any frontend UI work that comes out of this but that is not defined at the moment.

As far as I understand it, this issue is just the original older issue for:

- #47998

**Comment by slimsag** [comment]
Just to clarify:

* This issue is about _removing the requirement to sign up / sign in_ when starting App, which we'd really like to have for Starship.
* The other issue #47998 is discussing how we can implement this, but it also explains how we can implement federation (signing into a sourcegraph.com account, also very desirable but a separate issue / nice to have for now.)

**Comment by taylorsperry** [comment]
Closing because sign-in requirement was removed in [this release](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1679003912703439).
