### ISSUE TITLE
Add api for fetching resolved repositories by absolute path 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#48128]
So the flow for the local repositories in march release will be the following. 

1. You click on the local repositories button in the picker
2. We send a request to the backend, hey please open the native macOS finder and pick a directory
Backend calculate the absolute path and returns it to the client https://github.com/sourcegraph/sourcegraph/issues/48127
3. Client make a request with backend with local path and render the resolved by this path suggestion (actually, maybe we can merge the absolute path and suggestion query if it's possible)
4. And then user click submit (connect) button, and then the client configure external service configuration based on absolute path, and we start discovery syncing phase for local repos on the BE

In this issue we should focus on the 3 step and add some API query to get the list of repositories by absolute path

**Comment by keegancsmith** [comment]
I'm removing my assignment right now since I am not gonna work on this API today (I think). I'll get to it this week, but maybe can adjust priorities based on feedback from your blockers @vovakulikov. What can help unblock interactions @vovakulikov is maybe speccing out what the graphql looks like? That will be the first thing I do when I work on this, so would be cool to get a head start :)

If @gl-srgr has cycles to work on this before I get a chance he should / we can collab.

**Comment by gl-srgr** [comment]
@keegancsmith I am starting today on this, specifically:

> Client make a request with backend with local path and render the resolved by this path suggestion (actually, maybe we can merge the absolute path and suggestion query if it's possible)

I'll be focusing on "discovery" of local repository suggestions first and so the osascript file picker will not be included in my immediate deliverable, but is still something we'd like in setup experience for starship so either of us can pick that work up when available.

**Comment by vovakulikov** [comment]
@gl-srgr can we close this one, or are there any follow up and you want to keep this?

**Comment by gl-srgr** [comment]
@vovakulikov Yes we can close this one, just a summary:

#48984 : Pr is indirectly related: It returns external services (with option to see which ext svc is autogenerated by sourcegraph app on startup) and does not return repos. However, setup experience uses the returned external service to then call the localDirectory() query from this [PR](https://github.com/sourcegraph/sourcegraph/issues/48127), so that we can identify currently sync'd repos across all local ext svcs. So between those two PRs we have all of the local repo graphql queries for setup experience
