### ISSUE TITLE
Implement backend-based file picker for the local repositories path

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#48127]
Based on the conversation with Sourcegraph App and Setup experience teams, it seems that we can't use browser file picker for getting info about absolute path for the directory with repositories, but it seems possible to get absolute path through backed based file system picker. We need to check this idea, and after we can try to adopt this in the Setup Wizard local repositories step. 

The flow, in general 
- You click on the local repositories button in the picker
- We send a request to the backend, hey please open the native macOS finder and pick a directory
- Backend calculate the absolute path and returns it to the client
- Client make a request with backend with local path and render the resolved by this path suggestion (actually, maybe we can merge the absolute path and suggestion query if it's possible) 
- And then user click submit (connect) button, and then the client configure external service configuration based on absolute path, and we start discovery syncing phase for local repos on the BE

Desired API is simple 
```gql
query GetAbsolutePath {
  getLocalAbsoluteRepositoryPath {
     path
  }
}
```

This query opens file picker via backend terminal command, also this query should be in pending state while user is picking a path in the file, and as soon as user picks the path and click submit in file picker this query should be resolved with picked absolute path.

**Comment by keegancsmith** [comment]
Copying from slack the solution

```shell
osascript -e 'return the POSIX path of (choose folder with prompt "Select a repository or folder with repositories")'
```

So I think what is needed now is someone to hook that up to an API. I would expect two APIs. One for determining if it is available and one to actually run it. We should gate it to only be run on mac by an admin in sourcegraph app.

**Comment by vovakulikov** [comment]
@keegancsmith 
>. One for determining if it is available 

I would put this info in the window.context (it seems like we should have this info there) in order to avoid flashes on the screen, Like you open setup wizard, we show to you local repositories step, then we make network, and it turned out that this option isn't available (because you're on Linux) and we redirect you to the next step. 

With window.context we would have this info in sync way and could do redirect immediately

**Comment by keegancsmith** [comment]
There is a lot of overlap in how I am thinking of this with #48128 since they are both to do with local directories. Here are my thoughts and I will get implementing it today now that I have thought it through. Please comment @vovakulikov @gl-srgr.

@gl-srgr I might be stomping on your toes with this implementation, sorry about that. But to me the API is the important part, the actual discovery stuff for local repos already exists as a Go API.

### API design

```graphql
extend type Query {
  """
  Runs a host system native file picker and returns the directory picked. This
  is intended to be used by Sourcegraph App.
  """
  localDirectoryPicker(): LocalDirectory!
  # Note: we don't specify an optional dir since it isn't obvious just yet how
  # to support that on darwin. If we do add support, it will be optional (and
  # default to cwd).

  """
  Returns the local directory at dir. This is intended to be used by
  Sourcegraph App.
  """
  localDirectory(dir: String!): LocalDirectory!
}

"""
LocalDirectory represents a directory on the host machine. This is an API
specific to Sourcegraph App.
"""
type LocalDirectory {
  """
  Return if LocalDirectory picker API is available. This should only be true
  for admin users on Sourcegraph App instances on supported operating systems.
  """
  pickerAvailable: Boolean!
  # Note: we will also make this available as part of the context (or
  # something else) to prevent screen flicker in the wizard setup.

  """
  Path is an absolute path to a local directory that exists. If LocalDirectory
  was created via picker this is the path picked. If null the user canceled
  the operation.
  """
  path: String

  """
  Repositories is the recursive list of repositories found under path. It can
  be null if this was created via picker and the user canceled the operation.

  Note: This field is blocking to compute. It uses heuristics to return a
  best-effort list in 5s.
  """
  repositories: [LocalRepositores!]
  # Question: Would it be better to be a connection with pagination? There
  # are serious limitations to this due to it not being a DB query, which is
  # why I chose a list.
}

"""
LocalRepository represents a repository found recursively from a directory on
the host machine. This is an API specific to Sourcegraph App.
"""
type LocalRepository {
  """
  The name of the local repository. This is usually the relative path from the
  root this repository was found.
  """
  name: String!

  """
  The absolute path to a local repository.
  """
  path: String!
}
```

Notes:

-   I expect the flow to be `localDirectoryPicker().path` followed by `localDirectory(path).repositories`. That is because we can quickly return the path picked, but computing the repositories can be slow. So we can show a spinner or something.
-   I'm not sure that I like making `pickerAvailable` part of `LocalDirectory`. This makes the other fields more tricky since they can be nullable. I think I should just remove it and make the whole thing error if used on something we don't support. Then we expect app to use the context value that is smuggled in? I'll likely make this decision when implementing, but leaving the more expanded design around for comments.
-   I like the `LocalDirectory` is used for both `path` and `repositories`. This feels correct from what the things actually are, and feels like we could add more functionality around this as we expand on apps capabilities.


### OS implementation notes

I will support it since I develop on a linux machine so it makes my life easier while developing this API. Linux options (may be missing):

-   zenity
-   xdialog

Mac

    osascript -e 'return the POSIX path of (choose folder with prompt "Select a repository or folder with repositories")'

This picks a weird location to choose from (Documents for me). I tried changing it but life started getting complicated. Might have to investigate doing it via javascript.

**Comment by keegancsmith** [comment]
@vovakulikov contains a stub API that should hopefully unblock frontend dev / you can critique. I am still working on it (ie it doesn't actually use a file picker just yet), but the idea is you should be unblocked.

**Comment by vovakulikov** [comment]
@keegancsmith just to make sure I get it right

`localDirectoryPicker()` returns `LocalDirectory` that contains `path` (it makes sense), `pickerAvailable` (probably also makes sense, but I think we also will get this info through `window.context`) but `repositories` doesn't seem right here (since you mentioned "but computing the repositories can be slow. So we can show a spinner or something") Or you mean that we want to reuse types for both queries but shouldn't query `repositories` field if we want this to be fast?

>I should just remove it and make the whole thing error if used on something we don't support

I agree, fail fast approach should work here better.

> I expect the flow to be localDirectoryPicker().path followed by localDirectory(path).repositories. 

That is exactly our (my and @st0nebraker) thoughts. I checked the PRs above (I haven't tested them manually, though), but the schema looks good, and it should be easy enough to integrate it with our UI for local repositories step. 

One thing to check since I've seen different conversations in slack and github, what kind of configuration schema for "Other" external service do we have? 
Just this, right?
```
 "root": "/User/Project/<basically any global path here>"
```

**Comment by gl-srgr** [comment]
> generic preview API

I don't think this is a must have for local repos, so @vovakulikov if you are okay with using the described `local*` graphql query and you don't need to use the graphql queries for the remote code host setup step then I believe we can keep this API. We can decide to implement the necessary interface to enable the generic preview api after starship.

> One thing to check since I've seen different conversations in slack and github, what kind of configuration schema for "Other" external service do we have? Just this, right?
> 
>  "root": "/User/Project/<basically any global path here>"

This is the plan for the updated schema. Since we don't need anything else besides the absolute path, will you be okay with using the returned `LocalDirectory` @vovakulikov ?

**Comment by gl-srgr** [comment]
@vovakulikov One more thing about the ext svc configuration: Currently there is special case identification for Other external service where we [check the repos array](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/other.go?L91&subtree=true) of the configuration. I'm adding another hardcoded identifier so that means for setup experience if you create a local repository external service then you should populate the repos array with a single element:

`"Repos": ["src-serve-local"]`

this will be merged with my PR https://github.com/sourcegraph/sourcegraph/pull/47779

**Comment by keegancsmith** [comment]
I am closing this issue since we now have a graphql API for running the filepicker https://github.com/sourcegraph/sourcegraph/pull/48605/files#diff-08320ad40f2325036a08d1dc7420ff7a5bf13383dab16b9e0af0b19113ea6a70R7:

```graphql
localDirectoryPicker {
  path
}
```

There is still the jscontext to land, but I don't see a reason not to approve as is. https://github.com/sourcegraph/sourcegraph/pull/48728
