### ISSUE TITLE
Clicking a line adds an entry to your browser history

### ISSUE THREAD

**Issue by tbodt** [sourcegraph/sourcegraph#4816]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** sourcegraph.com

#### Steps to reproduce:

1. Click a line in a file

#### Expected behavior:

Nothing should happen

#### Actual behavior:

The line is selected and adds an entry to your browser history specifically for that line. This should only happen when you click in the gutter.

**Comment by sqs** [comment]
This overall behavior was intentional and helps when navigating around a large file, especially when jumping to definitions and references in the same file. We can be smarter here, though. I propose we adopt a heuristic here and make the following change:

If you click on a line (not gutter) that is less than 10 lines from the currently selected line, the new line URL is replaced (not pushed) in the history stack. This matches VS Code’s behavior, BTW.

Sound good?

**Comment by tbodt** [comment]
I'm fine with adding an entry to browser history when you jump to a definition or a reference, but I often double click on random lines to select them just to focus my attention to read them, without intending to add a history entry.

The 10 line heuristic would be an improvement, though.

**Comment by nicksnyder** [comment]
Similar feedback from a customer: https://sourcegraph.slack.com/archives/C0W2E592M/p1591051793299800

**Comment by lrhacker** [comment]
@fkling Was able to knock this out really quickly - thank you so much Felix!

As a note here so it's tracked, there may be separate considerations or behavior in the future for the CodeMirror implementation of the blob view (still in prototype); these changes specifically will updated the existing blob implementation.
