### ISSUE TITLE
Add writing case study page to docs

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4828]
https://docs.google.com/document/d/1jEDplo8zKp0h36RfbKZG3O5-dg8_sLhuixfCMBL1UI8/edit#heading=h.7dty0x9oi1xf

**Comment by kghopson** [comment]
Will be making modifications in a new doc [here](https://docs.google.com/document/d/1jV11-bvuyGHg3uxJJb2o8Dymexxphf_X5S9aPLbaC1I/edit)

**Comment by kghopson** [comment]
@sourcegraph/product-team I finished making my changes to the [doc](https://docs.google.com/document/d/1jV11-bvuyGHg3uxJJb2o8Dymexxphf_X5S9aPLbaC1I/edit#) but need some feedback regarding the intended audience and clarification. Please review my comments (and the doc in general) when you have a moment.

**Comment by dadlerj** [comment]
Hey @kghopson —case studies are currently owned by the marketing team these days, so please make sure to get approval from @lorihey and @aileenrose on this. 

This is very timely, because Lori and I are currently writing three case studies this week :). Lori is in charge of the process, and I'm involved as the CE, and just because I have some history on how case studies have been written in the past.

We are using a totally new process this time around as well—e.g., we are working with our PR firm to write the first draft. So this definitely needs a refresh. I left a few comments, but I defer to Lori on the overall process.

**Comment by kghopson** [comment]
@lorihey Recommends that we just scrap this doc completely, since this process will be changing once the new VPM starts. Closing the PR
