### ISSUE TITLE
Extend "Other" external service schema with local repositories fields

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#48473]
In the setup wizard UI we will have a special step for the local repositories, in this UI you should be able to specify path for the local repositories and there will be two options
- Specify just direct path to the git repository 
- Or specify path and recursively find all git repositories in this path 

In UI it would be like this 
<img width="829" alt="Screenshot 2023-03-01 at 14 21 29" src="https://user-images.githubusercontent.com/18492575/222214748-984d0524-e466-4c47-abf7-3ae366f89c61.png">

This information about picked path and discover mode should be stored somewhere, it looks like it should be part of "Other" (special external service that handles for us local repositories setup) configuration 

For example:
``` 
{
  path: "/User/vova/Projects",
  mode: FLAT | RECURSIVE
}
```

So in this issue we need to extend Other extsrv configuration with path and mode fields and also we should be able to read this information through API somehow (I think at the moment there is no way to fetch local repositories external services)

Maybe we could introduce a special query/resolve for this like
```gql
getLocalExternalServices() {
   ... on ExternalService {
       id
       kind
       displayName
       repoCount
       config
     }
}
```

Or we could extend existing API 
```
query GetCodeHosts {
        externalServices(local: true) {
            nodes {
                id
                ...
            }
        }
    }
```
`local:true` filters out all non local externalServices on the backend and returns only local

**Comment by keegancsmith** [comment]
@vovakulikov This is kinda what @gl-srgr has been working on in https://github.com/sourcegraph/sourcegraph/pull/47779. That is the work which makes our Other external service support this use case. The configuration will contain a field referencing the local repository path. Then like you normally do you can ask for the synced repos for that service.

This won't give you back the local paths, these are contained inside of the cloneURL which I think we encrypt by default. As such we can add it to the generic metadata field?

The way our discovery works is that if a user picks a git repo then that is all we find. I don't see why we should distingiush between recursive or not. IE if a user picks a repo, then that is what we find and won't find any others. If they pick a random directory then we recurse to find.

Is there anything else you need that is local specific?

**Comment by vovakulikov** [comment]
> The way our discovery works is that if a user picks a git repo then that is all we find. I don't see why we should distingiush between recursive or not. IE if a user picks a repo, then that is what we find and won't find any others. If they pick a random directory then we recurse to find.

I agree with this, but I do believe that @almeidapaulooliveira  had some consumers about this behaviour

**Comment by vovakulikov** [comment]
Just for the history - My comment about this behavior in the slack thread https://sourcegraph.slack.com/archives/C04J6HSHVJ5/p1677179646940149?thread_ts=1677168465.573239&cid=C04J6HSHVJ5

>even one button will be fine because if user wants to add just one git repository, they will find this repository in the picker, if they want to add multiple they will select high level directory that contains many repositories. This is what I would expect if I worked with this for the first time

**Comment by gl-srgr** [comment]
Recursive and multiple paths are two options/considerations that we were planning to include for starship but from recent discussions (both in and out of github) I believe we can remove these from scope.

- _multiple paths_ refers to having one external service express interest in multiple directories for sync'ing. Specifically, we would pass all of the directories to `/list-repos-for-path/ `endpoint and get back repositories detected.
- _Recursive_ refers to declaring intent for each path, so ext svc could declare if the walk of directories would look at subdirectories or not.

I'm fine with removing these for Starship. Note that replacing the multiple paths `roots` field with a single path `root` field in the `Other` external service configuration does not necessarily mean that external service cannot sync multiple repositories, since a non-git directory that contains multiple git directories will result in multiple git directories being detected and sync'd according to the described discovery logic (and I played around with this today to confirm). 

Once we also apply the below assumptions as described by @keegancsmith's comment then a setup experience created `Other` external service will only have one repository to sync at most.

1) assumption: setup experience is the only way app users will choose to select local repos to sync
2) assumption: setup experience  will only add a directory to the ext service configuration if it was confirmed by file picker to contain a git repo (as described in the above comment from @keegancsmith) and it was selected by the user from the file picker results

We can add either of the above two enhancements later, for either the sync operation or just the discovery local repos query, but I'd say we save it for after starship. This will also simplify the current [PR](https://github.com/sourcegraph/sourcegraph/pull/47779).

I will comment on the local repos discovery implementation in the https://github.com/sourcegraph/sourcegraph/issues/48127

**Comment by gl-srgr** [comment]
Just one more clarification after re-reading the proposal [here](https://github.com/sourcegraph/sourcegraph/issues/48127#issuecomment-1453165687): I am under the impression that after both localDirectoryPicker and localDirectory queries run, if there are multiple `LocalRepository` found for `LocalDirectory` then in the setup wizard the user has to select one and only one repository whose path will populate the `Other` external service. This was why I mentioned above that we can assume we'll have no more than one repository sync'd by the setup wizard created external svc.

Let me know if I misunderstood.

**Comment by keegancsmith** [comment]
> Recursive and multiple paths are two options/considerations that we were planning to include for starship but from recent discussions (both in and out of github) I believe we can remove these from scope.

Recursive is the only option. If you select a non-git directory we recurse looking for git repos. If you pick a git repo the recursion stops straight away.

Multiple paths/roots support is needed? Assuming the wizard has selections / you can add multiple directories we need it. There are two approaches here that I think make sense: an external service per directory or a single external service containing multiple roots. I think the latter (which you have done) feels the nicest. 

> 2. assumption: setup experience  will only add a directory to the ext service configuration if it was confirmed by file picker to contain a git repo (as described in the above comment from @keegancsmith) and it was selected by the user from the file picker results

This is not what I meant. The file picker just picks a directory. If it is a git repo, then our discovery mechanism and syncer will just find that. If not it will find 0 or more repos rooted at it.

> Just one more clarification after re-reading the proposal [here](https://github.com/sourcegraph/sourcegraph/issues/48127#issuecomment-1453165687): I am under the impression that after both `localDirectoryPicker` and `localDirectory` queries run, if there are multiple `LocalRepository` found for the selected and returned `LocalDirectory` then in the setup wizard the user has to select one and only one repository whose path will populate the `Other` external service. This was why I mentioned above that we can assume we'll have no more than one repository sync'd by the setup wizard created external svc.
> 
> Let me know if I misunderstood.

I think you may have? It all depends on how the wizard works, but I suspect you pick a LocalDirectory then the wizard previews the LocalRepositorys it will sync. If you then add it, we pass it off to the external service (with root set to the LocalDirectory) and that will sync Repos which correspond to the LocalRepository.

**Comment by keegancsmith** [comment]
@vovakulikov I think we pretty much have all the code out for review for this issue:
- https://github.com/sourcegraph/sourcegraph/pull/47779 adds a way to specify a root for the Other external service
- https://github.com/sourcegraph/sourcegraph/pull/48819 adds the local absolute filepath to the external service metadata
- https://github.com/sourcegraph/sourcegraph/pull/48605 adds an api for getting getting local repos and paths before they are synced

The shape of the GraphQL API may change directly for the last point (IE repositories field on LocalDirectory). But I expect that to then be incremental work on the frontend. The other change that may need to happen is I am unsure if we expose metadata for an Other repo in the GraphQL API.

But I am of the belief that frontend is unblocked w.r.t. this issue (if they base work on the soon to be merged PRs) and this issue will be closed as soon as those PRs land.

**Comment by vovakulikov** [comment]
Thanks everyone, I'm about to close this one.
