### ISSUE TITLE
app: macOS bundle is not merged; we're shipping code not in `main` w/manual process

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#48827]
Allow users to install the Sourcegraph app through a download button on MacOS, rather than running the `brew install` and `sourcegraph` commands from the CLI. 

Some criteria from @slimsag: 

1. It is an automated process that occurs after a Git push to app/release-snapshot in a CI pipeline - I don’t want us to get stuck creating releases manually using some hacked together process.
2. It consumes a single sourcegraph binary and the output is an app file - i.e. we do not base it on goreleaser which I have my sights set on getting rid of.
3. It is signed & notarized
4. There’s time to review the approach and make sure it fits well with where we are going.

For this issue, @peterguy will own implementation (with review from @slimsag) and work with @almeidapaulooliveira for design. @marekweb would you please make sure that these downloads are captured along with the number of installations via the CLI?

**Comment by almeidapaulooliveira** [comment]
@taylorsperry - I suggest changing: `through a download button on MacOS` to
`through a native installer for Mac`

**Comment by peterguy** [comment]
We will have three install/download options for macOS:
1. `brew install ...`
1. download a zip file containing a single binary
1. download a dmg file containing a macOS app bundle the user can drag to `/Applications` (or wherever)

The first two are unchanged as options (the zip file will contain a signed binary that will not cause alarming popup messages when they run it)

The third one is new and will be modeled after the board meeting demo. It will be signed and notarized so that it will also avoid alarming popup messages.

**Comment by peterguy** [comment]
I think I answered this offline, but just to record the answer here, most of the process is ready for automation. Building a dmg file requires macOS - I have found no suitable tools to build a dmg to our specs, even when starting with a template dmg. GitHub Actions has macOS VMs available, so we'll probably need to use that to generate the dmg.
The autmation scripts that build the app, sign and notarize it, zip archive it, and copy to the "latest" bucket work when run manually, but there is buildkite-specific code in them that have not been tested. I will need help figuring out how to test on buildkite.
For reference, [this is the app bundle PR](https://github.com/sourcegraph/sourcegraph/pull/49176)
