### ISSUE TITLE
Visual Basic code intelligence & search lang: filter

### ISSUE THREAD

**Issue by YouveGotMeowxy** [sourcegraph/sourcegraph#4901]
I code mostly with VB.net. Is there a plugin or something for sourcegraph that provides vb syntax highlighting/code intelligence?

**Comment by slimsag** [comment]
Syntax highlighting support fixed by #10374 and will be in Sourcegraph 3.16.

Code intelligence and other language support will still need to be added, so leaving this issue open for that.

Example:

![image](https://user-images.githubusercontent.com/3173176/80898193-8665a900-8cb5-11ea-9492-e0fa161559d0.png)

**Comment by rvantonder** [comment]
Closing since this works now. Example: https://sourcegraph.com/github.com/12meses12katas/Febrero-Roman-Numerals/-/blob/miguelerm/RomanNumerals/AssemblyInfo.vb
