### ISSUE TITLE
Jump to definition on external symbol does nothing

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#4905]
- **Sourcegraph version:** 3.6.0-rc.1

#### Steps to reproduce:

1. Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/browse/lib/targets.go#137
2. Hover over `Lexer`.
3. Click `Go to definition`.

#### Expected behavior:

Either jumping to sourcegraph.com (best) or no `Go to definition` button is shown, or it's grayed out with an explanation for that (less good).

#### Actual behavior:

There's a loading spinner but nothing happens and there's no feedback at all.

![image](https://user-images.githubusercontent.com/67471/61303878-88bf4b00-a7e8-11e9-94a1-3b5b8b27fd69.png)

**Comment by tsenart** [comment]
cc @keegancsmith

**Comment by lguychard** [comment]
Removing bitbucket, browser-extension labels since this also happens on https://k8s.sgdev.org/bitbucket.sgdev.org/SOUR/vegeta/-/blob/lib/targets.go#L137:17

I don't think this is a regression, but the experience here could clearly be better.

**Comment by felixfbecker** [comment]
Seeing this GraphQL request error in the network panel every time I click j2d:

![image](https://user-images.githubusercontent.com/10532611/61305167-a1c8fb80-a7ea-11e9-86e7-05735342c09f.png)

This is not logged to the console though

**Comment by felixfbecker** [comment]
What's interesting is that `uri` is not nullable but it is `null`, because graphql-go is not spec compliant: https://github.com/graph-gophers/graphql-go/issues/173

@sourcegraph/core-services is it expected that the `uri` resolver returns an error when a repo is not found?

**Comment by keegancsmith** [comment]
@felixfbecker What would you expect it to do? You are the main consumer of the uri field, so lets match it to your ideal behaviour and we will fix it.

**Comment by mrnugget** [comment]
(I don't know if this is related, so feel free to redirect me to another issue, but I cannot get the tooltip to show up with a definition. I tried this in Chrome and in Firefox, I point the extension to k8s.sgdev.org, I reloaded and hard-reloaded multiple times, I hovered above the `Lexer` identifier ~50 times now and the tooltip never showed up with data. Twice it showed up with a spinner and then silently disappeared)

**Comment by felixfbecker** [comment]
@mrnugget that depends on whether you see the same errors in the console

**Comment by felixfbecker** [comment]
@keegancsmith in this case, does "repo not found" mean that the repo is not found and also not in any external service, i.e. not just _not cloned_ but literally _does not exist_? In that case I would expect `repository` to be `null` (probably without an error, because I believe other resolvers behave this way in our API).

**Comment by keegancsmith** [comment]
repo not found always means it doesn't exist on the instance. In this case it means it doesn't exist. We do not ask gitserver at all if the clone exists, this is purely a lookup in our repos table. I'll look into what we do if you just ask for name, since I think that also throws an error? Changing that behaviour would likely break other parts of our codebase if we do work that way.

**Comment by efritz** [comment]
Moving discussion of this request over to https://github.com/sourcegraph/sourcegraph/issues/13137.
