### ISSUE TITLE
Symbol search on k8s.sgdev.org often times out

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4926]
- **Sourcegraph version:** 3.6
- **Platform information:** k8s.sgdev.org

#### Steps to reproduce:

1. Open network tab in browser console
1. Make sure that TypeScript code intelligence is disabled by adding the following to your user settings:
```json
 "typescript.enable": false,
 "typescript.serverUrl": ""
```
1. On k8s.sgdev.org search for `repo:^github\.com/sourcegraph/sourcegraph$ lang:typescript f:web/src/SourcegraphWebApp.tsx`
1. Click on `web/src/SourcegraphWebApp.tsx`
1. Hover over `readStoredThemePreference` in line 137
1. See the `Search` GraphQL in network tab being stopped after 10s

Trace: https://app.lightstep.com/sourcegraph-dev/trace?span_guid=5815d48c2ee3e94c&at_micros=1563361054217717#span-5815d48c2ee3e94c
Another trace:

**Comment by keegancsmith** [comment]
I know we are working on indexed symbol search. But the fact that symbol search fails on a single repository indicates there may be a bug in the symbol service that we should resolve. Can someone from the search team debug this once we are done with release testing this week?

**Comment by kzh** [comment]
I can look into this since I'm currently working in this codebase (`cmd/symbols`).

**Comment by chrismwendt** [comment]
It looks like the symbols service creates a pool of N ctags processes:

https://github.com/sourcegraph/sourcegraph/blob/5661a8085980968f7b2bb2a0bc7258c4ba659fea/cmd/symbols/internal/symbols/parse.go#L23-L38

Those ctags processes receive incoming parse requests in an interleaved file-by-file fashion, given the file content on stdin.

So, I think it's possible for the ctags generation for each individual repository to be fast, but when interleaved, some can take a long time (kind of like "user" vs "real" time in the `time` command).

However, even if we group by repository instead of by file, symbol searches over all repositories will still be quite slow because of on-demand ctags generation. Zoekt-base symbol search would probably fix this. Linking to https://github.com/sourcegraph/sourcegraph/issues/3534#issuecomment-507588572

**Comment by keegancsmith** [comment]
@chrismwendt the example query that is failing is not over all repositories though, it is over a single repo. We should confirm there is nothing else going on. I agree if we have a large queue of things to index due to other searches then this would fail and indexed search would fix. But we should confirm that is the case.

**Comment by chrismwendt** [comment]
@keegancsmith I think it is searching over all repositories (try expanding the spans a few levels deep):

![image](https://user-images.githubusercontent.com/1387653/61407558-40ad3080-a89b-11e9-82ed-7938e9f1b047.png)

basic-code-intel searches for a matching symbol in this order:

- The current repository
- All repositories

`readStoredThemePreference` wasn't found in the current repository, so it searches in all repositories.

**Comment by kzh** [comment]
Based on our sidebar, it seems that either our `universal-ctags` version is not picking up `readStoredThemePreference` (and other symbols) or our ctags entry parser isn't working. I will try to debug this.
![Screen Shot 2019-07-17 at 1 05 01 PM](https://user-images.githubusercontent.com/3507526/61408855-dd6ccf80-a895-11e9-8e97-664ef2347a5c.png)

I ran `universal-ctags` locally on this file and it does recognize `readStoredThemePreference`, but is missing other symbols that Sourcegraph does include. `universal-ctags` has built in support for TypeScript as of Jan 2nd, but we're still using third party TypeScript ctags configs. Maybe there is a conflict?
```
--langdef=typescript
--
  | --langmap=typescript:.ts.tsx
  | --regex-typescript=/^[ \t]*(export[ \t]+([a-z]+[ \t]+)?)?class[ \t]+([a-zA-Z0-9_$]+)/\3/c,class/
  | --regex-typescript=/^[ \t]*(declare[ \t]+)?namespace[ \t]+([a-zA-Z0-9_$]+)/\2/n,module/
  | --regex-typescript=/^[ \t]*(export[ \t]+)?module[ \t]+([a-zA-Z0-9_$]+)/\2/n,module/
  | --regex-typescript=/^[ \t]*(export[ \t]+)?(default[ \t]+)?(async[ \t]+)?function[ \t]+([a-zA-Z0-9_$]+)/\4/f,function/
  | --regex-typescript=/^[ \t]*export[ \t]+(var\|let\|const)[ \t]+([a-zA-Z0-9_$]+)/\2/v,variable/
  | --regex-typescript=/^[ \t]*(var\|let\|const)[ \t]+([a-zA-Z0-9_$]+)[ \t]*=[ \t]*function[ \t]*[*]?[ \t]*\(\)/\2/v,variable/
  | --regex-typescript=/^[ \t]*(export[ \t]+)?(public\|protected\|private)[ \t]+(static[ \t]+)?(abstract[ \t]+)?(((get\|set)[ \t]+)\|(async[ \t]+[*]*[ \t]*))?([a-zA-Z1-9_$]+)/\9/m,member/
  | --regex-typescript=/^[ \t]*(export[ \t]+)?interface[ \t]+([a-zA-Z0-9_$]+)/\2/i,interface/
  | --regex-typescript=/^[ \t]*(export[ \t]+)?type[ \t]+([a-zA-Z0-9_$]+)/\2/t,type/
  | --regex-typescript=/^[ \t]*(export[ \t]+)?enum[ \t]+([a-zA-Z0-9_$]+)/\2/e,enum/
```
(https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph@992aa567fa80979d952cc7cad5e8c07caef8c069/-/blob/cmd/symbols/.ctags.d/additional-languages.ctags)

**Comment by chrismwendt** [comment]
@kzh I filed that as a separate issue: https://github.com/sourcegraph/sourcegraph/issues/4931

**Comment by keegancsmith** [comment]
We can't rely on global symbol search yet. I think it may be better if we falled back to global text search (like basic-code-intel used to do). Is that possible? This may also be the reason why we have been having reliability issues with the symbol service, due to this overloading it. Is this possible to implement (as part of 3.7)

**Comment by chrismwendt** [comment]
Yeah, that's super easy to do. It would be an extension-only change, so no need to tie it to a release.

**Comment by mrnugget** [comment]
@kzh @chrismwendt For what it's worth: `readStoredThemePreference` is defined in the same file ([see here](https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/web/src/SourcegraphWebApp.tsx#L96)), so I'd guess your suspicion regarding ctags is right :)

**Comment by chrismwendt** [comment]
I'm adding a toggle for global symbol search in https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/123

**Comment by chrismwendt** [comment]
Merged the PR and published language extensions. Set

```json
  "codeIntel.globalSymbolSearch": false
```

to disable global symbol search.

**Comment by ijt** [comment]
@kzh, is this still an issue now that your zoekt changes are merged?

**Comment by kzh** [comment]
Update: I'm not exactly confident that this fixes the issue. On k8s.sgdev.org, `readStoredThemePreference` now takes 1.7s to search for yielding no results across 38k repositories. This is probably not the latency we wish to achieve with hovers. It's probably a lot faster with results that do exist. I'll try to do some benchmarks. I'm also unsure with how many concurrent requests Zoekt is able to handle.

**Comment by keegancsmith** [comment]
@kzh I would suspect general search improvements should be tracked in another issue? As it stands we shouldn't be timing out anymore. If so, can we close this issue?
