### ISSUE TITLE
LSIF: errors being thrown when hovering whitespace

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#4951]
Not sure which component this comes from / should be fixed in, so filing here.

#### Steps to reproduce:

1. Visit https://sourcegraph.com/github.com/gorilla/mux@d83b6ffe499a29cc05fc977988d0392851779620/-/blob/mux.go#L69
2. Open console
3. Hover whitespace

#### Expected behavior:

No errors are being thrown.

#### Actual behavior:

Numerous errors being thrown in the console:

![image](https://user-images.githubusercontent.com/1741180/61616115-ef6cba80-ac67-11e9-84b6-62b4379b515d.png)

**Comment by chrismwendt** [comment]
Ah, sorry you ran into this, but thanks for bringing this to my attention! This was fixed by https://github.com/sourcegraph/sourcegraph/pull/4932 but production was pinned to an older lsif-server. Fixed in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/c968f7cb3a3d2c95f3bd6ec624918b18e90cf73f
