### ISSUE TITLE
Funky behaviour between auto-generated and manually set code host connections

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#49737]
Loom https://www.loom.com/share/fa77c1bc494f414ba26687e809288d49

#### Steps to reproduce:

1. Run Sourcegraph App locally in any repository dir
2. See in the wizard that you have this repository 
3. Set a path that resolves different repository 
4. See that you have both repos on the instance 
5. Then edit the repository path in the wizard so that it will resolve different repo
6. See that the built-in repository from the terminal disappeared from the instance

**Comment by gl-srgr** [comment]
This should fix the issue described and portrayed in the Loom recording.

As far as I can tell there isn’t a modification / mutation of the unedited (autogenerated) external service, but the empty string root path in the configuration which we set when clicking reset path will end up interpreted as current working directory `.` when we discover repositories, so it picked up sourcegraph repo in cwd on discovery but fails to sync because we don’t succeed when there’s a relative path like `.`  .  This means that it does not matter which repos the autogenerated external service is sync’ing and the Reset Path will error on whatever repo is in the current working directory for sourcegraph app, **even if that repo was not being sync'd before Reset Path was clicked**

**Comment by gl-srgr** [comment]
@vovakulikov I merged PR 49744, If you get a chance you might want to test this out. I tested it out myself, now after reset path your external service will remain with root: "" and this will no longer get errors/warnings anymore, and instead you'll just sync 0 repositories (because we'll skip it on the local files discovery operation).

**Comment by slimsag** [comment]
Closing since should be fixed (in theory at least)
