### ISSUE TITLE
Improve migrator drift check for air-gapped instance

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#49813]
This issue is to track usage experience improvements for air-gapped instances of Sourcegraph

See internal issue thread for more details: 
[https://sourcegraph.slack.com/archives/C04DMC5Q971/p1679381273350999?thread_ts=1678887371.884609&cid=C04DMC5Q971](https://sourcegraph.slack.com/archives/C04DMC5Q971/p1679381273350999?thread_ts=1678887371.884609&cid=C04DMC5Q971)

Migrator Upgrade command currently runs a drift check which requires access to the public internet. To bypass this check users can use the `--skip-drift-check` flag with `upgrade`. However if such users want to check drift they must run drift passing a path directly to the local file: `migrator drift --file <PATH>`, a [schema file](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40main+f%3Ainternal%2Fdatabase%2Fschema.*%5C.json&patternType=standard&sm=1&groupBy=path) must be present on the machine running migrator commands in an air-gapped instance.

In general these files can be sourced in [https://github.com/sourcegraph/sourcegraph/tree/main/internal/database](https://github.com/sourcegraph/sourcegraph/tree/main/internal/database) making sure to select the correct version flag, for instance at tag v4.5.1 --
frontend: [https://github.com/sourcegraph/sourcegraph/blob/v4.5.1/internal/database/schema.json](https://github.com/sourcegraph/sourcegraph/blob/v4.5.1/internal/database/schema.json)
codeintel-db: [https://github.com/sourcegraph/sourcegraph/blob/v4.5.1/internal/database/schema.codeintel.json](https://github.com/sourcegraph/sourcegraph/blob/v4.5.1/internal/database/schema.codeintel.json)
codeinsights-db: [https://github.com/sourcegraph/sourcegraph/blob/v4.5.1/internal/database/schema.codeinsights.json](https://github.com/sourcegraph/sourcegraph/blob/v4.5.1/internal/database/schema.codeinsights.json)

One suggested way to improve this is to bake these files into a directory on migrator as part of the migrator image

/cc @sourcegraph/delivery

**Comment by DaedalusG** [comment]
As a bandaid until a code fix can be implemented a how-to doc may be valuable to air-gapped instance admins

**Comment by marcleblanc2** [comment]
From https://sourcegraph.slack.com/archives/C032Z79NZQC/p1680132481123799?thread_ts=1680131150.689749&cid=C032Z79NZQC

Impact: Smooth upgrade to v5.0 blocked for our largest customers (air gapped instances)

1. Root cause
- When the migrator container starts up, it checks the database schema release versions against its own version, and if the database schema version is older than the migrator container's version (ex. first start up during an upgrade), then the migrator attempts a drift check, then a database migration schema upgrade
- Database schema description JSON files are stored in a GCP bucket, and are needed for the drift check
- Customer instances that do not have internet access to the GCP bucket fail the drift check
- Customer admins that have their update checks enabled are shown that there's an update available, with no warnings, then encounter this issue
- This issue leaves the admin confused, the docs aren't clear or self-serviceable, and their instance is stuck offline, so they're forced to contact Sourcegraph support
- The admin is forced to make a decision between skipping drift checks, or the time consuming workaround for offline drift check while their instance is down

2. Environment setup, what kind of air gap setup do they have?
- Any deployment type, on any network config where the instance cannot reach the GCP bucket

3. Workaround
- This process https://sourcegraph.slack.com/archives/C02BJ8T258D/p1679701645861869?thread_ts=1679690111.465949&cid=C02BJ8T258D, which is super time consuming and does not instil confidence in our admins.

**Comment by DaedalusG** [comment]
It turns out that this was actually always supported but it will now be the preference. An issue will be opened to improve the release process so that updating embedded tags -- see the PR for more details: https://github.com/sourcegraph/sourcegraph/pull/50207
