### ISSUE TITLE
user report: Syncing errors on dmg installer

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#49986]
User reporting sync/indexing errors after using the dmg installer. Context in [Discord](https://discord.com/channels/969688426372825169/1079867414541516901/1088638757089058896)

**Comment by dgroomes** [comment]
Hello, I am the original reporter and I'll try to add some more context. The indefinite "initial indexing in progress" message in the screenshot below is what prompted me to say "I'm having sync/indexing errors" in the linked Discord message.

I tried a few things since I initially reported but the "initial indexing in progress" issue persists. FWIW, I tried:

* I uninstalled/reinstalled the Sourcegraph app
* I pared down to just one repo (scip) instead of having many repos
* I worked around this issue #50192 but that didn't seem to do anything except eliminate the "Failed to get docker version" console log message 

---
**Note:** I'm happy if you close/reopen a more focussed issue. I wanted to look more into the "We were unable to determine the indexserver that hosts the index." but I didn't get a chance.

---

![CleanShot 2023-03-30 at 17 13 30@2x](https://user-images.githubusercontent.com/2716950/228975859-9aff9310-c7bd-46e8-b359-3aea92e95821.png)
