### ISSUE TITLE
TypeScript: Code intel popover shown for keywords 

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#50094]
We're displaying search-based popovers for keywords. I think this is a a regression because we're only supposed to show popovers for "interactive" tokens, which don't include keywords:

![image](https://user-images.githubusercontent.com/458591/228496600-6ef5453c-ae9d-4320-8eaf-73ea14346c7b.png)

@philipp-spiess tried to bisect but could even reproduce the issue as far back as 3b250c21b51ea238f39740967efac9818a839976:

![image](https://user-images.githubusercontent.com/458591/228496749-ad2e3be4-baa2-4137-9fa6-ac19387a06c8.png)

**Comment by valerybugakov** [comment]
[Quote](https://github.com/sourcegraph/sourcegraph/pull/44698#issuecomment-1334163085) from [the PR](https://github.com/sourcegraph/sourcegraph/pull/44698) where this behavior was introduced:

---------------------
> I got some unexpected code-intel popup content which I didn't get on dotcom. Not sure if it may be caused by my local Sourcegraph instance.

This is just an example of bad search-based code intel. When we implement tree-sitter highlighting for TypeScript then we can make `number` and `boolean` "built-in types" so that they don't have popovers by default.

> Some tokens (like the arrow on the screenshot) are not expected to have valuable code intel information. Maybe they shouldn't support 'Space' clicks for code-intel popups display. Hovering these tokens on dotcom doesn't trigger the code-intel popup.

Same issue as above, that will be fixed with a tree-sitter highlighter, which we're planning to fix once @tjdevries is done with scip-go.

---------------------

The improved token selection behavior was implemented behind the feature flag, so the problem described in this PR was not a blocker. But now, this is a default behavior, and seeing code-intel popovers on unexpected tokens is confusing.

@olafurpg, what's the current state of improvements to the highlighter? Would you suggest fixing the problem on the client side or waiting for search-based code-intel updates?

cc @taras-yemets because of the [Token selection: followup review comments](https://github.com/sourcegraph/sourcegraph/issues/45006) issue.

**Comment by valerybugakov** [comment]
I'm also changing the priority of this issue to P2 since it's a known behavior spotted at review, and I assume we knew about it when we enabled it by default. Please feel free to change it back if you like.
