### ISSUE TITLE
Admin: pagination, filtering on the embeddings page

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#50172]
When there's 100s of repositories with embeddings, managing the list is impractical.
We're feeling this pain ourselves with 300 open source repositories on .com

Need to:
- Add pagination
- Add filtering
- Make it so you can select multiple and remove embeddings

**Comment by deepak2431** [comment]
@malomarrec Can I take up this issue to work on?
Currently, this [page](https://docs.sourcegraph.com/cody/embedded-repos) has a search box which is also not working. Also, a better UI for the display of the embeddings would be good to have.

**Comment by malomarrec** [comment]
Hey @deepak2431 apologies for my delay here.
This part of the admin pannel is more enterprise-ish. While we love contributions, would you be interested in working on a more community feature? Feel free to pop into our discord, and we can help out there

**Comment by deepak2431** [comment]
Hi @malomarrec, no problem.
I see. I am already in the discord and have understood more of the Cody extension codebase and web. So, it would be okay to take up any community feature to work on related to work on. Let me know if you need help with any of them.

I am also working on this [issue](https://github.com/sourcegraph/sourcegraph/issues/50399) with @jdorfman . Need your input here!

**Comment by marcleblanc2** [comment]
Customer [8290](https://github.com/sourcegraph/accounts/issues/8290) has requested a 'Select All' checkbox, or we could implement the `repo:` filter, or regex.

**Comment by malomarrec** [comment]
We discussed this. 
This is very important before we declare GA (no timeline), but we should focus on clearing up the main technical uncertainties for now (backend choice, speed, scalability, multi-repo context fetching)

**Comment by jtibshirani** [comment]
We're going to tackle this as part of the "Seamless embedding updates" project (https://github.com/sourcegraph/sourcegraph/issues/50173).

**Comment by stefanhengl** [comment]
I believe we can consider this done. Here are the relevant PRs:
- #53079 
- #52999 
- #52915 
- #52326 

These changes give us autoindex, pagination, filtering, and backlinks from repositories to embeddings jobs.

We didn't implement "Make it so you can select multiple and remove embeddings", because to the best of our knowledge, customers haven't requested this feature so far. Instead we try to automate this as much as possible. For example, we detect scenarios in which an index is outdated (incompatible format, different model) and create a new index from scratch. 

Feel free to reopen if you feel something is missing.
