### ISSUE TITLE
Add feedback thumbs up and down back in VS Code

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#50180]
- If the user is connected to sourcegraph.com, collect:
  - thumbs up/down 
  - AND the prompt ([terms](https://about.sourcegraph.com/terms/cody-notice)). We will first check if the code is public or private on a best effort basis:
    -  check if there is a git clone URL in the context repo.
      - if not, pass
      - if yes, check if it exists on sourcegraph.com
        - if not, pass
        - if yes, this is an open source repo. Log the query and context. 
- If the user is connected to any other sourcegraph instance: just collect thumbs up / down.

- `CodyVSCodeExtension:codyFeedback:thumbsUp`
- `CodyVSCodeExtension:codyFeedback:thumbsDown`

To pass the query prompts, we can use the`public_arguments` property (see Eric's thread below).

**Comment by malomarrec** [comment]
From @ebrodymoore:
> You can [search query prompts] in the public_arguments field and it would go into Amplitude attached to the search event. We used to collect all search queries so could do this the same way (unless I'm misunderstanding)

**Comment by nathan-downs** [comment]
Any data that we want to keep within the instance the user is logged into can go into the `argument` field (private data we don't want sent to our analytics database but may want to collect for the internal site admin use). Anything that we want sent into Amplitude needs to be in the `public_argument` field and shouldn't contain anything that we don't want to collect.

Both of these fields are key-value pair JSON objects that are stored in the Postgres `event_logs` table of the instance. They'll get sent as-is to Amplitude when the user is logged into dotcom, otherwise they'll be extracted and marshaled in a ping for private/managed instance users.

**Comment by malomarrec** [comment]
Note: once we've collected some data, we'll send a sample to Anthropic as per [thread](https://sourcegraph.slack.com/archives/C052QCQSL06/p1681314066107019)
