### ISSUE TITLE
app: precise code intel / batch changes support (executors require `docker` to be in the PATH)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#50192]
We learned in https://github.com/sourcegraph/app/issues/4#issuecomment-1489043922 that the PATH is not set up correctly in the macOS app bundle, as a result `docker` cannot be found and precise code intel / executors do not work.

**Comment by dgroomes** [comment]
I had found and investigated this same issue when I started using Sourcegraph App and for what it's worth, here are my notes:

* [A StackExchange answer that describes a similar problem and a workaround](https://apple.stackexchange.com/a/243946)
  * > The loginwindow process sets a user's environment. It sets the variables TMPDIR and PATH, consults Directory Services and sets SHELL HOME USER LOGNAME . PATH is set to /usr/bin:/bin:/usr/sbin:/sbin unless modified by launchd
* [A minimal Swift program (as a Bundle) that demonstrates the default `PATH`](https://github.com/dgroomes/macos-playground/blob/80e591e308bf37e93b8b19d1ff8981a0f1131504/README.md?plain=1#L72)
   * >   20:59:39: Welcome to 'macos-playground'! This message is brought to you by a program written in the Swift programming language.
     20:59:39: The 'PATH' environment variable is set to:
     20:59:39: /usr/bin:/bin:/usr/sbin:/sbin
* [My own notes](https://github.com/dgroomes/sourcegraph-playground/commit/046c1f7a6f9d3f388487465238fce7f007fc1995#diff-1a84c4895772e70e009dfae15c5b42f3c3d6600789b1a25f6cdcaa316d603c9eR31)
   * >  Failed attempt # 2: changing the Info.plist to customize the PATH via the LSEnvironment property doesn't work because only the application developer who signed the app can change the Info.plist (my weak understanding). I wound up doing the launchctl config user path trick described in the earlier linked StackExchange answer. 

I think editing the `Info.plist` is the way to go but I'm out of my depth on macOS desktop application development.

**Comment by peterguy** [comment]
Do we want to continue to use Docker containers for Zoekt, or package Zoekt in the app bundle, like we do with src-cli and git?

**Comment by slimsag** [comment]
Zoekt should get built into the main binary since it’s just Go code and
would be trivial to do so..

..but Zoekt is not really relevant here, executors **require** Docker for
precise code Intel and batch changes (the latter has users explicitly use
Docker containers in batch change specs)
-- 
Follow me on twitter @slimsag <https://twitter.com/slimsag>.

**Comment by slimsag** [comment]
With Tauri we will enable this feature: https://github.com/tauri-apps/fix-path-env-rs

which should fix this / ensure Docker is on the path as long as the user has it installed.
