### ISSUE TITLE
Diff search timing out with new gRPC errors

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#50498]
The search https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+type:diff+author:slack&patternType=standard&sm=0&groupBy=author is timing out with the following error message:

![image](https://user-images.githubusercontent.com/1976/230742488-693f83ae-6db1-471f-add8-3858347c9497.png)

And another at https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+type:diff+author:be&patternType=standard&sm=0&groupBy=author:

```
Rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8265794 vs. 4194304)
```

![image](https://user-images.githubusercontent.com/1976/230742552-5c80dfb9-1085-4d45-ad83-959d44127b93.png)

**Comment by ggilmore** [comment]
For https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+type:diff+author:slack&patternType=standard&sm=0&groupBy=author, similar behavior happens even when gRPC is disabled:

<img width="1904" alt="Screen Shot 2023-04-10 at 10 16 08 AM" src="https://user-images.githubusercontent.com/9022011/230954696-ab01bfe8-5063-4ca0-89ec-3a68675c1f10.png">

- [Trace with gRPC enabled](https://console.cloud.google.com/traces/list?tid=2ef8d175e7df1cd21a6028a452e1dd27&authuser=0&project=src-747bc765eb31a4873e4b)

- [Trace with gRPC disabled](https://console.cloud.google.com/traces/list?tid=37281c5890f12e742b89fa5d8014cb3e&authuser=0&project=src-747bc765eb31a4873e4b)

For https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+type:diff+author:be&patternType=standard&sm=0&groupBy=author, the query simply times out instead of running into a max message size issue (so, probably this specific issues is gRPC specific)

<img width="1909" alt="Screen Shot 2023-04-10 at 10 18 24 AM" src="https://user-images.githubusercontent.com/9022011/230955137-b52130d5-784f-4773-94ad-c15aac8c9f95.png">

- [Trace with gRPC enabled](https://console.cloud.google.com/traces/list?tid=8cb7e13334fe7a9cf45e4f35af8c02f3&authuser=0&project=src-747bc765eb31a4873e4b)

- [Trace with gRPC disabled](https://console.cloud.google.com/traces/list?tid=3bdf203bfd26dca75f77dc9b570fabd6&authuser=0&project=src-747bc765eb31a4873e4b)
