### ISSUE TITLE
Structural search insight always shows 0 for most recent data point

### ISSUE THREAD

**Issue by nihaals** [sourcegraph/sourcegraph#50506]
- **Sourcegraph version:** v5.0.0

#### Steps to reproduce:

1. Create a "Track changes" insight
2. Enter a structural search e.g. `lang:Python patternType:structural requests.get(...)`
3. Notice the number of results always drops to 0 in the most recent data point in both the preview and the actual insight

#### Expected behavior:

It shows the correct number of results.

#### Actual behavior:

It always shows 0 as the number of results.

For example:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/18350092/230915907-a56b2ab5-7b74-4a79-9665-d1b3ae696661.png">

**Comment by gl-srgr** [comment]
The issue is that we only [pass](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/structural/structural.go?L194) `RepoRevs` to the structural search method but if a revision is not empty string then we end up using that revision as the branch name instead of using `HEAD`, see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/searcher/internal/search/search_structural.go?L318).

Zoekt let us know before this logic when we called [`PartitionRepos`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/zoekt/indexed_search.go?L177:6) that we should be using `HEAD`, but this information is stored in the IndexedRepoRevs.BranchRepos member which we don't pass along to `runStructuralSearch`.

I have a few solutions in mind and will run them by @camdencheek

**Comment by gl-srgr** [comment]
This fix is available as of 5.0.3

**Comment by gl-srgr** [comment]
Insight for testing, prior to fix:

![Screenshot 2023-05-03 at 6 38 25 PM](https://user-images.githubusercontent.com/105310278/236094123-42612967-5e45-4de7-9a6b-b56d29104f98.png)

Same insight, reprocessed after version with fix deployed:
![image](https://user-images.githubusercontent.com/105310278/236090456-fcf824f4-6a00-438c-a6bb-6a2de046b842.png)
