### ISSUE TITLE
Customer reports of 503 errors 

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5058]
[$CUSTOMER](https://app.hubspot.com/contacts/2762526/company/407948923) is reporting sporadic 503s.

The 503s likely originate from Apache perhaps [due to this](https://serverfault.com/questions/265199/mod-proxy-returns-503-errors-even-after-proxied-service-is-back-up). It is possible there are multiple root causes that bubble up as 503s.

There are 3 deep-dive investigations tracking separate occurrences of this incident:
* The first links to this issue from the private issue tracker.
* The second is in the customer Slack channel reported on 7/31 14:24
* The third is in the customer Slack channel reported on 8/1 11:07

**Comment by beyang** [comment]
Closing this in favor of https://github.com/sourcegraph/the-oa-tasks/issues/36, since it's no longer being worked on as SWAT.

**Comment by slimsag** [comment]
@beyang I'll keep this open for tracking purposes & remove your assignment.

**Comment by beyang** [comment]
Moving out of SWAT to keep that milestone clear.

**Comment by slimsag** [comment]
## Update

After rolling out the Apache load balancer configuration changes I recommended to the customer, the issue here is fixed -- and to alert us to this type of issue in the future we are already tracking the addition of monitoring for when inter-service communication is failing: https://github.com/sourcegraph/sourcegraph/issues/4240 (I will continue proactively monitoring closely in the meantime.)

We've gone from 25-33% of requests leading to 5xx errors, to just the 1-5% of actually problematic requests now. To fix the remaining 1-5% of requests, which I believe are from heavy searches timing out (most likely from scripts), we are already tracking issue #3534 and #2865 -- both of which are top priorities for us.

## Further details

Percentage of requests that led to a 5xx error before:

- Aug 27: 33.1% of requests
- Aug 28: 24.2% of requests
- Aug 29: 33.0% of requests

Percentage of requests that lead to a 5xx error after:

- Sept 3: 4.5% of requests
- Sept 4: 2.3% of requests
- Sept 5: 1.5% of requests (day not over yet)

The remaining 1-5% are coming from two things I strongly believe:

1. Symbol searches hitting the Apache 2m proxy timeout ([which will be helped by 3.7](https://github.com/sourcegraph/sourcegraph/issues/3534)) (most likely cause)
2. Very large text searches with large `count:` parameters timing out before returning millions of results (which [will be helped by pagination](https://github.com/sourcegraph/sourcegraph/issues/2865) in 3.7) (less likely cause).

Since the primary issue here is resolved, I am closing this issue now.

**Comment by slimsag** [comment]
We received another report of this, but it was due to a different underlying cause: https://github.com/sourcegraph/sourcegraph/issues/5686

Raising zoekt-indexserver's memory from 8 -> 16 GB addressed the issue by allowing the stuck repository to index, thus preventing zoekt from pulling too much over the network. Follow up issues for us:

- https://github.com/sourcegraph/sourcegraph/issues/5686
- https://github.com/sourcegraph/sourcegraph/issues/5684
