### ISSUE TITLE
app: enable sourcegraph.com sign-in / Cody opt-in

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#50759]

**Comment by chwarwick** [comment]
@marekweb I thought you would have the most context on if this is ready to be closed.

**Comment by chwarwick** [comment]
@taylorsperry  This issue mentions a Cody opt-in is this something different than the current 

```
By using Cody, you agree to its license and privacy statement.
```

Because we will be routing cody requests though dotcom and dotcom has specific data retention policies we should make that clear to users.  It's the same as using the extension connected to dotcom but depending how the setup flow goes it may not be as clear why they connecting to dotcom and that it is related to cody.
