### ISSUE TITLE
Implement keyword search context as fallback for cody web

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#50786]
Right now, keyword based context is stubbed out in the web client. We need to bring it on-par with the VS Code extension.

**Comment by jtibshirani** [comment]
@thenamankumar implemented a prototype here: https://github.com/sourcegraph/sourcegraph/pull/51488. I compared it to ripgrep on several examples and found the ranking and performance to be worse.

I'm working on a prototype v2 that builds on Naman's work. My plan is to improve on the existing `patternType: keyword` feature (#38923):
1. Modify the parsing to ensure we don't search over too many terms. This is a big cause of slowness, since Zoekt can't efficiently execute large "OR" queries.
2. Add an experimental scoring option to Zoekt to perform BM25 (or as close as we can get :)) I found this will help the result ranking, since it's more accurate than re-ranking on top of Zoekt, and also search performance.

When we have prototype v2, the team can try it out and see if it looks promising or not!

**Comment by jtibshirani** [comment]
Update: I uploaded a prototype v2, which updates `patterntype:keyword` and adds a new scoring mode to Zoekt.
* https://github.com/sourcegraph/sourcegraph/pull/52233 
* https://github.com/sourcegraph/zoekt/pull/583

The results look decent in my testing, and it compares well to ripgrep on our test dataset:

NDCG@k | ripgrep | prototype
-- | -- | --
@1 | 0.1830 | 0.2155
@5 | 0.2921 | 0.3608
@10 | 0.3409 | 0.4178
@20 | 0.4176 | 0.5017

Proposed next steps:
* Work with @thenamankumar to integrate into Cody Web
* Gather dogfood feedback from team on performance + relevance (we need to solidify our "acceptance criteria" here)

**Comment by thenamankumar** [comment]
@jtibshirani wow this is amazing!

**Comment by mrnugget** [comment]
@jtibshirani heads up: closing this because we just discussed it in sprint planning and said it's done. Please reopen if that's false.
