### ISSUE TITLE
Return files that contain a keyword and have been modified by a specific person

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50880]
https://github.com/sourcegraph/accounts/issues/6036

[Spawned from a thread in the customer's support channel](https://sourcegraph.slack.com/archives/C02UM8A9M2R/p1678812044400949)

User wishes to search across repos for a certain keyword with files that have been modified by a specific individual.

`author:name type:diff keyword` will only return the latest author for that git diff, whereas the user is interested in the history of authors.

**Comment by gl-srgr** [comment]
Customer post from the linked slack thread:

> yes! I could use `author:name type:diff` keyword to cover some cases, but it doesn't cover this case: I modified fileA at some point, I saw something in the file that left some keyword in my mind. Another day I want to search for it, but I forgot the file name, `author:name keyword`  will help me find it.
It's a heavily used feature for me when I was in Google, to use Google's code search. I'm not sure for others though.

**Comment by gl-srgr** [comment]
From the above copied slack post the user's goal is to find one or more file matches where

- the file was previously modified by a user matching `author` criteria
- the file contents, at some revision, matches a query/pattern input such as `keyword`

I'm taking into consideration existing gitserver logic (e.g. [`commitSearcher`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/gitserver/search/search.go?L102)) and searcher logic and I have a few approaches in mind. I'm open to discuss on a call if that's easier.

#### 1.) Determine all files modified by an author with `git log --author` and search those files in indexed search

Pros: 
- If we can get a set union of file paths across all the commits from git log --author then we simply search across the indexed revisions of those files 

Cons: 
- We could miss the desired result if we only search the latest but the user's desired result is an older revision of a file (e.g. keyword is a function prefix present at the time of modification that has since been renamed). 
- our set of file paths to search will include since deleted files
- the --author arg would not match our current author keyword behavior in type:diff or type:commit search; for consistency with current author keyword we'd want to use commitSearcher logic.

#### 2.) For each file at the latest revision we get a list of all authors and if at least one entry matches our `author` keyword criteria then we search the file at the latest revision
Pros: 
- We don't have outdated file paths as mentioned in (1.) and instead we're just dealing with files represented in our indexed search.

Cons: 
- Similar to (1.) we're missing older revisions

#### 3.) Apply author match on commits with `commitSearcher` as we do now and then for each matching commit's modified files we run `git show <rev>:<file> `for each modified file and run the pattern search against the file contents
Pros: 
- We can utilize existing `author` keyword logic and `commitSearcher` logic to get files at the time of the commit. Also we get to use before and after which is not present in options (1.) and (2.).

Cons: 
- Currently we can search against the modified lines of a commit with `type:diff` search. If we have gitserver searching against the full blob then we'll ideally maintain parity with our current `standard` search type that utilizes zoekt and searcher. I'm not sure what effort and complexity this would be.

#### 4.) Apply author match on commits with `commitSearcher` as we do now and then for each matching commit we send the commit's modified files list to searcher to get unindexed search results for just those files for the specific commit 
Pros: 
- We can use existing `commitSearcher` to get modified files per commit.
- We can use searcher's [`PrepareZipPaths()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6c372eaabedbd247e7e8d9e1a61317de91f1c4ad/-/blob/cmd/searcher/internal/search/search.go?L260)  to reduce unindexed search scope to a set of file paths for each revision, and then call [`regexSearch()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/searcher/internal/search/search_regex.go?L264) as we would for a standard unindexed search.
- We can use before and after keywords to define a window the user is interested in.
- If user just wants the latest matching revision of any given file (for a given time window) then perhaps we can reduce workload by not fetching older matching revisions of that file after initial match for that file.

Cons: 
- Need to add new requests since this requires more interservice communication: frontend -> gitserver commit searcher, which has a dependent frontend -> searcher
- We'd be fetching archives of the specified file paths for each matched commit. The volume of authored commits (scoped with `before` and `after` keywords), the quantity of files modified, and the size of the files can lead to an expensive operation.

-----------

I've started working on an implementation of (4.) but since there are a lot of tradeoffs to discuss I wanted to bring this up for discussion. Again, I'm open to setting up a call to simplify and expedite discussion.

**Comment by gl-srgr** [comment]
cc @taras-yemets let me know if you have any thoughts

**Comment by taras-yemets** [comment]
@gl-srgr, thanks for the detailed options analysis! Great work!

I was initially thinking of 
- getting the list of unique files modified by the user (e.g., with `git log --author`)
- checking if the file exists at the target commit
- searching across the files at the target commit.

I think it matches what you described in the first option.
<hr>

The approach you took (4.) sounds reasonable to me, though I don't have extensive knowledge of gitserver and searcher logic. 
>If user just wants the latest matching revision of any given file (for a given time window) then perhaps we can reduce workload by not fetching older matching revisions of that file after initial match for that file

I may be missing some important use cases, but I'd expect to get the latest matching revision of a file for this kind of query.

**Comment by camdencheek** [comment]
Nice summary! I think there is a missing option here that could be promising: do a normal search, but post-filter based on the provided author. This ensures that the filter will consistently work for all search modes (HEAD, old revision, indexed, unindexed, diff search, commit search, etc.).

We do a similar thing with [code ownership filters](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@aa9ec56421fe8d7a823caf925e28336009595e7b/-/blob/internal/search/job/jobutil/job.go?L187-191). This won't be the most performant thing, but it will work consistently. 

One more note: please add a predicate for this behavior rather than reusing the `author:` field outside of commit/diff search. This has some pretty specific semantics, and it is much easier to document and explain a `file:modified.by()` than it is to explain an `author:` field in file search.

**Comment by gl-srgr** [comment]
@camdencheek Thanks for the feedback! I'm looking into the predicate approach.

Re: the `author` keyword: I was considering adding a new search `type:` that falls under the same family/within the same grouping as `diff` and `commit`. By same grouping I just mean how we distinguish them in the [docs](https://docs.sourcegraph.com/code_search/reference/queries#keywords-diff-and-commit-searches-only) based on behaviors and keywords. In this case would you be more comfortable utilizing existing `author` keyword for the new search type? Re: the implementation details we'd have `author` used within commitSearcher as it is now and we'd make no plans to change the current behavior (if we do need to change existing author behavior that'd be a significant scope change). Let me know what you think! Thanks again!

**Comment by camdencheek** [comment]
> how we distinguish them in the docs based on behaviors and keywords

I'd really like to move our query language _away_ from having so many different modes of operation. Creating a whole new search mode just for this feature feels like it's moving in the wrong direction. 

I'm being a little vague, so more concretely, take a look at some of the examples [here](https://github.com/sourcegraph/sourcegraph/issues/50539). This is the direction I'd like to go: moving top-level filters into object-scoped predicates. This way, we don't have filters that only apply to certain search modes, making it more difficult to write an invalid query. Additionally, it lets filters be composed more easily.

All that to say I'd much prefer if we implemented this as a predicate that works in all search modes rather than as a special case in a new search mode.

**Comment by gl-srgr** [comment]
That makes sense! There's certainly a non trivial commitment to supporting a whole new `type:` and would not align with object scoped predicates. I'll pursue the predicate approach and let you know if I run into blockers.

**Comment by gl-srgr** [comment]
[changelog](https://github.com/sourcegraph/sourcegraph/blob/v5.1.0/CHANGELOG.md) mentions relevant PR #53206 which merged this feature
