### ISSUE TITLE
Batch changes: force a merge past failing CI checks.

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50902]
Submitted to support channel for https://github.com/sourcegraph/accounts/issues/1789, Tuesday, January 10, 2023, by `REDACTED`: "https://github.com/sourcegraph/accounts/issues/1789 has started to take advantage of Sourcegraph's Batch Change feature. For the PRs that are created, we have CI processes that run (AWS builds, GitHub Actions, things like that). Some of these checks are required.

The changes we're making are not to production code and shouldn't be subject to the CI processes and GitHub branch protection rules. We assumed the Batch Change would be a force merge operation, but it appears to be a normal merge that is failing due to our branch protection rules.

Our last Batch Change is failing to merge on 87 out of 279 PRs. Is there anything we can do to trigger a force merge through Sourcegraph? Otherwise, we'd like to put in a Feature Request for that functionality.

If you have any questions, feel free to reach out to the shared slack channel withhttps://github.com/sourcegraph/accounts/issues/1789 (https://sourcegraph.slack.com/archives/C03UUH37SBG/p1673380044326879))

**Comment by sanderginn** [comment]
GitHub doesn't support the concept of a force merge. Users with administrator rights are able to ignore branch protection rules. There's two options here.
1. The customer adds the [bypass branch protection role](https://github.blog/changelog/2022-08-18-bypass-branch-protections-with-a-new-permission/) to a GitHub account that has been configured for global Batch Change use. This should probably be a bot/service account.
2. We have to implement a new git source/provider that just uses plain `git` instead of GitHub/GitLab/etc APIs. This would enable force merging with `git` commands.

Option 1 doesn't require any work on our side. Option 2 is a considerable amount of work that is definitely out of the paper cut territory.

**Comment by sanderginn** [comment]
I've [posted the suggestion for option 1](https://sourcegraph.slack.com/archives/C03UUH37SBG/p1692722637770509?thread_ts=1673380044.326879&cid=C03UUH37SBG) in the customer channel. Let's see what they say

**Comment by sanderginn** [comment]
Closing this as the customer [reported this is no longer an issue for them](https://sourcegraph.slack.com/archives/C03UUH37SBG/p1692727499024029?thread_ts=1673380044.326879&cid=C03UUH37SBG)
