### ISSUE TITLE
search results on sourcegraph.com don't make clear which repos were searched or how many

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5091]
Here is an example of search results:
![Screen Shot 2019-08-05 at 1 52 06 PM](https://user-images.githubusercontent.com/15530/62494497-88332800-b788-11e9-9bc6-229c0eac6d1e.png)

There is no indication of how many repositories were searched, and no link to find out which ones.

**Comment by ijt** [comment]
@christinaforney what do you think?

**Comment by nicksnyder** [comment]
In a private deployment, there is an implied "search all of my company's code", otherwise Sourcegraph wouldn't be useful.

For Sourcegraph.com it isn't clear that we don't search "all of GitHub" for example. Specifically for sourcegraph.com I think it might be worth updating the current product message to look something like this:

![Screen Shot 2019-08-05 at 2 04 54 PM](https://user-images.githubusercontent.com/754768/62495188-08a65880-b78a-11e9-80c0-b4a39c9f6386.png)

**Comment by ijt** [comment]
@nicksnyder, even on these private deployments, users don't necessarily know the current state of "all the code connected to the instance" so adding this could still be useful to them. Two use cases come to mind: 1) new employees who don't know what all the repos are yet, 2) repositories getting added or removed means existing users might need to know the current state.

**Comment by ijt** [comment]
Even so, what you're proposing does have the advantage of being crystal clear about the context on sourcegraph.com.

**Comment by christinaforney** [comment]
I think this is useful messaging for sourcegraph.com, I'm not certain about private instances though. 

Considerations for @ijt 's points:
>1) new employees who don't know what all the repos are yet, 
I don't think telling them here is the appropriate place to discover this. They will learn what repos are available based on search results shown to them and company onboarding. Hopefully as we improve search ordering these results can be ordered in the most relevant way.

>2) repositories getting added or removed means existing users might need to know the current state.
I think this is a separate status issue - in reality, it would be pretty shocking to us if, for example, sourcegraph/sourcegraph ceased to exist on sourcegraph.com. The add or removal situation should really be a notification of some sort indicating system health, rather than a prompt below the search results.

**Comment by nicksnyder** [comment]
I agree with Christina on both of the above points. I don't think it is important to show what repositories that we searched over for customer instances because it is implied that the answer is "all".

For example, Google doesn't tell you which websites it searched over but you trust it is searching over all of them.
