### ISSUE TITLE
add extra argument indicating if commit signing is enabled for codehosts

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#50944]
We have the [`CreateBatchChangesCredential`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/batches/resolvers/resolver.go?L1116) mutation for creating credentials for Batch Changes.

Let's extend that mutation to create signing keys for codehosts.

**Comment by courier-new** [comment]
This mutation is currently very code-host-centric: the result is supposed to be a valid credential configuration for a single code host that matches the required `externalServiceKind` and `externalServiceURL` args passed to the mutation. My understanding is that for this commit signing MVP, a user will create a single SSH/GPG key to use across _all_ code hosts. If that's the case, it seems to break the intentions/expectations of `CreateBatchChangesCredential` a bit, and IMO may be better served as its own mutation. But I'd love to hear more of your thoughts on this to make sure I'm understanding this right. Why in particular do you feel like extending `CreateBatchChangesCredential` was the clearest choice here?

**Comment by courier-new** [comment]
We resolved this question during our sync last week: Since we concluded we will reuse the same SSH key used for code host authentication for commit signing as well, we *can* extend the mutation and use the key that we were already generating for every user credential behind the scenes. In addition, we will add another column to the credentials table to indicate whether or not a user has opted in to commit signing.
