### ISSUE TITLE
github oauth: only request "repo"  oauth scope when using github per-user repo permissions

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#5111]
https://github.com/sourcegraph/sourcegraph/blob/ac604356549e7835bbcf1feab0da27bf3ea65b56/enterprise/cmd/frontend/auth/githuboauth/provider.go#L58-L63

Our GitHub OAuth implemenatation always requests the [repo](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) scope, even though it's only used [by the github per-user repository permissions feature](https://github.com/sourcegraph/sourcegraph/pull/920#issue-229863413). (Note that GitHub's OAuth model doesn't allow us to request separate read / write permissions per-repository)

We should strive to request only the minmium permissions that Sourcegraph actually needs. We should **only** request the "repo" OAuth scope when the per-user repoisotry permissions feature is enabled in the external service configuration. 

cc @sourcegraph/core-services

**Comment by keegancsmith** [comment]
What happens when:
1. No ACL support enabled.
2. User logs in via oauth.
3. Admin adds ACL support.
4. User uses Sourcegraph.

Do we need to store extra state? How does the upgrade path work?

I'm hoping we would just do the current requests and they would fail with a specific error code. Then we switch the user to some sort of oauth upgrade flow?

I'm also unsure how to triage the importance of this issue? Which customer complained about this?

**Comment by nicksnyder** [comment]
Relevant Slack thread: https://sourcegraph.slack.com/archives/CLZ3BK0Q6/p1565118728000200

@ggilmore is this a blocking issue for the customer?

**Comment by nicksnyder** [comment]
I am moving this out of a milestone because it doesn't sound like a quick change.

**Comment by tsenart** [comment]
@ggilmore: Which customer requested this? Can you add the HubSpot link? If it's not super relevant anymore, can we close until it resurfaces?

**Comment by tsenart** [comment]
Closing until it resurfaces.
