### ISSUE TITLE
RFE: Allow HTML files to be optionally rendered in the UI

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#51122]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01P4R0RZH9/p1682430663863569)

#### Feature request description

When viewing an HTML file, allow the user to optionally have the file rendered.  It would also be nice if the rendered view had a distinct URL so it could be shared.

**Comment by camdencheek** [comment]
So, this is pretty easy to do in its simplest form. I took a look, and we can sanitize the HTML like we do markdown and render it with like a 2 line change.

The problem is that rendered raw HTML usually looks pretty garbage. With Markdown, there is a known intended structure with headings and we can provide meaningful styling, but HTML usually relies on external styling to make it look good and make sense, and we can't know what CSS was intended to apply to any given HTML file.

Example:

![Image](https://github.com/sourcegraph/sourcegraph/assets/12631702/6c651034-93f7-45a4-88f1-c6fbbfaa8fed)

For browsing code, I expect unrendered HTML to be much more generally useful. So I don't think we should show rendered HTML by default like we do markdown, and I'm not entirely convinced it will be a good user experience to allow showing a rendered version at all.
