### ISSUE TITLE
Update dev instructions to recommend not checking out in GOPATH

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#512]
Now that this repo works outside of GOPATH we should update the readme to recommend not checking it out in GOPATH. Checking it out in GOPATH causes problems https://github.com/sourcegraph/sourcegraph/pull/482#issuecomment-432815491 and editor code intelligence not to work because it doesn't use Go modules by default.

**Comment by keegancsmith** [comment]
FYI I am using the GOPATH checkout since there are still many tools I rely on that don't work in a modules world. Namely go-rename and guru (for references). godef can also be a bit iffy. I just manually run `GO111MODULES=on go mod vendor` so that the GOPATH tooling works. But I think for the enterprise repo due to layout and submodules it won't work on GOPATH at all, but for just OSS it works fine.
