### ISSUE TITLE
Repo from GitHub external service not being cloned

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5124]
I wanted to have https://github.com/felixfbecker/test-phab-staging on k8s.sgdev.org.
I tried adding the repo to the existing GitHub external service through `repos`. It would update successfully, but the cloning indicator would show all repos are cloned, and the repo would not be in the repositories list.

I also tried adding an extra GitHub external service with
```json
"repos": [
    "felixfbecker/test-phab-staging"
  ]
```
and changing it to 

```json
"repositoryQuery": [
    "felixfbecker/test-phab-staging"
  ]
```

https://k8s.sgdev.org/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjMw

None worked and I have no idea where to see why.

**Comment by unknwon** [comment]
(Disclaimer: I don't know the cause) I'm not sure when did it clone, but it is there now :thinking: https://k8s.sgdev.org/github.com/felixfbecker/test-phab-staging

**Comment by mrnugget** [comment]
The problem is that the syncing process is really, really slow on k8s.sgdev.org and it takes a long time for the new repository to end up in the repos table.

See the previous issue:
* https://github.com/sourcegraph/sourcegraph/issues/4911

In the next release we'll concentrate on improving the sync performance and making the whole site-admin experience better when you have tens of thousands of repos.

**Comment by tsenart** [comment]
@mrnugget: Let's create a parent issue for "streaming syncing".
