### ISSUE TITLE
Codebase inference triggers when cody is not being used

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#51349]
![Image](https://user-images.githubusercontent.com/7814431/235652945-c5bcb303-815c-413c-8d7e-be4e318ac36b.png)

It seems that Cody is constantly looking for the git clone url, but there are scenarios (like the example this user shared) that Cody shouldn't be trying to infer the codebase until it is focused.

Doing so it will display errors not relevant to the user.

**Comment by mrnugget** [comment]
@beyang can you take a look at this if you have the time?

**Comment by abeatrix** [comment]
This should be taken care by https://github.com/sourcegraph/sourcegraph/pull/51274 and include in release v0.0.10
We are now logging the error in console [instead of using popup ](https://github.com/sourcegraph/sourcegraph/pull/51274/files#diff-c6daa76d2e92815b3c46180419f9887c11ab74d6902f98d288f8e48472cf401cL728)during the auto detection step as we should limit system pop up to errors relevant to the system.
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@306cce682150e32d0a2e8d1e3ad3a96b12d9110f/-/blob/client/cody/src/chat/ChatViewProvider.ts?L685

**Comment by mrnugget** [comment]
@abeatrix does that mean that you're currently trying to confirm whether it's fixed or not, or that it is fixed?

**Comment by abeatrix** [comment]
@mrnugget It was fixed only for that specific error, but this new PR should now fix the root issue: https://github.com/sourcegraph/sourcegraph/pull/51714
