### ISSUE TITLE
Ripgrep search can be very slow and cause unresponsiveness

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51631]
We've received reports from customers that using ripgrep can lead to really slow context fetching, and generally freeze up their local machine:
* https://sourcegraph.slack.com/archives/C052CJK4EBY/p1683324738463519?thread_ts=1683244257.995039&cid=C052CJK4EBY
* https://sourcegraph.slack.com/archives/C0W2E592M/p1683579674793519

**Comment by jtibshirani** [comment]
Some ideas:
* Apply the same [file exclusions/ safeguards](https://github.com/sourcegraph/sourcegraph/blob/main/enterprise/internal/embeddings/embed/embed.go#L163) we do for the embeddings service.
* Make sure we're limiting the number of threads ripgrep can take. Even if context fetching takes a while, it should never freeze up the user's workspace.
* Find some slow queries and profile them.

**Comment by abeatrix** [comment]
Update: a couple of users have reported the fix we introduced in v0.1.3 has made Cody usable for them. Cody doesn't freeze up anymore but it is still slow. 

We should consider limiting the numbers of files for each search. Will investigate further and report back

https://discord.com/channels/969688426372825169/1107642007410724864/1108701822237024256

**Comment by abeatrix** [comment]
We have updated the Params for our rg settings and that have resolved the immediate issue where local machine froze. we’ve limited how many thread the rg process a machine can use and exclude unimportant files so I don’t think there is anything more we can do because there are just so many variables and factors.

Like what kind of computer are they on
How big is their codebase
What happen if the work space has multi repos
Etc 

We have also fixed the useContext to none issue so users can now turn off keyword search if it's not working for them, so I believe we can close this issue for now, as we have solved the unresponsiveness problem, and think of an alternative where rg is not a suitable option for some users in another issue.

If anyone disagrees please feel free to reopen the issue.
