### ISSUE TITLE
Improve performance of browser extension so we can remove the 50 file limit in PRs

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#5172]
Our browser extension is [currently limited to providing code intelligence on 50 files](https://github.com/sourcegraph/sourcegraph/pull/5170) due to [performance issues on PRs with a large number of files](https://github.com/sourcegraph/sourcegraph/issues/4994).

We need to fix the underlying performance issue (suspected cause is recreation of every code view when a new one is added) so we can remove this 50 file limitation.

**Comment by lencioni** [comment]
👋 I'm the person who reported the problem here https://github.com/sourcegraph/sourcegraph/issues/4994

Admittedly, I don't know anything about how this browser extension works or things that you have tried or are already doing, so take these ideas with that lack of context in mind.

I have two thoughts for things that might be worth trying to improve performance, and I'm wondering if either or both of them would help?

1. Have you considered any strategies to lazily provide code intelligence, or to only provide code intelligence for files that are currently visible inside the viewport? I think using IntersectionObserver could work well here.

2. Are you able to move work off the main thread? [Comlink](https://github.com/GoogleChromeLabs/comlink) might be worth looking at to help with WebWorkers. (Although poking around it looks like you are already using WebWorkers with worker-loader https://github.com/sourcegraph/sourcegraph/blob/c36a98202a3913de5a8a92389dbe3641f53b2416/shared/src/api/extension/worker.ts)

Of course, if you can also reduce the amount of work being done that seems worth doing as well!

**Comment by nicksnyder** [comment]
Is this done?

**Comment by felixfbecker** [comment]
Fixed by #5541
