### ISSUE TITLE
cody bug: links to files are escaped after being fully rendered and show up as HTML

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51768]
This is on 0.1.1. See:

<img width="343" alt="screenshot_2023-05-11_10 11 34@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1185253/224cc794-edd5-4986-8969-7da97f002a09">

This only happens once it's fully "streamed" in I think:

https://github.com/sourcegraph/sourcegraph/assets/1185253/8cbe334c-b157-4e33-b357-9b83aed9e66f

@philipp-spiess assigning to you since I think it's related to your latest changes in the parser

**Comment by philipp-spiess** [comment]
Some context:

So this happens when we do hallucination detection inside inline strings like this in markdown:

```
`./README.md`
```

I’m confused why this is not working, I specifically tested for this case again after Roks comment here: https://github.com/sourcegraph/sourcegraph/pull/51576#discussion_r1187557402
Will look into it.

**Comment by philipp-spiess** [comment]
<img width="896" alt="Screenshot 2023-05-11 at 12 29 47" src="https://github.com/sourcegraph/sourcegraph/assets/458591/af334243-7a30-4f4b-af90-ec8f5e2bc86e">

omg i forgot to push it 😭
