### ISSUE TITLE
llmproxy: Talk about zero retention and error messages

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#51998]
https://sourcegraph.slack.com/archives/C05497E9MDW/p1684243137128289

**Comment by bobheadxi** [comment]
cockroachdb does nice redaction for us which already works for Sentry reports - yesterday, we touched briefly on this topic and agreed we don't want PII in our logs either. I [have a PR up](https://github.com/sourcegraph/sourcegraph/pull/53109) to adjust this better so that we're not redacting _everything_, and what I'm thinking next is to build in error redaction into `sourcegraph/log` - I [spiked this yesterday](https://github.com/sourcegraph/log/tree/error-redaction) and I think we can make it work. The core idea: log fields are very obvious in what you are logging, and we can catch PII logging in review. Error messages, however, are magic strings that may have all sorts of stuff composed of layers of helpers, so our biggest PII risks are in errors.

Some concerns:

* our multierror is home-grown (by me sorry :sweat_smile: ), and looking at it again I am not sure it implements cockroachdb error redaction correctly. there's a lot of unwrapping behaviours and interfaces in cockroachdb, for now I don't think we have many usages of our multierrors so just keep an eye out there
* `internal/observation` converts some errors to strings based on filtering behaviour, which will expose redacted data. We only use this for background jobs though so we should be safe

Discussing in Slack, we agreed that redaction in logging is ultimately this is low-priority, and being careful with logging/tracing/sentry is sufficient for now.
