### ISSUE TITLE
Cody for JetBrains: Publish on JetBrains marketplace

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#52006]
Publish on JetBrains marketplace: With README, install instructions, screenshots / vids.

**Comment by olafurpg** [comment]
Some progress towards this issue

- we just published 3.0.0-alpha.1 to the "Alpha" channel. This release is still too rough to kick-start internal dogfooding, but it's nice to have a published version so that we can start using the plugin ourselves to develop the plugin :D 
- submitted a request to make the publish token available in CI so that we can automate releases on git tag push https://github.com/sourcegraph/infrastructure/pull/5026

**Comment by vdavid** [comment]
Submitted!
