### ISSUE TITLE
Cody: Hallucination detector marks existing directories as false

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#52117]
Steps to reproduce:

- Ask `Where is saml auth defined` (sourcegraph codebase)
- You can see `doc/admin/auth/saml/` is highlighted as false when it exists https://docs.sourcegraph.com/admin/auth/saml

![image](https://github.com/sourcegraph/sourcegraph/assets/68532117/2323399e-760a-44c3-a979-7b60628bd65f)

**Comment by SuperAuguste** [comment]
I was showing Cody to someone and they remarked this as well; there are two big issues:
- It doesn't match directories that end with `/` in text
- It will eat up punctuation, for example `The current directory is /a/b/c.` will try and find directory `/a/b/c.`, which doesn't make sense

Looking at the code the second point seems intentional, the first not so much. I think a good solution for the second is just testing with and without punctuation and only marking a hallucination if neither is matched.
