### ISSUE TITLE
UX: Admin creates Batch Change GH App

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/sourcegraph#52220]
![image](https://github.com/sourcegraph/sourcegraph/assets/59381432/79276337-68ed-4d16-9256-fac13f9f9870)[Lofi Wireframes](https://excalidraw.com/#json=Qpr6zSlOBQX-WJp6uTFmv,1HT51ahdaIlM_vlenpkU0Q)
1. Admin BC Settings page has a new "Commit signing integrations" section for Batch Change specific GH Apps
2. Read all batches code host connection nodes, but only GitHub for now allows commit signing
3. Clicking `Create GitHub App` kicks off the logic from `<CreateGitHubAppPage />` to create a GH App. We won't show the form since we will prefill the values. Fill out the name field with "Batch Changes {GitHub-Instance-Name} App", the url is the GitHub instance. Change the [`default_permissions`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx?L42) property `content: 'write'`. Add a `?domain=batches` query param to the GitHub call.
4. Auth happens through GitHub integration
5. BE will re-direct user back to `/site-admin/batch-changes` page (#52475)
6. This page should now have an updated node for the code host connection with the GitHub App related actions

**Comment by courier-new** [comment]
Some minor suggestions to expand upon the plan you've outlined!

1. "Commit signing tokens" -> "Commit signing integrations"
2. At some point we should also query the `commitSigningConfiguration` field I suggested in [the other issue](https://github.com/sourcegraph/sourcegraph/issues/52484) to know whether or not a given code host connection already has commit signing configured. But we could also leave this for the edit flow issue instead.
3. I agree we should reuse the component for that page but maybe it's still a batch change route, like `/site-admin/batch-changes/new-github-app`. Otherwise I think it could get confusing since the URL looks like you've "left" the batch change settings section. This would also enable us to render the page with custom props, such as a custom page title/description and setting the placeholder name to "Batch Changes App", without having to infer it based on a URL parameter from within the component itself, which just tends to be a lot less future-proof.
4. 👍
5. In fact, we could take it a step beyond just prefilling the URL -- we could hide the form input field altogether and just hold onto the URL to send along with the normal create requests. We wouldn't want the user to modify it anyway, or else it wouldn't actually create a GH App for that specific code host connection.
6. 👍 
7. We also got a sense from Milan of [how we'll need to update the middleware](https://sourcegraph.slack.com/archives/C01LJ9DK8ES/p1684771551059309?thread_ts=1683706478.832879&cid=C01LJ9DK8ES) to handle the various GitHub callback URLs. I know you know this, just adding the link here so it's easy to find again. 😛
8. 👍
9. 👍

**Comment by st0nebraker** [comment]
So essentially combine step 3 & 5? I'm cool with that! Makes sense to take away any user input there since it's not needed @courier-new
