### ISSUE TITLE
JetBrains: implement Figma design for Chat

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#52824]
The design https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/IntelliJ?type=design&node-id=3-14235

**Comment by szymonprz** [comment]
Regarding the message bubbles with the message content including the code snippets for example, there are two ways to do that, one way is to convert markdown from the response to html and then to modify this html to include some additional things like buttons to copy some content etc. and the second way is to transform this response with markdown directly to swing and idea components with which our plugin will have a look & feel more integrated with the IDE itself. 

Now I will try to do some basic parsing of the markdown to build the swing ui components instead of building the html

**Comment by vdavid** [comment]
@szymonprz do we need anything to mark this as Done?

**Comment by szymonprz** [comment]
Last pr should mark this issue as done and we can open new issues for next things like: Recipes panel and button to reset current conversation
