### ISSUE TITLE
Root cause concurrencyLimit errors

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#53398]
Context: https://sourcegraph.slack.com/archives/C05ABRRGB0B/p1686602381494679

**Comment by bobheadxi** [comment]
Resolution:

1. roll out revision, was broken
2. roll back
3. roll out cache versioning revision, healthy
4. roll back to step 1's revision which was unhealthy
5. it's now healthy????

we took redis dumps along the way and it seems somewhere between 3 and 4 the v0 cache entries finally updated correctly, and have TTLs set so that they will expire tomorrow. We're now (finally) deployed up to https://github.com/sourcegraph/sourcegraph/commit/b67c4a75c73f5849684a21c7ceff1b899edda221

I suspect this was a case where the new revision didn't claim the worker lock and the old revision didn't "really" spin down, which we somewhat observed in traces:

![image](https://github.com/sourcegraph/sourcegraph/assets/23356519/3003144a-d244-4c5c-93a7-0d8623d531f3)

https://github.com/sourcegraph/sourcegraph/pull/53416 adds some tweaks to help us diagnose this better in the future, but for now I think we should just leave things as-is and depend on the new cache versioning in the future to make sure this doesn't happen again.

cc @unknwon
