### ISSUE TITLE
Indexed symbol search: definitive performance regression

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5364]
#### Workaround

When upgrading to Sourcegraph v3.7.1, set the following in your site configuration to avoid opting into the new symbol search implementation:

```
"search.index.symbols.enabled": false,
```

#### Problem

After we introduced indexed symbol search in v3.7.1, both symbol and text search performance appears to have regressed. This issue is to investigate and fix that.

Note in the following that:

1. All tests ran solely on their own for 17 minutes each (one test cannot affect the other).
2. The name field indicates the exact search query that was being ran.
3. The `P95 change` (orange) column indicates the percentage change in 95th percentile query duration after migrating from Sourcegraph v3.5.2 to v3.7.1. Positive numbers are performance regressions, negative numbers are performance gains.

All queries were ran against theoa.sgdev.org over 10h period using [vegeta](https://github.com/tsenart/vegeta) and the CSV comparison report was generated using [kingkai](https://github.com/slimsag/kingkai). The instance has 12,981 repositories In total cloned and indexed fully, and 42GB of data was generated by vegeta (happy to upload this somewhere if anyone is interested). I eliminated all external factors that I could not contribute to the code / design itself, i.e.:

- All repositories were completely cloned and reindexed.
- The "before" column actually indicates when Zoekt was constrained in CPU resources and Jaeger was enabled, the "after" column is actually after me doubling the CPU availability count and [disabling Jaeger due to proven performance concerns with it](https://github.com/sourcegraph/sourcegraph/issues/5363). Given this, I expected to see substantially better perf, but did not.

Results: https://docs.google.com/spreadsheets/d/12YpKTP58FOIUkFqrdBotlDJHyinu7-itiY-Hd0xuCoY/edit#gid=2136071970

**Comment by keegancsmith** [comment]
This is surprising. My best guess is we are using more ram due to storing symbol information offsets in memory now (previously we never ran ctags). This leaves less RAM for the FS cache => more often paging in memory when reading the posting lists.

But that is just a guess. Best thing to do is run a profile with a regressed pod. What exactly is the CPU and RAM limits/requests btw? Any chance we were indexing while these tests were running (in either case).

Another thing is you don't specify `index:only` in the symbol search, which means we may be falling back to the old symbol search in the new version. However, the more important regression is how this has affected normal indexed text search.

An interesting thing to first rule out is to run the new zoekt-webserver, but only on v15 indexes. And see if we still have a perf regression. This may indicate some other surprising change that happened, rather than it being due to symbols.

@kzh can you comment on this and create a plan of action. We can sync sometime this week and do some investigation together if you like.

I suggest we have a disk snapshot of v15 and v16 indexes so we can test both relatively easily. Alternatively we can temporarily run indexed-search twice, and just update the `svc/indexed-server` to change which endpoint it points to.

**Comment by keegancsmith** [comment]
Plan sounds good. I'd caution against making the vegeta concurrency too high, since profiles become harder to read. Use the lowest QPS rate with a regression. cc @sourcegraph/core-services

**Comment by tsenart** [comment]
> report was generated using kingkai

Oh hello there, new tool, I like it!

**Comment by slimsag** [comment]
> I'd caution against making the vegeta concurrency too high, since profiles become harder to read. Use the lowest QPS rate with a regression.

Definitely agree, I plan to redo these load tests with this actually to eliminate that concern since our behavior can be quite erratic with even 1 QPS on very slow / heavy searches.

I found @tsenart added support for sub-1 QPS rates in https://github.com/tsenart/vegeta/pull/423 last night which I've found quite useful -- i.e.:

```
vegeta attack [...] -rate=0 -max-workers=1 [...]
```

maybe I'll send a PR to note that in vegeta's README.

**Comment by tsenart** [comment]
> I found @tsenart added support for sub-1 QPS rates in tsenart/vegeta#423 last night which I've found quite useful -- i.e.:

It's not sub-1 QPS. It simply sends requests as fast as possible, when `-rate=0`. `-max-workers` allows you to define a maximum concurrency level.

**Comment by slimsag** [comment]
yeah, that was poor wording on my part -- thanks for the clarification. I said sub-1 QPS because I was thinking specifically about `-rate=0` `-max-workers=1` with requests of consistent duration >1s, in which case it is sub-1 QPS -- but I see now that was a roundabout / poor way to explain it.

**Comment by kzh** [comment]
Update: I'm currently working on a bunch of memory optimizations for Zoekt symbol search. This regression is probably due to what Keegan mentioned about increased paging since there are now more contenders for memory (being the symbols data). This regression can probably be easily fixed by increasing memory, but before falling back to that option, I want to see if these memory optimizations will do the trick or at least significantly lessen the necessary memory increase.

Some random observations that I found interesting:
- The very first search after `zoekt-webserver` is started (after `kubectl delete pod <indexed-search pod>`) will always be slow (ex: 10s). I think this is due to all the indexes initially being loaded via mmap which acts somewhat like a cache (initially empty) in virtual memory that does lazy fetching (paging) from disk. Afterwards, repeating that search will be a lot faster (ex: ~0.5s) since the relevant data has already been fetched from disk. However, if in the future, there is a greater demand for memory, the current memory in the cache will be invalidated to make room.

**Comment by slimsag** [comment]
Update: Kevin and I spent a while re-running some independent benchmarks, it appears as though the cases where performance looked worse was entirely due to factors I hadn't accounted for in my benchmarks. After accounting for the too-high QPS, avoiding running the requests in parallel, and a few other things, it does appear perf is generally the same.

I'll post a further update here tomorrow with numbers from an overnight load test.

**Comment by slimsag** [comment]
Took me longer than I thought to make sense of the numbers, but I am finally confident enough in them to close this out. Definitive isn't so definitive, and load testing is _H.A.R.D._.

Final load test comparison between v3.6.2 and v3.7.1: https://docs.google.com/spreadsheets/d/1oPzePjD8YLrnppLm3nk46h48_Cxipz4_QqRMBYaIOYQ/edit?usp=sharing

Quoting my summary in there:

> - Large symbol searches roughly 20x faster, performance and throughput on-par with indexed text search.
> - Some 0-2s symbol searches have worse throughput, but better non-truncated results
> - Text search performance roughly the same, marginally worse in some cases

Thank you @kzh and @keegancsmith for you diligence here in helping me look into this (and sorry this turned out to be a waste of your time!) -- I've learned a lot here so I can do this better in the future and have some ideas to make our search more load-testable seamlessly I'll propose later.
