### ISSUE TITLE
Cody: Support auto config cody.codebase for remote workspace

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#53728]
RE: https://sourcegraph.slack.com/archives/C05AGQYD528/p1687239045934679

Reported by warren: 
> some of our users seem to be working on local only / ssh projects using vscode plugins like - https://code.visualstudio.com/docs/remote/ssh. This messes with cody determining context for certain files. Currently I'm just telling folks to use cody.codebase to set context between uses.

**Comment by deepak2431** [comment]
@abeatrix Are you looking into this? If not, I can try to fix this up.

But can you add some more context about this issue? As I use remote SSH for development and use Cody in it. When I open the settings there, I can configure the Cody settings under remote SSH, too because I can see there three different options `User`, `Remote SSH`,  and `Workspace`.

**Comment by abeatrix** [comment]
Hey @deepak2431 thanks for looking into this 🙇🏻‍♀️ i think this will be covered by the upcoming support of multi repo context so I'd suggest hold off on this for now! 

Moreover, I also couldn't reproduce the issue using remote codespace so I'll need to gather more info from Warren as well 😁

**Comment by deepak2431** [comment]
@abeatrix Got it. Good to hear that it will be covered in a multi-repo context!
But, as said I am not 100% clear of what this issue is.

**Comment by DaedalusG** [comment]
Apologies folks I jumped the gun on this report. The users that had reported this error to me were both working on projects that dont use `git` and for which `cody.codebase` wasn't set. Since cody uses `git remote get-url origin` at the workspace root to determine context they were seeing the `not indexed` indicator.

Closing as an erroneous report
