### ISSUE TITLE
Assigned ownership flow QA

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#53737]
1. Watch [assigned ownership flow](https://loom.com/share/52a68074b7b34b16a129287e8c590ddf?sid=5be8cef4-387c-4145-bbb5-a43090fe320d)
2. Go to [S2](http://sourcegraph.sourcegraph.com)
3. Look at [list of engineering teams](https://sourcegraph.sourcegraph.com/teams/engineering/child-teams), and see if you find your team there. In a later step you can use these teams as owners.
4. Use search to find directories/files that your team owns.    Note: `-f:has.owner()` will eliminate those with ownership coverage.
4. Go to repo/directory view and click _Show more_ on Own card
   ![repo/directory page with show more button on own card highlighted](https://github.com/sourcegraph/sourcegraph/assets/153410/8d135353-c333-4f43-a1e5-18bc39b9757d)
6. Add owner you would like or promote an inferred person to an owner:
    ![ownership drilldown page with add owner button highlighted and make owner button highlighted](https://github.com/sourcegraph/sourcegraph/assets/153410/e03df00a-06b7-44e0-b07d-de4105a1ac3e)
7. Go back to search results and see if you can find more directories to assign ownership to.

Please give us feedback on this flow. What works? What does not? Give us a comment below. Please like and subscribe ⏯

**Comment by cbart** [comment]
Feedback from a run-through with @indradhanush:

- team name letter-avatar in teams view could use all caps
- assign any owner button missing in blob view panel
- on S2 own analytics page rendering does not work #53735
- on p4 history and own bar errors

**Comment by vdavid** [comment]
Even though I couldn't make this work this time, I find it totally cool and imagine it'll be instanely helpful for teams!
Extra thanks for initiating this dogfooding effort and describing the process in such a detailed way both in a vid+text. 👌 

Feedback:
- I'm on the Cody team, didn't find my team, so I went for stuff of my old team, IAM. → Suggestion: add Cody team.
- I've tried to assign the IAM team as an owner for [this file](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody/src/services/AuthProvider.ts#tab=ownership) (the examples were all about directories, but the instructions said "find directories/files that your team owns" and I only wanted to set ownership for this file, not the entire dir) but didn't find a way to do it. Tried the [docs](https://docs.sourcegraph.com/own) but didn't find it there either. → Suggestion: make the UI clearer for this use case.

I hope this helps :)

**Comment by cbart** [comment]
Thank you for this feedback @vdavid! Bunch of aspects you mentioned are already being addressed by mighty @sashaostrikov, but I'll run through the list again to make sure all the gaps you pointed are filled.

THANK YOU FOR TAKING THE TIME TO DO THIS 🔥

**Comment by jhchabran** [comment]
+1 to what @vdavid said, the screenshots really made it easy for me to just get started and add things. 

- I managed to add ownership to files, clicked on file's ownership tab -> add owner 
- We're reorg'ing ship, so that was the time to create a new team :) 
- Added a bunch of folders with our stuff, was glad to see we can have multiple owners too 😊 

I'm extremely hyped by being able to tag and map all we own, it's going to be crucial for our team future to properly say what we own and do not. 

The thing I want the most at this point is to be able to simply commit a codeownership file in each folder, our stuff is really spread out deep so, submitting them manually is only good for a few obvious folders, and can only get my team so far when it comes to ownership. 

I'm sure this will come and you know about this usage pattern 🙏

**Comment by sashaostrikov** [comment]
Thanks everyone!
I'm closing this ticket, as we had a good participation and the QA week is over.
