### ISSUE TITLE
Cody: Stop generating button doesn't works perfectly

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/sourcegraph#53798]
The stop generating button still generates the response after cancelling it before the response starts.
CC: @abeatrix 
See this video for the behaviour:

https://github.com/sourcegraph/sourcegraph/assets/44617923/59f2c5f8-8397-43a8-b493-3989f036c391

**Comment by abeatrix** [comment]
Have a PR for the fix! Thank you so much for letting us know <3

**Comment by deepak2431** [comment]
@abeatrix Awesome, Saw your PR it would fix it.

**Comment by deepak2431** [comment]
@abeatrix @philipp-spiess I still see some awkward issues with this Stop Generating button if I cancel it before any response starts. It shows an error message and sometimes completes the response. Might be some regression which needs to be fixed.

https://github.com/sourcegraph/sourcegraph/assets/44617923/79f07170-d5e1-4de9-a6e4-7f5cd1429456

**Comment by abeatrix** [comment]
@deepak2431 thanks for letting us know! this sure looks like a regression since we were able to confirm the issue was fixed in one of the previous pre release. Since this looks different than the issue which was reported originally, do you mind filing a different issue so our team can pick it up for next sprint? Philipp and I are on PTO for the next two weeks but someone from our team should be able to get on it shortly 😄

**Comment by deepak2431** [comment]
@abeatrix Sure, I can create a new issue and tag someone who can look into it.

And, Congrats to you, @philipp-spiess, on the 5.1 release. It was for sure big with a lot of consistent work efforts from the team :)
