### ISSUE TITLE
App: Make tauri sign-in url appear less alarming (due to parameter named "secret")

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53849]
Internal [feedback](https://sourcegraph.slack.com/archives/C05AQ5LPAH1/p1687346186948969?thread_ts=1687346066.270919&cid=C05AQ5LPAH1). 

![Image](https://github.com/sourcegraph/sourcegraph/assets/43555476/1b887d52-488f-44de-98b8-050e0e5db09b)

**Comment by marekweb** [comment]
Renamed the issue to better describe the problem.

The problem is that the parameter name, "secret", draws attention to itself. But it's not actually leaking anything that is secret.

We can't omit the line entirely from the logs because we need to read it from the logs in order to launch the app frontend.

We could rename `secret` to something less alarming, like `s`
