### ISSUE TITLE
Bug with duplicated repos in setup

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#54003]
There are some bugs when a user adds the same repo more than once. Reported by @almeidapaulooliveira [here](https://sourcegraph.slack.com/archives/C04PE4H6XGT/p1687466620203379). 

## Steps to reproduce:
- Launch the application and proceed to the repository adding functionality.
- Add the same repository multiple times; observe that the application does not prevent this duplication.
- Try adding a different repository and notice that the previously added repository gets duplicated.
- Attempt to remove the duplicated repositories; observe that sometimes they can be removed, and sometimes they cannot.
- Leave some duplicated repositories and proceed.
- Navigate to the context selector and attempt to find the duplicated repositories; observe that the context selector does not show the duplicated repositories.
- Navigate to the application settings and confirm that the duplicated repositories do not appear.
- Add the same repositories again, duplicated.
- Return to the context selector and try finding the newly added (and duplicated) repositories.
- Observe that the repositories can now be found in the selector.
- Try adding the found repositories to the context, and observe that the application does not allow it.

Video recording:
https://github.com/sourcegraph/sourcegraph/assets/64257673/1112d695-affa-429a-872f-6a6ec94a6230

**Comment by vovakulikov** [comment]
This should be fixed with today's merged PR from @fkling, you still can add more than one identical repository in the setup flow, but you're able to delete duplicates through the UI delete button. UI doesn't have a problem removing duplicates. 

Based on this, we can leave this issue as a follow-up for the original problem (ideally, we shouldn't be able to add duplicate repositories, but to do this, we also need to add error UI; unfortunately, it will take more time than we have now before release, I suggest to close this and add error UI in the post-release) 



https://github.com/sourcegraph/sourcegraph/assets/18492575/ad03aff0-5227-47c5-a3cc-b377c50d63a0
