### ISSUE TITLE
Teach users about the new chat and history buttons in the VS Code welcome guide

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/sourcegraph#54231]
User feedback is showing people are missing the panel header buttons (new chat, chat history, and "..." containing settings etc), as they're only shown on hover on the top Cody pane header.

The Welcome guide should include this to help people discover these:

https://github.com/sourcegraph/sourcegraph/assets/153/3cb3e79f-220c-4121-bcf9-91773bfce6ff

Going forward, I think we should test moving away from using those native VS Code panel buttons that only show on hover, and follow Gitlens’ pattern of button bar inside the panel (which could use a quickpick):
<img width="262" alt="Screenshot 2023-06-27 at 10 01 40 am" src="https://github.com/sourcegraph/sourcegraph/assets/153/4758df3e-0001-4684-a880-c1838da9b490">

**Comment by umpox** [comment]
@toolmantim Do you have a proposal of how we can include this in the welcome guide?

Some options:
1. Include this as part of a walkthrough video. Will mean we have to record a new video though
2. Update the walkthrough copy text to mention the icons directly. Unfortunately[ it seems we can't use these icons easily in our markdown](https://github.com/microsoft/vscode-discussions/discussions/179).
3. Change these buttons to text instead of icons, e.g.:
<img width="500" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/9516420/a7938dad-58a8-4820-9a1f-21bc18d20f4a">

**Comment by umpox** [comment]
Super fast 🐎 😁
