### ISSUE TITLE
Enable automated build of Cody App for Windows

### ISSUE THREAD

**Issue by nelsonjr** [sourcegraph/sourcegraph#54323]
## Problem to solve

Automate the build, test, and distribution of Cody App for Windows

## Measure of success

Changes to sourcegraph/sourcegraph are bundled into a ready-to-distribute Windows MSI, pushed to GitHub and other appropriate release points for Windows.

**Comment by burmudar** [comment]
Had a meeting with Nelson where we went over the windows build.

* `build-windows.sh` builds the `sourcegraph-backend` and the final `Cody.exe`
* digitally sign `sourcegraph-backend` and digitally sign `Cody.exe`
* build custom MSI - we ignore the one built with Tauri, since the one we built manually has some extra bells and whistles.
* a windows specific manifest is currently produced which has the signatures and urls ready. It's similar to the current manifest produced by the release pipeline for `Cody App`

### The plan going forward

#### Phase 1
[ ] Get buildkite running on the windows machine Nelson is using for the current windows build
[ ] Get current release pipeline to utilize the machine. Can be a simple step like `echo`
[ ] 1. Build `sourcegraph-backend`, `Cody.exe`
[ ] 2. Sign artifacts

### Phase 2:
[ ] Windows Artifacts get added puslibhed along with the other platform artifacts as part of release
[ ] Windows manifest is produced
[ ] `sg app update-manifest` handles publishing and updating of the windows manifest
[ ] DotCom updater endpoint handles reading the windows manifest seperately

**Comment by burmudar** [comment]
App has been deprecated
