### ISSUE TITLE
Port to Bazel: go:generate schema/gen.go + internal/database/gen.go

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#54820]

**Comment by burmudar** [comment]
So I did some quick exploration on this because when you look at the command `go:generate` executes (`gen.sh`) it invokes `sg  migration` ... which seems easy enough to replicate in bazel...

I added the following rule
```starlark
load("//dev:write_generated_to_source_files.bzl", "write_generated_to_source_files")
genrule(
    name = "generate_squashed_sql",
    srcs = ["."],
    outs = [
        "frontend/squashed.sql",
        "codeintel/squashed.sql",
        "codeinsights/squashed.sql",
    ],
    cmd = """
    outs=($(OUTS))
    # $(location //dev/sg:sg) migration squash-all -skip-teardown -db frontend -f $${outs[0]}
    touch $${outs[0]}
    """,
    tags = [
        "requires-network"
    ],
    tools = [
        "//dev/sg:sg"
    ],
    visibility = ["//visibility:private"]
)
```

I tried putting it at various places:
- `migrations`
- `migrations/gen`
- `internal/database/`

But when you invoke the rule you'll get:
```
bazel run //migrations/gen:generate_squashed_sql
WARNING: Cannot run target //migrations/gen:generate_squashed_sql: Not executable. Will continue anyway
ERROR: /Users/william/code/sourcegraph/dev/sg/BUILD.bazel:135:10: in go_binary rule //dev/sg:sg: cycle in dependency graph:
    //migrations/gen:generate_squashed_sql (14ff45410d16754e299393b2e70a99f9afc28bdda933f2102d19859c4e50aa78)
.-> //dev/sg:sg (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //dev/sg:sg_lib (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //internal/database/migration/store:store (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //internal/oobmigration:oobmigration (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //internal/version/upgradestore:upgradestore (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //internal/database:database (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //internal/database/dbtest:dbtest (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //internal/database/migration/schemas:schemas (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //migrations:migrations (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //migrations:frontend/squashed.sql (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
|   //migrations:generate_squashed_sql (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
`-- //dev/sg:sg (4dbd3ed3513383b60b608ee3a172eaf9468aede81d9a89e972d7638ef09f9c51)
WARNING: errors encountered while analyzing target '//migrations/gen:generate_squashed_sql': it will not be built
INFO: Analyzed target //migrations/gen:generate_squashed_sql (1 packages loaded, 0 targets configured).
```

**Comment by burmudar** [comment]
Got most of the migrations working with bazel. Initially with just a `genrule` and then also with a rule implementation. I quite like the rule implementation but it is probably overkill considering there would (at this point time) only be 3 users of the `migration` rule.

Getting it work comes with a price though - I had to set `no-sandbox` and also `--action_env=PATH=$PATH` so that the host path environment get propagated properly. We need access to the host environment so that `createdb` can be used which `sg migration` calls out too.

At the moment there is no builtin way to pass in `--action_env` automatically, which makes integration the rule with `write_all_generated` difficult.

I tried various ways to get the host environment PATH variable to propagate properly, but ultimately it seems the `cli` flag `--incompatible_strict_action_env` we pass in our `.bazelrc` makes it so that `bazel` will always not use the host environment PATH. When this flag is removed, the host path is picked up but this is a _nasty_ approach.

#### Proposal 1
On linux systems, the standard path _should_ be ok since `createdb` and other pg tools should be available in `/usr/bin`. On MacOS we would have to append `/opt/homebrew/bin` to the path so that brew installed binaries get picked up.

We have Nix users, and on their systems we would encounter a problem with this approach. There is no hardcoded path we can use since the binary can be at some random path in the nix store. It is therefore, that going this approach might need some more investigation.

#### Proposal 2
Look into whether we can download the pg tools binaries from somewhere and then download them with `http_archive` in bazel. This will make this more heremetic and not rely on anything in the host system. The problem is that theres binaries are dynamically linked and it might be difficult to link them statically or even just to get a readily available place where these binaries are hosted.

#### Proposal 3
There might be other pg tool binaries that migration relies on, but if it is just `createdb` look at what `createdb` is doing - can't we replicate it with just normal queries like `CREATE DATABASE` and `GRANT ROLE`. If we can just do it in straight SQL we can elminate the dependency on `createdb` and the `sg migration` is self contained.
