### ISSUE TITLE
Port to Bazel: sg lint: dev/check/go-dbconn-import.sh

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#54836]
1. Evaluate why this is useful in the first place 
2. Decide how to port it to Bazel or simply scrap it 
3. Do the work
4. ???
5. Profit

**Comment by Strum355** [comment]
1. Evaluate why this is useful in the first place

Quoting the script:
> This script ensures pkg/database/dbconn is only imported by services allowed to directly speak with the database.

Certain entrypoints (e.g. blobstore, executor etc) should be protected/forbidden from accidentally or purposely importing anything that transitively may depend on initializing a connection to the database, which would cause issues in deployment but not locally.

2. Decide how to port it to Bazel or simply scrap it

I've been looking into this and hit a snag when it comes to determining (with a nogo linter) what main packages we want to run the dependency graph check for, and whether the main package is in the allowlist:
for all packages, `(*golang.org/x/tools/go/analysis.Pass).Pkg.Path()` returns a value e.g. `github.com/sourcegraph/sourcegraph/internal/database/dbconn`, EXCEPT for the `main` package, where the path is `main`. `(*golang.org/x/tools/go/analysis.Pass)` doesnt seem to provide us with a way to determine a similar path name for the `main` packages, which is a bit of a pickle

**Comment by Strum355** [comment]
For anyone nerd sniped into the problem, checkout https://github.com/sourcegraph/sourcegraph/tree/nsc/nogo-dbconn and run e.g. `bazel build //cmd/executor` (or some other main package). Observe the files in /tmp/bazel_log/ (where we write a file for each package because capturing stderr is hard). Youll have files such as `github.com_sourcegraph_sourcegraph_cmd_executor_internal_config.txt`, but not a `github.com_sourcegraph_sourcegraph_cmd_executor.txt`, that one will be `main.txt` instead :pensive:
