### ISSUE TITLE
Function of extension-contributed buttons is not clear

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#5488]
I just noticed that on Sourcegraph.com the buttons above a file also show up as text:
<img width="838" alt="Screen Shot 2019-09-06 at 08 39 30" src="https://user-images.githubusercontent.com/1185253/64406347-df773180-d081-11e9-81b9-98636d317e16.png">

See here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go#L12:41

I don't think that's the intended behavior, since it doesn't show up on sourcegraph.sgdev.org: https://sourcegraph.sgdev.org/sourcegraph/enterprise@093a16521df58e6c49cf70e6a4832137e740265a/-/blob/enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go

(@lguychard: I don't know who to assign this to, feel free to re-assign!)

**Comment by lguychard** [comment]
@mrnugget this the default styling of buttons contributed by extensions ("Blame" by `sourcegraph/git-extras`, "Discussions" by `sourcegraph/code-discussions`, "Owner" by `sourcegraph/code-ownership`). They're not displayed on sourcegraph.sgdev.org because these extensions aren't activated for your user profile on sgdev.

Did you not expect these buttons to be present (maybe you only expected them in the browser extension)? Or do you think they should be styled differently?

**Comment by mrnugget** [comment]
> Did you not expect these buttons to be present (maybe you only expected them in the browser extension)? Or do you think they should be styled differently?

Hmm, yes, I would've expected them to be styled differently. 

But I think what threw me off the most and made me suspect that this is a bug is that I've been clicking all three of them without anything happening:

![bar](https://user-images.githubusercontent.com/1185253/64508250-417fa300-d2dd-11e9-8f47-94ea8fdcfd99.gif)

(Just to be clear: I'm clicking on these buttons/links in the gif).

There is no feedback on
1. what is supposed to happen when I click on one
2. whether it worked or not
3. whether I need to click on something or not

**Comment by lguychard** [comment]
OK. For context:
- "Owner", "Blame" and "Discussions" are contributed by extensions.
- "Owner" is just a label (and is not styled as a link). It displays the code owner on hover. It would usually display it inline (eg. `Owner: @mrnugget`, or `3 owners`), but this file happens to be in the special case where the name of the single owner is too long, so it's only displayed on hover. That label should probably read `1 Owner`, though.
- "Blame" triggers the display of git blame decorations. Blame decorations are only shown on selected lines (the link title, shown on hover, is `show/hide Git blame line annotations`):
![image](https://user-images.githubusercontent.com/1741180/64508833-b1daf400-d2de-11e9-8ba3-b52a6a096fe1.png)
- "Discussions" triggers the display of inline code discussions if they exist (the link title is "show/hide inline discussions):
![image](https://user-images.githubusercontent.com/1741180/64509154-6b39c980-d2df-11e9-8053-315f67eaf8d5.png)
- The line wrapping & history icon buttons you also click on are stock and present on all code views (as are other icon buttons in that toolbar)
- Line wrapping only takes effect if the viewport is narrow enough (as it would in a normal editor):
![image](https://user-images.githubusercontent.com/1741180/64509338-cc619d00-d2df-11e9-8c24-dcd1449f03a7.png)
- History is shown in a panel view at the bottom of the file:
![image](https://user-images.githubusercontent.com/1741180/64509466-0fbc0b80-d2e0-11e9-85a9-458425399161.png)

Things that could've prevented confusion:
- A more complex tooltip than just a link title on buttons contributed by extensions, possibly showing which extension contributed the button, and linking to this extension's docs.
- Not displaying the "Discussions" button, or explicitly making it disabled, when there are no inline discussions to display on the current file.

Overarching issues:
- The display of contributed action items to the code view toolbar is, I feel, an unsolved UX/design problem. Too many contributed actions make the toolbar messy (especially in the browser extension). The current styling makes it non-obvious that the items are buttons, but making them look more "button-like" would be very awkward/ugly in the webapp with our stock button styles.
- This could be solved preferring to use the command palette, rather than contributed action items, but the command palette is not discoverable / non-intuitive for users.
- It is generally difficult to discover,  from the UI, what was contributed by which extension, and why.

cc @christinaforney to put this on your radar as future improvements we should think about.

**Comment by mrnugget** [comment]
Thanks for this great reply, @lguychard :clap: 

>     * "Blame" triggers the display of git blame decorations. Blame decorations are only shown on selected lines (the link title, shown on hover, is `show/hide Git blame line annotations`):

I have to admit that I knew this (or: I realized it after clicking on a few things), but wanted to bring the point across that it's hard for a new user to make sense of this. Especially if they've used the "Blame" button on GitHub, where the whole layout changes as soon as you click on it.

**Comment by felixfbecker** [comment]
With the improvements I made in the past week I consider this solved ✅
There were a lot of individual issues raised in this thread, so I'll try to reiterate and address them all individually here to make sure I didn't miss any:
- _Styling is inconsistent (they look like text)._
  - I improved the general styling in #9503 to make them stand out as buttons and added icons in https://github.com/codecov/sourcegraph-codecov/pull/48 and https://github.com/sourcegraph/sourcegraph-git-extras/pull/109.
  - I fixed the "pressed" state of the Discussions toggle in https://github.com/sourcegraph/sourcegraph-code-discussions/pull/21. Note though that discussions were always experimental and [is not a feature we want to invest in further](https://github.com/sourcegraph/sourcegraph/issues/9649), so not the same bar for quality can be expected when this extension is installed by a user. It's not good of course to have this in the extension registry as something maintained by us and we will consider removing the extension too when we remove the rest of the code, but given it has to be manually installed I think this is not _as_ big of a concern.
- _Function of action items is not clear._
  - I think the proper way to communicate the function of action items is a tooltip. These were already there, so I looked at the specific tooltips we have for the action items mentioned:
    - **Blame toggle**: The tooltip didn't make it clear that it only works on selected lines. I made this explicit in the tooltip in https://github.com/sourcegraph/sourcegraph-git-extras/pull/112 (this is configurable BTW with the setting `git.blame.decorateWholeFile`)
    - **Discussions toggle**: I think the tooltip is as good as we can do.
- _Nothing happens when clicking the buttons._
  - There can always be situations where toggling some UI does not actually result in any immediately visual change beyond the visual feedback on the button. We could of course show an additional notification like "Blame toggled" or "Blame toggled, but there are no selected lines" etc., but I think that is too intrusive. I think this is fine if the tooltip communicates the function so that the state is _intuitive_. Addressing individual action items:
    - **Blame toggle**: I think this is intuitive now that the tooltip explains it only works on selected lines.
    - **Discussions toggle**: I think it is intuitive that nothing would happen upon toggling discussions when there are no discussions in the file. The pressed state was fixed (see above), so there is visual feedback now.
    - **Code owners**: This extension didn't have an action command defined, which is actually not valid according to our extension schema. I thought about the best way to fix this, and decided to give it an action that takes you to the resolved line of the CODEOWNERS file that sets the applied rule in https://github.com/sourcegraph/sourcegraph-code-ownership/pull/30
    - **Line wrapping toggle**: I think it's intuitive that this would not result in a visual change if none of the visible lines overflow.
    - **History toggle**: I confirmed this pops open the history panel correctly (I can't tell if this was actually clicked in the gif or what might have been wrong).
