### ISSUE TITLE
Initial setup should ask for license key early

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#54971]
The intial setup flow takes over the entire screen and unless you skip it, you don't get to configuring anything just yet. I just configured a few code hosts and now am getting errors, because without a license key (that you cannot have set at this stage), you can only add one private repository. 

<img width="1015" alt="Screenshot 2023-07-14 at 20 15 15@2x" src="https://github.com/sourcegraph/sourcegraph/assets/19534377/3aa1a9c5-ccab-4509-8511-612ec9d7eb30">

/cc @sourcegraph/source

**Comment by erzhtor** [comment]
So, because there is a chance that we go with a different direction of admin onboarding and not using existing setup wizard, @kopancek and I have decided to work on the core logic of checking whether certain configuration is pending/requires some actions. 

I didn't want to change this issue title/description and created another https://github.com/sourcegraph/sourcegraph/issues/55665, which I will swap in this sprint/week. 

This ticket can be handled once we have clear UI/UX on a setup checklist.

**Comment by meglynst** [comment]
See designs: https://github.com/sourcegraph/sourcegraph/issues/55641
