### ISSUE TITLE
External service button label is confusing

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#54974]
![image](https://github.com/sourcegraph/sourcegraph/assets/19534377/f08f63b0-ab54-40c3-8de1-ab75fd7048b5)

I'll let this speak for itself

/cc @sourcegraph/source

**Comment by BolajiOlajide** [comment]
This one's tricky because we only display the `View` label instead of the `Edit` when that connection can't be edited. This is true for configurations created from a file using the variable `EXTSVC_CONFIG_FILE`.

So technically, the label there is `VIEW` because when you click it you go to the `Edit` page but in`read-only` mode.

![CleanShot 2023-07-15 at 15 27 25@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/80a2c9e9-fa05-4c2f-86cf-020780de759c)

**Comment by eseliger** [comment]
ah, I see, but it led me into thinking that there's no "other" view mode, the one that is the actual view mode 🤔

**Comment by mrnugget** [comment]
Can we hide the button then if it's not editable? Or will that confuse users?

**Comment by BolajiOlajide** [comment]
Created a [short demo](https://www.loom.com/share/078578fc8b4e4464b6590ab0dc986f90?sid=e13fbeed-1313-48d7-afd8-fb8e2d0381df) for this to share with the rest of the gang.
