### ISSUE TITLE
Natural language search

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#55105]
Spike: Consider natural language search in app. We probably need to better expand on what that means.

**Comment by cbart** [comment]
Figure out:

- what's already happened here
- how can we benefit from work that has already been done
- is this an app feature? or just something we can include in app?

@thenamankumar FYI

**Comment by cbart** [comment]
For what it's worth - overheard that there were two projects:

- Magical search - this was translating a natural language query into a sourcegraph query; I think the decision was not to continue on this
- Natural language search - in Job Fair in Q3

**Comment by thenamankumar** [comment]
Hey @cbart so beginning of Q2 we played with building Magical Search experience which utilized teaching LLM about the SG Query Language and then asking it to convert the human query into SG search query. I performed that operation well, but the usecases were limited due to the obvious limitations of the SG search itself. It didn't seem magical enough, given in natural language users have higher expectations and can literally ask anything which SG search not necessarily have capability to answer. So I don't think there is anything which we can re-utilize from the previous experiment to implement the ideal Natural Language Search for Q3. 

Now about Natural language Search: 
1. What works on App can definitely be implemented for Web (not the other way around), so lets not keep Natural Language Search limited to App. Also we have multiple times more users on Web than App. Though I am not sure of the scope of the PRFAQ. 
2. There are 2-3 ways of doing natural language search:
   1. Embeddings: 
      - Perfect for App's usecase with limited no. of repos to support. 
      - For web, you need to limit the scope to certain repos manually because performing embeddings search over 100K repos is not possible AFAIK.
      - In its current form even embeddings are limited to just code snippets and does not include any meta data like commits, diffs, ownership, precise code-intel and all.
   2. Keyword search powered by zoekt. 
      - Not possible on App as there is no zoekt there.
      - Works for web. Can support higher scale (I assume) than embeddings but lower quality of results.
      - A good fallback when repos do not have embeddings generated. 

Anyways the ideal solution will be to use combination of embeddings + keywords + code intel, may be not for v0 but eventually. 

Also if we want to quickly experiment and test the current quality of search powered by embeddings, I have the prototype ready which I can get out in 1-3 days. https://www.loom.com/share/6be1bedacda14486b015ae83defbdb3a

p.s. @camdencheek knows much more than I do.
