### ISSUE TITLE
No Access-Control-Allow-Origin sent from GraphQL API on sourcegraph.com

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5517]
This breaks the Gitlab native integration, because it cannot fetch the user configuration from sourcegraph.com. Is there any reason why we wouldn't allow any origin to make a GraphQL request? Not sure if this is a code issue or a config issue on sourcegraph.com.

![image](https://user-images.githubusercontent.com/10532611/64567485-32184e00-d30d-11e9-858c-b1836703a8f7.png)

**Comment by keegancsmith** [comment]
These sort of security issues are a blindspot for me, I do not understand them. I'll defer to someone else who has experience in this area to make the call on what to do here. Please add me back if I need to spend time researching this and make a decision :)

**Comment by mrnugget** [comment]
I think the reason we don't use `Access-Control-Allow-Origin: *` is because we required authentication in the API. But you cannot use the wildcard [with credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Directives)

We _could_ set `Access-Control-Allow-Origin` to the `Origin` supplied in the request. We could also combine that with a whitelist (say: only gitlab/bitbucket/github). (But since the Gitlab extension also runs on self-hosted Gitlab instances, I don't think a whitelist is possible.)

Since our API is public and we already offer a CLI tool to access it, I don't see a big reason to not do it. (Except, of course, with browsers being able to send requests to Sourcegraph instances, it's easier to do a DDoS)

**Comment by slimsag** [comment]
> We could set Access-Control-Allow-Origin to the Origin supplied in the request.

FYI, we have this capability already.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/cli/http.go#L147-148

**Comment by slimsag** [comment]
The main reason to not allow any origin to make requests to Sourcegraph is to prevent cross-origin attacks, of course. We should _NOT_ allow this.

For example, if I run https://attacker.com and you visit it, I can make GraphQL requests to Sourcegraph.com authorized under your account to steal your email address, delete users if you are an admin, and all sorts of other fun things.

What we can do is pick and choose which domains / origins have the right to make GraphQL requests, such as how we whitelist requests made by the browser extension's origin.

**Comment by tsenart** [comment]
What's the resolution here? Is there an action to be taken? Doesn't seem this is going to make it for 3.8 so removing from the milestone.

**Comment by 1am3r** [comment]
This is still an issue in our installation.
Is there any fix for it? We're running Sourcegraph 3.10.0

**Comment by slimsag** [comment]
Hi @1am3r -- can you please file an issue for what you are facing exactly with details? This issue is most likely not your actual issue (which I suspect is a more general question of how to configure the GitLab native integration)

**Comment by slimsag** [comment]
@felixfbecker I am going to close this issue given I have answered the original question above that we cannot do this:

> Is there any reason why we wouldn't allow any origin to make a GraphQL request?

https://github.com/sourcegraph/sourcegraph/issues/5517#issuecomment-530102702

As noted in my response, we can pick and choose which domains / origins have the right to make GraphQL requests, but cannot whitelist all origins as it would be a security vulnerability. I believe we have likely already worked around this given that we have launched the GitLab native integration already.
