### ISSUE TITLE
Gitserver GC logic potentially not working

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#5522]
- **Sourcegraph version:** Sourcegraph.com

The kubernetes/kubernetes repo was loading extremely slowly on sourcegraph.com. Stephen tried running `git gc` on the repo and it took a very long time, enumerating 140k objects in 3 minutes. He fixed the slowness by re-cloning the repo.

See original slack thread here: https://sourcegraph.slack.com/archives/CHPC7UX16/p1568075963065700

**Comment by keegancsmith** [comment]
Thanks, I'll take a quick look into the underlying issue here. Maybe there is something we can tweak in the disk cleaning logic.

**Comment by keegancsmith** [comment]
Took a look into this:
- We reclone every 45 days roughly.
- I can't find evidence of this not working in the logs. I see other repos recloning
- Kubernetes was last recloned on the 10th of September. 
- prometheus is not exporting metrics from gitserver

Action items:
- Reclone more aggressively in the case of git detecting too many loose objects.
- prometheus targets gitserver

Rather than reducing the interval, I think its likely better to just be more aggressive with fast moving repos. Reason I am hesitant to reduce days is the long tail of repos do not need this behaviour (and in fact, we could maybe avoid recloning them for even longer?)

**Comment by keegancsmith** [comment]
Prometheus metrics added in https://github.com/sourcegraph/deploy-sourcegraph/commit/722a63772eaab91dfdd58f2c89677e5b1ecf8a54
