### ISSUE TITLE
Remove github-proxy

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#55290]
Remove github-proxy and all references from the docs and from any deploy-sourcegraph* repo.

- Remove mentions of `GITHUB_BASE_URL` everywhere
- Implement redsync based locking in github clients: https://github.com/sourcegraph/sourcegraph/pull/56485
- Remove github-proxy code: https://github.com/sourcegraph/sourcegraph/pull/56485
- Remove github-proxy from deployments:
  - Cloud controller
  - https://github.com/sourcegraph/deploy-sourcegraph/pull/4268
  - https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/942
  - https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/49
  - https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/348
  - https://github.com/sourcegraph/deploy-sourcegraph-docker-customer-replica-1/pull/49
  - Any other repos?
  - Add to main repo changelog
  - Add upgrade notice to 5.3: https://github.com/sourcegraph/sourcegraph/blob/main/doc/admin/updates/kubernetes.md
- github-proxy set the IdleConnTimeout to 30s, stating the following:
  ```
  // Use a custom client/transport because GitHub closes keep-alive
  // connections after 60s. In order to avoid running into EOF errors, we use
  // a IdleConnTimeout of 30s, so connections are only kept around for <30s
   ```
- We sometimes see ErrTaken errors in S2
- Consider tuning back the logger.Error statements to logger.Warn

/cc @sourcegraph/source

**Comment by eseliger** [comment]
What to work on before the release:

- We want to increase the number of tries to see ErrTaken errors less frequently - maybe investigate why there's a limit of retries anyways? Should we instead use context deadlines? 
- We sometimes see ErrTaken errors in S2 - We downgrade those to warnings, they are not an error since we best-effort lock here
- Consider tuning back the logger.Error statements to logger.Warn

**Comment by daxmc99** [comment]
Hello! Are we planning to remove this service on cloud as well? 
Seeing as how work is already underway, we could follow an "accelerated" cloud launch process 
(go/cloud-launch). It would be really impactful for the cloud team to understand how this change impacts our github rate-limit architecture. 

We would like to understand how this might impact our cloud customers and what alerting we can safely drop. 

cc @sourcegraph/cloud

**Comment by eseliger** [comment]
Hello hello!

Yes, the idea is that after the 5.2 release we start removing the service from all deploy methods, dashboards, and so forth.  For 5.2, it remains part of it (due to time) but it will be useless.

> It would be really impactful for the cloud team to understand how this change impacts our github rate-limit architecture.

Instead of using a separate service, we now use a federated locking mechanism that is based on `redis-store`. The locking will also be best-effort. Small redis downtimes should not affect functionality.

> We would like to understand how this might impact our cloud customers and what alerting we can safely drop.

Anything around the github proxy service can be removed. We added new prom metrics for the GitHub locker. [See here](https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fsourcegraph&branch=main&file=monitoring%2Fdefinitions%2Fgithub.go&editor=VSCode&version=2.2.16&start_row=8&start_col=1&end_row=8&end_col=1)

Does that answer your questions for now? 
We will come back to you when the docker service is actually being ripped out
