### ISSUE TITLE
Exhaustive search interface

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55455]

**Comment by keegancsmith** [comment]
@Piszmog I haven't read the code insights code yet (will tomorrow). I think that has the potential to make big changes to how I think about this. So take this with a grain of salt. However, I thought I would propose some code now to start the discussion. After designing a bit I realise it will likely change a lot after reading how code insights works again. However, I like having taken the time to think from first principles.

I am thinking about what interface would be useful for the worker to use. To me it seems like there are two main things the worker needs to ask of search:

1.  break search into atomic units (a search per repo@branch)
2.  search a unit and give results back in csv

I am biasing the design to be csv based to simplify. Additionally I assume the worker takes care of using the search units correctly and storing the outputs/etc. This design also needs to handle resuming, even after process restart. This is why I am thinking exposing some sort of atomic units.

```go
type Backend interface {
  // NewSearch parses and minimally resolves the search query q. The
  // expectation is that this method is always fast and is deterministic, such
  // that calling this again in the future should return the same Searcher. IE
  // it can speak to the DB, but maybe not gitserver.
  //
  // I expect this to be roughly equivalent to creation of a search plan in
  // our search codes job creator.
  //
  // Note: I expect things like feature flags for the user behind ctx could
  // affect what is returned. Alternatively as we release new versions of
  // Sourcegraph what is returned could change. This means we are not exactly
  // safe across repeated calls.
  NewSearch(ctx context.Context, q string) (Searcher, error)
}

// UnresolvedUnit represents zero or more revisions we need to search in a
// repository for a refspec. This can be inferred relativley cheaply from
// parsing a query and the repos table.
//
// This type needs to be serializable so that we can persist it to a database
// or queue.
type UnresolvedUnit struct {
  // Repository is the repository to search.
  Repository api.RepoID

  // RefSpec is something that still needs to be resolved on gitserver.
  RefSpec string
}

// Unit represents the smallest unit we can search over, a specific repository
// and revision.
//
// This type needs to be serializable so that we can persist it to a database
// or queue.
type Unit struct {
  // UnresolvedUnit is where this Unit got resolved from.
  UnresolvedUnit

  // Revision is the resolved revision.
  Revision api.CommitID
}

// Searcher represents a search in a way we can break up the work. The flow is
// something like:
//
//   1. UnresolvedUnits -> just speak to the DB to find the list of repos we need to search.
//   2. ResolveUnit -> speak to gitserver to find out which commits to search.
//   3. Search -> actually do a search.
//
// This does mean that things like searching a commit in a monorepo are
// expected to run over a reasonable time frame (eg within a minute?).
//
// For example doing a diff search in an old repo may not be fast enough, but
// I'm not sure if we should design that in?
//
// We expect each step can be retried, but with the expectation it isn't
// idempotent due to backend state changing. The main purpose of breaking it
// out like this is so we can report progress, do retries, and spread out the
// work over time.
type Searcher interface {
  UnresolvedUnits(context.Context) ([]UnresolvedUnit, error)

  ResolveUnit(context.Context, UnresolvedUnit) ([]Unit, error)

  Search(context.Context, Unit, CSVWriter) error
}

// CSVWriter makes it so we can avoid caring about search types and leave it
// up to the search job to decide the shape of data.
//
// Note: I expect the implementation of this to handle things like chunking up
// the CSV/etc. EG once we hit 100MB of data it can write the data out then
// start a new file. It takes care of remembering the header for the new file.
type CSVWriter interface {
  // WriteHeader should be called first and only once.
  WriteHeader(...string) error

  // WriteRow should have the same number of values as WriteHeader and can be
  // called zero or more times.
  WriteRow(...string) error
}
```

**Comment by keegancsmith** [comment]
After watching the code insights sync recording and reading the doc on insights backfilling I think the direction of the above idea gels with what @coury-clark also thought of at first.

Code Insights has this concept persistent repository iterator. In the design above UnresolvedUnits would be the call you do which gives you the persistent repository iterator. The above design introduce a resolved unit, which in the "Code Insight parlance" would then be something like a revision iterator. IE we likely need some sort of persisted state where we can report back per repo@revision errors/progress/etc. This likely would also be its own worker job.

But I think following Code Insights lead and designing the state we persist to match what we want to report to the user is key. IE I think this feature will win or fail on the confidence we give in users around errors/progress/retries/etc.

So I like the above search interface, but maybe we should use less abstract names. But maybe one can start building against the above interfaces something which implements the persisted iterators/etc? WDYT @Piszmog

### Raw notes from Insights Backfilling / Scheduling

-   [Insights Backfilling / Scheduling](https://docs.google.com/document/d/1KA60kOJqJDGQcmXsGm7Fr6LBLKjXg_F-4lJsQKgV8KE)
-   [scheduler - sourcegraph/sourcegraph - Sourcegraph](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/internal/insights/scheduler)

They have two worker queues, one to analyze a new insight and setup jobs and another to actually run the searches. This seems like good design and we should copy it. There is a chance if we decide resolving revisions as slow it could be part of the first job or maybe part of another 3rd worker job. IE a target use case is searching all branches.

For `newBackfillHandler` the main IO work done is calculating the set of repos to search and enqueuing the subsequent jobs.

For `inProgressHandler` it is some nice code mostly using the iterator abstraction described later + executing a plan on each item. Nice stuff that seems very applicable to exhaustive. The code also looks good :)

The `PersistentRepoIterator` seems reuseable. It stores an array of repository IDs in postgres with a cursor and list of errors (by repo id). The code also seems to be in good shape for re-use, although some refactoring would need to be taken to use a new table/etc.

Right now I was thinking of storing which revisions to search as part of iteration as well, but we can possibly do both. IE a repo iterator and a revision iterator? That would be the most trustworthy but not as simple as a single slice. It all depends if we expect a resolving the set of repo@revisions to be able to be done in request or if we want to break up that work as well.

A con to the model mentioned was that because they serially work through the set of repos throughput is super slow. But the user experience was really good due to that. This seems like the right tradeoff for exhaustive as well. Additionally within this model it feels like we can tweak for performance.

Overall atleast straight up copy pasting to success from code insights seems like a good strategy. In cases where it makes sense to refactor and share we do that, but I would focus on functionality before code reuse.

**Comment by Piszmog** [comment]
Yea, I have been bouncing around the design of Code Insights and Batch Changes (my background). I think Code Insights makes the most sense to do.

Batch Changes is very similar to Insights, except having an iterator BC creates a new worker job in the DB (which sounded like an initial route that Insights thought about but didn't want to clutter the DB).

What BC does is,
1. Creates an initial workspace job
2. When the workspace job is handled, it calls the streaming API to get the list of repos/workspaces
3. Creates a new entry in the DB as an "execution" job
4. The execution jobs get worked on by a worker (executor in this case, but uses the worker framework under the hood)

The BC approach make sense because of the Executor piece - since jobs are being sent to a separate service to do work, it makes sense to track each workspace/repo separately. Like Insights, you do get metrics like errors/progress/times/etc on that repo/workspace level (and rollup to the top level job that started it all).

The BC approach feels valid to me as well but since we don't want to pass this something like Executors to run, I feel the Insights iterator approach is a bit cleaner.

**Comment by Piszmog** [comment]
I have an [Excalidraw](https://app.excalidraw.com/s/4Dr1S6qmmY7/23EDPGr7yAC) that I am making to help compare BC and Insights

**Comment by Piszmog** [comment]
> So I like the above search interface, but maybe we should use less abstract names. But maybe one can start building against the above interfaces something which implements the persisted iterators/etc?

Yea, I agree. I think we should use names that directly correlate with what it is doing. When I was digging thru the Code Insights functionality, I had a tough time following along since I was not use to the jargon.

> They have two worker queues, one to analyze a new insight and setup jobs and another to actually run the searches. This seems like good design and we should copy it. There is a chance if we decide resolving revisions as slow it could be part of the first job or maybe part of another 3rd worker job. IE a target use case is searching all branches.

> Right now I was thinking of storing which revisions to search as part of iteration as well, but we can possibly do both. IE a repo iterator and a revision iterator? That would be the most trustworthy but not as simple as a single slice. It all depends if we expect a resolving the set of repo@revisions to be able to be done in request or if we want to break up that work as well.

I was wonder about that too - tracking the revisions. I don't yet know enough about search to know if tracking the revision was something to do as well.

I was thinking the initial work was to simply build the list of repos (like BC and Insights). Then if we need to figure out the revisions and track those, that should be a further broken down process - determine the revisions only when we start on the repo.

A thought I am having is what does concurrency look like in this model? In the case of Insights, it is a bit easier since there is one iterator to track - making concurrency easier. But when we introduce another iterator that tracks a specific repo's revisions, do we have N revision iterators per repo that we are concurrently processing? If so, should re reuse the revision iterators to minimize rows to the DB table?

I have an [Excalidraw](https://app.excalidraw.com/s/4Dr1S6qmmY7/23EDPGr7yAC) with some possible solutions for what this flow looks like (it include BC and Insights to help compare).

> A con to the model mentioned was that because they serially work through the set of repos throughput is super slow. But the user experience was really good due to that. This seems like the right tradeoff for exhaustive as well. Additionally within this model it feels like we can tweak for performance.

Yea, I agree. Insights does have the ability to configure the [concurrency](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/insights/scheduler/backfill_state_inprogress_handler.go?L197) of searching repos - so it is not necessarily serial.

> Overall atleast straight up copy pasting to success from code insights seems like a good strategy. In cases where it makes sense to refactor and share we do that, but I would focus on functionality before code reuse.

I think Code Insights is overall a good model to learn and mimic. Though, there are some parts that are pretty complex and have a lot of moving parts. I would prefer to start simple and get it working before trying to reuse their code - but borrowing the concepts of repoIter and such would be great!

**Comment by Piszmog** [comment]
I think to close this out is just "Use less generic names."

For getting this interface in, I feel it would be good to add the interface when we start to add the search logic to the backend flow. That way we can ensure naming sounds right and the interface makes sense.

I have a branch where I have started to add the logic to search for repos, so I could add this interface in there.

**Comment by keegancsmith** [comment]
> I think to close this out is just "Use less generic names."

Done in https://github.com/sourcegraph/sourcegraph/pull/55858

> For getting this interface in, I feel it would be good to add the interface when we start to add the search logic to the backend flow. That way we can ensure naming sounds right and the interface makes sense.
> 
> I have a branch where I have started to add the logic to search for repos, so I could add this interface in there.

I think this can be a smaller independent PR, which then can be adapted to be used by your in progress work. If we find it doesn't work well in your current PR then we can change how it works? Additionally it allows us to start implementing the search logic independently if we have the time.
