### ISSUE TITLE
gitserver: reports error when cloning repository with same name of deleted-but-not-purged repository

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#55545]
Reported in in [Slack](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1691063941309499?thread_ts=1690911929.734609&cid=C05EMJM2SLR).

When repo is marked as deleted in `repo` table, but not yet [purged](https://github.com/sourcegraph/sourcegraph/blob/eabdecd94105af576df2d74bf5bc15e9e26d4cd0/internal/repos/purge.go#L91) from the disk space, there might be a case when another repo with the same name is added and we [error](https://github.com/sourcegraph/sourcegraph/blob/419272d4acd9669ddacd1fa76a030a3b4b0a9e7b/cmd/gitserver/server/server.go#L2272) while trying to clone, because the git dir is busy on the disk space.

**Comment by mrnugget** [comment]
Discussed in planning: do a 1d spike to find out how nasty it would be to fix this correctly. Also related to git debuggability efforts.

**Comment by eseliger** [comment]
Here's a writeup of what I observed digging deeper into this problem. From a "getting this fixed" perspective, we would need to switch to identifying repos uniquely, which means:
- The gitserver client needs to talk ID, not RepoName, as that isn't unique
  - With that comes a migration period to make sure new services can talk to older gitservers during rollout and vice-versa. Not super hard, but costs some time
- gitserver would need to map the repo ID to a directory
  - Currently, we just transform the repo name into a path and join that with the root of the data dir
  - Instead, we would need to either store them on disk by ID and migrate the file system (without 2 minor versions, that would prevent downgrades)
  - Or we could store the "path on disk" in the gitserver_repos table, where we could prevent duplicates and call a repo with a naming conflict `{regular_path}-{randnum}`, which would be 99% backwards compatible. The `dir` function is currently used heavily, so we would need to measure the impact of doing a DB call in that function on some heavy instance like scaletesting or dotcom. 

I am estimating this effort to be at least 2 weeks, given we need to migrate clients in a backward compatible way, do performance measurements, and potentially implement optimizations like caching (which themselves come with challenges).

With that, I am going to move this ticket into backlog for now.

---

Here's a bit of a raw writedown of what I found while looking deeper how this causes a reclone loop (disclaimer: I am 97.43% sure here):

So the problem we're seeing here:

They have a repo called `A`, with externalID `123`
They deleted that repo, now there's another repo that is also called `A` but with externalID `234`
In our database we now have 2 repo entries
- `name: DELETED-TIMESTAMP-A externalID: 123`
- `name: A externalID: 234`

When gitserver sees any of these two repos, they are effectively _the same_ on disk, because we get a path for a repo by:
- Stripping the DELETED- prefix
- Then normalizing the name to filepath
- and join that with the data dir gitserver operates in
So after (1), the repos will have the same path, `/data/repos/a`.

Technically, this could mean that repos are being served that should not be accessible to a user if extID 234 doesn't have the same viewer permissions, although there should be repo checks done by clients talking to gitserver, so these requests _should_ not come through, though. 

Why are they seeing an issue?

The repo purge worker looks for repos that are deleted in the database. So it will see `DELETED-A` with status `cloned` in the db. It will talk to gitserver, and ask for the repo to be deleted. Gitserver then finds the repo on disk using the above algorithm, and deletes the repo from disk. By that, the git dir for the new repo `A` also disappears. 
Now, why do we see a loop? Why is the new repo becoming uncloned?
When we update the gitserver_repos entry for `DELETED-A`, we do: 
- Delete the directory on disk, for the undeleted version of `DELETED-A`, so, for `A`.
- Then update the gitserver_repos entry where name = s.name(`A`) => `A`. So we just set the `A` repo uncloned as well
- Then update the gitserver_repos entry where name = `DELETED-A` (why do we [do 2 updates here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/repo_info.go?L95-102)? not clear, probably oversight(?))

Now, the repo is gone from disk, and both repos are marked as uncloned. `DELETED-A` will no longer be seen by the purge worker. `A` is a non-deleted repo that has clone_status = `uncloned`. 

From here, really anything could trigger a reclone:
- All exec calls
- Diff search
- `repoUpdate` calls from repo-updater
  - for example, from an external service sync
- janitor(?)
- GQL call to recloneRepo

I'm suspecting that it's `repoUpdate` from a sync, but that probably doesn't matter too much here. (Side-note: wow this is all so intertwined, navigating through this was.. fun)

So let's assume `repoUpdate` prioritized this uncloned repo, and fired a clone request to gitserver:
- `repoUpdate` calls gitserver for update of repo `A`
- `A` not found on disk, it gets cloned instead of updated
  - Clone status of `A` (not `DELETED-A`) is set to `cloning`, eventually `cloned`

DB state now:
- `name: DELETED-TIMESTAMP-A externalID: 123 cloneStatus: not_cloned`
- `name: A externalID: 234 cloneStatus: cloned`

Perfect, exactly what we wanted. The deleted repo isn't purged, we recloned the correct repo contents, and the clone status columns are all correct.

Where's the loop here? I don't know yet. I do know that all this state handling feels extremely brittle though.

Update: After further investigation, it seems that `server.syncRepoState` can update the clone state of the deleted repo to cloned again, which would start this thing over, causing the loop, because we end up with the exact database state we had at the beginning. 
- It lists all gitserver_repos in the database, including deleted repos (only on restart though, or if the gitserver address count changes)
- It then checks if the undeleted version of the repo name exists on disk
- It will find `DELETED-A` on disk, because it's undeleted name is also `A`
- It then updates the clone status of that gitserver_repos entry in the database (because here we DO use IDs) to cloned again.

New DB state after this procedure:
- `name: DELETED-TIMESTAMP-A externalID: 123 cloneStatus: cloned`
- `name: A externalID: 234 cloneStatus: cloned`

Why did it stop eventually? I am not sure. Maybe they stopped tracking the new `A` repo? Maybe the gitserver stopped restarting? This would need more investigation but running out of time. If this is a pressing issue, we can continue here.

---

Other side observations: 

- The janitor still looks at repos and might reclone repos that are deleted, thus marking them as cloned again? At least, from initial inspection I don't see how we would stop janitoring(?) a repo when it is deleted in the db.
