### ISSUE TITLE
Embedding index determines model for generating embedding query

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#55975]
Currently we rely solely on the site config for determining which model to use for generating the embeddings for a query string. If the model used for generating an index does not match we return an [error](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@97b604f15bd66e2728bf37fe62764e0ffde52853/-/blob/enterprise/cmd/embeddings/shared/search.go?L65-69) notifying user to reindex.

To reduce downtime while migrating models we should utilize the model of the embedding index to generate a query, even if that model is no longer the model identified in the current site config. This allows us to service queries while larger repos are being reindexed by the worker. 

- _**This requires that the single configured provider supports both the old model and the current model.**_ If we need to support multiple providers we should spin off a ticket and rescope the parent issue.
- Results will be fetched from indices generated across multiple models since scope selection could select multiple repos and each repo is indexed separately, so some indices will "update" to the new model before others. Spoke with @camdencheek and we're okay with this multi-model results set.

_How does this support our goal of [simplified migration](https://docs.google.com/document/d/1lW_tAO44mww3DMnrPiUyXIeqzLK6lK3lXIaddoLs5-Y/edit)?_

- Reduces downtime for large repos that require reindexing. To trigger the reindex to the new model we need to update site config. Without this change we'd generate queries with the new model as well and that would be incompatible with our complete, populated indices that used the old model.

**Comment by camdencheek** [comment]
@gl-srgr, following up on an earlier conversation we had, and this seemed like the best place. 

For Qdrant, we'd talked about using a single collection for all models. I tried to implement that over the weekend, but remembered why I didn't do it that way in the first place. Qdrant supports multiple vectors per payload, but not dynamic vectors. They must be declared at collection creation time, which means it's not a good fit for migrating between models since we won't know the model name or dimension number ahead of time. 

So, for now, plan to have a single qdrant collection per model (as it's currently implemented)

**Comment by jtibshirani** [comment]
Closing this out, as we're not investing in embeddings at the moment.
