### ISSUE TITLE
Display invalid query banner

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55976]
If a query is not supported and the query times out or there are skipped results, display information that the exhaustive search cannot run because the query is not supported.

## Technical Details

- Call the GraphQL API to validate the query
- If there are errors in the query, nicely display the errors
- Provide link to docs on support queries
- Do not allow the user to run an exhaustive search if the query is not supported

## Done

- Demo
- Storybooks

**Comment by vovakulikov** [comment]
This (partially) was implemented in this PR https://github.com/sourcegraph/sourcegraph/pull/56369

Why partially? Because we decided to go with client-side validation by parsing queries and working with lexemes instead (not ideal but should be enough for the October release), We will come back to this issue with backend-side validation if we see a large number of invalid queries in search jobs.
