### ISSUE TITLE
Test and update Chrome extension deployment via GSuite 

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5604]
Requested by https://app.hubspot.com/contacts/2762526/company/430823645

**Comment by lguychard** [comment]
Update after testing the GSuite integration:
- The docs in their [current state](https://github.com/sourcegraph/sourcegraph/blob/92a222cb6b8fa84ef03f2975a8978875faef5918/doc/integration/google_gsuite.md) do not reflect the actual admin install experience (The Google Chrome admin interface has changed).
- A feature mentioned in the docs (setting `sourcegraphURL` through policies) is not actually supported: the [managed schema](https://github.com/sourcegraph/sourcegraph/blob/master/browser/src/extension/schema.json) does not contain that property, and it's never checked in the code either.
- Features that were used for this deployment (setting `enterpriseUrls` through policies) are broken: `enterpriseUrls` were used so that the user could easily grant permissions to the Sourcegraph URL and the code host url(s). If `enterpriseUrls` existed in managed storage, the extension would attempt to open the options page, and show a prompt there for the user to grant additional permissions. `enterpriseUrls` are still checked for in the code, but don't do anything in the simplified options page (https://github.com/sourcegraph/sourcegraph/commit/5cd6abd87a06aa48181c294c3494319390d9f6f4).

Planned work to fix this:
- [ ] Remove the GSuite installation docs until this is improved.
- [ ] Add the ability for admins to set the `sourcegraphURL` through policies.
- [ ] Remove useless fields from managed schema.json
- [ ] Think of how to best handle permissions requests for the sourcegraph URL & code host URL(s). Proposed idea: the site admin can set an array of `codeHostURLs` through policies. The extension's toolbar icon shows a red badge if:
    - The user needs to grant permissions to the `sourcegraphURL` set through managed storage.
    - The user needs to grant permissions to the `codeHostURLs` set through managed storage.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Closing this now that https://github.com/sourcegraph/sourcegraph/pull/5929 is merged.

@dadlerj I've filed https://github.com/sourcegraph/sourcegraph/issues/5995 as a follow-up re: the experience of granting permissions on code host URLs.
