### ISSUE TITLE
Find references button doesn't appear on Go code, once open no references found

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5615]
Try to find references to `Entry` here: https://sourcegraph.com/github.com/uber-go/zap/-/blob/zapcore/entry.go#L144:6

Two problems:

1. The find references button doesn't appear. Why?
2. If you do land on the references link from e.g. the "Uses" link on godoc.org https://godoc.org/go.uber.org/zap/zapcore#Entry you just get `No locations found`. Why?

**Comment by chrismwendt** [comment]
Fixed in:

- basic-code-intel https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/145
- bump version https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/146
- Go https://github.com/sourcegraph/sourcegraph-go/pull/98
- TypeScript https://github.com/sourcegraph/sourcegraph-typescript/pull/245
