### ISSUE TITLE
Azure OpenAI on the back-end

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#56167]
@chwarwick could you please fill in the details on what's supported/absent after your work on back-end Azure OpenAI?

**Comment by chwarwick** [comment]
Currently chat is supported and autocomplete is not.

A good example of what we should be doing here is in https://github.com/sourcegraph/sourcegraph/pull/56120 which adds support for Fireworks.  The difference is that Azure Open AI will not modify the Cody Gateway because it is customer specific and not a shared provider that will utilize Sourcegraph's credentials/keys.

**Comment by chwarwick** [comment]
The corresponding cody vs code extension changes for the fireworks provider are here https://github.com/sourcegraph/cody/pull/839/files

I think it's likely that we would want a way for the sourcegraph server to setup a configuration with in the extension, but I don't see that as a requirement currently.
