### ISSUE TITLE
Upgrade perforce versions to 2023.1

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#56247]
Our dogfood instance, and dependencies bundled with our services are still on a 2020 version. We should see what it takes to get them upgraded. https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1692718127445519

/cc @sourcegraph/source

**Comment by burmudar** [comment]
To minimize potential impact on the current "prod" perforce instance we should launch a duplicate deployment and upgrade that deployment - since upgrading the perforce db is not backwards compatible.

- [ ] Take a snapshot of the perforce root disk
- [ ] Alternatively, look at only copying the db files
- [ ] deploy 2023.1 with alternate deployment
- [ ] test upgrade of perforce db on alternate deployment

**Comment by burmudar** [comment]
The perforce version has now been upgraded to 2023 and using SSL.
