### ISSUE TITLE
JetBrains: close gap with VS Code for telemetry events

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56467]
Currently, there are minor gaps in how the JetBrains plugin emits telemetry and how VS Code emits telemetry. This is an umbrella ticket to track fixing all those gaps

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56468
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56469
```

**Comment by olafurpg** [comment]
Related discussion https://sourcegraph.slack.com/archives/C059N5FRYG3/p1694510104478649

**Comment by chwarwick** [comment]
I looked at this initially by porting the logic in the VS Code extensions [logger](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/completions/logger.ts) but ran into issues with it.  Since it's embedded within the fetching process it's able to do things that aren't possible when accessing autocomplete though the agent.  

I think the following needs to occur:

- Split the logic that clears the current autocomplete & submits the suggested event [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java?L61:15&popover=pinned)
  -  We need to be able to clear the current autocomplete without submitting the event incase the next autocomplete returned has the same completionID. 
- The suggested event should be logged when
  - An autocomplete is accepted
  - An autocomplete is dismissed - I'm not sure of this case
  - An autocomplete is replaced with a new autocomplete having a different completionID
- When an autocomplete comes with the same id as the previous the displayed duration should continue to grow if the suggestion is visible.
  - I didn't typically see the autocomplete visible in the typeover scenarios so that is likely a different but related issue.
