### ISSUE TITLE
Chat history storage goes off limit on Brave browser

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#56510]
https://sourcegraph.slack.com/archives/C022SPMNR0W/p1694426693416129

**Comment by vdavid** [comment]
Also happens on Chrome (see the same thread).

To bring some context here from Slack, it looks like we don't handle the case when we exceed the localStorage quota. The error message is:

```
Unexpected Application Error!
Failed to execute 'setItem' on 'Storage': Setting the value of 'user-history:VXNlcjozNzM3Mg==' exceeded the quota.
Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'user-history:VXNlcjozNzM3Mg==' exceeded the quota.
    at c.migrateOldEntries 
```

As @fkling suggested: "A quick fix would be to catch and silently ignore this error. The real fix would be to understand what all the things are we using local storage for and redesign it with the understanding that local storage is not guaranteed (but that might be difficult depending on what we are using it for). If that’s mainly due to the size of the chat history then we shouldn’t store chat in local storage and use indexeddb instead."

**Comment by chenkc805** [comment]
@chenkc805 to look into how often this happens, but in the meantime marking this as a P2 because this is limited to Cody Web (Chrome and Brave so far)

**Comment by efritz** [comment]
I asked one question in Cody Web on sourcegraph.com and hit the 50 per day limit.

**Comment by chenkc805** [comment]
I think I had the same experience: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1694475560431059

**Comment by chenkc805** [comment]
CC: @taylorsperry - Cody Web users are hitting errors due to local storage. Not sure if we've thought about ways to solve this or how this falls respective to your team's priorities

**Comment by vdavid** [comment]
Closing it then
