### ISSUE TITLE
Clicking "show more" button sometimes does not work

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5655]
1. Visit https://k8s.sgdev.org/search?q=bootstrap.fallback+count%3A1000
2. You'll see some results. Scroll to the bottom of the page and click "Show more".
3. No matter how many times you click it, it does nothing. No requests are fired off in the Network tab of Chrome.

The GraphQL response clearly indicates we did not hit the limit, so it is surprising it does not increase the `count:` parameter as it usually does.

**Comment by slimsag** [comment]
@christinaforney @nicksnyder this has made users feel like Sourcegraph is providing incomplete results, can we get this on the roadmap somewhere? I think maybe @attfarhan would be a good owner perhaps. @felixfbecker previously mentioned to me somewhere that the logic around "Show more" is iffy, and needs to be revised and tests added

**Comment by nicksnyder** [comment]
The frontend limits count to be 1000; presumably because no user could possibly scroll through all those results:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/search/results/SearchResults.tsx#L300:18

Increasing the count in this scenario wouldn't help anyway (since only a handful of results are being returned).

The real question is "why is limitHit true when only a handful of results are returned".

**Comment by nicksnyder** [comment]
This is a search backend issue as far as I can tell. @attfarhan could work on this after he is done with filter UI, but that could be 2 releases from now. @tsenart if there is someone on the backend team that could pick this up before then (e.g. @unknwon @kzh @ryanslade), this would be a nice one to get done.

**Comment by tsenart** [comment]
@kzh: Would you have time to work on this before branch cut after RFC45(webhooks)?

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by lguychard** [comment]
This has been stale for a while, and does not appear to be reproducible with streaming search results.
