### ISSUE TITLE
Support for GitHub usernames ending in hyphens

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5667]
- **Sourcegraph version:** latest
- **Platform information:** k8s

Reported by https://app.hubspot.com/contacts/2762526/company/430823645

>Hey there!  Quick question.
>
>We have a user with a GitHub username ending in a hyphen - specifically, $REDACTED.
>
>According to [this help page](https://docs.sourcegraph.com/admin/auth/#username-normalization), this username is invalid, but I don't see how this user can log in to Sourcegraph given that.
>
>Is there a workaround, or some way to get around this issue, given that this is a legal username in GitHub?

Apparently GitHub stopped supporting usernames ending in hyphens years ago, but existing users were allowed to keep theirs. E.g. I just tried creating a new user and found this:
![image](https://user-images.githubusercontent.com/5589410/65261152-76011500-dabc-11e9-9424-c25896e98e27.png)

But here's a SO issue from a user who ran into a similar problem with a different service: https://meta.stackoverflow.com/questions/359284/github-usernames-cant-end-with-a-hyphen-but-mine-does

Would it be reasonable for us to normalize by just dropping the ending hyphen, if a username has one?

**Comment by tsenart** [comment]
@unknwon: Could you take a look at this today after you're done with your current PR? What do you think of @dadlerj's suggestion of normalizing by dropping the hyphen? That should be an easy fix.

**Comment by unknwon** [comment]
If it happens very rare, I agree to drop the **start** and **end** hyphen.

>Usernames that start or end with '-' or '.' are not allowed

**Comment by dadlerj** [comment]
I confirmed with the admin that dropping the hyphen would be acceptable:

>Yeah, this one is a really weird edge case, hah.  Since this only applies to private instances, there's very little risk of a collision, and in this case we would certainly not have one.
>
>If it's a quick fix, that'd be great.  I assume that there's currently no way to override the username that Sourcegraph assigns?
>
>I haven't actually attempted this, but if I (as a site admin) were to create the user an account via the site-admin panel would that work?  It appears to give me the option to set a username associated with an email.

I don't think it would be possible to do manually.

**Comment by unknwon** [comment]
@dadlerj do you think it's worth dropping the start hyphen as well? Or just dropping the end hyphen in the quick fix?

**Comment by dadlerj** [comment]
>I ask because according to the following rule, the user could have disallowed characters in both start and end positions, which in that case we make hyphens ourselves.

This should never be a problem (for GitHub, at least), because GitHub's username rules never allowed other characters (as far as I know).

>@dadlerj do you think it's worth dropping the start hyphen as well? Or just dropping the end hyphen in the quick fix?

I have no idea if this will ever be an issue haha. If it's trivial to add this as well, then sure I guess 🤷‍♀. I leave it up to you and Core Services!

**Comment by unknwon** [comment]
It's a one line fix either way. But I see some tests failed, e.g. "john(test)@gmail.com", it was rejected but now proceed as "john-test".

I think it is fine because no one ever reported they are not able to use their email in Sourcegraph?

**Comment by christinaforney** [comment]
I looked into how Gitlab chooses to do username validation as a secondary data point. Here is the specific regex that is allowed on the frontend: https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/path_regex.rb#L122 
It does not allow the starting character to be a hyphen, but the ending character can be.

What would it take to allow the username/email rules for each auth provider we support so that the username would always match? Could we simply just trust the auth provider to do good enough username validation and take the given username without question? Why do we do any sanitization on username for SSO? Are there risks with doing that? Then, for Sourcegraph auth we can use whatever rules we feel makes the most sense.

**Comment by unknwon** [comment]
@christinaforney:
>What would it take to allow the username/email rules for each auth provider we support so that the username would always match?

We currently have [5 calls to `auth.NormalizeUsername`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+auth%5C.NormalizeUsername), if we "allow the username/email rules for each auth provider", we will have 5 functions instead of 1, which is still pretty small in scale.
