### ISSUE TITLE
Perforce depot clones deleted from gitserver without any indication of why

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#56902]
- **Sourcegraph version:** 5.1.7
- **Reported by:** https://github.com/sourcegraph/accounts/issues/6938

#### Overview

On several instances over the past couple of weeks, the Git repository mirror of a Perforce depot has mysteriously been deleted from disk and started re-cloning.   For smaller git repos, this is not an issue because the repo can re-clone quickly.  However, for Perforce depots, this re-clone can take hours.

Suggestions for improvement:

* Clearly indicate to the admin why the repository was/is deleted and is being re-cloned
* Only delete a repo on disk if absolutely necessary

/cc @sourcegraph/source

**Comment by eseliger** [comment]
We should see improvements in 5.3 wrt. corruption detection that might delete repositories. 
In addition, a purge worker that would try to make sure ample disk space is remaining that didn't actually fix the issue in the long-run because we would reclone has been disabled for customer instances, preventing "ghost deletes".

These two things together are the only sources that I could see which might cause this behavior, so unless the customer is still seeing this issue after upgrading to 5.3, I will consider this not a problem anymore.
