### ISSUE TITLE
YAML Hyperlinks Omit The Last Number

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/sourcegraph#57043]
- **Sourcegraph version:** v5.1.9
- **Platform information:** Web App (on all platforms)

#### Steps to reproduce:

1. Navigate to a YAML file with a hyperlink within it that ends in a digit.
 

#### Expected behavior:

The hyperlink is fully highlighted and clickable.

#### Actual behavior:

The hyperlink is not fully highlighted nor clickable.

![image](https://github.com/sourcegraph/sourcegraph/assets/86978415/9ed1cbd6-2b0c-4b8f-befc-45939b4b4264)
<img width="1190" alt="Screen Shot 2023-09-26 at 10 52 52 AM" src="https://github.com/sourcegraph/sourcegraph/assets/86978415/8c7dff06-6cda-4411-bcf3-95add0cadf22">

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/search-platform

**Comment by alexAtSourcegraph** [comment]
Occurring at https://github.com/sourcegraph/accounts/issues/548

**Comment by keegancsmith** [comment]
This is likely a webapp issue, I don't think the search backend is involved in this. CC my best guess for the current owner of this @sourcegraph/code-search

**Comment by jasonhawkharris** [comment]
Looks like [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/linkifiy/get-links.ts?L60) is where the problem is. My current theory is that there is an edge case in linkifyjs (the package we're using to identify links) when handling new lines and trailing characters.

It seems like linkifyjs is treating each line as a separate string to register as a hyperlink. So when it gets to the last line "https://testing.com/112", in my case, it correctly identifies "https://testing.com/112" as a link.

However, when rendering the links, it looks like it is stripping off the trailing newline character. So the "a" gets left off.
