### ISSUE TITLE
Setup 80k repos on k8s.sgdev.org

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#5726]
We want to find out what breaks on a cluster with 80k repositories. Its best to find that out early in our 3.9 development cycle. This issue tracks the work needed for this, and should contain findings as issue comments. We can then file follow-up tasks either as part of 3.9, or for work in 3.10.

**Comment by keegancsmith** [comment]
Note: We should also care a lot about the onboarding experience of setting up 80k repos, not just how the system behaves with 80k repos.

**Comment by kzh** [comment]
I'm currently working on importing the additional 50K repos into our internal bitbucket, gitolite, gitlabs, and github instances.

**Comment by keegancsmith** [comment]
@kzh can you post an update of our findings and decisions here and close this out?

**Comment by kzh** [comment]
Here are the findings from attempting to set up k8s.sgdev.org with 80K repositories onto one large `indexed-search` node.

Adding an additional 19K repositories rendered the `indexed-search` pod into a `CrashLoopBackoff` state. An initial look at the logs showed that `zoekt-webserver` was unable to load the additional repositories into memory. The Go runtime malloc calls were panicking and the `mmap` syscall was returning `unable to allocate memory`. This was expected behaviour, so we bumped the memory allocated to the pod (120Gi -> 350Gi). Strangely, the same error was happening. There was nothing wrong in the `dmesg` output. After doing `free -g`, it appeared that there was indeed 350Gi allocated but only about 100Gi (~50k shards) was being used before `zoekt-webserver` crashed.

The consensus is to merge horizontal scaling for zoekt before proceeding to investigate performance with 80K repositories. For now, the k8s.sgdev.org instance has been reverted back to the original state with 40K repositories. The additional 19K can be added back by adjusting the `repositoryQuery` in the Github Enterprise external service config to `public` + `affiliated` and removing `orgs: ["sourcegraph"]`.
