### ISSUE TITLE
Initial zoekt indexing does not report errors and stays processing

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#57337]
I recently broke my indexer by setting CTAGS_COMMAND to something zoekt didn't like. All I get is 3/31 repos indexed in the status message, and on the repo page I get 

![image](https://github.com/sourcegraph/sourcegraph/assets/19534377/26a0d9f4-6b44-415d-93ff-746ded66ca9d)

Two things:

- It wasn't actually attempting to index when I looked at the page, which feels misleading
- It doesn't give any indication that there's a problem. For simpler debugging without reading server logs, it would be great to get some more information there

/cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
I opened #58793 to try to address this as much as possible:
* Don't show a loading spinner and falsely claim that a repo is indexing when it's not :)
* If an index is out of date and it's been a long time since the last successful run, show a warning. Unfortunately this doesn't address the case where the initial indexing job for a repo fails.

 Because of our indexing job architecture, it's really tricky know when an indexing attempt has failed. We could try to have Zoekt tell Sourcegraph about failed indexing attempts, but it would be messy and didn't seem worth the complexity.
