### ISSUE TITLE
JetBrains: automatically trigger autocomplete in specific location

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#57366]
When typing `prompt` in the example from this tweet here, autocomplete doesn't trigger automatically. I have to alt-backslash to get autocomplete loading

 https://x.com/_PabloDev/status/1709725732270751956?s=20

We should fix it so that autocomplete is triggered automatically here. Minimal example to reproduce

```ts
interface DoInteractionRequest {
    chatId: string
    prompt: string
    systemPrompt: string
}

interface Fuzz {
    string: () => string
}

const z: Fuzz = {} as any

const interactionRequest: DoInteractionRequest = {
    chatId_CURSOR_
    prompt: z.string(),
    systemPrompt: z.string(),
}

```

**Comment by Sa1to** [comment]
Are there any other examples? In this case, for latest cody nightly version, I'm regularly getting completions:



https://github.com/sourcegraph/sourcegraph/assets/9321940/6a95fdb0-a9ce-41a3-87a6-24a1af628993

**Comment by Sa1to** [comment]
Before this issue was resolved [JetBrains: integrate autocomplete with lookup manager#57335](https://github.com/sourcegraph/sourcegraph/issues/57335) We weren't triggering autocompletion when IJ lookup manager was triggered so there might be a case in which you get `chatId` suggestion from IJ lookup manager therefore cody autocompletion wasn't triggered... 🤔  

https://github.com/sourcegraph/sourcegraph/assets/9321940/44deee6e-8443-4aa7-aaec-056e75a99471
