### ISSUE TITLE
Remove github-proxy

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#574]
@keegancsmith suggested in https://github.com/sourcegraph/deploy-sourcegraph/issues/121#issuecomment-432207823 that it should be possible to remove github-proxy.

I don't know what that entails, so I'm filing this issue.

**Comment by tsenart** [comment]
Since the authz stuff also uses `extsvc/github`, we need to tread carefully here to not regress on making too many concurrent requests to the Github API, were we to remove github-proxy.

An idea is to use Redis or Postgres' distributed lock features to serialise Github requests without github-proxy.

**Comment by tsenart** [comment]
With automation doing lots of Github calls that are not coming from repo-updater, github-proxy is still useful to prevent abuse rate limit being triggered due to too many concurrent requests, so we want to keep it around.
