### ISSUE TITLE
No search results due to GitLab repo permissions/ACLs and rate limiting

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5761]
- **Sourcegraph version:** 3.8.0
- **Platform information:** Single Docker image

Reported by:
* https://app.hubspot.com/contacts/2762526/company/887065580

>Dan,
>
>I just tested with a colleague. He got the following immediately after searching.

[screenshot of “No results” on a search, no timed out repos or errors visible at all]

>The logs show a ton of the following, probably due to rate limiting from GitLab.

```
15:47:36           frontend | t=2019-09-27T15:47:36+0000 lvl=eror msg="Failed to fetch
 visibility for GitLab project" projectID=XXXX gitlabHost=https://gitlab-app.XXXX/
 error="Get https://gitlab-app.XXXX/api/v4/projects/XXXX: context deadline exceeded"
```

>I then elevated his status to “Site Admin” and he immediately got results and no longer has trouble searching.
>
>I demoted his status back to a regular user and removed the GitLab permissions. His search returned a little slower, but still got results as expected.
>
>So it definitely looks like a bug around permissions.

I've requested config details for reproducing.

**Comment by dadlerj** [comment]
Related to https://github.com/sourcegraph/sourcegraph/issues/4812

**Comment by tsenart** [comment]
For future reference, some levers we have to discuss in the next planning cycle:
- Manual permissions feature (rather than replicating code host permissions)
- Contributing ["API response for all projects a user has access to"](https://gitlab.com/gitlab-org/gitlab/issues/20532#note_224002249) to Gitlab since it's open source (likely not straightforward, less preferred)
- Adding some concurrency to our Gitlab authz providers to speed up fetching permissions (within the acceptable rate limits).

**Comment by keegancsmith** [comment]
Do we have any idea how much pain this is causing customers? IE interested in how we prioritise this.

**Comment by tsenart** [comment]
Closing until it resurfaces @dadlerj.
