### ISSUE TITLE
Blob view: keyboard navigation

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57813]
Navigating code by via keyboard is the most natural way to browse for many developers. It would be great to allow users to browse code with a cursor and keybindings that match their natural habits in the editor.

Note, this is not an obvious/decided task. We should do a bit of research first to determine _whether_ we want to tackle this and support it moving forward before implementing it.

- [ ] Determine what CodeMirror can do out of the box
- [ ] Audit the state of keybindings in the web app in general
- [ ] Determine what bindings we can support, how they would conflict with other key bindings, and whether it can/should be configurable
- [ ] Figure out whether we can easily hook into "go to definition" with keyboard shortcuts
- [ ] Think through how difficult this feature would be to support moving forward

**Comment by jasonhawkharris** [comment]
Looks like @olafurpg has already done some [really great work here](https://github.com/sourcegraph/sourcegraph/pull/44698). Olaf, is there anything you would've liked to get to on this that you didn't? Maybe being able to map moving between tokens to `hjkl`?

**Comment by olafurpg** [comment]
I would try to avoid adding support for custom shortcuts because we are constrained by the browser for what kinds of support we support. For example, we should not allow overriding Cmd-L because it's a built-in browser shortcut to select the URL bar. The built-in shortcuts vary from browser to browser. For example, Cmd-O is overridable in all browser except Safari. I suspect >98% of users are going to stick with the defaults anyways so custom shortcuts are only going to satisfy a small minority number of users.

We already support keyboard navigation for some actions

- arrow keys to move between tokens 
- space to load popover
- enter to go to definition

I still need use the mouse to do a lot of things:

- Papercut: when using Cmd+F to find an occurrence, press Escape, and then try to use arrow keys to move between tokens. Currently, we don't automatically selected match after you press escape. In editors like VS Code, when you press escape after search with Cmd+F, the matching text is automatically selected, and subsequent arrow keys move based on the selected text.
- Move between recently open files. You can use Cmd-left/right to go back and forth in the browser history but we don't have an abstraction around "these are your open files" like editor tabs work in IDEs where you can use ctrl-tab to cycle between open files.
- Go to specific line. CodeMirror automatically registers an alt-g shortcut, which kind of works but currently has no custom styling in our blob view we, don't scroll to the matching line, and we don't automatically move the selection/cursor to that line.
- Moving back and forth between the reference panel and blob view. You can use escape to close the reference panel but there's no reliable or intuitive shortcut to re-open the reference panel.
- Find references.
- Go to implementation.

The biggest problem with shortcuts is that they are difficult to discover. We currently have the `?` shortcut to display all supported shortcuts and we should continue keeping that list up-to-date as we add new shortcuts. However, I think it would be even more impactful if we extend the fuzzy finder (Cmd+K) to support "commands" like goto-def/x-ref/x-impls/go-to-line. In the fuzzy finder, we can display the shortcut just like VS Code and IntelliJ do in their command palettes

<img width="730" alt="CleanShot 2023-10-25 at 10 32 47@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1408093/15f526da-0256-4777-831c-6f6494d2ec70">

<img width="651" alt="CleanShot 2023-10-25 at 10 31 37@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1408093/e8f4f116-9300-417a-b3e8-55028c992094">

**Comment by olafurpg** [comment]
My personal recommendation is to de-prioritize keyboard navigation because we have bigger problems to solve. Most users are going to interact with our app primarily with their mouse regardless if we add more shortcuts or not. If you invest in keyboard navigation then you are only going to impact the user experience for a minority of users. It's better to invest our limited bandwidth into solving problems that affect all users (and there are plenty of such problems).

**Comment by olafurpg** [comment]
Just hit on a keyboard related papercut, reproduce:

- Open https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/agent/src/agent.ts
- Cmd-F and search for graphql, press enter until you hit line 228
- Use the mouse the click on the line number in the gutter in preparation to share a link there
- Press `y` shortcut to canonicalize the URL (point to git hash instead of `main` branch)
- Expected behavior: URL becomes canonical
- Actual behavior: Cmd-F search input is still focused so it appends `y` to the existing `graphql` query

This may seem like a small issue, but papercuts like these add up quickly and they make it painful to use the blob view with the keyboard.

**Comment by olafurpg** [comment]
Ideally, we should have a shortcut to copy a canonical link to the current **selection** of the editor. This action would be accessible in the fuzzy finder similar to how it works in VS Code, and the fuzzy finder would educate the user about the existence of the keyboard shortcut
 
<img width="756" alt="CleanShot 2023-10-26 at 09 01 05@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1408093/cd1ea44a-6dc2-445d-9395-e1477f9505bc">

**Comment by camdencheek** [comment]
Just came across some [previous work](https://github.com/sourcegraph/sourcegraph/issues/43176) on this

**Comment by jasonhawkharris** [comment]
@camdencheek, how about this as an approach: 

Keyboard navigation in Code Search is still a feature that sits behind a feature flag. I think we should do the work to get this away from its status as an experimental feature by fixing the paper cuts mentioned by @olafurpg above. After using the feature quite extensively for the last few weeks, I think it's worth pursuing and publicizing, as it has vastly improved my Code Search experience. 

I don't think new features are needed at this time. We just need to clean up some of the obvious paper cuts that discourage users from buying in fully. Thoughts?

**Comment by camdencheek** [comment]
That sounds like a great plan 🙂 Feel free to create a new issue if you feel this one is too noisy and doesn't represent the work we want to do

**Comment by camdencheek** [comment]
Closing this per @jasonhawkharris's recommendation because turns out we're actually pretty happy with the state of keyboard navigation, and this is not a place we feel is low-hanging fruit after some of the improvements made here.
