### ISSUE TITLE
Search Contexts with >1000 repos in JSON configuration cannot be created

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/sourcegraph#57932]
- **Sourcegraph version:** 5.1.9
- **Platform information:** observed on docker-compose and k8s deployments

#### Steps to reproduce:

1. Create or Edit a search context 
2. Select JSON configuration
3. Add >1000 repos
-- For ease, you can use this [context](https://cse-k8s.sgdev.org/contexts/%40morgangauth%2Fmany-repos/edit) with this json config: [searchContext1000repos.json](https://github.com/sourcegraph/sourcegraph/files/13180917/searchContext1000repos.json)
5. Click 'Test Configuration'
6. Comment out the last repo in the JSON and then test configuration again

#### Expected behavior:
scenario 1: After step 5, the search context should be successful. 
scenario 2: The error message states that repos cannot be found, so by commenting out the last repo (which does not match the error message), the error should persist if that repo actually cannot be found
*Note the expected behavior was confirmed to be working in v3.37*

#### Actual behavior:
1. After step 5, the search context returns an error that repositories cannot be found (the # of repositories not found will match the # of repos over 1000 listed in the search context)
![Screenshot 2023-10-25 at 3 58 44 PM](https://github.com/sourcegraph/sourcegraph/assets/113058716/199faa9e-82a6-4705-97e4-97202a408007)
2. After commenting out a repo which is NOT the same one listed in the error, the search context is able to be saved successfully indicating that the repo WAS able to be found, but the search context has an issue with finding repos over the limit of 1000. 
![Screenshot 2023-10-25 at 3 59 12 PM](https://github.com/sourcegraph/sourcegraph/assets/113058716/8ae03cf3-1762-40e9-992d-8ad2a7011f34)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by morgangauth** [comment]
Occurring at https://github.com/sourcegraph/accounts/issues/7485

**Comment by camdencheek** [comment]
Quick update: found the root cause. The webapp fetches repositories to validate them, but does not use pagination and just [tries to get them all in one go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e0eb29ced63bfc2cf5b3aa20d07183116bd76fe6/-/blob/client/web/src/enterprise/searchContexts/backend.ts?L12-12). The backend [limits the number of results in a page to 1000](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e0eb29ced63bfc2cf5b3aa20d07183116bd76fe6/-/blob/cmd/frontend/graphqlbackend/repositories.go?L119-119), even if the client requested more. The webapp should page through results.

I've added this to our team's backlog, but given that the root cause is just a webapp problem (and not a general repository listing problem like I was worried) I do not think fixing this is super high priority.

Depending on how the repsitories are chosen to be added to the search context, the customer may be able to get around the bug with search-based query contexts. They could use something like `repo:has.topic()` or add repo metadata to each of these repos that they want in the search context.
