### ISSUE TITLE
Code Intel is broken on file extensions that don't match case

### ISSUE THREAD

**Issue by RichardBelzer** [sourcegraph/sourcegraph#57974]
- **Sourcegraph version:** 5.2.1
- **Platform information:** Fedora Server

#### Steps to reproduce:

1. Have a file in the repo that is all caps. Example could be `MYCODE.CPP`.

#### Expected behavior:

Code intel works. When moving my mouse over a function call, I would get a popup that lets me either go to definition or see references.

#### Actual behavior:

Code intel doesn't function on the file. Looking in the browser logs, there is an error that states "unrecognized file extension"

![image](https://github.com/sourcegraph/sourcegraph/assets/69686380/b72abad7-a93c-4370-a907-7ba0fcd61035)

This is similar to what @slimsag worked in https://github.com/sourcegraph/sourcegraph/issues/13007. We fixed syntax highlighting a couple years ago, but at some point between `3.2.3` and the current version `5.2.1` we introduced a regression where code intel no longer works on those kind of files.

**Comment by RichardBelzer** [comment]
Did some research and discovered that this issue occurs starting in `5.2.0`. It works fine in `5.1.9`.

It was triggered by the change in https://github.com/sourcegraph/sourcegraph/issues/51547 by @ggilmore

As a temporary workaround, you can disable gRPC by adding:

```
"experimentalFeatures": { "enableGRPC": false }
```

To the site configuration which will fix this problem in `5.2.0+`. Hopefully this issue gets fixed soon, or at least while the option to disable gRPC is still available.

Please allow users to continue to disable gRPC until this issue is fixed, thanks!

**Comment by jdorfman** [comment]
Thanks @RichardBelzer! I notified @ggilmore

**Comment by varungandhi-src** [comment]
Thanks for reporting the issue.

Reproduced: https://sourcegraph.com/github.com/electronicarts/CnC_Remastered_Collection/-/blob/REDALERT/MP.CPP

<img width="895" alt="CleanShot 2023-11-01 at 09 52 49@2x" src="https://github.com/sourcegraph/sourcegraph/assets/93103176/19c7cb8b-d7cc-4d1a-9ba6-f895711dd613">

**Comment by varungandhi-src** [comment]
There are two different bugs here.

1. The squirrel code path doesn't handle `.CPP` as an extension. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/symbols/squirrel/language-file-extensions.json?L45-57
2. The codepath which uses GRPC takes the first error and treats that as fatal somehow, instead of falling back to a search query if squirrel fails (which should be the expected behavior). I haven't yet exactly identified where this is.

**Comment by varungandhi-src** [comment]
Previously, when Squirrel encountered an error, it was converted to something like this for the `LocalCodeIntel` endpoint.

```
{"repository":{"id":"UmVwb3NpdG9yeToyNg==","commit":{"blob":{"localCodeIntel":"null"}}}}
```

This gets converted to a `null` `LocalCodeIntelPayload` value in the frontend, and the code keeps going on as normal.

With GRPC, we actually bubble the error in the backend as an "error" result in the response. The error in the response gets mapped to a `throw` in `queryGraphQL` causing an immediate error.

For the `SymbolInfo` case, we end up getting something like:

```
response={"repository":{"commit":{"blob":{"symbolInfo":null}}}}
```

This gets handled properly instead of throwing an error: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/codeintel/legacy-extensions/util/api.ts?L287-290

```
        const symbolInfoFlexible = response?.repository?.commit?.blob?.symbolInfo ?? undefined
```
