### ISSUE TITLE
Add schema validation for auth provider is required

### ISSUE THREAD

**Issue by stephenh** [sourcegraph/sourcegraph#580]
After setting up google oauth, I decided to go back and just use built-in auth, and so deleted the auth provider auth block (instead of putting back the built-in auth provider). Which locked me out of the admin, so now I need to reset the state to start over. Seems like ideally the config's JSON schema validation could keep me from saving this invalid config.

**Comment by sqs** [comment]
In Sourcegraph 3.0-preview (coming out next week) we will make the recovery case much better here: you will be able to sign into a management console on a separate high port number and change this config there. cc @ggilmore 

However, even after that, it would be good to be able to catch this kind of error. Currently we can warn about it, but we do not prevent you from saving it, because many warnings are just about old/deprecated config (they are not fatal errors). We should distinguish between warnings and errors in config, and prevent you from saving errors.

**Comment by KattMingMing** [comment]
If you're still locked out, you can manually edit the configuration file.

If you followed our [quickstart documentation](https://docs.sourcegraph.com/#quickstart) the configuration file is stored here: `~/.sourcegraph/config/sourcegraph-config.json`

Running from source: `dev/config.json` inside the Sourcegraph repository.

**Comment by francisschmaltz** [comment]
@stephenh In Sourcegraph 3.0, [auth providers](https://docs.sourcegraph.com/admin/config/critical_config#authentication-providers) are now set [management console](https://docs.sourcegraph.com/admin/management_console) so this shouldn't be an issue moving forward.
