### ISSUE TITLE
Ranking: improve result diversity

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#58057]
Often, all top search results can be dominated by a single file type (or even a single file), when having a mix of options would be most helpful. This is especially true for broad queries without a super specific intent (for example "index server", "file permissions", etc.)

Overall, two principles are important in helping address this:
* As much as possible, ranking scores should be comparable across programming languages and file types.
* Sometimes data sources truly have a different notion of relevance (like docs vs. code, or if we eventually expand to issues/ PRs). So sometimes simple rules are needed to ensure we include matches across data sources.

Specific ideas:
* Make sure that one programming language doesn't dominate another
  * This can happen because one language has imprecise symbols support (like tsx)
  * Also, we weigh symbol kinds differently for different languages, so a 'method' in one language might score lower than in another. We could consider standardizing symbol scoring across languages to ensure overall scores are comparable.
* Docs files tend to be disadvantage compared to source, since they don't contain symbols. Maybe we could always mix in a docs file into the top 5 results if one isn't already present.
* Sometimes there are a bunch of matches in one file, which means we hit the match limit and you only see one file in search results! Can we limit the number of matches counted per file? 

/cc @sourcegraph/search-platform

**Comment by keegancsmith** [comment]
> Sometimes there are a bunch of matches in one file, which means we hit the match limit and you only see one file in search results! Can we limit the number of matches counted per file?

This is something that frustrates me in our current sourcegraph logic. We hide 100s of results behind show more but then end up only showing one file in our display limit. Somehow tackling this feels very important. It can be tricky because you don't want to send down large responses in those cases, but having an extra request when you click show more doesn't feel ideal either.

**Comment by stefanhengl** [comment]
What do you think about adding a `FileMaxMatchCount` to `zoektOptions` and then setting this to a fraction of the display limit if that is set. We could still search the whole file to get the scoring right, but truncate the results if we reached the limit.

**Comment by keegancsmith** [comment]
> What do you think about adding a `FileMaxMatchCount` to `zoektOptions` and then setting this to a fraction of the display limit if that is set. We could still search the whole file to get the scoring right, but truncate the results if we reached the limit.

Yup maybe we could experiment with that if a count: is not set? By experiment I mean on our feature flag. I think we should still be showing statistics that there are more matches but that is a bit more engineering. Alternatively we could say there are more matches, and then when the person hits expand we show them via issuing another search?

**Comment by keegancsmith** [comment]
@jtibshirani what are your thoughts on the current diversity boosting we have?

Possible changes:
- more boosting, not just 1 result. Maybe boost stuff into top 10 to ensure diversity of extensions
- boost docs specifically as you mention. Maybe always ensure there is 1 doc in the top 10?

Otherwise trying to balancing across languages seems quite difficult to encapsulate in a single task, but rather our tests and philosphy of development need to encourage that.

I do think we need to do the filematchlimit stuff.

This issue has a bunch of ideas, I wanna break it up into things we know we want to tackle now. So looking for some thumbs up on the above/etc.

**Comment by jtibshirani** [comment]
> @jtibshirani what are your thoughts on the current diversity boosting we have?

I'll ponder a bit and suggest an idea for what we could implement in the short term... be back soon :)

> Otherwise trying to balancing across languages seems quite difficult to encapsulate in a single task

Indeed, maybe it'd make sense to spin this out as a separate issue. It feels like its own mini-project, which would require first investigating any differences in scoring between languages. I think it'd be helpful, but not as high priority as other ranking work.

> I do think we need to do the filematchlimit stuff.

+1 to tackling the file match limit issue, this seems really useful.

**Comment by keegancsmith** [comment]
I added a task to the tracking issue about file match limit and moved this task to a "lower priority" section.

**Comment by jtibshirani** [comment]
I thought about this more and suggest we close this in favor of separate tasks:
* Addressing the file match limit
* Making sure we properly balance across languages so one language isn't always advanced over others -- I can file a separate issue (lower priority)
* The existing issue about docs search: https://github.com/sourcegraph/sourcegraph/issues/58059 (lower priority)

I don't have an immediate suggestion for improving the docs vs. code ranking -- I'll play around with some examples using the ranking integration test. I think either it already turns out to be passable (now that we boost Markdown sections), or they are still disadvantaged and we could boost docs specifically.

As a high-level comment, it makes sense to me to manually mix in docs vs. code, because they're different data types and have a different notion of relevance (and therefore scores). But it feels a bit hacky to boost code results based on file type -- ideally we'd just score things consistently and we could compare them fairly.

**Comment by keegancsmith** [comment]
> I thought about this more and suggest we close this in favor of separate tasks:
> 

> * Addressing the file match limit

I've already added a task entry to the tracking issue. However, I have not yet converted it into an issue. I think when tackling it its worth fleshing it out then and making it a first class issue?

> As a high-level comment, it makes sense to me to manually mix in docs vs. code, because they're different data types and have a different notion of relevance (and therefore scores). But it feels a bit hacky to boost code results based on file type -- ideally we'd just score things consistently and we could compare them fairly.

I agree with this assessment. However, specifically coding in diversity seems like a good approach since we likely will never do a perfect job at scoring. Not just diversity by file type, but diversity of symbol type/etc is likely also useful. My intuition here is diversity is a hack for us to guess at the intention behind a query via the use of the users scroll wheel :)
