### ISSUE TITLE
Automatically build zoekt in CI

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#5819]
Right now our fork of zoekt has to be manually built from our infrastructure repo. It would be better if it were built automatically on every change to the master branch in https://github.com/sourcegraph/zoekt.

**Comment by keegancsmith** [comment]
Alternatively we could build it as part of sourcegraph/sourcegraph? We already build it in there for the server image.

**Comment by nicksnyder** [comment]
sourcegraph/sourcegraph would certainly be better than the current state, but it does feel a bit weird since the code isn't in that repo.

**Comment by slimsag** [comment]
Moving the code to this repo would allow us to have:


1) a clear distinction of Sourcegraph code vs. upstreamable changes (we
could even maybe get rid of our fork entirely?)
2) the Dockerfiles and code in same location
3) remove the ability for Sourcegraph/servers zoekt version to be
inconsistent with what is in the published docker images (this is possible
today because one builds latest and the other is pinned in go.sum)

Seems like that would be best?
