### ISSUE TITLE
Tree View: different icons for different file types

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#58417]
We should have different icons for each file type, which will make scanning the file tree much easier.

![Image](https://github.com/sourcegraph/sourcegraph/assets/62355966/4294c4a2-f821-46c4-b223-dc5ec52f951b)

**Comment by jasonhawkharris** [comment]
cc: @vovakulikov, @taiyab

**Comment by vovakulikov** [comment]
I’m a big fan of how JetBrains IDE works with this. You see that they use icons for different extensions, yes, but they also blur/grey generated files and green highlight test files which helps a lot with finding things that you’re looking for (especially with tests because the name of the file and its test usually are the same)

<img width="344" alt="Screenshot 2023-11-17 at 15 07 59" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/cc6f0c05-510f-489a-be6f-1793841380b3">

**Comment by jasonhawkharris** [comment]
Neovim: 
![Screenshot 2023-11-17 at 12 25 42 PM](https://github.com/sourcegraph/sourcegraph/assets/62355966/905366ca-531c-4528-801d-634ed3b7e918)

VS Code: 
![Screenshot 2023-11-17 at 12 26 36 PM](https://github.com/sourcegraph/sourcegraph/assets/62355966/1e28be3f-a5c1-4579-be12-e5b6b41b980e)

**Comment by jasonhawkharris** [comment]
I think a combination between intellij's graying out of certain file types and the icons like the two screen shots I posted would be a good move.

**Comment by taiyab** [comment]
Giving feedback on: https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1700261573801559?thread_ts=1700242956.234639&cid=C05EA9KQUTA

**I love what you've done @jasonhawkharris!**

After a bit of experimentation, I've come up with this:
<img width="230" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/8182ba8d-b50d-4735-acb5-93b14c63c4e0">


I'd recommend:
- "Normal" files -> keep as you've done
- Test files -> add a small dot indicator to the bottom right of the icon to differentiate
- Generated files -> Color icon `icon-muted`, color label `text-muted`

cc @rob

**Comment by jasonhawkharris** [comment]
@taiyab Awesome! Great ideas. Do you also want to talk about colors of the icons? I just used our builtin colors but maybe we need to create a new collection of global colors to use for the icons?
