### ISSUE TITLE
Nil pointer exception on index configuration page

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#58453]
https://sourcegraph.com/github.com/vitejs/vite/-/code-graph/index-configuration

Cannot tell what is specific to that repo, have not been able to reproduce it
with other repos on Sourcegraph.com. I have not yet attempted to reproduce it locally.

Reported by @Strum355 in Slack: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1699625070804179

**Comment by kritzcreek** [comment]
Debugged this together with Anton. The failure for vitejs/vite in particular is that the typescript.lua inference script tries to read the contents of every `package.json` file, of which the vite repo has >200, but we limit the amount of files to be read to be less than 100.

The reason this surfaces as a null pointer error rather than a proper error message is because of a missing `return nil, err` in the graphql resolver code in: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4b7dd276141b9e1165360f1e3e881a16a3619f5b/-/blob/internal/codeintel/autoindexing/transport/graphql/root_resolver_configuration_repository.go?L111

This was broken in the combination of these two PRs:

https://github.com/sourcegraph/sourcegraph/pull/47751
https://github.com/sourcegraph/sourcegraph/pull/52408

I'm working on the immediate fix for the nil issue and will write up a separate issue for fixing the typescript inference script to read less files.

**Comment by kritzcreek** [comment]
Wrote up the issue with the default TypeScript index script here https://github.com/sourcegraph/sourcegraph/issues/58880
