### ISSUE TITLE
`lang:SQL` incorrectly includes file extension `.inc`

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#58681]
![CleanShot 2023-11-30 at 15 49 18@2x](https://github.com/sourcegraph/sourcegraph/assets/93103176/f30f28ad-22a6-4b27-a610-bfad937f46fc)

The first one is a C/C++ include file. https://sourcegraph.com/github.com/tensorflow/tensorflow@2d6d24d62b6eb1e44dae182984844342343a74f7/-/blob/tensorflow/core/ir/tf_op_names.inc

The second one is an HTML file. https://sourcegraph.com/github.com/rust-lang/rust@1670ff64bf1ccb2ad71068254b53725631c55864/-/blob/src/doc/footer.inc

/cc @sourcegraph/search-platform

**Comment by camdencheek** [comment]
cc @jtibshirani since you've been working on that language detection feature flag

**Comment by jtibshirani** [comment]
I verified this would be fixed with the `search-content-based-lang-detection` flag enabled. We can't fix it with the current extension-based strategy, since `.inc` is in fact sometimes used for SQL.

I'm closing this out in favor of this issue to enable the feature by default: https://github.com/sourcegraph/sourcegraph/issues/60676
