### ISSUE TITLE
Use GraphQl to collect users and feature flags set

### ISSUE THREAD

**Issue by airamare01** [sourcegraph/sourcegraph#59169]
#### Feature request description

https://github.com/sourcegraph/accounts/issues/579 would like to use GraphQL to gather user information for all users that have a specific feature flag set, this functionality will be useful for them to help keep up with user lists.

#### Is your feature request related to a problem? If so, please describe.

Currently, GraphQL doesn't have a constructible query to return users with feature flags set.
#### Additional context

https://github.com/sourcegraph/accounts/issues/579 believe that getting user information such as `username`, `email`, `display_name`, `created_at`, `updated_at`, `deleted_at` from all the users that have a specific feature flag set would be advantageous information to monitor and maintain users.

**Comment by camdencheek** [comment]
We generally don't encourage customers to enable feature flags. If an option is meant to be enabled by customers, we promote those to experimental settings rather than feature flags.

However, for boolean feature flags (not the percentage rollout ones, which probably shouldn't be used by customers directly), you can list the users that have overrides for that feature flag. This query can also be modified to just list it for a specific feature flag.

```
query EvaluateFeatureFlag {
 	featureFlags {
    ...on FeatureFlagBoolean {
      name
      overrides {
        namespace {
          namespaceName
        }
      }
    }
  }
}
```

**Comment by camdencheek** [comment]
We should extend our GraphQL `User` type to be able to list and evaluate feature flags for that user. It should be pretty straightforward and would be helpful for the feature flag admin page. 

cc @bahrmichael this would be a really great early task to pick up because it would touch 1) our GraphQL layer, 2) our DB layer, and 3) feature flags. If you want to tackle this, feel free to assign yourself.

**Comment by bahrmichael** [comment]
Sounds good! I'll assign it to myself, but it will take a few days before I'll have the time to get started.

**Comment by camdencheek** [comment]
Yep, no rush. This should not be an urgent task

**Comment by bahrmichael** [comment]
Here are some open questions:

- Organization scoping: If I understand right, multiple organizations can exist on one Sourcegraph instance. An admin would run this query for one (or with subsequent queries multiple) organization(s). Therefore this use case only needs to take into account users that are part of an organization, right? If not, what query would an admin use to display all users (I have not seen any instance users query).

Here's an example query that would operate on an organization:

```
  organization(name:"michael-test") {
    name
    members {
      nodes {
        username
        featureFlagOverrides {
      		targetFlag {
        		... on FeatureFlagBoolean {
          		name
          		value
        		}
      		}
      	        value
            }
      }
    }
  }
```

- What do we think about the structure of the request above? Do we prefer something that reuses code with minimal addition (see above), or should we lean towards a "prettified" request schema that would add additional code. Since the above query results from adding the featureFlagOverrides field on the `User` type, the same lookup can be done for a user, or any other requests that can resolve a user. A potential issue with the structure above is that it `on FeatureFlagBoolean` hints at different types which "probably shouldn't be used by customers directly". Below is an idea for a structure that we could massage the current `featureFlagOverrides` into:

```
  organization(name:"michael-test") {
    name
    members {
      nodes {
        username
        featureFlagOverrides {
          name
      		value
    		}
      }
    }
  }
```

That's just an idea, I did not look at the implications on typing yet.

**Comment by bahrmichael** [comment]
I found another query through which instance admins can list all the users on that instance. So the org scoping question is probably resolved, as long as the user's schema has the feature flag info.

```
  users {
    nodes {
      username
      featureFlagOverrides {
        targetFlag {
          ...on FeatureFlagBoolean {
            name
            value
          }
        }
        value
      }
    }
  }
```

**Comment by bahrmichael** [comment]
I experimented a bit more with our gql layer today, and worked on the structure below. It's not working well yet, but it should give us an idea of what could also be possible.

![Screenshot 2024-03-05 at 16 35 57](https://github.com/sourcegraph/sourcegraph/assets/1830132/e381f0f7-d625-4afd-96fc-3e165739a385)

**Comment by bahrmichael** [comment]
Had a quick chat with @camdencheek and this is the request schema we'll be aiming for:

```
users {
  nodes {
    username
    evaluateFeatureFlag("test-flag")
    evaluateFeatureFlag("test-flag-secret")
  }
}
```

That should yield a list of users, their username (or any other fields that already exist on the user) and the info how one or more feature flags would evaluate for each user.
