### ISSUE TITLE
Allow configuring gateway when customer uses BYOK

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#59576]
At this point gateway works in the enterprise instance only when embeddings or completions use gateway. https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=cb%2F59262%2Fenterprise-instance-uses-gateway-for-attribution&file=internal%2Fcodygateway%2Fclient.go&editor=VSCode&version=2.2.16&start_row=46&start_col=19&end_row=46&end_col=19

For guardrails, we need to allow for separate config in case customer is BYOK

**Comment by chwarwick** [comment]
Returning the url & generating the token from the license key is easy, however the problem is that these customers will not have Cody enabled on their license and because of that may get blocked at the gateway.  One potential way to deal with this would be to enable Cody for the license but allow no requests; however I  _think_ rate limits of 0 are not currently allowed.
