### ISSUE TITLE
Search Filters: broken link to advanced filters docs

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#59597]
This link goes to an error page. This may be related to the new docs page and/or versioned docs.

![Image](https://github.com/sourcegraph/sourcegraph/assets/12631702/0bd667f2-c816-4fa1-a657-ccf67c5b12d0)

**Comment by vovakulikov** [comment]
cc @peterguy

**Comment by peterguy** [comment]
The "error" message (it's presented as an error, but it's more like a warning) happens on S2 and dotcom because they are versioned differently from the semantic versions that the docs site recognizes.

This is the error message on the docs site when coming from S2 (will change slightly as the version of S2 changes)

<img width="759" alt="Screenshot 2024-01-15 at 09 35 12" src="https://github.com/sourcegraph/sourcegraph/assets/129280/b98323bb-b208-46f8-8638-be89976a075f">

The docs link that shows that error message is https://docs.sourcegraph.com/@257706_2024-01-12_5.2-13923a7a9f66/code_search/reference/queries

Also note you can trigger the warning by putting arbitrary text after the at sign.

For a counter example, the docs site has docs for version `5.2`: https://docs.sourcegraph.com/@5.2/code_search/reference/queries

None-comprehensive list of potential solutions:
* Modify the docs site to
    * always redirect to the latest version when the version string is not recognized
    * recognize the version string pattern from S2 and dotcom, and redirect to the latest version
* Modify S2/dotcom to omit the version from the docs links.

@MaedahBatool is there a preference from the docs side on how to address this?

**Comment by jasonhawkharris** [comment]
Hey there @MaedahBatool. Just wanted to check in on this before I start working on it: 

> @MaedahBatool is there a preference from the docs side on how to address this?

**Comment by MaedahBatool** [comment]
Hey @jasonhawkharris yes please would love your contribution here. Please create a PR here: https://github.com/sourcegraph/docs
