### ISSUE TITLE
opentelemetry-collector not picking up module changes

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#60069]
Our public otel-collector image does not contain the changes in the [builder.template.yaml] (https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/wolfi-packages/opentelemetry-collector/builder.template.yaml?L26) file.

This can be verified by running `docker run  --platform linux/amd64 -it --entrypoint /bin/sh  sourcegraph/opentelemetry-collector:260262_2024-02-01_5.2-e57325307a7f` and then running `otelcol-sourcegraph components` 

`prometheus` is an expected component

Building locally with `sg wolfi image opentelemetry-collector` produces an image with the correct modules added

**Comment by willdollman** [comment]
Root cause was that the wolfi base images hadn't been updated since this change was made to the base image. Normally this is done before each release (we'd slipped behind on this but should be good going forwards).

To pull in updates immediately after updating a package we maintain, you can either use [step 7 in this docs page](https://docs.sourcegraph.com/dev/how-to/wolfi/add_update_packages#update-an-existing-packaged-dependency) or [rerun the buildkite pipeline](https://docs.sourcegraph.com/dev/how-to/wolfi/add_update_images#update-base-images-for-a-new-release) to update the automatic PR.

I've updated the images and the latest otel image from [this build](https://buildkite.com/sourcegraph/sourcegraph/builds/260365#018d698d-ea35-4c2a-bb97-3de27817b1a3) on `main` works:

```
> docker run -it --entrypoint /bin/sh index.docker.io/sourcegraph/opentelemetry-collector:260365_2024-02-02_5.2-e294192bc203

$ otelcol-sourcegraph components | grep prometheus
    - name: prometheus
```

**Comment by daxmc99** [comment]
Thank you @willdollman 
This issue appears to be fixed!
