### ISSUE TITLE
"New regular expression toggle" notification shows up on site init page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#6028]
It is showing up on the site init page, which is unintentional.

It should only show up for users for whom it is new. That means users who existed as of a previous version. I.e., if you set up a brand new 3.9 instance and sign into it, you shouldn't see this notification.

![localhost_3080_sign-in_returnTo=%2F (1)](https://user-images.githubusercontent.com/1976/66814851-20b5f900-eeec-11e9-8db9-6bb723f5e759.png)

**Comment by sqs** [comment]
@attfarhan This shows up on new instances and it is distracting. There are a lot of other things that a site admin sees after setting up an instance: this, the global alerts at the top, the onboarding, etc. It is easy to get confused. I think it is important to make this not show up for new instances or new users.

**Comment by slimsag** [comment]
I understand our admin on-boarding flow currently sucks for multiple reasons, including the ones you mentioned: global warnings / alerts about `externalURL`, needing to setup repos and find the right place to go for this, the on-boarding indicator, and more.

That said, I think that:

1) Removing this would be technically challenging / complex, as we do not have a way to determine if a user is "new" or not and there are many edge cases here.
2) Having this could in my opinion be _beneficial_ for new users (but less so for site admins). With literal search by default, we don't draw enough attention to the fact that Sourcegraph search is extremely powerful anymore because as a user you don't have to deal with its complexities anymore (a good thing).

My proposal would be to reword the alert as follows:

![image](https://user-images.githubusercontent.com/3173176/68794997-4af2f780-060d-11ea-977d-1843aa498b6e.png)

**Comment by slimsag** [comment]
If my argument here isn't bought by @sqs and @christinaforney -- then the best solution I can offer in terms of avoiding technical implementation complexity and achieving what we want would be to wait until most of our customers have upgraded to 3.9 and then remove the alert outright. We should be very careful to not remove it too early, though, as this would lead to customers on old versions upgrading and being surprised by the change without any notice (e.g. if someone goes from 3.8 -> 3.11 they would not see it). I would estimate removing it in 3.12 would be best.

**Comment by nicksnyder** [comment]
I don't think rewording the alert addresses the issue here. In any case, this should be a new issue and not a re-open of this one. I am going to close this issue since the original issue is resolved (and the screenshot is out of date) and open a new one for the new problems stated.

**Comment by nicksnyder** [comment]
Filed:
- https://github.com/sourcegraph/sourcegraph/issues/6580
- https://github.com/sourcegraph/sourcegraph/issues/6579
