### ISSUE TITLE
k8s.sgdev is funky

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#6039]
temporarily turned on builtin auth.provider and new users cannot search

![image](https://user-images.githubusercontent.com/534011/66860604-5e457100-ef42-11e9-821c-b8844453e81f.png)

even though there's like 30k repos in there

adding repos does nothing (they don't show up in the list of repos, regardless of state selector (cloning, all, not cloned...))

**Comment by tsenart** [comment]
@sourcegraph/core-services: We should find out what's going on here to determine if it's truly a release blocker or not. Leaving as release-blocker for now.

**Comment by mrnugget** [comment]
@keegancsmith and I figured it out.

The problem was that a single external service configuration had invalid "auth provider" configuration: https://k8s.sgdev.org/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjM1

That then lead to `seriousProblems` being populated here:

https://github.com/sourcegraph/sourcegraph/blob/b1f43ea108b0e93c9df3f75b7f756aaee95c53a1/enterprise/cmd/frontend/internal/authz/init.go#L35-L50

which sets `allowAccessByDefault` to `false`.

*Problem*: these `seriousProblems` are never logged or shown in the UI.

They are assigned to `/dev/null` basically: https://github.com/sourcegraph/sourcegraph/blob/b1f43ea108b0e93c9df3f75b7f756aaee95c53a1/enterprise/cmd/frontend/main.go#L52-L53

**Comment by keegancsmith** [comment]
Made it so we at least log the problems in the logs (and added extra debug info in our traces in filtering) https://github.com/sourcegraph/sourcegraph/pull/6060

**Comment by mrnugget** [comment]
@tsenart Both @keegancsmith and I think this is not a release blocker, since it has likely been there for a longer time.

**Comment by uwedeportivo** [comment]
👍

**Comment by tsenart** [comment]
@keegancsmith, @mrnugget: Moved to Backlog. Please change if necessary.

**Comment by keegancsmith** [comment]
I believe we can close this. We resolved the issue on k8s.sgdev and have filed follow-up issues on the poor visibility about the misconfiguration.
