### ISSUE TITLE
Establish a procedure of cherry-picking extension fixes when needed

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#60420]
We need a way to cherry-pick necessary fixes onto extensions once we find regressions with customer-evaluation setup. @chwarwick and @slimsag can help you here due to their prior experience with S.

**Comment by arafatkatze** [comment]
<img width="533" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/fa9f3133-3ea8-4df0-8b8a-d0933c47c9a1">


[See Thread](https://sourcegraph.slack.com/archives/C05JDP433DL/p1707783251576479)

**Comment by cbart** [comment]
Please also consider fixes to the extensions.

**Comment by arafatkatze** [comment]
The cherry picking extension fixes needs to be seen differently for different IDEs. For the purpose of this problem we deal with only 2 IDEs JEtbrains and Vscode.

## Jetbrains([Thread](https://sourcegraph.slack.com/archives/C05JDP433DL/p1707854232903989))

The overall consensus from many people to approach the updates/fixing is to start with the stable versions and stick to them with incremental updates lumped together with stable updates. In case of urgent fixes or fixes curtailed to to a specific team here's what we do(From Olaf)
- (preferred) pre-release build. Users can optionally switch to nightly channel OR download the nightly build from the marketplace and "Install plugin from disk". The second option is convenient because the user stays on the stable channel, and updates automatically to the next stable once it's out.
- (last resort) Custom build. If we have low confidence that we have fixed the issue, we can use ./gradlew buildPlugin as 
[@Ara](https://sourcegraph.slack.com/team/U06AA724TK3)
 mentioned above and ask a user to "Install plugin from disk"

## Vscode ([Thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1707893714771629))

The overall consensus from many people is to ideally stick to stable versions. Tell them a decent stable version and then tell them to STICK to it for a while. If they need specific fixes we will add those fixes to the new stable releases bundled together with other changes and ask them to move onto the new stable release. I know how to make a release super fast so that shouldn't be a problem. 

Worst case scenario: If  customers require a separate release channel (e.g., because they have a different default config), we could produce a separate "Cody Enterprise" extension. This should be just a mild manipulation of our Github actions script. 

Also its theoretically possible to bundle the application in a file and then send that too but its too much work and we shall avoid it. 

Additional notes from Beyang
<img width="1124" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/63b9a4f6-c8d9-42fe-8d06-8df36a46629c">
