### ISSUE TITLE
Bedrock endpoint patch

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#60450]

**Comment by arafatkatze** [comment]
@cbart @chwarwick can this be closed because of this [thread](https://sourcegraph.slack.com/archives/C05JDP433DL/p1707895835645139?thread_ts=1707771615.512579&cid=C05JDP433DL)?

**Comment by chwarwick** [comment]
> @cbart @chwarwick can this be closed because of this [thread](https://sourcegraph.slack.com/archives/C05JDP433DL/p1707895835645139?thread_ts=1707771615.512579&cid=C05JDP433DL)?

Not yet, we need to tighten up the process here, to keep things organized in case there are additional future needs.  

- I need to self review a bit more-make sure I didn't miss something about approach.  Generally I want to take the 3rd part providers in the direction of configure "like their 3rd party sdk suggests" so that it provides a wider set of options for configuration.  Azure already moved that direction, and I need to make sure this change doesn't make that more difficult.
- We need to get the commit reviewed and merged to main so it becomes part of future releases (we should include in 5.3.1)
- Determine the correct way to preserve this.  Likely a branch off 5.2 with a tag indicating this is in use. 
- Build the final image from there that location.

**Comment by chwarwick** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/60536
