### ISSUE TITLE
SAMS account not found on dotcom while broadcasting subscription change

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#60631]
Slack: https://sourcegraph.slack.com/archives/C06EJ55ULJ1/p1708382908501219

When SSC calls dotcom's API to refresh rate limits for the SAMS account ID, dotcom checks the `user_external_accounts` table to find the SAMS external account.

Dotcom is not able to find any user for the account id provided by SSC.

**Comment by thenamankumar** [comment]
Might be somehow related to: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/518

Not sure.

**Comment by vdavid** [comment]
Thoughts and questions moved from Slack:

1. **Severity:** What does this mean in effect? Rate limits won't get updated, right? But then it happens the first time the user uses a Cody feature, correct?

2. **Affected users:** When does this happen? I guess it's when a user hasn't signed in to dotcom since our switch to SAMS. It'd imply that this is a transient problem because of our switch to SAMS. Normally, every user would have a dotcom account connected to SAMS at this point.

3. **Solution:** What can we do? I guess we could do this (bold text signifies changes to make):
    - **Add** a check on the SSC side to see whether dotcom has a SAMS external account for the user.
    - If it doesn't exist, we **redirect** from SSC to dotcom, to a **new page**
    - Dotcom would redirect to SAMS
    - SAMS would redirect back to dotcom based on the return URL, back to the same "new page" we added
    - That page is just a redirect back to SSC.

This would take a few seconds for the user's browser, but it's pretty seamless.

Depending on the impact (see questions no. 1 and 2 above), we can do no. 3 or not do anything.

> Re: Technically the SAMS service should take care of making sure there is a an account for user on dotcom. I am not sure if we should be adding that check in SSC service.

Dotcom is just one of the clients for SAMS. I don't think it's SAMS' responsibility to ensure dotcom has an account for users. It's SSC's requirement.

**Comment by vdavid** [comment]
I'm curious about @chrsmith's opinion, but as I said above, I think this is an artifact of the Dotcom SAMS migration and has low impact on users. I'd still implement my suggested solution above, but would handle this as a P1.

**Comment by chrsmith** [comment]
Closing this out so we can use https://github.com/sourcegraph/accounts.sourcegraph.com/issues/572 as the canonical issue tracking the SAMS account on dotcom doesn't line up with accounts.sourcegraph.com.
