### ISSUE TITLE
symbols: keyword search interpreted differently for indexed vs unindexed

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#60698]
The query `repo:^github\.com/sourcegraph/sourcegraph$ repo link picker type:symbol` has two results via indexed search and no results if via unindexed search. The indexed path is the correct one here, since there is a symbol called RepoLinkPicker. Technically what Zoekt is doing is searching for any document which has those symbols not just a single symbol with those terms. So I suspect there is a bigger issue here with how symbol search interprets queries.

- Indexed link https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+repo+link+picker+type:symbol+&patternType=keyword&sm=0 
- Unindexed link https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40main+repo+link+picker+type:symbol+&patternType=keyword&sm=0

Follow-up from an extra I noticed while debugging https://github.com/sourcegraph/sourcegraph/issues/60379

/cc @sourcegraph/search-platform

**Comment by stefanhengl** [comment]
Root cause:

[maxNumSymbolResult](https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph@55d005de7ddb0148652bb42cde6b2197e01c736d/-/blob/cmd/symbols/internal/api/handler.go?L19)

for the query `repo file picker` the most relevant job we create is an AND job with three children `repo`, `file`, `picker`. The limit of 500 truncates the relevant result in "web/src/repo/RepoLinkPicker.tsx" from the `repo` child job.

One could argue that the actual root cause is that we don't have native support for AND/OR for symbol searches.

My suspicion is that customer won't hit this problem too often because the issue is limited to frequent terms and unindexed search (which we consider rare). However, this is still problematic, because there is no workaround.
