### ISSUE TITLE
observability: Grafana: CSRF token invalid error

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6075]
#### Steps to reproduce:

1. Go to https://sourcegraph.com/-/debug/grafana
2. Click the "x" on the panel in the home dashboard to close it
3. Observe the following error:

![Selection_017](https://user-images.githubusercontent.com/1646931/66977715-dfdcf200-f05b-11e9-9f28-e85da0e2462d.png)

On refresh, the panel returns, whereas I'd expect it to remain hidden

**Comment by uwedeportivo** [comment]
the PR is introducing a security hole. it wouldn't impact anything other than the opportunity to vandalize grafana dashboards, but it's not a good precedent. i like our csrf protection implementation and now that i know how this stuff works i need to have a better fix. i'll probably revert the PR if we cannot think of a way to salvage the approach.

**Comment by beyang** [comment]
Does Grafana not have its own CSRF protection? What's the security issue if the exception applies only to Grafana URLs?

**Comment by uwedeportivo** [comment]
after talking and trying it out with @slimsag it looks like we're ok:
in addition to csrf we also have cors middleware which protects us

**Comment by uwedeportivo** [comment]
grafana only has SameSite cookie attribute as csrf protection and because we're running grafana in anonymous mode there are no cookies involved.

the security issue i was worried about is somebody using csrf to modify grafana dashboards

**Comment by uwedeportivo** [comment]
i think i was wrong. CORS doesn't protect us. we still have the security hole. https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2017/september/common-csrf-prevention-misconceptions/

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Note: The way to fix this is by using Grafana's auth.proxy feature. Right now, we have Grafana in anonymous mode because when we implemented the proxying for Grafana I found a vulnerability in its handling of CSRF with auth.proxy which made it impossible to use in a secure way without having a proxy that rewrites JS (effectively impossible).

They have since fixed this in the latest version of Grafana, so we can use it now: https://github.com/grafana/grafana/issues/17316

This may also implicitly resolve https://github.com/sourcegraph/sourcegraph/issues/9720

**Comment by uwedeportivo** [comment]
👍 to get this in for the next release.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
We're working on making it easy to configure Grafana alerting through a configuration file that can be committed to VCS, which should make solving this issue less important: https://github.com/sourcegraph/sourcegraph/issues/10641

**Comment by slimsag** [comment]
@daxmc99 do you want to make a case for doing this in 3.17? My take on the situation is that this is mostly an issue today because people need to edit Grafana for setting up alerting, and doing it via a config file would be better in almost all cases, so https://github.com/sourcegraph/sourcegraph/issues/10641 becomes most important and makes this issue mostly nice-to-have

**Comment by daxmc99** [comment]
On review, this might be something to move out until #10641 is completed. It looks straightforward but grafana config would be something to commit to a VCS and store as a config file. 
For now, I will focus on https://github.com/sourcegraph/sourcegraph/issues/9983  and upgrade the deployments. 
I expect that to solve some of these issues

**Comment by slimsag** [comment]
Anyone facing this can access Grafana directly to workaround the issue: https://docs.sourcegraph.com/admin/observability/metrics#accessing-grafana-directly

I am not sure we should actually fix this.

We don't need write access to Grafana in general because we provision dashboards from disk, and I am not sure we _want_ customers modifying things in Grafana at all (instead of treating it as a read-only source for info.) Most importantly, there is not a secure way to do this without relying on the application we are proxying (Grafana) to handle POST requests in a secure way - and Grafana previously did not for a long time and wasn't responsive to me in fixing the vulnerability here. I don't think we can safely/securely do this unless we (a) fully trust the application we're proxying is secure in specifically an auth proxy coniguration or (b) that it contains no data or POST operations we would care about unauthenticated actors performing.

Can fwd' vulnerability report which has more info to whoever is interested.

**Comment by daxmc99** [comment]
Closing since wontfix

**Comment by daxmc99** [comment]
Could be fixed by https://github.com/grafana/grafana/issues/7450

**Comment by bobheadxi** [comment]
https://github.com/sourcegraph/sourcegraph/pull/17134 makes it a bit harder to run into this error (generated dashboards are no longer editable)
