### ISSUE TITLE
Default symbol sidebar to using Zoekt for indexed branches

### ISSUE THREAD

**Issue by kzh** [sourcegraph/sourcegraph#6078]
The symbols sidebar currently uses the on demand ctags generation symbols service. Similar to symbol search, we can instead take advantage of the fact that this data is already pre-generated and stored via Zoekt. For indexed branches (ex. `HEAD`), we should default to Zoekt to avoid redundant work and provide a more responsive user experience.

👩 Customers:
- https://app.hubspot.com/contacts/2762526/company/464956351

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by aisbaa** [comment]
This would be nice, since on big repos symbols sidebar tend to timeout, right round 5s mark from what I observed.

<img width="412" alt="Screenshot 2019-12-04 at 15 23 58" src="https://user-images.githubusercontent.com/82692/70146097-2fc65580-16aa-11ea-8bb7-327a84ed5c9a.png">

Though symbols tab does not seem to be used a lot, not sure if it is due to not working properly or something else.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by kzh** [comment]
I’ve started work on this.
