### ISSUE TITLE
"Show references from other repositories" broken / janky

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6124]
Repro: 
* Go to https://sourcegraph.com/github.com/gorilla/mux@ff4e71f144166b1dfe3017a146f8ed32a82e688b/-/blob/mux.go#L24:19&tab=references
* Click "Show references from other repositories"
* Observe that you need to wait a beat for button to update and the reference panel flickers during this time. Seems janky.
* Observe also that no references from other repositories show up, though at least one external reference [exists here](https://sourcegraph.com/github.com/gorilla/pat@64353c32462b061dae6304fdff2d7282ca8de838/-/blob/pat.go#L26:6)
* Nothing observed in the browser console logs.

We should probably have an e2e/regression test for this functionality.

**Update**: I did manage to see the external references left side panel show up for a bit, but then it went away and I can't get it back.

**Comment by efritz** [comment]
It worked for me, although it was slow. It looks like Go LSP is enabled on sg.com, which takes forever to find external results.

<img width="799" alt="Screen Shot 2019-10-21 at 1 47 26 PM" src="https://user-images.githubusercontent.com/103087/67233694-5b96c000-f409-11e9-82c2-b3033fdcc34b.png">

**Comment by felixfbecker** [comment]
We have this in our org settings:

```json
  // Disable language servers so that our experience mirrors the customer's first experience.
  // See https://sourcegraph.slack.com/archives/C0EPTDE9L/p1555985679033400?thread_ts=1555540818.017900&cid=C0EPTDE9L
  "go.serverUrl": "",
  "typescript.serverUrl": "",
```

I would like to challenge this - we have customers who use these languages, so what do we (outside from the codeintel team) concretely gain from seeing the first use experience but never the experience all of our customers see that actually have (and pay for) precise codeintel?

**Comment by efritz** [comment]
I may have been mistaken about LSP being enabled. In that case, the mux repo code intel is falling back to basic intel. Maybe @chrismwendt has something to add about the speed results show up.

**Comment by chrismwendt** [comment]
> * Observe also that no references from other repositories show up, though at least one external reference [exists here](https://sourcegraph.com/github.com/gorilla/pat@64353c32462b061dae6304fdff2d7282ca8de838/-/blob/pat.go#L26:6)

Sometimes the Go Sourcegraph extension won't find any references because it only looks in the first 30 repositories returned from a godoc.org query for the import path. Often times, a repository will import a package but not use the specific symbol you're interested in, resulting in wasted computation.

On the slowness: each of those 30 repositories initiates a separate WebSocket connection, initializes go-langserver, and makes an LSP request, which is kind of like opening 30 browser tabs at once.

There may be ways to improve the efficiency of this operation, such as using text search as a prefilter.

> * Observe that you need to wait a beat for button to update and the reference panel flickers during this time. Seems janky.

The speed/jankiness might be caused by a couple network round-trips to edit and fetch user settings in the extension host (not in the extension). Here's the part of the extension manifest that provides the button (notice `updateConfiguration`):

```json
      {
        "id": "externalReferences.toggle",
        "command": "updateConfiguration",
        "title": "${config.go.showExternalReferences && \"Hide references from other repositories\" || \"Show references from other repositories\"}",
        "commandArguments": [
          [
            "go.showExternalReferences"
          ],
          "${!config.go.showExternalReferences}",
          null,
          "json"
        ],
        "actionItem": {
          "label": "${config.go.showExternalReferences && \"Hide references from other repositories\" || \"Show references from other repositories\"}"
        }
      },
```

https://github.com/sourcegraph/sourcegraph-go/blob/b580599a6a7722ccb2217044a44b79a149409d73/package.json#L22-L37

**Comment by beyang** [comment]
So not a regression; I just got unlucky?

**Comment by beyang** [comment]
So not a regression; I just got unlucky?

If this will be obviated by LSIF work, feel free to close.

**Comment by chrismwendt** [comment]
> So not a regression; I just got unlucky?

Correct, this is how LSP-based global refs for Go have worked since I created the extension.

> If this will be obviated by LSIF work, feel free to close.

Yes, global find refs will be much better with LSIF (assuming all repos have LSIF data uploaded).
