### ISSUE TITLE
Add reliable way to opt out of the Svelte experiment

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#61298]
We want to rollout specific pages of the Svelte prototype on S2. To do this we can enabled the `web-next-rollout` feature flag. This feature flag tells the server to serve the Svelte application for specific routes.

We should also provide a simple way for the user to opt-out of this. It's technically possible to do this by adding feature flag overrides to the URL, but that ultimately results in  a broken experience:

- The server respects the override and serve the React version. The override is persisted in local storage and and whenever we check for the feature flag value it will now be false. Most importantly that causes links to stay inside the React app.
- Problem: When the user goes to S2 again (e.g. in a new tab) they will be served the Svelte version (the server doesn’t now about any override since it’s not in the URL). This might already be surprising to the user. Now if they navigate to the link in the React version and e.g. click Search Home in the menu they will stay in the React version because that link is affected by the local override. This is an inconsistent experience.

Things to do:

- Allow user's to override feature flags for themselves. If we can permanently set the feature flag on the server we avoid the server state/local state mismatch.
- Update the opt-out link to set the feature flag on the server instead.
- Replace the current beaker button in React app with a more descriptive button to opt back in and possible also opt into the full svelte experience (i.e. the repo pages) by overriding the `web-next` feature flag (which is what the beaker button currently does but only via the URL, not permanently)

**Comment by camdencheek** [comment]
Okay, so, looking closer, I do not think feature flags are going to be the best way to move forward. They'll require some significant updates to get working for this work.
1) Currently, we only have "create", "delete", and "update" operations. No "create or update", which means we need to make one request to fetch the override ID and a second to update or create it. Not ideal.
2) Modifying "create" to act like "create or update" is also a pain since we have two unique constraints and Postgres does not allow "ON CONFLICT" clauses for two different constraints. (Looking forward to the MERGE command in PG15).
3) The DB constraints on feature flags also require that the feature flag exists in order to create an override for it. Also not ideal for this scenario.
4) The discoverability of feature flags is still not great. 

Our settings API already allows patching settings, so I think maybe we just make the svelte webapp and svelte rollout experimental features.

**Comment by fkling** [comment]
Can we easily read the settings on the server during the request?

**Comment by camdencheek** [comment]
Yes, we can
