### ISSUE TITLE
Create exit survey to capture why users cancel

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#61355]

**Comment by chenkc805** [comment]
@rrhyne - since you're working on those confirmation pages, maybe we can squeeze in an exit survey if a user cancels onto a page that we can direct churned users to. What do you think?

**Comment by chenkc805** [comment]
Instead of building this with engineering, we'll just do this every month manually for users who churned. 

Here's the spreadsheet I used for the previous survey: 
- https://docs.google.com/spreadsheets/d/1bLb_MECscqEoLOQljLrpdg5lLhzPL_9h4Nu3I35SV1M/edit#gid=1324299288

Here's the results
- https://docs.google.com/spreadsheets/d/1CgYDrx4T27huw-K_ne-r9wIRrUY28dvIz5_t5wddoAk/edit?usp=drive_link

Here's the email copy we used:
Subject Line: We'd Love Your Feedback! <5 min survey

Dear [name],
We noticed that you recently canceled your subscription to Cody Pro. 

We're sorry to see you go, and we want to learn from your experience to improve our product.

Your feedback is incredibly valuable to us. It helps us understand what we're doing well and where we can enhance our service to better meet the needs of our customers. That's why we've put together a quick survey, which should take <5 minutes.

<EMBEDDED TYPEFORM SURVEY> 

By completing this survey, you'll be providing us with insights that will directly shape the future development of our Cody Pro. We take customer feedback very seriously, and your responses will be carefully reviewed and acted upon.

Thank you in advance for your feedback. We're committed to continuously improving our product, and your input is invaluable in helping us achieve that goal.

Best regards,
The Cody team at Sourcegraph
