### ISSUE TITLE
Claude-3 models are showing red on sourcegraph.com Cody subscription section

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#61351]
The Claude-3 models are displaying in red, this usually signals they are not valid values, however these should (and do) work.  

![Image](https://github.com/sourcegraph/sourcegraph/assets/6098507/d3f1aa34-8b31-437f-8b0f-17d55286dd74)

**Comment by chwarwick** [comment]
The Claude-3 models are displaying in red, this usually signals they are not valid values, however these should (and do) work.  


![Image](https://github.com/sourcegraph/sourcegraph/assets/6098507/d3f1aa34-8b31-437f-8b0f-17d55286dd74)

**Comment by chwarwick** [comment]
cc @philipp-spiess in case you know off hand where to set this.

**Comment by RXminuS** [comment]
Got started on this, but stuck on getting dev-environment working. https://github.com/sourcegraph/sourcegraph/compare/main...rik_nauta/model-badges

**Comment by philipp-spiess** [comment]
@chwarwick Maybe this runs an old server version? This is set here: https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx#L43-L45

**Comment by arafatkatze** [comment]
@chwarwick  I see that the code for this stuff is [here](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fsourcegraph.git&branch=count-token&file=client%2Fweb%2Fsrc%2Fenterprise%2Fsite-admin%2Fdotcom%2FproductSubscriptions%2FCodyGatewayRateLimitModal.tsx&editor=VSCode&version=2.2.16&start_row=164&start_col=13&end_row=172&end_col=13) but I try to go upstream into the [CodyServicesSection](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fsourcegraph.git&branch=count-token&file=client%2Fweb%2Fsrc%2Fenterprise%2Fsite-admin%2Fdotcom%2FproductSubscriptions%2FCodyServicesSection.tsx&editor=VSCode&version=2.2.16&start_row=66&start_col=13&end_row=66&end_col=32) which has the UserSubscriptions route if as the upstream if you keep going upstream.

I am still not sure of the exact edge case of when this appears and I don't have the user with myself to be able to replicate this. But I agree with philips understanding that this is happening because of an older instance [not supporting the model list  ](client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx) on those branches because the name of the claude 3 models does not exist the model switches to the[ default category of "danger"](client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx) which makes them red.

**Comment by philipp-spiess** [comment]
Rolling this out now, this was stuck for some reason see https://sourcegraph.slack.com/archives/C04MYFW01NV/p1711370382944259

**Comment by philipp-spiess** [comment]
<img width="943" alt="Screenshot 2024-03-25 at 13 50 56" src="https://github.com/sourcegraph/sourcegraph/assets/458591/92dd9144-8b0e-424e-ab3f-f6e98f41fa86">

yeah it was just a lagging rollout. all good :)
