### ISSUE TITLE
Code Insights export to CSV failed to export with data error: extended protocol limited to 65535 parameters

### ISSUE THREAD

**Issue by Galindo-J** [sourcegraph/sourcegraph#61353]
- **Sourcegraph version:** Observed on v5.3.2 & v5.2.4
- **Platform information:** 

#### Steps to reproduce:

1. Create an Insight with a user account using a query that runs over a large number of repos that the user does not have access to. 
2. Attempt to export the results to CSV.

#### Expected behavior:
Export is successful 

#### Actual behavior:
Export errors with the following
`failed to export data: failed to fetch all data for insight: fetching archived code insights data: extended protocol limited to 65535 parameters`

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by camdencheek** [comment]
[Slack context](https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1710346770335499?thread_ts=1710201929.953689&cid=C05EA9KQUTA)

**Comment by bahrmichael** [comment]
Recap from the Slack conversation:

There's this part in the code that lists all the repositories that a user does NOT have access to: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@153e84aed28bd258fa1073e427a3757897e86365/-/blob/internal/insights/store/store.go?L900-906

We then send that list into a follow-up query. If there are too many repositories that you don't have access to, then 💥 .

A possible fix could be to remove this roundtrip through the application layer, and keep the evaluation in the database. To do that we need to bring the conditions of https://sourcegraph.com/github.com/sourcegraph/sourcegraph@153e84aed28bd258fa1073e427a3757897e86365/-/blob/internal/database/repos_perm.go?L84:6-84:21 into https://sourcegraph.com/github.com/sourcegraph/sourcegraph@153e84aed28bd258fa1073e427a3757897e86365/-/blob/internal/insights/store/store.go?L982.

**Comment by bahrmichael** [comment]
Questions:

- Do we have tests that populate the database (preferably a real postgresql engine that can run and verify our query) with 10k+ records, or tests that I could base such one on? I would prefer to add a test that can prevent this bug from reappearing, but I'm afraid that this may take very long to run.

**Comment by peterguy** [comment]
It looks like this error happens because there are more than 65k predicates being fed to [this query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9a2960c014e71147271f69bd67948cc462439179/-/blob/internal/insights/store/store.go?L970). We should be able to get around this 65k limit by chunking up the [array of predicates](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9a2960c014e71147271f69bd67948cc462439179/-/blob/internal/insights/store/store.go?L911) so there are fewer than 65k of them every time we [join them using AND](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9a2960c014e71147271f69bd67948cc462439179/-/blob/internal/insights/store/store.go?L968) and run the query.

Those predicates include both [included](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@153e84aed28bd258fa1073e427a3757897e86365/-/blob/internal/insights/store/store.go?L925) and [excluded](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@153e84aed28bd258fa1073e427a3757897e86365/-/blob/internal/insights/store/store.go?L913) [repos](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@153e84aed28bd258fa1073e427a3757897e86365/-/blob/internal/insights/store/store.go?L933), so I'm not sure that removing excluded repositories will shrink the list enough to always avoid this error.

**Comment by camdencheek** [comment]
> We should be able to get around this 65k limit by chunking up the [array of predicates](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9a2960c014e71147271f69bd67948cc462439179/-/blob/internal/insights/store/store.go?L911)

Preferably, we don't have an array in the first place. If you zoom out one level, we query the list of excluded repos first, then use that as an argument. Instead, we can just add that permissions clause to the query so it all runs in-DB

**Comment by camdencheek** [comment]
> Do we have tests that populate the database

I'm not sure we have any specific test. However, we do have tests that run against a real DB (see [dbtest.NewDB](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@698bc0590435b619f2f6aa68823d59e2e3e4f450/-/blob/internal/adminanalytics/users_test.go?L70-70)). You can write a routine that populates it with a ton of repos, then run your test against that.

**Comment by bahrmichael** [comment]
Making good progress, and have a local proof of concept with the more advanced query.

---

For later reference here's a test before a fix that reproduces the error in `store.go`:

```
	t.Run("respects repo permissions", func(t *testing.T) {
		var repoIds []api.RepoID
		for i := 0; i < 70_000; i++ {
			repoIds = append(repoIds, api.RepoID(i))
		}
		permissionStore.GetUnauthorizedRepoIDsFunc.SetDefaultReturn(repoIds, nil)
		defer func() {
			// cleanup
			permissionStore.GetUnauthorizedRepoIDsFunc.SetDefaultReturn(nil, nil)
		}()
		got, err := seriesStore.GetAllDataForInsightViewID(ctx, ExportOpts{InsightViewUniqueID: view.UniqueID})
		if err != nil {
			t.Fatal(err)
		}
		if len(got) != 0 {
			t.Errorf("expected 0 results due to repo permissions, got %d", len(got))
		}
	})
```

Leads to:

```
        -----: extended protocol limited to 65535 parameters
```

---

I will now push a WIP version for the query that can deal with more than 70k repo permission entries. It needs some more work to get all the auth variations ported, but I don't expect any blockers here.

**Comment by camdencheek** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/61580
