### ISSUE TITLE
Svelte: Implement File and Directory Popovers

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#61930]
We have these new file and directory popovers that should be available from hovering an item in the file tree.

## File

<img width="570" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/527b6fe6-4d92-43d0-bdd4-e5742989becc">

## Directory

<img width="577" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/b5f3741a-2f5f-4d0a-addb-bdc0f0ec5db2">

Figma: 
https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=3076%3A268943&mode=design&t=EoCY3jMhKH1y7A0N-1

**Comment by jasonhawkharris** [comment]
@taiyab Okay. I've run into some limitations here I wanted to let you know about. These will change the designs you've put forth. I wanted to get your okay on where we're at in terms of what data we're actually able to display:

1. OWN - Own is a mess at the moment, and I think getting that info to display here is probably more trouble than it's worth for now. For the time being, I recommend forgoing the own section completely. This applies to both files and directories. 
2. There really isn't a good way to get total size of a directory. We could probably add a `totalBytes` field to the backend, but I wouldn't know how to do this without slowing everything else down in the process.  
 
At the moment, this is how we're looking on both versions of the popover: 

For Files: 
![Screenshot 2024-05-06 at 12 34 50 PM](https://github.com/sourcegraph/sourcegraph/assets/62355966/3c34237f-d1d0-4273-828f-ee251e068b69)

For Directories: 
![Screenshot 2024-05-06 at 12 34 29 PM](https://github.com/sourcegraph/sourcegraph/assets/62355966/af209fe2-5fd4-461e-84d7-0802c941b04b)

**Comment by taiyab** [comment]
@jasonhawkharris This is looking great! 👍 

To address what you said:
1. Happy to eliminate it for now. We need to note somewhere to come back to OWN as we actually need to make it a functional part of the product.
2. Happy to merge without it and come back to it. Keep in mind, this could just fetch the size data on hover, so it shouldn't slow much down. @camdencheek for ideas on getting that data in correctly. It should be identical to what we already have on the blame view header but for all entities.

A few other (minor) points, which are probably already on your mind:
- Where it says `gen.go` or `internal` in the screenshots, it should be the full path. I get if we add this now, the path can get long, so we'll need to use the same `...` convention we intend to use for the full path for the file header. We intend to do the same thing as the React version which is to add an ellipses inbetween the first directory and parent directory of the selected/hovered file/dir. So `something/.../something/file.go`
- We can probably remove the `@` symbol in the "Last Changed @" heading. Looking back at it now, could be confusing as you might expect something directly after it (I know this is in the designs, so this is me changing my mind)

Thanks for your great work @jasonhawkharris!

**Comment by jasonhawkharris** [comment]
@taiyab I think Own, in general, needs a bit of an overhaul. I think the product is better with Own and we should address this in a future sprint. 

I think there is a way to get total size of all files in a directory, but there isn't any processing for it in the backend at the moment. I suppose there is a world where we could calculate this on the frontend, but that doesn't seem like a great solution. In any case, adding this to the request will lead to slower response times because, from what I can tell, we don't have this number hanging out somewhere ready to pull with the rest of the data. We'll need additional processing. @camdencheek can you confirm this?

> Where it says gen.go or internal in the screenshots, it should be the full path

So, in that scenario, gen.go actually is the full path. It is at the root of the directory, so it's only parent is the root folder, hence why it's just showing up here as the file name. Same for internal. Here's a screen shot of what will happen with longer path names: 

![Screenshot 2024-05-07 at 10 51 33 AM](https://github.com/sourcegraph/sourcegraph/assets/62355966/5fd6cedb-5a56-42a2-9a92-05c0e20e48a6)

I'll remove the @ sign.

**Comment by camdencheek** [comment]
> Keep in mind, this could just fetch the size data on hover, so it shouldn't slow much down.

Fetching on hover doesn't really solve this because it is calculated on the fly and it scales in cost with the number of files in the entire subdirectory tree. So if your repo has 1M files, we're making 1M+ network requests in the backend.

I'd really love to add some aggregated, pre-computed stats like the language distribution, file count, byte count, line count, etc. for each directory. This would also be useful for the language stats code insight and various other places that end up being surprisingly expensive. I don't _think_ this is super high priority...but I've wanted it enough times that maybe it's worth adding 🙂

**Comment by taiyab** [comment]
> I'd really love to add some aggregated, pre-computed stats like the language distribution, file count, byte count, line count, etc. for each directory. This would also be useful for the language stats code insight and various other places that end up being surprisingly expensive. I don't think this is super high priority...but I've wanted it enough times that maybe it's worth adding 🙂

I'm intending to use all this stuff in a lot of different places in the future, so we should invest the time do this now.
