### ISSUE TITLE
Revive explore page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#6260]
The link to the explore page was removed in a recent commit accidentally: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+explore+type:diff+f:NavLinks+after:%223+months%22&patternType=regexp

It should be added back to `NavLinks.tsx`.

**Comment by sqs** [comment]
@christinaforney:

> Thoughts on moving the explore link to the dropdown list near help? While it’s not an issue now, it will start to get noisy up in the top bar and I’d like to keep it clean. Concerns are that it would be too hidden to be useful at all.

That sounds reasonable. But I have an alternate proposal to address the "too noisy up in the top bar": make the search bar not expand to fill all remaining width. Especially as the search default experience becomes interactive search, it will need less width. Even now, it rarely needs the full width. That gives us more room to put important links in the top (such as in the future campaigns, perhaps notifications, etc.).

**Comment by christinaforney** [comment]
Agree we should change the search bar width, especially since we'll be taking up some space with the multiple modes toggle in that area. Given the valuable content we're adding in this area with campaigns/notifications, does the explore link fit in terms of use/importance with these? Or is it more of a discovery/guidance link that people would still seek out via the dropdown nav? 

For consistency, it feels like items in the top should cause action within the application (getting started checklist/notifications/cloning status/campaigns/command palette) compared to informational/configuration (help, settings, explore). 

We don't need to solve this right now, so I'm sending a PR to add explore back to it's original spot.
