### ISSUE TITLE
Add dev docs page on how to spin up/down AWS and GCP VMs for testing

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6273]
Teammates regularly claim that they shut down their test instances, and then I see continued spend associated with their linked accounts. @ggilmore, this recently happened with you, and you figured out how to get it down to zero... 

If you can throw a single set of bullets into our docs, I'd REALLY appreciate it. If you're too busy, but you can put the bullets into this thread for me, I will publish it :).

**Comment by ggilmore** [comment]
Lately I've been using https://github.com/gruntwork-io/cloud-nuke, but that only was feasible since I've been running other instances in separate AWS accounts (running it in our main AWS account would delete everything). 

I swore an RFC about moving our infrastructure to Terraform - but I can't find it in Google Drive for some reason (was it deleted). In any case, something like that is what would be needed here (and would be decently involved).

**Comment by daxmc99** [comment]
@dadlerj If this is still a concern, please reopen but we do have some resource creation tracking via the distribution resource bot.
