### ISSUE TITLE
v5.4.5071 Security approval

### ISSUE THREAD

**Issue by craigfurman** [sourcegraph/sourcegraph#63107]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [x] All feasible CVEs are closed.
- [x] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by craigfurman** [comment]
cc @jdpleiness @DaedalusG

**Comment by evict** [comment]
https://www.notion.so/sourcegraph/Accepted-CVEs-for-Sourcegraph-5-4-5071-5bd83735240c4e05bb1d7f8ffe318209?pvs=4 

in case we decide to rebuild the image and include https://github.com/sourcegraph/sourcegraph/pull/63104, i can always remove the issues. Since it's only impacting `server` it's OK to go ahead in case it's not feasible.
