### ISSUE TITLE
Literal search: not possible to search for "/-/godoc"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6314]
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+/-/godoc&patternType=literal

**Comment by unknwon** [comment]
I guess this is similar to what we discussed about `:`, you would have to use regexp search for now: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22/-/godoc%22&patternType=regexp

**Comment by attfarhan** [comment]
This is a very weird one. For some reason, doing this search makes our `detectPatternType` function return `-1` and an error even though the patternType is passed properly.

**Comment by attfarhan** [comment]
@rvantonder, this breaks at https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search.go?utm_source=VSCode-1.0.14#L155-158. It appears our Parser does not like `/-/godoc` as an input.

**Comment by rvantonder** [comment]
It's happens here in the parser, I'm still looking into how to go about it: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/pkg/search/query/syntax/parser.go#L175

Note: I don't think this crops up in the 3.9 release (didn't test), because running `Parse` on the query in this part of the code was part of the refactor I did.

**Comment by rvantonder** [comment]
Alright, so the scanner generates a (regex) pattern token because of the [`/.../` syntax](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/pkg/search/query/syntax/scanner.go#L118), which makes sense as far as the current parser. As a compromise to implementing/changing the parser for literal search, I suggest we go with the suggestion to [extract the pattern type with regex](https://github.com/sourcegraph/sourcegraph/pull/6256#issuecomment-547850214) within this function (only).
