### ISSUE TITLE
Subscriptions are created in a "canceled" state by default

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#63225]
Subscriptions are being created in a "canceled" state. Here is a [30-sec Loom](https://www.loom.com/share/ea13b13f1e7148848bf16d50a92423f0) that demoes what happens.
This is after https://github.com/sourcegraph/sourcegraph/pull/63213 was merged.
The expected behavior is for new subscriptions to auto-renew monthly.

**Comment by chrsmith** [comment]
This is super confusing, but we need to be clearer in the terminology:

The Subscription is NOT in the `canceled` state. Rather, the Subscription is in the `activate` state, but the `CancelAtPeriodEnd` is set to `true` rather than the expected false`. (So it _will be canceled_, rather than _IS_ canceled.)

**Comment by chrsmith** [comment]
This looks like there is a but somewhere on our side. Here's how to see how the Subscription was created:

1. Log into Stripe and drill into the Customer

<img width="1345" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/4029847/83ecb4c6-0639-4560-93d0-db15fe23081d">

2. Drill into the Subscription

<img width="1312" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/4029847/be14a6dc-aa43-4e1e-8ecf-cae5a37bd0a4">

3. At the bottom of the page in the Stripe Console is a list of "logs and events", which should give you the history for what modifications were made, by who, etc.

<img width="692" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/4029847/44ff13a8-48a1-4b91-af49-443b2df069f4">

So this is the HTTP request we made to create the subscription, and we are clearly setting the `cancel_at_period_end` to `true`. So perhaps some wire is getting crossed due to a typo or something when we are transitioning from the `api` package to the `product` package, etc.

But ultimately, we just need to double check that the call to `stripe.SubscriptionsService::New` has the right "options" on it. (i.e. setting `CancelAtPeriodEnd` to be `false`.)

<img width="1003" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/4029847/36519ee3-d0c3-458c-a14a-e9864d08ca7f">

**Comment by chrsmith** [comment]
Remember how in my first comment I said "this is super confusing and easy to get wrong"... well the problem is that we are using our own `product.CreateTeam` function for the first time. And it's had the wrong default for, like, ever.

https://github.com/sourcegraph/self-serve-cody/blob/main/cody/backend/internal/product/create_team.go#L15-L16

We just need to change that 🤦 .

**Comment by chrsmith** [comment]
https://github.com/sourcegraph/self-serve-cody/pull/870 should fix this. Sorry for the noise.
