### ISSUE TITLE
a8n: Gracefully handle changeset deletion in code hosts

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#6396]
Some code hosts allow changesets to be deleted, others don't. For instance, GitHub pull requests can't be deleted (only closed or merged), but Bitbucket's PRs can.

To be reliable in the face of upstream deletions of changesets, the `a8n.Syncer` must be changed to handle this scenario gracefully.

My intuition is that if the changeset is deleted on the code host, we should delete it on Sourcegraph, as we do for repositories.

But that may be weird if we were the ones creating the changeset upstream and someone deleted  manually. @sourcegraph/automation, @sqs: Thoughts on the desirable user experience here?

**Comment by sqs** [comment]
The UX would be weird because 

1. we currently have no way to show that a changeset was deleted, it would just disappear (creating the misconception that progress was made toward completing the campaign)
1. presumably (when we support editing/updating campaigns) in the future, we would then try to recreate the changeset, which would probably violate the user’s intent

To mitigate (1) can we show a timeline event if a changeset is deleted?

For (2), I’ll ask customers on BBS in what cases they delete PRs and will incorporate that info into the plan for when we support updating campaigns.

**Comment by tsenart** [comment]
> To mitigate (1) can we show a timeline event if a changeset is deleted?

I think that is doable. We could also set a `deleted_at` flag and show it clearly in the UI that the changeset has been deleted upstream. What do you think would be best?

**Comment by sqs** [comment]
> We could also set a deleted_at flag and show it clearly in the UI that the changeset has been deleted upstream.

👍

**Comment by tsenart** [comment]
cc @sourcegraph/automation

This needs a frontend mock up on how this would look. @felixfbecker: Can you add it to your backlog?

**Comment by felixfbecker** [comment]
I'd imagine we simply add a fourth state `DELETED`, with a 🗑 icon, and also add it to `ChangesetCounts` so it's considered in the burndown chart (same color as closed).

**Comment by mrnugget** [comment]
> also add it to `ChangesetCounts` so it's considered in the burndown chart (same color as closed).

Does that mean it also contributes to the `Closed` count? Or do we add a `Deleted` count and just display them in the same color?

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
