### ISSUE TITLE
Impossible to search for colons in literal search

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6490]
It is impossible to search for a `:` character in literal search mode because we treat it as a special character to denote a search filter. Escaping `\:` does not work, and you can't wrap it in quotes. 

Slack thread: https://sourcegraph.slack.com/archives/C07KZF47K/p1572557671374200

**Comment by attfarhan** [comment]
The thread has one suggested solution which is to relax the filter parsing we do. If a user puts a colon, and the filter is not valid, we should treat the colon surrounding string as literal, not as a filter.

The pushback is that users would then not know if they put an invalid filter if they got no results, but RFC 14 will introduce keyword highlighting that will decorate filters that are detected in the query.

**Comment by felixfbecker** [comment]
The other problem would be that you might want to search for something that is also a valid filter, e.g. `file:.*foobar` to search for a property declaration `file` followed by something containing `foobar`. There might be ways to then workaround that again, but it would further mystify the search syntax instead of improving confusion, and you get into a rabbit hole of workarounds.

**Comment by rvantonder** [comment]
It is not possible to search for patterns that clash with our parser syntax without a quote/escape mechanism. We've decided not to add escaping to literal search for the foreseeable future. But: it is now possible to work around this issue for all searches using the `content:` field, which overrides the search pattern. So, the following are all valid and work as expected:

`content:"repo:foo"`
`content:"file:.*foobar"` 

etc.

**Comment by raxod502-plaid** [comment]
When searching for `content:"keyword: \^?1"` I'm getting `Type error at character 0: invalid quoted string: "keyword: \^?1"`. Regex search is enabled. I tried getting rid of the quotes, but then the part of my query after the space is ignored. I tried putting a backslash in front of the space, but then my search returns no results which is definitely not correct.

I just want to do a regex search for `keyword: \^?1`. Is there a way?

**Comment by rvantonder** [comment]
Hey @raxod502-plaid. Sounds like you're on a slightly older version of Sourcegraph, `< 3.20`, so I'm going to try give an answer that will work on that version. The answer I'd like to give you is that you need to escape the `\` because it's inside the quotes, so your query would be:

`content:"keyword: \\^?1"`

But, there was previously a bug where this would not be interpreted for regular expressions and was fixed in versions `>= 3.22`. In fact, in recent versions, you don't need `content`, and can simply do `keyword: \^?1` which should work.

For `< 3.20`, I am wondering if you'd get by doing this possibly:

`keyword:\ \^?1`

but I suspect that it will complain that `keyword` is not recognized, and because of the bug between `3.20` and `3.22`, using `content` won't help you to escape this 😞

**Comment by rvantonder** [comment]
Ah wait! There's hope. Try this:

`/keyword: \\^?1/`

or

`/keyword:\\ \\^?1/`

**Comment by rvantonder** [comment]
Oh, if you're just trying to escape the carat, `/keyword: \^?1/` should be sufficient!

**Comment by raxod502-plaid** [comment]
Yes, we are currently running version 3.17.1. Your last suggestion, `/keyword: \^?1/`, works perfectly—the alternate regexp syntax with slashes seems to work around all the issues. Thank you so much!

**Comment by rvantonder** [comment]
Great!
