### ISSUE TITLE
a8n: Preview campaign with wait: false returns less results

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#6620]
As @mrnugget mentioned on slack, 
> when using "wait": false the repository search returns less results. And when specifying "wait: true", the request timeout kicks in after ~60s.

**Comment by mrnugget** [comment]
The problem: with a search query like `repo:github`, which should match all 187 repositories I have in my instance, and `wait: true` the search returns all 187 repositories. If I specify `wait: false`, the search returns 1 or 2 repositories, no errors.

Here is the relevant part of the code:

https://github.com/sourcegraph/sourcegraph/blob/102292039d12ce22a6630745b3cffc390e81edda/enterprise/pkg/a8n/resolvers/resolver.go#L433-L449

From my first debugging experiments it seems that the search function used here, `graphqlbackend.SearchRepos`, returns early and a limited number of repositories when we use the `context.Background()`.

Since `graphqlbackend.SearchRepos` constructs a new `searchResolver` and gets fresh `context.Background` I can't come up with an idea of why this happens:

https://github.com/sourcegraph/sourcegraph/blob/102292039d12ce22a6630745b3cffc390e81edda/cmd/frontend/graphqlbackend/search.go#L776-L799

**Comment by slimsag** [comment]
The problem here (educated guessing) is that if you want to consume the entire result set in both cases, you need to specify either `count:999999999` or `timeout:2m` as part of your query string. I would suggest doing this via string manipulation for now (in the future, we can use the paginated search API).

The Go context controls when the search returns, but not how many results we try to find. When there is no count parameter or timeout specified, we have a small time budget for results and aggressively return quickly once we found enough.

**Comment by slimsag** [comment]
Also I filed https://github.com/sourcegraph/sourcegraph/issues/6627

**Comment by slimsag** [comment]
Note: this is the same behavior you see in the product as a user, e.g. https://k8s.sgdev.org/search?q=Router&patternType=literal vs. https://k8s.sgdev.org/search?q=Router+count:999999999&patternType=literal

**Comment by slimsag** [comment]
To clarify a bit, there are three aspects at play here:

- The Go context timeout, which has the deadline for the overall search.
- The file match limit (`count:`), which [defaults to a measly 30](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@676a10a/-/blob/cmd/frontend/graphqlbackend/search.go#L215) (because that is good in our UI use case).
- The user-controllable `timeout:` which overrides your Go context timeout: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@676a10a/-/blob/cmd/frontend/graphqlbackend/search_results.go#L824 and defaults to a measly 10s *unless* `count:` is specified in which case it is an unlimited timeout.

Thus, specifying `count:99999999` solves this.

Also, I would highly suggest ensuring your queries always have `index:only` or are scoped to a small number of repositories, because running large queries like this against unindexed search can cause considerable harm to instances unfortunately.

**Comment by mrnugget** [comment]
But only the first one, the Go context timeout, is relevant here, right?

When we switch between `wait: true` or `wait: false` the only thing that changes is the `ctx` passed to `graphqlbackend.RepoSearch`.

And if we pass in the user-request `ctx` the search _does return all results_, even if no `timeout:` or `count:` is specified in the query.

**Comment by mrnugget** [comment]
Yeah, I can confirm my suspicion: `count:99999` does nothing. Here are my debug log outputs:

With `context.Background()` the query `repo:k count:99999` returns 2 results:

```
INFO Starting search, query: repo:k count:99999
INFO searchResuler.Results done, ctx: context.Background, alert: <nil>
INFO Search done, query: repo:k, duration: 11.925166ms
INFO Creating CampaignPlan and CampaignJobs, len(rs): 2
```

With the request `ctx` passed in the query `repo:k count:99999` returns 29 results:

```
INFO Starting search, query: repo:k count:99999
INFO searchResuler.Results done, ctx: context.Background.WithValue(type *http.contextKey, val <not Stringer>).WithValue(type *http.contextKey, val 127.0.0.1:3082).WithCancel.WithCancel.WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type sessions.contextKey, val <not Stringer>).WithValue(type actor.key, val Actor UID 1, internal false).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>), alert: <nil>
INFO Search done, query: repo:k, duration: 2.928013ms
INFO Creating CampaignPlan and CampaignJobs, len(rs): 29
```

**Comment by slimsag** [comment]
You are right, this particular issue is only related to the Go context, I see that now. That said, you will run into the issue I described above later on when you start searching over large #s of repos

**Comment by slimsag** [comment]
At first the fact that using context.Background here changes the behavior to include _less_ results made zero sense to me: If anything, that context is longer lived so it should give you more results, right?

But something came to mind: auth. With your request context when `wait: true` is specified, you are presumably an admin and bypass all auth, but with `context.Background()` you lose all of that so maybe that excludes a large number of repos for some reason on whatever instance this is being tested on?

**Comment by mrnugget** [comment]
> But something came to mind: auth. With your request context when `wait: true` is specified, you are presumably an admin and bypass all auth, but with `context.Background()` you lose all of that so maybe that excludes a large number of repos for some reason on whatever instance this is being tested on?

I think that might be it!
