### ISSUE TITLE
automation should not construct searchResolver itself

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6627]
automation is currently constructing the search resolver itself in the GraphQL package:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@676a10a3370362d070f6bf3fea83c40c8de88652/-/blob/cmd/frontend/graphqlbackend/search.go#L773-798

This is brittle because it is only used by a8n and bypasses all of the other logic we execute before initializing a search resolver for regular GraphQL search queries:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@676a10a/-/blob/cmd/frontend/graphqlbackend/search.go#L77-125

I suggest you modify `SearchRepos` to call into `(&schemaResolver).Search(...)` because:

- It is easy for someone to add code to `(*schemaResolver).Search` that would break `SearchRepos` today.
- By not reusing `(*schemaResolver).Search`, it would be harder to adopt paginated search in a8n in the future.
- You are currently missing out on proper defaults like literal search and validation of your search queries due to this.

@mrnugget I am assigning you but unsure if you are the right owner, feel free to reassign

**Comment by mrnugget** [comment]
Another idea I have (see #6572) is to use `zoekt.Searcher.List` instead of going through the whole search path, since we're really only interested in repositories. @keegancsmith recommend that in https://github.com/sourcegraph/sourcegraph/pull/6309#issuecomment-548691096 and I think that makes a lot of sense for what we're trying to do here.

**Comment by slimsag** [comment]
I would suggest exposing that functionality through the search syntax instead, customers have had a desire for that same functionality and us needing it is a good signal we should have it exposed. i.e. adding something like `type:repotextmatch` such that `index:only type:repotextmatch foobar` effectively just translates into `zoekt.Searcher.List`.

**Comment by slimsag** [comment]
Also, if automation users are providing these queries (I assume they are) then they will need the defaults that we configure at a higher level than `zoekt.Searcher.List` (such as literal search by default instead of regex, etc)

**Comment by mrnugget** [comment]
> This is brittle because it is only used by a8n and bypasses all of the other logic we execute before initializing a search resolver for regular GraphQL search queries:

I agree somewhat, but also not entirely, because in a8n we do have the luxury of being able to support only one version of the search api (for now) so I started using `(&schemaResolver).Search(...)` but then removed the things we don'tneed and got rid of the state (`*schemaResolver`) and that's how I ended up with this function.

That being said, you're totally right with this oint:



> Also, if automation users are providing these queries (I assume they are) then they will need the defaults that we configure at a higher level than `zoekt.Searcher.List` (such as literal search by default instead of regex, etc)

Because we do want to use structural search soon and going to `zoekt.Searcher.List` would we cumbersome I assume.

**Comment by slimsag** [comment]
Well, ultimately I leave the decision here up to you of course. I trust you to do what is best here 😄If it was me, I would want to own less of the search implementation side and be able to effectively say "we are just running the same GraphQL API our frontend does" because that separates a whole class of issues for you.

Again though -- whatever you think is best here I am happy with 👍
