### ISSUE TITLE
gitserver should auto-recover from corrupt repository clones

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6676]
An admin ran into an issue where a repository was corrupt and search was failing because of it:

```
1 error occurred: * diff search failed: failed to search commit diffs REDACTED@: git command [git log --no-prefix --max-count=31 --unified=0 --extended-regexp --regexp-ignore-case --all-match --author= -z --no-abbrev-commit --format=oneline --no-color --source --no-patch --no-merges -GREDACTED --regexp-ignore-case --pickaxe-regex --extended-regexp --] failed (output: ""): exit status 128 (stderr: "error: packfile .git/objects/pack/pack-REDACTED.pack does not match ... (truncated)")
```

This is the state the repository was in:

```
$ docker exec -it gitserver-7 sh -c 'cd /data/repos/REDACTED && time git log -- -n 1 HEAD'
error: packfile .git/objects/pack/pack-REDACTED.pack does not match index
error: packfile .git/objects/pack/pack-REDACTED.pack does not match index
error: packfile .git/objects/pack/pack-REDACTED.pack does not match index
error: packfile .git/objects/pack/pack-REDACTED.pack does not match index
error: packfile .git/objects/pack/pack-REDACTED.pack does not match index
error: packfile .git/objects/pack/pack-REDACTED.pack does not match index
fatal: bad object HEAD
Command exited with non-zero status 128
real    0m 0.00s
user    0m 0.00s
sys    0m 0.00s
```

Deleting the repository from disk manually was needed to recover from this. Gitserver should automatically handle this case somehow.

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

cc @sourcegraph/core-services

**Comment by unknwon** [comment]
Hmm... I guess it's already too late to ask, but does the customer happen to try `git gc` on the repository before deletion?

**Comment by tsenart** [comment]
How often is this happening?

**Comment by slimsag** [comment]
> Hmm... I guess it's already too late to ask, but any chance the customer happened to try git gc on the repository before deletion?

No sorry

> How often is this happening?

Just once so far, will report back if I see it happening more frequently.

**Comment by keegancsmith** [comment]
One of our janitor jobs should run `git fsck` to check for issues. I'm not sure how intensive git fsck is, but if it is this may not be tenable. This does mean for a time a repo may break a feature like cross repo diff search (or even git resolve-rev?). I think this is likely better than parsing the stderr of all commands (seems complicated/bad perf), or just limiting it to git log even (issue may occur in other places). WDYT?

Note: in general we don't run git gc since it is computationally quite intensive for IO and CPU. We are a code mirror, so its actually cheaper to just reclone.

**Comment by slimsag** [comment]
The problem is, how long will features be broken until the next git fsck runs?

**Comment by keegancsmith** [comment]
> The problem is, how long will features be broken until the next git fsck runs?

A day? At least the problem would resolve itself. Not sure if the rarity of this sort of issue justifies the engineering effort and cat-and-mouse of detecting and correcting these sort of problems.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
We're going to do a spike to check if we could just rely on the exit code of each git command to assess whether there's a filesystem consistency error (or any other error that we'd deem indicative of the need to re-clone the repo from its origin).

**Comment by keegancsmith** [comment]
Investigated this today. Log:

<a id="org5eedc06"></a>

# exit code investigation

exit(128) is the most common call to exit. Examples:

-   bad options passed in to revision
-   `die_nicely` function. Only used by fast-import.
-   failing to add a file to the index
-   failing to get OID
-   &#x2026;

Essentially, it seems exit code 128 is used generally. It isn't reserved for corrupt repositories.

I think we will have to rely on parsing stderr output. However, we need to ensure whatever we do is very efficient, since it can very easily become a bottleneck.


<a id="org73e3503"></a>

# stderr format investigation

error function/macro is very consistently used in the git codebase. Most of them look like the sort of thing we would want to detect. It seems to output a line like:

    error: msg...

In the case of us dieing, the prefix used is fatal. This can happen due to user input rather than a corrupt repo. I think going down the route of detecting `^error:` on stderr will be good signal. However, it is hard to know if we will have too many false positives. As such I think we should emperically verify it by implementing error parsing but only logging it on Sourcegraph.com. Then investigate the errors found after it running on dot-com for a week.

**Comment by keegancsmith** [comment]
Logging the output for Sourcegraph.com is implemented by https://github.com/sourcegraph/sourcegraph/pull/7968

Will revisit this task in a week or two once we have collected data.

**Comment by keegancsmith** [comment]
Early days, but this has only fired once so far. A good sign this heuristic will work well:

```shellsession
> for pod in gitserver-{0,1,2,3,4,5}; do kubectl exec $pod -- tail /data/repos/git-stderr-error.log; done
2020/01/27 01:55:24 github.com/kubernetes/enhancements error: Could not read 3cff00247a334582e1530c6ff264637f013e67d2
```

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
So this heuristic has some error messages which do not point to repository corruption. So we will have to whitelist specific errors. Here are the counts of errors we have received on sourcegraph.com:

```shellsession
$ cat git-stderr-error.log | cut -b 21- | sort | uniq -c | sort -n
   1 github.com/mame82/p4wnp1_aloa error: Could not read 966daefa2fb84bd66b5cb7128c6378e4e74ded99
   1 github.com/rook/rook error: Could not read 5a83c7f0086992b2e8d3c1a16ad7362a2886659b
   3 github.com/kubernetes/enhancements error: Could not read 3cff00247a334582e1530c6ff264637f013e67d2
   4 github.com/aws-amplify/amplify-cli error: object 335927deb33d86b6c7082a84a43a716aed6a5071 is a blob, not a commit
   4 github.com/aws-amplify/amplify-cli error: short SHA1 1325 is ambiguous
   4 github.com/pingcap/tidb-operator error: object 156639577dd2ea91cdd53b25352648387d985743 is a blob, not a commit
   4 github.com/sourcegraph/sourcegraph error: short SHA1 d308 is ambiguous
   8 github.com/sourcegraph/sourcegraph error: short SHA1 d300 is ambiguous
  12 github.com/flutter/flutter error: object 45043b3ff0440f4d7937f8c68f8fb2881759edef is a tree, not a commit
  72 github.com/cortexproject/cortex error: Could not read d24d09b8bc5d1ea2c3aa24455f4578db6aa3afda
```

So the heuristic I propose is looking for "error: Could not read" and then cleaning up those repos.

**Comment by tsenart** [comment]
@keegancsmith: Sounds good to me.
