### ISSUE TITLE
Search configuration data

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#670]
A request to be able to see search results in files that do not exist in a Git repository, such as configuration files served by a system like etcd/Zookeeper. This would be provided by a Sourcegraph extension using the search result provider API. It would eventually run on the backend but TBD on whether that would be in scope for 3.1 (highly unlikely running it on the backend too would be fully ready, it might be feature-flagged off by default).

**Comment by sqs** [comment]
Update: The [Search GitHub issues](https://github.com/sourcegraph/sourcegraph/issues/962) project on the roadmap is building the extension APIs necessary for this. I am pushing  this back one month and we will reevaluate it then when we have the extension APIs necessary for this.

**Comment by keegancsmith** [comment]
We are thinking of creating a search provider which recursively monitors a directory on a filesystem. The provider will expose what it finds on the FS via HTTP. This seems like a simple approach for developers to add integration for zookeeper/etc since they will just need to code a sync daemon. Additionally from an operational perspective this is relatively easy to understand and manage. @andyfang would this seem like a decent way to extend sourcegraph search?

**Comment by andyfangdz** [comment]
@keegancsmith thanks for updating this issue with the approach! The approach of monitoring a FS makes a lot of sense, and we would really appreciate it if this is available.

**Comment by camdencheek** [comment]
Closing this since extensions have been removed from the product. 

Searching non-git data sources is something that we will likely consider at some point, but not through extensions and probably with more specific prioritization of more-used data sources (like GitHub issues).
