### ISSUE TITLE
a8n: Handle the deletion of external services and repos

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6727]
It's currently undefined what should happen when a site-admin deletes/updates an external service that then deletes repositories that are connected to existing `Campaign`s,`CampaignPlan`s, `CampaignJob`s, `Changeset`s, `ChangesetJobs`.

Here is the current "schema":

<img width="757" alt="a8n_schema" src="https://user-images.githubusercontent.com/1185253/69252815-e65b0e00-0bb3-11ea-8178-d4509e8ffbb1.png">

The **first step** is to define what should happen in the following cases:

1. What should happen to the changesets on the code hosts if a user deletes a `Campaign` on Sourcegraph?
2. What should happen to the Sourcegraph Automation Changesets when a site-admin deletes a repository (e.g. by changing the external service config)?
3. What should happen to a diff/changeset (`CampaignJob`) in a `CampaignPlan` when a site-admin deletes a repository?

Once that list exist, the **second step** is to handle the deletion of repositories/external services in these places.

**Comment by mrnugget** [comment]
@sqs @christinaforney I added the three main questions that get to the heart of the matter (Sourcegraph `Changesets`/`CampaignJobs` are connected to repos on code hosts).

I think once we have answers to these three, we can start fixing a lot of things that would currently break.

**Comment by sqs** [comment]
@christinaforney Please review my answers below and edit this comment to reflect your final decision here.

> What should happen to the changesets on the code hosts if a user deletes a Campaign on Sourcegraph?

The changesets remain on the code host.

> What should happen to the Sourcegraph Automation Changesets when a site-admin deletes a repository (e.g. by changing the external service config)?

- The changesets remain on the code host.
- The changesets are removed from the campaign.
  - As a future enhancement (not required immediately, we'll solicit customer feedback for priority), instead of removing the changesets from the campaign, they can be shown in a special "associated repository no longer exists" state in the campaign, so that the campaign author has confidence that the campaign is indeed affecting all of the repositories they originally intended to affect.

> What should happen to a diff/changeset (CampaignJob) in a CampaignPlan when a site-admin deletes a repository?

This can occur when a CampaignPlan is generated, then in the meantime a repository is deleted, then the CampaignPlan is provided as input to create a campaign.

In this case, there will be an error in the `Campaign.changesetCreationStatus` field for our attempt to create the changeset on a repository that no longer exists. For now, because we do not support changing a campaign's plan after creation, this error will persist and there is no way to make it go away even if you call `retryCampaign` (other than re-adding the repository).

If this is annoying, we can make it possible to dismiss errors in the UI, but we can prioritize this based on customer feedback.

Note that it is not an acceptable complete solution in this case to deem the CampaignPlan invalid if it refers to a nonexistent repository, because the race condition still would exist. The true complete solution is to support changing a campaign's plan after creation, which we intend to do in the future anyway.

**Comment by christinaforney** [comment]
Updated. LGTM!
