### ISSUE TITLE
Tracking Issue: Speed up Node builds in CI 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#6770]
See [RFC 79 - Refactor CI Pipeline for more information](https://docs.google.com/document/d/1_F2xiuNxkrdTHhgaR3jyaaWcs9OsUs9eMAF9fSCxie0/edit#)

One of the main goals of RFC 79 is to speed up our CI pipeline. NPM/Node build steps are the most time-consuming operations that we run (~>5 mins per build). What can we do to speed things up?

**Comment by eseliger** [comment]
It seems we can store the artifacts of the webapp enterprise build step for use in the 
- server docker image
- frontend docker image
if i'm not mistaken

Additionally, in the local environment build time for an equal codebase (which happens all the time for backend only changes) went down from 2.4min to 55s on the second build, when `node_modules/.cache` is retained between builds.

**Comment by felixfbecker** [comment]
I think the biggest problems are:
- Caches not being persisted between builds (only global caches like `yarn`), e.g. `tsbuildinfo`, Babel caches, Parcel caches, ...
- Sequential work that could be in parallel. E.g. management console, web app and integration assets are build sequentially to build the Docker image in various shell scripts called before and during the `docker build`.
- Duplicate work that could be unified. E.g. management console has its own package.json for no reason, therefor we run `yarn` twice sequentially even though the dependencies largely intersect.
- Lastly, build time. Fast webpack builds is still not a solved problem in 2019.

**Comment by eseliger** [comment]
The two slowest jobs in CI on branches are
1. build server image (9m55)
2. run web team cosmetic toolchain (5m43)
3. non-enterprise web build (3m36)

If we were able to shave more than 4 minutes off the server image build, splitting up the 2. is really easy, since the steps don't depend on each other. 
In the 3m range there are so many jobs, it would require a lot effort getting over the level of the 3rd slowest.

From what I have seen, we only have the server image to run e2e-tests (correct?). But everything we do to build that image, we basically do once again in other tasks. Like building the enterprise app, running yarn to get dependencies for the build, ...
If we were able to use the already split up tasks and store artifacts to glue the server image together much faster, maybe that will help with the problem. Additionally, since we have to wait for the build jobs, we maybe can build the image _within_ the e2e step if it get's fast enough by that - then we would save the docker registry push as well as removing the image at the end again, even more time savings

**Comment by eseliger** [comment]
![image](https://user-images.githubusercontent.com/19534377/69454763-39c18d80-0d67-11ea-8aca-022a99c8ed7b.png)

pasting in a sample from another repository, where strictly no redundancy was achieved with just having steps that have a hard dependency on each other wait instead of doing duplicative work (like `yarn`, building a client to be baked into a docker image, ..)

**Comment by keegancsmith** [comment]
> * Caches not being persisted between builds (only global caches like `yarn`), e.g. `tsbuildinfo`, Babel caches, Parcel caches, ...

I monitored htop on our CI while building the server image. Pretty much the only time we didn't max out all cores was `yarn`, and it was for a significant amount of time. So I believe that is where all our low hanging fruit is. Does anyone have any experience instrumenting yarn/node/whatever to try find out why? Also what hacks can we do to speed it up?

Idea: copying `node_modules` from a previous run may help. What do you think? Previous experience with other languages tells me this may sacrifice correctness? If it does sacrifice correctness, we will just not do it in the case of building an image we will docker push. But for example these sort of hacks could greatly improve the performance of any step that needs to run yarn (eg tests, docker builds for e2e).

> * Sequential work that could be in parallel. E.g. management console, web app and integration assets are build sequentially to build the Docker image in various shell scripts called before and during the `docker build`.

This is now done in parallel thanks to @ggilmore.

> * Duplicate work that could be unified. E.g. management console has its own package.json for no reason, therefor we run `yarn` twice sequentially even though the dependencies largely intersect.

I would like to make management console less of a special snowflake with regards to asset embedding and building. @felixfbecker I don't have the experience around node to make what you suggest happen, could you just do a hacky commit which does it and I'll follow up to ensure it builds / integrates correctly.

> * Lastly, build time. Fast webpack builds is still not a solved problem in 2019.

Without doing some drastic change (like switch to Bazel) I don't see us solving that. However, I am guessing someone with experience in JS build tools taking a quick look may find some low hanging fruit?

@sourcegraph/web I'd really appreciate someone spending like a day trying to find wins here since this is by far the slowest part of our CI pipeline. It is only going to get worse as our org grows and the complexity/amount of TS we do grows. A fun fact about build/CI systems is the pain grows `O(n^2)` with org size since every additional developer introduces more code * more builds.

**Comment by eseliger** [comment]
Carrying over the node_modules/.cache folder should help getting things compiled faster 
I didn’t see a good obvious way to do caching in buildkite in their docs though

**Comment by lguychard** [comment]
@felixfbecker had opened a PR to combine management console & root package.json (https://github.com/sourcegraph/sourcegraph/pull/5348). @felixfbecker do you have context on what additional work is needed to merge this?

**Comment by felixfbecker** [comment]
Apparently I had met a bug that would need to be re-investigated: https://github.com/sourcegraph/sourcegraph/pull/5348#issuecomment-524400863

**Comment by felixfbecker** [comment]
> I monitored htop on our CI while building the server image. Pretty much the only time we didn't max out all cores was yarn, and it was for a significant amount of time. So I believe that is where all our low hanging fruit is. 

@keegancsmith I wouldn't expect it to ever max out CPU because I'd expect yarn to be IO-bound (disk and network). yarn has multiple phases: resolution, fetching packages into the global cache, and copying them from the cache into node_modules. I assume the cache is shared between builds as its on the agents disk, so the fetching should be a noop in the general case, leaving copying as the only  expensive step.
Are there things we can do to speed up IO? Are we using SSDs for Buildkite?

Persisting `node_modules` works but only until native addons and `postinstall` scripts get involved. Then it may break after every update of Node, every update of a native addon (e.g. node-sass), every update of a package that does fancy postinstall (e.g. puppeteer) and get only resolved by nuking the cache.

**Comment by felixfbecker** [comment]
>> Sequential work that could be in parallel. E.g. management console, web app and integration assets are build sequentially to build the Docker image in various shell scripts called before and during the docker build.
> This is now done in parallel thanks to @ggilmore.

I see integration assets and the webapp being built in parallel now, but I don't see where the management console is built in parallel (or built at all)?
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/pre-build.sh

**Comment by ggilmore** [comment]
@felixfbecker 

> > > Sequential work that could be in parallel. E.g. management console, web app and integration assets are build sequentially to build the Docker image in various shell scripts called before and during the docker build.
> > 
> > 
> > This is now done in parallel thanks to @ggilmore.
> 
> I see integration assets and the webapp being built in parallel now, but I don't see where the management console is built in parallel (or built at all)?
> [sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/pre-build.sh](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/pre-build.sh)

You're not looking at the right build script: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/server/pre-build.sh

**Comment by ggilmore** [comment]
@felixfbecker 

> > I monitored htop on our CI while building the server image. Pretty much the only time we didn't max out all cores was yarn, and it was for a significant amount of time. So I believe that is where all our low hanging fruit is.
> 
> @keegancsmith I wouldn't expect it to ever max out CPU because I'd expect yarn to be IO-bound (disk and network). yarn has multiple phases: resolution, fetching packages into the global cache, and copying them from the cache into node_modules. I assume the cache is shared between builds as its on the agents disk, so the fetching should be a noop in the general case, leaving copying as the only expensive step.

To put a finer point on this, when we mean `yarn` it's shorthand for talking about both the `yarn` package installation process and the `webpack` builds invoked via `yarn run ...` . I assume @keegancsmith specifically means that the actual `webpack` build is pinning the CPU.

The cache is shared, but note that agents are regularly created/destroyed when we autoscale depending on the number of pending builds: https://github.com/sourcegraph/infrastructure/blob/3641958591af7297539652319c99ac1a5a1eed2d/docker-images/buildkite-autoscaler/buildkite-autoscaler.go#L53 Still, anecdotally, the time to fetch packages is still much quicker than the `webpack` build. 

> Are there things we can do to speed up IO? Are we using SSDs for Buildkite?

Yes, we use SSD's: 

- ![Screen Shot 2019-12-06 at 1 47 21 PM](https://user-images.githubusercontent.com/9022011/70358827-17337800-182f-11ea-8fe1-ab584756d819.png)
- https://console.cloud.google.com/kubernetes/nodepool/us-central1-a/ci/buildkite?project=sourcegraph-dev&organizationId=1006954638239
- https://github.com/sourcegraph/infrastructure/blob/master/kubernetes/ci/buildkite/buildkite-agent/buildkite-agent.Deployment.yaml - we don't have any network disks ("slow" I/O) are mounted in the agent 

https://github.com/sourcegraph/infrastructure/blob/master/kubernetes/ci/buildkite/buildkite-agent/buildkite-agent.Deployment.yaml

**Comment by felixfbecker** [comment]
> To put a finer point on this, when we mean yarn it's shorthand for talking about both the yarn package installation process and the webpack builds invoked via yarn run ... . I assume @keegancsmith specifically means that the actual webpack build is pinning the CPU.

Okay, I definitely misunderstood this. Going forward, let's please not refer to the build scripts as "yarn" - yarn is not involved here except for launching a shell script that then runs webpack/parcel/etc. "yarn" should mean "installing dependencies".

> The cache is shared, but note that agents are regularly created/destroyed when we autoscale depending on the number of pending builds: sourcegraph/infrastructure:docker-images/buildkite-autoscaler/buildkite-autoscaler.go@3641958#L53

Ah, I didn't think of that. That makes me think that this caching is not sufficient and we should have some out-of-band mechanism (that also shares between agents). That could not only cache dependencies, but cache Babel and TypeScript caches too.

> Still, anecdotally, the time to fetch packages is still much quicker than the webpack build.

That's expected and I don't think that will change. We can still improve both though.

**Comment by ggilmore** [comment]
> > To put a finer point on this, when we mean yarn it's shorthand for talking about both the yarn package installation process and the webpack builds invoked via yarn run ... . I assume @keegancsmith specifically means that the actual webpack build is pinning the CPU.
> 
> Okay, I definitely misunderstood this. Going forward, let's please not refer to the build scripts as "yarn" - yarn is not involved here except for launching a shell script that then runs webpack/parcel/etc. "yarn" should mean "installing dependencies".
> 
> > The cache is shared, but note that agents are regularly created/destroyed when we autoscale depending on the number of pending builds: sourcegraph/infrastructure:docker-images/buildkite-autoscaler/buildkite-autoscaler.go@3641958#L53
> 
> Ah, I didn't think of that. That makes me think that this caching is not sufficient and we should have some out-of-band mechanism (that also shares between agents). That could not only cache dependencies, but cache Babel and TypeScript caches too.
> 
> > Still, anecdotally, the time to fetch packages is still much quicker than the webpack build.
> 
> That's expected and I don't think that will change. We can still improve both though.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
Is this still an issue?
