### ISSUE TITLE
Syntax highlight for Bazel skylark files

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#6827]
#### Feature request description

It would be great to have syntax highlight for Bazel skylark files. Is it something only you can can do? Or is it possible to achieve that by mounting few files in syntext-server pod?

#### Additional context

https://sourcegraph.com/github.com/bazelbuild/bazel/-/blob/distdir.bzl

**Comment by slimsag** [comment]
hi @aisbaa -- thanks for filing this! I'll see what we can do about getting this in soon.

Unfortunately [adding a syntax](https://github.com/sourcegraph/syntect_server#adding-languages) is a fairly involved process just due to the number of submodules/dependencies that need to be updated in order to do it.

Do you have a preferred Sublime Text 3 or TextMate grammar that you use in editors with Bazel? (if not, I'll just find a popular one and we'll try that)

**Comment by aisbaa** [comment]
> Do you have a preferred Sublime Text 3 or TextMate grammar that you use in editors with Bazel? (if not, I'll just find a popular one and we'll try that)

I don't, but I'll ask devs to comment here if they have preference on this.

**Comment by rmaz** [comment]
The Bazel VS Code plugin includes a textmate grammar, we could use that one: https://github.com/bazelbuild/vscode-bazel/tree/master/syntaxes

**Comment by slimsag** [comment]
@aisbaa @rmaz this has been fixed and will be shipped in 3.10.1 later today. Example:

![image](https://user-images.githubusercontent.com/3173176/69581304-87224280-0f93-11ea-9121-ed8573c234e9.png)

**Comment by rmaz** [comment]
👍
