### ISSUE TITLE
Highlighting cuts off before the last line shown in the preview

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#6900]
For multiline matches, the last line in the preview context is not highlighted when it should be. If the expand button is available, clicking the expand button colors the last line if it should have been highlighted. This behavior is misleading because it looks like the highlighting stops and isn't part of the match, but really it is part of the match, but just not highlighted.

Affects regexp and structural search #6899.

[Example query](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+func.*%5Cn.*%5Cn&patternType=regexp)

Screenie:
<img width="626" alt="Screen Shot 2019-11-27 at 8 40 04 PM" src="https://user-images.githubusercontent.com/888624/69775523-37d83f80-1156-11ea-8ee0-60bbc2ada834.png">

Gif:

![ohnoo](https://user-images.githubusercontent.com/888624/69775565-54747780-1156-11ea-8e98-25161aca4b43.gif)

**Comment by rvantonder** [comment]
Bumping the visibility on this: @unknwon also ran into this issue and it can happen with single line matches too [thread](https://sourcegraph.slack.com/archives/C0C324C91/p1580288444032600).

**Comment by attfarhan** [comment]
Thanks, added this to my 3.13 plan

**Comment by attfarhan** [comment]
After some research on this: @unknwon's case is due to [SubsetMatches](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e6183fd1ab543f6ed72f2e6e1666c168e0034999/-/blob/shared/src/components/FileMatch.tsx#L81:15) being set to 10 by default. In his example, there were 10 matches already, and the un-highlighted match is just a context line. If he clicks 'show 8 more matches', then it shows the full set of matches. This is a separate issue, where perhaps the solution should be that we check the line of context to see if there is a match, and highlight it if so.

**Comment by attfarhan** [comment]
Correction: it's the same underlying issue. The line of context never gets highlighted in both cases.
