### ISSUE TITLE
Rust code intelligence

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7]
Support Rust on Sourcegraph.

**Comment by chrismwendt** [comment]
Experimental Rust support has been shipped in Sourcegraph 2.8! Check out the blog post https://about.sourcegraph.com/blog/code-intelligence-for-more-languages-and-lsp-language-server-protocol-support

![demonstration of hovers from the Rust language server inside databricks/click](https://cl.ly/383f3V0P1r1u/Screen%20Recording%202018-05-07%20at%2005.58%20PM.gif)

Thanks go to the [rust-lang-nursery/rls](https://github.com/rust-lang-nursery/rls) project for providing the language server.

**Comment by sqs** [comment]
Better Rust support is planned for December 2018. https://docs.sourcegraph.com/dev/roadmap#december-2018

**Comment by chrismwendt** [comment]
We've since [removed Rust support](https://about.sourcegraph.com/blog/java-php-experimental_language_servers-temporarily-unavailable) and don't have immediate plans to bring it back. There are two potential forward:

- Improve the initialization time of RLS (needs to compile the entire project before providing code intelligence, can take minutes)
- Wait for [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) to be able to replace RLS (years out)

Neither of these are particularly appealing since Sourcegraph is sensitive to initialization time (because analysis is performed on the fly) and we'd like to improve code intelligence on a time scale on the order of months.

**Comment by spacejam** [comment]
@chrismwendt rust-analyzer supports definition and reference look-up today, are there other bits of functionality that are important for sourcegraph that are currently missing? I'm having trouble pinpointing the sourcegraph code that formerly interacted with RLS in the public repos.

@matklad can shed light on the relative stability for specific APIs that you would like to handle, but I believe that "years out" may not be accurate for stable implementations of sourcegraph's requirements.

This is a cool tool and it would be a shame for the growing rust community to lose support :)

**Comment by matklad** [comment]
"couple of years" might be a good estimate for 100% coverage of the Rust language, but some part of those 100% is already working today. For example, goto defenition for imports pretty much just works. So, if partial support of the Rust language is interesting, rust-analzyer can provide that. 

>can shed light on the relative stability for specific APIs 

The "as a library API" is totally unstable, but we can ship a statically linked binary which talks LSP, and that is of course stable.

**Comment by LandKingdom** [comment]
I personally wouldn't mind waiting some time before being able to use the tool.

**Comment by chrismwendt** [comment]
@spacejam The 3 main bits of functionality are hover tooltips, definitions, and references. It sounds like rust-analyzer would work pretty well since it already has support for 2 of those 3.

Now that code intelligence on Sourcegraph is provided by [Sourcegraph extensions](https://docs.sourcegraph.com/extensions), anyone can build a Rust extension with the same functionality as other language extensions like [Go](https://sourcegraph.com/extensions/sourcegraph/lang-go), [TypeScript](https://sourcegraph.com/extensions/sourcegraph/lang-typescript), and [Python](https://sourcegraph.com/extensions/sourcegraph/python).

Since Sourcegraph extensions are JavaScript bundles that run in the browser, they are constrained to communicate with a remote language server over HTTP or WebSockets. To satisfy this constraint, we've added WebSocket and zip archive fetching (to get the repository contents on disk) to the Go, TypeScript, and Python language servers. Rust would probably need similar functionality, but what's nice is that the extensions are free to choose how to do that - Sourcegraph does not mandate any particular transport or protocol be used.

**Comment by chrismwendt** [comment]
Rust code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/rust-lang/rust@57d7cfc3cf50f0c427ad3043ff09eaef20671320/-/blob/src/librustc_typeck/check/mod.rs#L222:36) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/52602118-439c8480-2e16-11e9-842d-bdb83285c461.png)

This implementation uses ctags and search, so it's not 100% accurate. However, it's a good starting point and can be combined with rust-analyzer or RLS in the future.
