### ISSUE TITLE
Expose combined diffStat on Campaign(Plan)

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#7092]
Exposing a combined `diffStat` on the `Campaign` and `CampaignPlan` resources would help not having to fetch all changesets just to show the diff indicator for the campaign. This is really redundant as we move to using the `FilteredConnection` component for diffs on campaigns, that is able to lazy load more content. Hence the diff would not be the correct number until all entries have been loaded. This is a step to mitigate performance issues when we have larger diffs

**Comment by eseliger** [comment]
Note:
save diffstat on the patch, so it's easily retrievable and we can also return the total diffstat on the campaign _including_ those that are already merged, having a total diffstat of what the campaign ever touched.

**Comment by mrnugget** [comment]
I've been thinking about this issue a bit, turns out we need to take care of multiple things:

* Some campaigns now have patches (#8981) from multiple patch sets attached to them.
* For changesets we can't rely on the diffstat of patches, since (a) manual campaigns don't have patches and (b) changesets might change upstream, so we need to recompute every time.

So, there's two problems worth fixing contained in this issue:

1. Batch-loading all the necessary entities in the backend to compute a combined diffstat
2. Caching the diffstat on the involved entities to avoid computing the diffstat again and again

1. is far easier than 2. due to the aforementioned reasons (changesets might change upstream).

But 1. alone would not be a huge performance improvements, since we need to load _all_ changesets and all _patches_ involved in a campaign, parse their diffs or ask `gitserver` for their diff stat.

**Comment by eseliger** [comment]
Hmm yes my idea was to have it as 3 columns of the `changesets` table so a query like

```sql
SELECT SUM(added) as added, SUM(changed) as changed, SUM(deleted) as deleted
FROM changesets WHERE id = :id
```

I'd assume that's pretty fast even for 10k changesets. But it does not account for upstream changes of course..

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
@eseliger how do you envision the GraphQL API additions? Should this be a separate `diffStat` field on `Campaign` or two `diffStat` fields on `RepositoryComparisonConnection` and `PatchConnection`?

**Comment by eseliger** [comment]
Currently we always only want to display all at once so the first seems like the way to go

**Comment by mrnugget** [comment]
Just for record keeping, I'm quoting myself in #10285 here:

> [...] this here includes no caching. For now I want to hold off on adding caching until I have a clear idea of how to invalidate said caches. I don't think it's a high priority right now. Will also document this in #7092.
