### ISSUE TITLE
Need result from all branches

### ISSUE THREAD

**Issue by devops81** [sourcegraph/sourcegraph#7122]
#### Question description
Repo:- https://github.com/devops81/DevOps-Demo
(You can fork it for use)
**IMAGE 1 SHOWING QUERY BEING USED**
![image](https://user-images.githubusercontent.com/23429963/70406113-8bd90300-1a37-11ea-91bb-c7bb91300158.png)
**IMAGE 2 SHOWING ONLY FROM MASTER BRANCH**
![image](https://user-images.githubusercontent.com/23429963/70406164-bc20a180-1a37-11ea-8b0b-56a63c87a7b0.png)

**Query being used :-** 
repo:devops81/DevOps-Demo$@*refs/heads/ type:path java

In result we want all the branches of the repository which contains *.java files but SG is currently giving result from master branch only
#### Additional context

---

https://app.hubspot.com/contacts/2762526/deal/1261049054 (https://app.hubspot.com/contacts/2762526/company/2428850551)

**Comment by sqs** [comment]
Partially fixed by #7459. Support for searching all branches (without needing to list each one in the query) is coming soon.

**Comment by rvantonder** [comment]
Related to #10571

**Comment by rvantonder** [comment]
This is working as requested: 
[`https://sourcegraph.com/search?q=repo:devops81/DevOps-Demo%24%40*refs/heads/*+type:path+java&patternType=literal`](https://sourcegraph.com/search?q=repo:devops81/DevOps-Demo%24%40*refs/heads/+type:path+java&patternType=literal). 

We've also since updated the documentation to more precisely describe the syntax: https://docs.sourcegraph.com/code_search/reference/queries#repository-revisions
