### ISSUE TITLE
Add support for directory-level decorations

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#721]
![image 5](https://user-images.githubusercontent.com/1387653/46499038-e3486700-c7d3-11e8-8ecd-8c8284d7b809.png)

This would be useful for Codecov, or any other extension that has directory-level rollups.

**Comment by tistru** [comment]
I'm working with a customer who is definitely interested in this and are hoping to have an "ls -l" type of directory view ready by end of year. I see that this issue is pretty dated and currently does not have anyone assigned. Is there someone actively working? Is there any work completed on this what I can use to provide some insight into how a customer can adopt this within our extension platform?

**Comment by felixfbecker** [comment]
Here's @AlicjaSuska's design: https://www.figma.com/file/zenC7UHayCK84KNFavAPA0/%F0%9F%8F%80Alicja-playground?node-id=380%3A5234

**Comment by felixfbecker** [comment]
Here's VS Code's extension APIs for decorations on tree view items (conceptually similar): https://github.com/microsoft/vscode/issues/54938#issuecomment-698957318
We probably want something similar, but different/targeted towards our use case and extension API conventions.

**Comment by AlicjaSuska** [comment]
I've moved designs to the separate [Figma project](https://www.figma.com/file/Bb0SA1zYNVQSXakzkMVhpH/Codecov-line-decorations-721?node-id=246%3A11) @tjkandala @felixfbecker

**Comment by tjkandala** [comment]
The web app will support the File Decoration API in release 3.23 

(Codecov extension)

![Screenshot from 2020-11-27 18-48-36](https://user-images.githubusercontent.com/37420160/100692952-e874b280-3359-11eb-9ee0-cfe3a93688f7.png)
