### ISSUE TITLE
Precedence between `patternType` in queries and RegexpToggle is not clear

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#7269]
With the introduction of structural search, and `structural` being a new, valid `patternType` value, it became apparent that using the regexp toggle can be unintuitive. @rvantonder [thought that it was a bug that the `pattenrType` param in the search query overrode the regexp toggle while testing patternType:structural](https://github.com/sourcegraph/sourcegraph/pull/7267#issuecomment-566787393). It does feel   intuitive that pressing a UI element would determine behavior in many cases. 

Should we have the regexp toggle take precedence over the patternType param?

**Comment by attfarhan** [comment]
We had several reasons for doing so, outlined in [RFC 31](https://docs.google.com/document/d/11avb0ixXHGmHrpUM1-1ijSxogWiYMXXH1SCM8ozvX-s/edit). 

Other reasons _not_ to allow the regexp toggle to override:
- It wouldn't be possible to get to `patternType:structural` through the UI element, which seems bad. (Potentially also an a11y issue?)

**Comment by rvantonder** [comment]
High-level, if we have knowledge that the user input contains two signals for selecting something, we can either (a) define a precedence (which we have done currently) (b) raise an error or (c) control where and how those signals are set.

Long term we should think of a way to set what kind of search should run without giving the user multiple avenues to send a signal. For example, through separate inputs. See RFC 75.

Low-level, for this case, if there are two signals there is no intuitive idea what happens. To communicate the precedence of the input query being higher, in this case I would expect the toggle to be disabled so that it isn't possible to send multiple signals.

**Comment by rvantonder** [comment]
We addressed this by adding a toggle.
