### ISSUE TITLE
What is the proper alternative to `auth.public`? 

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#7369]
Removing `auth.public: true` in the site config caused a couple bugs  (https://github.com/sourcegraph/sourcegraph/issues/7359, https://github.com/sourcegraph/sourcegraph/issues/7354) for unauthed users on sourcegraph.com since `authRequired` in the webapp relies on it to determine whether or not to display certain components and allow requests: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/auth.ts#L71:31. 

Adding the option back fixed the bugs listed. I believe it was removed in the [management console removal PR](https://github.com/sourcegraph/sourcegraph/pull/7197), but am not 100% sure since there's no git log for site config changes. 

The docs state that [`auth.public`](https://docs.sourcegraph.com/admin/config/critical_config) is no longer an option as of 3.8, but it seems we still [rely on it in several places in the codebase](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/sourcegraph%24+auth.public&patternType=literal). 

For now, I've added `auth.public` back to sourcegraph.com to fix the bugs. If it is deprecated, what's the proper alternative to it?

**Comment by dadlerj** [comment]
@attfarhan I'm confused by this — my PR that "removed" it didn't actually remove it, it just deprecated the option and made it so that it was only ever true on sourcegraph.com: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/46595d6b756fcfeccd90b1dffe26fe758f6de62f#diff-54a8e578fdaacf491cc917ee23186e58R32.

So given the value was still true on sourcegraph.com, how did sourcegraph.com break because of it?

>it seems we still rely on it in several places in the codebase.

FWIW, those are all documentation except for the single usage that caused the issue here.

**Comment by attfarhan** [comment]
@dadler OK this is helpful.

These lines should've been updated to check `window.context.sourcegraphDotComMode` when the auth.public was deprecated: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b46cee36cdd95676ffa8f7b8a046b84208d4e528/-/blob/web/src/auth.ts#L60-71

It still relied on the `auth.public` being present in site config, and it was indeed removed from site config on sourcegraph.com recently. If you go to sourcegraph.com/site-admin/config and see it set to `true` there, it's because I just added it back a few minutes ago. 

I'll make the fix, thanks for the context

**Comment by dadlerj** [comment]
Thanks! 🚀
