### ISSUE TITLE
negated repohasfile is ineffective

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7380]
The query [`-repohasfile:Dockerfile docker`](https://sourcegraph.com/search?q=-repohasfile:Dockerfile+docker&patternType=regexp) is showing results from repositories that do contain a Dockerfile:

![image](https://user-images.githubusercontent.com/1976/71432271-346ca100-268d-11ea-823b-80564ed3af45.png)

Expected is that repositories with a Dockerfile (eg `facebook/fbctf`) are omitted.

**Comment by tsenart** [comment]
@sqs: I see you added this to the 3.12 milestone. Do you deem this higher priority than the [other work we planned for it](https://github.com/sourcegraph/sourcegraph/issues/7190)? If not, I'll put this in 3.13.

**Comment by sqs** [comment]
@tsenart Yes, I consider it more important because it is a bug in advertised and documented functionality. It would be acceptable to restrict the negated repohasfile operator (ie in the same way we don't support negated terms) and then push the actual fix to 3.13.

**Comment by tsenart** [comment]
@sqs: Alright. @keegancsmith: Do you have the bandwidth to pick this up? If so, please update the tracking issue.

**Comment by keegancsmith** [comment]
Will fix.

**Comment by keegancsmith** [comment]
This has turned out to be a pretty bad regression since 3.10. Essentially repohasfile has been completely broken since then. A unit test wouldn't of picked this up, we probably needed an e2e test. This regression was due to the introduction of horizontal search.

@slimsag are we still doing patch releases of 3.10 and 3.11? If so I'd recommend cherry-picking https://github.com/sourcegraph/sourcegraph/pull/7504 into both releases.

**Comment by keegancsmith** [comment]
@slimsag I saw you mentioning a 3.11 patch release on another PR. So went ahead and cherry-picked the fix for this issue onto the 3.11 release branch. c30e9d2c0dd01440821bcf4da8fc7df744e6c63f
