### ISSUE TITLE
Firefox add-on is temporarily unavailable

### ISSUE THREAD

**Issue by djhworld** [sourcegraph/sourcegraph#744]
Following this link: https://addons.mozilla.org/en-US/firefox/addon/sourcegraph/ from documentation here https://docs.sourcegraph.com/integration/browser_extension

The response you get it 

> This add-on has been removed by its author.

Is this expected?

**Comment by sqs** [comment]
Update on this: We are still working with the Firefox add-ons reviewers to get it approved again. They flagged it because it has the capability to connect to your Sourcegraph instance and run code from [Sourcegraph extensions](https://docs.sourcegraph.com/extensions) you've enabled. In the meantime, you can [build Sourcegraph for Firefox from source](https://github.com/sourcegraph/sourcegraph/tree/master/packages/browser-extensions). Sorry for the interruption!

**Comment by dpshelio** [comment]
wrong ling above, here's where you can [build Sourcegraph for Firefefox from source](https://github.com/sourcegraph/sourcegraph/tree/master/packages/sourcegraph-extension-api).

**Comment by sqs** [comment]
Sorry, we just moved around the directories. The correct link for building the browser extension is https://github.com/sourcegraph/sourcegraph/tree/master/client/browser. (I also updated the link in the above post.)

**Comment by sqs** [comment]
The Firefox extension is back! Get it at https://docs.sourcegraph.com/integration/browser_extension. We are now self-publishing it, so we don't anticipate any other interruptions, and it will be more up to date with our Chrome extension.

**Comment by johanbrandhorst** [comment]
> The Firefox extension is back! Get it at https://docs.sourcegraph.com/integration/browser_extension. We are now self-publishing it, so we don't anticipate any other interruptions, and it will be more up to date with our Chrome extension.

FYI, your README still points at this issue, I assume you want to update it :).

**Comment by kumar303** [comment]
The README here also still says that the Firefox extension has been disabled: https://github.com/sourcegraph/sourcegraph/tree/master/client/browser

**Comment by sqs** [comment]
Ack, sorry for missing this earlier. The README is fixed in a PR I just sent up at https://github.com/sourcegraph/sourcegraph/pull/2831.
