### ISSUE TITLE
Search git history for a specific dependency

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7489]
From [this Twitter thread](https://twitter.com/DavidWells/status/1214267128519393284):

> Is it possible to search git history for a specific dependency that was used?
>
> Trying to find some code I wrote that I know uses a specific module but can't remember when or what branch it happened in.

My current understanding is the user wants to issue a search query across all named branches of a git repository. The dependency could be detected by a search query like "file:package.json <name-of-dependency" and then it would just be a matter of running that search query over every named revision in the repository.

**Comment by keegancsmith** [comment]
This sounds very related to what @sqs is hacking on https://github.com/sourcegraph/sourcegraph/pull/7459

**Comment by dadlerj** [comment]
I also responded at https://twitter.com/DanielNealAdler/status/1214269178062000129

While I said "yes", the current functionality doesn't support semantic search (i.e., searching for a dependency, specifically, rather than text matches). 

It is possible to do a diff search over all branches already, however (using `repo:example-repo@*refs/heads`).

**Comment by beyang** [comment]
Closing as dupe of #7459
