### ISSUE TITLE
Renovate PRs are not getting automatically merged

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#7576]
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/1849 was opened and approved 3 hours ago, but is still not merged. You can look at some recent closed PRs to see there is now a high latency here. This might be related to product changes on Renovate's end.

**Comment by felixfbecker** [comment]
Related: https://github.com/renovatebot/app-support/issues/39
cc @rarkins

**Comment by rarkins** [comment]
If you log into the dashboard, you can see the recently run logs. Automerging happens if (a) Renovate runs, and (b) When it runs, the branch is green and up-to-date. The logs can be used to determine why it didn't automerge.

You can also trigger runs on-demand for any repo if you have `masterIssue` enabled and look into the Advanced section:
![image](https://user-images.githubusercontent.com/6311784/78868895-f7fa6080-7a43-11ea-9475-7fb5c9864227.png)

**Comment by slimsag** [comment]
We are replacing Renovate for the use case of Docker image updates specifically, see https://github.com/sourcegraph/sourcegraph/issues/10011#issuecomment-639953001

Closing.
