### ISSUE TITLE
Docs for installing Firefox extension could be much better

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7598]
I observed a user installing the Firefox extension.

- Landed on https://docs.sourcegraph.com/integration/browser_extension
- Clicked **Install Sourcegraph for Firefox**
- Immediately presented with "Requires access to all sites", accepted it
- Went to Go files on GitHub and got nothing.
  - Went to public Go files, clicked on things, hovered on things, got absolutely nothing.
  - Got GitHub find-references/j2d and wasn't sure if it was GitHub or Sourcegraph.
  - Questioned if he actually installed it, went to addons page in Firefox and saw error:

![image](https://user-images.githubusercontent.com/3173176/72028336-56465600-323f-11ea-9ec3-326546f421e5.png)

  - "Let's just assume I'm trusting enough to assume this _isn't a virus...._" and eerily clicked trust anyway enable slider.

Even if we cannot fix these, we could easily make this process MUCH more obvious by linking users who click **Install Sourcegraph for Firefox** to a page that explains what is going to happen next and why they should bypass all of the extremely dangerous-looking warnings Firefox present to them

**Comment by taras-yemets** [comment]
Just checked the current state of the Sourcegraph extension for Firefox and it seems this issue is no longer reproduced:
- we don't have that 'security or stability issues' badge anymore
![Screenshot from 2022-02-17 15-59-27](https://user-images.githubusercontent.com/25318659/154496936-c9f80c63-2fb9-4732-98e1-adc9ae2f3b45.png)
- code intel on files works as expected![Screenshot from 2022-02-17 16-15-18](https://user-images.githubusercontent.com/25318659/154500033-7211adf0-050b-425a-afdb-ef9f6593a94b.png)

What do you think, @slimsag? Should we keep this issue?

At the same time screenshots and descriptions on Chrome and Firefox web stores seem a bit outdated. And it is a good idea to audit and update them (will start a discussion around it).

**Comment by slimsag** [comment]
Awesome, looks like this is fixed! Thanks for following up on this!
