### ISSUE TITLE
debt: we have some unused zoekt timeout heuristics

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7661]
We have heuristics around the MaxWallTime to give Zoekt for searching [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@66a8e70/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L70-72) and those heuristics only activate when the conditional `query.FileMatchLimit > defaultMaxSearchResults` is true.

At the same time, `query.FileMatchLimit > defaultMaxSearchResults` cannot be true from a search codepath (I think) because you would need to specify a `count:` which in turn would set `UseFullDeadline` to `true` and thus [override the heuristic](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@66a8e70/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L118)

**Comment by Akarshit** [comment]
I am trying to look into this issue but I don't fully understand what the solution is? Is to just remove these [these](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@66a8e70/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L70-72) lines or is it something more sophisticated?
Any help would be much appreciated.

**Comment by stefanhengl** [comment]
Closing this because the code changed a lot since then. There is only one call site for zoektSearch and [useFullDeadline is always set to "false"](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=sh%2Fpython-dep&file=cmd%2Fsearcher%2Finternal%2Fsearch%2Fsearch_structural.go&editor=JetBrains&version=v1.2.2&start_row=302&start_col=16&end_row=302&end_col=16). @camdencheek can we remove "useFullDeadline" from the arguments of zoektSearch?

**Comment by camdencheek** [comment]
@stefanhengl Yeah, I think we can. We have a bunch of fancy deadline logic from before we had streaming everywhere that I've been slowly removing, but I missed that `useFullDeadline` is not used. Thanks!
