### ISSUE TITLE
Sourcegraph.com code intel issues on latest commit

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7731]
- **Sourcegraph version:** "Sourcegraph.com"

#### Steps to reproduce:

Running through a demo path, I've seen a few issues related to code intel on sourcegraph.com in the last 5 minutes.

I started by searching in our repo (`repo:^github\.com/sourcegraph/sourcegraph$`) and clicking on a result. This result automatically added the latest commit SHA to the URL and search bar (in this case `@df1ee9a`) just a few seconds/minutes after the commit was merged. From there, I ran into.

1. Code intel failed for me on Go files for a while. After refreshing the page a few times, it worked, though, so I can't repro. The console error message was the one about not having access to the zip archive.

2. The Codecov extension fails for me. This makes sense (I assume codecov hasn't completed running yet?) but it's a bit annoying to have to jump backwards in time to see annotations.

3. Symbol search fails (got a screenshot of this one). If I remove the `@df1ee9a` from the search, no error.
![image](https://user-images.githubusercontent.com/5589410/72372680-9da76900-36bb-11ea-8105-0a3fb678577f.png)

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40df1ee9a+todo+type:symbol&patternType=literal

Seems like all of these are related to the UI wanting to show the freshest possible files, but various external analyses haven't caught up yet (code intel, codecov)?

**Comment by dadlerj** [comment]
Perhaps due to https://github.com/sourcegraph/sourcegraph/issues/7735

**Comment by chrismwendt** [comment]
1 and 3 are probably caused by a full disk.

1. go-langserver has a [max cache size of 50GB](https://github.com/sourcegraph/go-langserver/blob/1afa9c06d8bb8b2c5746e539ed4eb80c23b21db3/main.go#L47) by default, and we haven't overridden it in [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/e8008df85badc98ec561b7d288a95faefa79b44f/configure/lang/go/lang-go.Deployment.yaml#L31)
2. How do you imagine the UX improving? Perhaps the Codecov extension could fetch the last report that ran and show that. Additionally, it could calculate the diff since the last Codecov report and push the info through the diff and apply it to the current view. These are also solutions to stale LSIF data - maybe there's a possibility of reusing logic here.
3. Symbols in prod has a [max cache size of 100GB](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/e8008df85badc98ec561b7d288a95faefa79b44f/base/symbols/symbols.Deployment.yaml#L37-L38)

**Comment by efritz** [comment]
If there's no index for this repository and the symbol disk is full, we won't be able to get symbol search or search-based jump-to-def (as it relies on symbol search).

I think the resolution here is having better paging/alerts for such conditions, which distribution is making good progress on.
