### ISSUE TITLE
Sourcegraph.com out of disk space

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7735]
- **Sourcegraph version:** "Sourcegraph.com"

Visit a not-yet-cloned repo (I just cloned this one during a customer demo:  https://sourcegraph.com/github.com/marick/Midje)

Once cloned, run a search: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/marick/Midje%24+test&patternType=literal

See this:

![image](https://user-images.githubusercontent.com/5589410/72377644-b2d4c580-36c4-11ea-8a6e-5a617f5620eb.png)

**Comment by slimsag** [comment]
I think this is actually more a product issue than anything else: searcher should not be running out of disk space because it should not be mirroring all repositories in gitserver that it runs over. It should manage its cache more effectively to stay within the constraints of the disk, I think. cc @keegancsmith @sourcegraph/core-services

**Comment by ggilmore** [comment]
https://sourcegraph.slack.com/archives/CMBA8F926/p1579032103019300?thread_ts=1579031769.018400&cid=CMBA8F926 resolved

**Comment by slimsag** [comment]
Can you clarify why what I said above isn't valid?

**Comment by chrismwendt** [comment]
Fixed pod-tmp-gc in https://github.com/sourcegraph/infrastructure/commit/09f43d04b6fef785936752a0272416dcce599d2d, see https://github.com/sourcegraph/infrastructure/issues/1620

**Comment by keegancsmith** [comment]
To make it clear why the linked (to private repo) fixed our issue. Our job which cleaned up space used on the host for old kubernetes pods was broken due to a bug in go's os.RemoveAll. We switched to just shelling out to `rm -rf` and that resolved the issue. @chrismwendt We use this same Daemonset for our kubernetes customers, so this probably deserves a CHANGELOG entry.

**Comment by tsenart** [comment]
>  was broken due to a bug in go's os.RemoveAll.

Super curious about this. Link to bug report?

**Comment by keegancsmith** [comment]
haha, you do realised you pasted a link to a blog by @efritz?

**Comment by tsenart** [comment]
> haha, do you realise you pasted a link to a blog by @efritz?


![](https://media0.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif?cid=5a38a5a258461dafa94a87413c86b24f972f36ea23c844ad&rid=giphy.gif)

**Comment by efritz** [comment]
This bug follows me job to job.

**Comment by unknwon** [comment]
I heard the story of this bug on @efritz's first day at San Diego, LOL.

**Comment by ryanslade** [comment]
I really like @efritz's article regarding Monads, probably the best I've seen:
https://eric-fritz.com/articles/
