### ISSUE TITLE
internal API for gitserver exec using repo ID

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#7812]
First target client will be lsif-server, which wants to remove its dependence on names (due to renames).

**Comment by efritz** [comment]
I can take this as long as I understand the core team's vision for such a feature (I have my own, but I want to make sure that it lines up with what would be done if it was a core-only effort).

I'm assuming this should be an HTTP API set up with the internal router that takes the same structure as input as gitserver's exec endpoint *except* it takes (raw numeric) repository IDs instead of the name

**Comment by keegancsmith** [comment]
Additionally it shouldn't just proxy the request if we can get away with it. Instead it should HTTP redirect/etc.

**Comment by efritz** [comment]
> Additionally it shouldn't just proxy the request if we can get away with it. Instead it should HTTP redirect/etc.

This is difficult for exec requests _in particular_ because the payload expects the repository name, which we don't have until it hits the frontend in the first place. 

Took a stab at it: https://github.com/sourcegraph/sourcegraph/pull/7828. This creates a route that translates an integer ID into a name (via repo table lookup), then does a reverse-proxy serve of the gitserver address (and adds the repo name to the request body, so we can't _strictly_ proxy it to gitserver without modification).

I think this has several benefits: we do not have to know _much_ about the payloads except what the proxy director needs to rewrite - specifically we don't need to deserialize and call the client directly; additionally, because we don't proxy we can accept requests that would hit multiple gitservers and proxy them in parallel (such as `RepoInfoRequest`, which would contain a list of names _on that shard_).

**Comment by efritz** [comment]
Implemented in https://github.com/sourcegraph/sourcegraph/pull/7828.
