### ISSUE TITLE
a8n: Finish implementation of `src actions exec`

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7850]
I want to finish https://github.com/sourcegraph/src-cli/pull/80, check off the TODOs mentioned in the PR and possibly adding improvements.

**Comment by mrnugget** [comment]
I'm upping my estimation on this, because I think it would be helpful if we implement the `src campaigns create -interactive` command that's suggested by the CLI right now. What do you think @sqs?

(cc @tsenart)

**Comment by sqs** [comment]
Sounds good. In case it wasn't clear, that `-interactive` flag means the command would show a diff (probably in a pager like `less`) and then ask the user for the title, description, and branch name in terminal UI form fields, and confirmation before creating it. So similar to the web UI now. To simplify it, it is fine to require the title/description/branch to be passed as CLI flags and just show the diff and ask the user for confirmation.

If you had a different idea in mind, that is probably totally fine, I just wanted to lay out what I was thinking.

**Comment by mrnugget** [comment]
> command would show a diff (probably in a pager like `less`) and then ask the user for the title, description, and branch name in terminal UI form fields, and confirmation before creating it. So similar to the web UI now. To simplify it, it is fine to require the title/description/branch to be passed as CLI flags and just show the diff and ask the user for confirmation.

Sounds good to me! But just to be clear: with "terminal UI form fields" you mean single-line prompts, right? Or did you have an ncurses interface in mind?

---

Another idea I had that I wanted to run by you: instead of having `scopeQuery` in the actions.json I think it would be great to only have the `run` ("steps") in the JSON and specify the scopeQuery as a flag:

```
src actions exec -reposQuery 'repo:github.com/sourcegraph repohasfile:README.md' -only-repos
```

We could then add an `-only-repos` flag so users could preview the list of repos we found and tweak the `-reposQuery` query before running the plan.

In the future we could then add `src repos search 'query here'` and then do something like this:

```
src actions exec -repos $(src repos search 'query here' | jq '. | join(", ")) ' -f action.json
```

**Comment by sqs** [comment]
@mrnugget I had ncurses in mind, but thinking more, it should probably open `$EDITOR`. The first line is the campaign title, the rest is the description, except for the line beginning with `Branch: ` or `# Branch: ` which is the branch name. The description will be multi-line, so single-line prompts would not work, and an ncurses editor would be annoying.

**Comment by sqs** [comment]
@mrnugget Re: moving `scopeQuery` out of the action file, that helps in some cases but hurts in others. In general, similar tools have the concept of a "test" to determine whether or not the script to change files should run. For shepherd this is `should_migrate`. For us this is `scopeQuery`. In both cases it feels like a part of the campaign rather than a flag (which is only saved in shell history). While you are iterating, I understand it is nice to have a flag for this, though.

Adding `-only-repos` does sound like it would complicate/overload the command too much. Also it feels ugly to have one CLI flag `-only-repos` (kebab case) and another `-reposQuery` (lower camel case).

Also, regarding `scopeQuery` vs `reposQuery`: for large monorepos I think we will want this to match trees not just repos in the future. So I would recommend calling it scope query. If you decide to call it repos query, you should spell out the full word `repositoriesQuery` for consistency (almost all places in our API use that instead of `repo`/`repos`).

What about keeping the `scopeQuery` in the action file but having another subcommand devoted to helping you iterate on the right scope query? Like `src actions scope-query` that could read in the action file and show you the repos matched, or accept CLI flag input for an arbitrary query and show you the same. Then if you run `src -v actions exec` (verbose) it would print out a message like `# Matched 17 repositories. Use 'src actions scope-query' for help with scoping.`.

**Comment by mrnugget** [comment]
> Also, regarding scopeQuery vs reposQuery: for large monorepos I think we will want this to match trees not just repos in the future. So I would recommend calling it scope query. If you decide to call it repos query, you should spell out the full word repositoriesQuery for consistency (almost all places in our API use that instead of repo/repos).

Good point. At the moment, though, I have a feeling that users sometimes expect `scopeQuery` to work like an exact search whose results are fed into the Automation campaign. The majority of that is, IMHO, a UI problem (it should make clearer what the scopeQuery is and what it's not), but I also suspect that the name doesn't help.
> What about keeping the `scopeQuery` in the action file but having another subcommand devoted to helping you iterate on the right scope query? Like `src actions scope-query` that could read in the action file and show you the repos matched, or accept CLI flag input for an arbitrary query and show you the same. Then if you run `src -v actions exec` (verbose) it would print out a message like `# Matched 17 repositories. Use 'src actions scope-query' for help with scoping.`.

Sounds good!

**Comment by mrnugget** [comment]
PR merged: https://github.com/sourcegraph/src-cli/pull/80
Documentation here and in the `-help` output of `src`: https://github.com/sourcegraph/sourcegraph/pull/8064

I'm still not checking off this ticket, because I want to work on some "polish" I mentioned here: https://github.com/sourcegraph/src-cli/pull/80#issuecomment-578750992

I don't necessarily think this polish is a release blocker, but I think it's better to have it.

**Comment by mrnugget** [comment]
Last PR after which I'd consider this ticket "done": https://github.com/sourcegraph/src-cli/pull/91

**Comment by mrnugget** [comment]
Closing this ticket now. Here's a recording of the new CLI workflow:

![new_campaign_flow](https://user-images.githubusercontent.com/1185253/73296650-6df37780-420a-11ea-8f10-171a4c1c481d.gif)

1. Run `src actions scope-query` to see over which repositories the action will run
2. Run `src actions exec` to execute the action that runs a shell command and 2 Docker containers per repo
3. Pipe the (now cached) patches to create a campaign plan (that can be shared)
4. Create a campaign
