### ISSUE TITLE
a8n: Clean up after deleting / closing campaigns

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7892]
This issue is a place for us to discuss what should happen when we close or delete a campaign.

For close and delete what should happen to:
* pending campaign jobs
* pending changeset jobs
* completed campaign jobs
* pending changeset jobs

**Comment by mrnugget** [comment]
"pending campaign jobs" cannot exist on a Campaign. A CampaignPlan has to be fully finished before a Campaign can be created.

In general, since we currently cannot distinguish between, "processing" and "pending", we should simply block closing/deleting a Campaign if there are "processing"/"pending" jobs.

**Comment by tsenart** [comment]
@mrnugget, @ryanslade: Should this be pulled in 3.14? If so, please label things accordingly.

**Comment by mrnugget** [comment]
I don't think this is valid anymore after #8008.

> pending campaign jobs

Don't exist anymore. After #8008 we only use `CampaignJob`s to store `diffs`. They're not being run or processed anymore.

> pending changeset jobs

It's not allowed to [close a Campaign](https://github.com/sourcegraph/sourcegraph/blob/1f791aa1e566494419646a50ffbba62e24c3f516/enterprise/internal/a8n/service.go#L484-L491) or [delete a Campaign](https://github.com/sourcegraph/sourcegraph/blob/1f791aa1e566494419646a50ffbba62e24c3f516/enterprise/internal/a8n/service.go#L583-L589) while it has pending/processing `ChangesetJob`s.
