### ISSUE TITLE
a8n: Updating partially published Campaigns is not supported

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7915]
Right now we don't support updating a Campaign's changesets when they've
only been partially published. We have an explicit check in the code
that makes sure to only update changesets if the Campaign has been
published.

But that means that we don't support the following scenario:

1. Create Campaign with 10 changesets *in draft mode*
2. Publish 2 of 10 changesets, creating them on code hosts
3. Update Campaign to change name, description or arguments (`scopeQuery`, `matchTemplate`, ...)
4. 2 already-published changesets are updated/closed on code hosts.

Supporting this is not trivial, since we'd effectively need to detect
whether we're in this subset-published mode and depending on that, do a
different update than we'd do otherwise.

#### Option A

In the normal update path (all or no changesets are published), we create "missing changesets" on codehosts that haven't been created before.

But in this new subset-update path (where only subset of changesets is published), we haven't created `ChangesetJobs` for all repositories yet, so we shouldn't create those now.

Instead, we should _only_ update the Changesets that have already been published, but _only_ if the updated Campaign would create them again.

If the updated Campaign would _not_ create them again, we'd need to close them.

#### Option B

Another possibility: when you update a Campaign, all already-published changesets are closed by default and only recreated/updated when you re-publish them individually or publish the whole Campaign.

**Comment by tsenart** [comment]
Will this be part of 3.13? Please label things accordingly if so.

**Comment by mrnugget** [comment]
> Will this be part of 3.13? Please label things accordingly if so.

I don't know yet. I need @christinaforney's input on this and whether we go with Option A or B or something entirely different.

**Comment by christinaforney** [comment]
I predict that this partially published state is actually going to be the most common for making updates. Stepping back and thinking about the likely the user flow and desired experience: I send out the campaign for review, it looks good or I make a few changes. Then, I test it on a handful of repos only to find that I missed something and builds now fail for all changes. I will want to update my campaign, and preview the changes. This piece needs to be validated with customers, but I think that I'd want to send the campaign out for review without "spamming" the PRs with changes in case I wanted to iterate on my previews, I could then re-publish the same commits, I would expect the same PR to be updated (rather than opening a new one), assuming that repository is still included as part of the changes.

Takeaways from the thought exercise:
- It seems like Option B is actually better for the user flow. 
- Could we give the user the option to update the published PRs vs. go back to a draft state? How much extra work is this?
- We should focus on getting the pure states (draft and fully published) updating with a nice user flow first. 
- We should solve this before moving on to stacking diffs.

**Comment by mrnugget** [comment]
>     * Could we give the user the option to update the published PRs vs. go back to a draft state? How much extra work is this?

That would include implementing both options, I think. I honestly think, though, that this is what we should be aiming for. Now that I have your input I'll try to see how hard it would be to implement a combination of both options and get back to you (or implement it 😄 )

> * We should focus on getting the pure states (draft and fully published) updating with a nice user flow first.
> 
> * We should solve this before moving on to stacking diffs.

Agree with both of these assements. I assigned this to me and will work on this before my more research-y things in 3.13.

**Comment by mrnugget** [comment]
@christinaforney Little update on my approach after thinking this through again. I'm going to first try to implement the updating of the already-published changesets without any closing/re-opening.

The reason for that is that for now it's straightfoward to think about ("what's published on a codehost will be updated or closed if it shouldn't exist anymore") and easier to implement.

I wrote "for now" because unpublishing single changesets (closing but having the ability to reopen) would be a new concept. Right now you cannot close/reopen single changesets anywhere in our UI (but on the codehosts! an option we always have.), even if the campaign has been fully published or not. But once we have the updating logic in place, we could still add the whole published->unpublished functionality on top.
