### ISSUE TITLE
src-cli versioning UX

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#7951]
I recently ran into some friction with the src-cli <-> Sourcegraph versioning scheme we have, and I'd like to open a discussion on how to make it smoother.

In the process of helping a customer through an issue, I created a new `src extension copy` command, released a new version of src-cli, and instructed them to follow  https://github.com/sourcegraph/src-cli#installation. There are a few issues with the new versioning for src-cli:

- The customer's instance is older than 3.12 and doesn't have the [redirect handler](https://github.com/sourcegraph/sourcegraph/pull/7600), so it 404ed. Maybe a docs update would be sufficient here.
- The handler on Sourcegraph.com [redirects to src-cli version 3.10](https://github.com/sourcegraph/sourcegraph/blob/0e439ad32e108c368fb91524cb9127ace382ba25/internal/src-cli/consts.go#L9) (hard-coded), which wouldn't have had the new subcommand. Is there a way to keep these in sync? If not, maybe the redirect handler should fall back to older minor versions if a release for the current minor release doesn't exist. After adding a new subcommand in a commit to master, that commit needs to get cherry-picked to the minor branches and each needs a new patch release. This would needs docs, too.

The URL 404ed, so I instructed the customer to download the binary directly from GItHub at `latest`.

This dovetails into https://github.com/sourcegraph/sourcegraph/issues/3231

**Comment by slimsag** [comment]
> The customer's instance is older than 3.12 and doesn't have the redirect handler, so it 404ed. Maybe a docs update would be sufficient here.

Yes, done: https://github.com/sourcegraph/src-cli/commit/cd785d74aa583cb258138e546a0c639af2b3ae8e

> The handler on Sourcegraph.com redirects to src-cli version 3.10 (hard-coded)

This is not true. It redirects to the latest patch release corresponding to the major.minor version that is hard-coded, such that if the version is hard-coded on a user's instance to e.g. `3.10.1` they will get the latest `3.10.x` version (say `3.10.2). Additionally, assuming you followed [the instructions](https://github.com/sourcegraph/src-cli#releasing) for releasing the new version, that constant on Sourcegraph.com would reflect the latest version of the CLI anyway.

> After adding a new subcommand in a commit to master, that commit needs to get cherry-picked to the minor branches and each needs a new patch release. This would needs docs, too.

This is only needed if you are trying to release a new feature out-of-band with Sourcegraph, which should not be the norm. The assumption is that we are now releasing src-cli alongside Sourcegraph, so to speak. Effectively, it should've been:

- You add a new command to `master`
- You cut a new src-cli release following the instructions in the README.
- Sourcegraph and the latest src-cli version are released on the 20th of each month.
- If a user wants access to it earlier, they can be advised to install the absolute latest version from sourcegraph.com just by running [the commands in the README](https://github.com/sourcegraph/src-cli#installation) but there is no guarantee that version will be compatible with their Sourcegraph version.

@efritz that all match up with your expectations?

**Comment by efritz** [comment]
Sort of. I think it's fine to have the following steps:

- Add a new command to master (say we're in the 3.13 cycle)
- Cut a src-cli release
- Cherry-pick into 3.12.{x+1} and release that patch (assuming that the feature would work on a 3.12 instance)
- Same with 3.11, if necessary

This is the way this feature was _meant_ to work when I wrote it so that we can do compatible releases of src-cli after an instance has already shipped without having to change the instance code or configuration.

I don't think that new commands will necessarily be rare, and bug fixes will want to follow the same release procedure.

> The assumption is that we are now releasing src-cli alongside Sourcegraph

I think this is less true in reality. If we were really releasing src-cli features in lockstep with Sourcegraph it shouldn't be released separately at all - it should be shipped with the instance so that there's no version discrepancy.

src-cli being a consumer of Sourcegraph means that it might need to move at a different rate, which I think is fine. If we really want to make that assumption a reality I think we need to rethink the release and installation process a bit more.

**Comment by slimsag** [comment]
Cool, that sounds fine to me for now. Can you document those steps @efritz and close this issue?

**Comment by efritz** [comment]
See https://github.com/sourcegraph/src-cli/pull/86.
