### ISSUE TITLE
External services UI shows GitHub Enterprise improperly

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#8265]
On v3.12.6

Repro:

1. Go to Site admin > Manage repositories > + Add repositories
2. Select GitHub Enterprise (expected: the name field is filled with "GitHub Enterprise", actual: "GitHub")
3. Create it
4. Go back and edit it (expected: the header shows "GitHub Enterprise", actual: "GitHub.com" as in the screenshot below)

I don't know if this is causing any underlying problems or if it's just a visual glitch.

![image](https://user-images.githubusercontent.com/1976/73742673-cc848e00-4701-11ea-866a-5696fb57a14a.png)

Adding to 3.13 milestone because it is a bug with high potential for confusion or worry. @tsenart Can you please assign/schedule this?

**Comment by unknwon** [comment]
I think it's a visual glitch, working on it now.

**Comment by unknwon** [comment]
After some digging, I realize the fix to this problem might require non-easy change for me. I think the @sourcegraph/web team should own fix this.

The root cause:

1. We use a "map" to return what should be the proper title:

https://github.com/sourcegraph/sourcegraph/blob/541ef3c940d1796c3faf56ed16e92013a3050651/web/src/site-admin/SiteAdminExternalServicePage.tsx#L128

2. The problem is, we have same kind for both GitHub.com and GitHub Enterprise:

https://github.com/sourcegraph/sourcegraph/blob/541ef3c940d1796c3faf56ed16e92013a3050651/web/src/site-admin/externalServices.tsx#L1071-L1072

**Comment by lguychard** [comment]
Hmm, looks like this was introduced in https://github.com/sourcegraph/sourcegraph/commit/216dfaccb10976825138a47a29db2bdcb631c211

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
