### ISSUE TITLE
Add support for repository visibility filter in search

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#8344]
A customer (https://app.hubspot.com/contacts/2762526/company/557475882) would like to filter repositories by the `visibility` param from the GitHub API: https://developer.github.com/v3/repos/#list-your-repositories 

This is a nice-to-have (not urgent), but will be helpful for running campaigns.

**Comment by unknwon** [comment]
It's surprising that GitHub's advanced search does not support visibility option 🤔 https://github.com/search/advanced

**Comment by evanweible-wf** [comment]
It looks like they do, just not via that UI. They use the `is:` argument rather than `visibility`:

- `org:Workiva is:public`
- https://github.com/search?q=org%3AWorkiva+is%3Apublic&type=Repositories

And maybe that maps to the `type` parameter instead of `visibility`? I'm not sure.

**Comment by unknwon** [comment]
Good finding, @evanweible-wf! 

In that case, the following GitHub code host connection config should work:

```json
  "repositoryQuery": [
    "org:Sourcegraph is:public"
  ]
```

**Comment by christinaforney** [comment]
@unknwon - Thanks for thinking of that! Unfortunately, it doesn't work for this case - we would like to be able to run this query as part of the `scopeQuery` or as a search filter inside of Sourcegraph, not as a code host configuration.

**Comment by unknwon** [comment]
Ah, gotcha. I missed understood the problem. Thanks for clarification!

**Comment by tsenart** [comment]
@unknwon: Your recent PR #8495 paves the way for this feature, which more generally applies to all code hosts we integrate with, not only GitHub. cc @rvantonder, once we have this column, we should find a way to integrate it with the search syntax.

**Comment by tsenart** [comment]
@rvantonder: FYI: We now have the `private` column in the repo table. This feature could be easily added, including frontend. I'll label it with `good-first-issue`.

**Comment by tsenart** [comment]
cc @mrnugget and @eseliger, apparently this was asked for in the context of campaigns, so please triage.

**Comment by mrnugget** [comment]
It would be great to get this into the next release, but I'll need to taker a closer look to see how difficult it would be.

**Comment by keegancsmith** [comment]
The backend change is relatively straightforward and not that big. Unsure the work required on the frontend.

**Comment by mrnugget** [comment]
Seems fun. I could take this on. I'd estimate at 1 day for me. Or do you want to do this @rvantonder?

**Comment by rvantonder** [comment]
@mrnugget feel free to take it if you want it in the next release. One day taken off here to me means one day longer till `and`/`or` queries, and any time I gain is more valuable for that essential feature. Since the current description says the `visibility` addition is not urgent I'm not strongly motivated to take it on this release.

**Comment by rvantonder** [comment]
@mrnugget so to introduce this filter, you want to add the keyword here:
```
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@640ca8e6539faf5a88fbc3bec471a8421348008b/-/blob/internal/search/query/searchquery.go#L13-92
```

Then you can access the value with something like `q.Fields[FieldCase]` for a query `q` wherever the logic is introduced. Note: this will change slightly and become `q.Fields()[FieldCase]` because of https://github.com/sourcegraph/sourcegraph/pull/9208 but the gist is the same.

On naming, `visibility` is good, but there might be a name that better encompasses the idea, since we deal with more code hosts besides GitHub. I'm not sure, but if you come up with something better don't hesitate (or poll in channel).

The @sourcegraph/web side will have to update knowledge of `visibility` or the like to autocomplete enum values, and for smartSearch highlighting.

**Comment by mrnugget** [comment]
Thank you @rvantonder!

Regarding the name of the filter: I think we should go with `private:[yes,no,true,false]` instead of `visibility:[all,public,private]` because we don't need the "all", since the absence of the filter defaults to "all". But I'm happy to let you or @christinaforney decide on that.

**Comment by rvantonder** [comment]
I don't think the semantics of implementing this filter with the semantics of a boolean value is a good idea. It will run into the same issue as #7003 and won't allow exclusively private repo filtering, e.g., we want the following to be expressible:

- include only private repos
- include private repos along with other repos
- exclude private repos

If we follow what we did for `fork`, `archive`, it will lead to a psuedo-boolean value domain where we introduce something like `private:only` and all the trouble that comes with that. This also will not allow, for example, the support of `visibility:internal`, without introducing a separate `internal:<psuedo-boolean>` parameter.

So, I think we should stay with the semantics of `visibility` taking on a label/enum value. But the name of the filter itself can be `visibility` or even `is`, or something else.

**Comment by mrnugget** [comment]
Ah, that makes a lot of sense. Thank you! Going with `visibility` for it then, since that makes the most sense in that context to me.

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/2243289985 

For GitLab.

>Quick question/feature request: Is there a simple way to filter out public repos in a personal space?

>For context, often in Gitlab I have a personal space, but share repos in it publicly in case others want to see them.

>I don't universally want to exclude them from searches, but would be good to be able to select to exclude them
