### ISSUE TITLE
Incorrect z-indexes in UI

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#8380]
I've encountered a few places where the z indexing seems off.

One example is the progress indicator for providers:

![image](https://user-images.githubusercontent.com/103087/74344146-c0d43f80-4d71-11ea-99cb-ff2facc1b87e.png)

Another is the overlapping of the active sidebar item in the repo settings page and the dropdown menu for the current repo tree.

![image](https://user-images.githubusercontent.com/103087/74344150-c16cd600-4d71-11ea-8fa5-a35d549cf20d.png)

**Comment by felixfbecker** [comment]
I thought about this and have a proposal how to solve this once and for all and prevent regressions in the future:

1. `z-index`es are global and lead to errors because they are sprinkled throughout the app. The solution to this would be to colocate them.
Let's have a single file `z-indexes.scss` that defines all z-indexes in order as SCSS variables. Reference them where needed: [![z-index matches](https://sourcegraph.com/search/badge?q=r:%5Egithub.com/sourcegraph/sourcegraph%24+z-index+f:css%24&patternType=literal)](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/sourcegraph%24+z-index+f:css%24&patternType=literal)
2. Enable [`value-no-numeric-constants`](https://www.npmjs.com/package/stylelint-value-no-numeric-constants) on `z-index` to force the use of variables instead of numeric constants (prevent regressions). The lint message should be customized to mention `z-indexes.scss`.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Related #8045

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
I'm deprioritizing this compared to other issues we have, and because the draft PR I had opened needs to be rethought a bit with regard to stacking contexts and requires some more tooling investment, like a VS Code extension that highlights whenever there's a CSS property that creates a stacking context.
