### ISSUE TITLE
Add BitBucket build status support in bitbucket-server-plugin

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#8386]
The Bitbucket server plugin currently does not support sending build status related webhook events.

We'd like it to be able to send build status `created` and `updated` events:
https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Buildstatuscreated

Related to:  https://github.com/sourcegraph/sourcegraph/issues/7093

**Comment by kzh** [comment]
I started taking a look at this. Listening to the event [BuildStatusSetEvent](https://docs.atlassian.com/bitbucket-server/javadoc/4.0.7/build-api/reference/com/atlassian/bitbucket/build/BuildStatusSetEvent.html) and producing a webhook payload is in the works. However, there seems to be a caveat. There isn't a way to retrieve the repository from the event in the BBS Java API due to this:

> Note that the request doesn't specify a repository. This is because the same build information will be shared across all repositories containing the targeted commit. In practice this means forks of the same repository stored in Bitbucket Server will all display the same build information for common commits.
https://developer.atlassian.com/server/bitbucket/how-tos/updating-build-status-for-commits/

All that is provided is the commit hash. Querying for the specific repository/changeset might have to be done on the Sourcegraph side. The current payload schema is:
```
{
  "user": User,
  "commit": "commitid"
  "status": {
    "name": "Unit Tests (Python)",
    "description": "Build started",
    "state": "INPROGRESS",
    "key": "mybuildtool",
    "url": "https://my-build-tool.com/builds/MY-PROJECT/BUILD-777",
    "created_on": "2015-11-19T20:37:35.547563+00:00",
  }
}
```

**Comment by ryanslade** [comment]
Great, thanks for looking into this.

I had a similar problem with GitHub since Check events can also apply to multiple repos. I think as long as we have the commit id we'll be able to do a lookup on our side, even if it means adding a new column.

Is there any way to get the remote branch name? That's what we're using for GitHub in order to find the correct PR given a build event.

**Comment by kzh** [comment]
Unfortunately, the branch name isn't exposed by the API either.

**Comment by kzh** [comment]
I uploaded a build containing the merged PR to bitbucket.sgdev.org.
