### ISSUE TITLE
Backup snapshotting of Sourcegraph instance might corrupt .git dirs

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#8415]
- 3.12.6 
- AWS linux intel EC2: docker-compose 

#### Steps to reproduce:

1. Follow https://docs.sourcegraph.com/admin/install/docker-compose/aws to create a sourcegraph instance
2. Add one repo to it
3. Create a snapshot of the volume: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-creating-snapshot.html
4. Create a second EC2 instance and for the volume choose to use the snapshot just created

Observe the repo .git directory in inconsistent state (if you're lucky and it reproduced)

![image](https://user-images.githubusercontent.com/534011/74485429-97014280-4e6f-11ea-8780-ee236bc5f2a1.png)

#### Notes:

This doesn't seem to be AWS or docker-compose specific. Any snapshotting that happens while a git operation is in flight could potentially trigger this.

/cc @mrnugget

**Comment by keegancsmith** [comment]
To reproduce I assume you kept the zoekt disk /  etc since we managed to find results. This is quite tricky to solve properly since it isn't even necessarily even just git that is the issue here, but the filesystem probably needs to be told to flush caches. I'm not sure what we can do, other than maybe add an endpoint which flushes fs caches. Adding first class support to backing up in each of our services seems like a lot of work.

As for how this is failing, we can probably file another issue about making it fail nicely. For example if we set `GIT_DIR` then git won't do the discovery all the way up to `/data` and instead will fail with a better error message. Additionally we could look into making our janitor job more aggressively detect bad `.git` dirs. WDYT?

**Comment by tsenart** [comment]
Ping @uwedeportivo, see above.

**Comment by slimsag** [comment]
> As for how this is failing, we can probably file another issue about making it fail nicely. For example if we set GIT_DIR then git won't do the discovery all the way up to /data and instead will fail with a better error message. Additionally we could look into making our janitor job more aggressively detect bad .git dirs. WDYT?

This SGTM

**Comment by keegancsmith** [comment]
Sent out a PR to set GIT_DIR https://github.com/sourcegraph/sourcegraph/pull/11808

**Comment by nguyenlethaihoang** [comment]
Hi bro @uwedeportivo , can you give me some advice for backing up Sourcegraph?
