### ISSUE TITLE
Add an option to force plaintext (no syntax highlighting) for debugging

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#8433]
Deal-blocking for https://app.hubspot.com/contacts/2762526/company/554275594

## Background

We are being compared to a fork of https://github.com/google/codesearch, which lacks syntax highlighting and is very bare bones, but search results show up very quickly. With Sourcegraph, the result boxes show up instantly, but it takes awhile for the code contents to show up, and current hypothesis is this delay is due to syntax highlighting.

## Success criteria

* Top-level goal is make search results appear as quickly as they do in the legacy code search system (i.e., nearly instantly)
* Proximal goal is to add a setting that can disable syntax highlighting, ideally a setting which can be enabled/disabled per user, but if this would take significantly longer, a global site config flag is okay, too.

**Comment by dadlerj** [comment]
@slimsag just to check, is this a priority of yours? If not, should this code (syntax highlighting, generally) and this particular issue be reassigned to core?

**Comment by dadlerj** [comment]
Bump @slimsag

**Comment by slimsag** [comment]
For the customer-specific topic here, let's continue discussion in https://github.com/sourcegraph/customer/issues/45

For the broader topic of "is syntax highlighting making search results slow?" I believe the answer is no and the hypothesis in the issue statement here is incorrect. Someone will need to actually measure the performance here.

From intuition and recollection, the breakdown of time spent displaying search results is

1. The fact that the webapp currently fetches the entire file of contents for displaying each search snippet (https://github.com/sourcegraph/sourcegraph/issues/6992), likely the worst offender.

Also, similarly, I believe the time spent syntax highlighting is by a large majority spent:

1. Fetching the file contents from Gitserver (takes around 500ms-1s IIRC)
2. Actually highlighting the file (~200-700ms)
3. Transferring the large amount of HTML data back to the client (depends on user's network connection).

We should measure and discuss this more, or fix https://github.com/sourcegraph/sourcegraph/issues/6992 first -- but I want to be clear that:

- "Disabling syntax highlighting" may really not give us much benefit
- "First loading unhighlighted and then loading highlighted in the background" may just make things worse by putting more load on gitserver fetching and the user's network.

I am removing "good first issue" because this is no longer about just adding an option to disable highlighting as an experiment to test a hypothesis.

**Comment by slimsag** [comment]
On revised thought, I am content with the following:

- Add monitoring for syntax highlighting vs. gitserver perf: https://github.com/sourcegraph/sourcegraph/issues/10049 (this should be done first)

- Add a user setting (i.e. can set in user, org, or global settings cascade) which disables syntax highlighting by forcing plaintext rendering. This should be a 100% backend change and not too difficult

**Comment by nicksnyder** [comment]
Are we planning this for 3.17? If so, please add this to the 3.17 milestone.

**Comment by felixfbecker** [comment]
My intuition is also that the core problem here is #6992

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
The metrics are in place for https://github.com/sourcegraph/sourcegraph/issues/10049.
