### ISSUE TITLE
Searches from browser extension should respect 'search.defaultPatternType' setting

### ISSUE THREAD

**Issue by byrongrogan** [sourcegraph/sourcegraph#8498]
- **Sourcegraph version:** 3.12.5
- **Platform information:** OSX Chrome 80.0.3987.106 / Sourcegraph extension v20.2.5.1810

#### Steps to reproduce:

1. Set   `"search.defaultPatternType": "regexp"` in Site settings
2. Search from the chrome address bar (`src <query>`)

#### Expected behavior:
The search uses 'regexp' mode

#### Actual behavior:
The search always uses literal mode regardless of settings, with no clear way to override

This is confusing behavior. It looks like the browser extension always sets `patternType=literal` regardless of settings, even though some folks strongly prefer the regexp mode.

**Comment by unknwon** [comment]
cc @sourcegraph/web for triaging, or maybe it's a backend bug?

**Comment by lguychard** [comment]
cc @attfarhan -- didn't we discuss this when we went with literal search by default?

**Comment by attfarhan** [comment]
We don't currently read the `defaultPatternType` setting from a user's settings in our search clients (browser extension and CLI), since we didn't want to block on making that request to the webapp in order to determine the proper search URL to redirect to.

When we discussed this, we agreed to make omnibar searches always default to literal, since we want all our search clients to have the same default. The way to override the literal pattern type is to include `patternType:regexp` in queries from the omnibar -- we thought that regexp users are more likely to know about the `patternType:` filter, but we know this is not ideal.

The problem is that if we don't explicitly append a `patternType` URL parameter to searches coming from the browser extension, our webapp will by default append `patternType=regexp` to the URL, which is logic we have in order to ensure old URLs without a `patternType` param would still work. We don't currently distinguish whether a URL is coming from the browser extension (or some other client) or not, so we treat all URLs without a `patternType` param as a legacy URL.

@lguychard it seems the browser extension [does fetch the settings cascade sometimes](https://sourcegraph.com/search?q=platformContext.settings+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:browser/src/&patternType=literal). We could experiment with fetching the settingsCascade when the browser extension initializes to determine a user's default pattern type. If a user does a search before the request completes, we could fall back to literal search. What do you think?

**Comment by byrongrogan** [comment]
@attfarhan @lguychard If this is particularly difficult to get right automatically, adding a simple `default search type: regex | literal` setting to the browser extension would be reasonable too.
