### ISSUE TITLE
src-expose serve finds subprojects

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#8636]
src-expose serve finds git repos under a directory and serves up an endpoint to list all repos and git fetch/clone them. Currently it stops crawling into a directory once it finds the `.git` directory. However, this means we don't serve subprojects. eg if your directory structure is this
```
- project/.git
- project/subproject/.git
```
then we only list `project`. However, we should also list `project/subproject`.

Here is were we do the crawling https://github.com/sourcegraph/sourcegraph/blob/bac12cbb510c78d10ec5aae855615d6305b71721/dev/src-expose/serve.go#L141-L145

Requirements:
- Recurse into subprojects
- Don't recurse into `.git`. This is for performance reasons.

Nice to have: Only recurse into subprojects if it is a bare repo. Context: `src-expose sync` creates bare repositories, and is the use case for subprojects. However, `src-expose serve` can also be used to export local normal git repositories into Sourcegraph. But recursing into non-bare repos is a lot more work (eg node_modules/etc is an order of magnitude more syscalls). So we can only do the recursing if the `.git` is configured as a bare repo.

**Comment by joshuabezaleel** [comment]
Hi @keegancsmith , this is my first time looking into the sourcegraph repository, is it okay for a first-timer to have a shot on this?
This is actually also my first time knowing about bare repo so if it's okay I would like to ask several questions and I am sorry if the questions are too simple:
1. I notice that the difference between a bare repo and a non bare repo resides in the `config` file with the line of `bare = <true/false>`. Does this mean that to check whether a repo is a bare one or not we dive into the `.git` folder first, check for the `config` file, and if it contains `bare = false`, it excludes that particular directory since it would be non-bare repo? 
2. When we create a bare repo, we also got several folders like `branches`, `hooks`, `info`, `objects`, and `refs`, so a subproject will be a subdirectory/subfolder with name except those 5? 

Thank you very much and hope you have a great day ahead :slightly_smiling_face:

**Comment by unknwon** [comment]
Hi @joshuabezaleel, good to know you're interesting in implementing this! 



> 1. I notice that the difference between a bare repo and a non bare repo resides in the `config` file with the line of `bare = <true/false>`. Does this mean that to check whether a repo is a bare one or not we dive into the `.git` folder first, check for the `config` file, and if it contains `bare = false`, it excludes that particular directory since it would be non-bare repo?

You are basically correct, but it might be easier and more reliable to just [shell out to `git rev-parse --is-bare-repository`](https://stackoverflow.com/questions/1830701/how-do-i-check-if-a-repository-is-bare).



> 2. When we create a bare repo, we also got several folders like `branches`, `hooks`, `info`, `objects`, and `refs`, so a subproject will be a subdirectory/subfolder with name except those 5?

These directories are inside `.git`, which in fact we shouldn't even look at them. 

If I understand the original post correctly, the directory structure looks like:

```
- project/.git
- project/subproject/.git
```

In this example, once we encounter `.git`, we just skip it (mark it as a repo of course) and then look at `subproject` directory, and continue checking subdirectories of `subproject`.

**Comment by joshuabezaleel** [comment]
Hi @unknwon , thank you for the really fast and kind reply! Truly appreciate it :slightly_smiling_face: 

For the 2nd point:
I am truly sorry if my understanding of the issue is still wrong :slightly_frowning_face: . 

> Nice to have: Only recurse into subprojects if it is a bare repo. Context: `src-expose sync` creates bare repositories, and is the use case for subprojects. However, `src-expose serve` can also be used to export local normal git repositories into Sourcegraph. But recursing into non-bare repos is a lot more work (eg node_modules/etc is an order of magnitude more syscalls). So we can only do the recursing if the `.git` is configured as a bare repo.

Looking at the last paragraph at the issue above said that to recurse into subprojects only if it is a bare repo, but when I tried to create a bare repo in my local with `git init --bare`, there will be no `.git` folder in the directory since all the contents of it will be placed directly at the root of the directory and thus we can only find a `.git` folder in a non-bare repo initialized by plain `git init`. I attach my attempt on my local machine down below.

![image](https://user-images.githubusercontent.com/7043511/75540795-513ba100-5a4f-11ea-9fb1-d73dc644bccc.png)

Thank you very much beforehand for replying, @unknwon !! :slightly_smiling_face:

**Comment by unknwon** [comment]
@joshuabezaleel 
> Looking at the last paragraph at the issue above said that to recurse into subprojects only if it is a bare repo, but when I tried to create a bare repo in my local with `git init --bare`, there will be no `.git` folder in the directory since all the contents of it will be placed directly at the root of the directory and thus we can only find a `.git` folder in a non-bare repo initialized by plain `git init`. I attach my attempt on my local machine down below.

The directory name of a Git repo is arbitrary, I think it's just how `src-expore` chooses to organize directories on the file system. It always uses a subdirectory named `.git` to indicate where the actual Git repo is stored (e.g. `project/.git` for Git repo of `project`). 

Therefore, we have `project/subproject` as a subproject, and have `subproject`'s Git repo be stored in the `project/subproject/.git`.

Here is a maybe better example:

```
- project/.git
- project/subproject/.git
- project/subproject/subsubproject/.git
- project/subproject2/.git
```

**Comment by keegancsmith** [comment]
@joshuabezaleel yes you can create have a bare repo which isn't `.git`. For the purpose of this task you can ignore that. The optimization is about the repository structure created by `src-expose sync`. In that case we will have the `.git` directories, and they will be bare repos.

Also thank you for tackling this. Looking forward to reviewing :)

**Comment by joshuabezaleel** [comment]
Thank you for the explanation, @unknwon !!! That's super helpful :blush: 

HI @keegancsmith , thank you very much for the kind and patient reply! Truly appreciate it :slightly_smiling_face: 
I just want to make sure several points, if that's okay with you, before trying to attempt:
1. So any kind of project repo directory, both bare and non-bare repos, will have a `.git` folder inside them, right? 
2. Let's say I have a project directory structure as below:
```
bare-repo-1/.git
bare-repo-1/bare-repo-2/.git
bare-repo-1/non-repo/         (no .git folder inside)
bare-repo-1/non-bare-repo-1/.git
bare-repo-1/non-bare-repo-1/bare-repo-3/.git
bare-repo-1/non-bare-repo-1/non-bare-repo-2/.git
```
So if my understanding is okay, it should return 3 directories since we shouldn't recurse to a non-bare repo:
- bare-repo-1
- bare-repo-2
- non-bare-repo-1

I am so sorry for a shallow understanding. Thank you very much and hope you have a great day ahead! :grin:

**Comment by unknwon** [comment]
> 1. So any kind of project repo directory, both bare and non-bare repos, will have a `.git` folder inside them, right?

Yes, you're right.

---

Thanks for the concrete example, sounds right to me :) But defer to @keegancsmith  to confirm.

**Comment by keegancsmith** [comment]
> 1. So any kind of project repo directory, both bare and non-bare repos, will have a `.git` folder inside them, right?

For the purpose of `src-expose` yes. However, you can create bare repos where `$(basename $GIT_DIR)` is not `.git`. But we do not support those, we rely on `.git` existing. This is a fine trade-off to make for `src-expose`, so adding in support for that is out of scope.

> 2. Let's say I have a project directory structure as below:
> 
> ```
> bare-repo-1/.git
> bare-repo-1/bare-repo-2/.git
> bare-repo-1/non-repo/         (no .git folder inside)
> bare-repo-1/non-bare-repo-1/.git
> bare-repo-1/non-bare-repo-1/bare-repo-3/.git
> bare-repo-1/non-bare-repo-1/non-bare-repo-2/.git
> ```
> 
> So if my understanding is okay, it should return only 3 directories since we shouldn't recurse to a non-bare repo (and the subprojects inside it):
> 
> * bare-repo-1
> * bare-repo-2
> * non-bare-repo-1

Your understanding is correct. To be a little more explicit the list of repos is:

* bare-repo-1
* bare-repo-1/bare-repo-2
* bare-repo-1/non-bare-repo-1

Note: this optimization is a nice-to-have, you don't have to do it :)

**Comment by joshuabezaleel** [comment]
Hi @keegancsmith , I am sorry for putting a PR this late. Hope it could satisfy the requirements.

This is my first time contributing to Sourcegraph and I am still learning Go so I am really sorry beforehand if I got several things wrong. Looking forward to the review! :slightly_smiling_face:
