### ISSUE TITLE
search: support code or content search type.

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8743]
It'd be nice if we have a search type selector that restricts searches to `code` or `content`, similar to `type:file` and `type:repo`. We'd have to separate the logic and filter Zoekt results to do this, since we currently return both content and file results for a pattern. It'll take a bit of effort, but not crazy complex.

**Comment by tsenart** [comment]
@keegancsmith believes you might have partially done some of this already. Can this be closed, or put into the 3.15 milestone?

**Comment by rvantonder** [comment]
No, it's not done. For example, these two queries are equivalent:

- `repo:foo`
- `type:repo foo`

For content, or code, we would want the following to be the same:

- `content:foo` (I introduced this part)
- `type:content foo` (this doesn't exist)

Meaning: we detect the `type` value, if it exists, and then decide how to use the pattern for searching things. The problem is that in the original example I gave, with `repo`, we _don't_ actually treat the two queries equivalently in some cases. In some parts of the code we just assume that the only way to query a repo is if `repo:foo` is specified and not `type:repo foo`. This creates nuanced bugs. So, we want the equivalent treatment with something like `type:content foo`, but we should be careful to add the logic so we don't deal with the same problem as `type:repo foo`.

**Comment by rvantonder** [comment]
This is a nonessential and good first issue, which we can use for new members to familiarize with search code. I'd like to not take on nonessential tasks in 3.15.

**Comment by rvantonder** [comment]
Hi @fedealconada, thanks for your interest! A contribution that addresses this specific issue might get pretty involved. We labeled it a "good first issue" mostly in mind for new full time employees for on-ramping. As an external contribution, this might require quite a lot of effort (not to discourage you, I just want to be upfront about the complexity and time cost here). 

I'd love to understand a bit better what your goals and desired outcome for a contribution to Sourcegraph are. That way we can establish what allocation of work/effort makes sense and the right level of support so I can help you get a successful outcome. Mind answering these quickly?

1. Would you say you primarily want to contribute to our codebase and merge a PR (and learn about the codebase along the way)? If not, what is the goal/outcome you are hoping for?

2. Do you feel strongly about developing and using the feature in this issue, or would you be open to working on an existing issue that achieves the same goal/outcome in Question 1, but with a lower entry barrier?

Optionally, it'd be helpful to know how many hours you'd realistically be willing to spend on any contribution. We can follow up after that :-) I'm not sure we have something like an open chat. An issue tracker may be good enough, and we have plenty of docs to help answer questions about the code base. If those come up short, we can probably figure something out.

**Comment by fedealconada** [comment]
Thanks for your answer @rvantonder, really appreciate that. I've been using Go recently, so one of my goals is to get well-versed at it. In order to do that, I thought about contributing on an interesting open-source project using the language. Regarding 1), yes, I'd like to contribute and learn about the codebase along the way. Answering 2), the second option :) 
I'm not sure about the hours as this would be on my spare time. But, whenever I feel motivated I don't mind spending some time doing something I like xD. 
If that sounds good to you, I'd be happy if you could point me out some issue with a lower entry barrier as you have said and we could then take it from there.

**Comment by rvantonder** [comment]
Great! Give me a day or two to look through our tracker for something interesting/valuable with good scope and, and I'll loop you in on one or more of them :-)

**Comment by fedealconada** [comment]
Awesome! Thanks for the help @rvantonder :)

**Comment by rvantonder** [comment]
@fedealconada thanks for your patience, let's continue in #9640

**Comment by notjrbauer** [comment]
@rvantonder I tried to look at this issue because I was interested in learning more about sourcegraph's code search engine. I was expecting a lot more code, but wanted to check here before looking silly in a PR. [I came up with one small addition](https://github.com/notjrbauer/sourcegraph/commit/940b200fe1f26ed79ceedc980d6d08c3f7342408.patch) and hope I'm not being too naive.

**Comment by rvantonder** [comment]
Unfortunately that won't work. That code path will return both file paths and file content results from our Zoekt search component. We need to make sure that the Zoekt results are only content when `content` is specified. 

We are in the process of overhauling our tests so that this sort of addition can be well-tested--right now, I suspect that would be difficult to do as an integration test, so it is best to hold off on this addition until that testing work is in place.

**Comment by rvantonder** [comment]
Done via `file:`
