### ISSUE TITLE
Ability to select code from search results page

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#875]
#### Feature request description

The ability to select code form results on the search results page. 

#### Is your feature request related to a problem? If so, please describe.

It could be useful to select text directly from results rather than having to click into each result and back out. Some workflows could include needing to copy/paste bits of several results.

#### Describe alternatives you've considered.

Clicking into each result, copying what you need, and clicking the back button for each result.

#### Additional context

One UX could be to not navigate onClick if cmd or ctrl are being held.

**Comment by alexism** [comment]
I would like to support this request as I ran into the same challenge today. My intent was to browse code from search result to search result. Currently this means: click through a match, copy the next search pattern, paste it into the search bar, and execute.

Anything Sourcegraph could do to improve this flow would be awesome.

**Comment by vanesa** [comment]
Thanks for this suggestion @ijsnow . Would you find it more UX friendly if you could click a button that deactivates the link to the search results and allows copying the text from the results list directly? 
I'm concerned about "enabling to copy when pressing Cmd/Ctrl" not being intuitive enough/hard to teach to our users, so that there should additionally be a visible option users can click to unlock the ability to copy the search result from the results list.
@francisschmaltz what do you think? Would it make sense to place a "turn off link to search result" button somewhere in the search result preview box? 

Regarding @alexism's suggestion, I'm imagining a feature where the user can press a certain key and the mouse arrow gets little plus sign which allows clicking on any term in the search results preview that automatically adds that term to the query. Would that help with your work flow? I opened feature request to tackle this idea: https://github.com/sourcegraph/sourcegraph/issues/1246

**Comment by ijsnow** [comment]
Yes! I think that would be UX friendly. However, I think it would be ideal to be able to do this via a keyboard shortcut as well. It wouldn't be too much work to implement one once we implement the other since its the same logic.

Alternatively we could just have an icon with a tooltip saying to hold cmd/ctrl to select code to help with educating users. I think this makes sense because I can't imagine a reason why a user would want to leave the link disabled after their done selecting.

**Comment by nicksnyder** [comment]
I think the right solution here is to do exactly what GitHub does when viewing code files. There is a left gutter with line numbers that are clickable and you can always select the code itself.

**Comment by sqs** [comment]
Justification for what @nicksnyder says:

- It is the simplest.
- It is familiar (it's how most other search tools work).
- With search result providers coming soon that provide all kinds of different content, it no longer makes sense to guarantee that all search results have a 100% clickable area.

I do worry that it makes the click target much smaller, though, so I would want to test the UX first.

**Comment by nicksnyder** [comment]
We decided to backlog this since the solution isn't clear.

**Comment by slimsag** [comment]
This was reported again by @ijt here: #5228

**Comment by lguychard** [comment]
From https://github.com/sourcegraph/sourcegraph/issues/10092#issue-604253446: 

> A user at https://app.hubspot.com/contacts/2762526/company/464956351/ complained that It is impossible to select text in the search results UI so he has to navigate to the file first, he said this is a very common workflow for anyone developing Java code and right now it is very annoying to have to navigate to the file first.
>
> Full context: https://sourcegraph.slack.com/archives/CMB6K7SMN/p1587499846168800

**Comment by attfarhan** [comment]
@imtommyroberts we discussed UX for this feature in the past but didn't reach a consensus. Do you have a sense of the preferred way to do this?

**Comment by mrnugget** [comment]
After reading through this ticket (and bumping into the issue myself a lot), I'm wondering what was missing to reach consensus.

It sounds like the idea (https://github.com/sourcegraph/sourcegraph/issues/875#issuecomment-447417760, https://github.com/sourcegraph/sourcegraph/issues/875#issuecomment-459867618)  was to do what GitHub does in its search results view (example: https://github.com/search?q=NewRecorder&type=Code) which is to make the code itself selectable and the line numbers links that have an hover effect.

What were the concerns with that?

**Comment by rrhyne** [comment]
I agree. Clickable line numbers is a fitting solution. I personally found it very surprising that all text was a link when first learning the application. 

As it's a fairly large change to current behavior, It may be necessary to communicate the change to experienced users. A quick suggestion:

Upon clicking a line in a search (when no text is selected), display a popover pointing to the corresponding line number. Popover text would read:

"Click a line number to view a file at a specific line."

Clicking anywhere would dismiss the popover permanently. If we received customer support tickets on the subject, we may want to require dismissal of the popover to ensure users are seeing the message.

**Comment by poojaj-tech** [comment]
Click target area can be increased significantly by making the line of code implicitly clickable (like  [Opengrok](http://android.macpod.net/search?project=android-4.0.1_r1.2&q=import&defs=&refs=&path=admin+cts&type=&si=q) does), this may make it feel like less big of a change.

**Comment by christinelovett** [comment]
https://app.hubspot.com/contacts/2762526/company/578600789

**Comment by malomarrec** [comment]
+ 1, this was reported by @indradhanush internally. 
The problem is clear, however to change this we would need to validate that it doesn't impact the core interaction of: click anywhere to go to the file + line clicked. This requires design, and does't fit into our current priorities.
Keeping backlogged for now.

**Comment by fkling** [comment]
This feature has been implemented in #30033/#30351 (#30308 also fixes an issue with copying text in Firefox).
In this implementation we are preserving the current behavior (clicking on a result opens the file), unless text has been selected.
