### ISSUE TITLE
indexed-search: Performance improvements for concatenated regex queries

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#8800]
A customer reported indexed-search running slower than expected for regexes of the form `(AX|AY|AZ)` (or groups of constant strings). We suggested adjusting the regex to `A(X|Y|Z)`. This did indeed improve the performance of the query, but it is still slower than expected. As such, we should investigate potential performance improvements for evaluating these sort of queries.

### Context

Zoekt's matching engine transforms regex's into a tree of substring queries. These substring queries can efficiently consult zoekt's index to find potentially matching documents. So a regex like `foo(bar|baz)` will become the query `(AND (content "foo") (OR (content "bar") (content "baz")))`. My guess at the performance issue is that `(OR ...)` could be more efficiently rule out poor matches.

### Ideas

1. Investigate how to more efficiently evaluate / reduce the work done for `(OR ...)` in zoekt's matchtree evaluater.
2. More generally see if we can more efficiently consult the zoekt index for regular expressions with groups.
3. Translate `(X|Y|Z)` where `X`, `Y` and `Z` are strings into just substring search. This avoids the cost of running the regex engine in this common case.

**Comment by keegancsmith** [comment]
For (3) I would suggest taking a look at how you can inspect a regular expression using [`regexp/syntax`](https://golang.org/pkg/regexp/syntax/). We do it in a few places in Sourcegraph and Zoekt: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/+fork:yes+syntax.Parse%5C%28+%28regexp%7Csyntax%29&patternType=regexp#11

What is likely most interesting is how zoekt's function [`RegexpToQuery`](https://sourcegraph.com/github.com/sourcegraph/zoekt@ef3ec2393b46a046da9ca00d8d63191bf88368d3/-/blob/query/regexp.go#L48) which translates a regex into a bunch of substring searches. See it's uses to also understand were to implement the optimization/etc. This work should also be upstreamable to google/zoekt.

**Comment by asdine** [comment]
If I understand correctly, whenever the parser detects a regular expression (other than a litteral, which is also a valid regexp but is treated differently by the parser), it always uses the regex engine on all documents, which means that there is a potential performance cost on any regex usage.
I might be wrong though, I'd appreciate if someone has some insight on this subject.

I am analyzing how the matchtree is generated for `needle or thread` compared to the one generated for `needle|thread`.

First, after playing with the tests and a lot of Printlns, I realised that [RegexpToQuery](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/query/regexp.go#L48:6) doesn't return an exact translation or a regexp into a query, but simply creates a simplified version of the regex.

Example:

| Regex | Query |
| --- | --- |
| `^foo` | Substring: `foo`| 
| `foo` | Substring: `foo` |

I'm currently trying to improve the  [RegexpToQuery](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/query/regexp.go#L48:6) function so that it can detect whenever there is an unsupported regex syntax, meaning one that doesn't translate directly to a zoekt query, it indicates that this is a simplification and that it should work as usual. If not, then we can skip returning a regex node altogether and call [newMatchtree](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/matchtree.go#L663) recursively for that query.

**Comment by keegancsmith** [comment]
> If I understand correctly, whenever the parser detects a regular
> expression (other than a litteral, which is also a valid regexp but is
> treated differently by the parser), it always uses the regex engine on
> all documents, which means that there is a potential performance cost
> on any regex usage.

Kind of. It will only run the regex on documents which contain matches
on the substring query it creates with RegexpToQuery. The substring
query will skip documents which don't match the trigram iterator
used. Then additionally note the signature of matches:

  matches(cp *contentProvider, cost int, known map[matchTree]bool) (match bool, sure bool)

The key argument here is "cost". The "cost" of regex is higher than
substring. So we will call matches on substring before we call it on
regex. So if substring has no matches it will return (match=false,
sure=false). This will prevent us running the regex engine.

You will note there is room for improvements here even on top of what is
detailed in this issue. For example the "noMatchTree{substring}" only
needs to look for one match in a document, not all matches.

> First, after playing with the tests and a lot of Printlns, I realised
> that
> [RegexpToQuery](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/query/regexp.go#L48:6)
> doesn't return an exact translation or a regexp into a query, but
> simply creates a simplified version of the regex.

Yes, RegexpToQuery tries to create a query which will match atleast all
the same documents the regexp would match. eg if your query is
(foo|.*|bar) it should return const{true} since it can't restrict ".*"
so it can't give a reasonable substring query.

> I'm currently trying to improve the
> [RegexpToQuery](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/query/regexp.go#L48:6)
> function so that it can detect whenever there is an unsupported regex
> syntax, meaning one that doesn't translate directly to a zoekt query,
> it indicates that this is a simplification and that it should work as
> usual. If not, then we can skip returning a regex node altogether and
> call
> [newMatchtree](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/matchtree.go#L663)
> recursively for that query.

That sounds perfect. So just to make it clear it can do it for "foo" but
not for "^foo" since it can't represent the anchor.
