### ISSUE TITLE
Webhook always initialized with example.com

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#8827]
#### Steps to reproduce:

ExternalURL initially is example.com, which always points the BBS webhook to a wrong address.

**Comment by unknwon** [comment]
Possible solution, use `conf.Cached`:https://github.com/sourcegraph/sourcegraph/blob/88c74bb0699ae77de08a14a2d55d417f38b06959/internal/conf/client.go#L98-L104

**Comment by unknwon** [comment]
I'll take a look next Monday (March 9th), but anyone feel free to pick up.

**Comment by unknwon** [comment]
Update: It would be simple task to solve with `conf.Cached`, except [we also accept CLI flags for setting default value for **ExternalURL**](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=master&file=cmd%2Ffrontend%2Finternal%2Fcli%2Fserve_cmd.go&editor=JetBrains&version=v1.1.2&utm_product_name=GoLand&utm_product_version=2019.3.3&start_row=191&start_col=29&end_row=191&end_col=29). First attempt failed.

I do not know what's the life state of these flags, since we now advocate customers all set `externalURL` in their site configuration.

The ugly workaround is here: https://github.com/sourcegraph/sourcegraph/pull/8885
