### ISSUE TITLE
Add match case toggle to search

### ISSUE THREAD

**Issue by cherealnice** [sourcegraph/sourcegraph#900]
#### Feature request description
Hello,

I have been using Searchable for a few days now and it's great!  One thing I noticed is that queries are not case sensitive by default.  Even though it's easy enough to pass `case:yes`, it would be nice to have a quick toggle for this option, as it's common for many editors.  If this is something you discussed and decided against please let me know!

#### Is your feature request related to a problem? If so, please describe.
Kind of. I had to dig though the docs to perform a case sensitive search, which was not preferred, but good documentation made it pretty easy :D

#### Describe alternatives you've considered.
Just passing the option in the query works, but it seems like this is a common enough option that it should be easily available.

**Comment by sqs** [comment]
We should add a `case:yes` dynamic search filter for queries that contain terms and that do not already contain a `case:` keyword.

**Comment by vanesa** [comment]
@sqs shouldn't the `case:yes` appear as a dynamic filter even if it is already contained in the query (shown selected) so that the user can easily remove it from the query?
I added the code for a `case:true` filter to appear whenever there are search results here: https://github.com/sourcegraph/sourcegraph/pull/1233

**Comment by vanesa** [comment]
Resolved: https://github.com/sourcegraph/sourcegraph/pull/1233
