### ISSUE TITLE
Try enzyme for cleaner snapshot tests

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9040]
Our current snapshot tests are quite polluted with internals of properties that are being passed. As suggested here https://github.com/sourcegraph/sourcegraph/pull/9033#issuecomment-599526016 we could give enzyme a try to see if that yields better outputs.

**Comment by attfarhan** [comment]
+1 for this. After trying to add snapshot tests for the `ActivationDropdown` (which uses a Reach UI component that uses portals) with @eseliger and @felixfbecker .  After trying a number of workarounds between `testing-library` and `react-test-renderer` we kept running into errors, and it seems like the only accepted solution is to use enzyme: https://github.com/facebook/react/issues/9244#issuecomment-288771209. This was a lot of pain to try and create snapshot tests due to `testing-library`/`react-test-renderer`.

IMO the benefit of snapshot tests are not worth if it takes more than minimal effort to create them, since they rarely catch issues, and don't really provide context on how the component actually looks when rendered.

For my component I'm going to create a story for storybooks, which @felixfbecker is planning to hook into Percy, and that seems much more useful, but I'll also try introducing Enzyme to create snapshot tests since we'll need a good solution if we continue to add more Reach UI components.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
