### ISSUE TITLE
Immediate no results in structural search

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#9079]
Repro:

1. Go to https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph+%22New%28:%5Bargs%5D%29.:%5Bimmcall%5D%28%22+lang:go&patternType=structural

Expected: see some results (clicking "Show more" does result in results being shown fairly quickly)
Actual: immediate empty search results page with "Show more" button

Also, it is unexpected that it says "No results" definitively but also shows "Show more".

![image](https://user-images.githubusercontent.com/1976/76881008-bfe17280-6835-11ea-8f7f-a868b6497618.png)

**Comment by rvantonder** [comment]
Yeah the UX here isn't great here. This is a known issue, but I don't think we're tracking it. The reason this happen is because two kinds of regex searches for structural search are performed and cascaded (the first tries to find results quickly, the second more expensive). 

This should either 
- automatically run the second if the first doesn't return results or
- the first 'show more' should be something more like an 'increase timeout' suggestion, though timeout isn't necessarily the right hint.

By the way the query contains an unbalanced `(`. This isn't intended to be valid. You might get a result, but really this should raise en error or alert so that the query can be correctly interpreted.
