### ISSUE TITLE
Browser extension contacts sourcegraph.com if access token is rejected

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#922]
Repro:

1. Set Chrome extension Sourcegraph URL to http://localhost:3080 (which you are signed into)
1. Load a page on GitHub
1. Delete the access token it created from your account on http://localhost:3080
1. Sign out of http://localhost:3080
1. Reload a page on GitHub

There are 2 problems:

- ~Even after doing this, the browser extension still tries to send an `Authorization` header (presumably with the revoked access token) (see the console errors in the screenshot)~ I fixed this by going to http://localhost:3080 and right-clicking the extension icon and clicking "Enable Sourcegraph on this domain". I think this prompt should have been shown automatically because it was the exact Sourcegraph URL I had entered.
- The browser extension also contacts sourcegraph.com for some reason (see the network devtools entries in the screenshot)

![screenshot from 2018-11-09 22-25-25](https://user-images.githubusercontent.com/1976/48298216-5d70a900-e46e-11e8-94e2-bc6d905d6067.png)

**Comment by ijsnow** [comment]
Could you elaborate more on what the issue is? It seems like this is about two unrelated things.

1) I don't think the browser extension should work if we don't have a valid token and are not signed in.

Following the repros to get to look at the full network tab, the requests are that are going to sourcegraph.com are the `ViewerConfiguration` requests coming from extensions settings cascades. It's hitting .com because the first request gets rejected and the retry logic moves on. Is this a request that should be treated as sensitive data calling for the no retry flag?

**Comment by sqs** [comment]
> Following the repros to get to look at the full network tab, the requests are that are going to sourcegraph.com are the ViewerConfiguration requests coming from extensions settings cascades. It's hitting .com because the first request gets rejected and the retry logic moves on. Is this a request that should be treated as sensitive data calling for the no retry flag?

Yeah, this request should not be retried on Sourcegraph.com if it fails on the configured Sourcegraph URL.
