### ISSUE TITLE
`src-expose serve` should serve from current dir if no argument supplied

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#9292]
If no argument is supplied, I was expecting `src-expose` to look for git repositories in the current directory.

The current functionality of serving git repositories previously synchronized to `$HOME/.sourcegraph/src-expose-repos` wasn't intuitive for me and I didn't at first understand where the list of repos from `/v1/list-repos` was coming from.

My proposed fix would be either:

 - require a path be provided, like `docker build` does, or
 - if no argument supplied, serve from the current directory.

This current behavior also causes an error if running `src-expose serve` without an argument as it expects the `~/.sourcegraph/src-expose-repos` directory to exist.

**Comment by keegancsmith** [comment]
Are you using the latest version? The latest version prints out a log of what it is serving
```shellsession
$ src-expose serve   
serve: 2020/03/25 09:51:34 listening on http://[::]:3434
serve: 2020/03/25 09:51:34 serving git repositories from /Users/keegan/.sourcegraph/src-expose-repos
```

This is intentional behaviour and is relied on by an existing customer who runs `src-expose sync` separately to `src-expose serve`.

For the move to the `src-cli` tool (#9243) I think adjusting the behaviour to PWD makes sense. I'd like to save the change until then, since it will be a breaking change. I'll document that in the above issue.

**Comment by ryan-blunden** [comment]
Sounds good!
