### ISSUE TITLE
Browser extension overlay's position is incorrect when Octotree sidebar in pinned

### ISSUE THREAD

**Issue by yaohui-wyh** [sourcegraph/sourcegraph#9308]
- **Sourcegraph version:** Browser Extension 20.3.18.1833
- **Platform information:** Chrome 80.0.3987.149

When [Octotree](https://chrome.google.com/webstore/detail/bkhaagjahfmjljalopjnoealnfndnagc) sidebar is pinned on GitHub, Browser extension overlay's position is incorrect.

![image](https://user-images.githubusercontent.com/3115235/77525349-d89bf900-6ec3-11ea-985a-a00424466f89.png)

**Comment by felixfbecker** [comment]
Interesting find, thanks!
Octotree works by adding `margin-left` to the `<html>` element. We position the  tooltip relative to the `<body>` (`relativeElement: document.body`). However, `body` is not actually `position: relative`. This still works because `<body>` is usually not different from the viewport. But when Octotree adds the `margin-left`, `<body>` gets moved too. The only thing we have to do to fix it it seems is to set `body { position: relative; }` in our CSS.

**Comment by vdavid** [comment]
This seems to work fine now:

![Image](https://user-images.githubusercontent.com/2552265/194018251-60164a01-60c3-4d0e-a2bc-5e6f42c8e716.png)
