### ISSUE TITLE
☂️ Code intel paper cuts

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9346]
I've encountered several code intel errors/bugs this morning in https://sourcegraph.com/github.com/sourcegraph/sourcegraph that have made the Sourcegraph user experience quite frustrating to the point where I no longer feel like Sourcegraph is adding to my productivity. Here is a sampling:

I have the following user settings:
```
"lang-go.accessToken": "REDACTED",
"go.accessToken": "REDACTED",
"go.showExternalReferences": true
"go.serverUrl": "wss://go.sourcegraph.com"
"extensions': {
    "farhan/go-imports-search": false,
    "sourcegraph/go": true,
    "sourcegraph/go-imports-search": true,
}
```

1. With LSIF enabled, go [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3cc281d64606d1ec4fa2a5dd8533d07c4ae29d78/-/blob/internal/trace/traceutil.go#L31:2&tab=references) and click on the `Tracer` field in the `Tracer` struct. Note that there is a reference to this field in the very same file.
  * First time, the tooltip window takes forever (more than a minute?) to pop up. There is no indication that anything is happening in the interim.
  * Sometimes the tooltip window has a "find references" button
  * Sometimes it doesn't.
  * When it does, I click on "find refs" and see "no references".
  * Then I wait a minute (as I'm typing this issue actually), and references pop up.
  * Now, after another minute, the "find references" button has disappeared (I don't think I've touched the UI in the interim).
  * It often takes awhile for the tooltip to show up at all, and then it might be missing the "Find references" button.
2. With LSIF enabled, go [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3cc281d64606d1ec4fa2a5dd8533d07c4ae29d78/-/blob/internal/trace/traceutil.go#L31:21) and click on `opentracing.Tracer`.
  * Sometimes I get a hover, but no jump-to-def or find-references button. How does it serve me a tooltip without a corresponding j2d? And even if it can't j2d (because it's an external def), shouldn't it at least show me find-refs in the same repo.
  * Sometimes a "Go to definition" button pops up, but only briefly, then goes away.
  * Sometimes, the tooltip itself seems to go away, and then I try clicking around on surrounding definitions, and nothing works for a few seconds. It feels like something has been killed and needs to restart before it comes back online.
3. [Tracer.New](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3cc281d64606d1ec4fa2a5dd8533d07c4ae29d78/-/blob/internal/trace/traceutil.go#L35:17) has a whole bunch of references, but not "Find references" button appears.
![image](https://user-images.githubusercontent.com/1646931/77674032-36722480-6f48-11ea-985e-472ba925baf2.png)

Now, I add `"codeIntel.lsif": false,` to my user settings.

1. Go to [traceutil.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3cc281d64606d1ec4fa2a5dd8533d07c4ae29d78/-/blob/internal/trace/traceutil.go#L30:6).
  * No hovers show up initially.
  * Hovers show up after what feels like 30s of waiting. Falling back to language server, presumably? This feels longer than it used to take.
  * Now references show up. References in general take awhile to populate. (20 seconds?)
  * After reload, the tooltips pop up fairly quickly, but show the spinner. This at least tells me something is making progress.
  * Jump to external defs work!
  * Now, after leaving the page alone for awhile, I come back, and "Find references" button no longer shows up...
  * Works on refresh, but you gotta wait for what feels like reinitialization.

I am leaving LSIF disabled for now, because I feel on the whole it is a better experience, even with the warts described above.

Meta question: I encounter these types of issues extremely often now, and it feels like it has gotten worse over the last few months. Are we dogfooding our own product enough here?

**Comment by felixfbecker** [comment]
I looked into this because it is always possible that this is a problem in the webapp code, not necessarily in code intel. Here are my findings:

#### Reproducing 1.:

The references provider fails with this error:
```
Error: {"message":"Response code 422 (Unprocessable Entity)"}
```
(Note how there is JSON inside the message - weird)
Looking at the Network tab, I see the LSIF GraphQL references query failed with that error:
```json
{
  "errors": [
    {
      "message": "{\"message\":\"Response code 422 (Unprocessable Entity)\"}",
      "path": ["repository", "commit", "blob", "lsif", "references"]
    }
  ],
  "data": {
    "repository": { "commit": { "blob": { "lsif": { "references": null } } } }
  }
}
```
I suspect this is some error from an internal LSIF service, that was JSON-stringified into the error message for some reason.

The same error happens with Number 2.

#### Reproducing with `codeIntel: false`:

The Go langserver receives the hover and definition requests, but takes a very loooooong time to respond. I can't dig into why unfortunately, it seems that the WebSocket responses from the Go language server don't include any OpenTracing spans (although maybe those could be found in the Jaeger UI).

While the message hasn't gotten a response yet, we don't show a loader. I don't know why, I'd assume this is a webapp bug we need to look into. We should show a loader in the hover after a very short time.

I also don't know why the find-references button sometimes doesn't show, I was able to reproduce that too. This is likely a web issue too.

------------------------

Now since this is also a meta-issue and not just about specific bugs, I am thinking how can we detect this better? Even though we have Sentry running in prod and it caught the error in (1), I can't find this issue in Sentry. Maybe we don't have Sentry configured on dotcom? This may help us to catch issues like this, if we monitor Sentry more closely.

The other issues of course did not result in an error. More testing maybe?

**Comment by efritz** [comment]
The find refs should be fixed with https://github.com/sourcegraph/sourcegraph/pull/9347. This doesn't fix anything about the langserver performance (we've explicitly de-priorized langservers before I even started working here).

The other issues seem like web/UX issues. I'd be happy to contribute effort or weigh-in on these, but I don't feel like the codeintel team has enough bandwidth to own fixes in this area.

**Comment by efritz** [comment]
Merged #9347. This particular issue was only introduced in https://github.com/sourcegraph/sourcegraph/commit/d675a6acb4db5428c3b7742192a72b70f17ac814, which was after the 3.14 branch cut. Should be fixed on DotCom shortly.

As for language server performance, it's _always_ been very slow. Perhaps you've just become accustomed with the past few months of having LSIF data available on sg/sg that it seems slower than it had in the past? We haven't touched the language server implementations in any meaningful way since I've started here.

The remaining issues seem like poor latency (which we're addressing up and down our stack as part of our "make LSFI work for OSS" work), and unexpected hover tooltip behaviors. The later seems like a web issue, but I'd be very interested in sitting in on these UX talks and throw some effort at it where I'm able to.

cc @lguychard feel free to delegate some of this work to us if it falls closer to our end of the stack.

**Comment by nicksnyder** [comment]
@efritz When your fix is deployed, can you confirm that (1) and (2) are fixed?

Given limited resources, I think we should consider prioritizing better UX for (3), but working to actually diagnose and fix the performance of language servers themselves is out of scope and not a priority.

Since @sourcegraph/web owns (3) I have assigned @lguychard to triage.

**Comment by lguychard** [comment]
> While the message hasn't gotten a response yet, we don't show a loader. I don't know why, I'd assume this is a webapp bug we need to look into. We should show a loader in the hover after a very short time.

I figured out what is very likely the root cause of this: https://github.com/sourcegraph/sourcegraph/issues/9349

**Comment by lguychard** [comment]
> I also don't know why the find-references button sometimes doesn't show, I was able to reproduce that too. This is likely a web issue too.

I'd like us to understand & fix this in 3.15.

**Comment by imtommyroberts** [comment]
I left some thoughts on this in #8830 (which was a response to customer feedback). 

@lguychard if there is scope for UX improvements to be included, on my end I can definitely get that done for 3.15. Maybe we should have a call and sync on this before next week?

My feeling is that minimal/no design artifacts would really be necessary, it's just a case of confirming that the user is informed of loading/errors in an appropriate manner.

**Comment by felixfbecker** [comment]
https://github.com/sourcegraph/sourcegraph/issues/9350

**Comment by efritz** [comment]
@imtommyroberts @lguychard I'd be interested in sitting in on such a chat if possible.

**Comment by efritz** [comment]
I've confirmed DotCom now shows references for the first `Tracer` symbol linked in the issue description.

**Comment by lguychard** [comment]
@felixfbecker reassigned to you since you're taking on #9349 and #9350

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
@beyang with #9347, #9349, and #9350 fixed, could you revalidate whether this is still a problem? I want to be 100% sure we fixed your bad experience (i.e. _all_ the bugs that caused it, not just _some_ that were contributing to it) 🙂

**Comment by beyang** [comment]
Just ran through all these flows again and verifying that they went well. Thanks for fixing! I've re-enabled LSIF in my user settings on sourcegraph.com :)
