### ISSUE TITLE
Loader is never shown if hover provider is called before providers are registered

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#9349]
The hover tooltip has been designed to show a loader if no provider has emitted after 1200ms. However we have noticed some cases where this didn't work, for instance https://github.com/sourcegraph/sourcegraph/issues/9346#issuecomment-604581293:

> While the message hasn't gotten a response yet, we don't show a loader. I don't know why, I'd assume this is a webapp bug we need to look into. We should show a loader in the hover after a very short time.

I managed to reproduce this locally. This will always happen when hovering over the token before extensions have activated:
- Since no providers are registered, [`getLocationsFromProviders()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fc7f5de30b49820c698573a1919a1a804f1b16b1/-/blob/shared/src/api/client/services/location.ts#L127-151) will emit an empty array
- As a result, [`getDefinitionUrl()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fc7f5de30b49820c698573a1919a1a804f1b16b1/-/blob/shared/src/hover/actions.ts#L186-188) will emit `null`
-  As a result, [`definitionUrlOrError` will emit before `LOADER_DELAY` has lapsed](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fc7f5de30b49820c698573a1919a1a804f1b16b1/-/blob/shared/src/hover/actions.ts#L112-116), causing the loader to never show

**Comment by felixfbecker** [comment]
@lguychard I _think_ it is a bit different. There are different loaders that can show, in the hover tooltip, and inside the go to definition button. The code you linked is responsible for the latter. But what we would like to see is the loader for the hover. Whether the hover loader is shown is determined inside `HoverOverlay`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fc7f5de/-/blob/shared/src/hover/HoverOverlay.tsx#L183-186 .
The `LOADING` value is used when the `getHover` callback has not emitted after the delay. _But_ we have the same problem here, when providers are not registered yet, `getHover()` will immediately emit `null`. While if providers are registered fast enough though, it will wait to emit until the provider emitted.

**Comment by felixfbecker** [comment]
So basically the problem is that we have a single flat Observable with no way to know when after a value loading of fresh values has begun again. This is actually a problem that @efritz faced too with reference providers iirc (showing values, but also continuing to show a loader).

A simple solution to this might look something like 
```ts
interface Emission<T> {
  isLoading: boolean
  results: T
}
```
For hovers, definition, references, etc.

**Comment by felixfbecker** [comment]
(The curious might wonder why it wasn't written like that in the first place. The reason is that the original code was written when there was no streaming, and no concept of multiple providers. Just a single codeintel HTTP request/response API.  Meaning there is only "loading", "result"/"no result"/"error", and no state to handle of "no result", then "loading" again. All the other stuff got bolted on top later)

**Comment by lguychard** [comment]
> I think it is a bit different

Yes, you're right (and the code you linked to is indeed the relevant code), but as you mentioned the root cause is the same.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
