### ISSUE TITLE
Improve docs for uploading LSIF data via src-cli

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9362]
Reported by https://app.hubspot.com/contacts/2762526/company/947819054

1. Update docs to indicate the minimum supported version of Git for `src` to determine the repo name from where the command was run (or alternatively, a version that we can guarantee works?). Waiting to hear back on what Git version was in use that caused this to fail.

1. Update docs to specify that the `--repo` flag for LSIF uploads must be in the format `<host>/<org>/<repo>` (or whatever is actually correct) _without the scheme_. 

1. Update docs to clarify that `src` will automatically set the root to whatever directory the dump file is in, rather than PWD, and how to change that. Perhaps also just change this behavior?

**Comment by efritz** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/9365 and in https://github.com/sourcegraph/src-cli/pull/162.

> Perhaps also just change this behavior?

src-cli documented the default to be the root of the repo, when it's actually the dirname of the dump file. This has been updated but behaviors have not been changed. We can have a bigger discussion around this, but I think the current behavior (which is now correctly documented) is the correct (I could be convinced otherwise).

**Comment by efritz** [comment]
Closing as immediate issues are resolved. Let me know if we need to cut a new src-cli version for this (or if it needs to be patched back to the 3.10 releases for older instances).
