### ISSUE TITLE
Removing intermediate caching on frontend for raw endpoint

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9372]
I added some instrumentation to the raw endpoint on Sourcegraph.com to see how it is used. Over the last 3 days effectively only the archive endpoint is used. Additionally only requests for the root path seem to be used.

I then mined some recent logs to see how often the same repository is fetched. It turns out the long tail of repositories are only fetched once, and some repos were fetched upto 4 times.

All this evidence together tells me storing the archive on disk in the frontend is not worth the cost. We can just directly stream the archive from gitserver. This does mean we won't set the `Content-Length` HTTP header.

Considerations:

-   Does removing `Content-Length` cause issues?
-   Is Sourcegraph.com representative of extension use? Do our customers use extensions which much more frequently access things other than the archive?

Pros:

-   Removes the main use of the frontend volume. (need to confirm if its the only user). If we can remove the volume, then it simplifies deployment. (The volume has been a source of issues at multiple customers).
-   Faster responses.

<details>

requests per second over 5min for the last 3 days:

![image](https://user-images.githubusercontent.com/187831/77764819-f1341c80-7045-11ea-9e5f-1efa8f608e2a.png)

Requests are dominated by rootarchive. Here is a graph of non-archive. rate isn't that useful, so it is the number of requests over 5min for the last 3 days. Notice we bursts of upto 100 requests over 5min for files that 404:

![image](https://user-images.githubusercontent.com/187831/77765064-5ee04880-7046-11ea-9ba3-d84c7d85b29c.png)

The below is a histogram. For each repo we observe how many times it was requested. So 126 repos are only requested once, 12 repos are requested 2 times, etc.

    $ kubectl logs -lapp=sourcegraph-frontend -c frontend --tail=5000 > frontend.log
    $ grep 'raw endpoint sending archive' frontend.log | grep -o 'repo=[^ ]*' | sort | uniq -c | awk '{ print $1 }' | sort | uniq -c
     126 1
      13 2
       7 3
       4 4

Here are the promql queries used

```promql
sum by (type) (rate(src_http_raw_endpoint_total[5m]))
sum by (type) (delta(src_http_raw_endpoint_total{type!~".*archive"}[5m]))
```

</details>

**Comment by keegancsmith** [comment]
@sourcegraph/code-intel @sourcegraph/web Are there any concerns with the above proposal. I know extensions are the main use of the raw endpoint. In particular

> Does removing Content-Length cause issues?
> Is Sourcegraph.com representative of extension use? Do our customers use extensions which much more frequently access things other than the archive?

**Comment by efritz** [comment]
The code intel extensions currently use only the GraphQL API.

**Comment by felixfbecker** [comment]
No concerns from my side.

> Does removing Content-Length cause issues?

A real world effect of this would be that the TypeScript LSP code intel cannot show a progress bar while the archive is being fetched (in case that takes a while for monorepos). Looking at sourcegraph.com though, it seems like `Content-Length` is already not sent (probably because of Cloudflare), so this would only affect private instances that still run the TypeScript language server (I don't know if there are any still, maybe https://app.hubspot.com/contacts/2762526/company/464956351). It will still function properly though (no crashes etc). LSIF/basic code intel would not be affected in any way afaik.

Another minor effect would be no progress indicator of the browser when downloading a large file, but that doesn't sound important / like a realistic scenario.

> Is Sourcegraph.com representative of extension use? Do our customers use extensions which much more frequently access things other than the archive?

I can't answer this, but removing `Content-Length` shouldn't really matter for this, no? I would imagine individual files (like from the download button in the webapp) can be fetched the same way file content can be fetched when requested through the GraphQL API for display (`git show`?), but I don't know the implementation.

**Comment by keegancsmith** [comment]
> The code intel extensions currently use only the GraphQL API.

Oh, interesting. So is the main use of this the LSP servers? (cc @felixfbecker). Those are deployed in the same data centre, we could avoid going via the public internet to fetch these archives if that is the case.

I think campaigns are also a heavy user of this endpoint, so makes sense to improve it in the short-term at least.

**Comment by felixfbecker** [comment]
> Oh, interesting. So is the main use of this the LSP servers? 

Yep, that's what the raw API was originally built for, and with the prospect of also powering file downloads (which we now have thanks to you) and in the future displaying images in markdown files.

> Those are deployed in the same data centre, we could avoid going via the public internet to fetch these archives if that is the case.

Yeah, we can I think. We wanted to _allow_ (maybe even recommend?) language servers to be deployed in isolation, which is also why they use access tokens to communicate with Sourcegraph instead of internal endpoints. That's also a security consideration, because a language server may be publicly exposed and even potentially do arbitrary code execution and should not have access to more data than the access token it was passed allows. Essentially it's not a "trusted" service. But if we can uphold that constraint, it doesn't have to go through the public internet.

**Comment by keegancsmith** [comment]
I think with the work the LSIF team is doing our use of LSP will decrease dramatically. Then our main use of this endpoint will be campaigns, and in that case it mostly will go via the external endpoint. So I don't think it is worth looking into how to go via internal endpoints yet. Hopefully the PR I just shipped will improve the situation a bunch. Will follow-up in this issue and #progress on Thursday with some graphs.

**Comment by keegancsmith** [comment]
Performance is much more stable. Here is the p95 over 1 hour. The other percentiles look similar.

![image](https://user-images.githubusercontent.com/187831/78352744-2b06a500-75a9-11ea-89d5-3fd075f5201e.png)

I only started measuring disk space usage after deploying the fix, so it is hard to comment on how much the situation has improved. But here is the graph of % free on frontend for the last 2 days. Given how often we ran into this issue this is much better. But there are other uses of `vfsutil` we still need to tackle to make frontend use no local disk. (Note the y-axis is starting at 70% free)

![image](https://user-images.githubusercontent.com/187831/78352958-93558680-75a9-11ea-8c22-56d301fb212e.png)
