### ISSUE TITLE
Structural search result count reports number of line matches rather than pattern matches

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#9426]
[This structural search](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/elastic/++%22try+%7B:%5B_%5D%7D+catch+%28:%5Be%5D%29+%7B+%7D+finally+%7B:%5B_%5D%7D%22+lang:java&patternType=structural) displays that 21 results were found, but the number of code reviews displayed is significantly less than that.

<img width="583" alt="Screen Shot 2020-04-01 at 2 02 32 PM" src="https://user-images.githubusercontent.com/133014/78098102-755d1a00-7421-11ea-9f18-12b05fb56335.png">

**Comment by rvantonder** [comment]
Result count refers to line counts, not blocks. Unfortunately this is an artifact of the historic decision to use line-based matches as the basic primitive/type for content matches in Sourcegraph instead of ranges. So this is a known issue.

There is a way to override the match count in the GQL resolver, so that the result number you see here is accurate per block. But it's not an easy fix for structural search, because more information needs to be communicated from `searcher` than the RPC currently makes allowances for. Even with this fix, it won't fix a related issue for the number of additional matches sometimes reported on the right hand side of the file content match window, since that derives I think entirely from the line matches types. A wholistic fix will likely be expensive.

We should absolutely do it, but it is not a fainthearted thing to undo the line match decision, so I haven't committed to it yet, and probably won't in the next couple of iterations. A quick fix for the result count summary, perhaps!

**Comment by ryan-blunden** [comment]
> A quick fix for the result count summary, perhaps!

For sure, I was thinking the same thing.

@christinaforney @rvantonder @imtommyroberts, What do you think about either:

- a) Changing  the message from "__x results__" to "__x results (line matches)__".
- b) Adding an ⓘ icon with the hover text __Results are the number of line matches, not files in which a match was found__.

**Comment by christinaforney** [comment]
Short term: I suggest changing the text to "x matched lines" 

Med/long term: Can we simply add the number of matched files and show both stats? I'm not sure if adding this information would be easier than changing it, but I think both pieces of information are interesting.
e.g. "4 files with 21 matched lines in 28 seconds"

**Comment by rvantonder** [comment]
> Short term: I suggest changing the text to "x matched lines"

This is more of a web change, and applies only to content, I think. It'd also have to adjust appropriately for file/repo/commit matches.

For 
> e.g. "4 files with 21 matched lines in 28 seconds"

it's also probably a webapp thing that can be gleaned from results that the backend returns.

**Comment by rvantonder** [comment]
@ryan-blunden I really really dislike this bug so I addressed it in the PR #9541. There's a screenie there showing there's still the limitation of `Show more` on the right, but I can probably get that fixed too soon. Overall this is probably easier than adding *line matches* because we'd need to case out on the kind of search being down.

**Comment by rvantonder** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/9564 to follow up on the remaining work here.
