### ISSUE TITLE
Browser extension not working on OSS repository

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9556]
The author of this PR reached out to me to ask if I could review this change to one of our open-source repositories: https://github.com/sourcegraph/checkup/pull/109/files. In doing the PR, I found that code intelligence from Sourcegraph doesn't work. Here's the output from the browser console:

![image](https://user-images.githubusercontent.com/1646931/78379576-6c865880-7587-11ea-8d74-f3878b0a5c26.png)

**Comment by lguychard** [comment]
These errors are surfaced from the go language server https://sourcegraph.com/github.com/sourcegraph/go-langserver@46b1224662e1c621287c2039a8db7cd67a1d83c5/-/blob/langserver/ast.go#L40:75

The positions in hover requests are correct. Using basic code intel, code intelligence works:

![image](https://user-images.githubusercontent.com/1741180/78383215-51900480-75d8-11ea-9471-068ed0d51447.png)

cc @sourcegraph/code-intel to triage

**Comment by efritz** [comment]
@keegancsmith any possibility your recent changes caused this behavior?

**Comment by keegancsmith** [comment]
Very possibly related. We can try roll-back to the older version `index.docker.io/sourcegraph/lang-go:insiders@sha256:fdc94b291825648a436c656846cf274f5ce1e52c561ce6de8a11a95984c4d74a` to confirm.

**Comment by efritz** [comment]
Also, did the raw API change in a meaningful way? I've seen some discussion about it but haven't followed closely.

**Comment by efritz** [comment]
Updated lang-go with hash `fdc94b291825648a436c656846cf274f5ce1e52c561ce6de8a11a95984c4d74a` but it seemed to display the same behavior.

**Comment by efritz** [comment]
Behavior:

- can replicate on right-hand side of diff view
- cannot replicate on left-hand side of diff view
- cannot replicate on non-PRs

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/issues/9372 is the only work related to the raw API I am aware of.

**Comment by felixfbecker** [comment]
I've seen these errors before, but I can't find any old issues

**Comment by felixfbecker** [comment]
I've only ever seen these in Go though, never TS, which would make me think the raw API can't be at fault since it powers both

**Comment by creachadair** [comment]
After more digging, what we see is that fetches for the new files on the RHS of the diff are returning empty content.

**Comment by efritz** [comment]
** Breaking news **

This only affects PRs with zero-length files on the new rev (in commits were files are added).

Errors are populated from [this line](https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/langserver/build_context.go#L99). Related, it looks like [this line](https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/langserver/util/context.go#L22) returns zero-length content readers.

We suspect that we're getting particular errors (`expected 'package' but found EOF`) on such PRs due to a scanner error that occurs because the set of dependencies in the cached zip archive has zero-length go files.

**Comment by efritz** [comment]
I am seeing the same bad behavior locally if I revert the langserver to sourcegraph/go-langserver@9ad62c7ec68e377b41a8b8dd846e573b76634172 and the frontend to sourcegraph/sourcegraph@55f9f21d28ca0362dd20bf6798ede024e80cfba3.

@beyang have you seen this behavior in the past or is this brand new? I've been trying to triage this for over five hours and the two leads I had aren't being fruitful (it's no change to the lang-server, and it's not related to @keegancsmith's recent change to the raw API).

**Comment by efritz** [comment]
> I've seen these errors before, but I can't find any old issues

> I've only ever seen these in Go though, never TS, which would make me think the raw API can't be at fault since it powers both

@felix Could you provide any more context here? I'm currently at a dead end with this.

**Comment by felixfbecker** [comment]
Unfortunately not. I only remember seeing them before, and only with Go. So likely not new, and not raw API. Maybe it's some go langserver specific caching. But I've never worked on the Go langserver, sorry :/

**Comment by keegancsmith** [comment]
The weird part is if you visit the RHS repo, these errors don't happen and code-intel works. Both viewing the added file and hovering over the existing file (which triggers the error) don't give any issues.

This makes me believe it is something different between how the extension inits/communicates with the langserver on a PR vs a repo code view. An important thing to note is the PR is from a forked repo. My educated guess is it would have something to do with that.

**Comment by efritz** [comment]
The code intel team has no immediate plans to continue triaging this issue. We have de-prioritized work on language servers _in general_, and we have also de-prioritized work specifically on go-langserver where this bug seems to lie. As this behavior also appears on older versions of go-langserver and the frontend, this does not seem like new behavior.

I've filed https://github.com/sourcegraph/go-langserver/issues/383 to track this issue in the future if there are any new updates.

An immediate solution to your problem, @beyang, is to enable LSIF on the checkup repo.
