### ISSUE TITLE
No basic code intel in fork repo

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#9583]
Repro:

1. Go to https://sourcegraph.com/github.com/DikangGu/rocksdb/-/blob/utilities/cassandra/format.cc#L260:20
1. Hover over things that should have hover (eg `ConvertExpiredColumnsToTombstones`, `RowValue`, etc.)

Expected: see hover with go-to-definition and find-references button

Actual: no hovers, no buttons

Note that the hovers and go-to-definition/find-references **DO** work in the origin (non-fork) repo at https://sourcegraph.com/github.com/facebook/rocksdb@a67fb4c9bddd26854d2b6e848702d4a19e6f3f11/-/blob/utilities/cassandra/format.cc#L264:10&tab=def.

Reported by a user from https://app.hubspot.com/contacts/2762526/company/554275594

**Comment by efritz** [comment]
Search has disabled forked repo results by default. In order to enable these results for search-based code intelligence, change this setting globally or in your user settings: https://github.com/sourcegraph/code-intel-extensions/blob/master/extensions/template/package.json#L53.

Closing this issue as it's currently working as expected. If you'd like to open discussion about this default (change of behavior or documentation), please open another issue or drop in our team's channel to discuss changes.

If you have an issue with the indication of hover tooltips in the absence of any results, please contact the web team (who are currently in discussions related to the UX around this area).

**Comment by sqs** [comment]
Proposed different behavior in https://github.com/sourcegraph/sourcegraph/issues/9634
