### ISSUE TITLE
Minor: Retry lsif index upload when clone is in progress

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#9700]
When uploading lsif indices to a sourcegraph instance via src-cli, the command fails if cloning the repo is still in progress. The user would pretty much always retry the command, so we should just do that for them.

It'd be really simple to add this retry to the src-cli command, but could we alternately have the instance accept the upload instantly but not start processing until the repo is cloned? I assume this would be more work but not sure how much more. @creachadair @efritz

**Comment by efritz** [comment]
I'd lean towards putting the retry in src-cli (which may need a change in the LSIF upload proxy in order to surface the specific error), but I can't think of a _super_ compelling reason why the worker couldn't do the same work. Either way _something_ is going to have to poll the repository status before processing.

At first I was worried doing it in the worker would have too many uploads for invalid repositories/commits, but the clone-in-progress condition at least ensures that the repo is valid (the commit may still not be, and the worker would have to validate this, which is currently doesn't have to).

I'd like @creachadair to weigh in on his thoughts.

**Comment by creachadair** [comment]
I agree it makes sense to retry _somewhere_. My intuition is that the right place is in the bundle manager rather than the client. Doing it in the client is easier to implement, but doesn't solve the UX problem created by the error we have now.

The interesting question is at what point we know that the failure is due to a repo that is cloning. We don't really want to back off and retry for _every_ possible error, e.g., if someone tries to upload data for a repo on a private instance, for a repository that instance is never expected to have, it would be ugly UX to have the client back off and retry for a while before reporting an error. And in that case, the error (still) wouldn't give the user what they really need to know.

I think right now, neither the client nor the bundle manager can distinguish between:

1. A repo we do not have now, but can and will clone ASAP, and
2. A repo we do not have now, and do not have access too.

Both seem to report the same error. The Sourcegraph UI knows, so we must have the information somewhere (probably gitserver?). But there's a kind of timing issue: If I'm doing an upload, and my upload is the reason the repository will be cloned and indexed, the state of the system will not be (1) until _after_ my query fails.

Assuming all of that is vaguely correct, I think we'd want something like this:

1. Client presents upload for repository R to the bundle manager.
2. Bundle manager requests that R be (asynchronously) cloned and indexed if it's not already.  The reply is (inter alia) either "ok, ready", "ok, cloning", or "no, sorry".
3. If the reply is "no, sorry", that error is propagated back to the client and reported to the user immediately (case (2) from above).
4. Otherwise, the bundle manager accepts the upload.
    - If "ok, ready", it does the normal thing we do now.
    - If "ok, cloning", it queues the upload to be processed once the clone is finished.

Step (4) might require some changes to the update logic (depending when the repo status database gets updated). But then, at least, we aren't retrying unless we know it's worthwhile to do so. 

I think it ~never makes sense to make the CLI wait for `lsif upload`, since uploads are already processed asynchronously: Making the client back off and retry just to get something in the queue is the kind of thing that drives calm people into a rage. 🙂

**Comment by gbrik** [comment]
I think they don't report the same error. src-cli will output "repository not found (clone in progress)" for this condition, and the RepoNotFound error in the server source has a CloneInProgress boolean field. Agree with everything else.

Maybe a good time to go over more detailed arch & file structure of the code intel parts of sourcegraph/sourcegraph?

**Comment by creachadair** [comment]
> I think they don't report the same error. src-cli will output "repository not found (clone in progress)" 

I think that's just the string from the gitserver, but that does suggest we might be able to hack it by parsing that string on the bundle manager. 🤦‍♀️

**Comment by efritz** [comment]
The current flow is:

1. Client upload to LSIF upload proxy
2. LSIF upload proxy ensures the repo/commit exists and checks permissions
3. LSIF upload proxy sends upload to precise-code-intel-api-server
4. API server puts a record in the db and sends upload to precise-code-intel-bundle-manager

Right now only the LSIF upload proxy has a repository name, which is converted into an ID and sent to the api server. Once we leave the frontend we have the assumption that the repo and commit exist (or had existed at one point) on gitserver.

We could update the worker to poll the frontend before processing to ensure the revision exists and just put it back on the queue with a timeout period to retry later if the repository is still cloning.

**Comment by creachadair** [comment]
> We could update the worker to poll the frontend before processing to ensure the revision exists and just put it back on the queue with a timeout period to retry later if the repository is still cloning.

Yes—but I think we'd also have to make the proxy not report failure at step (2) if the repo _can_ be cloned but hasn't yet, right?

**Comment by efritz** [comment]
Yes, so if we want to do it in the backend rather than on the client, we'd need to 

(1) change the LSIF proxy to ignore repo-clone-in-progress errors from ensureRevision
(2) add a delay field to the lsif_uploads table
(3) change the work selection in the worker to ignore work in a delay period
(4) add a pre-step in the worker to ensure that the revision exists; if the commit does not exist and repo is cloned, throw away upload; if the repo clone is in progress, put work back with delay

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by gbrik** [comment]
Make sure to also cover #9985

**Comment by efritz** [comment]
How I would propose implementing this feature:

1. Add a method to the [codeintel gitserver client](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/codeintel/gitserver/client.go#L7) that check the status of a repo/commit (should return some flag indicating whether or not it's a temporary/still-cloning error, or if it's something else like repo or commit are unknown).

2. Run `./dev/add_migration.sh` to create a new migration file that adds a `process_delay` column to the `lsif_uploads` table. Feel free to rename this, but should probably be a timestamp value indicating "don't process me until ___".

3. Add a method to the [job handle interface](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/codeintel/db/job_handle.go#L43) that will "put back" the upload with some additional/configurable delay. This will probably also require adding additional methods to DB and to the observability struct in the same package (compile errors will guide you here).

4. Update the [dequeue](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/codeintel/db/uploads.go#L194) method to skip any uploads where the process delay falls within the current time.

5. In the [worker dequeue method](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/precise-code-intel-worker/internal/worker/worker.go#L77), you should ensure that the repo and commit exists. If it doesn't, the it should be put back into the queue with some process delay and the worker should move on to the next item int eh queue.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
