### ISSUE TITLE
observability: improve/restructure admin documentation

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9773]
### Today

In our docs (https://docs.sourcegraph.com/admin/observability) we have:

- Observability
  - Metrics / Metrics and dashboards
    - Guide to metrics
    - Guide to dashboards
  - Tracing
  - Alerting
    - Alerting: custom consumption
  - Logs
  - Health checks
  - Other tools

And the generator for Grafana and Prometheus dashboards is named `observability` at the root of the repository.

### Proposed

I think instead this should instead be:

- Observability
  - Monitoring
    - Dashboards
    - Alerting
    - Health checks
  - Debugging
    - Tracing
    - Logging

With the generator for Grafana dashboards and Prometheus rules being named `monitoring` at the root of the repository.

The most important aspect here is that "Observability" includes two categories:

1. **Monitoring**: How you know when something is wrong (Grafana, alerting, health checks)
2. **Debugging**: How you debug when you know something is wrong

Note: We already have `monitoring` and `debugging` labels on GitHub for filing issues in these categories, which is nice.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Much of the work has been done here (renaming the generator, adding extensive docs to the handbook), but one part still remains: https://docs.sourcegraph.com/admin/observability

Pushing that back to 3.17.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
I did some restructuring in https://github.com/sourcegraph/sourcegraph/pull/16939 . I didn't break it out into `monitoring` and `debugging` subfolders (to avoid breaking links), but we now have:

![image](https://user-images.githubusercontent.com/23356519/103613174-fcb35d00-4f60-11eb-8758-44db31206787.png)

![image](https://user-images.githubusercontent.com/23356519/103613187-04730180-4f61-11eb-8e57-3db27635cc94.png)

I think this is good enough for the time being, we can make further delineations between debugging/monitoring in table of contents etc but I don't think we should change the folder structure since that will break links (especially with things like generated docs, which customer alerts link to). Closing
