### ISSUE TITLE
Alert admins if containers are crashing/restarting

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9793]
when containers restart, alerts should fire. Should work in all deployment environments.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
This should be covered by in all environments except `server` deployments (since https://github.com/sourcegraph/sourcegraph/issues/9791) by the `cadvisor_container_restart_count` metric and the [associated alert](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@583d470abf479098ba8afc394b11b4d90a1431dc/-/blob/monitoring/shared.go#L58), right?

**Comment by slimsag** [comment]
I think the only thing left to do here is confirm this works in k8s and docker-compose deployments. Then, we should promote the alert to a critical one (so admins would be paged) and ensure it won't fire on `sourcegraph/server` deployments.
